### ISSUE TITLE
Cloudwatch ec2_instance_attribute not working with template variable

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#10018]
`ec2_instance_attribute($region, Tags.Name, {"tag:Role":["api"]})` works

`ec2_instance_attribute($region, Tags.Name, {"tag:Role":["$role"]})` doesn't, when $role should be `api`

also tried `ec2_instance_attribute($region, Tags.Name, {"tag:Role":["[[role]]"]})`

**Comment by kaptajnen** [comment]
I am seeing the same issue. I noticed if I refresh the browser window after selecting a new value in the drop down, the instance ids show up.

**Comment by nelg** [comment]
Also have a similar problem.
$servername is a template variable, set from a graphite query for the name of servers

Then, $instanceid is set with a cloudwatch query:
ec2_instance_attribute($region,InstanceId, { "tag:Grafana_Hostname": ["$servername"] }) 

The problem seems to be an ordering / refresh problem.
Error in the logs looks like:`
t=2017-12-12T02:10:23+0000 lvl=eror msg="Request error" logger=context userId=7 orgId=1 uname=gleno error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:491 (0x431e12)\n/usr/local/go/src/runtime/panic.go:63 (0x430d1d)\n/usr/local/go/src/runtime/signal_unix.go:367 (0x44919b)\n/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/metric_find_query.go:490 (0xd27734)\n/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/metric_find_query.go:368 (0xd25a74)\n/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/metric_find_query.go:183 (0xd22017)\n/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/cloudwatch.go:73 (0xd16c4d)\n/go/src/github.com/grafana/grafana/pkg/tsdb/request.go:17 (0xbaf659)\n/go/src/github.com/grafana/grafana/pkg/api/metrics.go:46 (0xde305e)\n/usr/local/go/src/runtime/asm_amd64.s:511 (0x4610d1)\n/usr/local/go/src/reflect/value.go:434 (0x4bf825)\n/usr/local/go/src/reflect/value.go:302 (0x4bee03)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x7d4538)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x7d3e39)\n/go/src/github.com/grafana/grafana/pkg/api/common.go:37 (0xdfeecb)\n/usr/local/go/src/runtime/asm_amd64.s:509 (0x460fba)\n/usr/local/go/src/reflect/value.go:434 (0x4bf825)\n/usr/local/go/src/reflect/value.go:302 (0x4bee03)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x7d4538)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x7d3e39)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x7f154d)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x7f1485)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_tracing.go:25 (0xb97813)\n/usr/local/go/src/runtime/asm_amd64.s:509 (0x460fba)\n/usr/local/go/src/reflect/value.go:434 (0x4bf825)\n/usr/local/go/src/reflect/value.go:302 (0x4bee03)\n/go/src/github.com/grafan`

**Comment by torkelo** [comment]
@mtanda any ideas why template variables isnt working in ec2_instance_attribute queries like

ec2_instance_attribute($region, Tags.Name, {"tag:Role":["$role"]})

**Comment by mtanda** [comment]
@torkelo I can't replicate the issue.
`ec2_instance_attribute($region, Tags.Name, {"tag:Role":["$role"]})` return correct result.

Anyway, all templateSrv replace is done in frontend.
https://github.com/grafana/grafana/blob/v4.6.3/public/app/plugins/datasource/cloudwatch/datasource.js#L249-L255
https://github.com/grafana/grafana/blob/v4.6.3/public/app/plugins/datasource/cloudwatch/datasource.js#L195-L201
Please check the request to backend.

**Comment by bergquist** [comment]
Might be fixed by https://github.com/grafana/grafana/pull/10603
