### ISSUE TITLE
Hide certain parts of the data source settings page

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#10015]
I think the amount of options at the data source setting page is starting to grow too much. I'm not questioning the need for all settings but I'm not sure we need to view all at the same time.

We could introduce more tabs or hide options under an "advanced" options pane that could be expanded.

Some screens shoots from current data source settings. 
![image](https://user-images.githubusercontent.com/618863/33325943-f320856e-d453-11e7-9fa3-3dfe46c3bbf4.png)

**Comment by zoltanbedi** [comment]
@jessover9000, @sarlinska is this something that is interesting for UX team?

**Comment by jessover9000** [comment]
Thanks for pointing this out, yes I think it's not a bad suggestion. I think accordions like we are using in Enterprise Reporting settings could work well. However I feel like this would need a thorough evaluation of all data sources and their types of settings in order to categorize which ones should be directly accessible and which ones can be hidden until the user expands them. We can keep the issue and add it to the UX backlog, but priority-wise it will have to wait.

**Comment by zoltanbedi** [comment]
The datasource config pages got some ux love recently I hope you find it satisfying Carl. 😄
