### ISSUE TITLE
Feature for having multiple templates in the same dashboard

### ISSUE THREAD

**Issue by xo4n** [grafana/grafana#1003]
Would it be easy to have more than one template per dashboard? Like in the image below, the idea behind is to compare the same graph with different combinations of the template variables
![multiple templates per dashboard - grafana](https://cloud.githubusercontent.com/assets/9038651/4862648/7918786e-610e-11e4-956c-ddff205da1a9.png)

**Comment by amoussoubaruch** [comment]
Hello,

Now it is 2017, is this feature already implemented ?
We are implementing dashboards with multiple sections, where we would like to have separate pull-down menus, one per each section.
A section can be a separate tab in a page, or a part of the page (middle, bottm).

Any advice would be appreciated.

Thanks in advance,
Anirvan

**Comment by agrawalreetika** [comment]
@amoussoubaruch Did you get the way to do it? Even I have the same requirement , please do let me know.

**Comment by amoussoubaruch** [comment]
@agrawalreetika it not works. Sorry.

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
