### ISSUE TITLE
Pagerduty is not respecting the auto resolve incidents setting  

### ISSUE THREAD

**Issue by dragonpaw** [grafana/grafana#10222]
- What Grafana version are you using?
4.6.2

- What datasource are you using?
Graphite

- What OS are you running grafana on?
Ubuntu 16.04

- What did you do?
Setup Pagerduty integration with the checkbox for 'Auto resolve incidents' unchecked.
Setup a test alert for `max(something) > 0`.
Set `something` to 1.
Wait.
Set `something` back to 0.

- What was the expected result?
Incident would open, and be left open.

- What happened instead?
Incident was resolved a couple minutes later. Pagerduty log shows "Resolved through the integration API."

**Comment by bergquist** [comment]
Grafana auto resolves pagerduty by design. 

I guess it should be possible to make that configurable.

**Comment by dragonpaw** [comment]
I don't understand your comment @bergquist. There's already a checkbox in the config for Pagerduty's alert system within Grafana that has that checkbox to not auto-resolve. I'm asking for the checkbox to actually work as indicated.

![screen shot 2017-12-21 at 5 25 26 pm](https://user-images.githubusercontent.com/74992/34281526-2b13a87a-e674-11e7-874f-78bac8523f5e.png)

**Comment by bergquist** [comment]
@dragonpaw sorry. I missed the fact that the pagerduty notifier handles this differently compared to Grafanas core.

**Comment by bergquist** [comment]
I found the bug. It's due to bad default values.

When a new pager duty notifier is created. The checkbox is unchecked but the default value for the setting is `true`. I will fix this in master soon.

A workaround for this bug 
1. Check the `Auto resolve incidents` checkbox
2. Save the alert notifier
3. Uncheck the `Auto resolve incidents` checkbox
4. Save the alert notifier

**Comment by bergquist** [comment]
Thank you for reporting this!
