### ISSUE TITLE
Feat request: Nested folder

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#10339]
It would be awesome to have the ability to put folders in folders.

**Comment by daniellee** [comment]
This is possible but decided to keep it simple to start with (in Grafana 5.0). The complicated part is implementing the recursive permissions.

**Comment by davewat** [comment]
Perhaps start incrementally with non-recursive permissions?  In the database, adding a folder value for parent-id (to reference the parent folder's id), and then of course the work needed around the GUI to utilize and display the organization of folders.  Initially, however, just have non-recursive permissions (permissions are just assigned per folder, as they are now).

**Comment by jdfalk** [comment]
Any progress on this?

**Comment by mohanraj1939** [comment]
I'm exited to see this feature in grafana even with non-recursive permissions.

**Comment by josvo** [comment]
Would be great to have this feature!

**Comment by Zauxst** [comment]
My organization would make good use of this feature as well.

**Comment by amjad** [comment]
This would be very useful for us as well. Any progress on this?

**Comment by simplyviks** [comment]
Any progress on this ? this is a much needed enhancement.

**Comment by salmansamie** [comment]
We need this kind of hierarchy. Stuck at one use case to separate PROD, QA and DEV environments. Then by Alerts and Metrics by deployed agents and so on. Nested folder structure is a dire necessity.

**Comment by jkenn24** [comment]
It would be great to have nested folders for my organization. Having different permissions on those interior folders so that sub folders can have different permissions for different groups of users would be a good idea as well. For our use case we have folders containing dashboards about a topic "A" but certain dashboards are more sensitive and should not be view-able by all users. It is difficult because these sensitive dashboards also can't be set to lower permissions than the parent folder which is rather annoying because it forces the creation of multiple folders such as "A sensitive" and "A general" (among other folders of B, C, D, etc). This structure also makes it hard for users with access to both because you never know where to look for what you want.

I would like to see implemented at least one of the following (if not both!):
1) Ability for folders in folders
2) Ability for certain dashboards/ sub-folders to have lesser permissions than the parent (this way all of our dashboards could be in folder "A" but some could be hidden while other are accessible by different user groups)

@daniellee If this is not something being actively worked on or road-mapped can you (or whoever knows the folder/permission system well) offer some insight on how it works or what changes *could* be made to add this functionality? I would be willing to take a stab at it, but I'm still working on my understanding of the source and my typescript so some insight/ tips from the pros would speed things up greatly!

**Comment by lemon1112** [comment]
Any progress on this?

**Comment by torkelo** [comment]
No there is currently no plan for this from the core team.

**Comment by jkenn24** [comment]
Personally, I was able to get this finished and working based on my specifications. It isn't folders inside folders, unfortunately, but in my opinion the ability to have dashboards inside a folder that can have different/ lower access levels than the folder itself was a step in the right direction and was an overall improvement to the issue in my use case at least. I fixed the above bug where dashboards without permission were still being shown so now they won't show up in the list at all unless you have permission.

You can take a look at what I did here: https://github.com/jkenn24/grafana/commits/new-dashboard-permission-system

No promises that it is completely bug-free or helpful to anyone, but it's something. I'm also new to most of this codebase and to web programming so I don't promise that it's well done, but it seems to be functional thus far. 

Best of luck!

**Comment by konradgaluszka** [comment]
@torkelo Are there plans to add just the permissions changes from @jkenn24 that introduce new (RESTRICTED) role and allow to have public and private dashboards in folder? We could ignore nesting for now. 

I've made some improvements to @jkenn24 changes in the fork:
https://github.com/SabreOSS/grafana/commits/v6.1.x-custom, because there were some missing tests and a bug. 
It's not yet based on master, but I can update it.

Thanks

**Comment by michaeldrey** [comment]
Any plan for this to be prioritized? Would love to have this feature. Our use case is that each root folder is an organization and they add their dashboards to that folder. Would be great have subfolders so we can organize dashboards by system.

**Comment by raidsec** [comment]
+1

**Comment by infa-kparida** [comment]
+1

**Comment by corford** [comment]
So how do people namespace dashboard collections in a shared grafana instance? In an ideal world root level would just contain team/squad folders (and maybe a "special" folder) -> next level for each of these folders would then contain dashboards.

Or is it best practice not to share a grafana instance org wide and instead each team/unit/squad has their own?

**Comment by trallnag** [comment]
@corford That's how we currently do it / plan to do it in our DevOps teams. We don't really have the need for a global Grafana since most of the dashboards are only really interesting to people close to the visualized data.

If the need arises for a more high level set of dashboards I'd just go for a Grafana instance just for that maybe coupled with its own federated Prometheus that gets it that from other Prometheus servers down the line.

**Comment by HabibMAALEM** [comment]
It's an important feature for our organisation, and it will be great if you plan it

**Comment by jasper-zhang** [comment]
+1

**Comment by liuyk0109** [comment]
+1

**Comment by matgn** [comment]
+1

**Comment by paul-ovchinnikov** [comment]
+1

**Comment by matgn** [comment]
+1

**Comment by lunchev** [comment]
+1

**Comment by pbellof** [comment]
+1

**Comment by konstantin-921** [comment]
+1

**Comment by wavedocs** [comment]
+1

**Comment by ihippik** [comment]
+1

**Comment by lzpsqzr** [comment]
+1

**Comment by lzpsqzr** [comment]
+1  it will be great if you plan it

**Comment by AndeyS** [comment]
The ability to create a folder within a folder came in handy. For example, at least so
Project 1
     | --Direction 1
     |     | --- Production
     |     |         | ---- Dashboard 1
     |     |         | ---- Dashboard 2
     |     | --- Development
     |               | --- Dashboard 1
     |               | --- Dashboard 2
     | --Direction 2
        | --- Production
        |         | ---- Dashboard 1
        |         | ---- Dashboard 2
        | --- Development
                 | --- Dashboard 1
                 | --- Dashboard 2
We have a lot of additional dependencies for which the ability to create such a menu made navigation very easy. 
Best regards.

**Comment by howard-feng** [comment]
Any progress on this? It will be very great if you plan it.

**Comment by matgn** [comment]
A tree structure would be awesome. Meanwhile, we are grouping our Dashboards directories thanks to naming rules... So painful and regressive....

**Comment by spaiz** [comment]
Must have feature. We use grafana to monitor and visualize our infra and business metrics. With multiple teams, many domains and microservices it's very hard to work with grafana without ability to create sub folders to keep grafana's UI clean. We try to use some name conventions, but it's not enough.

**Comment by rjulius23** [comment]
Any update on this feature ?

**Comment by sandeepkumaruppala** [comment]
It would be great if we can see this feature live.

**Comment by aktentasche** [comment]
bump

**Comment by rijeshharidas** [comment]
Bump

**Comment by zibinli** [comment]
bump

**Comment by lrolsen** [comment]
bump

**Comment by Occul77rick5** [comment]
I agree, it would be nice to see this happen. Our org is looking at this as a solution and this is one of the limiting factors of going fully with Grafana/Prometheus stack

**Comment by 22itay** [comment]
bump 👍🏻

**Comment by WeiTangLau** [comment]
Nested Folders make so much sense!
Please implement this!

**Comment by DanishIsrar** [comment]
Looking forward to see this feature live. Would be very helpful for managing our monitoring dashboards.

**Comment by newtondev** [comment]
This is actually turning into a showstopper for us for using Grafana, can someone please look at this, or at least point us in the right direction on how we can create our own plugins for doing this.

**Comment by partyzan543** [comment]
Must have feature!

**Comment by DonjPhanvi** [comment]
In this day and age, this feature should be implemented a long time ago.

**Comment by sebboness** [comment]
Please implement this feature as this is quite important for our org and data organization!

**Comment by mozhi-bateman** [comment]
Bump

**Comment by Bharat-B** [comment]
bump

**Comment by astafan8** [comment]
bump :)

**Comment by pedro948** [comment]
bump

**Comment by Mahdigolbaz** [comment]
bump

**Comment by xuebkgithub** [comment]
bump

**Comment by danielelopez1** [comment]
yes it will be really nice to have this feature implemented.

**Comment by aktentasche** [comment]
I mean, this will not happen unless a commercial entity requests it.

**Comment by ZoharZrihen** [comment]
Will be awesome to have this feature.

**Comment by tanandy** [comment]
We are also interested by this feature as everyone. Thank you

**Comment by Ekkertan** [comment]
bump

**Comment by Illia-M** [comment]
bump

**Comment by leovct** [comment]
bump

**Comment by marefr** [comment]
90% of the replies doesn't help and notifies a lot of people. I've locked the conversation. Please use the +1 reaction to upvote instead.

**Comment by joshhunt** [comment]
*Finally*, nested folders will be enabled by default in the next Grafana release, probably Grafana 11 🥳 

Fixed by https://github.com/grafana/grafana/pull/8463
