### ISSUE TITLE
One bug with “plugin Table”: drag table to change the width, and the table value changed

### ISSUE THREAD

**Issue by dragonhzl** [grafana/grafana#10356]
Steps to reproduce the bug:
1. Go to: http://play.grafana.org/dashboard/db/table-panel-showcase

2. Set Time Range to **“This week so far”**.

3. Enter to edit Table **“Row color mode”**, and change options to:
    Table Transform : **Time series aggregations**.
    Columns: **Total**.

4.  Return to Dashboard page, and click refresh button In the upper right corner to refresh Table “Row color mode”. Now, the Total value shows **“702.14K”**.

5.  Drag Table “Row color mode” to fit to the full width, and click refresh button In the upper right corner to refresh Table “Row color mode”. Now, the Total value shows **“1.29Mil”**.  Total value changed.

**Comment by torkelo** [comment]
1) This is due to Graphite and max data points parameter, this parameter is automatically set to panel width 
2) If you want accurate totals you can set max data points parameter to 1 (in ds options row in the top right of metrics tab)
3) Also to get the correct total for Graphite queries you need to set consolidation function to `sum` using the consolidateBy function.  

![image](https://user-images.githubusercontent.com/10999/34376590-c3b47196-eaec-11e7-8e22-0b32cca9d93d.png)
