### ISSUE TITLE
[Feature Request] Custom UI themes

### ISSUE THREAD

**Issue by rlipscombe** [grafana/grafana#10495]
I found #4909, which was closed with the following:

> You can create your own theme by forking Grafana and changing the sass variable files :)

That's fair. My request has smaller scope:

Could we have the ability to *add* SASS variable files to grafana? I'm not talking about a full-blown theme designer, and I'd like to avoid forking the source code. I'd just like a way to copy an existing SASS file, edit it, and drop it in a directory on the server, and then be able to choose that.

Why? Because I've got multiple environments (hence multiple instances of grafana), and it'd be useful to quickly see which one I'm looking at (e.g. by having a different theme for each one).

**Comment by rlipscombe** [comment]
One of my team pointed me to this: http://www.neteye-blog.com/2017/12/how-to-customize-your-grafana-theme/

...which gets most of the way there, I guess.

**Comment by rlipscombe** [comment]
What about building the SASS file offline and copying the results to a directory on the server?
Essentially I'm looking for a way to manage a set of themes, without needing to maintain a separate fork of grafana for each one.

**Comment by thinrope** [comment]
Disclaimer: I am just starting to use Grafana, not sure about the whole picture yet.

I guess using the [pointed article](http://www.neteye-blog.com/2017/12/how-to-customize-your-grafana-theme/) is one (cumbersome, yet powerful) way.

What about adding 2 additional themes, call it custom-{dark,light} or local-{dark,light}, that are exactly as the upstream dark/light themes, but add a custom patch that is simple CSS. Initially those files we'll be empty (or with comment like "put your CSS here") and I guess they should be imported from [grafana.light.scss](https://github.com/grafana/grafana/blob/master/public/sass/grafana.light.scss) and [grafana.dark.scss](https://github.com/grafana/grafana/blob/master/public/sass/grafana.dark.scss) at then deployed. Ideally they should be in some `local` folder, so that redeployment doesn't overwrite them (not sure how people do it). Alternative is to add some checkbox `Apply local theme customizations` near the theme selection dialog. Not sure which is easier or better, but both will work.

**Comment by uh10** [comment]
I tried build from this site: http://docs.grafana.org/project/building_from_source/  , but it stop's with 
"package context: unrecognized import path "context" (import path does not begin with hostname)"
on Ubuntu.
Ok, now i can search, find something, and come deeper and deeper in a other "path" (in this case the "go"-Installation), this cost much time. :-(

The dark-Theme ist nice for my, only the Background of the graphs should be not: $dark-1: #141414;
Why is it not $black: #000;? Why this reducing of the contrast?

**Comment by manilabay** [comment]
hello folks, please could you say me where is the package.json for the dark theme?
I followed
 http://www.neteye-blog.com/2017/12/how-to-customize-your-grafana-theme/

and Im lost when I ran:
npm run build 

Due the package.json is missed in the SASS files directory

tia.

**Comment by anjum121** [comment]
I was trying out Grafana theme followed/checked this site http://www.neteye-blog.com/2017/12/how-to-customize-your-grafana-theme/. it's not aligned with the current version of Grafana.

Steps to follow 

- get Grafana following this link https://grafana.com/docs/project/building_from_source/
- On my mac I had to update my go version to latest otherwise I was getting some error
- Once everything is up & correct. I did `go run build.go setup` and `go run build.go build`
- To run backend i use this command `./bin/darwin-amd64/grafana-server`.
- In a new terminal, I run this command for frontend `yarn start:hot` build.
- Then open `packages/grafana-ui/src/themes/dark.ts` and modify the theme variables.
- Unfortunately, you need to keep re-start backend server to reflect those changes. 

anyone have a better idea, please suggest

**Comment by yesoreyeram** [comment]
I have a workaround for this issue. Refer [Boom Theme plugin](https://github.com/yesoreyeram/yesoreyeram-boomtheme-panel). 

![image](https://user-images.githubusercontent.com/153843/56890715-24ef7680-6a72-11e9-9978-64bb1b931335.png)
![image](https://user-images.githubusercontent.com/153843/56890722-2d47b180-6a72-11e9-8de0-078035674c31.png)

**Comment by mario56** [comment]
Boom Theme plugin. must add panel to my dashboard which i not want.
and I want to save theme which I custom defined. when I refresh bowser, dashboard come to default

**Comment by yesoreyeram** [comment]
@mario56 - If you use boom theme plugin in your dashboard, the panel should be in your viewport. ( top of the dashboard ). Other wise, it will be pushed for lazy rendering by grafana. So if you have the panel at the bottom /  not visibile, then the panel will be applied only when scrolled.

**Comment by mario56** [comment]
> @mario56 - If you use boom theme plugin in your dashboard, the panel should be in your viewport. ( top of the dashboard ). Other wise, it will be pushed for lazy rendering by grafana. So if you have the panel at the bottom / not visibile, then the panel will be applied only when scrolled.

Right. My new solution is to write an app plugin which only load custom css to overwrite base css

**Comment by StaelensJarne** [comment]
I also want this feature!

But there is a temporarily workaround:  (This is maybe a little insecure, but still the most efficient way)
1) Set the setting `disable_sanitize_html = true` in your `grafana.ini` file.
2) Restart your Grafana server.
3) On the dashboard that you want to change css, add a text panel.
Set the Mode to html.
Add css content as a script tag:
```
<style type="text/css">
#panel-2 {
  background-color: red;
}
</style>
```

**Comment by leshy** [comment]
another workaround that I've been happy with, if you have a nginx reverse proxy in front of grafana is to use nginx sub_filter feature,

here I target html head and grafana.light css link separately from grafana.dark in case you'd like to do different light/dark overrides
```
location /grafana {
    proxy_pass http://grafana;
    sub_filter '<link rel="stylesheet" href="public/build/grafana.light.' '<link rel="stylesheet" href="https://example.com/grafana.override.light.css" /> <link rel="stylesheet" href="public/build/grafana.light.';
    sub_filter_once on;
}
```

**Comment by ajakov** [comment]
@leshy your comment is pure gold, thank you so much!

**Comment by thinrope** [comment]
So, as stated by the devs in https://github.com/grafana/grafana/issues/71662#issuecomment-1819121932 essentially custom themes will be even less "supported" :-/

It looks like the new theming support (move from SASS to emotion) in https://github.com/grafana/grafana/issues/32784, most CSS ids are pseudo-random, so hacking on top of the default is not practical (assuming ids change upon recompile)...

On a second read of [Emotion Theming](https://emotion.sh/docs/theming) and that "provides powerful and predictable style composition", it looks like instead of writing CSS that uses selectors directly, we might need to add a JS layer on top.

**Comment by joshhunt** [comment]
We've been going through and cleaning up older issues, and we've decided to close this one because we don't believe we'll add it to the product in the medium to long term. I understand this has been open for a while, and there's a lot of enthusiasm behind it, but we discussed this as a team and we believe there's a number of technical, UX, and brand/commercial problems with adding this to Grafana.

For example, for a while we've been focused on increasing the reliability of Grafana, especially between upgrades, by limiting the number breaking changes we introduce. We want to be able to move quickly on adding improvements to Grafana, and exposing an API for custom themes would often force us to choose between being able to move quickly and breaking users who used this feature. Also, Grafana OSS is sometimes distributed as a part of other software projects to their users for monitoring, and custom themes could put us in a position where users get confused by custom branding about whether or not it's Grafana.

I hope that closing the issue gives people clarity on where we stand, rather than leaving people hanging hoping one day we'll get to it.

If people have specific problems that they believe custom themes could solve, please reply here or file a new issue so we can assess and figure out if there's another way we can solve it.

**Comment by paolomia** [comment]
Hi, I am interested in the topic, not for theme branding, but just to use a monospace font in plots like status history and tables.
The issue is that with the current font the text is never aligned in the tables and neither in y axis. A monospace font would improve readibility
