### ISSUE TITLE
[Feature Request] Different intervals for every dashboard in playlist

### ISSUE THREAD

**Issue by jsedy7** [grafana/grafana#10741]
Grafana: 4.6.3 and 5.0.0-11571pre1
Datasources: Prometheus/InfluxDB
OS: Debian

Hello, I would like to have a function to change interval for every dashboard in playlist. I think interval in Edit Playlist page. Currently we can set one interval for all dashboards in a playlist. I would like to have multiple intervals, because dashboards may have a different importance. It could be fine function. 

What do you think? 
Thank you for you time! 🙂

**Comment by bergquist** [comment]
Thank you for taking the time to provide feedback to us. 

Right now we don't think this idea aligns with the current scope/goal of the Project. I'm closing this issue since we want open issues to reflect the current state of the project. It doesn't mean we never considered it. A closed issue can still get attention from other users and be reopened.

**Comment by opensourcefan** [comment]
In all my years of using Grafana I continue to circle back to this limitation. Out of a handful of panels for example, a couple will ultimately be more critical than the others. I find myself having to tailor those panels so I can register the information in the limited time frame that I have set as a compromise for the whole playlist.

I don't know why this isn't a feature and honestly I don't know why there aren't more requests. Am I doing something wrong?
