### ISSUE TITLE
[Feature Request] Serverless Support

### ISSUE THREAD

**Issue by dowlingw** [grafana/grafana#10789]
**Description**
Add support for running "Serverless" on public (or private) cloud.

This can be achieved by adding support for NoSQL backends for both the Database and Session layers. Particularly of interest are AWS DynamoDB and Google Cloud Datastore.

**Commentary**
Not sure if this is an interesting goal for core project, so lodging as a single request (not one for each piece of work required).

This would introduce some complexity to `sqlstore` and SQL migrations.

There is currently no support for nosql backends in `github.com/astaxie/beego/session` - this would need to be implemented as a custom provider and ideally contributed upstream.

**Comment by bergquist** [comment]
You can run Grafana 5 (in beta) stateless if you provisioin data source and dashboard from configuration. Just start a container with config files and use local database. 

I think that's as serverless as Grafana will be. Removing the dependency on a SQL server would be massive work since we rely on DB transactions. The only way I see this happening is if the datastore provides a postgre/mysql interface that Grafana can use.

**Comment by AnthonyWC** [comment]
I don't think running on public cloud should necessarily imply a NoSQL backend; for example there is AWS RDS which support MySQL/MariaDB.  

And I don't think a serverless version of grafana would make much sense since lambdas are meant to be short lived; running grafana as long running containers seems to make more sense.
