### ISSUE TITLE
Bug (v5-beta1): Batch move from General to folder

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#10818]
Unable to move more than a few dashboards from General into a folder. After those where moved I seem to not be able to move anymore. No errors the move modal stays open.

**Comment by daniellee** [comment]
Just moved 11 dashboards from General to a folder. What error did you get?

**Comment by torkelo** [comment]
no error just nothing happens when I click Move button beside a bunch of requests that seem to reload the background result list view (no move requests)

**Comment by torkelo** [comment]
I am running under subpath (nginx reverse proxy), not sure if that could be a factor.

**Comment by marefr** [comment]
I've tried this now using nginx proxy. First I had some problems because I had some dashboards missing uid that I tried to move. Got error in requests and the modal didn't close.

However, after fixing above errors I moved 24 dashboards back and forth between General folder and another folder. It may look like the modal has frozen since the request are executed in order and not in parallel, but should disappear as soon as all dashboards have been moved. Also if there are plugin dashboards, there will be 2 request for each move instead of 1.

@torkelo can you show me later on your problem?

In the future I think that having a separate endpoint in the API for batch moving a lot of dashboards would be very helpful for both Grafana frontend and anyone using the API directly.

**Comment by marefr** [comment]
@torkelo could you please include chrome network requests screenshots when this happens for you?

**Comment by torkelo** [comment]
now I actually got an error:

![image](https://user-images.githubusercontent.com/10999/36026393-1b49374e-0d97-11e8-9979-8370441c5546.png)

**Comment by torkelo** [comment]
I have a dashboard that is failing in the schema upgrade :)  (the old dashboard imported from Grafana v1).

Not sure why the the schema upgrade thing is running when you move but think we can close this. maybe add some error handling

**Comment by marefr** [comment]
Closing this for now
