### ISSUE TITLE
Feat Request: Allow template variable wise row expansion.

### ISSUE THREAD

**Issue by shivam-bidgely** [grafana/grafana#10969]
- What Grafana version are you using?
Grafana 4.6.3
- What datasource are you using?
Influxdb
- What OS are you running grafana on?
Ubuntu
- What was the expected result?
Have the ability to control which rows will expand and show when a particular template variable is selected.

**Comment by torkelo** [comment]
not sure we need this, if you only want to view data for the selected variable then it's better to not have any rows at all and let all graphs change. 

for example:
http://play.grafana.org/d/000000056/graphite-templated-nested?orgId=1

Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
