### ISSUE TITLE
Viewing snapshot without login shows unauthorized from annotations api

### ISSUE THREAD

**Issue by matti** [grafana/grafana#11006]
Two grafana instances A and B - A is configured to save snapshot to B. When the snapshot link is visited the snapshot works, but shows unauthorized from /api/annotations (that will always return `[]`)

Setting `GF_AUTH_ANONYMOUS_ENABLED=true` fixes this, but I'd want my snapshot server to be non-anonymous.

**Comment by SamuelToh** [comment]
+1 for this.

**Comment by torkelo** [comment]
This is probably because the annotations query did not complete in time for the snapshot to complete

**Comment by kjetilmjos** [comment]
Tried setting the timeout to 600s. Still no difference. The dashboard loads fast when accessing it normally

**Comment by blessyezi** [comment]
how do this with /api/snapshots?

**Comment by sormbrek** [comment]
+1 for this.  

It doesn't look good when our users see "Unauthorized" while viewing the populated dashboard at the same time, and have asked our team why they are still getting the errors.  Is there any plan on fixing this?

**Comment by ryantxu** [comment]
annotations are not stored in the snapshot -- a new query is executed when the dashboard (with snapshot) is loaded.

I'm not sure what the right behavior is:
* show an "Unauthorized" warning -- since the user can not query for annotations (current behavior) -- maybe limit the warning to the panel, not the dashboard?
* catch any error and just don't show annotations?

what is the expected behavior?

**Comment by torkelo** [comment]
Unable to replicate this. Could it be that the annotations queries where slow and did not finish in time?

**Comment by matti** [comment]
no they were not, but I believe the man
