### ISSUE TITLE
Dashboard does not load in beta5

### ISSUE THREAD

**Issue by felixPG** [grafana/grafana#11018]
Please include this information:
- What Grafana version are you using?
5.0.0-beta5
- What datasource are you using?
Prometheus

Hi:

Recently Im trying grafana-beta5 to use the load of datasources and dashboards automatically when grafana start. 
Datasource load work fine and is cool!
Dashboard load work fine but with errors **due to datasource**:

**Templating init failed
Datasource named ${DS_PROMETHEUS} was not found**

I import manually the dashboard and is working fine, but NOT when I put in yaml under **/etc/grafana/provisioning/datasources/**

Regards

Felix

**Comment by torkelo** [comment]
Dashboards used in provision need to raw dashboard json , not export for share dashboards.

Use the view json feature from dashboard settings view to get the dashboard json

**Comment by felixPG** [comment]
Thanks for your reply, working like a charm after a little change:

RAW JSON
```
  "description": "",
  "editable": true,
  "gnetId": 3320,
  "graphTooltip": 0,
  "hideControls": false,
  "id": 2,
  "links": [],
  "refresh": "5s",
  ...
  ...
  ...
```

Modified JSON

```
  "id": null,
```
Is possible to clarify in the documentation that **id** need to be null?

Regards

Felix

**Comment by timlepes** [comment]
I am having the same problem.  I only encountered the problem after upgrading.  Previously, I had been using the included Prometheus/Grafana stuff as it was back in February, I believe.  Everything was fine.  Then there was a change made on [2023-03-21 - The matrix-prometheus role lives independently now](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#2023-03-21) since my prior update.  After updating and including the changes, I now get the same error as reported here in my Grafana dasahboard:  "Datasource named ${DS_PROMETHEUS} was not found".  I am not very familiar with Grafana or how to configure it, as my only experience has been through this playbook.  I am going to attempt to find my "raw json" and see if I can figure out how to set my UIDs to null, as suggested.  In the meantime, I am hoping that adding myself to the issue will help raise it.
