### ISSUE TITLE
show results of non-failing queries when only one of multiple queries fails

### ISSUE THREAD

**Issue by fsauer65** [grafana/grafana#1101]
I have a situation where a graph panel shows 3 lines, each obtained from a separate (influxDB) query, but one of these queries fails because no data has been written to (a new) DB yet so the series does not exist yet. The other two are fine, yet the entire panel remains empty and in an error state until the third query starts delivering results, at which point all 3 start showing.

![image](https://cloud.githubusercontent.com/assets/869597/5114678/ebbf8f34-7008-11e4-806b-c17635be1334.png)

until the first red dot shows up, nothing shows... I'm using the latest 1.9.0-rc-1
Please render the non-failing query results

**Comment by craftytrickster** [comment]
I consider this to be a somewhat serious bug, because an error in one query halts rendering on the entire graph. If I am monitoring something in production I do not want to lose visual feedback simply because one query is having issues. I am in the process of making a fix for this, I will keep you posted with the results.

**Comment by kmoppel** [comment]
+1. PR seems ready to be merged...

**Comment by torkelo** [comment]
Since influxdb 0.9 all influxdb requests are sent as one. So this issue have to be solved in Influxdb
