### ISSUE TITLE
PostgreSQL data source stopped working with 5.0

### ISSUE THREAD

**Issue by zdzichu** [grafana/grafana#11055]
Please include this information:
- grafana-5.0.0-1.x86_64
- postgresql datasource
- on Fedora Linux
- upgraded from 4.6.3 to 5.0
- dashboard should continue working
- but metric error appeared

Logs show:
> t=2018-03-01T16:51:50+0100 lvl=eror msg="Metric request error" logger=context userId=2 orgId=1 uname="Tomasz Torcz" error="parse postgres://svc-grafana-ro:metrics@%5B::1%5D:5432/house_metrics?sslmode=disable: invalid URL escape \"%5B\""

Configuration of datasource (working in 4.6.3):
Host: [::1]:5432
Database: house_metrics
User: svc-grafana-ro
Password: redacted
SSL Mode: Disable

**Comment by svenklemm** [comment]
Unfortunately this got introduced when url encoding all the parts of the connection string. Apparently you are not supposed to encode the square brackets from ipv6 colon notation, i have to double check if you need to url encode the host part at all. As a temporary workaround you can either leave out the port part and use ```::1``` as host since port 5432 is the default postgresql port anyway or use a proper hostname like ```localhost``` that maps to that IP.
