### ISSUE TITLE
As Admin can no longer change another user's password or re-add a previously existing user and access their invitation URL

### ISSUE THREAD

**Issue by elapse2039** [grafana/grafana#11065]
Upgrading Ubuntu 16.04 Grafana yesterday, I can no longer change another user's password when logged in as Admin.  If I create the user, there is no invite-url button any more but I can copy the invitation URL and manually login as that new user and set a password.

If I delete and re-add a previously existing user (so I can activate the account myself) there is no pending invitation listed. 

I cannot use the forgot-password feature because it fails to email.  I have not setup any email capability on the Grafana host.

**Comment by torkelo** [comment]
if the user exists already he is added to the org directly, so no invitation to create Grafana account. 

If you go to Server admin > Users > find user, then you can set password.

**Comment by darshil-doshi** [comment]
Hi, I am facing the same issue.

I created a user, set it's password and logged in using the credentials.
Next, removed this user. When I try to re-add the user, instead of being listed under pending invites, user is listed as existing users.
My final goal is to change credentials/permissions of the re-added user.

Thanks in advance.
D
