### ISSUE TITLE
Grafana 5.x slack - posting as incoming-Webhook 

### ISSUE THREAD

**Issue by VR6Pete** [grafana/grafana#11079]
Using grafana 5.x on Ubuntu 17.4 and using slack as notification channel. 

When an alert is being posted it doesn’t post unde grafana user but instead the user it posts as is simply “incoming-Webhook”

Is this a bug or is there somewhere to overwrite this? 

Cheers

Pete

**Comment by bergquist** [comment]
Hi Pete

That is indeed the intended implementation. We don't want to use a bot or something like that since that might differ between peoples setups. Nor do we intend to extend the current implementation in the foreseeable future. Once https://github.com/grafana/grafana/issues/6841 have been implemented people can choose to implement their notifications for their exact use-case

I'm closing this issue since we want open issues to reflect the current state of the project. It doesn't mean we never considered it. A closed issue can still get attention from other users and reopen when suited.
