### ISSUE TITLE
Remove `id` from json when provisioning dashboards

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#11138]
Currently, we block dashboards containing an `id` since we cannot guarantee that id in the database. Instead of blocking the dashboard we should remove the `id` and give the user a warning about it.

**Comment by Bonko** [comment]
I observed a corresponding problem:

During our migration to Grafana 5, we removed all dashboard  `id`s from our json files in order to get rid of the error messages.

When updating a dashboard in Grafana 5 and using `view json` afterward to store the updated json, an `id` field gets re-added which then breaks the import again.

In order to avoid future errors, it might be a good idea to not export the `id` field at all.
