### ISSUE TITLE
IE 11 compatibility

### ISSUE THREAD

**Issue by jonasbleyl** [grafana/grafana#11165]
- What Grafana version are you using?
**5.0.1**

Grafana has several UI issues with the update to version 5 when using it in Internet Explorer 11.
These include:
* Login page logo
* Sidebar icons + logo
* The 'edit' view for any graph
* The pie chart plugin

Also, login seems to not be working.

Unfortunately that means that Grafana is unusable in IE even though version 4.6.0 worked fine.
Is IE 11 compatibility something that will be worked on or is it not supported? 

I can provide more detailed examples with screenshots if needed.
Thanks!

**Comment by daniellee** [comment]
I discussed IE 11 support with the team on whether we do/should/will support it.  We really do not want to tons of work to keep Grafana working in IE11 but can fix some of the critical issues so that it mostly works. Getting the UI to be polished for IE11 is not a priority considering its market share and its poor support for modern CSS.

The edit view is easy to fix and we will release a fix for that in Grafana 5.0.2. Are there any other issues that you would deem critical that should be fixed. 

Login worked fine for me (albeit it looked a bit weird). Can describe the problem in more detail, please.

**Comment by jonasbleyl** [comment]
Unfortunately in our organisation we have hundreds of users that still use IE 11 so having Grafana work correctly in IE 11 is a must for us. I can understand that the UI won't be as polished due to the poor CSS support however.

Login seems to be working for me now so that might have been another issue. Sorry about that.
So, apart from the edit page you mentioned; here are the main UI/UX issues that I could find:

* Popup when refreshing any page, when attempting to sign in/out and when clicking a link to another dashboard.
![image](https://user-images.githubusercontent.com/12758226/37206089-278af37c-238f-11e8-98f9-8707a8aea3e6.png)

* Legends don't appear when set to display to the right in graphs and in other plugins such as pie chart.
![image](https://user-images.githubusercontent.com/12758226/37206135-55677fd6-238f-11e8-87fe-3c6732007fbc.png)

* Login page
![image](https://user-images.githubusercontent.com/12758226/37206169-756ad936-238f-11e8-9199-d4e2228a920d.png)

* Navbar icons
![image](https://user-images.githubusercontent.com/12758226/37206185-803fb61a-238f-11e8-9277-9925bf10c8d6.png)

* Dashboard search alignment
![image](https://user-images.githubusercontent.com/12758226/37206270-e1151caa-238f-11e8-8756-b8cea70bb875.png)

**Comment by bgruenefeld** [comment]
hi,
today we recognized the same IE11 issues as jonasbleyl reported.
we are using grafana version 5.0.3

Especially the edit view and the pop up are serious issues for us.

what are the plans for fixing these two issues?

kind regards,
Bernd

**Comment by torkelo** [comment]
Not sure we can support IE 11 fully.

**Comment by bedrin** [comment]
IE11 market share might not be big, but in enterprises it's still most used browser. At least all the basic functionality should work in IE11.

**Comment by bgruenefeld** [comment]
full agree with @bedrin 

for the next 1,5 years we have no chance to switch to a modern browser as IE11 is set as default browser by our IT administration.

**Comment by daniellee** [comment]
Most of the issues are fixed in the master branch and will be included in the 5.1 release. There is one very difficult issue to fix - legends on the right hand side of the graph panel. The auto width does not work. To work around it on IE11, you will need to set an explicit width in the Width field for Legend:

![image](https://user-images.githubusercontent.com/434655/38253263-87380046-3756-11e8-9d37-cbc4ea7386b2.png)

One more fix left to be merged - the alert list styling.

**Comment by daniellee** [comment]
Closing this as all planned fixes are implemented now and will be released in 5.1.
