### ISSUE TITLE
[Feature Request] variable in dashboard title

### ISSUE THREAD

**Issue by JamesGalt** [grafana/grafana#11191]
Hi, It would be nice to be able to use a variable in dashboard title so we can differentiate multiple tabs with same dashboard.
Thanks

**Comment by marefr** [comment]
Okay gotcha. Sure I'll reopen it. But it don't make sense to render each selected variable value in the browser page title. How would you propose this will work, do you have any suggestion?

**Comment by JamesGalt** [comment]
Using variable in dashboard settings, as below
<img width="615" alt="capture d ecran 2018-03-12 a 16 42 42" src="https://user-images.githubusercontent.com/13592957/37293790-93c5d444-2614-11e8-8e40-5bd8b8b69b39.png">

**Comment by marefr** [comment]
Still find this solution a bit weird since the users who is browsing dashboard will see *Dashboard title $variable_name* everywhere. I would strongly suggest that you create separate dashboards instead to solve this. Creating dashboards programmatically can be something to look into if you want to have same dashboard content/panels but based on different data.

We'll keep this open and wait to see if there are other users interested in this feature. If a lot of users upvotes this we'll consider to implement/merge it.

**Comment by JamesGalt** [comment]
The problem is that I have more than 200 values in the variable I want to use in the title... I usually open several tabs to see some of them so it would be handy to be able what we see in the tab title, maybe an option elsewhere than dashboard title, like "tab title"?

**Comment by bergquist** [comment]
Thank you for taking the time to provide feedback to us. 

But I don't see us implementing this in the near or midterm future. So I'm closing this issue since we want open issues to reflect the current state of the project. It doesn't mean we never considered it. A closed issue can still get attention from other users and be reopened.

**Comment by Gauravshah** [comment]
@JamesGalt did you fond any workaround for this ?
the title helps in searching for dashboard within chrome browser.
We have GMV dashboard that can display data by app. so if people search in the url "GMV iphone" they would get the link to the dashboard with filters applied.
with today they have to search GMV then still go back to filters and change it to iphone

**Comment by xavierog** [comment]
@Gauravshah What do you mean by "still go back to filters and change it"? As of today, if you find a formerly visited URL in your browser's history (here through the address bar) and that URL has the adequate query string parameters, then you should not have to adjust the filters...

**Comment by Gauravshah** [comment]
@xavierog that is correct but then looking through parameter in a long URL is difficult.
<img width="1193" alt="Screen Shot 2019-05-22 at 1 18 16 AM" src="https://user-images.githubusercontent.com/620559/58158588-95338700-7c2f-11e9-9dc9-ffe8d9ccac1f.png">

**Comment by nathanpegram** [comment]
I am using a workaround for this by running a little script inside a text panel that is otherwise empty and unobtrusive:

`<script` type="text/javascript">
`window.document.title = '$VARIABLE' + ' Base Title';
`</script>

Not sure if that will help @Gauravshah with searching, but it helps me identify which tab I'm looking for among many. Which is I think what @JamesGalt was trying to accomplish.

It would be nice if there were a way to do this in the dashboard setting - a separate setting for what the rendered page title will be from what the dashboard title is within grafana. That separate setting would of course need to interpret and update dashboard variable values.

**Comment by xavierog** [comment]
@nathanpegram That is a clever workaround; too bad it requires to set `disable_sanitize_html = true` in grafana.ini ...

**Comment by nathanpegram** [comment]
@xavierog yes, precisely. That's why it would be nice if this were built into the dashboard settings.

**Comment by pete-mckinney** [comment]
This would be a very useful feature for my group as well.  We have one dashboard that serves as an overview of our entire environment, and then a detail dashboard that represents the activity of a single server.  It would be nice to be able to represent the server name variable in the title, so I could open multiple instances of the detail dashboard and see the name represented in the tabs.

**Comment by bugfix4u** [comment]
I would also like to see this feature implemented. When managing hundreds of systems, it would be nice to have the dashboard title/browser tab reflect the chosen system that is being viewed.

**Comment by JadeKessinger** [comment]
I would also like to see this feature implemented  - same use case as @pete-mckinney and @fabbaena
