### ISSUE TITLE
[Feature Request] Annotation in dashboard title

### ISSUE THREAD

**Issue by JamesGalt** [grafana/grafana#11192]
Hi,
It would be nice to be able to use annotations in dashboard title so we can see last value of an important metric directly in the tab title.
Thanks

**Comment by bergquist** [comment]
Thank you for taking the time to provide feedback to us. 

Right now we don't think this idea aligns with the current scope/goal of the Project. I'm closing this issue since we want open issues to reflect the current state of the project. It doesn't mean we never considered it. A closed issue can still get attention from other users and be reopened.
