### ISSUE TITLE
[New Feature Suggestion] per panel HTTP source and parser to widen the Grafana use-cases

### ISSUE THREAD

**Issue by jhsenjaliya** [grafana/grafana#11229]
I see Grafana is leading dashboard tool having capabilities to fetch data from deep storage, which is also the limitation I see where someone will have to push the data to the deep storage.
if Grafana provides a way to fetch data directly from HTTP URL which can differ per panel ( not necessarily storing the data, but that would be awesome too ), it would allow user to leverage full capabilities of grafana as dashboard tool.
would like to get community feedback on this.

because of my use-case, I have already started working on this feature, but my knowledge of Grafana codebase is limited and i m only targeting TABLE panel type which works for my use-case, I would be happy to have someone join the feature team to develop complete feature.
Please let me know if more details are needed.

**Comment by bergquist** [comment]
Grafana support datasource plugins. So you can write your own plugin that consumes any kind of information from where ever you want. http://docs.grafana.org/plugins/developing/datasources/

If you want to write a generic json transformer I suggest you start doing it as a plugin. If the plugin becomes popular it might end up in Grafana core. Since we dont accept new plugins to core Grafana at the monent, I'm closing this issue. That doesnt mean this can never be a part of Grafana. Just that it's not something we want to work on in the upcoming year.

**Comment by jhsenjaliya** [comment]
Thanks @bergquist for the suggestion, I have created datasource plugin for HTTP that would fetch data over REST endpoint, but I find grafana core ( go proxy module) has limitation that it makes call to predefine datasource target and can not be dynamic target supplied via panel.
I doubt if app plugin can provide the mentioned functionality but i will explore and come back to you. may be different HTTP source per panel is too much.
Thanks again for your reply.
