### ISSUE TITLE
Provisioning dashboard with alert rules should create alerts

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#11247]
Provisioning of a dashboard that has alert rule(s) fails with an invalid alert data error. Reported in #11227

Similar, when creating a new dashboard that has alert rule(s) it should be possible to save that without failure with invalid alert data error.

**Comment by jeremyjpj0916** [comment]
Looking forward to this fix up, currently am making all dashboards with no alarms and configuring them manually due to this bug. Have the JSON ready with the alarm data ready once fixed to swap over though!(Granted if the fix does not change the alarm json data format from how it currently looks lol).

-Jeremy
