### ISSUE TITLE
Customizing Graph Panel message “No data points”

### ISSUE THREAD

**Issue by abmalam** [grafana/grafana#11250]
Hi there,

We are using Grafana 4.4 and have a request from a user if he can display “No metrics available” or any other customized message instead of the default “No data points” where there is no data available from a data source in a graph panel. The data source in this case is “Prometheus”.

Thanks.

Please include this information:
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

![graph data coming](https://user-images.githubusercontent.com/37160334/37420129-6e90fc7a-278c-11e8-9f88-e92426ccdb00.jpg)

![graph data not coming](https://user-images.githubusercontent.com/37160334/37420141-739dbcee-278c-11e8-9040-212b894dbf6e.jpg)

**Comment by bergquist** [comment]
Thank you for taking the time to provide feedback to us. 

We don't want to introduce settings for things like this. It just ends up being a maintainability burden. I'm closing this issue since we want open issues to reflect the current state of the project. It doesn't mean we never considered it. A closed issue can still get attention from other users and be reopened.
