### ISSUE TITLE
Smaller distribution file?

### ISSUE THREAD

**Issue by porjo** [grafana/grafana#11254]
`grafana-5.0.2.linux-x64.tar.gz`ways in at a whopping 51MB compressed. Removing `tools/phantomjs` and `public/build/*.map` files brings this to under 20MB.

It would be nice if the development & debug extras were removed from the distribution file.

**Comment by torkelo** [comment]
95% of that reduction is the phantomjs binary that does compress well, and that binary is needed during runtime. We will explore a way to make this a dependency that users have to install separately when we move to headless chrome instead of phantomjs.

The *.map files are important to include in official releases as they help in troubleshooting issues and are only loaded when you open browser dev tools.

**Comment by porjo** [comment]
> binary is needed during runtime

ah, ok - thanks! I had assumed phantomjs was used for testing. I gather it is used for server-side rendering...and is scheduled to be replaced by Chrome (#10751). Perhaps it could be made optional in future (I for one don't want/need server-side rendering).

**Comment by torkelo** [comment]
yes, I hope so. it would make the distributable so much smaller.
