### ISSUE TITLE
Graph displaying seconds is drawn inaccurately

### ISSUE THREAD

**Issue by drycoffee** [grafana/grafana#11265]
### What Grafana version are you using?
- Grafana v4.6.2 (commit: 8db5f08)
### What datasource are you using?
- Prometheus
### What OS are you running grafana on?
- Linux (4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)
### What did you do?
- Created a graph to display a metric which measures seconds.
- Set unit of the Y-axis to "seconds (s)"
- Measured value returns around 86400 seconds (one day).
### What was the expected result?
- Graph should be drawn on the 1.0 day marking
### What happened instead?
- Graph is drawn below the 1.0 day marking

![auswahl_393](https://user-images.githubusercontent.com/26259579/37479001-d3916084-287b-11e8-9c34-c83bdc7017d4.png)
### If related to metric query
For testing purposes - query: "86400"

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
Not sure if this helps, but here you go:
[network_traffic.har.zip](https://github.com/grafana/grafana/files/1816405/network_traffic.har.zip)

**Comment by bergquist** [comment]
That's weird. Might be a bug in kbn.

**Comment by free** [comment]
FYI, I've seen this happen too. What happens is that the precision (i.e. number of decimals) of the values on the Y axis hides the fact that the "1.0 day" label on your graph is actually closer to something like 1.07364 days, i.e. the grid doesn't actually include 1 day, just something around 22 hours (labeled as "22 hours") and something around 26 hours (labeled as "1.0 day").

Now that I have actually given it some thought, I would guess the grid is drawn at multiples of 10K seconds. 80K is 22.(2) hours and 90K is 25 hours. So your "1.0 day" grid line is actually drawn at 25 hours.

**Comment by martin2250** [comment]
Adding to this, the Y-axis labels seem to be rounded, rather than being truncated. Maybe also displaying seconds wouldn't hurt when only showing a small range and multiple Y-axis labels are sharing the same text.  ![image](https://user-images.githubusercontent.com/8293473/43359615-5ea8151c-92a5-11e8-9370-a84408e26ec3.png)

**Comment by Xavier59** [comment]
Dear devs,

It seems that this problem is not totally fixed (version 6.3.0-beta4 here).
I have data that go from a scale to 1 to 100. It auto scales well on big timeframes (days), but doesn't do well on small timeframes when my values are low.

Here is an example :

image
![image](https://user-images.githubusercontent.com/10245003/62462443-bbc18280-b787-11e9-94c0-6064f43dca96.png)


Is there any way I could have it to scale better on small timeframe when my values are low ?
Thank you

**Comment by torkelo** [comment]
this is fixed in later version of Grafana
