### ISSUE TITLE
Annotations hidden behind range

### ISSUE THREAD

**Issue by Shaunwild97** [grafana/grafana#11297]
Currently if there is an annotation behind an annotated range, you cannot hover on the annotation as the range covers it.

Could it be a possibility for the annotations to be displayed on top of ranges?

**Comment by thisisobate** [comment]
Hi @Shaunwild97 
We would need more information to help support you better. But from what I could see, it seems this has been fixed in the recent versions of Grafana. Please take a look at this dashboard [here](https://play.grafana.org/d/A28axz_Gz/new-dashboard-copy?orgId=1&from=1617001776531&to=1617007580409).

With that being said, if you feel this doesn't work as you would expect, please feel free to reopen this issue.

Thanks!
