### ISSUE TITLE
Migration Failed error: UQE_dashboard_org_id_slug

### ISSUE THREAD

**Issue by Moogleson86** [grafana/grafana#11351]
I am having an issue after updating to 5.0.3.

The service will not start due to this error:

msg="Exec failed" logger=migrator error="Error 1091: Can't DROP 'UQE_dashboard_org_id_slug'; check that column/key exists" sql="DROP INDEX `UQE_dashboard_org_id_slug` ON `dashboard`"

Any thoughts on a cause or resolution?

**Comment by bergquist** [comment]
Seems like the migration got into a bad state. 
My guess is that you are using mysql, which doesn't support transactions for schema updates and when you ran the migration the mysql server rejected parts of the migration so Grafana got into a state it cannot get pass. I suggest you create the index so Grafana can delete it or insert a dummie row in `migration_log` table with `migration_id` = `Remove unique index org_id_slug`

I'm closing this issue since it will be addressed by https://github.com/grafana/grafana/issues/11090

If my assumptions about mysql is wrong, please poke me so we can reopen this.
