### ISSUE TITLE
Feature Request: Org Templates

### ISSUE THREAD

**Issue by rijnhard** [grafana/grafana#11361]
Hi, the wording may be off but essentially this is the use case. 
To have an organisational level template with predefined dashboards, so that all that needs to happen is the org needs to be created from the template and all the dashboards that org would need are already loaded.

This is useful when you are providing statistics for clients that each have there own environment and will dramatically cut down on the time needed to spin up each client.

**Comment by bergquist** [comment]
This can be solved by provisioning dashboards to new orgs. http://docs.grafana.org/administration/provisioning/#dashboards

It will require a little scripting on your side but nothing major. Since we rather work on features like that I don't see us adding support for something like this in the future.
