### ISSUE TITLE
Folder expansion options

### ISSUE THREAD

**Issue by Codelica** [grafana/grafana#11370]
Love the new folder and teams additions.

Once thing I'd like to see is some mechanism to allow created folders to be expanded by default when the dashboard list is brought up, to make quick mouse navigation easier.  I think there are several possibilities:

1) Preserve the collapsed/expanded state of each folder shown (per user).
2) Allow for a default collapsed/expanded setting for each folder.
3) Auto expand the folder that the currently viewed dashboard is in.

I imagine there are other options.  From what I've seen so far, "general" seems to be permanently expanded, and only "recent" and "starred" preserve state.

Thanks for listening... (and for Grafana 👍 )

-James

Please include this information:
### What Grafana version are you using?
5.0.3

**Comment by bergquist** [comment]
@daniellee do you see us implementing this?

**Comment by marefr** [comment]
Little bit related to #10895

**Comment by mattiasholmlund** [comment]
I recently moved all of our dashboards into a set of folders to improve the structure. The result is however that it now always takes one more click to get to a dashboard, and I am already starting to regret the folders.

I would love to see option 1 (Preserve the collapsed/expanded state of each folder shown) implemented, preferably based on a cookie so that each browser session has its own state for which folders are open.
