### ISSUE TITLE
how to disable annotation query

### ISSUE THREAD

**Issue by ntting** [grafana/grafana#11408]
grafana version:5.0.0_Beta1
datasource:simplejson
os: win7, 64
i want to disable annotation query, because i don't use this feature, but it will show annotation query failed error.
i Comment the annotation query code in simplajson code ,but it didn't work, still have annotation query
**how to disable annotation query?**
annotation error:
![annotation](https://user-images.githubusercontent.com/13620253/38011349-a9f2e07c-328f-11e8-910e-ce2d63b7f5dd.jpg)
comment code:
![code](https://user-images.githubusercontent.com/13620253/38011379-c662260a-328f-11e8-8743-6db98131db8c.png)
query:
![query](https://user-images.githubusercontent.com/13620253/38011400-e064b2d4-328f-11e8-9204-974a42409f63.png)

**Comment by torkelo** [comment]
go into dashboard settings > annotations and remove your annotation query

**Comment by ntting** [comment]
@torkelo i don't add annotation query。
![annotation](https://user-images.githubusercontent.com/13620253/38016914-236162ae-32a3-11e8-9d54-1f4e1f0063c7.png)

**Comment by torkelo** [comment]
the error looks very strange, can you open chrome dev tools and check console? the api requests looks to return 200 OK, so no error. What is the response from the /api/annotations request?

**Comment by ntting** [comment]
@torkelo, the error is show in another country customer, i visit 200 ok.  I find the graph get the annotation by default,  because there isn't the annotation query when i use the same datasource in table.

**Comment by provenvelocity** [comment]
I get his same error if the browser is held open, I don't see that you solved it. I think this might be because of auth proxy... when i reload it works fine.  Any ideas?

**Comment by provenvelocity** [comment]
This is actually happening for me because the auth-proxy is timing out in the cookie and the the 
Annotation Query Failed error is the only one in grafana that outputs to the ui. the render is also having the same error at the same time and is not reporting to the ui. The core reason is that for some reason there is no code to handle for 302 cores errors when using auth proxy and redirect back to the auth system. 

example below with one login as the authproxy.... 

bliss-chat?orgId=1&refresh=5s&var-LOB=uber*&var-Site=All&var-DC=dca1:1 Access to XMLHttpRequest at 'https://app.onelogin.com/trust/saml2/http-post/sso/358421?SAMLRequest=nVNdj9owEPwrkd%2FzSbiCBZwop6pI1zaC9F5Pi70BS46dep07%2Bu9rAlQ89Hjok6Pd8ezMZD0jaHXHl70%2FmA3%2B6pF8dGy1IT405qx3hlsgRdxAi8S94Nvlt2deJBnvnPVWWM2i6vL1WRmpzP7%2Btd0ZRPxrXVdx9WNbs%2BgFHSlr5iwAWLQm6nFtyIPxoZTl0zgr47yos5IXUz5%2BCJCnOXuQxadR1mSQFdOyHMtwZvm4zIrJqJlgk7NoSYTOB%2BKVNdS36Lbo3pTAn5vnOTt43xFP051WRLEEOuwsOBmHsfugL%2Bl36JTx6AzoRNg2tUpCCCp1ShxexZnxce9s37XQvb5dLJRJFjwsZqcA%2BeDE3UR6Pxq46mWLqzrousQa1DZoGlScWNIWPUjwkI7Gk7LIZ%2BnNtPPojn8P9OunymolfkdLre37yiF4nDPvemTRF%2Bta8B8LypN8qCgZNwOUYwtKL6V0SMTS65zL3qActigk7fHoo5VtO3CKTj8VjyD8NZJb1EoHxxts%2FieguzDBxYk6lKtwvFsnTyuKIqisHRjqrPOX0P6lZ3HufeDtb%2Ff22Sz%2BAA%3D%3D&RelayState=%2Fapi%2Fdatasources%2Fproxy%2F1%2Frender' (redirected from 'https://bliss-dashboard-staging.uberinternal.com/api/datasources/proxy/1/render') from origin 'https://bliss-dashboard-staging.uberinternal.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by provenvelocity** [comment]
This is the code
    .catch(err => {
        if (!err.message && err.data && err.data.message) {
          err.message = err.data.message;
        }
        console.log('AnnotationSrv.query error', err);
          this.$rootScope.appEvent('alert-error', ['Annotation Query Failed', err.message || err]);
        return [];

responce

* Response Headers
    * cache-control: max-age=0
    * content-length: 154
    * content-type: text/html
    * date: Wed, 10 Apr 2019 22:24:43 GMT
    * location: https://app.onelogin.com/trust/saml2/http-post/sso/365152?SAMLRequest=xxxxx
%2Fapi%2Fdatasources%2Fproxy%2F1%2Frender
    * server: nginx
    * status: 302
    * strict-transport-security: max-age=604800
    * x-content-type-options: nosniff
    * x-frame-options: SAMEORIGIN
    * x-xss-protection: 1; mode=block
