### ISSUE TITLE
Reduce the amount of full page reloads in playlist mode.

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#11429]
When the playlist is complete Grafana will do a full page reload to get an updated version of the playlist and avoid potential memory leaks. The full page refresh can feel flashy and feel distractive compared to a normal cycle between playlist items. 

I think we can update the playlist every cycle without a full page reload and only trigger full page reloads every X playlist cycles.

**Comment by Stef3478** [comment]
We are running a Grafana playlist on a raspberry pi and during the full page reload it flashes white for some time, very distractive indeed. Would love to see a solution for this as well.

**Comment by delfuego** [comment]
Just wanted to chime in, though, to mention that as of right now, many folks (myself included) use playlists to **force** a full page reload because of memory leaks... so we still very much need that to happen, at least until memory leaks can be addressed. As it stands, playlists are the only way to run Grafana on many digital media player signage devices (e.g., Brightsign players) without the memory leaks causing total failure within hours...

**Comment by torkelo** [comment]
this should be very easy for anyone to contribute, relevant code is here:
relevant code is here:
https://github.com/grafana/grafana/blob/master/public/app/features/playlist/playlist_srv.ts#L22

change it to only do a full page reload every 3rd or 5th cycle?

**Comment by aocenas** [comment]
I will take a look.
