### ISSUE TITLE
Improve file structure in the grafana repo

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#11433]
* create new folder named `devenv`
* move `docker` to `devenv/ds-docker`
* create folder for provisioned dev datasources `devenv/ds-config`
* create folder for provisioned dev dashboards `devenv/dashboards`
* create bashscript for coping(windows)/symlining(nix) `dashboards.yaml` & `datasources.yaml` into `conf/provisioning`
* move `tests` into `devenv/tests`. (test config files can be moved to `/pkg/settings/test-data`
* move `scripts/benchmark` to `devenv/benchmark`
* move `examples` to `devenv/examples` (or just nuke it)

I would like to rename `scripts` to `build` but I'm not sure its worth it considering all how many paths we would have to update.

**Comment by bergquist** [comment]
One of the bigger goal for this is to share datasource configuration and dashboards in dev env. So its easy to get started working in certain dashboard features etc.

**Comment by torkelo** [comment]
Amazing!

**Comment by marefr** [comment]
This is nice! Some comments:

> * move docker to devenv/ds-docker
I think we should keep the name docker since there's not only docker container for data sources. 

If we move `tests` into `devenv/tests` maybe we should move the `tests/api` to somewhere else. `integration tests`?

Would be nice to move build related stuff to a `build` folder to clean up the root directory a bit. I guess this is mostly related to building the frontend code. `tasks/options` for example doesn't need to be in the root folder. Think `packaging` could be moved to a build folder.

`Examples` and `Emails` could possible be moved to some sub folders as well. Maybe `Examples` can be removed and we can have the alerting dashboard examples in the `devenv/dashboards`?

**Comment by bergquist** [comment]
> Maybe Examples can be removed and we can have the alerting dashboard examples in the devenv/dashboards
:+1:  

> If we move tests into devenv/tests maybe we should move the tests/api to somewhere else. integration tests?
I think this depends on the scope of the api tests. If those the goal of those is to make development easier, then `devenv` is fine. 

> Would be nice to move build related stuff to a build folder
This would require lots of path updates. I think we should consider all other changes first and fix the build related files later.

**Comment by torkelo** [comment]
looks like most of this is done, I think we can move docker to dev/docker  (not sure ds-docker is a good idea as docker compose blocks are more than just datasources)

**Comment by bergquist** [comment]
I'll create a PR for moving the docker folder.
