### ISSUE TITLE
[Feature request] $__interval in Prometheus should never be less than double scrape interval

### ISSUE THREAD

**Issue by distol** [grafana/grafana#11451]
Hi! I'm using Grafana 5.0.4, Prometheus 2.2.1.

### What did you do?

* Setup Prometheus to scrape every 30s
* Setup Scrape interval in Grafana datasource also to 30s
* Add graph with one counter metric:
  * `sum(rate(nginx_bytes_total[$__interval]))`
  * Resolution: `1/1`
* Try to open it in two periods:
  * Last 6 hours
  * Last 12 hours

### What was the expected result?

* Graph to show data for both periods

### What happened instead?

* Graph is not showing data for periods less than 12 hours because with my screen resolution with such periods I have 30s both in step and in `$__interval`, and to calculate such functions as `rate` Prometheus needs to have at least two points in range-vector.

### The real problem

* Yes, you could set min step for that query, or simply you could use static value instead of `$__interval`. But you will not be able to use the same dashboard with data sources with different scrape periods. For example, I have three Prometheus servers: main (scrape 30s, retain 2w), highres (scrape 2s, retain 1h) and longterm (scrape 5min, retain 1y).
* Yes, you could set some big enough value (in our case it would be 10m, double of longest of scrape periods) — and you will not have accurate data, only a rough approximation.
* Yes, you could always use resolution `1/2` (or lesser), but when you zoom in — you will always lose half of your data. For example, if you are looking at 30 min period, you will have only 30 points, but you have enough data in Prometheus to show 60, why not show all information?
* So, **the real problem is** — you should choose between "portability" and "accuracy" and never have both! Am I missing something?

### Feature request
There are two possible ways:

* Make`$__interval` in Prometheus be newer less than double scrape interval
* Add something like `$__interval_for_range_vectors`, that will have that semantic, to not to make breaking changes

### Simple patch
Thanks to [that commentary](https://github.com/grafana/grafana/issues/7664#issuecomment-367257838) I've made a simple patch that works for me:

```
--- a/public/app/plugins/datasource/prometheus/datasource.ts 2018-03-31 00:55:44.311730859 +0300
+++ b/public/app/plugins/datasource/prometheus/datasource.ts 2018-03-31 01:08:45.001737703 +0300
@@ -151,6 +151,11 @@
__interval_ms: { text: interval * 1000, value: interval * 1000 },
});
}
+ var intervalForRangeVectors = Math.max(minInterval * 2, interval);
+ scopedVars = Object.assign({}, scopedVars, {
+ __interval_rv: { text: intervalForRangeVectors + 's', value: intervalForRangeVectors + 's' },
+ });
query.step = interval;

// Only replace vars in expression after having (possibly) updated interval vars
```

**Comment by torkelo** [comment]
related to discussion here, https://github.com/grafana/grafana/issues/9705

**Comment by distol** [comment]
@free, thanks! I agree, that replacing `$__interval` would not be right! But having `$__interval_rv` gives us, right now, the real ability to make precise graphs with rate/increase.

**Comment by free** [comment]
One suggestion for a workaround (which I am using): define a recorded rule in Prometheus that takes the rate over as short an interval as you prefer. (This could vary from Prometheus instance to Prometheus instance, if you have varying scrape/eval intervals.) You can even work around the estimation errors introduced by Prometheus' extrapolation of rates, by using something like this:

    rate(foo[<eval_interval + scrape_interval>]) * <eval_interval> / <eval_interval + scrape_interval>

I.e. take the rate over eval plus scrape interval, (actually rate over eval interval, extrapolated) and adjust for the extrapolation.

Then in Grafana you can graph an `avg_over_time` of this and, optionally, if you want to be able to zoom in to arbitrary resolutions without having to specify an explicit min step, `or` this with the metric itself (so it the `avg_over_time` doesn't find any values within the range, you'll get the last value before the range (as long as it's not more than 5 minutes before):

    sum by() (avg_over_time(foo_rate[$__interval]) or foo_rate)

(I thought this would work with the `or` only, but you'll need the `sum` too, to aggregate the steps where you have an `avg_over_time` value because there is at least one sample there with the ones where there is no sample.)

Surprisingly complex, but effective. :o)

**Comment by bazhenov** [comment]
@free Does `TS - (TS offset $__interval)` works for you?

**Comment by free** [comment]
It works, with 2 limitations:
1. You need to set a min interval (otherwise you'll get a result that's mostly zeroes, with spikes for every sample.
2. It's twice as slow as `rate()`, because it needs to look up twice the series (it doesn't understand it's the same series on both sides of the operation).

It's mostly because of (2) that I'm not using it in my dashboards and went for the recorded rule approach described above, instead.

**Comment by bazhenov** [comment]
Yep, make sense. Thank you.

**Comment by matejzero** [comment]
How about setting `Scrape interval` in Prometheus datasource to 2*actual scrape interval? I'm using this solution and it works in my case. Would that solve the problem? What are the down sides of setting scrape interval like that?

**Comment by distol** [comment]
> How about setting `Scrape interval` in Prometheus datasource to 2*actual scrape interval? I'm using this solution and it works in my case. Would that solve the problem? What are the down sides of setting scrape interval like that?

You will lose half of the accuracy in all graphs.

**Comment by pjroth** [comment]
Grafana influxDB data sources solve this problem by allowing an option of "min time interval" on both the data source globally and on every query you can override this global setting.  This requires the report writer to understand the scrape interval so this isn't perfect but it gives an option at least that prevents graphs from showing no data when the time range displayed is short.

https://grafana.com/docs/features/datasources/influxdb/#min-time-interval

A similar solution could perhaps be added to prometheus itself where the given query range could be changed to a minimum configured value if the query is made with a time range that is less than 2x the scrape interval that is outside the scope of this project however.

**Comment by candlerb** [comment]
I can give a specific examples of the problem.

I am scraping an SNMP data source every 1 minute.  To confirm this: if I do a query with a 10 second step, you can see the value incrementing every 60 seconds:

```
# /opt/prometheus/promtool query range http://localhost:9090 'ifHCInOctets{instance="ix-asa1",ifName="DMZ"}' --step 10s
ifHCInOctets{ifDescr="Adaptive Security Appliance 'DMZ' interface", ifIndex="21", ifName="DMZ", instance="ix-asa1", job="snmp", module="if_mib1", type="device"} =>
1935939450161 @[1576099301.233]
1935939450161 @[1576099311.233]
1935939450161 @[1576099321.233]
1935942546355 @[1576099331.233]
1935942546355 @[1576099341.233]
1935942546355 @[1576099351.233]
1935942546355 @[1576099361.233]
1935942546355 @[1576099371.233]
1935942546355 @[1576099381.233]
1935947654557 @[1576099391.233]
1935947654557 @[1576099401.233]
1935947654557 @[1576099411.233]
1935947654557 @[1576099421.233]
1935947654557 @[1576099431.233]
1935947654557 @[1576099441.233]
1935952272456 @[1576099451.233]
1935952272456 @[1576099461.233]
1935952272456 @[1576099471.233]
1935952272456 @[1576099481.233]
1935952272456 @[1576099491.233]
1935952272456 @[1576099501.233]
1935958955468 @[1576099511.233]
1935958955468 @[1576099521.233]
1935958955468 @[1576099531.233]
1935958955468 @[1576099541.233]
1935958955468 @[1576099551.233]
1935958955468 @[1576099561.233]
1935962175141 @[1576099571.233]
1935962175141 @[1576099581.233]
1935962175141 @[1576099591.233]
1935962175141 @[1576099601.233]
```

Now, you'd think that `irate(..)[1m]` would work.  But it shows nothing.  What you actually need is `irate(..)[2m]`

What's fascinating is if you try `irate(..)[70s]`.  In Grafana the resulting graph looks like this:

![image](https://user-images.githubusercontent.com/44789/70663243-d89f2280-1c5f-11ea-8794-ee4205930d64.png)

At the command line:

```
root@ix-prometheus:~# /opt/prometheus/promtool query range http://localhost:9090 'irate(ifHCInOctets{instance="ix-asa1",ifName="DMZ"}[70s])' --step 10s
{ifDescr="Adaptive Security Appliance 'DMZ' interface", ifIndex="21", ifName="DMZ", instance="ix-asa1", job="snmp", module="if_mib1", type="device"} =>
85136.7 @[1576099391.998]
76964.98333333334 @[1576099451.998]
111383.53333333334 @[1576099511.998]
53661.21666666667 @[1576099571.998]
78065.25 @[1576099631.998]
# /opt/prometheus/promtool query range http://localhost:9090 'rate(ifHCInOctets{instance="ix-asa1",ifName="DMZ"}[70s])' --step 10s
{ifDescr="Adaptive Security Appliance 'DMZ' interface", ifIndex="21", ifName="DMZ", instance="ix-asa1", job="snmp", module="if_mib1", type="device"} =>
76964.98333333334 @[1576099450.079]
111383.53333333334 @[1576099510.079]
53661.216666666674 @[1576099570.079]
78065.25 @[1576099630.079]
229085.31666666668 @[1576099690.079]
```

As far as I can tell, what's happening is this. Prometheus is sliding the query along, and looking for two datapoints within the 70s window.  Most of the time, there's only one datapoint in that window, and the graph is blank:

```
....|...........|...........|....
            <------------->
          <------------->
```

But for around 10 seconds, two datapoints fit in the window, and so `irate()` can be calculated:

```
....|...........|...........|....
    <------------->
```

(aside: the same seems to be true of `rate` as well as `irate`).  Hence to get a continuous graph, you need to give a range of at least twice the sampling interval.

I think that the solution, as the OP originally said, is for grafana to provide a variable which is twice the step.  Unfortunately, prometheus does't accept arithmetic inside the range selector:

```
irate(...)[ $__interval * 2 ]    # gives "unexpected op.*" error
```

Now, when using `rate` instead of `irate`, and you're zooming out so the step is large, you're not actually interested in the instantaneous rate (this results in the problem of spikes appearing and disappearing as the time window moves).  If you've zoomed out so that the query step is (say) 5 minutes, then you want rate not irate, but you want it calculated over 5 minutes.  Is 10 minutes the right range?  No, actually it's 5 minutes *plus* 1 minute for the sampling interval; a 6 minute window ensures that the first and last points are 5 minutes apart.

So I *think* what we want is a variable which is the sum of the graph step interval plus the sampling interval.  Does that sound reasonable?

**Comment by free** [comment]
>So I think what we want is a variable which is the sum of the graph step interval plus the sampling interval. Does that sound reasonable?

Better yet, what would make most sense is if Prometheus provided a `rate()` function that did the obvious thing and returned the rate of increase over 1m when requested to return the rate of increase over 1m, i.e. (in your case) the rate of increase implied by the last two samples. Else you'd have to additionally provide the explanation above to every Prometheus + Grafana user. And make sure they understood it.

Also, you will notice that Prometheus extrapolates the actual rate to the requested time range. I.e. `rate(...[2m])` will indeed (on average) compute a rate based on the last 2 samples, but then (again, on average) multiply the result by 2 (because of extrapolation). And with a `6m` range (in order to compute an actual `5m` rate), you'd get the `5m` rate multiplied by `1.2`. So Grafana would have to provide both a variable that's the graph step plus the sampling interval and a variable that's the ratio of the above to the graph step.

Regardless, take a look at [Prometheus issue 3806](https://github.com/prometheus/prometheus/issues/3806) (disclaimer: filed by yours truly). And maybe try out `xrate()` in http://github.com/free/prometheus (again, forked by yours truly).

**Comment by davkal** [comment]
See discussion in #21417
