### ISSUE TITLE
Support Number Coloring with ES Raw Document field

### ISSUE THREAD

**Issue by mikich** [grafana/grafana#11519]
Similar bug was closed, but I guess with no fix or workaround was found: https://github.com/grafana/grafana/issues/8858

### OS running grafana: OSX 10.11.6
This seems like a bug in Grafana: the _source:Object, which holds a json in the response object return ALWAYS with quotes, no matter how field defined in elasticsearch... 
Here is the example (response for garfana table view):

```javascript
{
"responses": [
{
"took": 0,
"timed_out": false,
"_shards": {
"total": 5,
"successful": 5,
"failed": 0
},
"hits": {
"total": 42,
"max_score": null,
"hits": [
{
"_index": "index_name",
"_type": "logs",
"_id": "h9384h75d983475hd938475hd",
"_score": null,
"_source": {
"FIELD_1_FLOAT": "6",
"FIELD_2_KEYWORD": "Build",
"FIELD_3_FLOAT": "65031.39",
"FIELD_4_FLOAT": "5",
"message": "Build,6,5,65031.39",
"path": "/in/some_file.csv",
"@timestamp": "2018-04-02T15:00:00.000Z",
"@version": "1",
"host": "mac.local"
},
"fields": {
"@timestamp": [
1522681200000
]
},
"sort": [
1522681200000
]
}
]
},
"status": 200
}
]
}
```

But in Elasticsearch Index defined correctly:

```javascript
{
"mappings": {
"myType": {
"_all": { "enabled": false },
"_source": { "enabled": true },
"properties" : {
"timestamp" : {
"type": "date",
"format": "yyyy-MM-dd HH:mm:ss||epoch_millis",
"index": "true"
},
"FIELD_1_FLOAT": {"type": "float", "index": "true"},
"FIELD_2_KEYWORD": {"type": "keyword", "index": "true"},
"FIELD_3_FLOAT": {"type": "float", "index": "true"},
"FIELD_4_FLOAT": {"type": "float", "index": "true"}
}
}
}
}
```

**Comment by aocenas** [comment]
Needs to be checked if this is issue in Grafana or not. If Elastic returns the data as number (in JSON) and we convert it to string that's a bug on our side.

**Comment by Elfo404** [comment]
the issue seems to be that in the dataframe we build for the response every field is created as a string regardless of the field type:

https://github.com/grafana/grafana/blob/f7d6244fa24fbef295049144bdbfcd3a0ec54c19/public/app/plugins/datasource/elasticsearch/elastic_response.ts#L689

The easiest way to solve this would probably be analyzing the first returned document and use a field type that matches the returned value, or to be more accurate (but maybe unnecessary), issue a `_mapping` request as well and apply the proper type.

**Comment by Elfo404** [comment]
closing this in favor of https://github.com/grafana/grafana/issues/29431 which describes the same issue
