### ISSUE TITLE
[Bug] Importing a panel with the same UID overwrites without warning

### ISSUE THREAD

**Issue by josepiratilla** [grafana/grafana#11515]
### What Grafana version are you using?
5.0.4
### What datasource are you using?
Graphite and ElasticSearch
### What OS are you running grafana on?
Debian 8
### What did you do?
Export a dashboard, change some values (including dashboard name) and import it again.
### What was the expected result?
Create a new dashboard (has happened on previous versions) or throw a warning indicating that it will overwrite an existing panel.
### What happened instead?
It overwrote the panel, without any warning.

I know that changing the UID i can override this issue, but I think that at least it could warn the user because importing is a verb that intuitively means adding no updating.

**Comment by josepiratilla** [comment]
If importing with the same name it warns:
![image](https://user-images.githubusercontent.com/6843077/38425500-4fa3972a-39b4-11e8-8b94-7e56cbe50ecd.png)
But if importing with a different name, but same UID it does not warns and overwrite it.

**Comment by MakoSDV** [comment]
I just ran into this problem as well.  I was freaking out that my dashboards disappeared.  I commonly export/import dashboards to duplicate them to different datasources, which worked very well in Grafana 4.6.

Now I have to remember that every time I export a dashboard, I need to delete the UID form the json.  That's really annoying and very confusing for the user since that's not how it worked before.

**Comment by marefr** [comment]
Some more information.

Today, when importing a dashboard there's some logic handling if a dashboard will be overwritten or not. However this logic is implemented on the client side and only validates if there's exists a dashboard with same title. This is how it looks:

![image](https://user-images.githubusercontent.com/1668778/39719680-38ebfe5c-523a-11e8-9d8e-d739da42faf8.png)

But if you import a dashboard having a *uid* that some other existing dashboard has, you won't get any information that some dashboard will be overwritten.

This feature request suggests to solve this problem and make experience consistent with saving dashboards. Instead of validation of dashboard title are made client side and import button changing text to overwrite it's suggested to post to the server and wait for response, if overwrite required pop up overwrite confirm dialog or show inline on page  - this is kind of exactly how it works when saving dashboards. This should make it clearer for users to understand what's going on.
