### ISSUE TITLE
Grafana drops decimal precision far too fast

### ISSUE THREAD

**Issue by pvanderlinden** [grafana/grafana#11529]
Grafana used to display numbers with a decent precision, but since grafana version 5, the decimal precision drops to 0, as soon as you make a graph with more then one line.

I compared two versions:
4.6.3 and 5.0.4: Grafana 4 seems to drop all precision on a graph with more then 4 lines, Grafana 5 seems to drop all precision on a graph with more then 1 line which really restricts the usage of grafana. I found a work around by overriding the decimal on the legend for every single graph, it would be great to have a more useful auto precision.

- Grafana: 5.0.4
- OS: debian arm (raspbian)
- Datasource: InfluxDB: the database actually returns the metrics in the correct precision (1 decimal in this case)

**Comment by pvanderlinden** [comment]
I attached a screenshot and the raw results from the network console
![graph](https://user-images.githubusercontent.com/391586/38489327-ef7c10d0-3bdd-11e8-91a5-b2d74c20956d.png)
[raw.json.txt](https://github.com/grafana/grafana/files/1889157/raw.json.txt)

**Comment by pvanderlinden** [comment]
I even get this problem in single stat panel where the auto decimal decides to display no decimals at all.

**Comment by bfaivre** [comment]
I'm seeing this same issue. It worked as I expected in 4.6.3 for me as well.

**Comment by tonglil** [comment]
I am not sure if I have the same issue or not, but it seems like behavior has regressed since Grafana 4.

<img width="708" alt="image" src="https://user-images.githubusercontent.com/3250776/39219466-77e9e692-47df-11e8-8993-bb89ed74e59f.png">

Decimals are configured to `2`, however the tooltip and the legend both round the value. In Grafana 4, those places showed the value with the same decimals as what was configured for the y-axis.

I know the value is not "1" because when I adjust the scale of the axis, it shows more decimals.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/3250776/39219554-1224558a-47e0-11e8-8b0c-5f9f30b5fa0f.png">

**Comment by torkelo** [comment]
I don’t think there has been a change here, you use auto decimals for tooltip and so the decimals used will be determined y max / min compared with data max / min.

So for example if data max 100 and min 99 and y max / min set to auto the y scale will be from about 98 to 101 so need more decimals to show y axis ticks and legend decimals will use same amount of decimals (in some cases more) . If you set y min to 0 the the y axis will range from 0 to 100 so y axis ticks will need no decimals, legend auto decimals is based on same logic.

There is one minor change here now that I think more closely. Legend is rendered before graph in v5 and some of the auto decimals logic was extracted from graph rendering. So could be a minor difference

**Comment by torkelo** [comment]
we have improved legend & tooltip auto decimal precision in v5.2
