### ISSUE TITLE
Feature Request: Snowflake plugin

### ISSUE THREAD

**Issue by yada-instacart** [grafana/grafana#11587]
Snowflake plugin is currently the main determining factor for us to move ahead with Grafana. Thanks.

**Comment by bergquist** [comment]
We don't have any current plan developing such plugin. 

The company behind snowflake can always develop that plugin. We also provide professional services around creating plugins if that would be interesting for your company. Feel free to reach out to us at hello@grafana.com

I'm closing this issue since any work on such plugins would not be in core Grafana.

**Comment by neilsh** [comment]
I know this request is old/closed, but since Snowflake is accessed via pretty standard SQL, I wonder if just using the PostgreSQL plugin would work.

https://docs.snowflake.net/manuals/user-guide/querying.html

> Snowflake supports standard SQL, including a subset of ANSI SQL:1999 and the SQL:2003 analytic extensions.

**Comment by fhoffa-snow** [comment]
There's an official Grafana plugin for Snowflake now (Enterprise)

https://grafana.com/grafana/plugins/grafana-snowflake-datasource

**Comment by fhoffa** [comment]
There's an official Grafana plugin for Snowflake now (Enterprise)

https://grafana.com/grafana/plugins/grafana-snowflake-datasource
