### ISSUE TITLE
Embedded URL in 5.0 requires dashboard name

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#11617]
Grafana 5.0.3
MetricTank

We are trying to use an embedded URL:
https://grafana.prod.bloomberg.com/d-solo/LPlyrOZmz/machine-view?orgId=1&var-Machine=njlxdev1&from=1523873681815&to=1523916881815&panelId=2

This works. ... however if we strip out the dashboard name it doesn't work.

https://grafana.prod.bloomberg.com/d-solo/LPlyrOZmz?orgId=1&var-Machine=njlxdev1&from=1523873681815&to=1523916881815&panelId=2 

The GUID should be sufficient.

**Comment by torkelo** [comment]
You need something for the slug (name part) does not need to match name.

**Comment by marefr** [comment]
Labeled this as bug due to earlier fix of #11231. Could be nice to make this consistent.

**Comment by marefr** [comment]
Some pointers if someone is interested in fixing this:

Need to add a new backend route for the /d-solo route without slug parameter
https://github.com/grafana/grafana/blob/16b041608d2fd4b3c4e4a8a54332d3ef881dfd7c/pkg/api/api.go#L73

Similar to what exists for the /d/ route:
https://github.com/grafana/grafana/blob/16b041608d2fd4b3c4e4a8a54332d3ef881dfd7c/pkg/api/api.go#L69

Also need to add a new frontend route for the /d-solo route without slug parameter which basically is a copy of this without slug param:
https://github.com/grafana/grafana/blob/16b041608d2fd4b3c4e4a8a54332d3ef881dfd7c/public/app/routes/routes.ts#L73-L84

Similar to what exists for the /d/ route:
https://github.com/grafana/grafana/blob/16b041608d2fd4b3c4e4a8a54332d3ef881dfd7c/public/app/routes/routes.ts#L46

Think this should be enough since both `DashboardPage` and `SoloPanelPage` calls the same `initDashboard` function:
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/containers/DashboardPage.tsx#L80-L89
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/containers/SoloPanelPage.tsx#L42-L50

**Comment by 97amarnathk** [comment]
Hi. I would be interested in fixing this issue. Could this be assigned to me?

**Comment by 97amarnathk** [comment]
@marefr I have submitted a PR for this issue, could you look into it?
