### ISSUE TITLE
Alerting(RED) line should only there in grafana's graph. There should not be OK alert(GREEN line)

### ISSUE THREAD

**Issue by Aravindh-vnix** [grafana/grafana#11621]
I want to send the alert message when failure occurs, but in a graph I want only alert line(red line) I didn't want a green line in the graph. 

I want the only red line in graph(alerting), there should not be a green line in the graph

**Comment by torkelo** [comment]
green line? you mean the annotation events that show when the alert goes from alerting state back to OK? 

Don't think we will add an option for this. Maybe if this feature gets lots of up votes, but your the first in over a year of having the alert feature to come with this feature request. 

Just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
