### ISSUE TITLE
Add last none null option for single stat

### ISSUE THREAD

**Issue by callaway** [grafana/grafana#11659]
Recently switched from tsdb to metrictank and I think there may be an unanticipated interaction with the 'last time of measurement' stat. The data we're using is fairly sparse, perhaps one measurement an hour or even per day. As such the metrictank query returns a sparse array with a substantial number of nulls, including possibly at the end of the series. Example of returned data, artificially setting the number of points to be returned to 10:

datapoints:Array[10]
0:Array[null,1523672640]
1:Array[null,1523733120]
2:Array[null,1523793600]
3:Array[null,1523854080]
4:Array[199983,1523914560]
5:Array[null,1523975040]
6:Array[null,1524035520]
7:Array[null,1524096000]
8:Array[null,1524156480]
9:Array[null,1524216960]

This is true even when querying a very small range. If the native storage of the data is 30 second aggregations, metrictank will return a evenly spaced array with nulls for any 30 second range with no data. 

When displaying time of last measurement, the singlestat panel appears to look at the time of the last returned element in the array,regardless of whether it was null. It would seem that the correct approach - at least for metrictank as a source - would be to display the time of the last non-null observation, or allow the user to specify that behavior.

**Comment by bergquist** [comment]
If all measurements are above 0 you can update your query to something like this `currentAbove(transformNull(...,0),0)`

**Comment by callaway** [comment]
I tried a few variants of things like that and couldn't find on that worked - The one above ends up returning no data at all because the last measurement in datapoints[9] gets transformed to a 0, and then currentAbove() drops the entire series. A transform followed by a removeBelowValue() doesn't work either, because removeBelowValue replaces missing values with null, putting me back where I started.

**Comment by akumar387** [comment]
I was trying to do something **similar** to the OP:
I wanted to display the freshness of the data based on the time it gets inserted in the database.

So when no data is inserted, the data point is NULL along with a timestamp. And on using the single-stat option to display the time **`from Now`** to **`time of last point`** , grafana seems to pick up the last null value (observed using the `query-inspector`) instead of a not null value, thereby corrupting the freshness of the database.
<img width="248" alt="Screenshot 2019-04-25 at 2 33 06 PM" src="https://user-images.githubusercontent.com/48951262/56723721-231e6e00-6767-11e9-905b-258ac2c0e0f8.png">
I tried to get rid of these null-data points using transformNull, currentAbove and other combinations of transformations but nothing seemed to work.

Addition of **`last not null value`** or **`time of last not null point`** feature would really be great.

**Comment by torkelo** [comment]
Can't you filter out the nulls in the query?

**Comment by akumar387** [comment]
> Can't you filter out the nulls in the query?

I tried `transformedNull  0`, then added `>= 0` i.e `removeBelowValue(seriesList, 0)` but the null values in the data-point array doesn't go away.

**Comment by shanson7** [comment]
In graphite, functions that remove datapoints just replace them with nulls, so that doesn't help.

`currentAbove(transformNull(...,0),0)` will completely remove series with latest datapoint of null (or legitimate 0!).

So, either Grafana needs to have an option to ignore the nulls or graphite needs a function/option to return sparse arrays.

Maybe @dancech has insight into the feasibility of the latter option.

**Comment by DanCech** [comment]
Graphite does have a `noNullPoints` parameter for the `/render` endpoint to exclude null points from the output, which is something that we could consider adding support for in Grafana.

The simplest way to get around this today will be to use the [keepLastValue](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.keepLastValue) function to translate the `null` points to have the same value as the most recent non-null point.

**Comment by shanson7** [comment]
`keepLastValue` will not help for `last time of measurement` though, which was what the original complaint is about.

**Comment by akumar387** [comment]
Say the latest is `µ` and all the values henceforth are null, `keepLastValue` turns all the null values from that point forward to `µ`
But this doesn't help with the freshness problem I mentioned earlier since grafana uses the most recent value that arrived to calculate the time using `time of last point` which in this case would time associated with the latest `µ` . 

What I am specifically looking for is to ignore the timestamps of data-points that are null when calculating time using `time of last point`

**Comment by torkelo** [comment]
this is available in new stat panel
