### ISSUE TITLE
dashboard url is changed

### ISSUE THREAD

**Issue by ntting** [grafana/grafana#11666]
Dear grafana teams:

gafana:5.0.1

the dashboard url is: 
https://xxxxxxx-grafana-adve2i-default_space.xxxxxxx.com/d/9z0e1aWmz/desktop-3qk013o-00000001-0000-0000-0000-c400ad02ce8a?orgId=1
 
9z0e1aWmz: Whart 's this?

but when redirect to a dashbaord url, the first is ok, but after a minites, refresh the page in browser,  it show "dashboard not found."

but we can find the dashboard is exist. but open it  from dashboard manag the url is changed,   9z0e1aWmz is changed to another, how to fixed it?

**Comment by ntting** [comment]
I create the dashbaord by the api.

**Comment by marefr** [comment]
> 9z0e1aWmz: Whart 's this?

That's the `uid`of the dashboard, see [documentation](http://docs.grafana.org/http_api/dashboard/#identifier-id-vs-unique-identifier-uid). 

> but when redirect to a dashbaord url, the first is ok, but after a minites, refresh the page in browser, it show "dashboard not found."

Sounds like same issue as #11432 - are you using multiple organizations? Please specify the starting url and then to what url you're redirected.

> but we can find the dashboard is exist. but open it from dashboard manag the url is changed, 9z0e1aWmz is changed to another, how to fixed it?

This sounds very weird - can you please provide detailed steps of how you ended up with this result so that we can try to reproduce it?

Thanks
