### ISSUE TITLE
dashboards export is different than view json command

### ISSUE THREAD

**Issue by albundy83** [grafana/grafana#11704]
Please include this information:
### What Grafana version are you using?
Grafana 5.0.4
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Ubuntu 16.04
### What did you do?
Not working way :
I export dashboards using api (new way with uid from Grafana 5.x)
I manually import then in another grafana instance with 'Load json' command
I don't have any variables (templating)

Working way:
From my first grafana instance, I run 'View json' command, I copy content and I paste it in the second grafana instance. 
Everything is correctly imported 

### What was the expected result?
Export should produce same output than View json command no ?

No specific error is produced

**Comment by albundy83** [comment]
The problem is that is totally break import and export feature

**Comment by torkelo** [comment]
Export UI feature is currently only meant to be used with the import UI feature. 

If you want to use the dashboard save api use the view json view under dashboard settings.

The reason for this divide is unintuitive we know and your not alone in finding this problem, we hope to make this more clear and maybe find some other way to do this I be future. Anyway the reason is the export feature was but for sharing dashboard on grafana.com and that export process adds a bunch of stuff and templetize the json so an import wizard is possible.
