### ISSUE TITLE
Mssql 2008/2008 R2 doesn't work 

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#11707]
From the GO library we’re using in Grafana to connect to MSSQL:

> SQL Server 2008 and 2008 R2 engine cannot handle login records when SSL encryption is not disabled. To fix SQL Server 2008 R2 issue, install SQL Server 2008 R2 Service Pack 2. To fix SQL Server 2008 issue, install Microsoft SQL Server 2008 Service Pack 3 and Cumulative update package 3 for SQL Server 2008 SP3. More information: http://support.microsoft.com/kb/2653857

Add above to msssql docs.

**Comment by DanCech** [comment]
I believe that it's possible to hack around this issue by appending `;encrypt=disable` to the database name in the config, but that only works because we don't do any additional escaping of the database name before putting it into the connection string so not sure whether it's a good idea to recommend it as a solution.

**Comment by marefr** [comment]
@DanCech I don't think so :) We'll update the documentation. It should be a good practice to have an up-to-date database version with latest service packs.

**Comment by marefr** [comment]
Fixed by 79928974186840ebcc89b17f5b545e52f8d6edd8

**Comment by DanCech** [comment]
We should have a way for users to specify additional connection parameters, good practice or not folks do still run old versions of MSSQL and there are plenty of other scenarios where people may need/want to specify additional connection parameters besides just this workaround.
