### ISSUE TITLE
Feature Request: Simplekey option for opentsdb

### ISSUE THREAD

**Issue by HellDesk** [grafana/grafana#1176]
Any chance we can have the simplekey option implemented for opentsdb graphs, the legends get very long in some cases and using simplekey allows you to make them easier to manage.

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
