### ISSUE TITLE
Rotating Panels

### ISSUE THREAD

**Issue by tehdirector** [grafana/grafana#1180]
I have a few dashboards that have a main panel with a graph and smaller panels around it containing graphs/singlestats/html/etc. I would love the ability to have a panel rotate through multiple graphs, similar to the dashboard playlist only at the panel level. So that I can have a single dashboard with both static and rotating(playlist) panels.

Thanks!

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
