### ISSUE TITLE
Remove seconds in grafana table

### ISSUE THREAD

**Issue by mohanraj1939** [grafana/grafana#11837]
Hi all,

Please include this information:
### What was the expected result?
![grafanaerror](https://user-images.githubusercontent.com/33648564/39663172-ebf182fc-508b-11e8-9500-08885169dcbc.png)

### What happened instead?
![grafanaexpected](https://user-images.githubusercontent.com/33648564/39663165-e36c8ac8-508b-11e8-91d4-5d6d80d77ae4.png)

How can i remove the seconds & merge both the time in grafana Table from simple JSON datasource, I'm using webservice to fetch data from Cassandra Db & to display it in grafana table.
 
Sample Grafana Query Inspector:

[grafana response.txt](https://github.com/grafana/grafana/files/1976643/grafana.response.txt)

**Comment by marefr** [comment]
We have support for merging results from multiple queries since Grafana v5.0, see #9170.

Regarding your request for stripping seconds that is something that needs to be implemented in the datasource. I'm closing this since we won't work on this unless it's a very requested feature. If that's the case we will reopen this.
