### ISSUE TITLE
Connected Line Limit

### ISSUE THREAD

**Issue by steve-dave** [grafana/grafana#1183]
@torkelo it would be nice if a connected line limit could be set so that up to x nulls would be ignored, but a gap would be shown in the graph if there were more than x nulls.

I'm not sure how you implement connected line mode in Grafana, but I implemented it in Graphlot by simply dropping null values so it was quite trivial to limit the number of nulls that would be dropped.  Hopefully it is similar for Grafana.  Graphite supports connected line limit so it should not be an issue when using PNG render.

**Comment by eresposito** [comment]
+1

**Comment by jinowolski** [comment]
+1

**Comment by vigne** [comment]
+1

**Comment by PiR43** [comment]
+1

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
