### ISSUE TITLE
Docs: Add breaking change notice on removing `Read Only Editor` role 

### ISSUE THREAD

**Issue by FUSAKLA** [grafana/grafana#11834]
### What Grafana version are you using?
5.1.0
### What did you do?
User tried to log in (has by default assigned role `Read Only Editor`)
### What was the expected result?
He sees the dashboard
### What happened instead?
He gets permission denied

I thought this is a bug but actually found out the role `Read Only Editor` was deleted completely?
Seems to be that way according to the commit
https://github.com/grafana/grafana/pull/10166/commits/357116fd7347d94cd0b97824ced5a805212a2006

I can live with that but I spent long time finding that out and there is no mention in the changelog. Nothing in release notes although this is breaking change and should be stated this way I suppose?

Maybe I just failed searching in that case I'm sorry for bringing this up.

**Comment by FUSAKLA** [comment]
I see there was migration for that
https://github.com/grafana/grafana/blob/35106537f2fbee5fce4e53d7118fc79089902a6d/pkg/services/sqlstore/migrations/org_mig.go#L88

But problem is this could left in user configuration for LDAP where is possibility to state role to assign to user for given organization. This is exactly my issue which is not solved by the migration.

**Comment by daniellee** [comment]
The Read Only Editors role was replaced with the [viewers can edit](http://docs.grafana.org/installation/configuration/#viewers-can-edit) setting that allows all viewers to edit. Does that help in your case?

It should have been in the release notes as a breaking change and I agree - we should definitely update the docs with this information.

Also interesting to know that someone uses the Read Only Editor role (we used it for play.grafana.org). I think you are the second person to complain since we removed it. We reasoned that almost nobody uses it and that this change would not affect many people but as this is open source, you can never be sure.

ref #9653

**Comment by FUSAKLA** [comment]
Great, users can edit seems to be according replacement for the read only editor.

I actually liked the fact I was able to set this per group of users not globally but that is just minor issue. 

I was just suprised by the change. Thank's for the reply and hopefully I'm the last one to use this and brag about it :)

**Comment by marefr** [comment]
Closing this since there's no good place to document it.
