### ISSUE TITLE
Custom legend tooltip

### ISSUE THREAD

**Issue by yarix** [grafana/grafana#11840]
Running Grafana 5.0.4 on RHEL-7 with Prometheus data source.

when plotting a Prometheus metric as graph, the default legend can get cumbersome with all the labels. 
Fortunately,  in grafana we can modify that with "Legend format". However, when doing so the tooltip of the metric also gets changed accordingly and does not provide any 'tip' information.

I find it very helpful to customize the tooltip so it can add extra data to the metric.

current situation: tooltip = legend text:
![image](https://user-images.githubusercontent.com/6409857/39674117-d92e1454-514f-11e8-89df-0d80fad7e0c8.png)

suggested improvement, add customized tooltip format
![image](https://user-images.githubusercontent.com/6409857/39674244-7908ebd8-5151-11e8-92a2-d26d74505405.png)
 
![image](https://user-images.githubusercontent.com/6409857/39674270-f2ffc560-5151-11e8-82b7-b9876a410a8d.png)

the default of the tooltip foramt can be either the legend format (for backwards compatibility) or, if left blank, the entire metric data.

**Comment by zuchy2** [comment]
Running Grafana 5.1.3 on RHEL-7 with Prometheus data source.

![image](https://user-images.githubusercontent.com/40600479/41911523-2df922c4-794d-11e8-9f76-46c2e0b21201.png)

I would like to monitor Kafka lag and see for example just one topic by selecting it from the right list of topic (it can be more then one instance because there can be more consumers (title after "/" ). So I woul like to select topic and see groups which are connected to thist topic in hoover tip inside the graph. So, should be posible to have another title in "Legend format" and create new property to choose another hoover title from the same dataset ? For example: "Legend format" will show RTODS.RTODS.L2.PRODUCT_INSTANCE (3x) and hoover on line in graph will show: console-consumer-67317 or console-consumer-46168 or ipcrs_IPCTB_ha_s_recon_DLK_L2_PRI according to line in graph...

My legend format is now: c / {{consumergroup}}
I would like to have legend: {{topic}}
and hoover: {{consumergroup}}

is it possible ? Or can I ask you for the feature request on this ?
thank you 
Jan

**Comment by lawrenz1** [comment]
This would be very useful because currently we are truncating the label values, but want the expanded label to be displayed in the tooltip.

**Comment by ivanahuckova** [comment]
@grafana/grafana-frontend-platform I am adding this to your backlog.
