### ISSUE TITLE
[Feature request] provision data sources and dashboards from S3

### ISSUE THREAD

**Issue by matthew-hollick** [grafana/grafana#11879]
### What Grafana version are you using?
5.1.1
### What datasource are you using?
graphite
elasticsearch
cloudwatch
### What OS are you running grafana on?
Ubuntu 14.04

We are planning to write a cron job to pull dashboard provisioning files from S3. This made us think that it would be really nice if grafana could pull provisioning files directly from S3.

**Comment by jamessewell** [comment]
This would be really good  - check out Wizzy as a way of doing this in the meantime (https://github.com/utkarshcmu/wizzy), although you'd still need to schedule it.

**Comment by bergquist** [comment]
As much as I want to make it easier to provision dashboards from different sources its an ever ending job to support all cloud storages. I think this should be solved by the operator. There are tons of tools for pulling files from S3 to the local filesystem. 

Closing this since it hasn't got that much attention or contributions yet.
