### ISSUE TITLE
Panel with the ability to aggregate two series.

### ISSUE THREAD

**Issue by PresidentCamacho** [grafana/grafana#11880]
### What Grafana version are you using? v5.0.0

Hi, 

I'm in need of a panel (singlestat would be great) where two series can be aggregated into a single value. 

Take for example a client and a server service. Now I've them in a separate singlestat. But what I would like is to aggregate the values of these two into a single value and show them in a single singlestat. 
This would be great becuse then I can set the threshold so that if either of them are down the whole singlestat will show red. This will save alot of space, and make it easier for the viewer of the dashboard to understand.

Is there something you've already that can do this? Or would you say this is a good function to implement in future updates?

**Comment by torkelo** [comment]
Combining / aggregating series is the responsibility of your time series database (most can do it). For those that cannot we hope to solve it with this feature (in the future), https://github.com/grafana/grafana/issues/3677

**Comment by Sandwichzhao** [comment]
hello torkelo ,
  I have similar question. I have data of two day, I want to compare two day's data trend.Just like “Trend Box” that show current data is increase or decline.My DB is mysql, I can't find suitable plugin , 
because of “Trend Box”  don't work in mysql. Could you help me? or other plugin can help me ？thanks.
