### ISSUE TITLE
Arrows to move forward and backward in graphs

### ISSUE THREAD

**Issue by Claws-** [grafana/grafana#119]
Hi Torkel and thanks for your awesome work on Grafana! One awesome feature would be if there were arrows to move back and forth in time in the graphs, placed on the far left and right.

**Comment by franzgusenbauer** [comment]
+1

**Comment by cemo** [comment]
+1

**Comment by hngkr** [comment]
+1

**Comment by wcombs** [comment]
+1

**Comment by timgriffiths** [comment]
+1

**Comment by dsw6** [comment]
+1

**Comment by mattttt** [comment]
Recently played around with a couple ideas (this is button placement, not fully designed). I was chatting with @grobie at GrafanaCon and it got my brain turning. It needs a bit more design work and thought, but wanted to post it to the issue to keep conversation moving. 

- In this mockup, the secondary time range would control the amount of zoom and lateral movement (1hr, 1day, etc). Functionally it may be useful, but I dont like that it introduces a second time range into the top bar. I find it confusing,
![image](https://cloud.githubusercontent.com/assets/2886187/10638698/285b985a-77da-11e5-8b12-01b9794b1fa6.png)

- In this case, we just set sensible defaults for the zoom and lateral time movement (like it is now). I much prefer this idea, and coupling the buttons. ![image](https://cloud.githubusercontent.com/assets/2886187/10638703/2e40ba70-77da-11e5-90eb-76470bf5eae2.png)

Note:  Because going back in time feels more related to zooming out, the left arrow and minus sign are coupled, and right arrow and plus sign are together.

**Comment by torkelo** [comment]
nice mockups @mattttt , 

I am a little hesitant about adding so many new buttons / icons to the top nav though. Will have to be a very good reason, this might be a good reason but not sure.

**Comment by mattttt** [comment]
@torkelo agreed, but keep in mind that if we do it properly, we're just reclaiming the space (and adding a bit more) that the "Zoom out" text takes, while adding additional functionality.

**Comment by grobie** [comment]
Looking forward to that feature! Thanks for working on it.

In the first version there are a bit too many elements without a clear distinction from it, in the second one I fear it'll become a bit annoying moving forward and backward, as the two button groups are so far from each other.

I guess I'd suggest to reduce the space for the refresh button to `<reload icon> 1m` and show the "refresh every" only in a tooltip?

**Comment by torkelo** [comment]
the refresh interval is very important to have visible, otherwise it is hard to estimate how stale data is on tv displays

**Comment by grobie** [comment]
Sure thing! I only meant to remove the two words `Refresh every` but leaving the icon and the interval information.

**Comment by mattttt** [comment]
`Refresh every but leaving the icon and the interval information`
:+1: 

`it'll become a bit annoying moving forward and backward, as the two button groups are so far from each other.`
This is an excellent point, will continuing thought on this next week.

**Comment by mattttt** [comment]
Another variation, while I'm mucking with it:

![image](https://cloud.githubusercontent.com/assets/2886187/10671855/e958369a-78ba-11e5-9c3f-bed27dbb9db8.png)

**Comment by mattttt** [comment]
Question to the crowd: I'm not convinced that we need these options cluttering the interface, but I'd like to know how important the functionality would be. Is there ever a scenario where you would want control the zoom interval and the forward/backward intervals? Where we'd have an auto detect/best guess mode, but you could override it if you like. 

![image](https://cloud.githubusercontent.com/assets/2886187/10674629/0c1d584a-78ca-11e5-9786-831122a67881.png)

I also propose to extend our keyboard shortcuts to also help you navigate through both zoom levels & time. 

![image](https://cloud.githubusercontent.com/assets/2886187/10674938/89d4396a-78cb-11e5-8d7b-d6c0cc010409.png)

**Comment by mattttt** [comment]
To cap this off for the day, my recommended implementation for starters would be to handle the zoom & fwd/bck intervals automatically for the use (like the zoom is currently), with the addition of a tooltip to show them how much it will be changing. Do not implement the explicit time interval section (see previous comment), unless there is strong demand once the feature is released. 

![image](https://cloud.githubusercontent.com/assets/2886187/10675609/34730d8a-78cf-11e5-8c8a-aa863421e7f9.png)

**Comment by grobie** [comment]
I don't think configuration of the interval is necessary. Having something
like `1/2 * range` (e.g. jump 30m when looking at 1h of data) or just
`range` (jump by 1h when looking at 1h) should be fine I guess.

Keyboard shortcuts sounds awesome!

What I find kind of irritating right now with Grafana and app.raintank.io
is that the time settings are not persisted when switching between
dashboards.  The positioning of the time settings in the header bar kind of
gave me the impression that these are global settings, but they're being
reset every time I open a new dashboard. During outage investigation for
example, it'd be great to easily switch between dashboards while looking at
the same time range. Maybe something to store in cookies or URL parameters?

**Comment by mattttt** [comment]
```What I find kind of irritating right now with Grafana and app.raintank.io
is that the time settings are not persisted when switching between
dashboards...```

Yes! We've started discussing how to address this, but havent started addressing it yet. @torkelo and I will spend some time chatting today before he takes off.

**Comment by dsw6** [comment]
I think the zoom (in/out) feature is less useful than the forward/backward feature.  I find myself setting the time resolution to a value (ex:  15m, 1h, 7d, etc.) and then wanting to scan backward through the data using the same time resolution.  I would suggest leaving the zoom (in/out) feature as it currently works and have the forward/backward feature use the active time resolution.  Users can use the zoom feature to quickly find a reasonable time resolution for the graph and then use the forward/backward feature to move along the timeline using the time resolution.

**Comment by gabrielcrowdtilt** [comment]
Definitely keep it simple. This is something people wanted since Feb 2014, let's just do the fwd/backward arrows.

**Comment by torkelo** [comment]
@dsw6 not sure I agree, I find the zoom feature super useful, use it every time I use Grafana, never had a great need to move backward or forward, usually zoom in by marking on the graph, if I go to far I zoom out. If you have a fast TSDB this just so quick and smooth for me but that is because I use mainly Graphite which is super fast no matter what time range you use (due to rollups and that Graphite will use the right rollup automatically depending on time range)

**Comment by dsw6** [comment]
@torkelo I'm really looking forward to the  forward/backward feature.  I'm not suggesting removing the zoom feature.  I'm suggesting leaving the zoom feature as is and not connecting it to the forward/backward buttons.  Zooming allows you to quickly move to a desired time resolution.  Then the forward/backward buttons allow you to advance the graph along the timeline using the configured time resolution.  The forward/backward buttons simply use the time resolution.  It doesn't matter if you selected the time resolution through zooming or explicitly (ie:  15m, 1d, etc.).

**Comment by utkarshcmu** [comment]
@mattttt, @torkelo I think there is no need for the explicit buttons on the dashboard which are shown in the mockups. Only keyboard shortcuts are enough to move the timeframe of the dashboard and easy/faster to use than clicking so many times on those little buttons.

Right arrow - Move ahead in time for the whole dashboard
Left arrow - Move back by some fraction
Up arrow - Zoom in
Down arrow - Zoom out

Lets keep it simple!!!

**Comment by dsw6** [comment]
@utkarshcmu, I disagree.  I think forward/backward arrow buttons would be very nice and used a lot.  I also think keyboard shortcuts for the functionality would be useful.

**Comment by grobie** [comment]
Keyboard shortcuts are a nice feature, but not very accessible for new users. From all the feedback I got from our developers, not having buttons is a usability problem.

I'm also not sure it's a good idea to use plain arrow keys for time navigation. These keys are already mapped to specific functions in most browsers (scrolling around, etc.). Ctrl+arrow keys seems to be a safer choice as an example.

**Comment by mattttt** [comment]
Yep, dropping the buttons entirely is a non-starter in my opinion - people need to learn that the behavior exists before they can become power users. 

As for hijacking existing keyboard conventions, that's an interesting thought. Up and down are spoken for on long dashboards that need to scroll but left/right is interesting. There are a number of sites that do it gracefully (think left/right arrows to scroll through a photo album on flickr, etc), and perhaps something worth exploring. Especially since a dashboard is always full-width, you dont have side scrolling. I think I'd opt to go with a key combos like @grobie suggested, but that has its own drawbacks: Shift + L/R currently expands text selection by a character, Ctrl+Arrows on a Mac switches desktops :frowning:. 

Ultimately, this will be solved by prototyping and testing - and we can easily switch the shortcuts once the functionality is in place.

**Comment by andrewpwade** [comment]
+1. I'd love to see the backwards/forwards functionality implemented (buttons would be fine)

**Comment by sslupsky** [comment]
+1 for forwards and backwards function.

@torkelo I like to zoom on the time axis as well.  Anyway to implement a zoom on the y-axis?  That would be super helpful.

**Comment by alokdhir** [comment]
+10

**Comment by utkarshcmu** [comment]
@dsw6 I hope my PR #4597 does what is required in this feature request. Key points are listed in the PR.

**Comment by dsw6** [comment]
The work looks great.  I'm looking forward to using it.

**Comment by opentokix** [comment]
I would like to extend the functionality to be able to automatically refresh and step around a time, let's say last 24 hours in 30 minutes intervals. 

Especially useful when you have data mapped and color-coded on a world map, to see changes over time, last 24h, last week or similar.

**Comment by mr-manuel** [comment]
Was this feature removed again? Can't find it in version 8 and 9 (still beta).

**Comment by bluegaspode** [comment]
After reading through all these ticket (and the current docs ... https://grafana.com/docs/grafana/latest/dashboards/use-dashboards/ ) , I also cannot find  the feature anymore.

Has it been removed and replaced with something different?
Or is the feature removed alltogether?

I have a daily view of some chart, which is the perfect zoomlevel for investigations, and would love to have an easy way to now step through the last 14 days with this zoomlevel.

**Comment by bluegaspode** [comment]
To help those, that are as lost as I am, ChatGPT could point me to: https://github.com/grafana/grafana/issues/13687

So the buttons are still there, when you explicitly set an absolute time range. They are invisible when using the "default" relative time ranges. 
The keyboard short cut "t" + "left/right arrow" also helps. If you just hit it once, the timerange is set to an absolute range and you can either then use the buttons or continue using the shortcut.


This detail is not obvious by just reading the documentation.
