### ISSUE TITLE
Data is plotted and returned from Query inspector but not showing in Legend and Tooltips when string values

### ISSUE THREAD

**Issue by andrewllyons** [grafana/grafana#11900]
What Grafana version are you using? 
v5.1.2

What datasource are you using?
InfluxDB

What OS are you running grafana on?
CentOS 7

What did you do?
Upgraded our Grafana instance from v4.3.2 (commit: ed4d170)

What was the expected result?
Graphs are displayed correctly

What happened instead?
Graph data is being plotted as expected, however the values are missing from the legend and tooltips. Using the query inspector I can see the data.

If related to metric query / data viz: (commented out fields for privacy)

![image](https://user-images.githubusercontent.com/24909865/39860748-d30b179a-5481-11e8-9949-0b78bd65cd48.png)
![image](https://user-images.githubusercontent.com/24909865/39860911-58c36ce8-5482-11e8-91bd-7bc5c6d75d11.png)

**Comment by andrewllyons** [comment]
To compare here is the data that shows in our previous version (v4.3.2 commit: ed4d170)

![image](https://user-images.githubusercontent.com/24909865/39861814-28bcf52a-5485-11e8-8b15-c064cfc84dc5.png)

**Comment by yellowpattern** [comment]
grafana seems to have a problem graphing data when you use group by time and use an aggregation function such as "mean()". If you are using group-by-time/mean(), try removing them.

**Comment by andrewllyons** [comment]
For some added complexity, here's the data showing using a table panel instead of a graph panel with all the values there. The where clause is just selecting a specific tag and the group by is on that tag
![image](https://user-images.githubusercontent.com/24909865/39983953-d7aa95b4-579c-11e8-83ef-0c8462eee728.png)

**Comment by andrewllyons** [comment]
Figured out the issue, still seems like a bug (or maybe undocumented deprecated functionality?). The data type that this is stored against in InfluxDB is string, however it appears that Grafana does not show strings in the legend/tooltips whilst the Graph does interpolate this data. It's possible that there's a missing data conversion in the tooltips/legend code sections.

**Comment by daniellee** [comment]
@andrewllyons I'm surprised anything works at all if the value is a string (for example < and > in the where clause don't work with string values). So I think it is mostly luck that the Graph panel managed to plot something.

I guess this is a feature request for Grafana showing an error when attempting to use string values in the Graph panel?

**Comment by andrewllyons** [comment]
@daniellee My guess situates more around string interpolation, my guess is the graph panel has an explicit cast to float/int whereas the the legend/tooltips is missing that. It's an interesting problem which could be resolved by either:
* Casting all field values that are castable (Looking at you tryparse)
* Throwing an error when trying to plot on string values

**Comment by caitocrd** [comment]
Hi, I am using the same configuration and I have the same problem. The graphics are correct, but the values are not shown in the legend. Alerts do not work, they can be configured but they do not have data. If someone can give me an idea of what happens ... thanks

![screenshot 14](https://user-images.githubusercontent.com/40466262/41724092-25257e12-7543-11e8-8102-c23265676070.png)

**Comment by ch3paz** [comment]
Seems to me this problem is still existing (Grafana v6.5.1):

![grafana_legend_query_inspector](https://user-images.githubusercontent.com/3217661/70862368-c3feab00-1f3b-11ea-9de7-c1f21448cc7e.png)

**Comment by kubark42** [comment]
This is a terribly annoying issue and huge debug timesink because of the half-implemented function. I would argue that EITHER Grafana refuses to plot strings OR it keeps its behavior to plot strings and gives a status warning anywhere where it cannot show a value. To sit on the fence makes it look like a Grafana problem, either with the user's query or with a Grafana bug. In reality, the problem is upstream with the schema.

In a perfect world, it should just refuse to plot the string in any context, unless specially asked. This would allow people to catch incorrect schemas earlier in the development process. In this case, I wound up helping a friend whose database was misconfigured for years, and she had never dived into why the graphs weren't working. She simply accepted that it must have been her fault when in fact I was able to demonstrate it was a third-party providers fault in the way it feeds data to influxDB.

In a more global context, it is devilishly difficult for a novice user to figure out what is going on. Even the query inspector is almost negative work, because it confusingly shows string values as floats, i.e. `Array[157639005200, 14.7]` should appear as `Array[157639005200, "14.7"]`. Otherwise, it reinforces to the user that the values are proper numbers and not strings.

**Comment by gabor** [comment]
hi @andrewllyons , @caitocrd , @ch3paz , @kubark42 this issue was opened a long time ago, with a long discussion, and i'd like to confirm i understand the root problem before coming up with a solution. is the problem the following?

when numeric data is stored in influxdb in string-fields, and then queried in grafana, they can be graphed, but many other operations (alerts etc.) fail.

**Comment by ch3paz** [comment]
> when numeric data is stored in influxdb in string-fields, and then queried in grafana, they can be graphed, but many other operations (alerts etc.) fail.

Yes, that was the case for my installation. As i've changed then the type of the field in influx to float (iirc that correctly) i don't longer had this problem.

**Comment by gabor** [comment]
so this "functionality" (that you can graph numbers-stored-as-strings) only works accidentally and it is not something we support. there are some planned changes to how influxql queries are handled in grafana internally, and after those changes this will stop working completely, and will not cause confusion to users.
