### ISSUE TITLE
[Feat Req]: Disable stacked percent series for individual series

### ISSUE THREAD

**Issue by theomega** [grafana/grafana#1191]
If you have multiple series and want all but one of them stacked, percentaged on the left scale and the one remaining series on the right axes, non percentaged, this is not possible. 

Setting "Stack: false" using the "Series specific overrides" doesn't change anything...

Version 1.9

**Comment by ChemicalNovae** [comment]
+1 for this!

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.

**Comment by xhook** [comment]
+1
