### ISSUE TITLE
Connecting to MySQL Datasource using SSL TLS 1.2

### ISSUE THREAD

**Issue by Ajaysrndpt** [grafana/grafana#11924]
We are planning to connect to MySQL DataSource from Grafana using SSL but we are facing few challenges.

Just wanted to confirm if the SSL Connection is supported in Grafana for MySQL Datasource

I do see some settings in configuration file

For “postgres”, use either “disable”, “require” or “verify-full”
For “mysql”, use either “true”, “false”, or “skip-verify”.
ssl_mode = true

I hope this is related to the Internal DB if i am not wrong.

Need help on this

**Comment by Ajaysrndpt** [comment]
Hi All

Any update here will be helpful?

Thanks
Ajay

**Comment by marefr** [comment]
If you're referring to the internal Grafana database then there's some support for SSL using mysql. This issue #2998 fixed that. However there's another open issue #8570. Closing this since this may answer your question and/or it's the open issue you want to focus on. Reconsider open this again if you should have any other issue than the referred open issue.

In the future please search existing open/closed issues before creating an issue and please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

**Comment by peregrinius** [comment]
No this is a different issue. @Ajaysrndpt is referring to being able to set SSL mode in a connection string to a MySQL datasource. Not the same as #8570 which is specifying a CA file for SSL.

As pointed out other database Data Source options (Postgres/MSSQL etc.) offer this option. e.g.

![image](https://user-images.githubusercontent.com/5101137/61640021-e3e7b680-ac9c-11e9-9f07-2fef9233b0d4.png)

**Comment by marefr** [comment]
@peregrinius would suggest you open a new issue. Thanks

**Comment by peregrinius** [comment]
Thanks @marefr I was using an Azure MySQL database. The solution was to use a CA certificate that they provide in the documentation here: https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl

I also looked into the source code of the mysql library you use in grafana and it looks (from my limited knowledge of Go) that they don't provide an SSL option anyway.

**Comment by marefr** [comment]
@peregrinius just use the `With CA Cert` option:

![image](https://user-images.githubusercontent.com/1668778/62495308-cc98e500-b7d5-11e9-9f4b-8d863a5ce7ef.png)

**Comment by peregrinius** [comment]
when doing this I was given the error:
Metric request error

Until I provided the CA certificate
