### ISSUE TITLE
SMTP still not working

### ISSUE THREAD

**Issue by ShaunMaxwell** [grafana/grafana#12014]
### What Grafana version are you using?
v5.1.3

### What datasource are you using?
N/A

### What OS are you running grafana on?
Running the docker image in Kubernetes.

### What did you do?
Invited a new user.

### What was the expected result?
The new user should receive an email.

### What happened instead?
UI says invite sent successfully. Logs say:
```
grafana t=2018-05-21T11:35:52+0000 lvl=eror msg="Async sent email 0 succeed, not send emails: xxxxx@xxxxx.com err: 454 4.7.0 TLS not available due to local problem"
```

**Comment by daniellee** [comment]
> 454 4.7.0 TLS not available due to local problem

This is something to with your tls config either on Grafana or your mail server.

Can you provide more details:
- What are your [smtp settings](http://docs.grafana.org/installation/configuration/#smtp) in the grafana ini?
- Can you see what the real error (the "local problem") is on your mail server?
- Are you using STARTTLS instead of TLS?

You can also try setting the [log level](http://docs.grafana.org/installation/configuration/#level) to debug to see if Grafana returns more information about the error.

**Comment by ShaunMaxwell** [comment]
So no TLS should be used at all.

My SMTP settings are:
smtp_enabled: "true"
smtp_host: "smtp.inernal_domain:25"
smtp_skip_verify: "true"

I've also tried without skip verify.

The logs on the SMTP server show Grafana attempting to use STARTTLS despite no TLS being set up.
```
lost connection after STARTTLS from unknown
```

There aren't any other useful logs.

**Comment by daniellee** [comment]
@ShaunMaxwell skip verify is for self signed TLS certs -> it skips verifying that the cert is trusted by a CA.

It seems like your smtp server is trying to upgrade the connection to TLS with STARTTLS. Can you turn that off on your SMTP server? Or even better would be to use TLS.

ref #7189

**Comment by ShaunMaxwell** [comment]
Issue resolved by switching to an SMTP server that uses TLS
