### ISSUE TITLE
[Feat Req] Option to allow series not influence Y-axis scale

### ISSUE THREAD

**Issue by vthriller** [grafana/grafana#12067]
Basically what I want is to make select time series to behave like thresholds upon rendering.

Why can't I just use thresholds in the first place?

- **Thresholds can't be defined through queries, only constant values.**
- Threshold appearance options are limited, e.g. I can't make them dashed.
- Thresholds cannot be named (sure there are alerts, but they are even more limited, and I don't want to use Grafana for alerting).
- There are no hover tooltips for thresholds.

Trivia:
- Grafana version: 5.1.3
- Datasource: Prometheus
- OS: Linux

**Comment by danielmotaleite** [comment]
i too use series as thresholds, mostly because i get then through queries too.
Having a hardcoded value in grafana means that every time we change the software config, we have to remember to switch the grafana threshold. Having it as dynamic helps a lot... but the problems is it screw the Y axis.

So it is probably easier to set a new way to disable Y axis scale than redo the threshold to accept dynamic values and configs
