### ISSUE TITLE
"Grafana Admin" permission at LDAP-User is ignored

### ISSUE THREAD

**Issue by anthraxn8b** [grafana/grafana#12258]
### What Grafana version are you using?
Grafana v5.1.3 (commit: 087143285)

### What OS are you running grafana on?
Default docker image.

### What did you do?
Adding the "Grafana Admin" flag and updating the user as the global default admin in the UI.
After logging out an logging in again as the global default admin the LDAP user still has the "Grafana Admin" flag set.
After logging out and logging in with the LDAP user the LDAP user has no admin permissions at all.
After logging out and logging in again as the global default admin the LDAP user still has the "Grafana Admin" flag set.

### What was the expected result?
The LDAP user should have the "Grafana Admin" permissions.

### Additional info ###
I do not use LDAP for group/org assignments!
These sections have been removed from the toml file!
Assigning org-roles to LDAP users works.

**Comment by torkelo** [comment]
Admin permissions in per org level is different than server admin, remove group mapping’s from your ldap toml config if you want to manually control ldap user permissions.

We have fixed a bug in master that I think is present in latest stable that if you are Grafana admin and not admin role in current role you do not get the cog wheel sidemenu to access server admin pages, this is fixed in master I think

**Comment by torkelo** [comment]
sorry, noticed now that I mentioned that the group section was removed. In that case make sure you also set org role using the default admin user, then try to login with the ldap user.
