### ISSUE TITLE
"General" folder permissions

### ISSUE THREAD

**Issue by daldoyle** [grafana/grafana#12327]
### What Grafana version are you using?
5.1.3

### What OS are you running grafana on?
CentOS7

It would be really helpful to be able to change the permissions on the "General" folder. Our use case involves supporting both anonymous and logged in access to a set of dashboards. A "Public" folder has been made that is Viewable by anyone, and a number of other folders exist with various permissions for logged in teams.

The challenge is that all new dashboards by default go into "General" which is always viewable by all. This makes it prone to human error and saving something in the wrong place. Being able to lock down "General" would help with this and make it work just like other folders instead of being an exception.

**Comment by marefr** [comment]
Not sure I understand this. You can enable anonymous access for a Grafan instance and/or for specific organization. If you only want to expose certain dashboard to anonymous users, please setup specific organization for this use case. See http://docs.grafana.org/installation/configuration/#auth-anonymous.

Or am I misunderstanding something?

**Comment by daldoyle** [comment]
Hi Marcus,

Thanks for the quick reply. Maybe a broader view of this would be to make the General folder less special. Unlike any other folders it currently cannot be renamed, it is the default setting automatically for any new dashboards, and it cannot have its permissions changed.  Being able to change any one of those attributes I think would allow this use case.

We looked into the organization approach but it was considered confusing by our users, particularly the ones who would need to jump to different organizations for different data sets. If we could reference dashboards in multiple organizations that would probably solve that, but as it stands some amount of the dashboards would need to be copied and maintained as duplicates which is undesireable.
 
If this is too niche a use case or otherwise too hard to implement we can probably figure out some way to keep dashboards synchronized as duplicates, but I figured it was worth bringing up as a general request.

**Comment by marefr** [comment]
Thanks for your feedback.

> Maybe a broader view of this would be to make the General folder less special. Unlike any other folders it currently cannot be renamed, it is the default setting automatically for any new dashboards, and it cannot have its permissions changed. Being able to change any one of those attributes I think would allow this use case.

Understood. The general folder is special by designed because we needed that to behave the same as before Grafana 5 to be backward compatible and by that always making sure that there exist a folder to put a dashboard in and for those not want/need to use folders doesn't have to do any additional step for creating a dashboard. I can definitely understand need of renaming General folder, but regarding permissions I think we're looking at this from opposite angles.

A common setup for your use case is to give users organization role=viewer and then in certain folders assign them editor/admin permissions. Then they can only create dashboards in their folder where they have editor/admin permissions. Grafana v5.2 stable (not released yet) includes a lot of enhancements for supporting this setup better.

**Comment by azhiltsov** [comment]
Here is a different use case to support the idea of 'Editable General folder'.
We make all users as Editors by default.
We would like to allow Anonymous access to grafana.
At the same time we want to disable Viewer permissions for General and make it disabled by default for newly created folders as well.
By doing so Editors would need to make dashboard or folder explicitly available to Viewers in order to allow anonymous access to it. 
Anonymous can be considered as a dashboard/kiosk user here.

**Comment by 4orty** [comment]
@alexanderzobnin 
You marked this issue as completed, but where can i see related PR or changelog?

**Comment by ag0n1k** [comment]
@alexanderzobnin 
The same question. Can we edit the General folder permissions or not?
