### ISSUE TITLE
How to combine multiple field/column/metric values

### ISSUE THREAD

**Issue by danciugaby** [grafana/grafana#12324]
Hi, 

I am using Grafana 5.0.4 on Windows 7.
I have encountered the same issue using InfluxDB, ElasticSearch or MySQL:

Regardless of the used data source I find impossible to combine several field values.
For example the auto-generated query for InfluxDB is this:

"SELECT 'a' as 'a', 'b' as 'b', 'c' as 'c' from 'autogen'.'data' WHERE $timefilter"

Although I can aggregate on each individual indicated field (sum, mean, etc), I cannot combine the two or three columns into one. 
For example I would need a fourth column d = ('a'+'b'+'c')/3.

Yes, I am aware that one can have that "d" field,  as a predefined column (pre-computed) in the datasource (i.e. create a temporary table/result set, with that new column d computed as one needs to).

This is not a solution, since there are many new formulas I need to compute daily, this implies the existence of many columns that I have to create in the original data sources, so this has to be done on client side.

Has Grafana a solution for that? or maybe another workaround for the client-side?

Thanks,

G

**Comment by torkelo** [comment]
This is mainly a frustration on the poor query languages these time series databases use, in some others these operations are supported and easy to use (Graphite, Prometheus), so think this does need to be fixed in the database layer (InlfuxDB query language). or via Grafana meta queries (proposed feature) https://github.com/grafana/grafana/issues/3677

**Comment by onitake** [comment]
I rather think this is a limitation on the way the Icinga InfluxDB writer stores performance data and less a limitation of the query language.

Admittedly, if Influx "SQL" was less limited, it might be possible to combine the data, but if Icinga stored the values as a single record instead of separate tag:"metric" field:"value" tuples, we wouldn't have this issue in the first place. I had the impression that it is well within InfluxDB's capacity to store multiple "fields" in a record.
