### ISSUE TITLE
annotation toggle not properly synced with graph rendering

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#1235]
it often happens when i click to disable annotations that they still stay, or that when they're off and i toggle them on, the new graph still doesn't have them. seems like the rendering of new graph is not properly synchronized to the annotations-loaded event ?

**Comment by gitRahul** [comment]
@torkelo  I'm having similar issue with annotations, I'm using inluxDB. Adding annotations makes the dashboard slow, it takes 10-20 seconds to render all the graphs with annotations. Also if you pick refresh every 5s or 10s, the whole dashboard comes to a crawl and becomes unusable because for each refresh the annotations take upto 20 seconds to render.

Also great work by the way on grafana

**Comment by gitRahul** [comment]
never mind, I think it was slow because I have like 40 graphs on the dashboard and not because of annotations in particular.

**Comment by torkelo** [comment]
@gitRahul well you are correct (sort of), the rendering annotations can be really slow if you have ~100 more annotations
