### ISSUE TITLE
Preload data for next playlist dashboard before switching to it

### ISSUE THREAD

**Issue by weyrick** [grafana/grafana#1236]
We're trying out playlists and we've noticed that when it switches to the next dash in the playlist, it loads all the graphs all _after_ displaying the next dash. If there's a lot of data to load, this winds up showing a lot of spinning graphs and if the playlist interval is short, this happens frequently. 

It'd be great if it preloaded the data for the next dash in the playlist before switching to it, to avoid the spinning.

**Comment by w495** [comment]
But, I need it, too.

**Comment by andrea-borraccetti** [comment]
up

**Comment by SteffenNiemann** [comment]
We have operational data for different teams beeing displayed on one large screen, so that all team members can see it. For every team we have a specific dashboard that is displayed. The dashboards change every 20 seconds. The fact, that the dashboards are not preloaded causes flickering, which is a disturbance for workers. This is a very usefull feature for operations.

**Comment by RonaldFindling** [comment]
We have a similar usecase with operational data as described by @SteffenNiemann . Getting rid of this flickering would be very useful

**Comment by neilus** [comment]
+1

**Comment by nickper** [comment]
+1
