### ISSUE TITLE
Feature Request: add  a "Latency Time" to avoid  "last null values when non existent values found".

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#1241]
Could be interested  add a new parameter "Latency Time "   (config as 0 by default ).
This new parameter will force all query's to graphite done until "now - latency_time" ( when now selected, to advance de "now" time) , avoiding the last null values that have not yet collected and stored on the graphite backend.

**Consider use case:**

We are monitoring with "isNonNull()" graphite function the state of certain group of machines ( each group with 6 servers)

![image](https://cloud.githubusercontent.com/assets/5883405/5456532/7e15b00c-8544-11e4-8be8-631027e7a7e1.png)

by querying if cpu-state metric exist:

```
groupByNode(isNonNull(XXX.XX.*.*.*.system.cpu.percent-active), 3, 'sum')
```

And monitoring with single stat panel ( value shoud be OK=6 NOK<6) 

![image](https://cloud.githubusercontent.com/assets/5883405/5456554/ac95fc84-8544-11e4-85ea-ec0a6ff20464.png).

This stat panel shows ERROR **but servers are really ok**, the matter is in the last values not yet reported by graphite. 

![image](https://cloud.githubusercontent.com/assets/5883405/5456817/8982e610-8546-11e4-999b-df081e7842f1.png)

If we could configure a Latency (On Our platform we could configure 3 minutes as "Latency Delay Time") in most of cases will be enough to get "null values when non existent values found".

What do you think about?

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/5888268/5fdbbc58-a3f8-11e4-90c8-9107631bfee6.png)

I have taken a stab at this, I tried first adding it as a datasource option in the metrics tab, but did not like that. It feels better to have it in the time picker so that it is the same for all graphs on the dashboard. 

It might be hard to solve this in a simple way for all scenarios but cannot make everyone happy all the time :( 

The way it works is that in the timepicker options (under dashboard settings) you can specify a now delay. So if you put in "1m", and the select Last 15m from the timepicker the time range will be from: now-15m  to:now-1m

**Comment by toni-moreno** [comment]
Great !!!!!

Thank you very much @Torkelo  !! I will make a package from master  and test it monday morning !!!

**Comment by JeremyMorton** [comment]
Might it be better to have the now delay be an offset to both the start and end of the time range? Then it still shows 15m for example, from now-16m to now-1m, or, as another example, it would still show 1 whole hour: from now-61m to now-1m.

**Comment by torkelo** [comment]
Fixed in , https://github.com/grafana/grafana/commit/b940f4a97d7a849371bfb5345c1e8617140f26c7
