### ISSUE TITLE
Graph histogram bar height is over high.

### ISSUE THREAD

**Issue by SongYg** [grafana/grafana#12431]
What Grafana version are you using? v5.1
What datasource are you using? InfluxDB
What OS are you running grafana on? Ubuntu 16.04

When I drew a histogram with graph bar and X-Axis mode as Series, I got a bar whose height was over the Y-Axis value visibly.
<img width="960" alt="2018-06-28_105055" src="https://user-images.githubusercontent.com/13520404/42010463-4cbbeb36-7ac1-11e8-8840-d3a506e8a965.png">

**Comment by torkelo** [comment]
This is a due to a bug/limitation in the y axis tick selection when you use a non metric y axis unit (think the data IEC ones are the only ones that use non metric y axis ticks). 

There is a bug report for this but not easy to solve. 
https://github.com/grafana/grafana/issues/8957 

A temporary workaround is to switch to metric data units.
