### ISSUE TITLE
[bug] Table:  absolute url problem in Link

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#12448]
### CentOS

The absolute url in the Link field is wrong after the v5.2.0 update.
This was still good in the previous 5.1 version.

See the example:
https://snapshot.raintank.io/dashboard/snapshot/vs7pdvrVN9mFLTmxVTDZ03LVJs6c5Z5I?orgId=2

Please, repair it. Thank you!

![2018-06-28 21-06-27](https://user-images.githubusercontent.com/2911588/42056226-f21a0416-7b19-11e8-8bfd-75ed965d74bf.png)
![2018-06-28 21-06-24](https://user-images.githubusercontent.com/2911588/42056228-f2397c74-7b19-11e8-8573-50be624a32ed.png)

**Comment by torkelo** [comment]
We need the ${__cell:raw} syntax as by default variables will be url encoded, so this edge case when the cell value is a full absolute url we need the raw format. 

Try using `${__cell:raw}`  , it should work

**Comment by nthienan** [comment]
It should be noted in help.

![image](https://user-images.githubusercontent.com/10244759/42303455-05635926-803f-11e8-8f2f-540544099de1.png)

**Comment by sanchomuzax** [comment]
It worked earlier. But now it does not work. 😢

**Comment by geoff-va** [comment]
### Grafana v5.2.2

### Ubuntu 16.04.2 LTS

### MySQL DB

I'm unable to get this to work using the following syntax in the link url for a table cell:
`https://my.site.com/whatever/some_dashboard?var-my_var=${__cell_4:raw}`

The value in `__cell_4` is: `some+variable`

The `some+variable` is displayed properly when I hover over the table cell or copy the link, however, when I click the link the `+` is always replaced with a `%20` (space) in the address bar. This causes my MySQL queries to fail because it's searching for `some%20variable` instead of `some+variable`.

I've tried this in Chrome, Firefox and Safari and get the same results in each.

I've tried using `$__cell_4`, `${__cell_4}` and `${__cell_4:raw}` but all yield the same results.

**Comment by marefr** [comment]
Fix will be included in Grafana v5.3 stable. Looks like this in master right now

![image](https://user-images.githubusercontent.com/1668778/46086047-9f3bdd80-c1a7-11e8-80a8-5ba27c5422b9.png)

**Comment by volter** [comment]
Thank you!
