### ISSUE TITLE
HA: Multiple grafana instances operate same DB causing confliction

### ISSUE THREAD

**Issue by CrazyNash** [grafana/grafana#12473]
Please include this information:
### What Grafana version are you using?
the latest.

### What datasource are you using?
mysql

### What OS are you running grafana on?

centos

### What did you do?

Set up HA grafana

### What was the expected result?

it works

### What happened instead?

db opertation conflicts.

After DB was created, then start up two grafana instances, and noticed from log, each instance starting to run migrator, and at some point, failed for confliction, eg XXX_index already exists, what's the recommended setup in the scenario? is there a way to skip DB migrator, or is there a way to just let one instance to operate DB?

Thanks!

**Comment by torkelo** [comment]
The migrations run in transactions so this should not happen, but must be an issue with the migration log and HA. Strange that this has not happened before as ha setups are super common, must be due to some very unfurtunate timing when two instances start at the same time. But should definitely not happen at all

**Comment by marefr** [comment]
Mysql doesn't support transactions for schema changes so that's probably why. In HA setup and upgrade I would recommend to shut down all instances besides one and upgrade the remaining.

**Comment by marefr** [comment]
Closing this in favor of #11090
