### ISSUE TITLE
[Feat] Expose folder uid in dashboard meta for GET dashboard

### ISSUE THREAD

**Issue by Pwalne** [grafana/grafana#12491]
In a attempt to move copy dashboards from a development environment to a production environment we have come up with our own script to export / import via the HTTP endpoints.

There seems to be a issue with getting the Dashboards into the right folders, if the folder exists (and is the same id) it will work fine. But that is not the case if the folder does not exist, even if you specify a id & uid that is not already taken.

How to reproduce:

1. Create folder
2. Create Dashboard (Place it in the previous folder).
3. Export dashboard.
4. Export folder through HTTP endpoint
5. Remove folder.
6. Using HTTP endpoint, create new folder with previous export.
7. (Folder id has now changed, even when stating no override & giving a id / uid).
8. Try to import dashboard with it in folder, the dashboard will be placed in 'general'

This makes it difficult to make sure that dashboards being imported go in the correct folder. There is a uid field on the folder, why not link it like that?

**Comment by marefr** [comment]
That's a valid feature request.

If possible I would suggest you to use the [provisioning](http://docs.grafana.org/administration/provisioning/#provisioning-grafana) feature which has support for placing dashboards in correct folder between environment.

**Comment by Pwalne** [comment]
In the 'meta' of a exported dashboard json, there is the folderId, (You can also add folderId outside of the .dashboard property to add it to a certain folder). The problem is that when importing a folder via the http API, it doesn't retain it's id, and therefore becomes out of sync and requires manual intervention.

The proposed solution would be to change the way dashboards are linked to folders to use the folders uid which is already present, thus allowing persistent imports without manual intervention to reFolder dashboards.

**Comment by marefr** [comment]
Nothing stopping you from looking up the folder by id when exporting a dashboard and saving a temporary reference, then when creating the folder in new environment add mapping of the temporary reference and change the folder id before importing a dashboard to put in the correct folder.

I would recommend the provisioning feature if you want to do as little manual intervention as possible.I would keep this open for a while and see if it gets upvotes, then maybe we consider this feature.

**Comment by cdelmas** [comment]
Hi, I have the same need (I'm using Terraform with the Grafana provider to import my dashboards).

**Comment by PaulW** [comment]
I would also like to specify the UID for the folder when provisioning dashboards.

**Comment by marefr** [comment]
@PaulW could you please open a separate feature request for that. Thanks

**Comment by SamuelToh** [comment]
Parking my name here. Might take a look at this once all of my other pull requests have been resolved...

**Comment by gailane** [comment]
Dealing with the same issue, is there any intention to add this feature? Seems like a serious design flaw in the API, or a detail that must have been overlooked. The HTTP API documentation specifically states that the entire purpose of the UID is to make syncing the installs easier. Why on earth would you decide NOT to use the UID to specify a folder, and instead bind folder mapping to an ID that can't be user-modified or supplied? 

Provisioning the dashboards is not a blanket solution; it simply won't work in our use case as we use provisioned dashboards for a specific use case. I spent a few days writing a tool for this and now my work is wasted because I overlooked the folder UID issue. I had the original folder ID, UID, and title added to the JSON payload but no matter what I try, I just get "Failed to create dashboard". I've checked and there's not a single tool available to manage this process. So instead of just creating the folders and dashboards via the API using saved JSON files, I've got to create the folders and then run a separate script to update the folder UID in each dashboard JSON file to make this work.

**Comment by marefr** [comment]
@gailane not sure I understand everything you're describing. But if you use provisioning you can set the folder that dashboards should be provisioned to using folder title and folder uid in the dashboard yaml file, see https://grafana.com/docs/administration/provisioning/#dashboards for reference.

**Comment by mindw** [comment]
@marefr Thanks for pointing that out.
Provisioning is performed only at start-up (according to the link above). This implies grafana needs to be restarted for the above to take effect. 
It seems very odd that uid of folders is missing from the API but present in provisioning (unlike dashboard UID which is available in both).

**Comment by gailane** [comment]
@marefr We have a strict policy for using provisioned vs. non-provisioned dashboards. We have  many dashboards and we can only provision about 10% of them. For the other 90%, we needed a tool to regularly back them up and restore them if needed to a fresh grafana server. We have several environments we keep in sync and I just got really frustrated trying to make this work. After discussing this with my team, none of us could understand why the Grafana API docs mention the importance of a UID when really that only matters for provisioned dashboards and folders. For non-provisioned dashboards and folders, the folder UID couldn't matter less, since it's useless in the Dashboard HTTP API. Instead, I had to rewrite my restore tool to create the folder via cUrl, store the new ID of the folder in an object, using the old ID as the lookup key. Then when creating the dashboards via cUrl, I modify the JSON inline by replacing the old ID with the new one. This doubled the lines of code I needed. Admittedly, it is my fault for overlooking this detail, but the Grafana docs emphasize the importance of the UID to facilitate keeping multiple Grafana servers in sync. But when you create a new dashboard via HTTP API, you can't use the folder UID. You must use the folder ID only.

Provisioned dashboards are great but they don't work for everyone. Grafana doesn't have a lot of tooling which means your users have to write their own automation. We have so many dashboards and users in our case that we needed to ensure non-provisioned dashboards were first class citizens alongside the provisioned dashboards.

**Comment by M0rdecay** [comment]
That would be very helpful

**Comment by marefr** [comment]
For now, have you considered using the [dashboard search API](https://grafana.com/docs/grafana/latest/http_api/folder_dashboard_search/) instead?

**Comment by cr-lironkreiss** [comment]
Hello,

Is there any update here? I need the same feature- I wanna use the API to import dashboard to a specific folder.
Thanks

**Comment by marefr** [comment]
@cr-lironkreiss Since you're using the API you can workaround this. Lookup folder by uid to get the folder id and use that when saving dashboard.

**Comment by cr-lironkreiss** [comment]
@marefr thanks for the reply.
I know what's my folderId, I'm using the /import and I tried to give it as a param and also inside the json (as "folderId") key and it didn't work.
Can you elaborate on your suggested workaround?

Thanks.

**Comment by marefr** [comment]
@cr-lironkreiss the /import api is specifically to be used from Grafana UI when importing dashboards. Would suggest you use the [create/update dashboard api](https://grafana.com/docs/grafana/latest/http_api/dashboard/#create-update-dashboard) instead.

**Comment by cr-lironkreiss** [comment]
@marefr correct me if I'm wrong, but I can't create/update dashboard from json using the api, hence I need to use the import cause I have json template that.

**Comment by marefr** [comment]
@cr-lironkreiss so doing an import in UI of a dashboard from grafana.com and inspecting the payload POSTed to Grafana API (/api/dashboards/import I get this:

```json
{
  "dashboard": {
    "__inputs": [
      {
        "name": "DS_PROMETHEUS_111",
        "label": "Prometheus Data Source",
        "description": "Prometheus Data Source",
        "type": "datasource",
        "pluginId": "prometheus",
        "pluginName": "Prometheus"
      }
    ],
    ...
    "uid": "hb7fSE0Zz",
    "version": 13
  },
  "overwrite": true,
  "inputs": [
    {
      "name": "DS_PROMETHEUS_111",
      "type": "datasource",
      "pluginId": "prometheus",
      "value": "gdev-prometheus"
    }
  ],
  "folderId": 0
}
```

There you could provide your `folderId`.

**Comment by cr-lironkreiss** [comment]
@marefr thanks it helped!

**Comment by hybby** [comment]
I also humbly request that you consider adding a `folderUid` body schema attribute to the [create/update dashboard](https://grafana.com/docs/grafana/latest/http_api/dashboard/#create--update-dashboard) API and store that information in the response from the [get dashboard](https://grafana.com/docs/grafana/latest/http_api/dashboard/#get-dashboard-by-uid) API.  Right now, it's only posisble to use `folderId` which is not transferrable between installs.

I have a situation where I'm a user (but not an admin) of two Grafana installs.  I want to maintain the same dashboards and folder structures between them both.

If I create a dashboard in a folder on one Grafana and export it with the HTTP API, it is saved with a `folderId` meta attribute:

```
        "folderId": 259,
```

However, when I then try to import that dashboard on the second Grafana host, a folder with that particular ID will not exist.

When I create a folder, I cannot specify the `id`, only the `uid`.  The created folder will get whatever ID happens to be free on that Grafana.  So it's very likely that whatever value gets saved by my export will be wrong on the other Grafana instance.  

This means I can't have an install-agnostic version of an exported dashboard.

It also means that if I have a saved version of the dashboard, I need to know what host it was exported from to have a fighting chance of figuring out what the folder the `folderId` maps to.  It makes for a very complicated workflow that will probably break really easily.

Please consider implementing this as a feature - you use `uid` values to great effect elsewhere in your API and have even implemented them within the folders API, so why not allow them to be used in the dashboards API?
