### ISSUE TITLE
Show/Hide Series Not Working in Chrome Web Application

### ISSUE THREAD

**Issue by dannygr664** [grafana/grafana#12696]
Hi,

I am using the Grafana web application v5.2.0-pre1 (f17100e98) on a Windows machine, with the data source set to "default". In the Chrome browser, I created a graph panel with two series, and tried to click one of the series on the legend, which should hidden the other series. Instead, nothing happened. I replicated this in Internet Explorer and the feature worked as expected, showing only the series clicked on in the legend.

**Comment by marefr** [comment]
That's quite an old version and random commit. Tested with Grafana latest master (5.3.0-pre1) and Chrome 67.0.3396.99. Works as expected. 

Please try a newer commit/stable version and/or include more details, like
* Chrome version
* Screenshots
* Any errors generated in the Chrome dev tools console

**Comment by seanlaff** [comment]
I notice this behavior if all of the series have the same name in the legend. Clicking one of them does not hide/unhide the line. I think the code does a string match rather than mapping the series name to an underlying id.

If you have A, A, A, B, C then click any of the As will hide/unhide all of the As

**Comment by marefr** [comment]
That's the expected behavior. Please make sure to differentiate series names.
