### ISSUE TITLE
[feature request] Add filling in last seen value to grafana sql datasource fill mode

### ISSUE THREAD

**Issue by svenklemm** [grafana/grafana#12756]
Currently when using the $__timeGroup macro grafana allows filling in NULL for missing values or an arbitrary float value. It would be useful to have another mode where grafana fills in the last previously seen value for that series (last observation carried forward). While doing this in SQL is possible it complicates the query quite a bit and its more efficient to implement in the grafana backend.

**Comment by marefr** [comment]
Wouldn't using fill with null and threat null values as connected in graph panel do exactly this?

**Comment by svenklemm** [comment]
The resulting graph would probably look the same unless you are not having enough points to draw the line. But graph panel stat functions like avg would probably look different.

**Comment by marefr** [comment]
Guess you're right. Had a hard time understand why this might be useful but can see that it can be useful for sparse data. See that Influxdb has same functionality using fill(previous). Also other TSDB's supports this.

Think we should consider naming it `previous` instead of `last` for consistency and maybe more understandable? What do you think @svenklemm?

**Comment by svenklemm** [comment]
Sure last might be misleading and previous seems to express better what it does, I'll update the PR.
