### ISSUE TITLE
Remove Elasticsearch direct/browser access mode

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#12757]
Why?
* Very high maintenance burden to have multiple implementations in frontend and backend (elasticsearch is Grafana's most advanced datasource since it has a very complicated request/response model)
* Very confusing for end user that graph panel render based on frontend implementation and alerting evaluates data based on backend implementation
* To be able to use alerting there's no support for direct/browser access mode
* Security - No way for end user to access an index not configured in datasource
* Supporting both frontend and backend slows down the development of adding new features to  datasource

Would appreciate feedback for those using direct/browser access mode and why they're needing that.

**Comment by aocenas** [comment]
This may affect users. We could migrate users to use server mode without them needing to do anything but depending on the setup some users may have access to Elastic only from local machine not from the Grafana server. So probably needs some discussion if that is ok or how to approach this change.

**Comment by m4rkw** [comment]
Hello,

I would ask that you reconsider the decision to deprecate this feature. In an enterprise environment where OIDC is used to authenticate both to Grafana and to backend data source systems like Elasticsearch it is unwise to have the same JWT be accepted by both systems. Although this would make life easy in that the "forward oauth identity" feature could be used for authentication to elasticsearch, it would mean that credentials sent to grafana would also be valid for Elasticsearch which is exactly the kind of thing that oauth is supposed to prevent.

So in the case where the two systems do not accept the same tokens, "forward oauth identity" cannot be used. Browser access mode would allow us to put a proxy in front of Elasticsearch that handles bouncing the browser over to the identity provider and back in order to obtain a JWT valid for Elasticsearch.

Of course a much better solution would be native support for secure onward OIDC authentication to backend datasources, but since that isn't likely to be built any time soon (if at all), at least leaving the possibility to orchestrate such a thing oneself seems like a reasonable compromise at least in the short term.

It doesn't appear from the original post here that this use-case has been considered.

I am somewhat confused though as to what is meant by "supporting frontend and backend" - is this meant to imply that you support querying Elasticsearch through the Kibana frontend? I've tried configuring this and it doesn't seem to work at all, it's just trying to hit /_msearch so I can only assume this is intended to work with unauthenticated Elasticsearch clusters directly.

Thanks,
Mark

**Comment by trexx** [comment]
> Security - No way for end user to access an index not configured in datasource

We currently do this in a way using Kerberos authentication. Thanks to browser access, when Grafana initiates a connection to Elasticsearch via the browser, the user is able to invisibly authenticate via Kerberos. Their access is defined by their roles in ES, and if they should attempt to access they don't have access to, they are denied.

This is a killer feature for us since it frees Grafana from the burden of managing authorization.

If there's a better / easier way of doing this, I'd love to hear it.

**Comment by m4rkw** [comment]
@gabor could you please let me know if my comments on this issue and those from @trexx were even considered by anyone before you decided to remove the feature?

**Comment by meanmina** [comment]
@m4rkw we did take into consideration the comments on this issue and we have started some internal conversations around how we can support such flows in the future.

**Comment by atringham** [comment]
@meanmina are you planning on dropping support for this feature BEFORE providing an alternative?
