### ISSUE TITLE
Error using dimension_values with a filter

### ISSUE THREAD

**Issue by pablochacin** [grafana/grafana#12775]
### What Grafana version are you using?
5.2.1

### What datasource are you using?
CloudWatch

### What OS are you running grafana on?
Linux (Docker)

### What did you do?

Create a variable using the dimension_values function filtering by the "app" tag. 

`dimension_values(default, AWS/ApplicationELB, HealthyHostCount, LoadBalancer, {"tag:app": ["$application"]})`

The value of the $application variable used in the filter comes from another query
 `ec2_instance_attribute(us-east-1, Tags.app, {})`

### What was the expected result?
A list of LoadBalances for the given application

### What happened instead?
An error:

> Template variables could not be initialized: t.replace is not a function
 
I have tried using a fixed valued instead of the application variable (e.g. "myapp") with similar results. 

Removing the filter returns the list of all load balancers

**Comment by xlson** [comment]
@mtanda I'm not super familiar with the cloudwatch datasource code. Is it possible to filter on tags on a loadbalancer when getting its metrics?

**Comment by torkelo** [comment]
@mtanda do you know if this should work?

**Comment by mtanda** [comment]
It is not my code. https://github.com/grafana/grafana/pull/10873
I think filtering tag is not supported, because to get tag information, Grafana needs to call ALB API.
https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/Welcome.html

But, the backend code doesn't import the API package.

Resource group tagging is one of the solutions.
I already create the issue for it.
https://github.com/grafana/grafana/issues/8207

**Comment by xlson** [comment]
@pablochacin You can only filter on cloudwatch dimensions, you can find them documented here: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/elb-metricscollected.html#load-balancer-metric-dimensions-alb

I will update the documentation to link to those filters. As @mtanda mentioned there is a feature request for what you asked for that you may wanna :+1: to show your support (#8207).
