### ISSUE TITLE
Include None Option

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#12778]
### What datasource are you using? Prometheus

I'd like to make variables which I would use to exclude certain metrics.

To do so I would need something similar to the `Include All option` & `Custom all value` but for excluding, i.e., `Include None option` & `Custom none value`

Regards.

**Comment by torkelo** [comment]
how would that value render in a query? like `WHERE server IN ('$server')` and other scenarios  ?

**Comment by sylr** [comment]
@torkelo `gmetric_name{namespace=~"$namsepace",namespace!~"$notnamespace")`

both `$namespace` & `$notnamespace` would be regexp here.

**Comment by sylr** [comment]
Another possibility would be that we could manipulate the list with the following actions:

 - Select all, would checked all values (different from checking `All`)
 - Invert all, would checked currently unchecked values and unchecked checked ones

**Comment by marefr** [comment]
Closing this since this feels like an edge case for core Grafana. 

You can workaround this either by filtering out values in template variables so that they're not included in drop down list and or you can have two template variables, one where you can choose which ones to include and another one where you choose which ones to exclude. Then you can use what you wrote above

> gmetric_name{namespace=~"$namsepace",namespace!~"$notnamespace")
