### ISSUE TITLE
Configuring headers to a datasource in UI

### ISSUE THREAD

**Issue by pablochacin** [grafana/grafana#12779]
### What Grafana version are you using?
V5.3.0-pre1

### What datasource are you using?

None in particular, but interested in elasticsearch and simple json

### What OS are you running grafana on?
Linux (Docker image)

### What did you do?
I want to define a couple of custom header to pass an application authorisation token
Pull request  [Pass configured/auth headers to a Datasource](https://github.com/grafana/grafana/pull/11643) implements this feature and has been already merged.

### What was the expected result?
To be able to specify these headers when creating the data source.

### What happened instead?
Data source UI doesn't allow to define this attribute. Apparently, it is only available by means of datasource provisioning.

**Comment by Zivaga** [comment]
Thanks, very useful feature for me ! :) 👍

**Comment by FUSAKLA** [comment]
Hi, just wondering if this is on schedule to be implemented since it fell through few milestones already?
It would be really great at least for Thanos users if we could use this to enable/disable some features on the datasource side.

I'm the opposite of an UI developer but if there is no progress and motivation I might give it a try possibly?

**Comment by adrien-f** [comment]
I've spent a quick hour prototyping something.

Not an expert in Angular/UI but would something like this work out for you guys ?

![peek 2019-02-21 21-58](https://user-images.githubusercontent.com/781688/53201322-fe513180-3623-11e9-89fb-2d15bffbb95e.gif)

**Comment by FUSAKLA** [comment]
Oh I somehow missed this. This would be great!

**Comment by marefr** [comment]
@adrien-f interesting approach and good start. Lets hear what @torkelo or @Ijin08 thinks?

**Comment by adrien-f** [comment]
Hi @marefr, did you get any feedback on this ? Should I continue working on this feature or you already have something else planned for this ?

**Comment by marefr** [comment]
@adrien-f I think this is a good start, but has asked @Ijin08 to have a look. Basically the functionality is there, but design wise think we can reuse some existing elements. Would suggest you open a PR and we can continue discussion/review there. Thanks

**Comment by Ijin08** [comment]
@adrien-f My quick thoughts. First use form fields, the placeholders shouldn't be used as labels. Configured and reset button is good as is. Use neutral button(inverse) for delete. The X is enough. Also use inverse for the add button since Save & test is the primary action.  
<img width="1440" alt="Screenshot 2019-04-23 at 14 38 52" src="https://user-images.githubusercontent.com/23470681/56581573-8d070e00-65d5-11e9-9e86-f13632800a50.png">

Check out the Add value mapping on the new Gauge panel.

**Comment by weeco** [comment]
@adrien-f This is very much needed here as well. It seems like Grafana members would accept a PR on this. Do you intend to submit a PR for this feature?

**Comment by debojitkakoti** [comment]
@adrien-f Very much needed feature .

**Comment by adrien-f** [comment]
Hi everyone ! I'm glad you guys are excited about this and thanks for the input on the design parts. I'll quickstart a PR next week !

**Comment by jiacai2050** [comment]
@adrien-f  Any progress?

**Comment by adrien-f** [comment]
@jiacai2050 Work started on the MR 😄 I only have my weekends though to work on this, hope to have this working this one or next week.

**Comment by infa-ddeore** [comment]
how long will it take?

**Comment by wpdildine** [comment]
Is this available anywhere I would like to use this feature.  I'm not in a rush I can use ssh tunnelling in the meantime.

**Comment by marefr** [comment]
@wpdildine you can provisioning as a workaround, see [docs](https://grafana.com/docs/grafana/latest/administration/provisioning/#custom-http-headers-for-datasources)
