### ISSUE TITLE
Unable to change to Light Theme

### ISSUE THREAD

**Issue by Famedevon** [grafana/grafana#12770]
![grafana_issue](https://user-images.githubusercontent.com/41600251/43444391-c4666ef0-94e2-11e8-9fa8-672911960161.jpg)

**Comment by marefr** [comment]
What theme setting do you have on your user profile?

**Comment by ItsJulia** [comment]
I was also wondering, why I couldn't change my theme. 
What I found out so far:
There are two places, where you can change your theme. One is in "admin"** -> "Preferences". The other one is in "Configuration" -> "Preferences". 
When I want to change the theme in "admin/preferences", it is always working fine.
When I want to change the theme in "configuration/preferences", it has only an effect, when the theme in "admin/preferences" is set to "default".

Now my question: is this a bug or a feature? ;-)  
If its a feature, do you have any documentation for that behavior?

**or your user-name

**Comment by marefr** [comment]
@ItsJulia that's the expected behavior. Not that much documentation for this. We should try and fix that.  

It gives each user possibility to decide if they want specific theme or use the default. Each new user gets "Default" per default. Each new organization gets "Default" per default.  The default theme is "Dark" if org and user of org has "Default". Default theme can be changed thru Grafana configuration `default_theme = light`.

Also, as a bonus you can add a querystring parameter to any url in Grafana to temporarily switch theme for current session, i.e. http://localhost:3000/?orgId=1&theme=light.
