### ISSUE TITLE
[Feature request] Cloudwatch Query for a list of instances for which data is available in the selected time interval

### ISSUE THREAD

**Issue by ab791520b4** [grafana/grafana#12784]
I would like to be able to create a template variable which contains all instances for which data is available (given a region, namespace and metric name) in the selected time interval. So let’s say I have an ElasticBeanstalk environment with autoscaling active. Instances will come and go over time. I can then use for example the following dimension query to get a list of all instances for which ApplicationLatencyP50 data is available at any point in time (!) for the corresponding EB environment:

dimension_values($region,AWS/ElasticBeanstalk,ApplicationLatencyP50,InstanceId,{“EnvironmentName”:"$service"})

But let’s say I want to narrow down this list and I only want the list of instances for which data is available in the selected time interval such that the panels are not unnecessarily cluttered with instances that are non-existent in the currently selected time range anyway. To the best of my knowledge this currently cannot be done with a CloudWatch data source.

**Comment by mtanda** [comment]
@marefr 

It is technically possible, but it is very complicated...

The CloudWatch data source depends on ListMetrics API.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_ListMetrics.html

The API returns the list of `metric name and dimensions` which published to CloudWatch in past N days.
Due to the ListMetrics API doesn't handle time range, and it doesn't return Last update time of metrics for the dimensions, filtering current existing dimensions is impossible.

Some instances are terminated in past N days ago, but the ListMetrics still returns the instance ids in the dimensions list.

The N days is not documented in AWS docs, I guess it is 7 days, but not sure.

If the target is EC2 instance, we can filter dimensions by using EC2 APIs.
The instance id is never reused, so getting EC2 terminated time, we can filter the dimensions.

If the target is RDS or other services which id could be reused, we need to call GetMetricStatistics API, and filter dimensions by the actual metrics query API response...
So we need to support the feature like https://github.com/grafana/grafana/issues/4470 .

**Comment by sunker** [comment]
There's no support for this in the Cloudwatch API. However in grafana 6.5 we add support for using [wildcards](https://github.com/grafana/grafana/issues/20058) in dimension values. There's no guarantee that the timeseries that are being returned have been reporting data in the selected time frame, but at least it will throw away empty time series.
