### ISSUE TITLE
UI flickering (per design?)

### ISSUE THREAD

**Issue by PauloTemenos** [grafana/grafana#12894]
### What Grafana version are you using?
Grafana 5.2.0-1

### What datasource are you using?
N/A

### What OS are you running grafana on?
RHEL 7.5

### What browser?
Firefox 61.0.2

### What did you do?
Use dashboards with sporadic periods of having the mouse still.

### What was the expected result?
No UI flickering.

### What happened instead?
UI flickers

---

When we're using a dashboard, when we are looking and thinking and paying attention, if we have the mouse still for a while Grafana will automatically hide the left bar and cause a UI re-arrangement/flicker. When we move the mouse again it will automatically unhide the left bar and cause another UI re-arrangement/flicker.

This violates one of the golden rules of UI design - never make anything happen unless by user action, be still and reactive, which is why I'm reporting this as a bug.

I appreciate this might be working as intended and implemented in a well-intended manner but .. this is so annoying. Be still and reactive, don't have the UI do unrequested things on its own at «random» times... :(

**Comment by torkelo** [comment]
This automatic view mode when no user activity is detected is to make Grafana optimize space used for fullscreen monitors & TVs and is usually the desired feature. 

You can hide the sidebar permanently by clicking on the Grafana icon in the top left, this will cause the transition from active to inactive mode to be less jumpy. 

We might add a user option to disable inactive mode as you are the second person since introducing where this has been an issue https://github.com/grafana/grafana/issues/10642  (the view mode was introduced in v4 but was made more annoying with the change to a side menu in v5).
