### ISSUE TITLE
Automated packaging improvement : switch from FPM (ruby) to NFPM (Go)

### ISSUE THREAD

**Issue by jaimegago** [grafana/grafana#12932]
I just wanted to put the Go version of FPM, i.e. [NFPM](https://github.com/goreleaser/nfpm) on the maintainers radar.
Not sure it has all the feature needed for a drop in replacement but it sure would be nice to get rid of the Ruby dependency for Grafana packaging scripts.

**Comment by xlson** [comment]
@jaimegago Thanks for bringing it to our attention. I'll have to give it a proper look someday, wouldn't mind being able to remove ruby from the build chain as fpm is the only reason its there in the first place.

**Comment by markelog** [comment]
When I was going in with this issue, I was thinking it should be pretty simple
- just replace the tool and all should work, right? 

I guess not :), since `nfpm` and `fpm` use completely different approaches.

So far I faced following issues:
1. `nfpm` uses declarative approach i.e. with configuration file, with `fpm` we pass all the options via flags
1. `nfpm` kindly facilitates the file hierarchy of the builded packages, whereas we do it ourselfs 
1. with `nfpm` there is a limitation on dynamic paths for `files` field and we do have different paths for different archs
1. not sure when and where we actually build the packages for release, right now you can build debian package and if you on mac it will put a darwin binaries in it, hm
1. we would have to rewrite most of our release related logic of our `build.go` in order to incorporate changes in the approach
1. Some of the options still needs to be passed as values (at least version, package name {different for grafana enterprise} and etc) but as environment variables or via different nfpm configs
1. I believe in order to test the new changes properly you would have to test all possible builds for all archs, plus enterprise build. And frontend build takes a lot of time :)

So all and all, it seems implementing `nfpm` would require significant rewrite of the build logic. And at this point I am still not sure if it would cover all our cases
