### ISSUE TITLE
dividing two graphite metric series in grafana

### ISSUE THREAD

**Issue by aather** [grafana/grafana#1295]
I need to divide the delta of two series in grafana (version 1.9.0):

( nonNegativeDerivative(Series 1) / nonNegativeDerivative(Series 2) ) / scaleToSeconds(1)

Please let me know what is the best way to do it in Grafana editor.

Thanks,
Amer.

**Comment by torkelo** [comment]
@aather there is a graphite function called divideSeries that takes to series. For functions like this you have to use the query reference syntax (#A) to created nested queries.  

Example:
![image](https://cloud.githubusercontent.com/assets/10999/5609734/ab89b1d8-94a7-11e4-8837-d8d8adf674fa.png)

You can hide the series #A so that it does not show in the graph. (so it is is only used as parameter in query #B)

**Comment by aather** [comment]
Thanks for your prompt reply. I tried it and it does work as suggested.

Regards,
Amer.

**Comment by gargnisha1605** [comment]
Suppose,
Metrics A : test.count
Metrics B: test1.count
Metrics C:sumSeries(*.count)
eg test:5
test: 10
C:15

How to measure the percentage of Metrics A/ Metrics C ? I want to get (5/15)*100

**Comment by torkelo** [comment]
add  new query (do not specify any metrics)
add function asPercent (#A, #C) as parameters. this is a graphite function, grafana will replace #A with the query in A and #C with the query in C before sending to graphite.

**Comment by gargnisha1605** [comment]
Thanks,

Is it possible in Grafana version 1.5.4 or do I have to migrate to above versions, and if yes which version?

**Comment by torkelo** [comment]
I think that feature was added in 1.6, but I highly recommend upgrade to Grafana 3.0 (than import migrate your dashboards),

**Comment by gargnisha1605** [comment]
Thanks a lot Torkelo.
I am pushing some metrics from code to graphite and I am plotting these metrics on grafana. Thus increasing grafana version from 1.5.4 to higher version will not have any effect on graphite? 
IDo I have to change graphite configurations in that case?

**Comment by torkelo** [comment]
you do not need to upgrade graphite

**Comment by gargnisha1605** [comment]
Thanks Torkelo for such quick response.

**Comment by nikhilbansal** [comment]
Hi Torkelo,

Is it possible to perform these arithmetic operations of multiple series with Elasticsearch datasource.

**Comment by torkelo** [comment]
No Elasticsearch has no such query feature

**Comment by softwareklinic** [comment]
Any chance grafana will ever be able to sum or divide series for elastic??? or is this an elastic limitation?

**Comment by torkelo** [comment]
Yes, elasticsearch cannot do this

**Comment by reesechou2014** [comment]
But how can i do this by use openTsdb ?

**Comment by 646826** [comment]
How do I do it if I use MySQl?

**Comment by torkelo** [comment]
You can’t it’s a Graphite feature

**Comment by softwareklinic** [comment]
Ty

Someone  published a plug-in called
https://grafana.com/plugins/blackmirror1-singlestat-math-panel

Which is useful in elastic search based series calculation.


Regards
Keyur

On Nov 11, 2018, at 8:07 AM, Torkel Ödegaard <notifications@github.com>
wrote:

You can’t it’s a Graphite feature

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_grafana_grafana_issues_1295-23issuecomment-2D437672965&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=SOswRB2UZTNxsbMfKdjlPlDUscg9Enm8lphJ3yS9TPU&s=BII26poZzJ1vq6WqBs4_Ll6OSBfB6SOZKHKAiDjIMsg&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHMCidnW2HYhIsFKZ-2DXvwQ5bkI0ba0VVks5uuC8jgaJpZM4DOOB5&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=QdU9ynK_Pna3a4TlNm0IqSkTvAoOvgSYGNrfxhJcJgM&m=SOswRB2UZTNxsbMfKdjlPlDUscg9Enm8lphJ3yS9TPU&s=SKdedD4cMbd53jlNHMaR3KChCLbN15F2Hg8OQXYssd0&e=>
.
