### ISSUE TITLE
Logo disappears when side bar auto-hides

### ISSUE THREAD

**Issue by svet-b** [grafana/grafana#12957]
Not sure if the below is intended behavior or a bug, but it struck me as an odd UI "feature" so I figured I'd post here for comments.

### What Grafana version are you using?
5.2.1 (though I've experienced the same with previous 5.x versions)
### What datasource are you using?
Any
### What OS are you running grafana on?
Ubuntu 16.04
### What did you do?
While looking at a dashboard, hold still until the side bar auto-hides
### What was the expected result?
When the side bar hides I should continue to see the Grafana logo and dashboard title.

This is indeed the result when I *manually* hide the bar by clicking on the Grafana logo:
![screen shot 2018-08-17 at 11 11 16 am](https://user-images.githubusercontent.com/12831860/44258746-fb5a2c00-a20f-11e8-814b-83dc86723a2d.png)

### What happened instead?
The side bar auto-hides and I continue to see the dashboard title, but the Grafana logo disappears, along with the dashboard icon - leaving what looks like an awkward blank space:
![screen shot 2018-08-17 at 11 10 52 am](https://user-images.githubusercontent.com/12831860/44258763-0614c100-a210-11e8-98a4-dfa6197301db.png)

### Browser
Same in Chrome 68.0.3440.106 and Safari 11.1.2 (13605.3.8), both on Mac.

### Some analysis
This is primarily the result of the applying of the `user-activity-low` class to the HTML body when there is no user activity. This sets `display: none` for the entire `sidemenu` object and sets `opacity: 0` for the `gicon-dashboard` object.

On the other hand, hiding the side bar by clicking on the Grafana logo has a more subtle effect: hides the `sidemenu__top` and `sidemenu__bottom` divs, but not the Grafana logo, and does not affect the dashboard icon.

**Comment by marefr** [comment]
This is by design I think. Hiding sidebar is a different thing than the in-active view mode. You can Toggle in-active / view mode using keyboard shortcut d v or it will automatically enter in-active mode after some time - usually happens when displaying on a TV screen.

We're currently evaluating our different options regarding kiosk mode, in-active mode and possibly some other new mode ([see](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#new-experimental-features)) where we probably want to make this easier and more consistent. Maybe the automatic in-active mode is removed in the future, we don't know yet.

**Comment by svet-b** [comment]
Thanks for the explanation @marefr, makes sense. I agree that there are a few different use cases out there for different UI "looks", and it might take some experimentation to nail all (or at least most) of them in a consistent way. Will look out for future developments.
