### ISSUE TITLE
Support changing alert rule without requirement of updating dashboard panel

### ISSUE THREAD

**Issue by calebtote** [grafana/grafana#12973]
Requiring updates to the dashboard configuration allows for no easily maintainable way to make global changes to the alerting system frequency (i.e., if the granularity of alerts isn't fine enough and you wanted to update every alert in the application from every 60 seconds to every 10 seconds, this requires a manual update to every alert).

It would be very convenient if the alerts http api exposed endpoint for editing alert rules.

**Comment by marefr** [comment]
This is currently a limitation of the alerting feature, but updating the alerting database table is not something we officially support or recommend. Changes should be made thru HTTP API which is not supported at the moment. For me not closing this feature request I would like you to rephrase title and description. 

Title into something like "Support changing alert rule without requirement of updating dashboard panel". Do you agree?

**Comment by calebtote** [comment]
Makes sense to me, updated!

**Comment by marefr** [comment]
Thanks. I changed the issue description a bit.

**Comment by bergquist** [comment]
Thank you for taking the time to write down this issue. All thou this is not something we will implement in the current alerting solution. We are currently discussing major improvements to Grafana alerting and this issue will be addressed by such change. So I'm closing this issue since we want to keep issue about things that we will implement or fix in the near future.
