### ISSUE TITLE
Alerts not triggered for condition min()

### ISSUE THREAD

**Issue by darshil-doshi** [grafana/grafana#12985]
Grafana **version**: 5.1.3
**Datasource:** InfluxDB
**OS:** Ubuntu 16.04
Use case: Alert configured with:
- Evaluate every 10s
- When: min() OF Query(A, 15m, now) IS ABOVE 25

**Expected behavior:** Alert should have been triggered when temperature was way above threshold for over an hour.

**Actual behavior:** No alert triggered.

Metric query: `SELECT "temperature" FROM "foo" WHERE ("deviceId" = 'device1' AND "tag2" = '1234325') AND $timeFilter`

![errorpanel](https://user-images.githubusercontent.com/14038070/44350450-05548700-a4bd-11e8-8429-e9363dbfafb0.png)

**Comment by marefr** [comment]
What does the graph look like (screenshot) when you look at last 15 min (same as the range you're using for the alert evaluation)? And then when clicking on Test Rule - does that result looks correct compared to the 15min graph your looking at? Could you also include query inspector request/response. 

Could be something related to interval. If you explicitly group by 1min for example does that make any difference?

**Comment by darshil-doshi** [comment]
Last 15mins data
![data15m](https://user-images.githubusercontent.com/14038070/44411335-e1a84400-a583-11e8-9ed6-1a307eb736a7.png)

Query Inspector:
![queryinspector](https://user-images.githubusercontent.com/14038070/44411343-e836bb80-a583-11e8-87c0-1892887639a4.png)

Test rule
![test-rule](https://user-images.githubusercontent.com/14038070/44411617-93477500-a584-11e8-9bea-c6f12dbac347.png)

My system is generating data every 15 minutes. At times, I don't see data in last 20-25 mins even though data is present at 15 minutes interval.

I would also like to highlight that the value is in normal range, yet last state is showing as alerting. 
![alert-state](https://user-images.githubusercontent.com/14038070/44411883-2aacc800-a585-11e8-8b15-8b1446aab6e9.png)

**Comment by marefr** [comment]
Since your system is generating data each 15 minutes (for that point in time I suppose) you should configure your min time interval on datasource edit or metric tab options in panel to 15m. 

When looking at your dashboard you're using from:now-16m to:now-1m. I would suggest you use the same for your alert rule like `Query(A, 16m,now-1m).

It could also be something to do with you're only having one point in time range you're evaluating.

> I would also like to highlight that the value is in normal range, yet last state is showing as alerting.

That's probably because you've configured if no data or values are null=keep last state. Would recommend you to change this to no data for starters.

Other pointers: inspect the grafana server log with debug enabled, see http://docs.grafana.org/alerting/rules/#troubleshooting.

Try and add a group by 15m to your query

**Comment by marefr** [comment]
Closing this due to no response. Will consider reopen given more included details.
