### ISSUE TITLE
Show series based on value of custom variable

### ISSUE THREAD

**Issue by vadi2** [grafana/grafana#12982]
Using Grafana 5.2.2 and InfluxDB, how can I selectively show a series based on the value of a custom variable (so a toggle on top of the dashboard)?

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Hard for me to give any pointers since you didn't provide that much information. If you create topic at community site please include more information, like if you want a panel to be visible or not when toggle or if a certain series should be visible/hidden on toggle.
