### ISSUE TITLE
Graph: Staircase and null value=null calculates auto Y-Min incorrectly

### ISSUE THREAD

**Issue by MicahZoltu** [grafana/grafana#12995]
Please include this information:
### What Grafana version are you using?
v5.2.2 (commit: aeaf7b2)
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Ubuntu
### What did you do?
Created a graph with very large values (6,000,000 to 6,180,000 in the window) for the Y-Axis then enabled Staircase.
### What was the expected result?
The Y-Min "auto" setting would continue to function as expected and have a min of ~6,000,000
### What happened instead?
My chart's Y-Axis had a range of 0 to 6.18M.
### If related to metric query / data viz:
Very simple query, just:
```
SELECT last("number") FROM "measurement" WHERE time >= now() - 15m GROUP BY time(1s) fill(previous)
```
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
I don't believe this is relevant because the stairstepping is a client-side only switch, no data reload occurs when the issue presents.

**Comment by marefr** [comment]
I would suggest you to use the $timeFilter instead of `time >= now() - 15m`. 

The only way I'm able to reproduce something similar is when using `Null value=null` or `Null value=null as zero` and staircase or not using staircase and  `Null value=null as zero`. In my case the graph is actually starting from zero in the beginning and that's why my y-axis gets the ranges 0 to 600 instead of 470 to 530. 

I think you're getting zero in the beginning because you're using fill(previous) which in case there are no value in the beginning of time range it will be null.

**Comment by Gelunox** [comment]
I found this topic after encountering the issue myself. It seems that when staircase is active it requires a starting position, which in this case defaults to 0.

This requirement does not seem to be present when there is no previous data. Is it not possible to handle the case of previous value being `null` the same way as the case of previous value being not there?

**Comment by leeoniya** [comment]
@marefr @bergquist i think the new timeseries panel fixes this, can you please recheck? thanks!

**Comment by keegion** [comment]
I can still reproduce the bug in 7.4.0 Beta

<img width="1268" alt="panel" src="https://user-images.githubusercontent.com/29993013/105362131-2d52f200-5c03-11eb-9749-213d71a1f6bd.PNG">
<img width="389" alt="settings" src="https://user-images.githubusercontent.com/29993013/105362139-2f1cb580-5c03-11eb-80ff-68dc323d87f8.PNG">
<img width="202" alt="version" src="https://user-images.githubusercontent.com/29993013/105362145-317f0f80-5c03-11eb-9060-611ed47d462e.PNG">
