### ISSUE TITLE
bug/wrong implementation choice: cannot create datasource that does not exists (at the moment)

### ISSUE THREAD

**Issue by f1-outsourcing** [grafana/grafana#13082]
Cannot add a 'non-existing datasource'

I need to be able to add a graphite datasource, so i can import a dashboard.
I just want to look at the source of a panel. So who cares if the graphite datasource is not working. Do not make such dependencies.  
thus separate 'save & test' to 'save' and a button 'test'

grafana-5.2.2-1.x86_64

**Comment by marefr** [comment]
Are you trying to import a dashboard that required a graphite datasource? Since you have a json file to import you already can look at the source of a panel by just opening the json file.

**Comment by f1-outsourcing** [comment]
Yes. Of course I can look at the source, but that is not why we have invented GUI's not? 

But I already noticed, that although grafana generates an error on 'save & test' it still saves. So that maybe worth looking at also.

**Comment by marefr** [comment]
Grafana will always let you save a datasource to Grafana configuration database even though you haven't access to a datasource of certain type. That's why the button is called Save & test. Save is always guaranteed to proceed given you've entered all required information in the form. After save is done the test will be triggered. 

Going close this for now. The whole idea with importing dashboards is that you're doing that since you already have an existing datasource in place and would like a pre-built dashboard.
