### ISSUE TITLE
Singlestat and Graph panels use different $__interval calculations...

### ISSUE THREAD

**Issue by warezWally** [grafana/grafana#13137]
Please include this information:
### What Grafana version are you using?
5.3.2
### What datasource are you using?
InfluxDB 1.5
### What OS are you running grafana on?
RHEL 7
### What did you do?
Made a query on a graph, and the same on singlestat
### What was the expected result?
Identical values returned
### What happened instead?
After investigation I found that "Graph" and "SingleStat" panels work out the $__interval variables differently:

QUERY IN GRAFANA:

SELECT moving_average(sum("active"), 40) FROM "vantageJobs" WHERE ("type" = 'Transcode') AND $timeFilter GROUP BY time($__interval), "type" fill(previous)

Using Query Inspector... the query sent to InfluxDB

Graph: SELECT moving_average(sum("active"), 40) FROM "vantageJobs" WHERE ("type" = 'Transcode') AND time >= now() - 2d GROUP BY time(**2m**), "type" fill(previous)
Singlestat: SELECT moving_average(sum("active"), 40) FROM "vantageJobs" WHERE ("type" = 'Transcode') AND time >= now() - 2d GROUP BY time(**30m**), "type" fill(previous)

**Comment by torkelo** [comment]
Yes, this is by design. Graph panel tries to request as many datapoints as there are pixels in the graph (or there about, at least not more), while the singlestat defaults to 100 datapoints so tries to divide time range into 100 so no more than 100 datapoints are fetches. You can control this in metrics tab , expand options in top right
