### ISSUE TITLE
[alert issues]:The value inside the "OK" alert message does not appear to be returning to normal.

### ISSUE THREAD

**Issue by NeverSayFail** [grafana/grafana#13185]
What Grafana version are you using?
5.1.4

What datasource are you using?
prometheus

What OS are you running grafana on?
suse11

 What did you do?
I set the alarm value of less than 95% alarm

Conditions:
WHEN last() OF query(C,5m,now) IS BELOW 95

 What was the expected result？
When sending an "OK" alert message, the current value should be greater than 95%

### What happened instead?
There is a server with a current value of less than 95%, but on http://localhost:3000 View actually this moment has returned to normal, want to confirm whether there is a certain delay mechanism in this place

**Comment by marefr** [comment]
The OK message should only be sent when condition is no longer met/true, i.e. above 94, and if you refresh dashboard with alert rule it should be "OK"/green heart. 

If you change dashboard time range to last 5 min that should be equal to the data that the alerting evaluation are using. Depending on if you have certain graph panel display settings you may get different results since alerting evaluation only evaluates metric queries and doesn't care about any other graph panel settings. 

Type of query your using in combination with scrape interval/min step and resolution may also create unexpected results.

Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
