### ISSUE TITLE
Ability to control all options on 2nd Y-Axis

### ISSUE THREAD

**Issue by johntdyer** [grafana/grafana#1320]
I would love to be able to choose to display things like

*  current counts
*  scale
* ect

for items I put on the second Y Axis.  Currently you don't appear to have that degree of control.

**Comment by torkelo** [comment]
I am not sure what you mean by scale? Grid min/max? 
Current counts? 
ect?

**Comment by chron0** [comment]
I think it might be the same thing we talked about on IRC. As an example:
https://apollo.open-resource.org/flight-control/vfcc/#/dashboard/db/aquarius-external-environment

When we look at the left middle graph (Wind) it makes sense to use both Y axis, one for windspeed and one for direction. Now it would be great to have min, max and avg for the windspeed but it doesn't make sense for the direction in degrees, there really is no min max or average but in order to save screen estate it makes sense to merge both metrics into one graph. It would be great if we choose to split the Y axis to have custom legend control for both Y axis so that we could each Y axis the configuration that makes the most sense for the specific value. 

@johntdyer: If that is not what you meant I'll just open another issue :)

**Comment by torkelo** [comment]
@johntdyer what do you mean by scale?

**Comment by sbouchex** [comment]
Apparently, the scale on the left scale and on the right scale are not handled the same.

See this screenshot (today's build)

![2015-09-21_13h54_19](https://cloud.githubusercontent.com/assets/2684878/9991208/55b08f56-6068-11e5-8812-87cd8300ab13.png)

Scale on the left is correct, the right now does have 3 decimals (for example)

**Comment by torkelo** [comment]
unit, y axis Min / max and auto decimals can be different

**Comment by sbouchex** [comment]
Yep but even if the settings are the same, moving the metric from left to right is changing the result. See the 2 pictures, the metric 'Shared' is moved from Left to Right and the result is different:

![2015-09-21_15h27_42](https://cloud.githubusercontent.com/assets/2684878/9993087/1ff5a596-6076-11e5-933a-ba3baf2ba192.png)

![2015-09-21_15h28_05](https://cloud.githubusercontent.com/assets/2684878/9993090/25674c82-6076-11e5-982b-6c92d46cd9cd.png)

**Comment by torkelo** [comment]
no, just the amount of decimals are changed, which is expected as each y axis has its own min/max
