### ISSUE TITLE
Human readable display names for custom variables. 

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#13210]
Currently, the value and display name for custom variables are the same. There might be cases where it would be more suitable to display a human-readable value in the drop-down. Ex the `Visby` instead of just `SWE-4` when selecting datacenters. 

It would be possible to use mysql/postgres to store the values of such template variables but at some point, I think we should make easier to configure this within Grafana itself.

**Comment by lisimia** [comment]
Agreed, this would be very helpful for us as well. 

We are using a postgres datasource, the data looks like the following:

```
data table:
|CID|ts|value|
----
| 1 | 2019-01-01 | 1 |
| 1 | 2019-01-02 | 2 |
| 1 | 2019-01-03 | 3 |
| 2 | 2019-01-01 | 1 |
| 2 | 2019-01-02 | 2 |
| 2 | 2019-01-03 | 3 |
```
```
city table:
| CID | name |
----
| 1 | London |
| 2 | NYC | 
```

It would be nice to show `London`/`NYC` in the variable selector instead of `1`/`2` 

We currently have a lot of values and the team is forced to memorize random integers and it's stopping us from adoption of grafana

I would appreciate some direction on how this could be solved, I might be able to contribute some code as well

**Comment by MikeKulls2** [comment]
Note that the current solution limits it to 2 values. It would be good to be able to have more than 2 and be able to reference them with some syntax like this ${myvar:colname}. For what I am currently doing I have a state with 3 different representations, eg V, Vic, Victoria. The reason to use 3 is V is used as part of lookups (devices that start with V are in Victoria), Vic is used in some places where space is limited and the full name is used for graph headings etc.

It's also possible I could have different values for different purposes. eg a value could have a regex associated with it and another value for URLs

**Comment by CME64** [comment]
> Note that the current solution limits it to 2 values. It would be good to be able to have more than 2 and be able to reference them with some syntax like this ${myvar:colname}. For what I am currently doing I have a state with 3 different representations, eg V, Vic, Victoria. The reason to use 3 is V is used as part of lookups (devices that start with V are in Victoria), Vic is used in some places where space is limited and the full name is used for graph headings etc.
> 
> It's also possible I could have different values for different purposes. eg a value could have a regex associated with it and another value for URLs

I don't think @bergquist  meant to include partial matches instead using a full match all the time is more reliable and practical since the known scenarios are either using an ID instead of the name or a reference name (unique) instead of the friendly name. I don't see any problem here except performance in implementation whether the values will be reloaded on every refresh or cached and reloads after a configurable time to reduce the overhead of database connection and disconnection.

**Comment by MGinshe** [comment]
@lisimia It's actually already possible to do that with the TSDB, MySQL and PostgreSQL datasources.

For example, a variable named `${city}`:
```
SELECT
    name AS __text,
    cid AS __value
FROM city
```

This will show `London` in the variable drop-down, but using `${city:csv}` in your query will output the CID (`1`), instead of the city name. It will also show the city name (instead of the CID) when using the _repeat_ option on a graph/table.
    
    
Also @MikeKulls2's idea is interesting. I know that a few of my Dashboards would benefit from this, as it would reduce the number of re-queries required in some cases.

**Comment by bergquist** [comment]
Closing this since its a dupe of https://github.com/grafana/grafana/issues/1032
