### ISSUE TITLE
Variables are being updated without using 'Update' button

### ISSUE THREAD

**Issue by the0ffh** [grafana/grafana#13229]
I have been using grafana since version 4.2 (I believe), unfortunately this bug still persists.   

In my opinion the perfect solution would be to bind update confirmation/execution to the button explicitly and add a 'Cancel' button. 
    
### What Grafana version are you using?
5.2.4
### What OS are you running grafana on?
Ubuntu 16.04/18.04/, MacOs Sierra/HighSierra
### What did you do?
Clicked on left side menu item, after altering variable definition fields, omitting 'Update' button.
### What was the expected result?
No update performed on a variable.
### What happened instead?
Update performed on a variable.

**Comment by torkelo** [comment]
if variable B depends on variable A and you change variable B then it's going to update, otherwise, values for A will be incorrect and graphs could be incorrect etc. 

Can you provide more detail on your scenario and why you would like an Update button? This has never been requested before. 

It has been requested before in context with updating Graphs:
https://github.com/grafana/grafana/issues/1445

**Comment by the0ffh** [comment]
I think you misunderstood the issue. Here is a gif showing the problem:

![sep-12-2018 10-45-44](https://user-images.githubusercontent.com/26150100/45413416-6fee8200-b679-11e8-8f8d-f8a3a6dff4c3.gif)

**Comment by torkelo** [comment]
sorry, your right.

**Comment by hugohaggmark** [comment]
This is the defacto way variables work in Grafana since at least 6.0. The update button "just" updates the options for the Variable so any other change is updated instantly. I'm going to close this issue because I can't foresee that we'll change this behavior in a near future. We can always reopen this issue if it receives more feedback or upvotes.

Thank You to you for taking the time to create this issue!
