### ISSUE TITLE
Introduce a threshold for Annotations/Events

### ISSUE THREAD

**Issue by chron0** [grafana/grafana#1324]
Having the ability to put events/annotations into the graphs is an awesome feature because we can not only see how some metric behaves, but also see why it might do so. But depending on the number of different events we automatically create annotations for, say by some script, the graph is getting completely unusable when you increase the time range (zoom out).  For example:

https://apollo.open-resource.org/flight-control/vfcc/#/dashboard/db/stargazer-system-overview

When we look at the graph in 24 hours mode, we can see the cloudmap generation every 3 hours and the backup at night. Great and informative :) Now, when we zoom out to say 7d, not to mention 30d, some graphs aren't even visible anymore and things get really sluggish. We could either have a configurable threshold based on annotation count for the period or link the threshold to the period itself. 

As of now I'm not quite sure which makes more sense but at least from my perspective I guess that annotations are mostly interesting when zooming into the details (reducing the period) but since we're not all graphing the same metrics, it might be a different story for someone else's use case.

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
