### ISSUE TITLE
mssql: pass timerange for template variable queries

### ISSUE THREAD

**Issue by cgaborik** [grafana/grafana#13324]
atm the frontend does not pass the timerange on template variable queries in mssql. this patch changes the behaviour to include the timerange when the refresh mode for the variable is set to on time range change

I've updated the mssql datasource.ts file and tested, but I'm still navigating how to publish this change.

**Comment by marefr** [comment]
@cgaborik please open a pull request with your changes.

**Comment by marefr** [comment]
To fix this you can have a look at the [MySQL datasource code](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/mysql/datasource.ts#L116-L121) which already has solved this. The needed code is highlighted.

Basically we need the same code as highlighted for MySQL above implemented in the [MSSQL datasource code](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/mssql/datasource.ts#L109). 

As a bonus, to validate that your implemented changes are correct a test could be added [here](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/mssql/specs/datasource.test.ts) and would be similar to one of the [existing tests](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/mssql/specs/datasource.test.ts#L115-L152). However, instead of verifying the response is correct you would need to verify that the payload provided to `this.backendSrv.datasourceRequest` includes a data property with `to` and `from` properties having a value according to argument passed to metricFindQuery.

**Comment by cgaborik** [comment]
I've had it working for some time on our local Grafana instance. I think I merged the datasource.ts file correctly with https://github.com/cgaborik/grafana/commit/0ed8fb32480f838b418221f752b4978fb4d859fa

**Comment by marefr** [comment]
@cgaborik with that merge you've basically merged your PR to your fork of Grafana. Should be pretty straight forward to extract that commit onto new branch based on latest Grafana master and open PR here. If you're interested of course we would love the contribution.
