### ISSUE TITLE
Github auth docs need to reference root_url setting requirement

### ISSUE THREAD

**Issue by jpds** [grafana/grafana#13340]
The documentation at http://docs.grafana.org/auth/github/ needs to make a reference to the fact that `root_url`[1] setting needs to be configured as well.

[1]: http://docs.grafana.org/installation/configuration/#root-url

**Comment by marefr** [comment]
Changes are needed is in this file and section: https://github.com/grafana/grafana/blob/master/docs/sources/auth/github.md#configure-github-oauth-application

It needs to be changed so that it's clear that the callback URL must begin with configured [root_url](http://docs.grafana.org/installation/configuration/#root-url). When referencing the `root_url` it should be a link back to to the configuration page using a relative path, i.e. `/installation/configuration/#root-url`.

**Comment by mrudelle** [comment]
Same goes for http://docs.grafana.org/auth/google/. It is stated on http://docs.grafana.org/installation/configuration/#root-url but not the other way around.

@marefr or anyone else is looking into it? I don't mind throwing a small PR to add it on both pages.

**Comment by marefr** [comment]
@mrudelle no one else seems to looking into this so a PR would be very welcome.

**Comment by mrudelle** [comment]
@marefr here's a proposition

**Comment by marefr** [comment]
@mrudelle Thanks a lot!
