### ISSUE TITLE
Alerting fails when Prometheus is behind proxy with 'no such host' error

### ISSUE THREAD

**Issue by hkailantzis** [grafana/grafana#13365]
Read before posting: 

Please include this information:
### What Grafana version are you using?
5.2.4
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
MacOS High Sierra, 10.13.6
### What did you do?
Tested an Alert rule, when Prometheus is behind a reverse proxy.
### What was the expected result?
Testing an Alert Rule should be completed without errors
### What happened instead? 
Test Alert rule failed, with 'No such host' error. 

Accessing Prometheus via a reverse proxy (Traefik), from a browser works fine (under a specific domain, e.g.: prometheus.minikube). The data source in Grafana is set, but the 'Access' is set as 'Browser' (Setting it as 'Server', gives 'bad gateway' error).

The problem is when trying to test an Alert rule, it fails with 'prometheus.minikube no such host error'. The api call is visible and via Postman executes successfully. Both Grafana and Prometheus run under a local minikube cluster.

**Comment by marefr** [comment]
Alerting requires Grafana server to be able to communicate with your datasource. You need to make sure that the Server access mode instead of Browser is working for alerting to be able to function properly.

Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
