### ISSUE TITLE
[Feat] Acknowledge alerts

### ISSUE THREAD

**Issue by nikoalch** [grafana/grafana#13364]
Have the ability to acknowledge alerting within Grafana and have addition options to perform actions on acknowledgment of alert(call out to PD, slack, etc).

**Comment by bergquist** [comment]
Thank you for taking the time to provide feedback to us. 

Right now we don't think this idea aligns with the current scope/goal of the Project. I'm closing this issue since we want open issues to reflect the current state of the project. It doesn't mean we never considered it. A closed issue can still get attention from other users and be reopened.

**Comment by nielsk** [comment]
This would be a real great feature, so that I can acknowledge to my colleagues that I deal with the problem at hand.

**Comment by bergquist** [comment]
This is something all teams need but right now it's not something we want to focus on. 
That's why we integrate with so many different Alert notifiers. 

I'm closing this since we aren't gonna work on this for the next year at least and we want an open issue to be about things that we want to work on in a foreseeable future.

**Comment by anshul27jain** [comment]
Our team is also looking for same feature in order to acknowledge alerts sent by Grafana.
This is a essential feature required for any Alerting tool.

**Comment by broferek** [comment]
I'm also desperately looking for a workaround.

My use case is the following : 
1. Alert on a Loki pattern such as OutOfMemory within the last 15 minutes of received logs
2. Create an alert if the pattern is detected
3. The alert should remain in the status page until being acknowledged and resolved manually when the necessary actions has been carried out such as restarting my application.
Unfortunately, the current implementation will send a resolved status as soon as the pattern is no longer detected in the next time range.

**Comment by ppbrown** [comment]
@bergquist Any recommendations for a specific "Alert notifier" that would do the job?

**Comment by bergquist** [comment]
@ppbrown how about https://grafana.com/products/oncall/ ? :)
