### ISSUE TITLE
Security: PGSQL query sent by any client to server without validation

### ISSUE THREAD

**Issue by tdjac0bs** [grafana/grafana#13386]
Hello, I figured out that the SQL queries are sent from the front-end to the database using the query.php without  validation. This makes sense for an admin user (when creating/editing a dashboard), but it's a critical security bug for a regular user, because if you create a user that only have access to one dashboard, this user can sniff the call to query.php and resend the query with different parameters, getting any data from the database.

If it's not fixable, I suggest you to add a message to the datasource admin page: When you create a datasource all the data that this database user can see is potentially acessible from any grafana logged in user.

**Comment by torkelo** [comment]
This is sadly how all data sources work in that queries are composed by the frontend to the backend via the http api. Queries can be very dynamically composed out of template variables and partial components the user selects (variables can be include or modify any part of the query) so it would be almost impossible to have a fully locked down query api that allowed this flexibility. 

The way data source permissions & query access works for viewer roles is detailed in the docs:
http://docs.grafana.org/administration/permissions/#data-source-permissions

It might be possible to chage this in the future so that the query api only accepts dashboard & panel id but hat would require some big restrictions on the use of templating as queries could not be as dynamically composed. But it is something we might investigate in the future. 

If you need data isolation between different Grafana users you need to add data sources to different organizations, each data source needs to be configured with a postgres SQL user that only can query the data you want your viewer users to be able to access.

**Comment by torkelo** [comment]
we are going to be adding data source permissions soon (https://github.com/grafana/grafana/issues/2132)
