### ISSUE TITLE
Add role with no access by default

### ISSUE THREAD

**Issue by FloatingMaster** [grafana/grafana#13474]
It's a common case when you need to grant user access to only specific dashboards. From version 5.0 you can give specific rights to user, but you can't add user to organization without giving them some role. Our current workaround is:

1. Move all dashboards to custom folder (because you can't edit permisions to General folder). 
2. Delete viewer role from this folder
3. Add all users who had viewer access to new team
4. Grant read access to "viewers" team
5. Now you can add new users with viewer role and give them access to specific dashboards

Is there an official way to restrict user access to only specific dashboards, or is it possible to add new role without any access by default?

Grafana v5.2.4

**Comment by leepfrog-ger** [comment]
I think this would be a very sensible addition.

My use case:

- We have a set of dashboards that is regularly edited/expaneded
- There is a group of users that should be able to view select dashboards, but not all. Especially not all newly created ones
- LDAP authentication is used

My understanding is:

- that for LDAP signin to work I need to assign at least one role (so in this case the `Viewer` role)
- newly created dahsboards/folders automatically have the `Viewer` role mapped. This mean that the users of this group of useres can access those dashboards
- Even if I would configure LDAP provisoining to a dummy "staging" organization without any dashboards the moment I add them to the correct organization I need to select at least the `viewer` role

This is risky because forgetting to remove the default `viewer` permissions when creating a new dashboard would grant access that is not intended. A much better approach would be to be able to either let users login via LDAP without assigning any roles at all or have - like in this PR - a role that does not grant any access to newly created items.

Am I missing another way to realize my requirements?

**Comment by eleijonmarck** [comment]
@linoman should we close this?

**Comment by linoman** [comment]
This is now possible starting [10.2.x](https://github.com/grafana/identity-access-team/issues/262)
