### ISSUE TITLE
Create scripted dashboards from UI

### ISSUE THREAD

**Issue by rsheldon** [grafana/grafana#1352]
Reading the docs it seems like to add a scripted dashboard you need to have access to the server to upload your .js script. This isn't very user friendly or secure.

I'd love to see a feature where you could script a dashboard inline in the UI, see the results (in realtime?) and then save it as any you can for existing dashboard.

Also, I can see it being useful to have a panel that is scripted/dynamic within a larger static dashboard.

**Comment by skynet** [comment]
:+1:

**Comment by matteo20** [comment]
+1

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
