### ISSUE TITLE
Sidebar -> Top nav bar

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#13573]
Side menu cons
* Taking up valuable horizontal space. 
* It's creating a sort of half framing (together with dashboard nav) where we have side & top bar that does not look great
* Auto hide removes sidebar which changes the width of the dashboard which requires all panels to update & re-render
* No nice place to put home icon & search input

### Proposed new top nav:
![image](https://user-images.githubusercontent.com/10999/46656293-fe3d2180-cbad-11e8-9328-2f4b7ca008f3.png)

The above is just a mockup, not a final design. Need to add an explore icon, and a create button as well (see trello for reference). And change order of help icon and profile avatar image.

### Slide-out menu
I image the menu button would open up a slide in (over page) menu. Look of side menu needs a design mockup. 

### Hiding top menu
To save precious vertical space when in panel edit mode I think we need to hide top menu when entering panel edit/fullscreen mode. 

Of course it will hide like the sidemenu does in inactive & tv & kiosk modes.

**Comment by ryantxu** [comment]
Do we need the top/side bar?

Can all the side options show up in the standard dashboard search overlay?
![ggg](https://user-images.githubusercontent.com/705951/46691560-13b84880-cbba-11e8-805f-1dc67c95eba1.png)

The user icon could be to the right of the refresh button.

Just brainstorming :)

**Comment by wheelo** [comment]
How's everything going? Is the "top nav bar" available in the new version?

**Comment by torkelo** [comment]
No, we tried it but found some issues , might revisit some day

**Comment by AlexPW89** [comment]
Hi everybody,

Just to add some ideas to the topic:
It could make sense to show metrics in a top navigation.

Regarding this topic our company saw a need to develop a navigation bar panel. 
We install a set of Grafana dashboards for our customers and had the need to visualize specific values in each of those dashboards (like number of active alerts + system state). Plus we wanted to add links with icons.
The navigation bar is put at the top of each dashboard - _it makes the set of dashboards feel more like "one application"._
The problem is if we want to update the navigation bar, we need to update it in each dashboard. Logically, the navigation bar should be configured one level above (e.g. at folder level).

Thats what is looks like (navigation bar inside blue square):
![NavBarGrafana](https://user-images.githubusercontent.com/41908699/68286651-c0951b80-0081-11ea-9456-9fe372acd144.PNG)

1. Drop down list
2. Home button
3. Title
4. Alert numbers
5. Links (with text or icon)
6. Singlestat panel

Our customers usually consume it in kiosk mode.

Kind regards,
Alex

**Comment by dprokop** [comment]
@torkelo is this issue still relevant?
