### ISSUE TITLE
CSS alpha background-color applied twice in table cell with link

### ISSUE THREAD

**Issue by alastrange** [grafana/grafana#13606]
Upgraded from Grafana 5.2.1 to 5.3.0 and noticed table links are appearing strange when there is an alpha background defined for a cell.  Looking at the generated HTML shows both the TD and A elements for the link are specifying the same background color.

<td style="background-color:rgba(50, 172, 45, 0.16)">
	<a href="..." style="background-color:rgba(50, 172, 45, 0.16)">
	</a>
</td>

The table column style is set up to apply colors with a Threshold and Cell color mode.  The alpha is applied twice, which makes the link background color appear less transparent than the cell it is in.

**Comment by torkelo** [comment]
thanks for reporting this:

The problem is that the cell style is applied to the link. 

https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/table/renderer.ts#L261

This is required when the color style is set to the value (because then the link text needs to be colored). But for cell background it should not be set on the cell & link. 

Propose that we break the current style variable into two, cellStyle & textStyle. And for cell value color option we set both but for background we only set the cellStyle. 

https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/table/renderer.ts#L218
