### ISSUE TITLE
Bug: wrong date on sql Graphs with $__timeGroup

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#13621]
### What Grafana version are you using?
v.5.3.0

### What datasource are you using?
MariaDB

Since the update, the displayed value is added one day earlier, ie "delayed", when I used the `$__timeGroup` macro.

![20181011131014](https://user-images.githubusercontent.com/2911588/46802445-962d3d80-cd5d-11e8-99a4-d6a5778aff08.png)

Example with **$__timeGroup(...) as time_sec**

~~~
SELECT $__timeGroup(day, '1440m', 0) as time_sec,
...
WHERE $__timeFilter(day) 
...
GROUP BY time_sec
ORDER BY time_sec
~~~

Example with **day as time_sec**

~~~
SELECT day as time_sec,
...
WHERE $__timeFilter(day) 
...
GROUP BY time_sec
ORDER BY time_sec
~~~

Value of series with times:

![20181011141000](https://user-images.githubusercontent.com/2911588/46802657-3e430680-cd5e-11e8-8e41-fc6213c746f2.png)

See the No.29 values of the series:

The series of the **$__timeGroup(...) as time_sec**:

~~~
time = 1539129600000 as GMT: 2018. October 10., Wednesday 0:00:00
~~~

The series of **day as time_sec**:

~~~
time = 1539216000000 as GMT: 2018. October 11., Thursday 0:00:00
~~~

My time zone:

~~~
2018. October 11., Thursday 2:00:00 GMT+02:00 DST
~~~

Setting of the "Time Option / TimeZone" of the Dashboard is "Local Browser time", but the problem with "UTC" is similar than with it.

This error did not exist in the previous 5.2.0 version.

**Comment by marefr** [comment]
It's due to #11619

Same issue have been discussed here: https://community.grafana.com/t/preset-time-frames-broken-shows-no-data-points-date-is-5-hours-ahead/10683

> Our intention have never been to support anything else than UTC on Grafana and UTC in database/storing timestamps in actual UTC time in database. Unfortunately this have worked for you unintentionally before. Hopefully we can find a way to manage multiple timezones in dashboard/datasource in the future.

Solution: If you write your timestamps in your database either using column of datetime with timezone support type, datetime type (value written in UTC) or epoch milliseconds (UTC by design) it should work as expected.

**Comment by sanchomuzax** [comment]
Coat the button? 😄 

Unfortunately, I don't depend on the source data structure. I can't re-calculate this, the encapsulated data source is complex, can't be modified.

I have a lot of graphs that contain this display mode. These can be overwritten for up to several weeks. 😢

**Comment by marefr** [comment]
That's unfortunate and I totally understand your pain. Will raise this question with team and see what comes out of that. Will post an update here later.

**Comment by sanchomuzax** [comment]
Ok, I understand it, thank you!

I solved with this trick:

_Template variable:_
~~~
$timezone = 
    select (unix_timestamp(now()) - unix_timestamp(utc_timestamp())) / 3600
~~~

_MariaDB SQL:_
~~~
select $__timeGroup(log_date, '60m', 0) AS time_sec,
...
where log_date between $__timeFrom() + interval $timezone hour and $__timeTo() + interval $timezone hour
...
~~~

**Comment by yangliuyu** [comment]
Everything works fine in 5.1.3 (with MySQL 5.7), after upgrade to 5.3.1, I got the same problem, which caused by the time zone.  My time zone is GMT+8

My test data is only two rows. `created_at field` is TIMESTAMP type
![screen shot 2018-10-22 at 6 33 16 pm](https://user-images.githubusercontent.com/1361821/47288544-25253a00-d629-11e8-8b0b-a18b9f178533.png) 
and my query is
```sql
SELECT
  $__timeGroup(created_at, '1h', 0) as time_sec,
  count(1) as value

FROM test
where $__timeFilter(created_at)
group by 1
```

In 5.1.3, $__timeFilter will be converted to (according to the time picker range)
```sql
WHERE created_at >= FROM_UNIXTIME(1540202400) AND created_at <= FROM_UNIXTIME(1540288799)
```

and in 5.3.1, will be converted to
```sql
where created_at BETWEEN '2018-10-21T16:00:00Z' AND '2018-10-22T15:59:59Z'
```

Although the time epoch or time string are all set to UTC time, the result are total different.
`MySQL converts TIMESTAMP values from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval.` https://dev.mysql.com/doc/refman/5.7/en/datetime.html
Referenced from the official doc, my 'created_at' field is stored via UTC format and convert to local time automatically when displaying or filtering.  Therefore in general the time string filter in where clause should be local time other than UTC time. And FROM_UNIXTIME function will convert UTC time to local time 

in 5.1.3 the timestamp in sql result will not be converted to UTC time( is this a bug?)
the "Show Help" tab shows
"Time series:
- return column named time or time_sec (in UTC), as a unix time stamp or any sql native date data type. You can use the macros below."


but in 5.3.1 the time result will be converted to UTC time.
the result in sql is 2018-10-22 15:55:46 group to 2018-10-22 15:00
![screen shot 2018-10-22 at 8 01 16 pm](https://user-images.githubusercontent.com/1361821/47291314-bef2e400-d635-11e8-95d9-a17488a3b3c9.png)

I can set the Timezone in grafana's perference to make it display correct, but this lead to wrong semantic of time filter
![screen shot 2018-10-22 at 8 10 00 pm](https://user-images.githubusercontent.com/1361821/47291511-80a9f480-d636-11e8-806c-faba7d914ce5.png)

Therefore I prefer to use the function in 5.1.3 or remove extra time diff calculation in $__timeFilter and $___timeGroup. Or give user a option to enable or disable UTC time wrapper in macro functions. For my case I don't need to care about the UTC effect, local time is OK.

**Comment by alexkrasov** [comment]
> Everything works fine in 5.1.3 (with MySQL 5.7), after upgrade to 5.3.1, I got the same problem, which caused by the time zone. My time zone is GMT+8
> 
> My test data is only two rows. `created_at field` is TIMESTAMP type
> ![screen shot 2018-10-22 at 6 33 16 pm](https://user-images.githubusercontent.com/1361821/47288544-25253a00-d629-11e8-8b0b-a18b9f178533.png)
> and my query is
> 
> ```sql
> SELECT
>   $__timeGroup(created_at, '1h', 0) as time_sec,
>   count(1) as value
> 
> FROM test
> where $__timeFilter(created_at)
> group by 1
> ```
> 
> In 5.1.3, $__timeFilter will be converted to (according to the time picker range)
> 
> ```sql
> WHERE created_at >= FROM_UNIXTIME(1540202400) AND created_at <= FROM_UNIXTIME(1540288799)
> ```
> 
> and in 5.3.1, will be converted to
> 
> ```sql
> where created_at BETWEEN '2018-10-21T16:00:00Z' AND '2018-10-22T15:59:59Z'
> ```
> 
> Although the time epoch or time string are all set to UTC time, the result are total different.
> `MySQL converts TIMESTAMP values from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval.` https://dev.mysql.com/doc/refman/5.7/en/datetime.html
> Referenced from the official doc, my 'created_at' field is stored via UTC format and convert to local time automatically when displaying or filtering. Therefore in general the time string filter in where clause should be local time other than UTC time. And FROM_UNIXTIME function will convert UTC time to local time
> 
> in 5.1.3 the timestamp in sql result will not be converted to UTC time( is this a bug?)
> the "Show Help" tab shows
> "Time series:
> 
> * return column named time or time_sec (in UTC), as a unix time stamp or any sql native date data type. You can use the macros below."
> 
> but in 5.3.1 the time result will be converted to UTC time.
> the result in sql is 2018-10-22 15:55:46 group to 2018-10-22 15:00
> ![screen shot 2018-10-22 at 8 01 16 pm](https://user-images.githubusercontent.com/1361821/47291314-bef2e400-d635-11e8-95d9-a17488a3b3c9.png)
> 
> I can set the Timezone in grafana's perference to make it display correct, but this lead to wrong semantic of time filter
> ![screen shot 2018-10-22 at 8 10 00 pm](https://user-images.githubusercontent.com/1361821/47291511-80a9f480-d636-11e8-806c-faba7d914ce5.png)
> 
> Therefore I prefer to use the function in 5.1.3 or remove extra time diff calculation in $__timeFilter and $___timeGroup. Or give user a option to enable or disable UTC time wrapper in macro functions. For my case I don't need to care about the UTC effect, local time is OK. (created_at is stored as UTC time and displayed as local time)

Agree, got the same problem after upgrading to 5.3.1 (and thanks God for yum downgade :) ) - my db (mysql) stores the local time as UTC (and that's not something I can change in foreseeable future) so the mentioned conversion completely disturbing the intended timerange. Even if I'd know how to fix it in query (and currently I don't), I've got about 100 queries to take care of and it's quite frustracting. I feel that an option for a previous datetime macros behavior is something that's easy to add and much less painful for us, Grafana users that got this problem. Please consider it...

**Comment by sanchomuzax** [comment]
Yes, this feature causes a lot of problems.

Data tables can not be converted because in many cases, the code can not be modified easily.

If the query is changed, then my previous hack proposal can not be applied anywhere.

**Comment by marefr** [comment]
After some more details in #13769 we've understood that for MySQL this is a bigger problem than we initially thought. There's a fix in master now which will be released in upcoming v5.3.3 release. For details, see #13769..

**Comment by sanchomuzax** [comment]
Thank you!!!

**Comment by alexkrasov** [comment]
Thanks!
