### ISSUE TITLE
Support configuring encrypt option when connecting to MSSQL datasource

### ISSUE THREAD

**Issue by ramiro** [grafana/grafana#13629]
### What Grafana version are you using?
5.2.4
### What datasource are you using?
mssql
### What OS are you running grafana on?
Linux / Ubuntu / 16.04
### What did you do?
Try to access a gamut of SQL Server installations, many of them not under our control.
### What was the expected result?
Ability to connect to the data sources impacting as least as possible their deployments or configuration.
### What happened instead?
We are unable to connect some MS SQL installations, getting the documented `Login error: EOF` error message and others in a similar vein about the connection being reset immediately.
 
After reading:
- Grafana mssql data source plugin code source
- `denisenkom/go-mssqldb` docs
- go-xorm docs

It's clear the 

> MSSQL 2008 and 2008 R2 engine cannot handle login records when SSL encryption is not disabled. Due to this you may receive an Login error: EOF error when trying to create your datasource. To fix MSSQL 2008 R2 issue, install MSSQL 2008 R2 Service Pack 2. To fix MSSQL 2008 issue, install Microsoft MSSQL 2008 Service Pack 3 and Cumulative update package 3 for MSSQL 2008 SP3.

note at http://docs.grafana.org/features/datasources/mssql/#known-issues is a copy paste from the `denisenkom/go-mssqldb` [README file](https://github.com/denisenkom/go-mssqldb#common-parameters).

But there is no need to suggest users to perform these SQL Server upgrades, as simply passing `encrypt=disable` as a component of the Xorm/go-mssql connection string would solve the connection problem, although at the cost of not using encryption to access the datasource database.

This *encrypt* connection parameter is described in the same README file.

Perhaps an additional field could be added to the Grafana data source configuration dialog which could help users to get these connections working.

We've solved this locally by changing our user name from `'john'` to `'john;encrypt=disable'`

**Comment by ramiro** [comment]
> although at the cost of not using encryption to access the datasource database.

Correction. It's the credentials which gets swithed to be sent in cleartext.  Queries data is alredy sent unencrypted as the Grafana data source plugin currently uses the default `encypt=false` value.

**Comment by marefr** [comment]
For contributors:

**Frontend changes needed:**
We would need a new setting [here](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/mssql/partials/config.html#L28) called `Encrypt` which should be a select box with three values, disabled, true, false, where false should be selected by default. The select box should be connected to `current.jsonData.sslmode`. There should also be a tooltip explaining what the different options means/does: 
> - disable - Data sent between client and server is not encrypted.
> - false - Data sent between client and server is not encrypted beyond the login packet. (Default)
> - true - Data sent between client and server is encrypted.
> 
> If you're using an older version of Microsoft SQL Server like 2008 and 2008 R2 you may need to disable encryption to be able to connect.

[Here's](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/postgres/partials/config.html#L30-L38) a code example of postgres datasource ssl mode setting.

**Backend changes needed:**
Update the following [code](https://github.com/grafana/grafana/blob/master/pkg/tsdb/mssql/mssql.go#L55) so that `encrypt=<disable/false/true>` is included in the connecting string. Take the value from `dataSource.JsonData.Get("sslmode").MustString("false")`, see example from postgres datasource [here](https://github.com/grafana/grafana/blob/master/pkg/tsdb/postgres/postgres.go#L49).

**Comment by ramiro** [comment]
I intend to work on this.

**Comment by marefr** [comment]
@ramiro that's awesome. Much appreciated. Please reach out if you'll need help and/or open PR and we work it out from there.

**Comment by ramiro** [comment]
Thanks @marefr PR opened
