### ISSUE TITLE
stackdriver user-metrics duplicated response

### ISSUE THREAD

**Issue by recet** [grafana/grafana#13691]
### What Grafana version are you using?
5.3.1
### What datasource are you using?
stackdriver
### What OS are you running grafana on?
GKE
### What did you do?
Try to graph user-metrics created using logs-based metrics
### What was the expected result?
single graph - as in stackdriver dashboards.
### What happened instead?
duplicated response/graph. same response, shown twice. 
```
response:Object
  results:Object
    A:Object
    refId:"A"
      meta:Object
      series:Array[2]
```

### If related to metric query / data viz:
`metricType:"logging.googleapis.com/user/metricName`
its a `counter` metric, with unit `1`

**Comment by sunker** [comment]
Thanks for the feedback @recet 
I've tried to reproduce this issue by manually creating a custom metric of type counter, but I'm not experiencing the issue with duplicated graphs. I'm afraid I need more information in order to investigate this properly. Could you please paste the whole json output of the custom metric that you have created? The json output could be retrieved using the [API explorer](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors/get) for the projects.metricDescriptors.get endpoint. The name field should be something like `projects/[project-name]/metricDescriptors/logging.googleapis.com/user/metricName`.

**Comment by recet** [comment]
Thanks @sunker . below is the json output.
`{
  "name": "projects/REDACTED/metricDescriptors/logging.googleapis.com/user/RE-DACTED",
  "labels": [
    {
      "key": "requestMethod"
    },
    {
      "key": "apiName"
    },
    {
      "key": "requestSize"
    },
    {
      "key": "responseSize"
    },
    {
      "key": "requestQueryType"
    },
    {
      "key": "responseElapsedTimeClient"
    },
    {
      "key": "log"
    },
    {
      "key": "clientIp"
    },
    {
      "key": "requestEtClientName"
    },
    {
      "key": "responseCode"
    },
    {
      "key": "responseElapsedTimeTarget"
    }
  ],
  "metricKind": "DELTA",
  "valueType": "INT64",
  "unit": "1",
  "type": "logging.googleapis.com/user/RE-DACTED"
}`

**Comment by sunker** [comment]
@recet I'm still not able to reproduce this unfortunately. Could you please post an image that displays the graphs in Grafana (including the query editor) and also one image that displays the graph in Stackdriver using the same kind of query?

**Comment by recet** [comment]
Sure. below is the screenshots. note that grafana shows the same result twice. one in green, and the other one in orange color. I´ve redacted the apiname. both graphs use alignment period of 5 min. 

<img width="1363" alt="screen shot 2018-10-18 at 10 27 54" src="https://user-images.githubusercontent.com/31758928/47141641-6fbd5400-d2c1-11e8-82b3-30662689d3c6.png">
<img width="1170" alt="screen shot 2018-10-18 at 10 31 29" src="https://user-images.githubusercontent.com/31758928/47141645-70ee8100-d2c1-11e8-9dd7-b328b6fbed8e.png">

**Comment by sunker** [comment]
@recet, in the Metrics Explorer, how many resource types are you able to see in the dropdown? 
![skarmavbild 2018-10-19 kl 14 54 38](https://user-images.githubusercontent.com/2388950/47219440-16335300-d3af-11e8-9199-99633ab354ae.png)

As you can see, I have only one resource type - `gce_instance`. I might be the case that you have two, and that's why you're seeing to time series graphs.

**Comment by recet** [comment]
Thanks @sunker. Yes, i see two resource types. Looks like my metric also is an audited_resource log. 

Do you know if it is possible to select a specific resource type on grafana? or is this something I should find a workaround to?

<img width="707" alt="screen shot 2018-10-19 at 15 09 46" src="https://user-images.githubusercontent.com/31758928/47220114-21877e00-d3b1-11e8-902f-7a5a05883ec0.png">

**Comment by sunker** [comment]
Okay, so now we know what the problem is. 

No there's no workaround at the moment, but I'll add possibility to filter on `resource.type` in the query editor and create a new PR. Maybe you can help me with testing? 

Thanks @recet

**Comment by recet** [comment]
That sounds great @sunker. Sure, i will help you however i can. Thanks.
