### ISSUE TITLE
Problem using GF_SERVER_ROOT_URL on Grafana 5.3.1 on Rancher 1.6

### ISSUE THREAD

**Issue by thomasboussekey** [grafana/grafana#13707]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?

5.3.1

### What datasource are you using?

Influx

### What OS are you running grafana on?

Contenerized version of grafana, found on: https://hub.docker.com/r/grafana/grafana/

### What did you do?

* Define environment variable `GF_SERVER_ROOT_URL` for container
* Restart of container
* Try to log on the URL `GF_SERVER_ROOT_URL` with a web bowser (in public and private mode).
    * The URL has the following pattern: **https://xxxx.yyyy.zzz.org/grafana53**
    * I don't see the impact of the variable declaration into the file `/etc/garafa/grafana.ini`
    * As we use **HAProxy** as reverse proxy for exposure, I tried different configuration into its configuration file without effect on the error message.
* I get the following error message:

```
 If you're seeing this Grafana has failed to load its application files
1. This could be caused by your reverse proxy settings.
2. If you host grafana under subpath make sure your grafana.ini root_path setting includes subpath
3. If you have a local dev build make sure you build frontend using: npm run dev, npm run watch, or npm run build
4. Sometimes restarting grafana-server can help
```

> As it's a custom error page, port **3000** of the `grafana` container is correctly exposed

* Error code is a 404 error message.
* Direct exposure, without final `/grafana53` works fine.

### What was the expected result?

Application running

### What happened instead?

Message relating configuration problem

### If related to metric query / data viz:
Not

**Comment by torkelo** [comment]
you need a reverse proxy that does the url rewrite for the /grafana53 subpath

**Comment by thomasboussekey** [comment]
Hello @torkelo 

Thank you for the quick answer provided.

Searching on the interent, for `HAProxy configuration`, I found [this page](http://docs.grafana.org/installation/behind_proxy/#haproxy-configuration-with-sub-path)

According to my configuration, I have updated the `HAProxy` to set:

```
frontend http-in
  bind *:80
  use_backend grafana53_backend if { path /grafana53 } or { path_beg /grafana53/ }

backend grafana53_backend
  # Requires haproxy >= 1.6
  http-request set-path %[path,regsub(^/grafana53/?,/)]

  server grafana53 grafana53.influxdata.rancher.internal:3000
```

But it didn't work.
My container name is **grafana53**, hosted into stack: **influxdata**, using rancher internal domain address: **grafana53.influxdata.rancher.internal**
As my rancher environment contains 4 hosts, use of localhost + port exposure will not work.

I'm not at ease with HAProxy config.

Can you tell me if you see something wrong or if there's an track to investigate on?

Thanks in advance,
Regards,
Thomas

**Comment by dev-e** [comment]
Please reopen. This message became very annoying after upgrade from 5.2.4 to 5.3.1. No changes on reverse proxy side were made. Our deployment of Grafana have no subpath in URL, just https://grafana.domain.com

**Comment by thomasboussekey** [comment]
Hello @dev-e ,

As issue had been closed by @torkelo , I cannot reopen it.

My installation is a fresh new install of `grafana 5.3.1`, in order to test the new  version, and expect a migration of the environment currently in `grafana 5.2.4`.

@dev-e , can you reopen the issue for me?

Thanks in advance,
Regards,
Thomas

**Comment by thomasboussekey** [comment]
Hello @dev-e ,

As issue had been closed by @torkelo , I cannot reopen it.

My installation is a fresh new install of `grafana 5.3.1`, in order to test the new  version, and expect a migration of the environment currently in `grafana 5.2.4`.

@dev-e , can you reopen the issue for me?

Thanks in advance,
Regards,
Thomas

**Comment by dev-e** [comment]
@thomasboussekey, I suppose @torkelo can reopen

**Comment by foscoj** [comment]
@torkelo Got the same problem in 5.3.1, could you please reopen this issue?

**Comment by torkelo** [comment]
This is super strange l, we have no other reports of this not working, and using a reverse proxy in front of grafana is super common. 

Can you try to perform network logs for the requests between haproxy and grafana? Is the url rewrite working? What is url of the the request that is sent to Grafana? Does the grafana log include the output that the root url setting has been set?

**Comment by foscoj** [comment]
Hi, my setup is a bit messy, running nginx natively on one rpi3 and grafana inside docker on a different rpi3.

`t=2018-11-28T12:48:20+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=http subUrl=/grafana socket=                                                                                                                        
t=2018-11-28T12:48:22+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/grafana/ status=404 remote_addr=192.168.178.29 time_ms=20 size=23082 referer=                                                                 
t=2018-11-28T12:48:22+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/grafana/public/build/vendor.d1f313cb0bbe86ea2d5f.js status=404 remote_addr=192.168.178.29 time_ms=11 size=23082 referer=https://home.jondor.com/grafana/                                                                                                                       
t=2018-11-28T12:48:22+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/grafana/public/build/app.d1f313cb0bbe86ea2d5f.js status=404 remote_addr=192.168.178.29 time_ms=11 size=23082 referer=https://mydomain.com/g
rafana/                                                                                                                          
t=2018-11-28T12:48:22+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/grafana/public/build/grafana.dark.css status=404 remote_addr=192.168.178.29 time_ms=12 size=23082 referer=https://mydomain.com/grafana/    
t=2018-11-28T12:48:22+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/grafana/public/img/fav32.png status=404 remote_addr=192.168.178.29 time_ms=11 size=23082 referer=                                             
t=2018-11-28T12:48:25+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/grafana/public/img/apple-touch-icon.png status=404 remote_addr=192.168.178.29 time_ms=11 size=23082 referer=                                  
t=2018-11-28T13:10:59+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/grafana/ status=404 remote_addr=192.168.178.204 time_ms=11 size=23085 referer=                                                                
t=2018-11-28T13:10:59+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/grafana/public/build/vendor.d1f313cb0bbe86ea2d5f.js status=404 remote_addr=192.168.178.204 time_ms=14 size=23085 referer=http://mylocalNGINXreverse_proxy:3000/
grafana/                                                                                                                         
t=2018-11-28T13:10:59+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/grafana/public/build/grafana.dark.css status=404 remote_addr=192.168.178.204 time_ms=13 size=23085 referer=http://mylocalNGINXreverse_proxy:3000/grafana/      
t=2018-11-28T13:11:00+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/grafana/public/build/app.d1f313cb0bbe86ea2d5f.js status=404 remote_addr=192.168.178.204 time_ms=11 size=23085 referer=http://mylocalNGINXreverse_proxy:3000/gra
fana/    `

this is the output of the docker log, which logs should I pull from the container?
subURL seems to be set correctly.

grafana.ini is set to:
`
protocol = http
domain = mydomain.com
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/`

protocol is set to http in grafana.ini, because cert-handling is done via nginx reverse proxy and grafana wants to see cert config if set to https.

Docker file sets the GF_AUTH_BASIC_ENABLED to false, otherwise the reverse proxy would get an error about that. Basic_Auth is done for all locations of nginx, so no need for that redundant part.

`FROM rycus86/grafana:armhf                                                                                                       
COPY ./grafana.ini /etc/grafana/grafana.ini                                                                                      
ENV GF_AUTH_BASIC_ENABLED false`

`docker run -p 3000:3000 --restart=always --name grafana-rpi -d grafana/cluster-local`

nginx config is as simple as described here http://docs.grafana.org/installation/behind_proxy/:
`    location /grafana/ {                                                                                                         
        proxy_pass         http://grafanaMachine:3000;                                                                                 
        proxy_set_header Host $host;                                                                                             
} `

**Comment by kesor** [comment]
Future versions of Grafana will "just work" without this requirement for a rewrite rule. https://github.com/grafana/grafana/pull/17048
