### ISSUE TITLE
Grafana-Templating Issue

### ISSUE THREAD

**Issue by th936** [grafana/grafana#1370]
There a "*" in variable values when I create templating in Grafana, that is really noise. for example:

variable name: test
variable values query: Test.abc*
variable values will be shown: *, abc01, abc02, abc03..
All option: check

But actuall, there are many other servers besides abc* in Test. So when I select all about $test, all servers will be shown on all graphs. 
Is it way to delete "*" from variable values?

**Comment by torkelo** [comment]
You get the wildcard option because you have enabled the "All" option and the all option mode is probably set to wildcard. 

![image](https://cloud.githubusercontent.com/assets/10999/5854411/cb0da526-a22d-11e4-9a21-a3879e865b72.png)

If you do not want a wildcard for the "All" option, then you can pick glob (if you use graphite), or regex values (if you use influxdb). In those modes the All option will be a list of all the values in glob or regex format.

**Comment by th936** [comment]
Thanks a lot.

**Comment by 3fr61n** [comment]
Hi

I'm trying to use template variables + influxdb 0.8, in order to replicate the scenario found at http://play.grafana.org/dashboard/db/influxdb-templated-queries.

But it seems that using any regex (like $server = backend.*) is working in play.grafana.org, and in grafana 1.9.1, but it is not working in 2.1.0-pre1

Below I'm attaching the template variable definition

<img width="777" alt="screen shot 2015-07-14 at 12 44 10" src="https://cloud.githubusercontent.com/assets/6707509/8671520/15181ef0-2a26-11e5-8477-34faed4a912e.png">

Is there any way to troubleshoot or knob to fix it?

Thanks in advance
Efrain

**Comment by torkelo** [comment]
what is wrong? you get seville and valencia, do you expect something else? what is returned from influxdb?

**Comment by 3fr61n** [comment]
The problem is that the template variable does not accept something like sev.*  (it order to match seville) or val.* in case of valencia.

As you see in the picture below, I'm starting to write 'sev' and the menu below filter by this string. (So far it's ok)

![screen shot 2015-07-14 at 15 14 37](https://cloud.githubusercontent.com/assets/6707509/8673970/282833da-2a3b-11e5-8313-a82016b128b8.png)

But at the moment I begun with the regex '.*' all possible options disappear  

![screen shot 2015-07-14 at 15 14 56](https://cloud.githubusercontent.com/assets/6707509/8673969/25b8a3b4-2a3b-11e5-9ef5-52a4f2891d40.png)

Hope this information could help.
Thanks in advance.
Efrain

**Comment by torkelo** [comment]
well the auto complete / typeahead does not support regex , not sure why you expect / want that

**Comment by 3fr61n** [comment]
In my scenario, I have different groups of host, all hostname in the same group starts with the same letters (like site1-1, site1-2, site2-1 and site2-2) so I only have one dashboard with a template variable ($host_regex), and it's pretty easy to analyse and correlate info in one host, or if required (using the same dashboard) select all related host, just changing the regex.   (sometimes the regex should be site1.* or in other cases .*-1)

Is there any way to disable the auto complete?, because the influxdb does support that regex, but somehow the grafana is not accepting that regex

Thanks for your help
Efrain

**Comment by torkelo** [comment]
yea, I need to add back a feature that is not present in 2.1 (but is in 2.0),  in 2.0 you could add custom values to a template variable (that is set a value even though it is not included in the list of possible options). This is not possible in Grafana 2.1 (master) with the new multi select dropdown selector

**Comment by torkelo** [comment]
added new issue for this: https://github.com/grafana/grafana/issues/2344

**Comment by 3fr61n** [comment]
Thanks !!!
