### ISSUE TITLE
current should always be most recent value, not an average

### ISSUE THREAD

**Issue by bh9** [grafana/grafana#13713]
### What Grafana version are you using? 
4.6.2
### What datasource are you using?
Reproduced with both prometheus and influxdb
### What OS are you running grafana on? 
Ubuntu 12.04
### What did you do? 
zoomed out... 
### What was the expected result? 
current value should stay the same
### What happened instead? 
current value became the average of the last 3 measurements once >200 measurements were in the time range
 
possibly related to #11075

**Comment by torkelo** [comment]
This is related to how time series queries works (they aggregate data in order to not return millions of data points that will hang your browser). 

If you want the last value to stay the same you can change the aggregation function (influxdb has last, not sure what the equivalent function is in Prometheus). 

of you query has an avg aggregation and you zoom out every value will be a avg of underlying measurements

**Comment by bh9** [comment]
I hover over the end of the time series, the value is still correct, but now disagrees with the current measurement. From your description, the opposite would happen: 
![screenshot from 2018-10-17 16-12-45](https://user-images.githubusercontent.com/23195777/47096774-cfffb780-d227-11e8-91dd-bc9d453e5b94.png)
![screenshot from 2018-10-17 16-13-55](https://user-images.githubusercontent.com/23195777/47096777-d2621180-d227-11e8-9733-859202ca93fa.png)
Here, the current (most recent measurement) value is 10, but the value=current (big number) display says 8. The time series still says total is 10

**Comment by torkelo** [comment]
The singlestat has a different time interval / step by default so the query could be different, check query inspector. Make sure the aggregation function is the same etc (need to be last to be time range agnostic)
