### ISSUE TITLE
Feature Request: Can we get the smooth=csplines function of OpenTSDB

### ISSUE THREAD

**Issue by HellDesk** [grafana/grafana#1376]
Sometimes if you have lots of datapoints in a graph it can get quite spiky, if we can get access to use smooth=csplines in OpenTSDB this will make things more readable in some cases.

Thanks

**Comment by okor** [comment]
:+1: smoothing / splines would be very very nice

**Comment by utkarshcmu** [comment]
https://github.com/flot/flot/pull/872 - Once this pull request is merged in flot, hopefully, we can use it too.

**Comment by torkelo** [comment]
@utkarshcmu that is optimistic, given the PR has been open since 2012!

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
