### ISSUE TITLE
Export dashboard, options to templatize data source names (disabled by default)

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#13781]
Currently the export modal will always will create a "sharable dashboard" with extracted "inputs" and requirements. 

This makes this json not usable with normal dashboard save/update API and with provisioning. Something that is very unclear and confusing.  

I suggest we make the export modal have a checkbox (unchecked by default). 

* [ ] **Export for sharing** : Useful for sharing dashboard publicly on grafana.com. Will templatize data source names. Can then only be used with the specific dashboard import API. 

If unchecked the exportor should not extract requires & inputs. 

https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/export/exporter.ts#L31

I also think we can add more info to the export tab. When exporting a dashboard there's no information how to use the exported data. We have a dead end. Maybe link to the Export and Import in the docs?****

**Comment by DanCech** [comment]
It might make more sense to change the way that the export/import works so that instead of templating the data sources at export time we inspect the dashboard at import time and give the user the ability to select a data source for each named data source found in the dashboard (defaulting to the data source with the same name if it's present).  That way a saved dashboard would have the same structure as an exported dashboard, and we would avoid the confusion.

I would still like to have the `__requires` array to support Grafana.com, and would like to see the datasource plugin for any datasource variables included in it.
