### ISSUE TITLE
Remove PhantomJS

### ISSUE THREAD

**Issue by jschill** [grafana/grafana#13802]
Tasks:
- [ ] Deprecate PhantomJS #18914
- [ ] Migration path for users upgrading when PhantomJS is removed? Deprecate first and give users time to switch to image renderer plugin and removing PhantomJS in the major/minor release after?
- [ ] Handle case when Grafana doesn't have any image renderer setup
- [ ] Blog post
- [ ] Update documentation

**Comment by daniellee** [comment]
ref #11078

**Comment by torkelo** [comment]
We already use puppeter in the image rendering plugin :) 

https://github.com/grafana/grafana-image-renderer

The only thing that remains is to figure out how to make it easy to install the plugin & bundle it in the official docker container, write docs. Then I think we can remove the built in phantomjs version & binary

**Comment by jan--f** [comment]
Is there the possibility of getting this in before 6.0? Or is there a timeframe for 6.0?

I realize that such a change is not minor but phantomjs 2.1.1 is rather old and in many cases links against openssl 1.0 (not sure about binary shipped with grafana though) which is also end of life. While the security implications might be minimal (though they might not be) it is quite a problem for distro packaging where shipping prebuild binaries is a no-go.

**Comment by torkelo** [comment]
We are looking at doing this, problem is that upgrading to 6.0 is then going to break all server side rendering and alert images, user will have to install our new headless chrome plugin that requires nodejs . So we need to write some guides for how to install this and with docker we can bundle it in the image

**Comment by jan--f** [comment]
@torkelo I understand. Maybe it makes sense to add the option to build Grafana without phantomjs before version 6, something like "flick this switch, but you're on your own"?

Background is distro packaging; OpenSUSE is currently unable to provide official (as in "in the official repos") Grafana builds, due to phantomjs' dependency on openssl1.0. If Grafana could be build without this dependency I'm sure packaging could be figured out and that could feed back into upstream Grafana.

**Comment by c0d1ngm0nk3y** [comment]
@torkelo Hi, what is the current state/plan on this? We would really like to use the grafana docker container, but the security scan looks very bad due to phantomjs and the used openssl and libicu).

Could it be an option to remove phantomjs at least for the docker container and bundle it with nodejs?
