### ISSUE TITLE
Don't remove graph when datasource is busy.

### ISSUE THREAD

**Issue by rvdwenden** [grafana/grafana#1383]
When a datasource, in our case Graphite, is busy to respond in time, the graphs in our Grafana dashboard turn 'black' now (plus showing am orange triangle in the left top corner).
Wouldn't it be nicer that in case of a time-out, the current graphs stay on the dashboard, including the orange warning triangle.
BTW: This is the same behaviour as the singlestat widget: this widget never turn 'black', it always shows the last known data.

**Comment by torkelo** [comment]
not sure if that is good, the red error triangle could be missed and a user might mistake the data as current.

**Comment by rvdwenden** [comment]
The idea is to show the red error triangle AND showing the existing graph (just like the singlestat widget behaviour).
(by the way: Is there a way to set timeout period for a datasource request?)

**Comment by jorisdegeringel** [comment]
Would also like this behaviour. It could be a recebt datapoint shows us valuable information (like a failure) but a later time-out will make us notice this later (if it all) because of the 'black out'.

**Comment by maddenca** [comment]
>>BTW: This is the same behaviour as the singlestat widget: this widget never turn 'black', it always shows the last known data.

I actually consider this behavior with singlestat a bug and would prefer to have it shown N/A vs. making changes for graphs panels as well.

My use case is when using templates if I select a different item in my template, and there is an error from Graphite, it does not refresh to N/A but stays showing the old data (with a ! in the corner) for the previous template item which can be confusing.  In my case an error occurs because I use a function like maxSeries on a metric that might not exist for that specific selected item, but there could be other reasons of course.  

I'm adding my 2 cents here for triage to the best solution.  If I need to open an issue for changing behavior of the singlestat panel in case of error please let me know.

**Comment by torkelo** [comment]
@maddenca yes, please do that, I agree that the singlestat should not show a value if the last query failed

**Comment by rvdwenden** [comment]
There is also a link with this Graphite error:
Graphite API sometimes yields a no-datapoints.png image as a response (rather than a JSON response) :
https://github.com/graphite-project/graphite-web/issues/576

Seems to be fixed in newer versions of Graphite.
