### ISSUE TITLE
Grafana creates session files on HTTP API calls

### ISSUE THREAD

**Issue by radeklesniewski** [grafana/grafana#13841]
Hi,

I'm using Grafana v 5.2.3 deployed in OpenShift. Alongside, there is custom automation application working as a sidecar and is using HTTP API for dashboard & user provisioning. I've spotted, that Grafana instance is creating session files per every HTTP API request - is it expected behaviour?

After some time, we are getting below information in logs:

"t=2018-10-26T14:24:01+0000 lvl=eror msg="Failed to start session%!(EXTRA *os.PathError=open /go/src/github.com/grafana/grafana/data/sessions/0/e/0e8596e37b04d121: no space left on device)""

I'm not sure if it should work this way, creating session file after every HTTP API request quickly saturates disk available space. Is there any possibility to disable creation of session files for HTTP API calls?

What Grafana version are you using?
v 5.2.3
What datasource are you using?
Prometheus
What OS are you running grafana on?
Openshift 3.9

**Comment by torkelo** [comment]
If you authenticate via api key or basic auth no session will be created, otherwise you will have to pass the session cookie back in subsequent requests if you want to avoid creating many sessions 

There is already a /api/health endpoint for use with kubernetes liveness checks that does not create sessions either
