### ISSUE TITLE
v5 regression : Row bar - allow to fully hide the row line (row title + icon + area )

### ISSUE THREAD

**Issue by Daryes** [grafana/grafana#13856]
Version : migration from 4.6.3 to 5.3.2

This was previously available in v4.x and older.

The purpose behind is to reduce the amount of space taken by the row line and still allowing to regroup existing panel in a group using a (hidden) row.  
It also has the ability to prevent templated panels to overflow on different themed panels.  
Another use is when an existing dashboard is duplicated to create a new one, unwanted panels grouped in a theme using a row can be deleted in a single click by removing the row itself.  Not being able to hide the row line refrains from using such trick.

**Comment by torkelo** [comment]
In v5 the dashboard layout engine / grid system no longer requires rows. You can create any possible layout without rows. 

The only purpose rows now serve is to have collapsible sections in long dashboards and is also mainly there for backward compatibility with v1-v4.   We need the row title to be visible in order to get rid of the hard to find / hidden row menu in prior versions of Grafana.
