### ISSUE TITLE
Zoom in and out on a graph panel changes values

### ISSUE THREAD

**Issue by tekkeitserktok** [grafana/grafana#13975]
### What Grafana version are you using?
* v5.3.2

### What datasource are you using?
* Elasticsearch

### What OS are you running grafana on?
* Ubuntu 18.04 LTS

### What did you do?
* Tried to zoom out and in on a graph panel

### What was the expected result?
* Expected result was to see the same "Max" value on a response time

### What happened instead?
* Initially, max value was 60s. But when I zoomed in, it changed in 120s (the true value, verified when watching the raw datas from elasticsearch).

![capture du 2018-11-06 11-06-03](https://user-images.githubusercontent.com/459936/48057734-0f7d4c00-e1b5-11e8-88ba-492dd0c027d4.png)
![capture du 2018-11-06 11-05-40](https://user-images.githubusercontent.com/459936/48057736-1015e280-e1b5-11e8-865f-0e358c622731.png)

**Comment by torkelo** [comment]
the value shown in Graph and legend depends on your Elasticsearch aggregation function (Max, Min, Avg) and your group by time interval.

**Comment by torkelo** [comment]
thanks!

**Comment by baiwfg2** [comment]
@torkelo  Hi, torkelo. I met with the same problem in prometheus+grafana system. When I use `rate` with different `interval`, the maximum value could change hugely.  Or, with the same `interval`, just zoom in, the maximum value also change. 

So in order to get true insight to the `real value` and not to be mislead by `rate` or `irate` or different `interval`, I should zoom in as much as possible. The more I zoom in, the more correct my data is. Is that **correct** ?
