### ISSUE TITLE
Encrypt/obfuscate bind_password in TOML file

### ISSUE THREAD

**Issue by J-den-Boer** [grafana/grafana#13973]
### What Grafana version are you using?
5.2.4
### What OS are you running grafana on?
Windows 2012R2

Is it possible to encrypt or obfuscate the bind_password for connecting to LDAP, or simply using the credentials of the LDAP user the Grafana Server is running under? There is a policy in the company that does not allow plain text passwords in configuration files, even though it only has read permissions. 

This would make my current configuration of the TOML file easier and more simplistic, than relying on the login account of the user and password to connect to LDAP for authentication and locating the correct permissions.

**Comment by J-den-Boer** [comment]
When using the bind_dn & bind_password the password is in plain text. The question is if it is possible to not use a plain text password in the file. Is it possible to "encrypt" the password.

**Comment by marefr** [comment]
Yes I understand your feature request. Just wanted to know if you're aware of the single bind solution where you don't need to use the `bind_password`, only the `bind_dn`.

**Comment by J-den-Boer** [comment]
I am aware of this option and currently I am using this feature (maybe not the the most optimal extend). Currently not all my users are in the same node. For example I have multiple user OUs
bind_dn = "cn=%s,**OU=D1**,OU=Production,OU=Users,OU=Users,DC=ad,DC=company,DC=net"
bind_dn = "cn=%s,**OU=D2**,OU=Production,OU=Users,OU=Users,DC=ad,DC=company,DC=net"

I'm not aware if I can use a wildcards or another notation to combine the line above.

**Comment by marefr** [comment]
I tried to use an OR-search expression but not sure it works. At least I don't get any errors so please try this:

```toml
bind_dn = "cn=%s,(|(OU=D1)(OU=D2)),OU=Production,OU=Users,OU=Users,DC=ad,DC=company,DC=net"
```

**Comment by marefr** [comment]
Alternatively if you can, skip `OU=D*` and add the OR expression to the `search_filter` to filter out users only belonging to certain nodes (OU's).

**Comment by J-den-Boer** [comment]
For me the or expression did not work. But thank you very much for your help. Is it possible to add the feature request for "encrypting" the bind_password?

**Comment by marefr** [comment]
Sure, but it doesn't make any sense since you still need to have the encryption key in the configuration file.

**Comment by marefr** [comment]
@torkelo do you have any more suggestion on how to configure this for supporting a set of OU's?

**Comment by virasatkhan** [comment]
That did not work for me. However, based the following worked. 'AI' is my Domain.
`bind_dn = "AI\\%s"`

**Comment by jamshid** [comment]
Seems a best practice is to allow things like `bind_password` to be specified via a secrets file? It's sometimes preferred over putting secrets in environment variables.

So if `ldap.toml` contains `bind_password_secret_file=/etc/secrets/grafana/bind_password` instead of `bind_password` then the password is read from that file. 
The deployment system e.g. https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets or https://docs.docker.com/compose/compose-file/#secrets handles making the secret file available to the container.
Btw I guess some secret managers only make them available via a rest api like https://www.vaultproject.io/, but at least that can be put into an env variable.

**Comment by Deepti-lab** [comment]
Hi,

I too have a requirement to encrypt the LDAP password. My Grafana version is 6.0 and LDAP uses SSL. As per above comment if I use the below - 

So if ldap.toml contains bind_password_secret_file=/etc/secrets/grafana/bind_password instead of bind_password then the password is read from that file.

Then how the /etc/secrets/grafana/bind_password file will look like?

**Comment by GFLEMING133** [comment]
Is there a way I can put in a feature request for what @jamshid commented? Using a docker secret is definitely the preferred way to deal with this.

**Comment by justinmchase** [comment]
I came here to also request the toml config file support the addition of specifying which file contains the password. That would allow me to mount the secret into a file and maintain that seperate from this configuration.

**Comment by dbaboy** [comment]
With Apache, we are using GnuPG to create a symmetric encryption key and store that in a secure file. Apache then allows the 'exec' directive to allow decrypting the encrypted key.
AuthLDAPBindPassword "exec:/usr/bin/gpg --quiet --batch --passphrase /path-to-file -d /path-to-file.gpg"

Something like this will be a good to have feature.

**Comment by linoman** [comment]
This can be achieved by variable expansion. Take a look at the comments inside the example configuration.

https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/ldap/#grafana-ldap-configuration
