### ISSUE TITLE
New version keeps hanging Google chrome

### ISSUE THREAD

**Issue by calston** [grafana/grafana#1400]
Since the last release of Grafana for some reason when typing in the series name Grafana frequently hangs completely in Chrome, I presume some bad blocking call down to influxdb's series list (we have a *lot* of series).

**Comment by torkelo** [comment]
Thats bad, it could either be because influxdb is returning millions of series that causes chrome to hang (there is no blocking call so the only cause for a hang is huge data volumes that is to much for the chrome js engine to handle). Can you open chrome dev tools and inspect the query to influxdb and the response from influx? How long does the influxdb series list take, and how many series are returned? 

I know many have complained that the influxdb "list series" query can be incredibly slow when having multiple series. Something that is being fixed in InfluxDB 0.9

**Comment by calston** [comment]
Probably is Influx, while moving to new Grafana we also had to adopt the slightly less horribly broken version of Influx which uses LevelDB so that could be it.

**Comment by viljemskornik** [comment]
I'm experiencing the same issue. And I'm thinking one way of helping out from the Grafana side would be not to list metrics for every key change but rather wait for x amount of time before listing metrics and reset the timer for each key stroke. 

That way when you're typing this.and.that.and.server.cpu.avg it would only make one or two list series requests and since the result would be way smaller Chrome shouldn't freeze.

**Comment by calston** [comment]
That probably would be a good idea, start 200ms second timer canceled by key down after key up or something and then query. I think Influx also accepts a limit and pagination query doesn't it?
