### ISSUE TITLE
enhancement: anonymous role in dashboard permissions

### ISSUE THREAD

**Issue by faxm0dem** [grafana/grafana#14026]
It would be useful to add the possibility to change permissions for a dashboard for anonymous logins.
Right now, in order to make an organization's dashboards visible to anonymous users, without granting view to *all* dashboards is to duplicate it into the anonymous org.

**Comment by sunker** [comment]
One way to achieve this would be to make sure that all dashboards that you don't want to be accessible for anonymous users are put in folders and that they belong to team. Dashboards that should be accessible to anonymous users are preferably put in the general folder, hence it's not possible to add permissions on that folder. 

It's also worth pointing out that anonymous users have a default role, and this role could be defined in the configuration file, e.g `org_role = Viewer`. Knowing what role the anonymous user has, permission to a specific folder can be restricted by removing the org_role, e.g ´Viewer´ from the list of permissions on that folder.

Since there's a workaround for this, we don't see any reason to implement functionality to change dashboard permissions for anonymous users. 

See more on authentication [here](http://docs.grafana.org/auth/overview/)
