### ISSUE TITLE
Support auth via URL params in plugin routes

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#14088]
DataDog datasource requires API key which should be passed as GET parameter:
https://docs.datadoghq.com/api/?lang=bash#authentication

```
curl "https://api.datadoghq.com/api/v1/validate?api_key=<YOUR_API_KEY>"
```

So it's not possible to use plugin routes to proxy API requests transparently without adding key on the frontend. In order to make queries in secure way, plugin routes should be like this:

```json
"routes": [
{
"path": "datadog",
"method": "GET",
"url": "https://api.datadoghq.com/api/v1",
"urlParamsAuth": {
"params": {
"api_key": "{{.SecureJsonData.apiKey}}",
"app_key": "{{.SecureJsonData.appKey}}"
}
}
}
],
```

and frontend request `datadog/events/${event_id}` should be transformed on backend to `https://api.datadoghq.com/api/v1/events/${event_id}?api_key=${api_key}&application_key=${app_key}`.

**Comment by torkelo** [comment]
Can't you put it in the url directly? 

```
  "routes": [
    {
      "path": "datadog",
      "method": "GET",
      "url": "https://api.datadoghq.com/api/v1?key={{.SecureJsonData.apiKey}}", 
    }
  ],
```

But someone reported on the community site that it does not work, even though there is a unit test for that

**Comment by alexanderzobnin** [comment]
I think it doesn't work because we need different endponts like `api/v1/evens` or `api/v1/metrics`.

**Comment by daniellee** [comment]
@torkelo it only got added very recently but it definitely works. See Azure Data Explorer datasource for an example: 

https://github.com/grafana/azure-data-explorer-datasource/blob/master/src/plugin.json#L30

**Comment by alexanderzobnin** [comment]
Yes, currently routes can't add params to the end of the final endpoint url.

**Comment by MikeMutual** [comment]
I am wondering if this open request will solve my problem. I am trying to login to a Remedy account, and the way to do that is sending in the username and password as parameters. (Link to the documentation for this: https://docs.bmc.com/docs/ars91/en/login-information-609071516.html).

I want the username and password to be secure, so I am using SecureJsonData to store those pieces of data. I have tested using SecureJsonData and know that the credentials are stored correctly, but when I set the query parameters as the SecureJsonData values (SecureJsonData.username and SecureJsonData.password), it's as if the parameters don't exist.

Hopefullly this open request will solve my problem that would be great, but either way could someone let me know?

**Comment by alexanderzobnin** [comment]
@MikeMutual This feature related to GET params only (which are a part of URL string). POST params can't be passed in this way. I have the same problem with Zabbix - in order to get auth token, you should invoke `/login` request with username and password as a POST params, so it will be exposed to the frontend anyway.

**Comment by mitchmckenzie** [comment]
@alexanderzobnin   : I am working with @MikeMutual  on this issue. We are able to get the token ok using POST however we're unable to store the login credentials using SecureJsonData because the variable substitution isn't being done on the backend due to url params not being supported in the route config.  We are able to do the authentication using params passed in the body of the request or the url using verb POST. (body: username=foo@password=bar OR authURL?username=foo@password=bar).  What we want to be able to do is store the username and password in the secure json blob and have the variable substitution happen in the backend before the auth request is sent. I was unable to get the secure json substitution to work using the "data" attribute in the route config using something like : "routes":[ { ... data : "username={{SecureJsonData.remedyUsername}}&username={{SecureJsonData.remedyPassword}}" ... } ]
