### ISSUE TITLE
drop fields by field value

### ISSUE THREAD

**Issue by caodianlong** [grafana/grafana#14119]
My program (with spring boot) has lots of functions, we collect the function called count to the influxdb.
It has hundreds of field keys in a measurement, like:  functionA.count, functionB.count, functionC.count, functionD.count......and so on.  I would like to show the field witch is's value more than 0 with graph or table panel in grafana.  How can I drop the field witch value is 0.

Please include this information:
### What Grafana version are you using?
V5.3.2
### What datasource are you using?
influxdb V1.6.4
### What OS are you running grafana on?
CentOS 7
### What did you do?
using this metrics in graph panel:  select last(/count/) from test where $timeFilter
It returns hundreds of field keys
### What was the expected result?
drop the field witch value is 0
### What happened instead?
graph panel draw lines for every field, it cost too much time and hard to see lines clearly

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Try the influx community site as well since what you're describing is a problem with the influx query language support. If you had a function tag with A, B, C, D and a field count instead it should be very easy to just group by tag and filter out all zero values.
