### ISSUE TITLE
dashboard API doesn't contain repeating rows and repeating panels

### ISSUE THREAD

**Issue by LinuxGit** [grafana/grafana#14117]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
4.6.3
### What datasource are you using?
prometheus
### What OS are you running grafana on?
CentOS 7.3
### What did you do?
visit dashboard API: http://grafana_IP:3000/api/dashboards/db/:slug
### What was the expected result?
output current dashboard' real JSON Model, contain repeating rows and repeating panels, as well as scopedVars.
Like the JSON content of View JSON button on the dashboard.
### What happened instead?
JSON doesn't contain repeating rows.
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

Does any other other API that contains repeating rows and repeating panels, as well as scopedVars.

**Comment by marefr** [comment]
Works as expected on Grafana v5.3.3 given you've saved a dashboard with repeated rows and selected variables. Example dashboard: https://play.grafana.org/d/000000153/repeat-rows?orgId=1, by api: https://play.grafana.org/api/dashboards/uid/000000153.

But since the actual repeat is made in the browser and not the backend your described problem is currently never going to be easy to solve so closing this for now.
