### ISSUE TITLE
Embedded graphs (iframe) not rendering anymore

### ISSUE THREAD

**Issue by SquareBeard** [grafana/grafana#14284]
### What Grafana version are you using?
5.4.0
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Debian 9
### What did you do?
Upgraded from 5.3.4 to 5.4.0
### What was the expected result?
Embedded graphs would not be impacted.
### What happened instead?
Embedded graphs are not rendered. Instead a red exclamation mark appears with this message: `Invalid dimensions for plot, width = 422, height = 0"`

 I'm using the iframe generated by Grafana and it has a width and a height: `<iframe src="....?orgId=1&panelId=6&from=1543791600000&to=1543877999999&theme=dark" width="450" height="200" frameborder="0"></iframe>`

**Comment by jjose122** [comment]
I have also faced similar issue after 5.4.0 update. I get a red exclamation mark without any message. 

What works for me is, when i change the method to POST/GET and then switch again to iframe then the chart appears. 
But after saving the dashboard when i refresh the page, it doesn't work.  Also the AJAX Display tab "Mode" option is getting reset to "Escaped Text" instead of iframe.  When i change the Method in Request tab to POST/GET to again iframe. Everything works but fails after the page refresh.

**Comment by skladd** [comment]
Same for me for embedded panels on Debian 9, I had to downgrade via `sudo apt-get install grafana=5.3.4`
