### ISSUE TITLE
Explore: Logging, first time user with empty query field. 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#14290]
It's not clear what to do when you load a logging data source. 

Tried writing a query but got an error:

![image](https://user-images.githubusercontent.com/10999/49396839-646f9c00-f73a-11e8-8dec-eebe39db63b9.png)

I guess you need at least one label filter? Need to make sure this is clear. Another UX issue is lables and metrics button. No visual indication that those are dropdown buttons. It also not clear that selecting a label clears the query, thought it would add the label to the query. But that might very well be something you just learn (like clicking the panel title for the panel menu).

**Comment by davkal** [comment]
On a high level: Having to select a stream first is in line with other logging products, so I'm not too worried there. 

Agreed, the affordance is not ideal. You need at least one label in the selector to get a stream. So we somehow need to encode this in the UI. Then you can filter further by writing regex after the selector.

My proposal is to have 2 fields instead of 1: A selector field that is enabled first. The second field is for regex and will stay disabled until you have selected a label for the first field.

The cheat sheet gives you ideas what to do, but since you just went ahead and typed a query, it might need additional hints on how to get started.
