### ISSUE TITLE
[Feature Request] Add minimum panel height property to dashboard JSON

### ISSUE THREAD

**Issue by DarrenWhiteABB** [grafana/grafana#14334]
I would like to be able to set a property in the dashboard JSON that allows me to specify the minimum height for a panel. I require this as some of my custom developed panel plugins have a minimum usable height.

So I would be able to set the actual width and height for the panel in the gridPos object as well as being able to set an optional minHeight property that would stop an end user from making the height of this panel less than the value specified.

**Comment by torkelo** [comment]
you could specify this in gridPos in the dashboard json (at import & load time) but it would not work if you set this from your plugin and runtime (for new panels). As this is too late to communicate / set properties to the grid. 

Would it be ok if it only worked if the property was defined during dashboard load?

**Comment by DarrenWhiteABB** [comment]
Yes. This would be some predefined property set in the dashboard JSON for the panel. We have no use case which would require this value to be changed dynamically after the initial render of the dashboard.

**Comment by CME64** [comment]
in fact I have thought of this from a similar perspective. I found it difficult to show the dashboard on different screen sizes even though its UI is responsive. Sometimes it makes some panels smaller than they could render anything and sometimes they're just not fitting the full screen leaving a huge empty area that doesn't look good as a dashboard. I know this is difficult to solve dynamically because it may affect how the original design looks like in the end result.

I think this could be solved using user defined offsets for flexibility. e.g. setting a 3:5 for width meaning that it can shrink up to 3 grid squares and expand up to 5 horizontally, and the same for vertical/height settings. however 0:0 doesn't allow the panel to be scaled dynamically. what do you think? does this solve the problem?

**Comment by DarrenWhiteABB** [comment]
Hi @CME64. I agree that what you described would be a good additional feature for Grafana dashboards to support but for my use case I simply require a property which allows me to specify a minimum height for a panel. A height:width ratio property would not resolve this issue.
I need to be able to specify a minimum height for each panel in the JSON for my dashboards in a particular application I am developing which contains several custom panel plugins. This application is not being developed for mobile devices so I am not currently concerned about cross device support. Although I can imagine some use cases for a property similar to the height:width ratio you described for my particular instance a simple minHeight property alleviates the issues I'm having.

**Comment by CME64** [comment]
@darrenwhiteabb I understand what you described, but you missed the point. The solution I suggested isn't about aspect ratio, the x1:x2 property in the example is just for one dimension acting as a relative settings for minimum and maximum width or height

**Comment by DarrenWhiteABB** [comment]
@CME64 Sure. I understand now that the ratio you described on relates to only one dimension. In my case however I am only concerned with the minimum height. 
Would your solution remove the width and height properties from the gridPos object for each panel in the JSON for the dashboard? Or, for example, could you specify the actual height as 4 then using the solution you suggested define a ratio of 2:3 for height meaning that this panel can have a minimum height of 2 and a maximum height of 7?
To meet my business case I, at a least, need to be able to somehow declare a minimum height per panel.  The solution you proposed may be a bit more elegant than adding properties for minHeight, maxHeight, minWidth, etc and also provide extra flexibility in future in such cases where the maximum height must also be constrained.
