### ISSUE TITLE
CloudWatch data source - variables' values surrounded with braces in request sent to AWS

### ISSUE THREAD

**Issue by the0ffh** [grafana/grafana#14451]
### What Grafana version are you using?
5.2.4 and 5.3.2
### What datasource are you using?
cloudwatch
### What OS are you running grafana on?
osx
### If related to metric query / data viz:
![image](https://user-images.githubusercontent.com/26150100/49809083-53d4ac80-fd5e-11e8-99b2-0ef748fa4bde.png)

Please notice 'request.data.queries[0].metricName' in query inspector being surrounded with braces. 

The issue is present at least in v 5.24 and 5.3.2

**Comment by sunker** [comment]
@mtanda are you aware of this?

**Comment by mtanda** [comment]
I success to replicate the behavior.

It might caused by specifying `Multi-value` for the template variable.
![image](https://user-images.githubusercontent.com/224552/49928214-0776a180-ff03-11e8-8935-a29cb306b5c9.png)

CloudWatch datasource expect `Multi-value` is off for MetricName variable.
Grafana seems to make Array whether the count of selected value is only one.
It make value surround with brace.
![image](https://user-images.githubusercontent.com/224552/49928158-e31ac500-ff02-11e8-8a56-f581b5ea25b3.png)

To prevent such behavior, datasource can check the count, but I'm not sure it is good idea.
Anyway, the `Multi-value` is not supported, please check template variable setting.

**Comment by mtanda** [comment]
> Can multi-value support be expected anytime soon?

Depends on how many interests for the feature.
And I don't have any privileges to merge the feature for the main line.

The CloudWatch datasource expand dimension template variables.
https://github.com/grafana/grafana/blob/v5.4.2/public/app/plugins/datasource/cloudwatch/datasource.ts#L435-L459
Support multi-value for MetricName is technically possible.

If you really want the feature, change this issue title to feature request, and wait for getting interest.

**Comment by joedj** [comment]
+1 to adding good multi-value support for CloudWatch.  We are able to use multi-value sometimes, but not with e.g. multiple variable dimensions on a single graph, where the `{}` cause problems.
