### ISSUE TITLE
Grafana 2.0 Only own/group Dashboards visible in Dashboard owerview

### ISSUE THREAD

**Issue by phagedorn** [grafana/grafana#1447]
As customer i only want to see my own dashboards in the dashboard overview or the dashboards in my usergroup

**Comment by torkelo** [comment]
@phagedorn could you describe in more detail the use case you have? 

1. Is it only for filtering purposes so users do not have to see dashboards they most probably are not going to be interested in? 
2. Or is it because of security concerns that some users should only be able to see their own groups dashboards? 
3. Do dashboards for lets say user group A and user group B share the same Graphite or InfluxDB server?

InfluxDB and Graphite does not have a per metric/series authentication so even if Grafana implemented user groups and filtered visible dashboards on a user or user group basis the metrics would still be accessible to all users who have access to a Grafana account with a specific data source.

**Comment by phagedorn** [comment]
Hi @torkelo, first thanks a lot for building grafana and grafana 2.0. That helps me a log :+1:  
It because of security concerns that some users should only be able to see their own groups dashboards.
They should use the same graphite server. 
But i think its not possible at all with this client side code for fetching the json from graphite?

Usecase: 
1. multiple external customers
2. Custumer A should not see Dashboards from Customer B
3. Custumer A should not view or select metrics from the same graphite server in his own Dashboards

**Comment by torkelo** [comment]
@phagedorn then you will probably need to switch from Graphite to InfluxDB, where you can create separate databases for different customers with different authentication. 

Grafana will not provide per series authentication for Graphite. For this you need to open an issue in the Graphite project.

**Comment by kylemallory** [comment]
As a different use case... (I presented Grafana yesterday to our company and got a bit of feedback; the reception was overwhelmingly positive, but this come out the presentation):

Our intent it to collect data from all of our environments, development, test, production, infrastructure, etc, all within a single datasource (OpenTSDB).  We would like to be able to allow individuals the ability to manage and customize their own dashboards and views, possibly copying from public/shared dashboards, while protecting the integrity of public dashboards that are visible on NOC projectors, etc (ie, only authorized people can update/overwrite protected dashboards).

In the short term, I'd imagine a simple definition of "read-only" and "read-write" for editable permissions, and "private" and "public" for viewable permissions. 

![permissions mock-up](https://cloud.githubusercontent.com/assets/4668075/6151343/4885f888-b1d2-11e4-89b4-d8f54dd5136e.png)

If the Editable flag is "read-only", then the permissions tab is only visible by the owner of the dashboard, thus preventing non-authorized users from making a dashboard visible.

**Comment by phagedorn** [comment]
Doe "private" meams only visible to this user ?

**Comment by kylemallory** [comment]
Yes.  Also, the mock-up was quick-and-dirty; It would be appropriate that "Editable" is visible/editable, only if "Viewable" is "Public".  Editable has no relevance if Viewable is set to Private.

**Comment by herver** [comment]
Hi, 

That would be very useful for us as well, especially since now we have plugged Grafana 2.1 with our SSO via the auth.proxy.

Although everyone can get the raw data via the backend (Graphite), it would be nice to allow users to have "private" dashboards that could at some point be shared with users from the same Org.

**Comment by torkelo** [comment]
close in favor of https://github.com/grafana/grafana/issues/1128 https://github.com/grafana/grafana/issues/1611
