### ISSUE TITLE
[Bug] All links are the same as the first user who was invited. Multiple invitation

### ISSUE THREAD

**Issue by Labbs** [grafana/grafana#14483]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
Grafana v5.4.0 (commit: 69c5191)
### What datasource are you using?
Prometheus, Cloudwatch, Elasticsearch
### What OS are you running grafana on?
Ubuntu 18.04
### What did you do?
Create multi invite without email option
### What was the expected result?
Have a unique invitation link per user.
### What happened instead?
All links are the same as the first user who was invited. When the first user has validated the invitation, the link is that of the second guest user for all other users who are still waiting for validation.
### If related to metric query / data viz:
No

**Comment by daniellee** [comment]
Confirmed that this is a bug - we are in the process of converting from Angular to React and I think a bug got introduced here.

**Comment by daniellee** [comment]
@peterholmberg 

The bug is that the [ref object](https://github.com/grafana/grafana/blob/master/public/app/features/users/InviteesTable.tsx#L46) always gets the last value in the array of invites.This means that `this.copyUrlRef.current` in the [copyToClipboard function](https://github.com/grafana/grafana/blob/master/public/app/features/users/InviteesTable.tsx#L12-L13) always refers to the last node in the list.

I guess you have to create an array of refs?

**Comment by daniellee** [comment]
@Labbs this fix will be included in the next release of Grafana. Thanks for reporting it!

**Comment by Labbs** [comment]
Thank you, too speed :)
