### ISSUE TITLE
Logs Panel

### ISSUE THREAD

**Issue by ts-mini** [grafana/grafana#14576]
Please include this information:
### What Grafana version are you using?
Master (bleeding edge)
### What datasource are you using?
Loki

I've been using loki for a few hours.  Its awesome.  But now I was hoping I could add a panel to my existing dashboards (dashboards that track particular workloads) that show the Loki logs.  That way - when I zoom in on a spike in other data - I instantly see the corresponding logs for that timeframe.

I've looked and haven't seen a ticket or anyone asking for it officially (this might not even be the right place for it).

Is this something that will be implemented?

Thanks

**Comment by roidelapluie** [comment]
So .. the table will not work with loki?

**Comment by torkelo** [comment]
We hope do add table support as well (next weeks or months). Currently, it returns a special logs format but think we will refactor these formats in the coming weeks/months so that it works with the table panel as well.

**Comment by jgsqware** [comment]
This would be really handy when metrics from log will be available. 
I would love to not have to go back and forth between explore view and dashboard for specific data, especially when dashboard are already filtered or so

**Comment by davkal** [comment]
From @prg3: 

I want to have a dashboard for the various clusters I run with some canned queries so that the end users do not need to know or understand the underlying Loki queries. This is what we already do with graphs, so it would be very handy to give them a "tail -f" on various applications or containers. Of course with variables and selections.
