### ISSUE TITLE
New Time Picker & Unified time picker component

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#14651]
* [x] Update design of current time picker
* [x] Move refresh out to a separate component
* [x] Add tooltip with the selected time range
* [x] Share this component between explore & dashboard
* [x] Improve experiance on smaller screens (https://github.com/grafana/grafana/issues/11845)

**Comment by Ijin08** [comment]
<img width="1440" alt="screenshot 2019-02-04 at 08 46 52" src="https://user-images.githubusercontent.com/23470681/52195850-d444f480-2859-11e9-97c1-bb88d30e1cf2.png">

**Comment by Ijin08** [comment]
<img width="726" alt="screenshot 2019-02-06 at 09 13 17" src="https://user-images.githubusercontent.com/23470681/52328335-7e09ba00-29ef-11e9-9ef3-ad0f5f6b719b.png">

**Comment by aldanor** [comment]
Should the custom time ranges (#2417) be considered here as well?

**Comment by torkelo** [comment]
not initially as we want to keep the scope down

**Comment by savukadoo** [comment]
Some additional ideas for future use

- I second the suggestion from @aldanor having this is very useful as often teams , individuals have different times they class as Business hours / Operations hours vs Non Business Hours. So having the ability to create custom ranges is very beneficial. 
- Ability to exclude times ranges, so that data is not included  
- Advanced capability to have multiple time ranges, example "start of the week til the end of the week" and "time between 8:00 AM til 13:00 PM"
- Ability for a public holidays to be defined, probably part of the first point,however you may wan this to be inherited to all time filters so that when running long term reports these are excluded
- time filter inheritance for other time filters
