### ISSUE TITLE
Grafana2.0: remove user button is not working 

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#1466]
When trying to eliminate user, I can not do it ...

![image](https://cloud.githubusercontent.com/assets/5883405/6148925/4f77de6c-b205-11e4-8f8b-1381417e71e6.png)

**Comment by torkelo** [comment]
yes, user admin is currently under development, https://github.com/grafana/grafana/issues/1446

sorry for the state of the develop branch, but its really great that you are trying it out, because there is probably a lot that is not working or missing that we are not aware of or forgot

**Comment by torkelo** [comment]
implemented!

**Comment by toni-moreno** [comment]
OK ! @torkelo pleased to help you.

 I will test as many features as I could understand... but I have a lot of doubts on user management.

* How can I do a dashboard visible or editable only for certain users?
* what is the difference between the user editor in the account section (first picture) or the second one?.

![image](https://cloud.githubusercontent.com/assets/5883405/6151183/734c3b1c-b214-11e4-82fc-770444fdd427.png)

![image](https://cloud.githubusercontent.com/assets/5883405/6151160/5312c406-b214-11e4-9de6-a02bd8f1e732.png)

**Comment by toni-moreno** [comment]
What is the difference between "Log In" and "Sign Up" ?

There is any link or related document that can I read ?  I would like to not disturb you with trivial questions.

![image](https://cloud.githubusercontent.com/assets/5883405/6151241/d5dcc59e-b214-11e4-8c6b-3e039e5d4157.png)

**Comment by torkelo** [comment]
Grafana 2 uses a multi tenant account model similar to Google analytics (this is in order to support larger installations and SaaS setups), 

From the readme:
But a quick note is that Grafana 2.0 has a multi tenant account & user model where Dashboards, data sources, api keys, etc are tied to an account and not to a specific user. Users are coupled to accounts via an account user role (Admin, Editor, Viewer). The default configuration is set to a single account mode to make this user & account model easier to handle in a single account setup. User sign ups are automatically added to a main account with the Editor role (this can be overriden in the config file). The default grafana admin user that is created on first startup also creates the main account.

There is no user groups or permissions on individual dashboards. Users can be linked to accounts via a role (Admin, Editor or Viewer), Everything except user preferences are tied to an Account. 

So you can add users as viewer and they will not be able to create or update dashboards. But there is currently no way to make a user only see only some dashboards within one account. For that you need to create separate accounts.  

See my comment on this issue for more details on why there are no user groups: https://github.com/grafana/grafana/issues/1447

**Comment by torkelo** [comment]
No documentation currently, working on that. 

Login -> The user gets logged in / authenticated 
Sign Up -> Creates a user & logs the user in

You can also login & signup with Google OAuth or Github OAuth if you have specified OAuth details in grafana.custom.ini
