### ISSUE TITLE
Explore: Log graph bars get smushed together after split or window resize

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#14692]
0. Explore enabled, Loki datasource
1. Run query that returns log lines
2. Click Split

Result:

![screenshot 2018-12-31 at 12 10 00](https://user-images.githubusercontent.com/859729/50560104-2f347a80-0cf5-11e9-97cc-2677a7aaa080.png)

**Comment by aocenas** [comment]
We probably aren't passing the screen width correctly to compute the resolution of the graph

**Comment by ivanahuckova** [comment]
It isn't just split screen, it is any screen that has width under 1000px.

**Comment by aocenas** [comment]
> It isn't just split screen, it is any screen that has width under 1000px.

In that case it's possible we just send the number of lines there what is used as resolution for the graph. We do compute the graph separately in explore code thought so we may just do something else when processing the message. May be a problem for other datasources though like Elastic where we send one query with limit on lines but elastic does doc and aggregate queries which may need different settings because of this.

This though would probably go away if we move to a model where the log histogram is just function of the visualisation and the computation of the graph is done from the logs -> means you can decide on the buckets right in the visualisation based on actual width.

**Comment by ivanahuckova** [comment]
Well, the React graph would generally need some ❤️, because also Elastic logs visualisation is smushed. 
I have tried to fix this with https://github.com/grafana/grafana/pull/21922, but had to revert it https://github.com/grafana/grafana/pull/21968. I don't remember what is the reason why we are displaying loki bars as a lines with larger width, but it might be creating some problems for other usecases.

**Comment by ivanahuckova** [comment]
This is not happening anymore as we are creating histogram from actual logs and using time range based on the received logs. Therefore there is no smushing. Closing the issue. 
![image](https://user-images.githubusercontent.com/30407135/113007008-218d2a00-9176-11eb-8ce6-c47f09215ac7.png)
![image](https://user-images.githubusercontent.com/30407135/113007040-281ba180-9176-11eb-80cd-c6720fcb2477.png)
