### ISSUE TITLE
Explore: Design for query row options

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#14695]
Explore has the concept of query rows to select multiple data streams of either metric data or log lines. Each line maps to a separate backend request. There are cases now where it would be great to specify options for each row. Examples:

- Specify step in Prometheus query #13378
- Log line limit in Loki #14689 (second comment)

**Comment by Ijin08** [comment]
@davkal 
A big question here is if the query options will set one option or multiple options.

In case of one option simply having it in the same row as the query works quite well.
One option:
<img width="1440" alt="Screenshot 2019-09-06 at 11 06 03" src="https://user-images.githubusercontent.com/23470681/64416307-35a29f80-d097-11e9-8b61-bc8f9504dae1.png">
<img width="1440" alt="Screenshot 2019-09-06 at 11 06 16" src="https://user-images.githubusercontent.com/23470681/64416308-35a29f80-d097-11e9-80c5-86162ac09a77.png">

Having multiple options becomes a bit more tricky since they would have to be on a new row. Here they idea is to have a toggle that shows the options. To make it clear what query the options belong to we would have to increase the space between the query rows. To give space to the toggle button I moved the add query button to the top toolbar(I think we should move it there either way since it is a bit weird to have multiple add query buttons when one has more than one query). 
Multiple options:
<img width="1440" alt="Screenshot 2019-09-06 at 11 07 23" src="https://user-images.githubusercontent.com/23470681/64416688-f58fec80-d097-11e9-95f4-c16c2dc2a88e.png">
