### ISSUE TITLE
Custom datasources in v2.0

### ISSUE THREAD

**Issue by arussellsaw** [grafana/grafana#1472]
I apologize if i've just not found the answer, but i'm at a loss as to how to configure custom datasources in version 2.0 as changes made to src/config.js don't seem to be being used. ideally i'd like to be able to use the kairosdb datasource in version 2.0, but i'm not sure if this is possible.

**Comment by torkelo** [comment]
no, support for plugins has not been added yet. config.js is not used in backend mode

**Comment by smartynov** [comment]
I second that, it would be really useful to have an ability to create and use custom datasources. At least an SQL data backend (e.g. a query that follows some guidelines on results format).

**Comment by torkelo** [comment]
Fixed! All data sources are now plugins. 

Plugins are scanned and discovered by the backend, they are found by a plugin.json file like this:
```json
{
  "pluginType": "datasource",
  "name": "Graphite",

  "type": "graphite",
  "serviceName": "GraphiteDatasource",

  "module": "plugins/datasource/graphite/datasource",

  "partials": {
    "config": "app/plugins/datasource/graphite/partials/config.html",
    "query": "app/plugins/datasource/graphite/partials/query.editor.html",
    "annotations": "app/plugins/datasource/graphite/partials/annotations.editor.html"
  },

  "metrics": true,
  "annotations": true
}
```

This required some substantial changes because now data sources are loaded async (that is after application boot, similar to how panels are loaded, on demand). This will enable grafana to support more panels without effecting people who do not use them. Data sources can provide the own config partial to specify edit options (when you create/edit the datasource). 

This change has put the Grafana 2.0 "standalone" mode in big trouble (a mode where you do not need the backend and it works pretty much as in grafana 1.9.1 where dashboards are loaded from elasticsearch or influxdb). 

Considering scrapping the idea of a standalone mode, it creates to much complexity and strain on the frontend code to support both a backend mode and a standalone mode.

**Comment by torkelo** [comment]
One thing remain related to https://github.com/grafana/grafana/issues/1276 , and that is to make the templating editor and feature more data source neutral and allow data sources to provide their own editor.
