### ISSUE TITLE
How can we make a panel constant on top of the page?

### ISSUE THREAD

**Issue by Siddhu1096** [grafana/grafana#14864]
I am not able to make a panel constant on top . Can't find any options to do that.
![asdasdasdasdas](https://user-images.githubusercontent.com/22325249/51112400-963d4d80-1824-11e9-88f5-6fa375e75ab7.PNG)
I need to make this panel unmovable while scrolling down.
If there's no such thing, It'll be good to have one :) Very helpful.
Thanks in advance!

**Comment by torkelo** [comment]
this is currently not supported, and very unlikely we will so closing this.

**Comment by torkelo** [comment]
#
Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.

**Comment by Siddhu1096** [comment]
Thanks :)
