### ISSUE TITLE
Refactor App Insights raw query mode (Log Analytics) 

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#14942]
The Azure Monitor datasouce has integrations with multiple API's. The Azure Log Analytics API is very similar to the App Insights Analytics API but the query editor experience is totally different. The App Insights Analytics query editor should be refactored to share the same editor (either Monaco or Slate) as used for Azure Log Analytics. The current experience has limitations and also does not support autocomplete/intellisense for queries.

**Comment by torkelo** [comment]
remember to move it out of inbox :)

**Comment by mrtristan** [comment]
@daniellee i was about to open an issue but perhaps this one is very related and you already have me covered here. please confirm:

I use azure for only app insights at this time. AWS for everything else.

Prior to stumbling upon Grafana, I built my own monitor that had some canned Kusto queries that I queried App Insights for. I ONLY used an app id / secret combination.

I'm looking to do the same raw Kusto querying of App Insights instead of using the query builder functionality that currently exists in Grafana.

Also, for getting at Azure Monitor / Logs, is that 4 field authentication model the only way? Is there no Api Key/Secret approach for getting at that data? That auth model is very AD heavy and we don't utilize any Application or Domain services as our apps run in AWS...

sorry if this question isn't in the fully appropriate place.

**Comment by kylebrandt** [comment]
Unless there are some frontend differences in the code I am unaware of, as of 7.1 this is now the same editor (no more axis selectors or splitby).  The processing of the response is also the same, so assuming this can be closed.
