### ISSUE TITLE
varying legend heights within a row causes empty panel slots on next row

### ISSUE THREAD

**Issue by ryan-williams** [grafana/grafana#1495]
Here is a gif of a sequence of screengrabs from one of my dashboards, as an increasing number of metrics become initialized:

![output_kucz83](https://cloud.githubusercontent.com/assets/465045/6236086/61998226-b6b5-11e4-8b4c-b58653927a2a.gif)

About mid-way through the above animation, notice that the second row loses the leftmost 3 of 4 panels. Here is one of those frames:

![5](https://cloud.githubusercontent.com/assets/465045/6236213/7740603a-b6b6-11e4-846f-065d6562a954.png)

In fact, the same thing is happening to the lower-left panel in the first few frames, e.g.:

![1](https://cloud.githubusercontent.com/assets/465045/6236224/970e28ca-b6b6-11e4-8387-7b091accbeba.png)

Having different-height legends on panels in a row seems to mess up the next row.

**Comment by torkelo** [comment]
yes, this is because your panels are to small to fit the legend within one row, after a few series they need to stack. The height calculation only calculates the height of one legend row. 

You can fix this by having seperate panel rows, right now you are having only one panel row for all panels, which makes them flow to the next. Add new panel rows and move the panels so that have 4 panel rows (marked with the green icon the right). 

The panel height is tricky, especially for the legend as Grafana can not know in advance exactly the height of it. It could perform a second rendering pass and correct the height of all panels to the height of the heightest panel but that would slow down Grafana. 

In the future we will probably improve the row and grid system maybe migrate so something like gridster.

**Comment by ryan-williams** [comment]
thanks for that info @torkelo, makes sense that I should just make each logical row a grafana row
