### ISSUE TITLE
Add Alerts to all Graphic Panel type Plugins

### ISSUE THREAD

**Issue by Sunil84** [grafana/grafana#15059]
Hello Grafana team,

Firstly you guys are doing a great job. Grafana is a fantastic tool for visualization and we love it.

I would be nice if you could provide provision to add alerts in all the visualization panel types. 

Cause we use different graphic panel types for different dashboards as per requirements and in most of the cases we need to add alert panel as well. 

Please consider this request on high priority.

Please include this information:
### What Grafana version are you using?
Grafana v5.2.4 (0bbac5c)
### What datasource are you using?
Postgres
### What OS are you running grafana on?
Freebsd
### What did you do?
I have used table panel, traffic lights and polystat for visualization. There is no provision to add alerts for these panel types.
### What was the expected result?
Need to add alerts.
### What happened instead?
No provision to add alerts.
 
Thanks and Regards,
Sunil

**Comment by Siddhu1096** [comment]
+1 for this!!!

**Comment by marefr** [comment]
We're planning to make changes to alerting in the near future so that alert rules not are tightly coupled to a certain type of dashboard panel. This will still allow to visualize alert rules/queries in dashboard in some way that's still needs to be decided. 

Because of this I'm closing this feature request for now.
