### ISSUE TITLE
Inifinite loop when Scan for older logs clicked

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#15086]

**Comment by torkelo** [comment]
Are you using latest master? I fixed an issue with angular url <-> redux url state sync this weekend that might have solved this. Cannot replicate it locally.

**Comment by davkal** [comment]
Looks like this happens when the query is empty.
Separate issue: how did you end up there? There should be the StartPage being shown.

**Comment by dprokop** [comment]
1. Go to Explore
2. Change datasource to `TestData`
3. Change datasource to `Loki`

And no start page is displayed anymore

**Comment by hugohaggmark** [comment]
Can still reproduce this

**Comment by torkelo** [comment]
The root cause that I can identify is that during change data source
importQueries is called (before data source has fully changed), this generates a new empty query with new key prop, this new key prop causes an unmount/mount of QueryRow which causes a new mount of QueryEditor (wrapper for angular query editors in Explore), this component calls onQueryChange in it's mount function. So the result is we get a onQueryChange after importQueries (That did the resetting of the queries).

**Comment by torkelo** [comment]
Think this is fixed with hugos big refactoring of Explore
