### ISSUE TITLE
Data is not removed when transaction is cleared

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#15091]
When last query is removed (cleared to be precise), the data is still displayed. Clickin on `Run query` does not clear the data as well: 

![output.gif](https://images.zenhubusercontent.com/5c332a288332e72a247d9d08/2de8f33d-69e1-43bd-bdc2-1985661b3276)

**Comment by davkal** [comment]
I think it's fine to see results after the query has been cleared, especially if you're relying on result data for your next query (and you used the clear button to clear faster than manually deleting).
If the expectation was the result to be cleared as well, then I think it's a hierarchy issue. To address that, the clear button could be demoted to be inside the query field itself. This could be needed anyway since the more graphical query builders don't really need a clear action to begin with.

**Comment by torkelo** [comment]
Yes, not 100% sure that this is a problem

**Comment by torkelo** [comment]
closing this for now
