### ISSUE TITLE
Invalid downsample value sent to OpenTSDB

### ISSUE THREAD

**Issue by soulution** [grafana/grafana#1512]
When using a interval variable with the Auto option turned on, Grafana will send a invalid downsample value to OpenTSDB. This occurs when zooming in to a time span of just a few seconds. In my example, the downsample value was sent as "0.1s-sum" which causes OpenTSDB to return a 400 Bad Request error stating "Zero or negative duration: 0.1s".

Looking at the [OpenTSDB source code](https://github.com/OpenTSDB/opentsdb/blob/master/src/utils/DateTime.java#L150-L161), the correct way is to send the downsample value as "100ms-sum". I have verified that this works with OpenTSDB 2.0.1.

**Comment by torkelo** [comment]
This is fixed in master and in develop  (Grafana 2.0 branch), https://github.com/grafana/grafana/commit/a5fd40ed8045e4072f58ded23e811204285482b0

Another big change that was also introduced today is that Downsampling is enabled by default for OpenTSDB, so you HAVE to pick the correct downsample aggregator  or disable downsampling. 

If no downsample parameter (or template variable) is used Grafana will calculate it automatically based on the time range and graph width in pixels.
