### ISSUE TITLE
Add Explore Auto-Refresh Options

### ISSUE THREAD

**Issue by robmuze** [grafana/grafana#15192]
Is it  possible to enable the auto-refresh options after  selecting logs time range ?

**Comment by stevenpall** [comment]
@tomwilkie I believe what @robmuze means is it would be nice if the Grafana UI for Loki provided a way to "tail" logs. This could be implemented similarly (at least from the user's perspective) to the `Refreshing every` option on metrics dashboards.

One issue I've considered with this is it would put a fair bit more load on the backend storage since the same query would be getting run continuously. Perhaps a further improvement to this feature would be some sort of "caching" for log lines that have already been returned.

**Comment by tomwilkie** [comment]
@stevenpall we've got some basic support for tailing in the logcli client, plan is to move that server side at some point.  Then we'll add specific tailing options to the datasource and explore.

**Comment by jschill** [comment]
Auto-refresh was added to Explore in #16505 - closing.
