### ISSUE TITLE
Support for react panels without queries

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#15217]
In the old angular panels we panels could inherit from either PanelCtrl or MetricPanelCtrl, the later they would get the metrics tab. 

For react panels we have no similar distinction. Would be nice with a way, maybe in plugin.json to mark 
plugins as data panels  or widgets (dashboard list, alert list, text panel) . 

For react panels everything goes through DataPanel "hoc" that executes the queries and keeps the data loading state. It currently displays a message (and does not render the child render props) if there are no queries. 

So we need to have a way to know that panel plugin does not care at about queries/data.

**Comment by jschill** [comment]
Note to self. The current way we do this in the react-panels is to check if the plugin exports an onDataReceived function. This should also be replaced with the json prop.

https://github.com/grafana/grafana/blob/52fe6b031666704e8a8c3e01916828b63a9af00e/public/app/features/dashboard/panel_editor/PanelEditor.tsx#L85

**Comment by alexanderzobnin** [comment]
I have _Problems panel_ in Zabbix plugin which is not a metric panel. When I go to panel edit, I see a black screen and error in console: 
```
TypeError: "panel.targets.map is not a function"
The above error occurred in the <QueriesTab> component:
    in QueriesTab (created by PanelEditor)
    in div (created by PanelEditor)
    in div (created by PanelEditor)
...
```
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/panel_editor/QueriesTab.tsx#L203
This happens because panel uses a different `panel.targets` structure which is an object, not array. This panel doesn't work in any data sources except Zabbix, so I decided to create it as non-metric panel and implement its own query editor.

So in this case 2 solutions are possible:
1. I can change panel schema and do not use `panel.targets` for queries.
2. Grafana can skip adding query editor for non-metric panels.
