### ISSUE TITLE
Explore: Query row status does not adjust when long query 

### ISSUE THREAD

**Issue by jschill** [grafana/grafana#15246]
The query row status (information in the top right in the input area) does not adjust when there's a long query. We should position it relative to the other content.

![screenshot 2019-02-05 10 21 00](https://user-images.githubusercontent.com/224493/52263638-eabd7f80-292f-11e9-94dc-7993fbbf14f2.png)

**Comment by aocenas** [comment]
@davkal seems like this could be good onboarding issue, but the question is what would be a good fix. I would personally put it totally outside of the input in some way to make it easier.
Other solution could be to somehow inline it in to the end of the query but this can be hard to control in a way to prevent the counter being on its own row and also makes the position not stable in relation to the query text.
One more could be to align it so that the counter takes its own column of space but this could create a lot of awkward white space on multiline query.
