### ISSUE TITLE
Azure Monitor Documentation

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#15241]
Port the documentation from the plugin repo to Grafana's documentation.

**Comment by calum-gunn1** [comment]
Hi @daniellee ,

In the Templating with Variables section of the documentation you refer to chaining template variables with $rg as an example (Azure Monitor). This functionality doesn't seem to work in the plugin or in the beta version. When using a template variable in the graph editor, it substitutes the variables but passed it to the URL with parenthesis surrounding the value. This causes the API Get request to fail -  I would expect the cause is the same when chaining variables. Is this a bug or is the documentation inaccurate? or both :)

Huge fan of the Azure plugin- keep it up :)

Calum
