### ISSUE TITLE
Problem querying a long period

### ISSUE THREAD

**Issue by syepes** [grafana/grafana#1534]
Hello,

I have just found and issue when trying to query a long period like 6 months, the strange thing is that it works for 30 Days and if I try the same query in Graphite it works OK:

![query](https://cloud.githubusercontent.com/assets/333081/6410122/646bb910-be6c-11e4-8fd4-f37f3a3308f1.jpg)

Do you know what could be causing this issue?

I am running Grafana (master #7293ee0)

**Comment by torkelo** [comment]
what version of Graphite are you running? This is problably because you are running Graphite 0.9.12 which has a big flaw in its json api (it can return hundreds of thousands of data points, which can be megabytes big and cause issues for the browser and grafana). Many patch Graphite 0.9.12 with this graphite feature https://github.com/graphite-project/graphite-web/pull/334 

Its a feature that did not make it into 0.9.12, but it is in Graphite 0.9.13, I suggest you upgrade. 
http://graphite.readthedocs.org/en/latest/releases/0_9_13.html

**Comment by torkelo** [comment]
Or it could be something else that is strange with graphite, the error seems to be that Graphite is returning invalid json. Its not something I have seen before (and I regularly check 6 months or longer time ranges)

**Comment by syepes** [comment]
Its strange I am running graphite-web (0.9.x 8488aea2e2).
Do you have any suggestions on how we would find the issue.

**Comment by torkelo** [comment]
@syepes yes, that sounds familiar, seen that issue before, https://github.com/graphite-project/graphite-web/issues/813
