### ISSUE TITLE
Pass white listed headers from user requests to downstream datasource. 

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#15396]
Grafana should support passing whitelisted headers from the user's request to the datasource. Making it possible to authenticate the requests at the datasource level per user. 

`user req -> proxy, adds headers -> grafana -> datasource request, with header`

This should be added for any datasource supporting http. Hidden under advanced settings so only users who needs it are exposed to it. 

ping @brancz

**Comment by vtorosyan** [comment]
Closing this issue since this is implemented already (and partially not relevant).

**Comment by ringerc** [comment]
> Closing this issue since this is implemented already

Unclear how this is implemented - unless the functionality was since removed?

* Grafana has [limited support for OAuth forwarding and caching](https://grafana.com/developers/plugin-tools/how-to-guides/data-source-plugins/add-authentication-for-data-source-plugins#forward-oauth-identity-for-the-logged-in-user) of the `authorization_token` via `oauthPassThru: true` in the plugin's `jsonData` + the grafana go sdk's `opts.ForwardHTTPHeaders` - but this only forwards `Authorization` and `X-Id-Token`.
* Some plugins support forwarding allow-listed client _cookies_
* `send_user_header = true` injects a header with the grafana-level user identity in plugins that use grafana's http client
* `forward_user_agent = true` propagates the user-agent
* Some plugins support setting custom headers, but they can't source them from the client's http headers

I've been unable to find any generic mechanism for allow-listing additional headers to pass from the client HTTP request -> the datasource.

Note that even if such support existed, it would not work for Grafana-level alerts or other background/scheduled query features, since those don't have any client HTTP context at all.

https://github.com/grafana/grafana/issues/87364 suggests such functionality does not exist.
