### ISSUE TITLE
Grafana 2.0: SQL Data source

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1542]
With the backend comes the possibility to have SQL data source. 

My thinking is that when you add the data source you
- db type (initially only mysql and postgres and sqlite3)
- db connection details
- specify a metric query template (basically a SQL query with params)
- specify a annotation query template 

Maybe also an option to allow RAW SQL queries from the panel metric query interface. 

Any other ideas?

**Comment by syepes** [comment]
I would personally suggest some thing more in the line of Cassandra (CQL) or SparkSQL

**Comment by phagedorn** [comment]
Wow, this us very usefull.
- add a array of db servers for loadbalancing
- a field that concatenate a LIMIT X to the query 
- a switch for ORDER BY ASC DESC 
- chose db columns  for TIME and for VALUE from mysql table ?

**Comment by torkelo** [comment]
@phagedorn some like that, not sure about the switch for order asc/desc, grafana always wants them in ascending order (by time). not sure about the limit x either. 

more like a metric query template (written by user when they add the data source), this just an example, have not thought about this much yet.
```sql
SELECT MyValue as Value, Timestamp as Time 
  FROM MyMetrics
  WHERE SeriesName IN (?SeriesList) AND Time > (?TimeFrom) AND Time < (?TimeTo)
  ORDER BY Timestamp ASC 
```

@syepes I thinking as first step to implement something simple. Could you describe more what it would take to implement CQL or SparkSQL on top of a generic SQL database and what benefits? SparkSQL looks interesting from analaytics standpoint, any golang implementation?

**Comment by sysadminmike** [comment]
+1 for allowing raw SQL

**Comment by phagedorn** [comment]
@torkelo : Query templates sounds nice :+1: 
Works for me for existing tables

**Comment by nucleusv** [comment]
Will this datasource has a suggestion editor? What DB backends for this datasource can be used ?

**Comment by rippy4** [comment]
also interested in allowing raw SQL

**Comment by torkelo** [comment]
Initially mysql and postgres,  no auto complete isn't going to be included initially

**Comment by huhongbo** [comment]
interested +1

**Comment by sahilthapar** [comment]
:+1: for postgres

**Comment by pskerrett** [comment]
:+1: for postgres

**Comment by shirou** [comment]
:+1: for postgres with JSON type

**Comment by PRI-mcallen** [comment]
:+1: for postgres with JSON type

**Comment by juliusloman** [comment]
Any idea about the roadmap when SQL datasource will be available? In 2.0 or 2.1?

**Comment by torkelo** [comment]
@juliusloman not sure, maybe in 2.2 or 2.3, so much other stuff that was pused to 2.1 that needs to happen first

**Comment by torkelo** [comment]
But a PR is always welcomed

**Comment by gsaray101** [comment]
+

**Comment by hceylan97** [comment]
Having a SQL data source will definitely make grafana a top analytic tool. I would love to see it. Torkel, sorry not familar with github, what does PR entail?
+

**Comment by torkelo** [comment]
@hceylan97 it entails that someone tries implement it and submits it as pull request (i.e feature patch), I would love to implement this, but not sure when I will have to do it as I will probably have more high prio issues for the next couple of months

**Comment by hceylan97** [comment]
besides you, curious if anybody else is working on this?

**Comment by gsaray101** [comment]
:+1:

**Comment by gsaray101** [comment]
:+1:

**Comment by Esysteme** [comment]
+1 mysql

**Comment by agilgur5** [comment]
@torkelo I might start a PR for this pending the expected amount of work. Would love to figure out how to make new datasources so we can integrate more into Grafana. Could you give a rundown of what needs to be done to add a new data source and the work remaining for generic SQL support?

**Comment by nucleusv** [comment]
+1 Oracle

**Comment by timgriffiths** [comment]
+1 MS SQL

**Comment by imZack** [comment]
:+1: for postgres with JSON type

**Comment by pabloa** [comment]
+1 postgres / postgres with JSON type

**Comment by agilgur5** [comment]
@torkelo pinging again as this has been pushed back two months. I'd like to add some support for new datasources in Grafana and I'd love a rundown of how to do so and what is left for generic SQL support (pretty sure you'd appreciate if I could get a PR out too :))

**Comment by torkelo** [comment]
@agilgur5 no work has been done on this yet

**Comment by agilgur5** [comment]
@torkelo what about d0d995d? In any case a rundown would be much appreciated

**Comment by torkelo** [comment]
@agilgur5 that was mostly work on the data source plugin system nothing specific to a SQL data source

**Comment by discoduck2x** [comment]
+1 MS SQL !!!

**Comment by Esysteme** [comment]
with MySQL in front you can insert in any SGBD with engine XA & Connect !

**Comment by Dieterbe** [comment]
> specify a metric query template (basically a SQL query with params)
> specify a annotation query template 

i wonder if this is needed? maybe it's extra hassle we can avoid.
isn't it sufficient to specify the table and columns when using the DS ? or perhaps specify the table in the DS so you only need to specify columns when using it. i do suspect there will be many tables with each only a few columns.

**Comment by EliSnow** [comment]
What's the ETA for this?

**Comment by agilgur5** [comment]
@EliSnow https://github.com/grafana/grafana/milestones says around September 29th. This feature alone might be done before that, and there's also the possibility it gets pushed back (as it has been a few times already). Regardless, I don't believe any work will be done on this until after the 2.1 release.

**Comment by eosfor** [comment]
+ 1 MS SQL; +1 query with parameters
Actually why i'm asking. The simplest way to put perf counters to the scene from numerous windows boxes is to configure data collectors on them to put data directly to ms sql without any "middle ware collectors". So it would be really great to have an option jut to read that data from MS SQL. So this would be a really great option!

**Comment by goriparthi** [comment]
+1 - Postgres. 

Postgres is just a phenomenal DB. If I have time, I might look into this @torkelo

**Comment by EliSnow** [comment]
@torkelo, I'd like to contribute to getting this done. I'm looking at the commit referenced earlier for the datasource plugin system (d0d995d). Is there any documentation for the plugin system? What pieces are needed? Looking at other datasources in the [/public/app/plugins/datasource](https://github.com/grafana/grafana/tree/master/public/app/plugins/datasource) directory it appears to just be Javascript (Angular + AMD) and some HTML templates. Is there any Go code required to get this working or is it strictly Javascript?

**Comment by torkelo** [comment]
Since SQL databases usually don't  have a http api there will hävt to be some backend go code

**Comment by tamilsweet** [comment]
+1 MySQL & Cassandra

**Comment by EliSnow** [comment]
This is somewhat off topic, but I think a good step (or alternative step) towards getting a SQL data source. It would be great to allow an admin user, from the UI, to add a custom HTTP data source. 

The admin user could specify the base url and a javascript function which transforms a query into an actual http request. They could also provide javascript mapping function(s) which would transform the data returned from the http request into a common format understood by grafana. Eventually, there could be an interface for people to build their own UI query builder which could allow for hinting and such. One of the most important pieces of this is it has to be well documented.

Why is this relevant to this issue? Some people may elect to have their SQL database accessible through an HTTP endpoint rather than allow direct access. Perhaps grafana is not on the same network as the database and it has no direct access for security reasons. Even if the database is directly accessible and the user could provide raw SQL, there is still the issue that given an arbitrary SQL query, grafana is not going to know what format the data is returned in, and the javascript mapping functions will still be required (perhaps at the graph/dashboard level).

To avoid XSS perhaps we don't want any non-admin user to edit a dashboard and provide javascript functions which will be executed on the page. This could be avoided by requiring that SQL queries return data in a specified format. Alternatively, XSS perhaps could be mitigated through CSP.

I recognize that a determined person can currently add a custom HTTP data source by editing the source code, but this is more challenging because: 1) it's not documented (that I'm aware of), and 2) it requires different people to be involved, assuming a person's in a position where the roles "devops" and "grafana admin" are fulfilled by different people.

I personally was able to add a custom SQL data source through an HTTP endpoint which mimicked the influxdb interface. The query builder allows the user to specify arbitrary queries, I just needed to make sure my endpoint returned data in a format like influxdb. It's great, but it's hacky and leaves a lot to be desired.

**Comment by EliSnow** [comment]
Thoughts, @torkelo?

**Comment by roybass** [comment]
@EliSnow - Would you mind sharing the code?

**Comment by EliSnow** [comment]
@roybass, I am guessing you are asking about my code which mimics the InfluxDB interface.

I cannot share my specific code, and it probably wouldn't be very helpful if I did because it is specific to the language I used (Node.js), my database (Postgres), and the structure of my data (jsonb). The gist of what you need to do is create a `/query` HTTP endpoint which returns data in the same format that InfluxDB does.

Grafana will call your endpoint using the GET method with the `q` parameter of the query string being the search query/queries specified in your dashboard panel. Each query is delimited by a newline character. (Note: that the "Test Connection" button for testing your Data Source in the admin interface will send the query `SHOW MEASUREMENTS LIMIT 1`. If you return a 204 for that query that will suffice). You can design the search query to be your own DSL. I made my search query a simple JSON object. While you certainly could use real SQL for your search query, you should make sure the database user executing the query only has permission to `SELECT` on specific table(s). For me, my SQL queries are pretty long and gnarly, and I prefer to have a level of abstraction from the database.  

InfluxDB returns data in the following [annotated] json format:

```js
{
//each entry in "results" represents the result of a single query
  "results": [{
    // each entry in "series" represents a different group if the
    // query had a GROUP BY clause.
    "series" : [
      {
        "name" : "measurement name",
        // not sure which tags influx chooses to return
        // perhaps only the ones in the WHERE clause
        // grafana allows you to use tags in the alias pattern
        "tags" : {
          "foo" : "bar"
        },
        // I have not checked grafana's source but it's possible
        // it does not read the "columns" array
        "columns" : ["time", "mean"],
        "values" : [
          // time (in epoch ms), value
          [1442953067791, 41.2]
        ]
      }
    ]
  }]
}
```

If you don't have your own InfluxDB instance up and you need to play around with how Grafana sends it queries, you can use the [test dashboard](http://play.grafana.org) and your developer tools to take a peek.

As a disclaimer, I've probably missed something in how Grafana communicates with InfluxDB, but the above was enough to get me started.

Hope that helps.

**Comment by roybass** [comment]
Thanks! That's exactly what I meant

On Tue, Sep 22, 2015 at 11:57 PM, EliSnow <notifications@github.com> wrote:

> @roybass <https://github.com/roybass>, I am guessing you are asking about
> my code which mimics the InfluxDB interface.
>
> I cannot share my specific code, and it probably wouldn't be very helpful
> if I did because it is specific to the language I used (Node.js), my
> database (Postgres), and the structure of my data (jsonb). The gist of what
> you need to do is create a /query HTTP endpoint which returns data in the
> same format that InfluxDB does.
>
> Grafana will call your endpoint using the GET method with the q parameter
> of the query string being the search query/queries specified in your
> dashboard panel. Each query is delimited by a newline character. (Note:
> that the "Test Connection" button for testing your Data Source in the admin
> interface will send the query SHOW MEASUREMENTS LIMIT 1. If you return a
> 204 for that query that will suffice). You can design the search query to
> be your own DSL. I made my search query a simple JSON object. While you
> certainly could use real SQL for your search query, you should make sure
> the database user executing the query only has permission to SELECT on
> specific table(s). For me, my SQL queries are pretty long and gnarly, and I
> prefer to have a level of abstraction from the database.
>
> InfluxDB returns data in the following [annotated] json format:
>
> {//each entry in "results" represents the result of a single query
>   "results": [{
>     // each entry in "series" represents a different group if the
>     // query had a GROUP BY clause.
>     "series" : [
>       {
>         "name" : "measurement name",
>         // not sure which tags influx chooses to return
>         // perhaps only the ones in the WHERE clause
>         // grafana allows you to use tags in the alias pattern
>         "tags" : {
>           "foo" : "bar"
>         },
>         // I have not checked grafana's source but it's possible
>         // it does not read the "columns" array
>         "columns" : ["time", "mean"],
>         "values" : [
>           // time (in epoch ms), value
>           [1442953067791, 41.2]
>         ]
>       }
>     ]
>   }]
> }
>
> If you don't have your own InfluxDB instance up and you need to play
> around with how Grafana sends it queries, you can use the test dashboard
> <http://play.grafana.org> and your developer tools to take a peek.
>
> As a disclaimer, I've probably missed something in how Grafana
> communicates with InfluxDB, but the above was enough to get me started.
>
> Hope that helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grafana/grafana/issues/1542#issuecomment-142419032>.
>

-- 
The above terms reflect a potential business arrangement, are provided solely 
as a basis for further discussion, and are not intended to be and do not 
constitute a legally binding obligation. No legally binding obligations will 
be created, implied, or inferred until an agreement in final form is executed 
in writing by all parties involved.

This email and any attachments hereto may be confidential or privileged. 
 If you received this communication by mistake, please don't forward it to 
anyone else, please erase all copies and attachments, and please let me 
know that it has gone to the wrong person. Thanks.

**Comment by anayrat** [comment]
:+1: for Postgres!

**Comment by jmlero** [comment]
+1 for SQLite

**Comment by sysadminmike** [comment]
@roybass  -  you post has given me an idea and i have made a very basic start on a postgres proxy - i have not actually pointed grafana at it yet but am hoping via  influx custom queries it can pretend to be influx but is backed by postgres

**Comment by sysadminmike** [comment]
hi everyone who wants to connect to postgres - i have managed to get the above working and have an example graph going

**Comment by RobMcZag** [comment]
+1 postgres / postgres with JSONB type
@EliSnow we use node, postgres, influxdb and grafana... if you can, I'd like to look at your code :)
@sysadminmike will check it out !

**Comment by Esysteme** [comment]
:+1: MySQL

**Comment by sysadminmike** [comment]
@RobMcZag let me know what you think - I have used it for setting up a distributed metric collection idea: https://github.com/sysadminmike/yadms/

**Comment by utkarshcmu** [comment]
@torkelo, I am not sure how, a SQL datasource will scale with millions of datapoints being stored every day. I can agree on having a datasource for Cassandra which is highly scalable and awesome in performance.

**Comment by volter** [comment]
@utkarshcmu, I guess it's fair to say that relational databases aren't slow by nature. Anyway, even if they were, it can still be attractive to pull out data from a small table for annotations or whatever, so SQL databases are a very useful source of data, if you ask me.

**Comment by AlexKoe** [comment]
+1 Informix TimeSeries / Informix TimeSeries w/ JSON
@utkarshcmu Informix is an example how an object relational DB can support a highly scalable time series data implementation through an optimized timeseries data type (time series elements can be SQL data types and/or JSON documents). ;)

**Comment by arunasp** [comment]
Hello,

There is possibility to have SQL numeric data exported over HTTP interface using additional layer between SQL server and Grafana with the help of ArrestDB: https://github.com/alixaxel/ArrestDB
If someone could fork plugin from the existing HTTP based one that would be very nice. Personally I'm not an expert with Java coding here and need help with this.
This also would stack nicely with Restful API from other data sources - https://restdb.io/docs/rest-api

**Comment by cemo** [comment]
+1

**Comment by zensqlmonitor** [comment]
Hi, here is my first project in go:
Collect Microsoft SQL Server metrics, send to InfluxDB and visualize with Grafana
https://github.com/zensqlmonitor/influxdb-sqlserver

**Comment by akrus** [comment]
+1 to MySQL :)

**Comment by utkarshcmu** [comment]
+1 for VoltDB [In-Memory SQL DB]

**Comment by joerg16** [comment]
:+1:

**Comment by spacepluk** [comment]
How about jdbc?

**Comment by Stuermer** [comment]
+1 MySQL

**Comment by sbarale** [comment]
+1 MySQL

**Comment by 3add3287** [comment]
+1 PostgreSQL

**Comment by ianare** [comment]
+1 PostgreSQL

**Comment by tdyas** [comment]
WIP SQL datasource: https://github.com/grafana/grafana/pull/3964

**Comment by pabloa** [comment]
+1 postgresql

**Comment by mpmlj** [comment]
+1 Cassandra

**Comment by schmidb** [comment]
Hi, what is the status of a SQL datasource integration? For us it is of high interest to connect grafana to Amazon Redshift or Presto. There might be the option to put one of our developers on this topic. Is the SQL integration just some coding work or are there major changes required?

**Comment by tdyas** [comment]
I had a work-in-progress prototype in PR https://github.com/grafana/grafana/pull/3964 talking to my company's Redshift. So I believe just coding work (on my part or someone else's) at this point. Although there are several items listed in the PR that would need to be accomplished before making it production-ready.

**Comment by all-things-database** [comment]
+1 VoltDB

**Comment by sslupsky** [comment]
+1  Would be useful for annotations and text panels.

**Comment by mo-mughrabi** [comment]
+1

**Comment by damiencarol** [comment]
+1

**Comment by antoonh** [comment]
I've been running influxdb proxied through grafana now for a while. As a side hobby I'm  poking around with a web app firewall, and one thing I'd be really keen to find a solution to is something akin to prepared statements in order to preempt SQL injections. Right now, I have a collection of various regexes that detect sql injections, but finetuning those whilst retaining the capability to deploy new dashboards pretty much prevents that, leaving me no other option than to pretty much whitelist the argument section.
Conceptually, it would be simple: publish fixed proxy links for data collection created when the dashboard is created/updated, rather than have the query statement embedded in the argument of the url. All you'd have to do on the proxy side is map it to the real query and then send it over to the database backend. 
Dealing with this via the proxy parts of grafana gives the added elegance of database independence on being able to deal with prepared statements.

**Comment by evanbreznyik** [comment]
:+1: for the concept/idea as well as the ability to use more-or-less raw SQL if you want to supplement existing methods/features/metrics

**Comment by enp** [comment]
+1 for postgresql/mysql

**Comment by cudos** [comment]
todo mis dedos levantado para postgres

**Comment by zapient** [comment]
+1

**Comment by HammyHavoc** [comment]
+1

**Comment by MatMeredith** [comment]
+1.   Really need this!

**Comment by winmutt** [comment]
+1

**Comment by rahul8590** [comment]
Any updates on this ??

**Comment by tdyas** [comment]
I wrote an initial proof of concept which I put up as a PR to get feedback: https://github.com/grafana/grafana/pull/3964. The code worked fine for queries against a locally running PostgreSQL instance. I do not know if it would still work given source code changes in Grafana on the way to v3.

Unfortunately, I don't have the time to work on it anymore because the internal project that would have needed such a datasource, no longer does.

Given the source code for the proof of concept is publicly available in the PR, it would be nontrivial (but not a great amount of work) for someone else to take over. If you are a developer, this is a great way to learn the Grafana source code base. If you are not a developer, but have influence in your company, then I recommend convincing a developer in your organization to work on it.

This issue really demonstrates the "free rider" problem in open source. The "currency" of open source is code (in its broadest sense) and the time invested by contributors in that code. It seems to me everyone is happy to give a +1, but very few people contribute or use their influence to convince someone in their organization to contribute.

Want to influence the project's direction on this issue? Take over the proof of concept, complete it, and contribute it back, whether by doing it yourself or allocating your organization's time (in the form of a developer) to do it. That time allocation is most definitely an expenditure. Who's willing to "spend" the time?

For myself, I am willing to answer any questions about the proof of concept from whoever takes it over.

**Comment by anzai** [comment]
I sent pull request of this.

* https://github.com/grafana/grafana/pull/5168 "Add the datasource of RDBMS (PostgreSQL and MySQL) "

* You can see the detail of this:
https://github.com/anzai/grafana/wiki/SQL-DB-plugin-%28datasource%29

**Comment by nitram4** [comment]
+1

**Comment by grepwood** [comment]
+1 for Postgres, my workplace loves Grafana already

**Comment by yehosef** [comment]
We would love to see this - as a reference https://github.com/sirensolutions/kibi is a "friendly-fork" of kibana and sql support is one of the features they have added 
https://github.com/sirensolutions/kibi/tree/master/src/plugins/kibi_core/lib/datasources

if this helps.

**Comment by Jimilian** [comment]
Guys, please, stop posting +1. Just say thanks to @anzai and apply https://github.com/grafana/grafana/pull/5364 to your local grafana.

**Comment by nitram4** [comment]
mysql and postgre is awesome, Oracle or generic jdbc would be awesome (like in Kibi mentioned above)

**Comment by yehosef** [comment]
@Jimilian - the +1 is to get it into the main distribution.  Applying the patch means that when a new grafana is released, I'll have to reapply, which most users don't want to deal with.

**Comment by djdillon** [comment]
+1 for this feature, especially if it supports ODBC/JDBC

**Comment by anarcher** [comment]
:+1:  for postgres!! :-)

**Comment by juliusloman** [comment]
I took another approach to displaying data in RDBMS using RestSQL. RestSQL enables CRUD operations on relational databases and it's quite elegant solution to enable database operations using HTTP and REST methods.

I've written a Grafana plugin for RestSQL - [Grafana plugin (3.x) for RestSQL](https://github.com/juliusloman/grafana-restsql-datasource). However consider it as a PoC at this time :-)

In my setup no changes to Grafana code base are needed. However this setup needs Java (Tomcat) for RestSQL to work.

**Comment by deviousgeek** [comment]
+1. Awesome POC @juliusloman .

**Comment by sradco** [comment]
+1 . Would be really great for Postgres!

**Comment by ChromeHearts** [comment]
+1 Postgres!
+1 Raw SQL queries

**Comment by trequartista10** [comment]
+1 for cassandra!

**Comment by bergquist** [comment]
@juliusloman Would be awesome if you published that plugin on grafana.net?

**Comment by karthikeyan95** [comment]
+1 MYSQL and POSTGRES

**Comment by matias-pacelli-rocket** [comment]
+1 Postres!
+1 Cassandra!
+1 MySQL!

**Comment by ianrapha** [comment]
+1 Cassandra

**Comment by leite08** [comment]
+1 MySQL

**Comment by Alcon835** [comment]
+1 MS SQL!! :D

**Comment by makapuf** [comment]
Instead of creating N +1 comments, I suggest adding a :+1:  tag to the first line mentioning the DB you'd like to have supported ?

**Comment by nbluis** [comment]
:+1:

**Comment by Ziaunys** [comment]
+1 BigQuery.

**Comment by MarkoMarjamaa** [comment]
So is this plugin going to official version? I would like to have Postgres as data source.

**Comment by LooMaclin** [comment]
+1 PostgreSQL

**Comment by philip-wernersbach** [comment]
@all I've open sourced my InfluxDB-to-MySQL protocol converter and published it to https://github.com/philip-wernersbach/influx-mysql, and it's ready to work with Grafana.

**Comment by wazagit** [comment]
I would think that a JSON input gateway should suffice to allow practically any SQL input. I write the SQL to be executed through the proper driver, and the result JSON is consumed by grafana.

**Comment by envintus** [comment]
BigQuery datasets as configurable backends would be absolutely _**powerful**_.

**Comment by rdab100** [comment]
+1 MySQL

**Comment by philip-wernersbach** [comment]
@envintus If you have time to contribute, I'd love to have BigQuery support in https://github.com/philip-wernersbach/influx-mysql

**Comment by source-ram** [comment]
sparkSQL +1

**Comment by gsaray101** [comment]
any update on the sql plugin?

**Comment by LosBandolero** [comment]
having raw SQL support in grafana the best 👍 
any updates on this topic ?

**Comment by gbrian** [comment]
My naive try grafana-simple-sql-datasource!
DISCLAIMER: unpolished&clunky beta version ... but works for me 🤣 

https://github.com/gbrian/grafana-simple-sql-datasource

![image](https://cloud.githubusercontent.com/assets/767180/22974756/18b98688-f384-11e6-806c-806c2af9dd7c.png)

**Comment by osigida** [comment]
@gbrian looks good! 

I'm new to sql-js proxies, and have a question: there are different packages for different databases, liek MySql, MSSql, Postgress... 
Is it naive to think that your implementation will work with different DB's? 
If so, how this could be addressed? looks like we need some kinda of abstraction in between...

**Comment by gbrian** [comment]
@osigida, thanks!

Yep, main idea is to have a "xxxproxy.js" file for each SQL-like data source.

Next on my list is Apache Drill (https://drill.apache.org/)
If i did right it should be wasy as creating the proxy and setting up the connector like 
`http://simple-sql-server:port/?con=drill://drilluser:password@drill-server:port`
of course the task is converting datasource schema to simple-sql.

I'll be glad if you test it and send me back some feedback. Please open as many issues you find and I'll try to fix them asap.

Thanks in advance.

**Comment by anayrat** [comment]
@gbrian If you plan to implement Postgres. I'll be glad to help you and test.

**Comment by gsaray101** [comment]
great work. will this be for  oracle also?


Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone
-------- Original message --------From: Gustavo Brian <notifications@github.com> Date: 2/16/17  4:00 AM  (GMT-05:00) To: grafana/grafana <grafana@noreply.github.com> Cc: gsaray101 <gsaray101@yahoo.com>, Comment <comment@noreply.github.com> Subject: Re: [grafana/grafana] Grafana 2.0: SQL Data source (#1542) 
@osigida, thanks!
Yep, main idea is to have a "xxxproxy.js" file for each SQL-like data source.
Next on my list is Apache Drill (https://drill.apache.org/)

If i did right it should be wasy as creating the proxy and setting up the connector like

http://simple-sql-server:port/?con=drill://drilluser:password@drill-server:port

of course the task is converting datasource schema to simple-sql.
I'll be glad if you test it and send me back some feedback. Please open as many issues you find and I'll try to fix them asap.
Thanks in advance.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/grafana/grafana","title":"grafana/grafana","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/grafana/grafana"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gbrian in #1542: @osigida, thanks!\r\n\r\nYep, main idea is to have a \"xxxproxy.js\" file for each SQL-like data source.\r\n\r\nNext on my list is Apache Drill (https://drill.apache.org/)\r\nIf i did right it should be wasy as creating the proxy and setting up the connector like \r\n`http://simple-sql-server:port/?con=drill://drilluser:password@drill-server:port`\r\nof course the task is converting datasource schema to simple-sql.\r\n\r\nI'll be glad if you test it and send me back some feedback. Please open as many issues you find and I'll try to fix them asap.\r\n\r\nThanks in advance."}],"action":{"name":"View Issue","url":"https://github.com/grafana/grafana/issues/1542#issuecomment-280272622"}}}

**Comment by gbrian** [comment]
@anayrat , @gsaray101 

Looks feasible and should be quite easy:
https://www.npmjs.com/package/pg
https://www.npmjs.com/package/strong-oracle

**Comment by dstreppa** [comment]
+1 MySQL

**Comment by GuyCheung** [comment]
+1 MySQL

**Comment by brandonraphael** [comment]
+1 Cassandra

**Comment by sroblin** [comment]
+1 MSSQL +1 MYSQL

**Comment by mattttt** [comment]
HI @epizut: This premium plugin is under development as part of the overall effort. The premium plugin will take advantage of forthcoming core functionality. 

More to come here!

**Comment by chinmaya** [comment]
Are there any known limitations of using cassandra as a grafana data source? Or any other concerns one should be aware of before implementing a datasource plugin?

**Comment by brandonraphael** [comment]
Cassandra isn't a time series database so I don't think you can use it as a
data source in grafana. I am using opentsdb for my grafana data source

**Comment by chinmaya** [comment]
Cassandra supports time-series data modeling? Any thoughts based on [this](https://academy.datastax.com/resources/getting-started-time-series-data-modeling)

**Comment by IceMan81** [comment]
+1 for Apache Drill.

**Comment by poohsen** [comment]
I see the backend part of this PR has been merged but what's the overall status? Is there an ETA for a review and merge of any necessary frontend work?

**Comment by torkelo** [comment]
For MySQL there is a backend part & frontend part, with alert support. No support for Postgres yet

**Comment by jleclanche** [comment]
Postgres support will be really cool to use with http://www.timescale.com/.

**Comment by markfink** [comment]
I would love to see SQL support for athena: http://docs.aws.amazon.com/athena/latest/ug/what-is.html

**Comment by mathurj** [comment]
@torkelo I need assistance with the MySQL Datasource. I have the latest Grafana version installed (v4.4.3)

My grafana host is suppose grafana.host.org and I have an SQL database for an application that is hosted on a different host, let's say application.host.org. I have mysql db on the same application.host.org

When I add a new data source of type MySQL on grafana (i.e. grafana.host.org), it asks me connection details. I add the following details to it:

Host: application.host.org:3306
Database: dbname
User: dbuser
Password: dbpassword

Now when I save and test this connection, it gives me an error saying:

"Error 1045: Access denied for user 'dbuser'@'grafana.host.org' (using password: YES)"

Any leads on a solution to this? Why is it trying to access grafana.host.org when i have specified the db host as application.host.org? I can connect from grafana.host.org to application.host.org fine. However it gives me this error.

My understanding is, it should try to connect to the db on the application.host.org. When i connect to the db on that host on the backend, i get through without a problem.

Your help with thil will be much appreciated.

Thanks,
Jyoti

**Comment by cbandy** [comment]
> Error 1045: Access denied for user 'dbuser'@'grafana.host.org' (using password: YES)

This error is from MySQL. It has recognized that `dbuser` is connecting _from_ the network address that resolves to `grafana.host.org`. Check the permissions, password, etc at MySQL.

**Comment by chroto** [comment]
Any thoughts to supporting Redshift SQL dialect?

**Comment by jleclanche** [comment]
Redshift SQL is just Postgres 8.x family, which should be compatible with the recently-landed Postgres support. Haven't tried it yet but also interested if there's any errors.

**Comment by svenklemm** [comment]
If you dont mind proxying data through postgres you can connect grafana to (almost) any database with postgres foreign data wrapper (https://wiki.postgresql.org/wiki/Foreign_data_wrappers).

**Comment by DenRozhko** [comment]
+1 Oracle DB

**Comment by tammytankian** [comment]
+1 for MS SQL

**Comment by 646826** [comment]
+1 for SQLite

**Comment by linuxchips** [comment]
hi, any one interested in mssql, please check pr #10093

**Comment by gsaray101** [comment]
Has anyone worked on Oracle as data source? I would love to see it.

**Comment by jjeanis** [comment]
@gsaray101 and anyone who's interested - contact support@grafana.com if interested in testing the Oracle beta datasource.

**Comment by daniellee** [comment]
We have merged the Microsoft SQL Server data source to Grafana and it will be released in Grafana 5.1 (#10093, #11298). 

This means that Grafana now has support in core for MySQL, Postgres and MS SQL Server as data sources. We will not be adding any more sql databases as data sources to core Grafana so it is finally time to close this issue.

In the near future, we will have support for backend plugins so it will be possible to have other sql data sources as external plugins.

**Comment by blenard81** [comment]
Anyone looking at adding DB2 LUW support?

**Comment by mnlbox** [comment]
@daniellee what about Oracle and SQLite?

**Comment by daniellee** [comment]
@mnlbox There is an Oracle plugin already: https://grafana.com/plugins/grafana-oracle-datasource (It is not open source however)

Sqlite as a datasource is not on our backlog at all and I haven't heard of anyone working on it.

**Comment by thanhlv93** [comment]
+1 for Presto

**Comment by quentinus95** [comment]
SQLite datasource would be very useful!

**Comment by OverWorldD** [comment]
Sqlite!!!!!

**Comment by 646826** [comment]
Sqlite  !!!!!

**Comment by adlerweb** [comment]
> Sqlite!!!!!

> Sqlite !!!!!

Please use the 👍 function to show your approval and comment only if you can supply additional information, helpful notes, patches and similar - well - comments helping to solve the issue. Spamming developers, contributors or participants probably won't convince anyone to implement your requests.

Daniellee stated above there are no further efforts taken to support additional datasources in core and [plugins](http://docs.grafana.org/plugins/developing/datasources/) are the way to go. Also no one seems to have started working on SQLite so far. If you need a quick and dirty solution and don't want to write/commission/[adapt](https://github.com/grafana/grafana/blob/02ba467bf124b4f044e798eda5b7e8cafef07db1/pkg/tsdb/mysql/mysql.go) a whole plugin for/to [SQLite](https://github.com/mattn/go-sqlite3) it should be somewhat easy to build a smapp proxy-script to serve your SQLite-data as [JSON](https://grafana.com/plugins/grafana-simple-json-datasource) similar to doublemarkets [RRD-Proxy](https://github.com/doublemarket/grafana-rrd-server). Not a great solution speedwise, but you probably wouldn't be using SQLite if thats a concern.

**Comment by daniellee** [comment]
As @adlerweb says, there are currently no plans for the core Grafana team for a core Sqlite datasource. I don't think we would accept a PR for it either. However, we would of course, publish an external datasource plugin on grafana.com if someone wrote it.

**Comment by oz123** [comment]
> Any update on SQLite @daniellee ?

For those interested in SQLite support (or in fact those who wait for any data source), you don't need to wait long. It's pretty easy to write your own data source using Python. The documentation is a bit sparse (see https://github.com/grafana/simple-json-datasource), but it's possible. I have created a fairly extensive example in this [repository](https://gitlab.com/oz123/grafana-python-datasource/tree/master) and a blog post on [how to visualize SQLite with Grafana ](http://oz123.github.io/writings/2019-06-16-Visualize-almost-anything-with-Grafana-and-Python/index.html). The repository also includes a working example of SQLite and a small database for this example.

**Comment by leandro518** [comment]
+ SQLite vote !

**Comment by vevdokimov04041976** [comment]
vote for sqlite

**Comment by loveen** [comment]
> With the backend comes the possibility to have SQL data source.
> 
> My thinking is that when you add the data source you
> 
> * db type (initially only mysql and postgres and sqlite3)
> * db connection details
> * specify a metric query template (basically a SQL query with params)
> * specify a annotation query template
> 
> Maybe also an option to allow RAW SQL queries from the panel metric query interface.
> 
> Any other ideas?

For Sqlite

**Comment by connaisseur** [comment]
Vote for sqlite.

**Comment by Jul10l1r4** [comment]
Sqlite plsss

**Comment by oz123** [comment]
How come this is not mentioned here?
https://github.com/fr-ser/grafana-sqlite-datasource/blob/main/docs/installation.md
