### ISSUE TITLE
elastic error

### ISSUE THREAD

**Issue by yuynagforhacker** [grafana/grafana#15523]
Hello, I want to ask a question. When I visit my dashboard, I get unstable data when I get the elasticsearch data. The specific performance is that the data is failed. The message is as follows:
`rejected execution of org.elasticsearch.transport.TransportService$7@1bb2fc8a on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@21791eb0[Running, pool size = 4, active threads = 4, queued tasks = 1138, completed tasks = 944688]]`
Data can sometimes be acquired and sometimes not available. How to optimize?
elasticsearch version 5.6.12
Grafana Elasticsearch version 3.0.0
Access proxy
Group by time interval 60s
![image](https://user-images.githubusercontent.com/42826446/52998648-c3ea6780-345e-11e9-9d51-bb08d46721e8.png)
Thanks all.

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Since this is related to Elasticsearch and optimization I i would recommend you to use the query inspector in failing panel and extract the query sent to Elasticsearch server (in request) and then refer to that and ask in https://discuss.elastic.co/.
