### ISSUE TITLE
Explore: Log level filter hides results after query changed

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#15627]
0. Loki in Explore
1. Run a query that returns logs with error logs
2. Click the error log level in the chart (filters for error logs)
3. Change the query to return logs that dont have level error

Result: empty result, and there is no indication that lines were returned or that a log level filter is active

Expected:

- to see all new log results if the filtered level does not exist
- or an indicator that there are results, but they are currently hidden, and a way to reset the filter

**Comment by ivanahuckova** [comment]
@davkal This issue was fixed. I have tested several scenarios, but everything works as intended. See videos below.
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/30407135/69556979-0fa9de80-0fa6-11ea-8225-75170b2c749b.gif)

![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/30407135/69557016-2819f900-0fa6-11ea-99bf-d0e365fe439f.gif)
