### ISSUE TITLE
PhantomJS rendering broken in master

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#15635]
### What Grafana version are you using?
master (9efe767)
### What did you do?
Direct link rendered image of a panel using Grafana Testdata datasource
### What was the expected result?
Rendered png
### What happened instead?
Timeout error

### Investigation
A `git bisect` revealed https://github.com/grafana/grafana/commit/425636ff7082e7a8bf8d3bfb1c20c7a1a5fd81a7 introduced the problem. At first this seemed really weird as it only touched Explore/Loki code. Eventually found that the following change in Loki [result_transformer.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/loki/result_transformer.ts) make the rendering work again:

```diff
diff --git a/public/app/plugins/datasource/loki/result_transformer.ts b/public/app/plugins/datasource/loki/result_transformer.ts
index 1fbabba..56a9fac 100644
--- a/public/app/plugins/datasource/loki/result_transformer.ts
+++ b/public/app/plugins/datasource/loki/result_transformer.ts
@@ -1,4 +1,3 @@
-import ansicolor from 'ansicolor';
 import _ from 'lodash';
 import moment from 'moment';
 
@@ -137,7 +136,7 @@ export function processEntry(
     timeLocal,
     uniqueLabels
     hasAnsi,
-    entry: hasAnsi ? ansicolor.strip(line) : line,
+    entry: line,
     raw: line,
     labels: parsedLabels,
     searchWords: search ? [search] : [],

```

**Comment by alexanderzobnin** [comment]
I'm trying to debug phantomjs and found that it fails to load grafana page if `ansicolor` used (in any form, the problem is not a `stripe()` function itself, but the whole module) with following error:
```
If you're seeing this Grafana has failed to load its application files 
1. This could be caused by your reverse proxy settings.
2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath
3. If you have a local dev build make sure you build frontend using: npm run dev, npm run watch, or npm run build
4. Sometimes restarting grafana-server can help
```
That's standard grafana error page if something goes wrong during the page load.

I suggest to extract `strip()` function from `ansicolor` and do not use the whole module.
https://github.com/xpl/ansicolor/blob/master/ansicolor.js#L369

**Comment by alexanderzobnin** [comment]
@davkal Could you take a look and remove `ansicolor` in order to fix this issue?

**Comment by roidelapluie** [comment]
ooh thx

**Comment by roidelapluie** [comment]
I confirm this issue

**Comment by genofire** [comment]
Is it only a problem at loki - or global? maybe it is duplicated with #15631

**Comment by alexanderzobnin** [comment]
@genofire this issue affects all datasources and panels. Looks like phantomjs can't load grafana with ansicolor module included.

**Comment by xpl** [comment]
@davkal @torkelo Hey, I'm author of that `ansicolor` library that had caused your problem and made you have to vendor it. Sorry for that :) I would be super happy to fix the issue in the module itself, so it won't crap people's builds anymore.

I suggest that the problem is that it is not ES5-transpiled, right? I can make it ES5-transpiled no problemo.

Also I have added TypeScript typings to it just recently: https://github.com/xpl/ansicolor/blob/master/ansicolor.d.ts
