### ISSUE TITLE
$__ interval can't be used in Panel Title

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#15645]
I have the Panel which shows rate of change per Interval.  I would like to be able to put the current interval in panel title so it is clear what it shows.  However $__interval  does not seems to be supported in Panel title

Note: User defined Variables work fine.

![image](https://user-images.githubusercontent.com/3651746/53360372-62fddc00-3903-11e9-9863-459fed57d007.png)

![image](https://user-images.githubusercontent.com/3651746/53360514-b1ab7600-3903-11e9-8f87-b74b8b441d7a.png)

**Comment by andreykaipov** [comment]
I remember I also ran into this one a while ago. I'll take a look at this :-)

**Comment by reyjrar** [comment]
Would be useful in the "Label" section for the Y-Axis as well.

**Comment by bigunyak** [comment]
Stumbled on the same limitation. Would be great to have it in the title.

**Comment by BassTester** [comment]
Got the same problem today, would be great if that feature was implemented.

**Comment by Eraac** [comment]
Same here but I find a workaround, you can create a variable of type interval (named interval) with "auto option" enabled. This variable will be available in title

You need to display the variable first to be able to select "Auto" by default, then you can hide it

**Comment by trallnag** [comment]
@Eraac But the calculation of the auto value is not the same as `$__interval`.

I'm definitely bumping this request even though I don't have the knowledge to implement it. I think it is really important to know what the current interval is because it influences the looks of a graph enormously. Just look at the following two graphs:

![image](https://user-images.githubusercontent.com/24834206/89537398-954e8100-d7f9-11ea-96e0-0c8cd65fe6ca.png)

**Comment by pkolyvas** [comment]
I'm going to close this against #36990 which is newer but has more discussion.
