### ISSUE TITLE
Add horizontal scrolling

### ISSUE THREAD

**Issue by oxcsnicho** [grafana/grafana#1565]
It would be super useful if we have some sort of horizontal scrolling for a graph. When viewing a graph, one might want to scroll to earlier time range to take a look at those results. Need some way to keep the length of the time window but move it earlier

**Comment by torkelo** [comment]
good idea,

**Comment by jove1** [comment]
+1

**Comment by mikkoibisense** [comment]
+1 from me

**Comment by jraby** [comment]
that would be really useful,  IIRC Cacti used to have something like this that would allow you to show the previous/next interval.

**Comment by tanioschahine** [comment]
+1
Click dragging the graph to scroll would also be very nice and intuitive.

**Comment by wcombs** [comment]
+1

**Comment by lexh** [comment]
+1

**Comment by dstreppa** [comment]
+1

**Comment by PRI-mcallen** [comment]
+1

**Comment by zerthimon** [comment]
+1000000
This would be a killer feature!

**Comment by aleks-mariusz** [comment]
+1 would be great

**Comment by vskubriev** [comment]
+1.  Would be very great for me.

**Comment by aleks-mariusz** [comment]
might help to discuss what's technically needed for this feature to actually be implemented.   

as i understand it, today how grafana works is it loads a time-range of values from the back-end data source (in my graphite but could be influxdb/opentsdb/etc).. but only the amount of data that corresponds to the current "view" of time.   

however to implement horizontal scrolling, it would need to either a.) load on-demand the data to scroll in one direction or the other, as you scroll, or else, b.) load more data than is actually needed and 'save it' somewhere in memory in hopes you'll use it to scroll.  

the former version would mean you couldn't really scroll that smoothly, as the amount of data needed for the amount of scrolling, couldn't be delivered fast enough, or the speed at which you scroll would be limited by how fast you can load said data.   

and in the latter loading more/extra data than what is needed would not only be wasteful but also reduce performance/user experience

these are the challenges i believe to implement such a feature today, and what are keeping such a feature from having been implemented already.  if you folks have ideas on how to get around them or make them less of an impact, please do chime in.  one thing i can think of off the bat was instead of being able to 'scroll', you would instead 'shift' in one direction or the other, but this certainly couldn't be called 'scrolling' (at least not smoothly), at least with the first approach.

**Comment by vskubriev** [comment]
If shift is easy than scroll. I vote for shift. I think this is really can't be wasteful or can reduce performance. Just load other data by click the button or other control.

**Comment by shlomisut** [comment]
+1

**Comment by mtanda** [comment]
relate to https://github.com/grafana/grafana/issues/1387

**Comment by The-Nik** [comment]
+1

**Comment by zakjan** [comment]
:+1:

**Comment by nikut** [comment]
+1. I would be happy with the "shift" approach, just two buttons next to the time range picker at the top of the dashboard to go back or forward by one time period would do and should be really simple to implement.

**Comment by igsol** [comment]
In addition to just 2 "shift" buttons I'd like to propose following simplified scrolling approach.
When mouse button+Shift key are pressed, instead of making zoom (as it happens currently), it could be nice just to "freeze" getting the new data and just to shift already received data accordant to mouse moving alongside the time axis. After the mouse button is released the new data should be pulled and drawn to fill the "holes" appeared after scrolling. IMHO such approach makes user experience more smooth.
Sorry, if my explanation isn't clear.

**Comment by johnhtodd** [comment]
+1 for shift.  It would be ideal to have the visibility of the shift buttons selectable via a checkbox in the "Display" edit view.

**Comment by gwuillou** [comment]
Hello, I am totally agree to add these features. I think the scroll must be used for zoom in and zoom out and click and shift right or left to move the time range later or earlier. 

Then it will be better to use the Iframe as in the example:
http://docs.grafana.org/reference/sharing/

Now it this not easy to zoom out and to move the time range. It is a little bit tricky

Thank you for all the work done for grafana. It is a beautiful tool. But it could always be better!

**Comment by torkelo** [comment]
![image](https://user-images.githubusercontent.com/10999/39083949-9b633da4-456d-11e8-869d-7ab259214966.png)

the time picker allows you to zoom out and move time frame left and right

**Comment by markprotas-autonomic** [comment]
+1
