### ISSUE TITLE
World map panel not working properly in 6.0.0 stable

### ISSUE THREAD

**Issue by Yukinoshita-Yukino** [grafana/grafana#15654]
Please include this information:
### What Grafana version are you using?
Grafana v6.0.0 (34a9a62)
### What datasource are you using?
Elasticsearch 6.3.1
### What OS are you running grafana on?
Centos
### What did you do?
Just upgraded to Grafana V6.0.0 and the world map is not working properly as before
### What was the expected result?
Workd map working properly
### What happened instead?
Just load some dashboard with world map configured in previous version. 
The bottom part of the world map just failed to load.
But if you hit the `refresh` button on the upper right corner the world map works fine again.
<img width="1232" alt="wx20190226-155240 2x" src="https://user-images.githubusercontent.com/3638888/53396099-9497a580-39de-11e9-8216-de0b4cdb54b0.png">
No error in chrome console.
Just some unrelated warning I guess.
<img width="772" alt="wx20190226-160307 2x" src="https://user-images.githubusercontent.com/3638888/53396689-0f14f500-39e0-11e9-987e-0fce620dbd7f.png">
After click the `refresh` button
<img width="1233" alt="wx20190226-160751 2x" src="https://user-images.githubusercontent.com/3638888/53396965-d295c900-39e0-11e9-88cf-cde8d786b562.png">
<br>
<br>
 Another problem is that if I click on the `view` button for world map pannel, it will leave tons of space on the bottom, you still have to hit the refresh button to make it working properly.
<img width="2548" alt="wx20190226-155541 2x" src="https://user-images.githubusercontent.com/3638888/53396392-48009a00-39df-11e9-9810-27bfa26c84e2.png">
However this time the console got some error, not sure if it's related though.
<img width="773" alt="wx20190226-160210 2x" src="https://user-images.githubusercontent.com/3638888/53396647-f1479000-39df-11e9-90f3-f0099be979ea.png">
After click the `refresh` button
<img width="2546" alt="wx20190226-160822 2x" src="https://user-images.githubusercontent.com/3638888/53396982-d7f31380-39e0-11e9-8bae-eb83e9fecd08.png">
<br>
<br>
Neither of these two problems was in v5.4.3.
BTW I think this problem is somehow related to #15406. 
But since I got some more problems (clicking on view) so I opened a new issue.

**Comment by xlson** [comment]
Are you running the latest version of worldmap panel (0.2.0)?

**Comment by Yukinoshita-Yukino** [comment]
Oh so the worldmap is updated separately as plugin.
Sorry my bad.
I am closing this one.

**Comment by amotl** [comment]
Hi there,

while the issue obviously has been resolved for @Yukinoshita-Yukino, some others are experiencing similar erratic behavior on Worldmap.

We tried hard to mitigate any timing problems we experienced with the combination of Grafana and Worldmap within [1,2].

The most recent release of the upcoming Worldmap Panel designated to be mainlined can be installed side by side through:
```
grafana-cli \
  --pluginUrl https://github.com/hiveeyes/grafana-worldmap-panel/releases/download/0.4.0/grafana-worldmap-panel-ng-0.4.0.zip \
  plugins install grafana-worldmap-panel-ng
```

Please be aware that while we believe it should work pretty well for most people, it is officially considered to be beta quality, so you should know what you are doing when running this guy in production.

Saying this, we will be happy about any feedback in order to work on any remaining issues experienced by users from the community.

With kind regards,
Andreas.

[1] https://github.com/hiveeyes/grafana-worldmap-panel
[2] https://community.grafana.com/t/giving-the-grafana-worldmap-panel-some-love/17210
