### ISSUE TITLE
Setting permissions for individual panels in a dashboard

### ISSUE THREAD

**Issue by debmalyapan53** [grafana/grafana#15684]
Using grafana v6 built from source on win10...

 Basically I want the edit option enabled for only the graph panel, and disabled for all other panels present in my dashboard. 
How can I do it?

**Comment by xlson** [comment]
That is not possible at this time. You can control access for the whole dashboard but not individual panels.

**Comment by debmalyapan53** [comment]
@xlson Can you make this as a feature request?

**Comment by torkelo** [comment]
permissions on individual panels feels very unlikely to ever happen :)

Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.

**Comment by ibnpaul** [comment]
I'd like to +1 this. Our use case for it is panels that contain alerts; for our production environment we want to be able to disallow editing of the panel unless someone has specific permissions due to the sensitive nature of production alerts.

**Comment by debmalyapan53** [comment]
> I'd like to +1 this. Our use case for it is panels that contain alerts; for our production environment we want to be able to disallow editing of the panel unless someone has specific permissions due to the sensitive nature of production alerts.

Yeah, I opened this issue for the same use case.
