### ISSUE TITLE
Grafana 2 RPMs contain binaries which are broken on various flavors of Red Hat Linux

### ISSUE THREAD

**Issue by ajsmith** [grafana/grafana#1568]
I see the following error when I attempt to run the 'grafana' binary on a RHEL6 system:

    [user@localhost ~]$ /opt/grafana/current/grafana 
    /opt/grafana/current/grafana: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/grafana/current/grafana)

As seen above, the 'grafana' binary requires glibc version 2.14, and it's broken because I have a different version of glibc installed:

    [user@localhost ~]$ rpm -q glibc
    glibc-2.12-1.149.el6_6.5.x86_64

The system I'm testing on is RHEL 6.6, but other versions of Fedora, RHEL, and CentOS will be broken by this too.

**Comment by mzupan** [comment]
I see the same issue. Looks like the rpm is built on centos7 or el7

**Comment by torkelo** [comment]
yea, seen this as well, seems to a problem for many binaries built with the latest go compiles on ubuntu 14 or centos7 systems,  

Anyone know of a work around or fix?

**Comment by ajsmith** [comment]
@torkelo The fix should just be to rebuild the RPM for each Red Hat system you plan to target. If you have a source RPM, this is easy to do. Assuming you're already have an instance of the Red Hat OS you're building for, you'd run something like:

    rpmbuild --rebuild grafana-<some-version>.src.rpm

The 'rpmbuild' command comes from the 'rpm-build' package on Red Hat systems.

I'm not sure how FPM does things, but it can probably export a source RPM for you.

**Comment by torkelo** [comment]
So worked all day on solving this. Not so easy when you want to build packages in a CI system like wercker or circle ci, they both use ubuntu12 based images which has newer glibc 

I need to build the packages inside a centos6.6 docker container (on wercker or circle ci). I migrated to circle ci because it was fast and had better docker & caching support. Then opted to move the the centos6.6 docker container and process to its own repo in order to not slow down the test CI build on circle CI. 

https://github.com/grafana/grafana-packer
https://circleci.com/gh/grafana/grafana-packer 

It is its own repo but it has a cached & prepared centos6.6 container that will fetch latest from grafana/grafana  develop branch and build packages and publish to s3. 

So the rpm & debs & binary tar are now updated (built on centos 6.6)
http://grafana.org/download/builds

I have tested the binaries and they work on Centos5.11, centos 6 - 7, debian wheezy, debian jessie. On Centos5.11 you need to run "useradd -r grafana" before installing the package. 

Any feedback is much appreciated!

**Comment by ajsmith** [comment]
I verified the Grafana binary is now working on my RHEL 6.6 box. Thanks for the fix!

**Comment by torkelo** [comment]
@ajsmith thank you for the feedback! Will close this one. 

And related to this have built a new docs system and docs site (docs are now in the main repo, using mkdocs, docs has search!), 

I have JUST started on updating and writing new docs, so they will be very ruff and incomplete in the coming days, but hope have time to update and polish them enough to feel comfortable to have a beta release soon. 
http://docs.grafana.org/v2.0/installation/

**Comment by torkelo** [comment]
If anyone has time, I have started doing install & config docs, 
http://docs.grafana.org/v2.0/installation/ 
http://docs.grafana.org/v2.0/installation/configuration/

Feedback would be great
