### ISSUE TITLE
Every user can access a list of all other users.

### ISSUE THREAD

**Issue by passing** [grafana/grafana#15708]
I noticed that if I open the URL /org/users on Grafana with any user, I can see a list of all other users, even when only having 'Viewer' permissions:

![image](https://user-images.githubusercontent.com/8142186/53561036-06dac800-3b4e-11e9-9a6c-b2e7bfd816a9.png)

This can be easily reproduced using the grafana docker image:
```
docker run -ti -p 3000:3000 -e GF_AUTH_ANONYMOUS_ENABLED=true grafana/grafana:6.0.0
```
And then opening that link in your browser:
http://localhost:3000/org/users

**Comment by pitr** [comment]
Same for
- http://localhost:3000/org/teams
- http://localhost:3000/plugins (probably not a big deal)
- http://localhost:3000/org (can't save settings)

**Comment by xlson** [comment]
Thanks for reporting this.

**Comment by torkelo** [comment]
So this is fixed but just so you know the list of org users is open in Grafana by design for any member of the org (viewer & editor roles).  

So via the api any viewer user can fetch the complete list of org members. This api is open to users with only viewer or editor role as it is required to do user lookup for dashboard folder permissions. User with viewer role can be assigned admin for a folder and need then to be able admin permissions (and look up users).

Similar how you can search for add any GitHub member to a team or org.
