### ISSUE TITLE
Scrollbar issues in v6.0

### ISSUE THREAD

**Issue by gjcarneiro** [grafana/grafana#15711]
### What Grafana version are you using?
6.0.0
### What datasource are you using?
N/A
### What OS are you running grafana on?
docker
browser is: Chrome Version 72.0.3626.119 (Official Build) (64-bit)

### What did you do?
load page, drag mouse to right edge of screen, no scrollbar!

### What was the expected result?

I expect a scrollbar to appear, I expect to be able to click it easily.  The scrollbar should always be visible, and it should be easy to drag it using the mouse.

You assume that people always use scroll wheel every time.  That is not the case: dragging the scroll bar with the mouse lets you scroll faster and with more precise control.

Similarly, when you open a dashboard for the first time, it's nice to be able to hit the keyboard page down key, or down arrow, to have the page scroll.

### What happened instead?

Several annoyances:
1. the scroll bar only appears after you use the mouse wheel for the first time;
2. even when it appears, if you shove the mouse all the way to the right edge of the page, and click, it doesn't drag the scrollbar.  You have to go back left a few pixels in order to be able to drag the scrollbar.  This violates Fitts Law;
3. on first page load, keyboard doesn't work, for scrolling.

Possibly related: https://github.com/grafana/grafana/issues/14762

Note: already lots of people complained when you removed the native scrollbar when grafana 5.0.0 was released, see https://github.com/grafana/grafana/issues/11053

**Comment by torkelo** [comment]
The right edge of the screen issue will be fixed.

If your os or browser supports overlay scrollbar it will be a native scrollbar. It’s not so much about being pretty but that overlay scrollbar solve some usability issues and performance issues.

**Comment by torkelo** [comment]
The 2) issue with scrollbar not being at the far right was fixed (on all pages except dashboard), but looks like that fix is only in master. 

1.  This looks like only an issue on the dashboard page, will investigate. 

This new scrollbar is much better than the last, it's completely disabled if os or browser has overlay scrollbars enabled (most of OSX users in both firefox and chrome and safari) and is 100% native otherwise as well, just margin that hides the native one. The component helps with a number of issues but we can find alternatives as well if there are more reports of issues.

The not being able to use up/down keys without focusing page is annoying, we can try to fix. We will track if more have issues, your the first to have any problems with it again. Believe me we are not trying to cause you troubles we are doing this for good reasons.

**Comment by gjcarneiro** [comment]
Yeah, sorry, I was a bit inflammatory.  I edited my previous comment.  It seemed to me, on the surface, to be exactly the same problem we had in the v5.0.0 release, but I don't know the details.

**Comment by gjcarneiro** [comment]
When I say "The scrollbar should always be visible", personally I think it's fine if the scrollbar appears when the mouse moves.  But is pretty annoying if it only appears when you use the scroll wheel the first time.

**Comment by morozovsk** [comment]
> if you shove the mouse all the way to the right edge of the page, and click, it doesn't drag the scrollbar. You have to go back left a few pixels in order to be able to drag the scrollbar. This violates Fitts Law;

New scrollbar is absolutely not usable. I feel pain every time when I try to use it.

**Comment by torkelo** [comment]
> morozovsk

The problem of the scrollbar not being at the far right is already fixed. Can you try latest nightly build?  
https://grafana.com/grafana/download/nightly

I also opened a PR for it not showing initially, will be merged soon.

**Comment by morozovsk** [comment]
OMG! it works very nice! Many thanks!

**Comment by morozovsk** [comment]
Now scroll doesn't work when mouse over scrollbar.
Finally I returned to 5.4.3.
