### ISSUE TITLE
Alerts to Email are not sending images-----Grafana6.0.0

### ISSUE THREAD

**Issue by mjesse88** [grafana/grafana#15723]
Please include this information:
### What Grafana version are you using?
Grafana-6.0.0
### What datasource are you using?
Influxdb
### What OS are you running grafana on?
Centos 7.0
### What did you do?
Send alert successfully,but it can't include images.
### What was the expected result?
the notification channel I enable "include image", and 
external-image-storage try to open provider=local, but it also can't work.
### What happened instead?
I open the log levl to debug, but debug msg is normal:
![image](https://user-images.githubusercontent.com/19406155/53615170-ab750c80-3c17-11e9-833d-22f3abbb3428.png)

the grafana 4.3 it can works for me , i only use rpm to update to grafana 6.0.0

I really need this images on  email.

Thanks very much
mjesse88

**Comment by mjesse88** [comment]
and, I click “Send Test” on notification channe page, I can receive the email that includes image, but it can't work when my graph.

**Comment by roidelapluie** [comment]
Not sure if related, but since 6.0 we can not generate PNG

Mar 01 13:02:23 grafana01 grafana-server[25341]: t=2019-03-01T13:02:23+0100 lvl=info msg=Rendering logger=rendering path=d-solo/nippin-general/nippin-nippin-general-dashboard?
Mar 01 13:03:25 grafana01 grafana-server[25341]: t=2019-03-01T13:03:25+0100 lvl=info msg="Rendering timed out" logger=rendering
Mar 01 13:03:25 grafana01 grafana-server[25341]: t=2019-03-01T13:03:25+0100 lvl=eror msg="Timeout error. You can set timeout in seconds with &timeout url parameter" logger=context userId=45 orgId=1 uname=prometheus error="Timeout error. You can set timeout in seconds with &timeout url parameter"

**Comment by mjesse88** [comment]
Hello everyone，

I find the phenomenon: it can send email with images if grafana save the screenshot on /var/lib/grafan/png.  it send more than 100 email. only one png save it,so I receive this email include image. But only one email.

Thanks very much.
mjesse88

**Comment by ReasonDuan** [comment]
You can update the configuration file to the latest. I have encountered the same problems as you have before.

**Comment by ReasonDuan** [comment]
> Hello everyone，
> 
> I find the phenomenon: it can send email with images if grafana save the screenshot on /var/lib/grafan/png. it send more than 100 email on weekend. only one png save it,so I receive this email include image. But only one email, Then I try send email with this grah, it also can include image,
> but others grah can't. i donot know why , my all graphs is the same settting about alert setting, and recevier all is the same.
> 
> Thanks very much.
> mjesse88

You can update the configuration file to the latest. I have encountered the same problems as you have before.

**Comment by marefr** [comment]
Image rendering issues should be fixed in v6.0.1 so closing this. Reference #15631

**Comment by mjesse88** [comment]
Thank for your respone, I updated the Grafana to V6.0.1, the problem is gone.

Thanks again.
mjesse88
