### ISSUE TITLE
Allow an option to turn on/off the key bindings of grafana

### ISSUE THREAD

**Issue by debmalyapan53** [grafana/grafana#15748]
Allow an option to turn on/off the key bindings of grafana.
It would probably be nice if someone would be able to just toggle it from the **custom.ini** file itself.

**Comment by torkelo** [comment]
Is there any specific key binding you want to turn off? 

Not sure we are going to have server-wide option for this. Maybe in the future, we can have a user profile option,

**Comment by torkelo** [comment]
Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.

**Comment by debmalyapan53** [comment]
> Is there any specific key binding you want to turn off?
> 
> Not sure we are going to have server-wide option for this. Maybe in the future, we can have a user profile option,

@torkelo Not anything specific, I want to turn off all bindings. Maybe if not in the backend, any option in the front-end will do.
