### ISSUE TITLE
Treat metric query errors as zero

### ISSUE THREAD

**Issue by saurabh-86** [grafana/grafana#1577]
Feature request.

It would be nice if a graph panel could be configured such that it treated any failed query to a datastore as zero value, or some other configurable default.

For example, our application increments a metric counter in OpenTSDB when a failure occurs. Our scripted dashboard plots this data. However, if there has been no failure yet, that metric doesn't exist on the OpenTSDB datastore. In such a scenario, OpenTSDB returns a 500 to grafana, and the user sees a "Timeseries data request error".

**Comment by cboggs** [comment]
I like this idea, but I think Grafana should default to its current behavior of displaying the error - mainly because it aids in troubleshooting. When you see an error and hit the little red icon, you get a pretty quick idea as to what's happening and that you (in my case, anyway) have likely mistyped a series name or something.

To avoid errors for series whose names I've typed correctly but might not yet exist due to some external event not having occurred yet, I just bootstrap the series names I know of ahead of time. Insert a single null value at now-1year, and then the series exists for my dashboards. :-)

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
