### ISSUE TITLE
Editing row properties is still not possible in 6.0.0 stable

### ISSUE THREAD

**Issue by gitgia** [grafana/grafana#15800]
### What Grafana version are you using?
6.0.0 Stable
### What datasource are you using?
InfluxDB 1.7.3
### What OS are you running grafana on?
Ubuntu 18.4
### What did you do?
Tried to edit the row name
### What happened instead?
Grey screen

angular.js:14700 Error: [$compile:tpload] Failed to load template: public/app/features/dashboard/partials/row_options.html (HTTP status: 404 )
http://errors.angularjs.org/1.6.6/$compile/tpload?p0=public%2Fapp%2Ffeatures%2Fdashboard%2Fpartials%2Frow_options.html&p1=404&p2=
at angular.js:116
at angular.js:20254
at angular.js:17051
at angular.js:17095
at l.$digest (angular.js:18232)
at l.$apply (angular.js:18531)
at angular.js:18832
at h (angular.js:6362)
at angular.js:6642

**Comment by daniellee** [comment]
I can't recreate this. Renaming rows works for me - I could rename a row [on play.grafana.org](https://play.grafana.org/d/000000153/repeat-rows?orgId=1). 

It was fixed in #15159 which is included in 6.0.

I can also not find any reference to the row_options.html in the code for 6.0 ([the code](https://github.com/grafana/grafana/blob/v6.0.0/public/app/features/dashboard/components/RowOptions/RowOptionsCtrl.ts#L27) for the row options points to another template). 

How did you install Grafana 6.0? Or is something cached?

**Comment by gitgia** [comment]
It seems, something was not ok with our Docker volumes, after I deleted the existing ones and created new volumes, now it works.
