### ISSUE TITLE
New users not showing in "Add team member" to Teams dropdown list

### ISSUE THREAD

**Issue by mlmarloth** [grafana/grafana#15848]
### What Grafana version are you using?
6.0.1
### What datasource are you using?
sqlite
### What OS are you running grafana on?
Windows server 2016
### What did you do?
Create a new user, via ldap, try to add it to a team for permissions
### What was the expected result?
To see and select new user from "add team member" list
### What happened instead?
Only see users we had from versions before upgrade < 6

**Comment by bergquist** [comment]
> Create a new user, via ldap, try to add it to a team for permissions

The user needs to login to Grafana before the user is created without Grafana. Currently Grafana does not support syncing its user with LDAP in the background. 

That is something we plan to support in our Enterprise version. http://docs.grafana.org/auth/enhanced_ldap/

Closing this since I cant reproduce this when I log in users using ldap. Ping me if something is unclear and I will open it.

**Comment by mlmarloth** [comment]
Misunderstood, the user logs in, the user is created on the system and it exists in Grafana. But the user doesn't show up in add to team.

**Comment by marefr** [comment]
@mlmarloth please search/filter for the user in the drop down and you should find it.

**Comment by mlmarloth** [comment]
nope, nothing. I'm reverting to editing the DB. Just wondering if anyone is picking up the same issue otherwise it is this installation specific.

**Comment by bergquist** [comment]
Could this be an sqlite + windows problem?

**Comment by mlmarloth** [comment]
Could be. It used to work though. Just wondering if something significant changed between version 5 to 6 to cause this.

**Comment by torkelo** [comment]
The add team member user list has a limit of 10. But then you should be able to search for the user. 

Can you open chrome dev tools network tab and show a search query that returns empty and a result of the same api call for the Users page where the user is shown?

**Comment by mlmarloth** [comment]
> The add team member user list has a limit of 10. But then you should be able to search for the user.
> 
> Can you open chrome dev tools network tab and show a search query that returns empty and a result of the same api call for the Users page where the user is shown?

Yup, that's it. My mistake. I was "searching" then expecting to "add", instead of "add" then search. Assumed with the scrolling dropdown that it is all it is finding.

**Comment by viberan** [comment]
hey, just wanted to leave feedback on user experience here
I have had exactly the same problem for months, being not able to figure out why I could not add a user to a team since it did not show up in the drop down list. It's not apparent at all that one should start typing the name to search for a particular user. I was convinced that was a bug in grafana to not show all of the users... until I came across this page and seems I was not alone...
Perphaps it's something that needs improvement in the UI

**Comment by HIMADRI518** [comment]
+1, faced the exact same issue. The UI should definitely be fixed. I am glad I found this repo and realized I was searching the wrong way.

**Comment by Tirex** [comment]
+1, very non intuitive UI

**Comment by mikkokotila** [comment]
I think it could be better by saying in the search box something like "type to see more options..."
