### ISSUE TITLE
Common Time Regions definition for all Panels in Dashboard

### ISSUE THREAD

**Issue by sysrek** [grafana/grafana#15899]
**What would you like to be added**:
- Add possibility to create common Time regions for all panels on dashboard in JSON file. 

Nice to have:
- possibility of individual configuration of panel (modification time of common time regions, adding new time regions for dedicated panel, not displaying Time regions for dedicated panel).

**Why is this needed**:
In case when Dashboard contains a large number of panels and we want to define or reconfigure a Time regions we can do this once. We don't need to do this for each panel. We save the time and make it simpler for automatyzation.

**Comment by torkelo** [comment]
> In case when Dashboard contains a large number of panels and we want to define or reconfigure a Time regions we can do this once. We don't need to do this for each panel. We save the time and make it simpler for automatyzation.

The dashboad time range is already applied to all panels, so you can change time region and have that applied to all panels. Beyond that you can define a relative override for each panel & timeshift. 

Do no think we need more panel specific time range options. 

Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.

**Comment by torkelo** [comment]
Sorry, did not understand you were talking about the graph time region highlights.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
