### ISSUE TITLE
Introduce semantic commits convention

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#16021]
*Following @marefr proposal and things we discussed during PR retrospective*

Goals:
- introduce basic commits convention 
- automate meaningful change log creation
- long run: semantic releases https://blog.greenkeeper.io/introduction-to-semantic-release-33f73b117c8

## What is a semantic commit message?
It's a commit message that holds meaningful information about commit's **type** and optionally **scope** along with regular commit description: `type(scope): commit message`. I.e.
```
fix(explore): fixed number deduplication strategy returning non deduped log results
```

- According to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.3/) the types of commit messages are `chore, docs, feat, fix, refactor, style, test, perf`
- https://seesparkbox.com/foundry/semantic_commit_messages

## Possible solutions
1. git aliases
As simple as it is, everyone on the team can create their own git aliases for semantic commits authoring (https://adrianwong.fun/semantic-commit-messages/). To make it easier there is ready made script available, that creates the aliases automatically for you: https://github.com/fteem/git-semantic-commits

2. [`cz-cli`](https://github.com/commitizen/cz-cli) npm package
We can either introduce this package to our codebase or assume that each team member/contributor installs in their environment. By introducing `commit` script to our npm scripts, semantic commit messages would be created using `cz-cli`'s prompts:
![image](https://user-images.githubusercontent.com/2376619/54424013-468add80-4712-11e9-955e-e6b954a768dc.png)
So, when creating the commit one would use `yarn commit` instead of `git commit`

Above solutions address the need for semantic commits, but we also need those rules to be:
- **acknowledged** by both Grafana team and contributors
- **enforced**, to actually make use of them

### Acknowledge semantic commits
We can take inspiration from other open source projects and introduce **commits convention** to our contributions guideline: 
- [Vue's commit convention](https://github.com/vuejs/vue/blob/39d58e521a4a6bc4c0d42f17453421ae155ec04f/.github/COMMIT_CONVENTION.md)
- [Angular's commit convention](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit)
- [Karma's commit convention](http://karma-runner.github.io/3.0/dev/git-commit-msg.html)

### Enforce semantic commits
To automate PR's validation agains semantic commits we can use https://github.com/probot/semantic-pull-requests bot with `commitsOnly` option enabled, until we follow up on semantic PRs. It gives a nice feedback to PR author in the PR's checks section: 
![image](https://user-images.githubusercontent.com/2376619/54425102-cade6000-4714-11e9-8d5e-1c82d6145917.png)

**Comment by aocenas** [comment]
To be able to do automatic change log and get commits like in angular/vue/karma we would also need to either:
- `Rebase and merge` -> this would mean you would have to clean up all the commits before merge, so that all commits are meaningful and semantic.
- `Squash and merge` -> This would mean you would have to write the squashed commit message (most times in Github I assume) so that it is semantic (is it possible to check it before actual merge when doing that in Github?). So for example having commits: `[fix(explore): description,  test(explore): desc]` would result in one `fix(explore): description` commit in master. There is also a possibility you do not need have all commits in PR semantic as only the squashed one will remain.
- `Create a merge commit` -> I assume you cannot alter the message in Github or can you? If not this would not give you much benefit.

Are those assumptions correct? From looking at the angular/vue/karma they seem to be doing the `Squash and merge` variant but still having all PR commits semantic and also having a PR title in the same structure.

**Comment by bergquist** [comment]
I love the idea of writing informative commit messages that contains both a title, description and links to associated issues. 

But I'm curious what problem we are trying to solve with these restrictions?
I've used the chore, docs, feat, fix, refactor, style, or test categorization before and I'm not sure its added any actual value. 

Generating the changelog based on commits seems fragile to me. What if we want to correct/edit something? I would prefer generating it based on issues or PR's since we could edit those and regenerated the changelog.

**Comment by torkelo** [comment]
We used to do this for all commits, not sure why we stopped. maybe repetition in "fix(dashboard): fix..." 

But I am all for some standard to improve & make commits more consistent and readable.
