### ISSUE TITLE
Upgrade font-awesome from 4.7.0 to 5.8

### ISSUE THREAD

**Issue by wetterfrosch** [grafana/grafana#16074]
**What would you like to be added**:
I would like to have an update of font awesome from version 4.7.0 to ~~5.7.2~~ 5.8 :)

**Why is this needed**:
There are many new icons, like :sun_behind_large_cloud:!

A previous update is mentioned in [issue #1311](https://github.com/grafana/grafana/issues/1311).

**Comment by joshuawoodward** [comment]
Seems like a bit of work for this. https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

Also 5.8 released today :)

**Comment by angelinn** [comment]
I tried updating to 5.8 manually on my installation by replacing the sass files in public/sass/fontawesome and the new webfonts in public/fonts.

This produced no result, the icons just totally disappeared. Can you suggest how should the update happen?

**Comment by wetterfrosch** [comment]
> Can you suggest how should the update happen?

Maybe have a look at @torkelo's last commit for upgrading Fontawesome: https://github.com/grafana/grafana/commit/1f1244f285badcb8110f9bc1927dfa69f3b3af7d

This looks really ... complex.

**Comment by angelinn** [comment]
In this commit the grafana folder structure looks very different, also less is used instead of scss. The font-awesome css file is just a single file, now there are multiple files.

What i've tried since yesterday is to edit public/sass/_variables.scss, where i noticed the `fa-font-path` variable in the new fontawesome version wasn't set correctly, but after setting it to `../fonts' nothing changed.

**Comment by hugohaggmark** [comment]
Closing this issue as we're limiting the use of FontAwesome in favor of [React Unicons](https://github.com/Iconscout/react-unicons).

Thank You to you for taking the time to create this issue!
