### ISSUE TITLE
Group dashboards in folders

### ISSUE THREAD

**Issue by costimuraru** [grafana/grafana#1611]
There is currently no way of grouping dashboards, other than tag them with a common label. Things get messy quickly, when multiple teams create new dashboards or there are many apps that need to be monitored.
I've long been wishing for a way of grouping related dashboards. GDash used to offer something like this and it was very helpful in organizing dashboards. 

Grouping dashboards into folders may look something like this:
![image](https://cloud.githubusercontent.com/assets/952836/6709168/6f3722ae-cd7f-11e4-9e54-6573bd09da2c.png)

What do you think?

**Comment by toni-moreno** [comment]
:+1:

**Comment by torkelo** [comment]
Good feedback and mockup! I think this makes a lot of sense, Dashboard folders will also be good abstraction to place permissions on when permission on dashboard / dashboard folders will be needed.

**Comment by biancalana** [comment]
:+1:

**Comment by phagedorn** [comment]
:+1:

**Comment by sahilthapar** [comment]
:+1:

**Comment by pasancario** [comment]
:+1:

**Comment by bigkraig** [comment]
:+1:

**Comment by cemo** [comment]
:+1:

**Comment by agaon** [comment]
:+1:

**Comment by liyichao** [comment]
:+1:

**Comment by aibou** [comment]
:+1:

**Comment by iDemonix** [comment]
:+1:

**Comment by liyichao** [comment]
:+1

**Comment by andrejlucansky** [comment]
:+1:

**Comment by xneo64** [comment]
:+1:

**Comment by adriapa5** [comment]
:+1:

**Comment by findneville** [comment]
:thumbsup:

**Comment by pavleec** [comment]
:+1:

**Comment by mkeagar** [comment]
:+1:

In my company we were currently trying to use the Organizations feature to separate out different groups dashboards, but this causes problems for some managers who oversee different but related groups when they try to view the dashboards side by side in separate browser windows.

I realize we're using organizations incorrectly, so I am excited for this feature (Dashboard groups/folders with permissions) to be implemented.

**Comment by vlitvin** [comment]
:+1:

**Comment by sacasumo** [comment]
👍

**Comment by hxuanhung** [comment]
+1

**Comment by smeapng** [comment]
+1

**Comment by shalstea** [comment]
We would be very interested in seeing this one worked on.

**Comment by leigh507** [comment]
+1

**Comment by ehatch90** [comment]
We are really looking forward to this at my company. Will this 4.0 release include some kind of group permissions on the folders used to organize the dashboards?

**Comment by ekarak** [comment]
+1

**Comment by mbarragan** [comment]
+1

**Comment by un1x01d** [comment]
+1

**Comment by Alexul** [comment]
+1

**Comment by kotwal13aditya** [comment]
+1

**Comment by wfortin136** [comment]
👍

**Comment by biker73** [comment]
+1

**Comment by mattpoel** [comment]
:thumbsup:

**Comment by shalstea** [comment]
Getting folders first without LDAP / permissions around them would be a useful first step.  LDAP could be phase 2.

**Comment by mahendra** [comment]
👍

**Comment by royemmerich** [comment]
I see this topic is starting to attract some Raintank LUV (see: [Grafana 4.2 Beta Release](http://grafana.org/blog/2017/02/27/grafana-4.2-beta-release/#improved-support-for-multi-org-setup)), which is **great** and essential for better multi-tenancy support. YAY!

I'd like to highlight @madshall's comment about including datasource groups/permissions here:
https://github.com/grafana/grafana/issues/4893#issuecomment-226174772, which seems to go hand in glove with creating dashboard groups/permissions. Having one without the other would be incomplete in terms of data access security.

In terms of the planned "improved support for multi-org setup" development, how far will this development will be taken in terms of feature request #4893?

**Comment by max3163** [comment]
+1

**Comment by daniellee** [comment]
# Proposal: Dashboard Folders and a Permissions Model

## Overview

From this [issue](https://github.com/grafana/grafana/issues/1611):
> There is currently no way of grouping dashboards, other than tag them with a common label. Things get messy quickly, when multiple teams create new dashboards or there are many apps that need to be monitored.

There is also a demand for a more fine grained permissions model, both for dashboards and data sources. This feature should also solve that requirement.

## Goals

We want to keep this is as simple as possible. It should be
- Easy to understand.
- Easy to share folders with other users.
- Have minimal overhead for small organizations that do not need fine grained permissions.

## Proposal for Dashboard Folders

Folders will be a way to group dashboards:

- A dashboard can only belong to one folder.
- A Dashboard Folder has an owner - per default the user who creates the folder.
- Folders will be visible to everyone. If a user has access then they will be able to see the dashboards, if not then they will be able to see the Dashboard Folder owner (so that they know who to ask to request access).
- Dashboard search will also return Dashboard Folders in the search result.
- Each Dashboard Folder will have a home page that lists the dashboards and for admins/owners -> the list of users and permissions for the Folder.

To keep this first version simple, we propose only allowing one level of folders. Not having subfolders hugely simplifies the permissions model that is described below.

## Current Permissions Model

Dashboards are connected to an org. All users in an org have access to its dashboards. Roles are used to control read/write and admin access. Grafana currently has four roles: Admin, Editor, Read-only Editor and Viewer. Admins and Editors have full control over all dashboards. Admins can create/edit data sources. Read-only Editors can see the metrics tab and make changes but are not allowed to save (like on http://play.grafana.org). Viewers can view dashboards but cannot edit or save anything.

## Proposal for a new Permissions Model

This proposal introduces an Access Control List (ACL) model with user groups for Dashboard Folders. The default is that everyone has access to a folder and that their permissions depend on their user role (Admin, Editor etc.). An Admin or Editor can remove the default access for everyone and can then assign a user or user group to a Dashboard Folder and an ACL is created that controls permissions for the Dashboard Folder. User groups make it easier to assign permissions for multiple users to multiple dashboards.

- The user who creates the folder is the owner. The owner can be changed by an admin.
- Per default, the ACL contains the Admin, Editor, Read-only Editor and Viewer groups (based on the user roles).
- The permissions that can be assigned for a folder are: View, Edit, Read-only Edit.
- Users with the Admin and Editor role are allowed to create new Dashboard Folders.
- Users with the Viewer role are not allowed to create new Dashboard Folders.
- Editors who are owners and Admins can assign permissions to users or user groups for Dashboard Folders.
- Default permissions can be removed except for the Admin permissions (View, Edit). Example: if you want a dashboard folder with limited permissions, you go to the security tab, remove the default permissions (everyone edit / view), specify:  frontend-team  edit / view and ops : view
- A user group is a list of users. A user group can be assigned permissions in the ACL of a dashboard folder or data source.
- Admins can create user groups.
- User groups cannot contain user groups.
- If a user belongs to multiple groups, their permissions would be merged to give them the highest permissions possible.
- At a later stage, this ACL model will be extended to data sources.

### Use Case for Dashboard Folder Permissions

This [feature request](https://github.com/grafana/grafana/issues/4893) describes a complicated scenario with sub groups. This proposal should support this scenario except for the subgroups. To keep the complexity down, there is only one level of hierarchy. The subgroups use case would have to be worked around with some sort of naming convention e.g. Group1_SubGroup1.

## Feedback

We would love your feedback on this. The aim is to cover the use case above while still keeping it simple and intuitive for most of our users. This is why we chose the folder/directory metaphor and the ACL model as we believe that it should be familiar to most people.

Specific points that we we would really like feedback on:
- Should Dashboard Folders permissions be limited to just user groups or should it be possible to add both groups and individual users?
- Should it be possible to remove Admin permissions to make a Dashboard Folder private?
- Should we have an Admin permission for Dashboard Folders so that multiple users can administrate the permissions?

References:

- [Admin Roles](http://docs.grafana.org/reference/admin/)
- [Issue for Dashboard Folders](https://github.com/grafana/grafana/issues/1611) - #1611
- [Issue for User permissions per dashboard](https://github.com/grafana/grafana/issues/2132)- #2132
- [Issue for Fine Grained Permissions](https://github.com/grafana/grafana/issues/4893) - #4893
- [Issue for Extending LDAP to Dashboard Folders](https://github.com/grafana/grafana/issues/7212) - #7212
- [Issue for User Authentication & Groups and Roles](https://github.com/grafana/grafana/issues/1128) - #1128

**Comment by royemmerich** [comment]
> Specific points that we we would really like feedback on:
>* Should Dashboard Folders permissions be limited to just user groups or should it be possible to add both groups and individual users?

In order to keep things simple for smaller outfits, it would make sense to allow single users to be added to dashboard folders, thereby avoiding an additional configuration step.

Another approach would be to not allow single users to be added to dashboard folders and rather have a default user group to which everybody belongs. When a new dashboard folder is created, the default group could be automatically added to the dashboard folder.

>* Should it be possible to remove Admin permissions to make a Dashboard Folder private?

As a person in the admin camp I don't like this idea. I want to know what users are up to at all times.

>* Should we have an Admin permission for Dashboard Folders so that multiple users can administrate the permissions?

Absolutely! I want to be able to retain admin permissions on all folders within an organisation but also be able to assign user admin permissions to say the IT manager of a company to whom we are providing our services.

**Comment by shalstea** [comment]
As a larger firm which is integrating grafana into a broader suite of applications, we are not looking to use the administrative security features of grafana directly but indirecty by integrating our security system (SAML) with grafana.  In particular we want to associate our managed ACLs with the grafana folders.

Also note that in our system - we are OK with everyone having read-only access to all folders and dashboards, but restricting write access to the dashboards based on the folder/acl permissions.

**Comment by shalstea** [comment]
Also we would like APIs or some other way to automate the generation of folders.  When a user tries to edit a dashboard we would want to perform the authorization check to see if they have write access to the folder / dashboard or not.

**Comment by Cartroo** [comment]
+1

**Comment by Cartroo** [comment]
+1

**Comment by nbu** [comment]
👍+1

**Comment by benthorner** [comment]
+1

**Comment by coliin8** [comment]
+1

**Comment by umataro** [comment]
+2

**Comment by patoroco** [comment]
+1

**Comment by calvinboey** [comment]
+1

**Comment by wei-hai** [comment]
+1

**Comment by maxxscholten** [comment]
+1

**Comment by Slapper** [comment]
+1

**Comment by brunomagalhaes** [comment]
+1

**Comment by G-Geary** [comment]
+1

**Comment by PhantomPhreak** [comment]
+1

**Comment by iksaif** [comment]
Could the alerts defined in these dashboards also be categorized in folders in the related views ? (if not already the case)

**Comment by coolshiva123** [comment]
We have a similar requirement too to view the graphs based on particular user logged in

**Comment by jbtest** [comment]
Yes please.

**Comment by Vehyla** [comment]
:+1:

**Comment by bergquist** [comment]
@iksaif that a good question. I think not for v1 of dashboard folders but definitely later on.

**Comment by LeDistordu** [comment]
+1 !

**Comment by gitrc** [comment]
+1 can we get some basic folder grouping capabilities?

**Comment by iekulyk** [comment]
+1

**Comment by deepminimal** [comment]
+1

**Comment by lazycoder-ru** [comment]
+1

**Comment by nutell4** [comment]
+1

**Comment by dominic-miglar** [comment]
+1

**Comment by peterhassing** [comment]
+1

**Comment by f1erro** [comment]
What is the status of this?

**Comment by mikich** [comment]
+1
