### ISSUE TITLE
Provisioned dashboard can be deleted in UI

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#16130]
The delete button should not be visible for provisioned dashboards as it will be automatically restored. 

Maybe mention in docs that what disableDeletion controls. 

Created after this report: https://github.com/grafana/grafana/issues/16129

**Comment by aimuz** [comment]
I think adding a field to mark that it has been deleted and that other functions need not be changed

**Comment by aocenas** [comment]
@torkelo I think there will be an edge with this approach. If there is a dashboard that was provisioned, but with `disableDeletion: true` and file for that dashboard will be deleted, the dashboard will be kept but now there is no way to delete it, except for changing the `disableDeletion` which could delete also other dashboards.

I think we can add some flag in DB that will say, whether provisioning file is still in available and based it on that, so that we do not end up with dashboards that cannot be deleted.

**Comment by torkelo** [comment]
Agree, this is not straight forward. 

One other alternative is if disableDeletion is true and file removed, maybe dashboard should be not marked as provisioned anymore.

**Comment by aocenas** [comment]
Looking at the code, I think instead of doing nothing here https://github.com/grafana/grafana/blob/master/pkg/services/provisioning/dashboards/file_reader.go#L124 we could delete row in `dashboard_provisioning` table for that dashbaord. That should make it essentially non-provisioned for all the code right?

**Comment by torkelo** [comment]
yes, think your right.
