### ISSUE TITLE
Feature request: include org. name in dashboard URL

### ISSUE THREAD

**Issue by bbinet** [grafana/grafana#1613]
In a mutli-tenant setup, when we created a shared link from an specific organization context, then visiting this link only works when the current organization is the same as when the shared link was created.
This is logical, but I think it would be better if the shared link would also contain the organization information, so that grafana could try to automatically switch organization (if user is also part of the organization) when visiting a shared link.

**Comment by bbinet** [comment]
Note, the I'm currently using grafana revision 96ad3a04d4231248dd78d43bfd0a97909422e175

**Comment by torkelo** [comment]
good point

**Comment by Akulatraxas** [comment]
+1 - exactly what i need

**Comment by cemo** [comment]
+1

**Comment by jlopp** [comment]
:+1: 

Since I have anonymous access enabled I assumed that creating a 'sharing link' would result in a globally accessible dashboard URL that is available to anyone, regardless of whether or not they are authenticated. This is how it works if you share a dashboard from the default organization, but not if you share a dashboard from a user-created organization.

**Comment by torkelo** [comment]
Currently anonymous access is only implemented to work for one organization.  

Each organization is its own isolated island with its own data sources and dashboards and users (logins are global, user orgs are only permissions)

**Comment by jlopp** [comment]
Right, so once links to dashboards include namespacing for which organization they belong to, perhaps the next step could be for an organization to configure allowing anonymous access to them?

**Comment by torkelo** [comment]
no, anonymous access for multiple orgs is not going to happen any time soon. Will be very time consuming as we would have to change all urls to include org name. 

If you want anonymous access to all orgs in a grafana install you are using orgs in a non intended way :) They are mostly ment for multi tenant setups 

What will happen (to solve this issue) is an orgId in the share link (generated from the share modal). If the user has access to the orgId in the link grafana will make the the active org for that user.

**Comment by jlopp** [comment]
That's understandable; I'm sure I'm using Grafana in a non-intended way. I'm operating an instance that is publicly available to anyone and my goal is for anyone to be able to create and share charts with the public, regardless of if they have an account.

I'm essentially using organizations in order to restrict write access to only the dashboard creator.

**Comment by toni-moreno** [comment]
+1

**Comment by shoonoise** [comment]
Is there any estimations when it will be done?

**Comment by torkelo** [comment]
@shoonoise no eta :(

**Comment by ankanm** [comment]
+1

**Comment by tjamesturner** [comment]
could we get this issue labelled as type:bug? 

i think it is fair to say that the "share dashboard" feature is not working as intended. furthermore, it causes significant overhead in our organization to field questions about disappearing dashboards and disseminate the work around. i don't suppose it makes much difference, but it might help people find the ticket more quickly rather than creating more duplicates.

**Comment by bergquist** [comment]
I don't like the idea of having the orgid in the url. Code like that tend to spread all over the code base. 

If the dashboard does not exists in the currently logged in organisation the frontend could ask if the user have access to it in any other organisation and switch if that's the case.

**Comment by rlueckl** [comment]
+1 for this feature.

@bergquist: "If the dashboard does not exists in the currently logged in organisation the frontend could ask..." -> how would you differentiate between a Dashboard which exists in 2 different Orgs. with the same name (for example a simple name like "Overview")?

I think the Org. ID should be in the URL or as an alternative the Dashboard ID (which is unique across Orgs.) For a more detailed description see my ticket #3130

**Comment by bergquist** [comment]
@rlueckl Sigh... I forgot about name collision. Yea my suggestion does not work. But I will leave my comment for future ref.

**Comment by tjamesturner** [comment]
it seems that orgs were introduced to support multi-tennant scenarios, but are actually used in practice to support read-only access for specific users. rather than modifying the function of org id's, perhaps it would be easier and/or more valuable to add dashboard-level authorization? 

specifically, our needs could probably be met with a single org, if each dashboard had an owner who could designate the dashboard as "read-only" to everyone except himself (and org admins).  obviously, user and/or dashboard groups (like linux user/group/all permissions) would be even better for us, but not totally necessary for our most common use cases.

**Comment by jobrs** [comment]
+1

**Comment by dacjames** [comment]
+1 This would be an important feature for us. We use Orgs to organize dashboards for different groups in the company. Users that belong to an Org are allowed to edit dashboards within that Org, but all users can view dashboards across all Orgs to encourage collaborative debugging when we have problems. Because the Org is not included in the URL, there is no way to share a link directly to a given dashboard..  You have to mention the Org as an aside, which causes a lot of confusion.

Any interest in patches that fix this issue?

**Comment by JarleB** [comment]
+1

**Comment by jifwin** [comment]
+1

**Comment by lae** [comment]
I have the same use case as dacjames (except, most users only have access to one org) and it does cause confusion for users who have access to multiple. e.g. Production dashboard in two orgs - but graphs are totally different.

**Comment by utkarshcmu** [comment]
+1

**Comment by bergquist** [comment]
I suggested another approach to this problem in https://github.com/grafana/grafana/pull/3800#issuecomment-217445703

**Comment by bbinet** [comment]
You are referring to subdomains in https://github.com/grafana/grafana/pull/3800#issuecomment-217445703 but it is not always possible to use subdomains if you don't manage the DNS by yourself.
And personally I don't want to create subdomains for every organization I'm creating in grafana : I like to have a single URL for my grafana server.

I don't see the issue with including organization id in the URL: why do you consider it messy?

I don't find `http://<id or name>.grafana.local/dashboard/db/a-dashboard` less messy than `http://grafana.local/org/<id or name>/dashboard/db/a-dashboard`, do you?

**Comment by utkarshcmu** [comment]
Single domain is preferable in my use case too.

**Comment by lae** [comment]
Honestly I would also be okay with having a GET parameter to ensure anyone who uses that link falls onto a dashboard in the correct organization as well, if that's simpler to implement.

**Comment by jobrs** [comment]
+1

**Comment by tjamesturner** [comment]
@bergquist, would you be more comfortable with this feature if the org_id was an optional (http get or post) parameter?  it would be helpful if we could simply add the org id in our documentation and communication, even if it was not included by default in all the places that could generate a dashboard url.

**Comment by utkarshcmu** [comment]
How about this?

When a user opens up a dashboard URL, Grafana should check whether the logged-in user's current ORG is same as the dashboard's ORG. If it is not the same, then Grafana changes user's current ORG to dashboard's ORG and shows the dashboard to the user. [ A small message can be displayed on the right top as "Current Org changed to XYZ". ]

This way we do not need any org representation in the dashboard URL. And Grafana server makes the decision to switch current ORG of the user according to the dashboard he is trying to open.

I also think this is easier to implement and makes Grafana intelligent to switch the context of the user according to the dashboard a user is trying to open. :)

Thoughts?

**Comment by tjamesturner** [comment]
@utkarshcmu as mentioned earlier, there is no way of knowing which org a dashboard belongs in since the same url can represent two different dashboards based on the user's session context.  fundamentally, the current model is not REST-ful.

**Comment by lae** [comment]
@utkarshcmu You still need something in the URL to define what organization a dashboard is in. How else are you going to determine what organization a dashboard belongs to when the same dashboard name exists in two organizations?

**Comment by utkarshcmu** [comment]
@tjamesturner @lae You guys are right, I did not think about the condition when dashboard names are same in different organizations. Good Point !!!

**Comment by dacjames** [comment]
+1 to @tjamesturner concern. What is the problem with just changing the url scheme from:

```
/dashboard/db/{dashboard-name}
```
To:
```
/dashboard/db/{org-name}/{dashboard-name}
```

**Comment by tjamesturner** [comment]
@dacjames it seems like the only major "concern" i have heard so far is that adding the org id to the url will necessitate touching a lot of code, since there are a lot of places that generate dashboard urls. since organizations were bolted on to support siloed multi-tenancy, they do not fit well with the idea of an cohesive dashboard set that has segregated permissions. the advantage of using an optional http parameter rather than a required url prefix (as you suggest), is that the optional parameter would be backwards-compatible with existing intra-org links generated by the application.

**Comment by torkelo** [comment]
@tjamesturner yes, I think adding orgId as a query parameter to dashboards would be a good and relatively simple / low impact change. 

The reason this has not been a top prio issue is that organisations are designed for multi tenant setups with completely isolated data sources and dashboards with very few users in common. But many use it to control dashboard permissions and to group dashboards into "teams". In that case I think the organization feature is misused and better dashboard organization and permission features are better suited.

**Comment by bbinet** [comment]
@torkelo In my use case, I'm willing to use organizations in a multi tenant setup with completely isolated data sources and dashboards, but some of our users (especially the admin users) have access to all organizations, and it would be very useful to be able share a link that contains the orgId in some way.

As a user can be associated to multiple organizations, then I think it makes sense to provide a way to share a dashboard link that redirect to the correct organization.

+1 for the query parameter solution.

**Comment by dacjames** [comment]
@torkelo How is using orgs for team organization an "abuse?" What feature should be used instead? We need to organize dashboards by team, with "team" defined by an LDAP group and permissions are controlled at the team level. Orgs provide this today.

Query parameter would work for us, but I don't understand the compatibility argument. If you make the old and new URL schemes non-overlapping, it should be possible to support the legacy URLs as a redirect:
`/dashboard/db/{dashboard-name}` could redirect to `/dashboard/org/{currently-logged-in-org}/{dashboard-name}`. The code issue sounds like something that should be cleaned up anyways using something like `url_for(dashboard)`.

**Comment by torkelo** [comment]
@dacjames I am not abuse is the right term, just not what it was designed for. But I understand why people use it as there is no other way to group dashboards and users. 

I am not sure at leat I have made a compatibility argument, more that changing the url would require extensive changes as dashboard urls are generated in a lot places.

**Comment by nickjones** [comment]
Has hashing the dashboard and organization into a unique URL been considered?  I personally don't really care if the name of the dashboard is human readable in the URL since I end up with broken links half the time as it is.  We have the same team dashboard sharing issue; product generating teams have their own dashboards but also leverage IT's dashboards when infrastructure isn't behaving.

**Comment by dacjames** [comment]
@torkelo It seems from the outside that it would be valuable to make that change in general. I can imagine it would be painful, but centralizing URL generation behind an API would make solving this problem much easier.

**Comment by drewboswell** [comment]
Same problem here, when sharing between teams it becomes a nightmare switching constantly between spaces. (not to mention the support of "why has my dashboard disapeared" or "grafana is broken I don't see your board".

In our case we have 20+ dev teams, and the addition of the spaces solved a real overcrowding and modification control problem. This enabled for instance, a read only for teams on other teams spaces, but owners of their own spaces.

I agree with @dacjames In the url would be better (just the id), but a get parameter would be acceptable, just as long as we are able to do it. If it goes the way of the get parameter, if possible it would be nice to have the ability to turn it on constantly (i.e. click on dashboard, get parameter is there). We have no use for hiding it as it generates confusion otherwise.

**Comment by torkelo** [comment]
If this a high priority issue then a PR would be welcomed, it might take 4-5 months for me to go to this :(

**Comment by madshall** [comment]
Is anybody aside of Torkel working on this? I might be able to help.

**Comment by rjes** [comment]
This would be a really nice feature with a extension to "dashboard home" so the list is populated with all dashboards the user have access to. Using organizations is the only way to ACL what graphs a user have access to. And keeping the same graph in sync over several organizations is time consuming and prone to be forgot or missing sometimes.

**Comment by jifwin** [comment]
Is there any chance to have this before 4.0.0?

**Comment by bergquist** [comment]
Its not a high prio for us (Grafana team) at the moment. PR's would be appreciated.

**Comment by andycarlsonuk** [comment]
+1

**Comment by joshzitting** [comment]
Ill add my name to the list of ppl that would LOVE to see this. We use orgs for different environemnts at my work and anytime I share a link to a graph ppl get all huffy and puffy cuz they have to select an org... Definitely a bug.

**Comment by magnuspwhite** [comment]
This is a requirement especially considering all alerts have the URL to the issue. If you are logged in to another organisation, Grafana says the dashboard can't be found.

This change would also allow you to view multiple organisations dashboards at the same time

**Comment by EdwardKaravakis** [comment]
+1 for this feature

**Comment by giner** [comment]
+1 Missing this from the start of using Grafana.

**Comment by jayannah** [comment]
+1 .. very critical feature.

**Comment by petershrom** [comment]
👍

**Comment by nmische** [comment]
This was an inconvenience, but now that we have more teams adopting Grafana it is a real hinderance.

**Comment by linar-jether** [comment]
+1

**Comment by erokatyo** [comment]
+1

**Comment by jayannah** [comment]
This will be most useful feature which needs to be implemented ASAP. Without this feature the Grafana dashboard management with more than one Org is no useful at all.

**Comment by 3jow** [comment]
+1

**Comment by Kuckkuck** [comment]
+1

**Comment by urfuwo** [comment]
+1 as least for our use case it is very confusing like it is implemented. adding the org to the URL would be fantastic.

**Comment by BugRoger** [comment]
+1

**Comment by CarusDave** [comment]
+1 We are also using Orgs for teams to manage their dashboards and most importantly to restrict access between groups. That aspect works as expected and is a very useful feature.

However as mention by others, the problem comes when multi-org managers need to frequently move between teams and have to worry about switching Orgs because of broken links. Mostly they want to keep browser tabs open for multiple sets of dashboards, but can't. It's a big limitation.

**Comment by jifwin** [comment]
I'd like to propose a solution. I do have a proof of concept implementation of multi organizations support. It is based on a few things:
	- pages and API URIs are prefixed with "/orgXX/" e. g. https://grafana.com/org10/dashboard/db/dashboard_name, https://grafana.com/org10/api/dashboards/db/dashboard_name
	- all pages links in the code are build using an angular service, that puts the organization id into the url
	- all API calls are intercepted by angular interceptor, that also puts the organization id into the url
	- organization that is selected in the user profile (and saved in the db) is now the default organization for that user
	- the root path redirects to user default organization

It may sound like a workaround, but I guess that it's the easiest solution, without redesigning whole Grafana authentication model.

This allows multiple tabs with different organizations being open and sharing cross organization urls, provided that a second user is allowed to enter organization. In our solution we also implemented default readonly permission to all orgs, but I know it wouldn't go with current Grafana approach.

However my implementation is designed for Grafana 3, so before I would spend a lot of time on integrating that into Grafana 4 I'd like to know your opinion on that. Also it would require some more work, since I haven't implemented support for all things and authentication other that header, especially. Any help with that would be welcomed.

Please let me know how it sounds to you and is integration with Grafana 4 worth doing.

**Comment by bergquist** [comment]
If the url contains a query parameter called `orgId` Grafana will set the users org to the one in the query parameter and redirect the user to the same url. So by sharing url that contains `orgId` people will be able to load the dashboard directly. 

If you use grafana `Link to dashboard` functionality the orgId will always be included. 
![image](https://cloud.githubusercontent.com/assets/618863/23215135/9ad24370-f911-11e6-8ae2-23ec4339da89.png)

I'm closing this issue since we think this is a good enough feature for sharing dashboard between orgs. Please keep in mind that orgs was never designed for that purpose.

**Comment by magnuspwhite** [comment]
This solution over looks the fact that alert URLs will still suffer the same issues with dashboards not being found if you are currently viewing another organisation.

**Comment by bergquist** [comment]
@magnuspwhite That's a good points. I should also have mentioned that all urls generated in alerting for navigating back to the dashboard contains the orgId. https://github.com/grafana/grafana/commit/5174d050f2fb70da5e68b649cb63013aebb531a6#diff-b5f1434811f455370f213f8d66229166R116

**Comment by misqos** [comment]
It seems to be simply a little bit of duct tape applied to silence users who wants simple multi-organization workflow. What you repeat over and over again is that orgs was never designed for that purpose, but a lot of users want to use them differently than you expect. Maybe it is time to not to tell users what they should like and instead of that listen to them and make software more usable.

Merged solution does not enable to work with two different dashboards from two different organizations at one time. That's because Grafana API is stateful and current orgID is stored it database. Of course you can view opened dashboard, but trying to edit them both will fail. This simply sucks and it smells like you are implementing workarounds for stateful API and your organizations concept which nobody understands here. @jifwin suggested moving to more stateless API by suplying orgID in URL. You haven't even answered his comment.

**Comment by torkelo** [comment]
> @misqos 

It was never designed for that purpose is sadly our response. We are sorry, that is not what you want to hear if you are using Organizations as a way to handle user groups. Organizations in Grafana was built to handle multi tenant hosted setups with completely isolated sets of dashboards, datasources and users. 

I should probably have included org Id in urls anyway, even with that design goal, but in order to keep urls nice and simple I opted not to as I figured users who work for multiple companies would not be that frequent and they would not be switching constantly. Probably a faulty assumption but that was the reason. 

Sadly we do not have the time to do a total redesign of the API and page URLs (something that is very tricky to do in a backward compatible way and we value backward compatibility highly). If you want the pain of having dashboard urls work in a multi org setup no matter what the users "current" org is then a duct tape solution is the only one on the table if you want this "solved" within the next 2 year.

We have a plan for a non "duct-tape"  solution which we are planing on developing this year in the form of dashboard folders, user groups and permissions. 

But with this commit:
https://github.com/grafana/grafana/commit/d88286ab810cbfdf3455849aaa2376f42d86ca09 

All dashboards urls will contain a orgId query parameter, so you will always be able to copy paste the url and share with colleagues and grafana will switch to that org before loading dashboard. Not the ideal solution, as you say if have multiple tabs open with multiple orgs it still a problem.

**Comment by misqos** [comment]
@torkelo 
Right, I understand what goal you want to achieve with orgs being that separate. The main problem is that many Grafana users want to use organizations in different way than you expect because of lack of what you called "dashboard folders". Organizations are the only way to not to have all dashboards in one place.

Are there issues created for dashboard folders, user groups and permissions which can I follow? Is it just a plan or is it placed somewhere on Grafana roadmap? I really like Grafana and would like to use it extensively, but without such features it's a pain.

**Comment by magnuspwhite** [comment]
It is good to see a more immediate fix for urls containing the org ID allowing sharing and automatic switching when the dashboard is opened.

However, I think the assumption that, even in a multi-tenant setup, that users would not want to see multiple organisation data simultaneously is short sighted. I accept that my use case working with multiple organisations is not as common, but I still require information from many sources together.

There are 2 poor solutions we used to work around this situation. First, many read only users for wall and command center monitoring. Secondly, a single aggregate organisation with a data sources from each of the other organisations allowing overview screens and playlists to cover many organisations. The second being a great overhead and no longer in use because of this pain.

The addition of folders and permissions is still a welcomed addition, but in my eyes, not a replacement for organisational structuring.

**Comment by rlueckl** [comment]
@misqos: You might want to check out the following issue regarding folders: #1611

**Comment by joakimberglund** [comment]
Might be a "hack" but it works great for dashboards.

If we could get the same feature added for "Alerting" and "Data Sources" tabs we have a solution thats good enough until folders arrive. :+1:
