### ISSUE TITLE
Elasticsearch Geohash Aggregation arbitrarily limits to 7 units of precision

### ISSUE THREAD

**Issue by acedrew** [grafana/grafana#16188]
**What would you like to be added**:

# Allow geohash precision as supported by elasticsearch
I believe this is simply because the Kibana Geo Visualizer defaults to the same behavior, limiting you to 7 units of precision in your geohash. While I certainly understand on large data sets this could represent an overwhelming amount of data, on sparse sets, you sometimes need the precision from higher levels of hashing.

Should easily support up to 9, perhaps more? While kibana does default to a limit of 7, there is an arbitrary json field that allows you to override to higher levels.

**Why is this needed**:
Allow useful display of precision location data in sparse sets.

Happy to provide a PR for this, just need to get my Grafana Dev Environment set back up.

**Comment by marefr** [comment]
Precision up to 12 is supported since ES 2,0: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geohashgrid-aggregation.html#_options_3

I agree that it should be possible to override.

Changes needed here:
https://github.com/grafana/grafana/blob/090b3f6c6d43e09cfb5e2f54b6042e2dcfed9d2a/public/app/plugins/datasource/elasticsearch/bucket_agg.ts#L144-L149

In backend (alerting), seems like any numeric integer value is accepted as precision:
https://github.com/grafana/grafana/blob/090b3f6c6d43e09cfb5e2f54b6042e2dcfed9d2a/pkg/tsdb/elasticsearch/time_series_query.go#L274-L281

However you cannot use geo hash in graph panel with alerting so this is fine.

@torkelo any thoughts about this?

**Comment by robouden** [comment]
Beginner question:

1-I found the bucket_agg.ts and modified:

        _case 'geohash_grid': {
          // limit precision to 10 modified by rob oudendijk
          settings.precision = Math.max(Math.min(settings.precision, 10), 1);
          settingsLinkText = 'Precision: ' + settings.precision;
          break;
        }_ 

2- Restarted  Grafana as a service but still geohash precision 7 is maximum.

How to implement this patch on a locally installed version of Grafana running on Mac OSX?

regards
Rob Oudendijk
