### ISSUE TITLE
Share Panel Embed as iframe

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1622]
Share modal now has an embed tab: 

![image](https://cloud.githubusercontent.com/assets/10999/6763266/83948cbe-cf4b-11e4-8aa5-ebed356eb38d.png)

Put this on another web page and you get 
![image](https://cloud.githubusercontent.com/assets/10999/6763294/3c4c5250-cf4c-11e4-9ea7-c7756d77db39.png)

Some cavets:
1) You need to logged in to see the graph (Or enable anonymous access in Grafana 2.0) 
2) You can zoom in but you cannot zoom out, it does not update (no auto refresh).

**Comment by bigtalltree** [comment]
Is there anyway we can pass auto refresh as a URL parameter?

**Comment by afrozl** [comment]
I too am interested in enabling auto-refresh in the URL

perhaps as 'refresh=true'

**Comment by donnex** [comment]
Why was this issue closed? As far as I can see the original two issues are still not addressed? Are they not desired features for Grafana?

I would find the features really useful.

**Comment by torkelo** [comment]
@donnex it was closed because it was implemented a long time ago ( in milestone 2.0-beta1 as you can see on the right side).

You access the panel embed feature from the panel share dialog

**Comment by donnex** [comment]
Sorry for using such an old issue but I was referring to the issues mentioned in the orginal issue.

> You need to logged in to see the graph (Or enable anonymous access in Grafana 2.0)
> You can zoom in but you cannot zoom out, it does not update (no auto refresh).

I just tried this in 3.1.1 and if there is no way to share an iframe widget if you've got auth setup. Maybe this is by design? It still would be a really nice feature to be able to export and embed a specific graph on a public facing page without disabling auth all together.

If you disable auth (or embed it in a browser where you're logged in) there still don't seem to be a way to zoom out in the widget if you zoom in. Also if you click the graph name you get the normal Grafana edit options as you do inside Grafana.

If this is how it's supposed to work please let me know and I'll have to find another way to solve my use case.

**Comment by jmls** [comment]
@donnex : did you sort out the auth issue ?

**Comment by donnex** [comment]
@jmls No, I gave up on the idea to use Grafana on an external page. At least for the moment.

**Comment by jmls** [comment]
crap. thanks for the quick feedback though.

**Comment by rbianic** [comment]
This issue is still present in version 4.4.3 (commit: 54c79c5), why this ticket has been closed ?

**Comment by daniellee** [comment]
@rbianic what issue? Authentication? Have you tried the snapshot feature as an alternative.

**Comment by rbianic** [comment]
Yes, the issue is that an authentication is needed to view the graph when using the embed feature. I have tried the Snapshot feature and it works well. The feature to add is a way to embed graphs on an external website that stays up-to-date
