### ISSUE TITLE
Share Dashboard Snapshot

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1623]
Have implemented a proof of concept feature that would not require that much more work to make it production ready (maybe 1 day or to). 

It allows you to snapshot a dashboard with the data for all panels inside the dashboard json. The Grafana 2.0 backend will then save that using a guid like key (I think of it like a gist). 

You then get a link that anyone can use that (no authentication), they will be able to see the Dashboard data. But only the data that was visible when you did the snapshot. 

I am thinking about extending this to also include a public site that can receive and host these dashboards so you can share them to people who do not have access to your internal grafana server. like a "http://snapshots.grafana.org/4z1U4geCwfM0cENt6G0j" 

![out](https://cloud.githubusercontent.com/assets/10999/6765399/b59007fc-cfb4-11e4-8f09-fd40bef1a986.gif)

The snapshot name will just change the name of the dashboard in the snapshot. 

Feedback would be great.  Is some kind of Data anonymization going to be useful (to replace series names with xxx_1 etc, will make the graphs a lot harder to interpret, and there could be sensitive names in graph panel titles etc. But I guess that is up the user knowing when they create the snapshot. 

I am also thinking about having an Expire field to specify how long the dashboard snapshot should exist, that way you can share data with sensitive data to an external client (the dashboard will be visible for anyone with the link, but the dashboard snapshot will be removed after the specified time period, anything from an hour to a days, weeks for example)

**Comment by syepes** [comment]
+1 Great feature.

**Comment by rafrey** [comment]
:+1: I will definitely use this!

Will 2.0 still leverage apache/ngnix? If something like apache/ngnix is still being used it would be nice if there were a way to host shared dashboards separately from the rest of Grafana (so someone could bind the site for Grafana to a private IP address and the site for the shared dashboards to a public facing IP address). In some companies getting approval to host anything publicly (different from making it publicly available) can be very prohibitive, this way at least they can say they are hosting it on their own infrastructure. I could even see some IT departments setting up a second instance and only hosting shared dashboards on it in order to make them publically available but still keep them hosted on their own infrastructure if the ability to export/import shared dashboards between the public and private instances exists (which I assume it does if you can push them to a public instance). In the case that you have internalized hosting into the solution and replaced apache/nginx then providing this ability as a configuration option would make it pretty painless for the end user to implement.

It's a nice to have, so if it proves to be difficult it may only deserve a low priority ranking in a backlog. Creative IT departments are likely to come up with their own solution to address this if you don't provide one.

If you have suggestions on a better way to accomplish the same goal I'd love to hear your thoughts.

FYI I'd like to include Grafana in promotional materials (printed and video), do you have any suggestions for screen capture/printing and capturing video (I've noticed that you made some tutorials and have used video and stills in some of your presentations and on your website)?

Your timing is impeccable, thanks!

**Comment by rafrey** [comment]
OK I see now you are hosting on your own web server in 2.0, it would be really nice if you could allow users to configure a different IP for the shared dashboards (much more concise requirement, sorry for the long winded response above).

**Comment by rafrey** [comment]
Also :+1: on built in retention. If you could use a retention policy to default the expire field as well, and then perhaps display a days remaining on the dashboard snapshot somewhere (flash a banner at the top for a few seconds on open or something) and maybe even provide a renew option for certain security roles...just some thoughts. Having built in auth opens new doors. Personally, I think you should just display a warning about sensitive data and point the user in the direction of the alias functions when they create the snapshot; IMHO I think obfuscation/anonymity should be the user's responsibility. If they host this internally then setting up a proxy with auth in front of it and restricting access altogether will probably end up being the way to go. So many problems are introduced with modifying target/metric names, template variables, etc. when you use *bywildcard and grouping based functions in graphite, I'm not sure how it would really work?

**Comment by costimuraru** [comment]
:+1:

**Comment by torkelo** [comment]
Snapshot publishing is working, I have setup a snapshots.raintank.io site (payed for by raintank), that will host the public snapshots. Only need to configure a so this domain is behind a fastly CDN (so it will be super fast), and a valid SSL cert. 

Next up is adding an expiration time, and an option to change the public publish endpoint from snapshots.raintank.io  to something else (like @rafrey talked about, a away for companies that are very sensitive about sharing data hosted by others) 

![snapshot2](https://cloud.githubusercontent.com/assets/10999/6786340/0abca7b8-d162-11e4-87e1-c8c85500ff12.gif)

**Comment by mattttt** [comment]
In order to make it a bit clearer as to what is actually happening with the snapshot, wanted to adjust the modal to be more descriptive (without getting in the way of the high-frequency user):

![snapshot-modal-rev3](https://cloud.githubusercontent.com/assets/2886187/6830342/95c755cc-d2ef-11e4-812e-4a28a15af6fd.png)

**Comment by mattttt** [comment]
@rafrey Drop me an email and I can give you a rundown of some screengrab/animated gif methods.

**Comment by psujit** [comment]
Can we restrict the share option in the snapshot? I am showing the snapshot on my website and would not want the share option to be available to the user. The user can just view the graph and edit the parameters of the graph. But he should not be able to share it.

**Comment by torkelo** [comment]
@psujit in Grafana 3.0 you can disable external snapshot sharing

**Comment by psujit** [comment]
Thanks a lot for your input! I will update the Grafana version.
