### ISSUE TITLE
Shouldn't be able to create alert rule that uses unsupported template variables

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#16264]
In Grafana v6.0.1 (0c44a04) , when trying to use an alert on a templated query,
i get a warning box saying
"Template variables are not supported in alert queries"

This message is too vague. It is not clear what happens when one tries to have the alert anyway. (we have at least 1 customer that I know of trying to do this). It looks like it may execute, poorly, or in some degraded mode.
If the alert won't work, maybe it should just block out all the alert configuration and make it super clear the alert is disabled.

What is extra confusing is that "test rule" works, and there are state transitions so it looks like it works!

**Comment by marefr** [comment]
Moving this to 6.5 milestone. We have done some related work in #19087 so that when creating a new alert that uses template variables you won't be able to add alert. We have to have another look at this for 6.5 and see if there something left we can do. We probably don't want to do too much given the next generation alerting coming up.

**Comment by hugohaggmark** [comment]
Closing this for now after confirmation from @Dieterbe that our work in #19087 is enough for now.
