### ISSUE TITLE
Document how to setup Auth Proxy and IIS

### ISSUE THREAD

**Issue by stulincoln** [grafana/grafana#16453]
Hi

Are you able to add information for IIS here? I used the other Grafana document to get the redirect working fine, now having issues with the authentication using windows auth.

Thanks

**Comment by marefr** [comment]
We have a guide explaining using IIS as a reverse proxy but I guess that's not enough: http://docs.grafana.org/tutorials/iis/

**Comment by stulincoln** [comment]
The reverse proxy document was perfect and I was able to get that to work. Just trying to get the Windows Authentication piece going. Thanks

**Comment by marefr** [comment]
Grat. Closing this then

**Comment by stulincoln** [comment]
Hi. Just to confirm the first IIS document is great for reverse proxy. I am still looking fir configuration to do the reverse proxy with authentication via IIS and windows authentication

Thanks

Stu

**Comment by dskokmt** [comment]
Hi Stu, You may already have implemented but I have that configuration working with Windows integrated authentication. Just do everything on that IIS tutorial and:  

1. On IIS manager, select "Authentication" and enable **only** "Windows Authentication"  
2. Right click on "Windows Authentication" and select "Advanced Settings"  
3. Select "Accept" for "Extended Protection"  
4. Check "Enable Kernel-mode authentication"  
5. Right click on "Windows Authentication" and click on "Providers..."  
6. Keep **only** NTLM. Delete others  
  
My environment is Windows 2016.  
  
That's it! Add whoever you want to grant in "Authorization Rules".  
Registered user will be able to see Grafana and vice versa.

However, in IIS ARR and URL_Rewite environment, IIS cannot pass authenticated username to Grafana. Which means, Grafana needs to run in Anonymous access. This is because the IIS redirection works before authentication.
