### ISSUE TITLE
Better panel control for: intervalMs and maxDataPoints

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#16479]
Currently the queries generated are based on the panel width -- this works great to for graph, but gets a bit weird for other panels, especially the new repeating visualisations.  For example:

`intervalMs: 5000, maxDataPoints: 198`
![image](https://user-images.githubusercontent.com/705951/55835993-198fd780-5ad2-11e9-8b14-9d9893b2f2c8.png)

vs

`intervalMs: 1000, maxDataPoints: 673,`
![image](https://user-images.githubusercontent.com/705951/55836039-388e6980-5ad2-11e9-8f23-32946d79373c.png)

I don't know a good solution for this since the repeating is based on the response

**Comment by torkelo** [comment]
Yea, this one is super tricky. As you say there is no way currently to know how many queries the query will return & how it's going to be visualized. So think this will be up to the user to tweak. 

Some other related thoughts

1) I have been thinking of introducing maxDataPoints to all data sources as an alternative to min Interval. As min Interval is so hard to make time range agnostic without math (not supported right now) or using a time interval variable. maxDataPoints is super simple way to specify a time range agnostic limit to how many data points you prefer. 
2) Another problem with maxDataPoints and min interval is that they are both removed / cleaned when changing visualization (good and bad). 
3) No way for panels to suggest an appropriate value for maxDataPoints (something singlestat panel does currently), however that only works for the few data points that use it, which is why I want to do 1).

**Comment by ryantxu** [comment]
> I have been thinking of introducing maxDataPoints to all data sources as an alternative to min Interval

It is already passed to the datasources -- the question is if and how it should use `maxDataPoints`.

**Comment by ryantxu** [comment]
was fixed in grafana 7
