### ISSUE TITLE
Variables - Warn when using a multi-valued data source variable in non repeating scenarios 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#16543]
All / Multi-valued data source variables can only be used in row / panel repeat scenarios. If a user tries to use them in another non repeating panels or query variables.

**Comment by joshhunt** [comment]
During mob we've been investigating and understanding a few issues vaguely related to multi-select data source variables:

 1. Multi-select data source variables inconsistently display in the Data source picker. They only show when a single value is selected. When multiple values are selected, data source variables do not display in the data source picker.
 2. If a multi-select data source variable has been set as the data source (due to the above), and multiple values are selected, only the first selected data source is queried, and no warning or anything is shown to the user to let them know. 
 3. When you repeat a multi-select data source variable, the repeat-scoped-variable does not show in the data source picker. You're unable to select the repeated variable in the data source variable

We should fix the inconsistency from **[1]** either way (never show multi-select data source variables in the data source picker, or always show them), and then **[2]** is closely related.

**[3]** is a separate issue that could be fixed independently, but it could be made moot if we solve **[2]** by always showing multi-select data source variables in the data source picker.

**Comment by lpskdl** [comment]
During the mob session, We decided to revert the changes done from #52142  and propose possible solutions which are:

- Get the variables that belong to the dashboard. Check which ones are multi/all. Check if the panels are repeated by/repeated. 
- Init all variable usages when you are in the dashboard. But then we still need to go panel per panel to see which uses which variables and if they should show a warning.
- (start with this one )Panel chrome gets the dashboard model. It has template variables of itself. We can filter out all multi/all variables and only look at them when looking up which variables the panel uses.

**Comment by ivanortegaalba** [comment]
This is the PR which reverts the changes https://github.com/grafana/grafana/pull/53521
