### ISSUE TITLE
heatmap panel: show the ratio of points per cell in tooltip

### ISSUE THREAD

**Issue by woodsaj** [grafana/grafana#16603]
currently in the heapmap panel, the tooltip shows the count of points in each panel.   It is not always obvious how many datapoints per series are in each x-axis bucket, or even how many series are represented in each x-axis bucket.  The colour or opacity provide a guide, but it is not always clear enough.

From the legend, if a cell shows a count of 10, it is not obvious how much of the total number of points that represents. eg. If the x-axis buckets have an interval of 10mins, and a cell shows a count of 10, that could be due to 1 point from 10 different series (because the series has datapoints with an interval of 10mins) or it could be 10 points from 1 series (because the interval of the series is 1min).  If the user zooms out to a larger time range, the x-axis buckets could change size and the counts for each cell would all scale up by some number.

To bring clarity, it would be helpful if in addition to a cell showing a count of '10', i would also show the percentage the cell's count is of the sum of counts from all cells in the x-axis bucket.

**Comment by hrobertson** [comment]
I've just added a histogram heatmap and also found that counts weren't really that useful - even without the sampling issue you mention. I therefore changed my query to turn my histogram values into percentages:

`100 * your_histogram_bucket{} / ignoring(le) group_left your_histogram_count{}`

In my case I am combining the results from multiple kube pods of the same application so my query is actually:
`100 * sum(envoy_cluster_upstream_rq_time_bucket{deploymentconfig=~"$deploymentconfig"}) by (le) / ignoring(le) group_left sum(envoy_cluster_upstream_rq_time_count{deploymentconfig=~"$deploymentconfig"})`

In addition, I set the colour scale min and max to 0 and 75 (you may want different values) instead of leaving them auto. This is because having it auto range can mask the shape of your histogram.

Eg with auto colour scale, if the majority of your values fall in one bucket, that bucket will get the 'hottest' colour and if you have some outliers with a few percent each, they'll get 'cool' colours. - This is perfect and intuitive to look at. However...

Consider the case when there is no one bucket with a majority, ie your counts are distributed across many buckets so your histogram is kinda flat. The maximum bucket may only have 30% of the values, but it will still get the 'hottest' colour. When you look at this heatmap, you'd see a line of the hottest colour and think that represents in the majority of values.

How applicable this is to your data will of course vary.

**Comment by hrobertson** [comment]
Revisiting this issue over a year later as I found myself doing the same thing again.
It'd be nice if I could simply toggle a switch in the Visualization settings to show values either as absolute counts (the current default) or as percentages.
A separate on/off toggle would add the complementary value to the tooltip as @woodsaj described. (If absolute counts are used, show the percentage in the tooltip. If percentages are used, show the absolute count in the tooltip.)

I might look at implementing this if I find some time.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
