### ISSUE TITLE
Template variable ignoring new default value

### ISSUE THREAD

**Issue by taterhead** [grafana/grafana#16600]
**What happened**:

Template variable uses the wrong first default value set, even after its been updated

**What you expected to happen**:

Template variable should use the value that is shown on the screen

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a $test_var 'text box' variable on a dashboard, set the default value to 20.
2. Add another template variable, $test_var2, which will show you the value of $test_var (in my case, I used 'query' variable to a postgresql data source with the query being "select $test_var")
3. Save these changes. View the dashboard and see the same value (20) in both boxes
4. Edit $test_var to set the default value to 40. Save these changes.
5. Go back to the main dashboard page, make sure there aren't any HTTP GET variables set, reload the page, now $test_var *shows* 40, but $test_var2 should show 20, which is what's getting passed to queries.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.0.0
- Data source type & version: N/A, afaict this is a grafana issue
- OS Grafana is installed on: ubuntu 16.04.3 LTS
- User OS & Browser: 
Google Chrome | 73.0.3683.86 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Windows 10 OS Build 17763.379
- Grafana plugins: vonage-status-panel
- Others:

**Comment by torkelo** [comment]
After you changed the test_var to 40 you would need to save the dashboard and check the "save current variables"  checkbox. 

OR you need to enable refresh on dashboard load:
![image](https://user-images.githubusercontent.com/10999/56184719-65370980-601b-11e9-8ba7-5585cf1a26e9.png)

Because what happened is you changed the default value for test_var but did not update & save the test_var2, and if you do not have Refresh on dashboard load it wont be re-evaluate on dashboard load
