### ISSUE TITLE
[Feature request] Graph - Add Delta "Mode Option"

### ISSUE THREAD

**Issue by JohannesRudolph** [grafana/grafana#16612]
**What would you like to be added**:

I would like to add a "delta" mode option to Graph Visualization "Mode Options", available here in the UI:

![image](https://user-images.githubusercontent.com/130103/56189235-bc42db80-6027-11e9-8d11-09e345b598f1.png)

The "delta" mode option would render, for each point (x,y) in the graph the y-delta to the previous pixel's value, so e.g. when we have two consecutive points from the datasource (x1, y1), (x2, y2) they would be displayed like this using "delta mode": (x1, y1), (x2, y2 - y1) ...

**Why is this needed**:

Delta mode effectively allows users to effectively display a kind-of-`rate()` function on counters in a way that is robust to the "counter increased missed between `query_range` step intervals" issue explained [here](https://www.stroppykitten.com/technical/prometheus-grafana-statistics) and extensively discussed in [Prometheus Issue #3806](https://github.com/prometheus/prometheus/issues/3806) among others. 

For a simple visualization of the issue, see this screenshot

![image](https://user-images.githubusercontent.com/130103/56190606-dc27ce80-602a-11e9-852f-738e78949b6f.png)

The top graph is a `rate(metric[$__interval])` while the bottom graph is a straight `metric` query (`sum ... by` ignored for simplification). As the bottom graph shows, the counter does increase reliably at a 1-hour interval, however the rate function misses these increases when they fall in between step windows. This is highly unintuitive for inexperienced users as seen by the participation and number of votes/reactions on the linked prometheus issues. 

The Prometheus maintainers have made it clear that this kind of anomaly is conscious design decision/tradeoff in PromQLs query evaluation model. They further state that PromQL clients (Grafana in this case) are the right place to implement possible remedies. I see two options for users to trade-off the "counter increased missed between `query_range` step intervals" anomaly for a different set of anomalies. 

- explicitly "oversampling" ranges (e.g. `rate(metric[x])` with `x > $__interval`)
- the delta mode option proposed here

Oversampling has the downside that it's probably impossible to apply correctly on dashboards that do not have a fixed time-range and use dynamic `$__interval` ranges instead to allow zooming in and out. Implementing a delta mode at visualization time allows the best tradeoff between only fetching the minimum of data required for rendering from the datasource and giving a pixel-perfect "rate"/derivative of the metric that includes all data-samples.

A further advantage is that it allows users to easily display a second-order derivative of a metric when applied to a `rate(metric[$__interval])` query which is useful for some graphing scenarios too.

Note: I'm not sure this is the best way to go about "fixing" the "counter increased missed between `query_range` step intervals" issue. I know it's a tough issue with many compromises to make, given the sampling nature of metrics.

**Comment by torkelo** [comment]
> The Prometheus maintainers have made it clear that this kind of anomaly is a conscious design decision/tradeoff in PromQLs query evaluation model. They further state that PromQL clients (Grafana in this case) are the right place to implement possible remedies.

Think this is a data processing problem, so a problem in that should be solved in the TSDB backend query processing. Doing rate / derivative calculations in the visualization layer feels super wrong. 

Is there any other way to solve it?

**Comment by haizaar** [comment]
@torkelo You are right. I wish it was addressed on P8s level. I think we have a situation here where everyone is right on their own end but end-users are those who are suffering. Unless you use a P8s [fork](https://github.com/free/prometheus/issues/2) where is no reliable way of doing the proposed.

Since the conversation reached an impasse state on the P8s side, it worth trying to persuade the solution through Grafana. It will have an added benefit of having something that works regardless of behind-the-scenes implementation of P8s (Thanos, Cortex, etc.), but that's a debatable benefit.

I understand it's unpretty from the perspective of Grafana developers. I'm not familiar with Grafana code so trust your judgement to decide whether unprettiness outweigh the benefits for the end-users.

Apologies for the emotional reply, but having read most of the discussions on the subject for the last year, I'm quite sure it's a not technical decision for the most of it.

**Comment by JohannesRudolph** [comment]
@torkelo to add another perspective to this, I think having a "delta" drawing option is useful in its own right regardless of the Prometheus situation.

Just the way the staircase option changes interpolation behavior for drawing lines between available data-points, "delta" does the same. I understand why doing rate/derivative in the visualization layer feels wrong. 

The other path to go down would be the oversampling route. This is currently not possible because PromQL does not allow expressions in range selectors, so we're stuck with plain variable substitution. 

Making this work would thus require grafana to support user-definable variable expressions like `$oversampled_interval = $__interval + 30s` and then allow me to to substitute this into a Prometheus datasource query like this `rate( metric[$oversampled_interval] * ($__interval / $oversampled_interval) )`.
This is much better than having users "fiddle" with a custom $interval variable and relying on users to choose the right value depending on zoom level to get accurate `rate()` results...

Does that route look more promising to you?

**Comment by free** [comment]
I'll offer my 2c as author of [Prometheus issue #3806](https://github.com/prometheus/prometheus/issues/3806), and someone who spent many days looking into this issue (and 1+ year maintaining a Prometheus fork that's basically a couple hundred lines of code on top of standard Prometheus).

In my view the problem is definitely on the Prometheus end of things, so I am in agreement with @torkelo, here.

If you want a (not so) quick and dirty method to display intuitively correct increases on a graph in Grafana, you need not go any further than:

```
metric - metric offset $__interval
```

Or, if you want to protect against counter resets:

```
clamp_min(metric - metric offset $__interval, 0)
```

Or more accurate yet, if you want to also cover counter increases immediately following a reset:

```
metric - metric offset $__interval >= 0
  or
sum without() (metric)
```

(That last `sum without()` is there to drop the metric name from the labels, so you get a single metric rather than 2.)

Problem is (as I see it) that this last expression is about ~3x as slow as `rate()` or `increase()` and is exactly what Prometheus should be doing in the first place (without having to pay the penalty). Plus, while not exactly rocket science, it's a lot more involved and opaque than simply writing `rate(metric[$__interval])`.

That being said, Grafana could easily do this transformation client side. It is just a sad state of affairs that it would need to do it to begin with.

**Comment by free** [comment]
Also, @brian-brazil pointed out on the Prometheus issue thread that @JohannesRudolph's proposed approach would not be able to handle counter resets and aggregation. Prometheus recommends that aggregated rates should be written as `sum(rate())` rather than `rate(sum())` for precisely this reason.

Namely, if you have 2 counters from 2 instances and one of the instances gets restarted, said counter would go down to zero (or some positive value just above zero, if the counter is incremented before Prometheus gets to scrape it). Maybe a (simplified) example would be clearer:

```
metric1            100 102 105   1   4   6
increase(metric1)    *   2   3   1   3   2

metric2            200 202 204 206 208 210
increase(metric2)    *   2   2   2   2   2

sum(increase)        *   4   5   3   5   4
```

If you first summed the 2 metrics, then took the `rate()`/`increase()` instead, you'd end up with huge spikes:

```
metric1            100 102 105   1   4   6
metric2            200 202 204 206 208 210

sum()              300 304 309 207 212 216

sum(increase)        *   4   5 207   5   4
```

You could instead choose to ignore counter resets (and output zero), but the more counters you aggregate and the more they reset, the more zeroes you'd have in your output (even when only one of the counters has reset and you could get useful information out of the rest).

And, to summarize, this is the best you could do client-size, i.e. in Grafana. Unless you went completely bananas, queried the individual counters from Prometheus and did all of the data processing within Grafana.
