### ISSUE TITLE
Only show refresh interval in header only when refreshing

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#16627]
The time picker header used to look like this:
![image](https://user-images.githubusercontent.com/705951/56224417-759fb200-6024-11e9-9cdc-f38a5c3f22aa.png)

Now it looks like:
![image](https://user-images.githubusercontent.com/705951/56224379-63257880-6024-11e9-86d7-61124a6ccd7b.png)

The "Off" text is kinda too important for a feature that is not running :)

Can we either:
* put the refresh interval back in the time picker
* make the refresh option for 'off' more subtle -- maybe just the dropdown arrow?

**Comment by torkelo** [comment]
having it in the timepicker feels wrong (an upcoming redesign of timepicker that turns it into a simple dropdown with quick ranges is coming). 

But I agree, the off is a bit much. The arrow down with a tooltip could work.

**Comment by ryantxu** [comment]
Also, maybe I am a creature of habit, but the far right button seems the easiest to find.  It was previously refresh, now zoom out.  To me, the most natural order would be:
```
[zoom out] [time picker] [refresh]
```

**Comment by torkelo** [comment]
```
[actions]  [tv]  [zoom out] [time picker] [refresh]
```

I agree this is the best / most logical order. But it has issues. 

1) Zoom out to the left of time picker is problematic as zoom out changes time to an absolute time which increases the width of the time picker by a large factor making it very hard to zoom out again  without first finding the moved location of the button. This is why I moved it to the right of the time picker. 

```
[actions]  [tv]   [time picker]  [zoom out] [refresh]
```

2 The time picker is the most frequently used button (in my experience) on most dashboards.  and having it nestled in the middle like this felt a little bad. Which is why I moved refresh to left of time picker. 

But maybe with a more minimal refresh (without Off word). It could work.

thoughts @Ijin08 @davkal

**Comment by torkelo** [comment]
Alternative that I think could work: 

![image](https://user-images.githubusercontent.com/10999/56270645-ed3e1180-60f6-11e9-846a-1950eb517dab.png)

**Comment by Ijin08** [comment]
Couldn't it just be a pause icon and no dropdown arrow? We don't have a a dropdown arrow for time range. But I agree with [time picker] [zoom] [refresh].
 
<img width="959" alt="Screenshot 2019-04-18 at 13 14 16" src="https://user-images.githubusercontent.com/23470681/56357396-f0f79400-61db-11e9-908c-23da379b19b8.png">
