### ISSUE TITLE
Live tailing for Loki logs in Explore 

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#16666]
**What would you like to be added**:

Would be great to live-tail logs for a stream selection in loki in Explore.

**Why is this needed**:

Users sometimes are about to do something where they expect a certain log output. Tailing gives them this instant feedback.

**Comment by torkelo** [comment]
I am a bit afraid to go too deep into this before we have more data sources that support Logs (and the required refactoring that entails, minor data model rethink, how to switch between logs & metric mode for data sources that support that etc). 

At least the LogStream & mergeStreams stuff that is in Explore seems to like something we would want to try to move into Loki first and see what the multi data source story looks like before going too deep into this. 

thoughts @marefr @hugohaggmark ?

**Comment by steven-sheehy** [comment]
Providing feedback/use cases on the POC branch as requested by @hugohaggmark:

- It was a bit hard to find the live streaming option. Would it make more sense to add a `Live` option to the refresh picker for datasources that support it?
- Ideally, live streaming would behave exactly the same way as manually running and auto-refresh. This includes the graph and column selection.
- If that's not possible, as a user I think the essential feature is to `tail | grep` to quickly filter down results.
- It was confusing that changing query text didn't filter the current output. Only new lines added were filtered. This is especially confusing when changing labels from app=foo to app=bar since now output shows logs from both. I think if label selector changes the output should be cleared. If regex changes I think it should either:
  -  Filter all current output locally. Logs stay in memory and could become visible again if regex changes again.
  -  Clear all current output and start over
- There might need to be some upper limit to how many lines displayed in browser in case people accidentally leave live streaming on for days and it OOMs the browser.

**Comment by ryantxu** [comment]
Maybe related... in #16729, I added a [javascript test datasource](https://github.com/grafana/grafana/pull/16729/files#diff-de666b197c7588df626182a5097643baR201) that spits out pretend logs data.  Essentially a timestamp and random sentence.

It would be great to have this be able to tie into the logging UI
