### ISSUE TITLE
Playlists based on tags stopped working

### ISSUE THREAD

**Issue by omelnyk1** [grafana/grafana#16704]
**What happened**:
A playlist created on tags stopped working and shows only first dashboard without switching.
**What you expected to happen**:
Playlist works like a charm :smile: 
**How to reproduce it (as minimally and precisely as possible)**:
1. Create new playlist
2. Add dashboards using tags
3. Run playlist

**Environment**:
- Grafana version: 6.1.4 (fef1733)
- OS Grafana is installed on: CentOS 6.10
- User OS & Browser: MacOS Mojave 10.14.3, Safari/Firefox, Windows 10 IE

**Comment by omelnyk1** [comment]
@torkelo could you please have a look?
Thanks in advance.

**Comment by marefr** [comment]
Confirmed bug since Grafana v6.1.0. Thanks for the report

**Comment by jschill** [comment]
The JSON object returned from the playlist api has a `Url` param with an ending slash `/`. 
https://github.com/grafana/grafana/blob/e4f649e2c8c6dfb252a5b0f1f45db0fd9b3d44c9/pkg/api/playlist_play.go#L58

(`populateDashboardsByID` does not return an ending slash. It is only `populateDashboardsByTag`)

When the client is comparing the returned Url param with the one in the state they are not equal and because of that the playlist is stopped.
https://github.com/grafana/grafana/blob/e4f649e2c8c6dfb252a5b0f1f45db0fd9b3d44c9/public/app/features/playlist/playlist_srv.ts#L73
