### ISSUE TITLE
Stackdriver: Support more Alignment Period values

### ISSUE THREAD

**Issue by thomas-riccardi** [grafana/grafana#16739]
**What would you like to be added**:
Add more supported values to the Alignment Period for the stackdriver datasource:

![image](https://user-images.githubusercontent.com/1730297/56648464-af576500-6683-11e9-9831-8b7f7fe7050a.png)

The list is hardcoded here: https://github.com/grafana/grafana/blob/3a6f49837def15469bf85a96f260d84f26bc71ee/public/app/plugins/datasource/stackdriver/constants.ts#L232-L242

For example: `10m`, `2h`, `2d`...
Ideally it could even/instead support free text to be able to enter `3d` without polluting the drop-down menu with too many values.

**Why is this needed**:
The hardcoded values are arbitrary, one could want to align over other periods of time.

(related to #16738)

**Comment by sunker** [comment]
Sorry for the late reply @thomas-riccardi.

Like you say it would be nice to be able to manually set the alignment period like in the Metrics Explorer ui. However it's not possible since we need this field to support `grafana auto` and `stackdriver auto`, and there is no ui control that supports that at the moment. 

What we could do now is to add a few more options. I suggest we add 2m, 3m, 10m, 3h, 3d. How does that sound?

**Comment by thomas-riccardi** [comment]
@sunker seems good !
Going more than one week is probably not very useful: the data retention period is 6 weeks on stackdriver (source: https://cloud.google.com/monitoring/quotas).

That being said, it would still be blocked by #16738.

**Comment by sunker** [comment]
Yes, I'll remove #16738. I think that check was due to a previous limitation in the API. Also, it's not needed anymore since it's not possible to manually enter values in the query editor (it used to be in an early version of the datasource). 

PR coming up.
