### ISSUE TITLE
Grafana 2.0b - http basic auth blocks access to the app

### ISSUE THREAD

**Issue by aidos** [grafana/grafana#1673]
If I use http auth on my nginx proxy in front of Grafana, I can't access the Grafana at all.

I'm using a simple `auth_basic_user_file  htpasswd;` within nginx to restrict access. When I try to access the Grafana it just asks for my user / password again and again.

From tailing the logs, I can see that after I first enter the un/pw, it gets past the nginx authentication and to the grafana server in the background. Once I give up and hit escape on the auth box, I see a message on the page saying `{"message":"Invalid API key"}`.

**Comment by torkelo** [comment]
I think you need to strip the Authorization header from reaching grafana, the Grafana HTTP api is expecting an api key in the Authorization header. I think nginx should be able to do that.

**Comment by torkelo** [comment]
I looked closer into this, and the error you got should not happen, Grafana backend will look for "Bearer XXX" Authorization header, and basic auth sends "Basic xxxx", so there was a bug in the Grafana code that caused this. It is now fixed in master. If you want a new build immediately, you can find them here:
http://grafana.org/download/builds

**Comment by torkelo** [comment]
Oh, and thanks for reporting this!

**Comment by aidos** [comment]
Amazing, thanks! I haven't had the chance to look at this since I reported it. I was planing on changing the nginx config and posting it here. You've saved me the trouble :-)
