### ISSUE TITLE
Refactor how we use time, time ranges and time zones in Grafana frontend/ui

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#16806]
Today we have two interfaces defined in `@grafana/ui` for representing time ranges, `RawTimeRange` and `TimeRange`:

https://github.com/grafana/grafana/blob/b803ba26894e3c0553252eadc2251ebc272f411d/packages/grafana-ui/src/types/time.ts#L3-L12

`RawTimeRange`:
Is used around the code base for passing time ranges in raw format, i.e. relative and absolute time formats, around. Since to/from can be either a `Moment` or either a `string` there's hard to know that those values actually represents since the string can be either relative time ("now-6h") or either time in epoch ms as a string ("1556531245712"), usually coming from url parameters, or a `Moment`. This clearly is a code smell.

`TimeRange`:
Is usually used for passing time to datasource queries. 

`Moment`: 
It's quite bad that we expose `Moment` to plugins and pollute the code base. Makes it really hard to migrate to a different library and for example adding support for additional time zones. 

Parsing of time:
Is done from multiple places and using multiple functions. These functions need to check what the types are of the to/from of `RawTimeRange` every time.

`TimeZone`:
We also soon have a TimeZone interface in `@grafana/ui` that looks like this:
```javascript
export interface TimeZone {
  raw: string;
  isUtc: boolean;
}
```

But there's also another type called `Timezone` defined here: 
https://github.com/grafana/grafana/blob/7146d576e623a8b663ea5f66aa350624677408d1/public/app/core/utils/datemath.ts#L7 

**Investigation needed:**
Investigation is needed to see what kind of work being involved to create better interfaces for time ranges without exposing `Moment`. How to migrate away from exposing `Moment` to plugins. At least from a `grafana/ui` point of view one goal should be to not expose time from a 3rd party library. Internally we should still be able to use `Moment` over a migration phase. Additionally it would be nice to move all date, time and time zone parsing and conversions to a single place.

**Comment by AlexMabry** [comment]
I really like what you've done here by hiding the details behind an API.  Is there a way I can help migrate the codebase to support your vision? I love to refactor! :)

My motivation is to eventually have the ability to set which timezone is displayed in each panel.  Let me explain my use case: I monitor metrics in many industrial facilities that are often related to various production shifts. Having the graph being in the site's timezone (which isn't mine or UTC) would greatly help our team more quickly comprehend the information and diagnose issue quickly if necessary. Specifically, some of our metrics are related to energy consumption, and knowing the metric's expected behavior would depend on the site's local time. 

Also, have you considered using Luxon as an alternative to Moment? Here is a comparison of the two: https://moment.github.io/luxon/docs/manual/moment.html I've had good luck with it in my own projects, and I think it would help displaying non-local/non-UTC timezones.
