### ISSUE TITLE
2.0b1 - RFE: Allow customization of the login screen with message of the day

### ISSUE THREAD

**Issue by dutchiechris** [grafana/grafana#1684]
Because there is now a login screen it would be useful if you could customize the screen, at the minimum with a message of the day.  Maybe a text panel allowing any HTML goodness?  As-is I know users will call me (assuming they even know who I am) the first time they are confronted with a login screen instead of their beautiful graphs.  Some shops might also like to display some 'unauthorized access is prohibited' type of message to comply with security policies.

Not a top priority item, but something to add to the feature list.

**Comment by torkelo** [comment]
Thanks, good suggestion!

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
