### ISSUE TITLE
dashboard import is not working

### ISSUE THREAD

**Issue by JensNeu** [grafana/grafana#1690]
Hello, 

I installed the actual beta version today and tried to import my old dashboards that are stored in a 0.8.X Influx Database. 
I could see the dashboards but when I select one I just get a grey screen and have no possibility for any interaction. 
Can't see any graphs and also cannot delete these useless dashboards. 

I attached a screenshot showing the imported dashboards and another screenshot showing the browser content after I clicked on one of the imported dashboards.

Any Ideas? We are using grafana 1.9 at the moment and store the dashboard in an influx db 0.8.X

![dashboards_overview](https://cloud.githubusercontent.com/assets/11752880/6940430/236e1136-d877-11e4-9516-98cfd4b84f14.png)
![dashboard_error](https://cloud.githubusercontent.com/assets/11752880/6940439/324864ea-d877-11e4-8f61-a32dcd904d97.png)
Jens

**Comment by torkelo** [comment]
can you open chrome dev tools and inspect the javacript console for js errors? Did you add you InfluxDB 0.8.x data source that has our metrics as well (seperate influxdb database), and remember to mark it as default

**Comment by torkelo** [comment]
Oh, and you open chrome dev tools (firefox dev tools) using F12

**Comment by JensNeu** [comment]
Error: a.metricFindQuery is not a function this.updateOptions/<@http://XXX:3000/app/app.8ae07506.js:21:20718 i@http://XXX:3000/app/app.8ae07506.js:10:29756 j/<@http://XXX:3000/app/app.8ae07506.js:10:29928 Rb/this.$get</l.prototype.$eval@http://XXX:3000/app/app.8ae07506.js:12:5064 Rb/this.$get</l.prototype.$digest@http://XXX:3000/app/app.8ae07506.js:12:3578 Rb/this.$get</l.prototype.$apply@http://XXX:3000/app/app.8ae07506.js:12:5322 h@http://XXX:3000/app/app.8ae07506.js:10:13555 q@http://XXX:3000/app/app.8ae07506.js:10:15364 kb/</u.onload@http://XXX:3000/app/app.8ae07506.js:10:15904

I added my influxdb as default, but i'm not sure if i did that before or after the dashboard Import. I would like to Import again, but have to delete the dashboards before...

**Comment by torkelo** [comment]
you should not have to delete the dashboards, did you add a influxdb data source of type 0.8.x for you metrics? Please name the datasource with the same name as you did in config.js for grafana 1.9 ,  It looks like you have a templated dashboard, with template variables that are using a datasource that does not support metricFindQuery, it probably means that when you marked it as default it did not take effect (bug in beta1, fixed by doing a full page reload, this is fixed in master and in the next release). 

so try
1) Rename datasource name to be the same as the one specified in config.js (the key/property name in the datasources js object)
2) Try a full page reload
3) try a dashboard that is not using templates (just to check if they work)

**Comment by JensNeu** [comment]
Hi,
thanks for the immediate replies. Renaming the datasource that includes the data to the same name it had in the config.js file helped. All dashboards are showing graphs now.

**Comment by torkelo** [comment]
@JensNeu great! Will add that to the migration docs
