### ISSUE TITLE
[bug] gitlab auth failed

### ISSUE THREAD

**Issue by JimmyDaddy** [grafana/grafana#16968]
**What happened**:
Failed  to use GitLab  for signing in:
![76CA7439-9A7C-446C-A492-3CA9701F7A75](https://user-images.githubusercontent.com/16460813/57424080-fb400780-7248-11e9-8a25-e7cbe83afc84.png)

Error message:
```
lvl=eror msg="login.OAuthLogin(get info from gitlab)" logger=context userId=0 orgId=0 uname= error="Error getting user info: invalid character '<' looking for beginning of value"
```
**Anything else we need to know?**:
My GitLab Auth config:
```
[auth.gitlab]
enabled = true
allow_sign_up = true
client_id =key
client_secret = key
scopes = api
auth_url = http://gitlab.mydomain.org/oauth/authorize
token_url = http://gitlab.mydomain.org/oauth/token
api_url = http://gitlab.mydomain.org/api/v4

```
**Environment**:
- Grafana version: v6.1.4 (commit: fef1733)
- OS Grafana is installed on: CentOS Linux release 7.6.1810
- User OS & Browser: MacOSX/Chrome

**Comment by pedrotavares-MG** [comment]
@JimmyDaddy  I am facing the same issue.
How did you fixed it ?

**Comment by marcus-sa** [comment]
I'd like to know the fix as well since this happens when using Github OAuth

**Comment by tobiashochguertel** [comment]
Remove the `hostname: 'gitlab.mydomain.org'` setting from the docker-compose file or the docker command in your shell to ensure that the container resolves the IP address fro the dns `gitlab.mydomain.org` correctly - to the eternal ip address of your subdomain/domain.

you can check from the inside of the container which IP address will be used to resolve for your domain/subdomain by `ping` - use `ping` not `dig` to see which Ip address will get resolved, because `dig` uses the nameserver from `/etc/resolv.conf` an ping uses as first the hosts file and then an external dns.
