### ISSUE TITLE
Subsecond graphs not working 

### ISSUE THREAD

**Issue by markusr** [grafana/grafana#1698]
I tested the new 2.0-beta1 in conjunction with Influxdb 0.9-rc18. It works fine so far and I can see the graphs.

However, if I query for subsecond range the graph doesn't show any values.
Example query:
```SELECT mean(value) FROM "ssc_test" WHERE time > 1427921145s and time < 1427921352s GROUP BY time(0.1s) ORDER BY asc```

The problem is with  ```GROUP BY time(0.1s)```. If I change this manually to  ```GROUP BY time(100000u)``` the response from influxdb is correct and I see the points.

**Comment by torkelo** [comment]
ok, thanks for reporting this. It might not be fixed in a while, the InfluxDB 0.9 editor and datasource is in a very early stage, and this isnt a quick fix (chaning interval limit of 0.1s will effect other data sources, so need to figure out how to override that for influxdb). And before that I want to get InfluxDB 0.9 working in a more robust polished way (barely usable right now). But InfluxDB 0.9 might start maturing so that it is easier to test the editor and work on it.

**Comment by torkelo** [comment]
This will be fixed when the influxdb 0.9 editor is made more real (will allow you to override auto group by interval)
