### ISSUE TITLE
Test datasource: Error thrown when using table panel and table scenario

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#16996]
**What happened**:
Use test datasource in table panel with a table scenario. Error "Result of query #A is not in table format, try using another transform." is thrown and no data render. See https://play.grafana.org/d/44liOaiWk/16996-test-datasource-and-table-panel?orgId=1

**What you expected to happen**:
Table rendered with data

**How to reproduce it (as minimally and precisely as possible)**:
Use test datasource and table panel. Select Table static as scenario.

**Anything else we need to know?**:
Have tried postgres datasource and table format, but that works as expected.

**Environment**:
- Grafana version: master (5e44f00) and v6.2-beta1

**Comment by marefr** [comment]
@ryantxu do you have any idea about this problem?

**Comment by torkelo** [comment]
The reason is that test data source does no longer new up TableModel instances (which set type = table in constructor). In the table transformer in the table panel it looks for type === 'table'. This check needs an update. Moving this to 6.3 as I do not think this is critical for 6.2 stable.

**Comment by nmingotti** [comment]
Hi, 

The problem with **Table Panel** and "table view" still persists.

Here "table view" refers to the alternative view respect to "timeseries" in the Table Panel. 

Using your  [fake-simple-json-datasource-master](https://github.com/bergquist/fake-simple-json-datasource) as data provider, **SimpleJson** data source and then trying to visualize a Table/"table view" fails.

In **Grafana 6.2.1** there is the message saying "query #A is not in table format".

In **Grafana 6.3.3** there is no result displayed when setting "table view" instead of the defaut "timeserie" view. The interface hangs on a black screen when moving from the "Visualizations" to "Queries" slectors trying to get a tablish-output. 
 
What goes out of the Node service is the following.
```
 [{"columns":[{"text":"Time","type":"time"},{"text":"Country","type":"string"},{"text":"Number","type":"number"}],"values":[[1567025699552,"SE",123],[1567024699552,"DE",231],[1567023699552,"US",321]]}]
```

I confirm that the "table view" works if I use **Postgres** as datasource.

**Comment by nmingotti** [comment]
I solved it. 

The data farmat used in [fake-simple-datasource](https://github.com/bergquist/fake-simple-json-datasource/blob/master/index.js) `var table = ` is not recognized anymore. 

The format for taublar accedpted by Granana 6.X apparently is the one described in [JSON datasource](https://github.com/simPod/grafana-json-datasource). 

bye
