### ISSUE TITLE
Allow expiration of API Keys

### ISSUE THREAD

**Issue by Lou-Cipher** [grafana/grafana#17042]
Currently, API keys have no expiration date, making forced key rotation difficult.  We would like the ability to set an expiration time for API keys, after which time the key will be marked as invalid (but not necessarily deleted), and would have to be rotated.  Ideally, this would involve two parts.  First, the ability to specify an expiration time when creating an API key.  Second, enforcing an admin-controlled max expiration time, not allowing users to create keys with an expiration greater than this setting (possibly, and configurably, allowing admins to create longer-lived keys).

Our security team will not allow us to utilize API keys without an expiration date, so this would be a significant improvement for us.

**Comment by xlson** [comment]
@bergquist not sure how high we want to prioritize this, but I think it makes sense to implement this fairly soon. What do you think?

**Comment by bergquist** [comment]
I agree. Would be great to get this one into 6.3

**Comment by aocenas** [comment]
I have a few assumptions to clarify here regarding the design so let me know what you think:
- config value for max api key duration, if it is non empty all new keys need to have max expiration duration set and it needs to be less than that value. If it is empty you can set the max expiration time but do not have to. Existing keys will not be changed if the config value changes.
- In the UI it should be a duration input we have already, where you can set `1d` for example, meaning key is valid 1 day since creation (if it is left empty it will mean key won't expire). After creation I think it makes sense to have expiration date in the UI as a column and hide all expired tokens (otherwise they would pile up). @Lou-Cipher or do you have a use case for showing the expired tokens in the UI?
- `possibly, and configurably, allowing admins to create longer-lived keys` is there a good usecase for this? We do not have creator user id in the DB or UI and without it, it could be confusing to see long living keys without knowing they were created by admin (on the other hand this would also happen if the setting changes after key is created).

cc @bergquist @xlson

**Comment by bergquist** [comment]
1) Sounds good!
2) Nm. Not sure what kind of duration we can expect here. The golang parser only durations up to hours. the gtime package support weeks and years but not months(since length differ). Perhaps we could add a new function in the gtime package that allows months based on current date.
3) I think we can skip it for now.

**Comment by aocenas** [comment]
@bergquist 
2. For the duration I think the API should take just integer seconds so something like timeToLive. That means that in the UI we would just convert duration string like `1d/1w/1y` to number of seconds with moment.js and send it to backend.

**Comment by bergquist** [comment]
Sounds good!

**Comment by bergquist** [comment]
Just make sure to name the expiration variable in such a way that its easy to understand that it seconds. So it's easy to understand how to use the API for adding API Keys.

**Comment by Lou-Cipher** [comment]
@aocenas Regarding point 3, I'd agree, skip for now.  There is also an open issue to add more information about keys to the DB, #4961, to add creator info to keys (among other useful info).  If that were implemented, point 3 would make more sense to implement, too.

As to expired tokens showing in the UI, I could see making it a togglable option in the UI.  Could be useful for auditing API key history.  I don't personally have a need for it, but I can see it coming in handy.
