### ISSUE TITLE
Different Time Periods In Dashboard

### ISSUE THREAD

**Issue by ProTip** [grafana/grafana#171]
This is a bit of a bugbear for me in Kibana.  It would be great to support having per-panel time periods that can be, or can not be, overridden by the dashboard time period at will.

**Comment by torkelo** [comment]
I have spent a few hours working on this issue. So far it only works on the graph panel, need some feedback for how it should work on the singlestat panel. 

![image](https://cloud.githubusercontent.com/assets/10999/5898576/12bd82bc-a551-11e4-82f9-60385431bf4e.png)

There is now a time range tab in the graph panel edit view
![image](https://cloud.githubusercontent.com/assets/10999/5898615/724b73ba-a551-11e4-92b6-a0ed15320103.png)

You can override the relative time, and/or add a time shift. As you can see in the first screenshot the relative time override is displayed in the top right corner of the graph, as is the time shift if present. 
The way this works is that if the dashboard time is relative (for example Last 6h), then the relative time override will be applied. If the dashboard time is absolute, for example you have zoomed in. Then the relative time override will not be applied. That way the zoom works as expected even when you use it on a panel with a different time range. If you change back the dashboard time to a relative time the panel override will be turned on again. 

Time shift happens after the dashboard time / or the panel relative time is applied. The timeshift will still be active when an absolute time is used (for example when you zoom in). The problem with this is that if you select a region to zoom in on a timeshifted graph, the time range will not be what you expected as the zoomed in region will set to the dashboard time, but the graph time shift will still be applied. This could perhaps be fixed by disabling the timeshift if the zoom in happens on a panel where time shift is enabled.

Another issue is how to implement this on the singlestat panel. The only problem is how to visualize the relative time override or the time shift. Singlestat panels can be quite small, and some even do not have a title, so not sure where to put the info that the panel is not using the dashboard time range.

**Comment by mikhailov** [comment]
it's a bit off-topic, but what is the best way to send custom metrics (not-interval based like CollectD data) to Carbon? At the moment we use netcat (echo .. | nc) but the get only 1-min resolution data that rounded weird way.

**Comment by elvarb** [comment]
Is it possible to have this per metric? 

So you can show the last 7 days and the last 7 days before that it the same graph?

**Comment by torkelo** [comment]
@elvarb no, but that you can do easily with graphite timeShift function, if you are using InfluxDB I think you better request that feature on the influxdb repo. Timeshifting individual metric series is trickier and more performance intensive (not much).

**Comment by dowstreet** [comment]
Thanks for working on this!  A few thoughts -

It looks to be quite useful to allow different time ranges (including refresh intervals) for different panels.  What if each panel had to be set as one of two different modes?

1. use global dashboard settings, or 
2. use panel-specific settings.  

This is kind of what is implemented now, except that the per-panel settings are inherently related (via offset?) to the global dashboard settings, rather than being truly independent.  (i.e. having the full range of time settings available on a per-panel basis).  Do I understand this correctly?  Alternatively, if each panel its own (full) set of time settings could make things a bit cleaner and more flexible, although I don't know much the query / datasource code would need to be revised to allow this.

To handle zoom in this model, a reasonable default might be to only link the zoom actions of panels with the same time settings - either because they are both in 'use dashboard settings' mode, or because they have panel-specific settings that cover the same time range.  Maybe a panel could also have a 'disable linked-zoom' setting as well, so that it would not be altered based on zoom events originating in another panel.

One usability consideration is the amount of info one would need to populate to configure panel-specific time settings.  If the per-panel settings are truly independent of the global dashboard settings, but you actually want settings that are pretty similar - e.g. like a simple offset as in the example above - then the user has to do more work to figure out what to enter in there.  Perhaps this could be partially addressed by populating the default values in the per-panel time configuration with the global dashboard settings.

Anyway - thanks again for working on this part.  Getting the UI semantics to be intuitive does seem to be tricky when there are multiple time ranges covered.

**Comment by torkelo** [comment]
@dowstreet thanks for your feedback. 

1) If you use the relative time override option on the panel it will override the relative time of the dashboard. It is not relative to the dashboard time. It is completely independent. I do not see a use case where you want a fixed absolute time for a panel. Just a different relative time (relative to now). A different refresh could be an option, but might be unnecessary for now.   

2) The timeshift time can be relative to the dashboard time range if no relative time range override is specified for the panel. 

3) Zoom I think as soon as zoom/absolute time range is present in the dashboard all panels should use that time range, (and the timeshift should be applied). The only thing that is tricky is zooming in on a timeshifted graph. In that case the timeshift might need to be disabled.

**Comment by dowstreet** [comment]
Thanks Torkel - a few more thoughts:

1) One way that we use grafana is to look at data from different experiments.  If you want to compare different runs of the same experiment, it is handy to be able to set up one group of panels with the (fixed) time range of the first experiment, and then some other group of 'matching' panels for the fixed time range of the second experiment.  A related use case would be to set up a fixed range for the first set of panels (i.e. first experiment), and then set auto-refresh for the second set (experiment two) - so that you could monitor the second experiment in near real-time, while having the context of the first experiment.  (For looking at historical data, it is nice to be able to set the start/end time to known values, rather than computing the time window relative to the current time).  A workaround is to have two separate browser windows open, but all-in-one would be much better.

2) Ok

3) Zoom - To me it is intuitive to have the zoom events linked if those panels are showing data that is closely coupled.  If you have a case like in 1), though, the closely coupled events are separated by time - e.g. two similar network outages that occurred on different days.  Here 'similar' is the hypothesis that you want to investigate, and if you can zoom independently into two different time ranges, you can look at them side by side.  If, however, you are limited to a single 'zoom' range dashboard-wide, rather than per panel (or per set of panels), then it is tricky (impossible?) to look at both zoomed-in ranges at once.  Does that make sense?

Thanks again for working on this - and let me know if I'm overlooking how this use case could be handled with the current approach.

**Comment by torkelo** [comment]
@dowstreet good thoughts, now I understand better why a absolute time range on panel could be useful and have panels locked even when zoom in on another panel. Hard to visualize an absolute time on the graph though (will take up a lot of space to have the full date range in the upper right of the graph)

**Comment by rafrey** [comment]
I really like the idea of being able to set independent absolute time frames and zoom them independently for reviewing metrics against baselines or previous test iterations in the past and think its a very valid use case. One of the things that immediately attracts new users to Grafana is the UI though and it would be a shame to put a scratch or a dent in something so sleek.

I feel like you could still keep the UI clean if you added both independent zoom and absolute time frames for panels. To keep the panels from becoming cluttered consider using an independent zoom check box to toggle whether the panel reacts to zoom actions outside of it's own context (in other panels) and icons to represent start and end time in each panel, then allow the user to mouse-over either icon to see the textual time info for the panel's time span (similar to the existing mouse-over for global dashboard timespan).

Clicking the icons would allow you to set the start or stop time for absolute time spans in a popdown/up/out prompt. If the independent zoom is enabled then zoom actions should be relative to the panel's time span whether it is using a global time span or has been altered to an individual timespan (absolute or relative), so with independent zoom enabled you are essentially enabling the panel's independent time span and setting an absolute time span for the user. Of course with independent zoom enabled, zoom actions in other panels won't alter the timeline in this panel. Unchecking independent zoom will cause the panel's individual time span to be reset to the gloabl time span.

The features remain independent but tightly coupled.

Re-syncing the panel's timespan with the dashboard's global timespan could also be done in the set start/stop time popdown/up/out prompts, it seems like a logical place and gets it out of the main UI. You could also provide a visual cue to the user to let them know if the panel is using it's own timespan or the global timespan by changing the color in the icons to gray when the panel's individual timespan is not in use (use a flag to check this). Lastly, the Independent Zoom text box could be replaced with an icon with an enabled and disabled state as well, something like a magnifying glass with a big letter "I" for independent or something. You probably could put arrows on either side of it for zoom in and zoom out as well. 

I realize talking about this and making it happen in code are two different things alltogether, but is seems plausible and would really add quite a bit of value to the application.

If all panels have their own timespan then I'm hoping this is just a matter of maintaining a sync_with_global_time flag and when you set the panel's timeframe you either except a start and stop time passed from a user prompt or zoom action. For user set absolute time span if the flag is set to sync with the global dashboard timespan you disable the sync and set the panel timespan to what the user specified. If a zoom in/out action is performed outside the panel and the independent zoom is disabled action it in the panel regardless of whether the panel timespan is synced with the dashboard timespan or not, if independent zoom is enabled do not action. If a zoom action is performed within the panel and the independent zoom feature is enabled do not action it outside of the panel, instead action it within the panel using the panel's timespan (whether or not it is synced with the gloabal timespan). If independent zoom changes from enabled to disabled, also set the sync_with_global_time flag to sync with global timespan. If the independent zoom changes state from disabled to enabled leave the sync_with_global_time flag alone, however when a zoom action occurs inside the panel with independent zoom enabled, if the sync_with_global_time flag isn't set to disable the sync with the global timespan then disabled it before performing the zoom command.

![image](https://cloud.githubusercontent.com/assets/9465135/6101781/4b5e77e8-afe7-11e4-956b-d5c2e8ea2fd7.png)

**Comment by torkelo** [comment]
@rafrey thank you so much for you comment, that was great feedback, and a UI mockup screenshot as well. Exactly the kind of feedback I wish foor! :) 

Will try to work on this issue more after Grafana 2.0 backend and new UI views are more stable

**Comment by loopping** [comment]
For singlestat panels, ideas from rafrey of small buttons on graphs panels and the logic can be used, but we will need a "time range" panel in "edit panel".
In this panel we could find an "Overide relative time", a "Add Time Shift" and some check boxes
-show/hide "independent zoom" text or icon containing the time frame
-lock/unlock zoom with the dashboard's global timespan

With this I would be able to see a value for a metric updated once a day in singlestat panel.
To do so I'd put 1d in the "Overide relative time", hide "independent zoom", lock zoom.

**Comment by MitchSUEW** [comment]
+1 My usecase would be:
Showing current smart meter values and derivative values (per day/week/month/year of a smart meter counter. So I would be able to see within the same dashboard the current energy production(in kW) of my solar panels as well as the amount(sum) of energy produced per different timeframe  (in kWh).

**Comment by loopping** [comment]
From the develop branch, in file app/panels/singlestat/module.js, I have added the panel "Time range" at line 35:
<pre><code>$scope.panelMeta.addEditorTab('Time range', 'app/features/panel/partials/panelTime.html');</code></pre>
I have added the applyPanelTimeOverrides function (copied from app/panels/graph/module.js) at line 112
And added in updateTimeRange function
<pre><code>$scope.applyPanelTimeOverrides();</code></pre>
juste before
<pre><code>$scope.resolution = $scope.panel.maxDataPoints;</code></pre>
I can now override time range for single stats, which solve https://github.com/grafana/grafana/issues/1463 and I'm now able to see a value for a metric updated once a day in singlestat panel, independent from the global "time range"

**Comment by torkelo** [comment]
This is now available in singlestat panel as well (with the same override info to the top right). 

![image](https://cloud.githubusercontent.com/assets/10999/6430489/c3fdae7e-c00b-11e4-9340-3cbe7c770caa.png)

There is also a new option to hide the time override info. Absolute time range overrides will have to wait for Grafana v2.1. 

The singlestat addition is available in the develop branch (Grafana 2.0 & the new backend branch)

**Comment by rafrey** [comment]
Thanks! This will be really nice for performance analysis when comparing
different iterations of the same test. Adding the ability to effectively
freeze a panel with an absolute time range and zoom in on them
independently in v2.1 will make this an EXTREMELY powerful performance
analysis tool. If you get this working, I personally can't think on
ANYTHING else out there in the performance analysis world that provides
this functionality. Keep up the amazing work, much appreciated!

PS - what about an online repository of community developed dashboards? For
example say I develop and release an APM tool that uses Grafana? Now 200
other people develop something else that uses Grafana. Wouldn't it be cool
to see all of those in one place and be able to download them easily?
Ideally users could download the dashboard from within the app with a
search string and versioning would be built in...something to consider. I
can create an issue if you would like?

**Comment by torkelo** [comment]
@rafrey yea, a public dashboard repository is something that I have been thinking about as well (for many many months). Hope get it done some time this year, just needs some kind of templating feature as well (metric prefix paths etc)

**Comment by rafrey** [comment]
I'd suggest scoping it to start simple and plan it in such a way that the
full feature set is understood at the beginning and locked down until
completion so that people can begin to take advantage of it as soon as
possible. I think it could dramatically speed adoption. Allowing people to
just post a set scripts or configuration files and documentation in an
archive or something along with the dashboard json and just have the
dashboard added to the back end and the additional objects archive saved to
disk would get this to a usable state. Just making the suggestion because I
truly believe it would make this project much more visible and gain it some
major credibility. At some point you will be able to download everything
you need without developing any dashboards at all if it works well.

**Comment by rafrey** [comment]
It just occurred to me that creating a dashboards directory in the project
on github and just letting users submit push requests to store their
dashboard json there with a comment in it that has a link to their
documentation for configuring their metrics naming schema or configs to do
that with a client online might be a good first step...no
auto-implementation or anything just a central repository.

**Comment by rafrey** [comment]
Off topic, I'll create an issue and move this over.

**Comment by tlopo** [comment]
This may help someone, so below that's how I implemented  time shifting feature on my scripted dashboard.

1. Create a function to query your data source
2. Create a graph panel model from one  snapshot
3. Create a function to shift the time 

Below that's how  shift the time for influxdb.

```
function getSnapdata (query,shift){
        var snapdata = { "datapoints" : [], "target" : "targetname" }

        if (!isNotNull(shift)) {
                shift=0;
        }
        var result = runQuery(query);

        var points = [];
                _.each(result[0].points, function(e,i,list){
                var time=(e[0] + shift);
                var value=e[1];
                points.push([value,time]);
        });
        snapdata.datapoints = points;
        return snapdata
}
```
 And how I use it: 

```
var query= "your query goes here, make sure it's using  where time > now()-31d and time < now()-30d ";
var shift = 60 * 60 * 24 * 30 * 1000; // shifting 30 days in ms
var snapdata = getSnapdata(query,shift);
snapdata.target="Last month"

panel.snapshotData.data.push(snapdata);
dashboard.rows[1].panels.push(panel);
return dashboard;
```

**Comment by torkelo** [comment]
@tlopo what does that do that you can't do with the built in support for panel time shifts in Grafana 2.0?

**Comment by tlopo** [comment]
That allows me to compare a series (or any result for query) in the same  graph: ![graph] (https://sc-cdn.scaleengine.net/i/6612aa68f5677010ebdd7901254e9031.png)

**Comment by torkelo** [comment]
@tlopo you should request this that feature from InfluxDB  (or switch to Graphite) :)

**Comment by tlopo** [comment]
They will be supporting custom functions similar to stored procedure sometime (soon I hope) then it will be ok, I was thinking maybe I could create a very simple node.js app to proxy influxdb requests and add some custom functions...

**Comment by kokarn** [comment]
What happened to absolute time ranges? 
Is it dead in the water?

**Comment by kamarides** [comment]
+1

**Comment by joseche** [comment]
This has been already implemented with formulas, you just need to add the same metric twice and do:
timeShift ( metric, '-24h' ) in one

It works using graphite at least.

**Comment by rafrey** [comment]
@joseche I believe you may have misunderstood the use case. What you are suggesting (with timeshift) would implement a different releative time period, what is needed here is an absolute time period (a way to visualize a static time period that occured in the past against the current last X minutes for example). This could be used to compare what happened during a performance test that was conducted between X and X time X days ago against a current test that I started X hours ago (which is still running). You would have to rewrite all of your queries to modify the timeshift every time you started a new test for that to work (because it is relative to the current time and not absolute/static).

**Comment by mihino** [comment]
+1 
with influxdb

**Comment by vleushin** [comment]
This is essential feature, how come it is not implemented yet? Is it difficult?

**Comment by vleushin** [comment]
This is what is wanted:
https://github.com/grafana/grafana/issues/171#issuecomment-113533494

Not this:
https://github.com/grafana/grafana/issues/171#issuecomment-71444087

Why this is InfluxDB feature? Grafana queries InfluxDB and can query with -7d interval for example and then merge results.

**Comment by lukashes** [comment]
@vleushin +1
It really important feature to show different time intervals on same graphic. Is waiting some activity by this topic?

**Comment by trent** [comment]
+1

**Comment by max3163** [comment]
+1

**Comment by lucadistefano** [comment]
+1

**Comment by jiamc** [comment]
+1

**Comment by borisxm** [comment]
Yeah, having feature to shift query by some time offset back are hard to overestimate. For example, one may compare slow year-cycled processes just by specifying "-1y" or "-2y" for particular query and all features like zoom or tracking will work as expected.

**Comment by torkelo** [comment]
Mixing data from different time periods in the same graph is something you can do in Graphiite with the timeshift function

**Comment by borisxm** [comment]
Yes, Graphite allows one to do this, but about a year ago I've switched to Influxdb for performance reasons and found Grafana+Influxdb to be a wonderful pair. It seems, that the only solution for now is to setup a mirror with highly downscaled series in Graphite or adapt tlopo's solution.

**Comment by rafrey** [comment]
Please don't derail this feature request with inquiries about timeshift. As
explained mutiple times throughout the thread this is NOT a request to
timeshift in a query. We are trying zoom independently and to display an
absolute fixed time that is static and different than the time represented
by other panels in the same dashboard. I should be able to set or zoom to a
start and stop time, this is different that setting a relative offset or
timeshift by x amount of time. The primary use case is performance testing
and benchmarking but the feature could be applied to many others as well.

**Comment by gunererd** [comment]
+1

**Comment by Dichotomia** [comment]
What about the original request? Why has this thread been closed?

**Comment by torkelo** [comment]
@Dichotomia because the panel time range tab allows for different time periods for each panel

**Comment by Dichotomia** [comment]
I can't set absolute fixed time that is static and different than the time represented by other panels in the same dashboard.

**Comment by torkelo** [comment]
@Dichotomia that is true, there is a limitation.

**Comment by michelmarinho** [comment]
Hi, I tried "current month" now/M but dont work.  I did some wrong things?

**Comment by karthikeyan95** [comment]
Hi, as far as my understanding goes, grafana can support different time range for each panel using the time range option. But it is a relative time to the time range that i select at top of the app. 
Is there any development that is being done for giving specific time range for each panel.

currently a specific time is given for all the panels in a dashboard. Can it be like to override any single panel by giving a specific time range for that panel alone, which does not depend on the dashboard time range.

**Comment by emmettwmoore** [comment]
+1

**Comment by nurikk** [comment]
+1

**Comment by jisaitua** [comment]
+1

**Comment by joaquin386** [comment]
+1

**Comment by matlabombe** [comment]
+1

**Comment by devbhaskar** [comment]
+1

**Comment by jordanarseno** [comment]
+1

**Comment by SeriousM** [comment]
+1

**Comment by alrghods** [comment]
+1

**Comment by husainkhambaty** [comment]
+1
Just out of curiosity, has this feature been added if this request was closed? Quite keen on a similar usage as outlined here : [https://github.com/grafana/grafana/issues/171#issuecomment-73464325](url)

**Comment by clugoimx** [comment]
Still looking for a way to select an absolute range for a graph panel. Using relative has data shifting about as the time progresses throughout the day. 
I have one panel showing "yesterday" numbers and another that needs to show "last week" numbers while displaying on the same dashboard. As a relative value changes throughout the day so do graphs that should remain static.
In addition since my dataset doesnt include data since midnight I end up with a big gap that also grows throughout the day.

![image](https://user-images.githubusercontent.com/39413565/40499305-8f1a50ea-5f4f-11e8-8717-c44df97745f5.png)

**Comment by clugoimx** [comment]
Note I am using mssql as a datasource

**Comment by gisfinder** [comment]
I'm researching the tool to be used for SCADA historian dashboard. All other features are fine.
When I try to change the time period and zoom in/out I found it attached to all panels of the dashboard.
This does not afford with our requirement. I will have to transfer other solution.

**Comment by lprofession** [comment]
@tlopo How did you implement the  comparison of series  in the same graph? Need to develop any plugin?

**Comment by tvgh** [comment]
+1

**Comment by phiral** [comment]
+1 does anyone know if this feature is available now? can see this was requested 2014.

**Comment by alterecoop39** [comment]
Hello!

I know this topic is pretty old so I made a quick review of what's currently possible with InfluxDB and Grafana. 
If you're interested in this topic, I invite you to visit it!
[https://community.grafana.com/t/mutiple-time-ranges-on-same-dashbord-influxdb/15329](url)

Happy hacking!
https://alterecoop.fr

**Comment by feutl** [comment]
Perhaps a stupid question, who knows, but I am using Grafana 6 and InfluxDB and do not see the additional tabs like Time Range.
Is this feature limited to Grafana and Graphite ? I could not find any information why my Grafana setup is not showing me the additional options.
Thanks

**Comment by torkelo** [comment]
It’s moved to the bottom of the queries tab

**Comment by feutl** [comment]
> 
> 
> It’s moved to the bottom of the queries tab

Thanks but I still do not understand.
I looked at https://grafana.com/docs/v6.1/features/panels/graph/#time-range and I am using 6.1 as well, but cannot see this option.
Either doc is wrong or I miss something on my installation.

All I have on the bottom is "add time region" which seems to be something different. I also tried another browser but seems the same outcome.

**Comment by marefr** [comment]
@feutl you're in the Visualization tab, but you should look in the queries tab. See bottom here for example https://play.grafana.org/d/000000012/grafana-play-home?tab=queries&orgId=1&fullscreen&edit&panelId=2

**Comment by feutl** [comment]
You mean "Relative time" value is doing the expected - but why is the documentation wrong ? Is there a reason, I am new to the whole grafana thing - perhaps I missed something there :)

But thanks - this worked out :)

**Comment by marefr** [comment]
Grafana v6 introduced major changes in user interface and we haven't had time to update all of the documentation.

**Comment by zimonth** [comment]
Ah. So there is no "time range"-tab, or actually any tabs in the panel edit mode anymore. How to set that timerange then in current Grafana versions?

**Comment by talitha77** [comment]
I'm a bit late to the party but if I'm right this is a request to create a single panel with multiple timeshifted metrics on it.. i am measuring mwh with
SELECT INTEGRAL("value")/3600 FROM "channels" WHERE ("topic" = 'channels/read/Power/Bus/Output/P') AND $timefilter which gives me the consumption over a 24 hour period. I would like to get say a week or a months worth of these values timeshifted back. Is that possible??  something like SELECT INTEGRAL("value")/3600 FROM "channels" WHERE ("topic" = 'channels/read/Power/Bus/Output/P') AND time = now() - 24h
thanks
JP

**Comment by haverdude** [comment]
I too have a time period issue that is similar to what other people have previously posted.

I have two graphs of the _same data_.  I want the top graph to be very flexible (relative / absolute time ranges, zoom, etc.), and the graph under it to _always_ display the last 12h _completely independent_ of what the dashboard time picker is set to or whether I have zoomed in on the graph above it.  

Is this even remotely on the radar?

**Comment by MichaelTendoSsemwanga** [comment]
Please reopen. TIme shift solution does not pick allow dynamically setting time range from query data

**Comment by MaxDiOrio** [comment]
There needs to be an option to set specific time range per panel.  For example, the CloudWatch Billing dashboard.  There is absolutely no way to use a query to define the max per month over the entire range of 12 months.  So I would need to create individual panels per month and specify the time range per panel.

It's impossible to do this currently.
