### ISSUE TITLE
$__range uses dashboard range, not overwritten panel range

### ISSUE THREAD

**Issue by patrick246** [grafana/grafana#17102]
**What happened**: Dashboard is set to Last 6 hours, panel is set to This month so far (now/M). The `$__range` variable is used in a Prometheus query. Start and end parameters are correct, however, `$__range` evaluates to 6h.

**What you expected to happen**: `$__range` should evaluate to the overridden range

**How to reproduce it (as minimally and precisely as possible)**: Setup a new dashboard, add a new panel, override relative time and use `$__range` in the query. Then use the query inspector to view the replacement for `$__range`

**Anything else we need to know?**: Grafana is running in Docker

**Environment**:
- Grafana version: Grafana v6.1.6 (commit: cf9cb45)
- Data source type & version: Prometheus, Version 2.9.1
- OS Grafana is installed on: Linux *** 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux as Docker host, Linux bef47d8138a2 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 GNU/Linux in Docker container
- User OS & Browser: OS: Linux *** 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux, Browser: 
- Grafana plugins:
  - Alert List
  - Azure Monitor
  - Carpet plot
  - CloudWatch
  - Dashboard list
  - Discrete
  - Elasticsearch
  - Gauge
  - Getting Started
  - Graph
  - Graphite
  - Heatmap
  - InfluxDB
  - Loki
  - Microsoft SQL Server
  - MySQL
  - OpenTSDB
  - Plugin list
  - PostgreSQL
  - Prometheus
  - Singlestat
  - Stackdriver
  - Sun and Moon
  - Table
  - TestData DB
  - Text
- Others: Running in Docker (Image f96bf1723e2a)

**Comment by torkelo** [comment]
So if anyone wants to start on this, setup a prometheus data source and issue a query using $__range in a range vector. Use Query inspector to see what it get's interpolated to. 

Below the queries specify a panel relative time override. This changes the panel time range 
and it should affect the $__range variable. 

The reason it does not is that this code:
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/datasource.ts#L369 

uses timeSrv.timeRange() instead of taking in the time range as function arg (the query method gets a time range), pass the query time range to this function and use that.

**Comment by patrick246** [comment]
What are the next steps on this issue?
