### ISSUE TITLE
Filter metrics on namespace prefix

### ISSUE THREAD

**Issue by ronmb** [grafana/grafana#1713]
I was wondering if there was a way to filter or allow only a set of metrics to be made available in the drop down selection of the select metric input? 

I currently have a graphite instance that is shared by multiple small groups. These groups share a top level folder namespace but have their own folder namespace 
For example:
production.application.group1.*
production.application.group2.*

I'd need to be able to spin up distinct instances of the grafana dashboard for each group due to various reasons such as access control, confidentiality, etc.  When I spin up an instance I'd like to be able to provide a namespace prefix that allows them to only see their group's metrics. Is this remotely possible? 

I was looking through the code and the only location that i can see inserting a filter is in the loadMetricsRecursive function. My JS skills are rusty so I could be completely off base here.

**Comment by torkelo** [comment]
For this to be completly secure it would have to be handled by Graphite, otherwise it would be easy to work around the restriction with query likes `production.application.*.*.stats.count`. 

Sure Grafana could have specific proxy feature for graphite api /metric/find that would filter metrics, but would only be for easy of use (reduce options), it would not limit users from querying metrics from the complete graphite metrics space.
