### ISSUE TITLE
scrollbar in graph legend

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#17147]
In the master, I am now seeing a scrollbar on the legend:
![image](https://user-images.githubusercontent.com/705951/57961007-033f1d80-78c1-11e9-9775-220d47cc25d3.png)

This is in: Chrome 74.0.3729.157 (Official Build) (64-bit) on Windows 10 Enterprise 2016 LTSB

On my mac & windows laptops it does not have the scrollbar

**Comment by torkelo** [comment]
Strange, unable to replicate this

**Comment by torkelo** [comment]
Do you still get this? Closing this until we have more reports.

**Comment by alexandrul** [comment]
Same issue: Grafana 6.2.0 / 6.2.1 + Chrome 74.0.3729.169 + Win 7 x64 (even in Chrome's Incognito mode).

No scrollbars visible under Firefox 67.

**Comment by torkelo** [comment]
Any browser zoom enabled ?

**Comment by alexandrul** [comment]
@torkelo I am so sorry for not checking this earlier, in my case Chrome was at 90% zoom.

**Comment by svet-b** [comment]
On 6.1.4 and 6.2.2 we've been seeing vertical and/or horizontal scroll bars on chart legends in Chrome.

As above, though, this appears to be related to some combination of screen resolution and zoom level. On a 1440x900 screen scrollbars appears at 90% zoom (but not at other zoom levels). On a 1920x1080 they appear at a zoom level of 50% only.

Not sure what other info would be helpful in order to troubleshoot further?

**Comment by dprittie** [comment]
I am seeing this too, using Grafana 6.2.5 and Chrome 73.0.3683.75, screen resolution is 3840 x 2160

When zoom is at 100% the dashboard looks fine (no scrollbars). When zooming out to 90% I see some panels with horizontal scrollbars, some with vertical, and some with both. Zooming out further incrementally yields different results, some panels lose the scrollbar(s), some switch from horizontal to vertical.

Happy to provide more info if it will help diagnose this issue.

**Comment by torkelo** [comment]
think we can close this as it seems to only show in some edge cases when using browser zoom
