### ISSUE TITLE
AuthProxy: Does not respect `[auth.proxy].auto_sign_up`

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#17266]
Seems like a mistake during refactoring

https://github.com/grafana/grafana/pull/16950/files#diff-dc90ed542fb29715788afbc5a913c52cR269

**Comment by marefr** [comment]
This is how it looks in 6.2.x: https://github.com/grafana/grafana/blob/v6.2.x/pkg/middleware/auth_proxy/auth_proxy.go#L276

Not sure this is needed in 6.2.1 milestone

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/blob/master/pkg/middleware/auth_proxy/auth_proxy.go#L261

**Comment by papagian** [comment]
It seems that a [new option](https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L398) dedicated for LDAP has been introduced that it is [used](https://github.com/grafana/grafana/blob/master/pkg/middleware/auth_proxy/auth_proxy.go#L215) instead.

**Comment by marefr** [comment]
@papagian There's still a setting for `[auth.proxy]` named `auto_sign_up`, see [here](https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L389) and [here](https://github.com/grafana/grafana/blob/v6.2.x/pkg/setting/setting.go#L829).

That setting should probably be used [here](https://github.com/grafana/grafana/blob/master/pkg/middleware/auth_proxy/auth_proxy.go#L261) instead of `true`.

**Comment by papagian** [comment]
my mistake, I was checking wrong `UpsertUserCommand` call
