### ISSUE TITLE
Option to make description visible in TV/kiosk mode

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#17332]
**What would you like to be added**:
Option to make a description of a panel ("i" icon) visible in TV and kiosk mode.

This is how it looks now:
Normal mode:
![1](https://user-images.githubusercontent.com/19311511/58497012-4def4e00-817b-11e9-9da0-0db4aa2e7eeb.jpg)

TV/kiosk mode:
![2](https://user-images.githubusercontent.com/19311511/58497093-78410b80-817b-11e9-874a-bcf436da692b.jpg)

**Why is this needed**:
I would like to hide left and top bar (as it is in the TV mode) but keep the descriptions of the panels visible.

**Comment by torkelo** [comment]
TV / Kiosk modes are for showing dashboards on TVs in non-interactive way, which is why the interaction elements (menu carets, resize, buttons etc) are not visible. If you want a description to visible always you can add a text panel. A possible feature (think there is an issue for) is to have a description footer always be visible.
