### ISSUE TITLE
How to add datasource in Grafana2

### ISSUE THREAD

**Issue by gobwas** [grafana/grafana#1736]
Hello!

Just built grafana2 via go on MacOS.
`grafana web` is running, but I cant catch out - where can I add datasource to my InfluxDB?

Thanks.

**Comment by torkelo** [comment]
in the sidemenu, click on Data Sources. Sidemenu is opened by clicking on the grafana icon in the top right of the top header.

**Comment by gobwas** [comment]
Is it hidden? )

http://cl.ly/image/1b2j0q223D1z

**Comment by torkelo** [comment]
It should look like this: 
![image](https://cloud.githubusercontent.com/assets/10999/7064879/7322ba9c-deb2-11e4-9047-732160a9e45c.png)

The user you are logged in as "gobwas", how was it created? The only reason that the Data sources sidemenu option is hidden is because your gobwas user is not Admin for the "Main Org." organization

**Comment by gobwas** [comment]
Got this. Sorry!

Can you add some info in Docs about admin/admin login/password, to clarify this potential problem? 

Anyway, thanks a lot for the great job!
