### ISSUE TITLE
Panel plugins with skipDataQuery should still get properties refreshed

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#17361]
when skipDataQuery=true, changes to the time and refresh are not getting passed to the panel

**Comment by nmoreaud** [comment]
Same problem here. (grafana 6.6)
However, this is maybe because I am badly using Grafana.
I created an APP plugin with a PANEL that embeds its own datasource config.
I would like to hide the datesource tab, and use a datasource programmatically.

Idealy, I could provide the panel with a datasource using grafana toolkit in a regular way, however I didn't find the right API to do that. So I'm stuck for now using some custom data retrieving method + showing a dummy datasource that returns data I that don't want to use...

**Comment by nmoreaud** [comment]
Please, how can I hide the datasource from GUI while receiving the "refresh" signal (and optionally the time range) ?

**Comment by nmoreaud** [comment]
up

**Comment by mckn** [comment]
I can't reproduce this in Grafana 7 and above so I will close this issue. Please let me know if it should be reopen and in that case also provide some reproduction steps.
