### ISSUE TITLE
live option on grafana not showing every single log

### ISSUE THREAD

**Issue by nkristianto** [grafana/grafana#17378]
**What happened**: 
send log to loki every second and show log from grafana dashboard with live tail option, but grafana explorer dashboard not show every second log 

**What you expected to happen**:
every selected live tail option, grafana dashboard will show every single log sent from app

**How to reproduce it (as minimally and precisely as possible)**:

1. Started loki, promtail, and grafana using docker-compose.yaml that provided on the README file
2. Send log to loki url with the app
```
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/afiskon/promtail-client/promtail"
)

const (
	source_name = "test_application"
)

func main() {
	quitChan := make(chan os.Signal, 1)
	signal.Notify(quitChan, syscall.SIGINT, syscall.SIGUSR1, syscall.SIGUSR2)

	labels := fmt.Sprintf(`{source="%s", job="log", job_name="run_log"}`, source_name)
	conf := promtail.ClientConfig{
		PushURL:            "http://localhost:3100/api/prom/push",
		Labels:             labels,
		BatchWait:          1 * time.Second,
		BatchEntriesNumber: 1000,
		SendLevel:          promtail.INFO,
		PrintLevel:         promtail.INFO,
	}

	loki, err := promtail.NewClientJson(conf)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	for {
		select {
		case <-quitChan:
			loki.Warnf("caught terminating signal")
			os.Exit(1)
		case <-time.After(1 * time.Second):
			tstamp := time.Now().String()
			loki.Infof("source = %s, time = %s\n", source_name, tstamp)
		}
	}
}

```
**Anything else we need to know?**:

**Environment**:
- Grafana version: latest 
- Data source type & version: loki, latest version
- OS Grafana is installed on: Mac OS
- User OS & Browser: Google Chrome Version 74.0.3729.169 
- Grafana plugins: Loki
- Others: 

log at grafana dashboard:
https://user-images.githubusercontent.com/4598339/58580960-8de82b00-8278-11e9-87fe-5bc39402e295.png

**Comment by hugohaggmark** [comment]
I've done some initial investigations:

1. We have a "back pressure" situation, that means that the producer (in this case Loki) sometimes sends more messages then it's possible to render in the FrontEnd without making the whole browser irresponsible. Therefore I just added a very crude epic limitMessageRateEpic that introduces throttling per result sent through the websockets here: 
https://github.com/grafana/grafana/blob/0b9de3f7617711c8ec86cf137fddd4380fe0dd63/public/app/features/explore/state/epics/limitMessageRateEpic.ts#L12

This implementation unfortunately leads to not all log rows being shown.

2. The second challenge is if you for instance start live tailing for a query like `{cluster="xyz"}` you would not only get the "back pressure" situation because of the amount of data pushed through the websockets but you will also have a lot of streams in the result. So that means for every result pushed through the websockets you will have xx new rows (1 row per stream) to render. So I've seen 100 results/ms * 76 rows pushed through the websocket and we also need to handle the case when we only have 1 result/s * 76 rows and so forth.

So this is the complete challenge as far as I know. There are lossless and lossy approaches for solving this problem but I haven't developed anything yet so this is free for anyone to come up with solution.

**Comment by aocenas** [comment]
Some notes to this:
- fixing the perf issue with showing lots of log lines per time is one thing but there is also a usability problem in that case.
- right now you cannot pause live tailing and scrolling up won't give you persistent position over the log window (position is reset to bottom each time new log arrives). This makes showing just blinking wall of lines in high speed not that useful.

research:
- was looking at how kibana handles it. Their live tailing is just a 5s timer that scrolls to the current time, triggering a lazy load of 200 logs before and after current position. So this would also create gaps (if logs > 200/5s) but due to them lazy loading logs as you scroll, I assume that is not a big deal for them.

possible solution:
- change throttling to buffering to prevent freezing the browser (this will also overflow at some point but then we can throw away and log some warning that we are doing so, need to be tested what the limits are). Pause streaming when scrolling so the position is stable. Adding a resume button and/or resume streaming when scrolling to the bottom.

**Comment by ryantxu** [comment]
Note this is solved in the panelQueryState -- all messages are processed but updates to the panel are throttled

**Comment by aocenas** [comment]
At this moment this should be fixed by https://github.com/grafana/grafana/pull/18804 and https://github.com/grafana/grafana/pull/18836. There are some additional work to make the improve the performance like https://github.com/grafana/grafana/pull/18709.
