### ISSUE TITLE
Table panel annotations don't show directly

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#17382]
As far as I understand the way to display annotations in a table in Grafana, is to:
* add a new table panel
* go to viz options, and under transform select "annotations"
* it won't show any data just yet, but when you save the dashboard and reload it, the annotations will show.

I have several problems with this:

* the fact that you have to select "transform: annotations" is rather unintuitive, people would be looking for a datasource or query wherein which they can select annotations, they're not thinking about annotations. 
* why does it show metric query editors, this doesn't apply
* why is there no way to select what annotations query to use (e.g. text search, tag search)
* why does it show an alerting tab? this doesn't seem to apply to annotations?
* data only shows after save and reload

SolutionUpdate:

To fix this we need to check if we are switching to annotations transform:
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/table/editor.ts#L76

instead of render we should call this.panelCtrl.refresh() (only when transform changes to annotations)

**Comment by Dieterbe** [comment]
Furthermore, the timestamps are poorly rendered, and ditto for the tags. let's render them the same way we render them in annotation popups in charts? (in colored thingies)
![annotations-table](https://user-images.githubusercontent.com/20774/58687624-d6900900-838a-11e9-8ef7-b8f4ee038cbf.png)

**Comment by torkelo** [comment]
Thanks for the feedback dieter. Agree that the table annotation feature is a bit confusing. 

> the fact that you have to select "transform: annotations" is rather unintuitive, people would be looking for a datasource or query wherein which they can select annotations, they're not thinking about annotations.

This feature is to show dashboard wide annotations. It's confusing that this is part of the transform option I agree. But has to be a table option. 

> why does it show metric query editors, this doesn't apply

Because of this a table option, the table can either take data from the global dashboard annotations. or a query. The table panel cannot disable the queries tab just because an option is selected. 

> why is there no way to select what annotations query to use (e.g. text search, tag search)

You can do that in the dashboard annotation settings (Dashboard  settings / annotations / edit) you can define tag filters. This feature is designed to show annotations also visible in other Graph panels so would be confusing if the annotation table showed different annotations.  

> why does it show an alerting tab? this doesn't seem to apply to annotations?

Alerting tab? Can't see an alerting tab when I use the table panel. 

<img width="484" alt="Screen Shot 2019-05-31 at 09 53 26" src="https://user-images.githubusercontent.com/10999/58690542-16a2bc00-838a-11e9-8dcd-82d5c0a991bc.png">

> data only shows after save and reload

That sounds like a bug. Needs investigating!

**Comment by Dieterbe** [comment]
> Alerting tab? Can't see an alerting tab when I use the table panel.

my mistake. there's no alerting section

**Comment by Dieterbe** [comment]
> This feature is designed to show annotations also visible in other Graph panels so would be confusing if the annotation table showed different annotations.

i think both modes make sense. i have a use for different tables showing different sets of annotations. it reminds me of panels that have custom time ranges.

**Comment by torkelo** [comment]
To fix this we need to check if we are switching to annotations transform: 
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/table/editor.ts#L76 

instead of render we should call this.panelCtrl.refresh()   (only when transform changes to annotations)

**Comment by kaihendry** [comment]
Using the latest pulled grafana/grafana at time of writing **Grafana v6.4.4 (092e514)**, I only managed to show annotations via a tag: https://community.grafana.com/t/displaying-annotations-within-a-table-panel/6842/3?u=hendry

"Filter by Dashboard" doesn't work. Neither does an empty tag filter with "Match any".

My use case is to show all annotations across dashboards in a status page like https://status.aws.amazon.com/ _Recent Events_
