### ISSUE TITLE
Azure Monitor: change Datasource did not change workspace ID

### ISSUE THREAD

**Issue by silencev** [grafana/grafana#17417]
**What happened**:
When changing the data source, the Log Analytics workspace did not get changed.

**What you expected to happen**:
workspace ID get changed when data source is changed

**How to reproduce it (as minimally and precisely as possible)**:
1. create two Azure Monitor data sources
2. create a variable and select data source
3. create dashboard and have query to Log Analytics
4. change Data Source
5. see "request error" on the left-top corner

**Anything else we need to know?**:
![SQL_Performance_Issue_-_Grafana](https://user-images.githubusercontent.com/24366323/58850192-f93e5c80-86bf-11e9-858b-5c8932b9d6cb.png)

**Environment**:
- Grafana version: grafana cloud
- Data source type & version:  n/a
- OS Grafana is installed on: n/a
- User OS & Browser: firefox 67.0
- Grafana plugins: n/a
- Others:

**Comment by silencev** [comment]
May I know when it get fixed?
This bug is introduced after auto upgrade to v6.2
I'm using Grafana Cloud and cannot event downgrade the version.

**Comment by torkelo** [comment]
This is not really bug, if your query needs to change when change datasource the you cannot use the datasource variable features. It requires that the query remain identical and only the datasource change. Workspace is part of the query now so this makes this feature unusable without some new tricks

**Comment by jagilber** [comment]
@torkelo i am seeing some issues around this as well. i believe this is a bug. log analytics workspaces can be dropped and added using same name but guid will change. the only efficient way to remove data from log analytics is to delete the workspace so queries may or may not change with data source change. my scenario is i want to create template panels with queries for service fabric customers. the data structure/schema will be the same but each customer will have a different workspace id and queries will be the same. as @silencev says, last time i tested changing datasource, it nulled out all my queries workspace ids and broke all my panel queries. it didnt fallback to 'default' either. somewhat related, when saving as template, it is leaving the workspace id in the json meta as well which to me seems wrong as the guid is sensitive information. since name for log analytics has to be unique, could that be used instead of guid? (name is used when setting 'default' workspace in azure monitor settings. that way at least if workspace is recreated with same name it will not break the panels? being in support, i may drop a workspace multiple times a day for different case works. having to reset the panels workspace id's is very tedious. i looked at code briefly and it appeared it was hardcoded to array[0] instead of instance default workspace.

**Comment by silencev** [comment]
@torkelo 
yes, the query is identical to multiple Data sources.
you may reproduce by this query:
```
Usage
| where $__timeFilter(TimeGenerated)
| summarize sum(Quantity) by DataType, bin(TimeGenerated, 1h)
| order by DataType asc
```

**Comment by joshhunt** [comment]
As Torkel said, this is not really a bug, just a limitation of how queries and template variables work. Making the data source a template variable will not change any of the other properties of a query.

To achieve what you're after you would also need to use a template variable for the Workspace/Resource field, which uses your data source template variable. See documentation for more details on what Azure Monitor template variable queries are available https://grafana.com/docs/grafana/latest/datasources/azuremonitor/template-variables/

Note, there may be limitations with template variables and Azure Monitor that make this a bit tricky or confusing to do, so your mileage may vary. Definitely interested in hearing back with how you go on this!
