### ISSUE TITLE
Elasticsearch: Default max_concurrent_shard_requests of 5 not applied for version 7.0+

### ISSUE THREAD

**Issue by holiiveira** [grafana/grafana#17454]
**What happened**:

If the query returns more than 5 buckets, the alert returns: `No Series (reduced to null / no value)`
If it returns 5 or less, it works fine.

**What you expected to happen**:

Alert will be processed when the query returns more than 5 buckets.

**How to reproduce it (as minimally and precisely as possible)**:

Make a query that returns more than 5 buckets and set an alert to see returning null / no value.

**Environment**:
- Grafana v6.2.2 (commit: 07540df)
- Elasticsearch 7.0.0
- Server: Ubuntu 18.04 LTS
- Client: Windows Server 2016 - Google Chrome 74.0.3729.169

![test](https://user-images.githubusercontent.com/4368491/58962183-0a9b6d80-8781-11e9-868f-a819715221b3.gif)

**Comment by marefr** [comment]
@holiiveira thanks for the animated image. However I have some difficulty understanding what's going on (it's quite fast). Could you include a detailed description of how to reproduce and include some of the raw data and the query you're using.

Looks a bit weird that you have override relative time in panel, however when the alert rule are executed the override time is not applied. But you should be aware that you may be looking at different results in graph vs test alert rule.

I also see that you have a `$interval` variable defined in the min time interval field, what value does that have? When executing the alert rule the min time interval cannot be a custom variable so that may be your issue. Either add static min time interval to datasource config or panel config (no variable) or either change the date historigram from auto to a fixed interval like 1m.

**Comment by holiiveira** [comment]
@marefr thanks for the feedback.

The panel I am mounting is only for alerting.
I have an audit process that in a 12h interval updates me the status of the processes, or when a process is changed (start, stop).

The idea is that the alert, see the last value for the series, in an interval of 12h. (last,) query (A, 12h, now)

Using the data sample below, I set up a panel:

![01](https://user-images.githubusercontent.com/4368491/59612348-4cb69e80-90f3-11e9-9602-8ad75d287b90.PNG)

And the alert:

![02](https://user-images.githubusercontent.com/4368491/59612413-6b1c9a00-90f3-11e9-9b0b-c5529f2508e1.PNG)

In this configuration, I only get results in the alert if the group by size is set to <= 5.

Panel Json: https://gist.github.com/holiiveira/98e41a7f11e7bba6df79ecaa9ca875f0
Sample data, csv (Elasticsearch): https://gist.github.com/holiiveira/2516c6c1b4d831f79f47187a463f8e2c

**Comment by holiiveira** [comment]
@marefr I believe the problem is because of the `max_concurrent_shard_requests` parameter.

Log:
`lvl=dbug msg="Executing request" logger=tsdb.elasticsearch.client url="http://localhost:9200/_msearch?max_concurrent_shard_requests=5" method=POST`

Datasource:
![datasource](https://user-images.githubusercontent.com/4368491/60107757-d262cb80-973d-11e9-8011-6aaa27835ecc.PNG)

Regardless of the value that I put in the datasource, the alert log always shows 5.

By [default](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html) the value is 5.

**Comment by marefr** [comment]
@holiiveira yes you're right, the default is 5 and we have [code](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/config_ctrl.ts#L11) that should set it to 5 if you select version 7.0+, but doesn't seem to work as expected. 

Will update this issue to reflect this and label as bug. Thanks

**Comment by marefr** [comment]
Fixing this should also add note in upgrading docs for v6.2 [here](https://grafana.com/docs/installation/upgrading/#upgrading-to-v6-2) and marked as a breaking change in v6.2 changelog.
