### ISSUE TITLE
Browser becomes unresponsive while trying to load data more than 30 days 

### ISSUE THREAD

**Issue by kamalakarv** [grafana/grafana#1747]
Grafana version : 1.9.1
Browser : Firefox 37 ( ubuntu 12.0.4)

Recently I have setuped grafana for the project I am working on.
I observe that browser hangs when try to open graph for more than 30 days range.
Please find the screenshot attached for reference.

![grafana_1_9_1_cpu_issue](https://cloud.githubusercontent.com/assets/335352/7083091/2d8be412-df7b-11e4-9a33-bd19ad18cf9c.jpg)

**Comment by torkelo** [comment]
What data source are you using? Graphite? 

The reason client side rendering for graphite has been severely crippled with slow performance and browser crashes for large timespans was solved last summer, via this issue #170 . The reason client side rendering was slow was not because client sider rendering was slow but because the graphite json api returned every datapoint to the browser (which could be many many megs of datapoints when viewing large time spans). The maxDataPoints feature make sure that the same consolidation that happens for the PNG rendering happen for the json rendering, that is that only points that are drawn in the graph are returned.

I have mentioned this multiple times, in grafana docs, (and old grafana github wiki), and in issues. http://grafana.org/docs/performance/

Grafana can render 10-15 graphs with "the last year" of data in about the same time as the PNG :)

All you need to get good performance is to upgrade graphite to the 0.9.x branch or the 0.9.13 release.
