### ISSUE TITLE
Feature Request: add hook functions to improve control on scripted dashboards

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#1761]
As commented in https://github.com/grafana/grafana/issues/1672. Could be interesting to add some basic hook functions to  most important viewer user interactions.

As an example:
- on_dboard_change_variable(var_id, var_name, previous_value,new_value)
- on_dboard_end()
- on_dboard_init()
- on_dboard_before_refresh()
- on_dboard_after_refresh()
- on_dboard_time_windows_change()
- on_dboard_zoom(old_init_time,old_time_range,new_init_time, old_time_range)
- on_dboard_hotkey(key)

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.

a reinvention of scripted dashboards is on our radar, maybe using something like http://jsonnet.org/
