### ISSUE TITLE
Use a single annotation entry to represent a region

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#17647]
Annotations currently support regions by having two entries: on for the start, one for the end and then linking them with a regionId.

This structure is complicated and leads to some weird behavior.

Can we just add another field `EndTime` (or `EpochEnd`?) to the annotation and table?  The default value would be EndTime === Epoch

The query would need to change from:
```
sql.WriteString(` AND annotation.epoch BETWEEN ? AND ?`)
```
to something like:
```
AND ( ( annotation.epoch    BETWEEN ? AND ? ) 
  OR  ( annotation.epochEnd BETWEEN ? AND ? ) )
```

We would need a migration that:
1. adds the column with the same value as epoch
2. copies over all matching regions to the epochEnd
3. removes the regionId column and all the end versions

**Comment by kylebrandt** [comment]
Not familiar with it, but that sounds like a simpler schema to me. 

Assuming the two parms, `?`, `?` are search for a window of `start` and `end` respectively - that includes ones that are on either side of the window.... I think the logic can be reduced to `epochEnd >= start AND epoch <= end`

**Comment by marefr** [comment]
This would probably be the most optimal and performant solution, but I may missing something important here of why the current solution was selected or the region was an afterthought. Maybe due to supporting (region) annotations from any datasource?

@torkelo any history to bring in for this discussion?

**Comment by marefr** [comment]
Possible solution for #15764

**Comment by DanCech** [comment]
If you set `epochEnd` equal to `epoch` for annotations with no duration then you can find all annotations that "cover" a given period with `WHERE epoch < [end] AND epochEnd > [start]`.  I agree that this approach is much more elegant than trying to connect the dots between a separate start and end record.

**Comment by ryantxu** [comment]
> WHERE epoch < [end] AND epochEnd > [start]

That looks better, but would only show the ones that are completely within the window.  It would miss things that start or end outside the window.

Both queries (and the current implementation) will miss events that cover the entire span.  I think that is a fine tradeoff for now.

The real question is if there is a good reason for the multiple entries -- and if there was a good reason does it still exist?

**Comment by torkelo** [comment]
Can't remember exactly the reasons (It was my doing). Think it might have been to keep the annotation table structure & query as simple as possible but adds complexity elsewhere so I agree it looks best to change it so that a single annotation event can represent a region. 

We would need migration to merge them, but should be doable.

**Comment by marefr** [comment]
@torkelo can it have been related to supporting annotations from plugin datasources, like graphite?

**Comment by torkelo** [comment]
No regions where only supported by the internal Grafana datasource
