### ISSUE TITLE
ADFS OAuth2 code parameter is invalid error

### ISSUE THREAD

**Issue by MaxDiOrio** [grafana/grafana#17672]
**What happened**:
Unable to login when using ADFS 4.0 (Server 2016) and the Generic OAuth config

Receive the following in the Grafana event log:

t=2019-06-19T16:52:44-0400 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=307 remote_addr=10.85.144.43 time_ms=1 size=56 referer=
t=2019-06-19T16:52:44-0400 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=302 remote_addr=10.85.144.43 time_ms=0 size=334 referer=
t=2019-06-19T16:52:44-0400 lvl=info msg="state check" logger=oauth queryState=77d69f4df4f371c0c072b99933c5d14eab0d02d5a7edf1499ed41ee7b32201b3 cookieState=77d69f4df4f371c0c072b99933c5d14eab0d02d5a7edf1499ed41ee7b32201b3
t=2019-06-19T16:52:44-0400 lvl=eror msg=login.OAuthLogin(NewTransportWithCode) logger=context userId=0 orgId=0 uname= error="oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"MSIS9612: The authorization code received in \\u0027code\\u0027 parameter is invalid. \"}"
t=2019-06-19T16:52:44-0400 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=500 remote_addr=10.85.144.43 time_ms=22 size=1743 referer=

**What you expected to happen**:
Log in

[auth.generic_oauth]
enabled = true
name = ADFS
allow_sign_up = true
client_id = 9216db88-f3ad-4d8f-9c03-xxxxxxxxxxxxxxx
client_secret = kjST4V9nuwfxcYDO58z4Exxxxxxxxxxxxxxxxxxxx
scopes = openid
auth_url = https://adfs.domain.com/adfs/oauth2/authorize
token_url = https://adfs.domain.com/adfs/oauth2/token
api_url = https://adfs.domain.com/adfs/userinfo

ADFS Config - Application group
Created server application:
Redirect URI:  https://grafana.internal.domain.com/login/generic_oauth
Copied the client_id and client_secret into the config above.

Have a Web API with:
Relaying Party Identifier:  https://grafana.internal.domain.com/login/generic_oauth
Access Control Policy:  Permit Everyone
No Transform Rules
Permitted Scopes:  email, opened, profile

**Environment**:
- Grafana version:  6.2.2

**Comment by aocenas** [comment]
Hey @MaxDiOrio based on the error from the logs `MSIS9612: The authorization code received in \u0027code\u0027 parameter is invalid.` it seems like the code sent did not match the one we got in the redirect. Looking at the code though there does not seem to be much going on with the `code` parameter that could end in some error. I do not have a setup to test this right now but it would help a lot if you could check if the `code` really is correct:
- After authorisation in the ADFS you should be redirected to grafana url, in that url there should be `code` parameter in the query.
- Grafana should then do a request to ADFS that contains the same code (this needs some proxy though or something to log the request from grafana).

If the code is the same, it would seem the issue is somewhere on the ADFS side (and the error message does not make much sense), if they are different it is bug on our side. I will try to look into it but could take some time to do that.

**Comment by aocenas** [comment]
There are also some resources that could be of use, please let me know if any of them helped.
https://community.grafana.com/t/active-directory-single-sign-on/5433
https://stackoverflow.com/questions/45841537/how-to-configure-grafana-with-oauth-private-adfs

This docs should be also relevant for ADFS:
https://grafana.com/docs/auth/generic-oauth/#set-up-oauth2-with-azure-active-directory

Also it could be possible that the issue is with samesite setting, try changing it to `none` whether that helps:
https://grafana.com/docs/installation/configuration/#cookie-samesite

**Comment by marefr** [comment]
@MaxDiOrio have you had the change to look into above resources and/or samesite setting?

**Comment by marefr** [comment]
Closing this due to lack of response. Will consider reopen if you provide us the information requested.
