### ISSUE TITLE
Y axis time display error

### ISSUE THREAD

**Issue by ICLXL** [grafana/grafana#17676]
![image](https://user-images.githubusercontent.com/30027321/59812734-94cb0080-9341-11e9-9803-d98e35dee02d.png)

**Comment by ICLXL** [comment]
grafana  version = 6.2.4

**Comment by aocenas** [comment]
Hey @ICLXL, I would say this works as intended even though could be a bit confusing. There are multiple units that jump to the higher unit if possible for display so that the displayed value stays short. So for example instead of `20s` you could have `20 000ms` which is getting a bit long or `20Kms` which does not make much sense as far as units go. So the unit setting for axis in general means what does value 1 stands for (ie here it is 1ms) not that all the values in the axis have to be formatted in the same unit.

**Comment by ICLXL** [comment]
Ok, I see. Thank you
