### ISSUE TITLE
Why are you POSTing to graphite /render?

### ISSUE THREAD

**Issue by bydga** [grafana/grafana#1767]
In the last grafana (1.9.x) you were calling graphite's /render method (with parameters like target, format=json, maxDataPoints etc..) with HTTP GET method. Now with v2 you switched to POST - however our graphite installations seems not to support this (accodring to our admins we have a graphite 0.9.12). Plus not even in the graphite render api docs, its never mentioned graphite should be POSTed - http://graphite.readthedocs.org/en/latest/render_api.html.  ```The graphite webapp provides a /render endpoint for generating graphs and retrieving raw data. This endpoint accepts various arguments via query string parameters. These parameters are separated by an ampersand (&)```

What do you think? Is your graphite working (i guess it is..) so what version do you run?

**Comment by torkelo** [comment]
@bydga Grafana has always used POST by default, there was a config option added in Grafana v1.5 so that some users could change it a GET call. 

Graphite has always supported POST for the render call simply because it allows for more queries and larger queries being batched in one render call (without hitting the querystring length limit). 

It is very strange that this is failing for you, maybe you have some proxy infront of graphite that does not allow POSTs? 

If you are running Graphite 0.9.12 you really need to upgrade to Graphite 0.9.13 to get the maxDataPoints parameter  (without that feature Grafana can be really slow when querying over long time ranges due to graphite returning megabytes worth of points)

**Comment by bydga** [comment]
Hi, thanks for the reply.

You are right, i was overriding the http method in the config.js and i completely forgot about it now (as i am evaluating an upgrade to grafana 2). Is there a simmilar option in the config.ini in grafana 2 (cant find anything in the docs and ?  We have some problems with running the POST /render requests against our graphite installation (no proxy in the way though...)

now i found outthat  out problem has maybe a connection with: https://github.com/grafana/grafana/issues/28

**Comment by torkelo** [comment]
no there is no option to use GET, its very strange that your graphite install does not handle it.

**Comment by bydga** [comment]
I guess the problem would be with the graphite 0.9.12. Definitely nothing you should be worried about.

**Comment by bydga** [comment]
So i got back to this issue and finally found the answer to "POST not working to graphite".. We had the gunicorn dependency installed through distro packages, where the gunicorn version was really outdated (something around 15.x). After reinstalling gunicorn via pip (upgraded to 19.3), everything started to work. This info might help someone in the future :)
