### ISSUE TITLE
Explore: Error when clicking log row after highlighting expression

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#17687]
**What happened**:
When clicking a log row after highlighting an expression, an error message is displayed: 'parse error at line 1, col 37: syntax error: unexpected IDENTIFIER, expecting STRING'

![Jun-20-2019 12-07-58](https://user-images.githubusercontent.com/45561153/59844978-1d529c80-9354-11e9-9fd7-5b29f35365ea.gif)

**What you expected to happen**:
Nothing

**How to reproduce it (as minimally and precisely as possible)**:
1. Go to Explore and choose the Loki datasource.
2. Enter `{filename="/var/log/docker.log"} |= time` into the query bar.
3. Click the first row in the log results.

**Environment**:
- Grafana version: Grafana v6.3.0-pre (commit: 6fd4aa4b4)
- Data source type & version: loki:master
- OS Grafana is installed on: macOS
- User OS & Browser: macOS, Firefox 67.0.2

**Comment by davkal** [comment]
Here is what's happening: 

- the first results were loaded fine because selecting a label from the dropdown produced a valid query
- the query `{...} |= time` is invalid but was only executed once you clicked outside the query field (blur event)

From a UX point of view, this makes it annoying and surprising. Your action of interacting with row seem to "have caused" the issue, but it was only a side effect.

Blur events are problematic for Explore because they can trigger potentially expensive queries by mistake. My suggestion is to get rid of them, but we use them widely in the dashboard editors (which have no run buttons). 

The proper way forward would be to be consistent within each area: run-on-blur in dashboards, no run-on-blur in Explore.

**Comment by davkal** [comment]
Just realized that the match preview already highlighted `time` wrongly. It should not have, because the query is invalid. We should fix that before fixing the UX issue.

**Comment by kaydelaney** [comment]
> Just realized that the match preview already highlighted `time` wrongly. It should not have, because the query is invalid. We should fix that before fixing the UX issue.

Since the highlight updates as the user types, and since the syntax is going to be invalid as the user is typing in many cases, what is the expected behavior? Should an error be reported as the user is typing or should it just not do anything? Thanks

**Comment by davkal** [comment]
It should do no highlighting while the filter expression of the query is not valid.

Perhaps invalid syntax still can sneak through here: 
https://github.com/grafana/grafana/blob/57dadebbd8228ac451ea5c0bfb948ce891c9c131/public/app/plugins/datasource/loki/query_utils.ts#L37

Other than that, results added in that same function might still fail to form a regular expression used by the highlighter, but that's fine and in our favor since they are invalid:
https://github.com/grafana/grafana/blob/57dadebbd8228ac451ea5c0bfb948ce891c9c131/public/app/core/utils/text.ts#L8

**Comment by marefr** [comment]
My two cents even though i totally get that it's a nice feature getting highlight feedback directly when typing, but from datasource agnostic perspective I think that we can simplify explore and query fields by removing the highlight on typing and keep only the highlight  after the query response returns.

Thoughts?

**Comment by torkelo** [comment]
I am also a bit doubtful that the highlight as you type is all that useful , I have found it confusing as it tricks you into thinking it has executed a new query and your seeing the results

**Comment by dehrax** [comment]
I'll let @kaydelaney handle this because of the change in priority.

**Comment by marefr** [comment]
Think we need to discuss how to move this forward with @davkal when he's back next week.

**Comment by marefr** [comment]
There's been some discussions here whether we should support highlight as we type. The important thing is to fix the bug, i.e. that highlighting is not done when an invalid query have been entered.

I'll create a new issue regarding whether we should support highlighting as you type and/or make this feature more useful/user friendly since now you may not understand that query haven't been executed and/or log messages are only highlighted that are out of view.
