### ISSUE TITLE
Enable toggling single series on mobile

### ISSUE THREAD

**Issue by ITBeee** [grafana/grafana#17697]
**What would you like to be added**:
Simple On / Off option to toggle a series in a graph on a mobile phone.
I think a simple "strikethrough" like view would make more sense then this CTRL+MouseButton configuration which is not really intuitive.

**Why is this needed**:
On a PC i'm able to select a series with CTLR + MouseButton but i don't have this option on a mobile device. I have a graph with 3 series and can only show one or all of them on a mobile device like a phone or a tablet.

**Comment by BenProb** [comment]
@torkelo I move our discussion out of the pr into this issue to share it with other users.
You say "most intuitive as it behaves the same as file lists on windows, mac, linux"
But you can't compare a file list with the graph legend:
1. A file list e.g. in Windows Explorer is the main element in the app. In grafana the legend series selection is only a subelement to filter/select the visible items in the main view (the graph).
2. In file lists the start view is that none list item is selected. In grafana all items are preselected.
3. In file list the second click on the same element doesn't change the selection. In grafana change the selection from one element to all. This is not intuitive and very confusing.
4. In grafana with 3 series A, B and C: Select A+B with cmd+click. Then click B and select only B. After click a second time on B, every element A+B+C is selected. But the expected behavior is the previous selection A+B. This is also confusing.

Conclusion:
The current behavior is not intuitive and not the same as file lists.

What do you think about changing the default behavior to single click selections with checkboxes:
```
[ x ] A              [ x ] A              [ x ] A
[ x ] B -- click --> [   ] B -- click --> [ x ] B
[ x ] C              [ x ] C              [ x ] C
```

**Comment by torkelo** [comment]
It's a good suggestion, Grafana used to have the opposite behavior, many complained about making it really hard to isolate and view a single series in a busy graph (the most common action based on the feedback back them, this was about 3 years ago) 

Do not want to complicate the legend with checkboxes. It's tricky not sure what the right behavior and solution is

**Comment by BenProb** [comment]
> Do not want to complicate the legend with checkboxes

Checkboxes makes it not complicate. Contrariwise them make it easy to see which series are active and which not. Currently the difference is only normal to bold text!

> isolate and view a single series in a busy graph

Perhaps we could add gesture to do this:
Normal click --> toggle only clicked series on/off (other untouched)
CTRL / SHIFT + click or long press or double click --> isolate clicked series (all other off)

> the most common action based on the feedback back them, this was about 3 years ago

How can we get feedback from other users to force a good decision? Have you a form thread or similar from the old feedback?

**Comment by netweaver1970** [comment]
Is there anything happening with this issue? No more people using Grafana on their mobile devices? I have the same issue, using grafana/+influxdb on my HomeAssistant and I run into the same impossibility to toggle on/off single series.  

Maybe make the single click  behavior depending on a -newly to be build- panel specifc config setting? Either on/off or isolate/all, depending what the usecase is for the panel designer for that specifc panel ....

That would make everyone happy, apart from the grafana developer, as he/she needs to put that extra panel depending logic in :D

One could even go a step further, make a default behaviour for the whole panel and allow a -per series- override in for the  behaviour. Convenience and flexibility in one go. But again more work. I would already be happy with the 1st solution, a per-panel config setting to determine the behaviour.

For sure binding a modifier (such as CTRL) to any event (keybordkey or click)  is very mobile unfriendly ...

**Comment by vguna** [comment]
Sad to see that mobile support is not so important as it seems. Especially on small screens you want to focus on certain series only and get the others out of the way to see something. Why not simply check if it's a mobile device and show an additional checkbox that represents the "modifier key" like Ctrl? "Multiple selection" or so. Sounds easy to me :).
