### ISSUE TITLE
QueryInspector: Support inspecting query without having to re-issue query with inspector open

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#17737]
Correct me if i'm wrong, but it used to be the case that if a query failed, there was an error icon, and you could click on it and see the error.
Now when there is a failure you must use the redesigned query inspector feature, which requires re-issuing the query. This is a bad experience because so often a query issue is intermittent, and redoing the query results in a different result.

**Comment by torkelo** [comment]
I agree that this is not the best experience. 

The problem is that we do not have access to the raw http request after the fact. 

@ryantxu Correct me if I am wrong but that is true even with the new PanelQueryRunner, we could show an inspect view with raw data but not the raw http query & http response like the query inspector do, for that we need to listen and intercept the http requests. 

Or is there a way we can do this?

**Comment by ryantxu** [comment]
In the case of an error, we can show the raw request/response -- however, if the query ran OK, I do not think we can/should hold on to the raw response for every request.

This means from the dashboard:
* on error: Can inspect without re-issue query
* when OK: need to re-issue query to inspect

**Comment by Dieterbe** [comment]
@ryantxu this has been fixed I think right?

**Comment by ryantxu** [comment]
Not really -- the QueryInspector is a different thing, It essentially attaches to the backendSrv and shows the last request.  In the panel inspector we just save the last result (but processed!) of a query and the raw req/result when there is an error
