### ISSUE TITLE
Time Picker Improvements 

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#17802]
We want improve the current time picker: 

Designs:
![image](https://user-images.githubusercontent.com/10999/70220025-2985b700-1746-11ea-9041-ddcbacb29298.png)

https://www.figma.com/file/gXypOQEb8yU21RzlxXy2QW/Time-picker?node-id=141%3A2978

Todo: 
- Start with removing the current Select component and instead use a custom dropdown area (highjack the current absolute dropdown) 
- Make the dropdown view contain two split areas, (left absolute range, right quick ranges)
- Small screen view (turn the two splits in to a stacked collapsed views)
- Show calendar on input focus
- Store previous time ranges in local storage and show recent ones below the from/to input

**Comment by torkelo** [comment]
yea, search would be nice. But really you like the old ugly messy 4 random columns better? I hated that so much for years. think this new one is 10x better for quick ranges. even finding the ones further down is quicker for me because I do not have a scan across 4 random columns to find the one I need.

**Comment by towolf** [comment]
Well, now you have to scroll down a lot.

But I have often sat next to people and told them "switch to 3 months" and it took them a long time ...

**Comment by Dieterbe** [comment]
the 1-dimensional list is very frustrating because it requires scrolling any time i want to see more than 24h of data. and it being a simple list means every single option is thrown under there, without any hierarchy, making it hard to find the option you want. you basically have to scan over the entire list

I think this is a serious UX regression 

￼Ideally the experience should be:
1) 1 click on the button upper right to expand the time picker
2) spot the option you want quickly
3) click on the desired option

to support item 2, it would be better to have an overview of the different options (like we had before),
but perhaps organized slightly differently into different categories of options. 

If this makes it into a release, i think it'll be a painful experience for users and they will complain.
even if you don't agree that the new version is worse, at the very least it's a significant change that conflicts with experienced user's muscle memory.

=> IMHO, re-instate previous version, and maybe tweak the organisation of items slightly.

**Comment by torkelo** [comment]
Thanks for your feedback, maybe we made the new design a bit to simple to optimize easy of use for new users & better for mobile. While making it a bit worse for power users who remember where all options are. 

IMO I always hated the 3 columns that had a pretty weak logic behind the structure so it took a while to find which column the time range you were looking for was. Was no logic that Last 24h was in one column while last 2 days you had to jump to another column. 

But reducing those 3 columns to a single list without any structure maybe is not the right solution. We will see, more experienced users will probably complain as well and if enough do we can try to mock up an improved design.

**Comment by gaofei1982** [comment]
I like 6.2.x timepicker.

**Comment by jkfm** [comment]
Has there been any progress in this ticket? I concur with the criticism. While I agree that the columns did not always make sense, I think that replacing a "bad" organization with no organization is not a step forward at all. 

What I especially don't like is that custom time ranges require more clicks now.

**Comment by pauly7300** [comment]
I too am in the camp of liking the legacy behavior however I trust you're making changes based on cumulative feedback from customers.  

I will add however that it was not at all clear that the (new) long list of time ranges was a scrollable list.  In fact, I don't recall if there are any other _scrollable drop lists_ like this anywhere else in the UI.  This may be the source of the biggest 'shock to users'.  Introducing a scrollable drop list paradigm into a product for the first time (assuming my previous comment is correct), may be a difficult pill to swallow.  There really is no visual indication that there is more there to see.  Yes, one can argue that it's a learnable behavior and that users will eventually get it, but I do wonder how many first time users will even discover that there is more to be seen.

The below is my view on my Mac in Chrome and Safari (the render the same).  However, Firefox wins here as it briefly exposes the scrollbar and then fades after 500-1000 ms or so.  I suspect that's specific to how the browser renders that widget.  But if you can force that in all browsers, that would go a long way...  (animated gif of Firefox behavior at bottom)

![image](https://user-images.githubusercontent.com/11494052/63278946-d3ac0280-c26d-11e9-8bac-7f4813a64b20.png)

![grafana_droplist](https://user-images.githubusercontent.com/11494052/63279776-3c47af00-c26f-11e9-83fc-2826e005b769.gif)

**Comment by flopp999** [comment]
I have some user that complain about the new Time Picker, myself don't care so much, I will learn the new, just give it some time.
Maybe a selection for each user could be good.

**Comment by torkelo** [comment]
I have also been a bit unhappy by the new design (and I decided on it), will try to figure out an improvement in a 6.4 or 6.5

**Comment by Silvester23** [comment]
I also preferred the old time picker. It may not have been perfect, but seeing all options at once without having to scroll was a big plus compared to the new one.

**Comment by jessover9000** [comment]
I iterated the design, taking your comments here and lots of Grafanista feedback into account. :) this is ready for implementation now 👍 https://www.figma.com/file/gXypOQEb8yU21RzlxXy2QW/Time-picker?node-id=141%3A2978

**Comment by mckn** [comment]
@dprokop @torkelo my plan is to structure it the following way. Please ping me if you see any way we can improve the structure.

Since we want to have the `AbsoluteTimeRanges` within the scrollable container I can't really see any other way of doing this then have that component render on two times, hidden/displayed, depending on the media query.

![Imgur](https://i.imgur.com/kfw3H9E.png)

**Comment by torkelo** [comment]
@mckn that looks great 👍
