### ISSUE TITLE
Is correct the scaled Bps format?

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#1788]
Should Bps scaled in 1024 instead of  as 1000 (https://github.com/grafana/grafana/blob/master/public/app/components/kbn.js#L380) ?

Thank you very much

**Comment by torkelo** [comment]
hm.. should bps also scale by 1024?

**Comment by torkelo** [comment]
The bit rate is quantified using the bits per second unit (symbol: "bit/s"), often in conjunction with an SI prefix such as "kilo" (1 kbit/s = 1000 bit/s), "mega" (1 Mbit/s = 1000 kbit/s), "giga" (1 Gbit/s = 1000 Mbit/s) or "tera" (1 Tbit/s = 1000 Gbit/s).[2] The non-standard abbreviation "bps" is often used to replace the standard symbol "bit/s", so that, for example, "1 Mbps" is used to mean one million bits per second.

**Comment by torkelo** [comment]
seems right to scale by 1000

**Comment by torkelo** [comment]
http://en.wikipedia.org/wiki/Bit_rate
