### ISSUE TITLE
Wrong Last seen time at user sessions (auth tokens)

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#17953]
The recently added table that shows user sessions at _Admin -> Edit User_ page shows confused _Last seen_ time for auth tokens where `seenAt` is `0` - `50 years ago`. That's just because `seen_at` in db is `0`, but maybe we should display that as `Never` or figure out why it's less than `created_at` (_Logged on_).

![Screenshot from 2019-07-05 10-50-44](https://user-images.githubusercontent.com/4932851/60707410-583bff00-9f14-11e9-9244-d74114c251f9.png)

**Comment by torkelo** [comment]
Looks like token s are created with SeenAt set to 0
https://github.com/grafana/grafana/blob/master/pkg/services/auth/auth_token.go#L77

And rotate also sets to 0
https://github.com/grafana/grafana/blob/master/pkg/services/auth/auth_token.go#L228

@marefr any ideas why?

**Comment by marefr** [comment]
@alexanderzobnin @torkelo it's implemented according to discourse so that `seenAt` is only set [here](https://github.com/grafana/grafana/blob/master/pkg/services/auth/auth_token.go#L159) when a user "uses" a token for the first time. It's related to the rotation logic.

What's missing here is handling in API if `seenAt` is 0 we should use `createdAt` instead. Fix needed here:
https://github.com/grafana/grafana/blob/master/pkg/api/user_token.go#L97
 
Discourse have this as well, see [code](https://github.com/discourse/discourse/blob/888e68a1637ca784a7bf51a6bbb524dcf7413b13/app/serializers/user_auth_token_serializer.rb#L17-L21).

**Comment by urbanze** [comment]
Hello, I have similar problem, but with user IP (no auth tokens).

https://community.grafana.com/t/wrong-user-ip-127-0-0-1/59689

Any one can help me to fix it? I want to see real IP and not 127.0.0.1
