### ISSUE TITLE
Not able to use variable in constant template variable 

### ISSUE THREAD

**Issue by vpanchal72** [grafana/grafana#18028]
Sir, 

I want to create one variable like StartTime = ($__from/1000.0)-$timediff
where $__from is the time parameter and $timediff is the quarry pameter value

is there any way to create this type of paramenter

I tried in constant varialble but it is not working 

 
![image](https://user-images.githubusercontent.com/52157263/60962217-667e8680-a32b-11e9-9179-f9000242c52d.png)

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
@vpanchal72 we don't support math in variables. What you can do though, instead of using custom variable, you can put the expression directly in your query and skip using the extra variable.

Btw, not sure if you are familiar with that or not, but we also have community site (http://community.grafana.com) where you can ask questions. We use Github issues primarily for bug reports and feature requests.

**Comment by vpanchal72** [comment]
Thanks for your reply
