### ISSUE TITLE
Grafana 2.0: Only admin user can create new dashboards

### ISSUE THREAD

**Issue by martinkoch** [grafana/grafana#1806]
The save button for new dashboards currently only appears if I'm logged in as the 'admin' user. I believe this should also be the case if I'm logged in as another user that has grafana admin privileges.

**Comment by torkelo** [comment]
Make sure the user who cannot save has Editor or Admin role for the organization. 

By default the grafana config is configured so so that new users (or signups) get a Viewer role, Viewer organization role cannot create dashboards. There is also an Admin Organization role, admins can edit data sources. 

There roles are very different from the "grafana super admin user", that user can edit all users and orgs, and change server settings. 

If you want new users and signups to automatically be added as Editors change this setting: 
http://docs.grafana.org/installation/configuration/#auto_assign_org_role

Anyway to fix it you need to login with the account that is "Organization admin" (the one who can save dashboards, edit data sources), go to organization users (click organization dropdown in sidemenu), then remove and readd the user with the correct role  (sorry cannot change role right now). 

Will improve docs around this soon.

**Comment by huseyinkozan** [comment]
Hi,
Can you please add these "delete and add again" issue to the docs, if fixed ? 
I am digging second time to find this.
