### ISSUE TITLE
A simplified version of dashboard states

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#18075]
A simplified version of dashboard states that addresses two issues

1. Developers frequently want to create and test out ideas.  But then the leave the dashboards around.  When searching you can't always tell which dashboard is a test/dev one and which is production.
2. For sensitive systems the production version of a dashboard is critical.  Developers would like to be able to make changes, have them reviewed and promote them to beta and finally production, with a corresponding ability to back them out.

Grafana will support three levels of state:

Level 1 - Development (default value)
Level 2 - Beta
Level 3 - Production

- The state of the dashboard should be clearly visible on the screen, and configured in the Settings.
- Copying a dashboard or creating a new one will always result in the state being set to Development.
- A given dashboard could have up to 3 co-existing copies of the dashboard one at each level... for dev and beta one could potentially append -dev and -beta to the production URL.

Consider the following use case.

1. A production dashboard D exists as version 1.  It needs a change.
2. Developer a edits the D and creates version 2 but it is still in Development.
3. An initial code review wants to see D-v2 and D-v1 side by side to compare.  They also want to diff the versions.
4. Code reviewer signs off.  D-v2 is promoted to Beta... for further testing.  At this point we have two dashboards, D-v2 (Beta) and D-v1 (Production).
5. As testing proceeds, a smal change is made to add a new feature. D-v3 is created in dev. 
6. D-v2 is promoted to prod (the prod URL is NOT changed).  Two versions exists D-v3 (dev) and D-v2 (production).
7. Eventually D-v3 is promoted up and in the end you have one version in production D-v3.

**Comment by KristianLyng** [comment]
We're looking at exactly this, and so far we've investigated using separate Grafana installations and migrated dashboards from one to an other through magic. This feature request would be a much smoother solution.

One thing that needs to be adressed, though, is how to deal with parallel tracks. There are two issues I see: 

1. D-v3 tries to fix something unrelated to D-v2, and is, as such, based on D-v1. Classic merge/rebase issue. I figure this can be one of those "we don't fix that" things, because merging sounds like a royal pain.
2. We want to make multiple "D-v2" candidates to compare them all and present to a user for evaluation before we make a pick.

I think the "A given dashboard could have up to 3 co-existing copies" limitation is perfectly ok, BUT, then I'd like to be able to be able to:

1. Have a dashboard A in production
2. Copy dashboard A three times: B, C and D
3. We leave B, C and D mostly in dev/beta - do our thing, evaluate and compare.
4. Dashboard C wins - use dashboard C to overwrite dashboard A - with no change in URLs etc to dashboard A.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
