### ISSUE TITLE
auth.proxy whitelist not respected

### ISSUE THREAD

**Issue by kim0** [grafana/grafana#18109]
**What happened**:

I configured auth.proxy with a whitelist as below. I set `X-WEBAUTH-USER=kryako` for testing purposes. I found that grafana accepts and logs-in that username. While the whitelist should not be allowing my IP address!!

```
[analytics]
check_for_updates = true
[auth.proxy]
auto_sign_up = true
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
whitelist = 172.16.0.0/12, 10.0.0.0/8, 192.168.0.0/16, 127.0.0.0/8
[grafana_net]
url = https://grafana.net
[log]
mode = console
[paths]
data = /var/lib/grafana/data
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
[users]
allow_sign_up = false
auto_assign_org = true
auto_assign_org_role = Admin
```

**What you expected to happen**:

I expected this login request to be denied, since my browser is basically forging this header. Note that I am accessing grafana, through an ingress (nginx-ingress) running on kubernetes. Not sure if nginx modifies the headers somehow to make it trusted. But since grafana's logs (below) show my IP address, I am assuming grafana actually sees my read IP address and thus surprised as to why it is allowing the login

```
t=2019-07-15T00:01:32+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/dashboards status=302 remote_addr=52.138.219.254 time_ms=0 size=29 referer=
```

**How to reproduce it (as minimally and precisely as possible)**:

- deploy kubernetes, nginx-ingress, grafana
- Use Chrome's ModHeaders to add X-WEBAUTH-USER header
- Observe Grafana let you in, while not in whitelist IPs

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.2.5 (commit: 6082d19)

**Comment by markelog** [comment]
Log takes the IP address either from `X-Real-IP`or `X-Forwarded-For` HTTP headers. And if those aren't present, then from the TCP.

Whereas for the whitelist check we only take IP address from TCP connection. So in this case we take the address of the kube ingress proxy.

However, the purpose of the `whitelist` is to specifically check for the actual address, since those HTTP headers can be spoofed. The most common use-case for this feature is to check that request came from your local network.

We tried to use HTTP headers for whitelist before - it broke grafana for a lot of users, sorry, gotta close this
