### ISSUE TITLE
grafana does not validate variables in url

### ISSUE THREAD

**Issue by elias-putz-kiwigrid** [grafana/grafana#18157]
**What happened**:
If i define a custom variable and specify exactly which value should be selectable, the user can write whatever he wants in the url parameter and the specified list of available values is ignored.

**What you expected to happen**:
If only `foo` and `bar` are available for this variable, a 4xx should be returned if the user tries set the variable to sth else then `foo` or `bar`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Import basic dashboard:
```
{
  "editable": false,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 71,
  "iteration": 1563361802012,
  "links": [],
  "panels": [
    {
      "content": "# _ $foo _",
      "gridPos": {
        "h": 4,
        "w": 4,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "mode": "markdown",
      "timeFrom": null,
      "timeShift": null,
      "title": "Panel Title",
      "type": "text"
    }
  ],
  "schemaVersion": 18,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {
          "text": "bar",
          "value": "bar"
        },
        "hide": 0,
        "includeAll": false,
        "label": null,
        "multi": false,
        "name": "foo",
        "options": [
          {
            "selected": true,
            "text": "bar",
            "value": "bar"
          },
          {
            "selected": false,
            "text": "baz",
            "value": "baz"
          }
        ],
        "query": "bar,baz",
        "skipUrlSync": false,
        "type": "custom"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timezone": "",
  "title": "test",
  "uid": "igo7biNZk",
  "version": 1
}
```
2. Open url: your-grafana.com/d/igo7biNZk/test?orgId=1&var-foo=this-shouldnt-work
3. Text box shows `_ this-shouldnt-work _` even though only `bar` and `baz` are available for the variable `foo`.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.2.5 (6082d19)
- Data source type & version: none
- OS Grafana is installed on: Docker: grafana/grafana:6.2.5
- User OS & Browser: every browser
- Grafana plugins: none

**Comment by torkelo** [comment]
Variables support custom values as well (you can specify anything in the variable drop down) there is no enforcement / validation for any variable. We could add it this as an optional feature. Can you describe the reasons for why you need this validation?

**Comment by elias-putz-kiwigrid** [comment]
The user has the role `Viewer` and can access user specific dashboards. The datasource contains more than the user should be able to see, thats why the variable in this dashboard only contains specific values. If he can bypass this variable definition by writing any value directly into the url he can access data he is not supposed to see.

The only solution seems to be to setup multiple databases in our influx and add them as individual datasources to make sure the user cannot bypass the variable values.

**Comment by torkelo** [comment]
That is not how Viewer role works, a viewer can still query everything in a datasource. Viewer only means they cannot create/modify dashboards.

But dashboards define dynamic queries that can change in any way so there is no way to validate a query is the same as the one saved in the dashboard. If you need to isolate data from different users you need to place the data in different  datasources that support permissions , and create 2 orgs that use the different datasources

**Comment by apple-fan-pl** [comment]
> a viewer can still query everything in a datasource

Thats security breach with **highest priority**. May easily lead to a viewer can still query everything in a datasource escalation issue (PEI), another (extremely) harmful situation......

**Comment by torkelo** [comment]
In Grafana executing any query is part of viewing data.

What datasource do you use? Does it have script injection vulnerabilities?

**Comment by garyyang85** [comment]
I am using prometheus datasource. And my user are created dynamically.  It is very inconvenient to create and maintain a  prometheus datasource for each user.  Just try Grafana, I can filter out the specific data for each user by namespace or some other params in variable query.    Query is based on dashboard.  But the query params change in url or variable manually input can escape the variable definition.  Then why we define a variable scope and maybe a complex regex to filter the query result?  Do not know if this is common scenario. But at least, I think this is a reasonable requirement.

**Comment by ppolewicz** [comment]
I think there are two problems here:
1. (what was actually observed here and in #8731 and #31847) - the user is able to change a variable in an url and grafana doesn't immediately barf with a `400 Bad Request`.
2. The Viewer-level user can actually query anything they want, not just what the dashboards present, so the lack of dashboard variable enforcement is just a tip of the iceberg.

Even if prometheus would implement a different permission model, I still wouldn't like my Grafana to allow every user with a Viewer permission to run any query they want. This should be properly restricted in Grafana.

Why wouldn't we use a separate organization and different datasources? In some scenarios (like in mine...) we'd have to provision them dynamically and sharing panel library and dashboards between orgs is not enabled, so it would be very painful.

I understand the current security model does not provide this kind of parameter verification, but what I would expect, is not giving the Viewer user a power to provide any custom query to a datasource for grafana to execiute, but instead piping it through a filter. The current datasource endpoint would be (optionally?) closed for Viewer users and instead a query from the browser would refer to a browser panel id. Then that endpoint would check if the variables are allowed to be inspected by the viewer of the dashboard which is now being viewed, it would validate the time range and then assemble the query (taken from the database, not from the user), with variables and time range as parameters. A global setting would cause all of the Viewer traffic to have to pass through that "secure" endpoint instead of going through the current route.

The security filter thing, as worded in the last paragraph, doesn't seem to be all that complicated, but I don't know golang and I haven't read the code, so maybe actually it's much harder than it seems. @torkelo perhaps you know more? How much work are we talking about, a few hours, a few dozen, a few hundred?

**Comment by torkelo** [comment]
There is no way currently to validate those variables in a secure way, they can be query fragments or anything (dynamically set by the user). Many variables are dynamic in the way that the options are defined in turn by another query (whose results change with the time window).

So we could implement this secure query endpoint but we would have to disable most templating features for it to be secure.

**Comment by ppolewicz** [comment]
I understand currently there is no way to validate it in a secure way. I'm looking into changing precisely that - providing a way to securely validate it if a global option (or organization-wide option?) is set - I imagine this secure mode may not be desired by some users. It may not be a default setting for new instances.

If my understanding is correct, the work required to make secure dashboard viewing happen is:

- [ ] add an option (global or organization) to enable enhanced security
- [ ] add server-side verification of variable selection (including chained variables, where some values may be available for some time windows but not for the others)
- [ ] add a new endpoint for secure (queryless) data retrieval which instead of a query parameter accepts the panel id and then the query is extracted from the panel on the server-side
- [ ] disable most templating features if enhanced security is enabled
- [ ] click through it all and see if it works as expected (at least for the timeseries panel)

Does that sound right? Did I confuse or miss anything? I'm really not sure about the template part, what needs to be turned off and what can stay and how it will impact users who only use templating to parametrize queries (I think it barely hurts, if at all).

Would a PR for it be welcome?

**Comment by ppolewicz** [comment]
@torkelo is the plan good? Would a PR for it be welcome? Could you suggest someone I might hire to do the actual contribution? I might be able to find a golang developer, but I'd guess you might know someone who knows this part of the grafana codebase already.

**Comment by septatrix** [comment]
It would be very much appreciated to get literally any kind of feedback at this point @torkelo (or someone else from Grafana Labs). This is a huge limitation for giving Grafana access to most personnel and for those who are not aware of this it is a *huge* security vulnerability basically granting full database access to everyone with dashboard access.¹ I can understand that there might be some factors most of us have overlooked so far but there are currently multiple suggestions how this might be fixable and there has not been a response to any of them!

And if you do not think this is a security vulnerability (unlink the other users in these issues) you should at the very least document this somewhere in a big fat red alert box. I do not want to sound rude given that the rest of the product is fantastic but not getting *any* response on such an important topic is rather frustrating...² :(

¹ And the workarounds like read-only database users, SQL views etc all have significant drawbacks and do not even mitigate this problem realistically.
² Neither in this issue nor in the other ones similar to this.

**Comment by jalevin** [comment]
Hi @septatrix, 

We are continuing discussion here https://github.com/grafana/grafana/discussions/43487

**Comment by septatrix** [comment]
Still relevant, or at least close this as a duplicate of #43487

**Comment by gelicia** [comment]
Closing as a duplicate of #82950
