### ISSUE TITLE
legend table -> sort by name

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#18186]
on a graph panel, when creating a legend "as table", one can have summary stats like avg, total, etc and sort by those.
but it would very helpful if we could sort by series name as well.

not a good example, but anyway

![sort](https://user-images.githubusercontent.com/20774/61485186-cf57a580-a9a0-11e9-801a-474a10b429ba.png)

**Comment by torkelo** [comment]
If you disable sort on value it will default to sort from your query, so if you sort the series by name in your query you can so this right now. The main reason this does exist yet is that sorting series is best done in query, but might be some cases where having it table legend would be really use useful 👍

**Comment by Moosbueffel** [comment]
How can I do this for muliple queries and multible sources?

For me the best and simplest way would be to use the ordering of the queries. I can push them up and down. And I thougt, this is also the sorting in the panel than. For legend and also for a table.

**Comment by marcoboffi** [comment]
With multiple queries (A,B,C), I would have possibility to order alphabetically entire legend, not necessary before A, then B,....

**Comment by gillg** [comment]
To complete, in some cases, there is no "automatic order".
For exemple you could be able to sort things by status, and use an arbitrary order based on the status workflow.

**Comment by bijwaard** [comment]
Sorting on metrics would indeed be very helpful for stats and gauge panels, currently they seem to be sorted in the order that the query results come in. Only sorting on the query row would not help enough, since one query (like below) can result in multiple metric names (labels).
This is how my stats panel now looks like, having it sorted on label would be much appreciated, it can now change the ordering the next time the influx query is run.
![image](https://user-images.githubusercontent.com/6523124/152114671-c05dfb51-a484-4c71-9ee6-0d6b9be4eaf3.png)

**Comment by EivV** [comment]
I have a case as well. There is a bucket-based graph that I'd like to see sorted naturally. The source data has no padding and is sourced alphabetically. That is fine. 
![image](https://user-images.githubusercontent.com/45094143/188072742-0cff0838-9484-4073-8882-8d3b2359f4a2.png)

But when I apply either Transform with Regex or Override Display Name, the sorting does not change.
![image](https://user-images.githubusercontent.com/45094143/188073724-154b1f97-9e3c-4858-9b2b-7acd45b5e1c5.png)

**Comment by Dieterbe** [comment]
took a little longer than i thought, but i appreciate it :) thank you!
