### ISSUE TITLE
Light theme for individual dashboards

### ISSUE THREAD

**Issue by calebcall** [grafana/grafana#1824]
It seems I'm not able to switch individual dashboards to use a different theme from what is my default.  If I change my default to Light, everything is light, if I change it to Dark, everything is dark.  I can't see anywhere that allows me to set "Dash A" to use Light and "Dash B" to use Dark like you used to be able to do.  Is this possible still and I'm just over looking it?  I noticed all my dashes that were light were imported as Dark.

**Comment by torkelo** [comment]
Why do you want this on individual dashboards?

**Comment by calebcall** [comment]
We have several dashboards that have been designed by various users around both light and dark themes. Forcing them all to one or the other really puts a damper on users wanting to use grafana. This is the last issue before I'm able to get everything moved to 2.0.

**Comment by torkelo** [comment]
In what way are they designed for white or black? (just trying to understand the use case)

**Comment by kmoppel** [comment]
+1. I'd also really like to "just switch" between themes anytime, without going into any menus. And if changed it could be sticky during one session. Thanks for the great work anyways!

**Comment by torkelo** [comment]
Is there a reason why? Some dashboards work better with light theme than others?

**Comment by kmoppel** [comment]
Well for me it's mostly an "environment" issue I guess, e.g. when showing something to colleagues on a projector or when working on a laptop with a weak display the light theme is much more usable and it's just too inconvenient to go into settings and change it.

**Comment by torkelo** [comment]
and how would you want it? A big theme selection drop down always visible one every dashboard or in top nav? That is horrible. how often do you need to change theme?

**Comment by calebcall** [comment]
Our needs are similar in that users have built dashboards incorporating grafana and some have dashes built around a light theme, some around the dark theme for their graphs.  Depends on how and where they are being displayed.  Some have also built dashes that are more than just a grafana dash, but they use grafana in parts of their dashes.  I don't care about being able to have a quick switch option, but I would like to be able to set dash 'A' to a light theme and dash 'B' to a dark theme.  Just like you could do in pre-2.0.

Hopefully that helps clarify my reasoning for the initial request.

**Comment by kmoppel** [comment]
Hehe, true, a big theme selection drop down would be horrible indeed. But lets say a menu item "Theme" on the top left-side hamburger menu (similar to Organization) would make a lot of sense to me.

**Comment by abdullin** [comment]
Surprised this issue was closed.

I'm working on a presentation for the conference and wanted to include Grafana dashboard in the talk. Obviously, this requires a light theme (since default dark theme doesn't work well with the projectors).

Since, it seems, there is no easy way to switch a single dashboard to a light mode, Copenhagen Micro-services conference will have to go without Grafana. It is a pity.

**Comment by torkelo** [comment]
Why can't you set your profile preferences to white theme temporarily for the conference? 

You can also load grafana with &theme=light in url

**Comment by kalidasya** [comment]
@torkelo does the theme get parameter supported with scripted dashboards?

**Comment by torkelo** [comment]
it works on any page

**Comment by mvadu** [comment]
@torkelo Thank you for adding ` &theme=light`

**Comment by sylforever98** [comment]
@torkelo,  我想在制作dashboard 背景上加一个图片，这样我的dashboard就很漂亮，你能告诉我怎么样做吗？第二个问题，dashboard  每个board只能row,一排一排，但也需要vertical这样的集合，如下图：
![image](https://user-images.githubusercontent.com/4963248/29404409-7c0a1116-836d-11e7-9bf9-fe1de3e49628.png)

**Comment by qingweiqm** [comment]
兄弟，

you should use english to describe your request.

**Comment by MarkTurbo** [comment]
A simple ability to save the preferred theme for a dashboard in its 'Settings - General' section would really help! When multiple people are working on dashboards in a given Grafana instance, everyone is forced to use the default theme, but some users like DARK, some like LIGHT and some who like DARK still prefer the way some dashboards look in LIGHT.

Most of the users I work with prefer DARK, but I have some users who hate it and prefer LIGHT. Being able to set the theme at the User level would also help.

**Comment by torkelo** [comment]
You can set it on user level , it’s a user preference

**Comment by MarkTurbo** [comment]
Ha! OK. I couldn't find that option from the viewpoint of an Admin. I create users and can't see how I can set that for a new User. However, I now see that if I access my OWN User preference after logging in, I can see the option!

I can at least now tell a User that want's to use the LIGHT theme how they can set it in their preferences. The ability to set that when I create a User would be a nice to have though. Thanks for the info.

**Comment by tithij** [comment]
> You can set it on user level , it’s a user preference
I have the same dashboard that I use for different environments in our development stack. 
I'd like to use a background fill or image to indicate which one I am on.Yes, I could just look at the name, but to make a quick distinction I'd like a different background. 
I'd also like to change a panel's background so that I can differentiate between layers in the development stack - this is in the realm of background colours only, and not full UI redsign.

**Comment by calebcall** [comment]
@tithij You can use the plugin Boom theme to set a background image.

**Comment by bob454522** [comment]
I hate to see this closed too (i added a thumbs up, but wanted to add some context since @torkelo was asking for)-
I too would like to see a per dashboard setting for light/dark mode.

**my use case** (which can not be helped by the &theme=dark url variable):
Im almost always in admin "mode" (ie logged in as admin and viewing dashboards as admin), and there are some dashboards which i very much would prefer to see in dark mode, at all times.   Mainly dashboards with many stat panels, or ones with a few number of panels.

We do have a few "24/7" dashboards in kiosk mode on dedicated monitors (where i do use the &theme=light/dark url var - to great success!).  A majority of my dashbaord viewing is in admin mode, where i only want to see a few specific dashboards in dark theme (but the majority in standard light theme).

perhaps a solution would be the ability to switch dark/light (and would reload page on change) via a grafana dashboard variable?
thanks,  (Love Grafana!)

**Comment by spongenee** [comment]
we use aws X-Ray for tracing, and the traces are really difficult to navigate with dark mode. The errors/fault percentage, if it's < 30%, just do not stand out. I hate that we have to remind our users to temporarily switch so a setting to enforce a default theme per dashboard will help in this case.
