### ISSUE TITLE
Need to remove double quotes from the multi select template variable

### ISSUE THREAD

**Issue by ManimekalaB** [grafana/grafana#18267]
**What happened**: Need to remove the double quotes from the multi select template variable

**What you expected to happen**:
Elasticsearch query=> Query like (*TES-738* OR *TES-744* OR *TES-764*)

But getting double quotes

Elasticsearch query in detail it queries=> Query like ("*TES-738*" OR "*TES-744*" OR "*TES-764*")  

Not working while trying with dynamic values:
Variable name => [[dependednt_ticket]]
Variable value => dependednt_ticket => *TES-738*, *TES-744*, *TES-764*
Elasticsearch Query=> Query like [[dependednt_ticket]]
Elasticsearch query in detail it queries=> Query like ("*TES-738*" OR "*TES-744*" OR "*TES-764*")  

NOTE: double quotes is getting added here.

Working when tried with static values: 
Elasticsearch query=> Query like (*TES-738* OR *TES-744* OR *TES-764*)

**How to reproduce it (as minimally and precisely as possible)**:
Create a variable as below and assign it to the Elasticsearch Query
Variable name => [[dependednt_ticket]]
Variable value => dependednt_ticket => *TES-738*, *TES-744*, *TES-764*
Elasticsearch Query=> Query like [[dependednt_ticket]]

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aocenas** [comment]
@ManimekalaB I am not sure I understand what the issue is. Wrapping in quotes should not alter the result of the query and so `"TES-738" OR "TES-744" OR "TES-764"` and `TES-738 OR TES-744 OR TES-764` should be the same. Also I am not an expert on elastic search but not sure what `Query like (TES-738 OR TES-744 OR TES-764)` means, ES does not have `like` keyword as far as I know. Maybe you need to write it as `query:("TES-738" OR "TES-744" OR "TES-764")`? Could you share a screenshot of the query editor?

**Comment by hugohaggmark** [comment]
Hi @ManimekalaB, I'm closing this issue for now because of inactivity but we can always reopen it if needed.
