### ISSUE TITLE
User role 'Viewer' (or new role) should make it impossible to enter panel edit mode, or do other changes

### ISSUE THREAD

**Issue by drsprite** [grafana/grafana#1826]
I have anonymous access setup, with the org_role set to Viewer. The anonymous user is still able to change the view / add rows / delete panels, etc. 

I understand they cannot save these changes. 

Is there a way to add a role that is true read only? They cannot add / delete elements. They can only view the dashboards already built?

Thanks!

**Comment by torkelo** [comment]
What would be the reasons?

**Comment by crudbug** [comment]
:+1:

**Comment by torkelo** [comment]
please specify why this is important

**Comment by drsprite** [comment]
I guess I have no real reason other than if I provide someone read-only access and they start clicking around, I don't want to have to support them. I only want them to view the real time graphs. 

I can see it being a problem where someone added panels and created their own view, then they lost their changes on a refresh. If they're a Viewer, they should only be able to view. 

Just a thought. Thanks again!

**Comment by woodsaj** [comment]
maybe we could toggle the dashboard.editable attribute when calling the DashboardModel constructor in dashboardSrv.

```
if (contextSrv.user.OrgRole === "viewer") {
  this.editable = false;
}
```

**Comment by torkelo** [comment]
@woodsaj its tricky, what is viewer? I mean, I want "viewers" on play.grafana.org or my BI department to be able to view dashboards, but also open graphs make minor changes etc. The only thing they cant do is save or create new dashboards. 

I am not really sold on the idea that a viewer cannot enter graph edit mode. I am afraid that might give users the illusion that viewers will only be able to view the data in dashboards and not define their own queries (which would be simple to do, just inspect the network requests to the time series store and change the query).

**Comment by drsprite** [comment]
How about another role? readonly. It is what it is. Read only. That way Viewer can still view and make minor changes?

**Comment by crudbug** [comment]
I think a more general solution could be, user profiles which have associated dashboard CRUD configuration. In general, admin assigns the user roles.
e.g.
admin = create / read / update / delete
r_user = read
rw_user = read and create panels, not deletions

**Comment by torkelo** [comment]
Unless this gets lots of +1 I am not sure I see the need to hinder 'Viewers' from opening a graph in edit mode. Hindering users from moving panels, enter edit mode, and all other changes that one can make would just complicate the code. And I am not sure what the reason would be beside stopping users from doing stupid metric queries (or making it harder by not allowing them to enter edit mode). 

But if this is important for to users I will consider it.

**Comment by pasancario** [comment]
I'm also looking for a similar capability for one particular use case: 

Imagine you have an external customer that wants to access at your metrics. You want to share with him, a simple read-only dashboard to check and you just give him permission to move around defined graphs in time, but no possiblity to modify aggregation queries or see other series in same db, I guess this should be the same situation as sharing an snapshot of a dashboard. 

So, being capable to have the same view an permissions as in a snapshot dashboard, but with real time data.

**Comment by torkelo** [comment]
@pasancario that is not possible, because neither graphite, influxdb, nor OpenTSDB have "per series" permissions, and it is actually impossible for grafana to implement it (due to wildcard queries and other things). So if you share a "read only" or "view only" dashboard to an external client, if he has read access to your graphite or influxdb metrics, then even when he cant edit graphs, he can still just inspect the metric requests and issue other requests through curl or some other http client.

**Comment by pasancario** [comment]
So, the main problem will be "architectural" design to separete metrics for external customers or use snapshot dashboard capability from Grafana to let them access those data, without knowing our internal design.

**Comment by torkelo** [comment]
@pasancario yes, and by architectural it has to be a feature in what ever time series store you use.

**Comment by robertjakub** [comment]
@torkelo, maybe possibility to disable editing of metrics/series (I use influxdb, internal db proxy, and don't want anyone with the viewer role to change the metrics/series to see another graphs.)

**Comment by torkelo** [comment]
@robertjakub but even if I disabled it they could still issue any query they wanted (if they new some HTTP basics & curl. InfluxDB does not have a "per query" or per "series" permissions. So if Grafana added a feature that would prohibit Viewers from entering graph edit mode and changing queries, that feature would not be a complete protection,  users with Viewer role could still accces all metrics exposed from a single influxdb database.

**Comment by robertjakub** [comment]
@torkelo yeah, and even using the backend proxy, Viewer could still ask for any metrics/do any queries. The advanced user - can fetch the metrics and put it in their system/excel/whatever... The average user - it will be the blocking point ((-;. So - complete protection: move series to another instance of influxdb?

**Comment by torkelo** [comment]
Another influxdb database is enough

**Comment by michabbb** [comment]
+1 from me, a viewer should not be able to edit existing graphs or templates, a viewer is a viewer and not a editor...

**Comment by boldname** [comment]
+1
Viewer is only a viewer

**Comment by torkelo** [comment]
The reason I am hesitant to make viewer not able to open graph in edit mode is that admins will think that viewers can only see visible data when in truth they will (if they know some http) be able to query for all data exposed by the time series store. Since there is no per series permissions in graphite or influxdb

**Comment by robertjakub** [comment]
@torkelo just a quick dirty hack: check http referer for the data proxy requests? (e.g.: if the request come without http referer, or from the other than dashboard page - make it forbidden/restricted/whatever, or encrypt the query parameter with the user api key or sth)

**Comment by woodsaj** [comment]
What if we changed the 'editable' flag on dashboard from being true/false to being the role that can edit the dashboard.
editable=true  //backwards compatibility to allow all to edit
editable="Viewer"  //all users can edit
editable="Editor" //only editor and admin roles can edit.
editable="Admin" //only admin role can edit.
editable="None" //no-one can edit
editable=false //backwards compatibility for no-one being able to edit.

**Comment by torkelo** [comment]
@robertjakub all of your suggestions are easily faked with a http client, (like referer),  sign query parameters? Not sure graphite or influxdb has any query signing feature nor would that solve this issue. To solve it InfluxDB or graphite needs some per series permission filter that Grafana can pass.

**Comment by torkelo** [comment]
@woodsaj good suggestion! only problem I see is that I guess most would like a global option (or per org) for this.

**Comment by drsprite** [comment]
In my original scenario, I'm not so concerned about people being able to see the data if they know HTTP. I'm looking for a dashboard I can give to executives, and prevent them from clicking around and trying to manipulate the data on-screen. 

In theory they won't have HTTP knowledge, so no worries there. 

They are, however, curious and will click around if they know that they can. I'm trying to prevent that from happening. They see the dashboard graph series as we present it. No matter what they try to click on. Only allowing them control over the timeframes, zoom in/zoom out, etc.

**Comment by crudbug** [comment]
@drsprite I agree. I am also looking for the same use-case.

**Comment by michabbb** [comment]
@torkelo please stop thinking about security, for many of us this request has nothing, really nothing todo with security. And it's only about the webinterface. I would like to show my customers data, without to worry about they delete something by accident or change any views that took hours for me to create. Stupid people should be able to see data, nothing more. Own clients or coworkers are not interested in hacking something. Grafana is by far the best interface I have seen, but if I am not able to show my customers data without to worry they change or delete something by accident, the interface is useless to me AND for my customers. I am really sure, I am not the only one with exact the same problem.

**Comment by torkelo** [comment]
@michabbb i understand the use case. although I do not understand your worry that they may change or delete something, users with Role Viewer can not change or delete anything , sure they can edit a dashboard transiently, change colors, togle or high light series, but nothing they do can be saved. 

The only possible harm they could do is change the query so that it becomes very resource expensive and slows down the TSDB. 

While false sense of security might not be important for you it is for me, I want to be very explicit about security concerns and not give grafana users a false sense of security when it comes to sensitive data. 

Will try to add a new Role to accommodate your needs.

**Comment by michabbb** [comment]
@torkelo thanks for your understanding! The thing is, you say, things can be changed, but not saved, so why offer any buttons that give you the feeling That you can change something (permanently) , anyway? :-)
The webinterface is great, if we can achieve usability for everyone, there would be so more use cases, because a Admin don't need to worry any longer :-) the best solution would be, if a viewer even would not see any buttons, that could give him the feeling, that he is able to change anything. A fixed dashboard, with fixed graphs and fixed queries. Because on the other hand, creating nice dashboards is a real business product I can sell to customers. And if I could do this without giving them a hours of exercises, that would be perfect. 
And about the security issues: I totally understand, but when the webinterface acts like a proxy, the proxy can handle some things Graphite can't, and that's great. When the documentation of grafana explains, that webinterface roles have nothing to do with the real world, everybody can decide on his own, to use the webinterface-only features, so grafana will never be responsible for users who do queries by their own via http. 
Thanks!

**Comment by torkelo** [comment]
@michabbb it depends on perspective and use case. I find I do transient tweaks to dashboards all the time, change a query slightly, change summarize, toggle series, sort legend. etc,  all of which I want viewers to be able to do as well. I just want them NOT be able to overwrite or delete my dashboards.  Not really sure what harm you expect users to do when entering graph edit mode. 

Why would stopping users from entering edit graph edit save you "hours of exercises"?

**Comment by michabbb** [comment]
When I work with a company that has, for example, a callcenter with 10 people, young woman without any knowledge about graphite and howto change or create queries, they only have a dashboard to see some nice things to get a feeling if everything around them is working well. Next use case, a customer who has absolutely no knowledge about all the technique stuff, but he wants to see his sellings at the different platforms (shop, amazon, ebay)... These are real life use cases that only work, when there is no button, that gives the user possibilities to change (even it's not saved!) anything. And if there are any buttons like changing a query, people will start to play around or start asking questions, that their nature. And in this case you can setup a wiki, docu or whatever to explain everybody what's okay and what's not. Worst case, you have to invest a lot of time to explain that there are some things they could do, but please leave these kind of things untouched. 
So, maybe it's a possibility to give each button/action a name/id and in the config of grafana, you could disable or enable these actions/buttons based on the role. This could give the Admin maximum freedom of what a viewer can see and change. Default could be the way it is now, so that everybody who is using grafana now don't get problems, but others who need more control about the viewer would be happy, just an idea.

**Comment by migacz1125** [comment]
Hi, 

i tell You about my business need. I have one graphite app which collect stats from many customers. In grafana i need create organizations (is one customer) with user "Viewer" role. In my case "Viewer" can't create metrics and import dashboards because then have access to other customers stats. 

roles:

Viewer: Can view dashboards and can edit time range, Axes & Grid oraz Styles but not add nad edit metrics

Editor and Admin: Should create graphs and dashboards for Viewer

You can chack my changes here: https://github.com/migacz1125/grafana

What do You think about tthis ?

**Comment by torkelo** [comment]
@migacz1125 you case is not supported by Graphite, graphite does not have per series permissions. Viewers who know http can easily query metrics for other customers.

**Comment by migacz1125** [comment]
I know but i blocked graphite to outside by htaccess and grafana is on the same srv (grafana is access for user outside for one port).

**Comment by michabbb** [comment]
@torkelo you repeat yourself and we already know that graphite has no per serien permissions ;) we really are over this point. this project is about grafana and not graphite. a webinterface can handle things i am not able todo when doing raw queries. so please don´t repeat yourself all the time ;-)
what @migacz1125 is talking about is real life. if this "graphite permission" thing is so important for you, whats the problem to documentate this. we all now know, that this has nothing todo with security, its about people (mostly customers!) who are not interested to hack something. its about to make the webinterface more customer/end-user friendly, thats all ;) if there is realy a customer starting raw queries, so what, if a user bypassed the webinterface, what has grafana todo with that, nothing and so its not a grafana-security thing. you wanted to create "awareness" of this, and everybody in this thread understands, but "awareness" does not solve the needs ;)

**Comment by migacz1125** [comment]
+1 @michabbb and @torkelo what do You think about my logic user role in Grafana (without graphite permissions) ?

**Comment by torkelo** [comment]
@michabbb that comment was not for you, it was for  @migacz1125 who thinks that blocking graphite from outside access while exposing it though grafana via Viewer role will protect users from not viewing others metrics, which is wrong so I had to repeat myself.

**Comment by torkelo** [comment]
@michabbb I already understand your case, stop repeating yourself. The reason why I think security is important and and important for Grafana is that Grafana acts as a proxy to Graphite, and people trust Grafana, and think that Viewer means that they can use Graphite in a multi tenant secure maner. I have constantly to remind people that graphite cannot be used in a secure multi tenant scenario, and they care about security 

Just to quote from @migacz1125 
     
> In my case "Viewer" can't create metrics and import dashboards because then have access to other    customers stats.

**Comment by Akeru** [comment]
I read the whole thing twice and I'm still not sure I get it so please bear with me.

If you configure your Grafana datasources in proxy mode and firewall anything but your Grafana server from connecting to your Graphite (or whatever) server, any actions that is not allowed by the UI won't be possible. 

Grafana beeing then the single point of access to your data, provided the GUI allows it, you could setup some kind of RBAC per dashboard/series/ you name it.

Or did I miss something ?

**Comment by michabbb** [comment]
@Akeru i answer for myself: i don´t need proxies, firewalls or anything else. i don´t want to start a new security debate. maybe its absolutly mindless to restrict something by GUI, that you can do anyway via simple http calls, but that´s not the point - not for me. some customers need to be proteced, even for themself, that means they are not able to change graphs in general. and even if changes are not saved, like torkelo said, they shouldn't be able to change anything in the first place. watching nice looking graphs, play a little bit with the timeframe, watch different dashboards... the user role i need here is "dumbest assumable user" who is only able to watch dashboards of his company that he is assigned to. intersting (for them) buttons for editing graphs with strange variables, this is something they should never see.

**Comment by Akeru** [comment]
@michabbb Yup, sure, fully agreed.

The design I proposed intends to have both parties happy. It should provide the security @torkelo needs (no false sense, no security-through-obscurity) so he could implement the features you'd like to have, a rally dumbed down, static view of you data.

**Comment by torkelo** [comment]
@Akeru grafana will proxy all http requests to the graphite server, so if you Viewer access, you give http access to a Graphite instance, so someone who knows HTTP can explore all metrics

**Comment by Akeru** [comment]
@torkelo Ok, I thought so but was not sure. For this to work, you would have to process the requests before sending them to the Graphite instance. It could be doable but this might be tricky.

**Comment by michabbb** [comment]
this is the **5th time** i have to read, that a user with http knowledge is able to explore all metrics. 
how often ? is this ever and ever repeating notice something that really brings progress into this issue ? i don´t think so.
this issue is not about people with http knowledge at bad interests, it's about a gui that limits possibilities to a specific virtual user role, because the gui can act as a proxy or is able
to simply hide some control buttons/icons.

is this really a big deal to create a new role, let´s say "strict viewer" where users are not able to add rows, delete panels and other stuff... just dump viewing.... ???

**Comment by torkelo** [comment]
@michabbb what is with you? calm down. As you you see the misconceptions about security is common no matter how often I repeat it in this thread. I have already said twice that I agree with you, a new role would be a good idea so stop posting pointless comments :)

**Comment by michabbb** [comment]
@torkelo okay, peace ! ;-)

**Comment by Akeru** [comment]
@torkelo My bad, sorry !

**Comment by torkelo** [comment]
No problem, all is well :)

**Comment by bbinet** [comment]
+1 for a "dumb viewer" mode (ui only): this will just unclutter a bit the ui for non-technical people

**Comment by sysr-q** [comment]
+1 here as well.
Would be nice to have a dumb/strict viewing mode, even though people with knowledge can still explore other metrics.

**Comment by justmiles** [comment]
+1 for this

**Comment by torkelo** [comment]
For Viewer users they now get a panel menu that looks like this: 
![image](https://cloud.githubusercontent.com/assets/10999/7915312/f632a8d6-087c-11e5-9224-4adaa891cc73.png)

Will add a new role named `Read Only Editor`  to replace the old Viewer behavior.

**Comment by bbinet** [comment]
Thanks @torkelo !

**Comment by hrochniak** [comment]
One more remark regarding Viewer ... can you also remove "Panel JSON" possibility for Viewer? I don't understand why should just viewer of data be able to see whole my query with name of database, tables, column names etc... This would be much more easy to exploit if he knows structure, or?

**Comment by torkelo** [comment]
Every viewer can read that anyway and access all data as queries are issued from the browser, and the panel json is just viewing the panel model something that is already exposed to  browser and anyone can open browser dev tools to inspect dashboard json and with some http skill issue any valid tsdb query.

Viewer role has nothing to do about data access protection but is only about preventing user from being able to modify and save / create dashboards

**Comment by michabbb** [comment]
@torkelo first of all, thank you for creating this new user, i never said that, sorry. but as i got notifications about this issue here, and reading your last answer: it´s the same like 2 years ago. people complain about things a stupid user shouldn´t see and you start answering the same like before: 

- "why should i hide something, if the user can...." 
- "why should i hide something, if the user is able of....."
- "why should i hide something, if the gui is only a proxy"

and the most important thing is: poeple asking for hiding these things they don´t care.
the gui should be useable for stupid people, stupid people should not see anything they don´t understand because they start asking and this takes support, support costs money and time.

maybe next time someone asks about these virtual roles, you should offer him a "pay for this feature", maybe with https://www.bountysource.com/ - and everybody has a chance to get happy, just a recommendation ;)

**Comment by torkelo** [comment]
What the hell is wrong with you? I care about people understanding security implications so they are not misguided.he clearly wanted database names and tables to be private info, informing him that hiding the UI action would not accomplish that is wrong?

Please stop telling me that  I should stop clarifying things for confused users :)

**Comment by hrochniak** [comment]
Actually Michael wrote it exactly as I wanted in my first comment, thank you Michael. 

Of course, I understand there are security implications, but it is not about security. It is exactly about that part for "stupid" people (the gui should be useable for stupid people, **stupid people should not see anything they don´t understand** because they start asking and this takes support, support costs money and time). 

Ability to view graph on fullscreen and share some graph should be available for viewer, as is now, this is absolutely perfect. But why should anyone be able to see how was panel created and what query was used, if they are not interested? If I need it to share with someone, I would definitely use another role specific for that person, not for public viewer.

**Comment by torkelo** [comment]
Because a lot of people are interested, and hiding things that are not truly hidden creates a very dangerous false sense of information security.

Sorry if I misunderstood you, you seemed upset that people could see what tables data was coming from.

**Comment by hrochniak** [comment]
I don't understand what do you mean - who and why are interested? The only thing we want from viewer is to view data and work with it - view it on fullscreen or share it as picture - those are useful options and I think it is enough. Not to click and see let's say "source data" of panel. Just why? I understand there are other options to show this information, OK, I am aware, but I don't care. The only one thing I don't want is to have this option directly in panel, because for viewer it is really not relevant.  

Please, try to understand me - If I want Grafana to be system for showing numbers for quality guys and managers ("stupid" people mentioned above :) ), they should really don't see any options which they don't have to. And I think JSON of panel is really not needed for anyone else but editor.

**Comment by torkelo** [comment]
viewing panel json is a view action so fits perfectly for a viewer role, not sure why it's such a big deal to hide. Lots of people use this feature for anonymous (viewer) grafana setups. 

It's a pretty hidden view it's not like it's distracting or confusing users being hidden in a panel submenu.

**Comment by Tepew** [comment]
Our company use Grafana for our customers. And hide info about infra - it`s ok. Viewer can edit board without permissions - it`s very bad. Just add
editPanel=2
in url and Viewer can looked all metrics. Looks like a fence with holes

**Comment by NvBgm** [comment]
Still a viewer can get my data by inspect option and save it as csv  
How can i protect my data ??

**Comment by michabbb** [comment]
If something didn't get fixed after 8 years, you should do it yourself or leave this conversation and make peace with yourself 😁
