### ISSUE TITLE
Error when adding a new ES datasource

### ISSUE THREAD

**Issue by christine-gong** [grafana/grafana#18275]
**What happened**:
When I tried to add a ES datasource with daily pattern [xxxx-]YYYY.MM.DD to Grafana, it complains about the index was not existed. My local (PST) time is July 25th 2019, and the index exists on Elasticsearch is xxxx-2019.07.26.
When I checked the browser console, it only checked the index xxxx-2019.07.25 only and returned the 
```
resource.type: "index_or_alias"
type: "index_not_found_exception"
```

**What you expected to happen**:
Should not complain index not existing

**How to reproduce it (as minimally and precisely as possible)**:
add a daily pattern index to Grafana but the existing es index is one day later because of timezone difference

**Anything else we need to know?**:
no 

**Environment**:
- Grafana version: v6.2.5
- Data source type & version: Elasticsearch 6.4
- OS Grafana is installed on: Ubuntu 16.4
- User OS & Browser: Mac Chrome 
- Grafana plugins: na
- Others: na

**Comment by aocenas** [comment]
Hey @christine-gong is this happening when you test the datasource in the datasource config page or when using the datasource in dashboard?

**Comment by christine-gong** [comment]
Hi @aocenas it happens when I try to test adding a new datasource in the datasource config page

**Comment by aocenas** [comment]
There seems to be a few different issues that can cause this:
We use [timeSrv.timeRange()](https://github.com/grafana/grafana/blob/e1cec1069cfe700ee4578bb18f908ab47a96c71e/public/app/plugins/datasource/elasticsearch/datasource.ts#L86) which keeps the state of selected time range globally. So if somebody goes to some dashboard, selects some far away timerange, goes to datasource test, it will reuse that time range for that test possibly trying some old indexes.

By default the `timeSrv` has [wrong range](https://github.com/grafana/grafana/blob/fcdc29746f41570fd2541616cc94244f94e9ad0b/public/app/features/dashboard/services/TimeSrv.ts#L35) this should be `from: 'now-6h'` instead of just `6h`. This creates an invalid range and when testing which in then fallbacks to using `this.indexPattern.getIndexForToday()`. This flow should result in correct date though as it is using utc so the pattern should not be shifted.

@christine-gong can you or did you try testing after refreshing the page? I would assume you did but just want to make sure I can exclude the case when it is due to the cached time range from dashboard.

**Comment by hugohaggmark** [comment]
Hi @christine-gong, I'm going to close this issue for now because of inactivity but we can always reopen it if needed.
