### ISSUE TITLE
I want to show/hide panel based on date selection

### ISSUE THREAD

**Issue by samiramaspl** [grafana/grafana#18356]
Hello

I have my custom requirement in my dashboard to show/hide panels based on date selection.

I have one dashboard called  Dashboard-1 and have 7 panels for each weekdays

panel-1 [Show on Monday]
panel-2 [Show on Tuesday]
panel-3 [Show on Wednesday]
panel-4  [Show on Thursday]
panel-5  [Show on Friday]
panel-6  [Show on Saturday]
panel-7  [Show on Sunday]

I want to show only one panel of selected weekday based on selected date.

Is there any feature on grafana which help me to show / hide panels dashboard like like I want ?

**Comment by torkelo** [comment]
no there is no such feature and likely will not, first time this requirement has come up. 

Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.

**Comment by samiramaspl** [comment]
is it possible with template variable using Repeat panel or row based on selected values in template variable.?
