### ISSUE TITLE
SQLite as Datasource

### ISSUE THREAD

**Issue by fr-ser** [grafana/grafana#18376]
**What would you like to be added**:

I would like to use SQLite as a datasource.

**Why is this needed**:

Many smaller IoT applications use SQLite as their storage and it is not always trivial to change that behavior.

I would also be willing to implement this feature myself, I am just wondering where to start and if this is a good idea at all.

**Comment by com2u** [comment]
Great idea! I like this feature as well.

**Comment by renaudrenaud** [comment]
Interesting. I have plenty of use cases for this!

**Comment by fr-ser** [comment]
As far as I currently see it, this would be a change in the Grafana source code (and not a plugin).

If any core member gives this idea a "get-go" I would try to tackle it. Any further information or possible pitfalls would also be very much appreciated :wink:

**Comment by micelshima** [comment]
Thumbs Up!

**Comment by ilgrank** [comment]
I fully agree, a SQLite plugin would be sweet. Alas, the devs already commented that they **won't** add SQLite as an internal datasource and no one seems to be developing an SQLite input plugin.
See: #1542

**Comment by fr-ser** [comment]
Hmm. In that case I guess I'll look into Plugins a bit more. My previous assumption was, that plugins only work in the frontend via HTTP requests, but maybe not... I'll check it out later...

**Comment by freekvh** [comment]
So, this is not happening? Would be sweet with the default home-assistant docker...

**Comment by jonathanlb** [comment]
While it's not a totally generic SQL source, it's relatively straightforward to use [Express](https://github.com/expressjs/express)/[Fiber](https://github.com/gofiber/fiber)/etc to expose some SQLite queries to Grafana's [simple-json-datasource](https://github.com/grafana/simple-json-datasource).

For example, [sqlite32grafana](https://github.com/jonathanlb/sqlite32grafana) exposes SQLite3 columns as timeseries to Grafana.

**Comment by fr-ser** [comment]
I created a plugin that queries an SQLite reachable (through a network drive) on the Grafana host. I would consider this a first step

https://github.com/fr-ser/grafana-sqlite-datasource

**Comment by kevinvh001** [comment]
Hi fr-ser,
I use Grafana on my MacBook Pro to visualise live data ported from Victron-Venus_Docker_Grafana.  The data is ported to Grafana via http://localport:3000 and it works well.
I wish to visualise similar historical data stored on my hard drive.  I am struggling because I have no programming capability or understanding of database structures.
I installed your SQLite plugin on my Venus-Docker_Grafana installation, but it will not accept the Path "/Users/kevinhiscox/Documents/sqlite3/GXData.sqlite3".  It cannot find the database file which is definitely on my HD.  I suspect the issue is caused by Grafana receiving the live data from http://localport:3000.
I them quit Venus-Docker_Grafana and installed a standalone Grafana installation with "brew install grafana".  I started Grafana with Terminal and then opened Grafana in Safari using http://localport:3000.  OK - new clean Grafana installation.  I then tried installing your SQLite plugin but when I clicked on DataSources, I got a message saying "The following plugins are disabled and not shown in the list below:
frser-sqlite-datasource      Modified signature"
Can you help me please?

**Comment by fr-ser** [comment]
@kevinvh001 Please open an issue in the plugin-repo if you are experiencing problems: https://github.com/fr-ser/grafana-sqlite-datasource/issues
