### ISSUE TITLE
CloudWatch: Move min period implementation to backend

### ISSUE THREAD

**Issue by Dhananjay-Ghongane** [grafana/grafana#18493]
I am using backend plugin API of cloudwatch to qury data from AWS in my application. 

But it seems if "min period" is "Auto" then logic to determine Period for query is in frontend. 

<img width="839" alt="Screenshot 2019-08-11 at 2 02 15 PM" src="https://user-images.githubusercontent.com/45629183/62831674-c9bc4b00-bc40-11e9-81b1-2356d52f6c58.png">

here is code block from dtatasourece.ts :
`getPeriod(target: any, options: any, now?: number) {
    const start = this.convertToCloudWatchTime(options.range.from, false);
    const end = this.convertToCloudWatchTime(options.range.to, true);
    now = Math.round((now || Date.now()) / 1000);

    let period;
    const range = end - start;

    const hourSec = 60 * 60;
    const daySec = hourSec * 24;
    let periodUnit = 60;
    if (!target.period) {
      if (now - start <= daySec * 15) {
        // until 15 days ago
        if (target.namespace === 'AWS/EC2') {
          periodUnit = period = 300;
        } else {
          periodUnit = period = 60;
        }
      } else if (now - start <= daySec * 63) {
        // until 63 days ago
        periodUnit = period = 60 * 5;
      } else if (now - start <= daySec * 455) {
        // until 455 days ago
        periodUnit = period = 60 * 60;
      } else {
        // over 455 days, should return error, but try to long period
        periodUnit = period = 60 * 60;
      }
    } else {
      if (/^\d+$/.test(target.period)) {
        period = parseInt(target.period, 10);
      } else {
        period = kbn.interval_to_seconds(this.templateSrv.replace(target.period, options.scopedVars));
      }
    }
    if (period < 1) {
      period = 1;
    }
    if (!target.highResolution && range / period >= 1440) {
      period = Math.ceil(range / 1440 / periodUnit) * periodUnit;
    }

    return period;
  }`

If we have this logic in backend plugin somewhere in get_metric_data.go or  cloudwatch.go i can use direct backend api to get cloudwatch data. 

Request is to add getPeriod logic in backend if its mentioned Auto in panel configuration so that i can use backend API directly to query data from my application

**Comment by Dhananjay-Ghongane** [comment]
@marefr @mtanda,

I am new at github, Coluld you please help mi on this issue/Enhancement.

**Comment by hugohaggmark** [comment]
Hi @Dhananjay-Ghongane and thanks for contributing. We're looking in to this and we'll get back to this when we can.

**Comment by marefr** [comment]
Here's the related code in backend when period is auto (empty):
https://github.com/grafana/grafana/blob/91a911b64e4bfdfa5ca19354797b2969e41135fc/pkg/tsdb/cloudwatch/get_metric_statistics.go#L124-L131

So it's hardcoded to 60 if not namespace is AWS/EC2 then it's 300. 

@mtanda any input on why it was implemented as this instead of using the [interval calculator](https://github.com/grafana/grafana/blob/master/pkg/tsdb/interval.go)?

**Comment by mtanda** [comment]
CloudWatch automatically reduce data points resolution, Grafana need to set precise `Period` for query time range.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html
> Data points that are initially published with a shorter period are aggregated together for long-term storage. For example, if you collect data using a period of 1 minute, the data remains available for 15 days with 1-minute resolution. After 15 days, this data is still available, but is aggregated and retrievable only with a resolution of 5 minutes. After 63 days, the data is further aggregated and is available with a resolution of 1 hour. 

I didn't care about querying to backend without frontend, so backend code expect that parameter has precise `Period` value.

I'm not sure the use case because CloudWatch itself provides API.
But, moving frontend code to backend code, it will work.

**Comment by marefr** [comment]
Thanks @mtanda will change the title to reflect that moving frontend code to backend is needed.
