### ISSUE TITLE
Relative time in units of 'mon' or 'min' doesn't work

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#1864]
According to the Graphite render API mon is supported as a relative time offset for month (30 days) and min is for minutes.  In Grafana timepicker you just put m to indicate minutes and it seems to append 'in' when calling the Graphite render API.  But, if you pass mon it then makes it minon, or if you pass min (having read the API docs) it makes it minin.

Request is enhance the Grafana code to append 'in' only if the value passed is 'm' to allow m and min to be minutes and mon to be in months.

FYI, this is not a new 2.0 issue...the behavior is the same in 1.9.1

**Comment by torkelo** [comment]
you capital M for month, grafana will translate that to mon

**Comment by Krinkle** [comment]
That's a creative workaround, but is there hope for a more reasonable (and intuitive) solution in the future?

I assume monon and minon don't serve any purpose. In Graphite – nor any other backend.

All Graphite's Render API units are supported, except "mon". ([see documentation])http://graphite.readthedocs.org/en/latest/render_api.html#from-until).

"mon" is the one exception. This seems unnecessary as it unambiguously can only mean "month" in this context. This is silly bug caused by clever expansion from "m" to "min" without paying attention to the rest of the string. An honest mistake, but closing this as a question is a bit dull.

Patch welcome?


----
PS: At least it's now documented at [http://docs.grafana.org/reference/timerange/](http://docs.grafana.org/reference/timerange/#customize-relative-time-and-auto-auto-refresh-options)

**Comment by torkelo** [comment]
Not sure what you mean workaround or bug. M is the time range char in grafana that means month.  Not sure I see a bug or workaround here

**Comment by torkelo** [comment]
Grafana supports many data sources all with different notion if how relative time ranges should. e specified. So there is now right way here, Grafana specifies one way and translates that relative range to the current data source :)

**Comment by Krinkle** [comment]
@torkelo The workaround was the fact that Grafana blindly changed "m" to "min" without looking at the rest of the string. Causing "month" to become "m**in**onth", etc.

The end result should be that entering "min" and "month" either works as intended or results in an error that the user understands.

As of Grafana 4 or 5, this was fixed. The time ranger now sees "min", "mon", and "month" as invalid. Thanks!
