### ISSUE TITLE
AzureMonitor: Support multiple Application Insights Key/ID pairs

### ISSUE THREAD

**Issue by shavonn** [grafana/grafana#18668]
Microsoft has expressed interest in allowing users the ability to add multiple application insights to an azure monitor datasource.

Users should be able to add and remove application credential sets on datasource config. 
Work will also have to be done for use with query editor.

**Comment by ChadNedzlek** [comment]
I'm trying to make a PR to fix https://github.com/grafana/grafana/issues/15153, and I'm pretty sure if this happens I'll be back on square one with that change.  Is this likely to happen soon? Or will I be safe to continue working on that issue?

**Comment by torkelo** [comment]
Does the azure api support multiple keys?

**Comment by dylan-asos** [comment]
This issue is most aligned with what I want to do - happy to open separate issue if preferred. All of the other resources in Azure allow me to simply select them, then access the platform metrics for that resource type, but with AI resources we're forced to setup an API key and other configuration. 

If the service principal in Grafana has Monitoring Reader permission in Azure, then ideally I wouldn't have to configure AI resources in the Grafana plugin, I'd simply be able to :

* Select an AI resource from a list of possible resources of that type
* After selecting resource, have access any metrics available from that resource (both 'application insights' platform metrics and any custom metrics that have been created against the resource
* Run any log queries against that resource

This would greatly simply the operational overhead of managing the permissions to the AI resources from Grafana - just let the SPN do it rather than managing Application ID \ API key pairs.

Appreciate this is probably something that would need to happen on the AI resource permissions model rather than Grafana. 

NB: As a workaround, I can run cross-resource queries against any AI resource I like by specifying the Log Analytics datasource to execute the query, but would be good to make this more native + have access to the metrics as drop downs.

**Comment by ricohomewood** [comment]
Is there any movement on this work? It would be great to have multiple AI's in the Azure Monitor plugin as we would have an AI per microservice and would want to use Grafana to display these microservice metrics.

**Comment by dylan-asos** [comment]
Just for info - I've done something very similar automating some data retrieval. 

The AI API expects an 'application id' which you can retrieve from the management API with a call like, 

```
https://management.azure.com/subscriptions/{subscription-id}/providers/Microsoft.Insights/components?api-version=2015-05-01"
```

That returns all of the AI instances for a subscription, and you can get the confusingly named **AppId** field from each response, which corresponds to this 

![image](https://user-images.githubusercontent.com/16137664/82213538-35d48980-990c-11ea-9850-5c3af4b764dd.png)

Once you have that 

1. Generate an AAD access token, scoped for https://api.applicationinsights.io/
2. Call the query method (https://dev.applicationinsights.io/reference/get-query) with the AAD token, passing the AppId retrieved from the management API call. 

As long as the SPN used to generate the access token has Monitoring Reader access, you can now perform operations against the resource without requiring an API Key.

**Comment by buggsdummy** [comment]
When will this feature be added?

**Comment by meken** [comment]
In case anybody is looking for a work-around, note that [Monitoring Reader](https://docs.microsoft.com/en-us/azure/azure-monitor/roles-permissions-security#monitoring-reader) role has access to Application Insights data and can view data in AI Analytics. With Grafana 7.x you can already access the `Microsoft.Insights/components` namespace through the Metrics option, so as long as the Azure Monitor service principal has the right scope and permissions, you wouldn't even need the Application Insights Key/ID pair.

Similarly, with the new style [workspace based Application Insights](https://docs.microsoft.com/en-us/azure/azure-monitor/app/create-workspace-resource), you should be able to run your KQL queries through Logs query method.

**Comment by sunker** [comment]
We're going to deprecate the Application Insights query mode in Grafana in favor of querying this data through Metrics and Logs. Read more about this in our [docs](https://grafana.com/docs/grafana/latest/datasources/azuremonitor/#deprecating-application-insights-and-insights-analytics). I'm closing this issue now, but feel free to reopen if you feel the need to.
