### ISSUE TITLE
Grafana Database Tables inside PostgreSQL Schema

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [grafana/grafana#18714]
One of our customer uses grafana, they have a requirement to keep the grafana tables used for users, org, roles, dashboards etc inside their database with a postgresql schema like "grafana.user".

I see the grafana table structures, I don't see grafana has option to use schema for the tables. 

Is it possible to achieve this without code change in go language.

**Comment by dprokop** [comment]
@gopalakrishnan-subramani Looking at the code it seems like this is not possible, as the only thing configurable is the database name. But let me verify that with @marefr- Marcus, is there any workaround fur such case?

**Comment by liorld** [comment]
no yet

**Comment by liorld** [comment]
not yet

**Comment by marefr** [comment]
Think using a custom search_path in the postgres database should work. We fixed a bug earlier that shown that users we're using a custom schema with Postgres and Grafana, see #17357 for reference.

**Comment by ocherfas** [comment]
I came across a similar issue where I wanted the ability to configure the database schema name for the postgres connection. Are there any plans for implementing such a thing?

**Comment by marefr** [comment]
@ocherfas use a custom search_path as I refer to in https://github.com/grafana/grafana/issues/18714#issuecomment-524780258

**Comment by ocherfas** [comment]
I tried to use a custom search_path but I get an error on grafana initialization:
msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: pq: relation \"migration_log\" does not exist"
I think this is somewhat related to the fix you referred to on [#17357](https://github.com/grafana/grafana/pull/17357)
I'm using grafana 7.0.5.

Any suggestions?

**Comment by ocherfas** [comment]
Well it seems that the problem was that I had leftovers from previous grafana initialization on the public schema, and even through I changed the search_path for grafana user it still somehow found the previous migration_log table and failed.
So after cleanup it did work, but I still think this is not a very solid solution. For example in our case, we use grafana as part of our solution, so when we deploy our solution on a customer site, a reasonable request would be to create a database for us  on his PostgreSQL and give us a user that can control that database. It would be a bit "weird" to ask him to create an extra user and configure its search_path to "grafana" schema.
