### ISSUE TITLE
FeatureRequest: enable plugin authors to add icons to side menu items

### ISSUE THREAD

**Issue by lorenwest** [grafana/grafana#18872]
**What would you like to be added**:

An icon next to my plugin nav item

**Why is this needed**:

Grafana has icons next to all items in the left navbar. To maintain consistency with Grafana, I would like to add an icon to my page/dashboard definition in the plugin.json file, in a way that the [icon is displayed](https://github.com/grafana/grafana/blob/f3fb178efa95ef227fff7b5d6d2a4e5aaa37b9e7/pkg/api/index.go#L217) if my page/dashboard is listed as an addToNav type.

**Comment by briangann** [comment]
You can add dashboards and components to the sidebar using the configuration in the `plugin.json` file.

A good example is the `grafana-sensu-app` which has:

info section of src/plugin.json:
```
  "info": {
"logos": {
      "small": "img/sensu-v2-logo-dark.svg",
      "large": "img/sensu-v2-logo-dark.svg"
    }
```

includes section:
```
  "includes": [
    { "type": "page", "name": "Sensu Servers", "component": "SensuServersCtrl", "role": "Viewer", "addToNav": true, "defaultNav": true},
    {
      "type": "dashboard",
      "name": "Sensu Summary",
      "path": "dashboards/sensu-summary.json",
      "addToNav": true
    },
```

With the above the component "Sensu Servers" and the dashboard "Sensu Summary" are adde the the sidenav using the icon specified in the info/logos section.

**Comment by lorenwest** [comment]
Thanks for the reply, Brian. Yes, the plugin logo shows just fine. It's the icon next to the menu items (pages & dashboards) that are lacking an icon. All other Grafana side menu items have icons next to them except those included in plugins, and it's inconsistent for the user.

For example, if I wanted the settings gear icon next to the `Sensu Summary` menu item, it could be part of the plugin.json like this:

```
 "includes": [
    ...,
    {
      "type": "dashboard",
      "name": "Sensu Summary",
      "icon": "fa fa-settings",
      "path": "dashboards/sensu-summary.json",
      "addToNav": true
    },
```

Does this make sense?

**Comment by ryantxu** [comment]
See also:
https://github.com/grafana/grafana/pull/11824

I agree it is useful (obviously) and we need to figure out how to best expose this.

**Comment by hugohaggmark** [comment]
I will use the `feature-request` label for this one instead, as I think it makes more sense. Let me know if you think differently @briangann @ryantxu

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
