### ISSUE TITLE
Panel & Row repeats

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#1888]
Repeat panel or row based on selected values in template variable. 

Gif screencast showing how it works
![repeat_panels](https://cloud.githubusercontent.com/assets/10999/7427283/25c7c95e-efd8-11e4-9b98-cbf9462d5ac7.gif)

The repeat can be set on a panel or row:
![image](https://cloud.githubusercontent.com/assets/10999/7427291/60f2966c-efd8-11e4-9499-7b1a9be3cd35.png)

This feature builds on the new multi-select variable feature:
![image](https://cloud.githubusercontent.com/assets/10999/7427295/8264ba50-efd8-11e4-89a8-0bb6c933f695.png)

https://github.com/grafana/grafana/issues/1144

**Comment by deepakhj** [comment]
That looks great. I think it will work for system metrics where I want to repeat cpu or memory graphs for all selected servers.

**Comment by elisiariocouto** [comment]
Would this feature support the "All" value?

**Comment by torkelo** [comment]
@elisiariocouto yes it does

**Comment by elisiariocouto** [comment]
Great! Looking forward for this :+1:

**Comment by HerrBerg** [comment]
I just tried this really nice feature with repeating rows and its awesome.

Still I have one point for improvement:New rows are added at the end of the dashboard.

We have a dashboard which contains our needful metrics about servers which at the moment has five rows. When comparing e.g. cpu load for multiple servers the row feature is really helpful, but it would be nice if (in this case) the rows would be repeated in place and not appended at the end of the dashboard.
As I'm sure that there are also very useful scenatios where the rows are appended at the end it would be nice if it would be configurable where they are repeated (in place / end of dashboard).

**Comment by torkelo** [comment]
good point @HerrBerg ,  I  agree!

**Comment by lahma** [comment]
I'm trying out latest Grafana (nightly build) with InfluxDB 0.9. I'm trying to achieve row repeats with host so that I could issue queries like:

SELECT mean(value) FROM "cpu_usage" WHERE host='$host' AND $timeFilter GROUP BY time($interval) ORDER BY asc

But with row repeat it seems that I get the combined value for the host like "host1,host2", which won't work with Influx as there is not such host tag value "host1,host2" . In row repeat case I would expect to get value of row's repeat item "counter" instead of all the selected values. Same thing applies with panel, I'd like to get the single current value.

Am I missing something (like hidden running value)? Otherwise this looks like an awesome feature!

**Comment by torkelo** [comment]
@lahma did you specify row repeat and your `host` variable in the row edit menu?

**Comment by lahma** [comment]
Yes, I have $host specified in templating values coming from tags collection, row uses host and thus two rows are created. But each row has graph that uses where host = '$host' and no results as the query issued is where host = 'host1,host2'.

**Comment by torkelo** [comment]
hm..  I think scopedVars is not implemented for InfluxDB 0.9 yet

**Comment by lahma** [comment]
I've created a pull request https://github.com/grafana/grafana/pull/2207 for this. Now works for my use case.

**Comment by torkelo** [comment]
@lahma that is great, thanks!

**Comment by rschitz** [comment]
That's exactly what i need, thanks a lot!

**Comment by rschitz** [comment]
The "ALL" value is perfect, thanks again for this great addition. Just a thing, i first thought it was not working since you must click outside of the list menu (on chrome ?) to "validate" your choice. If it's not possible to do it dynamicaly, you should add a "OK" button.

**Comment by svet2lanochka** [comment]
Hello, it is great feature !
But I have some problems to make it alive as you show. 
We are using Grafana 2.6 with datasource Prometheus. 
I do see the panel repeated as number of selected values, but in the legend I see the All values ("server1|server2|...") together. 
What is the correct way to get relevant value that is actually displayed on the panel ?

**Comment by torkelo** [comment]
you can use prometheus legend alias patterns, maybe its' a bug in the Prometheus code if can't use your template variable is not working as expected in the legend format field

**Comment by waqark3389** [comment]
@torkelo This is a nice feature, but Im trying to figure something out for my TV displays. 
When selecting 4 servers to be displayed, I can see all of them appear fine, but as more are selected, the dashboard overflows from the TV screen.

Is there any way around this, essentially what I am asking is, could the panels and graphs scale down while being able to define a Px length and width? 

A bit unorthodox so I apologise in advance!

**Comment by torkelo** [comment]
you can set a min span in general tab

**Comment by waqark3389** [comment]
@torkelo Yes, but that is horizontal right? What about rescaling graphs to fit vertically as well..

**Comment by bergquist** [comment]
@waqark3389 http://play.grafana.org/dashboard/db/advanced-layout

**Comment by JeromeVi** [comment]
I'm sorry but where can I find the code of the example dashboard ? Because I can create the "filter" but I don't understand how to use the value and other stuffs. So is there a place where I can find the demo template of this issue ?

**Comment by mathurj** [comment]
Hi @torkelo 

Thanks for this lovely feature. Just one thing though. So, I am using a lot of Drilldown / detail link feature in my dashboards and on using All/multipe values, the row repeats perfectly well however the URL & URL title picks up all the values for of the selected variable instead of just one which is being used for that particular row.

Now, this works fine when i hover to the top left of the row/graph to go to the next link, it perfectly takes the one correct value to the variable, however when i hover across the rest of the graph, it pick up all the values for the variable and hence I cannot use that as it takes me to a page that does not exist.

Any leads on how I could get rid of this problem? Happy to provide more explanation if needed.

Thanks

**Comment by sikkandar86** [comment]
Hi @torkelo

i am selecting 5 server name , and i am getting 5 graph. but all the graph in single row. any way i can modifiy this one like each row only 2 graph should display?

**Comment by glitchy** [comment]
@torkelo is this not an example of a "hidden" panel that everyone has been asking for? and does "repeat panel" solve this? i see appearing/disappearing panels when you select/de-select different endpoints? i just went down [this](https://github.com/grafana/grafana/issues/4470) thread
