### ISSUE TITLE
Fix splunk streaming

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#19176]
We changed the streaming interface again so we need to revert splunk streaming change we did for 6.3

**Comment by alexanderzobnin** [comment]
That's really strange, but when plugin uses old streaming model (`query()` returns `Subject`) query fails with error:
```
PanelQueryRunner Error TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
```
I've found that this is caused by this `rxjs.from()` function:
https://github.com/grafana/grafana/blob/6b2e95a1f2c89c37ace3e4947677ba46c24c7213/public/app/features/dashboard/state/runRequest.ts#L135-L137
There's a related issue in rxjs repo: https://github.com/ReactiveX/rxjs/issues/4532
I'm trying to find a workaround.

**Comment by torkelo** [comment]
Ah, then the new you might need to upgrade and return observable (that is much better than. Subject ) observable will know when caller unsubscribes

**Comment by alexanderzobnin** [comment]
I've made some investigation and found that the problem is not that rxjs issue. In the Splunk plugin we use some useful functions from rxjs (like `from()`, `map()`) that is not exposed by Grafana. So we don't use rxjs from grafana, but include it into plugin webpack build. This causes a problem:

https://github.com/ReactiveX/rxjs/blob/d3e7e3f299e277b077602d26c59dab40ef0e1dba/src/internal/observable/from.ts#L97-L100
```ts
export function from<T>(input: ObservableInput<T>, scheduler?: SchedulerLike): Observable<T> {
  if (!scheduler) {
    if (input instanceof Observable) {
      return input;
    }
```
Because of different context, `input instanceof Observable` returns `false` in this case and finally, function fails. This behavior described here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_context_(e.g._frames_or_windows)

If I switch to rxjs from grafana, it works in this case, but since we use a lot of rxjs functions that not exposed to plugin, it becomes a problem.
