### ISSUE TITLE
Provide option to adapt default permissions

### ISSUE THREAD

**Issue by tktr** [grafana/grafana#19172]
**What would you like to be added**:
 
When creating new folders / dashboards, the following permissions are set by default:

- Admin: Admin
- Editor:  Edit
- Viewer: View

However, these permissions applied on creation are currently not configurable (only **after** creation). In some cases, it might not be desired to grant View access to **all** viewers by default.

**Why is this needed**:

Without having such an option, it is currently not possible for administrators to ensure proper access rights within a single organization. 
Imagine some users within an organization should not be able to see all dashboards by default. In case an "Editor" user creates a new folder, access to all viewers will be granted implicitly which in this case would grant unwanted permissions not being in control of the admin.

**Comment by tano46** [comment]
Same problem, same request :-)

**Comment by gitolihub** [comment]
Same request, Same problem ^^

**Comment by Ivanchukk** [comment]
Will be great to have it

**Comment by lovelski** [comment]
Same request, Same problem !!!

**Comment by guymeron** [comment]
Hi  @torkelo & @hugohaggmark 

I believe the following items are duplicates:
https://github.com/grafana/grafana/issues/30936
https://github.com/grafana/grafana/issues/19172
I would like to contribute a fix which will allow provisioned ACLs in dashboards.
Please let me know if this change is acceptable and I can continue with creating the PR.

**Comment by guymeron** [comment]
@torkelo @hugohaggmark 
Please let me know if this change is acceptable.

**Comment by candlerb** [comment]
I have the same problem with new users in an org, when I don't want to give permissions to everything by default.  The permission "Viewer (Role) can View" can be removed from individual dashboards, but you have to remember to do this for _every new dashboard you create_.

Either of the following solutions would work for me:

1. A new organization role, called "Everyone" or similar, which doesn't have any permissions by default.  You can set this role on "unprivileged" users, and then grant additional permissions to specific teams on particular dashboards as required.  Of course, if you do want a dashboard to be viewable by everyone, you can set "Everyone (Role) can View" on that dashboard.  OR:
2. A setting to prevent the default "Viewer (Role) can View" permission from being auto-added to new dashboards.

I prefer option 1.  The problem with option 2 is that the org viewer role (i.e. someone who can view all dashboards in this org) is still useful to keep IMO.  With option 2, *everyone* has the org viewer role, but it isn't useful because it can only view those dashboards which have explicitly had the permission "Viewer (Role) can View" added to it. In effect, "Viewer" role is the "Everyone" role.

Option 1 has the advantage of being fully backwards-compatible, because the default config is still to give new users the "Viewer" role, so everything works the same as before.  Only if you choose to, do you make new users members of "Everyone" instead.

I think it's a very simple solution, but perhaps Grafana would be worried that it might push people away from Grafana Enterprise :-(

**Comment by sdwerwed** [comment]
This is very important for us that we use Kubernetes, IaaC is the only way to set up and configure Grafana. All changes from the GUI are temporary. We need that future because provisioning for roles does not make sense if we can not use those roles for the dashboards/folder

**Comment by simonyangxy** [comment]
Same here

**Comment by Space2Man** [comment]
I would also need this feature. I either need the option to create users with no permissions at all and e.g. assign them permissions via teams. Or I need the option to not enable view permissions for all users with viewer role.

Thanks and best regards

**Comment by Talhazzers** [comment]
Same.

**Comment by matthijskooijman** [comment]
@candlerb, you wrote:

> 1. A new organization role, called "Everyone" or similar, which doesn't have any permissions by default. You can set this role on "unprivileged" users, and then grant additional permissions to specific teams on particular dashboards as required. Of course, if you do want a dashboard to be viewable by everyone, you can set "Everyone (Role) can View" on that dashboard. OR:
> 2. A setting to prevent the default "Viewer (Role) can View" permission from being auto-added to new dashboards.

I had a stab at implementing 1. by manually editing the database, which worked to some degree: I could create a user with a None role that could not access any dashboard except when explicitly shared with them, but I had to assign this user permissions to *all* datasources to allow them access to the right data.

Even more, I discovered that if you give access to a datasource (i.e. to the underlying influxdb), then the user can execute arbitrary queries on the database, not just the ones configured in the dashboards they have access to. This is also an issue without my database hacks: when you remove the Viewer permission from a dashboard, the dashboard itself can no longer be seen, but any Viewer can still access the data by writing their own queries.

This was reported 6 years ago in #6180 already, but closed as wontfix because it is hard to fix (which I guess it is, though not impossible). Even more, with the new public dashboards support, it seems to me that a fix for that issue might be [easier now than back then](https://github.com/grafana/grafana/issues/6180#issuecomment-1416910375). And if that would be fixed, maybe your suggestions can also be implemented (I would be in favor and also prefer option 1).

**Comment by double-yaya** [comment]
Same request, Same problem

**Comment by vtorosyan** [comment]
Thanks everyone for your thoughts and contributions. Grafana Enterprise supports [role-based access control](https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/) which allows to assign fine-grained permissions to users, teams, service accounts, as well as it allows to modify what Viewers, Editors or Admins can do by default. 

RBAC is available in all Grafana Cloud plans, including in our Free plan. We do not have any plans at the moment to make the feature available in Grafana OSS, so I'll have to close this issue for now.

**Comment by n2N8Z** [comment]
If the aim in restricting dashboard access was restricting access to the data displayed (as it was mine), then access controls on data sources  also needs to be fixed/implemented (https://github.com/grafana/grafana/issues/114769).
