### ISSUE TITLE
Bootstrap modal closes for the Esc key even with the keyboard property set to false

### ISSUE THREAD

**Issue by tharinduc** [grafana/grafana#19224]
Keyboard property is set to false in the bootstrap modal config object in **util_srv.ts**
 file in **"public/app/core/services/util_srv.ts"**. I expect it to prevent the modal closing when pressing the "Esc" key. But still the modal closes when I press the "Esc" key.

**Comment by aocenas** [comment]
Hey, @Simplelenz are you arguing that you would prefer modal to not close on 'Esc'? I agree that the code is a bit weird in that regard and will take a look how that argument is interpreted but in general I think the behaviour right now is correct and that we want to be able to close modal on 'Esc'.

**Comment by Simplelenz** [comment]
@aocenas , I mean if we pass false to keyboard property, then modal should not close for 'Esc'. Otherwise what is the use of passing false to keyboard property? I think at some point it overrides.

```
const modal = this.$modal({
      modalClass: options.modalClass,
      template: options.src,
      templateHtml: options.templateHtml,
      persist: false,
      show: false,
      scope: this.modalScope,
      keyboard: false,
      backdrop: options.backdrop
});
```

User must be able to control whether the modal should close to 'Esc' or not. If user pass 'true' to 'keyboard' property, then modal should close for 'Esc' and not when it is 'false'

**Comment by aocenas** [comment]
Yes I understand that, just wanted to make sure whether you are arguing for changing the actual behaviour that the user sees right.

So for me this means that the behaviour for the user is correct (closing on 'Esc' makes sense for the user), but the code is a bit odd because it seems like it should not allow that. Is that right? Just want to make sure we understand each other.

**Comment by Simplelenz** [comment]
Yes actual behavior doesn't reflect in the code here.

**Comment by aocenas** [comment]
Seems like there is [global binding](https://github.com/grafana/grafana/blob/fd21e0ba14dac32ae703dd6c73d93c84eeb881e2/public/app/core/services/keybindingSrv.ts#L49) on Esc that dismisses the modal anyway so the setting there does not have any effect.

**Comment by Simplelenz** [comment]
Then there shouldn't be that global binding. Because it makes some other code obsolete. What you expect from that global binding must be implemented in a different way I think.

**Comment by aocenas** [comment]
@dprokop this seems like a small cleanup task for platform team if it isn't already changed.
