### ISSUE TITLE
Possible to use grafana without the standalone server

### ISSUE THREAD

**Issue by chipmunc56** [grafana/grafana#1939]
I'm a heavy grafana 1.x user, great software!
I'm trying to make the upgrade to 2.x but would like to run the system in the same way as before (drop a folder into my apache www directory). 
Is this mode still supported?

thanks!

**Comment by torkelo** [comment]
no, you the frontend requires some backend components to run properly. but there are deb & rpm packages, init scripts & systemd, should be super quick and easy to migrate.

You can still use apache to reverse proxy grafana, if you want apache to be the public facing web server.

**Comment by torkelo** [comment]
Or to clarify the frontend requires many backend components. There was a standlone mode for a short while but it made the frontend code very complex and brittle, after a user survery only a very tiny minory carred about standalone mode, so it was dropped in order to spend more time on useful features instead.

**Comment by axel22** [comment]
So unfortunate that there is no standalone mode. :(

**Comment by nickman** [comment]
I agree, but only because I am serving 1.x off Solaris servers ...  No
golang you see .... Soon though, so I hear.
