### ISSUE TITLE
grafana.com community dashboards and plugins UI enhancements

### ISSUE THREAD

**Issue by daledude** [grafana/grafana#19484]
**What would you like to be added**:
This is related to #14682. It's closed and I don't see anything on the roadmap as was stated. I think it would be useful to allow sorting by the other metadata you capture as well as download count. i.e. submitter, reviews, date last updated, date added, etc.

**Comment by hugohaggmark** [comment]
Thank you @daledude for taking the time to add this, we'll have a look and see what we can do. Closing this as I've moved this issue to internal repo.

**Comment by zimmertr** [comment]
Would love for this to be supported

**Comment by hugohaggmark** [comment]
ping @DanCech

**Comment by holmesb** [comment]
Any ETA?  Sorting by downloads is pretty MVP

**Comment by zimmertr** [comment]
You ever comment on so many GitHub feature request threads that eventually you stop remembering why you needed them to begin with? 

Something something [Pareto Principle.](https://en.wikipedia.org/wiki/Pareto_principle)

**Comment by DanCech** [comment]
We're tracking this in our internal repo for grafana.com, we'll be adding some new features to the dashboards system soon!

**Comment by holmesb** [comment]
> We're tracking this in our internal repo for grafana.com

In that case perhaps the best public representation of this status is an open github issue.  I assume you will not provide read-only access to your internal issue tracker, in which case, since this issue is not closed, how can people easily distinguish between issues such as this that you assure are being worked on, and issues that have been resolved?  

Closed github issues provide better optics for a project than open ones.  I hope this isn't a "sweeping under the carpet" exercise, because the resulting loss of urgency for improvements will be damaging for grafana.
