### ISSUE TITLE
6.4.0: Stacked graphs not sorted by query order anymore

### ISSUE THREAD

**Issue by der-eismann** [grafana/grafana#19529]
**What happened**: After updating to Grafana 6.4.0 my stacked graphs for memory consumption (and others too, of course) have a seemingly random order.

**What you expected to happen**: Keep the previous behavior and show graphs in the same order as they were queried.

**How to reproduce it (as minimally and precisely as possible)**: Query multiple metrics from prometheus, stack them and try to manually adjust their order.

**Anything else we need to know?**:
Screenshot from Grafana 6.3.5:
![screenshot_6 3 5](https://user-images.githubusercontent.com/10406217/65966924-0d714b00-e461-11e9-8101-2de6ec498232.png)

Screenshot from Grafana 6.4.0:
![screenshot_6 4 0](https://user-images.githubusercontent.com/10406217/65966931-13ffc280-e461-11e9-8264-2a94c90bb92b.png)

**Environment**:
- Grafana version: 6.4.0
- Data source type & version: Prometheus 2.12.0
- OS Grafana is installed on: Official docker container & CoreOS
- User OS & Browser: Chrome 77
- Grafana plugins: Default

**Comment by der-eismann** [comment]
Another thing I noticed is that the axes show by default a lot of decimals, this was also different in the old version.
![screenshot](https://user-images.githubusercontent.com/10406217/65972444-229ea780-e46a-11e9-994d-d69133d13bc7.png)

**Comment by marefr** [comment]
Similar to #19448, maybe the same underlying problem?

**Comment by wtip** [comment]
I'm having the same issue.
For example with this dashboard https://grafana.com/grafana/dashboards/405
for prometheus and node_exporter.

**Comment by joker234** [comment]
Same issue here, the charts also change the colour when the dashboard refreshes. (Grafana 6.4.1)

**Comment by wtip** [comment]
Yes the big problem is that the colors change. Previously you could rely on the sort order to have predictable colors. Since they are random now the colors are always different

**Comment by torkelo** [comment]
Not sure how this ever worked before. In v6.3 Prometheus issues each query one by one, then combined the result, but the sorting was only done per query result , not on the final combined result. 

@davkal any ideas why/how the final series list (for all queries) was sorted in v6.3?

https://github.com/grafana/grafana/blob/v6.3.6/public/app/plugins/datasource/prometheus/datasource.ts#L304

**Comment by torkelo** [comment]
So to be clear this is a Prometheus only problem: 

The solution will have to be that we for non explore queries we have to wait for all queries to finish and then sort them by name & label. This sorting is currently done in the result transformer: 
https://github.com/grafana/grafana/blob/v6.3.6/public/app/plugins/datasource/prometheus/result_transformer.ts#L26 

But that is only run per query result, not on the final result (which is why I do not understand how this was not a problem in v6.3 as well)

**Comment by davkal** [comment]
The color assignenment happens on flattened index:
https://github.com/grafana/grafana/blob/dafc955338aef05af259ec361bbf1ac29454ec3a/public/app/plugins/panel/graph/data_processor.ts#L74

Processing of results happens only for results of the same query:
https://github.com/grafana/grafana/blob/dafc955338aef05af259ec361bbf1ac29454ec3a/public/app/plugins/datasource/prometheus/datasource.ts#L254

 If you have multiple queries, they will be "grouped" by the time they come in. So you can end up with `[a,b], [c,d,e]`, and sometimes `[c,d,e], [a,b]`, changing the index. I don't see a place where we order then according to request index, so that could be something to introduce to keep the dynamic feedback behavior while maintaining color stickiness.

**Comment by hugohaggmark** [comment]
Another diff is that we're using the new React Graph in 6.4.0 instead of custom Explore one in 6.3.5
