### ISSUE TITLE
Log Panel: Live tailing recreates websocket on refresh

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#19532]
**What happened**:

If you activates `Live` in the log panels and set the dashboard to refresh every 5s, the websocket is recreated every 5s and the panel doesn't update anymore.
![image](https://user-images.githubusercontent.com/1053421/65968435-23ffae00-e431-11e9-8953-19b5b584fcbc.png)

**What you expected to happen**:

Dashboard refresh should not affect live tailing log panel, only refresh the panel when not tailing.

**How to reproduce it (as minimally and precisely as possible)**:

1 - Create a new log panel and activate live.
2 - set up the dashboard to refresh every 5s
3 - look at all websocket opening in console.

**Environment**:
- Grafana version: Grafana v6.5.0-pre (ed03338)
- Data source type & version: Loki
- User OS & Browser: Chrome

/cc @davkal

**Comment by hugohaggmark** [comment]
Good catch @cyriltovena

**Comment by aocenas** [comment]
@davkal as we removed the Live option in dashboard should we close this or give it low priority?

**Comment by davkal** [comment]
Can you please check if Explore is affected as well?

**Comment by s-h-a-d-o-w** [comment]
@davkal I just checked this in Explore and setting the refresh to 5s and switching on Live does not result in multiple websocket connections.

(But there is odd behavior in that the query button says "Cancel" during live mode and if one clicks it, the websocket connection is killed but the UI state doesn't change. One stays in live mode without actually receiving live updates. Seems to me like the "run query" button should merely get disabled in the first place, since there are the two "stop" buttons for exiting the live mode anyway. Should I create a separate issue for that?)

**Comment by aocenas** [comment]
@s-h-a-d-o-w yes that is a bug, if in live tail the run button should not change to cancel. Can you create an issue for that? cc @kaydelaney

**Comment by Estrax** [comment]
Live tailing in dashboards was removed some time ago, in Explore it doesn't start multiple websocket connections. Closing this issue.

**Comment by Estrax** [comment]
@aocenas filled in an issue: https://github.com/grafana/grafana/issues/24079
