### ISSUE TITLE
Singlestat background or value color not applied for string values (when there is no value mapping or thresholds)

### ISSUE THREAD

**Issue by ramivis** [grafana/grafana#19548]
after upgrade from 6.3.5 to 6.4 the singlestat background broken if return is string

![img1](https://user-images.githubusercontent.com/47853421/66005450-deb79c80-e481-11e9-922f-becb20d252c9.png)

This only happens when there is a string value, and no value mappings or thresholds

**Comment by torkelo** [comment]
have you mapped the string to a value? What are your singlestat panel options?

**Comment by cicciopizza** [comment]
same problem:
in grafana 6.3.5 the visualization option of singlestat has:
![Selezione_066](https://user-images.githubusercontent.com/26459829/66034048-c5a5fe80-e508-11e9-9080-813fedd07f5a.png)
uptime is the column of mysql query:
![Selezione_067](https://user-images.githubusercontent.com/26459829/66034146-f8e88d80-e508-11e9-87dd-749b6a400a5d.png)

and the singlestat backgroung is correctly displayed in blue:
![Selezione_070](https://user-images.githubusercontent.com/26459829/66034495-a0fe5680-e509-11e9-8010-0f2603a67af3.png)


In grafana 6.4.1 the visualization option of singlestat has:
![Selezione_069](https://user-images.githubusercontent.com/26459829/66034329-58df3400-e509-11e9-882f-6fb49901dc12.png)

in the dropbox there is no "column" option,
and  the singlestat backgroung is BLACK:

![Selezione_071](https://user-images.githubusercontent.com/26459829/66034586-cee39b00-e509-11e9-8530-1c8d37615c6b.png)

**Comment by torkelo** [comment]
ok, so you have no thresholds you just want to set a static background color?

**Comment by ramivis** [comment]
> ok, so you have no thresholds you just want to set a static background color?

yes, in the old versions it works and not now. Now works only for numeric values.

**Comment by ramivis** [comment]
> have you mapped the string to a value? What are your singlestat panel options?

No, i dont mapped the string to a value. I dont use the threshold, just background color for the panel for any value (number or text)

**Comment by jimmybrancaccio** [comment]
Can confirm the same is happening for me. Trying to display the MySQL version. Background color used to work in 6.3.6 but does not in 6.4.1.

https://grafana.slack.com/archives/C05675Y4F/p1570124626200200

**Comment by apichart2499** [comment]
I have the same problem after upgrading to 6.4.1

**Comment by ramivis** [comment]
@torkelo need more details?

**Comment by ramivis** [comment]
what version the bug is fixed?

**Comment by hendrikvh** [comment]
This issue is best described in #19867. There is a use case where we want a singlestat's background to be set to a colour if any value is present.

This behaviour changed between `6.3.7` and `6.4.0`, affecting Singlestats with Strings while not affecting ones with numbers.

# Previous behaviour (`Grafana 6.3.7`):

Panels with Strings would be coloured with middle threshold colour. 
![previous-behaviour](https://user-images.githubusercontent.com/965952/70364721-711b5880-1896-11ea-88a0-0064960ba3e0.png)

![panelconfig-prev](https://user-images.githubusercontent.com/965952/70364772-9dcf7000-1896-11ea-9a27-26ea13fab682.png)

# Current behaviour (`Grafana 6.5.1` / build from master):
Panels will be coloured with first colour, and panels with Strings not coloured:

![current-behaviour](https://user-images.githubusercontent.com/965952/70364917-762cd780-1897-11ea-8b47-5339c66a85eb.png)

![panelconfig-now01](https://user-images.githubusercontent.com/965952/70364939-8e045b80-1897-11ea-9278-2e7c2c3aac1b.png)

Panel is now green for Numbers:
![panelconfig-now02](https://user-images.githubusercontent.com/965952/70364941-90ff4c00-1897-11ea-91ed-f0b96bca0318.png)

**Comment by dk-data** [comment]
Any idea when this will be fixed?

**Comment by SiGmAX666** [comment]
Very annoying "feature". Is there an ETA to fix?

**Comment by g3kk0** [comment]
Also just run into this. Are there any updates on when this will be fixed?

**Comment by unstable** [comment]
same issue with v6.6.2.

**Comment by Revolution1** [comment]
7.1.3 too

**Comment by torkelo** [comment]
Should be fixed in new stat panel in 7.2
