### ISSUE TITLE
Gauge font rendering does not scale correctly

### ISSUE THREAD

**Issue by ITGuyDave** [grafana/grafana#19636]
**What happened**:
Long text when using range text mappings on a gauge do not scale properly, resulting in the text overlapping the gauge itself. The scaling seems to hit a point where the gauge itself widens the value area, while also increasing the text size, resulting in only certain panel sizes being viable for use with long text in value mappings. The only workaround is to make the panel extremely large, or extremely small, or switch back to the singlestat (which is what I had to do in my case).

**What you expected to happen**:
Text scaling needs to be reviewed to adapt to all sizes appropriately, perhaps by pre-processing of the text width in line with the gauge to prevent the text appearing so large it overlaps the gauge itself; or allow manual font size similar to the legacy singlestat panel gauge (which I personally prefer, as it allows for consistent text sizes).

**How to reproduce it (as minimally and precisely as possible)**:
Create a relatively small gauge panel, and create a mapping that results in long text (e.g. "Very Poor"). The text overlaps the gauge itself depending on the panel size (simply adjust the panel size in varying width or height and this is readily observed with some sizes resulting in overlap).

**Anything else we need to know?**:
I have markers displayed on the graph also.
**Environment**:
- Grafana version: 6.4.1
- Data source type & version: InfluxDB 1.7.8
- OS Grafana is installed on: Raspbian Stretch (debian)
- User OS & Browser: Windows 10, Firefox 69.0.2
- Grafana plugins: Standard (no changes)
- Others: Screenshot attached

![image](https://user-images.githubusercontent.com/22867555/66255031-33308400-e7c2-11e9-8d8c-69912ca21cd8.png)

**Comment by CirnoT** [comment]
Additionally there's some weird behavior happening where text is rendered multiple times in different positions.

![chrome_2019-10-08_11-49-59](https://user-images.githubusercontent.com/1447794/66386175-077bec80-e9c2-11e9-99dc-bd7f8a7b5609.png)

**Comment by Agrigor** [comment]
This layered text which happens if any new value is shown, is really annoying. 
Its also happen if you resize the panel. 

In this state the gauge is unusable. Are there any plans to fix that?

Example:
![grafik](https://user-images.githubusercontent.com/8580748/70104811-83e82000-163f-11ea-9bb9-b18932fc7402.png)

**Comment by torkelo** [comment]
We have yet to replicate this after trying multiple times on different browsers. No idea yet what causes it and what the conditions are for how to replicate it 😢

**Comment by Agrigor** [comment]
Okay, no problem. maybe I can help :)

Your hint regarding the browser: In my first tests, I can reproduce it in Safari on mobile devices (iPhone and iPad) and Firefox on Windows 10 and Linux (Arch Bleeding edge distribution). All Software with the newest patches/versions.
But it's quite interesting, that I can't reproduce it in chromium. There it works like it should.

Maybe this info is helpful :)

**Comment by Agrigor** [comment]
In addition one possibility to reproduce: 
Just write sequently random values in an influxdb (or an other source where values (range with at least 4 digits) are updating all the time) and try to visualize them in a gauge. At the same time try to view it in two different browsers (Chromium/Chrome and Firefox) to see the differences.

Kind regards,
Agrigor

**Comment by CirnoT** [comment]
My screenshot is from Chromium, can replicate it by resizing panel, although depending on how it's resizes it's either more or less visible.

How it looks when page is opened:
![chrome_2019-12-05_21-22-08](https://user-images.githubusercontent.com/1447794/70270836-7a78c800-17a5-11ea-8e9f-ef3067ce6de1.png)

After changing size and bringing it back:
![chrome_2019-12-05_21-22-19](https://user-images.githubusercontent.com/1447794/70270840-7d73b880-17a5-11ea-99b8-c737758f0681.png)

If resized even more and left intact:
![chrome_2019-12-05_21-22-33](https://user-images.githubusercontent.com/1447794/70270845-7ea4e580-17a5-11ea-850e-64f832b56dfc.png)

**Comment by 0rn0lf** [comment]
Same problem here. I started using grafana yesterday. I created some panels and everything was fine until I tried to resize them.

![2020-01-15 08_51_40-Grafana](https://user-images.githubusercontent.com/35098710/72415457-c63f6980-3774-11ea-9f59-a6ddcf54918f.png)
![2020-01-15 08_52_20-Grafana](https://user-images.githubusercontent.com/35098710/72415459-c6d80000-3774-11ea-9f30-2ca60e8b8162.png)

**Comment by gelldur** [comment]
I'm using Grafana (grafana/grafana:6.7.2) docker image. It happens when I refresh dashbord: 
![image](https://user-images.githubusercontent.com/175790/79683797-b41a0f00-822c-11ea-8613-739ac142a5d7.png) or I just wait for auto refresh.

![image](https://user-images.githubusercontent.com/175790/79683658-cb0c3180-822b-11ea-9584-0feb01b5fadd.png)

![image](https://user-images.githubusercontent.com/175790/79683675-eaa35a00-822b-11ea-91c1-7092012317b8.png)

But when not using floating points it seems to work correctly. 

![image](https://user-images.githubusercontent.com/175790/79683686-ff7fed80-822b-11ea-88ea-2acf6c4220a2.png) ![image](https://user-images.githubusercontent.com/175790/79683692-07d82880-822c-11ea-90b2-abf708c94f4e.png)

When I refresh page everything looks ok, but after some time when data gets updated this happens.

Linux, Version 81.0.4044.113 (Official Build) (64-bit).

**Comment by karthanistyr** [comment]
I can confirm OP behaviour on v7.0.5 (no comment on the other issues)

![Capture_2020-07-06_11-37-40 150989926](https://user-images.githubusercontent.com/7722196/86580101-8a949800-bf7e-11ea-9c69-d310fe48e8a1.png)

It'd be nice if the text could be rendered in a safe, non overlapping zone, or alternatively, be outlined so that it remains readable (although I'm pretty sure this would violate the app's look and feel).

**Comment by Kamairo** [comment]
Why was this case closed? It still looks bad as of 7.3.6:
![image](https://user-images.githubusercontent.com/13257092/103026102-7277fb80-4553-11eb-9de8-ad9da3a81d77.png)
Could you please revisit this issue or better yet, give us an option to configure the font size manually?

**Comment by xxShoTz** [comment]
Same here.. the problem looks like is when the screen resolution is under 1080p.

![Screenshot_1](https://user-images.githubusercontent.com/65473858/103889214-cf7fbf80-50c4-11eb-9e4c-c722356510d9.png)

**Comment by MarkTurbo** [comment]
Still the same problem in v7.4.0. I upgraded a few days ago and gauges still look drunk!

I'm using chromium based Microsoft Edge (Version 88.0.705.63 (Official build) (64-bit)). All I do to reproduce the issue is...

- Create a new dashboard
- Click on 'Add new panel'
- Select Gauge
- Click on Apply

I end up with this...

![image](https://user-images.githubusercontent.com/29234864/107588684-25122500-6bb9-11eb-8ddf-258a7512b31a.png)

If I grab the corner and drag the panel around a little to resize it, I end up with this...

![image](https://user-images.githubusercontent.com/29234864/107588738-46731100-6bb9-11eb-9c33-48bde70fd692.png)

**Comment by rayures** [comment]
Still an issue with v8.2.3:
![image](https://user-images.githubusercontent.com/5716188/143437137-610aced1-66fb-44ef-995d-dad1aa39cf49.png)
@torkelo

**Comment by torkelo** [comment]
@rayures not caused by Grafana, it's caused by an external plugin, singlestat math or another singlestat plugin
