### ISSUE TITLE
CloudWatch dimension_values doesn't work for DynamoDB TableName dimension

### ISSUE THREAD

**Issue by danhbear** [grafana/grafana#19784]
**What happened**:
No data points are returned when using `dimension_values` to select the DynamoDB table names as a dimension, for a graph showing provisioned capacity or other CloudWatch metrics. Here is a sample dimension string that returns no results: `dimension_values(us-east-1, AWS/DynamoDB, ProvisionedReadCapacityUnits, TableName)`.

**What you expected to happen**:
A graph should be displayed with the `ProvisionedReadCapacityUnits` for each `TableName` dimension in the specified AWS account.

**How to reproduce it (as minimally and precisely as possible)**:
See screenshot:
<img width="1561" alt="Screen Shot 2019-10-12 at 10 41 07 AM" src="https://user-images.githubusercontent.com/631074/66705578-6486e380-ecdd-11e9-825a-b7cffc4610d5.png">

**Anything else we need to know?**:
Explicitly specifying the dimension values works as expected. It is only `dimension_values` that is not working.

**Environment**:
- Grafana version: Grafana v6.2.4 (ee01897)
- Data source type & version: CloudWatch
- OS Grafana is installed on: Linux
- User OS & Browser: Mac OS, Chrome
- Grafana plugins: CloudWatch
- Others: N/A

**Comment by papagian** [comment]
Could you also share the request/response to the CloudWatch.
Which is the query time range? Can you try increasing it?

Thank you!

**Comment by torkelo** [comment]
closing due to lack of update

**Comment by sachinvyas2012** [comment]
Hi, 

Though this issue is closed but I have a question on it - when using dimension_values(us-east-1,AWS/DynamoDB,ConsumedReadCapacityUnits,TableName) to get tables in a region, this query returns tables across AWS regions having ConsumedReadCapacityUnits as metric when using cloudwatch as datasource in Grafana. 

Ques 1) Is above query in Grafana variable supposed to return tables matching the metric name across region, if so, then what is need to specify / pass, region as parameter in query
Ques 2) How can I get tables in DynamoDB per region using a query in Grafana.

Thanks,
Sachin
