### ISSUE TITLE
Certificate trust issue with headless Chrome in grafana-image-renderer plugin

### ISSUE THREAD

**Issue by peteeckel** [grafana/grafana#19842]
I'm facing a problem with rendering graphs using the new grafana-image-renderer plugin.

When I try to render a graph, I get an error message along the lines of the following in the Grafana logfile:

```
t=2019-10-15T20:53:16+0000 lvl=eror msg="Rendering failed." logger=context userId=2 orgId=1 uname=testsysmanadm error="Rendering failed: Error: net::ERR_CERT_AUTHORITY_INVALID at https://192.168.106.102:3443/d-solo/nBvdEMtZk/graphite-metrics?orgId=1&from=1571150912888&to=1571172512888&var-Host=master1&panelId=4&width=1000&height=500&tz=Europe%2FBerlin&render=1"
t=2019-10-15T20:53:16+0000 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=testsysmanadm method=GET path=/render/d-solo/nBvdEMtZk/graphite-metrics status=500 remote_addr=192.168.106.101 time_ms=297 size=1722 referer="https://grafana.xxx.xx/d/nBvdEMtZk/graphite-metrics?orgId=1"
```

This seems to be a result of headless chrome not accepting the CA the certificate running on the physical server has been signed with. 

Environment: 
* CentOS 7.6
* Grafana 6.4.2
* Grafana Image Renderer 1.0.5

The certificate in question has been signed by an internal CA, which has been installed properly in the machine's trust store (`/etc/pki/tls/certs`). OpenSSL properly validates it:

```
[root@master2 grafana-image-renderer]# openssl s_client -connect 192.168.106.102:3443
CONNECTED(00000003)
depth=2 C = DE, [...]
verify return:1
depth=1 C = DE, [...]
verify return:1
depth=0 C = DE,  [...]
verify return:1
---
[...]
    Start Time: 1571173961
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

I have two issues with this: 
* The server/port to connect to for rendering the image does not seem to be configurable (i.e. run against the LB endpoint instead of the local Grafana server)
* There is no documentation on how to configure the trust store/additional trusted CAs for the embedded headless chrome, and I couldn't figure it out yet.

Am I missing something?

**Comment by marefr** [comment]
Have you installed the grafana-image-renderer as a [plugin](https://grafana.com/docs/administration/image_rendering/#grafana-image-renderer-plugin) or as a [remote rendering service](https://grafana.com/docs/administration/image_rendering/#remote-rendering-service)? Please include your Grafana configuration (strip out any sensitive information) and explain what public address (load balancer) is that you use to access Grafana.

**Comment by peteeckel** [comment]
* The renderer is installed locally as a plugin on both Grafana servers. 

* The configuration of the servers is as follows:

```
instance_name = master1.xxx.xx

[server]
protocol = https
http_addr = 192.168.106.101
http_port = 3443
cert_file = /etc/pki/grafana/certs/grafana.crt.pem
cert_key = /etc/pki/grafana/private/grafana.key.pem
root_url = %(protocol)s://%(domain)s:/
router_logging = false

[database]
type = postgres
host = 192.168.106.50
name = grafana
user = grafana
password = xxx
ssl_mode = verify-full
ca_cert_path = /etc/pki/tls/certs/hbr-dev-root-ca.crt.pem
max_idle_conn = 10

[remote_cache]
type = memcached
connstr = 127.0.0.1:11211

[analytics]
reporting_enabled = false
check_for_updates = false

[security]
admin_user = admin
admin_password = xxx
secret_key = xxx
disable_gravatar = true
login_remember_days = 1
cookie_secure = true
cookie_samesite = strict
strict_transport_security = true
strict_transport_security_max_age_seconds = 31556926
strict_transport_security_preload = true
strict_transport_security_subdomains = false
x_content_type_options = true
x_xss_protection = true

[snapshots]
external_enabled = false

[users]
allow_sign_up = false
allow_org_create = false
auto_assign_org = true

[auth.basic]
enabled = false

[alerting]
enabled = false

[metrics]
enabled           = true
interval_seconds  = 60

[metrics.graphite]
address = 192.168.106.51:2003
prefix = grafana.%(instance_name)s.

[auth.ldap]
enabled = true
config_file = /etc/grafana/ldap.toml
allow_sign_up = true
```

The configuration of the other server is essentially the same apart from instance_name and http_addr:

```
lagavulin:Desktop pete$ diff master*
1c1
< instance_name = master1.xxx.xx
---
> instance_name = master2.xxx.xx
5c5
< http_addr = 192.168.106.101
---
> http_addr = 192.168.106.102
```

The HA setup is as according to the following schematic:

![Grafana HA](https://user-images.githubusercontent.com/6815386/66904785-f9068400-f004-11e9-86d8-e1a124664a70.png)

**Comment by peteeckel** [comment]
Additional update: The certificate itself is not the issue, all relevant host names an IP addresses are in the SubjectAltName:

```
X509v3 Subject Alternative Name: 
    DNS:master1.xxx.xx IP Address:192.168.106.101, DNS:master2.xxx.xx, IP Address:192.168.106.102, IP Address:192.168.106.52, DNS:grafana.xxx.xx
```

**Comment by peteeckel** [comment]
I just tried the following to add the root/intermediate certificates to the NSS database in the hope of making them known and trusted to chrome: 

```
certutil -d sql:/etc/pki/nssdb -A -n hbr-dev-root-ca -t TC -i /etc/pki/tls/certs/hbr-dev-root-ca.crt.pem
certutil -d sql:/etc/pki/nssdb -A -n hbr-dev-subca01 -t TC -i /etc/pki/tls/certs/hbr-dev-subca01.crt.pem
```
No luck. The problem persists. 

The same attempt with a user specific `nssdb` for the `grafana` user:
```
certutil -d sql:/usr/share/grafana/.pki/nssdb -A -n hbr-dev-root-ca -t TC -i /etc/pki/tls/certs/hbr-dev-root-ca.crt.pem
certutil -d sql:/usr/share/grafana/.pki/nssdb -A -n hbr-dev-subca01 -t TC -i /etc/pki/tls/certs/hbr-dev-subca01.crt.pem
```
Doesn't work either. Still the same error message. 

Unfortunately setting the render log level to debug doesnt' provide much more enlightenment (at least not to me):
```
t=2019-10-16T13:28:23+0000 lvl=dbug msg="plugin started" logger=rendering path=/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64 pid=29722
t=2019-10-16T13:28:23+0000 lvl=dbug msg="waiting for RPC address" logger=rendering path=/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64
t=2019-10-16T13:28:23+0000 lvl=dbug msg="using plugin" logger=rendering version=1
t=2019-10-16T13:28:23+0000 lvl=dbug msg="Renderer plugin started" logger=rendering
t=2019-10-16T13:28:54+0000 lvl=dbug msg="Error Error: net::ERR_CERT_AUTHORITY_INVALID at https://192.168.106.101:3443/d-solo/nBvdEMtZk/graphite-metrics?orgId=1&refresh=30s&from=1571209623674&to=1571231223674&var-Host=master1&panelId=6&width=1000&height=500&tz=Europe%2FBerlin&render=1" logger=rendering
t=2019-10-16T13:28:54+0000 lvl=dbug msg="    at navigate (/snapshot/grafana-image-renderer/node_modules/puppeteer/lib/Page.js:602:37)" logger=rendering
t=2019-10-16T13:28:54+0000 lvl=dbug msg="    at process._tickCallback (internal/process/next_tick.js:68:7)" logger=rendering
t=2019-10-16T13:28:54+0000 lvl=eror msg="Rendering failed." logger=context userId=2 orgId=1 uname=testsysmanadm error="Rendering failed: Error: net::ERR_CERT_AUTHORITY_INVALID at https://192.168.106.101:3443/d-solo/nBvdEMtZk/graphite-metrics?orgId=1&refresh=30s&from=1571209623674&to=1571231223674&var-Host=master1&panelId=6&width=1000&height=500&tz=Europe%2FBerlin&render=1"
t=2019-10-16T13:28:54+0000 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=testsysmanadm method=GET path=/render/d-solo/nBvdEMtZk/graphite-metrics status=500 remote_addr=192.168.106.101 time_ms=315 size=1722 referer="https://grafana.xxx.xx/d/nBvdEMtZk/graphite-metrics?orgId=1&refresh=30s"
```

**Comment by torkelo** [comment]
The reason for your error is that your root_url is different from your cert domain name 

If your binding https with custom cert, I recommend use the callback_url property, set it to the full url you access your grafana server in the browser. 


 https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L688

**Comment by peteeckel** [comment]
Thanks a lot for the update and the pointer. Unfortunately, it doesn't help much - the problem persists.

I set callback_url like you suggested:
```
[rendering]
callback_url = https://grafana.xxx.xxx
```
which is **exactly** the URL used to connect to Grafana via browser.

The result is pretty much the same as before:
```
t=2019-12-03T13:43:23+0000 lvl=info msg="Renderer plugin started" logger=rendering chromeBin=/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome ignoreHttpsErrors=false timestamp=0001-01-01T00:00:00.000Z
t=2019-12-03T13:43:49+0000 lvl=dbug msg="Render request received" logger=rendering url="https://192.168.106.102:3443/d-solo/zxDJxNaZk/graphite-metrics?orgId=1&refresh=1m&from=1575355805570&to=1575377405570&var-Host=master1&panelId=6&width=1000&height=500&tz=Europe%2FBerlin&render=1" timestamp=0001-01-01T00:00:00.000Z
t=2019-12-03T13:43:49+0000 lvl=eror msg="Render request failed" logger=rendering url="https://192.168.106.102:3443/d-solo/zxDJxNaZk/graphite-metrics?orgId=1&refresh=1m&from=1575355805570&to=1575377405570&var-Host=master1&panelId=6&width=1000&height=500&tz=Europe%2FBerlin&render=1" error=map[] timestamp=0001-01-01T00:00:00.000Z
t=2019-12-03T13:43:49+0000 lvl=eror msg="Rendering failed." logger=context userId=1 orgId=1 uname=admin error="Rendering failed: Error: net::ERR_CERT_AUTHORITY_INVALID at https://192.168.106.102:3443/d-solo/zxDJxNaZk/graphite-metrics?orgId=1&refresh=1m&from=1575355805570&to=1575377405570&var-Host=master1&panelId=6&width=1000&height=500&tz=Europe%2FBerlin&render=1"
t=2019-12-03T13:43:49+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/zxDJxNaZk/graphite-metrics status=500 remote_addr=192.168.106.101 time_ms=247 size=1722 referer=
```

I also tried to have the renderer ignore HTTPS errors, without success as well:
```
t=2019-12-03T13:53:17+0000 lvl=info msg="Renderer plugin started" logger=rendering chromeBin=/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome ignoreHttpsErrors=true timestamp=0001-01-01T00:00:00.000Z
t=2019-12-03T13:54:03+0000 lvl=dbug msg="Render request received" logger=rendering url="https://192.168.106.102:3443/d-solo/zxDJxNaZk/graphite-metrics?orgId=1&refresh=1m&from=1575355805570&to=1575377405570&var-Host=master1&panelId=6&width=1000&height=500&tz=Europe%2FBerlin&render=1" timestamp=0001-01-01T00:00:00.000Z
t=2019-12-03T13:54:03+0000 lvl=eror msg="Render request failed" logger=rendering url="https://192.168.106.102:3443/d-solo/zxDJxNaZk/graphite-metrics?orgId=1&refresh=1m&from=1575355805570&to=1575377405570&var-Host=master1&panelId=6&width=1000&height=500&tz=Europe%2FBerlin&render=1" error=map[] timestamp=0001-01-01T00:00:00.000Z
t=2019-12-03T13:54:03+0000 lvl=eror msg="Rendering failed." logger=context userId=1 orgId=1 uname=admin error="Rendering failed: Error: net::ERR_CERT_AUTHORITY_INVALID at https://192.168.106.102:3443/d-solo/zxDJxNaZk/graphite-metrics?orgId=1&refresh=1m&from=1575355805570&to=1575377405570&var-Host=master1&panelId=6&width=1000&height=500&tz=Europe%2FBerlin&render=1"
t=2019-12-03T13:54:03+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/zxDJxNaZk/graphite-metrics status=500 remote_addr=192.168.106.101 time_ms=230 size=1722 referer="https://grafana.xxx.xxxd/zxDJxNaZk/graphite-metrics?orgId=1&refresh=1m&from=1575355805570&to=1575377405570&var-Host=master1&panelId=6&fullscreen"
```

**Comment by torkelo** [comment]
that is very strange (that setting callback_url did not have an effect) did you restart grafana-server in between?

**Comment by peteeckel** [comment]
Definitely, yes. Several times.

**Comment by peteeckel** [comment]
I just did a quick check regarding callback_url by setting it to the URL of a web server I control. Grafana doesn't even try to access it when I request a graph to be renderered, but the error in the Grafana log stays exactly the same, so the failure must be in a different (earlier) stage of processing the render request.

**Comment by marefr** [comment]
@peteeckel we just published 1.0.7 of the plugin which had a bug regarding ignoring HTTPS errors. Please try that out https://grafana.com/grafana/plugins/grafana-image-renderer

**Comment by peteeckel** [comment]
Just tried it: Same as before.

```
t=2019-12-03T17:08:56+0000 lvl=info msg="Renderer plugin started" logger=rendering chromeBin=/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome ignoreHttpsErrors=true timestamp=0001-01-01T00:00:00.000Z
t=2019-12-03T17:09:23+0000 lvl=dbug msg="Render request received" logger=rendering url="https://192.168.106.102:3443/d-solo/zxDJxNaZk/graphite-metrics?orgId=1&refresh=1m&from=1575371279773&to=1575392879773&var-Host=master1&panelId=4&width=1000&height=500&tz=Europe%2FBerlin&render=1" timestamp=0001-01-01T00:00:00.000Z
t=2019-12-03T17:09:23+0000 lvl=eror msg="Render request failed" logger=rendering url="https://192.168.106.102:3443/d-solo/zxDJxNaZk/graphite-metrics?orgId=1&refresh=1m&from=1575371279773&to=1575392879773&var-Host=master1&panelId=4&width=1000&height=500&tz=Europe%2FBerlin&render=1" error=map[] timestamp=0001-01-01T00:00:00.000Z
t=2019-12-03T17:09:23+0000 lvl=eror msg="Rendering failed." logger=context userId=1 orgId=1 uname=admin error="Rendering failed: Error: net::ERR_CERT_AUTHORITY_INVALID at https://192.168.106.102:3443/d-solo/zxDJxNaZk/graphite-metrics?orgId=1&refresh=1m&from=1575371279773&to=1575392879773&var-Host=master1&panelId=4&width=1000&height=500&tz=Europe%2FBerlin&render=1"
t=2019-12-03T17:09:23+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/zxDJxNaZk/graphite-metrics status=500 remote_addr=192.168.106.101 time_ms=269 size=1722 referer="https://grafana.xxx.xxx/d/zxDJxNaZk/graphite-metrics?orgId=1&refresh=1m"
```

**Comment by peteeckel** [comment]
```
[root@master1 grafana]# grafana-cli plugins ls 
installed plugins:
grafana-image-renderer @ 1.0.7 

Restart grafana after installing plugins . <service grafana-server restart>
```

And yes, I **did** restart :-)

**Comment by sakjur** [comment]
@peteeckel While I tested the image renderer plugin I had a problem with upgrading the plugin while running Grafana, I've reported that as #20841.

Did you shut down Grafana before installing 1.0.7?

> t=2019-12-03T17:08:56+0000 lvl=info msg="Renderer plugin started" logger=rendering chromeBin=/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome **ignoreHttpsErrors=true** timestamp=0001-01-01T00:00:00.000Z

the bold part _should_ be `ignoreHTTPSErrors` in 1.0.7.

**Comment by peteeckel** [comment]
In fact no, I just ran `grafanacli plugins install` while Grafana was running.

So I just shut down Grafana, then removed and re-installed the renderer plugin. Now it looks much better:

```
t=2019-12-03T17:26:15+0000 lvl=info msg="Renderer plugin found, starting" logger=rendering cmd=plugin_start_linux_amd64
t=2019-12-03T17:26:15+0000 lvl=dbug msg="starting plugin" logger=rendering path=/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64 args=[/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64]
t=2019-12-03T17:26:15+0000 lvl=dbug msg="plugin started" logger=rendering path=/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64 pid=26941
t=2019-12-03T17:26:15+0000 lvl=dbug msg="waiting for RPC address" logger=rendering path=/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64
t=2019-12-03T17:26:15+0000 lvl=dbug msg="using plugin" logger=rendering version=1
t=2019-12-03T17:26:15+0000 lvl=info msg="Renderer plugin started" logger=rendering chromeBin=/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome ignoreHTTPSErrors=true timestamp=0001-01-01T00:00:00.000Z
```

... and for the first time the rendering plugin actually renders a graph for me - so it's definitely a certificate trust issue that can be worked around by ignoring HTTPS errors. 

Just for the sake of better security: Is there a similar way to point the headless chrome browser to a specific CA certificate or OpenSSL style CA dir? Just ignoring HTTPS issues works (now), but it isn't really the best possible solution. 

Anyway, thanks a lot!

**Comment by peteeckel** [comment]
Just for the record: This also works without setting the callback_url:

```
t=2019-12-03T17:36:24+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/1/render status=502 remote_addr=192.168.106.101 time_ms=6 size=0 referer="https://grafana.xxx.xxx/d/zxDJxNaZk/graphite-metrics?orgId=1&refresh=1m&fullscreen&panelId=4"
t=2019-12-03T17:36:26+0000 lvl=dbug msg="Render request received" logger=rendering url="https://192.168.106.102:3443/d-solo/zxDJxNaZk/graphite-metrics?orgId=1&refresh=1m&panelId=4&from=1575372835601&to=1575394435601&var-Host=master1&width=1000&height=500&tz=Europe%2FBerlin&render=1" timestamp=0001-01-01T00:00:00.000Z
```

**Comment by marefr** [comment]
@peteeckel great :+1: Thanks. Would suggest open a feature request regarding CA dir at https://github.com/grafana/grafana-image-renderer. Yeah the `callback_url` is only needed when running remote rendering service (not installed as plugin).

**Comment by sakjur** [comment]
> Just for the sake of better security: Is there a similar way to point the headless chrome browser to a specific CA certificate or OpenSSL style CA dir? Just ignoring HTTPS issues works (now), but it isn't really the best possible solution.

`grafana-image-renderer` is using Puppeteer which doesn't seem to have APIs available for that based on my quick look. It might be possible for us to override that in some other way or somehow push for support for custom certificate handling in Puppeteer, it would definitely be preferable to instructing people to turn off HTTPS validation.

Great that the rendering works for you now and thanks for the report! 🙂

**Comment by kamisas** [comment]
> In fact no, I just ran `grafanacli plugins install` while Grafana was running.
> 
> So I just shut down Grafana, then removed and re-installed the renderer plugin. Now it looks much better:
> 
> ```
> t=2019-12-03T17:26:15+0000 lvl=info msg="Renderer plugin found, starting" logger=rendering cmd=plugin_start_linux_amd64
> t=2019-12-03T17:26:15+0000 lvl=dbug msg="starting plugin" logger=rendering path=/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64 args=[/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64]
> t=2019-12-03T17:26:15+0000 lvl=dbug msg="plugin started" logger=rendering path=/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64 pid=26941
> t=2019-12-03T17:26:15+0000 lvl=dbug msg="waiting for RPC address" logger=rendering path=/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64
> t=2019-12-03T17:26:15+0000 lvl=dbug msg="using plugin" logger=rendering version=1
> t=2019-12-03T17:26:15+0000 lvl=info msg="Renderer plugin started" logger=rendering chromeBin=/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome ignoreHTTPSErrors=true timestamp=0001-01-01T00:00:00.000Z
> ```
> 
> ... and for the first time the rendering pluygin actually renders a graph for me - so it's definitely a certificate trust issue that can be worked around by ignoring HTTPS errors.
> 
> Just for the sake of better security: Is there a similar way to point the headless chrome browser to a specific CA certificate or OpenSSL style CA dir? Just ignoring HTTPS issues works (now), but it isn't really the best possible solution.
> 
> Anyway, thanks a lot!

Hi Peteeckel, call u tell me how to resolve the problem ? where i can configure ignoring HTTPS errors ?
Thanks dude!
![certError](https://user-images.githubusercontent.com/38859759/74730413-f8455f00-523d-11ea-9a67-3d74212fa569.PNG)

**Comment by marefr** [comment]
@kamisas see environment variables https://grafana.com/grafana/plugins/grafana-image-renderer

**Comment by kamisas** [comment]
> @kamisas see environment variables https://grafana.com/grafana/plugins/grafana-image-renderer. Or if running using docker see https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md#environment-variables

I am using Ubuntu 18.04, and when type GF_RENDERER_PLUGIN_IGNORE_HTTPS_ERRORS=true int terminal nothing happens... if i restart grafana server nothing happens... still false...
I am sorry, but I am new to these parts ... I never used environment variables in production, I think something is missing :-(
However congratulations on the grafana project! Is insane!
![Ignore2](https://user-images.githubusercontent.com/38859759/74744596-6f88ec00-525a-11ea-82db-b9c1d63a4192.PNG)

**Comment by kozsoo33** [comment]
Hi,
I have just upgrade to 7.0 and lost the image rendering.
I tried install render plugin with grafana-cli, no success, maybe has no fw rules for it.

<pre>
[root@tool chrome-linux]#  grafana-cli plugins install grafana-image-renderer
Error: â Failed to send request: Get "https://grafana.com/api/plugins/repo/grafana-image-renderer": proxyconnect tcp: dial tcp: lookup https on 172.28.18.1:53: no such host
</pre>

I made manual install, downloading the plugin.
I can see the plugin as unsigned and not sure if it is loaded properly.

<pre>
t=2020-05-27T10:27:28+0200 lvl=info msg=Rendering logger=rendering renderer=plugin path="d-solo/GWrmds_iz/cdrcheck?orgId=1&from=1587971691483&to=1590563691484&panelId=2&width=1000&height=500&tz=Europe%2FBudapest"
t=2020-05-27T10:27:28+0200 lvl=dbug msg="Calling renderer plugin" logger=rendering renderer=plugin req="url:\"https://localhost:8443/d-solo/GWrmds_iz/cdrcheck?orgId=1&from=1587971691483&to=1590563691484&panelId=2&width=1000&height=500&tz=Europe%2FBudapest&render=1\" width:1000 height:500 deviceScaleFactor:1 filePath:\"/var/lib/grafana/png/lyCmk1WKeCBsT5YgJppl.png\" renderKey:\"nFC10cKzKAq2t34pgzOWWqfeP1DA9iCY\" domain:\"localhost\" timeout:60 timezone:\"Europe/Budapest\" headers:<key:\"Accept-Language\" value:<values:\"hu-HU,hu;q=0.9,en-US;q=0.8,en;q=0.7\" > > "
t=2020-05-27T10:27:28+0200 lvl=dbug msg="Render request received" logger=plugins.backend pluginId=grafana-image-renderer url="https://localhost:8443/d-solo/GWrmds_iz/cdrcheck?orgId=1&from=1587971691483&to=1590563691484&panelId=2&width=1000&height=500&tz=Europe%2FBudapest&render=1"
t=2020-05-27T10:27:29+0200 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=5
t=2020-05-27T10:27:29+0200 lvl=dbug msg="Setting extra HTTP headers for page" logger=plugins.backend pluginId=grafana-image-renderer headers="map[Accept-Language:hu-HU,hu;q=0.9,en-US;q=0.8,en;q=0.7]"
t=2020-05-27T10:27:29+0200 lvl=eror msg="Browser request failed" logger=plugins.backend pluginId=grafana-image-renderer url="https://localhost:8443/d-solo/GWrmds_iz/cdrcheck?orgId=1&from=1587971691483&to=1590563691484&panelId=2&width=1000&height=500&tz=Europe%2FBudapest&render=1" method=GET failure=net::ERR_CERT_AUTHORITY_INVALID
t=2020-05-27T10:27:29+0200 lvl=eror msg="Render request failed" logger=plugins.backend pluginId=grafana-image-renderer url="https://localhost:8443/d-solo/GWrmds_iz/cdrcheck?orgId=1&from=1587971691483&to=1590563691484&panelId=2&width=1000&height=500&tz=Europe%2FBudapest&render=1" error="Error: net::ERR_CERT_AUTHORITY_INVALID at https://localhost:8443/d-solo/GWrmds_iz/cdrcheck?orgId=1&from=1587971691483&to=1590563691484&panelId=2&width=1000&height=500&tz=Europe%2FBudapest&render=1"
t=2020-05-27T10:27:29+0200 lvl=eror msg="Rendering failed." logger=context userId=1 orgId=1 uname=admin error="Rendering failed: Error: net::ERR_CERT_AUTHORITY_INVALID at https://localhost:8443/d-solo/GWrmds_iz/cdrcheck?orgId=1&from=1587971691483&to=1590563691484&panelId=2&width=1000&height=500&tz=Europe%2FBudapest&render=1"
t=2020-05-27T10:27:29+0200 lvl=dbug msg="token needs rotation" logger=auth tokenId=220 authTokenSeen=true rotatedAt=2020-05-27T09:10:54+0200
t=2020-05-27T10:27:29+0200 lvl=dbug msg="auth token rotated" logger=auth affected=1 auth_token_id=220 userId=1
t=2020-05-27T10:27:29+0200 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/GWrmds_iz/cdrcheck status=500 remote_addr=10.201.141.8 time_ms=1737 size=1723 referer="https://tool.xxxxxx.intra:8443/d/GWrmds_iz/cdrcheck?orgId=1"
</pre>

I have tried to add internal or root CA to the nssdb, no success.
(I have signed cert by company, company internal CA, company root CA) 

Tried with these configs also:
<pre>
[plugins]
allow_loading_unsigned_plugins = grafana-image-renderer

[log]
filters = rendering:debug

[rendering]
callback_url = https://tool.xxxxxx.intra
rendering_ignore_https_errors = true
rendering_verbose_logging = debug
</pre>

Should ignore_https_errors ignore the certificate problem also?
I can see "ignoresHttpsErrors:false" instead of true.

<pre>
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Initializing PluginManager" logger=server
t=2020-05-27T10:51:28+0200 lvl=info msg="Starting plugin search" logger=plugins
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Scanning core plugin directory" logger=plugins dir=/usr/share/grafana/public/app/plugins
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Scanning bundled plugins directory" logger=plugins dir=/usr/share/grafana/plugins-bundled
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Transform plugin is disabled since the expressions feature toggle is not enabled" logger=plugins pluginID=gel
t=2020-05-27T10:51:28+0200 lvl=info msg="Registering plugin" logger=plugins name="Direct Input"
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Scanning external plugins directory" logger=plugins dir=/var/lib/grafana/plugins
t=2020-05-27T10:51:28+0200 lvl=info msg="Registering plugin" logger=plugins name="Graph Compare Panel"
t=2020-05-27T10:51:28+0200 lvl=info msg="Registering plugin" logger=plugins name="Grafana Image Renderer"
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Registering backend plugin" logger=plugins.backend pluginId=grafana-image-renderer executablePath=/var/lib/grafana/plugins/plugin-linux-x64-glibc/plugin_start_linux_amd64
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Backend plugin registered" logger=plugins.backend pluginId=grafana-image-renderer executablePath=/var/lib/grafana/plugins/plugin-linux-x64-glibc/plugin_start_linux_amd64
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Getting signature state of plugin" logger=plugins plugin=input
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Verifying contents of plugin manifest" logger=plugins plugin=input
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Getting signature state of plugin" logger=plugins plugin=grafana-image-renderer
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Getting signature state of plugin" logger=plugins plugin=graph-compare-panel
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Initializing AlertEngine" logger=server
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Initializing QuotaService" logger=server
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Initializing ServerLockService" logger=server
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Initializing UserAuthTokenService" logger=server
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Initializing DatasourceCacheService" logger=server
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Initializing LoginService" logger=server
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Initializing provisioningServiceImpl" logger=server
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Looking for alert notification provisioning files" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers
t=2020-05-27T10:51:28+0200 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers error="open /etc/grafana/provisioning/notifiers: no such file or directory"
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Initializing InternalMetricsService" logger=server
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Initializing TracingService" logger=server
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Initializing UsageStatsService" logger=server
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Initializing CleanUpService" logger=server
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Initializing NotificationService" logger=server
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Looking for App Dashboard Updates" logger=plugins
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Plugins: Adding route" logger=http.server route=/public/plugins/graph-compare-panel dir=/var/lib/grafana/plugins/graph-compare-panel-master/dist
t=2020-05-27T10:51:28+0200 lvl=dbug msg="starting plugin" logger=plugins.backend pluginId=grafana-image-renderer path=/var/lib/grafana/plugins/plugin-linux-x64-glibc/plugin_start_linux_amd64 args=[/var/lib/grafana/plugins/plugin-linux-x64-glibc/plugin_start_linux_amd64]
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Plugins: Adding route" logger=http.server route=/public/plugins/input dir=/usr/share/grafana/plugins-bundled/internal/input-datasource
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Plugins: Adding route" logger=http.server route=/public/plugins/grafana-image-renderer dir=/var/lib/grafana/plugins/plugin-linux-x64-glibc
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Checking for updates" logger=plugins
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Initializing Stream Manager"
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Found old rendered image to delete" logger=cleanup deleted=0 kept=0
t=2020-05-27T10:51:28+0200 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:8443 protocol=https subUrl= socket=
t=2020-05-27T10:51:28+0200 lvl=dbug msg="Waiting on services..." logger=server
t=2020-05-27T10:51:28+0200 lvl=dbug msg="plugin started" logger=plugins.backend pluginId=grafana-image-renderer path=/var/lib/grafana/plugins/plugin-linux-x64-glibc/plugin_start_linux_amd64 pid=5493
t=2020-05-27T10:51:28+0200 lvl=dbug msg="waiting for RPC address" logger=plugins.backend pluginId=grafana-image-renderer path=/var/lib/grafana/plugins/plugin-linux-x64-glibc/plugin_start_linux_amd64
t=2020-05-27T10:51:29+0200 lvl=dbug msg="Browser initialized" logger=plugins.backend pluginId=grafana-image-renderer config="map[args:[--no-sandbox] chromeBin:/var/lib/grafana/plugins/plugin-linux-x64-glibc/chrome-linux/chrome clustering:map[maxConcurrency:5 mode:browser] deviceScaleFactor:1 dumpio:false height:500 ignoresHttpsErrors:false maxDeviceScaleFactor:3 maxHeight:3000 maxWidth:3000 mode:default verboseLogging:false width:1000]"
t=2020-05-27T10:51:29+0200 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=5
t=2020-05-27T10:51:29+0200 lvl=dbug msg="Using browser version" logger=plugins.backend pluginId=grafana-image-renderer browserVersion=HeadlessChrome/79.0.3945.0
t=2020-05-27T10:51:29+0200 lvl=dbug msg="using plugin" logger=plugins.backend pluginId=grafana-image-renderer version=2


</pre>

Any idea or detailed guide is needed, thx.

**Comment by marefr** [comment]
@kozsoo33 either you configure ignore of https errors using grafana setting/environment variable:
```
[plugins.grafana-image-renderer]
rendering_ignore_https_errors = true
```

Or refer to https://grafana.com/docs/grafana/latest/administration/image_rendering/#certificate-signed-by-internal-certificate-authorities.

Also, have a look at https://grafana.com/blog/2020/05/07/grafana-7.0-preview-new-image-renderer-plugin-to-replace-phantomjs/ to understand that you can run as plugin or remote rendering service and different ways of configuration applies.
