### ISSUE TITLE
Extreme snapshotting

### ISSUE THREAD

**Issue by dvenza** [grafana/grafana#1985]
New feature request: snapshots linked to the dashboards they are generated from.

When I open a dashboard, I would be able to select from a list of "interesting time frames" that I marked as special and all the panels would shift back to that time frame I saved. They could work exactly as the current snapshot feature, but somehow linked and listed in the dashboard they are from.

If I could also add tags and descriptions to the snapshots it would even be better.

See also #1984

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
