### ISSUE TITLE
Grafana fails to start _silently_ when unknown key is declared in config.ini [database] section

### ISSUE THREAD

**Issue by jaimegago** [grafana/grafana#1992]
ubuntu 14.04
grafana 2.0.2 (debian package)

symptom
"sudo service grafana-server start" fails with no error message to be found, log file is empty

cause
Adding an unknown key=value in /etc/grafana/grafana.ini under the [database] section

I can reproduce this at will. I understand the failure, a log message would have saved me lots of trouble. FWIW the offending key was added because of bug in CM automation code.

 /etc/grafana/grafana.ini

[server]
http_addr=0.0.0.0
http_port=8080
protocol=http
[database]
type=mysql
host=127.0.0.1:3306
name=grafana
user=grafana
password=<REDACTED>
foo=bar
[security]
admin_user=admin
admin_password=admin
[users]
allow_sign_up=true
allow_org_create=false
auto_assign_org=true
auto_assign_org_role=Viewer
[auth.anonymous]
enabled=true
[session]
provider=memory
[analytics]
reporting_enabled=false

everything else is default

**Comment by torkelo** [comment]
Strange, fail to replicate this with v2.0.2

```
$ ./bin/grafana-server
2015/05/14 09:51:17 [log.go:75 Fatal()] [E] Unknown config key foo defined in section database, in file%!(EXTRA string=/home/torkel/dev/go/src/github.com/grafana/grafana/conf/custom.ini)

$ echo "$?"
1
```

Wait I see what is going on, the error is logged, but not the log file because logging to the log file is initialized after configuration is setup (config can contain log paths and settings). To fix this I have updated the settings init code so that logging is initialized after config defaults and command line configuration is read, but before the user specified config file is loaded (`/etc/grafana/grafana`) , the error "Unknown config key foo defined in section database"  is now visible in the log file. 

One other change in master is that this error is no longer considered fatal, so the grafana server will still start. What do you think about that change?

**Comment by jaimegago** [comment]
@torkelo This is perfect! Thanks for the quick fix. IMHO making sure the error is being logged + not failing to start is ideal but I thought you might have had some reasons to fail the start.
