### ISSUE TITLE
Azure Monitor: undefined is not iterable

### ISSUE THREAD

**Issue by maxilampert** [grafana/grafana#19944]
**What happened**:
Opening an Azure Monitor Log Analytics panel results in this error below the query editor, after clicking Run the error disappears, so only happens on the load of the graph configuration
![image](https://user-images.githubusercontent.com/1974396/67266560-c949f700-f4b0-11e9-80c2-14c29fa8c71b.png)

**What you expected to happen**:
No error message
**How to reproduce it (as minimally and precisely as possible)**:
Create Log Analytics query based graph
Leave the graph configuration
Edit the created graph again
The error appears
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.3
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Docker 
- User OS & Browser: Windows / Chrome 77
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Thanks for reporting this @maxilampert I can repro this on Grafana `master` 79fea5df2aeb72aafe91b118be031901d8772260

The issue seems to be this line that for some reason can be `undefined` i.e. not returned by Azure api I guess:
https://github.com/grafana/grafana/blob/79fea5df2aeb72aafe91b118be031901d8772260/public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_log_analytics/response_parser.ts#L194

**Comment by marefr** [comment]
@hugohaggmark are you planning to fix this? I tried to reproduce it but couldn't.

**Comment by hugohaggmark** [comment]
> @hugohaggmark are you planning to fix this? I tried to reproduce it but couldn't.

yes, I will.

**Comment by hugohaggmark** [comment]
I was thinking maybe someone with more knowledge about the Azure api could say if this is an expected behaviour :)
