### ISSUE TITLE
How to disable grafana menu buttons

### ISSUE THREAD

**Issue by aather** [grafana/grafana#1996]
Thanks to grafana, I was able to build a dashboard without having to know too much about java scripting and html. However, I need help with disabling some grafan menu buttons

We have clusters running in all AWS regions: us-east-1, us-west-1, us-west-2 and eu-west-1. Since graphite does not support replicas or data sharding, I decided to set up one graphite server in each region. grafana and Elasticsearch are also hosted on the same graphite server. I know grafana is a client side tool and thus can be host any where.  I have a homepage that have URL to dashboards in all regions:

![abyss-dashimage](https://cloud.githubusercontent.com/assets/5282686/7638055/17d85e7c-fa27-11e4-8fa0-152f32ade0c7.png)

Clicking a home button on dashboard takes to the same menu (shown above), no matter what dashboard users are using.  Problem is that users can overwrite the home button, or add/remove dashboards. They can also edit metrics. I want to give users read-only access to dashboards. How can I do it with grafana?

Thanks for any help you can provide.

Amer.

**Comment by torkelo** [comment]
You cant in Grafana 1.9. 

In Grafana 2.0 you can give users a "Viewer" permission that will not allow them to create or save dashboards (they can currently update graphs and queries because I see not reason to stop that because the data is accessible anyway as there is no per series permissions in graphite)
