### ISSUE TITLE
Repeating and carried over error messages

### ISSUE THREAD

**Issue by sarlinska** [grafana/grafana#20002]
**What happened**:
1. The same error message is duplicated a number of times (possibly triggered by each panel on the dashboard).
2. When going from the dashboard with error messages to a different page error messages get carried over.

![error1](https://user-images.githubusercontent.com/15225624/67506939-4c747400-f68e-11e9-844f-bd240ada876a.png)
<img width="1432" alt="error2" src="https://user-images.githubusercontent.com/15225624/67506940-4c747400-f68e-11e9-9b37-ffd74e7bbc4c.png">

**What you expected to happen**:
1. Show one error message per type.
2. Error messages should disappear when I am moving to a different page.

**Anything else we need to know?**:
An added bonus would be a better error message which quickly tells what I should investigate.

**Comment by torkelo** [comment]
the error should be automatically cleared after 7 seconds, where they not?

**Comment by sarlinska** [comment]
I think it was cleared – @Dieterbe? However, it's not enough to clear after 'x' seconds. If I am moving to a different page it should automatically clear the error messages regardless of how much time has passed. It is confusing to see those error messages on a page that has nothing to do with them.

**Comment by torkelo** [comment]
yes. agree if you quickly move to another page it should clear. But it's a bit tricky actually. As we have a few cases where we show a notification (success mostly) then switch page. So know when to clear is not straight forward. 

example when we show notification and then switch page is when deleting a data source (or use), then we show notification and then switch page.

**Comment by Dieterbe** [comment]
They cleared. I didn't count the amount of seconds.
The argument here is that by hiding the errors when you switch to a different view, you may potentially hide important information that's still relevant, or that the user still wanted to see, despite switching. Perhaps this can be solved by introducing an "error log" which is a separate panel somewhere that shows the log of all errors that have recently been shown ? (either scoped by dashboard or by session)

**Comment by amotl** [comment]
Hi there,

we don't know if this is the right place to drop our ideas about this, but we will just try to see if this resonates with you.

While working on an [improved version of Worldmap](https://github.com/panodata/grafana-map-panel), we added more detailed error signaling which we believe is crucial for the average user to setup and implement this panel. An example of this is outlined within https://github.com/panodata/luftdatenpumpe/issues/17.

However, we see that (this detailed) error signalling might not always be intended for end users at all. So, we already discussed the possibility of an out-of-band error signaling mechanism like @Dieterbe suggested:

> Perhaps this can be solved by introducing an "error log" which is a separate panel somewhere that shows the log of all errors that have recently been shown ? (either scoped by dashboard or by session)

So, we just came here to add our vote for that in order to take this into consideration for further UX improvements of Grafana.

If we are lucky, we might think about adding a respective proposal PR-wise. However, we believe we will have to digest more of the Grafana code base in order to be capable enough for that.

Thanks for listening and with kind regards,
Andreas.
