### ISSUE TITLE
Template variable query $__searchFilter tweaks

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#20006]
There are some issues with using this with Graphite tag values queries:

tag_values(host, namespace=os, name=cpu.percent.idle.g, host=~^(.*?)$__searchFilter)

Due to the fact that in this context __searchFilter is in a regex context not a normal Graphite glob/wildcard context

**Comment by nikoalch** [comment]
1. The query that gets sent always has a trailing '*' meaning 0 or more of the preceding pattern. So 'xyz' is really just 'xy'. 
2. (1) above is likely the root cause of: type in a single letter (x) and it doesn't filter from what I can tell. It seems to simply stop filtering as long as somewhere in the 10,000 drop down has a x in it. This is further illustrated by typing in xyz and then you see several xyz machines but also other non xyz machines. This is strange.
3. Again (1) above is likely the root cause of: If I type is an exact machine: xyzprxy-cc-004 I actually end up seeing two in the list xyzprxy-cc-004 and xyzprxy-cc-002 and since 4 is the 2nd I have to manually select it. An exact match should show only 1 and I shouldn't have to manually select it.
4. If I type in an exact match and then add one more char to it, it still shows the value. If I add a 2nd extra character is says there are None matching. I would expect this to happen after a single char.
5. Ranking would be very nice to have.  Ideally ranking we be implemented so that:
     1. full exact matches are highest
     2. partial matches that contain the entire entered string at the beginning are next
     3.partial matches that contain the entire entered string in the middle/end are next.
