### ISSUE TITLE
Docs feedback: http_api/data_source.md

### ISSUE THREAD

**Issue by rrey** [grafana/grafana#20048]
Hi,

It would be nice to have the list of parameters required/available for the datasource creation request body.
Having the details for each datasource type would be nice as well.

Regards

**Comment by achatterjee-grafana** [comment]
@marefr, where can I find the information to add. Thank you!

**Comment by marefr** [comment]
It's not that simple to cover each and every data source because each of them are unique. The easiest thing to do for understanding the request body when creating a data source of certain type is to use Chrome Developer Tools, or similar, and inspect the request payload of the create data source request under the Network tab.

Most of the specific data source options (JSON data and Secure JSON data) should be covered [here](https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources) for core/builtin data sources.

**Comment by achatterjee-grafana** [comment]
Removed assignment based on @marefr's comment.
