### ISSUE TITLE
Percent Diff alert methods seem to be broken.

### ISSUE THREAD

**Issue by ricky3688x** [grafana/grafana#20092]
**What happened**:
I’ve tried the percent_diff() formula, but it treats the value as absolute, not as percentage.

**What you expected to happen**:
trigger alert by percent_diff, not the value as absolute.

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/54268317/67823765-50295000-faff-11e9-8b36-90a6cb9b33c4.png)

**Environment**:
- Grafana version:V6.4.3
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome

**Comment by aocenas** [comment]
Hey @ricky3688x I think the problem is only with the visual representation of the threshold. Basically I don't think there is a way to visualize percentual threshold when you data is showing absolute values.

So the visualisation is wrong but the alert itself should work correctly (please file an issue if it doesn't).

@torkelo does it make sense to even show the threshold in this case?
