### ISSUE TITLE
Add Scatter Plot visualisation

### ISSUE THREAD

**Issue by buecking** [grafana/grafana#202]
It would be nice to view data as a scatter plot but this would likely require modifying the x-axis to something other than time.

**Comment by samhatchett** [comment]
I'm also looking for this feature in grafana. Anyone find a workable solution?

**Comment by PaulKuiper** [comment]
+1, allow the option to set the result of one of the queries on a graph as the x axis would be enough for me.

**Comment by Convolution** [comment]
+1 This would save me so much time. Currently I have to generate scatterplots separately and abuse the html component to get them in my dashboards.

**Comment by torkelo** [comment]
Can someone describe the feature in more detail, how to map a bunch of time series (value, timestamp) to the scatter plot?

**Comment by samhatchett** [comment]
I think the simplest version of this would allow the user to define a timeseries to use for the x-axis (TS1), and a timeseries to use for the y-axis (TS2). This pair of series would define a group of points to plot as long as both series are the same length and have values at the same time indexes.

How to define a second group of scatter points for the same plot would be another question - do you use the same x-axis values (TS1), or should you be able to define another series to use (e.g., TS3 vs TS4)? For my own use case, I would prefer to define each group of points separately, as in TS1-vs-TS2 and TS3-vs-TS4 on the same graph.

**Comment by victorhooi** [comment]
I would love to see scatter-plot support in Grafana as well!

To give a concrete example, one use case for us would be a scatter-graph of database queries.

The x-axis would still be time, but the y-axis would be query duration - here is a sample graph to show what I mean (done using matplotlib):

![mplotqueries_sample_plot](https://cloud.githubusercontent.com/assets/243499/8074089/ebfb7064-0f70-11e5-82b1-3b9ce01528b8.png)

In the above graph, colour represents the database (or collection) that the query was on - I could envision these just being different series in Grafana.

As you can see, visualising this data is very useful, as it shows you trends in database latency over time.

I'm looking at using InfluxDB to store this data, and Grafana to graph it.

Each point would have the timestamp, as well as the query duration (`fields.value`) - and the original query itself might be stored in a field (`fields.query_string`):

```
{
   "name": "query_durations",
   "tags": {
       "host": "server01",
       "database": "singapore",
       "collection": "rare_species",
       "type_of_query": "find","
   },
   "timestamp": "2009-11-10T23:00:00Z",
   "fields": {
       "value": 0.72,
       "query_string": "{ name: \"bob\"}"
}
```

I was also thinking of leveraging the annotations feature in Grafana somehow, so that when you hover over a point, it would show the original query (`fields.query_string`).

**Comment by bitglue** [comment]
@torkelo, here's what I understand "scatter plot" to mean:

Say you have two metrics, like "HTTP response time" and "disk queue length". And the question is, "How does the disk queue length correlate to my HTTP response times?"

What you could do then is have a graph where the X axis is the queue length, and the Y axis is the HTTP response time. Then you iterate over every point in time for the selected period ("from 1 hour ago"). For each data point in that period, you find the disk queue length and HTTP response time for that time. Then you use those values as the X and Y coordinates and draw a point on the graph. Repeat for each data point in the period.

What I'd expect to see with this example is something like, "My HTTP response times are good, until the disk queue length gets above 2 or so." Or maybe I'll see that, but a lot of points that fall outside that pattern, so I know there's some factor other than disk causing slow HTTP responses at least sometimes. Or maybe I'll see that they aren't correlated at all (maybe all my HTTP serving is done from cache?)

It would be most useful for me if there were some UI to pick two series of data, maybe not even on the same dashboard, and correlate them on the fly. Scatter plots make establishing these correlations a lot faster in complicated cases, and also help finding performance limits, like how big the IO queue can get in the example I gave. Scatter plots tend to reveal these kinds of saturation points as hockey stick shaped correlations, with the bend in the line showing the saturation point, and the spread in the points showing just how good of a predictor some metric (disk queue) is of another (HTTP response time).

**Comment by samhatchett** [comment]
__+1__ again on this, and I echo all sentiments above. A timeseries dashboard package really needs this basic feature, because some very important data characteristics can only show up when you're looking at the time dimension parametrically. Getting a picture of correlation and auto/cross-correlation is one example. Another example is to visually detect variation from an "ideal" parametric curve.

An example from the equipment monitoring industry: Say an "ideal" air blower is supposed to generate a certain range of air flow for a certain range of electrical power input. These two values are time series which, when plotted as an (x,y) scatter plot (air flow vs power), reveal a curve that emerges from the physics and fluid mechanics involved. Now, if the motor is damaged, or the propeller worn, then the measured values tend to diverge from that "ideal" curve and this is important information that will be completely lost if you are only able to look at (t,y) data for each sensor individually. I hope this is a helpful illustration of how such a display could be used.

**Comment by clongbottom** [comment]
I'm really keen for this and will try to write a plugin for is. @torkelo is there an example plugin whose style/format I could follow?

For many sensor applications plotting anything against anything else is pretty key- obviously filtered and grouped on time still. It allows visualising of patterns in the data which can't be seen in the time dimension alone.

**Comment by Stuermer** [comment]
+1

**Comment by sslupsky** [comment]
+1 this would be useful.  Another "spin" on this would be to create polar plots (Radius and Angle instead of X and Y).

**Comment by abravorus** [comment]
+1
While we are mostly using Grafana to monitor parameters against time (data sources - Graphite and ElasticSearch), it would be very useful to have parameter(s) against parameter plot. For example, power against rotation speed. 
To configure such a plot you need to specify one metric (in Graphite terms) for x-axis, and another metric(s) for y-axis. Requested set of metrics for the same timestamp will form the point(s) on the scatter plot.

**Comment by renrutnosaj** [comment]
+1

Right now we use a different package to handle the x-y plotting as reports, not live charts. Live charts within Grafana would be wonderful.

Minimal scatterplot requirement (for us) would be two series (make more plots if you want to compare more series). Pull-downs to select which series for which axis, colors, etc would be extra-nice, but not necessary for minimum viable feature set.

**Comment by cdelorenzo** [comment]
+1 scatter plot would be fantastic!!!

**Comment by mickdwyer** [comment]
+1 - very useful as lines often obscure interesting clusterings.

**Comment by axzhong3** [comment]
+1

**Comment by cnettel** [comment]
We also wanted to have this for a project. I made a fork with a very tentative solution based on some of the discussion here, i.e. use series 1 as the implicit X axis (and hide it). This also means that all series in the plot need to have exactly the same elements, through group by or naturally from the data source.

I would hope to make a pull request eventually, but it would be relevant to hear whether those doing +1 over the years would find this very limited implementation useful, or not.

https://github.com/cnettel/grafana/compare/master...scatter-plot-issue-202

**Comment by jifwin** [comment]
+1

**Comment by ikrush** [comment]
+++++++100000

**Comment by andreaaizza** [comment]
+1

**Comment by hbos** [comment]
+1

**Comment by mjtnajafi** [comment]
+1

**Comment by mjtnajafi** [comment]
+1

**Comment by dstreppa** [comment]
+1

**Comment by ashokrj** [comment]
+1

**Comment by b00lduck** [comment]
+1

**Comment by PostPrandialMickNolence** [comment]
+1

**Comment by buchbend** [comment]
+1

**Comment by samhatchett** [comment]
@cnettel - thanks for the work you've done. Your solution looks good - a nice functional starting point. Have you considered setting this up as a separate panel plugin, rather than as an extension on the standard graph panel?

**Comment by cnettel** [comment]
My motivation was that >95 % of the logic is still shared with the main panel (a difference relative to e.g. the histogram panel), although I agree that it from a user stand point it might make more sense to separate them. On the other hand, it is not unreasonable to first plot two series vs. time and then against each other, with the click of a button.

Very recently, I've been looking at my use case again, and I might fix those deficiencies that are most clear from my standpoint - basically the handling when the time stamps in the different series do not line up exactly, in my case due to two InfluxDB queries being fired with new data coming in, in between. My personal list of issues does not include refactoring it into a separate plugin, though I would of course welcome someone doing it...

**Comment by samhatchett** [comment]
I would also welcome "someone" rolling this into a plugin, since it seems pretty obvious that the mainline grafana development does not consider this to be a vital feature for inclusion in the built-in graph panel. TBH my expertise is not with js toolchains, and so i'm afraid this is a bit beyond what I have time to invest in figuring out. However assuming nobody has unsubscribed from this ancient issue, there are potentially around a dozen "+1"s that might have that capability and knowledge. @cnettel's diff shows that it's pretty trivial to get working as a prototype.

If anyone is interested in (for instance) cleaving the built-in graph panel into a separate repository as a panel plugin and get the build tools figured out, then there's a ready audience for it (see above and also #5641)! I am anxious to contribute what I can but I'm afraid that's limited to modifying existing code rather than setting up a build system for this purpose.

**Comment by abravorus** [comment]
Unfortunatelly I have not enough skills in js to contribute into scatter plot plugin development. But I still very interested in such a plugin. I will try to check @cnettel solution, may be next week. We use grafana in production environment so I have to wait some pause in our work to do any experiments.

**Comment by samhatchett** [comment]
looks like this may be an answer to the scatterplot issue: https://grafana.net/plugins/natel-plotly-panel

... even has 3-d graphs.

**Comment by sslupsky** [comment]
@samhatchett 

Thanks for the heads up.  I will have a more in-depth look at the natel plugin as they are using the same library (Plot.ly) that I choose to use.

The Natel plugin looks at first glance to be using different series for the x, y and z data.  My measurements have the coordinates of the data embedded in the measurement name.  So, I extract the x and y information from the measurement name and use the series data as the z component.  I then use the Plot.ly library (heat map) do render the plot.

Plot.ly looks very good.  I took a look at the Savantly heatmap plugin (which is really a treemap, not a heatmap) and the D3Plus library he uses.  In the end the heatmap will not do what I need it to do and D3Plus doesn't seem very active.  Plot.ly is very active by comparison and much, much more functional.

I have attached a screen shot here of what I have done.  If anyone is interested in this let me know.
 
![screen shot 2017-03-01 at 1 23 23 pm](https://cloud.githubusercontent.com/assets/16888734/23479632/5643566a-fe82-11e6-8b5c-aa50c94f4b39.png)

![screen shot 2017-03-01 at 1 32 24 pm](https://cloud.githubusercontent.com/assets/16888734/23479998/98a1a498-fe83-11e6-84b1-200d654da762.png)

![screen shot 2017-03-01 at 1 32 37 pm](https://cloud.githubusercontent.com/assets/16888734/23480001/9cdc96bc-fe83-11e6-8ae0-fa2c0aad9671.png)

**Comment by sslupsky** [comment]
@samhatchett @torkelo 

One other thing to mention, Plot.ly might be a good candidate to replace Flot in grafana in general.  Flot doesn't appear to be under active development anymore.  Plot.ly is under very active development.

**Comment by samhatchett** [comment]
@sslupsky thanks for sharing. Do you have this in a repo? I could see this being adapted for something like the WorldMap panel (which assumes a geohash in the metric name) to show heatmap over leaflet - take a peek at https://github.com/grafana/worldmap-panel/issues/17

**Comment by sslupsky** [comment]
@samhatchett Yes, that would be very useful.  I have been looking at the Worldmap plugin.  I have put mine in a Bitbucket repo.

**Comment by abravorus** [comment]
**@samhatchett**

Thanks for info. We have the same approach with different series for x, y and (optionally) z synchronized with timestamp. So for me natel-plotly plugin works "out of the box", great and many thanks.

**Comment by dstreppa** [comment]
Great job! @samhatchett thank you very much for the info.
@sslupsky referring to the images you posted above, I have a (maybe) silly problem: I do not find the tabs (General, Metrics, Axis, Legend, Display, Time range) in the Plotly plugin. How did you build the Heatmap?

**Comment by sslupsky** [comment]
@dstreppa @samhatchett I created my own plugin using the Plot.ly library.  I have it up on a Bitbucket repo at https://bitbucket.org/scanimetrics/scanimetrics-heatmap-panel if you would like to download and take a look at it.  It is certainly not a polished plugin but it is somewhat functional.  There are a few things that have not been finished (thresholds and series overrides).  I took my inspiration for it from the Savantly heatmap plugin (which is actually a Treemap).  I also took some inspiration from the new direction that the Grafana 4.0 UI is going as well.

**Comment by majj** [comment]
+1 @HeathKang  @Fatekiller23

**Comment by wols** [comment]
@samhatchett , @abravorus 
https://github.com/natelenergy/grafana-plotly-panel works for me also - thank you for mentioning.
My usage - screenshot: natelenergy/grafana-plotly-panel#6

**Comment by umasuthanramakrishnan** [comment]
@wols, Can you share a sample data set and steps as to how we can plot two time series data one against the other? Thanks!

**Comment by R-e-M** [comment]
I've just tried https://github.com/natelenergy/grafana-plotly-panel today and finally works fine for me. Thanks !

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by OverWorldD** [comment]
This! Plotly is not working anymore

**Comment by leeoniya** [comment]
we have an alpha X/Y Chart panel in the core that you can try:

![image](https://user-images.githubusercontent.com/43234/151886582-c1a85cd7-8d75-4829-84fc-420fd6572866.png)

you have to enable alpha panels first:

https://grafana.com/docs/grafana/latest/administration/configuration/#enable_alpha

**Comment by MatinF** [comment]
It seems to not be possible to show the XY Chart in Grafana `8.4.5` - I enabled alpha in the config, but it still does not show up in the panel options. 

XY scatter plots for time series seems like it should be a core feature - it's vital to enable basic correlation analyses within Grafana, but it seems almost impossible as no plugins allow this.
