### ISSUE TITLE
Set default "Limit number to"

### ISSUE THREAD

**Issue by stormnight** [grafana/grafana#2020]
Hello,
In "Starred dashboards" and "Dashlist" exists an option "Limit number to", to set the limit of dashboards displayed on each block. But this option is not saved / remembered for each user.
Is there any way to set the maximum number of dashboards to display in each these blocks persistently? (I don't want user must change it every time enter to Grafana)
Best,

**Comment by torkelo** [comment]
Are you talking about the Home dashboard specificially or the `Dash list` panel generally? Because the list panel has an "limit number to" option that can be saved, at least on all dashboards I tested. But you could be talking about the home dashboard, that has two dashboard list panels, and this whole dashboard is currently locked for editing. 

![image](https://cloud.githubusercontent.com/assets/10999/7720600/847c8736-fecf-11e4-9397-4559305c609f.png)

**Comment by stormnight** [comment]
Hello, thanks for your answer!

Exactly there. We have the option, and we can set it, but the data is not saved (We set it on '30', but every time we enter, it's again on 10).

We are using Grafana version: 2.0.2, commit: v2.0.2, build date: 2015-04-22 12:51:50

Thanks,

**Comment by torkelo** [comment]
Yea, the home dashboard cannot be saved in Grafana 2.0.2, you can create another dashboard that looks the same and there you can change it. I hope to add the ability to change the "home" dashboard,.

**Comment by 1tylermitchell** [comment]
I had similar problems with my default dashboard not showing all my dashboards (I had more than 10 of them).  I've had success editing the home.js file in /usr/share/grafana/public/dashboard - there I set limit:20 and I was good to go.

**Comment by torkelo** [comment]
@1tylermitchell in Grafana 3.0 you can customize your home dashboard and save it, and the in user profile preferences or in org preferences specify what dashboard you want to use

**Comment by 1tylermitchell** [comment]
Beautiful!  Will have to bite the bullet and upgrade my system.
