### ISSUE TITLE
Review contributor experience

### ISSUE THREAD

**Issue by sarlinska** [grafana/grafana#20234]
Plugin developers are an essential part of the Grafana's ecosystem. We should be able to answer: how is the documentation, what is the overall experience, what are there friction points?

- [ ] Prepare a research plan.
- [ ] Identify plugin developers to talk to.
- [ ] Run interviews.
- [ ] Summarise findings.
- [ ] Recommend further steps.

**Comment by AmyBlankenship** [comment]
FYI, here is what I have experienced so far

- go get does not work for custom grafana codebase used by my company. Documentation does not suggest that git clone will accomplish the same thing or how to proceed if you do use git clone (i.e. where you should put it for it to work)
- bra did not install due to case error in Makefile path and documentation. Once I successfully installed it by using go get with the correct case on "unknwon", Makefile still did not work because bra was still not in scripts/go/bra. bra run started, but failed because gcc was not installed. Installed tdm-gcc. I have to restart now, in the hope that this is still failing on exec "gcc": executable not found in %PATH% will resolve once the change in PATH is picked up.

**Comment by AmyBlankenship** [comment]
That did help, currently stalled out on [Bra] 02-21 12:26:40 [ WARN] Fail to execute command: go [run build.go -dev build-cli] - exit status 1

**Comment by AmyBlankenship** [comment]
This failed due to incorrect xerrors version. Potentially this is only an issue in our fork
https://github.com/golang/go/issues/34093

**Comment by sarlinska** [comment]
@marcusolsson we should probably update documentation ☝️
