### ISSUE TITLE
Support an Explore to Dashboard workflow

### ISSUE THREAD

**Issue by seanlaff** [grafana/grafana#20245]
Add a button in Explore that creates a new dashboard, pre-populated with the current queries being explored.

Often we find interesting things via Explore that we want to build a dashboard around. Right now this means we have to copy/paste the query by hand and create a new dashboard/panel.

This flow works if you navigate from a Dashboard -> Explore -> Dashboard, but not if you start out on a clean-state Explore

**Comment by ivanahuckova** [comment]
+2 this feature request was also mentioned several times during rich history research

**Comment by juancb** [comment]
We have  a very similar workflow to that described by @seanlaff and this would be save us so much time and tedium.

**Comment by Fridolin34** [comment]
+1 would be pretty nice.

**Comment by richardqlam** [comment]
+1 just felt this pain trying to look up usage data and then chart it as something more permanent after the fact

**Comment by ysenthu** [comment]
+1 Would be helpful for our use case very much.

**Comment by butangero** [comment]
+1 - this would be great!

**Comment by tomjohnburton** [comment]
+1 - Yes please

**Comment by butangero** [comment]
+1 - this would be very handy

**Comment by 09jvilla** [comment]
+1 - This would be awesome.

**Comment by samjewell** [comment]
I'd also like the reverse to be supported: From "Panel Edit" I'd like to be able to switch to Explore. In order to use the Explore features, while retaining what I have set up so far in the Panel Edit flow.

**Comment by anavss** [comment]
Hi @seanlaff @juancb @Fridolin34 @ysenthu @butangero @tomjohnburton 👋🏼 One of our UX Designers built a prototype that tackles this request, and we are looking for a couple of users to test it and give us feedback. If you are keen on participating, please [book a time with us here](https://ethn.io/94764). 🙂

**Comment by samjewell** [comment]
> @samjewell do you mean "Return panel with changes" functionality

Nope, I mean specifically from the Panel Edit page to the Explore page. ie. From here, I'd like to be able to switch to the "Explore" interface (or for the Explore and Panel Edit UIs to actually be identical, and offer the exact same options).

![image](https://user-images.githubusercontent.com/2903904/142244160-ae60aca3-0ff8-45fd-bf49-0bf852b0ae1e.png)

For example, with "Explore" you can split the screen, but in Panel Edit you can't.

I have a workflow:
- Enter "Panel edit"
- Make some temporary edits while I mess around and explore
- Don't want to persist these edits back to the panel or dashboard, but I do want to then split the screen, or use other explore features.

**Comment by Elfo404** [comment]
We had some discussion about this topic and agreed roughly on the following (more details to come if needed):

We are going to add a button in each explore pane to allow saving the pane state to either a new or an existing dashboard, when clicking on the button, a modal dialog will open, allowing users to either create a panel in an existing dashboard or in a new one (the latter being the default)

When choosing to save to a new dashboard, the user will be asked to specify in which folder the new dashboard shall be created and with which name, otherwise users will be asked to select the and existing dashboard to save the new panel in. The new panel will be placed at the top of the dashboard.

No further information shall be asked to the user, and all queries from the explore pane will be copied over to the existing dashboard (hidden queries will be copied as hidden also in the new panel).

The newly created panel will have a default visualization according to the current pane data when available, defaulting to table otherwise. When multiple visualizations are present in the pane (for instance, if different queries produce different visualization types) the first query's preferred visualization type shall be used).
The panel name will be set to a default name (ie. "New panel")

The modal will also allow users to either stay in explore or navigate to the dashboard where the newly created panel has been saved.

cc @nadinevehling

**Comment by samjewell** [comment]
> either create a panel in an existing dashboard or in a new one (the latter being the default)

Did you consider allowing the user to create a Library panel, as a third option?

> The new panel will be placed at the top of the dashboard

This feels like a slightly disruptive experience to me. Of course it will be obvious where the change is, but it might make the dashboard a poor experience for all users who use that dashboard between the new panel being added, and it later being moved to its "correct" location.

If we could save to a Library panel instead, then users could later go to the dashboard they want to extend, and add the saved-explore/library panel in the location they want it, meaning the dashboard is never saved in a potentially degraded state.

**Comment by nadinevehling** [comment]
@samjewell Thanks for your suggestions and ideas! The summary above is based on research we conducted with internal and external participants.
The research didn't point out a strong use case using library panels as a third option and different behavior.
We take your suggestions into consideration regarding possible future iterations.
