### ISSUE TITLE
CloudWatch: add $__interval_s for SEARCH expression

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#20262]
**Why is this needed**:
SEARCH expression take Period at last arguments in seconds unit.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/search-expression-syntax.html

Grafana doesn't provide interval variable in seconds unit, we need to `$__interval_s`, not `$__interval_ms`.

**Comment by marefr** [comment]
Thought there was an existing issue for this but couldn't find any.

**Comment by Geraz69** [comment]
I need this as well. for some reason CloudWatch will not take the parameter if you apply arithmetic in place.

**Comment by IppX** [comment]
As a workaround, I use a custom interval variable that I pass in the queries: https://grafana.com/docs/grafana/latest/variables/variable-types/add-interval-variable/

**Comment by bgardner-noggin** [comment]
Note that Cloudwatch will only support periods in multiples of 60

**Comment by vickyyyyyyy** [comment]
This is a feature request that we can’t see prioritising any time in the near future. If this is a feature that the community still wants, please re-open this in discussions and we may consider it further if it gets more traction. Thanks!

**Comment by rehevkor5** [comment]
Posted https://github.com/grafana/grafana/discussions/44489

**Comment by justinTM** [comment]
please re-open this PR, Grafana's design decision currently breaks both the CloudWatch `SEARCH()` function and the time range selector in dashboards.

**Comment by leeoniya** [comment]
there is some active work in this area: https://github.com/grafana/grafana/pull/43507#discussion_r801984334

**Comment by sunker** [comment]
> there is some active work in this area: [#43507 (comment)](https://github.com/grafana/grafana/pull/43507#discussion_r801984334)

I'm afraid the work in that PR is not related to this feature request. 

> please re-open this PR, Grafana's design decision currently breaks both the CloudWatch `SEARCH()` function and the time range selector in dashboards.

@justinTM can you elaborate a bit on this? In what way are search expressions and time range function broken? 

Using the `$__interval_s` variable in the period field (or in search expressions) would not be possible since the CloudWatch period only allows certain values, 1, 10, 30, 60, 300, 900 etc. What you could do though is to use the `auto` value for the period field. Please refer to our [documentation](https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/#common-metric-query-editor-fields).

**Comment by justinTM** [comment]
> In what way are search expressions and time range function broken?

if you choose to utilize the new CloudWatch features, adjusting the time range in the Grafana UI makes no difference to graphs; for example the state visualization has gaps between values no matter what range you select. 

similarly, SEARCH() will throw errors if you try to use the interval variable.  
  
really i think the issue comes down to this. why would Grafana create time range festures, and then create CloudWatch features, but then stop halfway and not bridge the gap between what Grafana offers and what AWS API van handle? just wipe hands clean and close every issue with WONTFIX and hope users just suck it up?  
  
obviously i read the documentation. neither auto, Auto, AUTO, 'auto', or "auto" work.   
  
have been trying to work around Grafana CloudWatch limitations as a team for probably weeks, maybe more.

**Comment by justinTM** [comment]
@sunker thank you for your quick response

the time range selector in Grafana is not compatible with the CloudWatch `SEARCH()` function.

using `auto`, `Auto`, `AUTO`, `'auto'`, `"auto"` in lieu of eg. `3600` leads to an error.

**Comment by sunker** [comment]
@justinTM as I said, the `auto` value for period is currently not supported in search expressions. Even though not ideal to parse the search expression, it would be probably be possible to add support for it.

**Comment by justinTM** [comment]
right so at this point, as i said, the time range selector does not work with cloudwatch dashboards  
  
and partial searches don't work  
  
and Grafana doesnt use CloudWatch api endpoints GetEntities or SearchMetricSchemas so there is no way to filter by resource tag value  
  
i saw there is resourceARNs templating variable query but i dont see how that would work with metrics search

**Comment by sunker** [comment]
>right so at this point, as i said, the time range selector does not work with cloudwatch dashboards

I believe time range selector is working as expected for all types of queries in the plugin. However, while manually adding search expressions, you cannot get the period to adjust for the changes in the time range. 

>and partial searches don't work because Geafana wraps quotes around dimension values even when Match exact option is deselected

There's no way to do partial matching using the query builder. You can use the expression to manually construct an expression that performs [partial matches](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/search-expression-syntax.html#search-expression-partial-match). Or use the `Metric Query` editor introduced in [Grafana 8.3.](https://grafana.com/blog/2021/12/01/grafana-8.3-released-recorded-queries-panel-suggestions-new-panels-added-security-and-more/#support-for-amazon-cloudwatch-metrics-insights-oss-and-enterprise). 

>and Grafana doesnt use CloudWatch api endpoints GetEntities or SearchMetricSchemas so there is no way to filter by resource tag value

We use the GetMetricData api and it doesn't allow filtering on tags. 

This issue is about adding support for the `$__interval` variable in the expression field. Can you please report bugs if you think something is broken and create a discussions if there's features that you'd like to see in the plugin? Also, there's the [community site](https://community.grafana.com/) for questions on how to use the plugin.

**Comment by justinTM** [comment]
Regardless of the method of constructing the panel, "manual" or otherwise, the time range selector does not affect the results of CloudWatch Metrics Search queries.  
  
i tested with the SEARCH() function as well as using completely default panel with CloudWatch datasource and Builder UI.

**Comment by justinTM** [comment]
> Can you please report bugs if you think something is broken  
  
I have done so already  
  
these are all interrelated issues. I wouldn't choose to use "manual" searches except for broken partial searching in Builder mode, and manual searches bring up the bug of Aliases failing to changed of panel annotations. so it's six of one half dozen of the other and getting hit with WONTFIX replies left and right is honestly getting frustrating.  
  
CloudWatch in Grafana is broken across the board.

**Comment by bryder** [comment]
I have the same problem. 

Grafana calculates the period when using auto mode. If we could access that value in the query expression the problem goes away. 

Now I have to make a work around variable and put some explanations on it so people can select the correct value based on the time period they are querying.

**Comment by sunker** [comment]
If the _Period_ field is left empty or it's set to `auto`, Grafana will try and [calculate](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/models/cloudwatch_query.go#L421-L432) a period based on the current time range. As said earlier in this issue, the _Period_ field is not applied when in the _Metric search code_ mode as we have no way of parsing the math expression defined in this field. 

What we could do is to add a macro for resolving the period within the _Metric search code_ field. The macros would then expand to a numeric period based on the same rules as when the _Period_ field is set to `auto`. For example:
`SEARCH('{"AWS/EC2","InstanceId"} MetricName="CPUUtilization"', 'Average', $__period_auto)`
`$__period_auto` would then expand to 60, 300, 900, 3600, 21600 or 86400 depending on what time range has been choosen.

Would that be helpful @bryder @onitake @justinTM?

**Comment by sunker** [comment]
See proposed solution [here](https://github.com/grafana/grafana/pull/60435)
