### ISSUE TITLE
Explore UI should match standard graph panel

### ISSUE THREAD

**Issue by howardjohn** [grafana/grafana#20293]
**What would you like to be added**:
The new(ish) Explore feature is super useful, but one thing I miss is the great panel UI on the full dashboards. The explore graph has a thick line with no fill, whereas the default graph panel has a nice thin line with fill that has come to be standard. It also doesn't allow hovering over the graph, etc. Overall its just slightly different from the standard panel which makes it harder to work with.

**Why is this needed**:
Both consistency and for improve UI/UX

This obviously isn't a huge issue, but just something I have thought would make me use the explore page more, rather than opening up a quick "scratch" dashboard

**Comment by torkelo** [comment]
Agree, this discrepancy is due to Explore being in 100% in react and some of the old dashboard panels are still in old AngularJs. 

We are working on a new graph panel that will share the same underlying component between
explore and dashboard view. 

think 6.5 will add a hover tooltip to Explore Graph
