### ISSUE TITLE
Grafana hangs on start when port is in use

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#20385]
**What happened**:
I started Grafana locally while already having another instance running, and it hung due to the port being taken.

**What you expected to happen**:
I expected Grafana to report the error and exit.

**How to reproduce it (as minimally and precisely as possible)**:
1. Start an instance of Grafana
2. Start another instance of Grafana
3. Observe that the second instance hangs due to the port being taken

**Environment**:
- Grafana version: Git revision 073e9ef9e7f380f7f53900953337491806462ca9
- OS Grafana is installed on: OS X

**Comment by marefr** [comment]
@aknuds1 remembered we have a change for v6.5 from this PR #19644. Can you verify if [this](https://github.com/grafana/grafana/pull/19644/files#diff-06cc78b0d87adc91d3c4b7c27db1b05dR93-R96) is the problem, i.e. `nil` is returned instead of error. If so, think we should try and fix that for v6.5 stable.

**Comment by aknuds1** [comment]
@marefr I'm trying to find out why the server doesn't exit when that function returns an error.
