### ISSUE TITLE
Feature Request - line fill to the top

### ISSUE THREAD

**Issue by FlorinAndrei** [grafana/grafana#2040]
Currently, the Line Fill option in Display Styles fills the space underneath the graph. This is what you would expect for graphs that are "good" when close to 0, and "bad" when close to 100 (or whatever is the max value). For example: CPU user cycles.

But other graphs are "good" when close to the top, and "bad" when close to the bottom. Example: CPU idle. It is counter-intuitive to fill the area underneath such a graph. It would be nice if there was an option to flip the fill direction for these graphs, and fill the area above the line.

**Comment by torkelo** [comment]
jquery.flot lacks support for this.

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
