### ISSUE TITLE
Grafana stuck on high cardinality prometheus query

### ISSUE THREAD

**Issue by shaikatz** [grafana/grafana#20512]
**What happened**:
When writing the labels in the query, for each character typed the client send an XHR request to the backend, when messing with high cardinality time series, it crashes the browser.

**What you expected to happen**:
There should be some grace period until I'll finish to type my query instead of sending a query for each character.

**How to reproduce it (as minimally and precisely as possible)**:
Search for high cardinality Prometheus metric, for example in Kubernetes you always have `container_memory_usage_bytes` and start typing labels: `{app="bla-bla-bla"}`.
You'll notice that after each character you send a query to the backend which returns very big results and crash the browser.

**Environment**:
- Grafana version: 6.5.1-beta
- Data source type & version: Prometheus 2.8.0
- OS Grafana is installed on: Linux
- User OS & Browser: MAC Chrome/Safari
- Grafana plugins: None

<a href="https://ibb.co/6y0kBhf"><img src="https://i.ibb.co/vc4SY5K/Screen-Shot-2019-11-20-at-13-46-45.png" alt="Screen-Shot-2019-11-20-at-13-46-45" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'></a><br />

**Comment by hugohaggmark** [comment]
Thank you for reporting this @shaikatz , we should debounce those key-presses

**Comment by davkal** [comment]
I'm afraid #20718 does not fix this issue. This issue is caused by the label request taking longer than keystrokes. Here is what happens:

1. `container_memory_usage_bytes{|}` calls the series API via `fetchSeriesLabels()` (which respects time ranges, but that's not important)
2. `container_memory_usage_bytes{a|}` calls the series API again, because at this point `this.labelValues[selector]` is still empty because the call in 1. has not returned yet to fill this cache. This then gets called over and over for every keystroke, until the request com 1 had returned (in the example above after 5 sec, during which a lot of keys can be typed)

See https://github.com/grafana/grafana/blob/f2574f49447c9d7cb952c3d178750e10eb1275f6/public/app/plugins/datasource/prometheus/language_provider.ts#L319

**Comment by aocenas** [comment]
@davkal good point will take a look at it again.
