### ISSUE TITLE
MySql size of data column in dashboard table

### ISSUE THREAD

**Issue by EstebanSantana** [grafana/grafana#2065]
The column data have a type "TEXT" by default.
This type is limited to 65,535 bytes.
The larger dashboard cannot saved correctly.
I update with "MEDIUMTEXT" and enjoy.

Thanks

**Comment by torkelo** [comment]
fixed in master

**Comment by torkelo** [comment]
and already reported :)

**Comment by YouZhengChuan** [comment]
Because the database is configured for sqlite, will encounter "database table is locked" error (https://github.com/grafana/grafana/issues/7992).
I have to export the Sqlite database contents to Mysql. However, some Dashboard because the configuration content is too large, into the Mysql after being cut off, and thus can not be displayed.

![9d52b99d-2d57-40e0-91ce-ca21ec417d80](https://cloud.githubusercontent.com/assets/3882312/25832694/aec589b4-349e-11e7-824d-ba51e4e4b3f9.png)

We have to edit ".sql" file and modfiy "dashboard" table data field type to "longtext" or "MEDIUMTEXT" before source ".sql" file.

**Comment by torkelo** [comment]
dashboard data column already is MEDIUMTEXT , was fixed in a version long a go. 

https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/migrations/dashboard_mig.go#L91

During dashboard schema migration Grafana will create all the mysql tables. After that it should be MEDIUMTEXT
