### ISSUE TITLE
Cloudwatch query to GetMetricData fails when requesting too many datapoints

### ISSUE THREAD

**Issue by andrewmcgilvray** [grafana/grafana#20652]
**What happened**:
Upgraded from 6.4 to 6.5 and cloudwatch queries that span more then three hours in the past and return more than 90k metrics are failing with the error : "too many datapoints requested in query A. Please try to reduce the time range"

**What you expected to happen**:
Grafana should detect if a query is going to possibly return more than the GetMetricData limits and either split the query into multiple requests or increase the minimum interval to get under the limits. The limits are :
 - 180,000 Datapoints Per Second (DPS) if the StartTime used in the API request is less than or equal to three hours from current time. 
 - 90,000 DPS if the StartTime is more than three hours from current time. 
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html
These limits cannot be changed and seem to not just be a per second threshold but a hard limit on the size of a singe query response.

**How to reproduce it (as minimally and precisely as possible)**:
query cloudwatch with a single query that will return more than 90k datapoints over a three hour period. For me this happens when i request the cpu average of all of the ECS services (96 of them) in a cluster for 24 hours. This gives 138240 datapoints.

I know I can manually specify a larger interval but as I widen my time range it will eventually fail again.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: Cloudwatch
- OS Grafana is installed on: grafana provided docker container
- User OS & Browser: macos + chrome 79
- Grafana plugins:
- Others:

**Comment by sunker** [comment]
Thanks for reporting this @andrewmcgilvray! 

The GMD api does not support pagination in the case there's at least one query that uses an expression. Had pagination been supported, this wouldn't have been a problem. 

Splitting the query into multiple requests, like we did before when `HighRes` was toggled, is not something we'd like to do because it adds a lot of complexity and also it's not very clear to the user that it could cost them a lot more money since they pay per GMD request. 

Personally I think it's best when the user actively defines the period, but in case a lot of users are asking for auto min interval we should add that.

**Comment by dneth** [comment]
This broke some of our dashboards out of the box as well and those that still work are more fragile since they could break by changing the time range.  So we're going to wait to upgrade until there's some kind of resolution to this.

Setting the min interval automatically works for our use cases and seems like a much smaller effort.
