### ISSUE TITLE
3rd party plugin Polystat and CarpetPlot plugins are broken

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#20662]
**What happened**:
petrslavotinek-carpetplot-panel
and grafana-polystat-panel

give the error:

![xxx](https://user-images.githubusercontent.com/291750/69622632-a4ade580-1041-11ea-9417-f271854693e3.png)

**Environment**:
- Grafana version: Grafana v6.6.0-pre (6a4ad136dc)
- Chrome and firefox

**Comment by roidelapluie** [comment]
I reproduced in play: https://play.grafana.org/d/oDa-tExWz/repro-gh-20662?orgId=1

**Comment by marefr** [comment]
Tested polystat on v6.5.x branch. 
- It works using development frontend build (`yarn start`)
- It  doesn't work using production frontend build (`yarn build`)

**Comment by roidelapluie** [comment]
![xxx2](https://user-images.githubusercontent.com/291750/69626399-e1c9a600-1048-11ea-9067-0b6eaa632b78.png)
![xxx2yy](https://user-images.githubusercontent.com/291750/69626401-e2623c80-1048-11ea-8fbe-392f8a7f6224.png)

**Comment by marefr** [comment]
Update I can see that polystat doesn't have `/** @ngInject */`, https://github.com/grafana/grafana-polystat-panel/blob/master/src/ctrl.ts#L140, where's piechart does have that, https://github.com/grafana/piechart-panel/blob/master/src/piechart_ctrl.ts#L17. 

This one also lacks `nginject` https://github.com/petrslavotinek/grafana-carpetplot/blob/master/src/carpetplot-ctrl.js#L89

But since they haven't been updated lately something must have changed for production builds of Grafana.

**Comment by yesoreyeram** [comment]
Seems [boom table panel](https://github.com/yesoreyeram/yesoreyeram-boomtable-panel) also broken in 6.5 https://github.com/yesoreyeram/yesoreyeram-boomtable-panel/issues/116 with the error `_this.$sce is undefined`

**Comment by marefr** [comment]
@yesoreyeram we're looking into it. Think it's one problem in Grafana and solving that should fix these kind of problems in all plugins.
