### ISSUE TITLE
i am a prometheus user,found Min step is not working.

### ISSUE THREAD

**Issue by gjpei2** [grafana/grafana#20727]
**What happened**:
when i set Min step to 1s,is not working.

**What you expected to happen**:
the query step can set,and the Min step become effective

**How to reproduce it (as minimally and precisely as possible)**:

when i query the prometheus's history data ,i expect set the qyery step to 1s, but the default step always 15s,only the Resolution can set the step to 30s,45s...1/2,1/3,i want have 15/1.  

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
you cannot go below the scrape interval you have defined in the data source settings

**Comment by harpratap** [comment]
@torkelo I have a similar issue 
Scrape interval at prometheus = 1s
Scrape interval set at data source in Grafana for this prometheus = 15s (Tried lower numbers too)
But the step always seems to default to 120 in the query it is making to prometheus because of which I am loosing some crucial data, no issues when I do the exact same query in Prometheus itself without any resolution set. 
I also tried setting min step to 15s and lower values.

- Grafana version: 5.3.2 but same issue on 6.5
- Data source: prometheus 2.4.3
- OS Grafana is installed on: docker image
- Grafana plugins: Pie chart

**Comment by torkelo** [comment]
Depends on time range as well if you look at long time range Grafana needs to make it bigger
