### ISSUE TITLE
Series override: "Lines: False" does not have desired effect

### ISSUE THREAD

**Issue by ecables** [grafana/grafana#2081]
Grafana 2.0.2 w/ InfluxDB 0.9.0-rc29

I have created a query that sums all returned values together for a "Total" entry in the table. I don't want this Total entry to be drawn on the graph, and only be present in the Table. I can achieve this partially through a series override using "Lines: false," but the Y-scale on the graph still represents the value of the Total query. In essence the line of the Total value is transparent, but still included in the graph's scale, which is not desired.

Here is a screenshot showing that the scale includes the Total entry in the table:
![screen shot 2015-05-30 at 10 37 59 am](https://cloud.githubusercontent.com/assets/5559459/7898544/11404b22-06b8-11e5-96f3-9646e195ac80.png)

I couldn't find a matching issue reported, so if there is one I apologize. Is this the desired result? Is there another way to workaround this that is required, in addition to a regex series override?

**Comment by torkelo** [comment]
lines false, assumes you have some other display enabled (like points or bars). 

Seems like you want another type of style override, "hide from graph" (like when you toggle series in the legend, but have  that option persisted). 

Just a tip, It not good practice to have both `max` and `avg` legend values on the same graph as Graphite or InfluxDB (what ever you use) will consolidate data points down to 1 data point per pixel, so if there are more data points then the values gotten by Grafana will be consolidated using avg or what ever consolidation function you have chosen, so max and avg cannot be correct at the same time (since they are calculated client side by grafana after your time series database as consolidated all measurements for the current time range down to something manageable for grafana)

**Comment by torkelo** [comment]
will close this infavor of #644
