### ISSUE TITLE
Streaming: Support incremental data updates

### ISSUE THREAD

**Issue by sebimarkgraf** [grafana/grafana#20826]
**What would you like to be added**:
I have implemented streaming in Grafana and found that handling everything in the datasource can lead to performance losses.
Many plotting libraries perform better when given incremental data than replotting the data completely all the time.

Therefore, I am using two flags in my datasource and in my panel specifying to transfer data incrementally.
Query:
![image](https://user-images.githubusercontent.com/24530526/70032836-864e6980-15ae-11ea-97c5-714c16e2d5e9.png)
Panel:
![image](https://user-images.githubusercontent.com/24530526/70032902-abdb7300-15ae-11ea-894f-f9be05545057.png)

Since the interface of datasources describes deltaTransfers as deprecated I didn't go ahead and create a proposal PR. 
Is there any way this could be integrated in Grafana allowing faster streaming?

**Why this is needed?**:
* Faster plotting when streaming

**Comment by torkelo** [comment]
What charting library are you using that supports incremental rendering? I know of no such library. 

Good charting libraries render most graphs in 30-200ms allowing for really smooth streaming graphs

**Comment by Sintifo** [comment]
Thanks for your answer!

I am using [Highcharts](https://www.highcharts.com/) to plot my data.
They don't really plot incrementally as this would not gain any performance.
But since the charting library needs to keep the point data as well for plotting it is faster to use 
their `addPoint` than `setData`

My test source provides me with a value every 1ms and while I am able to plot is using incremental data updates, I didn't manage to get smooth updates with setting the data each time.

My profiling showed frequent invocations of GC as the main problem. This lead to taking about 20ms of time only for setting the data and therefore redraws of more than 50ms.

I totally understand if this is out of scope of Grafana, but still wanted to provide you with information about the use case.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
