### ISSUE TITLE
Grafana Toolkit: Allow to extend webpack configuration

### ISSUE THREAD

**Issue by sebimarkgraf** [grafana/grafana#20833]
**What would you like to be added**:
I would be nice to be able to extend the grafana-toolkit webpack configuration.
Especially, enabling custom loaders would allow the user to customize the configuratio to their need.

I would like to add the webpack-loader, #20150 wants to add less-loader. Without this feature the grafana-toolkit will probably receive a lot of feature requests asking for specific loaders or other configuration.

**Comment by papagian** [comment]
@dprokop can you have a look at this one?

**Comment by stevenvachon** [comment]
Coincidentally, there was a discussion about this yesterday :)

**Comment by Sintifo** [comment]
Would you mind sharing the result of your discussion with me?

I checked and there are 3 possibilities that come to my mind:
1. Allow user to create a `webpack-override.js` file that overrides specific options. Hard to use with different versions
2. Allow user to create a `webpack-override.js` with specified attributes to append loaders / plugins 
3. Allow user to specify `ẁebpack: { plugins: [], loaders []}` in package.json

The third option seems the most consistent with the jest approach.

**Comment by Sintifo** [comment]
I implemented the WIP PR and option 3 doesn't allow to easily create options. Therefore, option 2 seems to be the best bet.

**Comment by stevenvachon** [comment]
I was thinking a `webpack.config.js` file that imports from @grafana/toolkit, so that the original is viewable. I think it's better not to overload package.json, especially with non-standard keys.

**Comment by dprokop** [comment]
Glad to see this discussion happening! I was thinking about Grafana toolkit exposing base config via imports. Then the entire configuration could be tweaked, pretty much the same thing that create react app does. Developer would implement webpack.config.ts file in plugins directory end export a modified config from it. If such custom config exists, then it's used instead of toolkits internal webpack config file.

Package.json approach does not feel right, it's not webpacks-famiiar approach. We use this for jest config only because it's one of the ways jest config can be provided

**Comment by Sintifo** [comment]
@stevenvachon Seems like a better approach than my fist one.
I would try to implement it today and update the PR if you have no other plans.
