### ISSUE TITLE
max metric is 26 rows for metric

### ISSUE THREAD

**Issue by yossip** [grafana/grafana#2087]
according to https://github.com/grafana/grafana/issues/1294 
there are A-Z only, 

can this be extended ? 

I need to put 46 (and sometimes more queries in one graph)

**Comment by torkelo** [comment]
why? cant use use wildcard queries? can you describe your scenario?

**Comment by yossip** [comment]
if I use wildcard then the results I get are not correct .. 

I have one host which I query for open connections, If i pull the host only I see 13-14 (which is the result from the mbeans), and if I use the * for the hosts the number of open connections is ~180-270

**Comment by torkelo** [comment]
I do not follow you, can you explain in more detail how your queries and metric namespace look? 

I think a 26 queries per panel limit seems way to high already, so will not likely raise it since 99.99% of cases can be solved with very low number of queries (and some edge cases for larger set around 10-20)

**Comment by yossip** [comment]
seems like there is another issue,

the graphite will show different values while the grafana shows different
numbers (see the screenshot)
do you have any idea what am i missing ? this is on that specific host
while others will display correct numbers

On Mon, Jun 1, 2015 at 3:20 PM, Torkel Ödegaard <notifications@github.com>
wrote:

> Closed #2087 <https://github.com/grafana/grafana/issues/2087>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grafana/grafana/issues/2087#event-318701163>.
>



-- 
Regards.
Yossi Makover Pepo

**Comment by torkelo** [comment]
I am not seeing any screenshot :(

**Comment by yossip** [comment]
![capture](https://cloud.githubusercontent.com/assets/12695578/7931169/e6625f6a-0916-11e5-8d35-8b3affcd620b.PNG)

**Comment by ThiruKumar** [comment]
Hi everyone, i am facing issues with grafana panel which has to filled with four graphlines. but grafana only shows first two queries of metrics editor (A,B) variables of the metrics. please help in this regard.

Thanks

**Comment by alchuk** [comment]
Dear Torkel.
This reminds me the famous "640K of memory should be enough for anybody". Sometimes it's not. 
I have to graph a summary of a number of subinterfaces of a number of interfaces of a number of routers.
I can aggregate some of them using wildcards, but it's still not enough.

**Comment by torkelo** [comment]
no, I do not think it's same. The need for more queries will always be an extreme edge case. The need for more memory was something everyone needed

**Comment by alchuk** [comment]
So, can you confirm this won't ever be fixed/implemented?

**Comment by torkelo** [comment]
but as soon as the need for more than 26 queries becomes requested by many then I am all for it. So far I can only think of 2 users (including you) who has needed it.

**Comment by alchuk** [comment]
OK. Thank you

**Comment by dinapappor** [comment]
I have an issue where I a building a rather large diagram using the diagram panel. On that panel I am using metrics from different machines (remote and/or listening ports) to determine weither or not code on the machine is running. 

This limit of 26 metrics stops me from mapping my entire production.

**Comment by eorochena** [comment]
I have the same issue, I need to build a large graph that has more than 26 queries

**Comment by KunX** [comment]
Same thing here. I already have a panel with 45 queries. Because of the graphite metrics hierarchy, I can't use wildcards. The only way I was able to do it was altering directly on the panel JSON the refid values from letters (A-Z) to numbers(1-45).

**Comment by buddyledungarees** [comment]
I think a common problem/use case is when transitioning from graphite style metrics to a tagging system like opentsdb or prometheus, there's a lot of metrics that might be better off as tags/fields but come in as separate metrics. 

Example: we have a dropwizard timer for every kind of rest api call and want to measure how many total api calls there were for a time period. Unless you have a generic rest.get, rest.post, etc metric with tag=<endpoint>, you end up with tons of separate metrics that you then need to aggregate to get total calls.

With opentsdb allowing for aggregation of distinct metrics via exp, we can add those values together otherwise there isn't any way currently to combine the separate queries results AFAIK. (see #8971 for a nice initial implementation)

I'm not saying it's the correct way but sometimes with codebases being what they are, metrics are transferred over almost as-is from statsd/graphite style naming. I would vote that moving to a more open ended identifier would allow users to scale, even if they end up shooting themselves in the foot.

**Comment by depinski** [comment]
We have metrics from various sources which require simple calculations that grafana provides and then graphs: sumSeries,diffSeries,divideSeries,asPercent etc. These data sources have different metric names and cannot be aggregated by using wildcard queries (which themselves are limited due to not being regexes). They are from different vendors and different systems but have the a common meaning that once calculated benefit from being shown on a single graph panel. This is why I need more than 26 metrics. I would say the case where people need more than 26 is quite common despite the fact that it's not being reported. I think extending the space to double letters would more than suffice.

**Comment by gitrc** [comment]
I resorted to using double letters to work around this issue, similar to @diogouchoas but it's really tedious editing the JSON.  Combining this with grafana-metaqueries to perform cross measurement / cross datasource arithmetic one quickly can exceed the 26 letter limit.

**Comment by xkilian** [comment]
Anytime you want to display data in a flowcharting/imageit type of panel, it is very easy to exceed the number of queries as these queries usually need to be aliased. A network diagram showing various interfaces and metrics of a network perimeter or DMZ, or a core network. These are panels that literally fill an entire screen.
Having more than 26 queries is not unreasonable for a panel that fills a screen. This is even less impactful with the new lazy loading scheme (good job on that!).
I look forward to seeing this limitation finally lifted. It could also be a configuration option that the local admin enables to avoid abuse.

**Comment by wetterfrosch** [comment]
> but as soon as the need for more than 26 queries becomes requested by many then I am all for it. So far I can only think of 2 users (including you) who has needed it.

I want to reboil this ... but just with an example for "why could this seem at any point a reasonable issue?": I want to make a seasonal compare of a data-stream, in particular about the extent of the north pole, as measured since more then 40 years:

![seaice](https://user-images.githubusercontent.com/506253/68529844-188e8500-0303-11ea-92dc-16e3edba913f.png)

So I am using more and more averages to fit the limit. But with this calendar year the limit is within th flux-datasource-plugin but already increased from 20 two 120 in one of the recent releases.
