### ISSUE TITLE
Singlestat: support empty value map texts

### ISSUE THREAD

**Issue by kaihendry** [grafana/grafana#20886]
**What happened**:

![image](https://user-images.githubusercontent.com/765871/70211365-d6285e80-176f-11ea-8042-c008467b0f2e.png)

**What you expected to happen**:

![image](https://user-images.githubusercontent.com/765871/70211398-eb9d8880-176f-11ea-81cc-22c0729eb553.png)
Without the "A"

**How to reproduce it (as minimally and precisely as possible)**:

```
local grafana = import 'grafonnet/grafana.libsonnet';
local dashboard = grafana.dashboard;
local prometheus = grafana.prometheus;

// Grafana UI Components
local singlestat = grafana.singlestat;

local vbug = singlestat.new(
    'valuemapbug',
    colorBackground=true,
    // Works
    valueMaps=[ { "op": "=", "text": "A", "value": "1" }, { "op": "=", "text": "X", "value": "0" } ],
    // Does not work
    // valueMaps=[ { "op": "=", "text": "", "value": "1" }, { "op": "=", "text": "", "value": "0" } ],
    // Red for zero, Green for 1
    thresholds='0.5,0.6',
    // Inverted colours
    colors=[
      '#d44a3a',
      'rgba(237, 129, 40, 0.89)',
      '#299c46',
    ],
  ).addTarget(
    prometheus.target('vector(1)')
);

  dashboard.new(
  'Bug',
  editable=true,
).addPanels( [ vbug ] )
```

**Anything else we need to know?**:

It does the expected thing for `vector(0)`, but not `vector(1)`

**Environment**:
- Grafana version: "sha256:4933878f8ba5cadfd66689139480b2de2ed76fa04af8ce4cfa9180a84e432b5e"

**Comment by torkelo** [comment]
not sure we support empty text values in value mappings

**Comment by kaihendry** [comment]
My use case is to present a _thin_ green bar in a **status page**.

I want to avoid a TICK or some other symbol and that would require way more height in the Singlestat. If there is a better way, let me know.

**Comment by hendrikvh** [comment]
@torkelo Mapping to empty strings successfully change the text in singestats, but the colour mappings do break, causing the above problem.

I think what happens here is:
1. In [displayProcessor:65](https://github.com/grafana/grafana/blob/4ad8b6f030273b40ea22ab9486ca8739af7a7b9b/packages/grafana-data/src/field/displayProcessor.ts#L65) we try to convert our text data to a number using `toNumber()`.
2. `toNumber` incorrectly converts an empty string `""` to `0` instead of `NaN`.
3. We override the numeric value in our data with 0.
4. Colour mappings based on the numeric value breaks.

I hope my understanding is correct. I'll make a PR for this.
