### ISSUE TITLE
Users from different Auth sources not merged

### ISSUE THREAD

**Issue by StupidScience** [grafana/grafana#20889]
**What happened**:
We have two Auth Providers atm (LDAP and Azure AD Auth). If i sign-up with Azure AD and then try to login with LDAP I got error `Error 1062: Duplicate entry 'user@example.com' for key 'UQE_user_email'` in logs.

**What you expected to happen**:
 I expect that users from different auth sources will be merged by e-mail or username. So if you change your auth source you do not need to set permissions from scratch

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure LDAP and Generic OAuth auth
2. Sign-up with OAuth
3. Try to sign-up with LDAP

Pretty sure that it will work same way when you are doing it another order.

**Environment**:
- Grafana version: 6.5.0
- OS Grafana is installed on: docker

PS. Not sure if it is bug or feature request.

**Comment by aknuds1** [comment]
Thanks for reporting, looking into it.

**Comment by torkelo** [comment]
Logging in using another auth provider should require a manual action to be allowed (Ie log in with old auth mechanism and add the second one as allowed) otherwise a form of highjacking of account could be possible.

**Comment by aknuds1** [comment]
Thanks for clarifying @torkelo :)

**Comment by aknuds1** [comment]
I tried to reproduce this with Google and GitLab OAuth providers respectively, since they are easily available to me. I also just downloaded a tar archive of Grafana v7.0.3 for Linux, instead of using Docker as you do (for simplicity). 

What I did was the following:

1. Start Grafana within the unpacked archive: `cd grafana-7.0.3 && ./bin/grafana-server`
2. Sign up to the locally running Grafana instance via Google OAuth
3. Sign out
4. Log in via GitLab OAuth, with the same email address as in step 1

This actually worked without any issues. The user's permissions are also kept (I tested by giving the user the admin role), no matter if I log in via Google or GitLab.

I'm wondering now if your issue is connected to the database you're using? Or could it eventually be tied to your combination of OAuth providers? Do you mind testing v7.0.3 and see if it still fails for you?

**Comment by StupidScience** [comment]
@aknuds1  not sure if my case same as yours. In your case you check mergability with two OAuth2 providers. But in my case there are OAuth2 provider and LDAP. Unfortunately we're still not on 7+ version so I can't check it right now.

**Comment by aknuds1** [comment]
@StupidScience Aha, I guess I will have to try LDAP.

**Comment by Jguer** [comment]
This should no longer happen as of Grafana 8.5 as the oauth lookup is now email only (and it will merge based on email)

If the sources have different casing

```ini
[users]
case_insensitive_login = true
```

should fix it
