### ISSUE TITLE
Explore: Loki query sometimes truncated if the filter expression is invalid

### ISSUE THREAD

**Issue by pracucci** [grafana/grafana#21145]
**What happened**:

In the Explore, if the filter expression contains the invalid `=~ "foo"`, it gets stripped off from the underlying query to Loki.

For example:
- Query in the explore: `{cluster="test"} =~ "foo"`
- Underlying query to Loki: `{cluster="test"}`

But:
- Query in the explore: `{cluster="test"} =~ "foo" != "bar"`
- Underlying query to Loki: `{cluster="test"} =~ "foo" != "bar"`

This non deterministic behaviour is confusing, cause if I type an invalid filter expression like `=~ "foo"` it should result in an error, while sometimes it apparently succeed because it's removed from the underlying query to Loki.

**What you expected to happen**:

To never manipulate the query sent to Loki, in order to get a deterministic behaviour.

**How to reproduce it (as minimally and precisely as possible)**:

1. Open the Explore and select a Loki data source
2. Query `{cluster="test"} =~ "foo"` (succeed even if invalid)
3. Then query `{cluster="test"} =~ "foo" != "foo"` (fail)

**Environment**:
- Grafana version: `v6.6.0-pre (331bc173cc)`
- Data source type & version: Loki
- OS Grafana is installed on: Linux
- User OS & Browser: OSX 10.13.6 & Chrome 79.0.3945.79
- Grafana plugins: N/A
- Others: N/A

**Comment by aocenas** [comment]
@kaydelaney do you know why this is happening? Something with loki versioning? Seems more like something we are doing deliberately than a random bug.

**Comment by kaydelaney** [comment]
Did a little digging and it seems like what's happening here is the following:
Back in May of 2019 a new filtering syntax was added to LogQL (https://github.com/grafana/loki/pull/492), which @davkal then added support for in Explore (https://github.com/grafana/grafana/pull/16674).
I guess support for the legacy filtering syntax was wanted, so `parseQuery()` has some logic that checks if, after the log stream selector (e.g. `{job="grafana"}`) there _is_ a filter operator (`|=`,`|~`,`!=`,`!~`), take the entire contents of the query field and send it to loki as the query, otherwise just take the log stream selector and send it as the query, and send the remaining text as the `regexp` parameter.
So this is why in the case of `{cluster="test"} =~ "foo"`, the `=~ "foo"` is just ignored, but with `{cluster="test"} =~ "foo" != "foo"`, `parseQuery()` sees `!= "foo"` and so thinks everything after the log stream selector is a valid filter expression, causing the error.

I suppose there are a few solutions to this problem, with the simplest being just removing the logic above if legacy filtering syntax is no longer needed (are there any people who still use that old version of loki?).

**Comment by aocenas** [comment]
Thanks @kaydelaney btw is `=~` something we actually used at some point or is that just a typo in the operator? Cause if I understand the old syntax was `{job="grafana"} test` and now it is `{job="grafana"} |="test"` right?

**Comment by kaydelaney** [comment]
Yeah, `=~` isn't a valid operator, so just a typo
