### ISSUE TITLE
Add authention proxy project to documentation

### ISSUE THREAD

**Issue by Sytten** [grafana/grafana#21158]
**What would you like to be added**:
We already have a nice documentation on how to setup an auth proxy using Apache. At my company we offer a multi-tenant version of Grafana for our customers and the proposed solution was not sufficient, so we built one in Go. It's using JWT tokens either in the header of in a cookie. I decided to open source the bulk of it here under MIT license: https://github.com/caido/grafana-auth-proxy

**Why is this needed**:
It's ready to use with a docker image and proper documentation. I thought it would be nice for the community to have a plug-and-play implementation that is production ready.

**Comment by dprokop** [comment]
@Sytten thanks for giving us heads up! @torkelo @oddlittlebird please take a look at this when you find time

**Comment by oddlittlebird** [comment]
Waiting for guidance from @torkelo and others.

**Comment by Sytten** [comment]
Any update?

**Comment by marefr** [comment]
Think we historically have said no adding documentation about third-party solutions because maintainers have been unsure of how to be able to maintain this over time. For example, if there's a new version/breaking change happening in a third party solution maintainers won't be aware of that and would be dependent on contributors making sure documentation is proper and up to date. 

But perhaps a section about unofficial auth proxy solutions with a link to this solution could be a good compromise. Then the information at the link would be in charge of providing proper information/documentation.

**Comment by ying-jeanne** [comment]
discussed with team, we could add third party section with the link to github instead to share this practice with community.

**Comment by Sytten** [comment]
FYI the repo was moved to caidooss as was the docker image.
https://github.com/caidooss/grafana-auth-proxy

**Comment by marefr** [comment]
We're open to accept a pull request adding a section to third-party auth proxies with a link to your GitHub project, but we're not going to work on this.

**Comment by Sytten** [comment]
I am not expecting too? Not sure what part of my previous message lead to that conclusion

**Comment by achatterjee-grafana** [comment]
Closing, based on the discussion.
