### ISSUE TITLE
Graphite query editor popups disappear

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#21177]
graphite editor function popup keeps disappearing for no good reason.
video showing the behavior with perSecond(): https://youtu.be/aNgamiM1KJM
but i've seen it with other functions too. e.g. sumSeries()

**Comment by Dieterbe** [comment]
bump. this issue is quite annoying.

**Comment by torkelo** [comment]
Unable to replicate this, tried with the same functions:
https://play.grafana.org/d/zKHrtmPWz/graphite-function-popover?orgId=1&fullscreen&edit&panelId=2 

What browser version are you using?

**Comment by Dieterbe** [comment]
for me it happens not consistently, but often enough. about 2/10 to 4/10 of times.
I can reproduce in Chromium Version 79.0.3945.88 (Official Build), but not in firefox :/

**Comment by Dieterbe** [comment]
i still run into this frequently. very annoying

**Comment by bob454522** [comment]
@papagian 
>I'm able to reproduce it if the window is too small.

Interesting,  what browser are you on?  (firefox maybe?)
Im on latest chrome windows10 (not chrome canary) and i tried expanding the browser window to full screen, on a 4k monitor (@ original, 100% dpi),  and the quickly disappearing issue still occurred.  I was hoping that this would fix it, as i would be ok with using the browser window at a very large size as a work-around,  but alas it did not fix it.  Thanks

**Comment by shanson7** [comment]
Happens to me too (has been for a while, just finally complaining now). Various versions of Chrome on macbook. 

Makes it very annoying to reorder functions.

**Comment by bob454522** [comment]
im using: Chrome Version 83.0.4103.116 (Official Build) (64-bit) - on windows10  (this has been occurring for 5+ months though, so through several chrome versions/updates ,  and a few grafana updates, such as v6.x -> 7.0  and 7.0 -> 7.0.3 -> 7.1.1 

**UPDATE**-  while making this screen cap gif, i noticed it seems exactly where you click on the letters of a function **sometimes**, has an impact on if the tool tip disappears.  I cant determine any "logic" or a workaround to this, except that it seems to matter (but does seem to be random).  the screen cap i made is about 2 minutes long so below is an additional private yt link, incase that helps too:
https://youtu.be/y2T0bnJyhTw

![grafanaTOOLtip](https://user-images.githubusercontent.com/60830628/89739109-7d6a3d80-da43-11ea-8b6d-e4967d700d02.gif)
_(i did have to obfuscate some small, sensitive parts of the series' names)_


**ORIGINAL post**:
One additional item i can point out,  while this (tooltip disappearing) almost always occurs,  it seems that if the function is in the first (earliest) position,  the issue is even worse.

What i mean by this is in the img below,  "averageAbove" (red underline) will very quickly (~0.5s) disappear after clicked, Regardless of if i move my mouse or not.
![image](https://user-images.githubusercontent.com/60830628/89738844-69254100-da41-11ea-998a-7bc0ff1a600c.png)

This is in contrast to functions not in the first position, where if i click, **but dont move my mouse at all**, the tool tip will often NOT disappear.  (however if i then move my mouse up, as if to try to click one of the 4x icons/options,  only then will the tooltip disappear, unless im very quick to click an icon/option).

this is a distinction i wanted to bring up incase it helps with debugging.
thanks

**Comment by ivanahuckova** [comment]
I have found 2 possible solutions. I will create PRs for both of them and I am interested in feedback on those.
