### ISSUE TITLE
TimePicker: storing zoom absolute time ranges in the "recent list"

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#21193]
**What would you like to be added**:
After zooming on an absolute time range for a graph panel it does not create a new absolute range I can pick from the time picker. I think we need to store the current absolute past time range when we navigate away from a dashboard. So if you zoom in on a graph, then go another dashbord, you can select that same time range.

**Why is this needed**:
This will help out a lot when jumping between different dashboards. It is a spin off from testing of the following PR: https://github.com/grafana/grafana/pull/20931

**Comment by sakjur** [comment]
While I'd like this, I'd consider zooming around lazily to be something I do a lot of and when I set a time range manually I put more thought into it and would like it to be retained for easy access for a longer time.

Would it be possible to have these time ranges stored so that they rotate out of the list much quicker than the time ranges I've hand-crafted? Say the list contains 10 items, then at most 3 of them are the most recent zoom time ranges so zooming around doesn't end up pushing my more carefully picked timerange out of the picker.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
