### ISSUE TITLE
graphite/metrictank <-> loki integration

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#21205]
prometheus queries can easily be converted to loki queries because of the same label selectors.

for graphite/metrictank it's a bit harder, but not that much.
we could perhaps "convert" queries with some mapping rules that describe how to from graphite metric names to loki label selectors. rules like:
```
metrictank.stats.<$env-$customer>.<$podname>.* -> {cluster="$env",instance="$pod"}
```
since the labels people use to run their services in k8s are up to them and detached from the terms used in carbon/graphite metric names, which by the way, can also get prefixes etc, these rulesets are custom to each environment/deployment.

i imagine these rulesets would be a config item in the datasource settings.

**Comment by Dieterbe** [comment]
update after talking to @ryantxu and @woodsaj , I learned: 
* grafana team has this on their roadmap already
* no work ongoing right now in grafana team. but what they do support is, if our render queries include labels, they can map those to a loki query
* any work of mapping metric id's or queries to labels ("translation layer") is still up in the air. 

Can somebody confirm this or provide more color?
maybe @kaydelaney or @hugohaggmark ?

**Comment by aocenas** [comment]
Hey, @Dieterbe as far as I know what you describe as a current state is correct, there isn't any ongoing work on this.

The datasource API allows for any datasource to get previous query from previous datasource and try to map it to it's own query. This could be used semi easily for this too.

Only issue I see is that the API could be improved to make this bit easier to implement. Right now each target datasource need to implement all the transforms to get something usable from the origin. Maybe there could be some some intermediate format so that the transforms in more sensible way like `origin query` -> `origin DS transform` -> `common format` -> `target DS transform` -> `target query`

**Comment by Dieterbe** [comment]
Thanks Andrej!
