### ISSUE TITLE
null point mode - detect gaps in timespans?

### ISSUE THREAD

**Issue by isj4** [grafana/grafana#2125]
The null point mode = null does not work as I expect it to. My expectations may be wrong.
I have a data series where there is a 13-hour gap in the data. However it is shown as connected.

![null_point_mode](https://cloud.githubusercontent.com/assets/12530623/8023704/6bd66d40-0d17-11e5-8372-0858d4e485c3.png)

The gap in data in the attached graph is from 6:22:23 to 18:58:40.
I would have expected that timestamp to be shown as "unknown", not as a  connected line.

**Comment by torkelo** [comment]
do you use influxdb? If that is the case you need to add fill(null) to your query, and a group by time lower limit (set by the group by time under your queries), for example set it to `>10s` if you write data every 10s, that way influxdb will insert nulls for missing intevals

**Comment by isj4** [comment]
I use OpenTSDB.
I guess what would be useful in this scenario is to have a setting in Grafana specifying what signifies a "gap" that should be treated as null.

**Comment by torkelo** [comment]
This should be a feature in OpenTSDB as both Graphite and InfluxDB has it.

**Comment by torkelo** [comment]
But you are right it could be done in grafana as well

**Comment by awwaiid** [comment]
Is there a fill-nulls for ElasticSearch? I haven't figured out a way so far.

**Comment by awwaiid** [comment]
Ahh... I think it is the min_doc_count here https://github.com/grafana/grafana/blob/91a814d295cb56aba3f8981f81cd5c04e928fe46/public/app/plugins/datasource/elasticsearch/query_builder.js#L110

**Comment by torkelo** [comment]
@awwaiid I changed to min_doc_type 0

**Comment by awwaiid** [comment]
Cool. I've been manually setting it to zero on my graphs with no obvious ill affect. I was thinking of submitting a button to toggle/set this in the structured editor,  but if zero always works that is even better.

**Comment by enesfnd** [comment]
Hey guys I'm using MySQL and I have same problem too. But I don't want to add null values for time gaps, Because this is not a solution this is just a data manuplation and this makes my database riddiciliously larger. I think that graphic library has to have a thresold for drawing lines between gaps. But I couldn't find anything in partial html files or configurations. Could you tell me in which file flot.js and d3.js configurations are done?
So I can observe if there is anyhing that I can do.

thanks

**Comment by gflex** [comment]
I had struggled with that problem for a while. Setup is InfluxDB with grafana 5.3.2 (and with few versions ago). Just to add to torkelo's comment ago: I had data with gaps. Whatever I did, Grafana showed them connected. I followed torkelo's comment  with one addition: I had to add a selector like last(), first() to the query. Otherwise, nothing was plotted.
