### ISSUE TITLE
Wrong permissions in grafana package for grafana.ini

### ISSUE THREAD

**Issue by yannh** [grafana/grafana#2126]
Hello! Regarding the Ubuntu / Debian package, it looks like /etc/grafana/grafana.ini gets installed as root:root and permissions 644, considering this file might contain passwords it probably should not be world readable? As grafana runs as user grafana, it looks like this would better be grafana:grafana with permissions 600 ?

Thanks!

**Comment by torkelo** [comment]
644 is the same as most config files on my system (nginx, apache, mysql)

**Comment by yannh** [comment]
Hello @torkelo, thank you for your quick reply! Indeed most of the configuration files in Linux/Unix are world readable, that is unless they contain passwords, which the grafana.ini file does contain - in which case the file should not be readable by users who should not have access to that password.

The file /var/lib/grafana/grafana.db is also world readable, although it contains sensitive data like passwords (-hashes?).  I think it would be best if this file wasn't world readable either, so 0600?

Thanks!

**Comment by damm** [comment]
Sounds like /etc/opt/grafana should be owned by grafana:grafana (at least on ubuntu) and the database should be 600'd as grafana as well

**Comment by phrend** [comment]
I agree, I locked down grafana.ini when I updated the settings within.

**Comment by torkelo** [comment]
anyone willing to help out with a PR for this? changing so that /etc/grafana/grafana.ini is readable only by root and grafana user should be easy to do in the post install script, 

https://github.com/grafana/grafana/blob/master/packaging/deb/control/postinst
https://github.com/grafana/grafana/blob/master/packaging/rpm/control/postinst

changing permissions on the db file, not sure that might need a code change
