### ISSUE TITLE
Get all query possible query for a dashboard

### ISSUE THREAD

**Issue by deathwarrior60** [grafana/grafana#21270]
**What would you like to be added**: I would like to have a endpoint which returns me all possible query for a specific dashboard

**Why is this needed**: I want to "secure" viewer access to be sure, they can only issue query on dashboard they have access to.

**Comment by torkelo** [comment]
> Why is this needed: I want to "secure" viewer access to be sure, they can only issue query on dashboard they have access to.

What do you mean secure a viewer? How would you do that? Via a custom proxy server that would lookup if the query was part of a dashboard the user had access to? That sadly does not work because of the way Grafana supports dynamic dashboards & queries (variables etc). So it currently impossible to restrict what queries a viewer can query unless they are separated into different data sources (in different orgs or using data source permissions)
