### ISSUE TITLE
Docs: Document changing user passwords

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#21365]
**What would you like to be added**: Instructions so that users can passwords in the Grafana UI. Right now, we only have written instructions for changing the Admin password using Grafana CLI.

**Why is this needed**: Because right now a Google search for "grafana change user password" brings up a bunch of other companies, then the Grafana docs instructions for changing the Admin password. We do not seem to have explicit instructions to help users or user admins change passwords.

**Comment by undoingtech** [comment]
The community [HowTo category](https://community.grafana.com/c/howto/6) seems like a good place for these instructions.  I don't think this would fit neatly into the guides, and the reference documentation looks more geared toward admins, not regular users.  

The HowTo category is sparse though, so I am not sure what determines which topics are allowed there.  I cannot make a new topic in the community since my account is new with little activity.

I would like to write the these instructions.  I'm just not sure where to put them.

**Can anyone clarify: can these instructions be put in the community HowTo?**

**Comment by oddlittlebird** [comment]
Whoops. Forgot to cite this issue in the new docs. :)

**Comment by undoingtech** [comment]
@oddlittlebird Nice work!  Thank you for the clarification. :)
