### ISSUE TITLE
Role mapping for Azure AD OAuth token with overage indicator

### ISSUE THREAD

**Issue by motoko89** [grafana/grafana#21366]
**What would you like to be added**:
Ability and configuration to handle role mapping of Azure AD users that belong to more than 6 groups

**Why is this needed**:
When a user belongs to more than 6 groups in Azure AD, the returned token has the format `groups:src1` where `src1` points to group membership information URL. Grafana should be configured to handle this

**Comment by aocenas** [comment]
@xlson can you take a look? I assume this is close to the auth work your team has worked on.

**Comment by xlson** [comment]
We'll take a look.

**Comment by jongyllen** [comment]
Just for reference - here the details how this works:
https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens

**Comment by marefr** [comment]
#20030 would make it easier to add this custom logic.

**Comment by twendt** [comment]
I think that this is not the way to go. I was trying to implement this during my work on #21581 . It seems to required extra permissions for the application on the Azure AD which even require admin consent. From the documentation the limit that you get the overage in the token is not 6 groups, but 200. From my experience the number of groups that users are a member of can be massive in a historically grown on-prem AD which is then synced into Azure AD.

I think that the better approach here is to use application roles. You can define them in the manifest of the registered application and once you have done that you can go to the corresponding enterprise application and add users and groups to these app roles. Now whenever a user requests a token for your application all the app roles that the user is assigned to will be added to the roles claim in the token. This is now application specific. You can still use the same groups, but you do the assignment within the Azure AD instead of creating a complicated search path in you grafana configuration. The registered application does not require any special permission with admin consent for this to work. You can also configure on the enterprise application that the user requires a role assignment. This means that the user will not get a token if not assigned to any of the app roles. grafana also does not have to do any extra call to the Azure AD to request the groups as the assigned roles are already part of the id token.

**Comment by marefr** [comment]
@twendt thanks a lot for your view on this. Really appreciate it. What you write makes perfect sense to me so I will close this issue.
