### ISSUE TITLE
Unable to replaces the series names (alias) on opentsdb graph

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#2148]
Torkel, I attached the screen shot. When I place a custom text in the alias text box, series name in the chart is not changing. 
![opentsdb_alias](https://cloud.githubusercontent.com/assets/3009225/8108938/b07c9e26-1021-11e5-9824-3159f9db17ed.png)

**Comment by torkelo** [comment]
what version of Grafana are you using?

**Comment by gsaray101** [comment]
Grafana version: 2.0.2, commit: v2.0.2, build date: 2015-04-22 11:51:50

**Comment by torkelo** [comment]
strange, this should work (works for me).  no one else has reported this. Try deleting the query row and start again. And open chrome dev tools to check for any js errors

**Comment by gsaray101** [comment]
If I have two same series, 1) I need to look at row data 2) I need to do down sample. But the same metrics. If I change the alias on 1, it works. If I try to change the alieas on 2, not working.

**Comment by gsaray101** [comment]
no js errors on chrome

**Comment by torkelo** [comment]
@gsaray101 are you talking about having two queries for the same metric?

something like this:
![image](https://cloud.githubusercontent.com/assets/10999/8112250/f27e3d9e-1066-11e5-8a5b-3adb1fe47745.png)

that is due to a limitation in the OpenTSDB API (no way to know which series belong to which query), this is fixed in OpenTSDB master, https://github.com/OpenTSDB/opentsdb/issues/438 

I plan to use the new api some time soon.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/1876
