### ISSUE TITLE
Annotations from graphite events are skewed in time

### ISSUE THREAD

**Issue by nurriz** [grafana/grafana#2155]
When I add an annotation with a graphite event source, they show up an hour earlier than graphite says it is. I don't have any other problems with timezone stuff, all graphs are fine and display correctly.

I run grafana and graphite on separate machines, both have the same timezone configured and are synced identically. We use "/Europe/Copenhagen", graphite has the same timezone configured.

When I add an event through graphite, it shows up at the right time. When used in grafana it shows up an hour earlier.

Graphite: 
![image](https://cloud.githubusercontent.com/assets/566325/8126434/c6f7683e-10ee-11e5-8337-4d3a1740e8b0.png)

Grafana: 
![image](https://cloud.githubusercontent.com/assets/566325/8126447/d895fb28-10ee-11e5-8472-22174c3c69dd.png)

My client (Windows) is set for the same timezone, which for summer time is UTC +2:00.

**Comment by torkelo** [comment]
Could be a problem with your graphite and daylight time saving, I know there are some bugs in 0.9.12 relating to daylight time saving. 

You can open chrome dev tools and inspect the response from graphite, it is most likely wrong. No one else has reporting this and the graphite events are showing up correctly for me. 

But if you can show the response from graphite along with a screenshot of where grafana draws the annotation we can identify if the problem is in graphite or grafana.

**Comment by nurriz** [comment]
I'm running 0.9.13 of the webapp. When I inspect the response it is indeed an hour earlier than what the events interface says. I'll take my problem elsewhere :)

**Comment by gshakhn** [comment]
@nurriz : Were you able to find the root cause?

We're hitting the same problem. We're in GMT-5. An event in the UI shows as `13:31:37 Tue 14 Jul 2015`. The AJAX call in Chrome reports 1436920297, which is `19:31:37 Tue 14 Jul 2015 GMT-5`. That's where the annotation shows up in grafana.

It feels like the AJAX call doesn't respect the time zone property set in graphite.

**Comment by damm** [comment]
Set Graphite to use the TZ you want https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/local_settings.py.example#L23

**Comment by gshakhn** [comment]
We're currently setting `TIME_ZONE = 'America/Chicago'`

It looks like Graphite is always storing the events in GMT? As a test, I did:

```
curl -X POST "http://graphite/events/" -d '{"what": "Some server started.", "tags": "server-start", "data":"Some server started.", "when":1436932353}'
```

Chrome dev tools indicates this is the response:

```
[{"data": "Some server started.", "what": "Some server started.", "when": 1436953953.0, "id": 5, "tags": "server-start"}]`
```

The `when` time from the event is off by 6 hours from what I set it to.

**Comment by gshakhn** [comment]
This problem looks similar to graphite-project/graphite-web#1028.

**Comment by nurriz** [comment]
I'm still baffled by this. I found out why it looks wrong in grafana though. The query grafana makes returns a timestamp that's one hour earlier than what is in the graphite events table. So it's obviously something in graphite.

Why the json output is wrong I don't know.

**Comment by Leobaillard** [comment]
I'm having the same problem using Graphite 0.9.13 and Grafana 2.1.0-pre1.

**Comment by torkelo** [comment]
@Leobaillard report it to graphite project, and double check your graphite timezone setting

**Comment by NoMotion** [comment]
@nurriz I am currently trying to solve this exact issue. Did you come to a a conclusion (a year later)?

**Comment by nurriz** [comment]
@NoMotion I created this https://github.com/graphite-project/graphite-web/issues/1281
The changes in this: https://github.com/graphite-project/graphite-web/pull/1034
made it work. This should be fixed in the newest version of graphite.
