### ISSUE TITLE
Allow font family selection in Table panel

### ISSUE THREAD

**Issue by tlinhart** [grafana/grafana#21668]
**What would you like to be added**:

It would be great if we could choose font family in the Table panel in a similar way to how we can choose font size.

**Why is this needed**:

We use Table panel to display logs from Elasticsearch. Log messages are best to be displayed with monospaced font, especially if the log messages are multiline. (At the moment, it's the most suitable way how to display them as Logs panel doesn't meet our requirements.)

To illustrate the idea I quickly monkey patched the stock Table panel and here's the result:

![image](https://user-images.githubusercontent.com/12714153/72898657-ce734800-3d24-11ea-8893-b4805d4ac0b8.png)

**Comment by torkelo** [comment]
Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
