### ISSUE TITLE
Frontend: Time Range picker changes doesn't trigger panel refresh

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#21680]
Steps to reproduce:
1. Click the time range selector and choose “Last 24 hours”
2. Click the refresh icon
3. Effect: nothing happens
4. Expected behavior: the graph refreshes to show the newly selected time range
5. Work around: click in the “Period” field and hit the Tab key.

Issue found when testing CloudWatch datasource in branch v.6.6.x

Error in js console: 
`2angular.js:14800 Possibly unhandled rejection: {"message":"Datasource named CloudWatch-redacted was not found"}`

**Comment by dehrax** [comment]
After some inital investigation this problem is probably related to template variables, as there are no options for region, namespace and dimensionValue. A reload creates the error: 
![Screenshot from 2020-01-23 14-57-43](https://user-images.githubusercontent.com/1438972/72990628-cb458e00-3df0-11ea-8961-62a27d0f3278.png)
Which logs:
```
{message: "Datasource named CloudWatch-mxdev was not found"}
```

Since a couple of them are QueryVariables it might be the query failing causing them to not have a value, which might be the reason for the time not being update.

Bug is in master too.

**Comment by dehrax** [comment]
The issue seems to be caused by the query variable having refresh set to `On Time Range Change `, with no defined data source.
![Screenshot from 2020-01-23 16-49-00](https://user-images.githubusercontent.com/1438972/72999911-59754080-3e00-11ea-9823-dcb30380a25d.png)

@sunker How was the data source not set? Imported dashboard with edited JSON?
