### ISSUE TITLE
Automatic cleanup of temp data folder

### ISSUE THREAD

**Issue by Bulbuc** [grafana/grafana#2172]
Hi,

First of all, there is no issue, but it seems I cannot find the proper info anywhere:

Is there an automatic cleanup of temporary data folder? Here I'm referring to png exports and sessions. Do I need to add a crontab entry for this or is already a mechanism implemented in grafana?

Thanks!

**Comment by torkelo** [comment]
sessions should be cleaned up but could be that there are leftovers when you do restarts not sure. PNG images definitly needs a clean up process (there is none at the moment)

**Comment by ZhukovAlexey** [comment]
Resolving the issue is good, but are there any documents how to use it?

As O can see there's in conf/defaults.ini

+[tmp.files]
 +rendered_image_ttl_days = 14

But in the latest grafana-4.0.2-1481203731.x86_64.rpm package I can't find those settings in conf/defaults.ini neither grafana.ini and on the Docs section there're no information too.

**Comment by bergquist** [comment]
@ZhukovAlexey in 4.0.2 rendered images older then 1 day get purged. Its not configurable anymore.

**Comment by ZhukovAlexey** [comment]
@bergquist I see now, thanks.
