### ISSUE TITLE
Annotations result in angular error

### ISSUE THREAD

**Issue by HerrBerg** [grafana/grafana#2176]
Grafana version: `debian` package` grafana_2.1.0-pre1` build from `2015-06-08`

When moving the mouse over an annotation the contents are not shown.
Instead there's a small grey block shown below the last row.
The Console shows an angular error.

**Comment by torkelo** [comment]
I am unable to replicate, can you show the exact json response for your annotation query? and also the angular error?

**Comment by torkelo** [comment]
any more details would be great

**Comment by pavleec** [comment]
I've the same problem in build from 19.06.2015. The error looks like below:
![angular](https://cloud.githubusercontent.com/assets/12551929/8331736/208ac66c-1a8a-11e5-99ec-16977ea1aa17.png)

Nothing has changed since the previously reported bug #2147 related to annotations displayed from from Graylog's Elasticsearch DB.

**Comment by torkelo** [comment]
I just tested against master and it seems to work fine for me. I still have not gotten the json response from elasticsearch, that will make it very easy for me to replicate it
