### ISSUE TITLE
Adding datasource via API doesn't work with non-default root_url

### ISSUE THREAD

**Issue by zanoni23** [grafana/grafana#2178]
When trying to automate the addition of a datasource as per https://github.com/grafana/grafana/issues/1789 I find that it doesn't work if I set the root_url to have grafana in a subpath (e.g. /test/grafana/ - used in ProxyPass in Apache).
When I try to query the API locally (not through the Apache) "http://localhost:8080/api/datasources"  I get message "access denied".  (Grafana is configured to listen on 8080).  When I query "/test/grafana/api/datasources" through the Apache I get the same message.
If I revert the root_url to have the default setting, it does work.  Grafana 2.0.2.

I tried the new Grafana 2.1pre and its new API version (different HTTP method used etc) and had the same issue but got message "not found" I think - again it worked with default setting but not a custom root_url.

**Comment by torkelo** [comment]
Can you check so that this is just not a cookie thing? because it does work from the UI so it must be that you are sending the api authentication wrong (either with the cookie or api key). The reason it can change when changing root_url is that the subpath is included in the cookie path (browser security thing)I
