### ISSUE TITLE
config: always redirected back to config page for the Instana data source plugin

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#21819]
**What happened**:

1. Opened the config page for the Instana data source
2. Click on any link in the menu
3. Get instantly redirected back to the config page

**What you expected to happen**:

To be able to leave the config page.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install the Instana plugin
2. Create 2 data sources instances for Instana named `Instana` and `Instana-1`. Don't need to add any settings - just save them.
3. Open the config page for the instance named `Instana`
4. Click on any link

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest master
- Data source type & version: Instana 2.5.1
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Ubuntu and Chrome
- Grafana plugins: Instana
- Others:

**Comment by torkelo** [comment]
Identified the reason here (I think), not sure why it only happens with the Instanta, probably a timing issue. 

The connect with cleanup causes a redux event at the same time as angular route change, which messes up the angular bridge srv.
The problem is this ordering: 

1) angular route change (via link click) -> angular $location url changed
2) redux action (for cleanup action) -> bridgeSrv -> detects a diff in redux store & angularUrl, thinks redux url is correct (ds settings page url) 
3) $routeChangeSuccess triggers for link click  (too late) to update redux url state

**Comment by torkelo** [comment]
This is very tricky to solve. The settings are changed in instanta async (in config ctrl), outside a digest so when you navigate away a digest is triggered, which triggers an angular watcher in plugin_component which triggers onChange which triggers a redux change, which triggers bridge srv redux store subscribe, and angular has already update it's url state but no yet triggered the routeChangeSuccess event.... 

Not sure how to solve this at the moment.

**Comment by torkelo** [comment]
think I have a solution
