### ISSUE TITLE
Alerts in Microsoft Teams  mobile application (iOS) don't display the details

### ISSUE THREAD

**Issue by unvadim** [grafana/grafana#21871]
Grafana v5.4.3, Teams Mobile v2.0.1 (iOS)

An alert sent by Grafana displays OK (all the details are present: title, summary, image) in the desktop Teams application however no details are visible in the mobile application.
![photo5305551265591307590](https://user-images.githubusercontent.com/3006990/73536234-2e0cda00-442e-11ea-8026-497ad2d5b824.jpg)

The test notification displays OK though:
![photo5305551265591307593](https://user-images.githubusercontent.com/3006990/73536241-3107ca80-442e-11ea-8b27-aa883a54031d.jpg)

**Comment by hugohaggmark** [comment]
Thanks for reporting this @unvadim but if this is working correctly in the desktop application for Teams but not in the IOS app I suggest that you contact Microsoft that makes both? I'm closing this issue now because this doesn't seem to be an issue with Grafana, but this issue can always be reopened if more evidence would point to Grafana.
