### ISSUE TITLE
Simplify theme support

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#21889]
The various approach to theming in grafana seems to have evolved

In @grafana/ui, the theme is passed in as a property, or we use [ThemeContext](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/themes/ThemeContext.tsx)
Elsewhere it is essentially read from the singleton loaded in `@grafana/runtime`

Do we ever need to support multiple themes at the same time?

Could the theme *always* be a singleton in `@grafana/ui`? and we remove the various other ways to pass it around?

**Comment by ryantxu** [comment]
Thoughts @dprokop / @torkelo ?

**Comment by torkelo** [comment]
The only downside I see with the singleton approach is that it will not trigger a react render if you change the theme so a theme change will always require a page reload.

Maybe not super critical for the app to change theme on the fly without a reload,  but for storybook it could be a problem

**Comment by dprokop** [comment]
> In @grafana/ui, the theme is passed in as a property, or we use ThemeContext

@ryantxu essentially the theme is always retrieved via context.  The thing with `Themeable` interface is to allow class components to retrieve the theme using higher-order component rather than using `<ThemeContext.Provider ... >` directly. It's not a result of an evolution but rather a design decision to allow flexibility. I'm not sure about having theme available as a singleton as this is not a React way of doing things. It has an advantage though as the theme could be automatically resolved in the `stylesFactory` function so there wouldn't be a need fo passing it around if styles require theme. 

But before doing any changes around this I'd like to explore the Emotion 10 approach to styling and see if we can maybe fit Emotion's approach to our case: https://emotion.sh/docs/theming

**Comment by ryantxu** [comment]
for now we can use:
```
<ThemeContext.Consumer>
          {theme => (
```
