### ISSUE TITLE
Strings with empty spaces appended are not converted to text in table plugin when the user selects the value mappings as as value to text

### ISSUE THREAD

**Issue by Kranthi-grafana-user** [grafana/grafana#22003]
**What happened**: Strings with empty spaces appended are not converted to text in table plugin when the user selects the value mappings as as value to text, type as string in column styles

**What you expected to happen**: If the strings has empty spaces appended, do not trim them, use the value entered by user as is to convert it to text

**How to reproduce it (as minimally and precisely as possible)**: 1) Create a dashboard
2) Choose table plugin
3)Choose data source which can result strings in table columns
4) In the column styles choose type as "string", value mapping as "value to text"
5) Click on + iocn
6) Enter string which has empty spaces in the value field
7) Enter some text (to which the above entered text should convert to) in text field next to -> icon
8) Observe that the value  has not converted to string

**Anything else we need to know?**: 

**Environment**: Windows
- Grafana version: Latest - v6.4
- Data source type & version: Elastic search 
- OS Grafana is installed on: Windows 10
- User OS & Browser: Chrome
- Grafana plugins: Table
- Others:

**Comment by AnushaBoggarapu** [comment]
Hi Grafana Team,

This issue happens with trailing white spaces to the string. Any update on it?

Thanks
Anusha

**Comment by sakjur** [comment]
👋 

Thanks for the bug report. For those of you experiencing this bug, please add a :+1: to the first comment so that we can see that there is some traction to get this fixed. Spontaneously I feel as though having trailing spaces and using value mapping is a bit of an edge case and as such is not a high priority for the Grafana team.

In case someone in the community would like to take a stab at solving this issue, you're welcome to do so 🙂

**Comment by zoltanbedi** [comment]
I wasn't able to reproduce this so I'm going to close this issue for now. If you think this is still happening we can reopen and investigate that.
