### ISSUE TITLE
Min time interval ux: Notify the user that time interval doesn't go below 15s

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#22001]
**What happened**:
"I was using a very short prometheus scrape interval (1s) because it was interactive so that people could get faster feedback…. When displaying things with a very small range vector (~5s), a whole lot of stuff fell through the cracks because the default grafana step never went below 15s.  Took me a while to figure out what was going on and realize I needed to update the Min time interval"
— #grafana-fails, public slack 
https://grafana.slack.com/archives/CSKQV9Y5B/p1578923076004500

Not sure how to solve this – show a tooltip/info box whenever users are displaying a small range vector with a too-big min time interval?

**Comment by ivanahuckova** [comment]
This PR should fix this https://github.com/grafana/grafana/pull/36422

**Comment by aocenas** [comment]
As we tried and then abandoned this @ivanahuckova can you write down some reasons why?

**Comment by ivanahuckova** [comment]
This was actually changed during the prometheus migrations and I think we can close it. Basically if user sets up scrape interval in data source to be 15s, then sets up min step in query editor to be 5s and calculated step based on (to - from)/width of graph is 10s on frontend the final used interval was 15s (based on scrape interval), and on backend it was 10s (considering min step) and we had agreed that backend behaviour was correct. So this wouldn't happen anymore. You can find more info here: https://raintank-corp.slack.com/archives/C8C98CETS/p1631089311064900. 

**Summary on why we abandoned `min|max|exact` step  modifier:**
We have implemented `min|max|exact` step modifier, but we decided to remove it after the fact, that it became too confusing.  W always calculate `safeStep` which is `timeRange/11000`, because Prometheus can't return more than 11000 results and it would result in error. And if the user selects too small step, we adjust it instead of making query fail. So now even though you've set exact/max step, if it was too small and the query would produce more than 11000 results, we change it to `safeInterval`.  Which is confusing.

**Comment by jessover9000** [comment]
I guess the main issue of the user here was that they didn't notice the discrepancy between what they manually set and what Grafana actually does / a lack of feedback from the interface when things aren't working right. Abandoning the step modifier means that the user isn't able to cause this issue any more? Or what exactly do you mean? 🤔

**Comment by ivanahuckova** [comment]
What I mean is that now you can set min step in Query editor as previously, but if your min step is **lower** than the scrape interval set on data source level, the min step value is considered. 

Previously:
```
min interval: 10s (query editor)
scrape interval: 15s (data source config)
calculated interval: 5s (grafana calculated interval based on the size of your screen so 1 pixel is 1 data point)

final interval 15s
```

Now:
```
min interval: 10s  (query editor)
scrape interval: 15s (data source config)
calculated interval: 5s (grafana calculated interval based on the size of your screen so 1 pixel is 1 data point)

final interval 10s
```

**Comment by jessover9000** [comment]
Ok, this sounds like at least the behavior of Grafana is now consistent with the settings the user enters there :) I think we can close this issue then and review again if anyone complains about it ;)

**Comment by ivanahuckova** [comment]
Closing the issue. 🙂
