### ISSUE TITLE
Elastic: Metrics results with Invalid date {}

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#22015]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Access play.grafana.org
Go to Explore
Select 'Elastic Metrics' datasource
Select Logs
See "Invalid date {}"

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
@aocenas I was doing some investigation and *Invalid date* here actually triggers https://github.com/grafana/grafana/issues/24077, as it results in null in time field which throws error in Table. Fixing this is also going to solve https://github.com/grafana/grafana/issues/24077.

**Comment by ivanahuckova** [comment]
This issue is probably connected to our data source config and/or data that we are sending. In data source settings, we have specified that the time field name is **@timestamp**, but we are not receiving its value in response, therefore it is null (and displayed as invalid date). 
![image](https://user-images.githubusercontent.com/30407135/81300031-6f3d0780-9077-11ea-9917-75862b3dde79.png)
This is the response from elasticsearch-v5 - no @timestamp:
![image](https://user-images.githubusercontent.com/30407135/81301316-330aa680-9079-11ea-8213-b54e58e01af4.png)

**Comment by Estrax** [comment]
@aocenas can confirm - `Invalid date` is caused by a lack of time field and its value in response. I don't see any good solutions to that, because they either lead to possible change of logs order or the user is going to lose some context if we e.g. hide that column. Maybe we can just display a kind of a warning that the time column has some NA/NaN values inside?
