### ISSUE TITLE
Alias changes do not propagate to overrides

### ISSUE THREAD

**Issue by raimondi1337** [grafana/grafana#22020]
Steps to reproduce:
- Add influx DB measurement to graph
- Fill in alias field
- Click on higher value series name/color in legend
- Set to Y axis
- Change name of alias

Line seems to disappear if you have a lower Y left max than the Y right max, but values in tooltip and legend remain. Took me a while to figure out why my line was there but not. It's a bad state. If you change the name of a series it shouldn't unset the overrides that apply to that series.

**Comment by sakjur** [comment]
The series override specifies "alias or regex" as what it's looking at for applying the override. It's not connected to a particular series, but rather to the alias of the server. To dive into why this matters: If you have an override for `kittens` and three time series all with the alias `kittens` and changes the alias of one of the series to `cat`, what should be the behavior? Should it duplicate the override, change it into a regex which applies to both, move the override together with the series and break the two remaining kittens series or simply assume that the override for `kitten` does no longer apply since the alias is now `cat`?
