### ISSUE TITLE
How to modify existing plugins?

### ISSUE THREAD

**Issue by bouaouio** [grafana/grafana#22065]
So I've been wanting to experiment integrating say an internationalisation library, the likes of i18next, into existing Grafana plugins, like the Graph or the Gauge. I was able to do simple stuff like date formating, language translation and others, but using CorpGlory's webpack version of the Graph Panel.

I would like to apply such modifications in the preinstalled Graph Panel that comes with Grafana, but I have no clue how to do so.

By that I mean I do not know how to add libraries, node modules, or source code to the existing plugin and recompile it to save such modifications.

I'd be really happy to have some insight on this matter.

**Comment by sakjur** [comment]
Hello @bouaouio,

The issues in this repository is primarily for bugs and feature requests regarding Grafana. Questions about Grafana in general, including plugin development is best taken on https://community.grafana.com to make sure we're staying focused on the Grafana development here.

As for the built in panels, they're part of the core Grafana code base and not distinguished as separate plugins. To get started with Grafana development, you can follow the [developer guide](https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md).

(+ before you go ahead and spend a lot of time on this project, if you'd want your changes to be merged to Grafana, please either find an existing feature request or open a new one aligned with your goal so that we can discuss your proposed changes and you can get an indication of whether or not the feature you're thinking of would be merged)

Good luck!
