### ISSUE TITLE
Use same color for series with same name / alias

### ISSUE THREAD

**Issue by cbarraford** [grafana/grafana#221]
When having a dashboard of several graphs with the same hosts, it would be nice if the same color is used for a host in all of the graphs. You'd need to be able to specify which unit within the metric path that should be used to calculate the default color on.

**Comment by czchen** [comment]
Hi @torkelo 

Is it possible to implement `make color changes apply to all graphs on the dashboard with the same series name` first? It will be very helpful because I don't need to pick color for every series in every graph in a single dashboard anymore.

As for `hash the series name (alias) and with that hashcode get an index into the colors array.`, I think you don't need to worry about color distinguishability because if the series count is small (< 10), every color can be distinguishable with each other, and if series count is big (> 30), the graph will not be clear no matter how you choose the color.

**Comment by nhooey** [comment]
Make sure this feature is compatible with Graphite's `aliasByNode()` and `aliasSub()` functions, in that the colour hash is generated based on the resultant series name, and not the unmodified metric name.

**Comment by xlash** [comment]
+1

**Comment by nhooey** [comment]
@xlash Please use the new "reaction" feature of GitHub so we don't get notified of your "+1" message.

**Comment by jifwin** [comment]
+1

**Comment by anhlqn** [comment]
Any chance that this feature will be implement in future releases? Kibana added this feature in 4.x https://github.com/elastic/kibana/issues/485, but I'm not sure how hard it is to add it. Our dev teams love Grafana for metrics.

**Comment by oplehto** [comment]
This would be excellent. Perhaps a combination of the hashcode and a global map would be a good solution. I would foresee that a combination of automatic and manual mapping would work for many cases: 
- Hashcode would automatically map colors consistently
- User could correct manually any colors that clash and the result would be saved into a global color map where a series regex is mapped to a color

Ideally the global map would have an API exposed so one could programmatically query and configure colors.

**Comment by eranrund** [comment]
Any news on this? Thanks! :)

**Comment by haguenau** [comment]
> Is this still relevant?

Yes. I would be interested in such a feature.

**Comment by wilfred-centrality** [comment]
We need this feature. Thoughts on how it should be implemented welcome

**Comment by Ruakij** [comment]
This would be very helpful indeed

**Comment by vbence** [comment]
In today's setup colors get very same-y after 16, greens can be still discerned when next to each other, but different cyan versions look pretty much the same. I would not be very concerned for getting similar colors.
