### ISSUE TITLE
@grafana/* breaking changes

### ISSUE THREAD

**Issue by vankop** [grafana/grafana#22165]
Hi all! So first of all I wanted to say thanks for rich plugin system. I already have written several one:
https://github.com/ozonru/data-grid-grafana-plugin
https://github.com/ozonru/template-value-grafana-plugin
and other custom plugins for our organization

All our plugins based on official react boilerplate https://github.com/grafana/simple-react-panel .
However, we faced with problem that `@grafana/*` packages (especially @grafana/ui @grafana/data) changes there are public API **a lot** between minor releases.

**What happened**:

minor upgrade `@grafana/ui@6.4` to `@grafana/ui@6.5` a lot of public API migrated to `@grafana/data`, more info [in this commit](https://github.com/ozonru/template-value-grafana-plugin/commit/68b23e743f387fc31e52385b3a858175b302a14d)
minor upgrade `@grafana/data@6.4` to `@grafana/data@6.5` changed `DataFrame` interface (new location for labels), more info [in this commit](https://github.com/ozonru/data-grid-grafana-plugin/commit/1f0760af18c94e7914ec9bf7669a6ce66ce023c8)
minor upgrade 6.5 to 6.6:
1. changed thresholds interface (need to migrate plugins options since previous interface will broke plugin) https://github.com/grafana/grafana/blob/6.6.1/packages/grafana-data/src/types/thresholds.ts
2. changed `FieldDisplayOptions` override behavior..

Could be other breaking changes.. Did not migrate all my plugins yet. Also I wanted to point that all this changes doesn't listened in release notes

**What you expected to happen**:

Ideally stop breaking public API.. Since grafana is tool with critical severity (in our organization there are SLA on it) grafana update comes to a lot of **engineering cost**

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Nice to have:
- Keep storybook healthy (maybe host publically), right now I need to read grafana sources a lot to write complex plugins.
- Make prettier and linting optionally in `@grafana/toolkit`. Don't block build with linting.

**Environment**:
- Grafana version: 6.4-6.5
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
@vankop thank you for reporting this! 

We are now trying to make the @grafana/* APIs stable to limit the number of such issues, so please consider the packages being alpha state. Since packages are considered alpha and we are following the Grafana versioning scheme, there might be situations until we release 7.0 when the breaking changes are introduced in minor release. We are also going to improve the messaging when it comes to breaking changes introduction. Sorry for all the trouble!

When it comes to Storybook and @grafana/toolkit requests could you please create a separate issues for those? We plan to have Storybook running publically in upcoming weeks .
