### ISSUE TITLE
Switch organization popup not order alphabetically

### ISSUE THREAD

**Issue by deathwarrior60** [grafana/grafana#22162]
**What would you like to be added**:
In the popup to switch to an org, the organization should be alphabetically ordered (like it was before)

**Why is this needed**:
I have like a thousand org, trying to find the one is ... hard

**Comment by sakjur** [comment]
Looks like an oversight from the migration of the switch org popup to React that they're now sorted by the organization's numeric ID instead of by name.
If someone from the community would like to fix this it's a matter of making sure this is sorted correctly (the array arriving from the backend should already be sorted alphabetically).

https://github.com/grafana/grafana/blob/ba7c9312868c9a7168334670bc244d71ad667217/public/app/core/components/OrgSwitcher.tsx#L30

https://github.com/grafana/grafana/blob/ba7c9312868c9a7168334670bc244d71ad667217/pkg/services/sqlstore/user.go#L320

**Comment by vikkyomkar** [comment]
@sakjur I will create a PR for this issue
