### ISSUE TITLE
Community call #2

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana#22198]
Join us for the a Grafana community call to chat about Grafana development.

Tuesday February 25, 16:00 UTC

We're going to keep things casual and open up for questions from anyone attending. Join in if you're interested in ongoing Grafana development, our roadmap, or have questions about specific PRs and issues.

Subscribe to this issue for updates and the Zoom link (to be posted here on the day of the call).

**Comment by marcusolsson** [comment]
Please join us for the community call today at **16:00 UTC**:

[Join the Zoom call](https://grafana.zoom.us/j/301983945)

[Meeting notes](https://docs.google.com/document/d/1GpgvanMeNqf-CDegv6E0yAV1s2f7H2knUFuNouqwX3A/edit)

**Comment by zhagyilig** [comment]
Hi, we are using Grafana with Zabbix plugin as datasource.
In order to monitor cpu usage. Unfortunally, Zabbix item is cpu idle-time, so we need to convert it this way: <CPU_IDLE_TIME> *-1 + 100. When this is done by a query in database (in the case we are acquiring metrics from other tools), we just embed this calculation into the query in Grafana. Now using Zabbix plugin, we cannot see how we can do such thing.
For us is very important to normalize the way cpu usage is shown so it is very important to convert idle time to cpu usage.

Thanks in advance.

**Comment by sakjur** [comment]
@zhagyilig You're more likely to get an answer to your question if you ask it in the community forums on [community.grafana.com](https://community.grafana.com). This is an announcement for our community calls, questions not related to the call itself are unlikely to be answered here so that we can stay on topic and make sure this thread stays readable.
