### ISSUE TITLE
Allow all data sources to be proxied through the server

### ISSUE THREAD

**Issue by waqark3389** [grafana/grafana#22311]
I am using Prometheus as a Data Source. Grafana is running inside Docker using Amazon RDS as backend. Grafana users access Grafana from many locations and I have my Prometheus server locked down to certain IP addresses. When accessing from a new location I must whitelist the IP address the browser is connecting to Grafana from in order to get access to Prometheus dashboards. 
Can we have a feature which allows for proxying all calls made to the data source through the Grafana server? 

GF Version: 6.5

**Comment by sakjur** [comment]
An option to do that exists in the datasource settings but disappeared in 6.5 because of a bug. It has since been reintroduced with 6.6.1 as of #21833.

See the Access option 👇 
![Screen Shot 2020-02-19 at 15 32 09](https://user-images.githubusercontent.com/298945/74843980-06be7400-532d-11ea-9c78-9a6804a3a27a.png)

**Comment by aknuds1** [comment]
Thanks for chiming in @sakjur! Assuming we can close this.
