### ISSUE TITLE
Hungry Rows

### ISSUE THREAD

**Issue by gretamosa** [grafana/grafana#22368]
**What happened**:

There are some hungry rows in latest Grafana version.

**What you expected to happen**:

No hungry rows.

**How to reproduce it (as minimally and precisely as possible)**:

See GIF

![captured](https://user-images.githubusercontent.com/16796053/75036453-2e8b1480-54b2-11ea-93b0-ba7772d47337.gif)

**Anything else we need to know?**:

Not sure if it is duplicated.

**Environment**:
- Grafana version: play.grafana.org

**Comment by ChrisGet** [comment]
This same behaviour happens when you add a new row to a dashboard. If you have "loose" panels (panels that are not part of a row) at the top of the dashboard and then add a row to the dashboard, the new row automatically consumes all loose panels.

**Comment by shanson7** [comment]
The workflow I need to use as-is is to add a temporary row to "eat" the loose panels, then add the row that I want to keep. I fold the rowToKeep and drag it into place then delete the temp row (making sure to delete row only, not panels too). Not a terrible workflow, but moderately annoying.

**Comment by joshhunt** [comment]
This is the expected behavior of rows in Grafana. Collapsing a row will hide all panels up until the next row, or the end of the dashboard.

I agree that there are some opportunities to improve the usability of rows so I've made a Discussion to talk about that https://github.com/grafana/grafana/discussions/42308
