### ISSUE TITLE
DataLinks: Links cause full page reload when linking to other dashboards or same dashboard 

### ISSUE THREAD

**Issue by Ultraseamus** [grafana/grafana#22380]
**What would you like to be added**:
Data Links seem very powerful, and go a long way towards making graphs/charts within Grafana more interactive. Even if you ignore their use case of helping to link out to 3rd party tools, they have the potential to be a much more powerful version of the +/- filter options that only show up on tables, and only work for ad-hoc template variables.

The trouble with the current implementation is that there is no way to configure a Data Link to update the current dashboard without doing a full page refresh (which can be very disruptive).

**Why is this needed**:

There should be another configuration option where you indicate that this Data Link is referencing the current dashboard. And when that is the case, click on it should just update the template variables and trigger panel refreshes as needed. The logic for this is really already built since there are functions designed to take parameters from the query string, and the ContextMenu item takes a parameter for an "OnClick" function. It all just needs to be hooked up.

That is essentially what I did in a private branch. If you want to link to the current dashboard, I pass in an OnClick function that calls into VariableSrv, and if that OnClick function is defined, I prevent page navigation as a result of clicking on the link. Currently, the URL is passed in the same as before, I just pull out the query parameters and run them through VariableSrv updates.

There are probably cleaner ways to accomplish this, but it does demonstrate how close it is to becoming an even more valuable feature.

**Comment by torkelo** [comment]
This was fixed in 6.6 , you should be able to update variables in the same dashboard with data links in 6.6

**Comment by Ultraseamus** [comment]
We are actually already running Grafana 6.6. It's possible we are talking about slightly different things?

As it is now, you can update variables in the current dashboard, but it means reloading the page, which is not ideal. A refresh can take awhile if you have a lot of templates, and you loss your place in the dashboard.

For my personal implementation of this feature, I added "e.preventDefault();" here: 

https://github.com/grafana/grafana/blob/aeab27c34cf8725530983e475be668470db7b5e3/packages/grafana-ui/src/components/ContextMenu/ContextMenu.tsx#L263

to stop the page navigation (when the url was for the current dashboard). Along with other small changes to pipe through the url to VariableSrv to have it converted into template update commands.

**Comment by matthubb** [comment]
Using a data link to update the current dashboard variables was a thing that I had sort-of working with an earlier version of grafana using a nasty amount of javascript in the link. The javascript links don't work since upgrading to v7.0.

It would be super useful to be able to update the current dashboard by clicking on a data link. My reading of these three other issues is that they all want this too:

https://github.com/grafana/grafana/issues/9259
https://github.com/grafana/grafana/issues/21693
https://github.com/grafana/grafana/issues/21123

One use case, for example is a dashboard that shows the aggregated information for a network device in one panel, and additional panels show per-port information, the per port information selected by template variable, links from the first panel update the variable used to construct the subsequent. I realise there are other ways of achieving this with multiple dashboards, but this form of drill down facilitates richer data-lead decisions about where to drill down.

**Comment by torkelo** [comment]
this should work, if your link is to current dashboard and includes  var-variableName=expressions etc , so not sure what more we can do

**Comment by matthubb** [comment]
Clicking on a data link which is to the current dashboard with variables set results in the page being reloaded.

This request is for a data link to be able to update the template variables of the currently rendered dashboard, causing any dependent panels to update appropriately.

**Comment by Stono** [comment]
> This request is for a data link to be able to update the template variables of the currently rendered dashboard, causing any dependent panels to update appropriately.

This is what we've just reported in https://github.com/grafana/grafana/issues/25115

Stopped working following v7 upgrade

**Comment by torkelo** [comment]
unable to replicate

**Comment by torkelo** [comment]
I can replicate the problem that links cause a full page reload: 

the target defaults to _self , it should not do that 
https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/field/fieldOverrides.ts#L370

**Comment by torkelo** [comment]
closing in favor of this bug report  https://github.com/grafana/grafana/issues/25115
