### ISSUE TITLE
Cannot add user if using OAuth and login form is disabled

### ISSUE THREAD

**Issue by ThisIsAreku** [grafana/grafana#22486]
**What happened**:
I can't add users to allow them to login only using Google OAuth2

**What you expected to happen**:
When disabling the login form to allow users to login only using GAuth, i expect being able to manage which users can login through OAuth

**How to reproduce it (as minimally and precisely as possible)**:
- Enable Google OAuth2 login and deny sign-ups
- Disable Login form
- Invite a user
-> It fail with a message "Cannot invite when login is disabled."

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.6.2 (3fa63cfc34)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
I'm checking with my colleagues to see if this is a bug. It's similar to #17824, although that might relate only to existing users.

**Comment by ThisIsAreku** [comment]
Yes, maybe I should have commented on this issue instead. I feel like #19048 wasn't fixing the right issue. When using Google OAuth i don't get how Grafana can check if the user is existing or not

**Comment by aknuds1** [comment]
I think #19048 solves a different issue from what you're having, i.e. inviting an _existing_ user to an org. Wrt. to your own issue though, I hear from my colleague that you should instead (of inviting a non-existent user to an org) use Server Admin -> Users -> New user.

**Comment by ThisIsAreku** [comment]
You're right, i missed the setting on Server Admin. it work without issues this way. Thanks for your time 👍

**Comment by aknuds1** [comment]
Great!

**Comment by ScubaDrew** [comment]
> You're right, i missed the setting on Server Admin. it work without issues this way. Thanks for your time 👍

Where is `Server Admin` I do not see this anywhere in Grafana. I only have "invite" under the Configuration -> Users tab

**Comment by bjolivot** [comment]
> Where is Server Admin I do not see this anywhere in Grafana. I only have "invite" under the Configuration -> Users tab

There is a shield icon on the left bar.
If it don't shows up, then you are only Org Admin, not general admin, you need to log with "admin" user then give your personal account global admin right.

**Comment by pjdewitte** [comment]
We have a similar server configuration (OAuth + login form disabled), and I would argue that you shouldn't need to be Server Admin to invite new users in this set-up. In our company, only the IT department is Grafana Server Admin - for good reasons.

What we do now (as Org Admin), when we want to add a new colleague to our Grafana Organisation:

1. Ask the colleague by email to log in with OAuth. The colleague can log in, but cannot see the Organisation dashboards yet.
2. Invite the user to the Organisation using the email address. The user is added immediately since the email address is known.
3. Email the user that he can log in again.

Obviously, it would be much more convenient if we could just invite the new colleague to the Organisation, after which the colleague receives an email from Grafana, can log in and see the Organisation dashboards.

The message is "Cannot invite when login is disabled.". Could it be that the check needs to be changed from "login form disabled" to "all login mechanisms disabled"?
