### ISSUE TITLE
Pass Referer in Datasource Proxy

### ISSUE THREAD

**Issue by disfluxly** [grafana/grafana#22550]
**What would you like to be added**:
Allow passing the `Referer` header in the data source proxy.

**Why is this needed**:
As part of https://github.com/grafana/grafana/issues/13949, the `Referer` was removed from getting sent along with the data source proxy. This was highly useful for troubleshooting purposes.

For example, this allowed us to pinpoint which dashboards were causing performance problems due to bad queries. This was _pivotal_ in helping us quickly identify the source of long-running queries that would cause the CPU on Influx to spike.

We currently have a different proxy that sits between Grafana and our data sources to do introspection of the queries and route them accordingly. We wanted to use the `Referer` in order to tag our Jaeger Traces. This would allow us to very easily, and in close to realtime, identify queries that took (for example) 5 seconds to execute and which dashboard executed that query.

**Comment by marefr** [comment]
There's already X-Dashboard-Id and X-Panel-Id headers sent (I think) that you could use. Issue open for adding X-Dashboard-Uid (#17410). Could possibly add an X-Referer header?

**Comment by disfluxly** [comment]
Hmmm. I'm not seeing those two headers when I'm inspecting request headers outbound from the UI.

I also don't see them in the headers my application receives from the dataproxy.

A quick search in the repo shows that they may only be available for graphite/prometheus datasources. I'm using Influx.

**Comment by Mugglephilip** [comment]
We also need this feature, since we use the Referer to count each dashboard's visits.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
