### ISSUE TITLE
Dashboard lint / analysis and schema validation 

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#22579]
**What would you like to be added**: A tool that can perform a lint like analysis on a dashboard.  Some things that could be easily caught:

1. A graphite query that is missing a closing quote
2. A reference to a data source that has been removed

Nice to haves would be additional analysis suggestions such as:
1. Duplicate queries - promote cross referencing.
2. Potentially running the queries and display performance metrics (maybe that should be part of Grafana)

**Why is this needed**:
We have thousands of dashboards and hundreds of users.  Configuration of the system can change and break existing dashboards.  Also users can make mistakes and it can be very difficult to see simple syntax errors in complex queries.  Having a tool that can to this would be very useful.

**Comment by shalstea** [comment]
One interesting idea - we export, nightly all dashboards into github as a backup.  So we have all the json files there.  Ideally we could run a job nightly across all the dashboards and give end-users a report on lint issues that need to be addressed.

**Comment by torkelo** [comment]
Interesting idea.

**Comment by torkelo** [comment]
sounds like a cool thing.

@Dieterbe what do you think?

**Comment by Dieterbe** [comment]
I love it! Surely this is not surprising :)

@ryantxu and I have been discussing some things along these lines as well. Ryan in particular had some ideas around we could make reusable components that help with parsing dashboards and converting them from one format to another (e.g. converting old style queries to tagged based ones). Not sure if this is very related though, but one important decision would be whether we write the linter in go or javascript.
For graphite query validation, perhaps we could reuse the code we have for this in metrictank.

Another idea would be finding queries that end on ".select metric" 

To be clear, everything discussed so far is static analysis.
Could also be interesting to make it dynamic (e.g. find queries that never return any data, or always result in errors). 
Also interesting how we could tie this to meta analytics.

**Comment by shalstea** [comment]
Finding old panels.  When upgrading to grafana 7 - we found "table-old" in a json when trying to debug a problem.

**Comment by mahob** [comment]
This feature is also interesting when using provisioned dashboards. I like to provision a certain subset of dashboards and when merging different branches you have to manually resolve merge conflicts in dashboards. Being able to lint or validate the dashboards before building new Docker containers would be great.

**Comment by nicolastakashi** [comment]
It's very interesting feature, any news about that?

**Comment by nvtkaszpir** [comment]
Was thinking about something similar recently, here are some suggestions:
## general

- dashboard has labels
- dashboard has time in UTC
- dashboard has shared corsshair
- labels?

## panels

- check if datasource is valid - to avoid grafana dummy datasource
- expr is not empty (or if the panel has queries at all)
- set min/max values (especially for percentage)
- for certain graphs display null values as null (disable connected)
- log scale does not have 0 (otherwise weird values are rendered)
- half screen width is actually 50%
- is using dynamic labels from query then use them in double curly braces (this might be tricky)
- prefer `$__rate_interval` instead of `$__interval`

## query specific

- if expr has specicic label selectors (for example kubernetes namespace)

**Comment by minhluantran017** [comment]
+100 for this feature.

Also seeing this one from Grafana: https://github.com/grafana/dashboard-linter
