### ISSUE TITLE
OAuth: search groups in access_token

### ISSUE THREAD

**Issue by GreenRover** [grafana/grafana#22631]
**What would you like to be added**:
The `role_attribute_path` JMESPath expression  should additionaly lookup the OAuth `access_token`.

**Why is this needed**:
Currently the "role_attribute_path" only checks `api_url` and/or `id_token`. However, some OAuth providers, for example Keycloak, don't provide group/role information at this point.

Those are normally included in the access token. So for Keycloak, a search would look like the following, in order to match the roles in access_token:
```
role_attribute_path = contains(resource_access."client-monalesy-test-int".roles[*], 'grafana_admin') && 'Admin' || contains(resource_access."client-monalesy-test-int".roles[*], 'grafana_editor') && 'Editor' || 'Viewer'
```

**Comment by aknuds1** [comment]
Can you please rewrite the issue using our provided issue template? That would make it much easier for us to interpret the issue, thanks.

**Comment by GreenRover** [comment]
@aknuds1  Better?

**Comment by aknuds1** [comment]
Yes, much better, thanks!

**Comment by ch-egli** [comment]
The request by @GreenRover seems to be more than justified, since the OpenID Connect specification does not provide a standardized claim for roles: 
[https://openid.net/specs/openid-connect-core-1_0.html#IDToken](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) 
[https://openid.net/specs/openid-connect-core-1_0.html#Claims](https://openid.net/specs/openid-connect-core-1_0.html#Claims)
Therefore it seems that the Grafana mechanism for authorization relies on _optional_ values that are not necessarily present in a given OAuth infrastructure. If a company's OAuth Server does not provide roles in the ID token (resp. /userinfo endpoint), the authorization with Grafana is not possible... This is my case: I use Redhat SSO that is currently based on Keycloak version 4.8.3.

**Comment by marefr** [comment]
@ch-egli thanks. So do you have reference to specification saying that claims for roles/groups should be in the access token?

**Comment by ch-egli** [comment]
@marefr I was pretty sure to find it in [https://tools.ietf.org/html/rfc7523](https://tools.ietf.org/html/rfc7523)... But it seems that OAuth 2.0 resp. OpenID Connect specs do not prescribe how roles/groups should be made available through access or id tokens. 
Anyway, at least for users of Redhat SSO / Keycloak that cannot influence the enterprise's OAuth infrastructure it would be helpful to provide a solution to access the groups/roles in the access token.

**Comment by rosieks** [comment]
What happen to this issue? It blocks me right now. Roles should be read from access_token while right now you expect them to come from ID token. ID token is about who you are, not what you can do.
