### ISSUE TITLE
Interpolation of className coming from emotion css prop is deprecated.

### ISSUE THREAD

**Issue by Estrax** [grafana/grafana#22645]
**What happened**:

A number of lines such as:
```
console.error node_modules/@emotion/serialize/dist/serialize.cjs.dev.js:180
>>       Interpolating a className from css`` is not recommended and will cause problems with composition.
>>       Interpolating a className from css`` will be completely unsupported in a future major version of Emotion
```
are being logged during tests/build.

**What you expected to happen**:

No emotion errors in Grafana repo.

**How to reproduce it (as minimally and precisely as possible)**:

Fetch a devenv and run `yarn test`. Look at components using emotion that do something with innerElement on hover over the outerElement, like tooltips.

Minimal generic example to show what we are talking about:
```jsx
const innerComponent = css`
  display: none;
`;

const outerComponent = css`
  &:hover .${innerComponent} {
    display: initial;
  }
`;

<div className={parent}>
  <div className={child} />
</div>
```
also mentioned there: https://github.com/emotion-js/emotion/issues/1217

**Comment by mckn** [comment]
hmm, do we have a real world example on this one? Because my initial way of solving this would be to add the `&:hover` to the `innerComponent` instead. If it depends on a context I would pass an indicator in that as a props that you can use when creating the styles.

**Comment by Estrax** [comment]
@mckn sure. Please look at [lines 67-82 of getLogRowStyles at @grafana/data](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Logs/getLogRowStyles.ts#L67-L82) and especially at line 73. It tries to interpolate the class name from the css property declared on line 12. We have quite a few elements such as this one, e.g. tooltips and popovers.

**Comment by dprokop** [comment]
Some discussion around this issue https://github.com/emotion-js/emotion/issues/1186

**Comment by mckn** [comment]
Just had a quick look at the example above and I understand what we are trying to achieve with `context` but I think we can do some refactoring to remove the need of interpolating classNames. I would even say that structuring the css/styling that way when using frameworks as emotion is an anti pattern and should be avoided.

**What, are you crazy @mckn?! (you might think)**

Bare with me and I will explain my point of view 🙏 I am thinking like this: when using react the goal is to create small and simple components that, by using composition, will be combined into a more complex UI. A framework like emotion makes it possible to write styling the same way and enables us to let the styling live together with the component.

So if we take the example referenced above. I am guessing that we are doing the `context` interpolation to be able to set stylings to an element that has the `styles.context` but only if it exists inside an element that has `styles.logsRow`. 

Instead of doing this in styling I would create the possibility to affect the behavior of the component when doing the composition. In this case there are a couple of ways of doing that (probably more but this is from top of my head).

- Create another component that will apply the styling that will be used in this scenario.
- Add the possibility to extend the styling from the parent component so you can control the look and feel when consuming the component.
- Pass some kind of flag/property that makes the component apply the styling internally. 

The benefit of doing it this way is that you get a clean api for the component. It will be easier to reuse  and by only looking at the component you will understand that the look and feel of the component can be changed/control from the outside/parent. 

Compared to the example above you have to look at the styling and also go through the parent tree to understand that the component will have other look and feel depending on where it is used.

Wow, that became much longer that I intended but hopefully it makes sense 🙈. If not I am super happy to jump on a call to talk more about this and maybe have a look at some more examples.

**Comment by dprokop** [comment]
>  I would even say that structuring the css/styling that way when using frameworks as emotion is an anti pattern and should be avoided.

I think this is very important note, it's worth landing in our code style docs.

Completely agree with with what @mckn said above. It needs to be decided on a case level, but in this particular scenario given in the PR description I think it's more about rendering vs not rendering element when it should / shouldn't be visible rather than controlling visibility with styles. With that in mind the `display: inline` should be encapsulated in inner's component styles, and possibli(if necessary) the display style should be controlled via either component props or state.

Given the React's and Emotion's declarative approach it's the component that requires styling that should encapsulate the styles rather that any other component in the tree.

**Comment by aocenas** [comment]
@mckn @dprokop I think the basic use case for this is something like a `button`, that has some style change on hover, but you also want to change style of `icon` that lives inside it. In this case the child component needs to know when button is hovered. The only way how to do this that I know outside of css nesting is to use onMouseEnter/Leave, change state of the button imperatively and pass that to the `icon`. Which is doable but not great.

Other usecase is external libraries where you don't have easy way to pass this as props.

**Comment by mckn** [comment]
@aocenas is it possible to link to that use case? Would love to have a look at it to see if I can think of anything 🙏

**Comment by aocenas** [comment]
@mckn well not a good one, but for example when I was migrating this https://github.com/jaegertracing/jaeger-ui/blob/master/packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanBarRow.css#L59 to emotion I just did not figure out easier way to do it.

**Comment by Clarity-89** [comment]
@mckn I also had a similar case to the above when migrating search results: https://github.com/grafana/grafana/blob/master/public/sass/components/_search.scss#L132. In this case when hovering on the search result row, the icon should be shown. 
In the end I just targeted the `a` element, but that doesn't feel like the best option here:
```
   wrapper: css`
        &:hover {
          a {
            opacity: 1;
          }
        }`
```

**Comment by mckn** [comment]
Awesome, love the examples and the activity in this thread. Will have a look at them asap.

**Comment by s-h-a-d-o-w** [comment]
Hm, while I get where you're coming from with the elaborate explanation above @mckn, like @aocenas , I can't help but think that moving from a simple `:hover` to having to handle enter/leave events with JS seems like a step back.

Since this issue was mentioned to me in the context of asking whether using styled-components was ever considered (the one emotion includes), I couldn't help but wonder what the preferred way of achieving something like this is when using that API. Here's what Max Stoiber (the author of the original styled-components - with essentially identical API) said about it: https://stackoverflow.com/a/41010688
And in this case, emotion seems to support it too: https://emotion.sh/docs/styled#targeting-another-emotion-component

But of course then the question becomes whether we would even want to use this approach instead of the current one.
While it would decouple styling from JSX code more (not having to pass around class names) and would remove the necessity of manually maintaining labels, I've only just begun looking at the code and so I'm not aware of whether it would truly fit the current overall architecture. (Although at least back [when it was introduced](https://github.com/grafana/grafana/issues/15438), @dprokop said that it can always be changed later. Of course that was a long time ago... 😉)

**Comment by dprokop** [comment]
All of above considerations are valid. However, we've been using emotion for over 1yr now, and we haven't encountered this issue that much so far, apart from 4 known cases reported by tests. I assume the more SASS styles we migrate to emotion (this wasn't a common scenario so far, most of the styles authored with emotion are new ones) the more vulnerable we might be. No doubt there is valid case for style cascade, especially in the hover scenario, but the cascade should be avoided to keep the styles as simple as possible. And personally I believe it can be avoided in most of the cases.

I like the idea of reconsidering emotion/styled @s-h-a-d-o-w , but I can't help myself taking a pragmatic approach here. To be clear, I'm not saying no to introducing @emotion/styled as an alternative way to style. But _if the problem it's going to solve is the one described here_, then IMO effort of introducing it, maintaining two paradigms of style authoring (yes, we have plenty of emotion css-prop like code already) and maintaining the package itself is significantly bigger compared to refactoring styles that use cascade currently.

So, as long as there is no strong argument for styled, I would stick with the current approach, enable emotion's `css` property from `emotion/core` and remove dependency on `emotion`.

But I'd also love to hear feedback from @peterholmberg @ivanahuckova @tskarhed @torkelo as you guys are also experienced with emotion code in Grafana.

**Comment by torkelo** [comment]
I also have a similar use case of hover over resource card and show buttons inside on hover, and want to use css for this not onMouseOver .  But did not use css interpolation for this but instead a hardcoded className set in the button so that the parent could control visibility via css

**Comment by hugohaggmark** [comment]
I can't recall stumbling upon this issue (yet) while working with emotion in Grafana. But again it seems I haven't worked with the UI for the last 6+ months :) 

I like pragmatism so I agree with @dprokop  and further more I totally resonate with that @mckn wrote above and I think this discussion could be a good candidate for the Front End weekly meeting, I'm happy to move my points in the upcoming Front End weekly to give room for this discussion.

**Comment by s-h-a-d-o-w** [comment]
@dprokop Since it seems we will talk about this soon anyway, I just wanted to note that I agree and didn't mean to simply introduce yet another paradigm. I meant full migration - but based on your and @hugohaggmark 's comments, I suppose the sheer quantity of code may just be too much.

**Comment by mckn** [comment]
Love the activity in this issue! I have not yet had the time to go through the latest examples posted in this thread but I just want to highlight that I am not saying that we should use mouse-events to solve scenarios like this. I agree and think that a solution like that is flaky and unnecessary complex.

What I am hoping for is that we probably can solve those kind of issues by restructuring the code a bit.

![to be continued](https://media1.giphy.com/media/efDT7dqlF5N2LVHG8C/giphy.gif?cid=ecf05e47b0b42b4321740fdcbeec1f5edfa0109938afc407&rid=giphy.gif)

**Comment by aocenas** [comment]
So even though I like to be pragmatic about this there seems to definitely be a problem (needing to change child style on parent:hover), which has multiple solutions and we should probably agree to what that solution is.

So far the solutions to this seems to be:
- use onMouseOver/leave and change prop on the child
- use hard coded class name on the child and use it from the parent
- use styled component pattern and nest the selectors

tbh I don't particularly like any of those but don't see any other especially as I do not see a way to restructure this case in way this problem would go away. So I think maybe we should at least agree on one approach so that people does not have to figure this one by one on their own and it's easier to refactor later on if better approach is found.

**Comment by torkelo** [comment]
not a big fan of this options `use onMouseOver/leave and change prop on the child`, think hover effects should as much as possible be driven by css

**Comment by mckn** [comment]
So I had a look at the different scenarios posted above and I might be naive but I think the solution that @Clarity-89 did [here](https://github.com/grafana/grafana/blob/master/public/app/features/search/components/SearchResults.tsx#L132) is a good and pragmatic way of solving this kind of situations.

I can see scenarios where this won't be enough and in that case I would define a static class name or an attribute as in the following [example](https://github.com/emotion-js/emotion/issues/1186#issuecomment-456252957).

To have good overview on how the styling is applied I would try to keep it as a component internal styling. If, how ever, it should be applied to a child component I would defined the styling in the parent component and then pass the combined `cx` styling as a props to the child component.

One thing that I realize when going through the examples, provided in this thread, is that the className that is used to scope the hover effect is element specific styling. This makes me believe that it would work to keep this internally in a component.

What do you guys think about this approach?

**Comment by Clarity-89** [comment]
> I can see scenarios where this won't be enough 

Yeah, I think targeting html elements directly won't work so well where the need is to target a specific element among the multiple ones. 

> and in that case I would define a static class name or an attribute as in the following example.

@mckn I also thought that to be a preferable approach here but after reading the further comments in that issue, it seems like there are some shortcomings, mainly the class names not being strictly namespaced. Not sure if this is gonna cause any style conflicts down the road, considering we still have a lot of angular styles. Maybe each component could have its name as an internal className?
Additionally, I thought we were moving to using a `css` prop, don't know how it would work with that. 

I think [this comment](https://github.com/emotion-js/emotion/issues/1186#issuecomment-549549817) highlights the fundamental issue here, being the differences between emotion's modular approach vs CSS cascading, which makes it really hard to find a suitable approach. 

> One thing that I realize when going through the examples, provided in this thread, is that the className that is used to scope the hover effect is element specific styling. This makes me believe that it would work to keep this internally in a component.

That's my impression so far as well.

**Comment by aocenas** [comment]
So I encounter this once more. In this case the issue is I am working with somewhat external lib and one way to style it is by injecting custom component for button. The issue is it still passes className to button and this class name is used to do the hover thing, so the button should be visible only if you hover over some area bigger than the button. Issue is that lib also uses emotion for styling so it passes className that is generated from emotion css. Funny enough in out Button component, because we use emotions cx utility, the class from className and Buttons own class are merged into single className and so the old emotions style `el:hover .${buttonClass} {}` does not work just because we use the cx utility.

Honestly I dislike the emotion update quite a lot at this moment :D
