### ISSUE TITLE
Can we have a per datasource switch to disable fetching Prometheus metadata?

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#22702]
Some systems have _a lot_ of metric names (100MBs worth) and fetching them causes Grafana to be sluggish.

**Comment by aocenas** [comment]
@gouthamve This is the same thing you reported isn't it? Was there any update to that regarding whether they run some older version?

**Comment by gouthamve** [comment]
The response from them:

> Hi @gouthamve - we are currently using Grafana v6.5.3 (05025c5).
> Not sure if this is an easy fix though. When we go to the explore tab and type the metric name the problem surfaces. Specifically the problem is in the /api/datasources/proxy/3/api/v1/series part of the call. The resulting json file that thanos-query creates for a high cardinality metric we use a lot is about 200MB in our case. This call is done via ajax and the response is sent to the browser, making it fairly slow / unusable.

**Comment by aocenas** [comment]
@davkal if I remember this fix first took a count of metrics right? So can this be an issue if they have smaller number of metrics but with very high cardinality so this fails on labels autocomplete?

**Comment by davkal** [comment]
The fix for the issue that @gouthamve is reporting is to update to 6.6 or above. There the behavior is as follows:

Our prom language service starts with label lookups disabled,  and then issues a call to `/api/v1/label/__name__/values` and checks the result list length to be lower than 10,000 to enable dynamic lookup.

I'm curious if 10,000 metric names works for them as a threshold or if they indeed have some high cardinality labels. Then we'd need a different strategy.  

But back to the OP's issue, if the response is so big, we need another probing query first to figure out the size of the installation both in terms of metric names (populates the label selector) and in label space (for dynamic label key/value lookup).

**Comment by tomwilkie** [comment]
> But back to the OP's issue, if the response is so big, we need another probing query first to figure out the size of the installation both in terms of metric names (populates the label selector) and in label space (for dynamic label key/value lookup).

Could do a `count({__name__=~".*"})` or even `count(count by (__name__) ({__name__=~".*"}))`, but those queries won't work on Cortex _and_ can be very expensive.

Alternatively, we could add pagination to the Prometheus metadata API - and only ask for ~10,000 name or something.  If we need to ask for more, its a sign we shouldn't ask.  @gotjosh might be able to help you out here.

> I'd only add a switch if all else fails. That label name query is important to populate the metric chooser.

I don't see a way of asking how many metrics names there are that isn't expensive right now.  I think we need a workaround as right now this is basically unusable for some (small) subset of users.  And unfortunately they are the power users.

**Comment by gotjosh** [comment]
> Alternatively, we could add pagination to the Prometheus metadata API

That's certainly an option but would need discussing, Metadata is always kept in memory and we don't do any sorting within Prometheus. It'll be hard to guarantee pages across requests w/o it.

> I don't see a way of asking how many metrics names there are that isn't expensive right now. 

I agree, using the metadata API might be the fastest but it's also not accurate given we never look in TSDB.

> Our prom language service starts with label lookups disabled, and then issues a call to /api/v1/label/__name__/values and checks the result list length to be lower than 10,000 to enable dynamic lookup.

Limiting on length does make sense @davkal, shouldn't we also add a check on size? We could issue a pre-flight `HEAD` request to check the content size before pulling the metric names.   The problem I see is that someone could be using a very long metric name (e.g. an entire HTML page by mistake) and effectively be misleading the current check.

I'm actually surprised to see 100MBs of metric names, in our Prometheis with  ~2.7M active I only see we have about 1800 metric names.

**Comment by davkal** [comment]
Just for a comprehensive take on this, is there a heuristic we can use as a proxy for size? Eg.

- Instant query of `up` and see either how many series there are, or how long it takes.
- results for target or service disco API?

I still would like to know if that huge metric names response is the result of nominal use, or if they did something odd.

**Comment by s-h-a-d-o-w** [comment]
@davkal If I understood it correctly, @gotjosh didn't mean to send a `HEAD` for the expensive query @tomwilkie mentioned (`count({__name__=~".*"})`) but the ones we already do and that return a large result.

At least based on this thread, it sounds to me like the former is slow/problematic but the latter - well, we're already doing that anyway.

If that is indeed the case, can't we really resolve this by doing the `HEAD` check? One would a) hope that the case @gotjosh mentioned, that a full HTML page is used as a metric name, doesn't occur thousands of times in the same prom instance anyway and b) even on the rare occasion that it does - should it not be up to the user to fix that? (I understand that we try to handle things gracefully but given that the other approaches described so far seem to have even bigger downsides, would it not be an acceptable sacrifice?)

And then obviously, if we detect that the size would be larger than a given number, we'd show a message like autocomplete can't be used because the size of their metrics is too large.

**Comment by davkal** [comment]
>> We could issue a pre-flight HEAD request to check the content size before pulling the metric names. 

>  @gotjosh didn't mean to send a HEAD for the expensive query

I think that's what he meant. The point was to run the query but not transmit the results (in an effort not to overload the system.

> @tomwilkie mentioned (count({__name__=~".*"})) but the ones we already do and that return a large result.

We're not using those queries yet. But tom's concern was that the query might not work on Cortex (hosted prometheus), so would be useless for a heuristic. 

Absent any other (cheap) heuristic, I think we might need that tab-completion on/off switch in the datasource after all.

**Comment by s-h-a-d-o-w** [comment]
Well, it occurred to me yesterday that I suppose there would be the option to create a service dedicated only to metric name serving that can match subsets quickly. But I suppose that's out of the question architecturally, otherwise it would've already been suggested here?

**Comment by tomwilkie** [comment]
re: HEAD, I'm not sure Prometheus implements this method for that endpoint.  We can always try and add it.

**Comment by davkal** [comment]
> there would be the option to create a service dedicated only to metric name serving that can match subsets quickly. But I suppose that's out of the question architecturally, otherwise it would've already been suggested here?

Your assumption is correct. We can't influence the deployments that exist in the wild even in the medium term. But the big ones are feeling the pain right now. Grafana can be updated/upgraded with less hassle, so we should go ahead on this.

**Comment by gotjosh** [comment]
From what I'm reading, I think the conclusion is to add the switch to turn it on/off. Sadly, I don't have any better suggestions than the ones proposed here. 

> re: HEAD, I'm not sure Prometheus implements this method for that endpoint. We can always try and add it.

Tom's comment is 100% right. Let me know if this is something worth exploring and I'll try to do what I can to get it in.
