### ISSUE TITLE
Security of multi-tenancy setup with SQL datasource

### ISSUE THREAD

**Issue by EduardSergeev** [grafana/grafana#22742]
We were planning to use Grafana to give external organisations access to some dashboards which would used SQL datasource but our brief investigation showed that it would be completely **unsecure** since apparently, at least in case of SQL, Grafana’s frontend just sends raw SQL query to backend so once a user is authenticated he can just issue any SQL query to the same backend to get any data from DB.

Normally, for secure solution, SQL would never leave backend (would be stored there) with frontend being able to only call predefined stored SQL but looks like it isn’t a case for Grafana.
Maybe the situation is different for other data sources but it seems that SQL + muti-tenancy = unsecure solution at least for now if I am not mistaken.

What we would like to see is a solution which does not allow our clients to issue or even see the raw SQL requests - it should be all contained within backend.

**Comment by bergquist** [comment]
This is because historically Grafana was a frontend-only app and as such queries for all roles was always made from the frontend. 

Never showing queries for certain roles will not be something Grafana will support anytime soon. 

There are some security measurements you can take. Ex orgs in Grafana does not share datasources which would allow different orgs to use the same instance but different instances. 

Also, make sure that the db user reading data from sql only have access to relevant data in the database. 

Grafana Enterprise also includes an option to setup [permissions for datasources](https://grafana.com/docs/grafana/latest/enterprise/datasource_permissions/) to restrict access.

**Comment by bergquist** [comment]
Closing this issue as this suggestion is something we heard before.
