### ISSUE TITLE
Multiple dashboards with the same UID in different folders creates race condition

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#22777]
Given there are two dashboards with the same `uid` Grafana will first create one dashboards but then update the same dashboards in the dashboard with the second dashboard json file from disk. Each time the provisioning feature runs it will flipp between the dashboard json files and delete/insert one of them into Grafanas database. 

This behavior is quite hard to understand for any operator who is not an expert on provisioning Grafana dashboards and something we need to help operators to identify. Given how unusually this is I think error logging should be enough.

**Comment by torkelo** [comment]
related issue: https://github.com/grafana/grafana/issues/12068

**Comment by bergquist** [comment]
If there are multiple dashboard with the same uid using one dashboard provisoniner we will log an error about it 
```bash
EROR[04-09|13:20:39] the same 'uid' is used more than once    logger=provisioning.dashboard type=file name="gdev dashboards" uid=_5rDmaQiz provider="gdev dashboards"
EROR[04-09|13:20:39] the same 'title' is used more than once  logger=provisioning.dashboard type=file name="gdev dashboards" title="Panel Tests - Gauge" provider="gdev dashboards"
```
Having the same check for all dashboard providers makes total sense.

**Comment by ZealousMacwan** [comment]
Grafana : v6.6.2 

I am facing same issue. I have two dashboards with same uid and title in same directory but with different file name. This happened because one was updated with some changes and than JSON was exported so ended up with different file name but same uid and title. Now getting same error.

`lvl=eror msg="the same 'title' is used more than once" logger=provisioning.dashboard type=file`
`lvl=eror msg="the same 'uid' is used more than once" logger=provisioning.dashboard type=file`

For me trouble is I have built the docker image with above and ended up with like,
I see only one dashboard ( of course it picking one of them ) and If I try to save it pops up 

`Someone else has updated this dashboard. Would you still like to save this dashboard?`

And If proceed with "Save and Overwrite", it doesn't save the changes made. Refreshing the page reverts the changes.
