### ISSUE TITLE
Use timeranges using week days in individual graph?

### ISSUE THREAD

**Issue by JeanFred** [grafana/grafana#2295]
(This ties in somehow to #171)

I would like to be able able to use on a single graph time ranges with week days.

My use case is to track the average number of deployments per business day over the weeks. To do that, I query graphite with `scale(summarize(events('deploys'), '7days', 'sum', true), 0.2)&from=monday-8w&until=monday`

I have not been able to do that in Grafana − did I mis it?

**Comment by torkelo** [comment]
no that is  not currently supported.

**Comment by JeanFred** [comment]
Ok ; thank you for the swift answer @torkelo :)

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
