### ISSUE TITLE
Extend last data point to the right

### ISSUE THREAD

**Issue by frigaardj** [grafana/grafana#2296]
Hi @torkelo 

I have a few metrics that are very slow moving (might change once a month or so). To avoid clogging up my OpenTSDB instance I only want to log these metrics when they change. In Grafana, I'm plotting them as a staircase line. However, the problem is that Grafana will only plot data up until the last data point (which is sensible). I was wondering if there is a way to extend the last value all the way to "now", a bit like this (red line drawn on):

![grafanaexample](https://cloud.githubusercontent.com/assets/4301021/8541751/453f0ca4-2488-11e5-8cef-18d1807bbc34.PNG)

Would appreciate your help,
Jack

**Comment by phemmer** [comment]
I too would like such a feature, but *only* for staircase lines. For staircase it makes sense as the staircase shows a horizontal line following the last value up until the next value. Meaning that if this feature were implemented, then as time progresses and another data point comes in, that horizontal line will still be there, just extended further. The same cannot be said for non-staircase lines. The only way that the staircase line would be changed/shortened as new data comes in is if the new data is for the time period already shown in the window (meaning historical points are getting added). As such, I think it makes sense for the feature to be enabled by default.

**Comment by araisch** [comment]
SELECT field(..) last()
GROUP BY time($interval) fill(previous)
![image](https://user-images.githubusercontent.com/35069589/37326968-b3d345ac-2694-11e8-8f77-17d8ec6033e6.png)

With this setting it works partially, but still: If there is no value in the zoomed range it doesn't query the last value before that range. For that there is none value shown at all.
![image](https://user-images.githubusercontent.com/35069589/37326980-c4ed9842-2694-11e8-8dc0-5587743fab1d.png)
This messes up dashboards with fast changing values (measured values) and status values (like switched on/off) because half of the status panels show just nothing when you choose a rather short range of time.

**Comment by torkelo** [comment]
I think this is best handled by OpenTSDB. 

We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
