### ISSUE TITLE
data source names should be case insensitive 

### ISSUE THREAD

**Issue by rajputvishwas** [grafana/grafana#23067]
**What would you like to be added**:
Recently I was performing import operation on Grafana 6.2.0, using dashboard.json file. The import fails with an error - not able to find data source "Prometheus", when I checked my data source name it was "prometheus", so I just changed entries in dashboard.json. After that I am able to successfully able to import the api.

so it would be nice if data source name matching should be case insensitive.

**Why is this needed**:
some custom templates have multiple entries for data source changing it would be time consuming exclusively when you want to automate the process

**Comment by aknuds1** [comment]
I agree that case insensitivity for data source names would be nice. However, since we currently allow for using Prometheus and prometheus as names for distinct data sources simultaneously making this change now could break the setup for some users (unlikely but possible and avoidable). We’d rather not do that, so we’re going to close this particular feature request.

Thanks for the feature request, we agree with the problem statement and we should try to find a solution to that :)

**Comment by AlexKotsc** [comment]
When exporting dashboards, we experience that the data source case is changed. (exported as lowercase, only works as upper case)

This means we have to edit the JSON manually upper casing the data source name.
