### ISSUE TITLE
Apply new designs to Tag components

### ISSUE THREAD

**Issue by Clarity-89** [grafana/grafana#23098]
**What would you like to be added**:
Apply [new designs](https://www.figma.com/file/I34UgAga9JvqjlxfKYZnve/Design-System?node-id=453%3A971) to the [Tag component](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Tags/Tag.tsx) as well as [TagsInput](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/TagsInput/TagsInput.tsx) in grafana/ui.

![Screenshot 2020-03-26 at 10 32 05](https://user-images.githubusercontent.com/8878045/77625865-0c6f3100-6f4d-11ea-9d70-835adf832539.png)

**Comment by rakhi2104** [comment]
@Clarity-89 I've implemented these changes. Need some suggestions on how to handle Accessible font colours based on Tag Background colour.

![Screenshot from 2020-06-16 22-31-34](https://user-images.githubusercontent.com/17671710/84805038-41a58f80-b021-11ea-8a90-9c3f59e71d28.png)
![Screenshot from 2020-06-16 22-31-45](https://user-images.githubusercontent.com/17671710/84805045-44a08000-b021-11ea-95ea-ad48a79535f4.png)

**Comment by Clarity-89** [comment]
Hi and thank you for the contribution! The tag colors are stored [here](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/utils/tags.ts), which are then returned by one of the functions below. Now that I look at that list of colors, I see that there's way more there than in the new designs, so I might need to check it with our UX team first.

**Comment by rakhi2104** [comment]
Thank you @Clarity-89. I've used the same set of colors you have mentioned. But, the font color is default to `gray98: '#f7f8fa'`. Is there any alternative for this?

**Comment by Clarity-89** [comment]
> Thank you @Clarity-89. I've used the same set of colors you have mentioned. But, the font color is default to `gray98: '#f7f8fa'`. Is there any alternative for this?

The way I see it, the new designs have 4 different font colors, which depend on tag background and the theme: 
```
lightTheme = {
  lightBg: '#343B40', // no color in our palette
  darkBg: '#ffffff' // white
}
darkTheme = {
  lightBg: '#141619',  // gray10
  darkBg: '#9FA7B3' // gray70
}
```
Seems like we'll need to add some logic to `getTagColorsFromName` that would return also a `textColor` prop with the correct color.

@jessover9000 @sarlinska do you have any quick feedback on this? Particularly how the tag text color should be determined? Otherwise we might need to pause this update if there is some extra design work needed.

**Comment by jessover9000** [comment]
From the UX side, I have been using the colors designated for the graphs in the ColorPicker component because they are accessible for light and dark theme. The logic of whether to use light or dark text on top of them is currently being decided on a per-color basis because e.g. yellow is always too light to use white text on top of it accessibly. See a legend about that in Figma: https://www.figma.com/file/I34UgAga9JvqjlxfKYZnve/Design-System?node-id=1141%3A141 (The left half should use dark text, the right half should use light text.) 

The original thinking was to use lighter color values in dark theme and darker values in light theme to maximize contrast to the background, so for the tags I used the -lightest and -lighter shade for dark and -darker and -darkest shade for light theme. 

Does that answer the question? If we can come up with a simpler/more logical solution how to apply colors, I'm all for it, but that's what we have now 🤓

**Comment by atymchuk** [comment]
@Clarity-89 This [design system ](https://www.figma.com/file/I34UgAga9JvqjlxfKYZnve/Design-System?node-id=453%3A971)is deprecated. Where can I get the latest?

**Comment by Clarity-89** [comment]
> @Clarity-89 This [design system ](https://www.figma.com/file/I34UgAga9JvqjlxfKYZnve/Design-System?node-id=453%3A971)is deprecated. Where can I get the latest?

The new design system is still under development and not available publicly it seems. Also I'm not sure if we will go with the same designs for the Tag component. @jessover9000 should this issue be updated or closed?

**Comment by jessover9000** [comment]
Hello @atymchuk, thank you for tackling this ✨  – I wasn't aware that community users would want to use our Figma file, especially since this issue is so old. You can view the new design system here: https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Design-system-v2.0-%E2%80%93-G7.4?node-id=3213%3A12883 We did iterate the tag design very recently (props to @hemdrup for the great work). However, since we're also working on the colors and are planning to overhaul the way color variables are structured in the CSS, maybe it makes more sense to hold off with the implementation until we have done the groundwork in that area?

**Comment by khushijain21** [comment]
I would like to contribute - any update with the implementation?
