### ISSUE TITLE
Annotations: Add a field to let plugins set the color of annotations

### ISSUE THREAD

**Issue by lfroment0** [grafana/grafana#23118]
**What would you like to be added**:
When using a plugin to create annotations, it would be nice to let the plugin choose the color the annotation will be drawn with.

**Why is this needed**:
This would enable plugins to embed some logic to visually differentiate annotations.

**Comment by xaviermerino** [comment]
@peterholmberg is there a way to change the color programmatically through the Annotations API?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
