### ISSUE TITLE
Add Datasource as Alias into dashboard

### ISSUE THREAD

**Issue by naumfujimori** [grafana/grafana#23215]
**What would you like to be added**:

Hi guys, 

I would like to request feature to add {{datasource}} into alias like:
![image](https://user-images.githubusercontent.com/39249830/77968655-9b0bf580-7333-11ea-979e-0f657322847a.png)

**Why is this needed**:

Today variables is not supported on alert option, so I ended creating single dashboard with mixed datasources and configuring alarms using OR like:
![image](https://user-images.githubusercontent.com/39249830/77968855-140b4d00-7334-11ea-9511-9405267a23b9.png)

Problem is when alert is triggered show me only the instance ID (AWS) and is very hard to locate the actual datasource of that device.
If we can add the datasource into alias or into alert message will be very good.

**Comment by bergquist** [comment]
Hi

I think I understand what you want to achieve but this is not how we intend to solve the problem. 
The underlying problem is that information about where the metrics come from is lost during alert evaluation. Which is something we intend to fix once we start working on improving the alerting feature in Grafana. 

I'm closing this since this exact feature request won't be implemented. feel free to ping me if I misunderstood what you want to achieve and I can reopen this.
