### ISSUE TITLE
Window.fetch: HEAD or GET Request cannot have a body.

### ISSUE THREAD

**Issue by fraform** [grafana/grafana#23224]
**What happened**:
Get "Window.fetch: HEAD or GET Request cannot have a body." when creating new dashboard.

![grafana_dashboard](https://user-images.githubusercontent.com/34766291/78017678-ea125480-734c-11ea-9823-0c92893276be.png)

**What you expected to happen**:
No error appears.

**How to reproduce it (as minimally and precisely as possible)**:
When you try to create a new dashboard and choose Prometheus AlertManager as datasource

**Anything else we need to know?**:
With Grafana 6.6.2 there is no problem.

**Environment**:
- Grafana version: 6.7.1
- Data source type & version: Prometheus AlertManager by camptocamp 0.0.7
- OS Grafana is installed on: Debian 10
- User OS & Browser: Firefox 74.0
- Grafana plugins:  Prometheus AlertManager by camptocamp (https://grafana.com/grafana/plugins/camptocamp-prometheus-alertmanager-datasource)

**Comment by jongyllen** [comment]
Hi, this issue seems to be with the prometheus alertmanager datasource (due to changes in Gafana 6.7)
There is already an issue for this in that repository, https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/issues/72
There is also a PR to fix it, https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/pull/73

So I am closing this issue in Grafana for this.
