### ISSUE TITLE
Template: add delimited values option for multiple selection

### ISSUE THREAD

**Issue by pdf** [grafana/grafana#2323]
Feature request to add an option allowing multiple selection as delimited values (in addition to glob and regex).  My use-case is for OpenTSDB, which uses a `|` delimiter, but this may be useful for other data sources, so the delimiter should probably be configurable.  Results would be of the format `val1<delim>val2<delim>val3`, so with pipe as the delimiter: `val1|val2|val3`; or comma: `val1,val2,val3`.

**Comment by utkarshcmu** [comment]
@pdf - I am not sure whether we should have a configurable delimiter or not. But I have implemented "pipe" delimiter for Opentsdb in #2808 

Now it is up to @torkelo to keep this issue open or close it depending on the need of this feature of configurable delimiter.

**Comment by utkarshcmu** [comment]
This can be closed because we have the pipe delimited format for Opentsdb. If we still want to keep this issue open for other kind of delimiters, we may, otherwise we can close this.

**Comment by robrsprd** [comment]
Hi everyone. I stumbled upon an use-case for custom delimiters. I wanted to create a custom selection for label names i want to aggregate by in my Prometheus-dashboard. For one selected value an expression like "sum(metricname) by ($labels)" works, but it fails with multiple values due to the pipe- instead of comma-seperation. Maybe this is reason enough to reevaluate the issue. Would be cool as it adds quite a lot of dynamic to boards - at least mine :)
