### ISSUE TITLE
Enable font size option for Stat panel

### ISSUE THREAD

**Issue by burton666** [grafana/grafana#23305]
I would like the possibility to change the font-size for the field title in the Stat panel. Right now I am showing the status about my hosts networkadapters where I have the networkadapter names in the font-title. 
But the text is so small I can bearly see it unless I resize the panel to take the whole screen.
I also searched the form and found several other questions about this but none had been answered.

**Comment by torkelo** [comment]
Can you show a screenshot? Grafana will optimize the font size for available space. 

So not sure what value a font size option will have, the text will just overflow the panel area. your option is to make the panel bigger so the title fits in a bigger font size

**Comment by burton666** [comment]
![stat](https://user-images.githubusercontent.com/19201764/78280678-c2bcb280-7519-11ea-8ae3-23d4254c87cf.PNG)

In order to get the network-adapter size readable the Stat-panel takes up almost the entire screen.

**Comment by torkelo** [comment]
As you can see the first title is very long and cannot be much bigger. And Grafana will align so font sizes are the same in a single stat panel.

There might be some very small room for improving the algorithm

**Comment by roastiek** [comment]
I have similar problem with stats panel. But I think real solution would be to support spliting long text to multiple lines.

My use case for stats panel is for showing metrics labels and changing its background color. If I could I would even hide metric value.

**Comment by michaeldmoore** [comment]
Maybe check out the Annunciator panel this is very much based on SingleStat with a additional number of features etc., including independent text element font sizes.

**Comment by mhaluska** [comment]
I would also like font size back (it was available in version 6). Now it doesn't look nice with automatic font sizing.

<img width="1592" alt="Screenshot 2020-05-20 at 08 22 53" src="https://user-images.githubusercontent.com/6524187/82412407-e3ae7800-9a73-11ea-957d-5da99afad46c.png">

**Comment by flurin** [comment]
We have the exact same issue with the autoscaling. It just looks wonky.

**Comment by mhollstein** [comment]
![Single Stat vs Stat](https://user-images.githubusercontent.com/56024424/83732867-fb2d5980-a64c-11ea-8318-a48f7f8704a9.png)

Text is to big or to small sometimes. Please add old option for font size.

**Comment by Mario-Hofstaetter** [comment]
As requested in [slack](https://grafana.slack.com/archives/CSKQV9Y5B/p1591269974058100?thread_ts=1591221521.057700&cid=CSKQV9Y5B) an simple example as of Version `7.0.3`:
![stat-panel-font-size](https://user-images.githubusercontent.com/33002073/83897911-7e86a200-a756-11ea-9a1b-c564b8e6a944.gif)

When using `Auto` its a little better, when using `Vertical` the font is really small too despite lots of empty space between the individual cells:
![tsyVQ1h3NR](https://user-images.githubusercontent.com/33002073/83898514-4d5aa180-a757-11ea-8d8d-7b1d28e4b572.gif)

**Comment by bbrantley** [comment]
+1 for font size settings for prefix and postfix.  “Custom unit” in lieu of postfix is okay, but the size is too large on our dashboards.  Space is precious, and we get a more usable result with larger numbers and smaller postfix/units.

**Comment by devZer0** [comment]
just posted my enhancement request to find it's already here at this place:  https://github.com/grafana/grafana/issues/25630

**Comment by lhuang61** [comment]
Another possible solution (which I think is more elegant) is to take into account all the Stat Panels on a dashboard and make the font size auto-scale but consistent across all of them.

**Comment by kyledevans** [comment]
![grafana](https://user-images.githubusercontent.com/1494609/87213875-db452180-c2ed-11ea-9cb6-546a3acb4be8.png)
My company has run into similar issues as others.  Having the ability to manually set the font size would fix some of the issues we've encountered.

**Comment by InsaneSplash** [comment]
I have the issue where the font size doesnt change based on the amount of data..... It just starts to wrap?

![image](https://user-images.githubusercontent.com/16985649/87221630-c3ad7d80-c36d-11ea-9a8b-71924f271fce.png)

**Comment by tve** [comment]
Same here: please bring the explicit font sizing back! Here's a screen shot of a "legacy" singlestat on bottom and a new stat panel on top. The value is way too small in the new stat panel (top), the value is great in the old singlestat (bottom) because I tweaked it (before upgrade to 7.x). The small auto-sized font for the value is ridiculous, I mean, the point of a stat panel is to prominently show one value, isn't it?

![Screen 2020-07-12 236](https://user-images.githubusercontent.com/39480/87259924-8c20fd00-c463-11ea-8553-3b0b346d1997.png)

**Comment by devZer0** [comment]
this really sucks enormously

**Comment by torkelo** [comment]
Thanks for the feedback, will think of ways to improve and fix this

**Comment by mmakaay** [comment]
Here's another usage example where things looks a bit off. 
There is enough room to format these stat panels using the same font size, but the graphing disagrees.

![afbeelding](https://user-images.githubusercontent.com/470371/87571487-6b0e1580-c6ca-11ea-99e3-33c73ebcb965.png)

**Comment by ryantxu** [comment]
I am hitting similar issues with layout changes while showing fast updating data.  As the values change and formatting updates, the sizes jump around :(

I don't think we should expose raw size configuration for two key reasons:
1) so many variations of the setting they explode and are super hard to maintain over time
2) setting a fixed font size that is applied regardless of the dashboard/browser size often looks bad.

The current strategy picks the text size based on what will fit in the available space.

Rather than exposing the size options, maybe we could/should make the reference text configurable, so that it can expect a fixed size text.

**Comment by bbrantley** [comment]
We had size options exposed in SingleStat that worked just fine for a lot of people.  I think just getting back to that point would be fine.

Some dashboards are tuned for a specific display/form factor.  In those cases, someone may be more concerned about putting in the effort to get things optimized ahead of time, rather than the flexibility of a generalized, responsive layout.

**Comment by fjlour** [comment]
I also miss the option to fix font size in single stat. This auto-scale thing is useful at times, but one should be able to define min-max thresholds for font size.

Here's an example:
![image](https://user-images.githubusercontent.com/42777078/87695418-622f4980-c787-11ea-8c27-2eaf8dd1b45d.png)

![image](https://user-images.githubusercontent.com/42777078/87695444-69eeee00-c787-11ea-9fc8-e65724f323e4.png)



Also, when there's only one series in the group by terms, the series label is missing and the graphic expands to fill the whole panel making it look rather strange.

![image](https://user-images.githubusercontent.com/42777078/87695588-91de5180-c787-11ea-8c0c-5e485b083aaf.png)

Auto-scale is nice, but it's just like Tesla self-driving thing: You are able to let it drive itself, but you can still override it and drive the car yourself you if see it's going to try to kill you. :D

**Comment by berezhinskiy** [comment]
+1 for font size and text color for stat panel. Thank you.

**Comment by rjsears** [comment]
+1 for returning to the old way of doing it where we can set the font sizes ourselves. This new way really screws with existing layouts.

**Comment by Soumyank** [comment]
+1, need font size option in stat panel. I would like to set the font size myself

**Comment by wikro** [comment]
+1. It looks really weird on some panels where it shouldn't be an issue, and there's less consistency in font sizing in panels of the same size as others have shown in screenshots.

**Comment by yoyekyoyek** [comment]
+1, it does not look good:
<img width="420" alt="Screenshot 2020-09-02 at 15 29 28" src="https://user-images.githubusercontent.com/53047857/92090488-c5287e80-edcf-11ea-8fde-824000c0dfa9.png">
<img width="1210" alt="Screenshot 2020-09-03 at 10 24 38" src="https://user-images.githubusercontent.com/53047857/92090527-d2456d80-edcf-11ea-8632-b10655950d46.png">
On a mobile it looks even worse, on value can use half of the screen...

**Comment by marcingminski** [comment]
I second this idea. The auto-scaling is not always good enough. Let us set the font size please.

**Comment by woot365** [comment]
The font is currently too small to be readable when putting it on a dashboard that's going on a monitoring wall. See stat panel versus single stat with 200% override.
![image001](https://user-images.githubusercontent.com/52417719/94134706-45378680-fe5a-11ea-8213-5fae36cca5ff.png)

**Comment by ChSanjayBabu** [comment]
Blendstat plugin gives flexibility to adjust font size, but i found problem changing backgroud

**Comment by ryantxu** [comment]
#28091 will help with *part* of the issues.  However, it will not help with the scale dependent issues.

**Comment by dmagliola** [comment]
+1 It would be great to have more manual control of how this looks

**Comment by MonilCereBulb** [comment]
+1 It will be really great if this feature is made available soon.

**Comment by WantStuff** [comment]
+1
Any way we can add the deprecated panels back into the Visualizations selection until this gets fixed?

**Comment by Anth0nyME** [comment]
+1 to this feature

**Comment by Sean-Madigan-Bose** [comment]
+1 could really use this feature

**Comment by cpmoore** [comment]
+1 Management wants all stat panels the same font size instead of the dynamic resize

**Comment by lestatk0ff** [comment]
+1

**Comment by Antoha-GS** [comment]
+1

**Comment by sheldonrong** [comment]
+1

**Comment by gustonator** [comment]
With all due respect to the devs, but this new auto-font-size formatting really sucks more than a vacuum cleaner.
Please bring back at least the font size option.

**Comment by wdbdesign** [comment]
+1

**Comment by dry4ng** [comment]
Getting lots of negative feedback from end users due to inconsistent font sizes.

**Comment by craffels** [comment]
+1

I use a lot of SingleStat panels. Replacing them with Stats panels is not an option, since the font size gets ridiculously small.
Just one example (left=SingleStats, right=Stats):

![Untitled](https://user-images.githubusercontent.com/9722081/100206397-8efa2700-2f06-11eb-8243-886a3d9d5e0e.png)

**Comment by bob454522** [comment]
+1 for this (we desperately need control over the font size , or specifically the minimum font size)
_(nb; i have left thumbs up as well as the +1 here)._

In this example below you can see just a *few* more pixels of height changes the font size from un-readably small, TO more readable. 
![grafana2](https://user-images.githubusercontent.com/60830628/100297569-934d3100-2f54-11eb-9f6c-aeebb5b51b22.gif)

Grafana is **beautiful** and i understand the Devs desire for consistency (ie the pre-set auto-font scaling),  but in this case i do think it is worth it to allow dashboard owners/creators to possibly make their dashboards look award (ie via forcing a font size) , for the sake of readability/function.

This issue is often a critical one in terms of usability.

thanks.
(Love Grafana!)

**Comment by torkelo** [comment]
True but then it would overflow it's container

**Comment by dgoadby** [comment]
This is bugging me too with my gauges (V7.3.4). I tried the Exact & Fit options but, although the image looks ok whilst editing, the end result is always as below. The only fix is to change the zoom level on Firefox to 90%. That's ok for me but not all users.

![PV_Generation_Last_12_hours_Grafana](https://user-images.githubusercontent.com/1812006/100530134-0d481900-31e6-11eb-838c-c2da21a661d5.png)

**Comment by nabelekt** [comment]
Agree that the option for manual control of font sizes would be a big help. When I have multiple Stat panels lined up, I want to force the font sizes to be the same regardless of the different panel sizes.

**Comment by bob454522** [comment]
Hi,  Here is a somewhat similar example i came across today (a bit on the extreme side though - watch the middle single stat as i resize it VS how it appears on load).  
(to be clear,  i do get the difficult position the developer is in with this specific issue-  as the fix is not clear , or even possible?)

If he allows users to define a minimum font size (or manual font size), which i would like,  - then the beautiful, and consistent look of grafana will be compromised a bit.   (i have yet to come across a system that scales as beautifully, across various viewports/window sizes, as grafana does)

Im not very knowledgeable on CSS , re this comment below (is from torkelo's reply above):
> True but then it would overflow it's container

but it does appear there is more room in each of these rows (but perhaps it only appears that way visually though).

thanks
(LOVE Grafana!!)

![grafanaRESEIZE10mb3](https://user-images.githubusercontent.com/60830628/101098611-d2990480-3588-11eb-8533-f5dcdabd2a70.gif)

**Comment by torkelo** [comment]
The stat panel has padding so the font size looks correct there, looks like table is better visualization for that super small and wide dimension

**Comment by gustonator** [comment]
One suggestion would be, not to set the font size, but to set the minimum width of borders. (ie. 0.5-10pt)
That way the look would be consistent, but we would be able to have a minimal control over font size.

**Comment by delvinwidjaja** [comment]
Hi, @burton666 I've been trying to change my panel color to red / green based on a (string)-value that I get from the database. Could you please tell me how to do that? I've tried using the threshold, but it can only be applied to numeric values

**Comment by tve** [comment]
yay!

**Comment by flurin** [comment]
whoot!
