### ISSUE TITLE
Zabbix datasource

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#2332]
Hello! I am developing datasource for Zabbix monitoring system and have very positive feedback from Zabbix users. It would be nice to work with Zabbix in Grafana out-of-box. Is it possible to add Zabbix datasource to Grafana project?

**Comment by jww0924** [comment]
+1

**Comment by nucleusv** [comment]
+1

**Comment by vektory79** [comment]
+1

**Comment by simple-snow** [comment]
I already use alexanderzobnin's integration. That would be cool in master, coupled with multiple data sources.
+1

**Comment by Pita123** [comment]
+1

**Comment by nopzor1200** [comment]
This is really neat, thanks so much for the work. I saw the site and the presentation (but couldn't read too much of it in Russian), and it looks like a really cool option for Zabbix users.

We're currently thinking a lot about how best to include support for more datasources "out of the box" with Grafana, but the issue is a challenging one. The more datasources we have the harder the problem becomes. Documentation is always a sore spot. So is testing and integration. 

It'd be awesome if Grafana could get exposure to the Zabbix install base. We'd love to think about getting this into upstream.Especially with your help it is definitely possible.

**Comment by alexanderzobnin** [comment]
I always try to keep documentation up to date because any feature without description is hard to use. You can review documentation for grafana-zabbix in [wiki](https://github.com/alexanderzobnin/grafana-zabbix/wiki).

**Comment by xiaoping378** [comment]
+1

**Comment by timgriffiths** [comment]
+1

**Comment by jmaitrehenry** [comment]
+1
I already use it from https://github.com/alexanderzobnin/grafana-zabbix without issue for now, could be nice to have it directly on Grafana

**Comment by jonaz** [comment]
+1 !

**Comment by andrewmcgilvray** [comment]
+1

**Comment by slick666** [comment]
+1

**Comment by christianchristensen** [comment]
:+1:

**Comment by xiaoping378** [comment]
+1

**Comment by slick666** [comment]
@torkelo is there a disposition on this ticket? Is the datasource being brought in? kept out?

**Comment by torkelo** [comment]
All new data sources are going to be extranal and listed on grafana.net, easily installed / updated via grafana-cli
