### ISSUE TITLE
Run docker image, how to config use mysql to store grafana data?

### ISSUE THREAD

**Issue by jackwang-github** [grafana/grafana#23349]
start docker image defalut data store database is sqlite3. But I want to use mysql to store grafana data, how can I make it happeen?

Thank you!

**Comment by nikobearrr** [comment]
Hi @jackwang-github 
It is pretty simple. Since you are using the grafana docker image, you should create a mysql service and add those as environmental variables in you grafana service:

```
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_HOST=<your host>
      - GF_DATABASE_NAME=<your database>
      - GF_DATABASE_USER=<your user>
      - GF_DATABASE_PASSWORD=<your password>
```

You should replace the host, database, user and password with your values and then grafana will create tables and save/load data from there.

**Comment by jackwang-github** [comment]
Hi @nikobearrr, Thanks for your reply, It works now. Can you tell me which script called in these variables？

**Comment by nikobearrr** [comment]
@jackwang-github I don't know where are the variables used from.

**Comment by jongyllen** [comment]
Hi, Grafana reads the values directly from the environment variables at startup-time. You can also set them in the config file.

For questions and discussions, please use the [community forums](https://community.grafana.com/)

**Comment by jackwang-github** [comment]
Thank you!
