### ISSUE TITLE
An unexpected error happened

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#23347]
**What happened**:
- Change a influxql query to use the "last" selector and the screen turned into an error page

**What you expected to happen**:
- For grafana to apply "last"

**How to reproduce it (as minimally and precisely as possible)**:
I can reproduce it easily with my dashboard but I don't know about elsewhere.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: influxdb 1.7.9
- OS Grafana is installed on: CentOS 6.10
- User OS & Browser: MacOS X/Chrom
- Grafana plugins: Diagram
https://grafana.com/grafana/plugins/jdbranham-diagram-panel
- Others:
![Screen Shot 2020-04-05 at 10 06 00 am](https://user-images.githubusercontent.com/24280758/78463873-8e1d4680-7725-11ea-94a9-f0139d8646fb.png)

**Comment by yellowpattern** [comment]
Also, grafana is reporting "Cannot read property 'length' of undefined" attached to a red triangle in the upper left corner of the screen.

**Comment by yellowpattern** [comment]
I cannot open this up in the query editor :(

**Comment by jongyllen** [comment]
Hi, thanks for submitting. I tried reproducing this with your environment but did not get the same error. Got another error tough. I am guessing this is related to the plugin and I see that you have already posted an issue regarding this plugin [here](https://github.com/jdbranham/grafana-diagram/)

Please come back if it turns out to be an issue with Grafana core and we will reopen this if needed.
