### ISSUE TITLE
root_url and Apache reverse proxy: unusual behaviour

### ISSUE THREAD

**Issue by jkur** [grafana/grafana#2340]
The root_url parameter in grafana.ini is highly unusual from a sysadmin point of view. When using root_url to make grafana available from a suburl, like http://example.com/grafana the server itself does not answer anymore. The proxy setting that is needed is also very unusual, if not totally wrong. I need to configure the apache proxy like this:

  ProxyPass /grafana        http://localhost:3000
  ProxyPassReverse /grafana  http://localhost:3000

Usually you would add the suburl to the destination URL also. And that makes sense, because i could use the server in the same was, as the proxy. http://localhost:3000/grafana would show the same page as http://example.com/grafana

So the configuration in Apache should be:

  ProxyPass /grafana        http://localhost:3000
  ProxyPassReverse /grafana  http://localhost:3000

With the setup of the root_url the server itself is not usable at all. I would consider this a bug.

Best regards.

**Comment by torkelo** [comment]
not sure I agree, this is pretty standard. if you add a sub url via apache then apache still requests normal requests to grafana (ie without suburl). But grafana frontend needs to be aware of the sub url to create correct cookies and links. 

Grafana cannot support http://localhost:3000/grafana and http://localhost:3000 at the same time , since the proxy adds the suburl. 

I guess an alternative would be when you change root_url (add a sub url) then you also need to have that sub url in the proxy pass. So the apache config should be (in that case)
```
ProxyPass /grafana http://localhost:3000/grafana
ProxyPassReverse /grafana http://localhost:3000/grafana
```

but that would require all backend routes prefixed and is just weird.

**Comment by jkur** [comment]
First of all, there was a typo in my first post. I corrected. Maybe that's already all the confusion. See the second apache config block.

Okay. I see, that it might be different views. But for example, take the jenkins software, which i typically have behind some proxy, does it exactly that way. The proxied call is with suburl included.

And i don't know if you follow my point: When you configure the root_url parameter, the application is not usable anymore through it's "native" port. While for example with jenkins, this is of course still possible.

It's absolutley not weird. There are absolut legitimate use cases. Internal access to some dashboard and external acces only via a proxy. I could use apache authentication and so on.

**Comment by kesor** [comment]
Future versions of Grafana will "just work" without this requirement for a rewrite rule. https://github.com/grafana/grafana/pull/17048
