### ISSUE TITLE
Templating: Regex on full graphite expended matches

### ISSUE THREAD

**Issue by wundrian** [grafana/grafana#2343]
I know this has been discussed in part in https://github.com/grafana/grafana/issues/2160:

I'm trying to limit a template variable query by including the value of a (independent) variable and then using _parts_ of the _full metric name_. Let's have an example:

Given metric names
city1.services.user1.bananas_eaten.count
city1.services.user1.apples_delivered.count
city1.gates.carts_passed.count

I want to capture template variables `$user` and `$city`, where grabbing possible user values is easy:
just a graphite query for `*.services.user*`. Now, I want `$city` to be limited by the `$user`. 

Here I'm stuck. I can ask the graphite API: `https://my.graphite/graphite/metrics/expand?query=city*.services.$user` and use a regex to pull out the values. But how do I do that in Grafana? All I can do is `find` metrics, which only gives me the last node of the metric name.

Can the template query mechanism somehow expose the full metric name so I could decide which values to construct out of it?

**Comment by torkelo** [comment]
If you want to user to limit city you should invert your metric name space, so you user comes first then city :)

**Comment by mattibickel** [comment]
But I'm not the only user (no pun intended) of that namespace, so I can't just switch those around. We have metrics that are not per-user, but every user has one city (could be more than one in the future) - the arrangement makes sense for us. If we could make this possible, I'm certain there a few ones here that'd be grateful for the tedious clicks saved (we *can* select the matching city by hand right now).

**Comment by Tenzer** [comment]
I think we have a related problem. We are using Graphite and get metrics through CollectD. CollectD's plugin structure means we get metrics named like: `<server name>.<collectd plugin>.<metric name>`.
It would then be neat if we in Grafana could make a templated dashboard for the specific plugin, where we then could pick the server we would like to see the metrics for.

A concrete example of this could be the Nginx plugin where we then could create a dashboard to show the metrics related to it, plus potential some standard metrics such as CPU and network usage. Metrics for that dashboard will all be called something like `<server name>.nginx.<metric name>`, so the neat way of finding servers to include in the host selector on the dashboard, would be to make a query for `*.nginx` and then show the first part of the metric name for the server name. This is however not possible currently, since we don't have access to anything above `nginx` in the metric tree name.

I had a look at the different endpoints Graphite make available, and it seems like it's possible to get the parent part of the metric name by either calling `/metrics/expand/?query=*.nginx` or alternatively to use `/metrics/find/?query=*.nginx&format=completer`. I can see from the Grafana code that "expandable" parameter is passed along from `GraphiteDatasource.metricFindQuery()`, but it's not clear to me what that is used for, so I don't know how big a change it might be.

**Comment by standaloneSA** [comment]
I have a very similar issue with templating. 

I have several machines where the data is being fed into graphite via Icinga, in this case, in the format: 

icinga.hostname.servicename.metric 

There are various operating systems and device types represented here. I would like to build a Linux dashboard (among others), and I can reliably determine that all linux hosts (and only linux hosts) have the metric: 

icinga.hostname.linux_load.load5 

Unfortunately, in the template menu, I cannot run a regex on that string, because when I fill "Variable Values Query" with "icinga.*.linux_load.load5", the variable is set to "load5", so I can't even use a regular expression to pull out hostnames. 

It would be GREAT if I could match RegEx against the entire metrics path for the matching metrics. 

Thanks! 

--Matt

**Comment by azhurbilo** [comment]
+1  
It will be good to get hostnames (*) in this case "icinga.*.linux_load.load5"

**Comment by thomas-tomlinson** [comment]
I also have a need for this.  Something similar to the InfluxDB functionality describe here but of course graphite compatible: https://groups.io/g/grafana/thread/how_to_use_regex_feature_for/56030?p=,,,0,0,0,0:RecentPostDate,,template+regex+,20,2,0,56030

**Comment by daire-byrne** [comment]
+1

This would really help with our dashboards. We used to use this a lot in graphitus.

**Comment by wiad** [comment]
Was looking for this today, trying to create a dashboard for all our apache metrics. So, +1.

**Comment by tsimouha** [comment]
We would like that feature too. We use m2g-poller to get 80k metrics into graphite and the application name comes next to the hostname (server.<OS>.servername.mysql,apache,etc). We need a way to get the "hostname of the mysql server" listed as a template in a dashboard. +1 👍

**Comment by bodgit** [comment]
:+1:

I was trying to build a templated dashboard for service X that had a hostname dropdown for only the hosts that had service X on them (assuming the metrics are organised as `hostname.service.*`).

I found https://groups.io/g/grafana/topic/how_to_use_regex_feature_for/56030 that suggested I could use a regex to match the metric name but it was only ever being fed the last node of the metric name. Then I re-read and noticed that it mentioned using InfluxDB rather than Graphite so I assume that's a difference between backends. It would be great to get something comparable without changing backends :wink:

**Comment by grantholly** [comment]
I've had luck using this feature before when dealing with multiple instances of elasticsearch installed on the same host.

My metrics for elasticsearch (see also: logstash) follow the structure of
`servers.<$(hostname -s)>.curl_json.<$(hostname -s)-logstash-$INSTANCE_NUMBER_$CATEGORY>.metric`

I want to have a drop down where I can select the host (I'll call is `$server`), but then I want a drop down for the specific elasticsearch instance (`$instance`) running on that host that is filtered by the prior.

Creating the first option `$server` is easy.  I can just use the globbing pattern `servers.*`

The next group I have to create by first setting up a pattern of `servers.*.curl_json.*`.  Then I create a regex group to capture the instance name by using `/(\w+-\d+)/g`.  That will capture "logstash-1", "logstash-2" and so on without capturing the other parts of the metric.

Combining the two, I can actually reference my first variable in my second by changing `servers.*.curl_json.*` to `servers.$server.curl_json.*`

**Comment by mcbsdEU** [comment]
Thanks you included reference #7792 
I see this request is quite old and hope it will be handled in near future:)
And thanks for great work.

**Comment by hany** [comment]
Ran into this myself. Would be great to have.

👍

**Comment by mcbsdEU** [comment]
Hi,
I see that lot of people would benefit out of this enhancement.
This issue was posted long time ago and I am worried it is not visible any more.
@torkelo any plan to work on this in near future?

Thanks!

**Comment by damienclaveau** [comment]
+1

**Comment by nb71** [comment]
+1

**Comment by jacobweber** [comment]
+1

**Comment by rowanruseler** [comment]
+1

**Comment by TiepelPa** [comment]
+1

**Comment by rmontgomery2018** [comment]
+1
This woul definitely help out with our dashboards.

**Comment by chronidev** [comment]
+1

**Comment by Great-Li-Xin** [comment]
Please, this will definitely help up out with our dashboards
