### ISSUE TITLE
Allow aligning left/right Y axis without aligning ticks

### ISSUE THREAD

**Issue by andig** [grafana/grafana#23462]
**What would you like to be added**:

Aligning Y axes was introduced with https://github.com/grafana/grafana/pull/10994. This PR apparently also aligns ticks by a certain factor. I'd propose to not align ticks by a fixed factor and instead let each axis scale individually.

**Why is this needed**:

Consider this panel:

![0A12FBDE-0B46-4B0A-BBF2-869ED6E9F550_1_105_c](https://user-images.githubusercontent.com/184815/78880541-da35f700-7a55-11ea-92fb-1b4a19575cb0.jpeg)

Once both axes are aligned, the left axis looses resolution since apparently both axes are tied together by a factor of 100. If the left axis as allowed to scale to 600 while the right scales to 100 the chart are would be more efficiently used.

**Comment by andig** [comment]
Here's another screenshot that show that the current mode for aligning the axes is sometimes not too helpful:

<img width="1151" alt="Screenshot 2020-04-11 at 13 04 50" src="https://user-images.githubusercontent.com/184815/79042098-24a1aa00-7bf5-11ea-93a1-711bafd1e0cc.png">

Going forward it might make sense to have two different alignment modes: `Zero` and `Zero and Ticks`. The latter is the current behaviour.

**Comment by Pwuts** [comment]
I think related to this is the issue that, even using the "align Y-axes" option, the axes are aligned to ticks instead of the exact level specified. So instead of a ratio of 1.78, I get a ratio of e.g. 1.7 or 1.8 between the axes, causing the lines to still be misaligned. Should I create a new issue for this or is it basically the same issue as this one?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
