### ISSUE TITLE
docker image cannot work change password Unauthorized

### ISSUE THREAD

**Issue by mengxifl** [grafana/grafana#23489]
**What happened**:
web gui give me Unauthorized when I change password page  after I login with admin 

![图片](https://user-images.githubusercontent.com/48743664/78960809-bf30b900-7b21-11ea-8b21-6b3e4ab57de5.png)

**How to reproduce it (as minimally and precisely as possible)**:

docker run -d --name=grafana -p 3000:3000 grafana/grafana

**Anything else we need to know?**:
logs:

 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=PUT path=/api/user/password status=401 remote_addr=192.168.11.1 time_ms=0 size=26 referer=http://192.168.11.10:3000/login

**Environment**:
- Grafana version: 6.7 I don't konw 
- Data source type & version: alpine
- OS Grafana is installed on: centos 7.7
- User OS & Browser:  chome firefox
- Grafana plugins: no
- Others: no

**Comment by mengxifl** [comment]
I think The problem is in version 6.7 . There is no such mistake When i use 6.6.3 .

**Comment by aknuds1** [comment]
I just tested the v6.7.2 Docker image like this: `docker run -d --name grafana grafana -p 3000:3000 grafana/grafana`. Then I did the following:

1. Log in as admin
2. Change admin password to "password"
3. Sign out
4. Log in as admin, with password "password"

Since I was able to change the password and successfully log back in again, using Docker as you did, I'm inclined to think you must've restarted the Docker container after changing the password or done something else wrong. Therefore I'm closing this as a non-issue. 

If you need further support I suggest you reach out to the Grafana community [forums](https://community.grafana.com) or [Slack](https://raintank-corp.slack.com/).

**Comment by vargaendre** [comment]
Hi,
I have the very same issue, I believe.
After installing Grafana, I can open it up in browser and log in the first time (with admin/admin) and then I get promted to change my password. Once I do that, I get redirected to the home dashboard but before it loads I get a HTTP 401 and Unauthorized message and redirected to login.

My current setup is this: I run Grafana as a docker image on an EC2 instance with port 3000. I add that to a target group and then use it in an Application Load Balancer. That's what causes the issue.
I try to log in through https://grafana.mydomain.com with no luck. In the custom.ini I've set grafana.mydomain.com as domain and protocol to http, because the TLS magic and the certficate is in the load balancer.

If I try to access Grafana straight through the EC2 instance IP and port 3000 and via HTTP then I can log in no problem. Still, I'd need my custom URL and also HTTPS.

Please help, what do I need to do to make this work? 
I've seen multiple people having this issue, but no real solution so far.

**Comment by marefr** [comment]
@vargaendre please enable [secure cookies](https://grafana.com/docs/grafana/latest/installation/configuration/#cookie-secure) since you're using https. Sounds like a [problem related to Chrome 81](https://grafana.com/docs/grafana/latest/installation/upgrading/#important-changes-regarding-samesite-cookie-attribute).

**Comment by vargaendre** [comment]
@marefr Thank you for the super quick response!
Unfortunately, setting secure_cookie = true did not change the situation. I am using Firefox.

**Comment by marefr** [comment]
Would suggest open a new issue.
