### ISSUE TITLE
Tracing: Dark theme issues.

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#23557]
So far the dark theme tracing component was mainly generated by inverting the colors but there are some issues with that.

![Screenshot from 2020-04-07 17-53-46](https://user-images.githubusercontent.com/1014802/79220155-cb838180-7e53-11ea-8baf-470b6229cd43.png)

From @davkal
- the muted grays are too muted and the teal pops too much.

**Comment by aocenas** [comment]
@davkal @jessover9000 @sarlinska can you add feedback here?

**Comment by davkal** [comment]
I don't think we can get around mapping colors manually, but we only need to do it once (jaeger to light grafana), because within grafana we have light/dark equivalents (e.g., `$panel-bg`).
Could even wrap this in a function that takes the jaeger hex code and the theme as input, and outputs the correct grafana color (with identical color and auto-inverts as fallback for new colors).

**Comment by sarlinska** [comment]
I do agree that teal pops so much that it almost hurts the eye. I think it would be best if @jessover9000 took a look at this as she's the best with defining color themes and making sure everything is consistent. How urgent is this @aocenas ?

**Comment by aocenas** [comment]
> How urgent is this
I assume 7.0 urgent as everything :). But I wanted to try to plug in some scheme from dashboards, I assume we have some to auto assign colors to multiple lines in graph for example.

Maybe I did not mention it but the teal is just one of possible colors and they are assigned from a pallet based on service name. The only modification to that I done was to remove some dark ones that would not be readable at all in dark mode.
