### ISSUE TITLE
Passing "All" values to another dashboard without enabled "All" option

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#2368]
Hi, this issue is related with the fixed bug on #2297 .

The _"All"_ variables is passing correctly (the bug was fixed) to another Dashboard (DS).

As an example:
The DS1 has metrics of _bk1,bk2,bk3_ as host.

The DS2 can show detailed metrics of more than one host, using repeat templating feature, but only if its passed by parameter ,_mutiple selection_ and _"All"_ **disabled**.
The host available on DS2 are _bk1,bk2,bk3_ (same as DS1) and _bk4,bk5,bk6_.

The first problem is that if DS2 doesn't have "All values" enabled, it doesn't recognize the passing value:
`&var-host=All`

The second problem is, if I activate, the "All" value on DS2 and I want to see detailed metrics of bk1,bk2,bk3, on the DS2, the "All" values shows, obviously, the bk1,bk2,bk3 and undesired bk4,bk5,bk6.

Would like to ask if its possible to pass the "All" values as it works on multiple selection feature:
`&var-host=bk1&var-host=bk2&var-host=bk3`

Thanks for all.

**Comment by sbengo** [comment]
Hi @torkelo, friendly ping.
Since the "fix_refresh_variable_from_url" commit, would be very interestant changing the mode that "All" is passed by URL:
Refreshing my issue, the "All" mode can be: glob, wildcards, regex wildcard, etc. When the the DB is shared or passed by URL, the "All" is passed as: `&var-app=All`, instead of the mode that you have selected.

I.E, testing on play.grafana: Selecting "glob", templating params should be passed as it is on multiple selection feature: `&var-app=backend&var-app=fakesite`.

Thanks!

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
