### ISSUE TITLE
Search: Cannot expand a dashboard folder after searching for it 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#23792]
Cannot expand a dashboard folder and see the dashboards inside it

**Comment by torkelo** [comment]
Example go https://play.grafana.org/d/000000012/grafana-play-home?orgId=1

and search for `Grafana Stats` this matches a folder named `Grafana Stats` I can then expand it and get all the dashboards that folder contains.

**Comment by Clarity-89** [comment]
@torkelo fixed in the commit above. The only thing is when searching for folder and switching to List view before expanding the folder, the result list will be empty since the items haven't been fetched from the api. This makes sense to me, since if we're in the list view, we're not searching for folders but for dashboards.

**Comment by torkelo** [comment]
great!

**Comment by torkelo** [comment]
>  This makes sense to me, since if we're in the list view, we're not searching for folders but for dashboards. 

agree
