### ISSUE TITLE
Save dashboard failure from server doesn't propagate to UI

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#24015]
**What happened**:
Saved dashboard, but didn't receive any feedback that dashboard saved.

**What you expected to happen**:
Success info message saying dashboard saved.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create new dashboard
2. Add graph panel
3. Alert tab -> Create alert and exit edit panel mode
4. Save dashboard

**Anything else we need to know?**:
Inspecting network response from save dashboard I notice a 422 status code with payload:
```json
{"message":"Alert validation error: error in condition 0: Evaluator 'IS ABOVE' is missing the threshold parameter PanelId: 2"}
```

Would have expected that error to show in alert message.

**Environment**:
- Grafana version: 7.0.0-beta1
- User OS & Browser: Chrome 81

**Comment by torkelo** [comment]
The bug is here (I am pretty sure), https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/components/SaveDashboard/SaveDashboardErrorProxy.tsx#L28 

We set error.isHandled = true but we only handle a few cases. We should only set this to true fo the cases we actually handle in the modal.
