### ISSUE TITLE
Legend lacks stddev, variance

### ISSUE THREAD

**Issue by metan0t** [grafana/grafana#2404]
Hi all,

I think the description is clear; the design less so. It requires info (probably as series) about the variance and count of samples per point. Thoughts on the design? Particularly how/where to manage the extra series?

Cheers,
-- Chris

P.S. Thanks for a great project/codebase!

**Comment by metanaut** [comment]
Working plan:
* Pass datasource into TimeSeries upon creation (in graph module).
* Later, in TimeSeries.getFlotPairs(), pull variance & count series from the datasource and parse them alongside existing data.

**Comment by torkelo** [comment]
Something that I find missing in all data sources is that i want them to return series summaries, like min, max, sum, avg, stddev  etc. Those cannot be accuratly calculated by Grafana as the time series data bases usually do on the fly rollup to only return as many datapoints as there are pixels on the graph. Grafana calculated legend values like avg, sum etc after the time series database consolidates points, which makes it so that only one legend value can be accurate (so you cannot show min, max and avg and expect all to be accurate all times)

**Comment by metan0t** [comment]
With the OpenTSDB data source the option is available to Disable Downsampling, which will make the series statistics accurate.

**Comment by torkelo** [comment]
@metan0t yes but you will hang your browser when OpenTSDB returns 100 0000 data points for each series :)

**Comment by metan0t** [comment]
I agree that there are series for which disabling downsampling is inappropriate, but there are also series that it is perfectly appropriate for. I'm not looking to change anything about existing downsampling behavior.

But sure, I think it makes sense that the functionality this Issue pertains to only be allowed if downsampling is disabled.

**Comment by metan0t** [comment]
Now that that's been resolved can you please reopen the issue?

Thanks,
-- Chris

**Comment by torkelo** [comment]
Then open the issue with OpenTSDB, makes more sense, will work in vastly more scenarios then :)
