### ISSUE TITLE
Debain/Ubuntu packagecloud repositories are not available

### ISSUE THREAD

**Issue by kvishnivetsky** [grafana/grafana#24062]
**What happened**:
![изображение](https://user-images.githubusercontent.com/3744827/80615541-013a8400-8a6a-11ea-8200-5085a6e2e99c.png)

W: Failed to fetch https://packagecloud.io/grafana/stable/debian/dists/jessie/main/binary-amd64/Packages  HttpError429
Repos are not available

**What you expected to happen**:
Repos available. I could update my Grafana to the newest version and have so much fun.

**How to reproduce it (as minimally and precisely as possible)**:
Go to
https://packagecloud.io/grafana/stable/debian/dists/jessie/main/binary-amd64/Packages

**Anything else we need to know?**:

**Environment**:
- Grafana version: 4.6.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Debain Jessie 8.10
- User OS & Browser: Linux Debian
- Grafana plugins: -
- Others: -

**Comment by papagian** [comment]
I'm not aware how packages are published in packagecloud.
The official way to install grafana on debian and ubuntu is described [here](https://grafana.com/docs/grafana/latest/installation/debian/#install-from-apt-repository).

In addition to this, most probably packages are not fetch due to the `Bandwidth or Storage Limit Exceeded` error.
