### ISSUE TITLE
StatPanel: Migration from singlestat does not support the metric name option 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#24076]
In the old singlestat we had a "name" option in the stat option dropdown. 

And was handled using a custom case: 
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/module.ts#L212

There is no equivalent option in the new stat panel.

**Comment by torkelo** [comment]
@ryantxu any ideas for how to support / migrate  the "name" option we have in the old singlestat?

**Comment by marefr** [comment]
Tried to use transformation to resolve it, but seems stat panel doesn't work at all with string values? If you don't want to support that I think we need a new panel?

**Comment by Mario-Hofstaetter** [comment]
Will this change support all available prometheus labels,
e.g. before in singlestat:

![grafik](https://user-images.githubusercontent.com/33002073/82696056-947c6900-9c66-11ea-8402-8dc2a0aa75a7.png)

Or is this issue about something else?

**Comment by ryantxu** [comment]
See also: #24829

**Comment by pleonex** [comment]
I found an ugly workaround by using the _Table_ panel instead. I will make my company to rollback to version 6.X because this issue is breaking all dashboard development and there is no viable migration path. Hopefully this workaround will be useful for others.

* Visualization -> Table
* Disable "show header"
* In Field -> column alignment to center
* In the query tab clean the content from "Legend" and select the Format "Table"
* Add a transformation: "Filter by name" and deselect every label except the one for the label you want

This is how it was looking with the previous panel
![image](https://user-images.githubusercontent.com/3107481/82824184-296ea480-9ea9-11ea-9c22-95b80a1214ea.png)

and this is how it looks with the ugly workaround
![image](https://user-images.githubusercontent.com/3107481/82824112-fe845080-9ea8-11ea-9dcd-162d99b7366f.png)

If I was able to increase the font size it would match almost the same but it's too hacky for our users to implement all time.
