### ISSUE TITLE
How to disable maxDataPoints?

### ISSUE THREAD

**Issue by youtome** [grafana/grafana#2409]
Hi.
I always use grafana very well.

Last week we changed from graphite-web 0.9.9 to graphite-api 1.0.1.
We seem to a graph that has been a little strange.

We think that because of this problem maxDataPoints to work.

So, we want to turn off maxDataPoints function.
And we use grafana 1.9.x version.

Thanks for your answer.

**Comment by torkelo** [comment]
you should not disable it, it  can hang your browser because then graphite can return hundreds of thousands of data points or generally be very slow. 

The problem you are seeing is likely caused by point consolidation, if you think the graph looks strange add the graphite function consolidateBy to your query and specify the consolidation function that fits the query (max, min, sum, avg, etc), by default points are consolidated using average

**Comment by youtome** [comment]
Thank you very much.

That is works.
