### ISSUE TITLE
v7.0.0-beta1: Axes configuration does not show properly

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#24091]
**What happened**:

I tried editing a panel and I can hardly see part of the configuration placeholders I want to use

**What you expected to happen**:

I am able to see the full text area

**How to reproduce it (as minimally and precisely as possible)**:

1. Open dashboard
2. Edit panel
3. Select "Axes"
4. See "Y-Max" is almost hidden/unreachable

e.g. https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&editPanel=2

**Anything else we need to know?**:

![image](https://user-images.githubusercontent.com/8693064/80703426-d09f2c80-8af3-11ea-8862-537efd055567.png)

**Environment**:
- Grafana version: v7.0.0-beta1
- Data source type & version: graphite
- OS Grafana is installed on:
- User OS & Browser: 
* Version 81.0.4044.122 (Official Build) (64-bit)
* macOS catalina 10.15.4 (19E287)
- Grafana plugins:
- Others: My resolution is 4K

**Comment by dprokop** [comment]
@nikobearrr thank you for reporting this issue. As mentioned in the [changelog](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#new-panel-edit-experiance) there are some inconsistencies in the way editors work for panels that we yet have to migrate to the new architecture. 

What I suggest for now is to resize the sidebar so that the options are more accessible.
