### ISSUE TITLE
Convert `$__interval` variable for Postgres to a valid SQL interval

### ISSUE THREAD

**Issue by wolph** [grafana/grafana#24152]
Currently the `$__interval` variable returns a value like this: `20m` which PostgreSQL won't understand.

For example, executing a query like this returns in an error:
```sql
SELECT $__interval + NOW()

SQL: SELECT 20m + NOW()
pq: syntax error at or near "+"
```

Actually replacing `$__interval` might result in errors, but having a macro as a shorthand would help a lot. Assuming we would have a macro `$__toInterval($__interval)` we could do this:
```sql
SELECT $__toInterval($__interval) + NOW()
```

Which could be converted to:
```sql
SELECT (interval '$__interval_ms milliseconds') + NOW()
```

When using window functions being able to do `some_timestamp + $__interval` can be _very_ useful.

**Comment by WoLpH** [comment]
For the time being, a very useful series that generates a series of timestamps using the given interval/from/to (including the last to) can be written like this:

This includes truncation of the from/to using the given interval so the dates are nicely rounded
```sql
SELECT *
FROM generate_series(
  to_timestamp($__unixEpochGroup($__unixEpochFrom(), $__interval)),
  to_timestamp($__unixEpochGroup($__unixEpochTo(), $__interval) + $__interval_ms),
  interval '$__interval_ms milliseconds'
) as times(t)
```

**Comment by WoLpH** [comment]
Additionally, a shorthand to get a (truncated) from/to would be very useful.

I would propose something like this:
```sql
$__timeFrom($interval)
```
To effectively return the same as:
```sql
to_timestamp($__unixEpochGroup($__unixEpochFrom(), $__interval))
```

And having the intervals converted would be useful too. Right now the `$__interval` is only useful for the macro functions but not in Postgres. It would be great if `$__interval` would effectively return a proper SQL interval:
```sql
interval '$__interval_ms milliseconds'
```

**Comment by marefr** [comment]
Already supported. Use the optional fill parameter in `$__timeGroup` macro, see https://grafana.com/docs/grafana/latest/features/datasources/postgres/#macros.

**Comment by WoLpH** [comment]
@marefr how about the other suggestions?

**Comment by marefr** [comment]
Please rewrite the issue description. I didn't really understand what you meant by that other thing so please try and explain more detailed. i'll reopen the issue when you've done the updates.

**Comment by WoLpH** [comment]
@marefr I've updated the issue specifically for the interval. Additionally a truncated version of `$__timeTo` and `$__timeFrom` could be useful but that's perhaps for another issue :)

**Comment by marefr** [comment]
To me seems like the existing `$__interval_ms` is enough?

**Comment by WoLpH** [comment]
There's are several "simple" methods which are useless in that case:

 - `$__time(dateColumn)` = `<dateColumn> as time`, 
 - `$__unixEpochFrom()` = `TO_TIMESTAMP($__timeFrom())`
 - `$__unixEpochTo()` = `TO_TIMESTAMP($__timeTo())`

Right now it's rather confusing that adding `$__interval` to a query works in some cases and doesn't in others because the Grafana intervals are different from the Postgres intervals.

Both Postgres and Grafana support `m` for minute, so the following works:
```sql
select now(), now() + '1m' "+1m";
              now              |              +1m
-------------------------------+-------------------------------
 2020-05-07 19:21:11.897683+00 | 2020-05-07 19:22:11.897683+00
(1 row)
```
But when Grafana switches to something like `1M` for 1 month we get unexpected results:
```

**Comment by zoltanbedi** [comment]
Looks like no one else was interested in this so I'm going to close it.

**Comment by mcgrawia** [comment]
hi @zoltanbedi, I know I'm a bit late to this issue, but I'm also attempting to use Postgres with Grafana (specifically TimescaleDB) and running into this issue as well. Could we re-open it?

**Comment by zoltanbedi** [comment]
@mcgrawia sure thing. Can you please also let us know what you are trying to do?

**Comment by gabor** [comment]
hi @mcgrawia thank you for the feedback.

the variable `$__interval` has a very specific meaning in grafana, so i don't think we will change it specially for the postgres use-case. 

with that said, the `$__interval_ms` variable should work just fine for all situations where one wants to use `$__interval`, your previous reply demonstrated one possible approach.

could you please explain why `$__interval_ms` is not a working replacement? 
thank you!

**Comment by idoberko2** [comment]
@mcgrawia I was able to workaround this issue like that:
```
SELECT
  time_bucket(($__interval_ms || ' milliseconds')::INTERVAL, t) AS "time",
...
```
Hope it helps.

**Comment by mcgrawia** [comment]
Hi @gabor, the `$__interval_ms` variable method works as needed, but was not easy to find. It would be helpful to add some examples in the Postgres documentation so users are aware `$__interval` will not work. Thanks

**Comment by gabor** [comment]
@mcgrawia i'm glad `$__interval_ms` helped. i raised a separate issue about improving the postgres plugin documentation at https://github.com/grafana/grafana/issues/90607 .

**Comment by swiffer** [comment]
if specifying a dashboard variable of type interval this is not accessible via $variable_ms and therefore queries depending on dashboard variables of type interval are still hard to write. any chance to see something added for this case?

**Comment by oliviasculley** [comment]
I've also been struggling with this due to needing to write some queries that give cumulative statistics at intervals that need to be configured, so I can't use the automatically generated `$__interval` or `$__interval_ms` variable, and I think I can't use the provided grouping macros for this.

It's a bit annoying to see that `$__timeGroup` and the others internally computing custom intervals to seconds as indicated by the example in the docs of `5m` converted to `cast(cast(UNIX_TIMESTAMP(dateColumn)/(300) AS signed)*300 AS signed)`, but otherwise not being able to access those computed seconds for other queries, whatever they might be. [This post](https://community.grafana.com/t/add-the-time-range-variable-to-postgresql-query-in-the-panel/81805/3) on the Grafana forums provides an example of what we're having to resort to since this functionality that is already being computed isn't being exposed anywhere.

I think the original issue was really hoping for a `$__toInterval($custom_interval)` macro that could be used without grouping such as in my problem, but I think that a `$__intervalToSeconds($custom_interval)` would let them accomplish the same thing and is being computed already and hopefully isn't very difficult to expose

**Comment by zoltanbedi** [comment]
@oliviasculley can you please open a new issue with your problem so we can track it?
