### ISSUE TITLE
Alerting: min() doesn't work as expected

### ISSUE THREAD

**Issue by StupidScience** [grafana/grafana#24179]
**What happened**:

When I choose `min()` for query condition it doesn't work as expected and looks like works as `max()`.

**What you expected to happen**:

I expected that if I choose `min()` for query for example for last 5 minutes it should evaluate minimum value during this period.

**How to reproduce it (as minimally and precisely as possible)**:

Create alert with conditions like this:
![image](https://user-images.githubusercontent.com/32177073/80852202-5e336700-8c2f-11ea-8dd0-8eadf3f2a12a.png)
Got any value and alert will be triggered.
This is how it looks like
![image](https://user-images.githubusercontent.com/32177073/80852287-0e08d480-8c30-11ea-87a6-41ec34d49063.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.1
- Data source type & version: Prometheus v2.17.1 + Thanos v0.12.0
- OS Grafana is installed on: Official Docker Image
- User OS & Browser: -
- Grafana plugins:
    - grafana-piechart-panel
    - grafana-worldmap-panel
    - flant-statusmap-panel
- Others: -

**Comment by papagian** [comment]
The min() is the reducer function used for reducing the series in order to be compared with the threshold.

From the screenshot, I understand that before the alert going to pending state there is only one point which equals to 1.0, so the minimum value is 1.0 which is above the threshold (zero). Then, during the For duration, there is one more point which equals to 1.0 so the alert is going to Alerting state. Then, there are no more points so the alerting is going back to OK state.

In any case, can you provide the evaluation interval and the For value, as well as, the output of [the Test Rule](https://grafana.com/docs/grafana/latest/alerting/rules/#troubleshooting).
