### ISSUE TITLE
Possible timeout on direct link rendered image

### ISSUE THREAD

**Issue by rsommer** [grafana/grafana#2419]
I recently updated to grafana 2.0.2 and i am trying to use the direct link rendered image feature. I discover something that looks like a timing/timeout thing: when i click on the direct rendering link, i get a black PNG with just the graph title, sometimes the little "loading"-icon in the corner. If i start minimizing the image (the width and height parameters of the url) i sometimes get the expected graph.
The log always gives me a "200 OK" and the grafana log just shows the correct render url with "PhantomRenderer::renderToPng".

**Comment by torkelo** [comment]
In Grafana 2.0.2 the png rendering will timeout after 1200 milliseconds and capture the image even though the time series metric request has yet to complete. Since metric queries should take around 25-100 millseconds to complete this is seldom a problem at least for time series databases that apply good roll ups. 

However this timeout is pretty low, so it has been increased to 10 seconds in Grafana 2.1 (master) which will be released very soon, you can download daily pre release builds here: http://grafana.org/download/builds.html
