### ISSUE TITLE
Transforms: Filter by name filters out field for ever

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#24208]
1. Create a new dashboard
2. Add new panel
3. Choose Test Data as data source
4. Choose CSV Metric Values and accept default values
5. Copy the above row 3 times
6. Change to Transforms tab
7. Choose Filter by Name
8. Expect to see all series but see only A-series [NOT OK]
![image](https://user-images.githubusercontent.com/562238/80938031-d046b000-8dd7-11ea-83ea-33f8c4e617ff.png)
9. Click on A-series, data dissapears [OK]
10. Click on back arrow to exist Panel Edit
11. Edit panel again
12. Click on Transforms tab
13. Expect to see Time and A-series, but A-series doesn't exist anymore [NOT OK]
![image](https://user-images.githubusercontent.com/562238/80938119-37fcfb00-8dd8-11ea-80fc-cf4360446acf.png)
14. Still no sign of the other series [NOT OK]

**Comment by torkelo** [comment]
>  8) Expect to see all series but see only A-series [NOT OK]

This is due to the fact copy query does not cause refresh (ie no new query/data is fetched). Mainly you copy a query to then do edits before we issue the query. So transforms won't see the new refIds until there are results for them. 

13) Expect to see Time and A-series

PR fix #https://github.com/grafana/grafana/pull/24211
