### ISSUE TITLE
Heatmap: should accommodate variable sized bins in tsbuckets mode

### ISSUE THREAD

**Issue by postwait** [grafana/grafana#24365]
The y-axis is non-sensical when the bins are all equal sized, but represent different y-axis ranges.  If I have a bin from [1,2) it should be have the size of the bin from [2,4).  In other words, using tsbuckets should still make the graph y-axis and data readable.

**Comment by WarriorOfWire** [comment]
The y-axis is nonsensical period in tsbuckets mode. I have not yet been able to generate data that aligns with this panel's expectation for data shape. Does such a configuration of data exist?

![image](https://user-images.githubusercontent.com/3454741/107846045-5f381e00-6d95-11eb-9c89-c850b3b81936.png)

It is shocking. With a query consisting of `time`, buckets labeled in even increments "10", "15", [...], "95", and a number for each [time,bucket] - should the bucket labeled "45" draw a huge rectangle from "45" to "90"? (in fact no, it should account for data from the "40" bucket to "45" according to the bucket bound selection)

In addition to drawing utterly bewildering buckets, despite strictly ordering the response by `time, bucket_name`, this panel _reorders buckets_ apparently via `buckets = random.shuffle(buckets)` in random cases, like with name prefixes, but not in others like with \d+ bucket name strings.

![image](https://user-images.githubusercontent.com/3454741/107846229-f651a580-6d96-11eb-9e3c-843c69d78571.png)

**Comment by leeoniya** [comment]
i believe this is fixed in the new heatmap panel we're finishing up for 9.0

in `Calculate: No` mode, the y axis will always have uniformly-sized cells (ordinal y axis), and y axis tick labels will always be the field names without any attempt to interpret what those tick labels contain, even when the labels might be numeric. we may at some point add an explicit panel option to interpret these labels as numbers for the purpose of allowing them to rendered on a linear or log y axis with cell sizes varying accordingly.
