### ISSUE TITLE
grafana-toolkit: No matching version found for @grafana/e2e-selectors

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana#24415]
**What happened**:

```
npx "@grafana/toolkit"@canary plugin:create my-plugin
```

fails with the following error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @grafana/e2e-selectors@^7.1.0-pre.0-e2c404518b.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@grafana/ui'
npm ERR! notarget 
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marcus/.npm/_logs/2020-05-08T07_15_34_854Z-debug.log
Install for @grafana/toolkit@canary failed with code 1
```

**Comment by muizabdul29** [comment]
I think it's because they have not yet released the v7 of Grafana. To be honest, I can't understand this workflow i.e. updating child modules before releasing main thing. This obviously means that plugin development at this point is broken and you have to wait for them to release v7.

Btw, I am having the same issue :(

**Comment by dprokop** [comment]
@muizabdul29 it's not broken. Canary release = released from master which does not guarantee stability. I suggest using stable versions, either beta releases (`next` tag on npm) or `latest`.
