### ISSUE TITLE
Transforms: Concatenation of fields

### ISSUE THREAD

**Issue by maemigh** [grafana/grafana#24484]
The new field from calculation is a great feature. It would be nice if fields could also be concatenated.

**What would you like to be added**:
Calculated fields by string concatenation

**Why is this needed**:
Can simplify queries or provide concat functionality where datasources do not

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
