### ISSUE TITLE
Cannot edit Dashboard Links

### ISSUE THREAD

**Issue by andyrbeal** [grafana/grafana#24523]
**What happened**:
Editing Dashboard links gives a Dashboard not found and returns to displaying the dashboard.

**What you expected to happen**:
Dashboard links can be edited

**How to reproduce it (as minimally and precisely as possible)**:
Go to play.grafana.org and edit dashboard links.

**Anything else we need to know?**:
I discovered this because I use a link to create a home button, 7.0 beta3 broke that button.  My other Drop down style links work, but the basic non-dropdown link now seems to refer to about:blank.  I don't think it was broken in Beta1, unfortunately I skipped beta 2 so I'm unsure when it broke.

**Environment**:
- Grafana version: 7.0.0 beta 3
- Data source type & version: ES, Mysql, influxdb.
- OS Grafana is installed on: RHEL/Oracle Linux 7.8
- User OS & Browser: Win10 Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/24416

**Comment by Mario-Hofstaetter** [comment]
I can edit my dashboard links, but they do not work.

is this related @torkelo and fixed with #24416 or a different issue?
Will test with next beta.

`Grafana v7.0.0-beta3 (2169fc1a3f)`

I have two dashboards with tag `foobar`
![grafik](https://user-images.githubusercontent.com/33002073/82085610-98037380-96ed-11ea-86a3-c95eff1b8d58.png)

Both have a dashboard link for the tag:
![grafik](https://user-images.githubusercontent.com/33002073/82085686-abaeda00-96ed-11ea-9191-06c8208743ac.png)

Both show a button that opens a blank page:
![grafik](https://user-images.githubusercontent.com/33002073/82085808-d4cf6a80-96ed-11ea-8fc9-04d0ce94aca5.png)
