### ISSUE TITLE
Feature Request: Allow listing datasources via API without "admin" key

### ISSUE THREAD

**Issue by juliusv** [grafana/grafana#24544]
**What would you like to be added**:

Currently only API keys with "admin" level are allowed to list datasources. E.g. with an "editor" key, I get:

```
$ curl -H "Authorization: Bearer XXX" http://grafana/api/datasources
{"message":"Permission denied"}
```

The reason is probably because the response also contains credentials for datasource access (even for `access: 'proxy'` datasources, where the browser does not need to know them). But maybe a non-"admin" response could omit those fields?

**Why is this needed**:

In PromLens (https://promlens.com/) I would like to pull the datasources currently configured in Grafana at the lowest-required permission levels, and then just proxy queries through Grafana for datasources with `access: 'proxy'`. I don't want an "admin" key that can read full credentials, or also mutate everything.

**Comment by juliusv** [comment]
Hmm, now I see that the API doesn't even include any of the secret fields (like basic auth passwords or header values), even for datasources configured for direct / browser access. That means that nobody can actually export these datasources fully and use them somewhere else. Is that intended? (makes me a bit sad)

**Comment by khanfouzia2** [comment]
I'm facing the same problem (unable to use datasource apis with non-admin users e.g. get datasource id by name). I would really like to have this functionality (if its really not available). Without having to differentiate between admin and non-admin user levels, it limits the usage of grafana, as non-admin users won't be able to see the panels which are using grafana datasource apis e.g. getting a datasource id in order to make an automatic query to display response after some computations on query results. 
Or I would really want to know if there is an alternative to achieve this?
