### ISSUE TITLE
MS SQL data source: Disable SSL certificate verification doesn't work

### ISSUE THREAD

**Issue by jericvizmanos** [grafana/grafana#24589]
**What would you like to be added**:
Disable SSL certificate verification for MS SQL Server Datasource

**Why is this needed**:
Encryption for MS SQL Server datasource has been added recently on #13629

While most data source allow disabling TLS verification, MS SQL datasource does not. Currently, there is no way to provide the CA Certificate in the datasource's configuration resulting in an error.

Error:
TLS Handshake failed: x509: certificate signed by unknown authority
<img width="458" alt="Screen Shot 2020-05-12 at 9 53 04 AM" src="https://user-images.githubusercontent.com/58444570/81722590-72007980-9436-11ea-97b8-727ed9b31a53.png">

**Comment by marefr** [comment]
Have you tried configured encrypt to disable?

**Comment by marefr** [comment]
Also what Grafana version are you using? That feature was implemented quite long time ago and not recently.

**Comment by jericvizmanos** [comment]
Hi @marefr - Thanks for checking this out! Yup. If encrypt = false, it goes through properly. However, when you set encrypt = true, it throws the error. Currently, there's no way to attach or place the certificate.

It's for Grafana v6.7.3.

**Comment by fifofonix** [comment]
Are we sure that encryption works at all for SQLServer connections?

We are getting the same TLS handshake error despite using a properly signed certificate.

We are using Grafana v6.5.2 (742d165) deployed in docker connecting to SQL Server 2017 (RTM) - 14.0.1000.169 (X64).

Unencrypted connection work fine.  And we are able to establish encrypted connections to SQLServer via other tools, e.g. SQLServerMgmtStudio without the need to explicitly trust the certificate (meaning it is validated via machine-configured trusted CAs) and also DBeaver (although because this is Java we need to specify a trust bundle).

Furthermore from the Grafana docker container command line we are able to execute openssl handshakes to other TLS-secured resources with the same CA chain as our SQLServer certificate.  And, we are able to complete openssl handshakes to the SQLServer itself - although I should note that this is a bizarre handshake as it shows no cipher selection - but I believe this is because Microsoft does something strange with its secure connections - schannel?

Without a connection-specific means to specify a trusted CA, my assumption is that the docker container's trust chain will be used, but perhaps as OP suggests there may need to be an explicit way to pass in a trusted CA if this is not respected?

**Comment by marefr** [comment]
I would suggest have a look at readme/issues at library we're using for connecting to mssql to figure out what's possible missing in Grafana: https://github.com/denisenkom/go-mssqldb#connection-parameters-and-dsn

**Comment by fifofonix** [comment]
Thanks @marefr.  I cloned the repo and was able to run a few tests on my Mac.  I have two observations.  For the purposes of these I'm presuming that grafana builds a DSN string behind the scenes in the sqlserver:// format that this library supports.

* Passing TrustServerCertificate=true will solve OP's issue
``` 
% export SQLSERVER_DSN=sqlserver://<hostname>?user+id=DOMAIN\\<username>\&encrypt=true\&password=<URL escaped password>\&TrustServerCertificate=true
% go test # passes
```
* Certificate Handling

It seems Go has its own way of specifying [trusted platform CAs ](https://stackoverflow.com/questions/40051213/where-is-golang-picking-up-root-cas-from) and on a Mac this does NOT involve using those in KeyChain.  For this reason in my tests I received same error as OP when using a validly signed cert on SQLServer.  However, the library does support specifying CA certs explicitly and tests of this work:
``` 
% export SQLSERVER_DSN=sqlserver://<hostname>?user+id=DOMAIN\\<username>\&encrypt=true\&password=<URL escaped password>\&certificate=/a/local/ca/cert.pem
% go test # passes
```
Whether the right longer term solution for Grafana is to allow the cert to be explicitly specified via UI or configuration, or to have users modify their local platform installation to include certs in a Go-supported location is up for debate.  Regardless, an update to SQLServer Data Source documentation in the short term, so it is understood that encryption with certificate verification requires that certificates for trusted CAs must be in Go-supported locations, may be appropriate.

For the time being my personal next steps to get this solved will be to add to the Go trusted CAs on my Alpine-based Grafana docker container.  I've still got some investigations to perform on this front to understand behaviour.  For example, comments in https://golang.org/src/crypto/x509/root_linux.go seem to suggest that only one of the string array will be used, but it is not clear to me (I don't know Go) if this is an ordered array, and whether I should assume just because I'm using Alpine that /etc/ssl/cert.pem is where I should append my CA certs.

**Comment by marefr** [comment]
@fifofonix sorry for the late response. Thanks for great investigation and writing this up, appreciate it. I would suggest you to open a PR if your interesting in getting this feature implemented. Similar functionality have already been added to the Postgres data source so should be pretty straight forward (I think) implementing this looking at the postgres implementation:
![image](https://user-images.githubusercontent.com/1668778/92662429-18825b80-f2ff-11ea-85a8-ae2f6df3a3a6.png)

Postgres [frontend code](https://github.com/grafana/grafana/blob/be8bc512cb97a9b82e00666b7a10774de856f51b/public/app/plugins/datasource/postgres/partials/config.html#L30-L63) and [backend code](https://github.com/grafana/grafana/blob/be8bc512cb97a9b82e00666b7a10774de856f51b/pkg/tsdb/postgres/postgres.go#L95-L115) for reference.

Let me know if you have any questions/concerns

**Comment by mortenaa** [comment]
Hi, we had this same issue when connecting to a Mssql server with a self signed certificate, so I had a go at fixing it.
https://github.com/grafana/grafana/pull/31865
