### ISSUE TITLE
[Feature request] Short-cut for ad-hoc graph

### ISSUE THREAD

**Issue by liyichao** [grafana/grafana#2464]
To make a graph is too complex in grafana: we need first new a dashboard, then select the left green widget to add a panel, and then click the graph title to edit the graph. 

Somtimes, I just want to see a graph of metric, I do not want to  create  a dashboard.

**Comment by torkelo** [comment]
I agree

**Comment by grobie** [comment]
:+1:

**Comment by cschotke** [comment]
+1

**Comment by LeeYeeze** [comment]
Happens to see this issue is still open. One more feature wanted, if users think the content an ad-hoc panel presents is valuable and should reside in one dashboard already exists, there should be a way to copy the ad-hoc panel to the dashboard instead of creating the same panel again manually in the dashboard

**Comment by coofercat** [comment]
I'm going to say "me too" for this one.

I'd imagine a 'disposable dashboard' or 'scratchpad' where the user can create graphs (or indeed any other type of widget). I guess it would be cool to make it possible to link to this temporary graph (perhaps save it to temporary storage when the user clicks a 'share' button?), or else to be able to 'cut and paste' some serialised config, or put the graph config into the URL (a little like splunk/kibana do) so that an ad-hoc graph can be passed between people as required. I also like the idea of being able to say "make a dashboard using this graph".

Another option would be to make dashboard graphs the start of an ad-hoc graph or dashboard. That is, you're looking at an established dashboard, click the "make one just like this" (or "make a new dashboard with this graph" button) and then get to hack about with it as you want without the chance of modifying the original dashboard.

In my use-case, I've got a graph of the time it takes to perform a few memcache operations (which should be super-fast). On a couple of servers it seems to take longer than elsewhere. To figure out what's going on, I'd now like to plot system load, or cpu utilisation, or network traffic against memcache performance. Those stats don't make sense on the actual dashboard, they definitely need to go elsewhere, but doing so is pretty slow (mostly because I'd end up editing a known graph just to find out how it was drawn so I can copy it).

Either way, right now, having to create a dashboard (which is auto-saved in a lot of ways) means that users are creating a lot of dashboards called "New Dashboard" which they then forget about (or are unware have been created).

**Comment by bergquist** [comment]
Agree.

As a side note. From 4.1 users will be asked to name their dashboards if it havent been saved before. Thus getting ride of the messy `New Dashboard` dashboard :)

**Comment by thenewwazoo** [comment]
I too would like to be able to slice data interactively, instead of having to build up a dashboard. Bosun has a nice feature like this, and it's the bread and butter of Graphite.

**Comment by garo** [comment]
I have used Graphite for a really long time and I love how I can very quickly just drill down into anything and display a graph. Doing the same in Grafana takes easily 5-10 times longer.

**Comment by amitkumar912** [comment]
We've been trying to work on this front. We started with a plug-in approach, but could not create a stand-alone panel. The panel needed dependency on the Row object, which depended on the Dashboard.

We looked into the scripted dashboard briefly, however we wanted it to be chart type agnostic.

The requirements we were looking to fill were:
- Make the ad-hoc graph shareable.
- Add the ad-hoc graph to a new/existing dashboard.
- Chart type agnostic. 

If anyone has made any ideas on how to accomplish this we'd love to hear it and hopefully be able to give ti back.

**Comment by mtanda** [comment]
https://github.com/grafana/grafana/issues/11741 will solve this.

**Comment by phemmer** [comment]
Not as I see it. #11741 is about modifying an existing panel. This issue is about rapidly creating a graph without having to go through the steps of add dashboard, and add graph.

**Comment by davkal** [comment]
This could be done in Explore, and together with starred queries (see query history) and URL sharing, you have something temporary.
