### ISSUE TITLE
Dashboard: Introduce dirty state that is set via deliberate change actions instead of ChangeTracker diff 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#24663]
We have a number of problems with the current ChangeTracker & unsaved changes warning. 

* It checks for changes using diff on the json model 
* To eliminate changes to the model that we do not really care about we clean up the original & changed versions
* But a lot of changes happen to the model that are not deliberately change actions that we cannot filter out in the change tracker diff. 
  * Things like Panel model migrations & defaults that are applied lazily on large dashboards with many panels (that scroll)   
  * If you expand a row we move the panels inside to the outer panels array, causing a big json diff but expand or collapse a row should not be considered an action worthy of unsaved changes warning.
   * Changes to template variable values should not be considered as a change worthy of unsaved change warning so ChangeTracker needs to go through a lot of cleanup to try to ignore them

We should change this logic and instead set a dirty flag when deliberate change actions occur (that should trigger an unsaved change warning). And could be good to make this dirty flag an array or bit flag so we can keep track of what has changed (on a high level)  and automatically show that in the unsaved changes warning (in a digested form). 

Other reasons for this:
* We want to introduce more dynamic grid layouts (so panels can dynamically adjust their gird size) but this would today cause a grid position update in the persisted model & unsaved change warning.

**Comment by Guyverix** [comment]
It was requested I put some information into this issue ticket as well since I am experiencing this problem when dealing with the imageIt plugin.  Attached is the diff between saves, when nothing config wise was changed.  The second image shows the actual dashboard.  I do suspect that the colour changes that imageIt uses also plays a role in Grafana thinking that a configuration change has occurred.

The easiest way to reproduce this would be a sensor metric that will change colours.  It does not really seem to sensitive to what values are in there, as long as a colour change is triggered. 

I am currently running version: 
v6.7.3 (a04ef6cefc) On an Ubuntu server, this happens on different versions and has been happening for at least the last 4 months of releases in my case.

![Selection_020](https://user-images.githubusercontent.com/1209259/82268648-66282200-9924-11ea-8e14-3e5a71c6cc73.png)

![Selection_021](https://user-images.githubusercontent.com/1209259/82268738-9a034780-9924-11ea-816e-d0961a31f357.png)

**Comment by annelaurefroment** [comment]
There is another issue with the unsaved changes warning, users with Viewer role on the org, and Editor role on a folder or dashboard do not get the warning when exiting a dashboard with unsaved changes. Only users with editor and admin roles at the org level do.
Would it be possible to fix that and give every body with rights to edit the warning ?
A bonus would be to have an option for user to disable the warning if they find it annoying, but the main request is to have it for everyone by default.

**Comment by mdvictor** [comment]
This was solved with the new approach, will close to clear the backlog.
