### ISSUE TITLE
Azure Monitor Plugin | 2 Variables | 400 Bad Request

### ISSUE THREAD

**Issue by s-ahuja** [grafana/grafana#24697]
**What happened**: Request failed status: 400 Bad Request

**What you expected to happen**: Query Results

**How to reproduce it (as minimally and precisely as possible)**:
InsightsMetrics
| where $__timeFilter(TimeGenerated)                              
| where $Metric == Name `<-- $Metric : value coming correctly in dropdown & Variables screen`
| extend ParsedTags = parsejson(Tags)
| extend AppName = ParsedTags.app
| where $AppNamespace == AppName `<-- $AppNamespace : value coming correctly in dropdown under the Variables section of Dashboard` COMMENTING THIS LINE WORKS. 
| order by TimeGenerated asc

**Anything else we need to know?**:

**Environment**:
- Grafana version: master (latest 7.1)
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Linux Container
- User OS & Browser: Chrome
- Grafana plugins: NA
- Others: NA

**Comment by daniellee** [comment]
The error message is terrible so will have to fix that - it should be returning the actual parsing error rather than saying it is a bad request.

In your query, do you have this line? `<-- $Metric : value coming correctly in dropdown & Variables screen`

`<--` is not valid KustoQL I think. Comments are `//`.

The other thing that is wrong with your query is that the values are not quoted. If you have a variable that is not multi value then you have to do the quoting yourself: `| where "$AppNamespace" == AppName`

When I ran your query without the comments then it worked for me. If you executing it without the comments, can you turn on debug mode and get the line that looks like this from the debug logs:

```
DBUG[05-14|19:27:19] AzureLogAnalytics                        logger=tsdb.azuremonitor Request ApiURL="https://api.loganalytics.io/v1/workspaces/a2c1b44e-3e57-4410-b027-6cc0ae6dee67/query?query=InsightsMetrics%0A%7C+where+%5B%27TimeGenerated%27%5D+%3E%3D+datetime%28%272020-05-14T11%3A27%3A19Z%27%29+and+%5B%27TimeGenerated%27%5D+%3C%3D+datetime%28%272020-05-14T17%3A27%3A19Z%27%29%0A%7C+where+%22test%22+%3D%3D+Name+%7C+extend+ParsedTags+%3D+parsejson%28Tags%29%0A%7C+extend+AppName+%3D+ParsedTags.app%0A%7C+where+%22test%22+%3D%3D+AppName+%0A%7C+order+by+TimeGenerated+asc%0A%0A"
```

**Comment by torkelo** [comment]
What should be done here? looks like the query was wrong? (with comments formatted the wrong way)

**Comment by joshhunt** [comment]
@s-ahuja Took another look at this, and as Daniel mentioned there appears to be a few syntax issues in your query. Try creating your query in the Azure Portal (without template variables) to double check that you have the syntax correct.

If the issue is still happening, feel free to reopen with more details.
