### ISSUE TITLE
AliasByNode doesn't work when the value of the alias is 0

### ISSUE THREAD

**Issue by annelaurefroment** [grafana/grafana#24785]
**What happened**:
Using the panels Stats, Bar Gauge and Gauge, aliasByNode gives the error `Cannot redefine property: 0`  when the value of the alias is 0 
![image](https://user-images.githubusercontent.com/49911675/82188827-0c722880-9921-11ea-9f65-a7fb30452fbd.png)
 
I checked, 00 or 01 work: 
![image](https://user-images.githubusercontent.com/49911675/82188916-2b70ba80-9921-11ea-8028-472a5a9954f4.png)
 

**What you expected to happen**:
Show the value for the alias

**How to reproduce it (as minimally and precisely as possible)**:
Use AliasByNode on a node with at least one of the values being 0. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.3
- Data source type & version: graphite
- OS Grafana is installed on: hosted grafana
- User OS & Browser:
- Grafana plugins: Stats, Bar Gauge and Gauge
- Others:

**Comment by ifrost** [comment]
@annelaurefroment - are you still having this problem? I was able to use "0" in the latest Grafana version:

<img width="1376" alt="Screenshot 2021-03-12 at 13 06 59" src="https://user-images.githubusercontent.com/745532/110941802-2ca02780-8339-11eb-8740-47d7e3de98e6.png">

This bug has been fixed by this PR: https://github.com/grafana/grafana/pull/24024 and it should be working in version >=7.0.0. Are you still using 6.7.3?

**Comment by ifrost** [comment]
Closing the issue for now, but please free to re-open it if you're still having problems with it.
