### ISSUE TITLE
Datasources: add support for non-JSON messages while parsing query responses.

### ISSUE THREAD

**Issue by Estrax** [grafana/grafana#24857]
Certain datasources on various edge cases (e.g. when a datasource goes down while processing the request) return responses that are not valid JSON objects (either just text or an empty response) and at the vast majority of cases Grafana throws a parsing error. For all core datasources we should add an ability to process non-JSON responses.

Should we treat all those non-JSON responses as errors? Or do we know of any cases where a non-JSON response is still a correct one? @davkal @aocenas @torkelo 

ref #24843

**Comment by aocenas** [comment]
Well the communication with DB should be handled by the data source code, it should know how to interpret errors. So I think this is not exactly a generic thing and should be handled be proper data source implementation. I think the main issue was with Elastic so it needs to be checked what the responses can look like and handle non json ones reasonably.

**Comment by davkal** [comment]
Yup, agree with @aocenas it's the DS responsibility to interpret errors (or non-availability) and throw an error that the user can later interpret correctly (e.g., not something like parsing errors that assume a certain data format).
In practical terms this issue here is too broad and not actionable. I recommend adding one for elastic since it sparked this.

**Comment by aknuds1** [comment]
What @davkal and @aocenas say sounds right to me. The individual data sources will probably have to catch non-JSON error messages and deal with them.
