### ISSUE TITLE
@grafana/ui plugin version mismatch unclear error

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#24923]
**What happened**:
When developing a plugin with `@grafana/ui` version v7.0 and using it in a Grafana version v6.x
```jsx
<Legend>Grafana</Legend>
```
causes the error
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

**What you expected to happen**:
The error message is very unclear.
Either expect:
- For it to just work (this might not be possible, as it would mean including several versions of grafana/ui)
- Display an error message of a version mismatch (only possible for future versions)

**Anything else we need to know?**:
[Migration guide for breaking changes](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/CHANGELOG.md#breaking-changes)

The problem is that plugin authors think they use the grafana/ui version listed as a dependency in the plugin, which is not the case. The ui version being used is the same as the Grafana version you are running.

Feel free to discuss possible solutions below!

**Comment by yesoreyeram** [comment]
@torkelo - Is that literally mean I can't upgrade to 7 until all of my third party plugins updated to use 7.x UI library?  As a plugin author, do i need to maintain separate builds for <7.x and >=7.x versions? 

Most of the broken things are from `@grafana/ui` library FormField, SecretFormField, FormLabel etc..

To give more context:  Though my plugin use 6.x libraries, when I use grafana 7.0.0 the editors (query editor, config editor,  panel editor etc) failed to open due to above mentioned breaking changes.  If I update UI library to 7.0, plugin no longer works in 6.x . Is there breaking changes anywhere communicated or i just miss anything?

**Comment by torkelo** [comment]
Yes, that is true. Many react plugins that used the alpha version of @grafana/ui need to be updated to work in 7.0 , and if updated won’t work in old versions.

Sorry if this causes problems but we had to do some big breaking changes in the library as we made it ready for beta

**Comment by tskarhed** [comment]
@yesoreyeram Breaking changes were mentioned in the [changelog](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/CHANGELOG.md#breaking-changes). Do you have any suggestion for where else we could communicate this?

**Comment by yesoreyeram** [comment]
That's fine @tskarhed . My initial impression was that plugin can independently have the different version of library components. But now I understand that the versions mentioned in the plugin's package.json doesn't honoured. Grafana's plugin version will override. I think this was not communicated clearly. 

Ideally plugin authors should be given freedom to use / stick with the version they want. Otherwise there will be pressure to keep updating the plugin based on the changes happening in the library.

**Comment by wbrowne** [comment]
Closing as stale - this is part of a bigger problem that will be tracked elsewhere
