### ISSUE TITLE
React UI storybook page to be not flashing.

### ISSUE THREAD

**Issue by ryuheechul** [grafana/grafana#24996]
**What would you like to be added**:
[React UI storybook page](https://developers.grafana.com/ui/latest/index.html) to be not flashing.
When dark mode, the main section in the center flashes with white background.
Since it's quite normal to keep clicking other components to see different compoents, this should be improved that background color stay same instead keep flashing.

**Why is this needed**:
No one likes flashing, It hurts 👀 .

**Comment by torkelo** [comment]
@tskarhed any idea why it's flashing the white theme when you navigate between stories?

**Comment by Clarity-89** [comment]
Seems like the addon we're using has light theme as default and then it gets switched to current dark theme, causing the flickers. I wonder why that hook isn't taking the current theme value from the local storage instead, since that's what they do for the theme switch in the toolbar: https://github.com/hipstersmoothie/storybook-dark-mode/blob/master/src/Tool.tsx#L47

**Comment by Clarity-89** [comment]
Made a PR in the addon repo that should fix this isssue: https://github.com/hipstersmoothie/storybook-dark-mode/pull/110

**Comment by ryuheechul** [comment]
@Clarity-89 fantastic!
