### ISSUE TITLE
Inspect: Download CSV & Excel format option 

### ISSUE THREAD

**Issue by BuJo** [grafana/grafana#25017]
**What happened**:

In the past there were problems reading exported CSV files in Excel due to the ";" separators, see: #2401 and #9083

In Grafana 7 the Excel Option is gone and the CSV files are now not loading properly anymore in Excel.

Have I just missed a Button or a new Configuration setting somewhere?

**What you expected to happen**:

Excel can read the exported CSV files without selecting separator manually.

**How to reproduce it**:

Use any Panel, Inspect Data, Export CSV.  Try to open with Excel.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0
- OS Grafana is installed on: Linux
- User OS & Browser: Windows / Chrome

**Comment by torkelo** [comment]
We will try to add this back in 7.1

**Comment by coussej** [comment]
Related to this, there are a few other options that are different from before / missing:

* Different: Possibility to export csv using human readable timestamps instead of unix. Used to be human readable < 7.x, no options to change. Breaks workflow for people exporting data to excel for further processing. 
* Missing: possibility to export taking locale into account (for example, in Belgium we have comma as decimal separators.

I made a pull request for the latter in 6.x, not knowing you were rebuilding the csv export. @torkelo would you accept a pull request for these features?

**Comment by torkelo** [comment]
absolutely

**Comment by ethirolle** [comment]
Just a point of clarification: there is not "right" or "wrong" in the choice of delimiter in the CSV, there are only choices that will favor some users depending on their language/country. It appears that Excel defaults to using a semi-colon delimiter in all/most of Europe, while comma-delimited has always been the default in US Excel. I tested this morning: if I open a CSV in the old format in my US-based Excel, it fails to separate the columns... so the old semicolon-delimited format was "broken" for US-based users in the same way that the new comma-delimited format is "broken" for Europe-based users.

In other words: the choice of delimiter is a trade-off that favors some users, and causes some inconvenience for other users, depending on their Excel settings, which depend on their language/country.

The best way to handle this is probably one of these options:

1. have Grafana take into account the regional settings for column and decimal separators

1. OR give the user the ability to configure these options in the export dialog

In either case, I agree with what @coussej said above: we should probably be consistent in using human-readable timestamps like "2020-07-14 06:00:59" (which Excel imports in proper date format), rather than the UNIX/Epoch timestamps like "1594637907000" (which Excel imports as numbers).

**Comment by anthraxn8b** [comment]
Hi!
I cannot find the feature in 7.2.0.
It would really really really be helpful...
I am currently trying to use Datatable Panel Plugin (https://grafana.com/grafana/plugins/briangann-datatable-panel) which as an integrated feature - but other downsides...
THX in advance!

**Comment by dprokop** [comment]
This is now fixed with https://github.com/grafana/grafana/pull/27284 and will be released in Grafana 7.3
