### ISSUE TITLE
Repeat Panel rendering issue

### ISSUE THREAD

**Issue by jbfavre** [grafana/grafana#2503]
I use Grafana with Zabbix datasource.
I use the new Repeat Panel feature to be able to compare same metrics from different server.

A typical Row in my dashboard is:
- static Graph, span 4
- "dynamic" panel with repeat panel, no size (by default span 12)

The second panel is displayed below the first one, because of span 12. I expected span 8.

When selecting another templated variable, I got 3 panels:
- static one, still span 4
- dynamic one wih span 6 (span 4 expected)
- another dynamic one wih span 6 (span 4 expected)

**Comment by rex** [comment]
I am seeing this as well. I have attached a screenshot of what we're seeing on our end. The dashboard structure should be

```
[       span-6       ] [span-2] [span-2] [span-2]
```

Which is evident in the first few lines of the dashboard as visible in the screenshot. But then for some reason it goes awry and starts reordering itself as well as resizing the columns :) I feel like it's important to note that this issue occurs whether there's two "multi-" variables selected, and _is not_ unique to or caused by having a huge number of variables selected.

<img width="1018" alt="screenshot 2015-09-14 11 52 25" src="https://cloud.githubusercontent.com/assets/4247754/9855984/7faac25e-5ad7-11e5-8247-5e5848583447.png">

**Comment by torkelo** [comment]
When using repeat panels put them on their own row :) Not ideal, but fixing this issue will break other layouts as well (when using row and panel repeat combos, where a single row extends to multiple rows due to span > 12)

**Comment by jbfavre** [comment]
That's what I am doing :)
My suggestion was either to dynamically calculate span size, or add a max-span option (there's already a min-span).
Further, I don't see the point when using both panel and row repeat: I already have rows with span > 12 :-/

**Comment by torkelo** [comment]
@jbfavre combining panel and row repeat is very useful, like each row can contain graphs for each IO interface (repeat panel), then repeat rows for each server. 

not sure what you mean  dynamically calculate span size, that is what is happening (with a min span applied).  Will take a look at this if more people have similar requirements.

**Comment by jbfavre** [comment]
@torkelo I already use both panel & row repeat.
The only problem I have is with panel repeat, when I have a "static" panel on a rox like:

[static panel span 4] [repeat panel] [repeat panel]

First repeat panel takes a span of 12, where I assume it should calculate there's only 8 left.
When I add another repeat panel, both repeat panels will take span 6, where I would like it to be 4:
12 - 4 static = 8 for both repeat panels, which makes 4 for each.

Repeated row do not change anything, only panel behaviour looks suboptimal to me.

**Comment by rex** [comment]
@torkelo That's a great idea, I'll begin doing that going forward!
