### ISSUE TITLE
Stackdriver datasource: the graph panel is not treating null values as zero when selecting "null as zero"

### ISSUE THREAD

**Issue by jhsilver2** [grafana/grafana#25031]
**What happened**: 
When using the Stackdriver datasource, the graph panel is not treating null values as zero when selecting "null as zero" in the Null value field nor is it treating null values as null when selecting "null" in the Null value field. Rather the graph shows as connected.
![image](https://user-images.githubusercontent.com/61845850/82699563-c3bcb700-9c21-11ea-8166-35c7e5ce9dd6.png)

**What you expected to happen**:
Expected result should be as shown in the Metrics Explorer in the Google Cloud Monitoring Console. A gap in data.
![image](https://user-images.githubusercontent.com/61845850/82699617-d636f080-9c21-11ea-8001-0140697ed160.png)

**How to reproduce it (as minimally and precisely as possible)**:
Using the Stackdriver datasource, graph the metric: pubsub.googleapis.com/topic/send_request_count
For the select field "Null value" select "null as zero" 
Notice that when there is a gap in data, the graph shows connected.
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.1 (this also occurs in 7.0.0)
- Data source type & version: Stackdriver 1.0.0
- OS Grafana is installed on: Ubuntu 16 LTS
- User OS & Browser: MacOS Chrome
- Grafana plugins: Stackdriver (Core) 
- Others:

**Comment by sunker** [comment]
@jhsilver2 do you still have this problem? What version of Grafana are you running?

**Comment by Xopherus** [comment]
I can confirm I'm also seeing this on Grafana 7.4.3

![image](https://user-images.githubusercontent.com/6126813/119702755-cdc05980-be23-11eb-8ea2-d1b4afd887cd.png)

**Comment by albrechtflo-hg** [comment]
Still an issue in Grafana 8.1.0.

**Comment by andresmgot** [comment]
I suspect that the issue here is that the API is not returning a value at all or that the value returned is not `null`. I tried to reproduce this but I couldn't find a query a query that return `null` or empty values. Can anybody in this thread provide a query I can try to use to reproduce the issue?

I see some code like [this](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudmonitoring/time_series_query.go#L227) that may be causing the issue but as I said, I was not able to reach that.

**Comment by iwysiu** [comment]
Does this problem appear in the time series visualization as well, or is it only in the graph type?

**Comment by iwysiu** [comment]
I was able to reproduce this using the query execution times metric from BigQuery. The issue is that the frontend expects the backend to insert filler null values for timestamps that don't have data, however cloud monitoring does not. Fixing this depends on the result of the conversation on #43507 about whether or not datasources should insert null values.
