### ISSUE TITLE
Cloudwatch:  Member must have length less than or equal to 1024 status code

### ISSUE THREAD

**Issue by dkel520** [grafana/grafana#25062]
I used grafana dashboard https://grafana.com/grafana/dashboards/969
lt looks normal

but if i check settings -> variables -> cachedclusterId -> Selection Options -> Multi-value

'metricDataQueries.4.member.expression' failed to satisfy constraint: Member must have length less than or equal to 1024 status code: 400, request id: 302d3ed6-24f3-4065-a56d-23934d486cb8

I get the following error

but grafana 6.24 is works fine

**Comment by ovalenzuela19** [comment]
I'm getting this same issue

**Comment by pawanyoda** [comment]
Yes this is getting me same as well While selecting all dynamodb tables data(around 50 tables) 
**Error:**
`'metricDataQueries.3.member.expression' failed to satisfy constraint: Member must have length less than or equal to 1024 status code: `

`Grafana Version: Grafana v7.1.1 `

**Comment by torkelo** [comment]
This is a cloudwatch limit in their new API, not something I think Grafana can do anything about

**Comment by gattie** [comment]
I know this issue is closed, but I wanted to provide an answer/solution when I ran into similar issues. In grafana I set a host variable which could contain as many hosts as might appear in a namespace in grafana. If enough hosts existed in the namespace and the `All` option was selected in the dropdown in grafana for the host variable I would get the error mentioned here.

When looking at the error you can see that whatever variable you're providing will be constructed in a series or OR statements which causes the query to go over 1024 characters. An example would look something like this:

> REMOVE_EMPTY(SEARCH('{my-namespace,"host"} MetricName="my_custom_metric" "host"=("my-long-hostname001.domain.tld" OR "my-long-hostname001.domain.tld" OR "my-long-hostname002.domain.tld" OR "my-long-hostname003.domain.tld" OR "my-long-hostname004.domain.tld" OR "my-long-hostname005.domain.tld" OR "my-long-hostname006.domain.tld" OR "my-long-hostname007.domain.tld" OR "my-long-hostname008.domain.tld" OR "my-long-hostname009.domain.tld" OR "my-long-hostname010.domain.tld" OR "my-long-hostname011.domain.tld" OR "my-long-hostname012.domain.tld" OR "my-long-hostname013.domain.tld" OR "my-long-hostname014.domain.tld" OR "my-long-hostname015.domain.tld" OR "my-long-hostname016.domain.tld" OR "my-long-hostname017.domain.tld" OR "my-long-hostname018.domain.tld" OR "my-long-hostname019.domain.tld" OR "my-long-hostname020.domain.tld" OR "my-long-hostname021.domain.tld" OR "my-long-hostname022.domain.tld" OR "my-long-hostname023.domain.tld" OR "my-long-hostname024.domain.tld" OR "my-long-hostname025.domain.tld" OR "my-long-hostname026.domain.tld" OR "my-long-hostname027.domain.tld" OR "my-long-hostname028.domain.tld" OR "my-long-hostname029.domain.tld" OR "my-long-hostname030.domain.tld" OR "my-long-hostname031.domain.tld" OR "my-long-hostname032.domain.tld" OR "my-long-hostname033.domain.tld" OR "my-long-hostname034.domain.tld" OR "my-long-hostname035.domain.tld" OR "my-long-hostname036.domain.tld" OR "my-long-hostname037.domain.tld")', 'Average', 60))

The fix for me was to set a custom value for All for that variable. I set it to `*` which meant the query changed to something much simpler like this when selecting All:

> REMOVE_EMPTY(SEARCH('{my-namespace,"host"} MetricName="my_custom_metric"', 'Average', 60))

Granted, this won't fix the issue if you are individually selecting multiple resources with long enough names that pushes the query over the 1024 limit, but if that is happening it may be time to reconstruct your query anyway.

**Comment by TryTryAgain** [comment]
Just echoing @gattie ... setting the variable's "Custom all value" to `*` allowed me to choose All from the dashboard's templated variables and it worked...no longer had the 1024 limit. My guess is this is because instead of sending All variables as "OR"'s as described above, it chooses `*` which only grabs what's available. It won't solve all cases but it definitely helped me. If "what's available" exceeds 1024 the same would happen although even in large environments I haven't come across that issue yet.
