### ISSUE TITLE
7.0 Stat panel: ${__field.labels.*} not evaluated in data links

### ISSUE THREAD

**Issue by tim-preston** [grafana/grafana#25106]
I have some dashboards that use data links in Stats panels that go to other dashboards for drill-down. In order to pass the correct variables to the linked dashboards I was using things like ${__field.labels.instance} in the data link URL. This worked fine in 6.7, but in 7.0 these are not being evaluated.

**What happened**:
After upgrading to 7.0 the URL passed to the linked dashboard contains "${__field.labels.instance}".

**What you expected to happen**:
I expected it to contain the value of the "instance" label of the data in the stat panel.

**How to reproduce it (as minimally and precisely as possible)**:
Add a data link to a Stat panel that includes variables set via the above method:
<URL>?orgId=1&var-instance=${__field.labels.instance}&var-ifName=${__field.labels.ifName}

Set up the dashboard in the link to handle the passed variables.

Use the data link and see what is passed to the linked dashboard.

**Anything else we need to know?**:
These ${__field.label.*} variables still show up in the popup for the URL editor (^space) and are correctly syntax hi lighted so this doesn't look intentional.

Also ${__url_time_range} is working as expected in Stat panel data links in 7.0.

**Environment**:
- Grafana version:
7.0
- Data source type & version:
Prometheus 2.x
- OS Grafana is installed on:
Ubuntu 18.04
- User OS & Browser:
macOS 10.15.4
Safari 13..1
- Grafana plugins:
Stat panel
- Others:

**Comment by torkelo** [comment]
Able to replicate this: https://play.grafana.org/d/q3grSFzMk/prometheus-labels-in-link?orgId=1 

@dprokop think the problem is the auto complete, it suggests ${__field.labels.labelName} when it should be ${__field.label.labelName}. (without plural s). 

Not sure where the suggestions are generated. Looks like we have a miss match in data link variable names, 

https://github.com/grafana/grafana/blob/master/public/app/features/panel/panellinks/linkSuppliers.ts#L26 

there it is plural, and here it is singular: https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/field/fieldOverrides.ts#L116
