### ISSUE TITLE
Variables: Grafana 7+ SLOW variable dropdowns needs virtualized rendering

### ISSUE THREAD

**Issue by Naumis1** [grafana/grafana#25135]
The old template variable dropdowns had a render limit of I think only 1000 items (rest required search to access). 
Think we need something similar for the new React template variable dropdowns, or virtualized rendering 

==========================
Hi, I have dashboard which has variable with 50k+ values (ip addresses). 
After update, from 6.x to 7.x, pressing dropdown to select ip is very slow. If I try to enter ip beggining to narow down selection, firefox starts to use all CPU from my pc and I get "A web page is slowing down your computer" warning with two possibilities. Stop execution or wait.. After 5 or 7 clics "Wait" It starts to work(slowly). Chrome is a bit better, but still very slow. I think 20x than Grafana 6.x version. I tried to change variable settings to do variable refresh "On dashboard load", "Never". But still the same.  
I am using fedora 31 with gnome.
Firefox 76.0.1 (64-bit), 
Chrome 81.0.4044.138 (Official Build) (64-bit),
Grafana 7.0.1 
I have same complains from windows users too. Both with Firefox and Chrome
P.S. Datasource is InfluxDB
Thanks!

**Comment by zhukaiqiang** [comment]
I have the same problem

**Comment by jon-rolfe** [comment]
To add some color for the devs, this is definitely a bug introduced in 7.0 rather than a feature request to allow for faster support of drop-downs with large variables. The variable appears to load on dashboard load just fine, but clicking on the dropdown and subsequent keypresses result in high memory/CPU usage. If given enough time (~15-45s per click or keypress), the variable listing will actually work/filter just fine, but in Grafana 6.x the dropdown appeared and was filterable instantly.

The below example has a variable with around 140,000 values, but time-to-load for me increases approximately linearly, e.g., 10k values =~ 2sec to dropdown, 50k values =~ 10s, 100k values =~ 20sec, and so on. First keypress(es) then take about 1/2 the time of dropdown load but subsequent keypresses, including backspace, load very quickly.

In all cases for me, the large number of results have been with type "query." Like @Naumis1, changing refresh interval does not appear to have an impact on loading speed.

Grafana Version: Grafana v7.1.0
Browser: Google Chrome 85.0.4183.83 for macOS
Data Source: clickhouse-grafana

Chrome Performance Tab:
![image (8)](https://user-images.githubusercontent.com/3102875/91606898-db45c300-e927-11ea-9f76-1f852c658229.png)

Chrome Memory Utilization:
<img width="416" alt="image (9)" src="https://user-images.githubusercontent.com/3102875/91607115-35df1f00-e928-11ea-8a6c-a0cd8c778ecf.png">

Let me know what other information I can get for you to be helpful. Thanks!

**Comment by hugohaggmark** [comment]
We merged an external contribution recently that should address this (I don't remember the PR Id but will post it when I find it) so have you tried upgrading to 7.2 release?

**Comment by hugohaggmark** [comment]
I found it #27525 should introduce a performance boost when opening the DropDown for large variables. This fix was released in 7.2.0-beta2.

Can you verify that #27525 fixes your issues @Naumis1, @zhukaiqiang and @jon-rolfe? Thank you.

**Comment by matthiaslee** [comment]
@hugohaggmark we also ran into this issue and it seems the latest version fixes this issue for us!

**Comment by hugohaggmark** [comment]
> @hugohaggmark we also ran into this issue and it seems the latest version fixes this issue for us!

I'm very glad to hear that @matthiaslee :)

**Comment by jon-rolfe** [comment]
> I found it #27525 should introduce a performance boost when opening the DropDown for large variables. This fix was released in 7.2.0-beta2.
> 
> Can you verify that #27525 fixes your issues @Naumis1, @zhukaiqiang and @jon-rolfe? Thank you.

Consider it verified over here as well. I think this issue is safe to close. Thanks!

**Comment by hugohaggmark** [comment]
@jon-rolfe thank you for taking the time to confirm ⭐

**Comment by hugohaggmark** [comment]
@Naumis1 I'm going to close this issue for now because it seems like it's already been fixed. If the mentioned fix doesn't hold as a fix for this issue we will of course reopen this issue.

All the best

**Comment by Naumis1** [comment]
> I found it #27525 should introduce a performance boost when opening the DropDown for large variables. This fix was released in 7.2.0-beta2.
> 
> Can you verify that #27525 fixes your issues @Naumis1, @zhukaiqiang and @jon-rolfe? Thank you.

Hi, sorry for delay. Yes I can confirm, that there is no problem any more. Thanks!!!
