### ISSUE TITLE
Viewer: Disable sharing options

### ISSUE THREAD

**Issue by zoliapjove** [grafana/grafana#25263]
**What would you like to be added**: Ability to disable sharing options for users with viewer role.
![image](https://user-images.githubusercontent.com/24809373/83406947-6cd09200-a418-11ea-9fa8-6c95434d7ed0.png)

**Comment by torkelo** [comment]
Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
