### ISSUE TITLE
Viewer: Limit access to raw data and queries

### ISSUE THREAD

**Issue by zoliapjove** [grafana/grafana#25264]
**What would you like to be added**: Ability to disable displaying raw data for users with viewer role. Now users with viewer role can view raw data and queries in Inspect > Data or Panel JSON. Viewer should be able to view data and download CSV file only with "Apply field configuration" enabled.
![image](https://user-images.githubusercontent.com/24809373/83408100-b7530e00-a41a-11ea-94ba-1ef13d8c4d77.png)

**Why is this needed**:
Raw data and queries can contain sensitive data.

**Comment by torkelo** [comment]
very unlikely we will ever be able to do this, as this transform is done in frontend so view user will always have access to the raw data & queries 

Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
