### ISSUE TITLE
Appinsights  and loganalytics issue when using query

### ISSUE THREAD

**Issue by Abster79** [grafana/grafana#25369]
**What happened**:
The Azure plugin with Appinsights and log analytics was working well for sometime,
since 2 weeks it suddenly stopped getting the data

Errors:
"parsing time "pageView" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "pageView" as "2006""

Cannot read property 'data' of undefined
"parsing time "RD001234567890" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "RD001234567890" as "2006""

**What you expected to happen**:
Kusto queries should get data from log analytics and applicationinsights

**How to reproduce it (as minimally and precisely as possible)**:
Use toggle text edit mode and fill in kusto query

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: Azure used in grafana core
- OS Grafana is installed on: unknown hosted at Aiven
- User OS & Browser: Windows 10, chrome, firefox, edge
- Grafana plugins:
- Others:

**Comment by peterholmberg** [comment]
Hello,
please use the bug issue template to describe your issue.

**Comment by Abster79** [comment]
Done, hope this is sufficient

**Comment by kylebrandt** [comment]
The 7.1 release has a new implementation for the two Analytics services.

The error to me I can think of two likely things from that error:

 1. Grafana is getting confused somehow about the Time column, and getting a non-date data as timestamps - e.g. 
 `RD001234567890`
 2. Somehow your data has changed, and the time column some how doesn't have valid time information?

Since so much has changed around this for 7.1 I'm going to close the issue hoping it is fixed in 7.1. If is _not_ fixed in 7.1, please reopen the issue, and if possible maybe show the query and resulting data in the Azure portal.
