### ISSUE TITLE
gf_install_plugins causes stack overflow

### ISSUE THREAD

**Issue by snypez** [grafana/grafana#25374]
**What happened**:
Process crashed with :
runtime: goroutine stack exceeds 1000000000-byte limit
fatal error: stack overflow

**What you expected to happen**:
download to eventually error or throw syntax error
**How to reproduce it (as minimally and precisely as possible)**:
Run the container with the following environment var. I was running in ECS.
gf_install_plugins="goshposh-metaqueries-datasource, natel-influx-admin-panel, grafana-clock-panel, grafana-piechart-panel, grafana-azure-monitor-datasource, digrich-bubblechart-panel, petrslavotinek-carpetplot-panel, mtanda-histogram-panel, grafana-worldmap-panel , citilogics-geoloop-panel, natel-plotly-panel, praj-ams-datasource, vonage-status-panel, jdbranham-diagram-panel, grafana-piechart-panel, alexanderzobnin-zabbix-app, michaeldmoore-multistat-panel, agenty-flowcharting-panel, raintank-worldping-app, https://<validpluginurl.com>/<pluginfilename.zip>;Test Plugin Name With Spaces"
**Anything else we need to know?**:
I don't know if the spaces in the plugin name after the semicolon are significant to this bug but they were there when the bug presented. The spaces after the commas are definitely significant as everything works fine with no spaces after the commas but with whitespace in the plugin names. When spaces are present after the commas all plugins install fine until an https plugin is encountered. The stack overflow presents after thousands of 'Failed downloading. Will retry once.' messages are logged.
**Environment**:
- Grafana version:
6.7.3 & 6.7.4
- Data source type & version:
- OS Grafana is installed on:
alpine container from grafana dockerhub
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by csielee** [comment]
Hi! I also met this bug.

I found that the entry point of the container [`run.sh#L65`](https://github.com/grafana/grafana/blob/master/packaging/docker/run.sh#L65) will try to parse `$GF_INSTALL_PLUGINS` and call `grafana-cli` to install plugins.

So if contain space after the comma like your example, the URL contains space at prefix.
```
--pluginUrl " https://<validpluginurl.com>/<pluginfilename.zip>"
```
But we want the URL like below:
```
--pluginUrl "https://<validpluginurl.com>/<pluginfilename.zip>"
```

Thus the `grafana-cli` says `Failed downloading. Will retry once.`.

However, I don't know why the stack is overflow.

**Comment by wbrowne** [comment]
Thanks @snypez and @csielee for reporting this issue and providing helpful information. I can see there's two problems here, one being that we're not handling the space in the `pluginUrl` field very well/not extracting the value with spaces in mind and another relating to using a plugin name with spaces. Taking the specific example `https://<validpluginurl.com>/<pluginfilename.zip>;Test Plugin Name With Spaces`, when omitting the whitespace after the comma character, this will succeed, but will download to the folder with the first word of the plugin name IE `Test`. I have not been able to reproduce the stack overflow error - but maybe that has since been solved in recent Grafana versions.
