### ISSUE TITLE
Prefix and postfix strings for Stat panel

### ISSUE THREAD

**Issue by bbrantley** [grafana/grafana#25375]
**What would you like to be added**:

The Unit option on Stat panel does not have an option to turn off the auto-scaling.  So, for example, a measurement that ranges between 0 and 9999W gets displayed as Watt when less than 1000 and KiloWatt when above 1000.  

In order to simply display the integer at all times, in SingleStat, we just use the postfix string instead to hardcode the unit ("W").

It would be nice to have this prefix/postfix option in Stat as well.

**Why is this needed**:

Unit scaling is not always desirable.  Since it cannot be turned off, this is a nice workaround.  Also, pre/postfix is handy for other things sometimes.

**Comment by torkelo** [comment]
This can be solved using custom units with `prefix:<prefix>` or `suffix:<suffix>`

**Comment by cicciopizza** [comment]
> This can be solved using custom units with `prefix:<prefix>` or `suffix:<suffix>`

OK, 
However it is not possible to use them both at the same time ... 


I hope that in 7.1 we will have the options present in 6.3 again:

Prefix / Postfix
Font size on Prefix / Postfix
Separate Color for Prefix / Postfix / Value

**Comment by jimmybrancaccio** [comment]
`prefix:<prefix>` isn't even working for me, but I agree with @cicciopizza. The following should be added back:

* Prefix / Postfix
* Font size on Prefix / Postfix
* Separate Color for Prefix / Postfix / Value

**Comment by Ultraseamus** [comment]
It seems odd to me that this was nto accepted as a regression.

At this point it has been a long time since Grafana had Prefix and Postfix options, but the existing options really do not provide the same functionality at all.

You used to be able to assign a custom postfix to a value while having it formatted as a specific unit. Such as:

$5,999 PreTax

Or even something as simple as wanting to add "mpg" to your unit. Once you have to define a suffix, you lose the option for any other formatting, your value will be stuck as the basic "locale format". The previous example would have to be:

5999 PreTax


IMO, the new system where there are hidden keywords to unlock prefix/suffix is just not very user friendly. And it is just unusable unless your value is less than 1,000. 

I would be interested in seeing a return to when Prefix and Postfix were separate options. But at the very least, it should be possible to chain formatting options for a single value.

**Comment by torkelo** [comment]
@Ultraseamus I agree it's not ideal, but trying to balance not having too many options that clutter the UI and that are rarely used. Sometimes we make mistakes and remove options that were really heavily used and sometimes it works out with no complaints.  For separate prefix/suffix we have not had that much demand for it yet, but you can open a feature request for it in the discussions section
