### ISSUE TITLE
Why drop the graphite tsdbQuery.Queries

### ISSUE THREAD

**Issue by faceair** [grafana/grafana#25385]
I am learning the code for grafana.
I found that in [this loop](https://github.com/grafana/grafana/blob/c6829645c7f1e31590dd561b6f05bff4a679c351/pkg/tsdb/graphite/graphite.go#L53-L67), all tsdbQuery.Query is assigned to the same target. This means that some of the queries were discarded, so why do that? Is this a bug?
Similarly in the prometheus process is [the query append to a list](https://github.com/grafana/grafana/blob/26626d907371aa1d642da1f2c1699234b29daa7f/pkg/tsdb/prometheus/prometheus.go#L150-L188), which looks correct.

**Comment by bergquist** [comment]
The answer is that the code is just really bad. 

In this case, there will never be more than 1 query since it's only used by alerting. Queries for dashboards are handled by the frontend codebase. https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/datasource.ts#L65

I'm closing this issue but if you want to improve the code quality I can reopen it. pull requests are more than welcome. If you are interested in that I suggest that you start by writing tests for the current behavior and then improve the actual code itself.
