### ISSUE TITLE
Hide other lines when click on one line in graph

### ISSUE THREAD

**Issue by liyichao** [grafana/grafana#2542]
When there are many lines in graph, it may be hard to see which series a line is corresponding to. Colors are not very useful. It will be good if I click on one point, other lines excluding the line containing the point auto hide, just as I click the name below the graph.

**Comment by mmoonzhu** [comment]
I have the same request.

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
