### ISSUE TITLE
API - User's personal dashboard / org not removed when the user is deleted

### ISSUE THREAD

**Issue by mgrzybek** [grafana/grafana#2545]
When the remote API is used to delete a user, it does not delete their personal dashboard / org. The consequence is that you can no longer create it using the same email because it results in a HTTP 500.

[admin_users.go:34 AdminCreateUser()] [E] failed to create user: Erreur 1062: Duplicate entry 'user@domain.tld' for key 'UQE_org_name'.

I suggest two options:
1. deleting a user through the API deletes their personal dashboard / org
2. deleting a user through the API is only possible when the dashboard / org is no longer present

**Comment by staticmukesh** [comment]
It means that if **user** is only admin user in the organization, then it should not allow it to delete ?

**Comment by mgrzybek** [comment]
That's true but it should be possible if the user is both admin of the org and the only member of it **and** the org's name is their username / user's email.

I don't know if an org can exist without an admin. I have not read the code or tested this fact.

**Comment by bbinet** [comment]
I'm also hit by this bug.
I get the following error in the logs when trying to create a new user with the same email as a previously deleted user:
`t=2016-12-06T17:31:51+0000 lvl=eror msg="failed to create user" logger=context userId=1 orgId=2 uname=admin error="UNIQUE constraint failed: org.name"`

What would be the workaround to be able to completely delete a user, so that I can create a new user with the same email address?

**Comment by jessabe** [comment]
Hello all! As this bug is 4 years old, and no one else seems to be facing this issue, I'm going to close this. If this is still something that's happening to you; feel free to comment and we can re-open this issue.
