### ISSUE TITLE
Elasticsearch alerts do not respect minimum interval

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#25528]
**What happened**:

Alerts defined on an Elasticsearch data source do not respect min interval defined in Query Option.

**What you expected to happen**:

When query options are defined, I expect identical behaviour between display panel and alerts. Using a too small interval lead to false positive / negative or just tracking a bogus metrics.

**How to reproduce it (as minimally and precisely as possible)**:

Let's graph the number of events over a 1h period with min interval = 1m.

![image](https://user-images.githubusercontent.com/1764725/84357927-acd90700-abc6-11ea-990a-059b8327df62.png)

We have between 40000 and 50000 events per minute. 

Now, I want to alert when number of events over a minute drops bellow 30000.

![image](https://user-images.githubusercontent.com/1764725/84358175-0a6d5380-abc7-11ea-9205-ebc1506a1371.png)

Unexpectedly, this rule is firing

![image](https://user-images.githubusercontent.com/1764725/84358244-27a22200-abc7-11ea-99e7-457d8b4422d5.png)

97 is much lower than expected (40 to 50k). Let's inspect the query result:

![image](https://user-images.githubusercontent.com/1764725/84358367-54eed000-abc7-11ea-9676-0ffaa7a4d871.png)

1591860099500 - 1591860100000 = -500ms. Time bucket is 500ms and does not respect minimum time interval defined in query options.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Debian Linux
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by douglyuckling** [comment]
Another effect of this bug is that we end up with way more buckets than necessary, and in my case that's causing Elasticsearch to refuse the query due to it requiring too many buckets.

I simply want to alert if a count's max value has been above 0 in the past 5 minutes. I have my min interval set to 1m, which would work great, but the alert query is ignoring that and for some reason choosing an interval of 200ms. That means 1500 buckets, which is over Elasticsearch's limit of 1000 buckets. I assume I could configure a higher bucket limit in Elasticsearch, but 1500 buckets is absurd when in theory I just need 1.

As a workaround, I can set an explicit interval of 1m on the query, but that really limits the usability of the graph: I can't view a time range bigger than 1000 minutes (~16h).

For now, I think my solution is going to be to use two copies of the query: one with an auto interval for the graph and a second hidden one with an explicit interval to be used by the alert. But it's really not great.

**Comment by douglyuckling** [comment]
It's also worth noting that the related "Max data points" option also seems to be ignored, and I'd consider that to be part of the same bug. (It actually looks like none of the settings in the Query options affect the alert queries.)

**Comment by marefr** [comment]
Should be fixed by #30049 and included in Grafana v7.4.0 and forward.
