### ISSUE TITLE
multiple values template variable not working with influxdb

### ISSUE THREAD

**Issue by adejoux** [grafana/grafana#2555]
Hello,

Templating is working well for influxdb when selecting only one value in the template variable but it's not working for me when selecting multpiple values.

An example query generated by grafana(I added foo in it to have a error and see the generated query) : 
![image](https://cloud.githubusercontent.com/assets/741174/9358411/280feace-468c-11e5-80b7-31b062e3bce3.png)

But with multiple values it's not working :

![image](https://cloud.githubusercontent.com/assets/741174/9358432/51a79dc8-468c-11e5-9f83-c144b2de56ae.png)

This query is using this regexp : /{vios1,vios2}/ but it doesn't retrieve any data in InfluxDB :

![image](https://cloud.githubusercontent.com/assets/741174/9358466/8b450c0a-468c-11e5-9450-e7cb00ea74c1.png)

It seems this syntax is not supported by Golang regular expressions which are used by InfluxDB :

![image](https://cloud.githubusercontent.com/assets/741174/9358505/c88e4630-468c-11e5-93c2-fbc8fec8b3c7.png)

![image](https://cloud.githubusercontent.com/assets/741174/9358539/f07b75b4-468c-11e5-8d30-b9a97591e040.png)

This regular expression would work :

![image](https://cloud.githubusercontent.com/assets/741174/9358601/3a36433c-468d-11e5-9879-96ab7b000084.png)

Thanks,

Alain

**Comment by torkelo** [comment]
that is not a valid influxdb query, you need to use =~ operator for regex values

**Comment by torkelo** [comment]
so when you specify the query using the Grafana editor you can enter `/$myvar/` and grafana will switch to the =~ operator. 

In 2.1.1 the variable suggestions should do this automatically

**Comment by adejoux** [comment]
I should have shown you the screenshots with grafana query editor first.

It's doing it but the query is not working :

![image](https://cloud.githubusercontent.com/assets/741174/9358795/304e61c8-468e-11e5-8dfa-df540e5aeaca.png)

It's working like that :

![image](https://cloud.githubusercontent.com/assets/741174/9358821/4986f826-468e-11e5-9d22-09b5595bedf3.png)

**Comment by adejoux** [comment]
And working with template variable if only one value is used :
![image](https://cloud.githubusercontent.com/assets/741174/9358887/a2639896-468e-11e5-8fc1-faaa99e3b0e3.png)

**Comment by jazzygeoff** [comment]
Hi, Yes, I seem to be having the same problem getting multiple values back from InfluxDB 0.9 using the grafana templating.
If I insert my data into influx using the old style tag.key.tag.key.value, then the templating works great using regex wilcards, and I see many lines on my graph. However, if I store a simple measurement/value and use tags instead (as we are supposed to in 0.9), then when I come to try to make a chart I only get data if I choose a single value, and if my regex captures multiple values then I get "No Datapoints".
The templating seems to be bringing back the correct values in the "Preview of values" pane when setting it up.
Not working - Multiple values selected:-
![image](https://cloud.githubusercontent.com/assets/1252335/9654792/db20649c-5224-11e5-9e8c-00549771686f.png)

Working (but only because I chose a single value from the dropdowns)
![image](https://cloud.githubusercontent.com/assets/1252335/9654817/0e9e0e78-5225-11e5-8a81-5617e61a154f.png)

**Comment by torkelo** [comment]
what does you influxdb queries look like ?

**Comment by jazzygeoff** [comment]
Hi, I re-created the above, and now I am seeing a line when selecting "all" for both my variables (I have 8 series in total), but it is a single line (a mean of all the series I suspect), rather than a line for each of the 8 series being selected by All/All. 

![image](https://cloud.githubusercontent.com/assets/1252335/9668654/b6533616-527a-11e5-8e32-fffc5d3f96f6.png)

The query is:-
SELECT mean(value) FROM "eva_cpu" WHERE "eva" =~ /$eva/ AND "controller" =~ /$controller/ AND $timeFilter GROUP BY time($interval)

Should I be using "regex wildcard" for my "All selection"? You can also see that the legend name is ".\*..\*", which I had expected to have been replaced with 8 seperate lines of the format $eva.$controller.

As I said before, if I insert my data into Influx using key.tag.key.tag.value, and then use regex in the query, then I do get the lovely seperate lines on the chart. (Although the legend alias naming still shows ".\*..\*" when All/All is selected.
In that instance where it works my query looks like:-
SELECT mean(value) FROM /eva.$eva.eva_cpu.controller.$controller/ WHERE $timeFilter GROUP BY time($interval)
And I get the following chart:- (I have removed the alias pattern in this image so that the legend is more useful rather than ".\*..\*")
![image](https://cloud.githubusercontent.com/assets/1252335/9669251/c7810f6e-527d-11e5-8fa3-2c3bd1f95be4.png)


Could it be a grouping issue in my query?

Thanks for your time on this mate - I find Grafana extremely useful - we are getting visualisation of data that we have never had before!

**Comment by adejoux** [comment]
Hello,

It's working for me now :

![image](https://cloud.githubusercontent.com/assets/741174/9669480/c638a68a-5287-11e5-8ac8-8dd0e4db5875.png)

You need to enable regex values in templating : 

![image](https://cloud.githubusercontent.com/assets/741174/9669512/0318a5d2-5288-11e5-9ed5-b714d18ec6ed.png)


And you need to group by tag variable names in your query : 

![image](https://cloud.githubusercontent.com/assets/741174/9669546/3ec0d17c-5288-11e5-9751-a823c32b929a.png)

So here you are only missing the grouping I would say.

**Comment by jazzygeoff** [comment]
Thankyou so much! You were right - just the grouping by my tag values that I was missing. And with the alias pattern set to $tag_\<variable\> I now have the perfect legend to go with it. 
![image](https://cloud.githubusercontent.com/assets/1252335/9672013/fdbfd446-528e-11e5-9008-0f49ef5c6234.png)
Thanks again for taking the time to respond! I appreciate it.

**Comment by andres-lorenzatti-olx** [comment]
Hello,
I´m sure this is not the right thread and appreciate you someone can point me in the right direction.
I just upgraded grafana from version 2.5.0 to 3.0.4.
Everything worked fine except regex string for templates, we used to add just a string and this stopped from working. The fix was adding "/" at the begin and the end of the string, but it was certainly painful to edit quite a lot of dashboards.
Thanks
