### ISSUE TITLE
granfan 7.0.3 in Graph Compare plugin panel display number not timestamp

### ISSUE THREAD

**Issue by wuguanyu** [grafana/grafana#25559]
**What happened**:
   in Graph Compare panel plugin display timestamp
**What you expected to happen**:
     in Graph Compare plugin panel display number
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
    7.0.3
- Data source type & version:
   influxdb
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
 Graph Compare panel 
- Others:

**Comment by wuguanyu** [comment]
![Uploading image.png…]()

**Comment by wuguanyu** [comment]
![image](https://user-images.githubusercontent.com/24486917/84469374-7d53f880-acb3-11ea-9dc9-57d012f2d6dc.png)

**Comment by sakjur** [comment]
It seems like the authors of the [Graph Compare panel](https://github.com/AutohomeCorp/graph-compare-panel) have abandoned development of the panel in favor of their [Compare Queries Datasource](https://github.com/AutohomeCorp/autohome-compareQueries-datasource). I'd recommend checking out if that would work for you.

Since this is a problem with a third-party plugin that we cannot act on, I'll close this issue 🙂
