### ISSUE TITLE
Replay controls

### ISSUE THREAD

**Issue by coussej** [grafana/grafana#25596]
**What would you like to be added**:
We recently wrote a hacky script to allow 'replay' of data on dashboards: https://github.com/factrylabs/grafana-replay-controls

Would you be open to a pull request where we add this functionality (properly implemented of course) to Grafana itself, as an option to enable it in the dashboard settings? 

**Why is this needed**:
In lots of use cases, it is useful to replay a scenario from the past. Our clients use it to see what happened in a process diagram
<img width="887" alt="image" src="https://user-images.githubusercontent.com/9944663/84641092-dfeb0580-aefa-11ea-8ac2-251258fa94e5.png">

**Comment by torkelo** [comment]
think this is better handled via a plugin 

Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.

**Comment by henjoe** [comment]
Hoping we can imbedded  this in grafana time range control. A lot of use cases specially for root-cause analysis.
