### ISSUE TITLE
Tooltip for "Auto Option" is wrong

### ISSUE THREAD

**Issue by Eraac** [grafana/grafana#25597]
**What happened**: 
The tooltip for "Auto option" is wrong into variables section (for type interval)

**What you expected to happen**:
A good tooltip

**How to reproduce it (as minimally and precisely as possible)**:
1. create a dasboard
2. add a variable (type Interval)
3. look the tooltip for "Auto option"

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/5497623/84644087-f6935b80-aefe-11ea-8192-b77d40fcdf57.png)

I guess the text is [here](https://github.com/grafana/grafana/blob/master/public/app/features/variables/interval/IntervalVariableEditor.tsx#L76), I can make the PR but I've no idea which text will be good for this

**Environment**:
- Grafana version: 7.0.3
- User OS & Browser: Chrome 83

**Comment by sakjur** [comment]
🤔 That's a good question. @oddlittlebird Do you have a suggestion for a better tooltip? Not sure if you're aware of the option (this was the first time I stumbled into it), it seems to add an option for taking the time range and dividing it by a number to get `n` intervals automatically.

**Comment by oddlittlebird** [comment]
@daniellee , are we understanding this feature correctly?
@sarlinska , FYI

The biggest problem is that "Values" is the wrong field name if what you are saying about how this feature works. The field name should be `Number of intervals` or something similar.

Tooltip: Divide the time range into a number of intervals.

What is the use case for this variable?

**Comment by sakjur** [comment]
Just to clarify, "Auto Option" adds one more option (**auto**) which is programmatically defined rather than static to the "Values" list, the options for that are shown to the right of that button in the screenshot 👇 .

<img width="1063" alt="Screen Shot 2020-06-15 at 17 52 32" src="https://user-images.githubusercontent.com/298945/84679012-0af04c00-af31-11ea-8202-d11cbe1efb97.png">

The use-case for the variable type is briefly explained under interval in
https://grafana.com/docs/grafana/latest/variables/templates-and-variables/#variable-types
