### ISSUE TITLE
Grafana alerting error. "error:"tsdb.HandleRequest() error Request failed status: 502 notresolvable""

### ISSUE THREAD

**Issue by gurupalakuru** [grafana/grafana#25611]
**What happened**: Trying to create alerts for my dashboard panels

**What you expected to happen**: I expected it work but when I click test rule above error pops up

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: Prod
- Grafana version: 5.2.2
- Data source type & version: Graphite & 0.9.15
- OS Grafana is installed on: CentOS Linux release 7.2.1511
- User OS & Browser: MacOS 10.13.6 & Chrome Version 83.0.4103.97
- Grafana plugins:
- Others:

Datasource access is added as browser

**Comment by sakjur** [comment]
Grafana 5.2.2 is no longer supported, please test with a recent version of Grafana (7.0.3 or possibly 6.7.4) and see if your problem persists.

From the error message it sounds like the problem is that Grafana cannot resolve the path that your browser can (alerting always runs from the server), you should debug your DNS to verify if the server can reach the datasource.
