### ISSUE TITLE
Jaeger datasource always proxies, event when Access: Browser is selected

### ISSUE THREAD

**Issue by timpalpant** [grafana/grafana#25699]
**What happened**: Jaeger requests are made through Grafana proxy mode, even when the datasource is configured to make requests directly from the Browser:

![browser-mode](https://user-images.githubusercontent.com/814226/85034258-e4f4c280-b14f-11ea-9476-29e64cbb1f94.png)
![request](https://user-images.githubusercontent.com/814226/85034386-0c4b8f80-b150-11ea-9700-b791675034f9.png)

Appears to be the result of: https://github.com/grafana/grafana/blob/5211a23f8d921714d839898a8e503ef8987d0773/public/app/plugins/datasource/jaeger/datasource.ts#L92
**What you expected to happen**: Requests were made to the backend from the Browser directly

**How to reproduce it (as minimally and precisely as possible)**: Configure a Jaeger datasource with Access: Browser. Open Explore mode and see that requests are made to the proxy.

**Anything else we need to know?**: If the Grafana backend does not itself have access to the datasource URL then this prevents use of the Jaeger datasource plugin.

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Jaeger
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: macOS 10.15.5, Safari 13.1.1
- Grafana plugins:
- Others:

**Comment by davkal** [comment]
Browser access was never meant to be there. Sorry for this.

**Comment by zoltanbedi** [comment]
Hi @timpalpant,
As @davkal said we are moving away from supporting the Browser access option. I'd like to understand your use case better. Can you please explain me when and why would you use this option?

**Comment by timpalpant** [comment]
We run all of our datasources on separate domains accessed directly from the Browser. This allows us to integrate datasources that may be on a separate network from the Grafana backend.

This allows running Grafana in a separate/isolated environment to reduce the risk of correlated failure. When monitoring the service, it also allows us to easily distinguish metrics about Grafana backend availability/latency from those of the datasources (although arguably this could instead be done through route matching).

**Comment by timpalpant** [comment]
> Hi @timpalpant,
> As @davkal said we are moving away from supporting the Browser access option.

@zoltanbedi could you explain the motivation? Is it specific to Jaeger datasource (e.g. to be able to switch to gRPC interface) or general direction for all built in datasources?

**Comment by aocenas** [comment]
@timpalpant This is a general direction we are taking with all datasource (especially new ones) mainly because of alerting and maintenance costs.

For alerting to work the data source has to have the querying logic implemented in the backend (usually Go) so it can be executed on the server. If we wanted to also support browser access we need to have the same logic also implemented on the front end in javascript. You can see such implementation with Elastic data source and this created a lots of issues and additional work for us.

This is why we decided not to allow browser access in new data sources and having the option in Jaeger config was a mistake. Even though specifically with Jaeger we may not need backend implementation for alerting there are also other considerations when moving the code to backend could be preferable and by having the browser access we are blocking such move and so it is easier to not support it from the start than to take it away later on.

So I understand there are benefits in having the browser access for some users, I assume it is possible to work around any issues from their end, while it makes it easier for us to provide other valuable features.

**Comment by timpalpant** [comment]
I see, thanks @aocenas for explaining. It's helpful to understand the general direction to be able to plan appropriately.

**Comment by aocenas** [comment]
@timpalpant sorry for not explaining this before the PR. In any case I will keep this open for reference to remove the browser access from the config.
