### ISSUE TITLE
Alerts are not working with 7.0.3

### ISSUE THREAD

**Issue by gowrisankar22** [grafana/grafana#25709]
What happened:
we upgraded from 6.5.2 to 7.0.3. After upgrade alerts are broken. Even though metrics are below the threshold it says alerts. More details 

**7.0.3**
<img width="1110" alt="Screenshot 2020-06-19 at 12 51 47" src="https://user-images.githubusercontent.com/20590107/85108112-c284a700-b22c-11ea-8e12-41da6a2d1d7a.png">

**6.5.2**
<img width="1123" alt="Screenshot 2020-06-19 at 13 10 58" src="https://user-images.githubusercontent.com/20590107/85109122-7470a300-b22e-11ea-89cc-eca2ff3b486b.png">

Testing the rule says state ok:
```
Object
firing:false
state:"ok"
conditionEvals:"false = false"
timeMs:"181.140ms"
logs:Array[4]
0:Object
message:"Condition[0]: Query"
data:Object
1:Object
message:"Condition[0]: Query Result"
data:Object
2:Object
message:"Condition[0]: Eval: false, Metric: xxx, Value: 0.011"
data:null
3:Object
message:"Condition[0]: Eval: false, Metric: xxx, Value: 0.018"
data:null
```

Environment:

Grafana version: 7.0.3
Data source type & version: Prometheus and stack driver
OS Grafana is installed on: Linux
User OS & Browser: Win 10, Firefox
Grafana plugins: none
Opinions to resolve:

**Comment by kali-brandwatch** [comment]
We had a similar issue. It turned out to be related to removed alert notification channels. I am opening a detailed bug report for it since I could not find anybody else flagging it.
In short: on 6.x grafana, when a dashboard had a notification alert configured to use a channel that has got removed, grafana would silently ignore it and not send any alerts through that one but still proceed with the others.
After upgrade to 7.x, grafana has introduced a notification to state something like:
```Unable to translate notification id to uid, Alert notification [ Id: 3, OrgId: 1 ] not found```
If your case is the same you will be able to find these entries in the grafana.log.
What happed there is that the dashboard got defined alerts to be sent to some channel. The channel got eventually removed in the alert notification channels configuration page.
As a side effect, you might also experience the same error when you try to make changes to the dashboard, where you will see the same error as above (as the alert is also included in the json `data` for the dasboard json model).
Seems like after introducing the notice about the translation from id to uid, there was some sort of break introduced in the code that prevented alert notifications to be processed any further, and dashboard changes to be made.
To make it more confusing, the alert notification channel cannot be seen in the UI, so you need to dive into the underlying database to see this settings, precisely because the notification id is not found, so it doesn't get displayed (yet it is kept in the json when you try to save changes)
@gowrisankar22 please check if this is your case as well. I will open a bug report now.

**Comment by aknuds1** [comment]
Please update the issue description to follow our standard bug template.

**Comment by marefr** [comment]
@gowrisankar22 please include alert rule definition and query(s) and debug logs if possible. Any difference pausing/unpausing the alert rule?

**Comment by kali-brandwatch** [comment]
I have created a detailed bug report under https://github.com/grafana/grafana/issues/25970

**Comment by aknuds1** [comment]
@kali-brandwatch Is that a different bug from what's reported here or should the two issues be combined?

**Comment by kali-brandwatch** [comment]
@aknuds1 I can't confirm they are the same. I suspect they are, but we'll need the OP to confirm

**Comment by aknuds1** [comment]
@kali-brandwatch OK thanks; I also think we need more detail from the OP in order to tell.

**Comment by kali-brandwatch** [comment]
@gowrisankar22 upgrade to 7.0.5 solved my issue, I believe you're experiencing the same.

**Comment by marefr** [comment]
Closing this for now. Let us know if it still doesn't work for you and we consider reopen this.

**Comment by gowrisankar22** [comment]
Thanks. I will update and comment on the ticket.
