### ISSUE TITLE
Template variable from MySQL query shows value instead of key when selected from multi-value dropdown

### ISSUE THREAD

**Issue by Berbe** [grafana/grafana#25711]
**What happened**:
Template variable selection shows value instead of key for *multi-value* selections

**What you expected to happen**:
Template variable to show key of selected entries

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a [template variable using a MySQL source](https://grafana.com/docs/grafana/latest/features/datasources/mysql/#query-variable)
2. Make the template variable *multi-value*

**Anything else we need to know?**:
- The `All` option does not need to be used
- Display is correct (key shown) when *single-value* mode is used for the template variable

**Environment**:
- Grafana version: v7.0.3
- Data source type & version: MySQL
- OS Grafana is installed on: GNU/Linux (Debian)
- User OS & Browser: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by sakjur** [comment]
Just to check with you: For me the key is shown in the expanded dropdown, but when I select one or more options, the value is shown in the listing on `option + option + option`.
![Screen Recording 2020-06-22 at 09 07 28 2020-06-22 09_08_27](https://user-images.githubusercontent.com/298945/85258546-f5ff4580-b467-11ea-9979-a399975efb58.gif)

**Comment by Berbe** [comment]
> Just to check with you: For me the key is shown in the expanded dropdown, but when I select one or more options, the value is shown in the listing on `option + option + option`.

Absolutely

**Comment by csanz91** [comment]
I'm also facing the same issue. In my case im using the json datasource plugin, where I also have key/values combinations.
In the code I can see two places where it joins the texts array into a string.
The first place where it does the array join is here: https://github.com/grafana/grafana/blob/78996516af1969f40b99f62b09ee6fb98d59d90f/public/app/features/variables/pickers/OptionsPicker/actions.ts#L184-L188

However, in this other part of the code, it checks if current.text is an array, which is not because we already joined the array before into a string. Then it uses the value array, which produces the problem exposed in this issue.
https://github.com/grafana/grafana/blob/78996516af1969f40b99f62b09ee6fb98d59d90f/public/app/features/variables/state/sharedReducer.ts#L127-L131

**Comment by Berbe** [comment]
Nice find!
Would it mean returning
```
text: texts
```
, if it has no side-effects, would be a solution?

**Comment by michalochman** [comment]
On top of that, the dropdown shows key correctly after refreshing the page with variables selected.

Control directly after selecting choices:
![image](https://user-images.githubusercontent.com/1628450/85534683-d572ef00-b611-11ea-85dd-45e08c703157.png)

The same control after refreshing the page:
![image](https://user-images.githubusercontent.com/1628450/85534778-e58ace80-b611-11ea-95ec-fe8a85583c44.png)

**Comment by Slach** [comment]
also, there is https://github.com/grafana/grafana/commit/13787294c6b3bbf7e7d797c3048758e13ee6443e?fbclid=IwAR3RV2hVvR2_vnEq5VrBbUGrFOjKt0B5NjsFhHBVurX-M3_JThA9LBdEzxw#r40292778
UI state skip options with .value which `!IsString()`

**Comment by barts2108** [comment]
I can confirm I have the same issue in Grafana v7.1.0 (8101355285) using builtin `mssql` datasource
