### ISSUE TITLE
Email Grafana table result (raw data) in csv through Jenkins Pipeline

### ISSUE THREAD

**Issue by shrutiseth** [grafana/grafana#25718]
**What would you like to be added**: Feature where in I can post an API request (With my grafana url, credentials, from and to dates/time, csv format) to email grafana table result raw data using Jenkins Pipeline. 

**Why is this needed**: While implementing continuous performance testing in DevOps, we plan to have load test results raw data in our email. Currently we have to manually goto dashboard and export/download table data in csv and then send an email. With this automated feature, we can achieve DevOps framework.

**Comment by torkelo** [comment]
sound like you want the Enterpris reporting feature. https://grafana.com/docs/grafana/latest/enterprise/reporting/  or the export as PDF https://grafana.com/docs/grafana/latest/enterprise/export-pdf/ 

Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
