### ISSUE TITLE
Graph visualisation of multiple CloudWatch time series not working

### ISSUE THREAD

**Issue by LloydW93** [grafana/grafana#25721]
**What happened**:
Multiple time series not displayed from CloudWatch query.

**What you expected to happen**:
Able to view multiple time series by grouping by two fields with an aggregation function

**How to reproduce it (as minimally and precisely as possible)**:
1. Clean install latest grafana via docker: `docker run -d --name=grafana -p 3000:3000 grafana/grafana:master` (side note: the commands at https://grafana.com/grafana/download/7.1.0-1b554b4dpre?platform=docker are incorrect)
2. Login and change password at localhost:3000
3. Add a CloudWatch data source (via access/secret key for this example)
4. Create an AWS Elemental MediaStore container and set up logging configuration as per https://docs.aws.amazon.com/mediastore/latest/ug/monitoring-cloudwatch-logs.html
5. Make some GET requests to this container, with varying response codes
6. Create a new dashboard/panel in Grafana, selecting the CloudWatch datasource and the CloudWatch Logs query mode
7. Select the log group for your MediaStore container
8. Run the following query:
```
filter Operation="GetObject"
| count() by bin(5m), HTTPStatus
```
9. Observe in the Table Visualisation that you have HTTPStatus and count columns for each time bin as expected
10. Observe that in the Graph visualiation there are only two time series: "HTTPStatus" and "count()"

**Anything else we need to know?**:
This fault was first observed in v7.0.3. We've been advised by the relevant AWS product team that this behaviour is not expected, and have seen a sample query run by them have the expected result of a time series for each of the other fields in the group by result.

**Environment**:
- Grafana version: master/7.0.3
- Data source type & version: CloudWatch
- OS Grafana is installed on: Docker/WSL2
- User OS & Browser: Windows/Firefox
- Grafana plugins: Builtins
- Others:

**Comment by torkelo** [comment]
Can you show the raw data (in table panel)

**Comment by LloydW93** [comment]
Table panel below:

![Annotation 2020-06-20 105829](https://user-images.githubusercontent.com/2572695/85199109-0aff9b80-b2e5-11ea-8f77-4b2a7dea0a0a.png)

**Comment by aocenas** [comment]
@LloydW93 From testing this it seems to be an issue of the query sort of. I think it is missing a `stats` keyword and so it should be
```
filter Operation="GetObject" | stats count() by bin(5m), HTTPStatus
```
Interestingly, without the `stats` keyword this does not seem to throw any validation errors not sure this is expected cause I did not find anything in the docs that would suggest you can omit it.

Because of that either cloudwatch returns something different but also we have some internal code that checks if query is a stats query which relies on the `stats` keyword.

In any case please check the data with the fixed query and let me know if that returns expected results.

**Comment by LloydW93** [comment]
I've tried adding the additional `stats` keyword, but this doesn't seem to have changed the result:

![Annotation 2020-07-09 182010](https://user-images.githubusercontent.com/2572695/87070682-102f7680-c211-11ea-9ec0-25a5bafe4a7d.png)
![Annotation 2020-07-09 182025](https://user-images.githubusercontent.com/2572695/87070691-11f93a00-c211-11ea-92fd-724c88f3eceb.png)

To check it wasn't a newline issue, I tried removing that as well, but this didn't help. I'm using PutObject instead of GetObject this time around, but I would be surprised if this is the deciding difference.

This was again with nightly so was `Grafana v7.1.0-0052dde8pre (3b383149db)` this time.

**Comment by aocenas** [comment]
Ah ok I think I know what is going on. Seems like there is only HTTPStatus=200 in the dataset, so it would make sense to show only one line in the graph with the count() as there are not multiple groups. The issues is that the HTTPStatus column is interpreted as a numeric value and is plotted as separate series instead of label.
