### ISSUE TITLE
[2.1.2] Postgres Case Sensitivity Regression

### ISSUE THREAD

**Issue by Jhors2** [grafana/grafana#2573]
It appears that the dashboard search field has regressed back to 2.1.0 status in the 2.1.2 build.  Searches for dashboards are again case sensitive.

**Comment by torkelo** [comment]
ah, I screwed up, somehow that commit is not in the 2.1.x branch (the 2.1.1 release was done from master as no big new feature / change had been merged in yet).   

I am not going to publish a new 2.1.3 patch release only for this, so please use a 2.2 pre release build if you really want this fix, http://grafana.org/download/builds.html

Sorry :(

**Comment by jsternberg** [comment]
Somehow a 2.1.3 release was created, yet this change still never made it into 2.1.3. If there's a 2.1.4, can this be included in it?

Is there a timeline for the new version that will have this fix? We prefer to use the officially supported debian package if possible rather than custom build our own packages.
