### ISSUE TITLE
Query editor missing from edit view (7.0.3)

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [grafana/grafana#25766]
**What happened**:
opened graph in editor mode, no bottom panel with edit options
**What you expected to happen**:
there should be a query editor present
**How to reproduce it (as minimally and precisely as possible)**:
select any graph, right click and select edit.
**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3
- Data source type & version:
influxdb
- OS Grafana is installed on:
Ubuntu 16.04 
- User OS & Browser:
windows 10, Version 83.0.4103.106 (Official Build) (64-bit)
- Grafana plugins:
- Others:

![grafana_edit](https://user-images.githubusercontent.com/22965146/85399143-5358cc80-b524-11ea-9805-f7b59dc07f12.png)

**Comment by marefr** [comment]
That looks weird. Not able to reproduce. If you open console tab in chrome developer tools can you see any errors logged there? 

Possible that you managed to resize the query editor to be positioned at the very bottom? If you open Application tab in chrome developer tools and inspect local storage, what's your value of `grafana.dashboard.editor.ui`? Here's mine for reference:
![image](https://user-images.githubusercontent.com/1668778/85401934-1eb43780-b55b-11ea-84d9-8bc7cd465a83.png)

Clearing local storage is a way to reset editor positions/settings to default.

Can you try and switch to `Fill` instead of `Fit`?   One other thing to try would be to zoom out browser until query editor is visible and resize the drawer.

**Comment by jgrammen-agilitypr** [comment]
Here is the console tab, and there are errors:
![image](https://user-images.githubusercontent.com/22965146/85402523-d3356580-b529-11ea-9c1a-26fb7b7f97ce.png)

changing fill and fit have no impact. clearing the local storage had no impact.
but your suggestion to zoom out, did revel the panel hiding below. as you can see in the gif below:

![grafana_missing_editor](https://user-images.githubusercontent.com/22965146/85405279-2a3d3980-b52e-11ea-9831-c9bab8894ce9.gif)

**Comment by marefr** [comment]
Thanks. Not sure the console errors is related. So when zoomed out and dragging the ruler up between panel and query editor. Then zooming to 100% and you still see query editor and then reload browser do you still see the query editor? Any idea how this happened?

**Comment by jgrammen-agilitypr** [comment]
ok, you may close this ticket
you are correct that the panel divider just moved/got dragged
I do not know exactly how this happened, but the issue is resolved.
I apologize for filling a ticket regarding something that is user error

**Comment by marefr** [comment]
No worries. But could always be a bug, you never now so better to be on the safe side and report it.

**Comment by timpalpant** [comment]
We don't know how this occurs but have seen two instances of it suddenly happening in our internal Grafana instance as well.
