### ISSUE TITLE
keep a selection when toggling to text mode and back

### ISSUE THREAD

**Issue by rdxmb** [grafana/grafana#25799]
I'd like grafana to keep my current selection when toggling from text mode to dropdown-mode and back.

Actually it looks like this:

![grafana_edit](https://user-images.githubusercontent.com/30314040/85534357-92b11700-b611-11ea-82a9-47b2654c013c.gif)

**Comment by torkelo** [comment]
Hi! 

I do not think this will be feasible / something we will work on, maybe if there is a PR and demand 

Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
