### ISSUE TITLE
Individual bar colors based on data point and threshold value

### ISSUE THREAD

**Issue by alouiseq** [grafana/grafana#2583]
Does Grafana currently support individual bar colors on the graph based on its data point against a threshold value. (e.g. if data point is over 70% of the threshold, then change color to red)? 

If not, are there any plans to implement something like this?

**Comment by discoduck2x** [comment]
+1

**Comment by torkelo** [comment]
it does not support this currently. And there are no plans (as plans -> it is planned to be implemented in next release or two). But it would be nice to have if it could be implemented without adding too much complexity.

**Comment by scrumpresident** [comment]
+1

**Comment by wanderanimrod** [comment]
@torkelo , thanks for the work on Grafana. Did anything come of this? If not, is there a technical reason we cannot do this? I want to investigate possible ways of adding this functionality but I don't want to waste time if a maintainer or contributor has already established that it is not reasonable. 

Thanks

**Comment by VanKurt** [comment]
+1

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.

**Comment by prashanth-sams** [comment]
Most beneficial feature if implemented

**Comment by ablecable** [comment]
+1

**Comment by luuuuuh** [comment]
+1

**Comment by torkelo** [comment]
use the bar gauge panel ?
