### ISSUE TITLE
Elasticsearch: Support logs context 

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#25878]
**What would you like to be added**:
Some mechanism that allows to show neighbouring entries.
Similar to Kibana's https://github.com/elastic/kibana/issues/40808

**Why is this needed**:
Consider filtering error entries and you want to investigate an error log entry.
During investigation you want to find the context that lead to that error. 
This means viewing previous log entries that have lower log level than the log error entry (diferent query filter).

**Comment by torkelo** [comment]
This is implemented for cloudwatch & Loki currently. 

I assume your using Elasticsearch?

**Comment by torkelo** [comment]
data source needs to implement getLogRowContext  https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/loki/datasource.ts#L375

**Comment by cdalexndr** [comment]
Yes, I'm using Elasticsearch 7.8.0

**Comment by simianhacker** [comment]
I started looking into this issue... At first glance it looks pretty easy but as I dug in I realized the arguments passed to `getLogRowContext` are not sufficient for the Elasticsearch datasource; the critical missing piece is the start/end time from the time picker. This is used to calculate the indices (for the Elasticsearch datasource)  via `this.indexPattern.getIndexList(timeFrom, timeTo)`. We would also want to use this in a `range` query to ensure the ES query isn't too wide. We can't just rely on `size` since it will pull back more data than you would expect and cause performance issues. 

@torkelo @Elfo404 I noticed on the DataFrame object, there is a `meta` key (`QueryResultMeta`) that has a `custom` key that appears to be a `Record<string, any>`. Would it be appropriate to add the time range used in the original query to that object? It looks like a few different datasource (Graphite, Cloudwatch, Loki) use it to pass data around.

**Comment by simianhacker** [comment]
Quick update, I got this working without having to use the `meta.custom` key on the `DataFrame` object; I stumbled across the `this.timeServ.timerange()` method that allowed me access to the time range. I found a few rough spots that I will point out in the PR once I have it ready (probably the next day or so). Here's a screenshot of it working:

![image](https://user-images.githubusercontent.com/41702/97932429-38e1fb80-1d2d-11eb-9b35-857ed652ace3.png)
