### ISSUE TITLE
Table doesn't allow for logQL queries as written

### ISSUE THREAD

**Issue by Wnthr** [grafana/grafana#25974]
The query {host="foo"} works just fine in explore mode, but when putting it into a panel query, it automatically assumes to split up the query based on each stream, with no discernible way to avoid this behavior. In my case, I get a selector for either {host="foo",filename="/var/log/kern.log"} or {host="foo",filename="/var/log/messages"} which seems presumptive.

My assumption would be that the first query above would indeed show all log entries where host is foo, to get the second behaviour I should have to put in two queries which separates those into the selectable ones.

**Comment by torkelo** [comment]
Not sure I understand your problem can you show with screenshots? Is it a problem with the query builder adding things to your query? Or results not showing as you expect?

**Comment by ivanahuckova** [comment]
@Wnthr just to confirm, when you are in dashboard, do you select logs panel? Because the behaviour that you are mentioning is in table panel. However, if you select logs panel, you will have the same view as in Explore mode. 
![image](https://user-images.githubusercontent.com/30407135/86281089-3fc0fc00-bbdd-11ea-860a-12e8ac378500.png)

**Comment by Wnthr** [comment]
Quite right, I was using the table panel rather than the log panel. Switching to the log panel, I get the expected behavior.
