### ISSUE TITLE
Is it possible to activate, that Viewers can't create new dashboards in an organisation?

### ISSUE THREAD

**Issue by chirshan** [grafana/grafana#2602]
I've created an user (viewer role) and I just noticed that the user can create dashboards in the organisation, but i want that the user only see one specific dashboard that is already configuerd. Is this possible at the moment? or is it a feature comming in a new update?

**Comment by torkelo** [comment]
It is fixed in master / upcoming release 2.2

But please keep in mind that a user with role Viewer can still issue any metric query against the time series database. Graphite, InfluxDB or OpenTSDB (or what ever you are using) do not have per metric name / namespace security, so a Viewer with some knowledge about http can view ALL metrics even though a small number are exposed in the org's dashboards. 

So do not think Viewer role means that the user has no ability to view metrics not exposed through already created graphs.

**Comment by chirshan** [comment]
Okay, that helps alot.

I keep that in mind.
