### ISSUE TITLE
Cloudwatch: MediaConnect Dimensions don't populate with AWS Cloudwatch data source

### ISSUE THREAD

**Issue by allimacmillan** [grafana/grafana#26032]
**What happened**:

Grafana doesn't see the MediaConnect dimensions from Cloudwatch. This makes it so I cannot use dimensions in queries, which severely limits the capability of queries. I found that searching for MediaConnect dimension keys using the variable template, None is returned, as shown:

<img width="710" alt="Screen Shot 2020-07-02 at 11 56 29 AM" src="https://user-images.githubusercontent.com/14915586/86399002-60c83200-bc5b-11ea-8669-14a927d4de42.png">

**What you expected to happen**:

I expected to be able to use the MediaConnect dimensions in my grafana queries. I also expected the dimension keys to show up when searched for using a variable template, like they do under "Preview of Values" for the AWS/CloudSearch namespace:

<img width="700" alt="Screen Shot 2020-07-02 at 11 57 12 AM" src="https://user-images.githubusercontent.com/14915586/86399146-98cf7500-bc5b-11ea-879b-ca9f19372273.png">

**How to reproduce it (as minimally and precisely as possible)**:

Repeat the search that I tried in the first screenshot with a Cloudwatch data source. Also try to add any dimension to a MediaConnect query.

**Environment**:
- Grafana version: v7.0.3
- Data source type: Cloudwatch
- OS Grafana is installed on: Centos 7
- User OS & Browser: macOS & Google Chrome

**Comment by papagian** [comment]
Thank you for reporting this.
The reason is that there are [no dimensions](https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go#L183) defined for `AWS/MediaConnect`.
Unfortunately the dimensions are not listed in [the documentation](https://docs.aws.amazon.com/mediaconnect/latest/ug/monitor-with-cloudwatch.html).

Can you share the output of the following command:
`aws cloudwatch list-metrics --namespace "AWS/MediaConnect"`

**Comment by allimacmillan** [comment]
Thanks for looking into this! Here is the output from that command:
[mediaconnectmetrics.json.zip](https://github.com/grafana/grafana/files/4879579/mediaconnectmetrics.json.zip)

I replaced the arn values with empty strings.
