### ISSUE TITLE
Grafana/ui: Segment component changes bottom margin on opening 

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#26091]
Seems like segment adds and removes `gf-form` class from depending on whether it is open which makes stuff jump around because of the margins:
![Peek 2020-07-06 16-58](https://user-images.githubusercontent.com/1014802/86608014-4ae3a580-bfaa-11ea-898d-352497c62c6b.gif)

**Comment by psrebniak** [comment]
@aocenas @jackw I can still reproduce it on play.grafana.org but on master it's already fixed with commit [bb45f5fedc5afd7035a27e56d798eb86464ad33c](https://github.com/grafana/grafana/commit/bb45f5fedc5afd7035a27e56d798eb86464ad33c#diff-a961fa7386b3ddffa8ee1cf79b736e360007803f667696797ea8649161f5f05a )

**Comment by oscarkilhed** [comment]
Fixed by: #28033
