### ISSUE TITLE
Time picker options

### ISSUE THREAD

**Issue by calebcall** [grafana/grafana#2612]
It would be nice to have the options of "yesterday", "today", "this week", "last week", etc as options in the time picker.

**Comment by torkelo** [comment]
"today" option is already implemented (it has to be added to existing dashboards manually, but looking at ways to add `1w`, `yesterday`, `5am - 7pm`  options.

**Comment by torkelo** [comment]
the `today` feature is not in v2.1 it is in master and 2.2 pre release builds

**Comment by cemo** [comment]
+1

**Comment by ecables** [comment]
I'd like to also request time picker default settings be something that can be set globally, so that new dashboards inherit the global settings, and can be further customized if necessary.

As it stands, every new dashboard I create requires me to add relative time options of "3h" and "4d," in addition to a -1m offset. Having this be configurable globally would be convenient.

**Comment by torkelo** [comment]
close in favor of https://github.com/grafana/grafana/issues/2761

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/9975662/affd1e7a-5ec4-11e5-9b57-b1cd73d8ffe0.png)

**Comment by calebcall** [comment]
Very nice.  I like that a lot.
