### ISSUE TITLE
Add power (e.g. square root) scale for Y axis

### ISSUE THREAD

**Issue by stevecj** [grafana/grafana#2613]
I'm graphing the ages of pending jobs in various queues, and I'm finding that neither linear nor logarithmic representations are ideal. With the linear scale, most of the detail is flattened to the bottom, and with the logarithmic scale, most of the detail is flattened to the top.

I believe that a square-root scale might be much more appropriate for this graph.

What are the prospects for adding power choices (at least square root) to the Y axis scale options?

**Comment by Doweig** [comment]
+1

**Comment by giphahne** [comment]
totally agree, I've found a power scale graph to be very useful.

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!

**Comment by tgs** [comment]
This would be very handy for me.  The square-root increases the visibility of the low end of the scale, but doesn't blow it all out of proportion like log() does.  log() also can't deal with negative numbers, while a cube-root handles them very nicely.

**Comment by MatheusCylo** [comment]
+1
