### ISSUE TITLE
What is $WORKING_DIR/conf?

### ISSUE THREAD

**Issue by oliverjanik** [grafana/grafana#2616]
Mentioned here: http://docs.grafana.org/installation/configuration/

The documentation on config file paths could use some clarity.

Do I copy the `/etc/grafana/grafana.ini` and call it `custom.ini`? Do I then modify the init script to point to my `custom.ini` ?

Actually the reason I had to read the configuration page, is because the Installation page didn't mention default admin username and password at all.

**Comment by torkelo** [comment]
its pretty clear in the docs, or, maybe not could be improved.  :)

![image](https://cloud.githubusercontent.com/assets/10999/9545563/74711fcc-4d8b-11e5-9b4b-0a6c4d2daa2d.png)

The confusion might be caused by Grafana being able to run (and installed) in different environments and scenarios. For example using rpm and deb the custom configuration is in `/etc/grafana/grafana.ini` as specified in the docs. When you install it manually (Downloading the binary tar or building yourself), grafana will look for a defaults config file and a `custom.ini` file (with overrides), the paths for these are by default relative to the working dir, but the paths for where these files are and what name they have can be overriden by command line args (utilized by the deb and rpm init scripts)

the installation page should probably mention that :)

**Comment by oliverjanik** [comment]
I see, the `/etc/grafana/grafana.ini` is already the custom one. I thought it was the default one.
