### ISSUE TITLE
add user to multiple organizations after signup

### ISSUE THREAD

**Issue by som-kanade** [grafana/grafana#26208]
**What would you like to be added**:

1.we have 3 clusters running to have them seperated different organizations are created authentication/signup is being done google/gmail SSO 
2.when user signups using google he should be viewer access to all 1,2 organizations (mentioned)
3. grafana.ini the configuration takes 1 value as organization id 

**Why is this needed**:
1. to ease user managment 
2.when user signups using google he should get viewer access to all 1,2 organizations (mentioned)

if this is already reported/solved please point to that page/documantation 

Thanks,

**Comment by torkelo** [comment]
No this is not implemented yet. 

Thanks for reporting this feature request. I do not think this edge case is something we will likely build into Grafana. 

Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
