### ISSUE TITLE
Superimposable legends

### ISSUE THREAD

**Issue by wrouesnel** [grafana/grafana#2623]
Something nice which PromDash does but which Grafana does not do is allow legends to be superimposed over the graphs they're associated with e.g.

![image](https://cloud.githubusercontent.com/assets/772445/9570456/d9ef30d2-4fcf-11e5-97f1-75971013cbc0.png)

It would be nice if grafana graphs supported this since it saves a heck of a lot of screen realestate when setting up HUD-type displays where you need to be able to look in closer and get more details of the time series without bringing it up on a local PC.

**Comment by torkelo** [comment]
This is actually pretty easy to implement. The only thing that is problematic is that the legend already has so many display & placement options :)

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
