### ISSUE TITLE
Browser hangs with large number of series/datapoints in Explore (Table)

### ISSUE THREAD

**Issue by timpalpant** [grafana/grafana#26243]
**What happened**: The browser becomes unresponsive if a large number of series are returned in Explore mode.

**What you expected to happen**: The browser displays the series result and does not hang.

**How to reproduce it (as minimally and precisely as possible)**: Issue a query in explore mode that returns a large number of series. We are using a Legacy Data Source Plugin that returns table results in the form described here: https://grafana.com/docs/grafana/latest/developers/plugins/legacy/data-sources/#query

**Anything else we need to know?**: It seems that the table is displaying a value for every timestep now, whereas previously it displayed one per series, which may be related. Pausing script execution in Chrome dev tools shows that the code is executing here:

![stack1](https://user-images.githubusercontent.com/814226/87170862-ebceab00-c29f-11ea-9ab6-03a517a29990.png)
![stack2](https://user-images.githubusercontent.com/814226/87170912-fab55d80-c29f-11ea-83e0-f713b11ef1c3.png)

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: custom
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Safari 13.1.1 or Chrome 81
- Grafana plugins:
- Others:

**Comment by timpalpant** [comment]
Is there a way to disable the table view in Explore mode as a workaround?

**Comment by Clarity-89** [comment]
I think this is an issue with the table panel specifically and not with Explore, as it happens outside Explore as well. I had one datasource query return error as HTML page from a 3rd party api and it caused the page to become very slow with the table plugin, the graph panel didn't have this issue.

**Comment by zoltanbedi** [comment]
We have something similar issue in our backlog. Maybe they are related. #25457

**Comment by timpalpant** [comment]
I was able to mitigate this issue by updating our datasource plugin to return `{meta: {preferredVisualizationType: "graph"}}`, which prevents the timeseries data from being automatically turned into a large number of table rows (one for each time point).

**Comment by aocenas** [comment]
@timpalpant 
> whereas previously it displayed one per series

Not sure what you mean here. Some datasources return a 2 different sets of data. Loki and Prometheus return time series data that is graphed and also a result of "instant query" which returns just the latest value for each query which is shown in the table. This is done with the `preferredVisualizationType` hint on the response but otherwise default behavior is to show the all data points both in graph and table.

In general though, we are trying to merge multiple time series into single table but maybe it does not make sense to show them all anyway. We already display only 20 in the graph with option to show all (which will possibly hang the browser if there are much more) could be similar case with the table as it may not make sense to show >100s or columns at the same time anyway.

**Comment by aocenas** [comment]
cc @torkelo @dprokop the processing and merging where it hangs happens in explore code, but this seems like a general type of problem that could have some generic solution also for dashboards.

**Comment by aocenas** [comment]
Recently this whole transform to table model was removed and instead a transform on top of dataFrames is used. Not sure if that changed performance or not so needs to be checked again.

**Comment by aocenas** [comment]
Seems like this while code path is not used anymore in Explore as we use the new table panel so shouldn't be a problem in dashboards either.
