### ISSUE TITLE
Transformations: Calculation should support to select all fields (Graph Panel)

### ISSUE THREAD

**Issue by edin008** [grafana/grafana#26251]
**What would you like to be added**:
On graph panel: transform, add field from calculation, binary operation.
Operation should support picking **all fields** to perform the calculation.

**Why is this needed**:
I need to divide all metrics on graph by 10. I have over 50 uniquely named metrics. At the moment it is only possible to pick one metric at a time on which I can apply calculation.

![image](https://user-images.githubusercontent.com/66313770/87214491-57128e80-c32d-11ea-8ec8-e3b7ae5bd3f7.png)

This problem does not exist in table panel because transformation reduce is supported and I can divide all values by 10 under calculation.

![image](https://user-images.githubusercontent.com/66313770/87214971-efab0d80-c331-11ea-9b91-6c2a777eb5ac.png)

**Comment by Ultraseamus** [comment]
This is similar to a request I tried (and failed) articulating a couple weeks back: https://github.com/grafana/grafana/issues/25851

Commenting here to provide some evidence that there is interest in this. If transforms start to get used more widely, I think it will be very common to run into this problem. Wanting to apply a calculation on every metric is a simple/common use case, and it is not really possible today. Not only can you not do it with a single operation, you would have to come back in and modify the transforms every time a new field showed up (which would be extremly common if you were selecting the Top N terms in a realtime series).

The limitation actually extends to other transforms as well. The "Organize" transform for example. If you have a field/column that can change dynamically based on a template selection, "Organize" becomes useless because you only set the order of one specifically named column (and that name can change). It also means that many Transforms will fall apart if the underlying query is changed.

Making them work a bit more generically like suggested here is, I think, the only way to go forward. It is enough of a blocker for my team that I am planning on implementing a workaround in a private fork. It will not be perfect, but the solution I have in mind would be to allow the user to input a "RegEx" filter (just like they can insert a constant today) for either half of the operation. Which is essentially the path you guys took back with the old Table plugin and "Column Styles". Rather than force the user to define a style for a very specifically named column, you allowed them to apply a style to any column that matched a pattern.

Not really having that ability is a regression, IMO. And it really prevents Transforms from being as useful as they could be.

**Comment by torkelo** [comment]
Ok, it's the same as https://github.com/grafana/grafana/issues/25851
