### ISSUE TITLE
Render Image Endpoint without a browser | like The Multi Router Traffic Grapher (MRTG)

### ISSUE THREAD

**Issue by MIKNOTAURO** [grafana/grafana#26250]
**What would you like to be added**:
An endpoint to get a png image from a panel dashboard more efficient, possibly without using a browser. Something like MRTG.
And maybe could be done in parallel

**Why is this needed**:
We are trying to use grafana in a SaaS platform... but apparently is not the right use case.
We are trying to generate dynamic Dashboards; since there is no native way to embed dashboards (as far as I know) we solved our problem with the render image plugin... but is really slow (because the browser) and high resources consumption.

**Comment by aocenas** [comment]
We moved to image rendering in the headless chrome because otherwise it was hard to get a proper rendering of the dashboard and/or panels considering how much code they contain. Other solutions usually just could not reliably parse and run the code needed for the rendering. So though I see the point I think there is very little change we will move to something else at this point.

At the same time, the rendering plugin is ... well plugin so other solutions can be created and used instead.
