### ISSUE TITLE
Dashboard links: tag searches being done per panel instead of per dashboard

### ISSUE THREAD

**Issue by fyang13** [grafana/grafana#26289]
**What happened**: When a dashboard configured with dashboard links to list dashboards by tag, when dashboard being accessed/refreshed, it should really just run the search to "/api/search?tag=XYZ&limit=100" once, but it's running numerous times(one for each panel), this cause lots of requests stalled while loading a dashboard with many panels, due to Chrome's "6 connections per origin" limit.

**What you expected to happen**: The search should be run once only

**How to reproduce it (as minimally and precisely as possible)**: Create a dashboard links by tag in the dashboard with 10 panels, load the dashboard and through web inspector you will see the tag searches being run 10+ times. 

**Anything else we need to know?**:

**Environment**: 
- Grafana version: Grafana 7.0.5
- Data source type & version: Unrelated, but we are using Metrictank
- OS Grafana is installed on: RHEL 7.6
- User OS & Browser: MacOS, Chrome or Safari
- Grafana plugins: 
- Others:

**Comment by adeverteuil** [comment]
I see a similar behavior in Firefox. In my observation, the progression is not linear.

No need to have a tag filter. No filter works as well. Filter with 0 results also reproduces the issue.

Grafana version: 7.0.5
Browser: Firefox 78
Data source: TestData DB

| Number of panels | Number of `/api/search` requests |
|---|---|
| 1 | 3 |
| 2 | 5 |
| 3 | 7 |
| 4 | 8 |
| 5 | 9 |
| 6 | 10 |
| 7 | 11 |
| 8 | 12 |
| 9 | 13 |
| 10 | 14 |

**Comment by torkelo** [comment]
Hm. Unable to see any correlation between number of panels and search requests. 
https://play.grafana.org/d/000000184/dashboard-links-issue?orgId=1

But I do see duplicate requests. Caused by this line of code:  
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/components/SubMenu/DashboardLinksDashboard.tsx#L23

And the fact that we generate a new linkInfo object every render so they always differ:
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/components/SubMenu/DashboardLinks.tsx#L23
