### ISSUE TITLE
TextBox: TextBox input value and results out of sync

### ISSUE THREAD

**Issue by msillence** [grafana/grafana#26348]
**What happened**:
Using a variable to select data I saved a default value
Updating the default value and saving the graph I now see the correct new value
Returning to the dashboard with just the minimal URL (without the variable parameters) the old default value is used to select data but the new value shows in the variable box
Clicking in the variable box and then outside the graphs now update showing the correct data

**What you expected to happen**:
I expected the new value to be used as a selector as shown in the UI

**How to reproduce it (as minimally and precisely as possible)**:
Create a promethus data source
Create a dasbboard
Create a text variable assign it a default valie
Create a graph on the dashboard using the variable to select data
save
update the variable value
save
return to the dashboard with the url without parameters
http://mygrafana.host/d/abc/def
(not with http://mygrafana.host/d/abc/def?param=value)

The data with the old selector value is shown (the new value correctly shows but is not used)

click in the text box - without changing anything click out of the text box

the new value now takes effect

**Anything else we need to know?**:

**Environment**:
- Grafana version:
7.0.6

- Data source type & version:
Prometheus

- OS Grafana is installed on:
Unix docker image

- User OS & Browser:
Firefox

- Grafana plugins:
None

- Others:

**Comment by msillence** [comment]
If you capture the json for the dashboard, delete the dashboard, import the dashboard the new value works as expected

**Comment by ivanahuckova** [comment]
I was sort of able to reproduce this as well, but only when I didn't save the current variable values **as dashboard default**. Therefore in my case, it was making sense, that the result was showing "old" default value , but problem was that TextBox and results were out of sync. 

![Kapture 2020-07-16 at 16 49 40](https://user-images.githubusercontent.com/30407135/87686306-a5d48400-c784-11ea-87af-693398dbf3c9.gif)

@hugohaggmark could it be related to https://github.com/grafana/grafana/issues/24576?

**Comment by msillence** [comment]
I can confirm

Changing it via the settings -> variables does work as expected for me

Channing it via the text box and saving - the displayed value and the displayed data are out of sync

**Comment by hugohaggmark** [comment]
@ivanahuckova you didn't check the checkbox when you saved so the value for the textbox and the value stored in the dashboard will be out of sync.

**Comment by ivanahuckova** [comment]
Yeah, but shouldn't it show the default value in both - textbox input and used in panel? Because (at least for me), it would be confusing to see the value in textbox that us different than the value used in panel.

**Comment by hugohaggmark** [comment]
@ivanahuckova  @msillence I'm going to try to explain this in steps because this is not the best UX. I've verified the behaviour with Grafana v6.0.0 and the behaviour hasn't changed since then. But maybe it is time to change it :)

First let's create a new empty dashboard and add this variable:
![image](https://user-images.githubusercontent.com/562238/89273750-43aec680-d640-11ea-95ad-b3b6c484468f.png)

Because this is a new dashboard we'll not see the switch asking us to save default values for variables but it behaves the same as if we would click on the switch **(IMPORTANT)** 
![image](https://user-images.githubusercontent.com/562238/89273894-78bb1900-d640-11ea-988e-db2da33e9e7c.png)

Next step let's add a Text panel with the following settings
![image](https://user-images.githubusercontent.com/562238/89274148-d18ab180-d640-11ea-8778-9a25a44a2e98.png)

Should look like this
![image](https://user-images.githubusercontent.com/562238/89274204-e1a29100-d640-11ea-8acd-6978e25e1ed6.png)

Now let's save this new dashboard and because I haven't touched the variable, I get this modal
![image](https://user-images.githubusercontent.com/562238/89274331-0f87d580-d641-11ea-9cc2-e87e7ce10351.png)

Ok, so next step is to change the value of the variable and see that both the value in the text box, in the Text Panel and the variable value has been added to the url **(IMPORTANT)** 
![image](https://user-images.githubusercontent.com/562238/89274488-452cbe80-d641-11ea-8276-ac614cb1b37c.png)

If we try to save now, the switch `Save current variable values as dashboard default` will appear.
![image](https://user-images.githubusercontent.com/562238/89274948-eae02d80-d641-11ea-935e-04a3f78690be.png)

So here's where it gets a bit hairy and It's important to dig under the scenes here. If you save without clicking on the switch above then only the value entered in the input field 
**Input field value:** ![image](https://user-images.githubusercontent.com/562238/89275996-58408e00-d643-11ea-9de5-811a6a707621.png)
 is updated/stored with the dashboard. 

If you select the `Save current variable values as dashboard default` switch and save then both the value entered in the input field and the default value for the variable is updated/stored with the dashboard.
**Default value:** ![image](https://user-images.githubusercontent.com/562238/89276074-75755c80-d643-11ea-9303-cc69f0e7c5f4.png)

Sorry for this long comment, and I hope you've gotten a better understanding about the UX issue we're facing here.

As long as you remember to select the switch `Save current variable values as dashboard default` everything works as expected and no out of sync occurs.

Now how should we fix this?
1.  If a user saves without selecting the `Save current variable values as dashboard default` switch we could reset the input field value to match the default value.
2. If a user saves without selecting the `Save current variable values as dashboard default` switch we could update the default value if that differs from the input field value.

Neither of the options seem good enough to me. If we choose the first option then users will get confused because they think they updated the default value but instead the input field is reset. The second option would be the least bad but would make the Text box variable behave like no other variable and users that are familiar with the existing behavior would be surprised too. WDYT is the best way to solve this @ivanahuckova @msillence ?

**Comment by torkelo** [comment]
> So here's where it gets a bit hairy and It's important to dig under the scenes here. If you save without clicking on the checkbox above then only the value entered in the input field

That seems incorrect. The default value in settings should always be saved if changed (as it's an option). The current value should only be saved if the checkbox is checked

**Comment by hugohaggmark** [comment]
> > So here's where it gets a bit hairy and It's important to dig under the scenes here. If you save without clicking on the checkbox above then only the value entered in the input field
> 
> That seems incorrect. The default value in settings should always be saved if changed (as it's an option). The current value should only be saved if the checkbox is checked

Yes, my bad in my explaination. I'll update my text. 

I still don't think this is a bug but a UX issue that we need to adress some day.

**Comment by thisisobate** [comment]
Investigated and noticed issue no longer exist on main.
Fixed #29407
