### ISSUE TITLE
Better UI support for multiple fields in InfluxDB - e.g. default selected field, and series name

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2635]
Grafana supports having multiple fields in InfluxDB - which is pretty awesome! =)

However, much of the UI is still geared towards having a single field named `value`.

For example, I have a measurement like this:
```
{
    "measurement": "iostat_multiple_fields",
    "tags": {
        "project": "foobar",
        "hostname": "dev.example.com",
    }
    "time": <some_time>
    "fields": {
        "system_cpu": 50
        "user_cpu": 80
        "iowait": 20
    }
}
```

If I create a new query in Grafana, the SELECT field will default to `mean(value)`, even when there is no such field name `value`, which can be confusing, particularly to new users.

Would it be possible to have it default to something else more meaningful - perhaps the first field (sorted lexicographically) that does exist?

![screenshot 2015-09-01 09 31 13](https://cloud.githubusercontent.com/assets/243499/9592954/41206958-508c-11e5-8db2-db7dc00c2f56.png)

Secondly, the default name for each series is also appears set to `<measurement_name>.mean` - for example:

![screenshot 2015-09-01 09 12 30](https://cloud.githubusercontent.com/assets/243499/9592918/b5b69824-508b-11e5-973a-516526bd9f43.png)

This can also be confusing - since if you add multiple queries on different fields, they all end up having the same series name - would it be possible to integrate the name of the field being used in there somewhere?

(I'm guessing the reason for this default was because we used to assume that we were always taking a function on `value`, hence, there was no need to show the field name).

**Comment by Sotfo** [comment]
try alias :smile:

**Comment by victorhooi** [comment]
I am aware of the alias field to name a series =) - however, I'm hoping for better *defaults* in terms of Grafana's support for multiple fields.

Having multiple fields is no longer an anti-pattern in InfluxDB 0.9:

https://groups.google.com/forum/#!topic/influxdb/7tHKkEMJWwQ

Hence, it would be cool if the out-of-the box support was there - so things like the default series name etc. taking it into account.

**Comment by torkelo** [comment]
@victorhooi the default comes from influxdb! It is returning the measurement name and the function, not the field name.

**Comment by torkelo** [comment]
I am not sure that is good InfluxDB data design, those should not be fields but measurements.

**Comment by victorhooi** [comment]
Hi @torkelo 

I actually asked this question on the InfluxDB mailing list:

https://groups.google.com/d/topic/influxdb/7tHKkEMJWwQ/discussion

Philip and Sean from the InfluxDB team chipped in. The last command from Sean was quite useful (https://groups.google.com/d/msg/influxdb/7tHKkEMJWwQ/nHvBt3TjBgAJ):

> There's no issue with having fields named "value" or not. The only way it impacts InfluxDB is that we have to pick something to use in the docs and examples, and since Grafana already likes "value" and it's a common presentation tool for InfluxDB users, we tend to use it, too. With 0.9 there's no reason to use or not to use "value" as a field key. 

and also, when I asked about the additional write-load from multiple fields:

> This cost may very well go away with an upcoming release. I wouldn't worry too much about designing the schema to avoid multiple fields per point. I think it makes for more readable queries and makes more queries possible. 

Also, apologies, I don't quite understand your comment above:

> It is returning the measurement name and the function, not the field name.

Hmm, I was thinking the *SELECT* box should default to the first field sorted alphabetically (e.g. `idle` in my screenshot above).

And that the name of the series, instead of being `iostat_multiple_fields.mean`, could be somehting like `iostat_multiple_fields.system_cpu.mean`.

Does that make sense?

**Comment by torkelo** [comment]
Well InfluxDB uses tags to organize data, a measurement should be the "what" your are measuring, lik "user_cpu" should be a measurement, the field should just use the value. It would be good if InfluxDB came out with some kind of best practice or recommendation on data layout. This is turning to the EXACT same problem InfluxDB 0.8 had which was a PAIN for Grafana, all InfluxDB users organize their data differently, no one knows how to organize data, no guidance, hard for Grafana to support all ways in a good and easy way without creating a complicated UI mess. 

ping @pauldix help please? 


> It is returning the measurement name and the function, not the field name.

You were complaining about the legend series name. I was just saying that this problem is due to InfluxDB returning the name in a strange way when you use a function. 

For example if you query `select mean(my_column) from logins.count`
The column (field name) returned will just be `mean`

![image](https://cloud.githubusercontent.com/assets/10999/9603812/982e32a8-50b3-11e5-927f-1785d258ced8.png)

Would be great if influxdb return my_column.mean or mean(my_column) or something instead of just the function name :)

**Comment by pauldix** [comment]
We're going to change the column names to be `mean(my_column)` in a future release, but will probably be 1.0 in a number of months. We're basically saving up the breaking changes like this to make at the same time. See this: https://github.com/influxdb/influxdb/issues/3838.

Although maybe there's a case for making the breaking change now, but I'm really hesitant to do that since many people are upset with breaking changes. Although some people are supportive of the iteration so I'm not sure.

As for using multiple fields, it's completely valid to do that. Right now field data is stored together so it could create inefficiencies, but later versions will store each field as its own range in the DB, so the number of fields on a measurement won't matter.

The end result will be that `measurements` represent a logical grouping of measurements that you're taking. It's a thing you're taking measurements about, like from redis, cpu, mysql, etc. Then each measurement will have fields which are the specific readings you're taking for the thing you're measuring (e.g. user, idle, key_count, connected_clients), then tags are the metadata that describe where the data came from or what dimensions you'd like to query on later.

At least that's what we're starting to coalesce on, but it's still up for a debate a bit.

The tricky part for a query editor is that you can't select a field until you select a measurement. Kind of like in SQL, you won't be able to populate a list of columns until you select a table.

It's almost like the `FROM` and `SELECT` portions of your builder need to be inverted, despite it going against SQL syntax. I think it's really because SQL assumes the user has complete knowledge of the DB schema, which is different from the time series use case where discovery is a necessity because there's so many combinations.

**Comment by torkelo** [comment]
thx @pauldix, this helps a lot. 

Will have to do some changes to the editor :)

**Comment by victorhooi** [comment]
@torkelo In light of the above, would it make sense to re-open this ticket?

**Comment by pkittenis** [comment]
@torkelo - the column name can be redefined, eg ```select mean(value) as value from <..>```

AFAIK this is not explicitly documented but [is shown in a continuous query example](https://influxdb.com/docs/v0.9/query_language/spec.html).

The name of the returned data column is now simply ```value```, allowing you to change the aggregation function without having to change the column name.

This is also what the ```graphite-influxdb``` plugin [uses for its influxdb queries](https://github.com/pkittenis/graphite-influxdb/blob/master/graphite_influxdb/classes.py#L265).
