### ISSUE TITLE
Can't remove invalid character when creating variable

### ISSUE THREAD

**Issue by dkozinn** [grafana/grafana#26562]
**What happened**:
I was creating a variable and accidentally typed an invalid character (@) in the name. An error indicated a validation error since only word and digit characters are allowed in a name. I tried to delete the incorrect character using backspace but the cursor stopped at that character and would not delete the invalid character. I had to leave the Add Variable screen to clear the field.

I subsequently found that if you type characters before the invalid character you can move the cursor to the beginning of the input field and use delete to delete all characters, including the invalid one.
![grafana variable name bug](https://user-images.githubusercontent.com/8498054/88337152-36224400-cd04-11ea-8a6e-a4b77a182c72.gif)

**What you expected to happen**:
Entering an invalid character should display a validation error then allow the user to backspace to delete that invalid character.

**How to reproduce it (as minimally and precisely as possible)**:
1) From a dashboard, click dashboard settings, Variables, Add Variable
2) In the Name field type "@". Validation error displays (expected)
3) Press backspace. Nothing happens.

**Anything else we need to know?**:
Screencap GIF demonstrates this. This can be reproduced at play.grafana.org 

**Environment**:
- Grafana version: 7.1.0  (8101355285)
- Data source type & version: N/A - This occurs before specifying a source
- OS Grafana is installed on: Docker container from official Docker Hub. Host OS for Docker is AWS Linux
- User OS & Browser: Windows 10 20H2 (Build 19042.388) - Beta, Browser Chrome 84.0.4147.89, also reproducible on current versions of FIrefox and Edge Chromium
- Grafana plugins: N/A
- Others:

**Comment by LucasRaschek** [comment]
I investigated this issue a bit. This is the first time I am trying to contribute to a project and I don't know the code of grafana so good, unfortunately. I found it very hard to debug the code, as I wasn't able to debug with Intellij's tools. I don't know how to run the frontend with Intellij directly instead of just building the frontend and serving it via the go backend, maybe someone can give me a hint. So I used good old `console.log()` and Redux dev tools to investigate the Issue.

**What I found out:**
The location of the bug is in the variables editor and it hasn't only to do with invalid characters. There is a line of code in the `changeVariableName` action, that checks if the newName (we want to assign the variable) is the same as the name, that is already set in the state of the variable. If that is the case. we return.
```typescript
    const variableInState = getVariable(identifier.id, getState());
    if (newName === variableInState.name) {
      return;
    }
```
I, unfortunately, don't fully understand yet, how this global variable state is set. But it seems like, the global name for the new variable is set to the last valid name entered. (Or empty string if nothing valid was entered yet.)

**What happens in this scenario:**
We create a new Variable:
1. `globalVariableName`: "" `variableEditorName`: ""
2. (we type "@") `globalVariableName`: "" `variableEditorName`: "@"
3. we try to delete "@", so the new name we want to set ist an empty string, but the `globalVariableName` is an empty string too, so we get into the body of the if statement above and therefore nothing happens.

Scenario 2:
We create a new Variable:

1. `globalVariableName`: "" `variableEditorName`: ""
2. (we type "s", which is valid) `globalVariableName`: "s" `variableEditorName`: "s"
3. (we delete "s", so the new Name is an empty string) `globalVariableName`: "s" `variableEditorName`: "" There is an error message, as this is an invalid name
4. we type "s" again, but nothing happens, because the `globalVariableName` is "s" too.

So the mechanism itself is broken and needs to be fixed. This check above isn't the best, as the `variableInState.name` is only the last valid name or empty if nothing valid has been entered yet. Maybe an own error message for empty field instead of "invalid character"

**Comment by LucasRaschek** [comment]
It is very buggy in general. As I recorded this gif I additionally found out, that there seems to be a bug, when a space is between words. Needs more investigation
![Peek 2020-08-06 15-09](https://user-images.githubusercontent.com/17753678/89535579-e14bf680-d7f6-11ea-84fa-23cc589fa422.gif)

**Comment by JalanshMunshi** [comment]
Hi @torkelo ,

I am able to replicate this issue with special characters on my Grafana server (Grafana v7.1.3). 

Is it a problem with my version or this bug is still visible? I checked the PR but the not able to find whether bug is a part of the version that I am currently using.

Looking forward for your reply.
