### ISSUE TITLE
Add an option to disable query input or change query params from url

### ISSUE THREAD

**Issue by garyyang85** [grafana/grafana#26567]
**What would you like to be added**:

When define a dashboard variable, add an option to disable selection input, only the filtered values can be selected.

**Why is this needed**:

This is very useful in some tenant scenarios. Say I have a dashboard for user A. Admin only need user A work on namespace name with userA prefix. I could define a variable to filter namespace like that, but now user A still have two ways to see other namespaces. 
1. Manually type other namespace name in the variable selection input.  like default or userB-xx
2. Manually set the namespace name to another one in url, like:&var-namespace=default   
Can we change the behavior like this: 
You can change param value in url, but if the value is not in the filtered options, it won't work

**Comment by torkelo** [comment]
related to 
https://github.com/grafana/grafana/issues/18157

and 
https://github.com/grafana/grafana/issues/20843 

Grafana dashboards are very dynamic due to template variables any possible query can be issued by any dashboard, so a user with viewer role can only access some dashboards (and not modify them or create new) can still issue any possible query. As Grafana does not do any query authorization to limit what queries a user can issue, if the user is member of an org with a specific data source then it will have access to query that data source 

What datasource are you using? Does it have any support for data isolation & query security?
