### ISSUE TITLE
Stat Panel: display name not showing when text mode set to Auto and explicitly set in field config 

### ISSUE THREAD

**Issue by Eraac** [grafana/grafana#26583]
**What happened**: 
The StatPanel doesn't render the display name anymore, since the 7.1

**What you expected to happen**: 
See display name in the panel

**How to reproduce it (as minimally and precisely as possible)**:
* setup a new dashboard, with a stat panel
* set a display name

**Anything else we need to know?**:
Everything was fine with 7.0.x

**Environment**:
- Grafana version: 7.1.1
- Data source type & version: default, stackdriver (and probably all others datasources)
- OS Grafana is installed on: kubernetes via the official helm chart
- User OS & Browser: mac os / chrome

**Comment by torkelo** [comment]
Set the new Text mode option to name and value. 

But the auto mode should show it. Will investigate.

**Comment by Eraac** [comment]
Indeed, Text Mode "Value and Name" fix this, but "Auto" display only the value

Thanks for the workaround!

**Comment by Eraac** [comment]
I just saw this bug only happens if you have 1 metric 

there are 2 stat panel here, 
- top has only one metric, auto mode -> display name isn't showing
- bottom has 2 metrics, auto mode -> display name is showing

![image](https://user-images.githubusercontent.com/5497623/88488822-2e76cf80-cf90-11ea-9005-e5fe0acc5c32.png)

**Comment by torkelo** [comment]
@ryantxu A bit conflicted on how to solve this or if it should be solved. with Text mode set to Auto should stat panel show display name if set via Field tab default? what about via override? I started on a fix like that, to check in StatPanel.tsx if fieldConfig.defaults.displayName was set and then switch text mode to value and name (passed to BigValue).  But not sure, maybe Auto should just be if count === 1 then do not show name, if you want to show name if count === 1 you have to change display name. and to fix broken old dashboards instead of adding logic in StatPanel.tsx we can do a migration that for panels with default displayName set we change textMode.  Only downside with that users will try to change Display name and it won't have any effect when text mode set to Auto.
