### ISSUE TITLE
Explore: Collapsing the graph row will cause it to disappear completely when query is re-run.

### ISSUE THREAD

**Issue by slim-bean** [grafana/grafana#26635]
**What happened**:

Was running a metric query on a prometheus datasource in Explore, shrunk the Graph to focus on the table, went to re-expand the graph row and it had disappeared completely.

Seems repeatable, as soon as you run your first query after minimizing the graph row it will disappear.

Same is true for the table, if you minimize it and run the query it will disappear also.

**Comment by torkelo** [comment]
unable to replicate, can you include more details? What version of Grafana, browser? what query? Any errors in the chrome console?

**Comment by slim-bean** [comment]
Just tried it with Firefox and Chrome, same behavior, Grafana version is master `v7.2.0-7860df22pre (2ba0083784)`

Nothing in the console logs.

**Comment by slim-bean** [comment]
The query didn't seem to matter but in this case it was `agent_wal_storage_active_series{pod="grafana-agent-rhhdb"}` against a prometheus datasource (cortex in this case)

**Comment by torkelo** [comment]
Was able to replicate now! executing a new query while collapsed was the key!

**Comment by aocenas** [comment]
I think this may be something with bad feedback loop after the unification. We are sending information whether table/graph are collapsed so that the may not run the query for something that won't be seen. On the other hand this means we will think there is not table data and so we remove the table altogether.

Not running query for collapsed elements probably made sense before, when explore sort of dictated what it wants to show and datasource should do that but now maybe we can just get rid of that and collapsing can be just pure frontend UI thing.
