### ISSUE TITLE
Templating: allow hiding variables from the user

### ISSUE THREAD

**Issue by jbergler** [grafana/grafana#2665]
We have a graphite like web service that we use to do dynamic key -> value lookups similar to what is discussed in #2188 and it works great but easily pollutes the selections the user can make in a dashboard.

It would be great if we could mark a variable in some way so that it continues to operate as normal but either isn't visible at all, or is only visible if there is >1 option to select.

**Comment by torkelo** [comment]
Not sure I think this is a good idea. Will close for now :(

**Comment by jbergler** [comment]
I played around earlier today with adding this, see: jbergler@d4337d6b8f92113ad986a0c7fc59d63921a4a7a6

Do you not think its a good idea because it adds complexity or because it doesn't fit with another solution you have in mind?

**Comment by n-st** [comment]
I was just looking for a way to do this as well:
I'm building a dashboard that displays data from several monitoring nodes that can be physically moved between locations, so it would be handy to have a way to select which node is currently at which location. Variables would work fine for that, but since the association 'location → node hostname' rarely changes, I don't want to clutter the dashboard with variable selectors (plus the hostnames are a purely internal affair, so shouldn't be shown to external people looking at the dashboard).

**Comment by nik-petrov** [comment]
+1 for this request

I use variables just to save us time from updating certain constant in many graphs.

**Comment by Tomcat-Engineering** [comment]
+1 for this.  

I use a variable to generate a set of "repeated panels" based on the data.  I don't need/want the user to be able to select a single value for the variable and only display one panel.  The rest of the dashboard is not filtered by that variable, so allowing the user to select a single value at the top of the dashboard is misleading.

Maybe I've missed something and there is already a way to do this?

**Comment by Tomcat-Engineering** [comment]
Ah, sounds like this ticket is now superseded by #4146

**Comment by RichiH** [comment]
Should this ticket be closed, then?

**Comment by torkelo** [comment]
@RichiH it is closed

**Comment by RichiH** [comment]
@torkelo Weird. I see you closed it on Sep 3, 2015, but it showed as open earlier... Now, I have the <closed> tag under the title...
