### ISSUE TITLE
Grafana Explorer randomly removes / reorders entries with same timestamp from results returned by Loki API

### ISSUE THREAD

**Issue by swisspol** [grafana/grafana#26714]
**What happened**:
If Loki API returns multiple entries with the same internal timestamp (as imported by Promtail), only a "random" subset is shown in the UI and the order may not be preserved either.

**What you expected to happen**:
With deduplication OFF, Grafana Explorer UI shows exactly what Loki API returns.

**How to reproduce it (as minimally and precisely as possible)**:
Here's an example series of entries returned by Loki API that show the bug. There are ~20 entries with `1596023152896762800` timestamp, but Explorer UI only shows 5.

```
          [
            "1596023152897829400",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'MaterialInstance /Game/Twinmotion.Twinmotion:ResourceMaterialGeneric_2147455351.'\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'MaterialInstance /Game/Twinmotion.Twinmotion:ResourceMaterialGeneric_2147455360.'\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896762800",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
          [
            "1596023152896762800",
            "LogTemp: Warning: Property mDiffuseMap on object type ResourceMaterial does not exist\r"
          ],
          [
            "1596023152896159600",
            "LogUObjectGlobals: Warning: Failed to find object 'StaticMesh None.'\r"
          ],
```

![image](https://user-images.githubusercontent.com/627915/88994315-ebbd3c00-d29c-11ea-83c6-bdaa46c77e5f.png)

This results in Explorer API saying there are only 522 results out of a query with a limit of 1630, implying we have reached the end of the stream for this time period, which is completely false as Loki actually returned 1630 results.

![image](https://user-images.githubusercontent.com/627915/88994528-743bdc80-d29d-11ea-8a67-1a7f934d24e1.png)

**Anything else we need to know?**:
n/a

**Environment**:
- Grafana version: Grafana 7.1.1
- Data source type & version: Loki 1.5.0
- OS Grafana is installed on: Linux
- User OS & Browser: Mac / Chrome

**Comment by aocenas** [comment]
So we do a deduplication of logs based on timestamp and the log message, because loki can send duplicate logs due to limitation of the ingestion architecture. In that case we actually don't want to show those duplicates. Are you saying that this is not a duplication but real logs and you want to show them even though the are exactly the same lines?

**Comment by swisspol** [comment]
I can't say if the app is logging multiple times the same messages or if it's Promtail / Loki that's "creating" duplicates. I certainly hope it's not the latter as it would imply you cannot trust Loki.

In my mind, deduplication should only remove entries that match both on content and timestamp, which means in this example that no entries should be removed.

**Comment by slim-bean** [comment]
I can add a little clarity here from Loki's perspective and what the behavior of Loki is today:

> I can't say if the app is logging multiple times the same messages or if it's Promtail / Loki that's "creating" duplicates. I certainly hope it's not the latter as it would imply you cannot trust Loki.

We don't have any known issues or any other reports of this behavior, if you are able to demonstrate that promtail or Loki are duplicating logs please do open an issue in the Loki repo. Based on lack of other people reporting this issue I suspect it's more likely the application is generating duplicates.

> In my mind, deduplication should only remove entries that match both on content and timestamp and are next to each other,

this is how Loki operates today, if multiple log entries are received with the exact same nanosecond timestamp and exact byte for byte content the multiples will be dropped and only one line kept.

> because loki can send duplicate logs due to limitation of the ingestion architecture.

If two log lines are received with the exact same nanosecond timestamp but _different_ content, the log lines are all saved. This isn't so much a limitation as much as a design decision, if the logs have different content we treat them as different lines despite having duplicate timestamps.

This will almost invariably lead to challenges in the UI if it does any kind of sorting of log lines based on a timestamp because the timestamp is the same. Loki should be returning these log lines in the order they were received even if they have the same timestamp so if possible to retain the received ordering from Loki they can be presented as received.

**Comment by ivanahuckova** [comment]
@slim-bean so just to confirm [this documentation](https://grafana.com/docs/loki/latest/architecture/#querier) should be then updated to include the information, that querier (Grafana) should deduplicate only logs that are next to each other, because we are currently [deduplicating all logs](https://github.com/grafana/grafana/blob/master/public/app/core/logs_model.ts#L396.) with the same [nanosecond timestamp, label set, and log message](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/loki/result_transformer.ts#L143). 

This is how it is currently: 
```
 Because of the replication factor, it is possible that the querier may receive duplicate data. To resolve this, the querier internally deduplicates data that has the same nanosecond timestamp, label set, and log message.
```

And on Grafana side, we need to update deduplication so only logs that are next to each other and have the same nanosecond timestamp, label set, and log message are deduplicated.

**Comment by slim-bean** [comment]
> that the querier (in this case Grafana)

This documentation is referring to the querier component within Loki's architecture and not a client such as Grafana

Loki will not return any exact duplicates (same nanosecond timestamp, labels, and log message) it is not necessary for Grafana to de-duplicate these.

**Comment by ivanahuckova** [comment]
Thanks for explanation @slim-bean! I think there was some confusion on our side then. We will fix this.

**Comment by ivanahuckova** [comment]
@slim-bean is this the same case when we are streaming (live tailing)?  Is there any special case here?

**Comment by ivanahuckova** [comment]
Just to summarize the findings:
- Loki doesn't send duplicate logs and we should remove deduplication [here](https://github.com/grafana/grafana/blob/master/public/app/core/logs_model.ts#L396.)
- Nanosecond timestamp + labels + log message is not unique, we should figure out what will we use as ids that are later used as key
- When implementing this, we should make sure that LiveTailing doesn't regress as keys and their consistency is important
