### ISSUE TITLE
DataLinks from data sources override user defined data link

### ISSUE THREAD

**Issue by LukeDearden** [grafana/grafana#26762]
**What happened**: Updated from 7.0.6 to 7.1.1 and DataLinks from Stat Panels on our dashboard using Log Analytics queries all reverted to "View in Azure Portal" ignoring the existing Datalink

**What you expected to happen**: It should render the Datalink correctly and open the correct link in a new tab

**How to reproduce it (as minimally and precisely as possible)**: Create a Panel that uses an Azure Log Analytics query and try set and follow the Datalink

**Anything else we need to know?**: Panel Links still work fine

**Environment**:
- Grafana version: v7.1.1 (3039f9c3bd)
- Data source type & version: Azure Log Analytics
- OS Grafana is installed on: Ubuntu 16.04.6 LTS
- User OS & Browser: Edge Chromium/FireFox 
- Grafana plugins: Azure Monitor 0.3.0

Example
![datalinks](https://user-images.githubusercontent.com/6813601/89162080-35977200-d57c-11ea-84f7-b2432b039d0b.png)

Actual link
![datalinks2](https://user-images.githubusercontent.com/6813601/89162547-ebfb5700-d57c-11ea-8951-537b23b07b72.png)

- Others:

**Comment by aknuds1** [comment]
@kylebrandt Is this related to your work?

**Comment by kylebrandt** [comment]
I can replicate this. I assume this is because we are sending the Azure portal link as a Datalink from the backend, and this situation runs into this issue.

There are two different places to set data links:
 1. The "Field" Tab
 2. The "Field Overrides tab"

In the Field tab, adding a new datalink seems to have no impact as described in the issue. 

In the Field Overrides tab, setting the datalink replaces the "View in Azure Portal" datalink that is returned from the backend ( @LukeDearden this might provide with a workaround - although I imagine not ideal ).

The override behavior seems like it good be okay to me, but since data links is plural (and is an array) - I think that when the Field tab, adding a data link should append to any existing data links provided by the backend. Are you able to look into this @ryantxu ?

**Comment by nickjacobsen** [comment]
I believe the underlying issue is lines 173 - 179
of
public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_log_analytics/azure_log_analytics_datasource.ts

Where rather than appending to the links array it just clobbers it.

   field.config.links = [
                  {
                    url: url,
                    title: 'View in Azure Portal',
                    targetBlank: true,
                  },
                ];

**Comment by etiennechabert** [comment]
I am having the same issue with cloudwatch, "field overrides" is indeed a nice trick allowing me to fix my issue, thanks for that 👍

**Comment by joshhunt** [comment]
Looks like the behaviour of this has changed, but there's still improvements we want to make to core Grafana to make setting custom data links on data sources that also set data links better.

**Comment by ivicamihalic** [comment]
Any news on this ? Could you at least please describe the process of overriding this data link field as it looks to me like its not possible anymore. Thanks

**Comment by joshhunt** [comment]
This is a current Grafana limitation, as explained by Torkel in https://github.com/grafana/grafana/issues/32007#issuecomment-814336439. Data links supplied by a source source will override any default data links specified in the panel options.

As a work around, the user can supply a data link using Overrides which will show in the panel. However, you will lose the "View in Azure" etc link from the data source.

![image](https://user-images.githubusercontent.com/46142/130054020-fb1c2b8e-eacf-43d9-acc0-fab2e341020d.png)

**Comment by hugohaggmark** [comment]
Hi @joshhunt @kylebrandt, are you actively working on solving this issue?

**Comment by aangelisc** [comment]
Hey @grafana/user-essentials, is this something that's been deprioritised? We've recently had an escalation related to this issue.
