### ISSUE TITLE
Value mappings for durations is broken

### ISSUE THREAD

**Issue by mamosk** [grafana/grafana#26763]
**What happened**:
Table panel in a dashboard with durations in seconds.
Value mapping for example "range from 1 to 3" applies to:
- 1 second (ok)
- 2 seconds (ok)
- 3 seconds (ok)
- 1 minute (bad)
- 2 minutes (bad)
- 3 minutes (bad)
- 1 hour (bad)
- 2 hours (bad)
- 3 hours (bad)

**What you expected to happen**:
Value mapping should apply to seconds only:
other values are only converted for presentation,
but the mapping should be intended for the unconverted values only.

**How to reproduce it (as minimally and precisely as possible)**:
Add a new pane to a new dashboard.
Select a SQL Server source and write this query:
`SELECT 1 as a, 2 as b, 60 as c, 120 as d, 3600 as e, 7200 as f, 0 as time`
Format as **table** (not as time serie).
In _Panel_ tab select **Table** visualization.
In _Field_ tab select Standard options > Unit > Time > **duration (s)** .
In _Field_ tab add a value mapping for value 2 with text "banana".
You will see something like this:
![image](https://user-images.githubusercontent.com/22736721/89180399-fd029300-d591-11ea-8901-b4847c44dd5c.png)
- column `b` is correct
- column `d` is incorrect and should display `2 minutes` instead of `banana`
- column `f` is incorrect and should display `2 hours` instead of `banana` 

**Environment**:
- Grafana version: 7.0.4
- Data source type & version: built-in SQL Server data source
- OS Grafana is installed on: Docker
- User OS & Browser: Windows 10 & Chrome

**Comment by aknuds1** [comment]
Does this also happen with the latest version (7.1.1)?

**Comment by mamosk** [comment]
Yes, I just updated to Grafana 7.1.1 as @aknuds1 requested and this still happens.
The problem does **NOT** involve thresholds, which work correctly.

### Example with production data:

Thresholds are these:
![image](https://user-images.githubusercontent.com/22736721/89189181-ecf1b000-d59f-11ea-81bd-b3aab18c5a4c.png)

These are the values _without_ mappings:
![image](https://user-images.githubusercontent.com/22736721/89189395-3510d280-d5a0-11ea-8654-c9cf015d26b8.png)

These are the values _with_ mappings:
![image](https://user-images.githubusercontent.com/22736721/89189328-1ca0b800-d5a0-11ea-8aa5-6a7e637554ca.png)
![image](https://user-images.githubusercontent.com/22736721/89189352-275b4d00-d5a0-11ea-916f-a0f1fd7bf614.png)

**Comment by svet-b** [comment]
Just came across this also, running 7.4.0-beta1. Worth noting that it's affecting all "interpreted" values with units, and not just duration. For example let's say I have power readings where the raw data is in Watts, and I want to map readings in the range from 0-30 W to show "off", as follows:
![Screen Shot 2021-01-27 at 12 32 49 PM](https://user-images.githubusercontent.com/12831860/105985487-ce2a2d00-609b-11eb-9cae-794e1a86b214.png)
In the below "Power 1" is the raw data, "Power 2" has units applied, and "Power 3" has units _and_ a range mapping. Works great for small values:
![Screen Shot 2021-01-27 at 12 27 32 PM](https://user-images.githubusercontent.com/12831860/105985312-991dda80-609b-11eb-8177-b2268354e1e5.png)
But this is what is shown for values over 1 kW:
![Screen Shot 2021-01-27 at 12 27 55 PM](https://user-images.githubusercontent.com/12831860/105985322-9b803480-609b-11eb-8a26-29c831c69bc7.png)
This affects value as well as range mapping. Essentially, it looks like the mapping is done after unit conversion, rather than on the actual data. Presumably it should be the other way around.
