### ISSUE TITLE
Update queries after template variable rename

### ISSUE THREAD

**Issue by LeonidVasilyev** [grafana/grafana#2678]
I use version 2.1.1. Right now after I change template variable name within Templating/Edit section I also had to update all queries that use changed variable. Because they are keep to reference old variable name. It would be nice to avoid this manual query manipulation and update them automatically instead.

**Comment by utkarshcmu** [comment]
+1

**Comment by utkarshcmu** [comment]
Also, with changing the queries, alias fields should also be changed. :)

**Comment by torkelo** [comment]
This would be nice. A bit tricky to do in a generic way but might be possible. 

We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
