### ISSUE TITLE
Jaeger operations list does not work if service name contains forward slash

### ISSUE THREAD

**Issue by timpalpant** [grafana/grafana#26870]
**What happened**: Attempting to list operations available for a service in the Jaeger plugin fails with a JS error if the service name contains a forward slash.

![jaeger-services](https://user-images.githubusercontent.com/814226/89678802-d4460a80-d8bd-11ea-8ce0-4eb0b8b3e87f.png)
![console-error](https://user-images.githubusercontent.com/814226/89678821-dd36dc00-d8bd-11ea-9437-605259859989.png)
![api-request](https://user-images.githubusercontent.com/814226/89678831-e1fb9000-d8bd-11ea-863d-5fe356aaee0c.png)

URL-encoding of the service name was done in #25674 but the overall functionality still does not work.

**What you expected to happen**: Operations for the service are listed

**How to reproduce it (as minimally and precisely as possible)**: Have a service name that contains a forward slash. Try to use the Jaeger plugin to find and select a trace for this service.

**Anything else we need to know?**: Making the same API call to Jaeger directly does return a response. Possibly the URL-encoding may be getting un-done by the proxy. There's no way to use direct mode due to #25699.

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: Jaeger
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Safari 13.1.2
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment]
I've tried to find the root cause of this issue and it seems like something related to our data source proxy backend code.
I've seen that `c.Req.URL.Path` passes back a decoded version of the URL and that `c.Req.URL.RawPath` have the right encoded URL that I sent in. It also turned out that `c.Params("*")` returns the URL decoded as well.

https://github.com/grafana/grafana/blob/05e37e9253761fe4360e81521b22cffe45405dac/pkg/api/dataproxy.go#L37

I think this is something that @grafana/backend-platform should take a look at.
