### ISSUE TITLE
Installation: APT source for Debian stable (jessie)

### ISSUE THREAD

**Issue by abravorus** [grafana/grafana#2688]
Hello,

The installation guide recommends the following APT source for grafana deb packages installation/upgrades:

deb https://packagecloud.io/grafana/stable/debian/ wheezy main

'wheezy' is oldstable Debian distribution with limited support. While it's noted in the installation guide that the line above could be used for other Debian and Ubuntu versions, may be it's better to change it to reflect the current stable Debian version 'jessie'. Like this:

deb https://packagecloud.io/grafana/stable/debian/ jessie main

The question arose during preparation of the upgrade from 'wheezy' to 'jessie'. I would like to be sure that grafana upgrades will work smoothly under 'jessie'.

Many thanks,
  Alexandr

**Comment by torkelo** [comment]
has the install docs mention it will work for jessie as well. Its a limitation in packagecloud that caused this solution (you cant mark a single package as compatiable with multiple distro versions, need to upload package for each distro version, and it was incredibly expensive to do that since only 20 packages where free)

**Comment by torkelo** [comment]
But for next release I will probably add it for jessie as default

**Comment by abravorus** [comment]
Ok, I understood. Thanks.

Alexandr
