### ISSUE TITLE
Azure App Insights Alert error - tsdb.HandleRequest() failed to convert dataframe "" to tsdb.TimeSeriesSlice

### ISSUE THREAD

**Issue by bhozar** [grafana/grafana#26897]
**What happened**:
Setting up App Insights to alert on metrics throws an error when tested, or in the grafana.log when left setup:
`error:"tsdb.HandleRequest() failed to convert dataframe "" to tsdb.TimeSeriesSlice: input frame is not recognized as a time series"`

Screenshot of Query:
![image](https://user-images.githubusercontent.com/1184220/89784839-47938a80-db11-11ea-8eb9-bf1d38c13953.png)

**What you expected to happen**:
Trigger an alert when the count is higher than X.

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: Azure Application Insights
- OS Grafana is installed on: Ubuntu 18:04
- User OS & Browser: Win10/Chrome

**Comment by kylebrandt** [comment]
I suspect that this from a "no data" state.  I was able to replicate this by picking a short query time in the alerting view, and also noticing that these metrics seem to be sparse (in other words no requests/failed, no datapoints). So assuming this is the case, I have created PR #26903 to handle the situation such that alert result will be "no_data" instead of an error.

**Comment by tincann** [comment]
Not sure if this is the right place to comment, but we're also experiencing this same issue with Azure log analytics queries. This makes our alerts basically fire randomly every couple of hours, so I'm very glad it's solved! I'm seeing that it's added to the 7.1.4 milestone. Do you have any idea when this version will be rolled out to Grafana Cloud?

**Comment by NaniKonduri** [comment]
I'm experiencing the above error after upgrading the grafana to 7.1.1 using helm, Any thoughts on how we can fix that? 
Data source we are using Azure Monitor and App-insights
