### ISSUE TITLE
Allow vertical aligning of text in "Text Panel"

### ISSUE THREAD

**Issue by beingyash** [grafana/grafana#26949]
**What would you like to be added**: An option to align text vertically too since as of now, till grafana v7.1.1, using HTML " \<h1 style="text-align: center"\>\<your text here\>" only aligns the text horizontally.

**Why is this needed**: This would be required for scenarios wherein someone wants to use static data labels to label other panels, typically using them as headers probably.

**Comment by sakjur** [comment]
This is a property of HTML, not Grafana. Refer to [MDN CSS text-align](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align?v=example) for more information.

**Comment by nvmendes** [comment]
The problem is that there is no way to vertically align text using css. I've tried all the options in the following link, and none of them worked in grafana, but all of them worked in a normal html page.
https://www.w3docs.com/snippets/css/how-to-vertically-center-text-with-css.html

**Comment by ChrisGet** [comment]
@sakjur annoyingly you closed this bug without paying attention to what was requested. The link you provided is about centering text horizontally. OP requested centering the text vertically.

I can confirm in Grafana v7.0.3 my usual method of centering elements vertically using transforms does not work. The raw style css transform statements in the Text panel gets ignored or overwritten by Grafana.

Being able to center the text natively within the Grafana settings would be very useful, rather than having to add inline css, which may or may not work.

**Comment by amirajoodani** [comment]
if we want to use this code to vertical text in graph :
writing-mode: vertical-rl;
text-orientation: mixed;
 where can we paste it ? in panel json format ? or other place ?
