### ISSUE TITLE
Unable to save to Elasticsearch

### ISSUE THREAD

**Issue by obfuscurity** [grafana/grafana#27]
I'm testing Grafana with a free Bonsai Elasticsearch instance at Heroku. I manually created the index (unsure if this was necessary):

```
$ curl -X POST http://user:pass@host.us-east-1.bonsai.io/grafana-dash
{"ok":true,"acknowledged":true}
```

Then I try to save a dashboard and I keep getting `OPTIONS 404 Not Found` errors. Am I overlooking something obvious? I don't see any documentation around needing `OPTIONS` for Elasticsearch anywhere, so it seems to me like this might be related to CORS.

```
Request URL:http://host.us-east-1.bonsai.io/grafana-dash/dashboard/New%20Dashboard
Request Method:OPTIONS
Status Code:404 Not Found
```

**Comment by tim-massey** [comment]
I am also having issues using a Bonsai.io elastic backend with `Credentials flag is 'true', but the 'Access-Control-Allow-Credentials' header is ''. It must be 'true' to allow credentials.`

**Comment by nz** [comment]
Nick with Bonsai here. As far as I know, CORS shouldn't need the Credentials flag, which passes the browser cookie and session info. All we really use is the Authorization header. That said, it's been a while since we worked on the CORS code; happy to hop into a quick chat or screen share to try to get a better test rig going and knock this one out. nick@bonsai.io

**Comment by tim-massey** [comment]
With @nz help I patched my copy of Grafana and removed `options.withCredentials = true;`

```javascript
if (this.basicAuth) {
        options.withCredentials = true;
        options.headers = {
          "Authorization": "Basic " + this.basicAuth
        };
}
```
