### ISSUE TITLE
Add Transformation Plugins

### ISSUE THREAD

**Issue by cpmoore** [grafana/grafana#27010]
**What would you like to be added**:

I would like to see transformations added to the plugin framework.  They should work similar to the current datasource and panel plugins.  

**Why is this needed**:

This would allow users to add their own transformations to Grafana to further make it perfect for their environment.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
