### ISSUE TITLE
Provisioning dashboard from grafana.com

### ISSUE THREAD

**Issue by scyto** [grafana/grafana#27059]
**What would you like to be added**:
Allow provisioning of dashboards from grafana.com 

Use the same provisioning dashboard yaml file format but allow a new type of grafana.net and then specify one or more dashboard numbers.

**Why is this needed**:
I am a member maintaining project https://github.com/unifi-poller/unifi-poller
We are creating a docker compose file to make it easier for folks using this to setup poller, influx and grafana.
We have several dashboards created and published on grafana.net (for example https://grafana.com/grafana/dashboards/10414)
We would like to be able to provision N number of dashboards by specifying the numbers (e.g. 10414, 10417) and have these provisioned from the latest version.

**Comment by scyto** [comment]
I also guess we would need to be able to specify a datasource for the dashboards to use too..

**Comment by davidnewhall** [comment]
Agreed. Would love to see an ability to fully-provision a grafana interface (data source and dashboards) while building a Docker installation. Thanks!

**Comment by marefr** [comment]
Since importing a dashboard from grafana.com (that requires variables/data source to be selected) is only supported thru the UI today a logical first step would be to support importing a dashboard (originating from grafana.com or exported for public use) thru the HTTP API. A logical next step could be supporting provisioning of dashboard (originating from grafana.com or exported for public use), but still reading them from the file system .

A step after these could potentially target this feature request of reading directly from grafana.com, but it's related to support more sources than file system in provisioning which we have no current plans working on in the short term.

**Comment by bertysentry** [comment]
We want this too. We're about to publish 25 dashboards that are tightly coupled, and it's a pain for us to export, publish and maintain, but most importantly, it's a nightmare for end users to import!

**Comment by scyto** [comment]
I assume this means this feature https://github.com/grafana/grafana/issues/27059 only works with type:file - there is still no type:<grafana.com:ID>

**Comment by marefr** [comment]
@scyto correct
