### ISSUE TITLE
Grafana brower error

### ISSUE THREAD

**Issue by karamjeetkaurpreeti** [grafana/grafana#27052]
**What happened**:I had grafana 7.1.0 but now i was installing 6.2 version.after installing both are not working.I have getting below error
If you're seeing this Grafana has failed to load its application files

1. This could be caused by your reverse proxy settings.

2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath

3. If you have a local dev build make sure you build frontend using: yarn start, yarn start:hot, or yarn build

4. Sometimes restarting grafana-server can help
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:6.2 and 7.1
- Data source type & version:
- OS Grafana is installed on:desktop
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
You'll need to fill in our issue template, most importantly how to reproduce. Otherwise, there's nothing we can do about this. I also suggest you consult our community [forums](https://community.grafana.com) or [Slack](http://slack.raintank.io), since it looks more like you need support, than having an actual bug. We use GitHub for bug reports and feature requests.

**Comment by karamjeetkaurpreeti** [comment]
I have updated the template
