### ISSUE TITLE
How do I do raw query plot on grafana ?

### ISSUE THREAD

**Issue by ajijohn** [grafana/grafana#2706]
I'm new to this , and wanted to just display raw values i.e  date, value. I'm using influxdb. All the graphs point to statistical functions. Is it possible to see a line plot?

**Comment by torkelo** [comment]
sure, just specify a group by time that is the same or lower than what you write data then you will get raw data. 

You can also switch to text editor mode and remove the mean(value) and specify just value , be aware that if you remove the group by time and get raw data you can easily overload your browser when viewing large time ranges due to influxdb returning millions of points
