### ISSUE TITLE
Prometheus: Use POST http method for template variable queries when possible 

### ISSUE THREAD

**Issue by david-ducos-percona** [grafana/grafana#27134]
**What happened**:
When using template variables, I realized that the request was being send using GET instead of the configured for the datasource which was POST.

**What you expected to happen**:
To use the datasource HTTP method, which in my case was POST

**How to reproduce it (as minimally and precisely as possible)**:
Configure a datasource with POST as HTTP method, I used Prometheus 
Create a new variable template using any query
Check the console of your browser how the request are being made.

**Anything else we need to know?**:
I realized of this issues as I have hundreds of servers, and I started to see "failed to fetch" when I used the variable with hundreds of host as parameter in another variable template.

**Environment**:
- Grafana version: 6.7.4
- Data source type & version: Prometheus 2.16
- OS Grafana is installed on: docker
- User OS & Browser: Mac & Chrome
- Grafana plugins: 
camptocamp-grafana-prometheus-alertmanager-datasource
digiapulssi-breadcrumb-panel
grafana-piechart-panel
grafana-polystat-panel
grafana-worldmap-panel
jdbranham-diagram-panel
natel-discrete-panel
petrslavotinek-carpetplot-panel
vertamedia-clickhouse-datasource
yesoreyeram-boomtable-panel

**Comment by aocenas** [comment]
So I assume we can use POST where it can be used which is only for the labels but as label values query do not support post there is not much we can do about that. That would be a feature request on prometheus side.

**Comment by cameronkerrnz** [comment]
I stumbled across this as being particularly painful when you have multi-value variables that have All enabled. In my case, I had a query such as the following:

`node_memory_MemTotal_bytes{app="$app",env="$env",instance=~"$instance"} - node_memory_MemFree_bytes{app="$app",env="$env",instance=~"$instance"} - node_memory_Cached_bytes{app="$app",env="$env",instance=~"$instance"} - node_memory_Buffers_bytes{app="$app",env="$env",instance=~"$instance"}
`

app, env and instance were drop-downs, with instance being a multi-value drop-down (the node running node_exporter). Instance was defined as follows:

`label_values(node_exporter_build_info,instance)
`

When instance was 'All' the query being sent grew in size proportional to the number of nodes in my fleet (not in that combination of app/env, which in this case only gives 8 instances)

You can see this reasonably clearly in the query inspector.

WORKAROUND 1:  Set the 'Custom all value' to be `.*`. This works because the Custom all value is not escaped, so regex characters are passed through and available for use in PromQL queries (eg. in `instance=~"$instance"`)

You can verify this in the query inspector.

WORKAROUND 2: (probably this is actually less of a workaround and more of case of how it should be done). Change the definition of the label_values query for the 'instance' variable so that it includes $app and $env.... but I'm unsure of how to do this at this time.

`label_values(node_exporter_build_info{app="$app",env="$env"},instance)
`
