### ISSUE TITLE
FeatureRequest: Alerting UI for viewers is unclear and suggests that they have the capability to edit alerts

### ISSUE THREAD

**Issue by mccollam** [grafana/grafana#27166]
**What would you like to be added**:

A change to the alert view for non-editor users to remove the "Apply" and "Save" buttons from the UI or otherwise make it clear that the user is unable to persist any changes to the alert.

**Why is this needed**:

Currently, a viewer who clicks into an alert (e.g. from the alert list panel) will be presented with the full editing view of the panel.  If the user then makes a change to the alert (e.g. changing the threshold) they can hit "Apply" and be taken back to the dashboard where the change will have apparently been made.

The change is not *actually* made (as can be seen by changing a threshold and looking at the state of an alert) and when the user goes to save the change an error is displayed.  But it causes confusion that a viewer can make this change and hit "Apply" to start with.

**Comment by hugohaggmark** [comment]
Thank you @mccollam I think we're doing a lot of design work concerning the Arleting UI. Is Ronalds suggestion already considered @jessover9000 ?

**Comment by jessover9000** [comment]
@hugohaggmark Ronald is talking about alert panels, which are unrelated to the Alerting UI I'm working on (=plugin for Grafana Cloud Metrics with Prometheus). I think there are two issues here: 
1. An issue with the panel edit in general, because I have read a similar complaint somewhere already about the panel edit and the "Apply" button being misleading. In the original design for the panel edit the button didn't say Apply but Preview. That label would be much clearer in communicating that the user isn't actually saving anything when clicking the button, so maybe that could be the first change.
2. An issue with feedback of alert panel editing capabilities. If a user doesn't have permissions to edit an alert, the panel edit should give clear visual feedback that any changes the user makes there aren't going to be saved. That might need a bit more thinking though, I'm not sure whether we reflect editing permissions in the panel edit at all currently.

**Comment by hugohaggmark** [comment]
thank you for clarifying that @jessover9000

**Comment by peterholmberg** [comment]
clicking a alert rule in the alertlist panel will take the user to viewPanel instead of edit since it was, https://github.com/grafana/grafana/pull/31872
