### ISSUE TITLE
Sync update of dependent variables

### ISSUE THREAD

**Issue by madshall** [grafana/grafana#2722]
Hi,

I'm passing values for two variables as URL params. The issue is that the second variable depends on the first one and in this case `promises.push` and `return $q.all(promises)` don't really do the job in `/public/app/features/templating/templateValuesSrv.js` because the response for second call comes back first and then the response and callback for the first call resets the second variable dropdown. The suggestion is to use chained promises insted.

**Comment by toni-moreno** [comment]
Hi @torkelo . We have impact on production environment due to this issue.  And I've reviewed the code  that produces this error.

https://github.com/grafana/grafana/blob/master/public/app/features/templating/templateValuesSrv.js#L48-L58

If I'm not wrong it seems like after load a Variable from URL it does a update for the other variables.

IMHO this update done after every variable load from URL has no sense to me . 

Correct me if I'm wrong , there is three ways to use template variables.

* Interactively  ( updating with the mouse the values in combos) : in this case __autoUpdateOptions__ the other variables is needed and never will use URL parameters isn't it?

* Non interactive: Loaded all variables from URL : ( useful  if you need pass a URL to share with other users ) . In this case you have usually ALL variables in the URL , so you don't need the __autoUpdateOptions__ to reload all the other values on any variable load , you should only substitute them on the dashboard JSON. Isn't it? 

* Load from URL with variables and after worked interactively: in this case you need you need __autoUpdateOptions__ when selected variables from combos but not in first load  (in the init function https://github.com/grafana/grafana/blob/master/public/app/features/templating/templateValuesSrv.js#L23 ) . Isn't it? 

IMHO I think that this autoupdate when loading variables form URL are giving us more headaches than issues solutions.

What do you thing about?

**Comment by torkelo** [comment]
@toni-moreno since variables depend on each other and you do not need to specify all variables in URL some kind of update is needed. Also the template variable values might need to be updated after url update. The problem is the cascade update I think. The code for this is pretty complex and there are many scenarios to think about. But I agree it needs to be fixed.

**Comment by toni-moreno** [comment]
@torkelo I agree that update is needed if variables depend on each other.

But current implementation ( autoupdate on URL variables found) give us a solution to a much improbable scenario, (scenario where somebody can write by hand the URL and variables and forgot some of them) , while a highest probable scenario (somebody wants view a dashboard with the exact URL with all variable values ) are now failing.

Perhaps the full solution is too difficult to fix now, but I suggest as a temporal workaround disable auto Update when passed url-variables to disserve/prejudice a minor number of users.

What do you think?
