### ISSUE TITLE
Can not get resource metics data from Azure China

### ISSUE THREAD

**Issue by macropan** [grafana/grafana#27243]
**What happened**: All resource metric data are NULL.

**What you expected to happen**: show the graph of resource metric

**How to reproduce it (as minimally and precisely as possible)**: configurate azure monitor for Azure china 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0+
- Data source type & version: Azure monitor for Azure China
- OS Grafana is installed on: CentOS 7
- User OS & Browser: MACos & Chrome
- Grafana plugins: N/A
- Others:
![image](https://user-images.githubusercontent.com/6326663/91426821-9706e400-e88f-11ea-845a-ab95b104dc5b.png)

**Comment by xlson** [comment]
@daniellee what team/person would be best for looking into this?

**Comment by kylebrandt** [comment]
I think the problem is with the following:

https://github.com/grafana/grafana/blob/7d72837d4079406b59b29022ec843a65606191d7/pkg/tsdb/azuremonitor/azuremonitor-datasource.go#L219-L235

We loop through, only looking for the constant path "azuremonitor". However, in this case we want a different route as defined in the plugin.json for the plugin:

https://github.com/grafana/grafana/blob/611d416f91968f451c952988f08d2111b1948e49/public/app/plugins/datasource/grafana-azure-monitor-datasource/plugin.json#L77-L91

So I think this should be done by selecting the route based on cloudname. So I think should be like application insights where it has this method:

https://github.com/grafana/grafana/blob/master/pkg/tsdb/azuremonitor/applicationinsights-datasource.go#L238-L255

https://github.com/grafana/grafana/blob/611d416f91968f451c952988f08d2111b1948e49/pkg/tsdb/azuremonitor/applicationinsights-datasource.go#L210-L214
