### ISSUE TITLE
Grafana 7.1.x break dashboards on legacy IOS devices

### ISSUE THREAD

**Issue by bisand** [grafana/grafana#27264]
I use an old iPad 2 (iOS 9.3.5) to display temperature and other sensor data from my house. After upgrading Grafana to 7.1.x the dashboards stopped to work in the iPad. It is working on all other devices I have laying oround, but not on iOS 9.3.5. The iPad is no longer possible to upgrade, so I hope you are able to find a solution to my problem.

I would like to use Grafana for may years, and like to stay up to date with the versions.

**What happened**:
After upgrading from Grafana 7.0.6 to 7.1.x the iPad 2 is no longer able to display the dashboards.

**What you expected to happen**:
I expected it to work!

**How to reproduce it (as minimally and precisely as possible)**:
- Use Grafana 7.0.6 and run your dashboards on an old iPad 2 (iOS 9.3.5). This should work.
- Upgrade to Grafana 7.1.x (7.1.5) and run the dashboards on the same iPad 2. This should not work.

**Anything else we need to know?**:
The dashboard uses timeseries data from InfluxDB 1.8.1
A zip file containing the dashboard json file used in the examples is attahed below.

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: InfluxDB 1.8.1
- OS Grafana is installed on: Latest Docker image (grafana/grafana:latest) running on host with Ubuntu 20.04.1 LTS 
- User OS & Browser: iOS 9.3.5 and Safari 
- Grafana plugins: influxDB
- Others:

v7.0.6 - Last working version running on Safari.
![image](https://user-images.githubusercontent.com/376963/91557048-0afac800-e934-11ea-813b-9ac4d3f3fa37.png)

v7.0.6 - Last working version running on Kiosk App for iOS
![image](https://user-images.githubusercontent.com/376963/91557262-717fe600-e934-11ea-879e-c2e8a1a589bd.png)

v7.1.5 - Not working, running on Safari.
![image](https://user-images.githubusercontent.com/376963/91557032-ffa79c80-e933-11ea-849b-e3b91f9494a5.png)

v7.1.5 - Not working, running on Kiosk App for iOS
![image](https://user-images.githubusercontent.com/376963/91557348-a12eee00-e934-11ea-8dcf-2d2e7e6f651c.png)

Dashboard export file:
[dashboard.zip](https://github.com/grafana/grafana/files/5141899/dashboard.zip)

**Comment by torkelo** [comment]
what version of safari is this ipad running?

**Comment by bisand** [comment]
I think it's version 9 Mobile. Below you can find the user agent string:
`
Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1a
`
It is not possible to upgrade Safari or use another browser since Apple is not updating iPad 2 anymore.

**Comment by bisand** [comment]
I was able to do some simple debugging on the iPad using [ios-webkit-debug-proxy](https://github.com/google/ios-webkit-debug-proxy), and I got the following error message in the console when loading the dashboard:
```
ReferenceError: Can't find variable: Proxy 
(anonymous function) vendors~app.4141596c10e564d57dfb.js:2
```
Attached you can find the javascript file included in the error message.

[vendors-js.zip](https://github.com/grafana/grafana/files/5166728/vendors-js.zip)

**Comment by brandon3055** [comment]
I have also run into this exact same issue. I thought i finally had a use for my brothers old Ipad 2. So i made a wall mount and set it up to do nothing but display my grafana home page in full screen and it worked. It was rather slow if i ever had to interact with it and it did not support some third party panels but it did what i needed it to do. Until this update. Now its back to apple e-waste until a fix is available. Last night i tried jailbreaking thinking it may be possible to install a more modern browser but i didn't have much success.

**Comment by zoltanbedi** [comment]
Hi @bisand that debugging was really helpful although I might say that we probably won't support safari 9 from Grafana 7.1. Because I really liked your setup I would like to help. I've added a polyfill for Proxy in my branch https://github.com/grafana/grafana/tree/zoltan/proxy-polyfill if you checkout this branch and build it then it might work in safari 9 again. I can't say it for 100% sure but if the problem was the Proxy object then it probably will. I'm going to close this issue now because as I said we don't support safari 9. If you need more help you can find me in our public slack channel.

**Comment by bisand** [comment]
Thank you @zoltanbedi, I will try to build and test your branch as soon as I can, and report back with the results.

**Comment by JSAnyone** [comment]
I have the same problem, I also hoped I could use my old iPad for Grafana.
@bisand, did zoltanbedi’s branch work?

**Comment by bisand** [comment]
@JSAnyone, I tried it a couple of times without any luck. Unfortunately, I haven't had time to do more extensive testing or digging into the details. Feel free to do seome testing on your part, and let me know if you succeed.

**Comment by 1602** [comment]
I found this issue when trying to set up my old iPad as grafana dashboard and I believe this is quite a common use case because many of us have unused and outdated devices laying around, why not give them a second life as data displays?

As a web developer myself, I understand how painful it is to support old devices, so maybe sticking with 7.0.6 is the only option, it would be great if this version was mentioned as the last one supporting legacy iPads in the docs or in the error screen. Speaking for myself - it looks like I will be running an instance of grafana 7.0.6 just to be able to see data collected by my home automation zoo.

**Comment by romanovacca** [comment]
as of today (28 sept 2025) ipad running ios 10.3.3, work with grafana 7.2.2 and fails on 7.3.0 onwards
