### ISSUE TITLE
Cloudwatch: Add support for resolution of resource tags in alias

### ISSUE THREAD

**Issue by Alex-Richman** [grafana/grafana#27280]
Add support for using resource tags in the CloudWatch query alias.

See attached PR for details.

Example:
![2](https://user-images.githubusercontent.com/1280519/91644580-416c3c00-ea35-11ea-867a-61fbcb02be7a.png)

**Comment by kmoberg** [comment]
This _should_ be a no-brainer. Presenting instance IDs that change constantly, makes no sense, when we all tag the resources that help us show what they actually are.

**Comment by macobo** [comment]
In https://github.com/grafana/grafana/pull/27281 @marefr said that:

> However, the referenced feature request #27280 haven't seen any activity/comments/upvotes, that together with the extra complexity, maintenance burden and possibly cost (performance and calls) makes it hard for us to accept this currently. 

This is baloney, here's a list of related or the same issue requests going back years:
- https://github.com/grafana/grafana/pull/8307
- https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/issues/14
- https://github.com/grafana/grafana/issues/13643
- https://github.com/grafana/grafana/issues/7294
- https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/issues/41
- https://community.grafana.com/t/cloudwatch-tags-as-alias/39931
- https://community.grafana.com/t/retrieve-values-for-tag-in-cloudwatch/9098
- https://community.grafana.com/t/seeking-to-retrieve-aws-cloudwatch-disk-volume-tags/7878
- And more (google for "grafana cloudwatch tags name")

See also reactions under the original PR.

As-is cloudwatch is pretty useless on grafana because what use are metrics without being able to distinguish or filter _what_ data is being displayed.
