### ISSUE TITLE
FROM dropdown shows template variables?

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2732]
(I think this issue is a bit similar to #2636)

I have a InfluxDB datasource in Grafana.

In the `FROM` dropdown, it seems to show my template variables, for some reason.

<img width="710" alt="screenshot 2015-09-14 03 00 33" src="https://cloud.githubusercontent.com/assets/243499/9837758/fbaf37b8-5a8c-11e5-8e9b-c19a73b0cd43.png">

This may actually be intended though - just thought I'd check with you?

**Comment by torkelo** [comment]
yea, its intended

**Comment by jgerschk** [comment]
I know this issue is closed, but I have a question, are template variables suppose to work from the from statement?

I see I can use regex in the from direct in InfluxDB 9.0, but seem like Grafana, at least my version does not work, errors.

eg:

SELECT last(value) FROM /$FS/ WHERE "host" =~ /$System/ AND $timeFilter GROUP BY time($interval), "host"

Am I wrong to assume we can use template variables in the from?

**Comment by torkelo** [comment]
@jgerschk yes, to my knowledge InfluxDB 0.9 supports regex in the FROM clause. And it works fine in grafana.

**Comment by jgerschk** [comment]
@torkelo regex within grafana in the from seem to work fine, I agree there, but my issue is using a template variable that seems to not work.

Am I missing something?

SELECT last(value) FROM /$FS/ WHERE "host" =~ /$System/ AND $timeFilter GROUP BY time($interval), "host"  -- give me an error parsing the query.

however

SELECT last(value) FROM /servera/ WHERE "host" =~ /$System/ AND $timeFilter GROUP BY time($interval), "host"  -- works just fine.

**Comment by torkelo** [comment]
what is the value of $FS variable?  You can inspect the raw query being sent to InfluxDB in chrome dev tools (f12) network tab.

**Comment by jgerschk** [comment]
That really seems to be the problem.  The value of $FS.

It is a unix file system so it starts with /  for /opt /boot, etc....

That seems to be the problem.

The query it looks like that is being sent is this

q=SELECT+last(value)+FROM+%2F%2Fopt%2F+WHERE+"host"+%3D~+%2Fvmux14sinfluxdb01%5C.cqginc%5C.com%2F+AND+time+>+now()+-+2d+GROUP+BY+time(5m),+"host"%0ASELECT+max(max)+FROM+"%2Fopt"+WHERE+"host"+%3D~+%2Fvmux14sinfluxdb01%5C.cqginc%5C.com%2F+AND+time+>+now()+-+2d+GROUP+BY+time(5m),+"host"

Having said that, if you manually type in /opt it does work, but using $FS does not. Could I still be doing something wrong here?

![fs](https://cloud.githubusercontent.com/assets/7864285/10338950/75205b38-6cce-11e5-9069-f16db417ba91.png)

![fs2](https://cloud.githubusercontent.com/assets/7864285/10338978/a2707582-6cce-11e5-83b3-22da52fdf625.png)

**Comment by jgerschk** [comment]
I did manage to get it to work, not the most usable way though.

SELECT last(value) FROM /\$FS/ WHERE "host" =~ /$System/ AND $timeFilter GROUP BY time($interval), "host"

Because we have an / we have to do /\$FS/ and it seems to work.

You can't do that in the editor per say, you have to use the line editor though to make it work.

Not sure there is a way to have that work in the editor...
