### ISSUE TITLE
CloudWatch logs does not support creating template variables

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#27447]
**What would you like to be added**:
Add support for creating template variables using CloudWatch Logs . Either a VariableQueryEditor needs to be set to some component or a special query language needs to be supported like with metrics https://grafana.com/docs/grafana/latest/features/datasources/cloudwatch/#query-variable

**Why is this needed**:

**Comment by zopanix** [comment]
Hey, I have a very specific use case for this.

Currently using the ContainerInsights for EKS solution from AWS. When enabling these "metrics" I realised that most of the useful metrics are not stored in Cloudwatch Metrics, but in Cloudwatch Logs. Not being able to set variables from certain fields is a real problem.

With EKS, I want to be able to have a variable which is the pod name, which is currently impossible because we can't query the pod name from Cloudwatch Metrics (I know they have a dimension called "PodName" in the metrics, but it's poorly name, it should be named "PodNamePrefix") and Grafana won't let me query it from Cloudwatch Logs. Si it's currently impossible for me to dynamically retrieve the list of pod names for which I'm having "Metrics" in Cloudwatch Logs (for a specific time window).

Thx

**Comment by sunker** [comment]
FYI: A template variable query for loading log group names was recently added. See https://github.com/grafana/grafana/pull/50100

**Comment by sarahzinger** [comment]
@sunker do you know is it ok for us to close this or is this still an open issue?

**Comment by sunker** [comment]
We still don't support variable queries based on CloudWatch logs, so let's keep this open.

**Comment by sarahzinger** [comment]
What would this look like exactly? I'm able to save a cloudwatch logs query string (and partial query string) as a constant and use it in cloudwatch logs:
<img width="745" alt="Screenshot 2022-11-30 at 3 38 55 PM" src="https://user-images.githubusercontent.com/6620164/204903354-1a9a83f7-cfeb-4de3-91cf-3903d23a0249.png">

Are you thinking this would work differently or have additional functionality?

**Comment by sunker** [comment]
I mean we should have a CloudWatch variable query type called `CloudWatch logs` that simply renders the whole logs editor. That variable could for example return @message and you use some regex to extract for example `RequestId`. Then you can use that variable in your logs query targeting the query data handler.

**Comment by sarahzinger** [comment]
ah ok that makes sense, so we'd want to save the results of cloudwatch logs query to a variable, that makes sense. thanks for talking it out

**Comment by sunker** [comment]
Just adding some clarification here: 

* The CloudWatch Logs plugin code editor already supports template variables, meaning if you add for example a custom variable into your log query, it will be expanded 
* There is a template variable query for loading log groups. This variable can be defined as a single-valued or a multi-valued template variable that can be used in the log group selector in the CloudWatch logs editor. 
* The region field inside the CloudWatch logs editor supports template variables

That means all fields in the CloudWatch logs query editor supports template variables. I think it would be helpful if more template variable queries target CloudWatch logs were added. For example, we could add a query for loading log group fields. That variable could possibly be used in the following way:
```
fields $fields |
sort @timestamp desc |
```
Where $fields expands to @timestamp @message etc.
