### ISSUE TITLE
Changing default datasource to new default datasource changes already defined graphs to new default datasource

### ISSUE THREAD

**Issue by szop85** [grafana/grafana#2744]
Hey guys,

consider following scenario: I've setup a "default datasource" which I've used until now and also setup a few dashboards with different panels. Now I've add a new datasource to my setup which I want to use as the "default datasource" because it fits better. After changing to the "new default datasource" all of my "old" panels using the "new default datasource" now and are not available anymore sind the datasource changed. Is this considered a bug or a feature? In my opinion I wouldn't want to have changed existing panels/dashboards to the new default datasource.

Cheers,
Szop

**Comment by torkelo** [comment]
this is a feature, as otherwise it would not be possible to change the default without having to change all panels. 

But I can see that this is causing issues. Panels refer to a datasource using the datasource name (So changing name is also tricky, you can change the default data source name without having any affect on panels, but changing none default data source will require you to open all dashbords and update all panels).

There should probably be a dashboard admin tool to mass update panel datasource references.
