### ISSUE TITLE
min_refresh_interval not work for explore

### ISSUE THREAD

**Issue by F4ncyMooN** [grafana/grafana#27494]
**What happened**:
When I set min_refresh_interval=1m, and use explore page. I found the min refresh interval is still 5s.
![image](https://user-images.githubusercontent.com/16536745/92689885-78feb080-f372-11ea-86b2-c51a5136e06d.png)

**What you expected to happen**:
Should only show >= 1m refresh interval options.
**How to reproduce it (as minimally and precisely as possible)**:
As above
**Anything else we need to know?**:
No
**Environment**:
- Grafana version: 7.1.3
- Data source type & version: any
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS & Chrome
- Grafana plugins: Explore
- Others:

**Comment by elliotpryde** [comment]
Reproduced this in 7.2.0.

It looks like [RefreshPicker is using some default intervals](https://github.com/grafana/grafana/blob/6145bf77cf4462af04353001cd7eda369e15b235/packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.tsx#L48) since no intervals were passed into the component. Those default intervals aren't being validated by the [context service](https://github.com/grafana/grafana/blob/d633cc3c09a4d13ee994fe0cf46c3e46cdab32bd/public/app/core/services/context_srv.ts#L60) before being rendered.

I thought this could be an simple first PR, I'll raise one in a moment.

**Comment by elliotpryde** [comment]
My understanding is that `min_refresh_interval` is used to stop dashboards from sending too many queries to datasources, is that wrong?

If that's the case, should dashboards and the explore page have different minimum refresh intervals? `min_refresh_interval` comes under the `[dashboard]` section of the configuration file at the moment.
