### ISSUE TITLE
Alerting: Add option to set state to No Data when query execution fails 

### ISSUE THREAD

**Issue by BasvanH** [grafana/grafana#27566]
**What happened**:
When planned/scheduled maintenance on our data sources kicks in, we get **Alerting** alerts from the alarms with the error:
```
tsdb.HandleRequest() response error &{dial tcp   x.x.x.x:xxxx: connect: connection refused A 0xc0007aa810 [] []   <nil>}
```

**What you expected to happen**:
I would expect the absence of the data source would be scoped within the 'No data' class in alerts.

**How to reproduce it (as minimally and precisely as possible)**:
Have an alert set on a graph, set the interval to 1h. Take the data source offline, you will get the **Alerting** message after one minute.

**Anything else we need to know?**:
We considered taking Grafana offline during the maintenance, but when doing this we also need to access all of our screens to restart the browser.

**Environment**:
- Grafana version: v7.1.5 (9893b8c53d)
- Data source type & version: Mysql v8
- OS Grafana is installed on: Centos 7.8
- User OS & Browser: Windows & Chrome

**Comment by kylebrandt** [comment]
Since this is for planned maintenance, I do not think adding an option like this is a good solution. This is because this option would still be present during non-maintenance hours, and could result is not getting alerts for users when things are wrong.

Some work arounds:
 - Alerts can be paused. I don't see a UI option to do this in bulk, but maybe that is something we can add?
 - There is an admin API call to pause all alerts: https://grafana.com/docs/grafana/latest/http_api/alerting/#pause-all-alerts (which can also unpause all alerts). Although if you have some paused before pausing all, those would become unpaused when you unpause them all.
 - Finally, you could edit grafana's configuration to have `execute_alerts = false` and restart it, and then revert after maintenance and restart again. But I'm not sure if a restart would still require you to reset your screens.

Do any of those options help?

In general, I think the main feature for this in the future should be silences https://github.com/grafana/grafana/issues/5856

**Comment by BasvanH** [comment]
The alert pausing is definitely something that could work. We could trigger this remotely via the API, but a build in scheduler would be more desired. This keeps things in sight of the UI people.

With restarting grafana we most definitely need to restart the screens as of authentication has expired.

**Comment by kylebrandt** [comment]
Glad the pausing will work. Part of https://github.com/grafana/grafana/issues/5856 of recurring silences, so closing this issue in favor of that one.
