### ISSUE TITLE
Right side of bar gauges cut-off

### ISSUE THREAD

**Issue by LuckyMallari** [grafana/grafana#27723]
**What happened**:

All **vertical** Bar Gauges are cut off on the right side.

![image](https://user-images.githubusercontent.com/6183345/93994804-2a272280-fd45-11ea-8260-39636e9de015.png)

![image](https://user-images.githubusercontent.com/6183345/93995048-5f337500-fd45-11ea-98d4-0a8614135f06.png)

![image](https://user-images.githubusercontent.com/6183345/93995100-6fe3eb00-fd45-11ea-9ca8-fa5a2fcc288a.png)

![image](https://user-images.githubusercontent.com/6183345/93995509-f13b7d80-fd45-11ea-9423-03e012993a11.png)

Only happens on the last element.

**What you expected to happen**:

Entire width of the last div should be visible. Seems like the width calculation does not take into account the padding. 

**How to reproduce it (as minimally and precisely as possible)**:

Add bar gauges, set to vertical.

**Anything else we need to know?**:

Reproducible on both Chrome and Edge

**Environment**:
- Grafana version: v7.2.0-beta2 (8406a5d319)
- Data source type & version: N/A
- OS Grafana is installed on: Debian
- User OS & Browser: Chrome
- Grafana plugins: Vanilla
- Others:

**Comment by therealcodlord** [comment]
I am getting this since upgrading to v7.2.0. I think this is a vertical scrollbar which is showing and cutting off the right side of all bar gauge panels.

In my Ubuntu Firefox 81.0 the scrollbar is visible as the grey but in other browsers such as Chrome the bar is the same colour as the background so it cuts off the right-side of the bar gauge. Here is where it's visible:

![bar](https://user-images.githubusercontent.com/38720757/94920309-f6b76700-04ad-11eb-865e-a6570c1edb49.png)

If I inspect the HTML I can change the style:
overflow: hidden scroll
to:
overflow: hidden hidden

And the bar goes away and the panel looks as it should.

**Comment by LuckyMallari** [comment]
I fixed mine differently:

`.panel-content {
  padding-right: 0;
}
`

**Comment by torkelo** [comment]
Unable to replicate this in latest chrome
