### ISSUE TITLE
More verbose logging for redis sessions

### ISSUE THREAD

**Issue by slick666** [grafana/grafana#2776]
When starting grafana 2.1.3 on a box where redis is the configured session management and the redis service is stopped...

Grfana fails to start but doesn't put anything into the log file.

Even with the logging set to "Debug" it's still a silent failure.

**Comment by woodsaj** [comment]
as mentioned in #3272, i think we just need to add the suggested code to catch panics and write them to the configured log handlers before exiting grafana.

The issue here isnt that the app panics, just that panics only get sent to stdout/stderr which will be lost when running grafana as a daemon depending on how this is done.

**Comment by xyntrix** [comment]
There is no debug info around using redis as a session store.  I have a password in my redis store -- does the plugin support that? There's no documentation around that property, but it does exist in the redis go-macaron class so.. maybe?

Adding a redis session store seems to crash grafana and because there's no debug data, I'm not really sure what's going on.  

As this issue has been open for 1.5 years, is it possible this will be looked into any time soon?

**Comment by xyntrix** [comment]
After much tracing of runtime and digging through the code, I figured out I needed to provide the config for redis as such:

provider = redis
provider_config = addr=1.2.3.4:6379,pool_size=1000,db=grafana,password=SECRET

..do wish there was more debug logs on what the session states are doing.
