### ISSUE TITLE
Explore for elasticsearch logs showing fewer logs than what exists

### ISSUE THREAD

**Issue by ebabani** [grafana/grafana#27777]
We are using the grafana elasticsearch datasource in order to explore logs.

**What happened**:

Sometimes a log query returns very few records, when we know that more logs are available during that time frame.

![image](https://user-images.githubusercontent.com/2236882/94203880-38cd2100-fe8e-11ea-8928-6a1558466277.png)

**What you expected to happen**:

We expect to see 500 log lines (according to the ES results) but instead only see very few, sometimes only 1-2.

**How to reproduce it (as minimally and precisely as possible)**:

This issue seems to be related to elasticsearch logs that have an `id` field. By default we do not set an `id` but some application logs can set one. 

Repro: On Elasticsearch, create log documents, some with an `id` field and some without. Querying over those documents will cause Grafana to only show logs from documents that have a unique id field value.

**Anything else we need to know?**:

The issue seems to be in the following code:

1. getIdFields will return an a FieldWithIndex object because at least one of the documents has a field named `id`
https://github.com/grafana/grafana/blob/19c14281033c36c98a5193b6bb7179a2108e1cdb/public/app/core/logs_model.ts#L326

2. The `uid` field will be set because the idField object exists https://github.com/grafana/grafana/blob/19c14281033c36c98a5193b6bb7179a2108e1cdb/public/app/core/logs_model.ts#L386

3. Logs will be deduplicated since the `uid` field is set. This will cause most of our logs to not be shown
https://github.com/grafana/grafana/blob/19c14281033c36c98a5193b6bb7179a2108e1cdb/public/app/core/logs_model.ts#L391

This behaviour seems to have been introduced in https://github.com/grafana/grafana/pull/18994

**Environment**:
- Grafana version: Grafana v7.0.6 (9f4a172a76)
- Data source type & version: Elasticsearch 70+
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome OSX
- Grafana plugins: None
- Others:

**Comment by aocenas** [comment]
The code is there because there was need for deduplication of logs line in case they are absolute duplicates in the sense that for example in loki because of replication of the ingesters the same log line could be ingested 2 times and got duplicated (this is different from when system creates 2 log lines with the same message). The solution for that was to create an ID for the log lines and if they have the same id then deduplicate them (again separate thing from the dedup switch).

I think we just shouldn't use `id` as a name for it as it is clashing with user defined id field maybe something like `grafana_id` or what ever to prevent clashing would solve this.

**Comment by ivanahuckova** [comment]
This was fixed in https://github.com/grafana/grafana/pull/29421 where we remove unnecessary deduplication.  https://github.com/grafana/grafana/pull/29421 was part of 7.4-beta release.
