### ISSUE TITLE
Not able to add datasource after grafana rollback from 7.1.3 to 6.6.2

### ISSUE THREAD

**Issue by VeenaThimmegowda** [grafana/grafana#27837]
**What happened:** After the downgrade of grafana from 7.1.3 to 6.6.2 not able to add any datasource.

**What you expected to happen:** Even after downgrade we should be able to add datasource.

**How to reproduce it (as minimally and precisely as possible):**

1. Install grafana 6.6.2 using helm chart
2. Upgrade grafana  to 7.1.3 version
3. later rollback from 7.1.3 to 6.6.2
4. Try to add datasource.
After downgrade datasource addition is failing with the below error. 

lvl=eror msg="Failed to add datasource" logger=context userId=1 orgId=1 uname=admin error="UNIQUE constraint failed: data_source.org_id, data_source.uid"

**Anything else we need to know?:**

**Environment:**

Grafana version: 7.1.3
Data source type & version: 
OS Grafana is installed on: 
User OS & Browser: n/a
Grafana plugins: 
Others: n/a

**Comment by VeenaThimmegowda** [comment]
Hi,

The workaround currently we are using to solve the issue is given below.
Before we do rollback we are manually dropping the unique index from data_source table .
**DROP INDEX `UQE_data_source_org_id_uid` on data_source;**

By using above workaround after rollback we are able to add datasource but it leads to one more issue i.e mentioned below.
Workaround with rollback worked, later we upgraded the grafana chart from 6.6.2 to 7.1.3 we observed that **UQE_data_source_org_id_uid** unique index was not added back.
If  index **UQE_data_source_org_id_uid** is not added back, will it cause any effects on grafana functionality.

So please confirm the workaround we are using correct or not.

**Comment by aocenas** [comment]
How did you exactly rolled back the grafana version? Mainly what did you do with the DB? Did you also restore from a backup that was done before the upgrade?

**Comment by VeenaThimmegowda** [comment]
Using Helm rollbck cmd we are rolling back to grafana previous version chart.
No we are not taking any backup before we rollback/downgrade from 7.1.3 to 6.6.2 chart.

**Comment by aocenas** [comment]
@marefr do you know what is the way to do downgrades? As far as I know we do not have down DB migrations so what ever got changed in the 7.1 would still be in the DB creating issues after downgrading back to 6.6 is that right?

**Comment by marefr** [comment]
@aocenas yes, what ever got changed in the 7.1 would still be in the DB creating issues after downgrading back to 6.6.

We always recommend to do a [backup before upgrading](https://grafana.com/docs/grafana/latest/installation/upgrading/#backup). 

If you upgrade again you should make sure you have the `UQE_data_source_org_id_uid` index. You should be able to see the migration log over the datasource uid related migrations.
```sql
select * from migration_log where migration_id = 'Add uid column'
select * from migration_log where migration_id = 'Update uid value'
select * from migration_log where migration_id = 'Add unique index datasource_org_id_uid'
```
Since you've manually removed the `UQE_data_source_org_id_uid` index I would suggest deleting that migration to make sure it will be run again next time you upgrade:
```sql
delete from migration_log where migration_id = 'Add unique index datasource_org_id_uid'
```
All of these manual changes to the database is not something we recommend, but we understand they may be needed in these kinds of situations where we don't provide a good downgrade story.

**Comment by fearless11** [comment]
Need to add double quotes，it works.
drop index "UQE_data_source_org_id_uid";
