### ISSUE TITLE
Option for folder names on Dashboard lists

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#27849]
**What would you like to be added**: Please, add an option for Dashboard list panel which allows to turn off the folder name labels. (These tags are new, released in version 7.2.)

![image](https://user-images.githubusercontent.com/2911588/94401576-1a577600-016b-11eb-8d30-cdd97958d1de.png)

**Why is this needed**: Displaying the label carries unnecessary information and increases the height of the box.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
