### ISSUE TITLE
Flux datasource: Documentation mentions v.timeRangeEnd to use as end time, actually is v.timeRangeStop

### ISSUE THREAD

**Issue by coussej** [grafana/grafana#27866]
docs at https://grafana.com/docs/grafana/latest/features/datasources/influxdb/ mention v.timeRangeEnd 
![image](https://user-images.githubusercontent.com/9944663/94465633-7d272c80-01c0-11eb-818c-3fd767ad0567.png)

this does not get replaced in the query, and an error is returned
![image](https://user-images.githubusercontent.com/9944663/94465719-9e881880-01c0-11eb-9534-df601ef49b6a.png)

When using  v.timeRangeStop it works as expected.

Grafana 7.1.5

**Comment by torkelo** [comment]
@oddlittlebird something the docs squad can take a look at ?

Maybe creating a GitHub docs project is a good idea to visualize & prioritize docs backlog & work in-progress 
And by project I mean one of these, https://github.com/grafana/grafana/projects. EIther under the grafana repo or under the grafana org (Org projects can have issues from many different repos)

**Comment by oddlittlebird** [comment]
We have a Monday.com board that we are using to organize our work. Since we work in multiple repos, it does not make much sense to have GitHub project boards.

And this is something that we would need an SME to help us with. There are several things that could be wrong here. Is it a bug in the InfluxDB data source? Is it a documentation update? If documentation, then what should the doc update be? 

This sort of issue needs to be driven by the devs that work on the data source. We're happy to update the documentation once the questions above are answered.
