### ISSUE TITLE
Grafana change the date picker to one view

### ISSUE THREAD

**Issue by acc-bert** [grafana/grafana#27928]
See the post [37313](https://community.grafana.com/t/grafana-change-the-date-picker-to-one-view/37313).

**Comment by torkelo** [comment]
Thanks for the feedback will take into account next time we update design of the time picker

**Comment by torkelo** [comment]
Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
