### ISSUE TITLE
Variables: Add timezone as global template variable 

### ISSUE THREAD

**Issue by DrMichael** [grafana/grafana#28024]
**What would you like to be added**:
I would like to have the timezone in which the data is displayed available in queries. E.g. when using date_trunc('day', ...) in psql, it gets truncated to midnight of the database server timezone, but displayed in the display timezone.

**Why is this needed**:
To correct above mentioned behaviour one needs the display timezone available in queries.
Or to be able to set the psql client timezone.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
