### ISSUE TITLE
Grafana Cloud Alerting: Alertmanager secrets should only be visible to Admins

### ISSUE THREAD

**Issue by runerys** [grafana/grafana#28110]
**What happened**:
When the alertmanager config is shown, secrets like api-keys and secret urls are displayed in clear text to both Editors and Admins.

**What you expected to happen**:
Only users with Admin role should see the secrets.

Editors are presented a read-only view, and here the secrets should be masked. This is done here: https://alertmanager-us-central1.grafana.net/alertmanager/#/status

Example config paths: 
receivers / opsgenie_configs / api_key
receivers / slack_configs / api_url

**Environment**:
- Grafana version: Grafana Cloud Standard
- Grafana plugins: Grafana Cloud Alerting

**Comment by gotjosh** [comment]
Hi @runerys this is not specific to OSS Grafana but instead of Grafana Cloud. We're aware of it and are working internally to prioritise it and make it better.

I'm going to close this for now given that OSS Grafana receives a high number of issues and there's nothing we can do here, but please submit a support ticket through Grafana Cloud if you have the chance.

Thank You!
