### ISSUE TITLE
Automatic Graph Completion Upon Activation

### ISSUE THREAD

**Issue by wengchen93** [grafana/grafana#2813]
Hi,

Is there a feature which automatically creates a graph or graphs displaying the metric queries when Grafana is activated (so the manual clicking "create Graph" and typing in metrics can be skipped)? If not which file in Grafana should I look into and modify to enable this?

Thanks!

**Comment by torkelo** [comment]
"graph displaying metric queries"? 

do you want a grafana dashboard to read your mind and automatically build you dashboards with nice looking and meaningful Graphs for your hundreds of thousands of metric series? 

Yea, put that code in the magic.go file :) Joking aside, we are looking at ways for people to share dashboards and to have dashboard repository so that people can quickly reuse someone else dashboard, this is useful for metric relating to infrastructure and standard applications (mysql, cassandra, redis, etc). But for custom application metrics its harder to build generic dashboard templates, you will have to build those yourself.

**Comment by torkelo** [comment]
Oh, If you have a concrete idea for what how to do what you talking about would work, please let know (how to automatically build meaningful dashboards)
