### ISSUE TITLE
Use 'Prefer' header on requests to Azure Monitor datasource

### ISSUE THREAD

**Issue by dylan-asos** [grafana/grafana#28199]
**What would you like to be added**:

On HTTP requests to the Azure Monitor data source, include a request header

Prefer: wait=time-to-wait-in-seconds

Pass through setting as configured by _dataProxy.timeout_

**Why is this needed**:

As per the documentation, this allows you to set the maximum timeout when calling the API. 

https://dev.loganalytics.io/documentation/Using-the-API/Timeouts

This will help ensure timeouts are correctly honoured across system-boundaries.

**Comment by dylan-asos** [comment]
Which I think is just this https://github.com/grafana/grafana/compare/master...dylan-asos:master

Shall raise PR if this looks sensible

**Comment by peterholmberg** [comment]
Please open a PR :smile:

**Comment by sarahzinger** [comment]
@dylan-asos just going through some old Azure issues and wanted to see are you still running into this problem?

**Comment by sunker** [comment]
We've closed this issue since it needs more information and hasn't had any activity recently. We can re-open it after you you add more information. To avoid having your issue closed in the future, please read our [CONTRIBUTING](https://github.com/grafana/grafana/blob/main/CONTRIBUTING.md) guidelines.

Happy graphing!
