### ISSUE TITLE
Add visual clue to differentiate a Graphite node vs an actual metric when building queries

### ISSUE THREAD

**Issue by jaimegago** [grafana/grafana#2822]
When user build queries there is no clue in the roll menu that pops out as to what is a graphite node and what is an actual metric. Something as simple as a different color or maybe an arrow icon pointing to the right for graphite nodes. I think the folder icone vs file in the stock graphite dashboard is useful. This is somewhat related to https://github.com/grafana/grafana/issues/347
For example when building a query for foo.bar.baz.metric1 and there is foo.bar.metric2 it could be something like.:
## 

foo >
## 

bar >
## 

baz >
metric2

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
