### ISSUE TITLE
Azure Monitor data source to support annotation range

### ISSUE THREAD

**Issue by scschneider** [grafana/grafana#28275]
**What would you like to be added**: The ability to pass in timeEnd when using the Azure Monitor data source to support annotation ranges.

**Why is this needed**: Some annotated events occur for a period of time and would be very useful to be able to specify an events entire time range.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
