### ISSUE TITLE
Elasticsearch templating fails if term contains whitespace

### ISSUE THREAD

**Issue by felixbarny** [grafana/grafana#2828]
According to https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Fields, when searching for a term that contains whitespaces, the term has to be quoted. Grafana currently fails to do this.

Example:
Template Variable: `host`
Value: `my cool server`

When referencing `$host` in a query like `name: response_time AND host: $host` the resulting query sent to ES is `"query":"name: response_time AND host: my cool server` rather than `"query":"name: response_time AND host: \"my cool server\"`.

The workaround is to enter this query: `name: response_time AND host: \"$host\"`. Note that quotes are not escaped here by grafana which could lead to other bugs.

**Comment by felixbarny** [comment]
The workaround fails when selecting `All` which results in `AND host: "(my cool server OR my other server)"`

**Comment by torkelo** [comment]
This is a partial fix, as using terms with whitespace will now work for All or mutli values (because then the lucene format will be used which will quote the values). 

But it will not work if you only have a single value selected! Because then no multi format is applied, so the raw value will be replaced (remember the templating system is a text substitution system). 

To fix so that both single and multi values work will require a major overhaul and change to the template system (would be a good thing), so that the multi and all formats are more context specific and not only applied on multi values but the formats are applied depending on where the variable is used, is it used in elasticsearch query then encode values as lucene condition, etc

**Comment by felixbarny** [comment]
Is there already a issue for the full fix? Any ETA? Will it be included in 2.5?

**Comment by torkelo** [comment]
@felixbarny no, as I said it will require a major overhaul of the templating system, or some clever workaround, no ETA for that

**Comment by felixbarny** [comment]
Would it be possible to always use the lucene format, even if only one value is selected?

**Comment by torkelo** [comment]
@felixbarny not currently as there is multi or all formats are not applied to single values. But maybe I am overstating the change involved. Requires more analysis for what change is best
