### ISSUE TITLE
Migrate from Yarn to NPM 7.x

### ISSUE THREAD

**Issue by stevenvachon** [grafana/grafana#28304]
Yarn 1.x is dead and 2.x [conflicts the ecosystem](https://medium.com/@njbmartin/whats-the-problem-with-yarn-2-ca59e3fabc9f) by removing `node_modules/`. Any plugin architecture should use `peerDependencies` for at least something, and NPM 7.x installs them. The only place I'm aware of that we need this is in [@grafana/eslint-config](https://github.com/grafana/eslint-config-grafana).

* Every _yarn.lock_ file will need to be replaced with a _package-lock.json_ file
* We'll have to use [lerna](https://npmjs.com/lerna) directly instead of as part of yarn
* A lot of CI/ops stuff will need to be updated

With this upgrade, we should force a minimum of Node.js 15.x as well.

@torkelo @woodsaj @ryantxu @dprokop

**Comment by Clarity-89** [comment]
npm still doesn't have a native way to fix the versions inside dependencies it seems (what yarn's `resolutions` does). So if we decide to switch, we might need to add a [separate package](https://github.com/rogeriochaves/npm-force-resolutions) for that. Also we're using yarn workspaces with lerna, not sure what would be the migration path to npm there.

**Comment by yuriy-yarosh** [comment]
@peterholmberg @stevenvachon 

Well, I'm building grafana with yarn 3 and `yarn workspaces focus --production -A` runs husky, which requires `fs-extra` to be in prod deps instead of dev during focusing :\

Other than that there's no other major compat issues so far... and webpack memleaks a bit, so needs bigger `max_old_space_size`.

```bash
nvm use lts/gallium 
npm install -g yarn
YARN_ENABLE_PROGRESS_BARS=false yarn install --immutable --frozen-lockfile
NODE_OPTIONS=--max_old_space_size=10000 yarn build
yarn run plugins:build-bundled
yarn plugin import workspace-tools
yarn remove fs-extra ; yarn add fs-extra
yarn remove husky ; yarn add husky
yarn workspaces focus --production -A
```

I'm unable to trim the `.yarn` dir otherwise, and `workspaces focus` does return 0 status code, even on errors.

For now I'm removing `.yarn` and `node_modules` entirely ... but hopefully we'll get some prerender capabilities with hydration one day.

**Comment by stevenvachon** [comment]
@yuriy-yarosh yarn 3.x is quite different; try yarn 2.x

**Comment by yuriy-yarosh** [comment]
@stevenvachon nah... webpack builds and resolves modules properly with PnP - there's no need for a downgrade.
Will report any errors if will ever come by, but haven't see any so far with 9.0.7 release.

**Comment by zoltanbedi** [comment]
We are going to look for alternatives and close this issue for now.
