### ISSUE TITLE
After deselecting all the items from the multi select drop down, able to see first option is always been selected in Grafana 6.7

### ISSUE THREAD

**Issue by rkanna911** [grafana/grafana#28372]
**What happened**:
While deselecting all the items in the multi select variables drop down list, it always selecting first item by default without selecting
**What you expected to happen**:
When we deselect all the items, it should be blank or nil or null.
**How to reproduce it (as minimally and precisely as possible)**:
Try to deselect all the items, that are already selected in the multi select variable drop down 
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.3
- Data source type & version: Elasticsearch 7+
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: none
- Others: Variables multi select drop down, deselecting all the items

**Comment by rkanna911** [comment]
![Capture](https://user-images.githubusercontent.com/73121561/96465434-97e04480-1246-11eb-84a7-b432de70fa40.PNG)

**Comment by ivanahuckova** [comment]
Hello @rkanna911, yes I was able to reproduce this issue on Grafana 6.7.3, but recently we have done a huge refactor of template variables and we also fixed some issues connected to this. I have tried to reproduce this issue in Grafana 7.2.1, but the issue has been already fixed in there. So if you upgrade to the latest version, you won't experience this issue anymore. 🙂
