### ISSUE TITLE
Optionally use suggestion API for OpenTSDB templating

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#2840]
Little backstory here: https://github.com/grafana/grafana/issues/1250#issuecomment-127779539. With terabytes of data it is impossible to rebuild metadata: OpenTSDB/opentsdb#549. At the same time, metadata collection doubles the load on HBase: https://github.com/OpenTSDB/opentsdb/issues/575#issuecomment-143849460. Without metadata collection Grafana templating for OpenTSDB is not very useful, since it doesn't work and you have to enter values by hand without any autocompletion.

Luckily, OpenTSDB has [suggestion api](http://opentsdb.net/docs/build/html/api_http/suggest.html) that works without metadata. I propose to make use of this API and add two more functions:

* `suggest_tagk()` to select tag keys.
* `suggest_tagv()` to select tag values.

I can probably come up with a PR if this sounds reasonable.

it also makes sense to dynamically request values for these two and `metrics()`, since `metrics()` now only shows 1000 first metric names. Not sure if I can do this, though.

**Comment by torkelo** [comment]
sounds like OpenTSDB should improve their meta database? 

But sure, a PR for this would be accepted :)

**Comment by utkarshcmu** [comment]
Use of suggestion API makes sense only in suggesting tag keys and values in Query editor but not in template variables. For template variables, we still need to use the search/lookup API (which is broken in Opentsdb v2.1.1 & v2.2.0RC1). Opentsdb's search/lookup API will be fixed in v2.2.0RC2 or the next release as the fix (https://github.com/OpenTSDB/opentsdb/commit/c4225ffbe32800b7e49e61d1ff8249a926bc983e) is committed to master after the release of v2.2.0RC1. :(

**Comment by utkarshcmu** [comment]
@torkelo This can be closed not as we have merged #3088.
