### ISSUE TITLE
Issue in grafana alerts when there is no data or app down

### ISSUE THREAD

**Issue by nehas247** [grafana/grafana#28427]
Hi Team,

I tried multiple conditions in Grafana Alert setup to get notified in case application is down or no data. But I am not recieiving any mail. Also If I am setting rule for 95% above value breach it is working fine but not for zero data.
![No Data 2](https://user-images.githubusercontent.com/38423756/96691437-857b1d80-13a2-11eb-9896-edd811b23a35.PNG)
![No Data](https://user-images.githubusercontent.com/38423756/96691448-8744e100-13a2-11eb-8da4-7a9fe58df136.PNG)

**Comment by nehas247** [comment]
Need help to setup alert in two cases if value goes above 95% or no data. In both the cases email shul be triggered for one application.

**Comment by ivanahuckova** [comment]
Hello @nehas247, when creating issues/bug reports, please use the template that you can find [here](https://github.com/grafana/grafana/issues/new?labels=type%3A+bug&template=1-bug_report.md). This issue seems more like a question and for those, we have actually a community site: https://community.grafana.com/. So definitely check it out! 🙂
