### ISSUE TITLE
Option to restrict Dashboard JSON view/export

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#2844]
I'd like to see an option to disable Dashboard JSON viewing/export for "Viewer" role, so that example dashboards can be made publicly viewable without having to share the source code behind them.

**Comment by torkelo** [comment]
The dashboard JSON will always be viewable via chrome dev tools or any other network monitor tool (as the dashboard json is loaded by the frontend)

So I am not sure what the point of this restriction would be. And you cant make something public without making every metric in your entire TSDB public, because Graphite, InfluxDB or OpenTSDB (what ever you use) do not have any per series permissions, so every metric will be exposed.

**Comment by rmoff** [comment]
> The dashboard JSON will always be viewable via chrome dev tools or any other network monitor tool (as the dashboard json is loaded by the frontend)

Ah, my misunderstanding. Thanks anyway.
