### ISSUE TITLE
Non-Negative Derivative Function missing for InfluxDB Datasource?

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2852]
For some odd reason, the non-negative derivative function isn't appear for me in Grafana, with a InfluxDB data-source:

<img width="326" alt="screenshot 2015-09-30 16 49 25" src="https://cloud.githubusercontent.com/assets/243499/10186331/6e2ba9f8-6793-11e5-95ff-b2804247147f.png">

I could have sworn it was there before.

I've currently running the latest from HEAD (42e7a70) at time of writing.

**Comment by torkelo** [comment]
It was there but it was not working, derivate and non_negative_derivate are not aggregate functions, so they should not be in that dropdown. As of InfluxDB 0.9.4 InfluxDB will throw error if you use derivate without an aggregation function as well.  

And InfluxDB are having some major problems getting those functions to work properly :( 

I am working on ideas to radically rethink the InfluxDB editor in order to support aggregation and transforamtion functions (with params) 
https://github.com/grafana/grafana/issues/2802#issuecomment-144102958

**Comment by victorhooi** [comment]
Aha, ok, thanks for clearing that up. I'll follow #2802 then - I assume if there is a fix for this, it will be discussed there? I noticed it's tagged with a 2.5 milestone - is that still a while off?

Is the workaround for now to just do a manual InfluxDB query, and add the derivative function ourselves manually?

**Comment by torkelo** [comment]
@victorhooi yes, that is a work around, but not sure you can get it to work even then, many claim they cant get the correct values when using derivate and group by time 

Not sure it will be included in 2.5, depends on how quickly I get get the new editor working, want to release 2.5 beta soon
