### ISSUE TITLE
Support of additional marker types for Graphs

### ISSUE THREAD

**Issue by andreashofm** [grafana/grafana#28528]
**What would you like to be added**:
Currently, the plot type "Graph" does only support (filled) point markers. It would be great if additional markers like squares, triangles, stars, plus, etc. could be added.

**Why is this needed**:
Having different marker types would be beneficial when superimposing several data streams as well as for highlighting purposes.

**Comment by hugohaggmark** [comment]
@dprokop is this something we're thinking about supporting in the new Graph?

**Comment by dprokop** [comment]
@andreashofm thank you for this feature request. I have added it to the new graph panel backlog and we will try to include this feature in the new graph panel.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
