### ISSUE TITLE
Loki/Explore: Distinction between Log labels and Parsed fields causes confusing with Loki v2

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#28706]
**What would you like to be improved**:
With the Loki 2.0 enhancements the Parsed fields part in log details can be confusing now. Because when we use the parsers in the Loki query language what is parsed shows up as labels, but users might think that **Parsed fields** is what is parsed by Loki. This was also mentioned on the workshop - that distinction between Log Labels and parsed fields causes confusing with Loki v2.

**Comment by treksler** [comment]
the worst part of the confusion between log labels and parsed fields is that they don't behave the same, but are treated the same in the UI

For example, in grafana with Loki 2, the parsed fields show up as labels, but when you click on the little + search icon (filter for value), grafana puts the label in the query like any non-parsed label 
`{container="my-container",parsed-field-label="parsed-value"}|json` which does not work
instead of 
`{container="my-container"}|json|parsed-field-label="parsed-value"` which would actually work for a parsed label
