### ISSUE TITLE
feature-request: table-panel - numbered rows

### ISSUE THREAD

**Issue by pfischer64** [grafana/grafana#28703]
When I use elasticsearch as a datasource, there is no easy solution to display numbered rows in a table panel. 

Therefore I suggest a new table option:

Show Row Numbers - toggle to show/hide row numbers

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
