### ISSUE TITLE
LogsPanel: Scrolling in dashboards does not work, log level is not customizable

### ISSUE THREAD

**Issue by howardjohn** [grafana/grafana#28723]
![GrafanaLogPanel](https://user-images.githubusercontent.com/623453/97815411-a36a3d00-1c42-11eb-8d2b-38af67b1cd01.gif)

The GIF above shows me trying to use the log panel (with loki data source).

1. The first issue is the scroll bar is not selectable by the mouse
2. At the bottom right there is a random white box. There is no info about it on https://grafana.com/docs/grafana/latest/panels/visualizations/logs-panel/ or in the Grafana UI, and I cannot click on it
3. Hovering logs switches cursor to the "link" mode, but clicking on them does nothing.
4. On the left of each log there is a grey line indicator. In https://grafana.com/blog/2019/10/16/new-in-grafana-6.4-the-logs-panel/ this is shown correlating with "level", but there appears to be no way to actually customize this (for example, if I want response_code==200 to be green)

Grafana is 7.3.1 running Kubernetes, browser Chrome  86.0.4240.111

**Comment by aocenas** [comment]
1. and .2
Should be fixed in https://github.com/grafana/grafana/pull/28974. Basically the issue was we were showing native scrollbars (this is where the white rectangle comes from for some reason Chrome shows that when both scrollbars exist) while for various reasons we use custom scrollbars in dashboards so showing both had this weird effect where dragging did not work.

3. 
This is styling because the row can expand in explore (but not in dashboards). We are working on enabling expanding the row in dashboards but that wasn't high priority lately.

4.
Yes there is no customization for how we are figuring out the levels at the moment. Can you create a separate feature request for this? This will be closed when we merge the bugfix.
