### ISSUE TITLE
Template variables: URL values not used for dependent variables

### ISSUE THREAD

**Issue by shanson7** [grafana/grafana#28791]
**What happened**:

We have many dashboards with 2 template variables A and B, where B depends on A. In some cases, there are links like `<grafana_url>?var-A=val`, where B is left empty and should be filled in. After upgrading to `Grafana v7.3.1` we are seeing that the template value query for B is not using the value for A specified in the URL. 

For a concrete example, let's say we have 2 variables `parentCluster` and `cluster`. Given a link like `<grafana_url>?var-parentCluster=val` the behaviors are:

## Grafana 7.2.0 

`values?tag=parentCluster&limit=10000`
`expr=parentCluster%3Dval&tag=cluster&limit=10000`

Which results in the initial values of variables:
`parentCluster=val`
`cluster=cval` (picked the first returned value from the query)

## Grafana 7.3.1

`values?tag=parentCluster&limit=10000`
`expr=parentCluster%3Ddefaultval&tag=cluster&limit=10000`

where `defaultval` is the default value saved to the dashboard for parentCluster instead of the value passed in the URL. 

Which results in the initial values of variables:
`parentCluster=val`
`cluster=cdefaultval` (The saved default cluster)

**What you expected to happen**:

I would expect that dependent variables would be resolved using the values passed in the URL

**Environment**:
- Grafana version: `Grafana v7.3.1 (6668161a88)`
- Data source type & version: Graphite (Metrictank)
- OS Grafana is installed on: Rhel 7
- User OS & Browser: Mac OS X & Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Here is a gist with a dashboard to replicate the issue: https://gist.github.com/torkelo/0afc8ef66f0c8f63ba136f96b139e2b5 
 require you to run the devenv  graphite11 docker block. 

Some log output from troubleshooting this:

URL: http://localhost:3000/d/exS-5d2Mk/graphite-nested?orgId=1&var-stats=response&var-substats=All
```
processVariable stats  response
actions.ts:276 set variable from url stats = response
actions.ts:625 update options stats
datasource.ts:336 metricFindQuery stats.*
actions.ts:237 processVariable substats  All
actions.ts:276 set variable from url substats
actions.ts:625 update options substats
datasource.ts:336 metricFindQuery stats.gauges.*    (The variable definition says stats.$stats.* and so this should interpolate as stats.response.*) 
actions.ts:327 set value stats = response
actions.ts:327 set value substats = response
```

@hugohaggmark as you can see the first variable (stats) does not actually set it's value from url until after it's options and it's child variable (substats) has been updated. So the query the child variable executes does not interpolate with the new url value. 

Think the problem is here: This function will trigger child updates but that is executed before the first variable has actually updated it's own value 
https://github.com/grafana/grafana/blob/master/public/app/features/variables/state/actions.ts#L276

**Comment by hugohaggmark** [comment]
@torkelo I'm on it

**Comment by dp106** [comment]
Sorry, opened a duplicate issue, looks like this is already sorted though
