### ISSUE TITLE
Shortcut for "duplicate metrics but timeShift back a week"?

### ISSUE THREAD

**Issue by petemounce** [grafana/grafana#288]
One of our most common use-cases for charts is 
0. look at now
0. look at now minus 7d

It would be really handy to have a shortcut on the edit-chart view, on a metric, so clicking on the cog shows `duplicate -7d` and `duplicate -28d` as well as the current `duplicate`.  That would save lots of manual clicking to accomplish the same thing.

Also, it would be nice to be able to do that for all targets displayed on a chart at once.

**Comment by dm9876** [comment]
Hi Torkelo, great project here. Hoping to test it out soon, but not a user yet so please excuse my terminology if its wrong.

It would be good this feature is implemented in grafana so it's a consistent and available feature regardless of the datasource. (I wish to use InfluxDB)

maybe the answer is related to this one https://github.com/grafana/grafana/issues/171 (different time periods / starting time per chart), but I would like to see it also possible withing a single chart, so that you can see small variance in the graph line which is not easy to compare when comparing in different charts

Also consider that the time shift could be relative as above with the graphite timeshift...  but could also be useful completely independent. My example would be for the two time period lengths to match (eg 30days) but to to index the start date time of each to different events / annotations. eg compare the performance of a particular metric between multiple runs where the start of each run is annotated.

maybe part of the solution could be to have a button on the popup that appears when you mouseover the annotation event which allows you to quickly set the starting time of that dashboard to the time of the annotation.

Dean

**Comment by ZeroPointTwo** [comment]
> Also consider that the time shift could be relative as above with the graphite timeshift... but could also be useful completely independent. My example would be for the two time period lengths to match (eg 30days) but to to index the start date time of each to different events / annotations. eg compare the performance of a particular metric between multiple runs where the start of each run is annotated.

+1 to something like this. It would actually be very useful for many of my use cases and I imagine many other people have the same use cases as well.

**Comment by torkelo** [comment]
We are trying use open GitHub issues as a way to track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long without any much interest in the feature or anyone showing interest in implementing it. 

A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
