### ISSUE TITLE
Variables: Can't use space in variable search

### ISSUE THREAD

**Issue by tobiasdirksen** [grafana/grafana#28848]
**What happened**:
Since one of the recent updates (I'm not sure which one), I can't use space anymore, when I search for a value option in a variable. This is a big problem, e.g., when you have many addresses in the variable, and you would like to search for a specific one. When I click space nothing happens. 

**What you expected to happen**:
I expect that a space is inserted in the search string, when I press space.

**How to reproduce it (as minimally and precisely as possible)**:
Create a custom variable with options including space on an empty dashboard:

![billede](https://user-images.githubusercontent.com/7211545/98226586-88574000-1f56-11eb-9513-844188cb9b5e.png)
======
Then try to search for one of the options. I can't insert space:
![billede](https://user-images.githubusercontent.com/7211545/98226734-b76db180-1f56-11eb-9b6e-3f2642d7606e.png)

**Anything else we need to know?**:
It does actually work on Android 5.1.1 and Chrome 86.0.4240.110:
![billede](https://user-images.githubusercontent.com/7211545/98228434-e127d800-1f58-11eb-9eea-55ef0cddc32c.png)

**Environment**:
- Grafana version: 7.3.1
- OS Grafana is installed on: Ubuntu 18.04.5 LTS
- User OS & Browser: Windows 10 Enterprise 18.03. Edge (86.0.622.61)/Firefox (82.0.2)/Chrome (86.0.4240.111)
- Grafana plugins: No plugin is used

**Comment by marefr** [comment]
Thanks. Please update your issue description - use the bug template to provide more information and needed details https://github.com/grafana/grafana/issues/new?labels=type%3A+bug&template=1-bug_report.md

**Comment by torkelo** [comment]
Unable to replicate 
<img width="250" alt="Screen Shot 2020-11-06 at 07 50 24" src="https://user-images.githubusercontent.com/10999/98335164-c317b180-2004-11eb-92e9-44bdc9ffbeb3.png">

**Comment by tobiasdirksen** [comment]
Thanks for quick reply. Hm, all my colleagues have the same problem. It's probably related to OS or browser version then.

**Comment by torkelo** [comment]
But there is a problem inserting space, sorry I miss read this

**Comment by torkelo** [comment]
This is by design space is used to select / deselect values

**Comment by tobiasdirksen** [comment]
Thanks. I see. However, this has worked previously, and does work on Android, and also on your screenshot above? I don't think it is that common to select with space in a dropdown, but maybe I'm wrong. Is there any workaround besides pasting the whole search text into the search field?

**Comment by DimaRabkin** [comment]
+1

I upgraded version 7.0.3 to 7.3.1 and it stopped working.
I checked this with Safari and Chrome

**Comment by tobiasdirksen** [comment]
I could maybe also add that space doesn't select/deselect in a single value variable. Nothing happens when I press space. It only works for multivalued variables, where it is also more intuitive, in my opinion.

**Comment by Grrrolf** [comment]
> This is by design space is used to select / deselect values

A suggestion: 
Instead of pressing space in the template variable search box for making a selection, what about having selecting and deselecting using space only work when highlighting the actual value (using the mouse or cursor keys). In other wordt, scroll down to the value which needs to be selected or deselected and press space. This will allow for quickly making one or even multiple selection.

In our dashboards showing for customers or products metrics, we fill the template variables with a list of customers or products and let the users use the template variable search box to search for a customer or products. This works really great and quick even, when the list of values is rather large.

**Comment by mpaloni** [comment]
+1 Copy pasting works as said, but would be nice to write the space directly to search field.

**Comment by jdburche** [comment]
While testing this functionality in Firefox and Chrome (running on Mac OS 11) on Grafana v7.3.7 I observed the following:

  * The spacebar **does** select items from multi-value drop down lists for variables
  * The spacebar **does not** select items from drop down lists for variables that are not multi-value
 
It would be nice to have spaces considered when searching these lists. If nothing else, perhaps this behavior could be made configurable for each variable?

**Comment by uebenes** [comment]
I have the same problem. You can not type any spaces to filter the result set. That is really confusing.

**Comment by barts2108** [comment]
We use Grafana where we present the user with a dropdown of names that describe digital and analog IO's (the real IO names are something like AI0000, AI0001 etc

![no whitespace](https://user-images.githubusercontent.com/520875/130081211-05732481-c973-4d4d-a34a-31942ed028f0.PNG)

In version 7.1.1 the whitespace did select an item in the dropdown and put the space into the input box as well. Now in version 8.1.1 the whitespace key is compleletly blocked. We would love to see the possibility to simply type in the searchbox (including whitespace) where even in the multiselect there would be an option that the spacebar does **not** select any item. Only use it for filtering.

Does anyone know where in the code the whitespace character is blocked ?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
