### ISSUE TITLE
Authenticate GitLab Admins as Grafana Admins

### ISSUE THREAD

**Issue by Paebbels** [grafana/grafana#28892]
**What would you like to be added**:
Currently, users authenticated with GitLab SSO are just normal users in Grafana.
A special trick is needed:
1. Allow user `admin` to login to Grafana
2. Login with a GitLab admin user so, the user is in Grafana's user database
3. Login as `admin` and assign admin right to the GitLab user
4. deactivate Grafana's `admin` user

**Why is this needed**:
At GitLab, it was discussed how to solve the problem, that GitLab admins are authenticated as Grafana admins.
It was investigated, that a change in Grafana is required for this feature.

Please have a look here, if you can goon from a code snippet provided as a proof-of-concept.

Discussion at GitLab: https://gitlab.com/gitlab-org/gitlab/-/issues/31125
Code Snippet: See https://gitlab.com/gitlab-org/gitlab/-/issues/31125#note_442395833 (click on `A patch`)

```patch
diff --git a/pkg/login/social/gitlab_oauth.go b/pkg/login/social/gitlab_oauth.go
index d6be068c2e..4a9b353f2e 100644
--- a/pkg/login/social/gitlab_oauth.go
+++ b/pkg/login/social/gitlab_oauth.go
@@ -96,8 +96,11 @@ func (s *SocialGitlab) UserInfo(client *http.Client, token *oauth2.Token) (*Basi
 		Email    string
 		Name     string
 		State    string
+		IsAdmin  bool `json:"is_admin"`
 	}
 
+	var role = ""
+
 	response, err := HttpGet(client, s.apiUrl+"/user")
 	if err != nil {
 		return nil, fmt.Errorf("Error getting user info: %s", err)
@@ -112,6 +115,10 @@ func (s *SocialGitlab) UserInfo(client *http.Client, token *oauth2.Token) (*Basi
 		return nil, fmt.Errorf("user %s is inactive", data.Username)
 	}
 
+	if data.IsAdmin {
+		role = "Admin"
+	}
+
 	groups := s.GetGroups(client)
 
 	userInfo := &BasicUserInfo{
@@ -120,6 +127,7 @@ func (s *SocialGitlab) UserInfo(client *http.Client, token *oauth2.Token) (*Basi
 		Login:  data.Username,
 		Email:  data.Email,
 		Groups: groups,
+		Role:   role,
 	}
 
 	if !s.IsGroupMember(groups) {
```

**Comment by splattael** [comment]
@Paebbels Thanks for pulling this discussion over :bow: 

While re-reading Grafana's [Generic OAuth documentation](https://grafana.com/docs/grafana/latest/auth/generic-oauth) I've realized that the more flexible approach could be to implement `role_attribute_path` (JMESPath) for [GitLab OAuth](https://grafana.com/docs/grafana/latest/auth/gitlab/) instead. For example:

```ini
role_attribute_path = is_admin && 'Admin' || 'Viewer'
# OR
role_attribute_path = is_admin && 'Admin' || 'Editor'
```

In fact, with a small tweak on the GitLab¹ side I was able to use the Generic OAuth in order to authenticate with GitLab _without any code changes_ :astonished: :

```ini
[auth.generic_oauth]
enabled = true
allow_sign_up = true
client_id = <CLIENT_ID>
client_secret = <CLIENT_SECRET>
scopes = api
auth_url = <GITLAB_URL>/oauth/authorize
token_url = <GITLAB_URL>/oauth/token
api_url = <GITLAB_URL>/api/v4/user
role_attribute_path = is_admin && 'Admin' || 'Viewer'
```

Having said that, bringing `role_attribute_path` to GitLab OAuth seems to be most convenient and flexible experience for Grafana and GitLab users.

<details>

<summary>¹ The GitLab tweak</summary>

Update `redirect_uri` of the registered OAuth Application in the database via `gitlab-psql` (GitLab omnibus):

```sql
update oauth_applications set redirect_uri = '<GITLAB_URL>/-/grafana/login/generic_oauth' where name = 'GitLab Grafana';
```

**Comment by papagian** [comment]
I agree with @splattael that adding support for `role_attribute_path` in the GitLab integration is preferable over the proposed one.

**Comment by splattael** [comment]
I've started working on this in https://github.com/grafana/grafana/pull/30025.

Feedback is very welcome!

**Comment by hobti01** [comment]
I've also been travelling this road, and the (only?) disadvantage with using the generic oauth provider is that all GitLab users (i.e. gitlab.com) would be allowed to login since there is no group exclusion as with `allowed_groups`.

Having the feature parity between providers to perform role mapping is needed for us.

**Comment by splattael** [comment]
With the help from @henrysachs we are moving #30025 forward now :tada:

After that PR is merged [GitLab's omnibus](https://gitlab.com/gitlab-org/omnibus-gitlab) has to upgrade Grafana to the then latest release. We should also refine the its default Grafana config and test it :grinning:

**Comment by copolycube** [comment]
Hello, I faced a bug and tried pushing a PR about this on https://github.com/grafana/grafana/issues/48637 / https://github.com/grafana/grafana/pull/49147
was this previously working / is this a regression ?
