### ISSUE TITLE
Template variable values not showing when using Postgres

### ISSUE THREAD

**Issue by shouryasimha** [grafana/grafana#28921]
Hello,
I'm extremely new to grafana so  please excuse me for my noob question. I want to list all the usernames by creating a template variable called 'username' which should be a drop down of all the existing usernames in the database.

username  : Query Variable (type of variable)
Query to list all username : select username from datasource
Datasource  : PostgreSQL

**Comment by papagian** [comment]
Closing it because this is only for filing bugs and feature requests. For questions you have to ask in [the community site](https://community.grafana.com/).
Generally speaking as a query you can use any valid PostgreSQL query (depending on your data/db schema). For some hints you can refer to the PostgresSQL [docs](https://grafana.com/docs/grafana/latest/datasources/postgres/#query-variable).
