### ISSUE TITLE
Using spaces in tags for annotations

### ISSUE THREAD

**Issue by mileippert** [grafana/grafana#2903]
I have a use case where I need to include spaces within multiple tags. (i.e. “sample tag 1” “sample tag 2”)
In the Issue #1474 you (@torkelo) wrote the following comment:

> the tags display on annotations will work with any data source as long as they return an annotation object with a tags property that is either an array of strings, comma seperated string, or space seperated string.

These spaces are therefore interpreted as separation characters if they are delivered in an array of strings or comma/space separated string.

It would be perfect when tags are delivered as an array of strings these spaces are ignored. Alternatively you could add the possibility to escape the spaces (using html or url escaping) which should be pretty easy to implement.

My workaround for this problem is to use underscores as substitute which does not look nice.

**Comment by torkelo** [comment]
this looks specific to graphite, https://github.com/grafana/grafana/blob/494ede5bbfddc7dc143c76703c7fde0ff5c207da/public/app/plugins/datasource/graphite/datasource.js#L116

I would welcome a fix :)

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
