### ISSUE TITLE
Add datasource for AWS RDS Performance Insights metrics

### ISSUE THREAD

**Issue by lobeck** [grafana/grafana#29269]
**What would you like to be added**:

AWS Performance Insights offer some buildin Metrics, that are not available through CloudWatch. They are a great addition to the existing CloudWatch metrics and provide much more insights into the database behaviour.

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights_Counters.html#USER_PerfInsights_Counters.PostgreSQL

**Why is this needed**:

Visibility into RDS is difficult, as the CloudWatch metrics are only very abstract and don't yield much information on their own. With the additional metrics from Performance Insights, one could get a much better few into the database and help with troubleshooting

**Comment by aocenas** [comment]
@lobeck thanks for the request. This is not on our roadmap at the moment so if you didn't already you could search whether there isn't existing 3rd party plugin for this as not all plugins are listed on https://grafana.com/grafana/plugins.

**Comment by Xopherus** [comment]
Would it be possible to add the metrics which are published by PI through Cloudwatch? There's [DBLoad, DBLoadCPU, and DBLoadNonCPU](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.Cloudwatch.html). I don't see these available, though I am on Grafana 6.7 (forgive me if they were added in Grafana 7).

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
