### ISSUE TITLE
Influx: There is not auth configuration when Flux language is selected

### ISSUE THREAD

**Issue by eQza** [grafana/grafana#29303]
**What happened**:
Can't connect to influxdb 2.0 when using flux datasource

**What you expected to happen**:
Somewhere to set https settings or certs

**How to reproduce it (as minimally and precisely as possible)**:
Add Flux datasource when influx is setup using TLS

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.2
- Data source type & version: Influx Version 2.0.0 (37cc047)
- OS Grafana is installed on: ubuntu
- User OS & Browser: chrome

**Comment by aocenas** [comment]
@eQza Can you send a screenshot of the config screen or exact version of the plugin you use? There were some changes and Flux and Influx datasource were merged into a single datasource and so now what I see in the config is this:
![Screenshot from 2020-11-24 12-53-21](https://user-images.githubusercontent.com/1014802/100090926-379b7e80-2e54-11eb-9e35-c812f2815d95.png)

Or are you saying this configuration section does not work for you?

**Comment by eQza** [comment]
I want to use Flux query language not InfluxQL

![image](https://user-images.githubusercontent.com/21050380/100091867-20a55e00-2e4d-11eb-9c0b-9289de56de8e.png)

**Comment by aocenas** [comment]
@eQza thanks for clarification. @davkal or @ryantxu I assume this is just a simple omission, or is there some reason this config does not exist when selecting Flux language?

**Comment by dswarbrick** [comment]
Duplicates #26388

**Comment by aocenas** [comment]
@dswarbrick thanks for chiming in, but I think these may be separate issues. The one you linked seem to be about a bug with the TLS but here it's about TLS setting not being there when you select the flux language in the configuration.

**Comment by dswarbrick** [comment]
@aocenas Supporting self-signed certificates would be possible if it were possible to specify "Skip TLS Verify", as is possible for InfluxQL data sources. Sadly, it is not yet possible for Flux data sources.

Or am I missing something here?

**Comment by aocenas** [comment]
@dswarbrick as commented here https://github.com/grafana/grafana/issues/29303#issuecomment-732921821 Flux option doesn't have any TLS configuration which I assume it should have so I think it's not just about the "Skip TLS Verify" switch. These are definitely connected but I assume the older one references older version of the plugin (when it was actually 2 different plugins). In that case I would rather close the older one in favor of this one.

Or are you saying that the Flux version should not have the same TLS options (and auth section) as InfluxQL?

**Comment by dswarbrick** [comment]
@aocenas I merely stumbled across both issues because I've hit the same snag. I have an InfluxDB v2 instance running with TLS enabled, using a self-signed "snakeoil" cert. I am unable to configure this as a data source because Grafana rejects the server's cert during the TLS handshake. The InfluxDB instance logs this:
```
Nov 26 14:54:14 nlnog-db influxd[7425]: 2020-11-26T14:54:14.362616Z        info        http: TLS handshake error from 185.48.x.x:38908: remote error: tls: bad certificate
```
The same instance works fine if configured as a legacy InfluxQL data source, because I am able to ignore TLS verification failures by enabling "TLS skip verify". My goal however is to start migrating to native Flux queries, and for that, I need a working data source.

**Comment by aocenas** [comment]
Right yeah I mean the core issue though seems to be that the whole Auth section in the config is missing so it should be added and made sure it works as it should. Not sure why it isn't there now I assume it's an artifact of merging the data sources when they were implemented as 2 separate plugins.

**Comment by dswarbrick** [comment]
InfluxDB v2 auth system is quite different to InfluxDB, since it uses "organizations" and tokens.

InfluxDB 1.x on the other hand used username / password, and this could be done either by HTTP Basic, or as parameters embedded in the HTTP query string.

AFAIK, neither InfluxDB 1.x nor 2.x support TLS client cert authentication, so those options would only be relevant if you had it running behind a reverse proxy, configured for TLS client cert auth.

**Comment by aocenas** [comment]
As you say there can be anything between the actual database and grafana so these Auth configs should be configurable for all data sources whether the DB uses them or some proxy in between.
