### ISSUE TITLE
"Generated SQL" does not show SQL when query has an error

### ISSUE THREAD

**Issue by adam-nielsen** [grafana/grafana#29424]
If I run an SQL query and click the "Generated SQL" link, then all the placeholders are replaced with their actual values and in the sidebar I can see the raw SQL sent to the server, which is very useful for debugging.

However if the server is returning an error, then Grafana does not show the raw SQL so it is very difficult to diagnose the error, particularly when the error appears to be in the way one of the placeholders is formatted.

This is what "Generated SQL" looks like when there is an error, no query can be seen:

![screenshot](https://user-images.githubusercontent.com/278772/100397171-07422300-3094-11eb-9662-1914a63258e0.png)

**How to reproduce it (as minimally and precisely as possible)**:

Put in an invalid SQL statement and try to view the generated SQL for it.

**Environment**:
- Grafana version: 7.3.4
- Data source type & version: PostgresSQL + TimescaleDB
- OS Grafana is installed on: DockerHub grafana/grafana:latest
- User OS & Browser: Firefox + Chrome

**Comment by aocenas** [comment]
For future reference this is how it looks like with successful query:
![Screenshot from 2020-11-27 12-16-35](https://user-images.githubusercontent.com/1014802/100443685-788cd080-30aa-11eb-96ae-8de261c88633.png)

I assume the full interpolated query should be shown even if server returns error (probably only if the query building fails we would have nothing to show).

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
