### ISSUE TITLE
Data links: Add autocomplete to "title" field

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#29480]
**What happened**:
try accessing autocomplete using `$` in the data link "title" field

this applies to data links in panel, fields, etc.

![Screen Shot 2020-12-01 at 2 03 05 PM](https://user-images.githubusercontent.com/1708631/100699304-f835da80-33dd-11eb-9548-db81505e93fa.png)

**What you expected to happen**:
since variable expansion is supported in the data link "title" field (not just "URL" field), I expect autocomplete to be available

**Environment**:
- Grafana version: 7.3.4

**Comment by ivanahuckova** [comment]
@grafana/grafana-frontend-platform  I wasn't sure if this is bug or feature request, but decided to add `feature-request` label as this wasn't supported before. Feel free to re-label, if I was wrong.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
