### ISSUE TITLE
Support of variable thresholds

### ISSUE THREAD

**Issue by andreashofm** [grafana/grafana#29497]
**What would you like to be added**:
Currently, thresholds (e.g. in bar gauge charts) need to be predefined values. In v7.3.3 you could also enter characters. I tried to define query variables and use them for dynamic thresholds. Though this was working in principle, it was buggy & thresholds were not saved upon dashboard reload. It would be fantastic if variables could be set as thresholds.

**Why is this needed**:
Variable thresholds are more flexible than static ones.

**Comment by ivanahuckova** [comment]
@andreashofm thank you for creating the feature request. Could you please tell us more about your use case. Also could you check if https://grafana.com/docs/grafana/latest/panels/field-options/standard-field-options/#color-scheme solve you problem. By using color scheme, you don't have to manually add tresholds, but tresholds are automatically calculated by Grafana based on your values or your min-max values.

**Comment by ivanahuckova** [comment]
Thank you for providing more information about your use case. It is really helpful!

**Comment by BBQigniter** [comment]
@andreashofm and now wait the next 5 years and it will still not be implemented - sorry for the sarcasm. there are several feature requests/issues for this, open since I think 2015 or so. 

And generally sorry for this comment - but seeing such generic comments from Grafana employees makes me quite mad.

Yes, I know it's open source and so on and **really a big thank you for this great product**! But if you do not add a for years requested and extremely useful feature, just tell the community why you won't add it and don't make such a mystery out of it. Maybe explain what the problem is about the feature request? Maybe someone from the community can resolve it?

Again, sorry for the rant, but I had to put this off my soul ;)

**Comment by RichiH** [comment]
@BBQigniter having tried to get weathermaps into Grafana since 2015, and working here since early 2020, I know how frustrating this kind of thing can be. It seems Obvious(TM) that it Should Be Done(TM). And yet, and yet...

Fun fact: You should be able to find comments from my past self requesting similar.  And yet, and yet...

Knowing how @ivanahuckova since early 2020 (Coincidence?! I think not!) and knowing how deeply she cares about her users, her statement was all but generic.

Prioritization is hard, and things always change. Would this make sense? Yes. Would it people at Grafana Labs want to work on it? Yes! Is this currently a focus point? I honestly don't know, I would need to talk to several people to find out. That's life. Not ideal, but that's life.

But all of this is just a long-winded intro to my main point:

You put it off your soul, and onto @ivanahuckova 's. Most likely not your intention, but communication is mainly defined through what arrives at the receiver.

So please don't do that.

**Comment by maemigh** [comment]
While this isn't a perfect way to derive load thresholds, my use case is something like a stat panel showing load (load1, load5, load15) where I would set thresholds based on CPU count, which is a template variable. I would like the values values to scale towards red as load value approaches $cpu_count (or a % of $cpu_count). 

Something like:

value > $variable
and
value > $variable * 1.2

**Comment by a-vogel-tappert** [comment]
A threshold based on a query or variable would be great.
Please enter that feature :-)

**Comment by ryantxu** [comment]
There is a path to adding a transformer step that lets you pick a query result and use it as the threshold for other fields/results

**Comment by torkelo** [comment]
So in v8.1 we are adding two new transforms that will allow you to extract config like min, max, unit and thresholds from a normal query:

[Config from query results](https://grafana.com/docs/grafana/next/panels/transformations/config-from-query/)
[Rows to fields](https://grafana.com/docs/grafana/next/panels/transformations/rows-to-fields/) 

We are soon switching to Github discussions for feature requests, will create an issue there next week to collect feedback on these new transforms

**Comment by Usipov** [comment]
You can add a field override with custom thresholds
It is not the best solution, because you have to add a parameter value to your metric name so that you can regex on it and select an appropriate field override

<img width="550" alt="Screenshot 2024-03-01 at 01 42 56" src="https://github.com/grafana/grafana/assets/1080247/501fd5e1-20a7-4ddb-8883-fc3807a6bcc3">

**Comment by kyurkchyan** [comment]
I have been struggling with this issue for 2 days now. 

I have no clue how the transformations allow defining a threshold dynamically. 

Can anybody share an example of a dashboard where it show how to
1. Define Threshold1, Threshold2 .... Thresholdn variables
2. Use those variables to set a threshold using transformations.
