### ISSUE TITLE
Grafana api/folders doesnt return all data

### ISSUE THREAD

**Issue by koren2888** [grafana/grafana#29524]
**What happened**: Get request to api route /api/folders returns only id, uid and title of each folder.

![Screenshot_20201202-102325_Chrome](https://user-images.githubusercontent.com/33178963/100847414-7a7ad900-3488-11eb-8405-dc491a659ddc.jpg)

**What you expected to happen**: According to the api doc, the request should also return for each folder the fields url, hasAcl, canSave, canEdit and more.
Link to API: https://grafana.com/docs/grafana/latest/http_api/folder/

![Screenshot_20201202-101701_Chrome](https://user-images.githubusercontent.com/33178963/100846892-bcefe600-3487-11eb-8daf-f8a79d523d03.jpg)

**How to reproduce it**: Get request to /api/folders

**Environment**:
- Grafana version: 7.3.3

**Comment by marefr** [comment]
This is an error in the documentation

**Comment by ying-jeanne** [comment]
tested, with api/folders, API returns only 
![image](https://user-images.githubusercontent.com/74549700/112815931-1e644200-9081-11eb-957f-423c596bed3d.png)

with api/folders/:uid, API returns details as above:
![Uploading image.png…]()

**Comment by marefr** [comment]
@ying-jeanne yes so the task of this issue is to update the documentation of the example response which currently is wrong, see https://grafana.com/docs/grafana/latest/http_api/folder/#get-all-folders

Here's the file that needs update: https://github.com/grafana/grafana/blob/master/docs/sources/http_api/folder.md#get-all-folders
