### ISSUE TITLE
Allow regex expression in alias

### ISSUE THREAD

**Issue by shangeo** [grafana/grafana#2973]
My series has the format: name.host.metrictype-protocol-operation-type.targetname-client-ipaddr.gauge.ops

I just want only the "type" to be displayed for the alias. But i am not able to do so as the alias field does not allow regex. So if i use $2, then "metrictype-protocol-operation-type" is displayed which is too long an alias.

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.

**Comment by flopp999** [comment]
I open this issue, because I am also interested in use Regex in Alias By.

Maybe this is implemented already
