### ISSUE TITLE
Relative time not overriden in snapshot url 

### ISSUE THREAD

**Issue by nasru1994** [grafana/grafana#29730]
**What happened**:
I'm trying to load the snapshot URL of a dashboard after overriding the time range that has been set in the visualization panel using the "relative" option. But after loading the snapshot URL, I found that the relative time range was not reflected in the particular panel.
**What you expected to happen**:
After loading the snapshot URL I was expecting the panel to be loaded with data with the relative time range applied
**How to reproduce it (as minimally and precisely as possible)**:
Step 1: Create a dashboard with any visualization panel.
Step 2: Edit the visualization and click on "Query options".
Step 3: In the "Relative time" tab add any time range. For eg:30d.
Step 4: Apply and Save the visualization.
Step 5: Make sure that the time range given in the dashboard and the relative time given in the visualization panel are different.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 7.3.4
- Data source type & version: Elasticsearch & [v7.10]
- OS Grafana is installed on: Linux
- User OS & Browser: Linux & Google chrome
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Hi @nasru1994, not sure I understand how this is going to work. 

The data in a snapshot is set for a specific point in time either by the chosen time in the timepicker or in your case by the relative time. This means we can't display any relative time data because what point in time would that data relate to? Another user might open the snapshot several hours, days etc after the snapshot is created and that wouldn't work.

I'm going to close this issue now, but we can always reopen it if there is more evidence presented.
