### ISSUE TITLE
Elasticsearch: Query requests no longer handled in backend  

### ISSUE THREAD

**Issue by eunice98k** [grafana/grafana#29788]
**What happened**:

After the latest refactoring of the Elasticsearch plugin, queries seems to no longer run on the backend. 
<img width="752" alt="image" src="https://user-images.githubusercontent.com/43913498/101959315-f5936c00-3bb9-11eb-9d78-3d2997cebed1.png">

Outputted error on console: 
`logger=alerting.evalContext ruleId=9 name="Panel Title alert" error="tsdb.HandleRequest() error type assertion to string failed" changing state to=alerting`

**What you expected to happen**:

This is a screenshot of what the expected output is to look like before the refactoring. It is expected to output the correct object with the query request and response.
<img width="745" alt="image" src="https://user-images.githubusercontent.com/43913498/101960713-d2b68700-3bbc-11eb-815f-fe2d099bb712.png">

**How to reproduce it (as minimally and precisely as possible)**:

Using the devenv, set up the Elasticsearch 7 sample datas and create a dashboard panel with Alerts. 
When viewing the `Test rule`, it outputs the error shown in the screenshot above.

**Environment**:

- Grafana version: Grafana 7.3.x
- Data source type & version: Elasticsearch 7.9.1
- User OS & Browser: MacOS & Google chrome

cc. @ahlaw @alolita

**Comment by ahlaw** [comment]
I think after the Elasticsearch query editor refactor, `timeField` is never set in the query now.

Just checked that the error is from the query object not containing the `timeField` field and failing here: https://github.com/grafana/grafana/blob/77d6100b44708e85d5b1233e4454847e88dcc306/pkg/tsdb/elasticsearch/time_series_query.go#L303

`timeField` is a required data source configuration option for Elasticsearch plugin and the backend query handler checks for this field, but for some reason it is optional in `ElasticsearchQuery`, which is why this bug went unnoticed: https://github.com/grafana/grafana/blob/77d6100b44708e85d5b1233e4454847e88dcc306/public/app/plugins/datasource/elasticsearch/types.ts#L65
