### ISSUE TITLE
This webpage has a redirect loop 

### ISSUE THREAD

**Issue by Tissa1** [grafana/grafana#2982]
when i login with the server to grafana i have always this page "This webpage has a redirect loop"

**Comment by torkelo** [comment]
whats you session store? out of disk space maybe? The default session store is using files.

There is a couple of other issues that describe the same issue, its usually caused by some problem with the session storage (not being able to store the session), or the browser cookies. Whats your root_url grafana setting? does it match the url in the browser? root_url is used when setting the grafana session cookie.

**Comment by Tissa1** [comment]
Hi,
I have always the same problem in all  the browsers.
What do you mean by session store ?

**Comment by jasonm** [comment]
I confirm that I saw the same issue when the disk was at 100% usage and the issue was resolved by clearing disk space.
