### ISSUE TITLE
Performance: Panel init performance can be improved (issue when > 100 panels)

### ISSUE THREAD

**Issue by piotr1212** [grafana/grafana#2994]
While trying to optimize page load times for some dashboards with many singlestats (+-80) we were surprised to notice that most of the load time was not spend in retrieving data from Graphite but in the loading/rendering of the page in the browser.

We notices that between "module.html?bust=" call and the "render" calls there is a delay of about 2 to 4 seconds. The delay seems to depend on browser, Chrome is slower than Firefox. 

To test this I've created a dashboard with 144 emtpy singlestats https://gist.github.com/piotr1212/5b3ebb4833e1c3996986. Loading this page takes about 6 seconds on my laptop with grafana 2.5-pre1. 

Is there a way to improve the frontend performance to lower the loading time?

**Comment by piotr1212** [comment]
It seems that Grafana 2.5 is +- 0.5 seconds faster than 2.1 but it still takes 2,5 seconds before it starts calling "render".

**Comment by torkelo** [comment]
Yea, all singlestats are loaded before the render calls go out (javascript in a browser is single threaded). This could perhaps be optimized slightly, but a loading time of about 2 seconds, and then 1-1-2 seconds to get data for all panels,  for a dashboard with 144 panels is pretty good (try loading a dashboard with 144 panels in any other dashboard software). 

Looking at it more closely the initial panel loading could be optimized, its slow now because of the way panels are loaded async (and require a angular digest cycle in between).
