### ISSUE TITLE
Paste in an SSL cert for Postgres, like for MySQL

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#29958]
**What would you like to be added**:
Allow me to paste an SSL cert in the Postgres data source config, instead of entering a file path.

**Why is this needed**:
The MySQL data source allows me to paste an SSL certificate into the UI, and it stores the cert in the Grafana DB. This is especially useful in hosted Grafana, where I don't have access to the filesystem. Postgres requires that I enter a file path for the SSL cert, which doesn't work in hosted Grafana. Would love to see the "paste" functionality for Postgres as an additional option.

**Comment by aknuds1** [comment]
Assigning this to @ying-jeanne since I understand she'd like to work on it.

**Comment by ying-jeanne** [comment]
as arve spot out during the daily discussion, we wanted to migrate pqx instead of pq package for postgres connection, we wanted to check whether in pqx we have a way to pass sslcert instead of sslcert filepath, https://pkg.go.dev/github.com/powerman/pqx#SSLMode according to the doc, it is still the filepath as parameter. In this case, we are going to store the string into file, then use the file path for connection. regarding security concern, we are going to write the file as readonly.

**Comment by aknuds1** [comment]
@ying-jeanne make sure only the user has permission to read the file, for security.

**Comment by aknuds1** [comment]
For reference, @torkelo has clarified that this functionality should come _in addition_ to the existing support for specifying paths to certificate files.
