### ISSUE TITLE
Gauge threshold colors are incorrect when their values were rounded up

### ISSUE THREAD

**Issue by luanhdeandrade** [grafana/grafana#29960]
**What happened**: The threshold colors remain unchanged when the rounded value reaches the threshold

**What you expected to happen**: The panel color stay the same as the one assigned to the number that is appearing in the panel

**How to reproduce it (as minimally and precisely as possible)**:
- Create a gauge panel
- Add Grafana as data source (random walk)
- Add transformation (Add field from calculation) and set the calculation as A-Series minus A-Series and alias the new field as Calc1
- Add transformation (Add field from calculation) and set the calculation as Calc1 + 99.451 and alias it as Calc2
- In Panel -> Display -> Fields set Calc2
- In Field -> Unit set Percent (0-100)
- In Field -> Decimals set 1
- Add Threshold (yellow color) and assign the value 99.4
- Add Threshold (green color) and assign the value 99.5
- Change the Base threshold to red

Final result can be seen here:

We can see below that the value (because of round up) reaches 99.5%, but its color is still yellow and not green (as I set to 99.5% in the threshold)

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/50885837/102905126-73c0ff80-4451-11eb-8f62-1dea77a8ca14.png">

<img width="396" alt="image" src="https://user-images.githubusercontent.com/50885837/102905212-8a675680-4451-11eb-8f92-618501cd6287.png">

<img width="405" alt="image" src="https://user-images.githubusercontent.com/50885837/102905233-93582800-4451-11eb-9975-eab5a232d283.png">

<img width="407" alt="image" src="https://user-images.githubusercontent.com/50885837/102905266-9f43ea00-4451-11eb-9f15-59700834f929.png">

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/50885837/102905287-a8cd5200-4451-11eb-8cc2-3b9029c4b0f0.png">

**Anything else we need to know?**:

**Environment**: Docker
- Grafana version: Grafana v7.3.4 (14c494085e)
- Data source type & version: Any (example in Grafana data source)
- OS Grafana is installed on: Linux/Docker
- User OS & Browser: MacOs/Safari
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
@luanhdeandrade thank you for creating this issue. It's an interesting one in terms of how Grafana should behave in rounding scenarios. 

The decimals option in the Field config is a data visualization option(or field display option), which means it does not influence the original raw value, but only tries to display it in the correct form. Mind, that when you show more decimals, then the value in your example does not actually apply yet to the threshold you want it to appear :

![image](https://user-images.githubusercontent.com/2376619/102998041-a688f780-4526-11eb-9f4a-a540aa27ddc8.png)

Thresholds calculation takes the raw value into consideration, rather than the one processed with field options.

From this standpoint, the visualization is correct. _The question is, if the rounding that you use is enough for the precision of your data?_ 

If this does not make sense to you please open a feature request.

**Comment by luanhdeandrade** [comment]
Hello. thanks for the info. We know that, mathematically, it is too rare to have numbers so exact, so in the real world numbers are most of the time inexact and this is why we sometimes make this kind of round when establishing goals.
I understand your perspective, but I think it would be very nice to have an option to make the threshold colors match the rounded number instead the raw value.
So, more directly answering to your question: Yes :)
I will proceed with the feature request then. Thanks

**Comment by dprokop** [comment]
Great, thank you very much @luanhdeandrade!
