### ISSUE TITLE
[FeatureRequest] Transforms: Add Script Option to add field from calculation transform

### ISSUE THREAD

**Issue by aldoferrante** [grafana/grafana#29973]
**What would you like to be added:**
Add a script option in the visualization panel transform tab mode select.

**Why is this needed**:
Currently only 2 options are available in the panel transform tab, "Binary Operation" & "Reduce Row", though useful, it may not provide flexibility for custom transformations. A JavaScript option provides more flexibility in transforming the data for application specific requirements. For example, storing a JSON in Influx DB string field, using JavaScript transformation in a visualization panel, we can parse the data from the JSON to display or reorder data and much much more.  A transform JavaScript option would address many customization requirements.
![image](https://user-images.githubusercontent.com/31166374/103019721-42116c80-4515-11eb-919d-a5c757794f5c.png)

**Comment by aldoferrante** [comment]
Additional comment to illustrate the need. We created a custom table to calculate a KPI and parse the JSON to filter certain variables. We used an SVG panel and wrote JavaScript in addition to SVG code to visualize the data. A better approach would be to use the standard Gauge Panel and write a JavaScript in the transform tab and not have to write code for visualization.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
