### ISSUE TITLE
grafana v7.1.3 use elasticsearch v7.5.0  Data source type bug

### ISSUE THREAD

**Issue by dususu** [grafana/grafana#29989]
grafana v7.1.3 use elasticsearch v7.5.0  Data source type bug

:> Have been abandoned,> instead of :>
Incorrect results：
![image](https://user-images.githubusercontent.com/23313692/103193581-d6b20b00-4917-11eb-9a0c-8b13e33721e1.png)
The correct results：
![image](https://user-images.githubusercontent.com/23313692/103193597-e03b7300-4917-11eb-9810-3b8dc939bd1b.png)

**Comment by Elfo404** [comment]
I'm not sure what's the issue here, `:>` is (among others) the proper way to do range queries. see https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-query-string-query.html#_ranges

I'm closing this, feel free to comment again if I missed something providing all the info requested in the issue template.
