### ISSUE TITLE
Add a `$__teams` global variable

### ISSUE THREAD

**Issue by ethirolle** [grafana/grafana#29996]
**What would you like to be added**:
Add a global variable (`$__teams`) that contains a list of the teams that the current user is a member of.

**Why is this needed**:
This would be similar to the `$__org` global variable: https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/#__org. It would allow the Grafana admins to customize a dashboard to return different results (or use different datasources) based on team membership.

In the customer's words:

> Scenario: If we have per-team datasources and want to have a shared dashboard where the datasource points to that team's datasource automatically.
> The more generic way might be to be able to define custom template variables for a team
> So the template variable could be used as the datasource name or part of the mane

An alternative fix for this same problem is described in this issue, which asks for per-team variables: https://github.com/grafana/grafana/issues/21071

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
