### ISSUE TITLE
Update links directing out to InfluxDB Flux docs

### ISSUE THREAD

**Issue by sjwang90** [grafana/grafana#30149]
From: https://github.com/influxdata/ui/issues/467 @lukeschantz 
Fixes completed in influxdata documentation; requires updates in Grafana

**What happened**:
Receive 404 when click on "Flux language syntax"

**What you expected to happen**:
Open Flux documentation when click on "Flux language syntax"

**Required Fix on Grafana**:
Need to remove “getting-started” from broken links:

Existing: docs.influxdata.com/influxdb/v2.0/query-data/get-started/getting-started
Replace: docs.influxdata.com/influxdb/v2.0/query-data/get-started

Existing: docs.influxdata.com/influxdb/cloud/query-data/get-started/getting-started
Replace: docs.influxdata.com/influxdb/cloud/query-data/get-started

**Comment by papagian** [comment]
Can you please retry? It's working for me (probably because of the new redirects). The link used is:
https://github.com/grafana/grafana/blob/1bc0cff736cb30e2f472ee59df5c54d6dc09c227/public/app/plugins/datasource/influxdb/components/FluxQueryEditor.tsx#L191
which redirects to:
`/influxdb/v2.0/query-data/get-started/getting-started/`
