### ISSUE TITLE
No data when time range is 1 hour but data shows fine when time frame is 3 hours in Grafana

### ISSUE THREAD

**Issue by som-kanade** [grafana/grafana#30200]
**What happened**:
There is no data when time range is 1 hour but data shows fine when time frame is 3 hours (> 1 hours) in Grafana

**What you expected to happen**:
Expected data to appear even when the time range is 15 min, 1 hour ( < 3 hours ) in Grafana

**How to reproduce it (as minimally and precisely as possible)**:
Json is attached for reference in doc format

**Anything else we need to know?**:
this is happening on certain dashboards only and not on all dashboards

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Influx
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome
- Grafana plugins: InfluxDB
- Others: NA

[dashboard.docx](https://github.com/grafana/grafana/files/5797729/dashboard.docx)

Please let me know if anything else is needed

**Comment by torkelo** [comment]
can you show what your query returns? what's your query and query options? What does query inspector say?

**Comment by torkelo** [comment]
sounds identical to https://github.com/grafana/grafana/issues/29858

**Comment by som-kanade** [comment]
i see the data in query inspector

**Comment by torkelo** [comment]
Can you show the query inspector results, and the graph results & panel json?

**Comment by som-kanade** [comment]
this is the query inspector 
```{
  "request": {
    "url": "api/datasources/proxy/157/api/v1/query_range?query=((sum(rate(mongodb_op_counters_total%7Bmongo_cluster%3D~%22INBOX-US%22%2Ctype%3D%22command%22%7D%5B20s%5D))%20by%20(instance))%20*%20on%20(instance)%20group_right%20mongodb_mongod_replset_my_name)%20*%20on%20(instance%2Cname%2Cservice)%20group_right%20mongodb_mongod_replset_member_health%7Bstate%3D~%22.*%22%2Cset%3D~%22inboxDb7%7CinboxDb0%7CinboxDb2%7CinboxDb3%7CinboxDb5%7CinboxDb1%7CinboxDb4%7CinboxDb6%22%2Cname%3D~%22172%5C%5C.31%5C%5C.35%5C%5C.115%3A27017%7C172%5C%5C.31%5C%5C.45%5C%5C.171%3A27017%7C172%5C%5C.31%5C%5C.46%5C%5C.182%3A27017%7C172%5C%5C.31%5C%5C.35%5C%5C.181%3A27017%7C172%5C%5C.31%5C%5C.42%5C%5C.38%3A27017%7C172%5C%5C.31%5C%5C.43%5C%5C.218%3A27017%7C172%5C%5C.31%5C%5C.36%5C%5C.116%3A27017%7C172%5C%5C.31%5C%5C.41%5C%5C.219%3A27017%7C172%5C%5C.31%5C%5C.46%5C%5C.240%3A27017%7C172%5C%5C.31%5C%5C.38%5C%5C.146%3A27017%7C172%5C%5C.31%5C%5C.42%5C%5C.201%3A27017%7C172%5C%5C.31%5C%5C.43%5C%5C.242%3A27017%7C172%5C%5C.31%5C%5C.38%5C%5C.84%3A27017%7C172%5C%5C.31%5C%5C.39%5C%5C.109%3A27017%7C172%5C%5C.31%5C%5C.44%5C%5C.101%3A27017%7C172%5C%5C.31%5C%5C.39%5C%5C.148%3A27017%7C172%5C%5C.31%5C%5C.39%5C%5C.29%3A27017%7C172%5C%5C.31%5C%5C.41%5C%5C.178%3A27017%7C172%5C%5C.31%5C%5C.42%5C%5C.235%3A27017%7C172%5C%5C.31%5C%5C.44%5C%5C.52%3A27017%7C172%5C%5C.31%5C%5C.47%5C%5C.53%3A27017%7C172%5C%5C.31%5C%5C.43%5C%5C.112%3A27017%7C172%5C%5C.31%5C%5C.46%5C%5C.106%3A27017%7C172%5C%5C.31%5C%5C.46%5C%5C.244%3A27017%22%7D&start=1610522295&end=1610525895&step=15",
    "method": "GET"
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "matrix",
      "result": []
    }
  }
}```

**Comment by torkelo** [comment]
Ok, so an empty result from Prometheus then, so not a Grafana issue but more a problem with the data or query

**Comment by som-kanade** [comment]
no @torkelo tried the same query in prometheus seeing metrics in prometheus UI

**Comment by Pingviinituutti** [comment]
I couldn't find an open issue with the problem, so I'll post why this happens at least on a setup that uses MariaDB as a datasource.

As people recommend, datetime data should be saved with the timezone UTC-0 in the database. This is OK, and when Grafana queries the data it shows correctly in the browser too with the client timezone applied.

But why would only time ranges of more than 1 hour return data, while 1 hour or less show no data? Well, Grafana's __timeFilter macro formats adds [FROM_UNIXTIME](https://mariadb.com/kb/en/from_unixtime/) functions so that the raw SQL query contains `WHERE timestamp BETWEEN FROM_UNIXTIME(time1) AND FROM_UNIXTIME(time2)`. The problem here is, however, that **`FROM_UNIXTIME` returns the value expressed in the database's current timezone**, which is the server's system datetime in MariaDB by default. Therefore, if the server's system time is something else than UTC-0, Grafana is actually querying an offset time range. If the default timezone for an ubuntu or raspberry pi is London UTC+1, the query of `now-1h` to `now` actually queries the database with `now` to `now+1h`, and returns no data. Depending on the server's/databases timezone, the offset varies and we see different no data issues.

This can be fixed with either changing the system timezone to a location with UTC-0, or by [changing it in the database config](https://mariadb.com/kb/en/time-zones/). A neat fix (feature?) could be to also add an option to set the session time zone in Grafana's datasource config.
