### ISSUE TITLE
World Map + Flux = Error when no results

### ISSUE THREAD

**Issue by schamock** [grafana/grafana#30290]
**What happened**:
When using the world map and selecting a time range that gives no results I get the following error: `Data error TypeError: undefined is not an object (evaluating 'this.datapoints.length')`
It's working perfect if the time range includes at least one event.
No problems when using InfluxQL

**What you expected to happen**:
When getting no events I just expect an empty world map just like using InfluxQL

**How to reproduce it (as minimally and precisely as possible)**:
Comparison of InfluxQL and Flux (Usecase is the visualization of blocked IPs with pfBlockerNG):
```
// working with InfluxQL:
SELECT count("action") FROM "ip_block_log" WHERE $timeFilter GROUP BY time($__interval), "GeoIP"
```
```
// not working with Flux when getting no results (but perfectly with at least one result):
from(bucket: "pfsense")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => (r._measurement == "ip_block_log" and r._field == "action"))
  |> group(columns: ["GeoIP"], mode: "by")
  |> count()
  |> drop(columns: ["_stop"])
  |> rename(columns: {_start: "_time"})
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.3.7 (1e261642f4) (was the same with 7.3.6)
- Data source type & version: Influx Version 2.0.3 (fe04d34)
- OS Grafana is installed on: raspbian buster
- User OS & Browser: not relevant
- Grafana plugins: World Map 0.3.2
- Others:

**Comment by ajimix** [comment]
I've having the same error but only after upgrading to grafana 8.0.0 and with MySQL dataset

**Comment by gabor** [comment]
@ajimix while it might be related, your issue is with MySQL not InfluxDB, please open a separate pull-request, so that things do not get mixed up (and add more details (the query you use, the structure of your data etc.)). thanks!

**Comment by gabor** [comment]
@schamock could you try to reproduce the problem with the current grafana version (8.0.2 or later)?

the handling of flux queries changed somewhat, so the problem might be solved now.
i tried a flux query, and was able to get world-map data displayed, and got no error-message when no events.

my oversimplified test-case:

- i had two measurements named "hh" added to influxdb2, both had a field named "num" that contained a number and a tag named "geohash"  that contained the geohash of the location
- i wrote this query:
```
from(bucket: "mybucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "hh")
  |> filter(fn: (r) => r["_field"] == "num")
```
- i used the transform "labels to fields"
- in the world-map configuration i set "location data" to "table"  and in the newly opened section set: "field mapping" to "geohash", set "metric field" to "num" and "geohash field" to "geohash"

and the world map worked.

then i "broke" the query by changing the measurement name from "hh" to "hh2". this of course means no data is found or returned. the world map panel did not show any places now, correctly, and also did not show any errors.

this is just one way how to get the data into the world-map panel, i assume the other location-data modes can be also used with a suitable flux-query. so please try out how it works for you in grafana8 and tell us if the problem is still there or not. thanks!

**Comment by schamock** [comment]
Hi @gabor,
thanks for your reply. With the upgrade to Grafana 8.x my World Maps where completely screwed ;) (which means: empty panels).
I tried to follow your advice, but it seams like that I'm doing something wrong.
That's what I tried:

```
from(bucket: "pfsense")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => (r._measurement == "ip_block_log" and r._field == "action" and r.Dir == "in"))
  |> group(columns: ["GeoIP"], mode: "by")
  |> count()
```
Location Data = table
Table Query Format = geohash
Location name Field = _empty_ 
Metric Field = _value (I assume that this is correct because that's the result of the grouping)
Geohash Field = GeoIP (according to the tag name)

Without the transformation I get an empty panel. As soon as I add the transformation "Labels to fields" an selecting "GeoIP" as the "Value field name" I can see the map again but I see a single circle at the north pole with an GeoIP of "n/a".

Also I see the following error I cannot really interpret: "Error: Missing geohash value"

The output of the Flux statement in InfluxDB seams to be fine.

If you could guide me, how to fix this, I would be very thankful!

**Comment by ajimix** [comment]
> @ajimix while it might be related, your issue is with MySQL not InfluxDB, please open a separate pull-request, so that things do not get mixed up (and add more details (the query you use, the structure of your data etc.)). thanks!

@gabor done https://github.com/grafana/grafana/issues/35917 thank you

**Comment by gabor** [comment]
@schamock thanks for trying out the upgrade (unfortunately we had to make some changes to the flux handling because of other problems).
what would help a lot is to get the csv-output from the influxdb-server (of course, sensitive parts removed).

if you run your query in the influxdb chronograf UI, there is a button below the graph-visualization to download-csv . it allows you to download the "raw" output from the influxdb database. could you please upload it here so i can look at it? please make sure to remove any part you consider private/sensitive.

(in general, it seem the world-map plugin has many possible modes (using that location_data field), and now it's a matter to find a working combination of that option and the flux query)

(also, my guess is that the mode i told you about wants geohash-strings, and you have in the database two-letter-country-codes or something similar, but we will see from the CSV)

**Comment by schamock** [comment]
@gabor You are right, I have to deal with the two-letter-codes. The above mentioned flux statement generates the attached output.

I also tried to configure the worldmap with "Location Data" = countries (the help text suggests, that this is the right setting for the 2-country-codes) without success (Error: undefined is not an object (evaluating 'this.datapoints.length')).
Another thing that I tried was adding a final `|> group()` to put everything in a single table, but this resulted in the same error.

Thanks for your assistance!

[2021-06-21-11-09_influxdb_data.csv](https://github.com/grafana/grafana/files/6685477/2021-06-21-11-09_influxdb_data.csv)

**Comment by gabor** [comment]
@schamock i think i found a way :) 

it's actually very similar to your original flux query, also, no need to do any adjustment to the world-map plugin settings  (so the location_data=countries is ok).

try this flux query:
```
from(bucket: "mybucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "ww")
  |> filter(fn: (r) => r["_field"] == "num")
  |> group(columns: ["country"], mode:"by")
  |> count()
  |> drop(columns: ["_stop"])
  |> rename(columns: {_start: "_time"})
  |> group(columns: ["country"])
```
it's basically the same as yours, except at the end, we do one more `group` thing.

afterwards, add a transform 'rename by regex', where in the first textbox enter `_value ` (there is an empty space at the end, and in the second textbox enter `` (nothing). the reason is that the labels that the system comes up with looks like `_value US` but we need it to be exactly `US` to pick it up by the world-map plugin. (actually i was debugging it by using the timeseries visualization, and i was looking at the legend-section, and kept transforming until all the names in the legend were two character country names).

now, the reason this works:

seems the way to fullfill worldmap-plugin's requirements is to give it data that has a time-column and numbers and two-letter-country-codes.

normally the flux query would only be:
```
from(bucket: "mybucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "ww")
  |> filter(fn: (r) => r["_field"] == "num")
  |> group(columns: ["country"], mode:"by")
  |> count()
```

the problem is, at this point, the result is not time-series data, there is no time-column anymore (that is correct, except world-map plugin does not like it).

so we do this trick at the end:
```
  |> drop(columns: ["_stop"])
  |> rename(columns: {_start: "_time"})
  |> group(columns: ["country"])
```

so now we have to create a time-column named `_time`, and if you check, every flux result has two timestamp-columns `_start` and `_stop`. so we drop `_stop` and rename `_start` to `_time`, and we got it. except, there is one more step. you see, `_start` and `_stop` are marked group=true (if you check the csv file). that means they are tags, not real data. so we add one more `group()` which says: the columns i name are tags, the rest are not tags. this way our needed column is not tag anymore but data, and all is well.

please try it and tell us if it helps!

**Comment by schamock** [comment]
@gabor Thanks for the detailed explanation of what's happening here! Your suggestion works perfectly! I'm back to the functionality of the Grafana 7.x

However: Now the original problem arises again: If datapoints are available, then the worldmap shows up like expected. But if the dataset is empty, I get the error mentioned in the original post.
As far as I understand, that is a situation, the worldmap plugin currently can't deal with.
Can you confirm this or did I miss anything?

(Just for context: I have too maps for visualizing IP-based blocks of my firewall. For the inbound view there a constantly hits -> no problem; outbound traffic is only blocked in very rare situations -> error of the plugin most of the time because of missing data)

**Comment by gabor** [comment]
@schamock thanks for reminding me about the original problem, i kind of forgot during the discussion 😄 
i was able to reproduce your problem now (the error when no data), will look into it more.

**Comment by gabor** [comment]
@schamock i looked into this more, and it seems the world-map plugin will need to be updated to handle this scenario, i created an issue in it's repo https://github.com/grafana/worldmap-panel/issues/320 

while waiting for that to get fixed, i recommend to run this query in influxql mode (it should be possible to setup your influxdb2 to answer influxql queries too).

another idea for a workaround would be to modify the flux query to artificially insert one more item to make sure the list is never empty, like an entry for a country-code with count=zero, but i'm not sure if this is easily doable. the influxql workaround is probably easier to do.

**Comment by schamock** [comment]
@gabor Thank you for the analysis and placing the issue in the correct place :)

**Comment by schamock** [comment]
Just in case anyone comes across this issue: I figured out how to avoid the error if the result is an empty dataset:

```
from(bucket: "pfsense")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => (r._measurement == "ip_block_log" and r._field == "action"))
  // the onEmpt:keep makes sure, that no empty dataset is returned.
  // This only works if the measurement has at least one entry in general (shouldn't be an issue)
  // This results in the country codes with 0 in _value, if no hits where found
  |> filter(fn: (r) => (r.Dir == "out"), onEmpty: "keep")
  |> group(columns: ["GeoIP"], mode: "by")
  |> count()
  // because the result can be empty, InfluxDB cannot generate a _time
  // _time is needed for the worldmap to work correctly, but the value itself has no impact
  // --> filling with now is sufficient
  |> map(fn: (r) => ({ r with _time: now() }))
  |> group(columns: ["GeoIP"])
```

In the end you should activate "Hide series" -> "with only zeros". And voila you get an empty map without error if no hits where found :)
Hope this helps

**Comment by gabor** [comment]
@schamock in grafana8.1 (beta is now available), there is a new panel called "geomap" (in beta), it might be a replacement for the world-map plugin. if you manage to get data where there is a 2letter-country-code column and a number-column, it should work fine with this panel (switch the Location-field in the panel to "lookup")

**Comment by schamock** [comment]
@gabor thanks for the info! As soon as 8.1 is released as stable I‘ll give it a try
