### ISSUE TITLE
annotations that represent a time range / period, not a point in time.

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#3031]
I'ld like to have some extended form of annotations so that i can mark time ranges on a graph, instead of points in time.
the graph below shows 3 benchmark runs that each have a start and stop annotation.
it's not immediately obvious where the starts and ends are.  it would be much nicer if the entire time ranges between start and end could be colored.
![hm](https://cloud.githubusercontent.com/assets/20774/10719741/c2ac02f4-7b64-11e5-8790-9cbe7076eeb6.png)

there's many use cases for this:
marking benchmark runs, marking outage periods, marking maintenance windows, marking alert statuses (i.e. time during which something was ok in green, and during which it was failed in red, etc)

here's a screenie of a graph that has a green marking, it could look something like this
![hm2](https://cloud.githubusercontent.com/assets/20774/10719777/5db289f8-7b65-11e5-8518-355f7c8f0ae7.png)

implementation wise, i see 2 main options:
- store events that have a start date and end date field. this makes it easy from grafana's perspective to get all needed data (because if for example the start of something was before the start of the graph, we still need to have it to apply coloring directly), though this requires a bit more complexity on the part of the tool inserting the events
- store start and ends as separate annotations. easier data format, easier for the tool inserting the events, but pretty tricky for grafana to get all data it needs.

**Comment by mtanda** [comment]
+1

**Comment by christianchristensen** [comment]
+1

**Comment by addshore** [comment]
+1

**Comment by mtanda** [comment]
I try to support this for in-progress Prometheus annotation PR (https://github.com/grafana/grafana/pull/2883).
This is diff of code.
https://github.com/mtanda/grafana/compare/prometheus_annotation_support...prometheus_annotation_support_range

The jquery.flot support time range annotation, I only change this line to make Grafana support time range annotation.
https://github.com/mtanda/grafana/compare/prometheus_annotation_support...prometheus_annotation_support_range#diff-6bf0b54acd1ab3c2f622db1f370f93ceL67

I want to use this for showing alert statuses.
In my use case, "store events that have a start date and end date field." is easier.

**Comment by xelite** [comment]
+1

**Comment by goldeelox** [comment]
+1

**Comment by xelite** [comment]
+1

**Comment by kylebrandt** [comment]
I would like this. One major plus is that you can possibly have a way to visualize a annotations that exist during but "outside" your query window. In other words, you can make it so annotations are not missing from view in the case that eventStart is before WindowStart && eventEnd is after WindowEnd.

**Comment by gtonello** [comment]
+1

**Comment by mcortinas** [comment]
+1

**Comment by vadimtk** [comment]
+1

**Comment by fipar** [comment]
+1

**Comment by jifwin** [comment]
+1

**Comment by smalik03** [comment]
+1

**Comment by jnicolson** [comment]
+1 - I have a use case where I am monitoring performance of a system which is globally distributed.  I would use Range based annotations to represent working hours of various geographic locations so that I could quickly see whether there was correlation between the metric and time time of day in a particular location.

**Comment by bodgit** [comment]
> In other words, you can make it so annotations are not missing from view in the case that eventStart is before WindowStart && eventEnd is after WindowEnd.

It would be useful if the only visible annotations where for example, end event, start event, end event, start event that the graph is highlighted from the beginning to the first end event, a gap, then a highlighted range, another gap, then highlighted from the last start event to the end of the graph, i.e. the start *or* end event is not (yet) visible.

Bonus points if there are overlapping but different events with different colours and it blends them.

**Comment by kylebrandt** [comment]
FWIW in Bosun they are represented with rectangles overlayed on the graph. The rectangles stay to the top of the graph, unless there is more than one in which case the stack downward until there is space available at the top again.

Normal cases tend to look like:

![screen shot 2017-01-25 at 10 52 25 am](https://cloud.githubusercontent.com/assets/1692624/22297885/af6e5e30-e2ec-11e6-8d98-c4750a3421bc.png)

Edge cases end up looking like:
![screen shot 2017-01-25 at 10 54 18 am](https://cloud.githubusercontent.com/assets/1692624/22297919/c2659756-e2ec-11e6-9064-cee288f2ce6b.png)

**Comment by Dieterbe** [comment]
Whoa Kyle. looks slick. if only we could get this in grafana too. cc @mattttt :angel:

**Comment by erezhdd** [comment]
+1

**Comment by nono303** [comment]
+1
OpenTSDB datasource already had annotations with startTime & endTime.
Actually only startTime is taken into account with

**Comment by srikiraju** [comment]
+1

**Comment by lukaszx0** [comment]
Hey I'm new to the grafana and I'm not familiar with its internals so I don't know how hard it'd be to implement it but I'm also in a need of this feature and would love to see in as a first class feature.

I'm thinking that since we do have _annotation regions_ feature available now, maybe we could base it on its foundation and open up API to have a custom annotation queries that'd provide data with markers (eg.: have optional `start` and `end` field that your query has to return so that grafana knows how to draw regions)

I realize that it gets tricky with multiple types of annotations and I like how bosun have solved that problem. Maybe it would be more readable it we'd put it as part of legend and then we can have labels on the left and when you hover over one of the regions (and only then), it'd show markers on the graph for it (see yellow region on sketch below).

Here's a quick and dirty sketch of how'd that look like based on [Annotations  grafana play example](http://play.grafana.org/d/000000010/annotations?orgId=1):

<img width="1393" alt="screen shot 2018-02-04 at 6 41 35 pm" src="https://user-images.githubusercontent.com/11562/35786660-a95663b2-09dd-11e8-97d5-6be28896e424.png">

@torkelo @Dieterbe what do you guys think?

**Comment by Dieterbe** [comment]
interesting idea. I think in practice this problem of too many (overlapping) annotations will not happen for some cases, and will happen in some others. so whatever solution we come up with, it should support "sparse" (range) annotations as well as "dense" (overlapping) annotations.

**Comment by torkelo** [comment]
this was implemented in v4.5 with grafana region annotations

**Comment by bodgit** [comment]
This only seems to be supported with the built-in annotations store, there doesn't seem to be a way to supply region annotations using other data sources.

**Comment by jlarmstrong** [comment]
+1
