### ISSUE TITLE
Migrate dashboards between organisations

### ISSUE THREAD

**Issue by Samuel1989** [grafana/grafana#3045]
Hi,

What I would like to be able to do is migrate a dashboard from one organisation to another... From what I can see this currently isn't available and I didn't have much luck finding an already open feature request.

Is this already available in 2.1.2? If not is it already planned for a future release?

Thank you,
Sam

**Comment by torkelo** [comment]
you maybe able to use this tool, https://github.com/m110/grafcli

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
