### ISSUE TITLE
Way to fix TS codestyle?

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#30477]
Running `prettier:write` or `lint:fix` tries to revert this change https://github.com/grafana/grafana/pull/30387 somehow

> Replace `(evt)` with `evt`

I remember it could be possible to run these commands to fix some styling issues. Now it produces changes in all files. Is it expected behaviour?

**Environment**:
- Grafana version: c91db6ae170f2e162bfb1114e71dc2a955a0cf10

**Comment by Elfo404** [comment]
This happened to me as well (also in different projects) when upgrading prettier. Usually, I found this happens because of mismatching versions being installed at the same time.

Have you tried completely removing your `node_modules` inside the repo? (you might have 2 different prettier versions installed in 2 different locations, ie. one in `node_modules` and another one in `packages/grafana-toolkit/node_modules`

OR

do you have prettier v1.x installed globally?

**Comment by simPod** [comment]
@Elfo404 oh daym. I have only run `yarn`. Will try to remove node_modules. I'm not installing anything globally :)

**Comment by simPod** [comment]
Yup, removing node_modules helped :/ Thanks!
