### ISSUE TITLE
Best effort behaviour for Alertmanager high availability setup

### ISSUE THREAD

**Issue by g574** [grafana/grafana#30509]
**What would you like to be added**:
Grafana is now able to connect to two (or more) Alertmanagers: https://github.com/grafana/grafana/issues/24195
However, if one of them is down, the "test" button throws an error message (notification channel settings).
Change the logic in a way that it connects to the one that is available.

**Why is this needed**:
The reason why people set up alertmanager clusters is redundancy. If Grafana does not send alerts because one of them is down that defies the purpose of having this cluster.

**Comment by aocenas** [comment]
@marefr pinging you as this seems like an oversight on our part.

**Comment by marefr** [comment]
Seems to me like this error shouldn't be returned here:
https://github.com/grafana/grafana/blob/0079a275afcc1dfe85f169ad0ddd67f6ef2b53b0/pkg/services/alerting/notifiers/alertmanager.go#L185

However, if all of the URL's fails it should probably return an error.

@g574 interested in opening a PR for fixing this? 

Pinging @alistarle here as well since he implemented support for multiple URL's in #24196.

**Comment by kurokochin** [comment]
Hi @marefr, I'm new to Grafana, but can I try work on this?
