### ISSUE TITLE
Bug: Shared tooltip and non continous series behave strangely 

### ISSUE THREAD

**Issue by rvrignaud** [grafana/grafana#3063]
Hello,

Using today latest binary it seems that date is not updating anymore in the tooltip after a "hole" of points in the graph.

A gif will be much more easy to understand:

![lre2hrchiv](https://cloud.githubusercontent.com/assets/525763/10789304/eada1044-7d7c-11e5-9403-7b4e494f513e.gif)

**Comment by torkelo** [comment]
cant replicate this, what data source are you using?

**Comment by rvrignaud** [comment]
We are using Influx 0.9.

**Comment by torkelo** [comment]
do you have a fill(0) or fill(null) to the query?

**Comment by pquentin** [comment]
We do have fill(none), yes.

**Comment by torkelo** [comment]
I asked for fill(0) or fill(null) :)   they are important for some cases, because they generate null values which make the easier for some of graph features to behave correctly.

**Comment by rvrignaud** [comment]
Hello,
@pquentin is working with me and talk about the same problem. We do use indeed fill(none).
Our query is like:
```
SELECT non_negative_derivative(mean("value")) AS "value" FROM "cpu/usage_ns_cumulative" WHERE "container_name" =~ /$rc$/ AND "pod_namespace" =~ /$namespace$/ AND $timeFilter GROUP BY time($interval), "pod_name" fill(none)
```
The data come from heapster (https://github.com/kubernetes/heapster).
In that case we are using GROUP BY "pod_name". Our pods tags (or field I'm not sure) is really not stable. We have multiple pod_name changing all the time.
It seems that if we use fill(0) or fill(null) all existing pod_name values are displayed which make dashboard unusable.

Maybe I'm missing something or doing something wrong.
What I should add is the "blocked tooltip date" may be related to a changed pod_name (used by group by).
Is that more clear ?

**Comment by neldog2** [comment]
We do have fill(null) and are hitting this same problem. I'm not sure exactly what is going on, obviously the timestamps are fine.  We are running the influxdb 0.12.1 and grafana 3.0 beta 7.  Changing the null values graphed from connected to zero fixes the timestamps on the shared tooltip.

![serpentinepresentgodwit](https://cloud.githubusercontent.com/assets/9114046/15079338/8bb2d974-137d-11e6-824a-21dfd2cffcc0.gif)

**Comment by torkelo** [comment]
Yes, that is correct.  Try setting a min limit for group by time so itit matches the rate you write data

**Comment by neldog2** [comment]
I'm assuming you are referring to the group by time interval at the bottom, as opposed to in the query.  If I set this to >60s(data written to influxdb every min) nothing changes at all and the tooltips are still erroneous.  I set this to >60s according to the little quick help button at the bottom that explains the group by time interval option.

![chrome_2016-05-06_12-50-29](https://cloud.githubusercontent.com/assets/9114046/15081577/2cdb2292-1389-11e6-8ae5-1d9baa4d189b.png)

**Comment by sblatnick** [comment]
We see the behavior on Grafana 3.0.4.  I erroneously opened duplicate bug #5572 where you can see more details.

**Comment by Krinkle** [comment]
Presumably the same bug is also causing graphs with metrics of consistently different intervals to have less-than-useful timestamps:

Here is a graph using Graphite and `summarize()`, showing daily and weekly summaries over top.

<img width="1354" alt="screen shot" src="https://cloud.githubusercontent.com/assets/156867/17260632/6e035028-55c9-11e6-9c6f-e56afd4fa248.png">

The tooltip is following the timestamps of the last (and least precise) metric: "weekly". Above it's hovering around June 18 04:00 but still showing the timestamp of the last weekly data point, June 11 20:00.

The problem is limited to just the timestamp. It seems to know what timestamp it is really at, since it presumably needed each value's timestamp in order to know which value to display. At that point, it should presumably pick the most accurate / latest timestamp.

I tend to work around this bug by setting the z-index of the most precise metric to 1 ("95" in my case, the one without summarize). Here, hovering the exact same point with the same values:

<img width="1334" alt="screen shot 2016-07-29 at 20 19 36" src="https://cloud.githubusercontent.com/assets/156867/17260728/dd92a6dc-55c9-11e6-841d-ea4c5c6186c5.png">
