### ISSUE TITLE
NodeGraph: Improvements kitchen sink

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#30630]
This is list of issues and possible improvements of the NodeGraph component for bookkeeping.

- [ ] As the color sections in a circle around nodes are driven by the data provided, each data source can have different colors with different meaning. Some sort of legend with explanation of what the colors means would help understand it. Also this legend could then be used to offer some additional actions like highlighting nodes based on max/min values of some stats.
- [ ] When hovering over node we also highlight and show stats of the edges connecting to it. It may be useful to have color coded or other emphasis on which edge is going in to the node vs out of the node.
- [ ] The context menu details (metadata) styling should be more aligned with other parts of grafana and how we present data.
- [x] Use better layout for the graph, something similar to https://github.com/juliuste/transit-map with more aligned nodes could help with quicker scanning of the graph.

### Performance
- [ ] At this moment we have a limit of 1500 nodes. At that point the main bottleneck seems to that browser needs to recalculate styles for each node on each pan or zoom action (because they are driven by css transform). There is a requirement to be able to "show" ~8k nodes. One possiblity is to improve the performance to be able to show the nodes (maybe with conditional rendering and responsive styling) but other is to provide some different means to make sense of such big graph that would be more useful to the user (different layout, search, ordering or highlighting just specific nodes.).

**Comment by lmangani** [comment]
Hope you don't mind some chaining a couple ideas this is the only topic on `nodeGraph` - feel free to delete if not appropriate.

### Documentation
* [ ] Documentation and/or a dummy datasource with the compatible format would greatly help others adopt this new component in other datasources. It seems the code would expect the following object structure: 
```
[
	{
      name: 'nodes',
      refId: 'A',
      fields: [
		{
			id: "one",
			title: "one",
			subTitle: 'service',
			arc__success: 0.5,
			arc__errors: 0.5,
			mainStat: 0.1,
			secondaryStat: 2,
		},
		{
			id: "two",
			title: "two",
			subTitle: 'service',
			arc__success: 0.5,
			arc__errors: 0.5,
			mainStat: 0.1,
			secondaryStat: 2,
		}
      ],
      meta: {
        preferredVisualisationType: 'nodeGraph',
      },
    },
    {
      name: 'edges',
      refId: 'A',
      fields: [
		{
		  id: "one" + '--' + "two",
		  source: "one",
		  target: "two",
		}
      ],
      meta: {
        preferredVisualisationType: 'nodeGraph',
      },
    }
];
```

**Comment by aocenas** [comment]
@lmangani there is a section in the docs for this https://grafana.com/docs/grafana/latest/panels/visualizations/node-graph/#data-api. It was added a few days after the beta so may have missed it. Also there is a scenario in the https://grafana.com/docs/grafana/latest/datasources/testdata/ though that isn't documented (seems we forget to add docs for new scenarios). Let me know if that makes sense or you think something more should be added for the docs.

**Comment by lmangani** [comment]
Thanks @aocenas you are a star, this is super useful! Will get on with more reading. Do you know if there are plans to let loki support nodeGraph type responses?

**Comment by aocenas** [comment]
@lmangani not sure about loki. Loki don't naturally store this kind of data so any transformation would be application specific. You could probably use the transformations functionality to get the data into proper shape or create a different plugin that would communicate with loki and do the transform there. What we will probably do is support this kind of view for tracing data sources where going between trace timeline and graph is more straight forward.

**Comment by lmangani** [comment]
@aocenas actually.. that's precisely our case where we can return/form a valid nodeGraph object (using cLoki or JSON in loki) but there are no ways for the loki datasource to pass down objects it does not support to the visualization despite them being perfectly valid in format. having Loki support for a 'nodeGraph` type allowing the structure would be awesome to have in final 7.4.

**Comment by aocenas** [comment]
Yeah unfortunately I don't think there will be any default support for loki in 7.4 nor in 8 to be honest.

At the same time I am not sure I understand your usecase, could you provide some sample of the data you store in loki and want to visualise in the node graph?

Also we will probably keep the Node graph as beta state for at least one more release and we want to try to figure out if the data structure can be simpler so it would be easier to use form other data sources but that will take some time.

**Comment by lmangani** [comment]
To be clear, and taking advantage of the "beta" stage, rather than an expectation of support I was referring to the need for an abstract type being available to developers and format hackers - if a datasource can be selected, it should be able to at least offer a type back, and as unlikely as loki might be, it seems the only exception forcing input type results constraints and not passing data to the viz. Having loki being able to "pass down" a `nodeGraph` type with compatible JSON would be enough for this to happen, with no expectations of support or stability of course - but it could make this a more exciting beta if other datasources could also support it. Our usecase is very creative and more tailored for plugin/datasource development, so not necessarily a good end-user usage example, but we've done the very same job in Kibana many moons ago. Thanks again, this is all very exciting.

**Comment by hectorj** [comment]
Hi!
Adding https://github.com/grafana/grafana/issues/33358.

To add to @lmangani 's remark, I also want to say I was surprised I needed special datasources to use this panel.
I originally wanted to use an SQL datasource, and thought that if I could get the fields right it would work.
But we can't set the dataframes' `preferredVisualisationType` nor `name` from most datasources so this is not currently possible, though it would be nice.

I'm not familiar enough with grafana's internals to know why `preferredVisualisationType` was required in the first place, so I'm not sure how hard it would be to implement.

**Comment by shaikadil95** [comment]
> Hope you don't mind some chaining a couple ideas this is the only topic on `nodeGraph` - feel free to delete if not appropriate.
> 
> ### Documentation
> * [ ]  Documentation and/or a dummy datasource with the compatible format would greatly help others adopt this new component in other datasources. It seems the code would expect the following object structure:
> 
> ```
> [
> 	{
>       name: 'nodes',
>       refId: 'A',
>       fields: [
> 		{
> 			id: "one",
> 			title: "one",
> 			subTitle: 'service',
> 			arc__success: 0.5,
> 			arc__errors: 0.5,
> 			mainStat: 0.1,
> 			secondaryStat: 2,
> 		},
> 		{
> 			id: "two",
> 			title: "two",
> 			subTitle: 'service',
> 			arc__success: 0.5,
> 			arc__errors: 0.5,
> 			mainStat: 0.1,
> 			secondaryStat: 2,
> 		}
>       ],
>       meta: {
>         preferredVisualisationType: 'nodeGraph',
>       },
>     },
>     {
>       name: 'edges',
>       refId: 'A',
>       fields: [
> 		{
> 		  id: "one" + '--' + "two",
> 		  source: "one",
> 		  target: "two",
> 		}
>       ],
>       meta: {
>         preferredVisualisationType: 'nodeGraph',
>       },
>     }
> ];
> ```

**Comment by shaikadil95** [comment]
I am new to NodeGraph and trying out with Graphql queries. Somehow I can not figure out the structure required for the NodeGraph, can anyone please help?

**My Graphql Query:**
`mutation {
  data:exportNodeGraph(input: {nodeGraphType: TEMPLATE, id:1}) {   
    name
    fields {
      ... on GraphNodeField {
        id
        title
      }
      ... on GraphEdgeField {
        id
        source
        target
      }
    }
    frame {
      meta {
        preferredVisualisationType
      } 
    }
  }
}`

**Response**
`{
  "data": {
    "exportNodeGraph": [
      {
        "name": "nodes",
        "fields": [
          {
            "id": "1",
            "title": "TITLE"
          },
          {
            "id": "2",
            "title": "RU"
          },
          {
            "id": "3",
            "title": "Sim-1"
          }
        ],
        "frame": {
          "meta": {
            "preferredVisualisationType": "nodeGraph"
          }
        }
      },
      {
        "name": "edges",
        "fields": [
          {
            "id": "1--2",
            "source": "1",
            "target": "2"
          },
          {
            "id": "2--3",
            "source": "2",
            "target": "3"
          }
        ],
        "frame": {
          "meta": {
            "preferredVisualisationType": "nodeGraph"
          }
        }
      }
    ]
  }
}`

**Comment by themikezipp** [comment]
+1 Above question. Does anybody have a working example format that we can use as a template?

I would assume the example here: https://play.grafana.org/d/Pbk2rfBGz/node-graph?orgId=1&from=now-5m&to=now
Is using a format like below, but I can't seem to re-create the viz using below formatting or any of the examples mentioned above.

{"name": "nodes", "refId": "A", "fields": [{"id": "0", "title": "root", "subTitle": "client"}, {"id": "1", "title": "service:1", "subTitle": "service"}], "frame": {"meta": {"preferredVisualisationType": "nodeGraph"}}}
{"name": "edges", "refId": "A", "fields": [{"id": "0--1", "source": "0", "target": "1"}], "frame": {"meta": {"preferredVisualisationType": "nodeGraph"}}}

**Comment by htroisi** [comment]
I am using Grafana version 7.5.1. I reproduced the Node Graph test data (with 2 nodes) from the [TestData DB](https://grafana.com/docs/grafana/latest/datasources/testdata/) datasource using my own datasource. When I switch from Table (to confirm the data) to Node Graph, I get an empty Node Graph. I've inspected the raw data and don't see anything suspicious.

**Comment by tomasfreund** [comment]
I'd also appreciate some more information regarding the data format and data source compatibility.
I have a PromQL query and I'm producing data in a format that matches the requirements in documentation. Nodes get displayed without any issues but when I add a query with edges, the whole panel just displays `0` in the bottom left corner.
Am I doing something wrong?

**Comment by shaikadil95** [comment]
> I'd also appreciate some more information regarding the data format and data source compatibility.
> I have a PromQL query and I'm producing data in a format that matches the requirements in documentation. Nodes get displayed without any issues but when I add a query with edges, the whole panel just displays `0` in the bottom left corner.
> Am I doing something wrong?

Can you share the structure of data?

**Comment by tomasfreund** [comment]
I'm using a labels to fields transformation to get the desired structure. The output in a table format looks like this:
| id  | title | source | target 
| ------------- | ------------- | ------------- | ------------- |
| node1  | Node 1 |
| node2 | Node 2 |
| node1-node2 | | node1 | node2 |

If I omit the edges, the nodes get displayed, adding any edges causes the whole panel to break. The ids in source and target match ids of existing nodes.

**Comment by aocenas** [comment]
Sorry for late reply here. For people who asked before Grafana 8.0.0, there was a bug where the `preferredVisualisationType` was required even in dashboards, basically preventing showing data from any other data source than few that explicitly supported the NodeGraph. In 8.0.0 this should not be an issue.

For the format, the docs are here: https://grafana.com/docs/grafana/latest/panels/visualizations/node-graph/#data-api
I think the main confusion stems from requirement that nodes and edges have to be 2 separate data frames. That means, for most data source I think, that you have to do 2 queries per panel. 1 that returns just the nodes and then second that returns the edges.

**Comment by tomasfreund** [comment]
Hi, thanks for the reply. I'm using Grafana 8.0.2 and have tried 2 separate queries, it does not seem to help, is there a requirement for the query name or something like that?
Could the issue be that I'm using a Prometheus data source with labels to fields transformation? Without the transformation it does not work either.

**Comment by tomasfreund** [comment]
Ok, I managed to make it work, I removed the transformation and made it 2 separate queries named `nodes` and `edges`.
I think the main issue is a lack of error messages and maybe missing examples for common data sources like Prometheus.

**Comment by lmangani** [comment]
Following the notes of @tomasfreund (thanks!) I also managed to make the visualization work using the latest 8.x release and clickhouse/vertamedia driver with two simple table format queries (nodes, edges) and no transforms. For anyone else trying, please note all source/target edges *must* exist as nodes ids for the visualization to work, and mainStats *must* be floats to display.

**Comment by hugodopradofernandes** [comment]
The problem is that using prometheus the only way I could do it work displaying nodes is using transformation "labels to fields". But it merges all queries on same table/dataframe....

**Comment by wz2b** [comment]
The easiest way I found to test this is to use the InfluxDB flux datasource and just generate some static objects
```
import "experimental/array"

array.from(rows: [
  { id: "A", title: "Circuit A", mainStat: 1.23, secondaryStat: 2, detail__url: "http://something" },
  { id: "B", title: "Circuit B", mainStat: 2.34, secondaryStat: 3, detail__url: "http://somethingelse" },
])
|> yield(name: "nodes")

array.from(rows: [
  { id: "1", source: "A", target: "B", detail__volts: 12470.0}, ])
  |> yield(name: "edges")
```

What this does is yields two static tables that the Grafana Influx driver turns into a resultset with two dataframes, one for nodes and the other for edges.

A number of things don't work for me still:

 * I think detail__volts should show up on the edge, at least when you hover over, but that's not working at all
 * Same thing for the detail__url I added ... doesn't work.

The documentation on the frame formats is excellent - thank you Grafana for documenting this so carefully.  However, it's not particularly convenient to generate two data frames from most datasources.

My main feature requests for this are as follows:

* It would really make things easier if instead of requiring two dataframes in a single response that you allow them to be separated as "Query A" and "Query B."  That would make it trivial to adapt this to other data sources including basic SQL.  What's even better is that it'd let you use a mixed data source - for example to store the node data in a TSDB, and the relationships in another place, like SQL.
* Static node data - like the name of the node - should be somehow separable from the node metrics (mainStat and secondaryStat) so you don't have to repeat all that data if you're using a TSDB.  If you're using influxdb it's not that bad to store the node name as a tag the convert it from a tag to a field in the query.  That's OK, but the relationship between the Node ID / Node Name is usually a very static configuration, and the mainStat/secondaryStat are dynamic so that really warrants them being stored some other place.

Storing static data in a TSDB really isn't a good thing.  I think the nodes, their names, and their relationships really belong somewhere else.  If you implemented Query A / Query B as I described, then you could actually store your nodes, their names, and their edges/relationships in just a JSON file; choose the mixed datasource; and fetch the node topology from an HTTP/REST/JSON file - it would be super simple.  What you'd have to do next is be able to query the dynamic data ... mainStat, secondaryStat, and any detail__* that might want to change.

**Comment by wz2b** [comment]
Some other feature I really want to have:

* Let me specify a "node url" field that's what happens if you click on the node.  My primary use case for NodeGraph is something like a network diagram.  What I really need badly is a way that I can click on a node and it will show me some details for that node on the same page.  IDEALLY this wouldn't be a URL at all, it would change a dashboard variable (which would cause other panels on that dashboard to possibly update).
* I would love to be able to display some data on the edge.  It could be a single metric, or a static label for that edge.  I'm working on a grid application so those edges are high voltage feeders.  Being able to show live current (amps) on those edges would be beyond awesome.
* There should be some way to format the metric (the float) - at least # of digits past the decimal
* Node color based on a Value Mapping / Range Mapping in combination with a user-selected field.  So for example I return `detail__state` and map 1 to green, 2 to yellow, ...  or even better, just let me send you `detail__rgb` ... and I want to ask this for both nodes (most important) and edges (also very useful)

I hope this feedback is helpful.  NodeGraph is pretty awesome so far.  I can't wait to see it mature!

**Comment by HighPlainsCoder** [comment]
> @lmangani there is a section in the docs for this https://grafana.com/docs/grafana/latest/panels/visualizations/node-graph/#data-api. It was added a few days after the beta so may have missed it. Also there is a scenario in the https://grafana.com/docs/grafana/latest/datasources/testdata/ though that isn't documented (seems we forget to add docs for new scenarios). Let me know if that makes sense or you think something more should be added for the docs.

That testdata is exactly what im searching for, but I dont see it at that link (did it get removed in a later revision?)  Can you or anyone point me to example testdata for node graph?

**Comment by devrimdemiroz** [comment]
> Ok, I managed to make it work, I removed the transformation and made it 2 separate queries named `nodes` and `edges`.
> I think the main issue is a lack of error messages and may be missing examples for common data sources like Prometheus.

@tomasfreund , I have tried your approach. Not limited but the closest to a result was a for a spring/prometheus datasource with two queries as SUCCESS and ERROR. Where I then merge on transformation and add calculations for mainStat,arc__success, arc__error.

The point I reached
- even with one query named "nodes" containing data fields mentioned, I was unable to reflect any second "edges" query that fits on Grafana
- nodes do appear on screen, but no way arc__success, arc__error is visible in legend nor their expected colours on nodes
Below is a sample query with instant/table selected.(non-instant same result)

```
label_replace( label_replace( 
  sum ( 
     rate(
              http_server_requests_seconds_count{env="test",outcome="SUCCESS" }[5m]
             )  * 60 
          ) by (instance) 

, "id", "$1", "instance", "(.*)") , "title", "$1", "instance", "(.*)") 
```

After transformations [merge, five add field from calculation, filter by name]
 table data as follows:


id | title | mainStat| arc__success| arc__error |secondaryStat
---|---|---|---|---|---
1 |p-1 |25.3 |100|0 |0
2 |p-2| 25 |99 |0.01|0 |0

You said you managed. Can you provide an example?

**Comment by marwin1991** [comment]
Any updates? @tomasfreund

**Comment by devrimdemiroz** [comment]
I would be happy to hear an update as well. Since then, sharing my knowledge as below...

The "service graph" feature is experimentally available at this point in time.  https://grafana.com/docs/tempo/next/server_side_metrics/service_graphs/

I did used it as documented , it works great and will be available in otel collector soon. 

As an impression, saw that the graphs can be customary constructed using correct labeling on prometheus metrics.

**Comment by mikegorman-nf** [comment]
I see several people stating they have succeeded with no transforms.  Is this a requirement?  I'm using an Elastic data source, and can't rename the fields, so I am transforming by RegEx to name the fields per the node graph requirements.  I get an error the nodes data frame requires an id field, making me believe the transform doesn't affect the frame, just the visualization output.

**Comment by deefdragon** [comment]
echoing @wz2b re displaying data on edges

I am working on an application that is largely asynchronous with data being passed from microservice to microservice via queues. The node graph would be an almost *perfect* way to visualize the state of the entire application but:

Its rather hard to see the state of the queues without the ability to change the way edges are displayed (color or width of the edge arrows based on the primary/secondary statistic would be ideal)

Also, the ability to have multiple edges between the same nodes, and determine how they are displayed relative to each other (stacked, fanned out, etc.) would be nice. We have different priority queues between the different services that would need to be monitored.

**Comment by deefdragon** [comment]
bumping to un-stale. Node is great but still could use some of the mentioned improvements.
