### ISSUE TITLE
[Question] Database compatibility

### ISSUE THREAD

**Issue by druchoo** [grafana/grafana#3069]
Is database structure different across 2.0.x, 2.1.x, 2.5.x? On 2.0.x now, if we upgrade to newer version can we rollback if needed, while using the same database?

**Comment by torkelo** [comment]
not sure between 2.0 and 2.1,    2.5 and 2.1 should be compatible 

The only thing to think about is that if you use 2.5 and start loading and saving dashboards, they might not look / work ok in 2.1 and 2.0.  Because grafana will upgrade dashboad schema when the dashboard loads so if you save a dashboard it will get the new schema.
