### ISSUE TITLE
graphite sumSeries does not give correct results

### ISSUE THREAD

**Issue by aather** [grafana/grafana#3091]
I want to aggregate receive/send network throughput metrics across all instances (in cluster), and thus tried using sumSeries graphite function, but not getting correct results.  Any idea what is the best way to aggregate metrics from various sources.  

In the graph below,  I am using grafana templating feature to match all instances in the cluster. In this case, cluster has three instances and I want to calculate aggregate throughput across the cluster. 
![net](https://cloud.githubusercontent.com/assets/5282686/10833147/256b8b86-7e4d-11e5-8ba2-ed2178e32fef.png)

**Comment by torkelo** [comment]
This is not a Grafana issue but a graphite query issue. 

But I might can give you some pointers to what could be going wrong, hm.. do not see whats wrong in the image car to enlighten me?

**Comment by torkelo** [comment]
also using max and avg in the legend can be misleading, as your queries will be using consolidateBy avg  (since you do not specify one), avg and max cannot be accurate at the same time as the legend values are calculated client side by Grafana after Graphite will do aggregation (point consolidation) , so in this case depending on time range only avg will be accurate, if you added consoldateBy(max) to your functions then max would be accurate

**Comment by cstroe** [comment]
Isn't it supposed to be `sumSeries(#A)` ?

**Comment by FS1360472174** [comment]
met same issue
