### ISSUE TITLE
Provisioning dashboard permissions ACLs as a code

### ISSUE THREAD

**Issue by nikitsenka** [grafana/grafana#30936]
As a DevOps engineer i would like to have capability to configure dashboard permissions ACLs on the grafana server start
So then i can persist and manage them as a code  
Currently it is not possible according to the documentation: https://grafana.com/docs/grafana/latest/administration/provisioning/

**Comment by guymeron** [comment]
Hi  @torkelo & @hugohaggmark 

I believe the following items are duplicates:
https://github.com/grafana/grafana/issues/30936
https://github.com/grafana/grafana/issues/19172
I would like to contribute a fix which will allow provisioned ACLs in dashboards.
Please let me know if this change is acceptable and I can continue with creating the PR.

**Comment by guymeron** [comment]
@torkelo @hugohaggmark 
Please let me know if this change is acceptable.

**Comment by torkelo** [comment]
There is an HTTP Api that can be used to provision dashboards and permissions

**Comment by guymeron** [comment]
Thanks @torkelo,
In K8S when a pod is deleted and then recreated, its manually defined ACLs don’t exist in the new pod.
This requires http API call upon pod creation.
Until the API call is requested, all dashboards are visible for all user types. This might expose dashboards with data which not all users should be exposed to e.g. customer data which should not be seen outside of EU region.
Since the dashboards are loaded once the application is launched, I’m willing to add the code to provision the ALCs with the dashboards.
