### ISSUE TITLE
Variables: Data source variable does no longer contain a separate default option after 7.4.0 upgrade.

### ISSUE THREAD

**Issue by hawran** [grafana/grafana#30996]
**What happened**:
We have got a couple of DataSources configured, one DS has been marked as `default`. This DS has been selected within a _variable_ (of the `Datasource` type) - I mean there was the something like **default** "value" among menu items and this value was selected. (The _variable_ is being referenced as a datasource for queries within a panel.)

After upgrade to `7.4.0` the `default` datasource has disappeared from the datasource _variable_, hence all data visualisations have failed. 

**What you expected to happen**:
The `defalut` "tag" on a datasource has some practical value.

**How to reproduce it (as minimally and precisely as possible)**:
1. Mark one datasource as a default one.
2. Configure a variable of the `Datasource` type within a dashboard.
3. Try to select the `default` value within this variable, there is not nothing like that.

**Anything else we need to know?**:
As a quick fix we have created a new datasource named `default`.

**Environment**: N/A
- Grafana version: 7.4.0
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
@torkelo I remember we did a change to the data source picker and I think this is an issue that we might have missed?

**Comment by torkelo** [comment]
yes, guess an extra default option is needed. 

Here https://github.com/grafana/grafana/blob/master/public/app/features/variables/datasource/reducer.ts#L44 we should add an extra option for the default data source I think. 

But the sources list there is the wrong type it's not the original list type returned by DataSourceSrv.getList (that has a isDefault bool) so might need to change something in order to pass that original source list to the reducer 

https://github.com/grafana/grafana/blob/master/public/app/features/variables/datasource/actions.ts#L24
