### ISSUE TITLE
DataFrame: Figure out where we should parse date strings to epochs

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#31016]
We had two fixes in 7.4.1 that handle date string to epoch parsing, but this is currently handled by individual panels or visualizations. 

There should be a more central unified way to handle this. 

GraphNG PR: https://github.com/grafana/grafana/pull/30981/files 

Old Graph PR: https://github.com/grafana/grafana/pull/30972

**Comment by torkelo** [comment]
@ryantxu can you take a look at this?

**Comment by ryantxu** [comment]
I think this can/should be in the `toDataFrame()` helper.  The string dates all come from the old table format.

We do need a generic way to support strings as dates -- or time with 1s precision or just year, etc

**Comment by leeoniya** [comment]
we're also not too far off from https://en.wikipedia.org/wiki/Year_2038_problem :D

**Comment by leeoniya** [comment]
there is potential for some information loss, since timestamps cannot encode the timezone or the "local" time, e.g. `Tue, 09 Feb 2021 20:54:52 GMT`. probably not relevant but something to keep in mind if we're gonna make the conversion uniform and not panel-dependent. any kind of custom parsing happening in panels that expects localized date strings goes out the window. i think the trade-off is worth it.
