### ISSUE TITLE
Incorporate addVariable flow into core variable e2e tests

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#31035]

**Comment by vickyyyyyyy** [comment]
For more context, our enterprise plugins use flows that are not currently being used in `grafana/e2e` (they are only exported) - these include `addAnnotation` (https://github.com/grafana/grafana/blob/master/packages/grafana-e2e/src/flows/addDashboard.ts#L101) and `addDashboard` (https://github.com/grafana/grafana/blob/master/packages/grafana-e2e/src/flows/addDashboard.ts#L41 additionally.

This means that if we have any breaking changes with latest stable version of Grafana, we won't receive any feedback on these flows being broken until our enterprise plugins' e2e tests fail. Our enterprise plugins builds would also be blocked until the fix is released in the next version. Currently also in discussion with our team on updating our build process to allow flexibility for this.
