### ISSUE TITLE
Singlestat "Error: Multiple Series Error"

### ISSUE THREAD

**Issue by jeansg** [grafana/grafana#3107]
In version 2.0 i use single stat with 2 rows, because the value it's a percent of row #A.
In the Row A i got the access metrics and in the Row B i got error metrics, so using the function "asPercent" i got this percentage of error in the access;
But in the new version i receive the following error:

Multiple Series Error
Metric query returns 2 series. Single Stat Panel expects a single series.

Can you help me please;

**Comment by utkarshcmu** [comment]
I am assuming that you have your queries similar to the following way, please let me know if they are not in this manner:

Row A : access.metrics
Row B : asPercent(error.metrics,#A)

So, these queries to Graphite will return 2 series(1 for each row) as the result which cannot be shown on a single stat panel because Single stat panel is supposed to show only 1 series.

Here is the suggestion you can try for your use case and see if it works:

1. Copy "access.metrics" from Row A and move it to Row B instead of "#A" like this:
**Row B: asPercent(error.metric,access.metrics)**

2. Remove Row A completely from the query list.

This should return a single series from Graphite(which is error as percent of access) and you can see the same information which you used to see before.

**Comment by torkelo** [comment]
singlestat will only work on the first returned series, so if you have multiple queries or one that return multiple it will complain. 

In you case simple click the eye icon on query #A to disable that query (it can still be used by in asPercent in query #B)

**Comment by jeansg** [comment]
Worked perfectly, thanks for the quick support, i did as @utkarshcmu describe and it worked, my scenario was:

Row A: asPercent(metric.errors.server-1, #B)
Row B: metric.access.server-1

And receving the mentioned error, and as @utkarshcmu describe my single stat back to work.

Thanks again;
