### ISSUE TITLE
GraphNG: Time series panel Tooltip is cut off at the top

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#31098]
**What happened**:

Tested new Time series beta Panel, with "Tooltip mode" = "All". The Tooltip position is different / incorrect, as the mouse cursor is in the bottom left corner, which may result in the Tooltip being cut off at the top (see below).
When having just a few series, tooltip position is the same as with Graph Panel.

Old Graph Panel Tooltip seems to show a maximum of 32 series (see #18425 Support more than 32 series in Graph tooltip )

**What you expected to happen**:

Panel tooltip behavior should not change (or get worse) compared to old Graph Panel.

Even though #18425 is not solved, It's better or more consistent to always show the Position Timestamp at the top of the tooltip and cut off the list after 32 series.
Current behavior of timeseries panel may show much less than the possible 32 series in tooltip depending on panel position in dashboard.

**How to reproduce it (as minimally and precisely as possible)**:

- Use any dashboard, e.g. <https://play.grafana.org/d/000000016>
- Duplicate (for comparision) Graph Panel und change to Timeseries Panel, set Tooltip mode to "All",
(Top is old Graph Panel, below is new Timerseries panel)

with just 4 series, there is no difference ✔️ 

![WaLgzZ4o8v](https://user-images.githubusercontent.com/33002073/107519136-2be86a00-6bb0-11eb-9bc8-77a324ed5b08.gif)

- Get more series (change to prometheus datasource and use `{__name__ =~ "prometheus_tsdb.+"}`) for both panels:
![grafik](https://user-images.githubusercontent.com/33002073/107519426-8d103d80-6bb0-11eb-881a-c7c9fa99979c.png)

Now, the timeseries panel tooltip position is different, the tooltip is not fully readable anymore 💥 :

![6MmeXKaGiD](https://user-images.githubusercontent.com/33002073/107520397-ab2a6d80-6bb1-11eb-85da-e06028edac3d.gif)

It's still ok with 17 series (`{__name__ =~ "prometheus_tsdb_head.+"}`)
![O1Gupdc116](https://user-images.githubusercontent.com/33002073/107521677-22accc80-6bb3-11eb-9144-4cfe2fadc124.gif)

----

**Environment**:
- Grafana version: `7.4.0`
- Data source type & version: prometheus
- OS Grafana is installed on: <https://play.grafana.org>
- User OS & Browser: Windows 10, Firefox 85.0.1
- Grafana plugins: Timeseries beta plugin

**Comment by dprokop** [comment]
@Mario-Hofstaetter thanks for reporting this and really sorry for responding so late. We are aware of this issue, yet I don't think we will ever guarantee the tooltip being bulletproof.

In my head I see few possible ways to solve this when there is not enough space for the tooltip to be contained within the window boundary:
1. Never cut off the tooltip, but limit the number of series visible in the tooltip to only as many as fit the screen. Make sure, the highlighted series is visible in the tooltip.
2. Limit the number of the series, make sure highlighted series is visible as well as the series surrounding it.
3. Allow scrolling the tooltip content. When the user holds the modifier key(ctrl/cmd) the tooltip would freeze and the user would be able to scroll its content.

We also need to optimize the tooltip positioning to always use the most optimal available space rather than, as currently, only take window overflow into consideration. I can see cases now when the available space is not utilized correctly:

https://user-images.githubusercontent.com/2376619/122391499-5e95db00-cf73-11eb-9557-1f76c2c5f96c.mp4
