### ISSUE TITLE
QueryEditors: SQL Data sources (Postgres & MySQL) Generated SQL button does not work anymore (7.4+) due to need for panel id & wanting to open inspect drawer

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#31112]
Since updgrading to 7.4.0 today, the "Generated SQL" button in a Graph panel does nothing. I click it, nothing happens. Tested in both Chrome and Microsoft Edge on Windows.

**Comment by Dan-gituser** [comment]
Hi. Can confirm this. With a postgres Datasource the button below the Query is broken (no Errors in Log).
As a workaround you can use the "Query inspector" on the right (one Line with the data_source).

**Comment by torkelo** [comment]
This is due to query editors do not have access to the real panel model anymore. The "Generated SQL" button opens the inspect drawer & Query Inspector. Not sure when this change was made. Think it should just look at the response data and open a view under query input like before. 

https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/postgres/query_ctrl.ts 

This opens the inspect drawer but it tries to use the panel id,  but the angular query editors do not have access to a real PanelModel anymore, just fake model with only the queries there. 
https://github.com/grafana/grafana/blob/master/public/app/features/query/components/QueryEditorRow.tsx#L80

QueryEditorRow does not even have access to the panel id (to make query editors usable in non-dashboard contexts). 

I wonder if it's a good idea for query editors to rely on there being an inspect drawer? We could make this a requirement add an `onOpenInspect(tab: string)`  to PanelProps (and angular editor scope), then all views that show query editors need to implement this. 

Thoughts @ryantxu @sunker?

**Comment by sunker** [comment]
I think that would be great!

**Comment by torkelo** [comment]
I opted to restore this feature to the query editors instead of opening the inspect drawer, not sure what the solution should be for react query editors

**Comment by torkelo** [comment]
Fixed in https://github.com/grafana/grafana/pull/31236
