### ISSUE TITLE
Optionally disable / hide the panel menu in dashboards

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#31190]
**What would you like to be added**:

Similar to dashboard editable flag, it would be nice to disable the panel menu:
![image](https://user-images.githubusercontent.com/705951/107830017-d5aa3100-6d3f-11eb-8b85-319a301ca7d0.png)

![image](https://user-images.githubusercontent.com/705951/107830099-fbcfd100-6d3f-11eb-8297-fb8e5bc668a4.png)

**Why is this needed**:
This options can be a distraction for operational dashboards

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
