### ISSUE TITLE
Data links: Auto suggest for fields shows display name instead of the real field name 

### ISSUE THREAD

**Issue by strizhik** [grafana/grafana#31200]
Hello,

I want to use the value from the _specific_ series to compute data link in the graph panel. It looks like the editor provides a suggestion for that, but the engine doesn't resolve the template into real value.

Steps to reproduce:
1. Open [https://play.grafana.org/d/000000012/grafana-play-home?orgId=1](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1)
2. Edit "server requests" panel
3. Click "Field" tab
4. Click "Add Link" button
5. Set something to the title (e.g. "test link")
6. Type $ at URL field and wait for the popup (code completion)
7. Select "Fields web_server_01" item. URL should be `${__data.fields.web_server_01}`
8. Click OK
9. Click on the graph and ensure that the expression in the test link is not resolved.

![image](https://user-images.githubusercontent.com/5673723/107891753-b246d800-6f31-11eb-8688-2c3aaf54c0bb.png)

On the other hand `${__data.fields.Time}` expression is resolved correctly:

![image](https://user-images.githubusercontent.com/5673723/107891705-6005b700-6f31-11eb-9afb-a0715b576667.png)

**Comment by torkelo** [comment]
The auto suggest is wrong, the name of the field is just Value for time series.

`${__data.fields.Value}`

**Comment by oscarkilhed** [comment]
@strizhik In order to make your scenario work you need a bit of a workaround. You cannot currently use a datalink that refers to a specific series if those series are from different dataframes. They need to be a single dataframe with multiple fields. If your data has multiple dataframes you can transform them into a single dataframe using the `outer join transform`. That together with #32057 should solve hopefully solve your problem.
