### ISSUE TITLE
Panel description not showing up when too many lines

### ISSUE THREAD

**Issue by ddobrinskiy** [grafana/grafana#31249]
**What happened**:
I have a `Graph Panel` with a very long description.

When I open it on my 13'' laptop and hover over the ℹ️  button in top-left corner, nothing happens.

Apparently, because my description height is larger than screen height

![grafana-info-tip-fail](https://user-images.githubusercontent.com/29500178/108084074-d7982b00-7084-11eb-9ccf-2687e1e022a8.gif)

**What you expected to happen**:
When I hover over the (i) button in top-left corner, the description appears and adapts to my screen size
![grafana-info-tip-success](https://user-images.githubusercontent.com/29500178/108082849-8e93a700-7083-11eb-86af-ed7f209bdb41.gif)

**How to reproduce it (as minimally and precisely as possible)**:

Create a panel, choose `graph` visualization, and then fill `Description` field with many lines of text.

After that, open the dashboard using a smaller screen, and hover on the ℹ️ in top-left of panel.

If text fits on the screen, add more lines until it doesn't

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.2.2 (f2479827)
- OS Grafana is installed on: Linux Server
- User OS & Browser: Windows 10 | Chrome Version 88.0.4324.150 (Official Build) (64-bit)

**Comment by torkelo** [comment]
Panel descriptions with content that does not fit the screen will be hard to support in a good way , would label this a feature request. Unless there a trivial way to fix it

**Comment by ddobrinskiy** [comment]
@torkelo maybe the first step could be increasing the panel width?

While it does not solve the problem fundamentally, it allows for even more text to fit it.

And therefore reduces current impact of the issue.

**Comment by ddobrinskiy** [comment]
Dynamic description width would also fix #31321

**Comment by natellium** [comment]
Hey @ddobrinskiy, as @torkelo mentioned this is a feature request rather than a bug. We just introduced [Github discussions](https://github.com/grafana/grafana/discussions) (see the [announcement](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341)) to improve how we handle feature discovery and delivery.
Because of this, I will close this issue, and ask you to open a discussion if you consider this is a feature we should give some thought to. 

If you have any questions about github discussions we have put together an [FAQ](https://github.com/grafana/grafana/discussions/36962), or feel free to ask us directly. Thanks! :)
