### ISSUE TITLE
Supporting jmespath for team_ids of generic oauth

### ISSUE THREAD

**Issue by shi-ron** [grafana/grafana#31252]
**What would you like to be added**:
jmespath expression to `team_ids` of generic oauth

**Why is this needed**:
With it, we can assign users from keycloak to teams.
For example, with configuration
```
team_ids: "contains(groups[*], 'A') && 1 || contains(groups[*], 'B') && 2"
```
the user of group `A` can be assigned to team ID `1` and analogue group `B` to team ID `2`

**Comment by marefr** [comment]
[Team sync](https://grafana.com/docs/grafana/latest/auth/team-sync/) is currently an Enterprise feature. #36307 adds support for extracting groups for generic oauth, but Grafana Enterprise is required to be able to sync those with actual teams. Maybe we'll support team sync for Grafana OSS in the future, but I'll close this for now since we're trying to only keep relevant feature requests open that we're planning to work on short term.
