### ISSUE TITLE
ElasticSearch _mapping lookup is done on current date

### ISSUE THREAD

**Issue by Qtax** [grafana/grafana#3125]
When using ES data source with a daily index pattern, and there is no index for current date: When you make a dashboard and you have selected the dates for which there is an index (eg. 2015-01-01 0:00 to 2015-01-01 23:59), and you try to select a metric field for a graph, you get nothing and in the server log you can see:

```
2015/11/03 13:27:10 [I] Completed /logstash-2015.11.03/_mapping 404 Not Found in 3.399072ms
```

That it's using the `_mapping` for todays date, which has no index, instead of the selected date which has an index (eg. `logstash-2015.01.01`).

Maybe you could change the `_mapping` lookup to use the selected date instead of the current date?

**Comment by 1tft** [comment]
Hello Qtax, one tip from me:
For this purpose I use index aliases (https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html), so I don't have to use the time pattern functionality of grafana. Maybe with elastic index templates you are also improve performance because grafana doesnt have to search for all indexes. Also I don't know if grafana time pattern technology can work with index gaps, like index for myindex-15, myindex-13, myindex-12. Could I access values from index 2013 via grafana index pattern technology?
So I use a cron job which run daily and use "myindex-complete" as index name in grafana:

curl -XPOST 'http://localhost:9200/_aliases' -d '
{
    "actions" : [
        { "add" : { "index" : "myindex-*", "alias" : "myindex-complete" } }
    ]
}'

**Comment by Elfo404** [comment]
Closing this as it has been fixed by https://github.com/grafana/grafana/pull/22318
