### ISSUE TITLE
UI FR: Autofocus on text fields when page loads

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3128]
It would save a lot of clicks or tabs if the input fields on various HTML templates are auto focused when they are loaded. For example:
1. Login page - User input field should be set to autofocus if loginMode is true.
2. Signup page - Email input field should be set to autofocus if loginMode is false.
3. Query Editor - Title input field should be autofocus if clicked on General, etc.

There are lot of other places where autofocus can be set and Grafana can be more user-friendly saving too many unnecessary clicks.

**Comment by daniellee** [comment]
This is partially implemented - for the login page and for some of the areas in the query editor. Our UX team is trying to improve UX issues like this all the time now.

This feature request has been open for a long time with few received upvotes or comments so we are closing it. We are trying to limit open GitHub issues in order to better track planned work and features.
