### ISSUE TITLE
Panel description: code block extending beyond panel width

### ISSUE THREAD

**Issue by ddobrinskiy** [grafana/grafana#31321]
**What happened**:

When Panel Description has a long code block, it overflows the popup window
![image](https://user-images.githubusercontent.com/29500178/108357382-6b413700-71fe-11eb-8dfb-31238c30d914.png)

**What you expected to happen**:

Popup window to extend in width to fit the maximum length of a code block

**How to reproduce it (as minimally and precisely as possible)**:
Create a panel, choose graph visualization, and then fill `Description` field with a `code block` (using \`) containing more than 100 characters

**Anything else we need to know?**:

**Environment**:

- Grafana version: v7.2.2 (f2479827)
- OS Grafana is installed on: Linux Server
- User OS & Browser: Windows 10 | Chrome Version 88.0.4324.150 (Official Build) (64-bit)

**Comment by thisisobate** [comment]
Hi @ddobrinskiy 

I tried replicating this on master but couldn't reproduce the bug. Have you considered replicating this bug on the latest Grafana version? if not, please do. Otherwise, I think you should try using the latest Grafana version to enjoy the latest features and a much better experience.

Whatever the outcome is, do let us know.

Hope that helps!
