### ISSUE TITLE
Problem with elasticsearch based variables after upgrade to 7.4.3

### ISSUE THREAD

**Issue by machytkafitanalytics** [grafana/grafana#31474]
**What happened**:
After upgrade to Grafana 7.4.3 variables using data source Elasticsearch are distorted - "Refresh" and "Sort" seem to be re-set to default values and seem to not work on load of dashboard. Only after editing then dashboards start to work again.

**What you expected to happen**:
No such problems should happen

**How to reproduce it (as minimally and precisely as possible)**:
After upgrade to 7.4.3 people start to complain about not working dashboards based on Elasticsearch data source - all these dashboards use variables with values extracted from ES. There variables were not working and started to work only after editing them.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: Elasticsearch 6.8
- OS Grafana is installed on: Debian 9/10
- User OS & Browser: different
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
can you share the dashboard.json ? (at least the templating section)

**Comment by hugohaggmark** [comment]
Hi @machytkafitanalytics also which version of Grafana did you upgrade from? Thank you.

**Comment by disfluxly** [comment]
Hey @torkelo  & @hugohaggmark. I'm seeing something similar well and figured I could provide some more color around the problem

**Environment:**
Grafana version: 7.4.3 (also tested 7.4.2 with the same problem)
Data source type & version: Elasticsearch 7.0+
Previous Grafana Version: 7.3.4

It appears that the problem happens to `ad-hoc` or _updated_ Dashboard Query Variables. What defines an update? Existing dashboard query variables that were created on Grafana Version 7.3.4 will continue to work, as long as they are not changed after the upgrade. Some things I've tested which factor as an "update":

1. Changing the Data Source on the query variable (changing to a new index pattern)
2. Changing anything about the query, even so far as adding a blank space at the end of the query.

The problem:

It seems that the problem is that query variables are _completely ignoring_ the time range set on the dashboard and are instead defaulting to the _global dashboard time range default (6h)_. This is very easy to reproduce:

On Grafana 7.4.3, do the following:
1. Create a new Panel
2. Change time frame to the past 7 days
3. Create a Dashboard Query Variable connected to Elasticsearch, do something extremely basic, such as `{"find": "terms", "field": "your_field_here.keyword"}`
4. Open up the Network tab on your browser. Check the network request that gets sent out when the above query executes. It'll look something like this:

```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"events-api*"}
{"size":0,"query":{"bool":{"filter":[{"range":{"data.start_time":{"gte":"1614769746741","lte":"1614791346741","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"1":{"terms":{"field":"your_field_here.keyword","size":500,"order":{"_key":"asc"}}}}}
```

If you take a look at the epoch time range above, the query only ran against 6 hours, which ends up leading to missing data.

You can also test the inverse by setting the time range to the past 5 minutes. The query variable will _still_ query for 6 hours ,which can lead to _added_ data on the dashboard.

This seems to impact ad-hoc filter variables regardless of whether or not they existed on the dashboard prior to the upgrade.

**Comment by hugohaggmark** [comment]
@Elfo404 is this something that is like the issue we talked about last week?

**Comment by torkelo** [comment]
Does the variable have refresh on time range? 
I test this dashboard: https://play.grafana.org/d/CknOEXDMk/elasticsearch-templated?orgId=1&from=now-2d&to=now 

updated the variable to use refresh on time range, and inspected the queries, both the variable and metric queries have the right time range filter

**Comment by Elfo404** [comment]
@hugohaggmark seems like it's the same behavior.

@torkelo thanks for testing this out, I also tried locally and everything works as expected.

@disfluxly can you check if this is the case?

as mentioned in https://github.com/grafana/grafana/issues/31165#issuecomment-786606015:
> when selecting 'On Dashboard Load' as a refresh option, we assume the query doesn't depend on the time.

The behavior since 7.3.x changed, but in fact, 7.3 was behaving incorrectly.


on a side note, maybe a better approach would be, instead of defaulting to a 6 hours time range, to define a time range based on the interval pattern (ie `now - now-24h` for a daily index, `now - now-7d` for a weekly index) but that's a different topic.

**Comment by disfluxly** [comment]
@Elfo404 

> when selecting 'On Dashboard Load' as a refresh option, we assume the query doesn't depend on the time.

This doesn't seem to make sense, for the following reasons:

1. If I have a dashboard that I have saved with an interval for the past 72 hours, then I would expect that the "On Dashboard Load", the query variables would look for data from the past 72 hours. I would just not expect that variable to refresh when something like the dashboard auto-refresh executes.
2. It's impacting variables that do not have a "Refresh" option, such as the `ad-hoc` filters. 
3. It's directly contradicting the documentation for the elasticsearch datasource: https://grafana.com/docs/grafana/latest/datasources/elasticsearch/#query-variable

> Returns a list of values for a field using term aggregation. Query will use current dashboard time range as time range for query.

4. This "fix" wasn't identified in the release notes for any 7.4.x release. This is a breaking "fix" that fundamentally changes the community and documentation understanding of "On Dashboard Load".
5. Since this behavior doesn't become apparent until an existing variable changes or a new variable is created, it's going to be highly confusing for users, who will do the same thing that I and others have done with troubleshooting to discover the 6h default since this isn't in the notes. Dashboards are just going to just suddenly break with no correlation to the change made.

I see this change as actually introducing a breaking bug, and it should be rolled back. The behavior should match what I described in 1 above, since that's what makes sense from the user understanding of "dashboard load" and also matches the documentation. If this isn't the intended behavior, then it may be better suited to introduce the "correct" behavior as a new option in the Refresh drop-down. As it stands right now, there's no way for a user to know that by selecting "On Dashboard Load" that it'll be limited to the past 6 hours.

One last thing, playing with the dashboard that @torkelo linked. Since solely changing the "Refresh" value on a query variable doesn't cause the query to execute, there will be no change in previewed values when moving from "On Dashboard Load" to "On Time Range Change", unless you slightly modify the actual query (adding a space at the end). This adds even greater confusion as it appears the change you're making has no impact to the results.

**Comment by Elfo404** [comment]
It makes sense, thanks for further clarifying @disfluxly.

In order to achieve this then we'll have to make sure the dashboard's time range gets always passed to `metricFindQuery` regardless of the refresh mode. this should allow us to achieve the desired behaviour while avoiding exposing `timeSrv` to plugins.

alternatively we can just expose `timeSrv` from `@grafana/runtime` so that it can be consumed by plugins, but that would put more logic on the plugin side potentially creating the opportunity to have incoherent behaviour between different plugins

/cc @grafana/grafana-frontend-platform
