### ISSUE TITLE
LDAP does not check if organisation exists before adding user to it

### ISSUE THREAD

**Issue by XANi** [grafana/grafana#3151]
By accident ( I forgot that AUTOINCREMENT in MySQL Galera cluster do not increment by 1) I've set up group mappings to non-existing ID (btw. Group ID really should be somewhere visible in UI).

After that when user logged he was added to that non-existing org and after that 
when changing organisations assigned to that user (usually when adding a new one) i sometimes get:

    2015/11/06 12:08:37 [I] LDAP: Searching for user's groups: (&(objectClass=posixGroup)(memberUid=xani))
    2015/11/06 12:08:37 [I] Ldap User Info: (*login.ldapUserInfo)(0xc208285650)({
     DN: (string) (len=48) "uid=xani,ou=users,dc=redmine,dc=xxx,dc=xxx",
     FirstName: (string) (len=7) "Mariusz",
     LastName: (string) (len=11) "Gronczewski",
     Username: (string) (len=4) "xani",
     Email: (string) (len=33) "mariusz.gronczewski@xxx.xxx",
     MemberOf: ([]string) (len=2 cap=2) {
      (string) (len=9) "admin-noc",
      (string) (len=13) "grafanaadmins"
     }
    })

    2015/11/06 12:08:37 [login.go:101 LoginPost()] [E] Error while trying to authenticate user: User is already added to organization
    2015/11/06 12:08:37 [I] Completed /login 500 Internal Server Error in 69.4287ms

removing user (and letting it be added again by ldap) works but there really should be at least a warning in the log about user having assigned org that do not exists

**Comment by torkelo** [comment]
I agree, sounds like a bug

**Comment by XANi** [comment]
There is few other issues regarding error reporting, none of errors actually tell user **which** user in **which** organisation had problem.

like message "Cannot remove last organization admin".... which doesn't say *what* user was supposed to removed... or *why* he was removed (in my case it was removing triggered byLDAP)... or in *which* org that happened.

I have tried to make a patch for it but gave up once I've noticed errors are just package variables so I can't just change it at the moment of generation.

Should I report separate issue for that ?

**Comment by drawks** [comment]
Yes, I'm seeing both of the above described behaviors in 2.5 with ldap auth.

**Comment by willemdh** [comment]
Grafana version: 3.0.0-beta2, commit: v3.0-beta2, build date: 2016-04-04 19:52:41

Last week AD integration was working fine in Grafana. Today when I try to login, I get:

"Error while trying to authenticate user"

in grafana.log I can see this:

2016/04/29 11:19:11 [login.go:102 LoginPost()] [E] Error while trying to authenticate user: User is already added to organization
2016/04/29 11:19:11 [I] Completed 172.19.4.146 - "POST /login HTTP/1.1" 500 Internal Server Error 53 bytes in 77235us

So what can I do to login again? Is the only solution really to delete the user with admin? i'd prefer not to have to delete the user. Any tip or workaround to prevent this issue is welcome. :)

**Comment by willemdh** [comment]
Ok, found the problem. /etc/grafana/ldap.toml contained a servers.group_mappings entry which referred to an organization that appears to no longer exist.

```
[[servers.group_mappings]]
group_dn = "CN=blabla"
org_role = "Admin"
org_id = 7
```
After commenting out this servers.group_mappings and restarting grafana-server I was able to log in again. This seems like something that should not be too difficult to fix?

**Comment by zstyblik** [comment]
I have hit this issue, `User is already added to organization`, as well. And it seems to me like it comes from user not matching any `servers.group_mappings`.

How to reproduce:
- user must be already known to Grafana, resp. be in DB. you should get why later on.
- make sure that user doesn't match any `servers.group_mappings`.
- try to login with the user - it should fail with `User is already added to organization`
- delete users in `global users` with Grafana super admin
- try to login again with the user. It works now.
- logout with the user
- try to login again and you should hit the same error, `User is already added to organization`, again.
- repeat as many times you want :|

**Comment by drewboswell** [comment]
I have this problem as well, although it is due to deleting organizations and still having the old confiugurations in ldap.toml.

\# Example:
Delete organization with id x
Leave ldap.toml config for organization with id x
No user which matches that rule will be able to log in

\# Resolution
temporary: Remove old config for that organization from the ldap.toml and login again
fix: as mentioned above it would be good to check if the org exists before trying to assign a user to it

**Comment by zstyblik** [comment]
Ok, so how about this for a start? It adds a "check" into `AddOrgUser()` to see whether Org with given Org ID exists.

```diff
diff --git a/pkg/services/sqlstore/org_users.go b/pkg/services/sqlstore/org_users.go
index fdd671d..11ea558 100644
--- a/pkg/services/sqlstore/org_users.go
+++ b/pkg/services/sqlstore/org_users.go
@@ -26,6 +26,12 @@ func AddOrgUser(cmd *m.AddOrgUserCommand) error {
                        return m.ErrOrgUserAlreadyAdded
                }
 
+               if res, err := sess.Query("SELECT 1 from org WHERE id=?", cmd.OrgId); err != nil {
+                       return err
+               } else if len(res) != 1 {
+                       return m.ErrOrgNotFound
+               }
+
                entity := m.OrgUser{
                        OrgId:   cmd.OrgId,
                        UserId:  cmd.UserId,
```
