### ISSUE TITLE
elasticsearch: histogram aggregation

### ISSUE THREAD

**Issue by yehosef** [grafana/grafana#3164]
I would be very helpful to include the histogram aggregation in the elasticsearch query builder.

**Comment by skundrik** [comment]
:+1: would be nice for things like count distribution graphs across

**Comment by xadhoom** [comment]
something like that ?

![screenshot from 2016-01-15 10-59-47](https://cloud.githubusercontent.com/assets/197981/12350402/1e51202e-bb77-11e5-91da-a0c83f45c31c.png)

this shows a distribution of concurrent connection count across the 24 hrs

to achieve that, I've modified the histogram plugin:
https://github.com/xadhoom/grafana-panel-plugin-histogram/tree/es_histogram

and added a new aggregation in ES query builder:
https://github.com/xadhoom/grafana/commit/4f665bafed24fb5e2508c08d29f6e99340ad8a91

which basically mimics Date Histogram by introducing a Term Histogram, in order to aggregate to something more than a simple date.

I've started using grafana no more than 5 days ago, so this is an idea than needs to be expanded and fixed, so any comment will be more than welcome.

**Comment by skundrik** [comment]
Yes, or things like
* Utilisation/per core
* Used memory/cpu per process
* msg latency distribution

**Comment by xadhoom** [comment]
well, maybe this discussion could me merged with #600 in order to have a full featured histogram support.

**Comment by gbrian** [comment]
+1
ES aggregations is painful for me, this could be really great!

**Comment by mtanda** [comment]
@xadhoom You already work for this in your fork repository.
If possible, would you share your work to origin? (make PR for grafana/grafana?)

**Comment by xadhoom** [comment]
Well,

right now is not complete and well tested.
We've modified the ES datasource but some small work still need to be done.

I'm waiting to test it well and for grafana to relase 3.0, at this point they will not add any new feature.

As soon as 3.0 is out, we'll try to push the mods to upstream for sure :)

**Comment by mtanda** [comment]
Thanks so much!! :-)

> Also I think upstream will want to define a "common" interface for histogram data, in order to work with all datasources.

I agree this point, InfluxDB has histogram() function too, and other datasource could have histogram function.
Need to define common interface.

**Comment by Spacefish** [comment]
+1

**Comment by LuboVarga** [comment]
+1

**Comment by vaibhavinbayarea** [comment]
+1

Is there any plan to merge changes made in https://github.com/xadhoom/grafana-panel-plugin-histogram/tree/es_histogram to the histogram plugin from mtanda? I see a merge branch but nothing in the master.

The changes made, especially "terms histogram" have been very helpful! Thanks a lot!

Please let me know if there is any help needed in moving this forward..

**Comment by mtanda** [comment]
There are big difference between xadhoom's branch (see https://gist.github.com/mtanda/ff39861b07ab1e00839f3f33129a108b), and I don't understand what xadhoom want to do.
So, it is hard to merge it, I don't have plan to merge it.

**Comment by jonesn** [comment]
+1
