### ISSUE TITLE
TimeSeries Panel: Auto scaling of Y-axis min & max does not work with precent units 

### ISSUE THREAD

**Issue by maemigh** [grafana/grafana#31679]
**What happened**:
When converting from graph panel to time series panel, the auto scaling of the Y-axis doesn't appear to work with 0-100% as the unit. If changing from linear to log base2, the axis and data disappear completely.

**What you expected to happen**:
Y-axis to be auto scaled.

**How to reproduce it (as minimally and precisely as possible)**:
Create a graph panel using 0-100% y-axis, with data not going above 40%, convert to time series panel.

**Anything else we need to know?**:
First is graph panel, second is timeseries.
<img width="738" alt="Screen Shot 2021-03-04 at 22 17 37" src="https://user-images.githubusercontent.com/4478053/109970509-7cc72a80-7d38-11eb-86e3-321b111b796d.png">

**Environment**:
- Grafana version: 7.5.0-beta1
- Data source type & version: Prometheus
- OS Grafana is installed on: RHEL7
- User OS & Browser: Chome latest

**Comment by torkelo** [comment]
Interesting, this is due to a special logic we have in applyFieldOverrides for the percent unit 
 https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/field/fieldOverrides.ts#L163 

I think the thinking was that setting min, 0 max 100 makes sense for the stat panels. 

Not sure how to change that without introducing a subtle breaking change, we could migrate it so that current dashboards with percent get a set 0, 100 min max

**Comment by AndrewFarley** [comment]
Just ran into this myself, found it annoying and came here to report this bug.  There's a workaround for this I figured out... instead of using the official "Percent" data type(s) I'm now using a custom data type called "%" to effectively work around this bug.  Definitely would rather this be fixed than to work around it  :P
