### ISSUE TITLE
Azure Monitor: Missing templating documentation for AppInsightsFilterValues

### ISSUE THREAD

**Issue by naveenkumarsp** [grafana/grafana#31670]
In App insight documentation, i have noticed that there is a field named AppInsightsFilterValues in the image where there is no documentation was not found. I am trying to create a variable using the custom metrics and i wander if there is any filter available to fetch the values of a custom metrics pushed in to a custom dimension.

Documentation Link : 
https://grafana.com/docs/grafana/latest/datasources/azuremonitor/#templating-with-variables-for-application-insights

Image: 
![image](https://user-images.githubusercontent.com/23748340/109947356-3acdc280-7cff-11eb-9c64-55c1b4eb619f.png)

**Comment by ivanahuckova** [comment]
Thanks for creating the issue @naveenkumarsp!

**Comment by mtxasko** [comment]
I understand the main subject of this issue is the missing documentation of the AppInsightsFilderValues() method (which I have not been able to get to work and after looking in the code I have not found any reference to it).

But, regarding what @naveenkumarsp says about _"I wonder if there is any filter available to fetch the values of a custom metrics pushed in to a custom dimension"_, I've been trying to do the same without success. Have you been able to find a way to do it?

Perhaps this request about fetching data using custom queries could become a separate issue @ivanahuckova? I've found an issue in the original repo of the Azure Monitor plugin (which was later discontinued to become a default plugin in Grafana) and I think it's the same problem @naveenkumarsp and I are having:

[Other options for "Templating with Variables" for AppInsights?](https://github.com/grafana/azure-monitor-datasource/issues/99)

Best regards :)

**Comment by sunker** [comment]
We're going to deprecate the Application Insights query mode in Grafana in favor of querying this data through Metrics and Logs. Read more about this in our [docs](https://grafana.com/docs/grafana/latest/datasources/azuremonitor/#deprecating-application-insights-and-insights-analytics).
Closing this issue.
