### ISSUE TITLE
Make free text template variables easier to use

### ISSUE THREAD

**Issue by yehosef** [grafana/grafana#3173]
(I don't know if such an issue - exists..- I tried to find it.)

I'm working on custom elasticsearch queries and it would be nice to be able to specify a query string that can be used in different charts.  I would think this should be a template variable, but it seems to want to specify specific choices, not allowing free text.

For many options, specific options is the only thing that makes sense.  But there are times where I want something that's flexible.  The closest I could come to is make a "custom" variable where I don't specify any options.  Then in the dashboard, I can type in a value that will be added to the queries as desired.

the problems are:
1) the text input area is too small
![grafana_-_discover](https://cloud.githubusercontent.com/assets/149253/11032763/a76523f8-86e6-11e5-8d90-cdb16c47cbc5.png)
2) even if I type in the value
![grafana_-_discover](https://cloud.githubusercontent.com/assets/149253/11032773/ba9aff2e-86e6-11e5-85ae-6f59e841224c.png)
if I go to edit it, it hides/deletes the text
![grafana_-_discover](https://cloud.githubusercontent.com/assets/149253/11032778/c7c4155a-86e6-11e5-9782-435d625a902e.png)

**Comment by LuigiClemente-Awin** [comment]
+ 1 on free text variables. Essential when the node list would be too long or for custom elasticsearch queries (e.g. user id).

**Comment by mattttt** [comment]
This came up in a conversation today, nearly the same use care. Will explore some interface ideas to make it clearer/easier to enter free text in template variables.

**Comment by fillest** [comment]
Yes please. We are trying to use Grafana for analytics graphing and our analytic needs to input some id for a query. Not only there seems to be no way to achieve this throuth the UI - I've just tried to make a custom html page which just redirects to an url with a graph variable value (I've tried different variable types), but this doesn't work either as it seems the value gets validated and ignored by Grafana.

**Comment by bergquist** [comment]
Good description in dupe issue #9591

**Comment by daldoyle** [comment]
Are there plans to do this with the "internal" team (sorry no clue how this works behind the scenes), or if I take a swing at it would it get pulled in? What sorts of things are required to get it accepted? I have a rough proof of concept working on my own development host that needs some polishing but I think works. It's ever so slightly hacky because all of the template vars today assume that there are options like a select element which isn't applicable here, but I kept the same interface to integrate.

**Comment by bergquist** [comment]
If you submit a PR we would be happy to review it. That said I cannot guarantee that we will merge it since this feature can be a little bit tricky and templating is a crucial part of Grafana so we don't want to hacky code :) 

But please submit a PR and we can continue the discussion about the implementation in the PR.
