### ISSUE TITLE
Repeated panel does not preserve "Right Y Axis" setting

### ISSUE THREAD

**Issue by neiser** [grafana/grafana#31749]
**What happened**:

I've defined a panel and repeated it for the variable "room". The last of the four metrics have been assigned to the right Y axis. This works for the first panel (where room=Bad), but is broken for the "repeated" panels (for example for room=Büro).

See this screenshot:

![image](https://user-images.githubusercontent.com/3863897/110200026-eee46000-7e5b-11eb-8cac-c16fd4dac2c7.png)

**What you expected to happen**:

The fourth query stays attached to the right Y axis.

**How to reproduce it (as minimally and precisely as possible)**:

Will provide minimal dashboard JSON reproducing the issue soon.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Debian
- User OS & Browser: Linux / Chrome 
- Grafana plugins: None
- Others: None

**Comment by torkelo** [comment]
the left / right y axis is set using a series override based on the series name, to make it more generic you have to update the series override to use a regex so that it matches on the repeated panel (where the series name is different from the source/origin panel) 

<img width="363" alt="Screen Shot 2021-03-06 at 09 16 43" src="https://user-images.githubusercontent.com/10999/110200145-bdb85f80-7e5c-11eb-8f57-aee05db67fbe.png">

**Comment by neiser** [comment]
@torkelo Thanks for that quick reply. 

So for my case, it works with by giving the series the legend value `Feuchtigkeit` (humidity in German) and then manually setting the "Alias or regex" value to `Feuchtigkeit`. Series overrides are found in the "Panel" tab in one of the accordeon entries. 

Is this documented somewhere? I've had a look at https://grafana.com/docs/grafana/latest/panels/visualizations/graph-panel/#y-axes and maybe a hint about "Series overrides" for repeated panels would have avoided this issue :thinking: 

I'm happy to craft a PR for documentation if you think that adding a hint at the place above would improve documentation.
