### ISSUE TITLE
Elasticsearch date histogram should have more units

### ISSUE THREAD

**Issue by yehosef** [grafana/grafana#3177]
The date histogram should also have week and month options.  If I'm looking at a year of data, I usually want to look by day/week if I'm using bar charts.

![grafana_-_hometalk_pulse](https://cloud.githubusercontent.com/assets/149253/11040248/035067ea-8714-11e5-9a21-f91f4e7d6c6a.png)

This is how it's done in kibana
![fullscreen_11_9_15__7_01_pm](https://cloud.githubusercontent.com/assets/149253/11040319/51da9ac0-8714-11e5-9b87-b61a586df705.png)

custom is the ability to define some specific range - eg 3 days or 4 weeks.  This would be great also - but at least to have longer ranges.

**Comment by 1tft** [comment]
Perfect, just wanted to create a ticket about this issue.
Because individual intervals like "1M" or "30d" doesn't work in grafana 2.5. Such intervals are simply not accepted by grafana.
But elastic should understand such intervals: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html

**Comment by Qtax** [comment]
@1tft and @yehosef, I just tried typing `7d`, `30d` and `1M` as intervals and it seems to work fine for me (except that `1M` is producing a bit odd results, but that may be my lack of data). Is this still an issue? Using current Grafana master branch (2.6 beta).

**Comment by 1tft** [comment]
Yes, seems to work like a charme!
