### ISSUE TITLE
Opsgenie Notification Channel "Test" always uses "alias" value of "alertId-0" (which makes alerts hard to find)

### ISSUE THREAD

**Issue by ethirolle** [grafana/grafana#31832]
**What happened**:
I created a new Alert "notification channel" of type "OpsGenie", and then clicked the "Test" channel. I couldn't understand why I wasn't seeing the alerts in Opsgenie, and with Opsgenie's support we finally saw that there was an alert previously created (from a different grafana Notification Channel) with the same "alias" value of "alertId-0" ... so the new alerts were de-duplicated into an older alert.

**What you expected to happen**:
I'd expect the "Test" button to always generate a new alert -- there's no need to specify an "alias" value for a test alert.

**How to reproduce it (as minimally and precisely as possible)**:
Created a new Alert "notification channel" of type "OpsGenie", and then click the "Test" channel. 

**Anything else we need to know?**:
Here is the HTTP request payload sent when we test this Notification Channel:

```
{"id":5,"name":"Opsgenie: system","type":"opsgenie","frequency":"","settings":{"uploadImage":true,"autoResolve":true,"httpMethod":"POST","severity":"critical","apiKey":"","apiUrl":"https://api.opsgenie.com/v2/alerts","autoClose":false,"overridePriority":true},"secureSettings":{}}
```

**Environment**:
- Grafana version: 7.4.3 on Grafana Cloud

**Comment by papagian** [comment]
The test creates a new alert but sets always the same alias.

The alias is set here:
https://github.com/grafana/grafana/blob/f55818ca702b21b1c5afc046c9a01a375a0b8ba2/pkg/services/alerting/notifiers/opsgenie.go#L125

It sends always `alertId-0` because the Rule.ID is not set (so it defaults to zero):
https://github.com/grafana/grafana/blob/6415d2802e1973f02e2a0ab9037045efc4b0ad5f/pkg/services/alerting/test_notification.go#L79-L85
