### ISSUE TITLE
query CPUUtilization metric failed for AWS EC2 instance by imageid

### ISSUE THREAD

**Issue by tj13** [grafana/grafana#3186]
failed to add CPU utilization graph for AWS EC2 instances by image id. the dropdown list always show with the instance id. 

below is screenshot.

<img width="848" alt="2015-11-10 2 42 05" src="https://cloud.githubusercontent.com/assets/14867953/11056151/9a7d296e-87b9-11e5-944c-4705f6afa72a.png">

**Comment by mtanda** [comment]
@torkelo The issue seems to be caused by your change.

You need to filter suggested dimension values by the dimension name.
https://github.com/grafana/grafana/blob/0fb110a4af268aac3fcfff7d4adf5906550eeb60/public/app/plugins/datasource/cloudwatch/query_ctrl.js#L91-L96
$scope.datasource.getDimensionValues() return all dimensions which has the relation to the Metric.
Without filtering, the editor suggest InstanceId dimension values for ImageId dimension key.

My original implementation handle it correctly.
https://github.com/mtanda/grafana/blob/be6cb24e10f3b6bc3228d67a1dfa2cb5474ef566/public/app/plugins/datasource/cloudwatch/queryCtrl.js#L101-L103

Why do you change the implementation.
Moreover, the change affect templating...

**Comment by tj13** [comment]
@torkelo @mtanda 

issue still exists in latest version 2.6.0-beta2. Dimensions only works under by InstanceID. when selecting Imageid or Instancetype, dimension value is empty.

![2015-12-11 6 41 48](https://cloud.githubusercontent.com/assets/14867953/11741968/5abca8fe-a037-11e5-895d-fd52b8b8f6f1.png)
![2015-12-11 6 46 15](https://cloud.githubusercontent.com/assets/14867953/11741988/7d64f5d2-a037-11e5-919d-e420a6e55a8f.png)

**Comment by tj13** [comment]
![2015-12-11 6 46 49](https://cloud.githubusercontent.com/assets/14867953/11742085/1f817548-a038-11e5-9b0e-3d49025962d1.png)

**Comment by mtanda** [comment]
@tj13 
It is not problem.
These dimensions are only supplied if detail monitoring is ON.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/ec2-metricscollected.html
ImageId
> This dimension filters the data you request for all instances running this EC2 Amazon Machine Image (AMI). Available for instances with Detailed Monitoring enabled.

InstanceType
> This dimension filters the data you request for all instances running with this specified instance type. This helps you categorize your data by the type of instance running. For example, you might compare data from an m1.small instance and an m1.large instance to determine which has the better business value for your application. Available for instances with Detailed Monitoring enabled.

I can't see such dimensions because I don't use detail monitoring :-)
```
$ aws cloudwatch list-metrics --region ap-northeast-1 --output json | grep ImageId
$ aws cloudwatch list-metrics --region ap-northeast-1 --output json | grep InstanceType
$
```
