### ISSUE TITLE
Feature request: adjust time interval based on data

### ISSUE THREAD

**Issue by direvius** [grafana/grafana#3191]
I store my measurements that represent experimental results in InfluxDB. Each experiment has a unique ID and it is stored in measurement's tag field. I made a template in Grafana that allows me to select points by experiment ID, but Grafana does not adjust time interval accordingly so I can't see my data.

Is it possible to add a checkbox "Zoom to data" that will make Grafana adjust time interval based on received data?

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features. 

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
