### ISSUE TITLE
PieChart: Can't display % in legend with decimals

### ISSUE THREAD

**Issue by maemigh** [grafana/grafana#31991]
There doesn't seem to be an option for decimal places when choose Percent as legend option. The decimals option in the Field tab didn't seem to have any effect on this either.

**Comment by dprokop** [comment]
@maemigh sorry for a late reply. I'm not sure I follow what Percent option do you refer to? Is it the Labels -> Percent option?

**Comment by maemigh** [comment]
@dprokop I think this screenshot can help illustrate. Because the legend gets rounded rather than showing decimal values, value2 has a pie slice even though it's shown as 0%.

<img width="1331" alt="Screen Shot 2021-07-14 at 11 42 46" src="https://user-images.githubusercontent.com/4478053/125552542-28883a12-3364-4717-b31b-7809f6113819.png">

**Comment by anybodysguest** [comment]
I have this discussion going on the the Community forum.  My issue is that because the Pie Chart is not using decimals in it's calculations (I assume), it's rounding up the biggest number and not representing smaller, fractional values.

https://community.grafana.com/t/piechart-doesnt-display-percentages-accurately/53294
