### ISSUE TITLE
Save the choice of "Flip results order" in Loki

### ISSUE THREAD

**Issue by lilianabiven** [grafana/grafana#32013]
**What would you like to be added**:
A way to save the choice of "Flip results order" would be great. Maybe it could be added with the other check boxes, which are saved :
![image](https://user-images.githubusercontent.com/80746856/111277493-ccf79400-8638-11eb-811f-55f5dda11921.png)
**Why is this needed**:
Currently we have to click "Flip results order" on every page reload / new query. Saving this choice would be useful because in our team we often need the results order to be flipped rather than in the default order.

**Comment by Elfo404** [comment]
@jessover9000 this might be relevant to logs navigation.

The potential issue with this is that when a query return fewer log entries than expected, it may be confusing for users to not see most recent logs on top (having a gap between the "first" log entry and the current time)

**Comment by Elfo404** [comment]
@hemdrup @jessover9000 Assigning this to you as we may need a clear way to communicate to users what is actually happening, or better that we are not modifying the query and there might be missing data.

**Comment by jessover9000** [comment]
Sorry for the delay in replying to this. We actually thought about whether we should have a toggle for this, but decided against it because we weren't sure what users' understanding is of the "Default sort order". So we decided to keep the wording of the button vague instead of saying "Newest/oldest first" and have it just be a flip switch. I guess if you want to persist a certain default for your sort order, you are right that a toggle might make more sense, but then maybe the wording should be more specific? Or is there a way to persist the sort order between queries even with the current button? @ivanahuckova originally implemented the flipping functionality, do you have an opinion about this?

**Comment by ivanahuckova** [comment]
The tricky part is to make sure users know it is only order of received results and it is not order sent in query to data source. Hmmm, maybe we could add checkbox next to this button with "Preserve this order" tooltip. So it is clear that we are Flipping results order, but user could save the preference in local storage. @jessover9000 yeah, we can save order in local storage similarly as it is done with toggles.
