### ISSUE TITLE
FR: tags in templating for type: custom

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3228]
Like we have tags for type: query in templating. We should have an ability to create tags for the type: custom too.

**Comment by torkelo** [comment]
Do you use tags?

**Comment by utkarshcmu** [comment]
A few users in my company asked for this feature today. Let me give u an example, how they want it:

1. Create a variable with 10 custom values.
2. Ability to choose 3 out of them and create tag 1, choose another 5 values for tag 2, and may be another 4 for tag 3.

This is the reason behind this FR.

**Comment by torkelo** [comment]
ok, thanks, good to know the use case (and there is an actually need for it)

**Comment by sfleiter** [comment]
+1

**Comment by Styx13** [comment]
+1

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
