### ISSUE TITLE
Elasticsearch datasource error parsing date field

### ISSUE THREAD

**Issue by d1rtym0nk3y** [grafana/grafana#3236]
I have an elasticsearch index with documents that look like this
```
{
  "_index": "cdr-2015-11",
  "_type": "cdr",
  "_id": "7c89806d-8a11-11e5-b607-3216005d57b1",
  "_score": 1,
  "_source": {
    "t_setup": "2015-11-13 14:18:45.953",
    "cdr_id": "7c89806d-8a11-11e5-b607-3216005d57b1"
    ...
  },
  "fields": {
    "t_setup": [1447424325953]
  }
}
```
I set up a datasource to use the t_setup field as the timestamp field (this is already used by kibana), the datasource saves and tests successfully, but when i try and create a graph i get an error.
```
{
  "root_cause": [
    {
      "type": "parse_exception",
      "reason": "failed to parse date field [1447403201693] with format [yyyy-MM-dd HH:mm:ss.SSS]"
    }
  ],
  "type": "search_phase_execution_exception",
  "reason": "all shards failed",
  "phase": "query",
  "grouped": true,
  "failed_shards": [
    {
      "shard": 0,
      "index": "cdr-2015-11",
      "node": "p8xgxO0_QYWU66Nf0AuANQ",
      "reason": {
        "type": "parse_exception",
        "reason": "failed to parse date field [1447403201693] with format [yyyy-MM-dd HH:mm:ss.SSS]",
        "caused_by": {
          "type": "illegal_argument_exception",
          "reason": "Invalid format: \"1447403201693\" is malformed at \"1693\""
        }
      }
    }
  ]
}
```

My cdr index does have a dynamic mapping which defines all t_* fields with that format, but kibana has no problem with using this field in queries.

**Comment by torkelo** [comment]
what version of elasticsearch are you using? Is t_setup mapped as date type in elasticsearch? can you show the raw query grafana sends and the one kibana sends? Grafana should send the same type of query (when it comes to date filtering)

**Comment by d1rtym0nk3y** [comment]
I'm using elasticsearch 2.0.0

This is the query section of the packet kibana sends

```
  "query": {
    "filtered": {
      "query": {
        "query_string": {
          "query": "*",
          "analyze_wildcard": true
        }
      },
      "filter": {
        "bool": {
          "must": [{
              "range": {
                "t_setup": {
                  "gte": 1447428970113,
                  "lte": 1447429870113,
                  "format": "epoch_millis"
                }
              }
            }],
          "must_not": []
        }
      }
    }
  },
```

And grafana sends 

```
"query": {
  "filtered": {
	"query": {
	  "query_string": {
		"analyze_wildcard": true,
		"query": "*"
	  }
	},
	"filter": {
	  "bool": {
		"must": [
		  {
			"range": {
			  "t_setup": {
				"gte": "1447408505769",
				"lte": "1447430105769"
			  }
			}
		  }
		]
	  }
	}
  }
}
```

So it looks like the issue is that kibana is sending "format": "epoch_millis" which is hinting to elasticsearch on how to parse the value, but grafana is not.

**Comment by d1rtym0nk3y** [comment]
It looks like this might be related to https://github.com/elastic/elasticsearch/issues/9725

**Comment by replay** [comment]
I've setup a local test environment with two elastic search instances, one is 1.7 and the other is 2.0. Both contain the same data. While doing that I've discovered something that might be of interest: 

The described problem seems to only happen if the index was created by the auto mapping functionality in a version <2.0, because the 1.x versions set the format of the `@timestamp` field to `dateOptionalTime` while 2.0 sets it to `strict_date_optional_time||epoch_millis`. If an index gets auto created in 1.7, but then upgraded to 2.0, the format definition persists which leads to this problem. Same if the template definition was made for 1.7 and remains unmodified during an upgrade to 2.0.

I've written a patch that makes the data source editor also ask for the elastic search version, please take a look and tell me what you think: https://github.com/replay/grafana/commit/ada9bfcae8140f53bd12139a58fc90a636029212

Disclaimer: This is the first time I've touched AngularJS, please look at the patch before merging it since I'm a total noob in that :)

Alternatively we could also just add a hint to the docs that says the `@timestamp` field must support the format `epoch_millis` explicitly in 2.x.

Here are some snippets illustrating the difference:

A mapping created by auto mapping in 1.7:

          @timestamp" : {
            "type" : "date",
            "format" : "dateOptionalTime"
          },

A mapping auto create by auto mapping 2.0 for exactly the same data:

          "@timestamp" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },

**Comment by morganchristiansson** [comment]
I just encountered this error and had to set Elasticsearch version to 2.x in the dropdown for the datasource.

Would've been great if this was done automatically.
