### ISSUE TITLE
Custom Color for term in pie chart v2 appears black

### ISSUE THREAD

**Issue by gadol** [grafana/grafana#32671]
**What happened**: When you choose a custom color for a term in the new pie panel it always appears black and not using the color you chose

![Screenshot 2021-04-04 171616](https://user-images.githubusercontent.com/19799025/113511644-7f03eb00-9569-11eb-992a-fa942569a791.png)
![Screenshot 2021-04-04 171620](https://user-images.githubusercontent.com/19799025/113511645-7f9c8180-9569-11eb-9fa9-21f253bada6c.png)

**What you expected to happen**: the slice I changed its color should use the chosen color

**How to reproduce it (as minimally and precisely as possible)**: click on the color bar next to the grouped by term in a pie chart v2 panel, and try to set a custom color

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.0+ (also tried on 7.5.2 on play.grafana.org)
- Data source type & version: doesn't matter
- OS Grafana is installed on: Linux
- User OS & Browser: Firefox and Chrome
- Grafana plugins: pie chart v2
- Others:

**Comment by ajaxous** [comment]
It seems like it's tied to the color gradient.  I've noted the same thing with the new pie chart (v2) -- I think the older pie chart was ascetically cleaner looking without the gradient.  The built-in color selector works on the new pie chart, but any custom colors either via the rgb(), rgba() or # just give black.  Very frustrating.

It seems like an underlying issue that when you want a solid color, you still get a gradient -- like on the background of the Stat panel -- it looks really weird because the ramp of the gradient for different colors is not visually uniform, so two gradients (for different colors) next to each other sometimes does not look good.  I'd much prefer it being a solid color like the 6.X version -- same with the pie charts -- the 6.X version looked better without the gradient (and the donut version of the pie chart was also thicker, which looked better).  I keep hoping that I can finally get all my 6.X dashboards moved to 7.X even if the visual quality in 7.X is not as good, but I'm still finding little show-stoppers like this one (the old pie chart isn't working with the new data frames and the new pie chart isn't working with custom colors)

It seems like there is the infrastructure in place for more color control, so hopefully it just hasn't been connected to the Pie Chart (v2) panel yet, but will be soon -- The panel is described as beta, so maybe they were just trying to get something out there since the old pie chart didn't work correctly in some cases.
