### ISSUE TITLE
the `org_user` table schema should utilize foreign keys for `user_id` and `org_id`

### ISSUE THREAD

**Issue by drawks** [grafana/grafana#3269]
Lack of foreign keys here makes the data unconstrained by the reality of the contents of `users` and `orgs` which compounds the complexity of troubleshooting various issues with auth backend integrations.

**Comment by utkarshcmu** [comment]
:+1:

**Comment by torkelo** [comment]
Grafana supports a lot of different SQL data sources, and foreign keys can have some major differences that will be problematic. Another reason we skip foreign keys is that we do a log of schema migrations and changes and not having to deal with foreign keys when doing those can be a huge time saver. 

But I agree we have had some bugs due to this, but overall they have been very few an non critical
