### ISSUE TITLE
When adding a new default datasource, it will be set also on opening old panels, braking them

### ISSUE THREAD

**Issue by kmoppel** [grafana/grafana#3274]
For the old panels would be correct still to select by default the datasources that were used to create them. Tested with Grafana 2.5.0 and InfluxDB 0.9 data sources.

**Comment by torkelo** [comment]
When you change default data source all panels that used that will now use the new data source. this is working as intented.

**Comment by kmoppel** [comment]
Ok thanks for the info @torkelo. But yeah, for me seems a bit weird still :) "default" in my mind applies to something new still. When you change a database column's default value, it doesn't change the old values.

**Comment by torkelo** [comment]
I agree, its for historical reasons. The panel -> data source reference is done with name only, and I wanted users to be able to change the name without having to change all dashboards & panels, so the "default" data source is specified by panels if when they set datasource: null, (null => default). Now that data sources are defined in the grafana database (and not in a config.js file like in Grafana 1.x) it might make more sense to reference data sources using id instead of name.

**Comment by kmoppel** [comment]
+1 for "id"-s :)
