### ISSUE TITLE
Feature Request: Panel drill down link icon selection

### ISSUE THREAD

**Issue by addshore** [grafana/grafana#3276]
Currently dashboard links support icon selection.
Drilldown links do not, but I would assume they easily could.

My usecase here is changing the icon to a question mark to emphasise that the link will explain / answer questions regarding a panel

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
