### ISSUE TITLE
Stat visualization auto min/max yaxis with multiple metrics

### ISSUE THREAD

**Issue by konvica** [grafana/grafana#32765]
**What happened**:
I updated grafana from 7.3.7 to 7.5.3 and installed few plugins and noticed my STAT visualization is no longer aligned. See image. 
![image](https://user-images.githubusercontent.com/35737801/113897231-f71d1b80-97ca-11eb-89a4-928ff92620f6.png)

It seems the yaxis of the graph is calculated separately for each metric (device). One of the device observed an anomaly so its y-axis is very wide, while other device have very narrow y-axis. 
I see 2 issues with this behavior:

- less beautiful
- It can cause misinterpretation if someone tries to compare the graphs this way

Easy fix is to manually set y-axis to constants, but then you lose the autoscale ability. I think that autoscaling each metric by itself is more dangerous than useful. 

**What you expected to happen**:
I expect autoscale to calculate global min and max across all metrics (devices).

**How to reproduce it (as minimally and precisely as possible)**:
I cannot publish dataset. Example data should be timeseries for multiple devices. Use STAT visualization using device as metric and add any anomaly to just one device. 

**Anything else we need to know?**:
This problem can be happening to people without knowing it, since it requires an anomaly to be fully visible (e.g. on above image, we dont know if the similar graphs on sides are using 0 as ymin limit). 
Might be connected to https://github.com/grafana/grafana/pull/30326

**Environment**:
- Grafana version:7.5.3
- Data source type & version: Postgresql 12
- OS Grafana is installed on: Official Docker Image
- User OS & Browser: Windows, Chrome
- Grafana plugins: grafana-clock-panel 1.0.1,grafana-simple-json-datasource 1.3.5, grafana-world-panel 0.3.2
- Others:

**Comment by kaydelaney** [comment]
@leeoniya

**Comment by leeoniya** [comment]
yes, this is a side-effect of that PR. the data min/max is now per-graph rather than per-panel since all the autoscaling behavior (including soft and hard limits) is now delegated to the graph component.

the point of softMin/softMax settings was in fact to stabilize the ranges in the presence of anomalies, but not having these settings in the stat panel while also removing the shared min/max across graphs has the opposite effect: destabilizing.

i don't think we intend to bring back the previous, shared panel-level min/max behavior, but at least we should look into exposing softMin/softMax in the stat panel as well (similar to Timeseries) bring back some range stability control with auto-scaling and hard-limiting anomalies.

i'll add this to the todo list.

**Comment by ecraven** [comment]
The previous behaviour was actually nice in specific use cases, so it is a pity that this has been removed :-/ I'd be happy about any improvement here.

**Comment by leeoniya** [comment]
i think for visualizations that use `<VizRepeater>`, (Stat, Gauge and BarGauge) we can bring this behavior back.

we'd need to disable independent ranging of the embedded chart component and have VizRepeater scan all the data and pass down the cumulative dataMin and dataMax that will then be used without any extra padding logic, which isn't needed anyhow when we're not showing a grid or tick values.
