### ISSUE TITLE
Drawer component - the scroll bar is overlapping with content

### ISSUE THREAD

**Issue by hemdrup** [grafana/grafana#32785]
1#  Issue  - The scroll bar on the drawer is 16px out rather than 4px, and therefore overlapping with the content

<img width="519" alt="Screenshot 2021-04-08 at 13 20 37" src="https://user-images.githubusercontent.com/21049979/114019918-44eb5f80-986f-11eb-93b7-c252c37b6c36.png">

2#  Issue - The title is not breaking when too long.

![Frame 225](https://user-images.githubusercontent.com/21049979/114020631-1752e600-9870-11eb-824f-6072f18ab2df.png)

Storybook:
https://developers.grafana.com/ui/canary/index.html?path=/story/overlays-drawer--global&args=scrollableContent:true

**Environment**:
- Grafana version: 7.5

**Comment by axelavargas** [comment]
Hello @hemdrup 😃, thank you for reporting these issues 🙌🏾 , here a small update: 

**2# Issue**  was solved and is merged 🚀 

**1# Isssue:**

After discussing this topic with the team, it was mentioned that in some scenarios on the Grafana project the scrollbar(_the custom one from the Drawer component_) is overlapping the content intentionally(because it is a scroll that is shown when hovering).

In the case of the Drawer component on Storybook, this component is flexible and depends on where is being used (can be used with content overlapping or not), if you want to take a close look at the discussion, you can take a look on this [PR](https://github.com/grafana/grafana/pull/33862) 


Therefore, I am closing this issue 😄
