### ISSUE TITLE
Remove the internal 'id' from the external data source API and always use 'uid'

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#32853]
The current APIs return data source `id` to the front end, but we encourage use of `uid` -- we should not expose the internal id and make sure all requests can depend on a stable uid.

Likewise back end plugins should work with uid, not internal IDs -- currently they are passed the internal ID but not the UID

For 8, we should update our APIs to make sure everything is using UID rather than id

**Comment by marefr** [comment]
There's many API's returning id rather than uid, not just data source :smile: 

> we should not expose the internal id and make sure all requests can depend on a stable uid.

This would be a breaking change for those integrating with Grafana. Doing it for Grafana 8 guess makes sense, but we might want to deprecate it first like we did for dashboards and remove them Grafana 9?
- https://grafana.com/docs/grafana/latest/http_api/dashboard/#deprecated-resources
- https://grafana.com/docs/grafana/latest/http_api/dashboard/#identifier-id-vs-unique-identifier-uid

It looks like we currently don't support updating data sources by UID so this could cause a "ripple effect" in integrations, such as Grafana terraform provider, grafana api client for go and other integrations. Dashboards are still referring to data sources using name.

> Likewise back end plugins should work with uid, not internal IDs -- currently they are passed the internal ID but not the UID

Backend plugins support UID in the [protocol](https://github.com/grafana/grafana-plugin-sdk-go/blob/867dddf55bd1438063435f15a1638f1bf6c2d605/proto/backend.proto#L27) and the [public API](https://github.com/grafana/grafana-plugin-sdk-go/blob/867dddf55bd1438063435f15a1638f1bf6c2d605/backend/common.go#L42). But you're correct in that that UID is not populated in backend plugin requests, see [code](https://github.com/grafana/grafana/blob/492227fa0a98d2013ee8d70e05d66624e7ab6869/pkg/plugins/adapters/adapters.go#L10-L28), [code](https://github.com/grafana/grafana/blob/492227fa0a98d2013ee8d70e05d66624e7ab6869/pkg/plugins/datasource_plugin_wrapper_v2.go#L29) and [code](https://github.com/grafana/grafana/blob/492227fa0a98d2013ee8d70e05d66624e7ab6869/pkg/plugins/adapters/adapters.go#L16).

https://grafana.com/docs/grafana/latest/http_api/dashboard/#deprecated-resources

> For 8, we should update our APIs to make sure everything is using UID rather than id

Are you referring to the whole HTTP API or only data source HTTP API? So I guess this specific things involves frontend work mainly updating who data sources are created/updated/deleted?

**Comment by ryantxu** [comment]
> It looks like we currently don't support updating data sources by UID so this could cause a "ripple effect" in integrations,

exactly -- this is the #1 request from people writing integrations.  The fact we use id sometimes and uid other times is super anoying.  Since we have uid, we should *always* use uid.  If our APIs don't support it, we need to make sure they do.  The feedback from people writing integrations is that the APIs have many odd gotcha's many of them stem from using internal ids and uids inconsistently.  cc @malcolmholmes 

> This would be a breaking change

yes totally, but lets explore creative approaches to how we solve this.  the ones that come to mind are:
1. return uid in the `id` field (make sure it is clear we will stop doing this)
2. have any existing APIs that expect `id` accept uid OR id -- yes this is a string/number distinction

In general if the clients never know internal ids our APIs will be forced to be (more) consistent for people writing integrations.

**Comment by marefr** [comment]
Goal here is to stop returning internal 'id' from the HTTP API for those endpoints that supports 'uid'. We want the Grafana UI to stop using these internal identifiers and use uid (unique identifier) instead. In addition, anyone that integrates with Grafana's HTTP API shouldn't (have to) rely on these internal id's. 

Suggested to start looking at the [dashboard API](https://grafana.com/docs/grafana/latest/http_api/dashboard/) to see how hard it would be to support it taking either an id or uid in URL path parameters for backward compatibility reasons. In regards to responses, 'uid' should always be returned rather than 'id' - this could be a breaking change but Grafana 8 is a perfect chance to do these kind of breaking changes.

After dashboard API, we should continue with as many as possible in prioritized order:
- [data source API](https://grafana.com/docs/grafana/latest/http_api/data_source/)
- [folder API](https://grafana.com/docs/grafana/latest/http_api/folder/)

After that there's potentially a lot more
- [folder/dashboard search API](https://grafana.com/docs/grafana/latest/http_api/folder_dashboard_search/)
- [dashboard version API](https://grafana.com/docs/grafana/latest/http_api/dashboard_versions/)
- [dashboard permissions API](https://grafana.com/docs/grafana/latest/http_api/dashboard_permissions/)
- [folder permissions API](https://grafana.com/docs/grafana/latest/http_api/folder_permissions/)
- etc

**Comment by malcolmholmes** [comment]
While getting rid of IDs would be helpful, perhaps another way of thinking would be just to make sure that UIDs are usable everywhere - in place of names and IDs.

One such example would be dashboard folders. When submitting a dashboard via the API, the user must specify the ID of the folder for the dashboard. This necessitates a prior lookup to convert the UID into an ID before the dashboard can be submitted.
