### ISSUE TITLE
oAuth: ability to influence the state parameter

### ISSUE THREAD

**Issue by p-bakker** [grafana/grafana#32887]
**What would you like to be added**:
I'd like to be able to influence the state parameter that is send with the oAuth requests

**Why is this needed**:
In a setup where there are multiple Grafana instances running and exposed via different urls (for example multiple K8S clusters, each with their own Grafana) and you'd like to use oAuth for authentication, without the ability to influence the state parameter, you'd either have to register the (callback) url for each Grafana instance individually on the oAuth client at the OP or have 1 oAuth client per Grafana instance at the OP

If you can add some identifier to the state parameter in the oAuth requests, you can have one generic redirect url, which then redirects the callback from the OP to the correct Grafana instance, based on the identifier in the state parameter

**Comment by marefr** [comment]
Can you please explain why having one oauth application configured per grafana instance doesn't work for you/is troublesome? What OAuth provider are you using?

Suggesting using the state parameter feels like a hack to me in lack of something else? Your suggested solution would open up for cross-site request forgery vulnerabilities. From https://tools.ietf.org/html/rfc6749#section-4.1.1: 

> state
>         RECOMMENDED.  An opaque value used by the client to maintain
>         state between the request and callback.  The authorization
>         server includes this value when redirecting the user-agent back
>         to the client.  The parameter SHOULD be used for preventing
 >        cross-site request forgery as described in Section 10.12.

**Comment by kminehart** [comment]
I'm going to close this one as it's unlikely that we will support this.

I'm just speculating here, but because your setup is so unique, one thing you can try is creating a proxy layer for your OAuth requests that handles your OAuth callbacks / auth requests.

The state argument is unique to each session, so use that to temporarily store the referrer in the proxy, and then when the callback request is sent with the same state argument, forward the request to the correct grafana instance.
