### ISSUE TITLE
line_format of LogQL fails to pad (left or right justify) strings when formatting with printf and width and/or precision

### ISSUE THREAD

**Issue by FSeidinger** [grafana/grafana#32943]
I wanted to format log messages from the Loki datasource using line_format with printf on strings containing ip addresses. This is the line_format part:

```
line_format "\"|\" {{printf \"%15.15s\" .ClientHost}} \"|\""
```

Given the following input lines:

```
{ "ClientHost":"192.168.224.124" }
{ "ClientHost":"192.1.1.1" }
```

I expect the following output lines:

```
| 192.168.224.124 |
| 192.1.1.1       |
```

But the output was:

```
| 192.168.224.124 |
| 192.1.1.1 |
```

So it seems, that the width and precision flags of printf for strings are ignored. I've tested different combinations width, precision, width and precision with left or right justification. Padding never took place.

I'm using:

1. grafana latest (v7.5.3) on docker community 20.10.5
2. loki 2.2.0
3. promtail 2.2.0
4. User OS Windows 10 with Chrome Browser  89.0.4389.114
5. Default set of grafana plugins coming with the docker image

**Comment by ivanahuckova** [comment]
@FSeidinger you can toggle *Wrap lines* settings to switch between **wrapping** which preserves newlines, spaces and tabs and **no wrap** that ignores newlines, spaces and tabs. Unfortunately, css property [white-space](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#values) doesn't have a value, that would ignore newlines and keep spaces and tabs. However, for your usecase, you can just use wrapping which results in your expected behaviour. 

**Wrap line off:**
![image](https://user-images.githubusercontent.com/30407135/115847930-ad1b7300-a423-11eb-90f1-59a116e4a0ce.png)

**Wrap line on:**
![image](https://user-images.githubusercontent.com/30407135/115848024-bc022580-a423-11eb-9a44-919727f63c6d.png)
