### ISSUE TITLE
Sharing legend between many charts

### ISSUE THREAD

**Issue by mlowicki** [grafana/grafana#3306]
It happens that the same charts (related set) have the same legend and would be more readable in some cases to have only one section with legend where items can be selected and it filters out all associated charts.

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
