### ISSUE TITLE
Make maximum variable elements configurable

### ISSUE THREAD

**Issue by oscni** [grafana/grafana#33149]
**What would you like to be added**:
Sorry for bringing this up again, found some old issue about the same thing but hear me out first before closing it :)
Maximum number of variable elements drawn in the GUI seems to be set to 1000. Would like to have it configurable some way instead of fixed. I need 1100 elements for an example.

**Why is this needed**:
The new time series panel is awesome and it allows for more different types of metrics on the same graph since you have support for lots of different axis. Therefore it would be perfect to have the ability to choose freely any of the variable elements on the same graph. When doing combined searched with multiple variables you're bound to how you filter the variables, for and example geographically, starting letter etc. and you can't really freely choose for an example metric 322 and 1045 regardless of what other metadata they have, which is a major drawback of course.

Also, the other issues about the same thing are a couple of years old and PCs do get faster all the time so changing to a configurable value with the default being 1000 will stop you from getting issues like this popping up regularly ;)

**Comment by hugohaggmark** [comment]
@oscni we only limit the render to 1000 items, if your variable queries have 1000+ items you can still search for them in the input as shown in the picture below. If this is not the case anymore, then you should report a bug instead because that should work. Thank you.

Example below shows a variable that holds 2187 items and we only render the first 1000, but if you search, you can still find items within all the 2187 items.
![image](https://user-images.githubusercontent.com/562238/115402469-b8845980-a1eb-11eb-9f90-65002db8c585.png)
