### ISSUE TITLE
[Firefox - Grafana 7.5] Mouse wheel vertical scrolling is bugged in query panel

### ISSUE THREAD

**Issue by alsitn** [grafana/grafana#33202]
**What happened:**
In the Query section tab of the Edit Panel of any Graph, vertical scrolling with the mouse wheel no longer works as expected. No other panel or tab suffer the same issue.
In Chrome and Opera everything work as expected.

**What you expected to happen:**
To be able to scroll with the mouse wheel as expected

**How to reproduce it (as minimally and precisely as possible):**
Install Firefox (latest).
Enter any Query tab with enough content to enable the vertical scroll bar.
Try to scroll down with the mouse wheel.

Environment (actual):

    Grafana version: 7.5.4
    Data source type & version: N/A
    OS Grafana is installed on: CentOS
    User OS & Browser: CentOS 7; Firefox 88
    Grafana plugins: N/A

**Comment by hugohaggmark** [comment]
Hi @alsitn and Thank You to you for taking the time to create this issue!. 

I can't repro this issue on MacOS, Firefox 88 with a Logitech Mouse. Closing this issue as I can't repro it and we're trying to limit open GitHub issues in order to better track planned work and features. We can always reopen or revisit this issue if more feedback is given.

![bug1](https://user-images.githubusercontent.com/562238/115656871-3d7b8a00-a336-11eb-8f90-6f796d8790fd.gif)
