### ISSUE TITLE
Global Data Source?

### ISSUE THREAD

**Issue by joakimberglund** [grafana/grafana#3322]
Atm all data sources is linked to an Org. if I understand it correctly.

It would be nice if there where an option when adding a data source to make it availible globaly or for some Orgs only.

Atm Im adding the same data sources to 5-6 Orgs....
(Using Orgs so that each group can have their own dashboard list, well and security also...)

**Comment by torkelo** [comment]
security? I mean if the orgs share data sources all data is accessible to all orgs

**Comment by joakimberglund** [comment]
Ah, sorry unclear with the "security". So that each Org has thier own dashboards and can't fiddle with others :)

**Comment by jobrs** [comment]
security would not be an issue if the credentials would not be part of the data source but of the user session.

**Comment by piotr1212** [comment]
I've got +- 10 shared datasources and +- 200 teams. I've patched Grafana to prevent the management of 2000 datasources. Datasources can now be marked as "global" and they will be available from all orgs. I was working on refactoring/cleaning is up so I could contribute it back. But @bergquist explained in his talk at fosdem yesterday that Orgs are not meant to split teams but for running multi-tenant Grafana. Splitting up teams will be implemented in a later release with folders. I understood global orgs probably won't be supported so I won't put time in finishing the patch.

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
