### ISSUE TITLE
Timeseries data request error - Unable to load datasource meta data

### ISSUE THREAD

**Issue by pschuermann** [grafana/grafana#3323]
When using grafana 2.5 with graphite 0.9.13 datasource in proxy mode I get many data request errors. Direct mode however works fine.

Request can be as simple as this:
```
url: /api/datasources/proxy/1/render
target: carbonator.HOSTNAME.disk.avg_disk_sec_read_14p
from: -6h
until: now
format: json
maxDataPoints: 638
```

Response:
```
{
  "message": "Unable to load datasource meta data"
}
```

I tested with grafana 2.5 and previous versions.

trace level logs show:
```
2015/11/24 16:31:21 [dataproxy.go:87 ProxyDataSourceRequest()] [E] Unable to load datasource meta data: Data source not found
2015/11/24 16:31:21 [I] Completed /api/datasources/proxy/1/render 500 Internal Server Error in 3.616358ms
```

**Comment by torkelo** [comment]
strange, what database are you using (for the grafana db)? never seen something like this and no one has reported anything similar.

**Comment by pschuermann** [comment]
I'm using mysql-server version 5.6

**Comment by mathieudurand** [comment]
I have the same issue. I am using grafana 2.5 with zabbix datasource in proxy mode. The problem is difficult to reproduce but happens often enough that I try to avoid the proxy mode for now. 

I am using nginx in front of grafana.

I will try to find more in formation to help on this problem.

The zabbix plugin I am using is: https://github.com/alexanderzobnin/grafana-zabbix

**Comment by johnnybobbybee** [comment]
Getting lots of these myself. Grafana with default sqlite3 db:
2016/01/26 14:16:51 [dataproxy.go:87 ProxyDataSourceRequest()] [E] Unable to load datasource meta data: Data source not found
2016/01/26 14:16:51 [I] Completed 10.X.X.X admin "POST /api/datasources/proxy/2/render HTTP/1.1" 500 Internal Server Error 49 bytes in 1696us
2016/01/26 14:16:51 [dataproxy.go:87 ProxyDataSourceRequest()] [E] Unable to load datasource meta data: Data source not found
2016/01/26 14:16:51 [I] Completed 10.X.X.X admin "POST /api/datasources/proxy/2/render HTTP/1.1" 500 Internal Server Error 49 bytes in 1760us

**Comment by torkelo** [comment]
Must be something wrong with your zabbix plugin , make sure it is installed and you have the correct version

**Comment by johnnybobbybee** [comment]
Not sure that comment was for me.. But I'm not using zabbix. Standard Graphite / Grafana install.

**Comment by mallniya** [comment]
Same problem here (grafana 2.6.0 using pgsql):
2016/02/12 18:03:33 [I] Completed 10.60.1.9 admin "POST /api/datasources/proxy/1/render HTTP/1.1" 500 Internal Server Error 0 bytes in 17123us
Moreover, at the same time # netstat | grep 6000 (6000 is my pgsql port) shows:
tcp4       0      0 10.41.40.11.44417      10.99.3.6.6000         TIME_WAIT
tcp4       0      0 10.41.40.11.63597      10.99.3.6.6000         TIME_WAIT
tcp4       0      0 10.41.40.11.41791      10.99.3.6.6000         TIME_WAIT
tcp4       0      0 10.41.40.11.19743      10.99.3.6.6000         TIME_WAIT
tcp4       0      0 10.41.40.11.55369      10.99.3.6.6000         ESTABLISHED
tcp4       0      0 10.41.40.11.55368      10.99.3.6.6000         ESTABLISHED
and 2 last is initial entries, that appears on grafana start.
After restarting grafana is actually showing some dashboards, but after I push update button in the top right corner new TIME_WAIT connections appear and most of dashboard's graphs in most cases doesn't rendered, but show red triangle in the left top graph block, saying "Timeseries data request error".
If I try to connect to the pgsql host directly it works without delay:
telnet 10.99.3.6 6000
So it's seems like nothing wrong with the connection, more like a grafana2 bug.

**Comment by rayprill** [comment]
We're seeing the same problem as the original poster with v 2.5.0-pre1, along with graphite database at release level 0.9.12.   The symptom is the Timeseries data request error along with thousands of occurrences of the following in the grafana log:

**2016/02/12 16:25:48 [dataproxy.go:72 ProxyDataSourceRequest()] [E] Unable to load datasource meta data: Data source not found
2016/02/12 16:25:48 [I] Completed /api/datasources/proxy/4/render 500 Internal Server Error in 14.84622ms**

The grafana configuration for database takes the default.   We have two datasources defined via the UI: elasticsearch and graphite.   We are storing dashboards in elasticsearch.  Otherwise the metrics datasource is graphite to the localhost.

More info: in our case this only happens with complex dashboards that are refreshed at a high frequency (5 seconds), and we cannot always reproduce it.  Additionally, graphite is being briskly updated with continuous incoming data.

My theory is that graphite is not playing well with grafana.  I turned trace and debug on, but no more info was provided.  A peek at dataproxy.go source code shows no more log output, so that makes sense.

Graphite/carbon db is configured with "inf" cache size. Is this a factor?  Is serving the query too expensive?  Not sure, but it is one idea I'm tossing around. 

Any further information or suggestions are welcome.
