### ISSUE TITLE
share dashboards without saving

### ISSUE THREAD

**Issue by linkslice** [grafana/grafana#3325]
under the 1.x branch we had the ability to create dashboards and graphs and share those without having to save a dashboard. I'm testing out the 2.5 branch and it seems like you have to save in order to use the share button.
We liked the ability to create temporary graphs and share the link without having to clutter the dashboards list with a bunch of dashboards that no one is planning to re-use. Could that feature be added back?

**Comment by abraithwaite** [comment]
This would be very useful to have back.

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Maybe the Explore feature and sharing the link would be a solution to this? https://grafana.com/docs/grafana/latest/explore/#share-shortened-link

Thank you to you for taking the time to create this issue!
