### ISSUE TITLE
Crowd integration

### ISSUE THREAD

**Issue by deejay1** [grafana/grafana#3333]
It would be great to have an Atlassian Crowd authentication connector to support single sign on between multiple apps, this could allow to include Grafana graphs in other products.

**Comment by bgruenefeld** [comment]
+1

**Comment by Arbuzov** [comment]
👍

**Comment by shurshun** [comment]
+1

**Comment by gmessner** [comment]
+1

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.

**Comment by ragstimes** [comment]
+1

**Comment by cudneys** [comment]
+1

**Comment by shurshun** [comment]
Well, you can use crowd <-> dex < oidc > grafana. And it works great!

**Comment by mkwardakov** [comment]
> Well, you can use crowd <-> dex < oidc > grafana. And it works great!

Thank you for the workaround.
