### ISSUE TITLE
conditionals in text fields based on template variables

### ISSUE THREAD

**Issue by timurb** [grafana/grafana#3346]
It would be nice if we could create ERB/Jinja-like templates in text fields.

That is for example display different text based on Grafana template variables.

**Comment by mtanda** [comment]
+1

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
