### ISSUE TITLE
E2E flow for loading existing dashboard and verifying its panel queries work 

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#33524]
**What would you like to be added**:
I would like our E2E testing framework to have the following capabilities:
1. load an existing dashboard - upload a JSON file or import via panel json. 
The latter is probably easier since we already have the [readProvisions](https://github.com/grafana/grafana/blob/master/packages/grafana-e2e/cypress/plugins/readProvisions.js) plugin. The drone plugin pipeline is setup to read provisions from the [plugin-provisioning repo](https://github.com/grafana/plugin-provisioning/), so that part is already in place. 
2. open the dashboard, run (refresh) and wait until all panels that are in the viewport has received a response from the backend. 
3. verify that no (unexpected) errors were returned from the backend
I'm not entirely sure how to do this. We could possibly check that there's no red error message on the top left of each panel, but then we're only able to test the happy path. What if we want a certain query to return an error? Another option would be to match a screenshot. Using that strategy, we'll only be able to test one certain time range. 

I'm not too familiar with the E2E testing package, but I think parts of the aforementioned capabilities are already supported in our existing flows. 

**Why is this needed**:
A few customers of our are pushing hard for improved quality assurance from our side. They want to be sure we don't break stuff in their datasource plugins when new versions of the plugin or major/minors of Grafana is released. Now one customer is asking explicitly for testing specific queries in a dashboard. 

**Concerns**: 
We'd like to avoid slowing down our builds more than necessary, so I guess we need to set a timeout for long running dashboard panel queries to 30 seconds or something like that.

**Comment by sunker** [comment]
Thoughts @hugohaggmark @vickyyyyyyy @ryantxu?

**Comment by hugohaggmark** [comment]
@sunker here are my 2 cents:

1. We use provisioning to load existing dashboards today, i.e. if you add a dashboard to https://github.com/grafana/grafana/tree/master/devenv/dev-dashboards then it's available in e2e tests (details in https://github.com/grafana/grafana/blob/master/e2e/start-server)
2. Waiting until responses are done in the backend is very tricky, in Cypress you can use intercept (https://docs.cypress.io/api/commands/intercept)to mock responses from the backend or add tags so that you can await on in your tests. The await part is not working 100% IMHO and we still need to add waits.  
3. I guess you can mock the responses in this case using intercept for error scenarios, but then there's the issue how to identify it in the ui. Maybe that red triangle could be one solution. Screenshot testing comes with a lot of false positives, so be careful with that.

**Comment by hugohaggmark** [comment]
I'm happy to get in a call and discuss this more.

**Comment by vickyyyyyyy** [comment]
@sunker 
1.

I'm not familiar with the flow of importing dashboards so I can't provide any helpful input for this 😔

2.

> wait until all panels that are in the viewport has received a response from the backend

Do you mean check that a specific response has been received or assert on something has loaded/rendered? Otherwise, agree with @hugohaggmark  re the `intercept` if you need to wait for a specific response.

3.

> What if we want a certain query to return an error?

Can you assert on the red triangle specifically?
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderCorner.tsx

> We could possibly check that there's no red error message on the top left of each panel

This could work but I'm not too sure how robust it would be? Testing for the absence of things is always tricky because you could assert that the alert doesn't show up and Cypress would pass but it may be because Cypress passes the check before the alert actually shows up?

> Another option would be to match a screenshot

Following on from what Hugo's mentioned, I agree and personally, I would limit screenshot testing. Core Grafana's UI can change a lot with releases and having to constantly update the screenshots can be a pain. Currently, for our enterprise plugins, we screenshot test only the graph/chart to ensure the data for the certain time range (actually) comes back and is the same - which may be what you meant? For the sad path, I would have thought asserting on the red triangle may be more robust over screenshot testing.

> We'd like to avoid slowing down our builds more than necessary, so I guess we need to set a timeout for long running dashboard panel queries to 30 seconds or something like that.

Yeah, this can be annoying, we've had a few plugins where the data takes a while to come back and we have had to increase the timeout by a few seconds 😬

**Comment by vickyyyyyyy** [comment]
Closing this as we split this out into:
https://github.com/grafana/azure-data-explorer-datasource/issues/245
https://github.com/grafana/azure-data-explorer-datasource/issues/246
