### ISSUE TITLE
Grafana embeds not working in Chromium/Chrome incognito window

### ISSUE THREAD

**Issue by tricoos** [grafana/grafana#33610]
OS: Raspberry Pi OS (buster) - latest version with all updates (command line calls), Windows 10 20H2
Browser: Chromium 88.0.4324.187 (official build)
Grafana: 7.3.2

When I start Chromium like this after the loading animation the error message "...this could be caused by your reverse proxy..." is shown for all embeds:
chromium-browser --incognito --kiosk http://example.com/my-page-with-embeds/

When I start Chromium and omit the "incognito" parameter it works as expected:
chromium-browser --kiosk http://example.com/my-page-with-embeds/

The same happens when I open an incognito window in Chrome on Windows - it only works in non-incognito mode.

![image](https://user-images.githubusercontent.com/8438806/116822537-a7d6ca80-ab7f-11eb-8e06-f710e86b21ef.png)

**Comment by torkelo** [comment]
Will need chrome developer console output to review the error

**Comment by tricoos** [comment]
![image](https://user-images.githubusercontent.com/8438806/116966153-d653c300-acaf-11eb-8282-844376efce76.png)

Website where the embed is inserted via an iFrame is accessed via HTTP and Grafana is hosted via HTTPS - works perfectly in normal mode, only breaks in incognito mode.

Sample embed URL (does not with any I tested):
https://{HOSTNAME}/d-solo/riqXZwRgk/webiq-share-dashboard?orgId=1&theme=light&panelId=4&theme=light&from=now-1d&to=now&refresh=1m

**Comment by tricoos** [comment]
This seems to happen because of this **default** setting in Chrome/Chromium:
https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

When I enable third-party cookies and site data it works. 
However, why is localStorage used anyway - or to ask differently: why is the exception not caught and localStorage simply not used? That might a a good workaround.

**Comment by glintik** [comment]
Hey @torkelo @ivanahuckova @kaydelaney,

As I can see localStorage is used in public/app/core/store.ts and considered as MUST EXISTS object in window object and available for writing. In number of browsers this assertion is false due to security policies, especially in incognito mode, i.e. from [Firefox 43](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/43):
<img width="755" alt="Screenshot 2021-09-13 at 23 51 35" src="https://user-images.githubusercontent.com/2947475/133154706-82b7fd59-17ae-4129-99d6-0c81b0e30592.png">

What I propose:
Modify store.ts to use fake storage window.$localStorage if window.localStorage is not writable.
If it's OK, I can prepare and test PR.

**Comment by kaydelaney** [comment]
Closing in favor of #40434
