### ISSUE TITLE
Setting the neutral-point of a gauge

### ISSUE THREAD

**Issue by sfranzis** [grafana/grafana#33702]
**What would you like to be added**:
The neutral or zero point of a gauge is at the left of the panel. When I set the range from e.g. Min=-5 to Max = 5 then the display of negative values looks not natural. 
I would like the neutral-point to be configurable in the standard field options (where we have Min, Max, ...).

**Why is this needed**:
My use case is a solar battery inverter, which shows positive values when charging and negative values when discharging.

This is how the gauge panel works now:
![gauge-1](https://user-images.githubusercontent.com/12957935/117032673-f613d700-ad01-11eb-85e5-8cc0846a309e.png)

This is what I would like to see - Neutral value = 0  (mockup not proportional to values):
![gauge-2](https://user-images.githubusercontent.com/12957935/117032700-fad88b00-ad01-11eb-89ea-2f325ba9ec82.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
