### ISSUE TITLE
Doc: Coordinate switching of next to latest for Grafana 8.0

### ISSUE THREAD

**Issue by achatterjee-grafana** [grafana/grafana#33796]
Traditionally, we have done the switching when beta is released.

However, given the quantity of PRs for 8.0 and also, keeping in mind that when we switch we will have to backport all changes, we have decided to make the switch closer to GA. Ideally, the day before GA announcement. Docs need to work closely with @robbymilo to make the switch on the correct date.

@oddlittlebird  is also suggesting we add a link/label to the docs landing page that will users directly to 8.0 docs. We need to a little more about this.

Tagging @daniellee , to help us with the date for GA.

**Comment by oddlittlebird** [comment]
To make this even more entertaining, we will also need to:
- Avoid polluting the archival 7.5 version with 8.0 content.
- Be aware if blog posts are linking to anything in the `next` folder and manage that, because previously during the beta period they linked to extant docs in the `latest` folder.
- Find out if @aligerrard and company plan on having any other links to the docs or beta content that we should be aware of.

**Comment by daniellee** [comment]
@oddlittlebird @achatterjee-grafana can this be closed now?

**Comment by achatterjee-grafana** [comment]
Closing, thank you for following up.

**Comment by achatterjee-grafana** [comment]
We have made the switch on June 7.
