### ISSUE TITLE
Alerts cause too many requests

### ISSUE THREAD

**Issue by daviend** [grafana/grafana#33837]
**What happened**:
My Grafana is getting metrics from the Azure Monitor data cource. I configured some alerts. During the day Grafana starts to give me status messages: 429 Too Many Requests. The error messege details are:

tsdb.HandleRequest() response error &{request failed, status: 429 Too Many Requests, body: {"error":{"message":"Rate limit of 86400 per day is exceeded.","code":"ThrottledError","correlationId":"b820d4d6-54b6-44d4-b43f-************","innererror":{"code":"ThrottledError","message":"Rate limit of 86400 per day is exceeded.","limitValue":86400,"moreInfo":"https://aka.ms/api-limits"}}} 

This error message is also the message body of the alerting email.

I think Grafana is requesting my endpoints many times just for the alerts until Azure informs me about the rate limit.

When I pause the alerts, the message no longer appears.

**What you expected to happen**:
I expect that Grafan is not producing too many requsts on my endpoint.

**How to reproduce it (as minimally and precisely as possible)**:
When I pause the alerts, the message no longer appears. When I resume the alertes, I will get the message during a day.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.5.5
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Azure App Service on Alpine Linux in Docker image
- User OS & Browser: all
- Grafana plugins: standard
- Others: ---

**Comment by marefr** [comment]
Would suggest trying to use more sensitive values for _evaluation interval_ and _For_ when configuring your alert rules, see https://grafana.com/docs/grafana/latest/alerting/create-alerts/#rule for more information.

If you still believe this problem occurs due to Grafana and not a configuration error please let us know including detailed information about your configuration/setup and we'll consider reopen this. Thanks
