### ISSUE TITLE
[FeatureRequest] Add possibility to copy time range to use the same range in different grafana dashboards

### ISSUE THREAD

**Issue by Hixon10** [grafana/grafana#33931]
I would like to have copy button to copy time range. 

My scenario is pretty simple. 
1. I open a grafana dashboard with `URL 1` in `browser tab 1`. 
2. I want to analyze data in the same time range, therefore I open grafana dashboard with `URL 2` in `browser tab 2`. 
3. Right now, I have to manually choose time range in the second dashboard tab, but instead of I want just copy it to clipboard from the first tab and insert it to the second tab. 

![image](https://user-images.githubusercontent.com/2648802/117823065-bdca4680-b275-11eb-8000-f51ab564e02e.png)

**Comment by Hixon10** [comment]
I think, it is a similar task - https://github.com/grafana/grafana/issues/17893

**Comment by mem** [comment]
+1 to this, I would really love to be able to take the current time range in one dashboard and apply to another dashboard.

What I do now is I go to the source dashboard, open the time picker, select the from string, paste it in the destination dashboard. Repeat for the "to" value. This requires switching back and forth between the dashboards and making sure I'm copy-pasting the correct values in the correct fields.

The _ideal_ solution would be to click something in the source dashboard that copies the value to the "clipboard" like "copy panel" does ("clipboard" in quotes because I suspect Grafana is not actually copying to the clipboard) and press a hot key in the destination dashboard (not even open the time picker) and have the time range updated to match.
