### ISSUE TITLE
Graphite: Authentication failure results in misleading error

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#34013]
Grafana master.
when you add a graphite datasource, but the auth is wrong, the UI says "HTTP error Bad Request"
web developer tools network inspector reveals the request to POST
	http://localhost:3000/api/datasources/proxy/1/render resulted ina response saying "Authentication to data source failed" (and it uses http code 400 which is not appropriate). see screenshot
![screenshot-auth-error](https://user-images.githubusercontent.com/20774/117998240-5df29f00-b34c-11eb-9e23-dc91febb3b56.png)

**Comment by marefr** [comment]
Introduced by #28962

**Comment by marefr** [comment]
@aknuds1 did you come to the conclusion that returning the actual 401 HTTP status couldn't be done because this bug where the browser prompts the user for username and password, since the data source sends back the header www-authenticate? Did you consider removing the `www-authenticate` header in the response and returning 401?

**Comment by aknuds1** [comment]
> @aknuds1 did you come to the conclusion that returning the actual 401 HTTP status couldn't be done because this bug where the browser prompts the user for username and password, since the data source sends back the header www-authenticate? Did you consider removing the `www-authenticate` header in the response and returning 401?

@marefr hey sorry, didn't see this initially.

I came to two conclusions:

1. Returning 401 HTTP status code together with www-authenticate header causes the bug of the browser asking the user to authenticate against Grafana.
2. That 401 should signal that the request to the server (Grafana in this case) is unauthenticated; it isn't, instead the problem is bad parameters to the proxied data source (Graphite). I think the correct thing to do in this case is to return 400 to signal a user input problem (i.e. bad configuration of Graphite), perhaps along with enough metadata to let the frontend code deduce that the problem is in fact bad Graphite credentials.

**Comment by Dieterbe** [comment]
@aknuds1 I think point 2 is right on! we can implement status codes more exactly but it is indeed critical that grafana properly communicates what happened with the grafana-to-datasource communication.  Clarity to the user is a paramount, because the grafana-to-datasource communication is largely hidden to them otherwise (e.g. they can't see it in the network inspector)

**Comment by aknuds1** [comment]
So I suppose we mainly need to fix this in the frontend (plus send some supporting metadata from backend)?

**Comment by marefr** [comment]
Changes related to this code needed: https://github.com/grafana/grafana/blob/2f690759c2cf6bbf68dbc52d2da93307cba523a8/pkg/api/pluginproxy/ds_proxy.go#L118
