### ISSUE TITLE
[FeatureRequest] Table column filter by values "check all" functionality

### ISSUE THREAD

**Issue by memfiz** [grafana/grafana#34054]
**What would you like to be added**:

Column filter by values needs select all functionality. Similarly, it has a "Clear filter" when you want to clear all checked values.

**Why is this needed**:

When using big tables there is often a need to filter by values to select many entries. Then you use the filter you can find e.g. 100 of values and there is no possibility to select them all with one click, you need to check them one by one, that is not feasible with such a large number of entries.

As an example
[https://play.grafana.org/d/baqo21CGz/column-filter-select-all-request?orgId=1](https://play.grafana.org/d/baqo21CGz/column-filter-select-all-request?orgId=1)
If you would like to select values of _id column that contain "5ndM" there is no way to check them all with one click after the filter finds them.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
