### ISSUE TITLE
Flux timeShift() not working correctly in Grafana

### ISSUE THREAD

**Issue by stefanbie** [grafana/grafana#34492]
Hi

If I do
`|> timeShift(duration: 10h, columns: ["_time"]) `
in Flux it moves the graph 10 hours forward, which is correct. if I, however, zoom into the graph (at the new time) no data is displayed. It seems like whether data is displayed depends on the if it is in the non time shifted interval but if it is displayed it is with the time shifted timestamps...

I use Influxdata cloud and I have tested on Grafana 7.2.0 and Grafana v8.0.0-beta

**Comment by gabor** [comment]
hi @stefanbie are you setting the timerange-constraint dynamically based on the currently selected window, or is it fixed?

what i mean:
this works:
```
from(bucket: "mybucket")
  |> range(start: 2021-05-25T14:00:00Z, stop:2021-05-25T14:10:00Z)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_idle")
  |> timeShift(duration: 60m)
```

as you see, i set the time-range to a fixed-time-range. i am getting data from influxdb from that time-range, and then i move them 60minutes into the future. if this produces any data, you can zoom into the graph and everything will work.

this will not work well:
```
from(bucket: "mybucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_idle")
  |> timeShift(duration: 60m)
```
as you see, i set a dynamic time-range, based on the currently selected time-range in grafana. problem is, as you start zooming, that time-range will change, and this will change the data you get.
at the beginning it will work and you will see the data you want. but then, when you zoom into the region where the timeshifted data is, suddenly `v.timeRangeStart` and `v.timeRangeStop` will point to a region of time in the future, where there is no data. so no data will be shown.

of course, maybe your problem is something different, this was just the first thing that came to mind. if it is so, please tell us more about the flux-query you use. (please remove the confidential parts of course)

**Comment by gabor** [comment]
hi @stefanbie i see. unfortunately there is no good fix currently for this, the explore-mode uses one time-range only, and when zooming, the time-range changes. so i recommend switching those time-ranges to have fixed numbers in them when using timeshift and wanting to zoom in. i hope that helps.

**Comment by stefanbie** [comment]
Hi @gabor still seems like a bug to me :)

**Comment by gabor** [comment]
@stefanbie i thought some more about it, and try this workaround:
```
import "experimental"

a = experimental.subDuration(d: 60m, from:v.timeRangeStart)
b = experimental.subDuration(d: 60m, from:v.timeRangeStop)

from(bucket: "mybucket")
  |> range(start: a, stop: b)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_idle")
  |> filter(fn: (r) => r["cpu"] == "cpu1")
  |> timeShift(duration: 60m)
  ```

(replace the "60m" with the duration you want). this should produce the results you need :)

**Comment by gabor** [comment]
@stefanbie (adding to the above workaround: this uses some "experimental" stuff in flux and there's a warning about them ( https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/experimental/#use-experimental-functions-at-your-own-risk ))

**Comment by gabor** [comment]
> Hi @gabor still seems like a bug to me :)

@stefanbie you see, the way this is designed to work is that you specify a time-range, and then the query reads data from that time-range. zooming modifies the time-range, so it does work the way it was intended.

i do understand your frustration with the situation. 
unfortunately, there is no easy fix for this. we would have to completely rework how explore-mode works, to maintain basically two time-ranges: one for data-querying, and one for data-displaying. that is a big change, and the number of cases where it helps seems small right now (and can be improved/fixed by workarounds), and it would complicate things for other uses cases. so for now we will not implement such a feature. i hope the workaround i described to you will help you fix this problem.

**Comment by stefanbie** [comment]
Hi @gabor , thanks for the update!
So, it seems like I will not be able to compare two graphs (without having to zoom out until both graph data periods are in time interval) if not using this experimental method. As I'm running in production environment I won't be able to use experimental (although it seems to work for some reason). Hope this will be available in the future as it is a nice thing to be able to compare graphs :)

**Comment by stefanbie** [comment]
Oh, ok, that sound fine. Im running a test for two hours that produces a graph every month. I would like to compare these graphs in the same panel.

**Comment by gabor** [comment]
hm... i see, so basically you want to see results for different months but they should be at the same time-range so that you can visually compare it, right?

**Comment by stefanbie** [comment]
Yes :)

**Comment by gabor** [comment]
hmm.. the best i could come up with is the following:
(we will draw cpu-usage for the last 5minutes, compare it with the same time-slice 5minutes ago and 10minutes ago):

we run this flux query:

```
from(bucket: "mybucket")
  |> range(start: -30m, stop: 30m)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_idle")
  |> filter(fn: (r) => r["cpu"] == "cpu1")
  |> set(key: "_measurement", value: "cpu_current")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "1")

from(bucket: "mybucket")
  |> range(start: -30m, stop: 30m)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_idle")
  |> filter(fn: (r) => r["cpu"] == "cpu1")
  |> set(key: "_measurement", value: "cpu_5m_ago")
  |> timeShift(duration: 5m)
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "2")

from(bucket: "mybucket")
  |> range(start: -30m, stop: 30m)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_idle")
  |> filter(fn: (r) => r["cpu"] == "cpu1")
  |> set(key: "_measurement", value: "cpu_10m_agao")
  |> timeShift(duration: 10m)  
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "3")
```

important points about the query:
- i basically run the same query 3 times, with different timeshift-values
- note that the time-range is not bound to the grafana-time-range. it is fixed to current-time. (this will allow us to zoom this in grafana without breaking anything)
- i overwrite the `_measurement` key in every part of the flux query, this will generate labels in grafana that we can work with
- the yield-part needs to be different in every query-part for flux reasons

you can now put this query into a panel, set the panel's time range to "last 5 minutes", and you should see nice data.

we can go another step even, right now the labels on the graph are ugly like: "usage_idle {cpu="cpu1", host="host", name="cpu_current"}". we only want the "cpu_current" part, we can do it with transforms:
- add a transform "organize fields". this will complain that the data is not a single frame. oh well, delete the transform
- add the transform "outer join", choose "field name" "_time"
- now we can add the "organize fields" transform, and simply enter new names for the fields that you want to rename.
(alternatively you can just experiment with the rename-by-regex transform).

i hope you find something useful here.

**Comment by stefanbie** [comment]
Hi @gabor , thanks for you effort on this, really appreciate!

**Comment by cesuper** [comment]
Hello @gabor and @stefanbie,
After a long time, did you find any solution for this? I am having the same issue...

**Comment by cesuper** [comment]
I am trying to implement your suggestions. However, when I increase the timeRange to involve more data to be timeShift-ed, the content of the timeSeries chart getting more narrow. This behavior is expected but I am unable to see the data. Any idea?

**Comment by gabor** [comment]
hi @cesuper , i'm sorry what do you mean by "more narrow"? could you maybe add a screenshot that shows the problem?

**Comment by cesuper** [comment]
Szia @gabor,
Greetings from Hungary :) 
Please look at the screenshot below, where two charts are taken place.
![image](https://github.com/grafana/grafana/assets/63722230/f22a1bc2-9d90-4211-af96-9e6d1124c457)
The first one called navigator, that I use to zoom in and out on trend points. Below you can see a series of points each of which belongs to one point on the navigator. I could say that each point in the upper chart is an aggregated (max, or mean) value for one series of points of the bottom chart. 
I would like to compare the values of the bottom chart by shifting them to a common timestamp as you can see here:
![image](https://github.com/grafana/grafana/assets/63722230/34462f3b-938f-42e5-b906-1410b76b5a9b)
My problems are the following: 
1. As the timeRange increase the series becomes less readable due to the X axis is the TimeSeries chart.
2. When I zoom in the second chart the timeRange changes so that the flux query has invalid data. Maybe If I can disable zoom on 2nd chart somehow...

Any idea how to proceed? Btw, should I open a new topic my questions?

**Comment by gabor** [comment]
szia @cesuper , thanks for the extra info. yes, a new topic would be better probably, could you please create it?
though, i'm not sure if we will be able to help you much here, these seem to be architectural limitations. but these days i don't work on influxdb-releated issues, but when you create a new issue, it will be looked at by the "currently working on influxdb issues" people, they may have new ideas to how to solve this.

**Comment by cesuper** [comment]
https://community.grafana.com/t/visualization-of-timeshift-result/90201 Done! Have a nice day, and thank you for your help!
