### ISSUE TITLE
UI rendering cuts off bottom of colored single row cells in table (7.5.6 + 8b1/2)

### ISSUE THREAD

**Issue by lux4rd0** [grafana/grafana#34529]
**What happened**:

When displaying tables that are only a single row height, the bottom part of the row is chopped off. (Using 3 segments in the layout editor: one for the title, one for the row header, and one for the cell).

If you give that panel four-block layout segments, you can see the full row.

**What you expected to happen**:

It would be nice that single-row tables (or multi rows) don't get cut off so that each table row equates to the UI panel segment size. There's actually room in the URL to show more the bottom of the cell - it's just cut off with gray border space. (Notable when using colored cell backgrounds)

**How to reproduce it (as minimally and precisely as possible)**:

<img width="1592" alt="table format" src="https://user-images.githubusercontent.com/30187533/119029820-c1915380-b96e-11eb-8258-833b1409f3e3.png">

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.5.6 (5fdad5bfe4) and Grafana v8.0.0-beta2 (9d4c719205)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: MacOS - Chrome Version 90.0.4430.212 (Official Build) (x86_64)
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Confirmed on Grafana Play https://play.grafana.org/d/b2ZF4Y6Gz/ui-rendering-cuts-off-bottom-of-colored-single-row-cells-in-table-7-5-6-8b1-2-34529?orgId=1

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
