### ISSUE TITLE
Grafana UI locks sometimes when creating a new dashboard and panel

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#34604]
**What happened**:
The flow of new dashboard -> new panel on main will _sometimes_ lock my browser.

**What you expected to happen**:
Not to lock

**How to reproduce it (as minimally and precisely as possible)**:
Keep creating dashboards, and click add new panel. If it doesn't lock, keep doing that until it does - no saving needed.

**Anything else we need to know?**:
This might only trigger with inspector open? Or perhaps more like to trigger with inspector open. When happens, a line isn't drawn on the plot before it locks.

**Environment**:
- Grafana version: 888683a8ad 
- Data source type & version: test-datasource
- User OS & Browser: Linux, Google Chrome Version 90.0.4430.93 (Official Build) (64-bit)

**Comment by leeoniya** [comment]
with devtools open to the Sources panel, press pause after the browser locks up and see where it's looping.

![image](https://user-images.githubusercontent.com/43234/119377167-6e771380-bc82-11eb-8281-aedfb91ea813.png)

might be same as https://github.com/grafana/grafana/issues/31724

**Comment by kylebrandt** [comment]
Here is where it paused on me:

![image](https://user-images.githubusercontent.com/1692624/119378416-42f92680-bc8c-11eb-9a3a-cd5abcf46147.png)

**Comment by leeoniya** [comment]
this looks like the same issue as #31724. the `convergeSize` in the call stack is where this can happen if the axes size calculation does not settle deterministically.

i would think to check to see if this bounces back and forth between 2 different return values (though i don't see this in the stack).

https://github.com/grafana/grafana/blob/888683a8ad2f0f05d66d5a5d085c230dbba26e33/packages/grafana-ui/src/components/uPlot/config/UPlotAxisBuilder.ts#L129-L148

probably would need to put a breakpoint into the anonymous fn above axesCalc() in the stack. really tricky because it's intermittent, console.logs may reveal more.

wish i could be of more help, but i have never encountered this, so without a repro :man_shrugging:
