### ISSUE TITLE
Frontend Platform: Cross team testing kitchen sink issue

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#34624]
Please add any found issues here:

**Comment by joshhunt** [comment]
**What happened**:

Stat panel visualisation shows a `cannot read property 'scale' of undefined` error if the value is non-numeric.

**What you expected to happen**:

It doesn't show an error, the graph/sparkline just doesn't render.

**How to reproduce it (as minimally and precisely as possible)**:

Sample panel: https://g80-beta.grafana.net/d/Y29yZf3Mz/joshs-azure-monitor?orgId=1&editPanel=15&from=1621912071030&to=1621933671030

1. Create a new panel using gdev-testdata data source, configured as:
    - Scenario: CSV Metric Values
    - String Input: hello_world
    - Alias: greeting
2. Set the panel visualisation and set 'Fields' to 'greeting'
3. _Panel crashes with exception_
4. Change 'Graph mode' to 'None' and observe the panel does not fix itself - you must toggle table view to rerender.

**Anything else we need to know?**:

Given Graph mode: Area is the default value, I don't think it should throw an exception and crash the panel if the data cannot be graphed.

**Comment by joshhunt** [comment]
**What happened**:

Setting visualisation to "Table view" when editing causes the panel data to not update.

**What you expected to happen**:

Updating a query when in the new "Table view" mode should still show new data as it's updated. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new panel using gdev-testdata data source, configured as:
   - Scenario: CSV Metric Values
   - String Input: hello_world
2. Configure the panel to use the Table visualisation
3. Change the 'String Input' in query editor
   - _Observe that the value updates correctly in the visualisation_ 😄 
4. Turn on the "Table view" mode
5. Change the 'String Input' in query editor
   - _Observe that the value does not update in the "table view" visualisation_ 😢 
6. Turn "Table view" mode back off
   - _Observe that the value still has not updated in the visualisation_ 😐
3. Change the 'String Input' in query editor
   - _Observe that the value updates correctly in the visualisation_ 😄 
  
I also replicated this issue using similar steps with the Azure Monitor data source, so the issue seems to be independent to the data source.

**Comment by gabor** [comment]
when using the timeseries visualization, switching between the tooltip-modes (single, all, hidden) does not apply immediately. if i save the dashboard and reload the browser it gets applied.

**Comment by undef1nd** [comment]
Catalog Plugin app: `Library` tab does not get highlighted when active. 
<img width="189" alt="Screenshot 2021-05-27 at 19 53 53" src="https://user-images.githubusercontent.com/10127682/119866681-b9fd1c00-bf25-11eb-9470-24f0156d7cc8.png">

**Comment by pkolyvas** [comment]
## Library panels loose fidelity in certain workflows.

### What happened

The library panel only displays 1 series of data (a different metric) when two are expected. 

<img width="940" alt="Screen Shot 2021-05-27 at 9 13 13 AM" src="https://user-images.githubusercontent.com/43178667/119878107-26652480-bf00-11eb-8d05-9301dec4a3f7.png">

## What I expected to happen

The library panel would show 2 series of data:

<img width="715" alt="Screen Shot 2021-05-27 at 3 32 32 PM" src="https://user-images.githubusercontent.com/43178667/119879418-9aec9300-bf01-11eb-9186-cbfbb45d93c1.png">

### How to reproduce it

1. Create a library panel from a (legacy) Graph Panel:
<img width="700" alt="Screen Shot 2021-05-27 at 3 32 39 PM" src="https://user-images.githubusercontent.com/43178667/119879456-a475fb00-bf01-11eb-971e-7c59d4c4925e.png">

2. Add an empty panel:
<img width="768" alt="Screen Shot 2021-05-27 at 3 33 36 PM" src="https://user-images.githubusercontent.com/43178667/119879578-c4a5ba00-bf01-11eb-8cc1-9bf3a27782a4.png">

3. Change the panel type to a library panel and pick the library panel in question:
<img width="424" alt="Screen Shot 2021-05-27 at 3 15 22 PM" src="https://user-images.githubusercontent.com/43178667/119879781-f454c200-bf01-11eb-9d61-08d992440f79.png">

4. Panel appears with no data and the wrong query:
<img width="1072" alt="Screen Shot 2021-05-27 at 3 15 40 PM" src="https://user-images.githubusercontent.com/43178667/119879850-0afb1900-bf02-11eb-88a1-a6c872af2fe4.png">

5. There's no way to proceed without saving the panel and breaking it everywhere:
<img width="713" alt="Screen Shot 2021-05-27 at 3 35 21 PM" src="https://user-images.githubusercontent.com/43178667/119879935-21a17000-bf02-11eb-864d-0fbaf515f870.png">

**Comment by hugohaggmark** [comment]
@pkolyvas thank you for taking the time to report this. I'll have a look

**Comment by joshhunt** [comment]
**Shared tooltip** X position is incorrect when scrolled.

Reproducable on https://g80-beta.grafana.net/d/Y29yZf3Mz/joshs-azure-monitor?orgId=1 with the two "GithubTestDataVM" panels after you scroll down a few 100px.

I think I saw discussion about this on Slack earlier, so im not sure if it's since been fixed

<img width="1648" alt="Screen Shot 2021-05-28 at 2 42 05 pm" src="https://user-images.githubusercontent.com/46142/119995131-309d2680-bfc5-11eb-966d-7f5e529614c6.png">

**Comment by yesoreyeram** [comment]
Browser crashes when toggling between graph & time series panels.  

Example: to reproduce https://g80-beta.grafana.net/d/O9oYtDeMz/crash?orgId=1&editPanel=2 ( change viz to old graph and then back to time-series ) browser crashes. 

* Create a time-series with 10 series ( random walk )
* Add a couple of overrides ( in my case, added y-axis placement, y-axis label )
* Save the dashboard
* Change viz type to graph(old)
* Change viz type to time-series and wait for few seconds then the browser will crash
* Also noticed the y axis override didn't work as expected.

confirmed the issue in beta2, beta3 

( @kminehart  confirmed similar issue for bar chart )

https://user-images.githubusercontent.com/153843/120511419-514cee00-c3c2-11eb-9e7e-d923950ab29b.mov

**Comment by kminehart** [comment]
If anyone has any tips on recording a stack trace or profile for the above issue i'm all ears. Any attempt to record a profile just stops whenever the tab crashes.

**Comment by kminehart** [comment]
Another bug: Manually annotations on the old Graph visualization do not display unless there is an annotation query on the dashboard.

To reproduce:
* Open a dashboard with no annotations.
* In a panel with the Graph (old) visualization, click on the graph to create a new annotation.
* This annotaiton will not be visible or will not be created.
* Create a new annotation query in the dashboard and save.
* Create a manual annotation again, and it should be visible now. Ones that were created before will not be visible.

**Comment by torkelo** [comment]
I do not think that is a new bug, creating annotations before dashboard is saved does not work
