### ISSUE TITLE
SSL implementation vulnerable for POODLE attack

### ISSUE THREAD

**Issue by brammeleman** [grafana/grafana#3483]
How about disabling SSL 3.0 as described here?
https://groups.google.com/d/msg/golang-nuts/mW_kKxEPfYc/yEyykO2OrYYJ

Bests,

Bram

**Comment by gdubicki** [comment]
I think that you should either:
a) implement this,
b) drop SSL support at all,
c) put a big fat warning in the docs (http://docs.grafana.org/installation/configuration/#protocol) and the default config file comments that your SSL implementation is unsafe.

**Comment by bergquist** [comment]
@gdubicki I think you are right. Ill make sure this is fixed in 3.1.2

**Comment by bergquist** [comment]
@gdubicki This should be disabled since 3.0 when we started building grafana using go 1 dec 2015 https://github.com/grafana/grafana-packer/commit/57a173715abafe93b2befdf868589c3a2faee857#diff-3254677a7917c6c01f55212f86c57fbf 

https://github.com/golang/go/issues/9364

But we should update the doc recommending upgrading to 3.x
