### ISSUE TITLE
Stat panel visualisation shows an error if the value is non-numeric.

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#34835]
**What happened**:

Stat panel visualisation shows a `cannot read property 'scale' of undefined` error if the value is non-numeric.

**What you expected to happen**:

It doesn't show an error, the graph/sparkline just doesn't render.

**How to reproduce it (as minimally and precisely as possible)**:

Sample panel: https://g80-beta.grafana.net/d/Y29yZf3Mz/joshs-azure-monitor?orgId=1&editPanel=15&from=1621912071030&to=1621933671030

1. Create a new panel using gdev-testdata data source, configured as:
    - Scenario: CSV Metric Values
    - String Input: hello_world
    - Alias: greeting
2. Set the panel visualisation and set 'Fields' to 'greeting'
3. _Panel crashes with exception_
4. Change 'Graph mode' to 'None' and observe the panel does not fix itself - you must toggle table view to rerender.

**Anything else we need to know?**:

Given Graph mode: Area is the default value, I don't think it should throw an exception and crash the panel if the data cannot be graphed.

This was working some time on main, then it broke, not sure exactly sure when.

Originally posted by @joshhunt in  [#34624 (comment)](https://github.com/grafana/grafana/issues/34624#issuecomment-847696649)

**Comment by leeoniya** [comment]
i have verified that this error does not occur on `main`, and was fixed by #34759.

however, there is still an invisible empty chart created even though there are no graphable fields that can be used. i opened up https://github.com/grafana/grafana/pull/34856 to omit the graph entirely and choose a layout that only has text (which becomes larger as a result of no longer needing the chart).

cc @joshhunt
