### ISSUE TITLE
Feature Request: "Now" axis in forecast graphs

### ISSUE THREAD

**Issue by cloud-rocket** [grafana/grafana#3488]
I really miss the "now" Y Axis bar, splitting the graph into previous and future time when working with future forecasts.

I am working with InfluxDB and it is possible to select relative time (e.g. "now-12h" until "now+12h"), but the graph is not clearly showing the past vs. the future.

I think it would be great to have another option of "NOW axis" checkbox within "Axes & Grid" settings 

Thanks

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
