### ISSUE TITLE
Wrong target version when compiling v7.5.7

### ISSUE THREAD

**Issue by Berbe** [grafana/grafana#34887]
**What happened**:
```json
"version": "7.5.6",
```
in https://github.com/grafana/grafana/blob/v7.5.7/package.json

**What you expected to happen**:
```json
"version": "7.5.7",
```

**Environment**:
- Grafana version: 7.5.7

**Comment by Elfo404** [comment]
Hello @Berbe good catch!

we had some issues during the release and some files were not updated correctly, this shouldn't cause any issue though (npm packages for example were published correctly, ie. https://www.npmjs.com/package/@grafana/ui is at `7.5.7`)

With the next (eventual) patch release, that file is going to be updated correctly.

I'm closing this as it shouldn't cause any issue.

**Comment by Elfo404** [comment]
@Berbe I'm sorry if I somehow miscommunicated what I meant 🙏 

What I was trying to say is that that version number is being generated automatically, and it will be updated correctly during the next release. 
Updating it manually won't trigger a new release, and we can't re-release 7.5.7 anyway, that's why I closed the issue in the first place, not because it's invalid, but because it's not actionable unless you are building grafana from sources.
