### ISSUE TITLE
New funcation advice

### ISSUE THREAD

**Issue by T3fan** [grafana/grafana#34914]
1.Add chart color customization function
  many chart plugins can’t change color (such as: Graph)

2.Add charts folder function (like Metabase)
   Many charts invoked by different Dashboards, but it can’t create charts folder, a lot of repetitive work. 

3.Add a Sharing privilege management function
   Many Dashboards need to show to anonymous users,  so they can view anonymous privilege Dashboards and not need to login.

4.Add a function, disable viewers or anonymous users to inspect data function
  Data Security (very important).

5.Add a global switch, enable or disable zoom chart by mouse.
  Not everyone needs zoom chart.

6.Add a default time range button on chart, chart will renew to default time range if click it.
  quickly switch chart to default time range.

7.About Absolute time range, add two calendars to set FROM time and TO time separately, 
  It usual causes interference when the set time range exceeds years.

8.Add PDF file export function, such as: export Dashboard and Dashboard folder to PDF files(like Tableau).
 Batch generate PDF report.

**Comment by Elfo404** [comment]
Hi @T3fan could you please follow the issue template for feature requests describing what you would like to be added and your use case?
Also please, open a single issue per feature request, It's really hard to keep track of different feature requests otherwise.

Closing this one in the meantime, looking forward to seeing the new ones

**Comment by torkelo** [comment]
Many of these already exist, time picker has separate from and to
