### ISSUE TITLE
Log scale for histogram x-axis

### ISSUE THREAD

**Issue by Spencer-Comin** [grafana/grafana#35002]
**What would you like to be added**:

The graph visualization, when the x-axis is in histogram mode, could have an option to have a logarithmic scale, similar to the y-axis.

![image](https://user-images.githubusercontent.com/52704940/120220879-b5bd5100-c1fa-11eb-9138-986d773422ac.png)

**Why is this needed**:

There is currently no way to show a logarithmic histogram, and it seems more appropriate that it be implemented as a modification to the built-in histogram rather than as a third-party plugin.

**Comment by leeoniya** [comment]
FYI, the histogram mode in the Graph panel (and the panel itself) is deprecated in favor of the new dedicated Histogram panel.

AFAIK, log histograms are fairly uncommon, so i'm not sure it makes sense to support this natively, as they're often awkward to interpret, since they effectively exaggerate the filled areas of the bins.

we discussed whether log histograms are something worth supporting in the core, but have left the question open for now.

e.g.:

![O_6](https://user-images.githubusercontent.com/43234/120222462-97a91e00-c205-11eb-8005-0ea7d29831fa.png)

**Comment by zoltanbedi** [comment]
Hi @Spencer-Comin as Leon said the graph panel is deprecated. Please try to use the new histogram panel. Thank you

**Comment by leeoniya** [comment]
let's leave this open till we figure out what we wanna do

**Comment by Spencer-Comin** [comment]
The use case I am encountering for log histograms is in reporting IO size distribution, where size is generally shown logarithmically (e.g. 0-1kB, 1-2kB, 2-4kB, 4-8kB, etc.), at least in my experience.

**Comment by leeoniya** [comment]
for this use case it seems more appropriate to run some kind of log histogram transform on the raw data (assuming such a transform is made available) and then using it in a BarChart panel with uniform bar widths and text labels (e.g. 0-1kB, 1-2kB, 2-4kB, 4-8kB, etc.)?

**Comment by Spencer-Comin** [comment]
This tends to get a bit noisy once the number of buckets exceeds 8 or so. Also the bucket size is rather rigid with this approach. It would be nice to have a histogram where the bucket size and count adapt dynamically to the size of the panel, though this may already be possible with some transform I don't know of yet

**Comment by bruvik** [comment]
> FYI, the histogram mode in the Graph panel (and the panel itself) is deprecated in favor of the new dedicated Histogram panel.

What is this new histogram panel? I can only find references to an old deprecated histogram panel (supporting grafana 4.0)

**Comment by leeoniya** [comment]
https://github.com/grafana/grafana/pull/33752

it's available since 8.0 beta releases since https://github.com/grafana/grafana/pull/34246

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
