### ISSUE TITLE
Logs panel: specify field selection

### ISSUE THREAD

**Issue by mieliespoor** [grafana/grafana#35044]
**What would you like to be added**:
On the logs panel it should be possible to select which fields from the log item is being shown. Sometimes, the full log message is not needed as it doesn't make sense to show all that information on a dashboard.

**Why is this needed**:
We have a query showing Cloudwatch Log data and a query similar to:

```
fields @timestamp, Level, Properties.CorrelationId, MessageTemplate
| sort @timestamp desc
| limit 20
```

When running the same query in Grafana, it will only show the data from the Level field and nothing else. The expectation is that we see the data for all the fields listed in the query.

**Comment by awsiv** [comment]
Yes please! :)

**Comment by aocenas** [comment]
I think this use case would make more sense with table panel.

Also one thing you can use is Toggle detected fields when in explore, see: https://grafana.com/docs/grafana/latest/explore/logs-integration/. 

Do you want to use this in dashboards? Is there a reason you want to use logs panel instead of table panel?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
