### ISSUE TITLE
Histogram: Bucket offset not used / no effect

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#35240]
I cannot see this being used in the code and cannot see any effect after changing it's value.

**Comment by leeoniya** [comment]
it's definitely used: https://github.com/grafana/grafana/blob/5f6c172b5aa039708463a8b666afa84bf904eae1/packages/grafana-data/src/transformations/transformers/histogram.ts#L171

though it requires specific conditions for the effect to be meaningful and visible.

the bucket offset should to be an equal divisor of the bucket size. it has the effect of shifting the aggregation window from one that is 0-based, e.g. bucket 5 offset 0: (0-5, 5-10, 10-15) to one that is offset e.g. bucket 5 offset 2: (2-7, 7-12, 12-17). if the offset is equal to the bucket size or a multiple of it, it will have no effect because it just "overflows" around again. so in the above example for the bucket size of 5. an offset of 8 would be equivalent of an offset of 3 and offset of 10 is the same as 0 offset.


https://user-images.githubusercontent.com/43234/120800376-7a29cc00-c505-11eb-9984-07b73f425242.mp4

**Comment by leeoniya** [comment]
we can maybe do a `showIf` to hide this setting when bucketSize is auto-determined (and effectively hidden from the user)

**Comment by torkelo** [comment]
@leeoniya yea, the auto bucket size could also be made much smaller, I always have to adjust it to get more than 5-6 bars
