### ISSUE TITLE
Time series panel: Series blurry when resizing page

### ISSUE THREAD

**Issue by uhthomas** [grafana/grafana#35301]
**What happened**:

The new time series is blurry when resizing the page.

**What you expected to happen**:

The visualization should not be blurry.

**How to reproduce it (as minimally and precisely as possible)**:

Load a dashboard and set your zoom to 50%, reload the page and reset it to 100%. The visualization will be blurry.

![image](https://user-images.githubusercontent.com/9749173/120926570-5b7a2f80-c6d5-11eb-8f5f-6f0b0075589f.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0-beta3
- Data source type & version: (new) Time Series
- OS Grafana is installed on: Kubernetes
- User OS & Browser: Windows 10 Pro, Chrome
- Grafana plugins: N/A
- Others: N/a

**Comment by torkelo** [comment]
This could be because of devicePixelRatio not updating or being cached.

**Comment by torkelo** [comment]
thoughts @leeoniya ? not sure we need to fix this, seems like an edge case

**Comment by uhthomas** [comment]
For me, it's not an edge case. I often zoom out to fit more data in for a screenshot or just to get a better overview.

**Comment by leeoniya** [comment]
this boils down to being able to detect changes to `window.devicePixelRatio`, for which there isn't a built-in DOM event or API. it can kind of be done with a mediaQueryListener hack [1], though.

does Grafana have something in place that can detect this already?

after hooking into whatever mechanism can detect this (directly or indirectly), we can re-init the charts.

[1] https://stackoverflow.com/questions/28905420/window-devicepixelratio-change-listener

**Comment by dprokop** [comment]
> does Grafana have something in place that can detect this already?

nope, none that I know of

**Comment by leeoniya** [comment]
does this sound like something that can/should be part of vizlayout?

**Comment by leeoniya** [comment]
i might be able to get this working without chart re-init. uPlot would have to just update the chart canvas size attrs, i think.

will try today.

**Comment by dprokop** [comment]
@leeoniya I wonder if this should not be part of uPlot core in the end, wdyt? I mean this behaviour ain't Grafana specific and I can imagine other uPlot consumers complaining about similar issue.

**Comment by torkelo** [comment]
Grafana does use devicePixelRatio for a bunch fo things (measuring text widths etc), and those are catched, so changing devicePixelRatio would have to invalidate the text measurement cache as well

**Comment by torkelo** [comment]
@leeoniya I view this as a pretty low prio issue, there are many many more important things to work on :)

**Comment by leeoniya** [comment]
this turned out to be pretty easy to get working well. uPlot now registers and dynamically updates a global MediaQueryList change listener which emits a custom `dppxchange` event that can be caught via `window.addEventListener("dppxchange", e => {})`.

every uPlot instance now listens for this event and internally recalculates all font and canvas metrics. the result is crisp plots after browser zooming on desktop. unfortunately, it doesn't look like dppx media queries fire during pinch zooming in mobile browsers :(

as @torkelo points out, we also need to invalidate some other caches on the Grafana side, but the next uPlot update will get us ~85% of the way there. try the results here: https://leeoniya.github.io/uPlot/demos/grid-over-series.html
