### ISSUE TITLE
Hotkeys: [Shift] + [?] not working to show help if keyboard language in windows is german

### ISSUE THREAD

**Issue by FireEmerald** [grafana/grafana#35372]
**Actual content:**
> "Press Shift + `?` on your keyboard to display all keyboard shortcuts available (...) in grafana"

**Issue:**
Pressing `Shift` + `?` does **not** open anything if keyboard layout is set to German on windows in chrome.
Perhaps it's because the `?` is on another position see [this image](https://en.wikipedia.org/wiki/German_keyboard_layout#/media/File:KB_Germany.svg).

![layout](https://user-images.githubusercontent.com/1107939/123043072-10139100-d3f8-11eb-9419-fc12d8e93c4d.png)
[German keyboard layout "T1" according to DIN 2137-1:2012-06]

**Further info:**
The shortcuts are viewable via:

![shortcuts](https://user-images.githubusercontent.com/1107939/121182135-13891300-c863-11eb-9140-6bcb7a557b73.png)

**Environment:**
- Windows 10
- Grafana v8.0.3
- Chrome 91.0.4472.114

**Comment by achatterjee-grafana** [comment]
Hi @FireEmerald, I tried Shift+? and it worked for me, I am on a mac. I am wondering if you are on a different operating system and the behavior is potentially different?

**Comment by oddlittlebird** [comment]
I don't have a 7.5.7 version handy, but it's working in Grafana 8.0 on Windows with Chrome.

@FireEmerald, could you check your popup permissions in your browser? It's possible those are blocking it.

It would help us to troubleshoot if you could share your OS and browser as well.

**Comment by FireEmerald** [comment]
Okay, this is not a docu issue, it's a bug. The shortcut only works when the keyboard layout in windows is set to English but my default layout is German.

**Comment by achatterjee-grafana** [comment]
Removed the docs type from this issue.

**Comment by torkelo** [comment]
Something wrong with https://github.com/grafana/grafana/blob/main/public/app/core/services/keybindingSrv.ts#L40  
Anyone who want to help troubleshoot this?

**Comment by ashharrison90** [comment]
i had a quick look. works fine on mac with german keyboard.

booted up my windows pc, and it indeed does not work on windows. 
think it's actually a problem with `mousetrap`, see https://github.com/ccampbell/mousetrap/blob/master/mousetrap.js#L400

i wonder if it's worth raising an issue on `mousetrap` instead, or another option is to improve our docs to list the alternative keyboard shortcut (`h`) which does work on all platforms. any thoughts @grafana/docs-squad ?

**Comment by achatterjee-grafana** [comment]
I am open to updating the docs with the alternate keyboard shortcut. I will open a PR for this.

**Comment by ashharrison90** [comment]
have created a pen here: https://codepen.io/ashharrison90/pen/PoprEMK
i'll raise an issue on `mousetrap` and see what they think 👍

**Comment by ashharrison90** [comment]
ok, ignore what i said above about it being something to do with `mousetrap` 😂 

i've just tried the codepen i linked above on my windows machine and it works fine.
so it's something in grafana that's swallowing the event before it gets to mousetrap 🤔

**Comment by ashharrison90** [comment]
ok figured out why the codepen wasn't reproducing the problem. it's to do with the fact that we're listening to the `keydown` event [here](https://github.com/grafana/grafana/blob/main/public/app/core/services/keybindingSrv.ts#L158). if i add that to the codepen it now reproduces the problem.

so we could just remove explicitly listening to the `keydown` event and use whatever `mousetrap` uses by default, presumably `keypress`. but this change was added for a reason, to support internationalised keybindings as part of https://github.com/grafana/grafana/pull/8311. 

i'm not an expert, but i think probably the correct way to support internationalised keybindings would be to explicitly add them instead. `p r` makes sense to `r`emove a `p`anel in english, but other languages might need some completely different key combination.

since there's another key binding that works, my inclination is to leave the underlying problem for now and tackle it as part of the wider effort on internationalisation.
