### ISSUE TITLE
Upgrade Cypress

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#35420]
We are still running on a 6.x version of Cypress so we should upgrade to latest as there are a lot of fixes!

**Comment by hugohaggmark** [comment]
@vickyyyyyyy @scottlepp @sunker pinging you guys if you're in the process of doing the same

**Comment by hugohaggmark** [comment]
To be crystal clear, I've created this issue because I'm going to start working on this tomorrow.

**Comment by vickyyyyyyy** [comment]
Thanks for letting us know 👍 

Currently, we've been seeing issues with our enterprise plugins' e2e tests and when we tried to update Cypress from 6.4.0 and 7.5.0, we've seen two issues where:

(1) An update to `tslib` is required
(2) This issue came up: https://github.com/cypress-io/cypress/issues/8759

Not sure if these were just isolated to our enterprise plugins but thought we'd mention it here as a heads up
