### ISSUE TITLE
MySQL: Not possible to use string/varchar as time in Grafana v8.0.0

### ISSUE THREAD

**Issue by maemigh** [grafana/grafana#35484]
**What happened**:
I'm not sure if this is a bug or if I need to change the query. However, this worked on versions prior to 8.0.0.

This query fails:
`SELECT distinct from_unixtime(time, "%Y-%m-%d") as time, count(*) as "NonCritical" FROM nagios_errors.nagios_errors_view WHERE $__unixEpochFilter(Time) AND Error != 'Recovery' AND Message LIKE "%PROBLEM%" AND Message LIKE '%Message sent with a severity of NonCritical%' group by from_unixtime(time, "%Y-%m-%d") order by Time asc`

With the error message:
`db convert time column failed: column type "[]*string" is not convertible to time.Time`

**What you expected to happen**:
This query worked on previous versions

**How to reproduce it (as minimally and precisely as possible)**:
Use `from_unixtime(time, "%Y-%m-%d") as time` as part of an SQL query

**Environment**:
- Grafana version: 8.0.0

**Comment by marefr** [comment]
I didn't know we supported strings as time. Not sure we can/want to support that on Grafana v8 because it would add additional complexity. What's your use case for this, resetting the time to 00:00:00? Wonder if you instead should use the [`$__timeGroup macro`](https://grafana.com/docs/grafana/latest/datasources/mysql/#macros) with a 24h interval - have you tried that?

I think the workaround here is simply something like this `select STR_TO_DATE(from_unixtime(time, "%Y-%m-%d")) as time`. Have you tried that?

**Comment by maemigh** [comment]
The workaround didn't seem to work for me, but using the $__unixEpochGroup macro fixed the problem.

**Comment by marefr** [comment]
Thanks. I'll close this for now, but we'll keep an eye open for others having this same problem and in case it gets a lot of traction I'll reopen this.
