### ISSUE TITLE
New ngalert-based alerts constantly flap from resolved to active to their Contact Points

### ISSUE THREAD

**Issue by mikeyk** [grafana/grafana#35539]
**What happened**:
We migrated to Grafana 8.0.0 and the new alerting system and since then, any alert that fires (and remains in an alerting condition) will notify its Contact Points of state changes that _Resolve_ and then _Alert_ continuously, every time the alert check runs. This leads to incidents being created/closed every N minutes in OpsGenie, or sequences of Resolved/Firing messages being posted to Slack.

When looking at the logs, it seems that these alerts are being resolved and then ~3 seconds later set to alerting once more.

One example (led to a Resolved message in Slack/OpsGenie)

![image](https://user-images.githubusercontent.com/21233/121612972-63f1a380-ca10-11eb-92a4-23e9bda5f485.png)

Another example (led to an Alerting message in Slack/OpsGenie, on an alert that had actually been alerting for 6 hours already and had posted many pairs of Resolved/Firing messages):

![image](https://user-images.githubusercontent.com/21233/121613242-eaa68080-ca10-11eb-9093-ff2638ce0d01.png)

These alerts are new `ngalert` alerts, running off an `InfluxDB` datasource. They are set up as follows:
![image](https://user-images.githubusercontent.com/21233/121612681-b8485380-ca0f-11eb-9173-674cf90b863a.png)

![image](https://user-images.githubusercontent.com/21233/121612697-c1d1bb80-ca0f-11eb-8db7-f6cb0eb7d884.png)

Throughout all of these flaps from resolved/active, the state in the Alerting UI is actually accurate and doesn't flap:

![image](https://user-images.githubusercontent.com/21233/121612738-d3b35e80-ca0f-11eb-9a1a-8f30b1179f82.png)

**What you expected to happen**:

Once an alert is triggered, until it actually resolves, no RESOLVE message is sent to any of the Contact Points. 

**How to reproduce it (as minimally and precisely as possible)**:

We can reproduce this by creating a new alert in the new system and having it trigger and not resolve. Every N minutes it will send a RESOLVE/ACTIVE pair to all contact points.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0
- Data source type & version: InfluxDB (built-in)
- OS Grafana is installed on: Ubuntu 20.04 using Docker
- User OS & Browser: Edge on Mac
- Grafana plugins: none
- Others: `ngalert` enabled

**Comment by dsiperek-vendavo** [comment]
We are having the same issue! 
Our Environment:
Grafana version: 8.0.0 (HA)
Data source type & version: Prometheus and Postgresql
OS Grafana is installed on: Azure AKS, official Grafana
User OS & Browser: not relevant
Grafana plugins: none
Others: ngalert enabled

**Comment by davidmparrott** [comment]
@dsiperek-vendavo What are your evaluation settings for the alert rule where you're also seeing this? Specifically wondering about what you have `Evaluate Every` and `For` set to.

**Comment by jdmaloney** [comment]
@davidmparrott We're seeing this bug also.  Ours are set for Evaluate Every 1 minute, for 2 minutes.  This is leading to us getting alerts in our Slack channel every 2 minutes.  Metrics are from an InfluxDB data source, let me know if any additional information you want.

**Comment by davidmparrott** [comment]
@jdmaloney I don't think it's likely that you are seeing the same issue as @mikeyk given the evaluation configuration you mentioned. What was happening there is by having the evaluation only happening every 5 minutes, and having the duration set to 1 minute, EndsAt was being set based on the For duration that was lower than the evaluatino frequency, so the Alertmanager would send a resolved notification, thinking that everything was fine and the alert source had gone away. 

The linked PR changes the calculation of EndsAt to accommodate this configuration by checking if the For duration is less than the IntervalSeconds (evaluation timer) and, if so, setting EndsAt to be twice the IntervalSeconds, allowing for some jitter in evaluation time. Because you're using the more standard evaluation configuration where your For duration is larger than IntervalSeconds, I wouldn't expect that you're encountering this issue but it's worth verifying none the less.
