### ISSUE TITLE
grafana graph bars uneven

### ISSUE THREAD

**Issue by ThierryHenry1994** [grafana/grafana#35542]
**What happened**:
I wanted to show the number and status of Redmine bugs per day through Grafana.My X-axis is time, and as time goes on, my bar graph is sometimes uneven, and I don't know what's going on.Does anyone know how to do to make my bar graph even
![image](https://user-images.githubusercontent.com/32047768/121636630-c0110200-caba-11eb-84f0-04bd600205a6.png)

**What you expected to happen**:
I want even bars
**How to reproduce it (as minimally and precisely as possible)**:
this is my sql
``` mysql
SELECT
  $__timeGroup(created_on, "1400m") AS time_sec,
  count(*) as value,
  is2.name
FROM issues i 
left join issue_statuses is2  on is2.id = i.status_id 
WHERE
  $__timeFilter(created_on) and to_days(now())-to_days(created_on)<7 
group by time_sec,is2.name
```

**Environment**:
- Grafana version:v7.5.7
- Data source type & version:mysql
- OS Grafana is installed on:windows
- User OS & Browser:firefox

**Comment by torkelo** [comment]
The graph time axis follows the time range, so if the last data point represents a bar that goes outside the time range it will be cut. There is no option to change this behavior. The new bar chart will support categorical x but it does not yet support your use case 100%

**Comment by leeoniya** [comment]
> The new bar chart will support categorical x but it does not yet support your use case 100%

the new barchart is unlikely to support this use case since its bar positions are not determined by time and there is no logical way to mix the two types.

try using the new Time series panel. it should position all bars on-center instead of left-edge. you will see half a bar width on each graph edge.

the way to make this closer to what you're asking is for the graph to show a larger time range than the query range and hope the extra time allowance matches the half a bar width to either side, which would be tricky because the bar widths are computed from the available space and not vice-versa.
