### ISSUE TITLE
TimeSeries: Hide null & and hide zero series 

### ISSUE THREAD

**Issue by krocans** [grafana/grafana#35592]
Time series panel although it contains visual enhancements lacks what I think important features of old Graph panel:

- hide series with 0/null values
- sort tooltip entries by value.

It would be nice to have those features in the Time series panel especially if it's going to replace Graph panel in future releases.

**Comment by torkelo** [comment]
Question is if this should be implemented as a transform to filter out fields & series or as field override matcher (and then use the hide in option that already exists)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
