### ISSUE TITLE
Shared tooltip in timeline panel

### ISSUE THREAD

**Issue by DmitrySidorow** [grafana/grafana#35683]
Hi! Thanks for the new timeline panel, it's a great replacement for the discrete panel!

Are there any plans to introduce a shared tooltip there?

**Why is this needed**:
It would be very convenient to compare discrete events with graphs

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
