### ISSUE TITLE
GraphNG: Plot reinitializes unnecessarily because of thresholdStyle 

### ISSUE THREAD

**Issue by srw2ho** [grafana/grafana#35848]
**What happened**: GraphNG reconfig update after each query request in PanelQueryRunner.ts

**What you expected to happen**: only update after configuration changing, -> improvement Performance of uPlot

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0-beta2
- Data source type & version: 
- OS Grafana is installed on: wsl2/docker
- User OS & Browser: chrome
- Grafana plugins: TimeSeries
- Others:

PanelQueryRunner.ts function   getData
```
 getData(options: GetDataOptions): Observable<PanelData> {
......
         if (!sameStructure) {

             sameStructure = compareArrayValues(lastData, processedData.series, **compareDataFrameStructures);
        }
        if (!sameStructure) {
          for each new frame structureRev will be incremented and this results into GraphNG Reconfig
          **structureRev++;**
        }

```
### shallowCompare returns always with false in case of comparing "thresholdsStyle-key", is the last key in key-array

```
export function shallowCompare<T extends {}>(a: T, b: T, cmp: Cmp = defaultCmp) {
  if (a === b) {
    return true;
  }

  const aKeys = Object.keys(a);
  const bKeys = Object.keys(b);

  if (aKeys.length !== bKeys.length) {
    return false;
  }

  for (let key of aKeys) {

**Key: thresholdsStyle** come always with false back
    //@ts-ignore
    **if (!cmp(a[key], b[key])) {**
      return false;
    }
  }

  return true;
}

```

**Comment by dsotirakis** [comment]
Hello @srw2ho, thanks for raising this. Mind creating a PR for that since it seems that you already had a look in the code? Didn't quite understand your thought.

**Comment by srw2ho** [comment]
Yes, I am not good at explaining.
I have debugged version 8.0.0-beta2. I noticed that the GraphNG component is always reconfigured after each new 
 Data request.

**Comment by dprokop** [comment]
@srw2ho thanks for reporting - indeed, the `thresholdsStyle` property unnecessarily invalidates the config. Interestengly enough, the hideFrom property, which is an object property too, does not invalidate the config, which means that these two properties must be treated differently somewhere upstream. Investigating.

**Comment by srw2ho** [comment]
Yes, it is only the thresholdsStyle object, whereas other objects do not cause any problems.

**Comment by torkelo** [comment]
Wonder if this is why https://github.com/grafana/grafana/pull/35910  just worked now (I get new series.color in uplot config for every data update)

**Comment by dprokop** [comment]
@torkelo I think this is not working because of the path properties that the thresholdStyles is defined under https://github.com/grafana/grafana/blob/7ff26bdfae25c19acb6cd6210509d0de22f43d1c/public/app/plugins/panel/timeseries/config.ts#L181

Since the mode is defined as string, rather than object, a bew object is created (https://github.com/grafana/grafana/blob/83f62c191263dfb52eabb65fe7e7aa3027d8bbc0/packages/grafana-data/src/field/fieldOverrides.ts#L299) every time defaults are applied, rather than relying on the reference to object from within https://github.com/grafana/grafana/blob/f4a40a4d85f2f20d757296343e6d43e8bc70cd0f/packages/grafana-ui/src/components/uPlot/config.ts#L287

This is more of a general problem of how we configure the options, rather than a particular bug related to field config or uPlot. 
I don't think there is an easy solution to that. We can either try to figure out a different way compared to using `set` in https://github.com/grafana/grafana/blob/83f62c191263dfb52eabb65fe7e7aa3027d8bbc0/packages/grafana-data/src/field/fieldOverrides.ts#L299, or do a deep comparison in the structure change detection(I want to avoid that).As of now I'm about to the thresholdStyle config to a custom editor to resolve this issue.
