### ISSUE TITLE
State timeline panel: Pagination or scroll view support

### ISSUE THREAD

**Issue by ashleyjlive** [grafana/grafana#35843]
**What would you like to be added**:
Add pagination **or** scroll view support to state timeline panel.

**Why is this needed**:
State timeline has the potential to be a very powerful and valuable tool for monitoring uptime of a large number of nodes. In my initial testing I found that for a high number rows the view tends to squish and fit all rows into the fixed view - which makes it very hard if not impossible to read [1]. It would be better to either:
• Have pagination (page numbers, etc)
• Allow overflow and provide a scroll view within the window rather than trying to fit everything in the window

My preference is for a scroll view as that fits more with the style of what the graph and time series does when their legends contain more data than what can fit within the window.

[1]
![image](https://user-images.githubusercontent.com/9400511/122309256-5331b800-cf51-11eb-8417-b74c7e5dc302.png)

**Comment by trollvottel** [comment]
+1

**Comment by trollvottel** [comment]
![grafik](https://user-images.githubusercontent.com/9528457/122409568-868d3a80-cf83-11eb-9e3d-22d32156a9ab.png)

Looks quite useless, doesn't it?

**Comment by ryantxu** [comment]
In the discrete panel -- we configured a row height and then that scrolled within the panel.  We could consider something like that

![Peek 2021-06-17 10-29](https://user-images.githubusercontent.com/705951/122445957-f507d380-cf56-11eb-8faf-0914a3555e3f.gif)

**Comment by ashleyjlive** [comment]
> +1
> 
> Without this, the classic 3rdparty 'discrete' panel is still the preference. I'd even call this a bug, because usually all panels may scroll internally.

Yeah agreed. I wouldn't really call this a feature request.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
