### ISSUE TITLE
PostgreSQL: I want to be able to specify the timezone easily.

### ISSUE THREAD

**Issue by atabisha** [grafana/grafana#35852]
**What would you like to be added**:

When trying to retrieve daily data in PostgreSQL, the data is aggregated between 00:00 and 00:00 UTC, and the result is not correct because it is not a daily aggregation in the original TZ.

The query I used may be wrong.
It is hard for a beginner to get data by specifying the time zone in PostgreSQL, so I would like to use Query builder to specify it easily like InfluxQL.

The following is what I write as Query builder.
![image](https://user-images.githubusercontent.com/82935824/122350918-9c512e80-cf88-11eb-8d2b-efb846a54f18.png)

**Comment by marefr** [comment]
The Postgres data source was built with simplicity in mind why historically if you haven't stored your timestamps in a column with a data type where the timezone is included it's up to the user to write such a query since Grafana cannot know what timezone is intended other than UTC. If you have an idea, please specify how you would write the query manually compared to your query above to resolve your timezone issue.

We don't intend to work on resolving this hence the "priority/awaiting-more-evidence" label. Will leave it open awaiting comments/upvotes from others that are interested in this feature.

**Comment by codeincarnate** [comment]
There hasn't really been any movement on this for nearly nine months. Agree with @marefr that unless timezone data is included already it's difficult to tell where that would be located (and thus tricky to add to the query builder). Going to close this for now, but if there's a pressing need please feel free to re-open.
