### ISSUE TITLE
Threshold editor not exported from @grafana/ui

### ISSUE THREAD

**Issue by Watermeloune** [grafana/grafana#35854]
Hello! ThresholdEditor isn't exported in packages/grafana-ui/src/components/index.ts
So it can't be imported from @grafana/ui
Could it be possible to add the export in future updates?

Thanks!

**Comment by torkelo** [comment]
this is by design, you can use it in a panel plugin using the field config system. 

Either by adding useFieldConfig() to your panel,

https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/stat/module.tsx#L13

you can also access it via standardEditorsRegistry with the id 'thresholds'

**Comment by Watermeloune** [comment]
The problem is that I have a specific use in the Editor and I need to import the ThresholdEditor for that.

And even if this is by design, I don't think it would be outrageous to make it importable.
