### ISSUE TITLE
Error with marshalling from stackdriver

### ISSUE THREAD

**Issue by eruizgar91** [grafana/grafana#35948]
**What happened**:
Importing a query that is working in stackdriver the following error is occurring.

```failed to unmarshal query response: json: cannot unmarshal string into Go struct field .timeSeriesData.labelValues.int64Value of type int64```

![image](https://user-images.githubusercontent.com/3496824/122561194-daf6ef80-d041-11eb-9e5a-dea1c0ddf81e.png)

**What you expected to happen**:
See the dashboard metric.

**How to reproduce it (as minimally and precisely as possible)**:
It's happening only with a particular query. I was able to import other MQL queries without problems.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.5.7 (91de51771c)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by sarahzinger** [comment]
@eruizgar91 Thanks for reporting this bug! 

I'm trying to figure out how to recreate this issue and am having some trouble. I'm wondering do you experience the same issue when you use the query builder (in this case you'd click the button that says "Switch to builder") and then select from the UI what you're hoping to see. It might be a situation where our query editor is not formatting our data properly but the builder might? It could help narrow down where the problem is and possibly be a temporary work around until the bug is fixed.

**Comment by eruizgar91** [comment]
When I try to use the query builder, it looks like the drop button has some kind of bug, because the elements that is showing is limited. Trying to find logging but the list don't go deeper than the `g` letter.

**Comment by TomBAMU** [comment]
we are actually observing the same issue. I could narrow it down to a "group by" issue with the MQL builder.

@sarahzinger the following query could only be used in the MQL query editor since the builder is not offering internal loadbalancers as  queries

Query 1: (leads to the error)
```
fetch internal_http_lb_rule
| metric 'loadbalancing.googleapis.com/https/internal/request_count'
| align rate(1m)
| every 1m
| group_by [metric.response_code, resource.forwarding_rule_name],
    [value_request_count_aggregate: sum(value.request_count)]
```
Query 2 - works totally fine
```
fetch internal_http_lb_rule
| metric 'loadbalancing.googleapis.com/https/internal/request_count'
| align rate(1m)
| every 1m
| group_by [resource.forwarding_rule_name], [value_request_count_aggregate: sum(value.request_count)]
```

**Comment by bspellmeyer** [comment]
https://github.com/grafana/grafana/blob/46f922fe1af1869e2e84962b149899569c04ed8e/pkg/tsdb/cloudmonitoring/types.go#L121

The JSON field `timeSeriesData.labelValues[].int64Value` is of type `string`.

Example query using the resource [https_lb_rule](https://cloud.google.com/monitoring/api/resources#tag_https_lb_rule) and the metric [https/backend_request_count](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-loadbalancing):

```
fetch https_lb_rule
| metric loadbalancing.googleapis.com/https/backend_request_count
| group_by 10m, [.sum]
| top 1
```

Returns the following response:

```json
{
  "timeSeriesDescriptor": {
    "labelDescriptors": [
      {
        "key": "metric.response_code",
        "valueType": "INT64"
      },
      {
        "key": "metric.response_code_class",
        "valueType": "INT64"
      }
    ],
    "pointDescriptors": [
      {
        "key": "value_backend_request_count_sum",
        "valueType": "INT64",
        "metricKind": "GAUGE",
        "unit": "1"
      }
    ]
  },
  "timeSeriesData": [
    {
      "labelValues": [
        {
          "int64Value": "200"
        },
        {
          "int64Value": "200"
        }
      ]
    }
  ]
}
```
