### ISSUE TITLE
PieChart: Support combining smaller slices into an other or rest category  

### ISSUE THREAD

**Issue by jdmaloney** [grafana/grafana#35960]
**What would you like to be added**:
- Ability to combine values below X%, eg. in v1 pie chart values below say 3% could be combined into a group that has a custom name
- Ability to sort the legend by any of the columns, right now it is just by name column alphabetical

**Why is this needed**:
Feature parity with v1.  Combining small values makes charts more easy to read and understand, sorting also makes it easier to see highest value components.  

I did not see these options as of v8.0.3, but please let me know if I'm somehow missing them.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
