### ISSUE TITLE
Series display names lost

### ISSUE THREAD

**Issue by Kallb123** [grafana/grafana#35964]
**What happened**:
Within the "Standard Options"->"Display Name" setting I have been using `${__field.labels.series_name}` for a while. Within the Flux query, I use `  |> set(key: "series_name", value: "Power")` which meant that the series was then called "Power". This is no longer the case and all the series are being displayed as "${__field.labels.series_name}".

**What you expected to happen**:
I expected the display name of the series to still be dynamic based upon the specified field.

**How to reproduce it (as minimally and precisely as possible)**:
Create a Flux query, include the set function and try to use it as a series display name.

**Anything else we need to know?**:
Reverting back to 7.5.8 fixes the issue and display names take effect again.

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: InfluxDB 2 Flux
- OS Grafana is installed on: Docker (Ubuntu Host)
- User OS & Browser: Windows 10 Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Can you open query inspector and check the JSON tab / then select DataFrame structure ? 

Can you paste that herE?

**Comment by gabor** [comment]
@Kallb123 i have a guess as what might be the problem:
when you use `|> set(key: "series_name", value: "Power")` a new column is created. whether it is a `field` or a `tag`, depends it's `group` attribute. `group=true` means it is a tag, `group=false` means it is data. i assume the newly created column is marked as data, not as a tag, and that's why it does not work in grafana8. (in grafana7.x we ignored this difference and assumed it is a tag, that's why it worked in grafana7.x). you will have to use the `group()` function to mark this newly created column as tag (group=true). something like `|>group(columns:[........ , "series_name"])` (unfortunately i do not know how to simply mark a single column as group, you always have to name all the group-columns. to find out which columns are already in the group, in influxdb-ui, in explore mode, add the query and [submit] and use the `view raw data` option.  check the first row you see there. this is the group-thing. check which ones are already `true`. those must be named in the `|> group()` call, and add `series_name` to it). another option is to use `|> drop()` to just drop every column you don't need.

i hope this fixes your problem. if not, we will need to see the raw csv output from your flux query. this is how you get it:
- influxdb-ui, explore-mode, when you enter your query and [submit] it, there is a download-csv button below the visualization. click it, download the csv
- please check the csv and make sure you remove every private/secret info
- upload the csv here

thanks!

**Comment by Kallb123** [comment]
@gabor you were exactly right. I've just re-upgraded to v8 (Docker makes it so easy 😅 ) and done the "group" stuff. I didn't go the "drop" route as I might use fields in future.

For me, using data from Home Assistant that's pushed to InfluxDB, I had to use the following commands:
```
  |> set(key: "series_name", value: "My Measurement")
  |> group(columns: ["_start", "_stop", "_field", "_measurement", "domain", "entity_id", "friendly_name", "series_name"])
```
This kept the `group=true` status on all the ones that had it already whilst adding it to `series_name`.
Thank you very much for your help, I'm now comfy on the latest version!

One bit of relevant feedback, it would be super useful to be able to reference "series" by their Grafana label (Server and PiHole in the image below). I know that each one of these can contain multiple series, so it might be complicated, but the logic required to set a display name is a little cumbersome.
![image](https://user-images.githubusercontent.com/1054734/123163730-f27f0f80-d469-11eb-9bf1-1df355f2968f.png)
Unless that's already a thing 😅

**Comment by gabor** [comment]
@Kallb123 i'm glad it worked!

about the usage of the series-names, i'm not sure what is the easiest way to achieve it currently. could you create a separate feature-request issue for it perhaps? (worst case we find out that it is already possible somehow 😄 )

**Comment by Kallb123** [comment]
> @Kallb123 i'm glad it worked!
> 
> about the usage of the series-names, i'm not sure what is the easiest way to achieve it currently. could you create a separate feature-request issue for it perhaps? (worst case we find out that it is already possible somehow 😄 )

Done  #36413
