### ISSUE TITLE
table panel: colorize cell value based on regex pattern match

### ISSUE THREAD

**Issue by patjlm** [grafana/grafana#3601]
In a table panel, it would be nice to colorize a string cell/text based on regex pattern matches.
For example I have different status of application deployments (started, finished, failed, rollback...) and would like to highlight those status with different colors.

**Comment by bergquist** [comment]
#3608

**Comment by mattpoel** [comment]
Would also love to see this feature :+1:

**Comment by MartynKeigher** [comment]
Pardon my ignorance here guys, but has this feature request made it into current versions of Grafana yet??

I am running an older version of Grafana (as I need a MySQL datasource, - _ running v3.1.0 to be precise_ - and was curious if newer version had this functionality yet! Thanks. 

PS: I know there is a version in alpha now that will support MySQL as a datasource, so once that's the stable is released, i'll upgrade to it.

**Comment by torkelo** [comment]
the open status means not implemented

**Comment by MartynKeigher** [comment]
Well yeah, and i figured as much, but... with it being quite some time ago that this was asked and people seemed to like it... I was just curious on the current state of it! Is it gonna happen at all? etc...

**Comment by daniellee** [comment]
@MartynKeigher we are not working on it right now. Here is our current [Roadmap](https://github.com/grafana/grafana/blob/master/ROADMAP.md).

**Comment by wei-hai** [comment]
+1

**Comment by Foxsa** [comment]
+1

**Comment by satishwin** [comment]
+1

**Comment by jameswongyou** [comment]
+1

**Comment by marefr** [comment]
While reviewing pull request #9455 which aims to solve this issue some concerns has arise regarding the solution. Our aim is to be able to merge this as soon as a good solution is decided.

With the suggested solution *Text to value mapping* are shown as optional when having a column of type *String*, see screenshot:

![image](https://user-images.githubusercontent.com/1668778/37299928-f66a3292-2624-11e8-85bc-e16f015b3dd5.png)

Right now, when adding text to value mappings they're only applied for the threshold formatting which means that the string value in column will still be untouched, but colors of cells and row can be changed.

There's a similar issue #7119 which aims to solve mapping of number/range to text (same solution as singlestat panel) which actually replaces number in cells with a string value, but does nothing with the threshold.

These two issues are very similar but at the same time not so similar since they're resulting in different end results :) I want to find a solution here that works for both scenarios, but at the same time make it easy to understand for the user what these options actually means.

The questions/concerns here are whether it's easy for a user to understand or weird that you only can change the mapping for the threshold and formatting? I think it would be a bit weird naming it *Text to value mapping* if it only changes the thresholds and taking the other issue solution into account.

**Some different suggestions on solutions here:**
1. As suggested solution but will replace text with value for both cells and threshold
2. As suggested solution but with additional option to replace text with value, including possibility to replace text in cells.
    - + Will allow to re-map text values to other text value (I guess)
    - - If replacing text with value I maybe as a user expect that this option is located when having selected type *Number* of a column?
3. Change the *Text to value mapping* section to *Replace text with value* suggested by @lucasrodcosta, excluding possibility to replace value only for threshold.
    - + Can be used for *Value to text mapping* named *Replace value with text* for #7119 and in singlestat panel.
4. Rename *Text to value mapping* to *Text to threshold value mapping*, excluding possibility to replace text in cells.
    - Makes it clearer from user perspective that this only applies to thresholds.
5. Adding the *Text to value mapping* section to the *Thresholds* section, excluding possibility to replace text in cells. 
    - + Makes it clearer from user perspective that this only applies to thresholds.
    - - Changes how threshold section works throughout rest of Grafana

 If you have any input to these suggestion feel free to comment. Your input is very valuable. Thanks

**Comment by marefr** [comment]
ping @grafana/grafana-labs-core-devs :point_up:

**Comment by marefr** [comment]
We've created a new issue, #11418, in favor of this to express the requirements needed to solve this together with several similar feature requests. By this we're hoping to find one solution for solving all (or most) of the feature requests for formatting/thresholds in panels and by that delivering a good and consistent user experience. We hope that this initiative can inspire and guide the community and contributors moving forward.

**Comment by pete00067** [comment]
![image](https://user-images.githubusercontent.com/53077624/63245864-c4d84680-c293-11e9-915f-97d0209b608d.png)
@marefr when I choose my column type to string, it only appears two options: value to text and range to text. How can I enable the text to value mapping?

**Comment by marefr** [comment]
@pete00067 you currently can't. Please refer to feature request #11418

**Comment by WilliamLHarms** [comment]
@marefr  - any update?  Should we go though our support channels?  (We paid for Grafana Enterprise)
![image](https://user-images.githubusercontent.com/37589680/64972898-161a2c80-d878-11e9-9791-cac6f25d5856.png)

**Comment by marefr** [comment]
@WilliamLHarms you're welcome to that.

**Comment by midchack** [comment]
HI Team,
I am trying to change the color of the cell to green on the below screen if the job completes before 7:00 AM if the job completes after 7:00 AM cell should change to red. i tried all the patterns and regex still not working can you please help:

![image](https://user-images.githubusercontent.com/57776100/68902084-5de8f300-0705-11ea-9641-e2e6bb9d5534.png)

**Comment by midchack** [comment]
can we color the cell with time value on column

**Comment by tkorkunckaya** [comment]
in my opinion, altering resulting values should not be grafana's job. Most of the time we are getting data from a database with a query. The query or the data source itself should be managing that. So matching string values to numeric should not result with the changing of displayed data, but only **formating of the data or the table etc**. Even there are some cases that we cannot directly manage the datasource or query so that changing displayed data may make sense, it should be done by other means like proxying the data source, scripting before inputting to grafana etc.

It may be too late, but i just bumbed into this kind of situation and was looking around if there is already a solution. I'll change how i get the data (e.g instead of getting a string column only, i'll get a numeric one also ((converted)) and use it for the trashold.

Thanks for your efforts by the way.

**Comment by midchack** [comment]
Thank you Raif.. appreciate your response \

**Comment by ssuparna2010** [comment]
What is the solution for this 3601. if i changed the type to string then colouring is not getting displayed then what is the solution

**Comment by pr1malc0de** [comment]
Can i assume coloring cells based on regex pattern is not currently planned? For my setup, if i could just use variables inside Value mappings i could have a column with Integer values matching thresholds then replace them using value mappings to a variable from a column in my data. Would this be a workaround for some people? Would need Value mappings to accept variables which they dont seem to currently though
