### ISSUE TITLE
Feature Request: Dimension_values from all or list of regions (CloudWatch)

### ISSUE THREAD

**Issue by pertu** [grafana/grafana#36036]
**What would you like to be added**:
Ability to call dimension_values() with region=ALL or with a list of regions.

**Why is this needed**:
Applications may run in multiple AWS regions and it's convenient to have single graph/variable with all the values.
For example, we get the list of all SQS queues in US-EAST-1 like that: 
```dimension_values(us-east-1,AWS/SQS,NumberOfMessagesReceived,QueueName)```.

But our application uses multiple regions.
To graph all SQS queues we duplicate variables/graphs (one for every region).

`dimension_values(*ANY_REGION*, AWS/SQS, ...,QueueName)` would simplify that.

**Comment by sunker** [comment]
Thanks for creating this issue @pertu! 

Currently, we use the [list metrics api](https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/list-metrics.html) to list dimension values. Region is not an argument in the call to this api. So in order to do this, we would need to create one new aws client for each region, and then for each client issue a new call to the list metrics api. This could potentially be slow and also expensive since you pay per request to the list metrics api. 

I'm gonna close this issue now, but feel free to re-open if the api:s change so that we can do this in a simpler way.

**Comment by justinTM** [comment]
@sunker thanks for sharing; I'm curious how you are making calls to the AWS API within grafana?

**Comment by sunker** [comment]
We're using the cloudwatch service in the [aws sdk for go](https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatch/). To list dimension values, we use the [list metrics](https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/list-metrics.html) api.
