### ISSUE TITLE
Variables: Restore the "never" refresh option

### ISSUE THREAD

**Issue by linar-jether** [grafana/grafana#36071]
**What happened**:
The `never` refresh option for dashboard variables was removed at https://github.com/grafana/grafana/pull/33533

**What you expected to happen**:
We would appreciate it if the option is restored, as it is very valuable for queries with long loading times.

**How to reproduce it (as minimally and precisely as possible)**:
Same queries are now required to be executed on dashboard load, which might significantly slow down loading, or save the variables as constants and manually perform updates (queries need to be managed externally)

**Anything else we need to know?**:
Aside from _very_ slightly increasing the dashboard's json size, there seem to be no downsides to keeping the option.

Thanks,
Linar

**Comment by AkanshaP12** [comment]
Just from API perspective, currently `https://grafanaserver:3000/api/dashboards/uid/<dashboard_uid>` returns complete JSON with templating/variable options. However, from the responses in [https://github.com/grafana/grafana/pull/33533](#33533), the main reason to remove the 'never' option is to reduce the response JSON size.

My suggestion would be to have something like verbose options in API to get options in the dashboard JSON response. So API URI could look like `https://grafanaserver:3000/api/dashboards/uid/<dashboard_uid>?verbose=true`, which returns variable options resolved in grafana. Otherwise, as Grafana API consumers we have to get SQL query from JSON and execute without knowing the data source, or connection to the data source.

**Comment by Nyan256** [comment]
For the love of everything holy, please restore the "Never" option or provide a workaround!

We have variables with tens of thousands of elements, even with local query caching it adds many seconds to page loads.

**Comment by bcavagnolo** [comment]
Ahoy. We recently upgrade our grafana to v8 and lament the disappearance of this feature. It really slow down the load of a number of our critical dashboards.

**Comment by mantydze** [comment]
Please restore "Refresh:Never" option. After Grafana 8 upgrade, multiple dashboards became unusable due to increased loading time.
