### ISSUE TITLE
FR: HealthCheck for Datasources

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3609]
TestConnection to the datasources at every 1-2 mins.

**Comment by bergquist** [comment]
This seems like an good extension to https://github.com/grafana/grafana/issues/3302

**Comment by bergquist** [comment]
This can only be done for datasources in proxymode. Which seems like nasty hack. 
What problem would this solve?

**Comment by utkarshcmu** [comment]
doing this for direct and proxy mode datasources is hacky. Having a healthcheck or an hourly ping to the datasources makes sure that setup in Grafana does not have any issues and its the datasources which has issues. This can be handy while troubleshooting Grafana and can make sure that its the datasources where the problem lies and not in Grafana.

**Comment by bergquist** [comment]
Proxy mode is also lacking any knowledge about how to validate a connection to the datasource since its the front end that know which URL to test for. I'm sorry but right now I don't see how this can make it into master. It would just be to hacky. I suggest you setup monitoring for each data source by them self and some kind of network test between the server hosting grafana and all the data sources. Might seem like a hassle but adding it to Grafana would just be to hacky :/
