### ISSUE TITLE
Notifications not getting sent when details contain spaces

### ISSUE THREAD

**Issue by dsiperek-vendavo** [grafana/grafana#36094]
**What happened**: Notifications do not get sent when you add a new details for alert with space in it. 

**What you expected to happen**: Notifications to get sent 

**How to reproduce it (as minimally and precisely as possible)**: 
Add custom detail with space in it.  See picture below!

**Anything else we need to know?:** 
![image](https://user-images.githubusercontent.com/70541548/123153634-ba9cab80-d41a-11eb-8ba2-f11732e87c4d.png)

**Environment:**
Grafana version: 8.0.3
Data source type & version: Prometheus / Thanos
OS Grafana is installed on: Azure AKS, official Grafana
User OS & Browser: not relevant
Grafana plugins: clean install
Others:

**Comment by codesome** [comment]
@dsiperek-vendavo the name of the annotation/label cannot contain spaces while the value can. So it should be `DashboardURL` here. This should have been caught while saving the rule. Can you check the logs if it has any errors related to this?

**Comment by dsiperek-vendavo** [comment]
I don't see any errors in the grafana logs.

**Comment by kylebrandt** [comment]
> the name of the annotation/label cannot contain spaces while the value can.

@codesome - I am wondering: 
1. For labels, is this only true of labels from the rule configuration - or is this also true of labels returned by the data (from queries). That will be an issue we need to figure out I think if that is true.
2. Why can't the key/name have spaces?

**Comment by codesome** [comment]
I think there is nothing stopping here to use spaces in the label names. I was having [this Prometheus rule](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels) in mind hence said without looking up. This needs some debugging, I will assign it to myself.

**Comment by codesome** [comment]
So it's basically the Prometheus data model that's making the labels/annotations invalid before Alertmanager processes it ([here](https://github.com/grafana/grafana/blob/a0dac9c6d9297bf0740a8689f37701f18215f588/pkg/services/ngalert/notifier/alertmanager.go#L507)). I don't see any technical reason why spaces would be a problem.

So we have 2 options here:
1. Don't allow spaces and follow the Prometheus data model.
2. Allow spaces and have custom validation.

(PS another TODO: the error log had no error message, because [here](https://github.com/grafana/grafana/blob/a0dac9c6d9297bf0740a8689f37701f18215f588/pkg/services/ngalert/notifier/alertmanager.go#L541) it should be `=` instead of `:=`)

**Comment by codesome** [comment]
The reason for Prometheus to not allow spaces might be largely the exposition format of `name="value"` where having spaces for names does not make sense. I think for alerting we should be fine with using spaces for label names.

**Comment by codesome** [comment]
Opened https://github.com/grafana/grafana/pull/36549 to allow spaces
