### ISSUE TITLE
GET /public/app/grafana.js HTTP/1.1" 404 Not Found

### ISSUE THREAD

**Issue by abhisant** [grafana/grafana#3614]
When I pull the latest code changes and run:

go run build.go build
grunt  ---> I get few warnings here.
When I use grunt --force, the build passes with warnings,

but when I restart the server, clearing the database and try to access http://0.0.0.0:3000, I get the following error:
GET /public/app/grafana.js HTTP/1.1" 404 Not Found

**Comment by torkelo** [comment]
What grunt warnings??

**Comment by abhisant** [comment]
Running "typescript:build" (typescript) task
>> public/vendor/npm/angular2/typings/es6-shim/es6-shim.d.ts(148,27): error TS2304: Cannot find name 'ArrayLike'.
>> public/vendor/npm/angular2/typings/es6-shim/es6-shim.d.ts(162,24): error TS2304: Cannot find name 'ArrayLike'.
>> public/vendor/npm/angular2/typings/es6-shim/es6-shim.d.ts(625,72): error TS2304: Cannot find name 'ArrayLike'.
>> public/vendor/npm/angular2/typings/es6-shim/es6-shim.d.ts(626,57): error TS2304: Cannot find name 'ArrayLike'.
>> public/vendor/npm/angular2/typings/es6-shim/es6-shim.d.ts(653,76): error TS2304: Cannot find name 'ArrayLike'.
>> public/vendor/npm/angular2/typings/es6-shim/es6-shim.d.ts(654,61): error TS2304: Cannot find name 'ArrayLike'.
Warning: Task "typescript:build" failed. Use --force to continue.

**Comment by bergquist** [comment]
@abhisant does this problem remain if you pull from master? Our CI build is green atm.

**Comment by sileht** [comment]
I have the same issue.

**Comment by torkelo** [comment]
@sileht strange, works on the build system, can describe more about your system, os, version, node version, npm version, any global typecscript version installed that could be causing issues?

**Comment by sileht** [comment]
$ lsb_release -sd
Ubuntu 14.04.3 LTS
$ npm -v
1.3.10
$ tsc -v
message TS6029: Version 1.7.5
$ node -v
v0.10.25

**Comment by sileht** [comment]
"npm ls" was still complaining as follow after a 'npm install':
├── UNMET DEPENDENCY systemjs-builder ^0.14.15
├─┬ tslint@2.5.1 invalid
│ ├─┬ findup-sync@0.2.1
│ │ └─┬ glob@4.3.5
│ │   ├─┬ inflight@1.0.4
│ │   │ └── wrappy@1.0.1
│ │   ├── inherits@2.0.1
│ │   ├─┬ minimatch@2.0.10
│ │   │ └─┬ brace-expansion@1.1.1
│ │   │   ├── balanced-match@0.2.0
│ │   │   └── concat-map@0.0.1
│ │   └─┬ once@1.3.2
│ │     └── wrappy@1.0.1
│ ├─┬ optimist@0.6.1
│ │ ├── minimist@0.0.10
│ │ └── wordwrap@0.0.3
│ └── underscore.string@3.1.1

So I have removed my local node_modules directory and recreate it from scratch with 'npm install' the warnings are gone but the "GET /public/app/grafana.js HTTP/1.1 404 Not Found" was still present.

So, I have decided to clean everything to not loose to much time of this.
git clean -fdx; go run build.go setup ; $GOPATH/bin/godep restore ; go build ; grunt; bra run

The problem is gone now. It looks like something doesn't upgrade smoothly on a dev environment.

**Comment by abhisant** [comment]
Yes, clean build using the following steps worked for me, thanks Mehdi.
> git clean -fdx; go run build.go setup ; $GOPATH/bin/godep restore ; go build ; grunt; bra run
>
