### ISSUE TITLE
Alerting: query with comparison operator prevents alert from resolving because query filters out non-alerting results

### ISSUE THREAD

**Issue by dsiperek-vendavo** [grafana/grafana#36179]
What happened: Alerts are not updating and they are showing multiple states 

What you expected to happen: Alerts should return what is returned i query when setting up alert

How to reproduce it (as minimally and precisely as possible):

Anything else we need to know?: 
![Screen Shot 2021-06-25 at 8 58 06 AM](https://user-images.githubusercontent.com/70541548/123457151-79caa100-d598-11eb-80f5-03e3e93bfc0e.png)

Environment:

Grafana version: 8.0.3
Data source type & version: Prometheus / Thanos X 2
OS Grafana is installed on: Azure AKS, official Grafana
User OS & Browser: not relevant
Grafana plugins: clean install
Others:

**Comment by zuchka** [comment]
Hi @dsiperek-vendavo 

Thanks for making this issue. Looks similar to https://github.com/grafana/grafana/issues/36165, you think? 👍

**Comment by dsiperek-vendavo** [comment]
This could be the same issue.  It seems nothing is recovering after alerting unless i manually save the alert again to refresh it.

**Comment by dsiperek-vendavo** [comment]
We are using also postgresql-ha and still an issue in 8.0.4

**Comment by davidmparrott** [comment]
@dsiperek-vendavo inferring from the alerting rule description in your screenshot, I am guessing that you have your condition configured so that if the value returned is `> 0.9` then you want to get alerted. As long as that value threshold is exceeded, you will continue to be in an alerting state. Are you seeing cases where a particular instance has dropped below that threshold but doesn't recover?

**Comment by dsiperek-vendavo** [comment]
> @dsiperek-vendavo inferring from the alerting rule description in your screenshot, I am guessing that you have your condition configured so that if the value returned is `> 0.9` then you want to get alerted. As long as that value threshold is exceeded, you will continue to be in an alerting state. Are you seeing cases where a particular instance has dropped below that threshold but doesn't recover?

Yes.  The UI is incorrect all the time.  Nothing seems to go away.

**Comment by davidmparrott** [comment]
The alerting engine evaluates the queries on the configured interval and, if the query returns a value such that the condition is alerting, it will continue to stay in an alerting state until a result is returned that is not alerting. The first result that is not alerting sets the state for that particular instance to normal. The alerts don't expire or go back to normal until a query result is returned that indicates that they should be. 

From your screen shot, it looks like your example is working correctly. The reason that saving the rule clears the alerting state is that evaluation is reset when a rule is saved.

**Comment by dsiperek-vendavo** [comment]
> The alerting engine evaluates the queries on the configured interval and, if the query returns a value such that the condition is alerting, it will continue to stay in an alerting state until a result is returned that is not alerting. The first result that is not alerting sets the state for that particular instance to normal. The alerts don't expire or go back to normal until a query result is returned that indicates that they should be.
> 
> From your screen shot, it looks like your example is working correctly. The reason that saving the rule clears the alerting state is that evaluation is reset when a rule is saved.

So then why have these not recovered?  They don't show up when i run it when i edit the rule and run it manually. I got a lot of different servers showing critical in the UI and the all have since been fixed or recovered!

**Comment by davidmparrott** [comment]
Can you show me new screenshot where the instance is alerting but the value is below the threshold?

**Comment by dsiperek-vendavo** [comment]
![image](https://user-images.githubusercontent.com/70541548/124813721-0b7fca00-df1a-11eb-8ca9-999fcc07b89d.png)
Shows no nodes listed.  But the alert still shows all the nodes have since recovered. 
![Screen Shot 2021-07-07 at 11 55 44 AM](https://user-images.githubusercontent.com/70541548/124814077-6addda00-df1a-11eb-9d7f-5fc578be9b28.png)
The alert values show the wrong value (its like they are not updating)
I added one of the servers disk graphs show you its not over 90% anymore
![image](https://user-images.githubusercontent.com/70541548/124814433-d88a0600-df1a-11eb-867e-9eb99c7e5a60.png)

**Comment by davidmparrott** [comment]
I think we're not quite on the same page here.  There are at least two rules that you've shared screen shots for. One named `Linux Disk Space` and one named `Windows Partition Space`. I'd like to focus on just one of them, and either works for me. 

Please share a screenshot that contains the complete rule configuration, or the JSON payload of the request that gets sent when you click the save button in the UI. Either should work, I just want to make sure I can see the complete configuration you're working with.

What happens when you click `Run Queries` in the rule edit/create UI? Here's an example of what I'm seeing for a rule I use when I'm testing changes I'm making:
![Alerting__Alert_rules_-_Grafana](https://user-images.githubusercontent.com/4461026/124834508-c4eb9900-df34-11eb-8f32-cfb9d7b79abb.png)

What about when you click `Preview Alerts`? Here's the output of that from the same rule:
![Alerting__Alert_rules_-_Grafana](https://user-images.githubusercontent.com/4461026/124834623-ef3d5680-df34-11eb-954b-f21ccb896a80.png)

Finally, can you grab a screenshot or copy-paste the relevant section from the `/api/prometheus/grafana/api/v1/rules` endpoint? Here again is the output from this rule running on my local machine:
![Mozilla_Firefox](https://user-images.githubusercontent.com/4461026/124834942-62df6380-df35-11eb-8500-f24b9ca5f095.png)

The arrows are pointing to the value that is generated by $B in my alerting rule and, if you glance back up at my config, I want to be notified when `$B < 0.9` for any `code`. I'm guessing that there's something that isn't configured correctly and my hope is that stepping through things like this will help us get to the bottom of it. Thanks for the engagement and working through this.

**Comment by dsiperek-vendavo** [comment]
Would it be possible to show you everything on a zoom?

**Comment by davidmparrott** [comment]
Feel free to reach out in our [public slack instance](grafana.slack.com) and we can work out how to get in contact. You can find me there with my name: David Parrott

**Comment by davidmparrott** [comment]
Circling back to this after chatting with @dsiperek-vendavo on a call. We discovered that the source of the behavior was a query with a [comparison binary operator](https://prometheus.io/docs/prometheus/latest/querying/operators/#comparison-binary-operators). A basic example of this would be `up{} == 0` 

To explain what is happening:
The presence of a comparison binary operator causes the query to return a subset of matches when the query is run. In this case, the operator was `>90` so only hosts that had more than 90 percent of their disk used would be returned as a match from the datasource. Grafana 8 alerts keeps track of all the matches seen using an in-memory state cache. When the query match is seen once, we do not prune it (at present). Because the query would never return a match once the entity had recovered, there was never a `Normal` result processed, leading to these alert instances hanging around in an apparently alerting state. 

The solution here was to remove the comparison binary operator from the query and instead add a `Math` expression that took the output of the Reduce expression and compared it to the threshold. I will create and link a new issue to address this scenario more elegantly in a future release. 

The last bit of information that is relevant here is that the reason for adding the operator in the first place was to reduce the number of instances in the alerting UI. At present, the UI filtering for `Firing` does not exclude alert instances with a `Normal` state, only alerting rules with zero alerting instances. I will also create an feature request (if one does not yet exist) to filter `Normal` alert instances out when this filter is selected.

Thank you so much for this great feedback and the opportunity to learn more about what did and did not work for you, @dsiperek-vendavo ! It was a very helpful chat.

**Comment by davidmparrott** [comment]
Linking the PR that will address automatic removal of orphaned/stale alert instances
