### ISSUE TITLE
How to use color to distinguish different Y axis values 

### ISSUE THREAD

**Issue by ThierryHenry1994** [grafana/grafana#36200]
**What happened**:
I want distinguish Bitech and KOTEI by color but I don't know how to do Could anyone tell me? tks.
![image](https://user-images.githubusercontent.com/32047768/123600419-3c307700-d829-11eb-8d7a-01c699790054.png)

my sql table is
|  company   | status  |  count  |
|  ----  | ----  | ----  |
| bitech  | new | 12 |
| kotei  | new | 4 |
| kotei  | in process | 3 |

**What you expected to happen**:
bitech one color kotei one color  like this
![image](https://user-images.githubusercontent.com/32047768/123600515-55d1be80-d829-11eb-8c0c-6f5d7bbdad63.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:7.57
- Data source type & version:mysql
- OS Grafana is installed on:windows
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by dsotirakis** [comment]
Looping in @grafana/grafana-frontend-platform

**Comment by tskarhed** [comment]
This seems like a case for field overrides. You might have to transform your data for this to work. In the panel editor to the right:

1. Click overrides
2. Add field override
3. Choose the desired field (KOTEI in this case)
4. Add override property - Color scheme

I'm closing this, since the question is more suited for https://community.grafana.com/
