### ISSUE TITLE
StateTimeline: Show value mappings in legend

### ISSUE THREAD

**Issue by pepjo** [grafana/grafana#36207]
**What would you like to be added**:
In the new state map added in Grafana 8, the information displayed in the legend comes from the thresholds' configuration. However, no name can be assigned to each region in that configuration. Instead, it would be great if the value mappings can be shown.

This is my current configuration:
![image](https://user-images.githubusercontent.com/1307305/123618452-2064ab00-d800-11eb-9cf8-09482dac8f91.png)

I would suggest doing something like the flant status map Grafana plugin:
![image](https://user-images.githubusercontent.com/1307305/123618647-50ac4980-d800-11eb-9fe5-ea91963860a4.png)

**Why is this needed**:
To have a legend that is meaningful.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
