### ISSUE TITLE
Support Data Links in Status History panel 

### ISSUE THREAD

**Issue by domclassen** [grafana/grafana#36240]
Currently you can configure data links in Status History panels but they don't show or function in 8.x (tested with 8.0.3).
This should ideally work just the same as in 7.x where we were using the community predecessors of that panel.

The intention is to have an aggregated view on status and then be able to drill into details, carrying over field values into the target dashboard.

**Comment by dsotirakis** [comment]
Hello @domclassen, thanks for raising this. Please can you use the template for creating features next time you create one?  Thanks!
```
<!-- Please only use this template for submitting feature requests -->

**What would you like to be added**:

**Why is this needed**:
```

**Comment by VolkrB** [comment]
I would like for this to also be added - Data links working in Status History Panels

I think this should already work, is it a bug?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
