### ISSUE TITLE
error when database is not exist in mysql

### ISSUE THREAD

**Issue by schen59** [grafana/grafana#3625]
I am trying to use mysql as the backend storage, I use the default database name 'grafana'. However, when startup, it will complain something like:
fail to initialize orm engine: Sqlstore::Migration failed err: Error 1049: Unknown database 'grafana'

Once I manually create the database 'grafana' in mysql, everything will just work fine.

I think the error happens because the database is not created in mysql beforehand? Can we automatically create the database in mysql? Thanks.

**Comment by dolftax** [comment]
@bergquist Could you point me to related file?

**Comment by xsank** [comment]
i meet the same problem on windows

**Comment by mitjaziv** [comment]
Hello All,

creating database automatically, without setting user permission/privileges is security risk.
Automatic creation of database is generally bad practice. (Not sure if i saw this functionality in other projects.) Having the same user for multiple databases is also not very advisable.

I checked the code for possibilities anyway and found out, that xorm connects directly to the database specified in conf. Which would mean that in case of error we would need to connect to master database to create DB. Which would result grafana user to have admin/create db privileges on whole mysql. 

@bergquist because all of this i would advise to close this issue with "Won't fix".

Regards

**Comment by torkelo** [comment]
think your right, closing this as wont fix
