### ISSUE TITLE
Unable to use regex influxdb tag in Alerting

### ISSUE THREAD

**Issue by tchameroy** [grafana/grafana#36276]
**What happened**:
I am unable to use the regex influxdb tag in Alerting, when selecting the tags for the query in Alerting, only specific tags are available.

Tags used for the panel query
<img width="627" alt="Screen Shot 2021-06-29 at 10 15 06 AM" src="https://user-images.githubusercontent.com/28870027/123833298-72bad000-d8c3-11eb-88dd-417ad2d2d013.png">

Regex tag missing in alert creation
<img width="624" alt="Screen Shot 2021-06-29 at 10 15 44 AM" src="https://user-images.githubusercontent.com/28870027/123833418-8bc38100-d8c3-11eb-9866-5cd507c6deb8.png">

**What you expected to happen**:
Expected Regex tags being an option and an alert created based on each tag under the Regex selection

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: InfluxDB 1.8.4
- OS Grafana is installed on: Ubuntu 18.04.5 | Docker 19.03.6
- User OS & Browser: MacOS | Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
template variables are not supported for alerting queries

**Comment by tchameroy** [comment]
@torkelo Are there any discussions available as to reasonings to not support template variables? Is there any documentation for using Grafana in a large scale enviroment that does not involve creating 10k dashboards to allow alerting to be used? We would like to use or work with Grafana alerting but it does not seem feasible without templating functionality at our scale. I am open to any suggestions you have.

**Comment by torkelo** [comment]
@tchameroy why do need template variables in the alert query? You can use wildcards and regex expressions to create generic queries that target a large set of series. 

Template variables are for dynamic filtering and dynamic dashboards. They do not make any sense for defining an alert rule. An alert rule you want a query that is well defined and predictable. Instead of the variable you just define the regex for what hosts or data centers you want the query to target.
