### ISSUE TITLE
Time Series: Only show selected series in tooltip

### ISSUE THREAD

**Issue by schollsi** [grafana/grafana#36290]
**What would you like to be added**:
When selecting specific series from a time series panel only the selected series should be visible in the tooltip. At the moment still all series of the panel are visible if tooltip mode is set to "All":
![image](https://user-images.githubusercontent.com/86708322/123926920-a7468e80-d98c-11eb-8f70-1ebd19c5f26a.png)

The desired behaviour can be achieved by manually hiding the tooltip via series override:
![image](https://user-images.githubusercontent.com/86708322/123927137-d52bd300-d98c-11eb-8951-4086bdfb7934.png)

![image](https://user-images.githubusercontent.com/86708322/123927205-e5dc4900-d98c-11eb-81d2-9dda25b17d72.png)

But this override option is reset by changing the selected series.

A possible solution could be an additional tooltip mode "Selected".

**Why is this needed**:
Most of the time only the values of the selected series are relevant for the user.

**Comment by Antiarchitect** [comment]
@dprokop This should be reverted for the common sense. Hide in area overrides (Viz, Tooltip and Legend) should be totally independent for sake of flexibility.

Good example:
![image](https://user-images.githubusercontent.com/50209/179866900-71a094bf-4979-49ea-b0ec-270407cc02a3.png)

I want to see Total in Legend and Tooltip but not Viz as I have all compounds displayed already and cannot do it because of this change.

**Comment by Shadow505** [comment]
@dprokop I agree with Antiarchitect. I need some data to be only be shown via the tooltip, nowhere else. This is currently not possible

**Comment by Shadow505** [comment]
I found a workaround to achieve the desired effect. Let me know if you still need it. It would still preferable that Grafana would implement this properly by having the 3 display values independent as suggested above.

**Comment by Antiarchitect** [comment]
@Shadow505 Let's compare our workarounds :)

Mine is:
- Add another query to the panel which have a wrapping aggregate function (sum, avg). 
- In overrides panel chose Graph styles > Style > PointSize and set it to minimal (1 currently)
- Another override (optional) Series > Hide in area > Legend

The result is: 
![image](https://user-images.githubusercontent.com/50209/214405298-0a6fb518-7410-4806-a05e-e196542c76ea.png)

**Comment by Antiarchitect** [comment]
@Shadow505 During the inventing of workaround I realized that additional query is much more flexible, because it can display not only Total but any other aggregate e.g. Average (only in the tooltip or just differently on the chart itself). Please take a look:
![image](https://user-images.githubusercontent.com/50209/214412372-bbca5a6b-b309-4997-add5-b738eb65d0de.png)

**Comment by Shadow505** [comment]
@Antiarchitect If I am not overseeing anything, this would also work with my solution. But that honestly depends on your data and the source. I have never used Prometheus so I don't know for sure (I am using InfluxDB). But at least there are now 2 different workarounds for other people that might run into that issue haha

Cheers :)
