### ISSUE TITLE
[Grafana 8.0.3] Time Series not show Right axis

### ISSUE THREAD

**Issue by Ales999** [grafana/grafana#36312]
![image](https://user-images.githubusercontent.com/367257/123998369-dd1a6000-d9ea-11eb-9e82-a57ca7efc275.png)

![image](https://user-images.githubusercontent.com/367257/123998428-ec99a900-d9ea-11eb-9905-d9b2b2544069.png)

![image](https://user-images.githubusercontent.com/367257/124001204-d3462c00-d9ed-11eb-9915-9c6ac200bc20.png)

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux debian 10 (buster) x64
- User OS & Browser: Windows 10, Chrome
- Grafana plugins:
- Others:

**Comment by victorclaessen** [comment]
I am also looking into this. I am getting a second axis when I set different units for some metrics. 
.

**Comment by dprokop** [comment]
@Ales999 this is by design. In TimeSeries panel axes are rendered based on the units you set for a series. By default, there is only one left axis, and every additional unit is rendered on the right axis. You can control this behaviour by using [Field Overrides](https://grafana.com/docs/grafana/latest/panels/field-options/#field-overrides)

**Comment by Ales999** [comment]
This is exactly what was done, I think that they closed early:
![image](https://user-images.githubusercontent.com/367257/124147199-e9b0be00-daa7-11eb-871d-a6fdb16d3995.png)

**Comment by torkelo** [comment]
@dprokop think this could be improved, if the Axis label is set via override (different than others) then could also be a reason to split out a separate axis?

**Comment by Ales999** [comment]
Now both queries all fall into one heap on the left side. But turning off the first magically, the second begins to display correctly, on the right side.

**Comment by Aceman87** [comment]
I understand that this is by design, however, I think there might be many people with use cases like mine. Namely, if you have e.g. temperature data from two sources and both are in celcius. Then if the scale on one of the sources is vastly different (e.g. by a factor of 100), the other data source data will basically flat line because of the scale difference between the data sources.

As a work around in 8.0.3 I have just dropped the units on the second data source all together (unit is short or none). This will create a second axis. However, this is not ideal.

**Comment by leeoniya** [comment]
> Then if the scale on one of the sources is vastly different (e.g. by a factor of 100), the other data source data will basically flat line because of the scale difference between the data sources.

a work-around is to use a logarithmic axis, though this cannot show negative values until we fix https://github.com/grafana/grafana/issues/7627

**Comment by wiz78** [comment]
>I think there might be many people with use cases like mine

me, for one. :-)  I had a graph with an average duration and a maximum duration. I wanted to keep max duration on the right, because it's a totally different order of magnitude than the average. I had to change one unit to a custom "secs" to achieve that, which is very hacky (apart from being ugly to see, it won't format time as nicely as it did in the previous version)

**Comment by dswarbrick** [comment]
Another scenario which I have used for many years with the old graph panel type: load average (1m, 5m, 15m) on the left axis, context switches on the right axis. Both are unit "short", but context switches are usually in the thousands, whilst load average is not (hopefully). This is currently not possible with new time series panel.

**Comment by torkelo** [comment]
same as https://github.com/grafana/grafana/issues/32165 currently you have to set a different unit to get new y-axis
