### ISSUE TITLE
Ngalert in Grafana 8 is missing option to "Keep Last State"

### ISSUE THREAD

**Issue by FireEmerald** [grafana/grafana#36376]
**What happened**:

The new alerting introduced with Grafana 8 is missing the "Keep Last State" option:
![alerting_rules](https://user-images.githubusercontent.com/1107939/124249035-c3c8ff00-db23-11eb-9c1d-0b2d16c14028.png)

No Data Option | Description
-- | --
No Data | Set alert state to NoData and rule state to Normal
Alerting | Set alert rule state to Alerting
Ok | Set alert rule state to Normal

**What you expected to happen**:
The legacy alerting system had the following options:
No Data Option | Description
-- | --
No Data | Set alert rule state to NoData
Alerting | Set alert rule state to Alerting
**Keep Last State** | **Keep the current alert rule state, whatever it is.**
Ok | Not sure why you would want to send yourself an alert when things are okay, but you could.

**Environment**:
- Grafana version: v8.0.3 (cae5c5e46b)
- OS Grafana is installed on: linux
- User OS & Browser: windows, chrome

**Comment by gotjosh** [comment]
Hi @FireEmerald, can you please shed some light on why do you need this feature? We've deliberate chose to remove it because the current alerting system decouples the alerting evaluation and notification into two separate parts.

The only use-case we could think of is to keep alerting in case the datasource goes missing which could continue to be the case given we won't have data to transition the alert to a new state.

**Comment by FireEmerald** [comment]
@gotjosh If the sampling interval is low and also subject to larger fluctuations, it can happen that no data point is available in the defined period `[now-15m to now]`. When I think about it, in the situation described it may also be a solution to generally increase the period of time included in the measurement.

**Comment by davidmparrott** [comment]
@FireEmerald I think you're on the right track there. Between setting an evaluation interval that is long enough that you'll have a data point, and also configuring a For duration, where the alert needs to have been in an alerting state for a set duration before firing, you should be able to keep noisy or flapping alerts under control. Did you have any additional questions about this?

**Comment by vbichov** [comment]
I realize that this issue was closed but any chance you guys reconsider restoring the `Keep last state` on `Alert state if execution error or timeout` - we have too many alerts and the underlying databases can become unreachable. On some more important alerts the `For` option is not possible because it will increase MTTx.
