### ISSUE TITLE
Alerts email with OK status does not showing metricname 

### ISSUE THREAD

**Issue by vasu0278** [grafana/grafana#36419]
Hi Team,

Can someone please help with below ask.

1. we are not seeing metric name in Grafana OK status email for which metric alerts got resolved.
2. if one alert is there on panel it's not triggering email for another raised alerts until specified reminder time or the existing alert is closed.

**Comment by torkelo** [comment]
The alerting system does not keep track of the state of individual series. So when the alert rules goes back to OK Grafana does not know which specific series it was that made it fire a moment ago. 

This is fixed in the new alerting system (out in preview in v8) https://grafana.com/docs/grafana/latest/alerting/unified-alerting/
