### ISSUE TITLE
NGAlert: Can not Create Managed Alert with Graphite

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#36572]
**What happened**:
When I try to run a new alert rule with new graphite queries through the managed UI the properties are missing from the model - and hence I get an error that the "target" is missing.

I can however run migrated queries that were already saved in the same alert view.

**What you expected to happen**:
The properties to be there and the query to run

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/1692624/124952787-87454980-dfe2-11eb-82f2-0ab54d2680fb.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6266a9e77a
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by peterholmberg** [comment]
For some reason the expressions query ends up in `graphite_query.ts::updateRenderedTarget` and causes a crash which prevents the model to update.

**Comment by dcharleston** [comment]
This is a high priority issue for us since we use graphite for the vast majority of our metrics and monitoring checks. I tried digging into what was causing this with my extremely limited knowledge of the Grafana codebase and frontend code. A similar error also shows up when editing a dashboard panel with a normal series query and expression query
![Screen Shot 2021-09-27 at 4 51 14 PM](https://user-images.githubusercontent.com/4481337/135001045-165a4a70-563c-4348-95a9-f6ebef0ce2e6.png)

This isn't as noticeable when editing a panel dashboard since a call is made to [handleTargetChanged ](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/graphite/state/helpers.ts#L149-L160_)with only the edited query in `state.queries` (this one works) before another call is made with both the series query and expression query in `state.queries` (this one fails with the error above). On the panel dashboard page the series query is updated correctly but you still get a console error from the second call to handleTargetChanged.

**First call works**
![Screen Shot 2021-09-27 at 4 49 43 PM](https://user-images.githubusercontent.com/4481337/135002423-ca69f062-3b32-46e1-a274-4e559c700fb9.png)

**Second call fails**
![Screen Shot 2021-09-27 at 4 54 10 PM](https://user-images.githubusercontent.com/4481337/135002451-5fe8a4b0-7599-4b87-b75b-c077c031bac5.png)

So it seems that when you create a new alert its including all queries and when you edit a dashboard it first includes only the single query that you edited and then includes all queries in the call that fails.

**Comment by peterholmberg** [comment]
@dcharleston thanks for sharing your findings ⭐
