### ISSUE TITLE
Alerting: Remove instances that stop reporting from cache and database

### ISSUE THREAD

**Issue by FireEmerald** [grafana/grafana#36645]
**What happened**:
The _Matching instances_ view does show entries which do not exist, should not be shown (last entry):
![wrong](https://user-images.githubusercontent.com/1107939/125250822-f7134700-e2f6-11eb-8c20-e280edf2f368.png)

**What you expected to happen**:
After initial setup the listed instances was like this (until some state changes of one of those listed instances):
![normal](https://user-images.githubusercontent.com/1107939/125250837-f975a100-e2f6-11eb-93c2-587921f20539.png)

**How to reproduce it (as minimally and precisely as possible)**:
<details>

1. Attach a postgres database to grafana containing the following table:
``` sql
CREATE TABLE "carmap" (
  "id" int8 NOT NULL DEFAULT nextval('carmap_id_seq'::regclass),
  "captured" timestamp(6) NOT NULL,
  "name" varchar(255) NOT NULL,
  "city" varchar(255) NOT NULL,
  "speed" float8 NOT NULL
);

-- Insert some rows, adjust speed (->50) to trigger alerts
INSERT INTO carmap (captured, name, city, speed) VALUES
  (NOW()-INTERVAL '3 SECOND', 'car1', 'berlin', 150),
  (NOW()-INTERVAL '3 SECOND', 'car2', 'berlin', 130);
```
2. Create a new alert, sql:
``` sql
SELECT t.name, t.city, CASE WHEN t.speed > 100 THEN 0 ELSE 1 END
FROM (
  SELECT RANK()
    OVER(
      PARTITION BY name
      ORDER BY captured DESC
    ) AS rnk,
    id, captured, name, city, speed
  FROM carmap
) t
WHERE
  rnk = 1 AND
  captured >= (NOW() - INTERVAL '5 MIN')
```
![2021-07-12 09_11_58-Alerting_ Alert rules - Grafana](https://user-images.githubusercontent.com/1107939/125245913-6e45dc80-e2f1-11eb-98ee-ad3d5d9db306.png)

4. Alert conditions:
![2021-07-12 09_12_20-Alerting_ Alert rules - Grafana](https://user-images.githubusercontent.com/1107939/125245887-68e89200-e2f1-11eb-82a2-617e1be21f8c.png)
</details>

**Anything else we need to know?**:
- Contact point: autogen-panel-recv-default_route
- Group by: -
- Timings: Group wait: 1s | Group interval: 2s | Repeat interval: 15m

**Environment**:
- Grafana version: v8.0.3 (cae5c5e46b)
- Data source type & version: postgres 13.3
- OS Grafana is installed on: linux
- User OS & Browser: windows, chrome

**Comment by kylebrandt** [comment]
I believe I have seen this under the following scenario:
 - Alert evaluation returns an error, this error doesn't have data, so the labels that come for the data are missing
 - The alert stops erroring, (for some reason that instance goes back to normal?) and lingers as an alert instance.

Maybe @davidmparrott has some additional input on how this might happen or if what I explained above sounds expected (with the current behavior, not expected in the sense that this is how we want it to work).

**Comment by davidmparrott** [comment]
This sounds like the most likely scenario, to me. We create an alert instance in the state cache for every combination of labels that are returned from the query, including when there is an error or incomplete label set. At the present moment, we aren't expiring any entries from the cache, which is why you're seeing these persistent instances that you don't expect.

I believe the best solution will be to start expiring instances from the cache after a set number of evaluations where no results are returned for a label set. 

The other issue that this brings up is around a nuance of what we mean by "No Data" being returned. We have two scenarios that can be interpreted as no data: 

- the presence of zero/null 
- the absence of any result

The first scenario is what our No Data configuration option is designed to handle. This is when your query is run and, for a given evaluation match (unique set of labels) there is no data returned or all values are null. So we have an evaluation result returned, but there is no data.

The second scenario is currently not handled. The alerting engine is largely event driven, meaning that we do something when we get an evaluation result returned. If no match is returned for an alert instance (because, for example, the alert instance was created from an incomplete set of labels) we don't ever touch that alert instance again. 

I have some thoughts on how to address the second scenario, which is what I believe is causing the behavior you are seeing @FireEmerald. I'll follow up with a PR to start handling expiring cache entries without any matches returned.
