### ISSUE TITLE
Live: Ignores serve_from_subpath=false

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#36693]
**What happened**:
I'm getting 403 errors because it can't setup the WS connection
![Screenshot from 2021-07-13 09-59-05](https://user-images.githubusercontent.com/1438972/125414324-ce6e6f10-7c71-4470-b21c-2eb01884e56e.png)
![Screenshot from 2021-07-13 09-59-32](https://user-images.githubusercontent.com/1438972/125414396-a2bd16ad-3bfc-4bd8-96ab-5690acbe0e7f.png)
```
WARN[07-12|22:30:57] Request Origin is not authorized         logger=live origin=http://localhost:3000 appUrl=http://localhost:10080/ allowedOrigins=

```

**What you expected to happen**:
For it to work.

**How to reproduce it (as minimally and precisely as possible)**:
Change config to this:
```
root_url = %(protocol)s://%(domain)s:10080/

# Serve Grafana from subpath specified in `root_url` setting. By default it is set to `false` for compatibility reasons.
serve_from_sub_path = false
```

**Anything else we need to know?**:

By just removing the root_url it is solved. Since I don't serve it from a subpath it should be ignored though.

**Environment**:
- Grafana version: main
- Data source type & version:
- OS Grafana is installed on: 
- User OS & Browser: Ubuntu, Firefox
- Grafana plugins:
- Others:

**Comment by tskarhed** [comment]
Not sure if this is directly related to the Live feature, since the appUrl seems to be set in a faulty way.

**Comment by FZambia** [comment]
From what I see:
* root_url is `%(protocol)s://%(domain)s:10080/`
* browser page url is `http://localhost:3000`

In this case WebSocket connection can't be established (403) since it checks request Origin over public (`root`) URL by default. If you set `root_url` to be

```
root_url = %(protocol)s://%(domain)s:3000/
```

Errors should go away. But I suppose there is a reason to have 10080 port? What is that reason?

**Comment by tskarhed** [comment]
I used that URL when troubleshooting issues related to subpaths or reverse proxies. I think that's what's required if you run the gdev version of nginx,or if it was Apache reverse proxy container. Can't really remember.

**Comment by FZambia** [comment]
I don't think `serve_from_sub_path` is somehow related to WS origin check (which is the reason of 403).

As far as I can see `serve_from_sub_path` just takes the `path` part of `root_url` and uses it internally. The reason why WS connection can't be established here is that `root_url` does not match request origin which is `http://localhost:3000` in this particular case. It's documented here: https://grafana.com/docs/grafana/latest/live/configure-grafana-live/#request-origin-check, also an ongoing pr: https://github.com/grafana/grafana/pull/36661

This causes lots of confusion, but since browsers don't have cross-origin policy enabled by default for WebSocket connections we can't avoid origin checks I believe to avoid connection hijacking.

> Can't really remember.

So you don't have this setup at the moment where you need to fix an issue? Should we close an issue then or do you have any other thoughts regarding this?

**Comment by tskarhed** [comment]
The issue is gone for me by just commenting out the root_url, so I'll just close this.

**Comment by FZambia** [comment]
That's because the default `root_url` is `http://localhost:3000/` which matches origin of request
