### ISSUE TITLE
Grafana channels are not imported correctly as the contact point

### ISSUE THREAD

**Issue by yasharne** [grafana/grafana#36697]
**What happened**:
After enabling `ngalert` on grafana, I see a long long list of random contact points: 
![image](https://user-images.githubusercontent.com/7656049/125421975-4d0fdd39-9625-451c-84e7-32b803dfee89.png)

**What you expected to happen**:
The actual notification channel is much less and contains other types like `webhook`:
![image](https://user-images.githubusercontent.com/7656049/125422638-4b2f8622-b6b3-4cae-b1f7-5c7deb2debfb.png)

**How to reproduce it (as minimally and precisely as possible)**:
enable `nginalert` in `grafana.ini`

**Environment**:
- Grafana version: 8.0.5

**Comment by codesome** [comment]
This is by design because of some fundamental difference of how alerts are routed in unified alerting vs the legacy alerting.

Legacy Alerting: Sends to a set of notification channels mentioned. Hence rules know about the contact points.

Unified Alerting: Rules have no idea where is the alert going. The routing policy takes care of deciding that. And to make sure that after migration the rule from a panel goes to exactly those contact points, we create 1 receiver (which can have >1 contact points (notification channels)) and 1 routing policy per panel alert so that there is 1:1 mapping.

But I agree that there is room for improvement here. If >1 receivers have the same set of notification channels, we should have only 1 receiver for that.
