### ISSUE TITLE
BarChart: Add support for data links

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#36709]
New BarChart panel would use the amazing feature of data links. Since it's based on uPlot we need to explore a way to re-use existing [ContextMenuPlugin](https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/timeseries/plugins/ContextMenuPlugin.tsx) used in the Time series panel.

BarChart uses quad tree under the hood as a spatial index. We already use quad tree lookup in the BarChart's tooltip implementation, that allows series/data point index retrieval based on the position user click on the chart. The position interpolator is provided to [TooltipPlugin](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx#L75) via the bar chart config builder: https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/barchart/bars.ts#L320

Similar interpolator needs to be used in the ContextMenuPlugin to retrieve frame/field index when user clicks on the bar.

The ContextMenuPlugin handles data links calculation on it's own based on the series and data indexes provided via `selection` property.

ref: https://github.com/grafana/grafana/issues/34608

**Comment by MadApe** [comment]
Data link support in the bar charts would be enormously helpful.  Today in Grafana 8.1.0 the ability to add data links is available in the BarChart panel configuration, but they don't work as was reported in #34608.  I see that issue was marked as a feature-request before it was closed in favor of this one.  Considering the data link option is available in the BarChart config, this seems more like a bug than a new feature.  Granted the "bug" may be that the data link option is presented at all if it's not supported.

The semantics aren't real important, but implementing this feature will certainly provide a valuable function to this panel while making it consistent with other panel types like the TimeSeries, PieChart, and Table.

**Comment by vishynit** [comment]
Hello @dprokop 
Could you give an update when can this be available. Thanks

**Comment by codeincarnate** [comment]
Making sure to drop a note here that this will almost certainly be impacted by  #44882

**Comment by leeoniya** [comment]
@nmarrs is working on this now, which is why https://github.com/grafana/grafana/pull/44882, (it forced me to try to explain the code to him :D)

**Comment by codeincarnate** [comment]
Ah that makes sense @leeoniya, I thankfully hadn't gotten too deep so it's all @nmarrs's 😄
