### ISSUE TITLE
UX: Improved sidemenu

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#3687]
![image](https://cloud.githubusercontent.com/assets/10999/12203841/50f4ec22-b631-11e5-90c2-8f058b138232.png)

This is just a start we have more refinements to this coming.

**Comment by torkelo** [comment]
This is just an idea I had that I quickly hacked in chrome dev tool to get a feel for it. 

![image](https://cloud.githubusercontent.com/assets/10999/12221528/dc0b599a-b79e-11e5-803a-c240a6d59053.png)

Maybe something like that? better styles for the side menu items maybe (background / text color, and some visual marker to highlight current active sidemenu item, like a dark inset arrow to the right) 

@mattttt @bulletfactory

**Comment by mattttt** [comment]
Worked through some additional options, and proposing expanding the concept of 2 menu states:
![new-sidemenu-functionality](https://cloud.githubusercontent.com/assets/2886187/12296532/4e3a8cd2-b9d6-11e5-85f5-e9c7ab5a5f74.gif)

**Comment by bulletfactory** [comment]
:+1:

**Comment by torkelo** [comment]
I like it! playing around with that idea (have not gotten to testing out the pinning,  but I like that feature)
![menu](https://cloud.githubusercontent.com/assets/10999/12337982/8b569d58-bb0d-11e5-86f1-10de6549d2c6.gif)

**Comment by mattttt** [comment]
I am a big fan of this, and I get a pang of excitement seeing this gif. We did not previously mess with the dashboard picker button, but this feels like a really nice evolution that cleans up the design as well.

I'd like to play with that drop shadow/highlight a bit, but this is really awesome.

**Comment by mattttt** [comment]
One more screenshot from Torkelo:

![image](https://cloud.githubusercontent.com/assets/2886187/12338187/7f663bec-badc-11e5-9373-c9b9b53b068f.png)

**Comment by bergquist** [comment]
Marvellous! Not to big of a change for Grafana users and still a big improvement.

**Comment by torkelo** [comment]
![menu](https://cloud.githubusercontent.com/assets/10999/12356838/fb32e360-bba4-11e5-8ad1-3d54ee986eda.gif)

**Comment by mattttt** [comment]
This is looking great, some remarks and TODO:

1. Need to implement pinned mode (and need icon from @bulletfactory) 
1. Flyouts need to be on hover, not on click.
1. Need to dismiss menu when clicking anywhere outside of it (like dashboard picker)
1. Discuss the Grafana wordmark on pinned state & widescreens & step down responsively to smaller menu button when necessary (@torkelo and @bulletfactory  to reach consensus)
1. Animation speed - currently too slow if it slides from the side, **but** that might be irrelevant because...
1. There’s different behaviors going on with the Main Menu vs Dash picker [sliding from left vs appearing below it] and I’d like those to be consistent. Given the down arrow, I'm thinking it should appear much in the same way as the dashboard picker.

**Comment by torkelo** [comment]
not on hover, hover stuff is annoying or?

**Comment by mattttt** [comment]
When I say flyouts, I'm just referring to the secondary menu items (items under Profile/Org or under Dashboard). The main buttons in the top nav will remain on click. 

Have the sub-nav items activate on hover will aid discovery and reduce clicks for. It also allows us to have a default click link, further reducing clicks (for example, clicking the main Dashboards menu item will take you to Dashboard home). Less clicks, more discovery :+1:

**Comment by evandro-portugal** [comment]
Maybe this is not the right place to, but it looks like this branch war merged into master, and I'm facing problems with the sidemenu not showing anything when I updated my code using master branch this afternoon. Tried to mess a little with the feature but was not able to fix it.

**Comment by torkelo** [comment]
@evandro-portugal your right, thanks for reporting that. Fixed in master/latest build

**Comment by torkelo** [comment]
@mattttt && @bulletfactory This is just a quick idea, not sure if it is a good idea. 

![navbar](https://cloud.githubusercontent.com/assets/10999/12379311/52a092c8-bd58-11e5-8626-1c5d1cb97dd5.gif)

Just wanted to try to unify the navbar styles. Other ideas I have (that might be bad), is having the dashboard picker (just the icon no title) available on other pages, like playlists and datasources. 

Another thing that could be interesting updating the design for standalone pages. 

![image](https://cloud.githubusercontent.com/assets/10999/12379343/f2f6353e-bd58-11e5-9e82-0b9447ac2f01.png)

The duplication of the Nav breadcrumb and page header is not ideal but hard to work around. I don't have a concrete idea but feel the topnav could be improved and maybe some cool page template background grid (just throwing out crazy ideas), to make the page feel more structured .

**Comment by mattttt** [comment]
Nice steps forward. I dont like extending the button style into the Dashboard icons - feels heavy and necessary. Further, having those icons sitting within the top-nav in the same style as the time-picker ties those together better as dashboard specific actions instead of top-level actions (like switching dashboards & main menu).

Agreed on breadcrumbs, needs some love still (not addressed in my screenshots below).

On the non-dash pages, I agree with a grid. I think it'll make it easier for app makers to build pages in the style of Grafana. Here are a handful of the pages I was working on, and at the bottom, a different style I was exploring. Feedback appreciated:

![grafana datasource](https://cloud.githubusercontent.com/assets/2886187/12380758/a5a11eee-bd48-11e5-8fdd-e9ca65cfe233.png)
![edit data source](https://cloud.githubusercontent.com/assets/2886187/12380755/a59fd73c-bd48-11e5-9a3f-7278009068cf.png)
![edit playlist](https://cloud.githubusercontent.com/assets/2886187/12380756/a5a0072a-bd48-11e5-92e4-081184d6ab4f.png)
![new playlist 2](https://cloud.githubusercontent.com/assets/2886187/12380759/a5a225e6-bd48-11e5-95ab-a96639a5f4ce.png)

And the alternate style, which is just a small evolution. I have a hunch @torkelo will like it and it's growing on me over the weekend (though to be fair, @bulletfactory likes the above much better). It looks good for data source and other simple forms, but it quickly breaks down on multi-column stuff. 

![grafanadatasource - 2](https://cloud.githubusercontent.com/assets/2886187/12380754/a59ed8e6-bd48-11e5-826e-032e909c88f0.png)

**Comment by torkelo** [comment]
@mattttt we need to decide what background we should have forms on, some are on panel background some directly on body background. Some of the form section headings are on body background some are in a seperate panel background box.


This is raintank's edit form for referense. 
![image](https://cloud.githubusercontent.com/assets/10999/12388554/d88487f2-bdd3-11e5-963a-646c077cef35.png)

**Comment by mattttt** [comment]
In the case you pasted, it's on the panel background because it's grouped within a section (similar to the grouping within Playlists. There are other examples within raintank where the form exists on the background directly - Grafana just has more top-level forms elements and raintank has more grouped ones.

**Comment by torkelo** [comment]
but I think we only have one of them, that is all forms should in in a section?

**Comment by bulletfactory** [comment]
I think reducing the "box-inside-a-box" feel will help the forms and page's scanability and seem a little better organized. But I don't think it means we have to lose the box on grouped elements such as data source list, though to work well together, the grouped section design will need a little extra thought. 

The evolved version of the existing style could work, if we can think through any multi-column needs at @mattttt mentioned.

This ticket was originally for sidebar, should we resume this in a dedicated issue?

T

**Comment by torkelo** [comment]
Suggestion of changing the sidemenu background to panel background, 

Current shade of gray: Feels a little distracting (ignore the peaking green row menu icons)
![image](https://cloud.githubusercontent.com/assets/10999/12703241/a323b07c-c83e-11e5-85ee-19e22c0ddabd.png)

Panel shade of gray (feels like the sidemenu blends in more) 
![image](https://cloud.githubusercontent.com/assets/10999/12703235/7e3e55c8-c83e-11e5-89b7-5ea19f05c6ea.png)

I know @mattttt that you will be experimenting with a new page header design. In a few tests I did without a top nav and sidemenu in collapsed mode (meaning only a sidemenu button in the top left corner), it felt a bit strange with only a buttton in the corner. So did quick hack to test an idea of a semi pinned sidemenu mode to use for non dashboard pages, that is to show a narrow version of the sidemenu even in "non pinned" mode. This solves the issue of only having a button in the left corner. 

Quick hack example
![image](https://cloud.githubusercontent.com/assets/10999/12703289/ce86bc18-c83f-11e5-98fb-31d01a2c06e9.png)

**Comment by mattttt** [comment]
We've had a bunch of discussions about the "semi-pinned" menu as a 3rd state. I like it functionally, but in this example, the menu switching from feeling attached to the top vs attached to the left side, as you navigate, scares me. 

Given the choice between the two, I'd retain the consistency of the top header for all non-dashboard pages, even if it's use is marginal at the moment.

**Comment by torkelo** [comment]
@mattttt yea, I agree , and would rather not do the semi-pinned state (complicated to implement)

**Comment by torkelo** [comment]
close this, further tweaks can be tracked via this issue, https://github.com/grafana/grafana/issues/4036

**Comment by dahai300** [comment]
@torkelo how to add a new item in sidemenu.thankyou. like your menu ,the "nginx" item in sidemenu.

**Comment by dahai300** [comment]
@mattttt  how to add a item in sidemenu in grafana3.1  thankyou

**Comment by kmohide** [comment]
@torkelo I have created a new plugin which I am using for creating a page which displays some data in a table format. How do I call an api from a backend service to populate my table. Thanks
