### ISSUE TITLE
[Time Series] Add Option to make positive and negative axis symetrical

### ISSUE THREAD

**Issue by yurividal** [grafana/grafana#36884]
When using auto for y-min and y-max, there could be an **option** to keep them always symetrical. It can be misleading when the +y axis is, for example, a lot larger than the -y axis,

![image](https://user-images.githubusercontent.com/8555749/126057143-3394580b-f1d5-444a-956e-ef60e334d953.png)
In this case, for example, if +y had automatically grown to 76Mib/s it would have been more intuitive for the viewer.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
