### ISSUE TITLE
login / signup form layout

### ISSUE THREAD

**Issue by gabrielcrowdtilt** [grafana/grafana#3698]
This issue is a suggestion for improving the login and signup. When google authentication is enabled, there is a small red button appears below the form. However, I think it'd be much better if the button was above the login signup form, so that the user will see it first and consider it as first priority, rather than an afterthought, down there, below the form. I think users visually exclude stuff that's out of the way, it says login, so users are thinking, oh I have to login on this form, their eyes aren't looking at other stuff. 

Also besides positioning, the google button could be much much larger in size, there are other google buttons that are easier for the user to notice visually. In conclusion, this is a design issue that would be simple to change and make it easier for users to figure out when to use google as the preferred auth.

**Comment by mattttt** [comment]
@gabrielcrowdtilt Solid feedback. It's an interesting challenge to solve. 

The priority of the fields depends a lot on how your company is using Grafana. Since Grafana is on-prem however, we dont have any user data/stats to help inform the decision. 

That said, I think the existing design can be improved quite a bit, and started playing with some ideas based on the above, showing what it would look like with one and two external authentications enabled.  Log in only so far - doesnt yet explore the New Account tab.

Existing field order:
![grafana-loginscreen-lower-goog](https://cloud.githubusercontent.com/assets/2886187/12246815/9ed20d40-b87e-11e5-8ede-a805f97dae9a.png)
![grafana-loginscreen-lower-goog github](https://cloud.githubusercontent.com/assets/2886187/12246816/9ed9c422-b87e-11e5-9b5c-15e4aefe933a.png)

Inverted field order:
![grafana-loginscreen-goog github](https://cloud.githubusercontent.com/assets/2886187/12246819/a7050c24-b87e-11e5-9139-af85fa45e2f3.png)
![grafana-loginscreen-goog](https://cloud.githubusercontent.com/assets/2886187/12246820/a708e772-b87e-11e5-91d0-91f43d460218.png)

**Comment by torkelo** [comment]
I like the first "Or login in with" below the login form.

**Comment by mattttt** [comment]
Same.

**Comment by bergquist** [comment]
Agree!

**Comment by mattttt** [comment]
@bulletfactory Care to pop in here and give some thoughts on a *super button* style for Grafana? I was originally using the existing button, but they were not big enough - so I believe we'll have to add a new one.

**Comment by bulletfactory** [comment]
I like the additions Matt has suggested (my preference is probably having
the additional login options below the login form). @mattttt and I briefly
chatted about creating a new "superCTA" convention that feels a bit more
prominent (there is a superCTA button type in raintank too). I like the
2-tone design style, I might first see how they look with the rounded
corners for consistency with its 'button brethren' - but big thumbs up.

**Comment by gabrielcrowdtilt** [comment]
thanks guys for the work you've initiated.
