### ISSUE TITLE
PostgreSQL: Add support for user with username containing whitespace

### ISSUE THREAD

**Issue by wbrowne** [grafana/grafana#37196]
>In the keyword/value format, each parameter setting is in the form keyword = value, with space(s) between settings. Spaces around a setting's equal sign are optional. To write an empty value, or a value containing spaces, surround it with single quotes, for example keyword = 'a value'. Single quotes and backslashes within a value must be escaped with a backslash, i.e., \' and \\.

https://www.postgresql.org/docs/10/libpq-connect.html#LIBPQ-CONNSTRING

**Comment by kitarp29** [comment]
@wbrowne Can I work on this issue?
I have past experience in PostgresQL.
And really want to contribute to this repo. This looks like a Quick fix to me.

**Comment by kirederik** [comment]
Hey @kitarp29,

The code for the Postgres plugin is [here](https://github.com/grafana/grafana/tree/main/public/app/plugins/datasource/postgres). The plugin will communicate with the backend through [here](https://github.com/grafana/grafana/blob/main/pkg/api/metrics.go#L23).

Let us know if you no longer plan to work on this one (I realise it has been a while since you volunteered).

Thanks!

**Comment by kitarp29** [comment]
Hi, I will look over this on the weekend if you guys don't mind.
I have college and internships during weekdays. I make time for Open Source on weekends only.
Thanks for the guidance @kirederik .

**Comment by kitarp29** [comment]
@kirederik @wbrowne 
I looked into all the files as far as I could.
AFAIK PostgreSQL allows adding strings with whitespace by default unless explicitly said to do otherwise.
There are several ways that whitespaces can be denied. Some that I could find were:
- Using a regex validator while creating a username
- using the TRIM function

Might be more.
It would be more helpful if you could help me direct to the schema of the project's DB

**Comment by kitarp29** [comment]
ping

**Comment by wbrowne** [comment]
Apologies for the delay @kitarp29. https://github.com/grafana/grafana/tree/main/pkg/services/sqlstore is the most relevant package here. If you want to see more detail in how the schema is made, you can follow the migrations defined [here](https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/migrations/migrations.go)

If you're looking for where the connection string is defined for PG then you can find that [here](https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/sqlstore.go#L289). We're use XORM as our ORM and the issue I found with this I detailed [here](https://gitea.com/xorm/xorm/issues/2010) - when I looked into this issue before it was limited by the fact that we'd need to upgrade XORM - which would be a significant effort. Feel free to investigate though and happy to hear your findings 😄

**Comment by kitarp29** [comment]
@wbrowne Why are we still using xorm?
We have got more efficient packages in Golang to query dbs.

**Comment by wbrowne** [comment]
@kitarp29 It's just a matter of different priorities

**Comment by kitarp29** [comment]
What's your advice?
How should I go forward with this?
Update XORM?

**Comment by wbrowne** [comment]
@kitarp29 I think you've reached the point I did where it's not so trivial to proceed. I think updating XORM is opening a can of worms right now and something we would have to agree on internally and approach delicately. In the context of this issue, I don't believe there's much else we can do for the time being unfortunately.

Thank a lot for taking the time to investigate this issue though.
