### ISSUE TITLE
[TimeSeries] Style -> Bars -> wrong width 

### ISSUE THREAD

**Issue by baur** [grafana/grafana#37192]
**What happened**:

In bar style shows wrong width (in screenshot second panel is repeted)
I think this is related with record count, wrong width when only 1 record, becurse top panel shows normal width

![image](https://user-images.githubusercontent.com/2898361/126939453-ac85591c-c209-4e7b-b1a3-468d972d8e5c.png)

![image](https://user-images.githubusercontent.com/2898361/126939339-55a81fec-8a61-40c2-a0ae-565ca5f48fce.png)

**What you expected to happen**:
With as top panel, with within one day 

**How to reproduce it (as minimally and precisely as possible)**:
Bar mode with only one record (DS: MSSQL)

**Anything else we need to know?**:

`{
  "id": 60,
  "gridPos": {
    "h": 7,
    "w": 7,
    "x": 17,
    "y": 12
  },
  "type": "timeseries",
  "scopedVars": {
    "StructureID": {
      "text": "Жомарт",
      "value": "37",
      "selected": false
    }
  },
  "transformations": [],
  "pluginVersion": "7.5.1",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "bars",
        "lineInterpolation": "linear",
        "barAlignment": 0,
        "lineWidth": 1,
        "fillOpacity": 56,
        "gradientMode": "hue",
        "spanNulls": false,
        "showPoints": "always",
        "pointSize": 8,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "scaleDistribution": {
          "type": "linear"
        },
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false,
          "graph": false
        },
        "thresholdsStyle": {
          "mode": "off"
        },
        "lineStyle": {
          "fill": "solid"
        }
      },
      "color": {
        "mode": "palette-classic"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "mappings": [],
      "noValue": "нет данных",
      "unit": "short"
    },
    "overrides": []
  },
  "options": {
    "tooltip": {
      "mode": "multi"
    },
    "legend": {
      "displayMode": "hidden",
      "placement": "bottom",
      "calcs": []
    },
    "graph": {}
  },
  "targets": [
    {
      "alias": "",
      "format": "time_series",
      "rawSql": "SELECT FactDateUTC as time ,DayFactCnt as value\n  FROM Nutrition.vDayPlanFact\nWHERE\n  $__timeFilter(FactDateUTC) and StructureID=$StructureID\nORDER BY\n FactDateUTC ASC",
      "refId": "A"
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "repeatPanelId": 17,
  "repeatIteration": 1627278788814,
  "repeatedByRow": true,
  "datasource": null
}`

**Environment**:
- Grafana version: v8.0.2 (5c5d45e19f) (same at v8.1 beta2)
- Data source type & version: MSSQL
- OS Grafana is installed on: Windows10
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by baur** [comment]
With 1 record

![image](https://user-images.githubusercontent.com/2898361/126940550-e1920b43-9a84-45fa-9d0b-6b299c377c49.png)

With 2 record

![image](https://user-images.githubusercontent.com/2898361/126940580-c4a69416-cc95-40d2-a1c3-0f213418b285.png)

**Comment by torkelo** [comment]
You have to group by a time interval that can inject some null values for Grafana to know the time interval for each value

**Comment by baur** [comment]
> You have to group by a time interval that can inject some null values for Grafana to know the time interval for each value

I can't catch about `group by a time interval`
but inserted null by union, only one null not helps, two null values gives effect but bars become very thin 

union all select util.fConvertUnixToDateTime($__from), null   
union all select util.fConvertUnixToDateTime($__from), null   

![image](https://user-images.githubusercontent.com/2898361/126970881-ba2dac6b-05fe-4c4e-a476-f3229e7dfdfd.png)

**Comment by axelavargas** [comment]
Hello @baur 👋🏾 ,

After investigating this issue, we believe there is a misunderstanding in how the bar styles work in TimeSeries (we will update the documentation to prevent this in the future).

**Your Data** 
Time                          |      value        |
------------------------------|-------------------|
12-05-2021 00:00:00           |    2              |


**Graph TimeSeries as bars**

When we choose this style of visualization, we should keep in mind the different options of alignments:

- Before-> bar is drawn before the point
- Center-> bar is drawn around the point (default value)
- After-> bar is drawn after the point

![defaultBarAligment](https://user-images.githubusercontent.com/239999/127449182-c6c8bdac-8fe9-4f68-b088-43e7488f39db.png)


**The missing information that caused the confusion**

**The bar widths in time series have no meaning.** why? how wide is a single datapoint at 2am? is it 10px? 100px? 1000px? the widths are chosen to occupy 60% of the available chart width.

So this means the bars are all technically "0" width since they don't represent duration. so we just pick a width that fills 60% of the space. if there are 10 datapoints, then each bar will be 6% of the total width. if there is 1 bar it will be 60%.

I think is worthy to remember that a TimeSeries is a sequence of measurements, ordered in time. Ideally, we use this visualization to see the big picture of specific measurement (CPU, memory usage, or for example a sensor that measures temperature), this is a very nice [intro to timeseries](https://grafana.com/docs/grafana/latest/basics/timeseries/) I found about this topic.

I hope this clarifies the issue. I am linking the [documentation](https://grafana.com/docs/grafana/latest/panels/visualizations/time-series/) as well (we will update it to include what I just mention about the bar width with no meaning).

**Comment by baur** [comment]
@axelavargas  

Thank you for answer! 

Yes, First of all Grafana is time series data tool but we using it as BI
