### ISSUE TITLE
Client unable to establish websocket connections to /api/live/ws. Server responds by status 403 during handshake

### ISSUE THREAD

**Issue by meena-erian** [grafana/grafana#37247]
**What happened**:
Client unable to establish websocket connections to /api/live/ws. Server responds by status 403 during handshake

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new docker container from the docker image grafana/grafana or build the source code into a docker image and run it.
2. Open the grafana instance from the mapped port using your web browser
3. Open the browser's developer tools and expand the "Console" tab
4. Log in to grafana

**Environment**:
- Grafana version: Grafana v8.0.6 (68fe9e3431)
- OS Grafana is installed on: Docker (Alpine or Ubuntu Same issue on both)
- User Browser: Google Chrome, Firefox, or Microsoft Edge

**Comment by FZambia** [comment]
@meena-erian hello!

Check out issue #36929 , also a known bug for origin with 443 port #36822 (with workaround over `[live] allowed_hosts` and should be fixed as of v8.1.0 beta 2). Closing this since this looks like a duplicate – if provided links won't help you to configure origin check please reopen this issue and provide a WARN line from Grafana server logs with a message `Request Origin is not authorized` (this is printed on every unsuccessful websocket request with 403 status code).
