### ISSUE TITLE
Quotes ("") Required in manual Dashboard variables for Azure Logs

### ISSUE THREAD

**Issue by ehuggz** [grafana/grafana#37357]
**What happened**:
When creating manual Dashboard variables for use in Azure Log queries, quotes ("") are required for query to work without failure.

**What you expected to happen**:
Manual Dashboard variables used for Azure Log queries should work without explicitly defining quotes as it does in other data sources

**How to reproduce it (as minimally and precisely as possible)**:
1. Create manual Dashboard query variable \<value\> without quote
2. Insert variable into Azure Log Query
3. Query fails
4. Add quotes to manual query variable \<value\>
5. Rerun query, query succeeds

**Anything else we need to know?**:
Including quotes as part of variable value inserts quotes into Dashboard titles - which is ugly.

**Environment**:
Grafana Pro 8.0.6

**Comment by joshhunt** [comment]
When including the variables in the query, the variable is just replaced as-is. If you're using the variable as a string, you will need to make sure you wrap the variable in the query with quotes if the variable should be treated as a string within the Kusto query.

![image](https://user-images.githubusercontent.com/46142/130090239-2c30bfb5-75c5-4fe3-ad28-ab1c8f7d13e8.png)

It should be enough to just wrap the variable macro in quotes, rather than include quotes in the variables value, that way it will not look ugly in the panel title.
