### ISSUE TITLE
feature request: data-point comment

### ISSUE THREAD

**Issue by peterroshouse** [grafana/grafana#3746]
I'd like a way to add a small comment to a particular point on a graph. My use case would be for identifying significant changes in the data over time. Point at a spike or trough and something like right-click -> add comment. Type in a short comment/link etc. and then there'd be something like a data point icon on that spot for future reference in weeks/months to come. If you point at the icon, the comment would pop up. This would be somewhat akin to the 'comment' feature in an excel spreadsheet.

Of course add/modify/change comments would be needed too.

Thanks

**Comment by nopzor1200** [comment]
I like the idea of using Grafana to visually 'mark'/'annotate' datapoint(s) on particular panels, especially when you're collaborating/sharing/snapshoting.

Don't you think that rather than adding comments to a particular "point", adding comments to a particular time range (the incident could be short or long) would be better?

Our own @dieterbe had what I thought was a pretty cool concept a while back: https://vimeo.com/121497776 (it was for marking a panel range as crit/warn/ok, but the concept is similar)

**Comment by thomastaylor312** [comment]
+1 For this idea. I think that a time range would probably be the best. You could turn a range into a single "point" by making it small enough

**Comment by utkarshcmu** [comment]
This can be used to implement the above mentioned feature:
http://www.flotcharts.org/flot/examples/interacting/index.html

**Comment by mattttt** [comment]
Time ranges feel like they make a bit more sense to persist in the panel even if the query/queries change (even mildly).

**Comment by thomastaylor312** [comment]
@mattttt I think it would be useful to have both kinds. Sometimes you want to annotate a specific event and so it should stay with the specified frame. Other times would be more what you are describing, where you want to annotate a specific part of the graph.

**Comment by torkelo** [comment]
this is a great idea, would like to have something like this.

Will close as this is similar to https://github.com/grafana/grafana/issues/1286
