### ISSUE TITLE
High resolution samples are overlapping on the X axis

### ISSUE THREAD

**Issue by hooliowobbits** [grafana/grafana#37514]
If i run the following query in influxdb i get the following rows.  note that the time resolution is very small.
```
> select * from "NOM_ECG_ELEC_POTL_II" where time > 1615517931325578239 limit 5
name: NOM_ECG_ELEC_POTL_II
time                NOM_ECG_ELEC_POTL_II
----                --------------------
1615517931325578240 8216
1615517931325725952 8177
1615517931327578112 8219
1615517931329576960 8217
1615517931329724672 8178
```
if i do a graph of the same query in grafana, i get a very weird result.  

![image](https://user-images.githubusercontent.com/3781911/128118748-a9be17e7-03db-40b7-b7ad-f34547a8f74d.png)

four of the 5 samples are overlapping on the X axis.  This leads to some very weird looking results when we zoom out:

![image](https://user-images.githubusercontent.com/3781911/128118961-043480b1-6922-4059-b320-9a1412154893.png)

there should be no vertical lines at all; these aren't present in the source data.

**Comment by oscarkilhed** [comment]
Looks like you're using data with nanosecond resolution. The time series graph only supports millisecond data as far as I know, the overlapping occurs because the time field is truncated. You could try using the XY chart. Using the data from your first example it looks like this:
![image](https://user-images.githubusercontent.com/468940/129152646-d137bdb4-bafc-4997-87fc-5a16cb885635.png)

The XY chart is currently in alpha, you can learn how to enable alpha panels here: https://grafana.com/docs/grafana/latest/administration/configuration/#enable_alpha
