### ISSUE TITLE
State Timeline: Memory leak 

### ISSUE THREAD

**Issue by yamagoya** [grafana/grafana#37573]
**What happened**:
Growing memory consumption when page using the State Timeline panel refreshes frequently

**What you expected to happen**:
No change in memory use.

**How to reproduce it (as minimally and precisely as possible)**:
I am experimenting with replacing Natel Energy's "Discrete" panel with the "State Timeline" panel.

I collect IP ping times for 7 ip addresses every 15s in a Postgresql database (using Zabbix).  Using the State Timeline panel with the Postgresql datasource I map the latest 6 hours of these values to 6 discrete colors and display in seven rows.  I tell Grafana to refresh the data every 5 seconds.  When the browser window is left open, memory is consumed at a rate of about 1GB/hr.  That happens whether the Grafana page is displayed in Firefox or Chrome.

A nearly identical page using Natel Energy's Discrete panel that presents the same data the same way and also refreshes every 5s does not exhibit this memory consumption.

Here is a graph of available system memory (memory decreases as the browser process uses more).  Firefox was running the State Timeline page from ~10:15 to ~15:45.  Chrome was running the same page from ~15:45 to ~18:00.  Firefox was running the alternate page using the Natel Energy Discrete panel from ~18:00 to ~20:00.

![Screenshot_2021-08-04_20-11-51a](https://user-images.githubusercontent.com/15166445/128282246-20f823a4-994b-4706-81d6-a7d583607d34.png)

**Anything else we need to know?**:
**Environment**:
- Grafana version: 8.0.6
- Data source type & version: Postgresql (whatever comes with Grafana-8.0.6)
- OS Grafana is installed on: Ubuntu-18.04 
- User OS & Browser:  Ubuntu-18.04 / Firefox-90.0 / Chrome-92.0.4515.107
- Grafana plugins:
- Others:

**Comment by leeoniya** [comment]
indeed, there's something going on here:

![image](https://user-images.githubusercontent.com/43234/128285806-340c99b9-75d8-4ddb-ba50-9ba70fa1921e.png)

similar settings but with timeseries looks ok:

![image](https://user-images.githubusercontent.com/43234/128286038-d0f6dacd-968c-402a-8d97-f84146cbbf19.png)

**Comment by leeoniya** [comment]
narrowed it down to somewhere in `<TooltipPlugin>` in https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/state-timeline/StateTimelinePanel.tsx

if TooltipPlugin is commented out, we're good again.

![image](https://user-images.githubusercontent.com/43234/128289973-3cfdd762-4d51-4b85-abfd-36116b0abd2d.png)

**Comment by dprokop** [comment]
Tried to debug this a bit and my finding so far is that the leak might be caused by the [setCursor hook added when there is a custom tooltip position interpolator added](https://github.com/grafana/grafana/blob/0e3fb55caa35e1594457e5b71414ba7933b48dd8/packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx#L98)

Here are profiles collected with and without [this piece of code](https://github.com/grafana/grafana/blob/0e3fb55caa35e1594457e5b71414ba7933b48dd8/packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx#L98-L115)

|with(leaking)|without(probably not leaking)|
|-|-|
|<img width="1248" alt="Screen Shot 2021-08-18 at 13 56 12" src="https://user-images.githubusercontent.com/2376619/129894529-4eaa0206-875d-41d6-99b9-d85edf68fddb.png">|<img width="1248" alt="Screen Shot 2021-08-18 at 13 55 15" src="https://user-images.githubusercontent.com/2376619/129894575-b5a21911-3921-4303-b451-b24439bb1b3a.png">|

The surprising thing to observe about the above is that during the profile collection the setCursor hook was never actually performed, as there were no interactions with the panel itself other than dashboard refreshes.
