### ISSUE TITLE
influxdb : GROUP BY time(auto) too granular.

### ISSUE THREAD

**Issue by steverweber** [grafana/grafana#3763]
I'm not sure how of if this is possible already...

It would really nice if "auto" in GROUP BY time(auto) could be mathematically tweaked to be less granular. (when viewing ~1month of data the query can be slow)

I do understand I could change the value from auto to a static value like 1h,
But perhaps enable something like:
"GROUP BY time(auto * 2)"
or a quick fix :)
"GROUP BY time(auto_0.5x)"
"GROUP BY time(auto_1x)"
"GROUP BY time(auto_2x)"
"GROUP BY time(auto_4x)"
"GROUP BY time(auto_10x)"

**Comment by torkelo** [comment]
auto is set so that you get 1 datapoint per pixel on the graph and if intervals are rounded up to a nice even group by time interval. 

If your influxdb queries are slow on large time ranges, maybe it could be solved by adding a rollup? I know rollups are tricky with influxdb (compared to graphite). 

Is the performance difference big between group by time 1h compared to 6h? Might be an issue with InfluxDB that they need to fix, I mean unless you have rollups it needs to read the same data, very little difference

**Comment by steverweber** [comment]
yes performance of influxdb is the issue, would aid continuous queries,

however performance in general becomes an issue when a dashboard has lots of points to render. auto_x2 would give a good performance boost to slow javascript engines with little to no change in what the user sees on their screen.

Some of my users running large 4k screens basically see no difference between 1 and two pixels, but they do see the network lag when updating charts.

**Comment by steverweber** [comment]
nm
/likely just slow influxdb/
