### ISSUE TITLE
Cannot save alert to different folder

### ISSUE THREAD

**Issue by valenvb** [grafana/grafana#37648]
**What happened**:

Moving an alert between folders by changing the Folder under Alert Type results in an error: `Failed to save rule: Not found`

**What you expected to happen**:

I expect to be able to save to a different folder in order to move the alert.

**How to reproduce it (as minimally and precisely as possible)**:

- have >=2 folders
- create an alert in one folder, save it
- edit the alert, change the folder to some other folder, hit save
- error dialog shows up in top right

**Environment**:
- Grafana version: 8.1.0
- Data source type & version: any
- OS Grafana is installed on: Docker on Centos7
- User OS & Browser: Ubuntu/Firefox
- Grafana plugins: none

**Comment by BradleyDHobbs** [comment]
Same thing happening for me

**Comment by kylebrandt** [comment]
Are you able to check the Grafana server logs and see if there is an error when this happens?

Also are you able to share any of the response / request from your browser inspector network tab?

Was not able to reproduce this locally - perhaps an issue with folder permissions on the folder you are trying to move to?

**Comment by bio** [comment]
I have the same issue after upgrading grafana to the latest version and migrating legacy alerts to unified.

error from the /var/log/grafana/grafana.log below
```
t=2021-12-10T18:57:36+0000 lvl=info msg="Request Completed" logger=context userId=2 orgId=1 uname=myusername1 method=DELETE path="/api/ruler/grafana/api/v1/rules/Migrated {\"dashboardUid\": \"7P30FESGk\", \"panelId\": 18, \"alertId\": 188}/SERVER1 - Disk usage mapper/vg1-lvol2 [/data/sites] usage (Percentage) alert" status=404 remote_addr=127.0.0.1 time_ms=2 size=29 referer="http://myserver1.com/alerting/sFO5Tbh7z/edit?returnTo=%2Falerting%2Flist"
```

**Comment by yuri-tceretian** [comment]
I am pretty sure there was another error before you got `Failed to save rule: Not found`. I just encountered this when tried to change the folder for an alert with a name that already existed in the target folder. I ended up losing the alert rule that I was trying to move. That happens because of the way API is designed: 
- when the user changes folder for an existing rule, UI sends a DELETE request to remove the rule from the previous folder and then sends a request to add a rule to the target folder. If the second request fails then the alert is gone from the database.

I see two possible scenarios to fix it:
1. (quick) update UI to send requests in the opposite direction: POST and then DELETE, so the user won't lose alert if POST fails.
2.  change API to handle individual rules and accept namespaces as a field. This will have another benefit: the folder can contain any characters.
3. Add a special API endpoint to move alert from one endpoint to another (not RESTful).

**Comment by alexweav** [comment]
FWIW, @yuri-tceretian's option number 2 feels  like the right way to go. In a typical REST API I'd expect to issue a single PUT request against an ID to do something like this. Right now it feels like we're forcing the caller to use deletes to work around the fact that the API is built around a natural key.

There is also the upcoming FGAC to worry about. It's very unnatural for the user to need Delete permissions to be able to change the name/bucket of a resource.

**Comment by yuri-tceretian** [comment]
I agree. As a quick fix we can implement 1. Changing API is much harder job which will take more time.

**Comment by gillesdemey** [comment]
Agreed that this should be a backend API change but we can create a quick fix to avoid losing alert rules.

**Comment by yuri-tceretian** [comment]
Adding it to frontend project. Let's address it in UI, and then we will work on API.
