### ISSUE TITLE
Loki: Log context doesn't work with queries that use parsers

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#37736]
**What happened**:
in explore view, when looking at loki logs, i click "show context" and get an error
**What you expected to happen**:
see the context
**How to reproduce it (as minimally and precisely as possible)**:
on our internal grafana labs ops instance, use this query:
```
{app="metrictank",cluster="hm-us-west2",role="write"} |= "number of purged (deleted) metrics from tank" | pattern "<_> <_> <_> <_> <_> <_><_> <foo>"
```
get some logs, and hit "show context". sometimes it seems to work, but usually it doesn't. I think that adding more `<_>` to the pattern may be related to it breaking

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.0 
- Data source type & version: Loki
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:
using firefox query inspector, you can see that grafana issues a request, but the it gets a http 400 back with this body: 
```
parse error at line 1, col 249: literal not terminated
```

**Comment by Dieterbe** [comment]
![context_000](https://user-images.githubusercontent.com/20774/128865838-e90d3d93-bf58-46f8-a244-c5a438ea1c7b.png)

**Comment by ivanahuckova** [comment]
@Dieterbe you actually discovered bigger bug - log context doesn't work with any parser. When we use parsers, we create parsed labels, and in frontend, we don't know which label is actual and which one is parsed. So when creating context query, we use all labels and return (usually) no results. However in pattern parser, the parsed label + value can have any form and therefore this specifically threw `literal not terminated`. But the issue is that we shouldn't use parsed labels.

**Comment by Dieterbe** [comment]
Glad I could help to uncover that :D thanks Ivana!

**Comment by ivanahuckova** [comment]
@cyriltovena @davkal  Maybe you'll have any thoughts on solutions for this.

The problem is that we are creating context query from the specific log row. The way how we currently do it is mapping over all labels and creating query out of it - e.g. if these are labels: 

```
cluster: "ops-us-east-0"
container: "app"
debug: "true"
```

the resulting query will be `{cluster="ops-us-east-0", container="app", debug="true"}`. This way we receive all rows in that log stream (ignoring filtering expressions). However, with the log parsing, we get parsed labels and these can't be used as actual labels. 

One idea I had was to use just common labels and ignore unique labels, as unique labels , but I am not sure if it is correct for log context and if it would cover all problems. 

This is how LogsRowModel that we use to create context query looks like:
```
export interface LogRowModel {
  // Index of the field from which the entry has been created so that we do not show it later in log row details.
  entryFieldIndex: number;

  // Index of the row in the dataframe. As log rows can be stitched from multiple dataFrames, this does not have to be
  // the same as rows final index when rendered.
  rowIndex: number;

  // Full DataFrame from which we parsed this log.
  // TODO: refactor this so we do not need to pass whole dataframes in addition to also parsed data.
  dataFrame: DataFrame;
  duplicates?: number;

  // Actual log line
  entry: string;
  hasAnsi: boolean;
  hasUnescapedContent: boolean;
  labels: Labels;
  logLevel: LogLevel;
  raw: string;
  searchWords?: string[];
  timeFromNow: string;
  timeEpochMs: number;
  // timeEpochNs stores time with nanosecond-level precision,
  // as millisecond-level precision is usually not enough for proper sorting of logs
  timeEpochNs: string;
  timeLocal: string;
  timeUtc: string;
  uid: string;
  uniqueLabels?: Labels;
}
```

**Comment by ivanahuckova** [comment]
Any thoughts on this @davkal @cyriltovena @slim-bean?

**Comment by ivanahuckova** [comment]
@davkal @cyriltovena @slim-bean @owen-d  Do you think creating log row query based on all labels ignoring the unique labels would be correct or no? Can you think of any other way how could we solve this?

**Comment by owen-d** [comment]
This is difficult without us distinguishing between index labels and parsed labels in the API. I don't think this is actionable at the moment, but it's a good datapoint for us to consider as we improve Loki.

re: common labels, how would you determine these?

**Comment by Dieterbe** [comment]
Thank you @ivanahuckova !!
