### ISSUE TITLE
Unified Alerting: Some Labels from datasources like Elasticsearch break notifications

### ISSUE THREAD

**Issue by dmit2k** [grafana/grafana#38055]
Using Grafana 8.1.0 with ngalert option enabled and with two Contact points created (Webhook type and Alertmanager type).

While everything works as expected with Prometheus datasource (template variables are expanded correctly and firing alerts sent to both contactpoints - see ref #37836), things broke with Elasticsearch datasource:

1) template variables like {{ $values.C.Value }} etc not being expanded in alerts

2) alerts are firing OK and can be seen in Grafana UI but not being sent to contactpoints

![grafana-ua-elk](https://user-images.githubusercontent.com/1772195/130024905-27e52265-9131-4f7d-a28d-ffde379c6652.jpg)

**Comment by MannChris** [comment]
I have the same issue(s) using Grafana 8.0.6 (with ngalert)

**Comment by dmit2k** [comment]
Further investigation narrowed down the bug: it fails if the label names contain dot, in my case {{ $labels.vhost.keyword }}

When I remove that label from message template it expands other variables fine, but still does not send alerts to contactpoints.

**Comment by kylebrandt** [comment]
Since these are based on go templating, periods are reserved in the Go template language. You should be able to do `{{ index $labels "vhost.keyword" }}` - does that work?

**Comment by arkadiusz-bach** [comment]
@kylebrandt it worked for labels but did not work for values, also as mentioned above alert is not being passed to contactpoints and in the logs there is information that it failed to put alerts in the notifier because label is invalid:
```
lvl=eror msg="failed to put alerts in the notifier" logger=ngalert count=1 err="invalid label set: invalid name \"hadoop.datanode.Hostname\""
```

**Comment by kylebrandt** [comment]
Thank you for that information, very helpful in clarifying for me.

The problem is our integration of Labels with Alert Manager Prometheus. The prom code has the following restrictions on label names:

```
// LabelNameRE is a regular expression matching valid label names. Note that the
// IsValid method of LabelName performs the same check but faster than a match
// with this regular expression.
var LabelNameRE = regexp.MustCompile("^[a-zA-Z_][a-zA-Z0-9_]*$")
```

So this restrictions needs to be considered. I see two choices:
 - We modify the Labels to be compatible. 
 - Extend (or just allow) at least Alert Managers notion's of an acceptable label name to include a larger character set 
 
Since there are a lot of possible characters from different data sources, I worry about doing label modification in a way the doesn't create collisions etc. I would also be concerned about the ability to link back to things from data generated from alerts. (Maybe this could be work around with some sort of annotations, but would be hacky).

I am less sure about trade offs on expanding the alert manager side - @gotjosh ?

**Comment by dmit2k** [comment]
> Since these are based on go templating, periods are reserved in the Go template language. You should be able to do `{{ index $labels "vhost.keyword" }}` - does that work?

Sorry, was able to test your hint only now. 

Yes, the trick with {{ index $labels "field.name" }} worked just fine, and I can also get the value of a query with {{ $values.B.Value }}

But the alert still not being passed to contactpoints (both Alertmanager-type and **Webhook-type**)

**Comment by dmit2k** [comment]
> The problem is our integration of Labels with Alert Manager Prometheus. The prom code has the following restrictions on label names:

Let me point out that it is broken not only for Prometheus Alertmanager contact point, but for Webhook as well! Not tested with other contactpoint type though.

**Comment by kylebrandt** [comment]
> Let me point out that it is broken not only for Prometheus Alertmanager contact point

Yes this is expected with the problem I described. The reason is that the new Grafana 8 embeds alert manager for the Grafana Managed Alerts, and all notifications from those rules go through the embedded alert manager (regardless of contact point). So  notifications policies and contact points in UI are alert manager under the hood.

**Comment by duylong** [comment]
Same issue with fields that have dots in Elasticsearch, I'm happy to see that a topic has been opened.

Has anyone found a workaround without creating any new fields?
