### ISSUE TITLE
Unable to install agenty-flowcharting-panel-0.9.0 on Grafana 8.x.x

### ISSUE THREAD

**Issue by Coder63** [grafana/grafana#38052]
**Steps to reproduce**:
Install Grafana operator integreatly/grafana-operator:v3.8.1
Installed Grafana 8.0.0
Unable to find flow chart plugin 

**Actual Result**:
Panel not found 

**Expected Result**
Drop down with flowcharting.

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: 8.0.0, 8.0.7, 8.1.1
- Data source type & version:
- User OS & Browser: 
- Others: Installed grafana using operator integreatly/grafana-operator:v3.8.1

**Comment by zuchka** [comment]
Hi @Coder63,

[The Grafana Operator project](https://github.com/grafana-operator/grafana-operator) is not maintained by Grafana Labs but is a third party project. If you continue to experience issues using that tool, I think your best path forward is to make a bug report [in that repo](https://github.com/grafana-operator/grafana-operator).

If you feel that this problem is specific to Grafana OSS and is reproducible without Grafana Operator, then we can re-open this issue and continue investigation. Thank you! 👍 

fwiw I was able to install that plugin on v8.1.1 via Docker Compose and the Plugin admin. I haven't tried deploying to k8s, however.
