### ISSUE TITLE
LDAP: support for nested groups

### ISSUE THREAD

**Issue by mike-sol** [grafana/grafana#3808]
It would be really excellent if nested groups were supported by the LDAP implementation. It seems that, at present, users must be direct members of any referenced LDAP group in order to get access / role assignment. 

This doesn't mesh well with the common access control pattern wherein one would define a group, e.g. "Grafana Admins", and nest within it existing groups that should have admin rights.

**Comment by choooze** [comment]
I'm also interested.

**Comment by timgriffiths** [comment]
+1

**Comment by druchoo** [comment]
+1

I was just trying to figure this out with no success. Tried using LDAP_MATCHING_RULE_IN_CHAIN 

`  (&(objectClass=group)(member:1.2.840.113556.1.4.1941:={0})) where the {0} value is the DN of the particular user.`

but that doesn't appear to be implemented? Not sure it would work anyway since you need to somehow obtain the user's DN.

**Comment by XakRu** [comment]
me too.

**Comment by hubby2004** [comment]
+1
