### ISSUE TITLE
Users with role "viewer" can add organizations

### ISSUE THREAD

**Issue by dennisjac** [grafana/grafana#3832]
I'm currently getting familiar with the user/organization structure of Grafana and noticed that a user that is added as a "viewer" to an organization can add additional organizations which seems strange to me since the role name suggests that the user can only view and not modify things.
Am I mistaken in this assumption and this is a bug or is this intentional.

Also there seems to be no way to delete the new organization. I could only find and delete it as a Grafana administrator.

**Comment by torkelo** [comment]
The role `Viewer` is only the role for the user within an organization. Grafana is a multi tenant system in that a user can be connected to multiple orgs. So just because the user is a Viewer within one org does not mean the user cannot create an organization for itself (and become Admin for that new Org). 

You can disable the ability for users to create new organization in grafana.ini 
http://docs.grafana.org/installation/configuration/#allow_org_create

If this is disabled on the grafana server admin can create organizations. 

You are right there are currently no way to delete organizations except by the grafana server admin,

**Comment by bato1985** [comment]
Hy torkelo i have Grafana 4.1.2, I set auto_assign_org = false and restarted grafana-server but still non admin users can create new organizations.
What alse can I do to disable that?
Any suggestions?

**Comment by torkelo** [comment]
http://docs.grafana.org/installation/configuration/#allow-org-create
