### ISSUE TITLE
Grafana v8.1.2 does not connect to Influxdb2.0 with fluxQL

### ISSUE THREAD

**Issue by msiemers** [grafana/grafana#38412]
FluxQL login attempt results in "InfluxDB Error: Bad Request"

My Settings:

<img width="1251" alt="Bildschirmfoto 2021-08-21 um 10 44 42" src="https://user-images.githubusercontent.com/34999079/130316306-c3be2ab4-17da-4c53-99b1-887409a2e22a.png">

I don't know what else to do. I have entered my Influx user as a user and saved the token that is stored in Influx as the password.

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: influxDB 2.08
- OS Grafana is installed on: ubuntu
- User OS & Browser: Mac/Safari
- Grafana plugins: 
- Others:

**Comment by gabor** [comment]
hi @msiemers , an influxdb database can be used either in "Flux" mode or in "InfluxQL" mode.
the InfluxDB version you mentioned uses "Flux" mode by default. if you want to connect to it in "InfluxQL" mode, there are some extra steps needed, you can see them described here: https://docs.influxdata.com/influxdb/v2.0/tools/grafana/#configure-grafana-to-use-influxql

alternatively, if you would like to connect in Flux mode, you can see the needed steps here: https://docs.influxdata.com/influxdb/v2.0/tools/grafana/#configure-grafana-to-use-flux

does this help?

**Comment by msiemers** [comment]
Ok i will try it.

**Comment by msiemers** [comment]
> hi @msiemers , an influxdb database can be used either in "Flux" mode or in "InfluxQL" mode.
> 
> the InfluxDB version you mentioned uses "Flux" mode by default. if you want to connect to it in "InfluxQL" mode, there are some extra steps needed, you can see them described here: https://docs.influxdata.com/influxdb/v2.0/tools/grafana/#configure-grafana-to-use-influxql
> 
> 
> 
> alternatively, if you would like to connect in Flux mode, you can see the needed steps here: https://docs.influxdata.com/influxdb/v2.0/tools/grafana/#configure-grafana-to-use-flux
> 
> 
> 
> does this help?

Sorry it doesn't work for me. 

I try the Authetication Method. I don't know what works wrong?

**Comment by gegtor** [comment]
Same thing here

<img width="924" alt="Screenshot 2021-08-24 at 01 51 30" src="https://user-images.githubusercontent.com/10978723/130533997-256edffb-0c12-41cc-a595-decbb8983d0d.png">

**Comment by gabor** [comment]
hi @gegtor , your problem is slightly different from @msiemers , you are using Flux mode, not InfluxQL mode.

the extra fields are not mandatory. the following fields should be enough for you to have a working connection:
- URL (in the HTTP section)
- Organization (in the influxdb_details section)
- Token (in the influxdb_details section)

there are specialized instructions for connecting to influxdb-cloud on the influxdata website, could you doublecheck those? ( https://docs.influxdata.com/influxdb/cloud/tools/grafana/#configure-grafana-to-use-flux )

if you think everything is configured correctly and it still does not work, you will have to look at the debug-logs from the grafana-server to find out more info, see here how to enable it ( https://grafana.com/docs/grafana/latest/troubleshooting/#troubleshoot-with-logs )

**Comment by gabor** [comment]
hi @msiemers , just to be sure, have you created the "InfluxDB DBRP mappings" as described in https://docs.influxdata.com/influxdb/v2.0/tools/grafana/?t=InfluxQL#view-and-create-influxdb-dbrp-mappings ?

if yes, then it should work.

if it still does not work, i recommend enabling the debug-logs in the grafana-server and looking at the logs to see more info, you can read about how to do it here https://grafana.com/docs/grafana/latest/troubleshooting/#troubleshoot-with-logs

**Comment by gegtor** [comment]
@gabor I think I found something in the logs
```
t=2021-08-24T16:14:03+0000 lvl=warn msg="Flux query failed" logger=tsdb.influx_flux err="invalid character '\\x1f' looking for beginning of value" query=buckets()
```

**Comment by gabor** [comment]
@gegtor thanks for the additional info. unfortunately in this case it does not help us to narrow down the problem. (connecting to an influxdb-cloud database from grafana does work for me).

we had this error reported in the past ( https://github.com/grafana/grafana/issues/30193 ) but we were not able to reproduce it. someone at the end of the issue reported that for them the problem was an incorrect token.

i recommend to try these experiments:
1. try to create a new token and use it instead. does it fix the problem?
2. in the grafana-datasource-config-page, set an incorrect token intentionally. are you getting the same error-message in the debug-log?
3. in the grafana-datasource-config-page, set an incorrect organization intentionally. are you getting the same error-message in the debug-log?

**Comment by msiemers** [comment]
I was able to solve the problem now. I did not pay attention to the fact that the password for the HTTP header authorization to be deposited must be entered as "Token API Token from InfluxDB". If this is done in this way, no data need be entered in the lower area.

<img width="1257" alt="Bildschirmfoto 2021-08-25 um 16 44 44" src="https://user-images.githubusercontent.com/34999079/130812348-659fdd5f-6e7f-4be9-a795-03f916c004ce.png">

The only problem I have now is that with Grafana I cannot access the data in the Influx DB.

<img width="590" alt="Bildschirmfoto 2021-08-25 um 16 39 08" src="https://user-images.githubusercontent.com/34999079/130812533-56b76e7a-2672-40c6-843d-d4ae9eb183d4.png">

But when I look in the Influx UI, data is available. What can still be the fault here?

**Comment by msiemers** [comment]
> @msiemers
> 
> it seems something is broken currently on the influxdb-documentation page, and the part i was referring to is missing or does not work. i tried to find a direct link to the part you need, and this should be it: https://docs.influxdata.com/influxdb/v2.0/query-data/influxql/
> 
> you see, influxdb2 organizes data in "buckets". but the InfluxQL language does not understand buckets, only databases. so now for every "bucket" you have to create an "influxql database". i hope this helps.

Sorry, that doesn't work for me. I'am not an expert.

**Comment by alexkar598** [comment]
Fixed the issue by setting "Accept-Encoding: Identity" in the header config. \x1f is the first byte of the gzip magic (1f 8b).
