### ISSUE TITLE
Use shorter date when little space available

### ISSUE THREAD

**Issue by deric** [grafana/grafana#3852]
With narrower span of chart Grafana is currently using longer format (including day and month even it's not neccessary):
![grafana-x-format](https://cloud.githubusercontent.com/assets/138573/12582191/dfd8ecd2-c43b-11e5-971d-808bb7d956a2.png)

(Grafana v2.6.0)

**Comment by daniellee** [comment]
Nice catch! The error is in the graph panel class in the [time_format function](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/graph.js#L439-L459). It takes the width of the panel into account when calculating the date format. The reason for that is the scenario where the width of a narrow panel means it cannot show the same granularity as a wide panel. In the example below the left panel can show seconds while the right panel can only show minutes due to size constraints.

![shortdateissue](https://cloud.githubusercontent.com/assets/434655/12597146/f91d3480-c483-11e5-9973-7bb7f1d678c2.png)

But in your example it doesn't work obviously.

**Comment by deric** [comment]
Well done, thanks!
