### ISSUE TITLE
Pie Chart Legend Shows invalid labels when there is no data

### ISSUE THREAD

**Issue by danieldonoghue** [grafana/grafana#38693]
**What happened**:
grafana 8.1 Pie chart shows incorrect legend when there is no data to show. see attached image

**What you expected to happen**:
When there is no data, there should be no legend and the "no data" (or equivalent) message should be displayed in place of any graph and legend in the panel.

**How to reproduce it (as minimally and precisely as possible)**:
an SQL query that includes time_sec, value and metric with 0 rows returned.

**Anything else we need to know?**:
The object returned from the query shows the following...
```
{
  ...
  "response": {
    "results": {
      "A": {
        "frames": [
          {
            "schema": {
              ...
              "fields": [
                {
                  "name": "time_sec",
                  "type": "number",
                  "typeInfo": {
                    "frame": "int64",
                    "nullable": true
                  }
                },
                {
                  "name": "value",
                  "type": "number",
                  "typeInfo": {
                    "frame": "int64",
                    "nullable": true
                  }
                },
                {
                  "name": "metric",
                  "type": "string",
                  "typeInfo": {
                    "frame": "string",
                    "nullable": true
                  }
                }
              ]
            },
            "data": {
              "values": [
                [],
                [],
                []
              ]
            }
          }
        ],
        "refId": "A"
      },
    }
  }
}
```

Also: the field override to hide columns from the legend displays them as disabled and does not hide them entirely. see attached image

**Environment**:
- Grafana version: v8.1.1 (90c87a52f7)
- Data source type & version: mysql 5.7
- OS Grafana is installed on: official docker image
- User OS & Browser: any browser, Mac OS
- Grafana plugins: none
- Others: n/a

![Screenshot 2021-08-30 at 12 40 51](https://user-images.githubusercontent.com/27728290/131327648-1daa40fd-53f6-4435-a9b3-43cb9b0e3f63.png)

**Comment by crockk** [comment]
I am still seeing this issue in the new Pie Chart Panel with multiple MySQL queries. Not sure if I should open a new issue or not, because it seems to be directly related to the above issue:
![image](https://user-images.githubusercontent.com/58015900/150882556-271af1d2-31e1-4b86-be44-13229115c636.png)

I have 4 MySQL queries. The queries that return no data are appearing in the legend as "time" and "value." 

It might also be worth noting that the chart is completely broken with the old Pie Chart Panel, showing "No data points" with the exact same queries:
![image](https://user-images.githubusercontent.com/58015900/150883042-c8324b0b-6d4e-481e-bf79-aa7f3bede931.png)
