### ISSUE TITLE
[OpenTSDB] Need a default value for fill-policy

### ISSUE THREAD

**Issue by vitorboschi** [grafana/grafana#3877]
All dashboards were broken because of undefined fill policy. I had to enter all dashboards and re-save them to use none in fill policy.

**Comment by vitorboschi** [comment]
Forgot to say, this is in the latest nightly, from 2016/01/28

**Comment by torkelo** [comment]
thanks for reporting this!

**Comment by utkarshcmu** [comment]
Why don't we split Opentsdb into two versions:
1. Pre 2.2
2. 2.2 and above

This fill policy feature came in 2.2. 

The reason I am not working on 2.2 features right now is because we need to decide on how should we move forward with 2.2 changes. We should revert fill policy changes (#3819) for now in my opinion and split the opentsdb datasource first.

What do you guys think?

**Comment by torkelo** [comment]
maybe add a version property to the datasource options?

**Comment by utkarshcmu** [comment]
Yes, that would be perfect and then modifying the queryCtrl according to the version of Opentsdb selected. That works.

**Comment by vitorboschi** [comment]
Adding version looks like a more sane option, as to avoid code duplication. However, this would not remove the need to use sane default values to avoid breaking old dashboards.
