### ISSUE TITLE
Forward OAuth Identity with elasticsearch datasource

### ISSUE THREAD

**Issue by Scotturbina** [grafana/grafana#38843]
**What happened**:

When I turn on the Forward OAuth Identity and try to "Save and Test" it prompts a sign in pop-up, I fill this with my credentials but nothing happens.

I receive this error from chrome dev tools:  `{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/data_source/_mapping]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\" charset=\"UTF-8\""]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/data_source/_mapping]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\" charset=\"UTF-8\""]}},"status":401}`

**What you expected to happen**:

I expect the user credentials being forwarded without the pop-up

**How to reproduce it (as minimally and precisely as possible)**:

I got Open Id as auth method for grafana.
My grafana config looks like this : 
```
[auth.proxy]
enabled = true
    header_name: X-Forwarded-User
    headers: 'Name:X-Forwarded-User Email:X-Forwarded-Email Token:X-Forwarded-Access-Token'
    auto_sign_up = true
    ldap_sync_ttl = 60
[dataproxy]
    send_user_header = true
    logging = true
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.2.1
- Data source type & version: Elasticsearch 7.9.1
- OS Grafana is installed on: REHL 
- User OS & Browser: REHL 8.4 and google chrome
- Grafana plugins:
- Others:

**Comment by kminehart** [comment]
I think you may be mixing up 2 different concepts.

The "Forward OAuth Identity" option is there to allow you to use the OAuth `access_token` issued to the Grafana server in the `Authorization` header of a data source request.

This would be like using a token from "Sign in with Google" in a google-related data source.

Since ElasticSearch is not an OAuth provider, this flow isn't possible in your scenario.

The auth proxy may be want you want in this scenario. I would suggest reading the documentation for that feature here: https://grafana.com/docs/grafana/latest/auth/auth-proxy/

In the meantime I'm going to close this issue. If you think there's a bug in Grafana that's keeping this from working, feel free to open a new issue or comment here.

Thanks!

**Comment by Scotturbina** [comment]
@kminehart I got grafana and elastic setup with Open Id, so it is not possible to pass the ```access_token``` right?
My ultimate goal is to restrict users to data source level, is this possible with auth proxy feature?

**Comment by Scotturbina** [comment]
@kminehart I was taking a look and there is way to pass Grafana's logged user to Elastic, seems this feature was asked here : https://github.com/grafana/grafana/issues/6359 and seems was solved here https://github.com/grafana/grafana/pull/15998 however,  I added in the grafana.ini  the dataproxy config as below, also I have` Access` configured with server
```
[dataproxy]
send_user_header = true
logging = true
```
This is how looks the configuration 
![image](https://user-images.githubusercontent.com/22263714/141532333-4c35ca80-b983-4592-a282-b99a7ce6fb6d.png)

![image](https://user-images.githubusercontent.com/22263714/141532254-50413cb9-10bb-4272-a46c-4585b8a58385.png)

But Grafana keeps asking me for the credentials every time I want to test it as shown below
![image](https://user-images.githubusercontent.com/22263714/141532741-1c9c981a-c68f-4562-90db-c6c53b544e50.png)

Is there something I am doing wrong?
