### ISSUE TITLE
the annotation is not displayed

### ISSUE THREAD

**Issue by bpof86** [grafana/grafana#38848]
**What happened**:
![image](https://user-images.githubusercontent.com/90040438/131994827-a0aa3946-0daa-47f2-8e39-966e08520acb.png)

![image](https://user-images.githubusercontent.com/90040438/131994892-c153a6d1-f785-49d6-926e-e7dfd6e16f56.png)

При создании аннотаций, на промежуток времени, если в отображении графика выбрать промежуток времени большей чем аннотация, то аннотация и подсказка ниже графика отображается корректно, если выбрать отображение данных меньшем чем период аннотации, то не отображается подсказка под аннотацией, при этом фон графика становится в цвет аннотации.

When creating annotations, for a period of time, if you select a time period greater than the annotation in the graph display, then the annotation and the hint below the graph are displayed correctly, if you select the data display less than the annotation period, then the hint under the annotation is not displayed, and the background of the graph becomes the color of the annotation.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: Zabbix
- OS Grafana is installed on: 
- User OS & Browser: Win10, Firefox and Chrome
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
@bpof86 thank you for opening this issue. Indeed, the hint is not displayed if you zoom so that the annotation covers the entire time range. However, as far as I see you are using the old Graph panel. We no longer maintain this panel and we suggest updating your visualizations to the new Time series panel. 

In Grafana 8.1 we have added annotations support to Time series panel, and this issue is no longer present.
