### ISSUE TITLE
Elasticsearch templating query relies on default field

### ISSUE THREAD

**Issue by faxm0dem** [grafana/grafana#3887]
I setup a template variable in grafana 2.6 as discussed *e.g.* in #2696 using the following terms query:

```JSON
{"find": "terms", "field": "host"}
```

This generates the following elasticsearch query:

```JSON
{
  "size": 0,
  "query": {
    "filtered": {
      "query": {
        "query_string": {
          "analyze_wildcard": true,
          "query": "*"
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gte": "1452010777761",
                  "lte": "1454053977761",
                  "format": "epoch_millis"
                }
              }
            }
          ]
        }
      }
    }
  },
  "aggs": {
    "1": {
      "terms": {
        "field": "host",
        "size": 0,
        "order": {
          "_term": "asc"
        }
      }
    }
  }
}
```

As you can see the query grafana generates (but does not give control upon) is `"query": "*"`.
This has the following drawback:

* it relies on the elasticsearch index' `index.query.default_field` setting
* Documents which don't contain the default field will *not* hit the query
* Worst case scenario: if you configure the `default_field` in your index to something inexistent in your documents, the term query returns nothing

So the proposal here is to make the underlying query configurable.

I'd probably go with `Query` and `Term Query` to distinguish between the two
Other solution: add a  "custom" mode where the user can put the whole json of the query (which would obviously need to be templateable)

**Comment by sslupsky** [comment]
I believe you can add a query term as follows?

"query" : "<put your lucene query here>"

**Comment by faxm0dem** [comment]
@sslupsky you're right it works when adding the `"query"` element to the JSON.
I still feel this should make it to a specific UI element. But a documentation clarification would also do.

**Comment by sslupsky** [comment]
@faxm0dem When you say "add the query element to the JSON", do you mean some sort of manual editing of the JSON query?  Or, did you mean add this to the templating "Query" UI element.  The latter is what I did, here is a screenshot:

![screen shot 2016-02-01 at 10 14 45 am](https://cloud.githubusercontent.com/assets/16888734/12724798/c8c62592-c8cc-11e5-9caf-6c083d418e66.png)


+1, I agree with you on the UI element, that would be nice.  I also agree the documentation needs to be updated as well, it was difficult to find this information.

**Comment by sslupsky** [comment]
Another thing that would be nice is to add another query option.  Something like "find": "values", "field": "<fieldname>".  For instance, I have a field that is an analyzed field (in hindsight it does not need to be an analyzed field but since it already is, it cannot be changed).  The values in this field contain several hyphens (i.e.: something like abcd-0123-0ced).  So, Elasticsearch analyzed the field values into dozens of "terms" such as "abcd", "0123", "0ced", etc.  What I want returned is a list of all the unique values in the field returned as the entire value.  Using my example, I would like "abcd-0123-0ced" returned but I am unable to have the templating feature to do this.  

The only two options for the query that I am aware of are

"find": "terms", "field": "<fieldname>" and 
"find": "fields", "type", "string".  

The former syntax returns the individual terms and the latter just returns a list of the fields.

**Comment by faxm0dem** [comment]
I meant adding it to the UI's query element's JSON

**Comment by jaredledvina** [comment]
@sslupsky - Did you find a workaround for that issue? I'm running into the exact thing when trying to use our hostname field which are split with hyphens.

**Comment by sslupsky** [comment]
Hi @jaredledvina ,

Yes, if you use the "raw" fields, you can work around the problem but that may involve reindexing.
