### ISSUE TITLE
N+1 query when syncing alertmanager configs for all orgs

### ISSUE THREAD

**Issue by gotjosh** [grafana/grafana#38885]
Grafana's multi-tenant nature means that each organisation gets their own Alertmanager. To make sure configuration is consistent over time, we have a process that fetches all organisations from the database and then for each organisation, we fetch their alertmanager configuration.

This produces a N+1 query where we'll make 1 query for all organisation IDs, and then 1 query for each organisation to fetch their configuration. I think we can make this better by fetching all active configurations by organisation in 1 single query.

https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/notifier/multiorg_alertmanager.go#L64-L119

**Comment by torkelo** [comment]
@gotjosh remember to add some labels to new issues

**Comment by yuri-tceretian** [comment]
Below is some analysis as well as notes to help me understand the way it works currently.
1. Performance. 
    * Startup. When the service starts it loads all organizations and then configuration of every organization. Although DB access method [GetLatestAlertmanagerConfiguration](https://github.com/grafana/grafana/blob/04d5dcb7c8e043ddfe628ab52ab62da1bcf686ba/pkg/services/ngalert/store/alertmanager.go#L19-L35) seems to assume that there can be many records per organization, the [table specification](https://github.com/grafana/grafana/blob/04d5dcb7c8e043ddfe628ab52ab62da1bcf686ba/pkg/services/sqlstore/migrations/ualert/tables.go#L298) sets a unique index. Therefore, it guarantees that during the start we always want to get all rows from the table.
I do not think that the loading all configurations in one request is a really good idea because the performance and the success of this operation depends on the size of the table `ngalert_configuration`. I would suggest an alternative - load the configs in chunks. The chunk size could be configurable. This functionality is supported on the ORM level. 
The same approach can be leveraged in [schedule](https://github.com/grafana/grafana/blob/7fbeefc090151e5c7a9b4fbfd95d06b08e8d5eef/pkg/services/ngalert/schedule/schedule.go#L177) too. The further improvement could be that both schedule and multiorg_am will use the same result from db.

    * Runtime. The service is running during the entire lifetime of the application. It polls the database every `SyncOrgsPollInterval`. During every poll cycle it does the same as during the initialization - reads all records. We can improve that by leveraging the timestamp fields (fields created_at and updated_at) and read only records that have been changed since the last polling cycle. However, it is worth mentioning that this will add a dependency on the time (eg it will be critical that all instances are in sync) as long as the timestamps are generated locally. The same approach could be used in the schedule too.

2. Consistency. As mentioned above, the current implementation of the "mulitorg_am" fetches the list of organizations and then fetches a configuration for each organization. Effectively, this is a client side inner join. There is no any foreign key constraint on database level, and therefore there is a possibility that fetching only the table `ngalert_configuration` will return more data than we would expect. It looks like in the schedule we do not do "inner-joins". Thus, it may be safe to assume the consistency between table `org` and  `ngalert_configuration`. Personally, I would prefer something less fragile as an assumption (eg create a foreign key or do the "client side join")


Summary
At the startup:
- The simplest solution would be to reuse what the schedule does and just pull all rows from the table. However, in the cloud this can quickly become a problem if the number of organization will be big.
- A little bit more sophisticated solution would be to split to chunks and expose that in the dbstore's interface, so users will have to take care of the proper fetching by themselves. 
- Next level would be to create a channel between dstore and users. This will make fetching asynchronous as well as keep the chunking logic isolated. As a side-effect we will be able to process the configs in parallel as the further improvement.

To optimize db calls during the service lifecycle we can keep the timestamp of the previous fetching cycle in the MultiOrgAlertmanager. During the next polling cycle we will request all records that were updated or created between the previous and the current timestamps. In the case of chunked read, the timestamp should be the time we make the first call in the series. Also, this will require us to add some indices to the table `ngalert_configuration`

**Comment by gotjosh** [comment]
> Startup. When the service starts it loads all organizations and then configuration of every organization. Although DB access method GetLatestAlertmanagerConfiguration seems to assume that there can be many records per organization, the table specification sets a unique index. Therefore, it guarantees that during the start we always want to get all rows from the table.

I don't think this is correct. The table [ngalert_configuration](https://github.com/grafana/grafana/blob/04d5dcb7c8e043ddfe628ab52ab62da1bcf686ba/pkg/services/sqlstore/migrations/ualert/tables.go#L283) is not the same as [alert_configuration](https://github.com/grafana/grafana/blob/04d5dcb7c8e043ddfe628ab52ab62da1bcf686ba/pkg/services/sqlstore/migrations/ualert/tables.go#L254) - I apologise as I can understand the naming scheme is quite confusing.

> The chunk size could be configurable. 

Good shout, feel free to use whatever iteration/batching technique you think it's right considering we want a trade-off between simple to main and performant. 

>  The further improvement could be that both schedule and multiorg_am will use the same result from db.

For the batching - yes, but I don't think the scheduler suffers from the N+1 problem given [it only executes a single query](https://github.com/grafana/grafana/blob/04d5dcb7c8e043ddfe628ab52ab62da1bcf686ba/pkg/services/ngalert/store/admin_configuration.go#L52). The memory overflow seems unlikely based on the current fields so maybe that's overkill? 


> create a foreign key or do the "client side join"

Good shout, this seems like it was probably an oversight - feel free to add it.

> During the next polling cycle we will request all records that were updated or created between the previous and the current timestamps.

How would you consider stopping services for organizations that are no longer present?

**Comment by yuri-tceretian** [comment]
>>Startup. When the service starts it loads all organizations and then configuration of every organization. Although DB access method GetLatestAlertmanagerConfiguration seems to assume that there can be many records per organization, the table specification sets a unique index. Therefore, it guarantees that during the start we always want to get all rows from the table.

>I don't think this is correct. The table ngalert_configuration is not the same as alert_configuration - I apologise as I can understand the naming scheme is quite confusing.

Thanks for pointing to the mistake. You're right, the table `alert_configuration` contains the history of the alert changes. So, it will make the chunking a little bit more difficult than just a simple scan.

>>  The further improvement could be that both schedule and multiorg_am will use the same result from db.

>For the batching - yes, but I don't think the scheduler suffers from the N+1 problem given it only executes a single query. The memory overflow seems unlikely based on the current fields so maybe that's overkill?

Agree, especially, considering the fact that those are two different tables 😄 


> How would you consider stopping services for organizations that are no longer present?

Good point. See below.


My plan is the following:
- get the current timestamp T
- multiorg alert manager reads the list of orgs in chunks
- as long as the id of the org is always increasing value, we can get the min and max id of the chunk 
- get all configurations since the last update 
```sql
SELECT * FROM alert_configurations AS A
WHERE id IN (SELECT MAX(B.id) FROM alert_configuration AS B WHERE B.created_at >= @T AND B.org_id BETWEEN @minId AND @maxId)
```
(this will require an index (org_id + created_at)
the second request does not need to be chunked because 1. we can control the chunk size by org id; 2. the result will be not big ( `len(orgs_chunk)` at worst)
- (same as the current) iterate over all manager instances organizations and remove manager instances that do not exist. This can be improved by creating a temp map, adding new and existing instances of managers and then swap with the old map. However, I do not think it is worth doing at this point.
