### ISSUE TITLE
State timeline: Empty data is shown as an existing data

### ISSUE THREAD

**Issue by SorryGames** [grafana/grafana#38900]
Good day! 

**Version**:
```
bash-5.1$ grafana-server -v
Version 8.1.1 (commit: 90c87a52f7, branch: HEAD)
```

Seems like panel **state timeline** shows empty data as an existing data. I use the same query for three different panels: **table**, **time series** and **state timeline** and I see different pictures. Please, consider the attachment...

![Screenshot from 2021-09-06 18-49-12](https://user-images.githubusercontent.com/34220689/132241214-809648d5-ff3b-4e87-8733-07d602b2fd04.png)

**Comment by dprokop** [comment]
> Seems like panel state timeline shows empty data as an existing data. I use the same query for three different panels: table, time series and state timeline and I see different pictures. Please, consider the attachment...

I don't think I understand this. What do you mean by "empty data"? I see you have actual values (0) in your data set.

Can you please share raw data with us? (go to Panel inspect, uncheck Formatted data in Data options, and download data as CSV file. 

Also- if you could share your panel JSON with us that would help us a lot investigating this.

**Comment by SorryGames** [comment]
I mean no data completely under the "Empty data". You could reproduce the issue by preventing Telegraf to send metrics.

Please, observe the time range after 18:00:34. I have shown that there is no data in **Table** as well as **Time Series** panels, but there is a green line in **State timeline** indicating existing data.


JSON of the dashboard is available [here](https://paste.ofcode.org/iVaXGnuciwpsyMWJnqeRvv).
I do not see the reason to publish CSV file because I have already presented **Table** with data sorted by timestamp.

**Comment by dprokop** [comment]
> I do not see the reason to publish CSV file because I have already presented Table with data sorted by timestamp.

We do see the reason tho as it helps us a lot to reproduce the issue against your data set without the need of manually adding those values:)

Regarding the issue: I think this may be related to state timeline option: [Merge equal consecutive values](https://grafana.com/docs/grafana/latest/visualizations/state-timeline/#merge-equal-consecutive-values). In the dashboard json you have shared it's turned on. Can you try turning it off to see whether or not it meets your expectations?

**Comment by SorryGames** [comment]
Okay, sorry for no data file attached. See below.
When it comes to **Merge equal consecutive values** it doesn't help, **State timeline** still show green line on time range with no data. 

[-data-2021-09-08 20 26 26.csv](https://github.com/grafana/grafana/files/7130743/-data-2021-09-08.20.26.26.csv)

**Comment by dprokop** [comment]
@SorryGames I had a chance to look at your data. IMO this seems to work as it actually should. State time line is intended to show **state changes over time**. In your case, since there is no state change since the last data point, the state is assumed to be the last one that was returned. Correct me if the intention was different @ryantxu?

I think what would better suit your needs @SorryGames is the Status history visualization which will show each state as a discrete value over time.

**Comment by SorryGames** [comment]
> @SorryGames I had a chance to look at your data. IMO this seems to work as it actually should. State time line is intended to show **state changes over time**. In your case, since there is no state change since the last data point, the state is assumed to be the last one that was returned. Correct me if the intention was different @ryantxu?
> 
> I think what would better suit your needs @SorryGames is the Status history visualization which will show each state as a discrete value over time.

Thank you for reply and for reviewing my attachments.

1) Actually it's gonna be a good discussion whether no data event is the state change or not. And to my mind no data event is exactly the state change. Also for me as an end user it was confusing to see Green State when there is a failure event at the node I'm monitoring.

2) When it comes to **Status History**, I could make a first glance suggestion that this panel is not designed to display a lot of node states. Besides I can't find the difference in **State timeline** and **Status History** because they are both designed to display the states of the node, but do that in different details.

**Comment by leeoniya** [comment]
> Actually it's gonna be a good discussion whether no data event is the state change or not.

@dprokop is correct in that state timeline shows transitions in state over time and assumes that state persists until explicitly terminated by a `null` value or a new state at some timestamp.

status history will render `null` values as gaps, and state timeline will render them as explicit state terminations (without requiring another state to start). i think this essentially comes down to `null` value auto-insertion for states that don't terminate past a certain time threshold, (it's kind of the opposite of https://github.com/grafana/grafana/issues/36616). this gets pretty hairy since you may want to know that this is an implicit state termination rather than explicit, and different series may have different rules for what's considered "dead", etc.

@SorryGames are you able to insert `null` values at timestamps when you consider a state has persisted too long?

**Comment by SorryGames** [comment]
> @SorryGames are you able to insert `null` values at timestamps when you consider a state has persisted too long?

Good day!

Thank you for reply.

At this point of time I've found the way how to do this in InfluxDB. Please, give me 1-2 more business days to test it well enough.

**Comment by SorryGames** [comment]
I think I have rethink the purpose of State Timeline and the issue could be closed. Thank you for assistance!
