### ISSUE TITLE
Alerting: Extend the API to fetch rules associated with specific dashboards/panels

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#38920]

**Comment by domasx2** [comment]
could be generalized to filtering by annotations. would be good to be able to retrieve both prometheus rules and ruler rules

**Comment by kylebrandt** [comment]
> Instead I think we should add two columns to the `alert_rule` table `dashboard_uid` and `panel_id` with an index on `(dashboard_uid, panel_id)` or even `(org_id, dashboard_uid, panel_id)`. We have to write a migration to backfill these columns from the existing `annotations` rows in the `alert_rule` table. What is not clear to me is whether these columns must be nullable or whether all alert rules must be related to a dashboard and panel.

I worry about making changes to the database (migrations) unless we are sure this is a longer term design we want.

I imagine users will want to be able to point to an alert rule from multiple dashboards. If this were in the db and relational, it would need another join table.

What we could do instead is when we create annotations, we create them with the UID of the alert rule. Then dashboard panels can get contain an entry pointing the Rule UID, effectively "subscribing" to a rule.

If we do this we would then have the existing `Dashboard / Panel ID` annotations are scoped down to be for creating a link in notifications.

Thoughts?

(^ Moved from https://github.com/grafana/grafana/pull/38713)

**Comment by domasx2** [comment]
> I worry about making changes to the database (migrations) unless we are sure this is a longer term design we want.
> 
> I imagine users will want to be able to point to an alert rule from multiple dashboards. If this were in the db and relational, it would need another join table.
> 
> What we could do instead is when we create annotations, we create them with the UID of the alert rule. Then dashboard panels can get contain an entry pointing the Rule UID, effectively "subscribing" to a rule.
> 
> If we do this we would then have the existing Dashboard / Panel ID annotations are scoped down to be for creating a link in notifications.
> 
> Thoughts?

Currently there's no use case for linking alert rule to multiple panels. We have the annotation link only to be able to replicate the behaviour of the legacy alerting system. I'd lean to discouraging any complication on top of this...

If we reverse the relationship and link from panel to rule, wouldn't it also complicate things by requiring to update panels when a rule is deleted? And we'd have to keep both rule annotations and panel model in sync? 

I'd say let's do the simplest thing possible to solve the current problem we have

**Comment by gerobinson** [comment]
I agree it would be nice to have something more generalized in that we could allow filtering of alert rules on their annotations, however it presents a number of cases that we would have to consider and could make this into a much larger task.

For example, Wwat happens if the annotations is templated? I don't think aren't going to expect to match the exact template string and so we are going to have to support not just prefix and suffix, but full text search.

I also agree with @domasx2 and think we should keep it simple so we can get this shipped. If we have no immediate plans to reference an alert rule with multiple dashboards or panels then I think the right change to make now is to add `dashboard_uid` and `panel_id` to the `alert_rule` table, or better, add an `alert_rule_uid` column to the `annotations` table. However, this could require more complex migrations as we allow customers to upgrade and downgrade from ngalerts.

**Comment by gerobinson** [comment]
I agree it would be nice to have something more generalized in that we could allow filtering of alert rules on their annotations, however it presents a number of cases that we would have to consider and could make this into a much larger task.

For example, what happens if the annotations is templated? I don't think aren't going to expect to match the exact template string and so we are going to have to support not just prefix and suffix, but full text search.

I also agree with @domasx2 and think we should keep it simple so we can get this shipped. If we have no immediate plans to reference an alert rule with multiple dashboards or panels then I think the right change to make now is to add `dashboard_uid` and `panel_id` to the `alert_rule` table, or better, add an `alert_rule_uid` column to the `annotations` table. However, this could require more complex migrations as we allow customers to upgrade and downgrade from ngalerts.

**Comment by gerobinson** [comment]
I agree it would be nice to have something more generalized in that we could allow filtering of alert rules on their annotations, however it presents a number of cases that we would have to consider and could make this into a much larger task.

For example, what happens if the annotations is templated? I don't think aren't going to expect to match the exact template string and so we are going to have to support not just prefix and suffix, but full text search.

I also agree with @domasx2 and think we should keep it simple so we can get this shipped. If we have no immediate plans to reference an alert rule from multiple dashboards or panels then I think the right change to make now is to add `dashboard_uid` and `panel_id` to the `alert_rule` table, or better, add an `alert_rule_uid` column to the `annotations` table. However, this could require more complex migrations as we allow customers to upgrade and downgrade from ngalerts.

**Comment by gerobinson** [comment]
I agree it would be nice to have something more generalized in that we could allow filtering of alert rules on their annotations, however it presents a number of cases that we would have to consider and could make this into a much larger task.

For example, what happens if the annotations is templated? I don't think aren't going to expect to match the exact template string and so we are going to have to support not just prefix and suffix, but full text search.

I also agree with @domasx2 and think we should keep it simple so we can get this shipped. If we have no immediate plans to reference an alert rule from multiple dashboards or panels then I think the right change to make now is to add `dashboard_uid` and `panel_id` to the `alert_rule` table, or better, add an `alert_rule_uid` column to the `annotations` table. However, this could require more complex migrations as we allow customers to upgrade and downgrade from ngalerts.

**Comment by gerobinson** [comment]
In the case where a rule group has rules, however its rules do not match the `dashboard_uid` and `panel_id` in the query string, should I remove those rule groups from the response or return them but without rules?

Should we return rule groups even when none of their rules match the `dashboard_uid` and `panel_id` we would expect something like the following:

```
{
  "status": "success",
  "data": {
    "groups": [
      {
        "name": "Test alert",
        "file": "gdev dashboards",
        "rules": null,
        "interval": 0,
        "lastEvaluation": "0001-01-01T00:00:00Z",
        "evaluationTime": 0
      }
    ]
}
```

**Comment by gerobinson** [comment]
In the case where a rule group has rules, however its rules do not match the `dashboard_uid` and `panel_id` in the query string, should we remove these rule groups from the response or return them like the following?

```
{
  "status": "success",
  "data": {
    "groups": [
      {
        "name": "Test alert",
        "file": "gdev dashboards",
        "rules": null,
        "interval": 0,
        "lastEvaluation": "0001-01-01T00:00:00Z",
        "evaluationTime": 0
      }
    ]
}
```

**Comment by domasx2** [comment]
> In the case where a rule group has rules, however its rules do not match the `dashboard_uid` and `panel_id` in the query string, should we remove these rule groups from the response or return them like the following?
> 
> ```
> {
>   "status": "success",
>   "data": {
>     "groups": [
>       {
>         "name": "Test alert",
>         "file": "gdev dashboards",
>         "rules": null,
>         "interval": 0,
>         "lastEvaluation": "0001-01-01T00:00:00Z",
>         "evaluationTime": 0
>       }
>     ]
> }
> ```



> In the case where a rule group has rules, however its rules do not match the `dashboard_uid` and `panel_id` in the query string, should we remove these rule groups from the response or return them like the following?
> 
> ```
> {
>   "status": "success",
>   "data": {
>     "groups": [
>       {
>         "name": "Test alert",
>         "file": "gdev dashboards",
>         "rules": null,
>         "interval": 0,
>         "lastEvaluation": "0001-01-01T00:00:00Z",
>         "evaluationTime": 0
>       }
>     ]
> }
> ```

Old question that I noticed just now, but I'd say remove. For Grafana anyway there's 1 group per rule now. Shouldn't even fetch groups that don't have relevant rules in it
