### ISSUE TITLE
$__from and $__to aren't following the panel's relative time

### ISSUE THREAD

**Issue by imReker** [grafana/grafana#38954]
**What happened**:
`$__from` and `$__to` return the dashboard's from & to, without taking into account the panel's Relative Time and Time Shift settings.
Maybe same as the old issue #20147 

![1](https://user-images.githubusercontent.com/4949937/132440040-b9ed05a9-9fa8-4fc9-bff3-7f5092f3d829.png)

**What you expected to happen**:
`$__from` and `$__to` should return the panel's from/to.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a panel
2. Set a relative time (like now/w)
3. Set panel Title to `$__from` and `$__to`
4. View the title.

**Environment**:
- Grafana version: Grafana v8.1.2 (103f8fa094)

**Comment by ashharrison90** [comment]
hey @imReker 👋 

i think this is by design. `$__from` and `$__to` are global variables associated with the dashboard itself, not with any particular panel.

there are specific macros for each datasource to access the time after the relative time/time shift have been applied. see e.g. [`__timeFrom()` and `__timeTo()` in the mysql macros](https://grafana.com/docs/grafana/latest/datasources/mysql/#macros). 

does that solve your problem? if not, what datasource are you using and what use case are you trying to solve?

**Comment by imReker** [comment]
> hey @imReker 👋
> 
> i think this is by design. `$__from` and `$__to` are global variables associated with the dashboard itself, not with any particular panel.
> 
> there are specific macros for each datasource to access the time after the relative time/time shift have been applied. see e.g. [`__timeFrom()` and `__timeTo()` in the mysql macros](https://grafana.com/docs/grafana/latest/datasources/mysql/#macros).
> 
> does that solve your problem? if not, what datasource are you using and what use case are you trying to solve?

No, I'm using Json query as datasource, which will make a HTTP request, so `from` and `to` related to panel is needed to generate URL
And, also I want show panel's time range in panel title as in the image I posted.

**Comment by ashharrison90** [comment]
in that case i think it's up to the maintainers of the json query datasource to implement a macro similar to `__timeFrom()`/`__timeTo()`, because `$__from` and `$__to` will always refer to the global dashboard from/to.

for the title, i don't think there's currently a way to do what you want. the timeshift is shown by default in the title, but there is no variable that contains the shifted + relative date, although that does sound like a reasonable feature request. my suggestion would be to raise that as a github discussion as per https://github.com/grafana/grafana/issues/36683 so we can gauge how valuable an addition that is. or we'd welcome any PR adding that functionality. 🙌

**Comment by baur** [comment]
for MSQL soved with  `$__unixEpochTo()` and `$__unixEpochFrom()` but here another bug #39933

**Comment by osakindoyin** [comment]
@ashharrison90 do you know the macros for infinity datasource?

**Comment by misilot** [comment]
Anyone know how to use the relative times from a panel with an infinity datasource? I need to be able to send the values as query parameters.
