### ISSUE TITLE
Timeseries panel stack to 100% affects legend and tooltip formatting.

### ISSUE THREAD

**Issue by hafkensite** [grafana/grafana#39404]
**What happened**:
Values in legend and tooltip are formatted as percentages when stacking to 100% is enabled.

**What you expected to happen**:
The value that is displayed uses the configured unit, not the percentage notation. So if the value is 1024, I would expect `1.02k`, not `102400%`

**How to reproduce it (as minimally and precisely as possible)**:
Enable stacking to 100% in the timeseries panel, and enable the legend with the `last*` values.

**Anything else we need to know?**:
In the old graph panel this does work as expected. 

**Environment**:
- Grafana version: 8.0.4
- Data source type & version: N/A
- OS Grafana is installed on: Debian Stretch
- User OS & Browser: Firefox
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
Looks like the problem is here: https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/timeseries/utils.ts#L51 

@dprokop Not sure we should change the field unit when stacking percent, or if we did we need to recalc all values so they are precentages, right now the percent option shows incorrect values in tooltip & legend (shows unit percent but the values are the original multiplied by 100).

**Comment by Willshield** [comment]
This problem can be reproduced on play.grafana also:

![image](https://user-images.githubusercontent.com/13013769/146211147-0280c950-b612-4b11-8bd9-a1b7e1628471.png)

The tooltip shows wrong percentages.
