### ISSUE TITLE
Azure Monitor query editor for Variables doesn't have Service or Resource picker

### ISSUE THREAD

**Issue by mitulk** [grafana/grafana#39444]
**What happened**:
Panel query editor has a resource picker:
![image](https://user-images.githubusercontent.com/14897058/134051771-3c01b357-78b6-4d49-b52f-eff07c548031.png)

Variable query editor doesn't:
![image](https://user-images.githubusercontent.com/14897058/134051836-03ddd461-1c37-49fc-a21e-4b95a4ed8dd0.png)

"Upon looking network traces, i see dashboard variable queries being to made to random first available workspace in the default sub specified in the datasource . How do i specify what workspace/resource to be queried for dashboard variable queries?"

**What you expected to happen**:
Be able to pick the right resource in the variables.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create Azure Monitor data source
2. Try to add panel and variable

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.2 (103f8fa094)
- Data source type & version: Azure Monitor
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by vishiy** [comment]
i see the same issue as well.

**Comment by mitulk** [comment]
Tagging @vishwanath who reported this issue

**Comment by joshhunt** [comment]
This is more or less as designed. As the Azure Monitor template variable editor lacks a UI there's no way to select the Logs Analytics workspace to query, so it will select the 1st workspace that comes back from the Azure API.

We do have some loose plans to replace this with the new ability for data sources to render custom UI for the template variable editor, which would give a much better experience over the arcane psuedo-kusto queries we have now, and theoretically using ARG , but nothing solid planned yet.

A work around could be, if possible, to create a subscription that has access only to the desired LA workspace, and set that subscription as the default in the data source settings.

**Comment by vishiy** [comment]
Thanks @joshhunt . Is there a way to force to use the previous version of AZM datasource, as this is a regression ? This completely make our dashboards not useable, as we cannot run any queries as part of filters. Unfortunately, moving every log analytics workspace to a separate subscription is not an option. Please advice.

**Comment by joshhunt** [comment]
Hmmm I understand the problem now. I will discuss with the team.

As Azure Monitor is a core data source bundled with Grafana, there is no way to roll back to a previous version without rolling back to a previous version of Grafana.

**Comment by joshhunt** [comment]
Discussed with the team, and talked about a path forward.

A summary of the issue: In Grafana 8.0 and 8.1, through our effort to simplify the Azure Monitor data source config, we removed the setting to specify a default workspace as we did not believe it provided much value for the query editor. We did not anticipate this would affect Kusto template variables in the way that it did. The default workspace variable should still be in the configuration jsonData, but just not used by any of the code.

We're hesitant to reintroduce the 

The solution we're thinking of is to render the Query Editor as the template variable query editor (perhaps with Metrics disabled, as that can not output data useful for template variables), and migrate existing template variables into this editor. 

 - For template variable queries we determine are Kusto LA Workspace queries (because they don't match our custom psuedo-functions), we will migrate them to `{ queryType: AzureQueryType.LogAnalytics, query: kustoTemplateVariableQuery  }`. If present, we can set the resource to the default workspace from the datasource configuration, otherwise just select the 1st workspace.
 - For our custom function (see [AzureMonitor template variables](https://grafana.com/docs/grafana/latest/datasources/azuremonitor/template-variables/) ), we migrate them to a new "classic" query type with their previous query.

This would have a neat benefit of enabling using ARG for template variables, which is cool 😄 

We would need to spike this out to investigate how feasible it is, but so far it seems like this is a nice trade off of something we can get out quickly which fixes the issue without hacky workarounds. I think one problem that could make this tricky is whether it's possible to call the backend query code for fetching template variable values @sunker (I think we can through resource handlers?).

Another option would be just to update the template variable query code to use the old default workspace value if present, but there would not be any interface for users to add or update this value - it would only be there for previously created data source, or if it was set manually via the API.

I think the first option is a better solution. @grafana/cloud-datasources

**Comment by andresmgot** [comment]
regarding the second option, would it be possible to easily add a workspace selector for the query? (and use that one rather than the `default` one from the configuration).

**Comment by joshhunt** [comment]
@mitulk @vishiy We've been discussing this more, about how to fix this problem and improve the experience of template variables with Azure Monitor. 

In the meantime, as a workaround, are you able to use cross-workspace queries to get these dashboards working? https://docs.microsoft.com/en-us/azure/azure-monitor/logs/cross-workspace-query#identifying-workspace-resources
