### ISSUE TITLE
Error rendering panel

### ISSUE THREAD

**Issue by HellMenda** [grafana/grafana#39456]
**What happened**:
After updating grafana 7 to Grafana 8, some panels doesn't render properly. Gauges do weird things like this when resizing:

![image](https://user-images.githubusercontent.com/8439974/134124819-98ed4cda-572c-4563-af1f-ae8d17545f95.png)

**How to reproduce it (as minimally and precisely as possible)**:
Use a gauge and resize the windows

**Environment**:
- Grafana version: Latest, updated yesterday
- Data source type & version: Mysql
- OS Grafana is installed on: Centos 7
- User OS & Browser: Windows & Firefox, Chrome, Edge (happens on all of them)

**Comment by torkelo** [comment]
We have no other reports like this, what plugins have you installed? What browser version are you on?

**Comment by HellMenda** [comment]
Tried on Win10 and Ubuntu with Firefox, Chrome latest versions.

Is it possible to rollback to v7? Had no issues there...

**Comment by torkelo** [comment]
strange, no one else has reported this and we are unable to replicate. Try without any grafana plugins and use chrome incognito mode to make sure there is nothing interfering

**Comment by HellMenda** [comment]
That, won't be a big problem. What really troubles me is what I described at https://github.com/grafana/grafana/issues/39457 

Following that instructions, the panels don't dissapear, but don't show the correct info.

I know it's my fault for not having a snapshot prior to the upgrade.... but is there any way to rollback to 7? Need those panels up again.

**Comment by MarcusCalidus** [comment]
We indeed do have the same problem here. 

the element id="flotGagueValue0" seems to duplicate with every refresh/redraw.

Grafana v 8.1.2
Problem exists since Grafana v 7.something 
It happens with Chrome, Edge both on macOS and Windows 10 and Safari 

no errors in Chrome Dev Console

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/4113366/134669681-a409b867-626c-4010-afdf-fb3410a37f0c.png">

**our installed plugins:**
aceiot-svg-panel @ 0.0.8
camptocamp-prometheus-alertmanager-datasource @ 0.0.8
cloudspout-button-panel @ 7.0.23
grafana-clock-panel @ 1.0.3
grafana-groupedbarchart-panel @ 1.0.3
grafana-influxdb-flux-datasource @ 7.0.0
grafana-piechart-panel @ 1.6.0
camptocamp-prometheus-alertmanager-datasource @ 0.0.7
innius-video-panel @ 1.0.1
jdbranham-diagram-panel @ 1.6.2
marcuscalidus-svg-panel @ 0.3.3
michaeldmoore-multistat-panel @ 1.4.1
mxswat-separator-panel @ 1.0.0
ryantxu-ajax-panel @ 0.0.7-dev
blackmirror1-singlestat-math-panel @ 1.1.7
vonage-status-panel @ 1.0.9

@HellMenda  ... could you please check if there is an overlap of installed plugins between us? That would be great.

**Comment by HellMenda** [comment]
Sure. This is the list of plugins installed. Many of them, are not in use. We mainly use Gauge, bar and Blendstat:

Alert list
Annotations list
Azure Monitor
Bar chart
Bar gauge
Blendstat
Clock
CloudWatch
Dashboard list
Elasticsearch
Gauge
Geomap
Getting Started
Google Cloud Monitoring
Grafana Image Renderer
Graph (old)
Graphite
Heatmap
Histogram
InfluxDB
Jaeger
Logs
Loki
Microsoft SQL Server
MySQL
News
Node Graph
OpenTSDB
Pie chart
Polystat
PostgreSQL
Prometheus
Stat
State timeline
Status history
Table
Table (old)
Tempo
TestData DB
Text
Time series
Welcome
Zipkin

A clean up is needed....

**Comment by HellMenda** [comment]
This problem only happen with Gauges. When converting from Gauge to Stat, the rendering problem dissapear. But... I need a Gauge...

**Comment by torkelo** [comment]
it could be caused by the Blendstat plugin , we had a similar issue with Singlestat math (which also is a fork of our old internal singlestat panel)

**Comment by MarcusCalidus** [comment]
@torkelo  ... we don't have Blendstat installed ... the problem persists all the same. I don't understand why the issue is closed

**Comment by torkelo** [comment]
@MarcusCalidus can you try without any plugins?

In an earlier post you mentioned you have these installed 
* michaeldmoore-multistat-panel 
* blackmirror1-singlestat-math-panel 

They are also known to cause this issue

**Comment by torkelo** [comment]
Do you get the same problem on https://play.grafana.org/d/KIhkVD6Gk/4-gauges?orgId=1&refresh=10s ?

**Comment by MarcusCalidus** [comment]
ahhhh... I see. We will check that. Thx for pointing that out.
