### ISSUE TITLE
Cannot select "All" in the Folder list

### ISSUE THREAD

**Issue by SunSparc** [grafana/grafana#39454]
**What happened**:
In the Dashboard list visualization I was selecting different folders to test which ones I wanted to use. Then I realized I was unable to go back to the "All" default option.

**What you expected to happen**:
I expect to be able to select the "All" option and have it show me all folders.

**How to reproduce it (as minimally and precisely as possible)**:
- open a dashboard
- add a new panel
- choose the "Dashboard list" visualization
- enable the "Search" option
- notice that the default option selected in the "Folder" list is "All"
- click on the "Folder" list and the "All" option will be highlighted
- click on a different folder
- apply/save your changes to the dashboard
- edit the panel you just added
- notice that the "All" option is displayed as the selected value in the "Folder" list.
- click on the "Folder" list and notice that the folder you last selected is highlight still, as well as the "All" option
- click on the "All" option
- apply/save your changes to the dashboard
- notice that all of the folders are not showing in your panel, instead, the contents will still be those of the folder that you chose which is not "All"
- clear your cache, try a new browser, notice that all can never be selected again
- delete the panel and create a new one in order to get access to the "All" option again

**Environment**:
- Grafana versions tried: 8.1.2 and 8.2.0-beta1
- OS Grafana is installed on: Ubuntu Linux
- User OS & Browser: MacOS with Brave and Chrome
- Grafana plugins: only Core plugins

<img width="778" alt="grafana-folder-list" src="https://user-images.githubusercontent.com/1380473/134097829-648be99b-dac4-4a77-afa8-3541cc6c8868.png">

**Comment by zuchka** [comment]
Hi @SunSparc, 

thanks for making this issue and for including such detailed reproduction steps 👍 

This sounds similar to [this issue this year](https://github.com/grafana/grafana/issues/31158).

It was fixed [with this PR](https://github.com/grafana/grafana/pull/31160/files).

I'm wondering if the issue is around here, where the code was last touched:

https://github.com/grafana/grafana/blob/855a49c21eae149aa200a133bf4375686b899b96/public/app/plugins/panel/dashlist/module.tsx#L46-L58

One thing I did notice in my research:

when you initially click the `search` toggle, grafana calls `api/search?limit=10&query=&type=dash-db`

clicking `all` on that first cycle:

`api/search?limit=10&query=&folderIds=null&type=dash-db`

clicking `General` = `https://play.grafana.org/api/search?limit=10&query=&folderIds=0&type=dash-db`

As @SunSparc noted, if you apply or save any folder other than `All`, like `general : folderIds=0` then reopening the editor, `All` now maps to the `folderIds` that you last chose ( `0` ).

**Comment by hugohaggmark** [comment]
The exact same issue exists in the Alert List panel too!
