### ISSUE TITLE
[FeatureRequest]: Make PanelEdit scrollable

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#39487]
**What happened**:

The Edit Panel screen cannot be scrolled when I use my MacBook trackpad in either Safari or - here's the kicker - Chrome.

~~When I plug in a USB Logitech mouse and use the scroll wheel, it scrolls normally.~~ I remembered incorrectly - it still does not scroll correctly with a USB scroll wheel mouse.

Other views in Grafana, such as a Dashboard or Edit Dashboard, scroll fine.

https://user-images.githubusercontent.com/46142/134208981-c8981ae6-1a95-4d26-b787-464e150cca8d.mov

**What you expected to happen**:

It scrolls :) 

**How to reproduce it (as minimally and precisely as possible)**:

On a Panel > Edit, try to scroll. It doesn't.

Tested on Grafana Cloud, and a local development version.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.4 (6855cdff7c) and v8.3.0-pre (878b54c83c)
- OS Grafana is installed on: macOS
- User OS & Browser:
   - macOS Big Sur 11.6 (20G165)
   - Safari Version 14.1.2 (16611.3.10.1.6)
   - Chrome Version 93.0.4577.82

**Comment by hugohaggmark** [comment]
Interesting, I can reproduce this as early as in Grafana 7.0.0 when the new PanelEdit was introduced. I'm using a scroll wheel mouse on:
![image](https://user-images.githubusercontent.com/562238/134287041-df3bb2f2-2e46-4f3f-a793-f66db76db4db.png)

![image](https://user-images.githubusercontent.com/562238/134287130-2f1f520a-f32f-45c9-a9cd-ce2352fd1d1b.png)

I'm going to mark this as a feature request instead of bug as you can still scroll the queries, transformations etc within the PanelEdit.

**Comment by torkelo** [comment]
Unable to replicate on a macbook big sur with chrome 93 or Safari 14.1.1

**Comment by hugohaggmark** [comment]
> Unable to replicate on a macbook big sur with chrome 93 or Safari 14.1.1

Interesting, where (at what position) do you scroll with the trackpad?

**Comment by torkelo** [comment]
@hugohaggmark the panel options pane and the queries pane

**Comment by hugohaggmark** [comment]
Aha, ok then it's the same for me, queries, transforms and options scroll fine but not the entire Panel Edit.

**Comment by torkelo** [comment]
ah, that is of course by design, otherwise we could not make panel options or queries scrollable

**Comment by sylr** [comment]
> ah, that is of course by design, otherwise we could not make panel options or queries scrollable

The design is flawed, as users we don't want to scroll in panels, we want to scroll the whole edit page.

Really, the editing experience of dashboards has been execrable since you switched to this layout with Grafana 7:

- Can't scroll the page
- Options are hidden under a right pane and within hidden groups and thus ridiculously hard to find.

I wish you would restore the old Grafana 6 layout that was simple and efficient.
