### ISSUE TITLE
FR: User removal from Org and Global users

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3953]
When we remove the user either from an organization or from Grafana global user list, Grafana should unset the "created_by"/"updated_by" fields in the dashboard table for that removed user.

**Comment by utkarshcmu** [comment]
Also, some kind of confirmation/warning message should also pop up that "Are you sure to remove this user and his 12 dashboards?" Something similar to this.

**Comment by torkelo** [comment]
but sounds like the dashboards will be deleted

**Comment by utkarshcmu** [comment]
What if people in the organization wants to keep dashboards created by someone. I think deleting dashboards should be optional whenever the user who created them is removed from the org or from grafana. There can be a checkbox in the removal confirmation modal to remove the dashboards too.

**Comment by torkelo** [comment]
I do not understand what you mean, when you remove a user, **NO** dashboards are deleted.

**Comment by utkarshcmu** [comment]
I think I was not clear before. Let me try to explain the use cases again:

1. Some users might want to get rid of the dashboards which a user created, when this user is either removed from Grafana or an Organisation. In this case, we can delete the dashboards which this user created. 

2. Other users might not want to get rid of the dashboard which this (to-be-removed) user created for the organization. Like in my company here, we do not want to delete the important dashboards which some employee has created for the org, even if he leaves the org or company. So, in this case we want to preserve his dashboards.

Here is my proposal for "Removing a user from an org or from Grafana":

When we delete a user from an org or Grafana, in the confirmation dialog box (modal), we can give an option to retain the dashboards which this to-be-removed user created. By default we can delete the dashboards he created. Let me try showing an image of this confirmation dialog box. :)

**Comment by utkarshcmu** [comment]
Something like this but with a **checkbox**:

<img width="647" alt="screen shot 2016-02-07 at 12 21 47 am" src="https://cloud.githubusercontent.com/assets/1019609/12871450/e2ac5a18-cd30-11e5-9f9f-e5f20f79ac92.png">

**Comment by torkelo** [comment]
Should it now say something like "Do you also want to delete 10 dashboards created by Tom" ? And should not be checked by default as that would be prone to accidental dashboard deletion 

Not sure why this is filed as a bug :) seems like a convenience feature

**Comment by utkarshcmu** [comment]
Changed it as a Feature Request. :)

**Comment by torkelo** [comment]
I think the problem of deleting dashboards created by deleted users might be better solved by introducting better filtering options in manage dashboards page (to show dashboards created by deleted users, dashboards not opened in last x months etc) 


We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
