### ISSUE TITLE
It is impossible to close a parenthesis in the query builder

### ISSUE THREAD

**Issue by trondhindenes** [grafana/grafana#39628]
**What happened**:
I'm trying to build a prometheus query.

**What you expected to happen**:
I expect that when I type `)` on my keyboard, grafana will add that character to the query

**How to reproduce it (as minimally and precisely as possible)**:
Type in `rate(traefik_service_request_duration_seconds_sum[5m]` and then try and close the parenthesis. It's impossible.
![z65uCv146R](https://user-images.githubusercontent.com/1747120/134806233-2b087f19-24e2-4e00-8a40-82dbec323d6f.gif)

**Anything else we need to know?**:

**Environment**:
- Grafana version: `8.1.4 (6855cdff7c)`
- Data source type & version: Prometheus (not sure if it matters tho)
- OS Grafana is installed on: Linux (Prometheus-stack helm chart)
- User OS & Browser: Chrome on Ubuntu 20
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
Hello @trondhindenes! What is your keyboard layout? I wasn't able to reproduce it with us-en keyboard, but we've had cases where some kinds of keyboards (french/international/...) were behaving unexpectedly.

**Comment by trondhindenes** [comment]
> Hello @trondhindenes! What is your keyboard layout? I wasn't able to reproduce it with us-en keyboard, but we've had cases where some kinds of keyboards (french/international/...) were behaving unexpectedly.
Hi, I'm on a Norwegian (nb-no) keyboard

**Comment by ivanahuckova** [comment]
We are in the process of switching code editor to Monaco. @gabor could you please check if this is an issue there?

**Comment by gabor** [comment]
hi @trondhindenes @mwennrich , we are working on a new version of the prometheus query-editor-field, which does not have this problem.

if you want to try it out:
an experimental version is available in grafana8.2.0-beta2 or later, but you have to enable a feature-toggle called "prometheusMonaco" (https://grafana.com/docs/grafana/latest/administration/configuration/#feature_toggles) to see it. please note that it is not finished yet, we do not recommend using it yet,  but you can try it out and see if the bug is fixed there if you want to 👍

**Comment by gabor** [comment]
the new prometheus query-field has been enabled in `main` branch, it should fix this problem. if not, please comment here and we can reopen the issue. thanks!
