### ISSUE TITLE
Alerting v8: metric value not populated when using SQL data source 

### ISSUE THREAD

**Issue by molsza** [grafana/grafana#39696]
**What happened**:
Create alert based on SQL query from MySQL data source, similarly as you create a time series with multiple data series. Use classic condition.

If series column is named `metric` then on preview chart  you are getting multiple series - which is correct.  

Then click on `Preview alert` - you are getting multiple series but metric value is always empty. There is no way to differentiate the series.

Now if you change the column name to something different like `instance`, then in preview alert you will get the instance label.   

**What you expected to happen**:
When column is named `metric` alert value should populate the `metric` field with values form metric column.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.5
- Data source type & version: MySQL
- OS Grafana is installed on: Linux
- User OS & Browser: n/a
- Grafana plugins: build-in
- Others:

**Comment by JohnnyQQQQ** [comment]
I just did an investigation to see what the problem could be. 

Here a few findings:

- It's a regression, legacy alerting is populating the metric field correctly.
- All SQL datasources should have this problem (I also tested postgres, same problem).
- The problem seems to be related to the evaluation pipeline, where the metric metadata is missing on the frame.

To fix this we would need to invest a bit more time.

cc @peterholmberg @armandgrillet

**Comment by JohnnyQQQQ** [comment]
I tracked down the bug to the Problem that we use the Frame name as Metric name (`series.GetName()`). 

https://github.com/grafana/grafana/blob/3da4e1cdcd363b9e47827d2b9f84a10761dc0e12/pkg/expr/classic/classic.go#L119-L122

For now the Frame name on an SQL Query is empty. What I think would be sensible is to use the column name as Frame name if the Frame name is not set on transformation in the function below.

https://github.com/grafana/grafana/blob/3da4e1cdcd363b9e47827d2b9f84a10761dc0e12/pkg/expr/nodes.go#L382-L420

@kylebrandt I think you know the code here quite well. Would you suggest to go forward with my approach or do you think we should fix the problem on another Layer?

**Comment by kylebrandt** [comment]
I will be starting to work on normalizing data type definitions in the coming weeks which should help with this confusion generally.

I will look closer tomorrow but I think for Time series, the Field's name should be the name of a metric like like "cpu", and if there multiple metrics with that same name then the labels property on the value field should have labels (like host=foo) to distinguish them.

This is because you can have multiple time series, one frame format (Wide) we support allows multiple value columns in one frame. So for consistency it is better if the frame name is not used for this.

In regards to classic, that is meant to be backwards compatible with old alerting and therefore not multidimensional, so specific changes for migrated rules can maybe happen is the specifics of what the classic condition operation does.

**Comment by JohnnyQQQQ** [comment]
@kylebrandt thank you for your input about the issue. 

Regarding your comment fixing the issue in the specifics of what the classic condition operation does I came up with a solution that is perhaps valid. I push for this as we need a solution for this soonish. 

WDYT?

```diff
diff --git a/pkg/expr/classic/classic.go b/pkg/expr/classic/classic.go
index 830d1ba1f1..60d9e42add 100644
--- a/pkg/expr/classic/classic.go
+++ b/pkg/expr/classic/classic.go
@@ -116,9 +116,13 @@ func (ccc *ConditionsCmd) Execute(ctx context.Context, vars mathexp.Vars) (mathe
                        evalRes := c.Evaluator.Eval(reducedNum)
 
                        if evalRes {
+                               metricName := series.GetName()
+                               if metricName == "" {
+                                       metricName = series.GetValueName()
+                               }
                                match := EvalMatch{
                                        Value:  reducedNum.GetFloat64Value(),
-                                       Metric: series.GetName(),
+                                       Metric: metricName,
                                }
                                if reducedNum.GetLabels() != nil {
                                        match.Labels = reducedNum.GetLabels().Copy()
diff --git a/pkg/expr/mathexp/type_series.go b/pkg/expr/mathexp/type_series.go
index 00962141d4..99ad8c6ab1 100644
--- a/pkg/expr/mathexp/type_series.go
+++ b/pkg/expr/mathexp/type_series.go
@@ -144,6 +144,8 @@ func (s Series) SetLabels(ls data.Labels) { s.Frame.Fields[seriesTypeValIdx].Lab
 
 func (s Series) GetName() string { return s.Frame.Name }
 
+func (s Series) GetValueName() string { return s.Frame.Fields[seriesTypeValIdx].Name }
+
 func (s Series) GetMeta() interface{} {
        return s.Frame.Meta.Custom
 }
```

**Comment by kylebrandt** [comment]
@JohnnyQQQQ Yikes, feels like GetName should maybe change, need to make sure it won't even panic if somehow there can be no Fields. Also maybe GetName should be part of the Value interface, give me a bit to look at this.

**Comment by kylebrandt** [comment]
I think GetName should change to what you proposed in GetValueName(), and no method is added.

I think the logic is probably the best we can do right now, but think that should live in `SeriesFromFrame`, so internally SSE becomes consistent (e.g. with `NewSeries`) and always has metric names as the Value (numeric) Field Name.

**Comment by JohnnyQQQQ** [comment]
Perfect, I'll spin up an PR and let you know 👍
