### ISSUE TITLE
Changing null point mode from 'connected' to 'null' stops rendering graph at certain zoom level.

### ISSUE THREAD

**Issue by nvtkaszpir** [grafana/grafana#4017]
Changing null point mode from 'connected' to 'null' stops rendering graph at certain zoom level.

Video shows in more detail what is happening.
https://www.youtube.com/watch?v=Sy8Y3Hv_fPM&feature=youtu.be

Data source is from elasticsearch in proxy mode.

**Comment by torkelo** [comment]
change your min doc count in your elastic queries to 1, when you zoom in it is possible that the date histogram interval is too small, so elasticsearch will return null values between each real value (since the min doc count per interval is 0), you can change the min doc count on the date histogram group by (click the options link next to the date histogram group by row). Specify min doc count of 1

**Comment by nvtkaszpir** [comment]
Well the issue is that when I move cursor to the graphing area, then there is a tooltip withe the values - so the data is there.

But indeed changing Min Doc Count to 1 solves the issue - then why isn't it by default to avoid thas problem?

**Comment by torkelo** [comment]
Min doc count 1 as default haso other problems  (like not seeing clearly when data is missing)

**Comment by torkelo** [comment]
The reason why the graph disappears is due to null vales between real values and you picking the option null point mode: null (instead of default connested that ignore null values)
