### ISSUE TITLE
Grafana 8.1.5 not able to create any new contact points or notification policies and getting error: failed to save and apply Alertmanager configuration

### ISSUE THREAD

**Issue by LaxmiRajawat** [grafana/grafana#40396]
**What happened**:
Migrated Grafana 7.5.1 to Grafana 8.1.5 but not able to create or save any new contact points and notification policies, getting below error : failed to save and apply Alertmanager configuration : failed to validate receiver "opsgenie test" of type "opsgenie" could not find api key property in settings.

**What you expected to happen**:
new contact points and notification policies or existing contact points and notification policies should be working fine after migration.

**Anything else we need to know?**:
Other github suggested removing opsgenie and redoing migration but we do not use opsgenie.

**Environment**:
- Grafana version: 8.1.5
- Data source type & version: InfluxDB- InfluxQL and Flux
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser:Windows,Chrome,Firefox
- Grafana plugins: Button, clock, Direct Input, Influx Admin, Pie chart, grafana-image-renderer

![Grafana 8 1 5 error](https://user-images.githubusercontent.com/87098594/137148475-f2b83d16-783f-45ad-8052-bee54383820c.JPG)

**Comment by grobinson-grafana** [comment]
Hi @LaxmiRajawat,

There are two possible options here: [rollback to legacy alerting](https://grafana.com/docs/grafana/latest/alerting/migrating-alerts/roll-back/) and then upgrade to Unified Alerting with Grafana 9.0 and see if the migration now works as expected, or re-create all missing alerts and notification channels.

If rolling back please know that all data created since upgrading to Unified Alerting will be deleted, so this might not be an option given the amount of time that you have been running Unified Alerting.
