### ISSUE TITLE
[unified alerting] [evaluation] NaN values trigger alerting

### ISSUE THREAD

**Issue by zoltan-fedor** [grafana/grafana#40392]
**What happened**:
I have an alert which is based on a ratio, where a division by zero can result an NaN value.
Unfortunately NaN values trigger alerting, independently from the "Alert state if no data or all values are null" setting and no Math or Reduce function allows the handling of the NaN values.

This means you cannot use division in the new unified alerts, because at low activity times they will return NaN and so will trigger the alert.

Ps.: "Classic condition" can handle the NaN, but unfortunately that doesn't allow you to use template variables, so that isn't a solution either.

![image](https://user-images.githubusercontent.com/3887295/137146910-741dba18-83cc-4778-86c3-71b6ef91c9aa.png)
![image](https://user-images.githubusercontent.com/3887295/137147324-2992c4e8-3e65-4484-a770-4a8ac6e98b93.png)

**What you expected to happen**:
I would expect either an option to handle NaN values or the "Alert state if no data or all values are null" setting to cover the NaN value too.

**How to reproduce it (as minimally and precisely as possible)**:
Create an alert based on a division by zero - which will result in NaN and try to make the alerting to ignore that and not to fire the alert - you won't be able to stop it from alerting.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Official Docker image
- User OS & Browser: Linux Mint, Google Chrome
- Grafana plugins:
- Others:

**Comment by gillg** [comment]
I don't know if a lot of people use NGAlerts with evaluation rules on Grafana but this issue causes a lot of noise.
In case of irregular reporting, grafana fire an alert for each "hole" because Reduce function considere it as NaN.

In my opinion, reduce should take the first valid point in range to avoid NaN and if all values are empty or NaN we should have an option to ignore NaN values in alerts.

**Comment by zoltan-fedor** [comment]
I agree, this causes a LOT of issues (eg false alerts). Due to this now I have to have silencers for all low-traffic periods (weekends in my case) and so during those times I cannot catch real issues. It kind of defeats the purpose of alerting.

**Comment by frankvdbh** [comment]
Tracking this as well as we moved to the new alerting system in staging environment and cannot align production until this is fixed. Most if not all of our alerts are based on multiple series (group by) where most of them are returning no data in the "OK" situation.

**Comment by zoltan-fedor** [comment]
Actually the "no data" is not a problem, as long as you don't have a ratio resulting in an NaN.
This is because "no data" can be handled (there is an option for it in the new alerting system), but for NaNs, there isn't.

**Comment by devgianlu** [comment]
I've made https://github.com/grafana/grafana/pull/43526 to fix this.

**Comment by zoltan-fedor** [comment]
@devgianlu , this is great, thanks for the fix. Let's hope it will get merged soon!!

**Comment by yuri-tceretian** [comment]
@zoltan-fedor thanks for reporting! Sorry, I did not catch it earlier. Thanks to @devgianlu's PR for bringing visibility. 
I agree the current design lacks the handling of NaN. However, I do not think I agree with the proposed way of handling it https://github.com/grafana/grafana/pull/43526: `NoData` describes a situation when the data source does not return any data. In my opinion, NaN does not fit that category as it is still a data point even though it is not a valid number. 

I think NaN is a better fit for the Error category because usually, it is an indicator of some invalid (or undefined) operations on numbers like `1/0`, `sqrt(-1)` or `log(-1)`. @kylebrandt what do you think?

**Comment by devgianlu** [comment]
I agree that division by 0 should be an error, but in the most common use case that means that there is no data. As @zoltan-fedor explained above:
> Without that the new unified alerting basically cannot be used for ratios
(like error ratios), as in low traffic periods (eg weekends), it will
occasionally throw NaNs and trigger this alert, simply because in the
selected timeframe the usage was so low, that it was a division by zero (eg
there was no traffic at all).

The problem usually occurs from doing `sum / count` calculations. A zero count is no data. Error would be fine too, just explaining my thought process.

**Comment by kylebrandt** [comment]
The SSE reduce operation needs Inf/NaN/Null Handling options I believe.

The current behavior is to return NaN from reduce is to return NaN if there series is empty, or contains NaN or Null values in. I think of this current behavior as "strict".

Using "strict" reduce operations means that if there are any NaNs or Nulls in a series that is reduced (with many cases, like mean, at least) will bubble up as NaN results in the end. In this situation, mapping NaNs to "No Data" seems incorrect (since there was some data for the series).

If an option (or options) exist for reduce operations to drop and/or replace Inf/Null/NaNs, then a single NaN in a series would not trigger a NaN result. In this mode, there still need to be a decision or user option on what value to return in the case where there no concrete numeric value. If NaN is returned in this case, then mapping it to No Data would make more sense, but we still have the error case that @yuri-tceretian points out.

If in the empty-after-filter reduce operations return null instead of NaN, and we distinguish those (unlike the current behavior) then perhaps Null maps to No Data, and NaN to error.

These cases are tricky to get the right design, I imagine related to this, the "math" operation also perhaps needs NaN/Null handling options, or perhaps functions like is isNaN. The math operation also needs join options for both items with it in a set, and in the case of series - point-by-point operations.

But that being said, making null different from inf/nan and introducing a dropna like option into reduce seems like a step in the right direction to me.

**Comment by gillg** [comment]
For information, I found a workaround to have a behavior similar to a pure Prometheus alert.
The idea is simple, you use exactly the same query that you would use on Prometheus (promql statement < xxx), then you double the condition in grafana with reduce + math $A < xxx (obviously it will be always true because $A already contains the condition), else you have a "real" no data else it's true.

But anyway I agree it could be interesting to have an option to choose how to deal with NaN (alert or no alert)

**Comment by zoltan-fedor** [comment]
@devgianlu is right - the original use case I have raised is the use case of monitoring error ratios.
In almost all serious monitoring systems you monitor ratios instead of actual events - ratios like error ratio, ratio of failed password attempts, ratio of short-lived sessions, etc.

Unfortunately all user-activity driven ratios in low traffic periods (eg weekends, overnight) - especially when the timeframe is short (1m or even less) - can results in NaNs simply because the denominator becomes 0. Currently, that will result in an NaN, which will result in an alert being fired.
To explain through an example: `sum(errored requests)[1m] / sum(all requests)[1m] `will become NaN if `sum(all requests)[1m]` is 0, which can easily happen during low usage periods (eg over the weekend / overnight).

As such, the unified alerting since 8.0.x is either throwing lots of false posittive alerts due to these NaNs or alerts need to be silenced for expected low traffic periods in advance (which hides real issues happening during those periods).
This is a serious shortcoming which had no workaround to-date (I haven't tested @gillg 's recommended workaround yet).

There could be many ways to solve for this. My preferred order of solutions would be:
1. Add an "isNaN" "math" operation to allow the handling/replacement of NaN values
2. Add a new configuration option (like No Data and Execution Error) to handle NaN
3. Bundle up the handling of NaNs with the No Data option, as the most typical reason to get NaNs is having no data in the denominator of a ratio.

#3 is certainly not my preferred option - because there might be other reasons for NaNs outside of "no data" (eg 0) in a ratio's denominator, but that seems like the quickest way to solve this relatively major issue and I do believe that no data is the major reason of NaNs.
If we could get rolling with solution #1 or #2, then that would certainly be preferred.

I know that solution design should not be driven by urgency, but we are at 8.3.x and this relatively major issue is outstanding since 8.0.x, so I would also consider giving some preference to the possible solutions based on their potential speed of delivery.

**Comment by devgianlu** [comment]
I agree, this issue is very annoying and been around for a while. #3 is definitely the quickest way too solve it (just merge the PR). #1 and #2 could be extensive solutions for the future.

**Comment by kylebrandt** [comment]
@zoltan-fedor As a work around, does something like the following currently work? `sum(all requests) && sum(errored requests)[1m] / sum(all requests)[1m]`

If the sum is zero, it should short circuit and not alert. This won't cover all the cases, but if the all_requests series is not empty but just zero valued, then this should avoid the div by zero.

**Comment by zoltan-fedor** [comment]
@kylebrandt, theoretically it should work, but I am not being able to make it work.

(1) This was the original Prometheus metric:
`sum (rate(traefik_service_requests_total{service=~"default-app1-.+",code=~"4..|5..",code!="404"}[1m])) / sum (rate(traefik_service_requests_total{service=~"default-app1-.+"}[1m])) * 100`
You can see how this becomes NaN when the denominator is 0 (which happens when there was no traffic in the last 1m.

(2) This is the modified one - which unfortunately errors:
`sum (rate(traefik_service_requests_total{service=~"default-app1-.+"}[1m])) && sum (rate(traefik_service_requests_total{service=~"default-app1-.+",code=~"4..|5..",code!="404"}[1m])) / sum (rate(traefik_service_requests_total{service=~"default-app1-.+"}[1m])) * 100`
This results in error:
`Failed to evaluate queries and expressions: failed to execute conditions: failed to execute query A: bad_data: 1:83: parse error: unexpected character: '&'`

Did I misunderstand what you were suggesting?

**Comment by gillg** [comment]
@zoltan-fedor add your math condition in the query (and keep it in the grafana, so change nothing else).
It will produce "No Data" instead of noisy NaN and everything will be fine

**Comment by kylebrandt** [comment]
If you do that in prom, it needs to be `and` and not `&&`, Server side expressions and promql have different syntax there.

**Comment by zoltan-fedor** [comment]
@gillg you are right. That seems to be working, although it is definitely a bit of a workaround.
Now that the condition has been added to the Prometheus query it will return No Data as long the condition is not satisfied (eg the error rate is below the threshold) and then returns the actual data once the condition is true (error rate threshold reached), so then it can go through the rest of the reduce and math operations. Obviously I will need to set the No Data setting to No Alert, but otherwise this should work.

Thanks, I think this is a reasonable workaround for the time being, which means that now we have a workaround for the issue, so there is time to implement a proper solution for the handling of NaNs, like (1) or (2) listed above.

**Comment by zoltan-fedor** [comment]
@kylebrandt you are right, that works too.

Okey, so we have two workarounds. Probably workaround (1) from @kylebrandt is a bit easier for most to understand:

(1) And the ratio's denominator as a boolean condition to your Prometheus expression before the ratio, so it looks something like:
`sum (rate(traefik_service_requests_total{service=~"default-app1-.+"}[1m])) and sum (rate(traefik_service_requests_total{service=~"default-app1-.+",code=~"4..|5..",code!="404"}[1m])) / sum (rate(traefik_service_requests_total{service=~"default-app1-.+"}[1m])) * 100`
This will make it return 0 when the denominator is 0 instead of returning the NaN from the ratio. (workaround by @kylebrandt )

(2) Add the condition to your Prometheus expression:
`sum (rate(traefik_service_requests_total{service=~"default-app1-.+",code=~"4..|5..",code!="404"}[1m])) / sum (rate(traefik_service_requests_total{service=~"default-app1-.+"}[1m])) * 100 >= 15`
This will make the expression return No Data when the ratio is not meeting that condition and the actual value otherwise. You will need to handle the No Data scenario in your alert. (workaround by @gillg )

**Comment by yuri-tceretian** [comment]
Glad we've found work around so we can focus on the properly addressing the issue.

From Kyle's analysis [above](https://github.com/grafana/grafana/issues/40392#issuecomment-1001640616) I can conclude that his suggestion is 
1. Distinguish between `null` and `NaN` (as well as `Infinity`).
2. Add option to drop `NaN` values from the collection of values

Another option:
1. Introduce support for functions `isNaN($expr)`, `isNull($expr)` etc
2. Implement filter operation. It will apply a predicate to every value of a dimension and if predicate's result is positive return provide the value downstream. It is worth mentioning that If the resulting collection is empty the operation should return error (or make it configurable).
As an addition to the Filter operation I would really like support for a conditional operator in Math operation (either ternary operator or some function `if(expr, expr, expr)`. This would make the Math operation a proper "map operation" that would allow to have better control on data. This will allow users to decide by themselves what to do with NaN values and map them to some values.

**Comment by kylebrandt** [comment]
This thread is making me think it might make sense to make a function called ratio.

`ratio($a, $b)`: Returns `$a / $b` or `0` if `$b == 0`.

Basically suppressing the `NaN` from `0/0` or the `Inf` from something like `1/0`. The second case could be changed not be suppressed if `ratio` returned 0 when `$a == 0 && $b == 0`. This would be more likely to catch user mistakes, but I don't think it would be the better choice since often we are dealing with time series, so if there is some slight mis-alignment, would get Infs, and this might trigger unwanted notifications.

**Comment by thomasstoermer** [comment]
We are having same issues with `NaN`, but queries based on:
`sum(increase(my_counter_metric[1m])) by (label1, label2)`

The problem occurs e.g. on deployments where metrics disappear (some metrics are only created on occurrence). So, I guess the improvements should also fix this one?

**Comment by armandgrillet** [comment]
This issue is fixed in 8.4, please reopen if that is not the case.

**Comment by bmcclory** [comment]
Just wanted to chime in here and mention -- I don't think this workaround is a good one:

> (1) And the ratio's denominator as a boolean condition to your Prometheus expression before the ratio

The value of the query will become the denominator value instead of the ratio value, because with [PromQL 'and' operator metric names and values are carried over from the LHS vector](https://prometheus.io/docs/prometheus/latest/querying/operators/#logical-set-binary-operators). You probably don't want to do math/reduce expressions on the denominator, right?

So 8.4 fix is really the only option here, I think. 

Also, I don't see a "Last" reduce function in 8.3.x, which I think is what you'd probably want here.  I don't think it's statistically valid to do a Mean of ratios over a range of time (as shown in the original screenshot) But I'm pretty new to Prom/Grafana alerting, so I could be misunderstanding something here. 

As a new user, some real world examples of alert rules for error ratios would probably be helpful.

**Comment by gillg** [comment]
In my opinion as Prometheus user, the only thing what make sense to follow a native Prometheus alert is :
- Make your promql query with "and" or whatever. In case of logic operator you are right the value is coming from the left part, and put your condition in the query to limit the number of results.
- use a math reduce "last" and replace null or Nan by 0
- create a fake always true condition ($B == $B) because the condition is already in the query...

At some point grafana should also implement an instant query instead of range query for alerting in case of Prometheus data source.
I think the original idea is to "simplify" alerting rules, with this UI, but you can stick to a Prometheus behavior with parameters above.

**Comment by yuri-tceretian** [comment]
> At some point grafana should also implement an instant query instead of range query for alerting in case of Prometheus data source.

Here is PR https://github.com/grafana/grafana/pull/44865 that needs some additional work.

**Comment by robinp** [comment]
In case it helps someone, there was a (dropdown?) option on the alerts operation  if the operation is strict or else what to do - for example replace non-numeric values with a given number.
