### ISSUE TITLE
Inviting new users to organisation generates dud URLS with 'localhost'

### ISSUE THREAD

**Issue by TysonJones** [grafana/grafana#4042]
I'm running Grafana 2.6.0 on RHL6.
When, through the organisations interface, I try to invite any new user to my organisation (with valid names and email addresses), it creates the dialog:
**Problem! Failed to send email invite**

When I look at _details_ of the invite under _Pending Invitations_, I see that it's tried to email an invalid URL, such as:
`http://localhost:3000/invite/34SvdJAooKFDLP5LDvprNPCWQ3YUsx`
That is, it has used `localhost` instead of the Grafana site's actual domain (which is online, fully functional and publicly accessible).

Currently, I have to modify and email the correct URL myself, which allows the user to register successfully.

**Comment by torkelo** [comment]
just update this root_url setting to be the correct one :)

http://docs.grafana.org/installation/configuration/#root_url

**Comment by souvikhaldar** [comment]
Thanks @torkelo

> just update this root_url setting to be the correct one :)
> 
> http://docs.grafana.org/installation/configuration/#root_url

**Comment by enggal17** [comment]
Hi @torkelo 
I've changed the root_url setting but it's not working. the invitation still the same with URL http://localhost:3000
![image](https://user-images.githubusercontent.com/52996025/122931314-f8f08700-d396-11eb-921f-79a7decda5e8.png)

**Comment by jadbaz** [comment]
@enggal17, you also have to set: GF_SERVER_DOMAIN explicitly

I have Grafana in docker behind nginx on port 8080
I want emails to arrive with "http://domain:8080"
I had to set both the domain and port
      - GF_SERVER_HTTP_PORT=8080
      - GF_SERVER_DOMAIN=domain

This means that nginx is communicating with Grafana on docker network on "grafana:8080" and nginx is also exposed on port 8080
This is the only way I managed to make this work

So the question is
Supposing I have Grafana behind nginx in docker network, can I have Grafana running on a different port than nginx?
Right now, if I want to change my nginx port to 8081, I also need to change "GF_SERVER_HTTP_PORT" to 8081 and then access grafana in nginx at: "grafana:8081". Otherwise, emails would still arrive with links to "domain:8080"

Finally, how would that work with https if nginx is managing https?

**Comment by polenilson** [comment]
> Oi@torkelo 
/usr/share/grafana/conf/defaults.ini
change the domain
domain = example.com.br

**Comment by 2019-05-10** [comment]
To the day 7 years later and this is still an issue!
Neither `domain` nor `instance_name` are used, but Grafana 9.3.2 still  stupidly insists on using the hostname of the host system! How is that even possible?

**Comment by Threx71** [comment]
if someone gets to see this as it's the first result on google in 2025,

A couple of lines before root_url in your grafana.ini is "enforce_domain" set it to true (and don't forget to uncomment it removing the ; )
