### ISSUE TITLE
Cannot select Log Analytics workspace resource in query

### ISSUE THREAD

**Issue by macropan** [grafana/grafana#40511]
**What happened**: when add a query for Logs query, cannot select workspace resource 

**What you expected to happen**: in the selectiong, i should to select LA workspace in resource group.

**How to reproduce it (as minimally and precisely as possible)**: create a dashboard panel, 
datasource: Azure China
Service: Logs
Resource: select a logs analytics workspace.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.1(The problem also existed in previous versions)
- Data source type & version:  Azure Monitor, Azure China
- OS Grafana is installed on: CentOS 6.9, docker contain
- User OS & Browser: Edge
- Grafana plugins:
- Others:
![Screen Shot 2021-10-15 at 5 20 26 PM](https://user-images.githubusercontent.com/6326663/137464399-9288bb8c-c518-404c-a86c-a6cac1c92fe2.png)
![Web capture_15-10-2021_173025_omcops bmw com cn](https://user-images.githubusercontent.com/6326663/137465837-03d02ee9-283d-4b05-bd80-7c6decb6a4df.jpeg)

**Comment by macropan** [comment]
Yes, sure. Currently I can edit the JSON manually.

**Comment by andresmgot** [comment]
Hi @macropan, let's try to debug the issue. When you click in the > chevron, if you check the Network tab of your browser, you should see a request like this one:

![Screenshot from 2021-11-24 18-03-09](https://user-images.githubusercontent.com/4025665/143283206-9db65186-8914-4a79-a935-4eb7193b4332.png)

Does that request return any error? Can you find any related error in the Grafana logs?

**Comment by ehuggz1** [comment]
I just had a similar issue, but in US Cloud. The issue was a little different however.
Azure Data Source, expand Resource Group, all resources listed, scroll down to Application Insights - click and windows scrolls back to resource group. Scroll back down to Application Insights and found it was not selected.

I realized I could select the resource group and I could select the resources immediately below the resource group. I found that if I clicked and selected a resource and the unclicked it, I could click the next one. I continued on down to Application Insights and was able to select Application Insights as a data source. I tested and LogAnalytics did the same thing.

Additional testing shows that scrolling a selected (checked) resource to the top of the window and then unclicking allows you to select any box already visible in the scroll window, which can then be scrolled to the top, deselected and item at bottom of scroll window selected, repeat until desired resource is in a window that is selectable.

Grafana Online (Pro) 8.3.3

**Comment by andresmgot** [comment]
Hi @ehuggz1,

That sounds like a bug. Can you send screenshots of the behavior that you are seeing so we can try to debug the issue? Also, are there any errors in the Console or Network tab of your browser?

**Comment by ehuggz** [comment]
The specific issue is a little hard to show in a screenshot - but is quite repeatable.
1. Create a new Dashboard Panel, select Azure Data Source and set service to Logs (Screenshot 1)
2. Click Open Resource and navigate to Subscription and Resource Group containing Kusto Query Data Sources (Screenshot 2)

Note: Resource Group must contain more Resources than will fit on the screen. Replicating the issue will require a resource group containing 10 or more resources, with the resource to be selected toward the end of the list of resources within the Resource Group.

3. Scroll past existing resources and try selecting a resource - click will be taken back to the resource group with nothing selected.

The work around I discovered is that you CAN select a resource that is initially visible, scroll the selected resource up to make more resources visible, de-select current resource, select new resource from bottom of visible list, scroll up, and repeat until the desired resource is selectable. 

While I've discovered a workaround, it is very time-consuming and tedious. Let me know if you have trouble replicating the issue and need more information as I will be glad to help.

![1-AzureResourcePickerBug](https://user-images.githubusercontent.com/54
![2-AzureResourcePickerBug](https://user-images.githubusercontent.com/544939/147127637-02ecb093-c542-4af8-ab15-12811c5aac16.jpg)
4939/147127619-9b83eaaf-8272-42a0-8280-8a71279f1c0c.jpg)
.

**Comment by andresmgot** [comment]
Thanks for the details @ehuggz I can reproduce the issue. Interestingly, only happens sometimes for me so if I scroll around, sometimes it allows me to click in the element and sometimes don't. If a resource is already selected and all the other items are disabled I am also able to reproduce the issue (clicking an element, causes the scroll bar to change). The bug seems different than the original one reported by @macropan though. Can you create a new issue so we can track them differently?

BTW, the `ResizeObserver loop limit exceeded` seems to be harmless (I don't get it in my browser).

**Comment by ehuggz** [comment]
Issue #43503  created

**Comment by iwysiu** [comment]
> 

Hi @macropan did you get a chance to look at this?

**Comment by macropan** [comment]
@iwysiu 
Sorry for being late in replying
for me, when I select resource, there is nothing shows. and no error in network tab of my browse.

![image](https://user-images.githubusercontent.com/6326663/148352036-ec2ee532-4191-4ce0-8f09-79144a236ab0.png)

**Comment by andresmgot** [comment]
thanks @macropan, if there are no errors, can you confirm that the response return no entries? if you check the response it should say something like `totalRecords: 0`:

![Screenshot from 2022-01-10 16-16-41](https://user-images.githubusercontent.com/4025665/148790133-347943a4-5c54-4248-a407-8c3f730e6ee0.png)

I suspect that the problem is in the request that we are doing to retrieve resources:

https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts#L85

I think that we are likely missing China locations in this hardcoded list: 

https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/azureMetadata/locations.ts

Can you verify if the location of your resources are missing from that list?

Other possibility is that the resource types list is incomplete:

https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/azureMetadata/resourceTypes.ts

Can you check if any of the above can be causing your issue?

**Comment by macropan** [comment]
![image](https://user-images.githubusercontent.com/6326663/149688468-e45e397c-02b5-405c-9ea5-89d271346a42.png)

![image](https://user-images.githubusercontent.com/6326663/149688441-adaa23d6-576c-4415-b2e8-3495608dd3b2.png)


 {
    location: 'chinaeast',
    displayName: 'China Eest',
    supportsLogs: true,
  },
 {
    location: 'chinaeast2',
    displayName: 'China Eest 2',
    supportsLogs: true,
  },
 {
    location: 'chinanorth',
    displayName: 'China North',
    supportsLogs: true,
  },
 {
    location: 'chinanorth2,
    displayName: 'China North 2',
    supportsLogs: true,
  },

The above 4 are regions of China, and I think there was no missing in resource types list
