### ISSUE TITLE
Alerting: alert rules page errors out on prom/loki datasources with no URL

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana#40614]
**What happened**:

If you have Grafana 8 alerting enabled, create a Prom or Loki datasource with empty URL and then go to alert list page, you see an error for these datasources. It is annoyingly easy to have such datasources, as they are saved before you even start filling out the datasource form. 

**What you expected to happen**:

Maybe datasources with no URL should be ignored? Or alternatively, produce a better error message that clearly explains the problem.

**How to reproduce it (as minimally and precisely as possible)**:

1. Have grafana 8 alerting enabled
2. Create Prometheus datasource, do not fill in URL
3. Go to alert list page, see error

I think related: https://github.com/grafana/support-escalations/issues/1146

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by gillesdemey** [comment]
We should be able to retrieve the URL from the `DataSourceInstanceSettings` located in `jsonData.directUrl`, will try something to either filter the errors from these "empty" datasources.

**Comment by armandgrillet** [comment]
Thanks for investigating @gillesdemey, @santihernandezc can you check if what Gilles recommends is the best way we could check for the URL? Or could we do another change in the backend to stop showing errors to the end-user?

**Comment by santihernandezc** [comment]
What @gillesdemey suggests solves the issue of created datasources with no URL, but we should also consider cases where the URL is non-empty but still invalid. IMHO this problem should also be addressed earlier.

Right now, datasources are being created before even asking the user for details, and the function responsible for saving this new datasource accepts an empty string as a valid URL.
https://github.com/grafana/grafana/blob/f346bbb3bb7354b9e77df10f3383a7be10badcb2/pkg/api/datasources.go#L202-L212

The request to create a datasource should be made after the user had the chance to fill out the corresponding form.

Also, there should be some kind of validation in place (e.g. indicating which fields are required and returning a `400` error if necessary) when creating/updating datasources in order to keep consistency and avoid saving invalid data.
