### ISSUE TITLE
Prometheus: Variables with the `:regex` modifier do not escape forward slashes properly (/)

### ISSUE THREAD

**Issue by kminehart** [grafana/grafana#40634]
**What happened**:

I created a variable that has multiple values that have `/` in them.

Example variable values:

```
grafana/grafana
grafana/tempo
grafana/loki
```

And I created a prometheus query and selected a couple of these variables and put them in my query with the `:regex` modifier. Example:

```
some_metric{repo=~"${repos:regex}"}
```

This produced a query like this:

```
some_metric{repo=~"(grafana\/grafana|grafana\/loki|grafana\/tempo)"}
```

Which results in a `Metric Request Error`.

**What you expected to happen**:

This should have actually produced this query:

```
some_metric{repo=~"(grafana\\/grafana|grafana\\/loki|grafana\\/tempo)"}
```

**How to reproduce it (as minimally and precisely as possible)**: Feel free to PM me for an explore link. :)

**Anything else we need to know?**:

**Environment**: Cloud
- Grafana version: Grafana v8.3.0-38162pre (6d4088292)
- Data source type & version: Prometheus

**Comment by gabor** [comment]
hi @kminehart @markspolakovs , could you try wrapping the regex-string into backticks instead of doublequotes?
something like ``some_metric{repo=~`${repos:regex}`}``

this should work. if not, please reply and we can reopen the issue.

(in general, how to escape a regex-string so that it works in many scenarios is quite complicated, but for this use-case the backticks should do the trick)
