### ISSUE TITLE
Elasticsearch alias field should support template variable interpolation 

### ISSUE THREAD

**Issue by a13xb** [grafana/grafana#4075]
I have a graph with 2 data series per template variable value. The default alias seems to be template variable value itself.

I want to set the alias (and legend) based on metric name _and_ variable. E.g. if I have two metrics `M1` and `M2`, and select two object (id=1111, id=2222), I want to see `M1 (1111)`, `M2 (1111)`, `M1 (2222)`, `M2 (2222)`.

But alias field doesn't seem to recognise the template variable and is using it verbatim and the result is `M1 ($id)`. Any suggestions?

**Comment by torkelo** [comment]
might be that it's not interpolating variables

**Comment by jalalahmad** [comment]
Is anyone working on this issue? I am facing a similar thing.

**Comment by marefr** [comment]
@rnsc Possibly yes, but we haven't prioritized it since only 2-3 people have upvoted it. If you're interested in contributing we're available to help and review. 

Should be a quite trivial change [here](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/datasource.ts#L257).

Something like 

```javascript
if (target.alias) {
  target.alias = this.templateSrv.replace(target.alias, options.scopedVars, 'lucene');
}
```

**Comment by ragnarok56** [comment]
is this problem solved by doing a terms groupby and including `{{term fieldname}}` in the alias?

**Comment by WonderWn** [comment]
@ragnarok56 answer is correct, Thanks it helped me!

**Comment by marefr** [comment]
Fixed by #14804

**Comment by beingyash** [comment]
@ragnarok56 Thanks for the solution but i have another variable inside that syntax which gets interpolated but then the whole term doesn't. Let me explain that with an example.

I have multiple terms that want to aggregate over based on values available from the custom variable dropdown i created.
The terms are:
 - myRegionName.keyword
 - myTerritoryName.keyword
 - myCityName.keyword
 
 So, instead of creating multiple queries/panels for each term, i create a custom variable "var" with values:
 - Region
 - Territory
 - City
 
So, in the terms aggregation query, now i use my${var}Name.keyword and it works like a charm based on the dropdown selection. The challenge occurs when i try to use the alias. Previously {{myRegionName.keyword}} worked alright, but in the current scenario, i need {{my${var}Name.keyword}} only interpolates the ${var} and not the resultant string in side the {{ }}, hence all series names are displayed as {{myAreaName.keyword}} and not the actual area names from the aggregated term.

@torkelo @marefr Because of this challenge, i'm unable to use transformations on my queries as both queries return the same series names.

**Comment by beingyash** [comment]
Turns out, [this](https://github.com/grafana/grafana/issues/24239) issue was already reported.
