### ISSUE TITLE
Bar chart: Stacking order by legend doesn't take effect for the first render

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/grafana#40874]
**What happened**:

https://user-images.githubusercontent.com/13729989/138099796-0bec7036-2ebf-4c00-a1ed-e435ca648c4d.mp4

**What you expected to happen**:

I expected to see the stacking ordered when I visit the dashboard the first time.

**Environment**:
- Grafana version: Grafana v8.3.0-pre (9e030970aa)
- Data source type & version: Test datasource

**Comment by leeoniya** [comment]
we've removed this functionality in https://github.com/grafana/grafana/pull/47373 to avoid:

- Series from re-stacking dynamically during data updates (can be quite bad experience with spikes, if stacking by dynamic min, max, last, or avg)
- Dashboards changing unpredictably from day to day or reload-to-reload

In addition to above, if series order can change without notice and colors were not explicitly set via overrides, then the colors can be re-assigned to other series, make the data hard to interpret. though this issue is not specifically related to stacking.

The stacking order now follows series order, and can be controlled via the [Organize fields transform](https://grafana.com/docs/grafana/latest/panels/reference-transformation-functions/#organize-fields), or by reordering the query. We intend to evaluate additional alternatives, such as adding `stacking.order` config alongside the existing `stacking.mode` and `stacking.group` config options.
