### ISSUE TITLE
Table panel:  Gauges do not perfectly align with values of different lengths

### ISSUE THREAD

**Issue by Trovalo** [grafana/grafana#40925]
**What happened**:
In a table panel, when showing data as a gauge bar with a fixed min and max scale value the plotted charts might not be aligned, and it depends on the "size" or better length of the number that is written on the right of the chart.

![image](https://user-images.githubusercontent.com/12230314/138854035-f0213483-03c6-41cc-a908-542840fe5d8a.png)

here is the whole override configuration
![image](https://user-images.githubusercontent.com/12230314/138854112-1a08e61e-10e7-44ad-a3b3-d66d534cdc9d.png)

**What you expected to happen**:
I expect the gauge charts to be aligned

**How to reproduce it (as minimally and precisely as possible)**:
see _what happened_
**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.1
- Data source type & version: InfluxDB 1.8.6
- OS Grafana is installed on: Windows Server
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: None
- Others:

**Comment by baldm0mma** [comment]
Hey all, looks like this is happening regardless either of the unit formatting (no current formatting in my screenshot) or the gauge display mode (basic, gradient, or lcd). I don't think this is adding padding in a weird way, nor is it css width prop issue, since everything defaults to 100%, but I'll take a closer look either way.

![Image](https://user-images.githubusercontent.com/46619047/221689114-88ae9aa3-4967-4968-9452-f8e0fb1dfa45.png)
