### ISSUE TITLE
8.2.2: Alertmanager never becomes ready

### ISSUE THREAD

**Issue by asciifaceman** [grafana/grafana#40964]
**What happened**: Upgraded to 8.2.2, Alertmanager never seems to have started, hours later. No visible configuration or logging around alertmanager to investigate deeper or point to existing working alertmanager

```
Error loading notifications
Alertmanager is not ready yet
```

```
Oct 26 20:45:08 ip-10-90-165-111 grafana-server[2846]: {"count":0,"err":"Alertmanager is not ready yet","logger":"ngalert","lvl":"eror","msg":"unable to lookup local notifier for this org - alerts not delivered","org":1,"t":"2021-10-26T20:45:08.757043915Z"}
```

I'd love to provide more details if they are relevant, but I don't have much to go on from logs or state other than the errors in the UI and the 409s on the backend.

**What you expected to happen**: Alertmanager to become available and tabs in alerts UI to load.

**How to reproduce it (as minimally and precisely as possible)**: Upgrade Grafana to 8.2.2 from 8.1 and launch 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.2
- Data source type & version: 
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by asciifaceman** [comment]
I'm wondering if it is possible there is a situation here where a bad alertmanager config was created as part of the migration causing it to not start, but it can't be updated unless alertmanager is started

**Comment by asciifaceman** [comment]
It seems this query may have fixed alertmanager for me

```
update alert_configuration set `alertmanager_configuration` = '{"alertmanager_config": {"route": {"receiver": "grafana-default-email"},"receivers": [{"name": "grafana-default-email","grafana_managed_receiver_configs": [{"uid": "","name": "email receiver","type": "email","isDefault": true,"settings": {"addresses": "<example@email.com>"}}]}]}}' where `id` = 1;
```

This set the am configuration to the default as defined in the codebase.

It appears the migration generated an invalid am configuration somehow.

Alert Manager is now working for me.

**Comment by zuchka** [comment]
@asciifaceman sounds like you are unblocked on this, so I am going to close the issue.

If that's not the case, please any new details to share and we'll reopen 👍

**Comment by SunSparc** [comment]
I just migrated database hosts and am seeing what appears to be the same issue. I have an instance of Grafana `v9.1.0` in two locations (old and new). I did a `mysqldump` of the existing database and imported it into the new database. As the new instance of Grafana was starting, several errors happened.

Here are some of the errors that seem most relevant:
```
logger=alerts-router rule_uid=t-ps_eOnk org=1 t=2022-09-01T21:54:00.668067674Z
    level=error msg="local notifier is not available" err="Alertmanager is not ready yet"

logger=alerts-router rule_uid=t-ps_eOnk org=1 t=2022-09-01T21:54:00.668167223Z
    level=error msg="no external or internal notifier - [%d] alerts not delivered" 1=(MISSING)

logger=ngalert.multiorg.alertmanager
t=2022-09-01T21:53:59.226291615Z
level=error
msg="failed to apply Alertmanager config for org"
org=1
id=191
err="unable to apply configuration: failed to build integration map: the receiver is invalid:
    failed to validate receiver \"Slack#testing-channel\" of type \"slack\":
    invalid URL \"\\xd6\\t\\x12\\x12\\xeb_8\\xf9d\\xbb\\xd4\\xc4]\\xed\\xaeMNhn\\xe9\\xd0CB\\xdc)|\\xd0\\x1fH\\xadU[\\x0f\\x80sV\\x88\\x93\\x94\\xc4\\xf0\\xe9r\\b\\x88\\xb2s4R\\xf3rȗ:\\xf7\\x9c\\x03\\xae\\vT!RH\\xe5\\xc9\\xd8\\x11d2\\x00\""
```

It could be that the database dump file was not able to support some of the data and so it was corrupted. The new server has some provisioning files, and perhaps those conflicted with existing provisions from the imported database.

I considered the query that @asciifaceman ran, but my `alert_configuration` table does not have any `alertmanager_configuration` field that starts with `'{"alertmanager_config": {"route":`. All the rows in that table for me start with `{"template_files":{"Slack Notifications Template":`.

I decided to try inserting that row:
```
insert into alert_configuration
    values (1,'{"alertmanager_config": {"route": {"receiver": "grafana-default-email"},"receivers": [{"name": "grafana-default-email","grafana_managed_receiver_configs": [{"uid": "","name": "email receiver","type": "email","isDefault": true,"settings": {"addresses": "<example@email.com>"}}]}]}}','v1',1662150428,1,1,'not-yet-calculated');
```
That did not seem to help.

I dropped the database, and started the migration over.

When I brought back up the new instance of Grafana with the migrated database, I updated the datasources manually and tested them to make sure they were working. There were still errors saying that "Alertmanager is not ready yet". So I dug around in the code for a bit.

```
// AlertmanagerFor returns the Alertmanager instance for the organization provided.
// When the organization does not have an active Alertmanager, it returns a ErrNoAlertmanagerForOrg.
// When the Alertmanager of the organization is not ready, it returns a ErrAlertmanagerNotReady.
func (moa *MultiOrgAlertmanager) AlertmanagerFor(orgID int64) (*Alertmanager, error) {
	<snip>
	if !orgAM.Ready() {
		return orgAM, ErrAlertmanagerNotReady
	}
	<snip>
}

func (am *Alertmanager) Ready() bool {
	// We consider AM as ready only when the config has been
	// applied at least once successfully. Until then, some objects
	// can still be nil.
	<snip>
}
```

After reading these comments, I opened the "Configuration/Preferences" page, edited the Organization name, and clicked "Update organization name". That was all it took. My new system is now working.

I do not at the moment have a good suggestion for improving this situation, since this is not really a supported use case.
