### ISSUE TITLE
Feature Request : Auto align panels in a row

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4100]
It would be nice to have a dropdown item in that left green icon for each row, that says auto align and that will automatically align all panels in that row.

Right now i have to do this manually and it does not work correctly if there are odd number of panels (ex: 12/5 = 2.5, with + and - icon i cannot shif .5  ? )

If there are even number of panels i still have to manually hit + or - (12/4) number of times.

Hence having auto align feature will make this task easier and would align well in a row.

<img width="1393" alt="screen shot 2016-02-21 at 10 49 29 am" src="https://cloud.githubusercontent.com/assets/406777/13204619/2a056298-d889-11e5-91ae-f7ebb2f0b0b8.png">

**Comment by evanbreznyik** [comment]
Agree, but also wish the span/width controls were as granular as height.  On large monitors, the different between a span of "1" and "2" is huge and potentially a waste of space.

:+1:

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
