### ISSUE TITLE
Low Vulnerability found by image scanner after uploading Grafana 8.2.2 image to AWS ECR

### ISSUE THREAD

**Issue by wsgomes** [grafana/grafana#41063]
We get images from Docker Hub and upload them to AWS ECR.
AWS ECR scans the image for vulnerabilities.
It found the below vulnerability in Grafana 8.2.2 image.

Name: CVE-2020-28928
Package: musl:1.2.2-r3
Severity: LOW
Link: [https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28928](url)

**Comment by fatbasstard** [comment]
Issue still present in 8.2.5. btw

**Comment by marefr** [comment]
This looks like a false positive since the [link](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28928) explains the vulnerability is in musl up to 1.2.1 and musl 1.2.2-r3 is included in Grafana 8.2.2-8.2.5 and includes the fix of the vulnerability so I'm going to close this. See https://github.com/alpinelinux/docker-alpine/issues/123#issuecomment-888426624 for more information.

**Comment by ocbrollingpaper** [comment]
This is ongoing still, I have contacted AWS regarding it and they are 'looking into it'

**Comment by carsonwah** [comment]
@ocbrollingpaper Could you kindly share the ticket as a reference if you have raised any? Many thanks.
