### ISSUE TITLE
CloudWatch: Investigate potential memory leak

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#41183]
Helping out fixing a strict typescript error in https://github.com/grafana/grafana/pull/41160#issuecomment-956427683 when I found this subscription being created but not added to any unsubscribable:
https://github.com/grafana/grafana/blob/6675b084bd1c2e54ecf071d9f9425897a9e76aa6/public/app/plugins/datasource/cloudwatch/utils/rxjs/increasingInterval.ts#L23

Investigate if this can be added to subscriber so when that is unsubscribed all child subscriptions are too.

**Comment by taleena** [comment]
@yaelleC I may be off-base here, but could this be worth looking at while we are involved in adding unit tests?

**Comment by andresmgot** [comment]
I have investigated this a little bit. 

The function `dispatch` is associated with the `scheduler` entity:

https://github.com/grafana/grafana/blob/6675b084bd1c2e54ecf071d9f9425897a9e76aa6/public/app/plugins/datasource/cloudwatch/utils/rxjs/increasingInterval.ts#L19

This `scheduler` generates a new `subscription` that, as explained in the first comment here, needs to be closed. This is done automatically since we are using `subscriber.add` for generating the `scheduler`:

https://github.com/grafana/grafana/blob/6675b084bd1c2e54ecf071d9f9425897a9e76aa6/public/app/plugins/datasource/cloudwatch/utils/rxjs/increasingInterval.ts#L12

The result of `scheduler.schedule`, which is a subscription, is passed to [`subscriber.add`](https://rxjs.dev/api/index/class/Subscription#add-) as a "teardown" argument. This means than when unsubscribing the parent `subscription`, the teardown arguments will be closed too. This is finally done in cloudwatch datasource code, in the `withTeardown` function:

https://github.com/grafana/grafana/blob/6675b084bd1c2e54ecf071d9f9425897a9e76aa6/public/app/plugins/datasource/cloudwatch/datasource.ts#L973

I have verified this, saving a reference to the subscriptions that the scheduler generates:

```
  const sub = this.schedule({ subscriber, counter: counter + 1, period: newPeriod, step, endPeriod }, newPeriod);
  subs.push(sub);
```

and verifying that the `subs` are closed with the parent subscription:

```
    return () => {
      console.log(subs.map((s) => s.closed)); // returns [false, false, false]
      innerSub.unsubscribe();
      console.log(subs.map((s) => s.closed)); // returns [true, true, true]
      onUnsubscribe();
    };
```

So there is no memory leak here :)
