### ISSUE TITLE
Alerting: Include data source ID in NoData alert

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#41330]
Recently, we added a new feature to Grafana alerting: a special alert when evaluation results in NoData state and it is mapped to `NoData`. See https://github.com/grafana/grafana/pull/40540 for more details. 
The current implementation does not report the ID of the data source(s) that cause NoData state. I think it will be useful to report this. 
If we think that this is a good idea, we need:
- [ ] _Decide where we put that information._ I believe there are only two ways: annotation and label. I think that label is a better choice as it will be handled by Alertmanager and be distinguished from other alert instances.
    - [ ] Name of the label\annotation. 
- [ ] The alerting supports multiple data sources, and therefore, there can be more than one instance of NoData. _Thus, we need to decide whether Grafana fires one special alert (DatasourceNoData) per alert rule or it creates one alert per data source._ I think per data source is the more preferable option. The data source can be reused in many Alert rules, and reporting per data source would allow users to have more control over the routing of such alerts to special teams.

cc @grafana/alerting-squad

**Comment by gerobinson** [comment]
I think using a label instead of an annotation is the better option here as it can be used for grouping and silencing and we can use `DatasourceName` for the label name.

I don't think it makes sense to have a `DatasourceNoData` alert per data source instead of per alert rule because we are not alerting on the entire data source not having data, more often than not its just one series that is missing for a condition in one or more alert rules. If we had an alert per data source how would we communicate which alert rules are affected and which series are missing?

**Comment by santihernandezc** [comment]
I agree with George. I think firing a special alert for each data source that returns No Data and informing which alert rules are using that data source would imply a big code change in the scheduler logic just for a few missing series.

For me it just makes more sense to fire an alert per alert rule (`DatasourceNoData`) and specify which datasource is having issues.

**Comment by yuri-tceretian** [comment]
> If we had an alert per data source how would we communicate which alert rules are affected and which series are missing?

For example, alert rule uses two data sources Prometheus, SQL and an expression that joins the results. Currently, when one of data is not available, Grafana creates an alert:
```
{ alertName: DatasourceNoData, rule_name: "Test-Rule", .... <rule labels and annotations> } 
```
My suggestion is to add information what data source did not provide the data. In the case of both data sources, I suggest we create two alert instances:
```
{ alertName: DatasourceNoData, rule_name: Test-Rule, datasource_uid: F2asR_Prometheus .... <rule labels and annotations> } 
```
and 
```
{ alertName: DatasourceNoData, rule_name: Test-Rule, datasource_uid: F2asQ_SQL .... <rule labels and annotations> } 
```

One instance can be routed to an observability team, another to, for example, marketing.

**Comment by gerobinson** [comment]
Ah I misunderstood! I thought we were talking about replacing the `DatasourceNoData` alert per alert rule with a single alert per data source such that the maximum number of alerts is the total number of data sources configured in Grafana. For example:

```
{ alertName: DatasourceNoData, datasource_uid: "Prometheus", .... <labels and annotations> }
 ```

```
{ alertName: DatasourceNoData, datasource_uid: "SQL", .... <labels and annotations> }
```

But what we are talking about is having a `DatasourceNoData` alert for each alert rule and data source tuple that returns no data, as per the examples above:

```
{ alertName: DatasourceNoData, rule_uid: "abc", datasource_uid: "Prometheus", .... <labels and annotations> }
{ alertName: DatasourceNoData, rule_uid: "def", datasource_uid: "Prometheus", .... <labels and annotations> }
 ```

I agree with this and I think the `datasource_uid` and `rule_uid` should be labels instead of annotations because as mentioned it creates separate alerts that can be grouped and silenced in Alertmanager.

**Comment by gerobinson** [comment]
Ah I misunderstood! I thought we were talking about replacing the `DatasourceNoData` alert per alert rule with a single alert per data source such that the maximum number of alerts is equivalent to the number of data sources configured in Grafana. For example:

```
{ alertName: DatasourceNoData, datasource_uid: "Prometheus", .... <labels and annotations> }
 ```

```
{ alertName: DatasourceNoData, datasource_uid: "SQL", .... <labels and annotations> }
```

But what we are talking about is having a `DatasourceNoData` alert for each alert rule and data source tuple that returns no data, as per the examples above:

```
{ alertName: DatasourceNoData, rule_uid: "abc", datasource_uid: "Prometheus", .... <labels and annotations> }
{ alertName: DatasourceNoData, rule_uid: "def", datasource_uid: "Prometheus", .... <labels and annotations> }
 ```

I agree with this and I think the `datasource_uid` and `rule_uid` should be labels instead of annotations because as mentioned it creates separate alerts that can be grouped and silenced in Alertmanager.
