### ISSUE TITLE
Dashboard: Expression "All queries must use the same datasource"

### ISSUE THREAD

**Issue by castillo92** [grafana/grafana#41341]
A couple of releases ago, the Mixed datasource + math Expression was broken in the Dashboard page. As I checked in version 8.2.3, we are not able to query dato from different datasources and the do some math expressions.

We setup Mixed datasource, then make the queries and finally try to do some math operation with Expression. We expect a result, but it said: All queries must use the same datasource.

If we remove the math Expression query, it works and dashboard shows some data of different datasources. Only affect after adding one math expression.

![image](https://user-images.githubusercontent.com/37965565/140485444-74d8e963-b337-4bb8-95d3-dd756f36b22d.png)

![image](https://user-images.githubusercontent.com/37965565/140492721-9909a971-354b-4c32-889d-2e460c7ad5b2.png)

**Environment**:
- Grafana version: 8.2.3
- Data source type & version: InfluxDB
- OS Grafana is installed on: Debian 10
- User OS & Browser: Windows, Google Chrome
- Grafana plugins: None
- Others: None

**Comment by kylebrandt** [comment]
Introduced in commit https://github.com/grafana/grafana/commit/6bda64cb193771256bab56060da2df067ce6f72a via PR https://github.com/grafana/grafana/pull/38571

I believe this is fixed with https://github.com/grafana/grafana/pull/41172 , but that is marked for 8.3.0, so maybe it should be changed to 8.2.x ... thoughts @ryantxu

**Comment by kylebrandt** [comment]
@castillo92 until the fix is in, I believe there is work around that will get you around this problem. If you move one of the expressions to be first in the list, it doesn't change how anything is executed or evaluated as far as expressions are concerns, but the API will correctly identify it as an "expression" request if the expression operation is first:

![image](https://user-images.githubusercontent.com/1692624/140520139-182f1d5a-088d-4600-b8c1-cc2f4f1c5cf3.png)

vs:

![image](https://user-images.githubusercontent.com/1692624/140520259-325095c5-591c-4e64-a3f8-b8e83e2db5c9.png)

**Comment by castillo92** [comment]
@kylebrandt

Thanks you very much for the explanation and images! Changing the order of one expression at first position works around to solve the problem. 😃

I am grateful to receive your quick response.

**Comment by kylebrandt** [comment]
Once the bug is fixed it shouldn't matter if it is first or not.
