### ISSUE TITLE
InfluxDB: Escape field values

### ISSUE THREAD

**Issue by rafaelvittoruthes** [grafana/grafana#4148]
webgui does not pre-load column names and their values when containing long strings and/or with ' withing the name.
switching to edit mode, the field value is written like 'begin 'middle' end' when it should be 'being \'middle\' end' or "being 'middle' end"

**Comment by torkelo** [comment]
please specify what datasource your using. I guess InfluxDB?

**Comment by rafaelvittoruthes** [comment]
Sorry for missing info: right, influxdb 

Enviado do meu iPad

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
