### ISSUE TITLE
Alerting: Fix out of bounds threshold handle

### ISSUE THREAD

**Issue by peterholmberg** [grafana/grafana#41631]
If you set a threshold that is higher or lower than the current data, the thresholds handle is not visible.

**Comment by gillesdemey** [comment]
Investigating this one

**Comment by gillesdemey** [comment]
It turns out we have to dig a bit deeper than the `VizWrapper` we use in the unified alerting feature, with the help of @peterholmberg I've narrowed it down to the `ThresholdControlsPlugin` that simply seems to refuse to render anything if the threshold is outside of the time series area.

https://github.com/grafana/grafana/blob/2b2c0b8b5e65c953595a62148a7a1f20f2f1adcb/public/app/plugins/panel/timeseries/plugins/ThresholdControlsPlugin.tsx#L56-L58

I'll work on a fix to render the threshold indicator at the top or bottom depending on where it disappears from the canvas area.
