### ISSUE TITLE
Grafana generic oAuth SSO not working with Azure Active Directory B2C

### ISSUE THREAD

**Issue by sky29** [grafana/grafana#41656]
**What happened**:
We are trying to integrate Grafana oAuth SSO ( with generic oAuth, like mentioned here: https://grafana.com/docs/grafana/latest/auth/generic-oauth/ )  with Azure AD B2C, but it is not working.

**What you expected to happen**:
1. Grafana oAuth SSO should work with Azure AD B2C (because both are following generic oAuth principle & have support).
2. hit Grafana URL in browser --> redirect to Azure AD B2C for Authentication/Login --> After Successful login - Grafana should load with User Details & Post login page

**How to reproduce it (as minimally and precisely as possible)**:

Our Grafana Configmap contains below details:
kubectl get cm grafana -n monitoring -o yaml

[auth.generic_oauth]
enabled: true
client_id: "client-id-from-azure-ad-b2c"
client_secret: "client-secret-from-azure-ad-b2c"
scopes: "openid"
auth_url: "https://azure-ad-b2c-tenant-name.b2clogin.com/azure-ad-b2c-tenant-name.onmicrosoft.com/oauth2/v2.0/authorize?p=azure-ad-b2c-userflow"
token_url: "https://azure-ad-b2c-tenant-name.b2clogin.com/azure-ad-b2c-tenant-name.onmicrosoft.com/oauth2/v2.0/token?p=azure-ad-b2c-userflow"
allow_sign_up: true

**Anything else we need to know?**:
1. We also checked with Microsoft Team & Azure B2C side we are able to run sample userflows (https://jwt.ms/) & verify authentication token also. So our understanding is Azure B2C configuration looks good, but somehow "Grafana oAuth SSO Integration with Azure B2C" not working.

2. We tried the solution provided in this link, but it is not working: https://community.grafana.com/t/sso-using-azure-ad-b2c/23454/2

3. We can see below error in Grafana logs:
lvl=eror msg=login.OAuthLogin(NewTransportWithCode) logger=context userId=0 orgId=0 uname= error="oauth2: server response missing access_token"
lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=500
 

**Environment**:
- Grafana version: 7.1.1

**Comment by marefr** [comment]
@sky29 I can see that you're using quite an old Grafana version, v7.1.1. 
- Have you tried a more recent version? 
- Are you aware of that there's a specific [Azure AD authentication](https://grafana.com/docs/grafana/latest/auth/azuread/) available that you maybe can use/works better for your use case?

**Comment by sky29** [comment]
@marefr  

- I have not tested the Grafana latest version (OSS) yet, but my understanding is "generic oAuth SSO" should be agnostic to grafana version & whatever current version we are running it is working with keycloak & azure ad.

- Yes we saw Azure AD authentication documentation, but we want to use "Azure AD B2C" not "Azure AD", it's different product. We already have Azure AD authentication in place with current Grafana version.

**Comment by marefr** [comment]
> I have not tested the Grafana latest version (OSS) yet, but my understanding is "generic oAuth SSO" should be agnostic to grafana version & whatever current version we are running it is working with keycloak & azure ad.

@sky29 yes, but we might have fixed issues with generic oauth since v7.1.1 and upgraded the oauth2 library which seems to be the one returning the error, based on this: https://community.grafana.com/t/how-to-avoid-the-error-oauth2-server-response-missing-access-token/44849/2?u=mefraimsson

I would definitely suggest spinning up a test instance of a more recent Grafana version and try setup Azure AD B2C. 

In general, since the library response with access token missing seems to me you're lacking either some scope or are using a bad client id or secret. Have you enabled/disabled [implicit grant](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-register-applications?tabs=app-reg-ga#enable-id-token-implicit-grant)?

I suggest you to reply in https://community.grafana.com/t/sso-using-azure-ad-b2c/23454/3 and ask for help there since they've clearly got this to work. GitHub is mainly for bugs and feature discussions, not questions. However, if you can provide more proof this is actually a Grafana problem we'll consider reopen this.
