### ISSUE TITLE
ngalerts: contact points and policies get erased

### ISSUE THREAD

**Issue by 12nick12** [grafana/grafana#41715]
**What happened**:
Every few days the contact points and policies get erased

**What you expected to happen**:
I expect the points and policies to stay there

**How to reproduce it (as minimally and precisely as possible)**:
I add contact points and policies and a few days later they're no longer there

**Anything else we need to know?**:
I have enabled debug anything I should look for in the logs? 

**Environment**:
- Grafana version: Grafana v8.2.3 (fb85ed6912)
- Data source type & version: Alert based
- OS Grafana is installed on: RHEL8
- User OS & Browser: Tested on Safari and Chrome
- Grafana plugins: ngalert
- Others:

**Comment by JohnnyQQQQ** [comment]
@12nick12 what [backend](https://grafana.com/docs/grafana/latest/administration/configuration/#database) do you use for Grafana (e.g. MySQL, SQLite..)?

**Comment by LefflerMediaLLC** [comment]
SQLite backend.

**Comment by 12nick12** [comment]
SQLite backend

**Comment by JohnnyQQQQ** [comment]
Okay, so the problem might be that you are not using persistent storage for the Grafana data. Make sure, that the path where the Grafana SQLite file is stored is persistent and not ephemeral. Otherwise, you will lose all your data, as SQLite is just a file on disk. Another option would be to use an external MySQL or Postgres server.

If you think this is an issue with Grafana and not with the infrastructure Grafana is running on, please give us an example how we can reproduce it step by step.
