### ISSUE TITLE
Display issue when creating new panel based on existing one

### ISSUE THREAD

**Issue by autoamator** [grafana/grafana#41753]
Query tab content becomes unreadable for a panel based on other existing panel.

Reproduction:
1. Create panel1 with a some datasource and configure a query. 
2. Create panel2 with datasource = "--Dashboard--" and select panel1 as a source

Expected:
Configuration of panel2 should be readable

Actual:
It is not:
![image](https://user-images.githubusercontent.com/9354531/142013007-c69a83e8-0cad-4937-932f-df54f1f2cb24.png)

For panel1 having a mixed source it gets even worse:
![image](https://user-images.githubusercontent.com/9354531/142013200-de796dc3-5423-4a5f-9252-1cb439e999c4.png)

Grafana version I'm using is v7.2.0 (efe4941ee3)
Confirmed in Chrome, FF, Edge.

**Comment by ashharrison90** [comment]
think this has been fixed in 8.x:
![image](https://user-images.githubusercontent.com/20999846/142026567-18a98de5-b1ca-470b-864a-92cb1f5b03ed.png)

**but** i did find another bug (i think?). in the `Use results from panel dropdown`, it shows the current panel as one of the options:
![image](https://user-images.githubusercontent.com/20999846/142026744-bb6b082a-63cb-4688-9edb-68037e063cac.png)

if you select the current panel, the browser locks up and goes into an infinite loop until it exceeds the call stack limit: 
![image](https://user-images.githubusercontent.com/20999846/142026915-a04b2c90-14f8-4b2f-a852-7580ba02e9c9.png)

**Comment by hugohaggmark** [comment]
@ashharrison90 great findings and I agree with you!

**Comment by hugohaggmark** [comment]
Opened a new issue for the infinite loop #41806. Closing this issue as I can't repro it on Grafana Grafana v8.3.0-pre (2319c52c85) and we're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!

**Comment by autoamator** [comment]
@ashharrison90, thanks for the hint!
