### ISSUE TITLE
the v8.2.4 grafana container cannot be built

### ISSUE THREAD

**Issue by pbolle** [grafana/grafana#41750]
**What happened**:
i wanted to build the current v8.2.4 grafana container

git clone git@github.com:grafana/grafana.git
git checkout v8.2.4
docker build   -f Dockerfile .

**Build Error**:

```
go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading github.com/klauspost/cpuid/v2 v2.0.5
/go/pkg/mod/github.com/hashicorp/memberlist@v0.2.4/awareness.go:7:2: missing go.sum entry for module providing package github.com/armon/go-metrics (imported by github.com/hashicorp/memberlist); to add:
        go get github.com/hashicorp/memberlist@v0.2.4
/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.2/mux_broker.go:12:2: missing go.sum entry for module providing package github.com/hashicorp/yamux (imported by github.com/hashicorp/go-plugin); to add:
        go get github.com/hashicorp/go-plugin@v1.4.2
exit status 1
exit status 1
The command '/bin/sh -c go run build.go build' returned a non-zero code: 1
```

**Environment**:
Linux (Ubuntu)

**Comment by mckn** [comment]
I have verified and I get the same error. Thanks for reporting this 🙏🏻

**Comment by timlevett** [comment]
https://hub.docker.com/layers/grafana/grafana/8.2.4/images/sha256-e06c8a26831c31f8b78397aade70f1fac1fcc3b3ad9a374f2335cc2c46fd5e5d?context=explore is the image you want, just pull that down.

The image in root is not the right image for this version, you have to use the one in packaging but its not straight forward. We've made improvements to this on the latest (main branch). Closing this since you can just pull the image from docker hub and expand from there.
