### ISSUE TITLE
grafana/ui: Add default type="button" to <Button>

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#41863]
Currently our Button component in grafana/ui does not specify a type attribute. By the specification this defaults to `submit` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type. This creates quite a number of bugs, because anytime somebody adds a button in data source config page, which is wrapped in `<form>` (and probably other contexts) that button will act as submit button for the form, see for example [this pr](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type).

As the submit case seems to be minority usecase and this generates lots of bugs, I think it would make sense to default to `type="button"` instead when not set. This would be a breaking change but I think it should not affect that much and relying on the default behavior should be easily checked at least in our code base (basically only where we use `<form>`)

**Comment by natellium** [comment]
@jackw I think you had some concerns about this, right?

**Comment by ashharrison90** [comment]
it would be a breaking change. so one to save for Grafana 9? 🤔

**Comment by aocenas** [comment]
@jackw yeah this would definitely be a breaking change but I would expect that the migration would be that just a handful of buttons would have to be changed to `type=submit` while in the current state we should go through much bigger umber of buttons and add `type=button` to make sure they don't create subtle bugs all over the place. I mean if my assumptions are right regarding the number of buttons which needs to be `type=submit`

**Comment by aocenas** [comment]
@tolzhabayev yes but we should be able to do breaking changes somehow. Especially with something small as this, it should not be that painful to move forward. Right now the "breaking change" issue seems to be the only thing stopping this even when there seems to be a general consensus that this is a good change.

Btw if we know about those it would be pretty cool if we just automated and created an issue in those repositories saying "you use grafana/button we are doing this change in the next release, make sure your plugin still works".

**Comment by tolzhabayev** [comment]
@aocenas I am neither for nor against change, that's up to owners of this component or the developers that share ownership to decide.

I only want to make sure that the teams that introduce a breaking change have to followup with the consequences. I think your idea of automating and creating an Issue is great! We also want to share plugin reviews process burden with more squads and would love to have more teams support us in pushing the updates through so that the plugins work with next release.

List of plugins: https://ops.grafana.net/d/dmb2o0xnz/imported-property-details?orgId=1&var-propertyName=Button&var-packageName=@grafana/ui
Github repositories for them can be found here: https://grafana.com/api/plugins
