### ISSUE TITLE
Plugins Catalog: improve accessibility of the Install Controls

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#41947]
**Related discussion:** https://github.com/grafana/grafana/pull/41749#discussion_r752309907

Add `alt=""` attributes to the `<Icon />` components to get them skipped by screen readers.

**Comment by oshirohugo** [comment]
I check this and our `Icon` element is a `div` with a `svg`, none of them support `alt` attribute. And according to this [reference](https://accessibilityinsights.io/info-examples/web/svg-img-alt/) if we want something like alt in a svg we need to add an `aria-labelledby` , therefore, as it is, the `svg` will already be skipped by screen readers. I've tested with chrome screen reader and it indeed skips the the icon description.

@leventebalogh can we close this since we are already since we are already skipping this icons descriptions?

**Comment by sympatheticmoose** [comment]
What do you think @kaydelaney ? This was your original suggestion from the [previous PR](https://github.com/grafana/grafana/pull/41749#discussion_r752309907)

**Comment by leventebalogh** [comment]
Sorry for the late answer on this. Yes, let's close it.
