### ISSUE TITLE
grafana can support influxdb continuous queries  some way

### ISSUE THREAD

**Issue by huhongbo** [grafana/grafana#420]
now the grafana  set group by automatically depending on how long the current time span ,but  query on the raw serial cost  a lot of cpu using the group by and slowly 
the influxdb using continuous queries to support down sampled data, so maybe using  some way to set influxdb queries to continuous queries depending the current time span

**Comment by xo4n** [comment]
+1

**Comment by mre** [comment]
+1 awesome idea

**Comment by Ynguibjoerg** [comment]
+1

**Comment by baze-** [comment]
+1
Simple templating in series name would work in most cases.

Could Grafana just pass the closest timepickers predefined value as parameter into series name?

If series would be "**temperature.&timescale**" Grafana could just replace the **&timescale** with one of the predefined values from timepicker: 5m,15m,1h,6h,12h,24h,2d,7d,30d

If visible time range is 16 hours then Grafa would use series "temperature.24h" because it is the closest one in this case.

This way creating continuous queries and all the downsampling would be handled in db and wouldn't become Grafanas problem.

**Comment by zyegfryed** [comment]
I'm definitely +1 with @baze-

**Comment by nicolargo** [comment]
+1 This feature will be awesome !

**Comment by malthe** [comment]
+1

**Comment by asgerlp** [comment]
+1

**Comment by PaulKuiper** [comment]
+1, much needed for high resolution signals to prevent slow processing

**Comment by hugoeld** [comment]
+1 for @baze- idea with $timescale

**Comment by krancour** [comment]
+1

**Comment by torkelo** [comment]
you should +1 in the influxdb repo instead :) 

So the current plan is:
1) support influxdb 0.9  (InfluxDB 0.9 is complete rewrite, different api and query language)
2) I do not know what InfluxDBs plan for CQ/Rollups are for InfluxDB 0.9, would love for them to have some standard way so that InfluxDB itself can pick the correct rollup depending on time range (like graphite does)

**Comment by nicksellen** [comment]
A [fully qualified measurement](http://influxdb.com/docs/v0.9/query_language/querying_data.html#selecting-the-database-and-retention-period) includes the retention period, which would effectively be the rollup period for a standard use case, perhaps something along these lines is the answer.

Although `SHOW MEASUREMENTS` doesn't seem to currently return the retention period (maybe it's just because I have it set as default).

**Comment by torkelo** [comment]
@nicksellen (or @pauldix might answer) is there a way in InfluxDB 0.9 to create a generic rollup query? Say I want all my `*.count` measurements (raw data every 10s) rolled up in 1min and  10min groups.   (then the same for non count bug aggregate using avg). How many queries would this be? 

Lets say I have 1000 different measurements, like "payment.count", "login.count" , etc I want them rolled up to "1m."."payment.count"  and "1m.login.count",  (fully qualified). Do I need 1000 continous queries or one? 

Looking at the docs for continous queries, I do not see how you are supposed to use them to create  generic rollup queries as the examples given all specify a fixed measurement name for the rollup series.

**Comment by nicksellen** [comment]
Doesn't look like it as far as I can see from [the docs](http://influxdb.com/docs/v0.9/concepts/continuous_queries.html).

It would be handy to have a seperate rollup config, perhaps baked into the retention configuration (like in graphite iirc) - something like: 1d (10s, sum), 1w (1m, sum), 1m (1h, sum), 1y (1d, sum) kind of thing (with custom aggregation function), querying would then be via fully qualified measurement.

Although it would need the rollup value added, so: `<database>.<retention period>.<rollup>.<measurement>` e.g. `mydb.default.1w.<measurement>`

**Comment by torkelo** [comment]
@nicksellen well I just do not understand how you can use InfluxDB without generic rollup rules, I think this was possible in InfluxDB 0.8 because you could refer the series name `:series_name` in the "INSER" part of the continous query. 

Anyway, there was a way to create generic rules. It should be easy to utilize those rules in grafana so that grafana can automatically pick the right rollup depending on time range (and auto group by time)

**Comment by nicksellen** [comment]
Yeah 0.8 seems to have [this feature](http://influxdb.com/docs/v0.8/api/continuous_queries.html#continuous-downsampling-of-many-series) allowing wildcard series matching:

````
select mean(value), percentile(90, value) as percentile_90, percentile(99, value) as percentile_99 
from /^stats.*/ group by time(10m) into 10m.:series_name
````

I haven't tried this on my 0.9 though. Not my priority right now. I imagine this will get an official solution after the actual 0.9 release though. Rollups are mentioned on [the homepage](http://influxdb.com/) so I don't think they have been forgotten.

**Comment by djace** [comment]
Is this going to be picked up eventually? Where can we +1 the influxdb team on this?

I've seen there's updated documentation about them in 
https://github.com/influxdb/influxdb/blob/72f52d44c9f615b728b76d9cd06a3956963e3695/services/continuous_querier/continuous_queries.md

Is there a workaround for CQs for us that are on 0.9.1 at the moment?

**Comment by nicksellen** [comment]
For now I've written a tool that will create all the rollup continuous queries I need using the API from a config file, for example:

```
default 8d
short 36d 5m
medium 90d 1h
long 380d 3h
archive 3800d 1d
```
in the format `<name> <retention> <resolution>`. My measurement names have a convention that the type is specified so it knows which aggregate function to use (`mean` or `sum` at the moment).

From this it'll create a retention period and a continuous query, which will then create the measurement when it runs. I find the continuous queries a little flakey right now though.

**Comment by djace** [comment]
Interesting tool! Is it published somewhere?

**Comment by torkelo** [comment]
@djace I do not think InfluxDB 0.9 supports "generic" continuous queries yet (for example a way to create a single continous query that roll ups all data into 5min intervals) .

**Comment by mobarre** [comment]
@torkelo: I've been researching this and I read somewhere that an equivalent to the former :series_name syntax is planned. although I failed to find a github issue opened for this so no way to +1 anywhere. Shall I create one ?

**Comment by torkelo** [comment]
@mobarre not sure you should ask me for permission on opening an InfluxDB issue

I find it strange that there is no issue for this yet, I do not understand how influxdb can be even close to production ready and usable without a solid and easy to use mechanism to roll up data.

**Comment by nicksellen** [comment]
... actually even the manual rollup via continuous queries aren't stable yet - https://github.com/influxdb/influxdb/issues/3362

I had to remove them for now. One user is running manual continuous queries now - https://github.com/influxdb/influxdb/issues/3362#issuecomment-124098463

I still have faith that this stuff will be resolved, but it does seem it's not as stable as the website is shiny :)

**Comment by hyvs** [comment]
InfluxDB 0.9.4 now supports backreference in continuous queries, see [influxdb/influxdb#2555](https://github.com/influxdb/influxdb/issues/2555)

+1 for @baze [comment](https://github.com/grafana/grafana/issues/420#issuecomment-72178893)

**Comment by RKelln** [comment]
:+1: 
Being able to specify the retention policy as a variable would be a halfstep towards automated choosing. Then when looking at older data you could manually switch the retention period on the dashboard.  

So you could do a continue query to the same series but different retention policy:

From: https://influxdb.com/blog/2015/10/21/continuous_queries_part_1.html
> In the next example below, a regular expression can be used in the FROM clause of a continuous > query to collect points selected from all measurements and write them into the 1h_policy retention policy with the same measurement names.
>
> CREATE CONTINUOUS QUERY myquery ON mydb 
>	BEGIN 
>   		SELECT mean(value) INTO "1h_policy".:MEASUREMENT 
> FROM /.*/ 
>    GROUP BY time(1h) 
> END

And then the influx query itself is: select * from mydb.$myretentionpolicy.mymeasurement

**Comment by rubycut** [comment]
:thumbsup:

**Comment by rubycut** [comment]
influxdata/influxdb#5750

**Comment by ruudboon** [comment]
:thumbsup:

**Comment by nextkitt** [comment]
👍

**Comment by mahendrent** [comment]
@adubovikov any idea when this will be integrated into the main branch? It's been a year already.

**Comment by adubovikov** [comment]
sorry, but i think you can use CONTINUOUS QUERY in the InfluxDB to make select in the correct "datasampling tables"

**Comment by torkelo** [comment]
We are trying use open GitHub issues as a way to track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long without anyone showing interest in implementing it. 
A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
