### ISSUE TITLE
Can't set custom all value

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4219]
I tried to use the new "Custom All value". Setting any value doesn't update the preview, doesn't change the All value in the drop down list and doesn't seem to get saved either.

@torkelo 

`Version 3.0.0-pre1 (commit: v2.6.0-1221-g82e7f1a)`

**Comment by torkelo** [comment]
thanks for reporting this, fixed!

**Comment by grobie** [comment]
@torkelo While I can confirm the custom value gets persisted now, neither the preview in the templating editor nor the actual value in the dropdown list use the custom value.

![screenshot from 2016-03-04 16-18-42](https://cloud.githubusercontent.com/assets/3432/13540516/0b843948-e225-11e5-984c-1ef9084afcd0.png)

**Comment by torkelo** [comment]
@grobie the custom all value is now show in the dropdown, "All" is the text representation, the custom value is used in the interpolation of the query, so when you select All, what is sent to your data source?

**Comment by torkelo** [comment]
^ correction "All value is *NOT* shown in dropdown"

**Comment by grobie** [comment]
Oooh. I entirely misunderstood this feature. I can confirm that the chosen value is used as template variable. I think the `all` in `Custom all value` made me believe this is going to change the `All` caption.

**Comment by catia92** [comment]
Hi. Using this "Custom all value" feature, is it possible to define a custom expression for the following purpose?
--
Selecting, for a certain application (using a variable $application), the first matching item (e.g. a random one) from each of the existing clusters (i.e. from the clusters that are respective to that application).


For example:
Having a variable $application, with the values: 
- App-a
- App-b
And having a variable $cluster, with the values: 
- a01, a02, a03 (which correspond to 3 clusters for the application "App-a");
- b01, b02, b03 and b04 (which correspond to 4 clusters for the application "App-b");

What I wish to do:
When opening the "cluster" filter:
- display all the existing clusters: a01, a02, a03, b01, b02, b03, b04.
- show "All" option
Then, when selecting the "All" option, I simply want to select 1 of the possible cluster values, per each application that was selected using the $application variable/filter.

Example: 
- when selecting $application = "App-a", I want to automatically select only 1 of the values: a01, a02, or a03, instead of selecting them all. And I want this to be considered the "All".
- when selection "App-a" and "App-b" in the application filter, the cluster filter (with the option "All" selected) should only display 2 items selected (i.e. one per application selected/checked).
The single cluster value selected (1 per application) could be a random value (e.g. the first one found, that matches that specific application name).

Is this feasible?
Thank you in advance.
