### ISSUE TITLE
Invalid regex escape in Prometheus queries

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4234]
This is a follow-up to #2918. Using a Prometheus datasource it's not longer possible to use a template variable with a All/multi-value. There was a work-around until 2cf1193 to use the pipe encoding instead of the regex encoding, but this is no longer an option with the rewrite.

The reason is that grafana uses a single backslash to encode meta characters in regular expressions. Prometheus expects a double backslash for proper encoding. A single backslash is interpreted as [escape character](https://en.wikipedia.org/wiki/Escape_character#Examples) starting an escape sequence. This behavior is very unlikely to ever change in Prometheus.

As the correct escape behavior differs between datasources, my suggestion would be to move the encode functionality to the datasource providers.

Here is an [example dashboard definition](https://gist.github.com/grobie/082d085dde46666612f1) you can import to reproduce the issue. The datasource is http://demo.robustperception.io:9090/.

```
# Request
/api/datasources/proxy/2/api/v1/query_range?query=process_cpu_seconds_total{instance=~"demo\.robustperception\.io:9090"}&start=1456954914&end=1456976514&step=21

# Response
{
  "status": "error",
  "errorType": "bad_data",
  "error": "parse error at char 37: unknown escape sequence U+002E '.'",
  "message": "parse error at char 37: unknown escape sequence U+002E '.'"
}
```

**Comment by grobie** [comment]
Here is [another live example][0] to see the difference in using single vs. double backslashes for encoding.

[0]: http://demo.robustperception.io:9090/graph#%5B%7B%22range_input%22%3A%221h%22%2C%22end_input%22%3A%22%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3A%22%22%2C%22expr%22%3A%22process_cpu_seconds_total%7Binstance%3D~%5C%22demo%5C%5C.robustperception%5C%5C.io%3A9090%5C%22%7D%22%2C%22tab%22%3A1%7D%2C%7B%22range_input%22%3A%221h%22%2C%22end_input%22%3A%22%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3A%22%22%2C%22expr%22%3A%22process_cpu_seconds_total%7Binstance%3D~%5C%22demo%5C%5C%5C%5C.robustperception%5C%5C%5C%5C.io%3A9090%5C%22%7D%22%2C%22tab%22%3A1%7D%5D

**Comment by pdf** [comment]
The tricky part will be that the query will need to be parsed to determine whether we're inside a regexp section, because the double-backslash in a string will result in a literal `\` being interpreted, [expanded example](http://demo.robustperception.io:9090/graph#%5B%7B%22range_input%22%3A%221h%22%2C%22end_input%22%3A%22%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3A%22%22%2C%22expr%22%3A%22process_cpu_seconds_total%7Binstance%3D~%5C%22demo%5C%5C.robustperception%5C%5C.io%3A9090%5C%22%7D%22%2C%22tab%22%3A1%7D%2C%7B%22range_input%22%3A%221h%22%2C%22end_input%22%3A%22%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3A%22%22%2C%22expr%22%3A%22process_cpu_seconds_total%7Binstance%3D~%5C%22demo%5C%5C%5C%5C.robustperception%5C%5C%5C%5C.io%3A9090%5C%22%7D%22%2C%22tab%22%3A1%7D%2C%7B%22range_input%22%3A%221h%22%2C%22end_input%22%3A%22%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3A%22%22%2C%22expr%22%3A%22process_cpu_seconds_total%7Binstance%3D%5C%22demo%5C%5C%5C%5C.robustperception%5C%5C%5C%5C.io%3A9090%5C%22%7D%22%2C%22tab%22%3A1%7D%2C%7B%22range_input%22%3A%221h%22%2C%22end_input%22%3A%22%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3A%22%22%2C%22expr%22%3A%22process_cpu_seconds_total%7Binstance%3D%5C%22demo.robustperception.io%3A9090%5C%22%7D%22%2C%22tab%22%3A1%7D%5D).

**Comment by grobie** [comment]
A simple alternative would be to side-step this problem and to revert the change in 0da4168836a73a8a10bd8cf8b2e40d61b6179498 and to just always escape template variables. Users have then to always use the regex matcher when using template variables, but at least that requirement will be consistent.

Note that Prometheus regurlar expressions are always anchored, so an expression like `instance=~"demo\\.robustperception\\.io:9090"` is actually `instance=~"(?:^demo\\.robustperception\\.io:9090$)"`. Therefore, it's be safe to always use the regex matcher even if only a single value is used. Another example is that users might use the regular expression matcher even without using All/multivalue, for example `nylabel=~".*$variable"`, here again it'd be beneficial to always escape the template variable value.

**Comment by torkelo** [comment]
@grobie strange, it works fine here:

now tested with label value that contains dots, and it works.
![image](https://cloud.githubusercontent.com/assets/10999/13490196/70bf5ba8-e12b-11e5-9204-1aa67b4d6200.png)

"avg(counters_logins{server=~"webserver-02|webserver\.03|webserver_03"}) by(server)"

**Comment by torkelo** [comment]
running prometheus 0.15, will try latest

**Comment by torkelo** [comment]
ok, get the error when running Prometheus 0.16.2 , maybe a bug in Prometheus?

**Comment by torkelo** [comment]
added special regex escape with double backslash, hope it doesn't break queries for users on Prometheus 0.15 .

The same rule applies that only queries that have multi or all enabled are regex escaped
