### ISSUE TITLE
QueryInspector: Support multiple queries 

### ISSUE THREAD

**Issue by jelmd** [grafana/grafana#42344]
**What happened**:
If one has more than a single query, the query inspector is useless because it always shows the query request/result for Query A, even if the cursor is currently in the textfield of another query (lets say B).

**What you expected to happen**:
Query inspector should show the currently focused query  or allow one to actually selected the query, which should be inspected.

**How to reproduce it (as minimally and precisely as possible)**:
Create a panel with 2+ queries and try to inspect query 2.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.2
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux Ubuntu LTS 20.04
- User OS & Browser: Linux Ubuntu LTS 18.04
- Grafana plugins: default
- Browser: firefox 85.0 (ubuntu vendor package)

Actually working with the query inspector is a real pain. There should be a separate Window, where one is able to explore datasources, be able to find out easily, which metrics are available and how they are labeled ...

**Comment by torkelo** [comment]
This is due to Prometheus issuing queries one at at time (no batch API sadly), the inspector is pretty low level can only inspect the requests and responses and it the data sources issues many it will only show one of them. You have to disable the other queries (eye icon) and leave the query you want to inspect.
