### ISSUE TITLE
loki log: The amount of data in the histogram and the table is not the same

### ISSUE THREAD

**Issue by wuzhihui1123** [grafana/grafana#42412]
**What happened**:
loki log: The amount of data in the histogram and the table is not the same

**What you expected to happen**:
the histogram has no data,

**How to reproduce it (as minimally and precisely as possible)**:
Query loki data in a relatively short time range

**Anything else we need to know?**:
when i query loki log: 
![image](https://user-images.githubusercontent.com/4246626/143813019-04017c2e-4b63-46a2-964e-0a31c3b7bc5c.png)

bug when i click tht button of [Reload log volume],  Will get the following result
![image](https://user-images.githubusercontent.com/4246626/143813419-1f5f5e2b-61e6-46c9-b63e-c09b587d2832.png)

**Environment**:
- Grafana version:  8.3.0-beta2

**Comment by ivanahuckova** [comment]
+cc @ifrost

**Comment by ivanahuckova** [comment]
I have copy-pasted @ifrost explanation from  #42702 for easier discoverability of why is this happening: 

This is how bucketing logs for Loki's log volume work:

Example:
* the user queries for logs with the range: 12:25 - 13:50
* log volume figures out the resolution / interval size for the histogram, let's assume for the example it's 1 hour
* a Loki query is made `count_over_time({...}[1h])` and start/end time the same as the selected range
* returned data would contain total logs for:
  * 1 hour before 12:25 with a bucket with a timestamp of 12:25
  * 1 hour before 13:25 (12:25+1h)  and a bucket at 13:25

<img width="1083" alt="Screen Shot 2021-12-03 at 09 36 31" src="https://user-images.githubusercontent.com/745532/144571616-c33d0d61-7c78-4a19-a7fb-30655a855348.png">

This creates two problems:
* bucketing is not natural, imagine a log with the time of ~12:20, it would be included in 12:25 aggregation, *but* imagine a log line around ~12:30, it would be included in 13:25 aggregation in the example above.
* there are logs outside of the selected range are included in the first aggregation

More natural bucketing would be as follows (this is what Elastic supports out of the box):

<img width="1060" alt="Screen Shot 2021-12-03 at 09 37 46" src="https://user-images.githubusercontent.com/745532/144571647-7b627d9b-8713-4f98-928c-6800a422a19e.png">

Note: this also means some log lines are included in the histogram but not in the results, but with more natural bucketing this should be way more clear where these log lines may be coming from.

How to create bucketing that would be more natural in Loki? Ideally, we would like to have negative offset for `count_over_time(...)` to look forward, not backward. Unfortunately, Loki doesn't support negative offsetting with queries but we can achieve a similar effect by:
* adjusting and aligning requested query range to cover desired buckets
* shifts returned buckets back by the bucket size

For example: instead of requesting Loki with a range of 12:25-13:50 we would request 13:00-14:00 (start/end rounded up to nearest bucket size). That would result in a response with two buckets at 13:00 and at 14:00. We would shift them back by an hour getting two bars at 12:00 and 13:00.

**Comment by pkrishnanreflexion** [comment]
@ivanahuckova 
How does this address https://github.com/grafana/grafana/issues/46454?
The issue in 46454 is about log volume showing the count, but log lines not appearing. The issue in this thread seems to be about the converse -- Log volume 0, but log lines are showing up.

**Comment by ivanahuckova** [comment]
It is the same issue - there is a miss-match between number of log lines and log volume because of how bucketing in Loki works. You can see in the images from the issue's description, that it can be miss-matched in both ways.

**Comment by pkrishnanreflexion** [comment]
Thank you for the clarification.

**Comment by gabor** [comment]
as described above, the problem is based on how bucketing works in Loki, and for now we consider the current situation as acceptable. thanks for all the info from the participants 👍
