### ISSUE TITLE
Unable to delete empty folders on Grafana dashboards

### ISSUE THREAD

**Issue by mary-sitzenstatter** [grafana/grafana#42486]
@darrenjaneczek and I found what we think is a bug. 

Scenario: we are trying to delete an empty folder _Dashboards > Manage_. 

1. Select checkbox for empty folder
2. Observe: _Delete_ and _Move_ buttons do not appear. 

Please see attached video for more details. 

https://user-images.githubusercontent.com/86840333/143937050-0f98df6b-7f38-44b2-bd88-9e31c93141cd.mp4

**Comment by dprokop** [comment]
Caused by the memoization [here](https://github.com/grafana/grafana/blob/70e759e0c0a4879aff1e0d6312b27fc30d087289/public/app/features/search/hooks/useManageDashboards.ts#L49) that invalidates the function only on results/canMove changed.

Same issue happens if you try to select and delete a non-empty dashboard that wasn't expanded in the list.
