### ISSUE TITLE
Min Step does not allow variable in v8.3.0

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#42605]
**What happened**:

Upgraded from 8.2.5 to 8.3.0 and it broke all my prometheus dashboards because I use a variable in the `Min Step`

```
error="failed to query data: time: invalid duration \"$step\""
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.0
- Data source type & version: Prometheus
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
Thank you for reporting the issue. This is a regression and fix will be part of the next patch release.

**Comment by ghobson2013** [comment]
Good Morning, 
I was trying to upgrade to the recommended emergency update to fix CVE-2021-43798 but then found that most of my dashboards were broken due to this bug , variable names don't seem to resolve anymore for min step, when can we expect a fix for this ? I can't roll back to a release that is vulnerable to the CVE.  
Thanks.

**Comment by corporate-gadfly** [comment]
This issue didn't make it in the 8.3.2 release? Sigh.

**Comment by kfox1111** [comment]
I'm seeing it too. there a 8.3.3 expected soon with the fix?

**Comment by corporate-gadfly** [comment]
Fixed for me, TY.
