### ISSUE TITLE
Alerting: Expose _actual_ state changes via state history

### ISSUE THREAD

**Issue by gotjosh** [grafana/grafana#42606]
Alerting within Grafana has a set conditionals that are able to manipulate the state of an alert based on certain parameters. 

<img width="435" alt="Screenshot 2021-12-01 at 17 21 47" src="https://user-images.githubusercontent.com/231583/144282585-28c502a7-c4eb-4959-bdbd-2a05f206780c.png">

As an example, an alert that goes from. Alerting -> No Data -> Alerting and has a setting of `alert state if no data or all values are null = Alerting` would actually show an alert that never stopped firing despite getting no data in one of their evaluations.

While is the expected behaviour per these settings, it is cumbersome for users to know that this what actually happen by looking at the state history that is created via annotations. 

An idea is to store these "internal" changes as annotations so that they can be displayed as part of the "state transitions" history.

**Comment by gotjosh** [comment]
Spoke with @gillesdemey about this and I'm thinking that once we merge #42479 this can be a follow-up. As a general approach I think we should consider:

- Using the annotation text and embedding JSON directly as opposed to creating a new field in the database that might (or not) involve backfills. 
- Then manipulated this JSON in the front-end to showcase the state that the alert is currently in and then the state that was masqueraded for it via the option.

**Comment by armandgrillet** [comment]
@joeblubaugh Is this related to what you're working on right now?

**Comment by joeblubaugh** [comment]
@gotjosh You're referring to the Grafana Alertmanager in the ngalert package, right? Not any signals from an external alertmanager / alert ruler.

**Comment by armandgrillet** [comment]
Before we do a fully improved alert state history for Grafana 9, this is a quick win we can have for 9.0.

**Comment by joeblubaugh** [comment]
I've walked through the code a bit now, and fortunately we have access to both the evaluation state and the translated state in the state manager right where the state annotations are written down.

The frontend uses special columns on the annotation in order to set the colors and text used in the state history table. It then also displays the text of the annotation in an unprocessed form.

A few ideas about how we might add the actual evaluated state to the chart annotation in addition to the derived state (and the corresponding frontend changes):
1. Create new states for Grafana Alerts in the frontend and in the annotations SQL table. These states will not otherwise be used in the backend. States are Alerting (NoData), Alerting (Error), OK (NoData), OK (Error). Add these states to the frontend code that generates the alert column colors. This is pretty simple in both the frontend and the backend, as long as those states aren't used in too many places where interpretations need to be changed.

2. Add a new value to the chart annotation - the "evaluated state". Use both of these fields when constructing columns. Add this evaluated state to the chart annotation text and process it in the frontend to change how the column text and color are generated in the state history table. We need to be able to parse this out of the annotation text, since we won't add any more columns to the annotation table, with good reason.

Overall I'd like to be doing more structured evaluation of the state history annotation text - it's "somewhat structured" and generally has a lot of duplicate information like the alert rule name that I'd like to filter out, and highlight what's different, like different label values for different rule instances. As we add optional rich alert state history, I'd also like to continue writing down annotation-based history for a while in parallel. So it'd be interesting to make it a fully JSON-serialized piece of data, if we can do it safely. _However_, the annotation text is also displayed on any linked charts, so making the annotation text complex is an issue there.

I'm going to pursue Option 1, and keep this idea of interpreting annotation text in the state history table in my back pocket for other UI improvements.
