### ISSUE TITLE
Upgrade from 8.2.6 to 8.3.0 corrupted alert queries

### ISSUE THREAD

**Issue by pkoenig10** [grafana/grafana#42699]
**What happened**:
I upgraded Grafana from 8.2.6 to 8.3.0. After upgrading, the queries for all my alerts were gone. Oddly enough, the expressions for those alerts were still there. The alert had fired and were in a permanent `Firing` state. There was an indicator that there was an error with the alert. There were no failed network requests.

I first tried simply downgrading to 8.2.6. But that did not resolve the issue. Only after restoring my Grafana DB from a backup was I able to recover my alerts.

I was able to reproduce the issue by upgrading to 8.3.0 again.

Before:

<img width="1524" src="https://user-images.githubusercontent.com/5273164/144557334-055cf820-d1b2-4eef-b33a-5952e364218d.png">

After:

<img width="947" src="https://user-images.githubusercontent.com/5273164/144557349-d5212c7c-76b1-4fb0-a044-b35c56356563.png">

<img width="1522" src="https://user-images.githubusercontent.com/5273164/144557383-307f86ae-c532-4ff4-b09e-8a129de9d923.png">

**What you expected to happen**:

Upgrading from 8.2.6 to 8.3.0 does not corrupt alerts.

**How to reproduce it (as minimally and precisely as possible)**:

This list of step is probably incomplete, but I'm not sure what else in my environment may have caused this.
1. Install Grafana 8.2.6
2. Create an alert
3. Upgrade to Grafana 8.3.0

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.0
- Data source type & version: InfluxDB 1.8.10
- OS Grafana is installed on: Official docker image, host is Ubuntu Server 20.04.3 LTS
- User OS & Browser: MacOS 10.15.7, Chrome 
- Grafana plugins: None

**Comment by armandgrillet** [comment]
Thanks for the detailed bug description, @yuri-tceretian will take a look.

**Comment by yuri-tceretian** [comment]
@pkoenig10 thanks for reporting! I think you use provisioning of data sources, don't you? Everything below is based on this assumption. 

I was able to reproduce the problem and it affects not only influx data sources but all provisioned data sources that do not have field UID specified. It is perfectly reproducible in the devenv.
Grafana alerting refers to a data source by its UID, when it changes the evaluator gets confused and reports an error. UI does not show the query because it can't figure out the type of the data source. The alert rule is not changed, though.

The breaking change was introduced in https://github.com/grafana/grafana/pull/41769. After that change, Grafana generates UID for provisioned data source if it is empty, and therefore changes it when it updates the database. Previously, it worked because ORM layer omitted empty fields while generating an update query. 

The fix is simple. While we fixing it the workaround is to update files of provisioned data sources with UID taken from the database.

**Comment by pkoenig10** [comment]
Thanks for the quick response! Yes I am using a provisioned data source and don't specify a UID.

**Comment by yuri-tceretian** [comment]
The bug will is addressed in Grafana 8.3.4
