### ISSUE TITLE
"NoData" alert not working in unified alerting

### ISSUE THREAD

**Issue by sebbleroni** [grafana/grafana#42774]
**What happened**:
I updated to unified alerting and no I am no longer able to receive "NoData" alert via my (working) notification channel (Telegram).

**What you expected to happen**:
Grafana should send notifications when no data is available to evaluate the alert condition.

**How to reproduce it (as minimally and precisely as possible)**:
1) Change to "unified alerting"
2) Set up Telegram as a new notification channel
3) Set up an alert on some query, make sure query and alert are working (e.g. track temperature and detect when temperature rises about threshold)
![Screenshot 2021-12-06 at 11-54-52 Grafana](https://user-images.githubusercontent.com/70020179/144834245-fc9a2316-9620-4383-8e9e-77f5fad7f1ae.png)
![Screenshot 2021-12-06 at 11-55-20 Grafana](https://user-images.githubusercontent.com/70020179/144834249-37d4ff8c-fac0-4502-bf24-6e5cf0c6abbc.png)
4) Set up notification policy
![Screenshot 2021-12-06 at 11-57-37 Alerting Notification policies - Grafana](https://user-images.githubusercontent.com/70020179/144834646-507ffbf8-8e7b-4d33-9848-acc7278cb79e.png)
5) Cut of data supply and observe what happens

**Anything else we need to know?**:
1) Notifications for "NoData" worked flawless in legacy alerting. 
2) The source of the problem seems to be the content of the message itself:

When sending "proper alerts", the log entry in grafana.log looks like:
```
t=2021-12-06T12:32:27+0000 lvl=info msg="sending telegram notification" logger=alerting.notifier.telegram chat_id=991107053
t=2021-12-06T12:32:27+0000` lvl=info msg="level=debug component=dispatcher receiver=\"Test Telegram Alert\" integration=telegram[0] msg=\"Notify success\" attempts=1" logger=alertmanager org=1
```
However, in case of a "NoData" alert produces an error
```
t=2021-12-06T12:36:31+0000 lvl=info msg="sending telegram notification" logger=alerting.notifier.telegram chat_id=991107053
t=2021-12-06T12:36:31+0000 lvl=eror msg="Failed to send webhook" logger=alerting.notifier.telegram error="Webhook response status 400 Bad Request" webhook="Test Telegram Alert"
t=2021-12-06T12:36:31+0000 lvl=info msg="level=error component=dispatcher msg=\"Notify for alerts failed\" num_alerts=1 err=\"Test Telegram Alert/telegram[0]: notify retry canceled due to unrecoverable error after 1 attempts: **Webhook response status 400 Bad Request\**"" logger=alertmanager org=1
```
The "Webhook response status 400 Bad Request" error points to an empty message string, and in fact adding a custom telegram message via "Optional Telegram settings" lets you send messages (however, I don't see how to include the alert information via this route).

**Environment**:
- Grafana version: 8.3.0
- Data source type & version: InfluxDB 1.8
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Ubuntu 20.04, Firefox

- Grafana plugins: None
- Others:

**Comment by ikkemaniac** [comment]
2nd this, I'm on v8.3.2

**Comment by ikkemaniac** [comment]
Did some digging, i think it's because '< no value >' is in the text that's sent but it should be replaced with the proper HTML entities.

Data sent to api:
```
...
Value: <no value>
...
```

Server response:
```
{
    "description": "Bad Request: can't parse entities: Unsupported start tag \"no\" at byte offset 523",
    "error_code": 400,
    "ok": false
}
```

documentation:
https://core.telegram.org/bots/api#sendmessage
https://core.telegram.org/bots/api#html-style
```
- All <, > and & symbols that are not a part of a tag or an HTML entity must be replaced with the corresponding HTML entities (< with &lt;, > with &gt; and & with &amp;).
- All numerical HTML entities are supported.
- The API currently supports only the following named HTML entities: &lt;, &gt;, &amp; and &quot;.
```

Need to dig around where in the code this is coming from.

**Comment by ikkemaniac** [comment]
Confirmed the '< no value >' (note that i need to add a space between the <,> and text because the gh markdown box is actually interpreting it as tag) text is the culprit by setting up a proxy and modifying the data and re-sending the POST command.

Quick fix is to use a 'custom' template which DOES NOT include the "< no value >" part. You can put this directly into the 'Message' box under 'Optional Settings' of the telegrm contact point. The template below is a straight up copy of the [default grafana template](https://github.com/grafana/grafana/blob/e1a5fa063a18e18e1b5db133f3425491a7e4feea/pkg/services/ngalert/notifier/channels/default_template.go#L13) with the "<" swapped for a "[" and removed one ```{{ end }}```

https://github.com/grafana/grafana/blob/e1a5fa063a18e18e1b5db133f3425491a7e4feea/pkg/services/ngalert/notifier/channels/default_template.go#L33

working template:
```
{{ define "__text_alert_list" }}
	{{ range . }}
		Value: {{ or .ValueString "[no value]" }}
		Labels:
		{{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}{{ end }}
		Annotations:
		{{ range .Annotations.SortedPairs }} - {{ .Name }} = {{ .Value }}{{ end }}
		{{ if gt (len .GeneratorURL) 0 }}Source: {{ .GeneratorURL }}{{ end }}
		{{ if gt (len .SilenceURL) 0 }}Silence: {{ .SilenceURL }}{{ end }}
		{{ if gt (len .DashboardURL) 0 }}Dashboard: {{ .DashboardURL }}{{ end }}
		{{ if gt (len .PanelURL) 0 }}Panel: {{ .PanelURL }}{{ end }}
	{{ end }}
{{ end }}


{{ template "__subject" . }}

{{ if gt (len .Alerts.Firing) 0 }}
  **Firing**
  {{ template "__text_alert_list" .Alerts.Firing }}
  {{ if gt (len .Alerts.Resolved) 0 }}{{ end }}
{{ end }}

{{ if gt (len .Alerts.Resolved) 0 }}**Resolved**
  {{ template "__text_alert_list" .Alerts.Resolved }}
{{ end }}


{{ define "__teams_text_alert_list" }}
  {{ range . }}
        Value: {{ or .ValueString "[no value]" }}
	Labels:
	{{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}{{ end }}
	Annotations:
	{{ range .Annotations.SortedPairs }} - {{ .Name }} = {{ .Value }}{{ end }}
	{{ if gt (len .GeneratorURL) 0 }}Source: {{ .GeneratorURL }}{{ end }}
	{{ if gt (len .SilenceURL) 0 }}Silence: {{ .SilenceURL }}{{ end }}
	{{ if gt (len .DashboardURL) 0 }}Dashboard: {{ .DashboardURL }}{{ end }}
	{{ if gt (len .PanelURL) 0 }}Panel: {{ .PanelURL }}{{ end }}
  {{ end }}
{{ end }}


{{ define "teams.default.message" }}
  {{ if gt (len .Alerts.Firing) 0 }}**Firing**
    {{ template "__teams_text_alert_list" .Alerts.Firing }}
    {{ if gt (len .Alerts.Resolved) 0 }}{{ end }}
  {{ end }}
  {{ if gt (len .Alerts.Resolved) 0 }}**Resolved**
    {{ template "__teams_text_alert_list" .Alerts.Resolved }}
  {{ end }}
{{ end }}

```

The change was introduced here:
#41951
https://github.com/grafana/grafana/blob/8c591d65567fe36b5582bb97be69b57b47409d0b/pkg/services/ngalert/notifier/channels/default_template.go#L16
and
https://github.com/grafana/grafana/blob/8c591d65567fe36b5582bb97be69b57b47409d0b/pkg/services/ngalert/notifier/channels/default_template.go#L37

I think this test should fail:
https://github.com/grafana/grafana/blob/8c591d65567fe36b5582bb97be69b57b47409d0b/pkg/services/ngalert/notifier/channels/telegram_test.go#L51
