### ISSUE TITLE
Notification on updated Grafana alerting sounds confusing

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#42818]
Feedback from a user feedback session.

**What happened**:

After a successful test using Grafana, this shows: 
<img width="469" alt="PS 2021-12-07 à 10 42 19" src="https://user-images.githubusercontent.com/2117580/145005318-72078951-d433-494d-9183-81599ef597ea.png">

when using "View Alerts" (grayed out for some reason), it shows this:
<img width="485" alt="PS 2021-12-07 à 10 42 25" src="https://user-images.githubusercontent.com/2117580/145005377-ab1fc486-1118-4701-9849-8796e86b051f.png">

This is confusing. Do you support this feature or not?

**What you expected to happen**:

The messaging regarding which alerting system is running should be clearer.

**How to reproduce it (as minimally and precisely as possible)**: New Grafana instance with one datasource set up.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.5
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by gillesdemey** [comment]
Needs investigation of this issue still occurs in 8.3

**Comment by gillesdemey** [comment]
There are a few places in the `cloud-onboarding` tool where we redirect to the Cloud Alerting plugin

https://github.com/grafana/cloud-onboarding/blob/30e6b7b8f8d83eace542bd4bde9e71f5853b2d5d/plugin/src/pages/Wizard/steps/Dashboards/Dashboards.tsx#L199-L201

https://github.com/grafana/cloud-onboarding/blob/30e6b7b8f8d83eace542bd4bde9e71f5853b2d5d/plugin/src/pages/Wizard/steps/Dashboards/Dashboards.tsx#L103

I'm not sure about the next steps; we could either

1. Update the `cloud-onboarding` plugin to use the new Grafana 8 alerting
Not all instances have it enabled and it's not enabled by default for Enterprise – though perhaps we need not care about the latter since they probably don't have the cloud onboarding plugin installed.

2. We stick to the current implementation until we have the new alerting enabled for all cloud users.

**Comment by gillesdemey** [comment]
We will get in touch with the HG and cloud folks and see if we can

1. Update the onboarding plugin to use the new alerting
2. Figure out if we can remove the Cloud Alerting plugin from default installations

**Comment by besartberisha** [comment]
Hi there, so with the new layout that we are aiming to have shipped by the end of the month, the plugin itself will change a bit and the last page referencing to the Alertmanager will be removed completely. 

Here is the PR: https://github.com/grafana/cloud-onboarding/pull/1169 once this is merged/released I think this can be closed.

**Comment by armandgrillet** [comment]
Sounds good, I cannot relate the issue to that PR as it's not in the same repository thus please let us know once this is merged.

**Comment by besartberisha** [comment]
Hi @armandgrillet just wanted to let you know that this has been merged and released with the onboarding plugin v5.0.0.
