### ISSUE TITLE
Incorrect timestamp in query when relative time is used in date-picker

### ISSUE THREAD

**Issue by porta-support** [grafana/grafana#42887]
Rechecked on v8.1.1 and v8.3.0

Brief STR for v8.3.0:
- computer's time = 2021-11-12 17:13:31 +0200
- create ElasticSearch data-source
- 'Explore' created data-source or create any dashboard using ES
- select relative time in date-picker, from=now-1h  and to=now
- go to ' Query inspector', click 'Refresh', check 'timestamp' range (gtl/lte)
-   gte = 1638972801790 ( = 2021-12-08 14:13:21 in UTC)
-   lte = 1638976401790 ( = 2021-12-08 15:13:21 in UTC)

Actual result: no matter what time-zone is set for date-picker (or user), it has no any impact on  timestamp values - looks like default browser TZ (+2) always used

Expected result: timestamp value set correctly, considering date-picker or user's time-zone

![Screenshot_2021-12-08_17-23-55](https://user-images.githubusercontent.com/9444785/145235783-bbe4a6e3-52cb-4200-b14f-58a1ec0b361a.png)

**Comment by ashharrison90** [comment]
hey @porta-support 👋 
i believe this is expected behaviour. 🤔 

if you think about it, your timezone shouldn't have any effect on a relative time query:
- relative time is basically `Date.now() - <some const (e.g. 1h)>`
- `Date.now()` will return the same value independent of your timezone

it should affect the **display** of the query results. here my local time is ~09:50UTC, browser time is set to UTC + 3:
![image](https://user-images.githubusercontent.com/20999846/145373701-d9f7fef0-4b21-4b84-8e84-3e2c6af41ba0.png)

you can see the graph ends at about 12:50 (UTC + 3).

lemme know if i've missed something and we can reopen this. thanks! 😄

**Comment by porta-support** [comment]
hi @ashharrison90 

> it should affect the display of the query results
Agree, timezone does affect results, but I'm interested in 'input values', used as a filter for database

The thing is, absolute time (in date-picker) **does converted to the configured time-zone** (and used as a filter, sent in request). So I would expect similar behavior for both, absolute and relative values

**Comment by ashharrison90** [comment]
@porta-support 

sure, that's because the timezone matters for absolute time. if we say 9am on the 9th december, the actual timestamp for that is different in the USA compared to China. 

if we say the last hour, the timestamp is exactly the same wherever you are in the world.

does that make sense? 😄

**Comment by porta-support** [comment]
@ashharrison90 

>does that make sense?
Yes - no questions left

Thank you.
