### ISSUE TITLE
Upgrade from 8.2.1 to 8.3.1 caused all Grafana alert rules to lose all their "query"-type expressions due to "data source not found" and requires the manual recreation of ALL alert rules

### ISSUE THREAD

**Issue by zoltan-fedor** [grafana/grafana#42886]
**What happened**:
I have upgraded from 8.2.1 to 8.3.1 and as the result of that ALL Grafana alerts have lost all their "query" expressions from the UI (typically expression A) - see screen below. All alerts show "Data source not found" error, the queries which rely on that data source are hidden, not accessible through the UI, while the given data source (Prometheus) is in fact still exist. Creating a new alert with the same rules and same data source works.
This has caused all custom alerts to be in an errored state obviously and they can't be fixed.

Also even if you delete all expressions, you cannot delete A and recreate A, as A is hidden. 
Also you cannot fix the given alert, as you cannot touch the hidden A rule and if you try to save the alert you get the "Failed to save rule: failed to validate alert rule "[alertname]": invalid query A: data source not found: cjM4-UD7z" error, so all these alerts need to be thrown away and recreated from scratch manually. What a shit-show.

![image](https://user-images.githubusercontent.com/3887295/145231221-bec8d0d8-6a87-4b1a-b208-d1f7b9290e33.png)

**What you expected to happen**:
Minor version upgrades should not result in the loss of alerts. It seems there is no test coverage for this if a minor version upgrade can cause such a thing.

**How to reproduce it (as minimally and precisely as possible)**:
Create some alerts on 8.2.1 and then upgrade to 8.3.1

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.1
- Data source type & version: Prometheus
- OS Grafana is installed on: official docker image
- User OS & Browser: Linux Mint, Firefox
- Grafana plugins:
- Others:

**Comment by zoltan-fedor** [comment]
> custom

afana

**Comment by bravier** [comment]
Got exactly the same issue today on update from 8.2.3 to 8.3.1 on CentOS 8.
Both packages were from the official repository and the datasource for the query was Elasticsearch.

**Comment by nicocti** [comment]
same here ! rolling back won't recover alerts...

**Comment by the-harpia-io** [comment]
I have the same problem with the data sources after upgrading from 8.2 to 8.3.0 - "datasource not found".

Looks like in the new version of Grafana - dashboard connects to a data source via Datasource UID and before 8.3.0 it used Datasource Name.

It means - if I copy dashboard from one Grafana to another - it won`t work even if I have the same datasource name and dashboard. It won`t work because datasource ID is different

Please share how to fix it?

**Comment by nicocti** [comment]
Regarding broken alerts, you can retrieve the initial search query by inspecting network requests on the alert webpage, looking for the "rules" API call and dig in the JSON. This is definitely not the solution, but can save you time if you need to fix it before a fix is released...

**Comment by hiloyt** [comment]
Exactly this same situation, but in my case, it's just pure Thanos (Prometheus) configuration. 8.3.0 and above causing missing queries in alerts from query A, you can't edit it or save, because Grafana says `missing data source <id>`.

I tried to upgrade from 8.2.5 and 8.2.7.

The only way to fix this quickly now, it restores the 8.2.x version and imports a backup of grafana.db or data into your external db.

**Comment by yuri-tceretian** [comment]
Thanks for reporting! Do you use provisioned data sources? If yes, then I think you encountered this bug https://github.com/grafana/grafana/issues/42699, which has been already fixed. The fix will be available in 8.3.4. https://github.com/grafana/grafana/pull/42999
Please see the comment https://github.com/grafana/grafana/issues/42699#issuecomment-991300349 for a workaround.

**Comment by zoltan-fedor** [comment]
Yes, you are right, that seems to be the same issue.
Glad to hear that it will be fixed in 8.3.4.
Thanks!

**Comment by yuri-tceretian** [comment]
Do you think we can close this issue?

**Comment by zoltan-fedor** [comment]
Yes, I think so.
Let me close it then
