### ISSUE TITLE
Time range selector get locked if time-range from url is faulty.

### ISSUE THREAD

**Issue by hterik** [grafana/grafana#42917]
**What happened**:
1. Open following url: `http://grafana/explore?orgId=1&left=["1639090799000","1639004400000","-- Grafana --",{"refId":"A","instant":true,"range":true,"exemplar":true,"expr":""}]`
Notice that the time-range parameters in `left` are "accidentally" swapped. (This happened when generating url in external system)
2. Grafana automatically redirects and appends `&from` and `&to` parameters to url. This doesn't happen when time range is correct)
3. Try to change the time range using the date picker in top right corner 
   Nothing happens, it is impossible to get out of the faulty state without re-opening a new explorer.

**What you expected to happen**:
If time range is faulty, present an error to user.
Changing time range using the date picker should work after this.

**Environment**:
- Grafana version: 8.3.1
- User OS & Browser: Firefox 94 and Chrome 96 both have same issue.

**Comment by ashharrison90** [comment]
can repro on main. it's a pretty edge case bug though given it requires you specifying an incorrect range in the query params.

**Comment by connorlindsey** [comment]
@grafana/user-essentials could you take a look at this since it is an edge case in the date picker?

**Comment by aocenas** [comment]
There seems to be a bit more going on when the time range in URL is reversed. TimeSrv tries to fix it but probably makes it even worse because it does not know about Explore internals.

It would probably be easy to "fix" in Explore, but means more ambiguity in the URL format and code to handle it. Would be sort of cleaner to just throw an error, similar to what we do when we weren't able to parse the URL format correctly.

@hterik do you have a strong usecase why you would want these URLs to work (meaning reverse and treat the URL as [to, from] instead).

**Comment by hterik** [comment]
No use case for trying to self-repair these urls. It would be extremely ambiguous if one wants to swap, clamp or do something else, which would just hide the true source of the error.
Presenting a error is the right solution here IMO. 


Nice to have is if the user can fix this manually afterwards by just selecting a new date. In the current state the date picker becomes totally dead after you've opened a faulty url like this.
