### ISSUE TITLE
Some custom email templates stopped working after migration to Grafana Alerting

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#42946]
**What happened**:
In a legacy alerting system users can leverage templates embedded to Grafana like [alert](https://github.com/grafana/grafana/blob/97978a7c02aceeffa530712ddf23fd5e93de65e2/emails/templates/ng_alert_notification.html#L100-L102) and specify custom messages using that template.
After migration to the new Grafana Alerting the configuration of the contact point is migrated as is but the resulting message is empty:
<details><summary>Example</summary>

Message template:
```
  {{ if gt (len .Alerts.Firing) 0 }}
    {{ len .Alerts.Firing }} firing:
    {{ range .Alerts.Firing }} {{ template "alert" .}} {{ end }}
  {{ end }}
  {{ if gt (len .Alerts.Resolved) 0 }}
    {{ len .Alerts.Resolved }} resolved:
    {{ range .Alerts.Resolved }} {{ template "alert" .}} {{ end }}
  {{ end }}
```

![image](https://user-images.githubusercontent.com/25988953/145432428-218a0c99-494a-40eb-a2e9-e82e161fdb13.png)
</details>

The problem is that legacy alerting uses an email sender template expander. It provides the message to the email sender service as is https://github.com/grafana/grafana/blob/722c414fef32a02ebb7dbe2458a494eba2bedd2c/pkg/services/alerting/notifiers/email.go#L93 and then the sender expands that message.
The new Grafana Alerting works differently: it expands the message before sending to the sender using Alertmanager template https://github.com/grafana/grafana/blob/9122e7f647f44c1ceb7b9eb0e05beff4e23dc9cd/pkg/services/ngalert/notifier/channels/email.go#L86.

**Comment by yuri-tceretian** [comment]
Currently, the workaround is to copy template from sender templates https://github.com/grafana/grafana/blob/97978a7c02aceeffa530712ddf23fd5e93de65e2/emails/templates/ng_alert_notification.html#L3-L98 and create a new template in Grafana Alerting.

**Comment by ehuggz** [comment]
Support uncovered this same issue. Ended up removing all previously created alert templates until further information or fix provided.

**Comment by alexweav** [comment]
Does it seem reasonable to go back to using the already-existing template rendering system in the email service in ngalerting?

We now have two separate contexts where template rendering may occur. If we want to maintain total backwards compatibility with legacy message templates, the JSON passed to the rendering engine in both cases must be compatible. I suspect even if we fix this locally in the existing ngalert renderer, we still have risk of similar bugs occurring in the future if the json in either place drifts. Even purely additive changes are in danger, because different structures could be added under the same name.

It looks like we should be able to merge the am template's data blob with the `Data` field in `SendEmailCommand`, and then the Email service will JSON-merge the two rendering contexts. Then, templates will have access to both datasets and there won't be a contextual mismatch at render time. This also ensures backwards compatibility in the additive scenario above - the older email service template would take precedence, forcing compatibility to happen naturally. This also provides a better separation of concerns IMO.

As @yuri-tceretian's [excellent investigation](https://github.com/grafana/support-escalations/issues/1335#issuecomment-989970776) pointed out, it may have been an intentional decision to render ahead of time - if so, does anybody happen to have context on this? @gotjosh @JohnnyQQQQ 

The PR that introduced this (#34044) doesn't provide much info, so my plan is to move forward with the merged template approach above unless anyone objects.

**Comment by alexweav** [comment]
After looking into this further, from what I can tell there are three issues here:

1. **Templates which embed other templates are broken.** We can see this in the customer's original template, this part fails to render: `{{ template "alert" .}}`. The template evaluator in the Email service knows about the alert template, but the evaluator in ngalerting does not.
2. **Some template fields are broken.** The Email service's template evaluator adds [additional fields](https://github.com/grafana/grafana/blob/97978a7c02aceeffa530712ddf23fd5e93de65e2/pkg/services/notifications/email.go#L27) to the template JSON prior to evaluation. Templates evaluated in ngalerting do not have access to these fields any more.
3. 3. **Legacy alerting templates use a different set of fields.** The [template JSON](https://github.com/grafana/grafana/blob/97978a7c02aceeffa530712ddf23fd5e93de65e2/pkg/services/alerting/notifiers/email.go#L88) used by the legacy alerting system is not compatible with the ngalerting template json. So, templates migrated from legacy alerting might be broken after the upgrade.

**Comment by alexweav** [comment]
With regard to #3, I suspect this may be expected to some degree, since the entire structure of alerts changed. We may be able to map some legacy template fields in the current system for compatibility, but I'll also ensure we have reasonable docs on this.

**Comment by alexweav** [comment]
With regard to issue 1, I noticed that the template called "alert" defined in the notification service's template engine contains HTML. However, I do not think we expect HTML in UI-defined templates to actually render embedded in the email. I'm concerned about allowing this from a security perspective.

Indeed, when I extend the notification service's renderer to also be able to render the message, the resulting content gets HTML-encoded automatically by the template engine:

![html-expand](https://user-images.githubusercontent.com/8410871/147129897-e5c940ad-5c9c-434d-b3ed-077ab1ccd2a2.png)


I do not think we expect custom messages created in the Alerting UI to be able to expand into rendered HTML in the resulting email, and I'd be hesitant to do so for security reasons.

**Comment by alexweav** [comment]
The core point of confusion here is that custom messages completely override the email content today. However, custom messages are also quite a bit more limited because they will never be able render HTML correctly. This is a bit annoying for the user, as they have to pick - custom message with no fancy alerts in the email, or fancy alert email with no message customization. So, if custom templates are being used, it's hard to embed links, etc.

One possible (but UX-changing) solution would be to have the ng_alert_notification template show the custom content at the top and the HTML-based content at the bottom. This allows links to alarms/etc to remain while also supporting custom messages. It would also have reduced confusion in this case, because it would have been clear to the customer that the template only affects the custom message, and not the content at the bottom of the email.

**Comment by alexweav** [comment]
More pain points that I will address:
- Customer tried to use the "alert" builtin, which is intended mainly for internal use in the core email templater, not the alert templater.
  - Customer may have been confused by [this](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/message-templating/#custom-template-examples) section, which also documents a template called "alert." But, it's just an example, not a builtin. Will improve this to be more clear that these are examples, not predefined templates.
  - We don't document our predefined templates anywhere. [This page](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/message-templating/template-data/) seems like a great place to document this. A template called "alert" is not one of them.

**Comment by ehuggz** [comment]
@alexweav Let me clarify a few points as the customer in questions:

1.  The original issue is documented in Support Ticket ##37333, please review carefully. In this ticket you will see:
     a. The original alert was called "rrzFullmessageAlert" and not alert.
     b. The use of the alert builtin was on instruction from Support as directed by engineering.
     c.  The problems observed with custom ngalert templates were resolved only after deleting all custom alerts templates, of any sort.

**Comment by alexweav** [comment]
@ehuggz I ran into a couple auxiliary issues with templating - I'm trying a few different angles at making the workflow a bit less confusing in general.

Firstly, the `rrzFullMessageAlert` is also hit by the same issue as described above. (it contains `{{ template "alert" . }}` this is chain-embedded rather than directly)

The core problem here, as @yuri-tceretian described in that thread, is that we have two templating engines with different levels of functionality. One builds the Alerting message, and the other builds the actual email. The typical flow is that the alerting message is constructed, the result is sent to the email system, and then embedded in the final email. This workflow is confusing, since both template engines have access to a different set of defined templates, variables, etc. I'm making a few small PRs to align them a bit better.

The largest difference between the two engines is that the alerting template engine does not support rendered HTML. That is to say, we do not currently allow a template created in the UI to directly produce HTML, or embed another template that contains HTML, and have that HTML render in the resulting email. The `{{ template "alert" . }}` used in `rrzFullMessageAlert` uses HTML to construct the rendering in the screenshot attached to the original issue. Even if the Alerting engine were given access to this template, it still won't render and work as we expect - the user just gets the raw, un-evaluated HTML text in the email. I am discussing this with the team, but I suspect we will be hesitant to change this for security reasons.

However, one thing we _can_ do, is improve the outer email template. [Here](https://github.com/grafana/grafana/blob/7936c4c52261d3a20a0ffec529be88e3e3ef380b/public/emails/ng_alert_notification.html#L272), the if/else statement in the template causes the final email to only contain the user-defined message OR the nice rendering of alerts - not both at the same time. Since custom messages can't render HTML per above, a user ends up really limiting themselves if they use a custom alerting message, because the nice alert rendering disappears, and they  have no way of replicating it without HTML. I think we should instead have the option of showing both - the custom message at the top, and the alert renderings below, not a strict either/or. This would let the user in the original issue create an email almost identical to what they're wanting. It would also clarify the workflow a bit and be more apparent to the user what the limitations of the templating engines really are. I'm running this approach by the team, I think it strikes a good balance.

**Comment by ehuggz** [comment]
@alexweav  Very succinctly, and nicely wrapped up. I followed documented alerting examples when creating rrzFullMessageAlert and experienced exactly the behavior described, i.e. losing the HTML formatting, with custom alerts. I found that mode unusable and removed all customer alerts as a result.

A mix of the two modes could be a decent compromise.

**Comment by alexweav** [comment]
Apparently it's not just "fixes #<issue>" to have a PR auto-close an issue, the phrase "fix #<issue>" also has the same effect. So probably worth not accidentally including that substring in a PR description or one might end up accidentally closing things 🙃

**Comment by tmpjg** [comment]
> Currently, the workaround is to copy template from sender templates

[yuri-tceretian](https://github.com/yuri-tceretian) can you give me more details about the workaround ?

**Comment by yuri-tceretian** [comment]
On-premise users can edit the email template that is on the hard disk. For cloud users, I think the only way around is to use webhook together with Mailgun, Sendgrid, or similar services.

**Comment by alexweav** [comment]
@tmpjg @yuri-tceretian Yes, we don't allow HTML defined in alert templates (created via the UI) to render in the resulting notification - it'll all get escaped, for security reasons.

If you have access to your instance's filesystem, the workaround is to merge your template directly into `<grafana-install-dir>/public/emails/ng_alert_notification.html` which is the base template for the HTML email. But, you need filesystem access to do so - we don't allow users to edit renderable notification HTML in the UI.

**Comment by ehuggz** [comment]
@alexweav I have a high priority use case where I need to send dynamic content from Azure Kusto queries in alerts from a Grafana Cloud instance. Do I understand previous comments that there is no workaround for custom alert email template for cloud users within unified alerting? Are webhooks to customizable external email services currently the only option for Cloud Users?

**Comment by alexweav** [comment]
@ehuggz Correct, this is something our team has had many internal discussions on over the last week or so.

We met with the SA team for WF today, who is in a similar situation - the SA team is writing a small proxy service for their use case.

We are aware of the feature need in general, but we are currently not in agreeance on a solution. Also, there are security concerns at play (supporting this effectively means creating a service that can send **arbitrary** HTTP requests on behalf of grafana from within grafana cloud's firewall). We want to make sure we get this right.

**Comment by milinpatel13298** [comment]
> @ehuggz <edited, as I misread the question initially>
> 
> Yes, unfortunately. The main reason why is due to a security concern. Even if we unify the two template engines (UI and email) into one, HTML content entered into the UI won't produce a readable email - the HTML will be displayed as raw text, not rendered.
> 
> The rendering issue is also something that we are very hesitant to change directly. Allowing users to enter HTML through the UI, that is then rendered when the email is delivered to another user, opens up a route for HTML injection. Since there are security concerns at risk, it's not something we can do without being absolutely sure that it is safe for all users. The grafana project intentionally has this barrier in place.
> 
> However, I suspect we may not be _fully_ out of luck here. We can check with the hosted grafana team - we might be able to replace the on-disk template file on a customer by customer basis.

@alexweav Dees this restrict the custom templates that are visible in the Alert Rules UI or just the actual email body?

**Comment by pzatschl** [comment]
Any update on the situation?
