### ISSUE TITLE
Null values always connected in time series panel in 8.3.1

### ISSUE THREAD

**Issue by STandon-3** [grafana/grafana#42993]
**What happened**:
When using a time series panel to visualise Prometheus time series data using a line style graph, when there are null values (i.e. no data retrieved from Prometheus for a period), the line connects these values. This behaviour has only occured since upgrading from Grafana 8.2.7 to 8.3.1.
Changing the selected option Graph styles/connect null values from Never, to Always, to Threshold has no impact.

The panel in Grafana 8.2.7:
![Screenshot 2021-12-10 at 16 56 17](https://user-images.githubusercontent.com/70574342/145621394-e9e6c957-bdf6-4d43-ad56-2d8e1539382e.png)

The panel in Grafana 8.3.1:
<img width="1199" alt="Screenshot 2021-12-10 at 18 12 05" src="https://user-images.githubusercontent.com/70574342/145621728-59cb644d-3a53-4fa7-9f7c-187e58dad1e0.png">

**What you expected to happen**:
I expected that the line would stop and not be shown when there is no data.

**How to reproduce it (as minimally and precisely as possible)**:
In Grafana 8.3.1, create a time series panel with a line graph style using a query containing null values. Try changing the 'Connect null values' option in graph styles and see that it never makes a difference. 

**Anything else we need to know?**:
[This](https://github.com/grafana/grafana/issues/40698) is a related issue about the same problem in the old Graph panel, which was solved by this [PR](https://github.com/grafana/grafana/pull/40757). However, I've tried changing the Time Series panel to the old Graph panel, and changing the null value options to null or null as zero doesn't work, the points are always connected.

**Environment**:
- Grafana version: 8.3.1
- Data source type & version: Prometheus 
- OS Grafana is installed on: 
- User OS & Browser: macOS Catalina/Firefox
- Grafana plugins:
- Others:

**Comment by bolshoytoster** [comment]
This issue appears to have been caused by #29633

**Comment by Alexul** [comment]
+1, also noticing this behavior in 8.3.1 in both old and new graphs
<img width="1288" alt="Screen Shot 2021-12-12 at 13 55 27" src="https://user-images.githubusercontent.com/10867201/145711212-f7cfbf9b-02d2-4df3-989c-34d1f18f577e.png">

**Comment by siebenmann** [comment]
I have also noticed this issue in our dashboards (and it caused us to revert to 8.2.7). It appears to be a general problem where under some circumstances values that should be null are instead invented as 0. One related case is that if you set a Time Series panel to Points, use a query that returns a mixture of present results and null results, for example in Prometheus Blackbox `count(probe_success == 0) by (probe)`, any time one of the time series has a result, all of the other time series are rendered at the bottom on the 0 line, although they don't seem to be actual 0 values if you mouse over them to see the tooltip with their value.

(Possibly this is a different bug but it certainly feels very related, if not the same thing.)

**Comment by michaelkebe** [comment]
This is related #43410.

Introduced in version 8.3.0

**Comment by michaelkebe** [comment]
I tried to reproduce it with the TestData DB Datasource, but here it works a expected:

Connected Null Values set to Never:
![image](https://user-images.githubusercontent.com/74952/147058120-6503e7c0-1858-4219-a393-0c10b261eded.png)

Connected Null Values set to Always:
![image](https://user-images.githubusercontent.com/74952/147058143-f79b2c28-6dd4-46ae-b84f-ee31a02998fe.png)

**Comment by STandon-3** [comment]
@michaelkebe It might only happen with a Prometheus data source, which was also indicated in [#40698](https://github.com/grafana/grafana/issues/40698) - although if anybody has experienced it with a different data source, it would be interesting to know!

**Comment by ivanahuckova** [comment]
I've looked into this and here is what is happening - we are correctly showing null/NaN values from Prometheus. You can test this out [here on play site with this example](https://play.grafana.org/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22demo.robustperception.io%22,%7B%22refId%22:%22A%22,%22instant%22:true,%22range%22:true,%22exemplar%22:true,%22expr%22:%22histogram_quantile(0.99,rate(prometheus_http_response_size_bytes_bucket%7Bhandler%3D%5C%22%2Fapi%2Fv1%2Fmetadata%5C%22%7D%5B$__rate_interval%5D))%22%7D%5D). The issue happens when Prometheus doesn't send us null/NaN data and basically just "skips" the step. I was able to make this happen when Prometheus was running but I paused the data. In this case, I didn't receive null/NaN points from Prometheus. 

In this case [on frontend we fill out missing steps with null value](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/result_transformer.ts#L383-L389). I checked that also native Prometheus probably does this (I run the query and looked into network tab to see if there are any null/NaN values, and there weren't). 

@gabor @Elfo404 Do we think it make sense to do this on backend or on frontend? We should probably keep this consistent and just implement it on backend, but wanted to. hear your thoughts on this. :)

**Comment by siebenmann** [comment]
An easy way to make a Prometheus query skip this way is to change the query from its normal form to something with a condition at the end, such as "> N" or "< N" for appropriate N (eg `node_load1 > 0.5` instead of just `node_load1`).

One way to explain what's going on is to say that Prometheus range queries skip this way because each step is evaluated separately, without knowledge of what time series were supplied at previous steps. If the query set operations at a particular step exclude a time series, there is no null value provided in the result for the step (Prometheus has no concept of 'null values'), it's just not there. If a consumer of Prometheus query results needs null values for missing time series, it needs to make them itself.

**Comment by sylr** [comment]
I might be wrong but the cause of this might also be the reason of https://github.com/grafana/grafana/issues/42868
