### ISSUE TITLE
SymLink in default plugins folder causes server to not load any plugins

### ISSUE THREAD

**Issue by acedrew** [grafana/grafana#43012]
**What happened**: 
I updated to 8.3.2 and my grafana-server instance started logging that no image renderer was installed. I checked using grafana-cli and it showed installed, I continued troubleshooting, including re-installing the plugin, and re-verifying the dependencies.
There was another error logged that I thought was unrelated:
```t=2021-12-12T17:13:23+0000 lvl=dbug msg="Couldn't scan directory due to lack of permissions" logger=plugin.finder pluginDir=/var/lib/grafana/plugins err="stat /var/lib/grafana/plugins/********-panel: permission denied"```

On further digging, this was a development plugin that was symlinked into the plugins directory from a development user's home directory. I removed the symlink and all the plugins loaded correctly. I also took some intermediate testing steps of adjusting the permissions of both the symlink and the target, making the grafana service user owner of both, it was only resolved on removal of the symlink.

To verify the plugin itself was not causing the problem, I copied the content of the symlinked folder into the `/var/lib/grafana/plugins/` directory, and everything continued to work.

**What you expected to happen**:
Whether or not symlinks should be allowed, I would have expected the grafana-cli to show the same issues. Preferably, a single plugin failing to load should not prohibit all other plugins from loading.

**How to reproduce it (as minimally and precisely as possible)**:
**I have not attempted to reproduce it** 
But I would start with placing a manual install of a plugin into a folder not in the default plugins directory, and symlinking to that plugin in the default plugins directory.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 8.3.2
- Data source type & version: N/A
- OS Grafana is installed on: Ubuntu Linux 18.04 5.4.0-1060-aws Kernel
- User OS & Browser: N/A
- Grafana plugins: Custom and standard
- Others:

**Comment by marefr** [comment]
Tested locally on main (f789a7f88cb838872ab756a299578eac4629bd50):
```
cd /go/src/github.com/grafana/grafana/data/plugins
sudo su
mkdir test
cd test
touch plugin.json
chmod 700 plugin.json
cd ..
chmod 700 test 
```

Started Grafana and got some random failure not related to loading plugins. But I could see that no plugins was loaded from data/plugins directory.

Had to turn on the following config:
```ini
[log]
filters = plugin.finder:debug
```

Then I got 
DBUG[12-16|15:46:59] Couldn't scan directory due to lack of permissions logger=plugin.finder pluginDir=/go/src/gith
ub.com/grafana/grafana/data/plugins err="filepath.Walk reported an error for \"/go/src/github.com/grafana/grafana/data/plugins/test\": open /go/src/github.com/grafana/grafana/data/plugins/test: permission denied"

I'm not sure how easy it is to change this so that rest of the plugins in a directory is loaded where some have permissions problems. What we definitely should do is log errors instead of debug because it's not very clear right now what's happening. To me it's not very clear right now why we log this with debug level here, but going to ask for some advice:
https://github.com/grafana/grafana/blob/f789a7f88cb838872ab756a299578eac4629bd50/pkg/plugins/manager/loader/finder/finder.go#L77-L84

**Comment by marefr** [comment]
I did test removing the if-statements below so that the error is returned:
https://github.com/grafana/grafana/blob/f789a7f88cb838872ab756a299578eac4629bd50/pkg/plugins/manager/loader/finder/finder.go#L77-L86

Running Grafana with this results in an error logged and Grafana continues its initialization phase.
EROR[12-16|16:09:09] plugin finder encountered an error       logger=plugin.loader err="filepath.Walk reported an error for \"/
go/src/github.com/grafana/grafana/data/plugins/test\": open /go/src/github.com/grafana/grafana/data/plu
gins/test: permission denied"

In addition, if the error is returned the loader continues to call loadPlugins even though there can never be any plugins to load because when an error is returned from finder the `pluginJSONPaths` will always be empty:
https://github.com/grafana/grafana/blob/f789a7f88cb838872ab756a299578eac4629bd50/pkg/plugins/manager/loader/loader.go#L56-L61

**Comment by simonc6372** [comment]
This also happens if a directory that the grafana user cannot access is in the plugin directory. 
This can happen if a more "secure" umask such as 0077 is used, and grafana-cli is ran as root rather the user that Grafana runs under.
At the very least, the error here should be reported at the `error` level, not `debug`.

**Comment by SimHacker** [comment]
Related issue:
Grafana plugins directory in /home doesn't work, and Grafana crashes and restarts. #44621
https://github.com/grafana/grafana/issues/44621
