### ISSUE TITLE
Not working custom cloudwatch metric without dimension

### ISSUE THREAD

**Issue by mpostument** [grafana/grafana#43098]
**What happened**:
After upgrading grafana to version 8.1.2 to version 8.3.2 all custom cloudwatch metrics without dimension is not displayed on grafana dashboards

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.2
- Data source type & version: CloudWatch
- OS Grafana is installed on: Centos
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by sunker** [comment]
Thanks for creating this issue @mpostument.

This issue was fixed in [this](https://github.com/grafana/grafana/pull/42800) PR. I think 8.3.3 will be released today or tomorrow, and that release should include this fix. 

Will close this issue now. Feel free to reopen it if you're still seeing this issue after upgrading to 8.3.3.
