### ISSUE TITLE
Explore: Datasource name should be escaped in URL

### ISSUE THREAD

**Issue by colega** [grafana/grafana#43190]
**What happened**:

I created a tempo datasource called `Tempo (ops)`, went to the explore mode and selected it, the URL looked like:

`https://somewhere.grafana.com/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Tempo%20(ops)%22,%7B%22refId%22:%22A%22%7D%5D`

The URL work as the browser does its magic, but it's especially annoying since you can't copy and use it in a markdown link like:

```
Look at [my trace](https://somewhere.grafana.com/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Tempo%20(ops)%22,%7B%22refId%22:%22A%22%7D%5D)
```

**What you expected to happen**:

Datasource name should be URL-encoded in the address, i.e. `Tempo (ops)` should be `Tempo%20%28ops%29`, and the URL should look like:

`https://somewhere.grafana.something/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Tempo%20%28ops%29%22,%7B%22refId%22:%22A%22%7D%5D`

**How to reproduce it (as minimally and precisely as possible)**:

- Create a tempo datasource called `Tempo(foo)`
- Go to explore mode
- Select the new datasource
- Check the url

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.6 and also 8.4.0-45467pre
- Data source type & version: Tempo
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome on both Linux & Mac
- Grafana plugins: N/A
- Others:

**Comment by Elfo404** [comment]
Thanks for reporting this.

just to have a bit more context, are you referring to Slack in this context? i tried your very same link and seems to work fine in a few other apps.

**Comment by Elfo404** [comment]
After discussing this internally we decided to not take any action on this. Although it may be bothering at times, we feel writing a custom encoding strategy for Explore only would be more problematic than beneficial and in general we feel this issue is more related to the markdown parser being used than Grafana itself.

To workaround this (and to have probably nicer URLs to share) for markdown tools that do not play nicely with parenthesis in URLs, users can still use the share button in the Explore toolbar to generate a shortlink
![Screenshot 2022-02-07 at 15 34 36](https://user-images.githubusercontent.com/1170767/152819669-922e25c9-9bff-456c-97fc-5dc01f2bec9c.png)

**Comment by colega** [comment]
Sorry I never gave back any context on this. Yes, I was referring to slack.

It seems that slack allows a closing parenthesis if there was an opening one, but it doesn't allow two if there were two, i.e., this link breaks in Slack: `https://grafana.com/foo(bar(baz)bar)foo`

![image](https://user-images.githubusercontent.com/1511481/154496176-912e7ba1-5437-4b5b-be56-00f817773257.png)

I think maybe the issue should be redefined to just extend the URL escaper that Grafana uses to also escape parenthesis (as you mentioned, it's not required by standard, but it seems to cause issues here and there)
