### ISSUE TITLE
Unable to add ApiKey to OpsGenie notification

### ISSUE THREAD

**Issue by pimjansen** [grafana/grafana#43214]
**What happened**:
While adding the OpsGenie notification below error is shown while testing after saving the form and re-opening:
```
alert validation error: Could not find api key property in settings
```

**What you expected to happen**:
Expect that the API key is stored correct.

**How to reproduce it (as minimally and precisely as possible)**:
* Add a new notification to OpsGenie
* Add all fields including ApiKey
* Run Test which is succesful.
* Click Save
* Click Back
* Open the OpsGenie notification channel again
* Click test button
* Error is shown that ApiKey is not found.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.3
- OS Grafana is installed on: Official docker image
- User OS & Browser: Ubuntu 20.04 / Chrome

**Comment by chloewlee97** [comment]
Hello, this issue is happening for our existing slack notification channels after an upgrade from v8.1.2 to v8.3.3.

The workflow for us is as follows:
1. Open existing notification channel (slack) 
2. Run Test
3. Error is shown

Saving the notification channel also throws the same error as well as another empty error notification 
<img width="1378" alt="Screen Shot 2021-12-17 at 9 49 14 AM" src="https://user-images.githubusercontent.com/78376671/146562604-77280065-2b3a-41e3-9380-86366d8ee38b.png">

Grafana logs are as follows (for the same transaction as the one in the screenshot above) 
```
t=2021-12-17T14:49:11+0000 lvl=eror msg="alert validation error: token must be specified when using the Slack chat API" logger=context userId=REDACTED orgId=1 uname=REDACTED error="alert validation error: token must be specified when using the Slack chat API" remote_addr=REDACTED
t=2021-12-17T14:49:11+0000 lvl=info msg="Request Completed" logger=context userId=REDACTED orgId=1 uname=REDACTED method=PUT path=/api/alert-notifications/3 status=400 remote_addr=REDACTED time_ms=2 size=91 referer=https://OUR GRAFANA HOST/alerting/notification/3/edit
```

Triggered alerts send notifications to these channels fine. It's just when we try to edit/test/save notification channel configurations.

**Comment by pimjansen** [comment]
Is there a workaround available? For example downgrade to 8.1 or where did this come from?

**Comment by peterholmberg** [comment]
@chloewlee97 do you have a slack webhook url or token specified?

**Comment by chloewlee97** [comment]
@peterholmberg yeah both the webhook url & token were set

**Comment by peterholmberg** [comment]
Just to clarify, are you using Grafana 8 "Unified Alerting" because in your screenshot it looks like "legacy" panel alerting?

You're mentioning that you migrated, was that from legacy to Grafana 8 alerting?

**Comment by pimjansen** [comment]
For me it is still legacy alerting.

**Comment by chloewlee97** [comment]
@peterholmberg still legacy alerting for me as well

**Comment by mogggggg** [comment]
I'm also seeing the same issue upgrading from 8.3.1 -> 8.3.3 with legacy alerting enabled using webhook URLs.

**Comment by gillesdemey** [comment]
I've investigated this and figured out that;

Secure settings are being fetched in the backend using the `OrgId` and notifier `Id`.

https://github.com/grafana/grafana/blob/8fcab78b332b4c539598bf5a31a6a06ee6c48c25/pkg/services/alerting/service.go#L129-L143

However the SQL query that is executed is using `OrgId: 0` – this seems to be because the `OrgId` is not added to the `AlertNotification` struct here

https://github.com/grafana/grafana/blob/8fcab78b332b4c539598bf5a31a6a06ee6c48c25/pkg/services/alerting/test_notification.go#L34-L39

This in turn fails silently since there are no SQL results to decode secure settings from when we create the notifier.

I will draft up a PR to fix this – it seems like multiple notification channels were impacted that used encrypted settings but was limited to the "test" command.
