### ISSUE TITLE
Docs feedback: /installation/kubernetes.md

### ISSUE THREAD

**Issue by matthewmucker-vizio** [grafana/grafana#43242]
The .yaml file appears to pull version 7.5.2 instead of the latest release. I'm new to both Kubernetes and Grafana so while I suspect this is wrong, I'm not sure what else, if anything, also needs to be changed in the .yaml file.

https://grafana.com/docs/grafana/latest/installation/kubernetes/

**Comment by achatterjee-grafana** [comment]
@gguillotte-grafana, FYI

**Comment by gguillotte-grafana** [comment]
@matthewmucker-vizio Can you confirm the specific version you're looking at, just to confirm that I'm on the same page?

For instance, the YAML on https://grafana.com/docs/grafana/latest/installation/kubernetes/ (emphasis on _/latest/_) appears to point to 8.4.4, which lines up with the version of the docs as of today (8.4.4). However, the YAML on https://grafana.com/docs/grafana/v8.3/installation/kubernetes/ points to 7.5.2.

This is important because it'll help me define where to backport the necessary changes.

**Comment by gguillotte-grafana** [comment]
Example:

![image](https://user-images.githubusercontent.com/100453168/162071124-9f288151-c0cd-4b86-97a3-dd3cd6f2a29b.png)

**Comment by chri2547** [comment]
The Kubernetes install docs have been recently updated and tested. https://grafana.com/docs/grafana/latest/setup-grafana/installation/kubernetes/

Closing this issue.
