### ISSUE TITLE
TimeSeries: Sorting Legend by Last* Doesn't Sort Stacked Items

### ISSUE THREAD

**Issue by kustodian** [grafana/grafana#43537]
**What happened**:
When sorting the items in the legend by `Last*` it doesn't sort stacked items on the graph.

**What you expected to happen**:
That it sorts stacked items on the graph as it does for `Last`, `Mean`, etc.

**How to reproduce it (as minimally and precisely as possible)**:

Just add a `Last*` value and try sorting on it. See the video below:

https://user-images.githubusercontent.com/1949229/147466840-80a42a44-ef41-4534-bb1c-13e4759b389f.mp4

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: Prometheus
- OS Grafana is installed on: CentOS 7
- User OS & Browser: ArchLinux/Firefox

**Comment by zuchka** [comment]
Thanks for creating this issue, @kustodian 

This sounds related to several issues:

- https://github.com/grafana/grafana/issues/34912
- https://github.com/grafana/grafana/issues/35554#issuecomment-873671806

I don't know if this stacking + last* issue runs up against the "interpolating nulls" reasoning mentioned [in this important comment](https://github.com/grafana/grafana/issues/35554#issuecomment-873859060), but perhaps?

> The stacking of null values required interpolating missing data points, and it caused numerous floating bars & and strange bugs. Not sure we will add that back. Is there another way to solve this using a transform?

Here is [a dashboard replicating the OP's issue](https://play.grafana.org/d/2fvRLzA7z/issue-43537?orgId=1)

Will let the squad decide how to classify this issue 👍

**Comment by kustodian** [comment]
It doesn't look like it's related to any of the linked issues/comments. I don't have any null data in the graph I'm showing and I don't have problems with stacking. Only sorting with `Last*` doesn't work.

**Comment by dprokop** [comment]
The problem lies in the fact that we use the reducer name instead of the reducer id as the sortBy key used for organizing the series (https://github.com/grafana/grafana/blob/e6d2324516e5c6b3fa2cbc612fb979e081bd75bb/packages/grafana-ui/src/components/uPlot/utils.ts#L207)

**Comment by leeoniya** [comment]
we've removed this functionality in https://github.com/grafana/grafana/pull/47373 to avoid:

- Series from re-stacking dynamically during data updates (can be quite bad experience with spikes, if stacking by dynamic min, max, last, or avg)
- Dashboards changing unpredictably from day to day or reload-to-reload

In addition to above, if series order can change without notice and colors were not explicitly set via overrides, then the colors can be re-assigned to other series, make the data hard to interpret. though this issue is not specifically related to stacking.

The stacking order now follows series order, and can be controlled via the [Organize fields transform](https://grafana.com/docs/grafana/latest/panels/reference-transformation-functions/#organize-fields), or by reordering the query. We intend to evaluate additional alternatives, such as adding `stacking.order` config alongside the existing `stacking.mode` and `stacking.group` config options.

**Comment by bboreham** [comment]
> or by reordering the query.

For the record, this doesn't work. Prometheus range queries always sort the series by label names/values.
