### ISSUE TITLE
Improve CUE DX - cannot generate

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#43534]
**What happened**:

I have changes in cue files and I'm trying to generate models. 

make target `gen-ts` seems not to work and grafana-cli does not update anything.

**How to reproduce it (as minimally and precisely as possible)**:

Modify `packages/grafana-schema/src/schema/table.cue`. Then try to generate the change into `packages/grafana-schema/src/schema/graph.gen.ts`.

```bash
$ make gen-ts

generating TypeScript definitions
go get github.com/tkrajina/typescriptify-golang-structs/typescriptify@v0.1.7
tscriptify -interface -package=github.com/grafana/grafana/pkg/services/live/pipeline -import="import { FieldConfig } from '@grafana/data'" -target=public/app/features/live/pipeline/models.gen.ts pkg/services/live/pipeline/config.go
/bin/sh: tscriptify: command not found
make: *** [gen-ts] Error 127
```

This produces no changes.
```bash
$ bin/darwin-amd64/grafana-cli cue gen-ts --grafana-root .
$ yarn run eslint . --ext .gen.ts --fix
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.x
- User OS & Browser: Macos

**Comment by zuchka** [comment]
any feedback, @sdboyer? 👍

**Comment by sdboyer** [comment]
Hi, back from holidays now.

First, apologies: the CUE subsystems remain woefully undocumented and have been for a while. We're finally turning the corner on that, sorta starting from the foundations and working up with the [Thema docs](https://github.com/grafana/thema/blob/main/docs/overview.md). Those have been the missing dependency prerequisite to documenting things like how this particular bit of codegen works.

The command that does the work here is actually `grafana-cli cue gen-ts`, not `make gen-ts`. However, `packages/grafana-schema/src/schema/table.cue` is not actually going to be generated by that command, as long as it's in [this blacklist](https://github.com/grafana/grafana/blob/8dc4c23a89a803061b48ef4e40bb545843ea2f71/pkg/cmd/grafana-cli/commands/cuetsify_command.go#L55-L60). That blacklist exists because [the underlying library](https://github.com/grafana/cuetsy) we use to do the ts generation is still a WIP, and has bugs in some cases.

cc @ryantxu just more confirmation here that docs are desperately needed. It's on my radar!

**Comment by simPod** [comment]
@sdboyer btw do you have any idea why TS definitions are generated from cue instead of having TS definitions in the first place? I'm curious what's behind the decision 🙃  especially considered

> CUE subsystems remain woefully undocumented

**Comment by sdboyer** [comment]
@simPod yup!

Short version: we always _have_ had TS definitions. What we're looking for in CUE is - among other things - canonical schema definitions that are equally clear and canonical on the frontend and backend. An [IDL](https://en.wikipedia.org/wiki/Interface_description_language).

More of the motivation was explained in our talk from last summer: https://grafana.com/go/grafanaconline/2021/dashboards-as-code/ . (Things have taken longer than we optimistically projected there, clearly - but we are making progress!)

**Comment by sdboyer** [comment]
This has all been overhauled in recent months into a more unified system, consisting roughly of what's described in #43534. Preconditions have _finally_ been met for docs to be coming in a proper way.

Fortunately, in the meantime, the answer is simple: `make gen-cue` should be the only command that needs to be run now.
