### ISSUE TITLE
TablePanel: hidden fields works but column filter does NOT

### ISSUE THREAD

**Issue by jcdauchy-moodys** [grafana/grafana#43575]
**What happened**:

Since release 8.2.x, we can now use a feature to be able to HIDE fields and still use in datalinks ( #24092 ), the main issue is now fixed :  https://github.com/grafana/grafana/issues/43191

But when you use at least 1 hidden field before one column where we want to use the "Column Filter" toggle, the "Column Filter" toggle is applied on another (further right).

If the  "Column Filter" options is used on a column which is BEFORE the hidden column, it works, so we can use this workaround for the moment.

**What you expected to happen**:

How to reproduce it (as minimally and precisely as possible):

Here is an example using the CSV example, the "Column Filter" toogle should be applied to "DestLocation" columns and NOT on "Count" column.

**How to reproduce it (as minimally and precisely as possible)**:

![image](https://user-images.githubusercontent.com/56868940/147647409-3ac7a983-c09d-4fac-a768-d741c010d055.png)

**Anything else we need to know?**:

So the "hidden field" feature is now usable, but you need to fiddle with column orders if you want to use the "Column filter" toggle.

**Environment**:

Grafana version: 8.4.0-pre (branch : fix-table-hidden-field-issues)
Data source type & version:
OS Grafana is installed on: Linux
User OS & Browser: Chrome
Grafana plugins: Table panel
Others:

**Comment by zuchka** [comment]
> 8.4.0-pre (branch : fix-table-hidden-field-issues)

fyi ☝️

**Comment by sbengo** [comment]
Encountered with the same problem:

When a column is hidden, the next column filters refers to the hidden column

Repro in https://play.grafana.org/d/OhR1ID6Mk/3-table  - v8.4.3-54429
- Edit panel 'Image cell and bar gauge cell'
- Mark "Column Filter" global property
- Modify the override property field with name "Something" and select "Hide on table"
- Mark "Hide on table" and click the "Sensor" Column

The filters refers to the hidden column "Something" instead of "Sensor" column

![image](https://user-images.githubusercontent.com/13196237/159300434-28a30f4c-40f9-4efb-8a78-5d117c005fa6.png)
