### ISSUE TITLE
Azure Monitor DS: Logs resource picker does not have support for variables.

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#43618]
**What happened**:
On a dashboard with variables if a panel is created with Azure Monitor datasource and Logs as the service, when a variable is selected as the resource, Grafana crashes and throws the error "PathNotFound": 
![image](https://user-images.githubusercontent.com/20448042/147941081-c3c93080-fb1c-4b6b-a8c9-157b2ebb7b15.png)

After some inspection, it seems as though it is because the resource path is not being properly populated, it is rather just injecting the resource name, not a full path: 
![image](https://user-images.githubusercontent.com/20448042/147941149-1c62dc05-e86e-43c3-9781-7d9dc520ad85.png)

**What you expected to happen**:

For the same resource selected above, except this time not through variables, this is what the user should see: 
![image](https://user-images.githubusercontent.com/20448042/147941245-402b7fae-1964-44f6-b2d7-dc33a806dc08.png)

and what the resource path should look like
![image](https://user-images.githubusercontent.com/20448042/147941311-a1f43150-4d6e-4161-b336-6c7202a8da66.png)

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard with variables using the Azure Monitor data source. 
2. Add a panel with the data source as Azure Monitor and the service as Logs
3. Select any of the variables in the dashboard as the resource path
4. Add a simple query for grafana to run.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 8.4.0-pre
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Windows
- User OS & Browser: Windows & Edge
- Grafana plugins:
- Others:

**Comment by sarahzinger** [comment]
@jcolladokuri I'm taking a look at this now and I'm wondering how did you go about creating the `res` template variable? 

I created a template variable called `workspaces` and used the grafana query function to grab potential workspaces like so:
<img width="844" alt="Screen Shot 2022-01-04 at 3 42 06 PM" src="https://user-images.githubusercontent.com/6620164/148121392-b565c0e4-56ba-42fa-b27a-a14e3ddebd08.png">

and I was able to select it and use it ok (I don't have any data showing, but I think that's because I have bad test data)
<img width="891" alt="Screen Shot 2022-01-04 at 3 43 37 PM" src="https://user-images.githubusercontent.com/6620164/148121573-a01622ac-42f0-45ef-8416-1ff2a6ed84d7.png">

I did notice if I created a hard coded query variable of just the name of the resource like so:
<img width="858" alt="Screen Shot 2022-01-04 at 3 44 45 PM" src="https://user-images.githubusercontent.com/6620164/148121674-3556860d-861a-48b6-9839-c25b24cc31b3.png">
that I did run into the same error:

<img width="883" alt="Screen Shot 2022-01-04 at 3 45 30 PM" src="https://user-images.githubusercontent.com/6620164/148121769-0cf5067f-8beb-46f8-8975-75c9ec111a28.png">

I assume it shouldn't be too difficult to get the resource uri from the name of the resource but I just want to make sure I'm taking into account the different ways a user could get here and what format their selection would come in.

**Comment by jcolladokuri** [comment]
Hey @sarahzinger thank you for taking a look! For some reason, workspaces variables get properly replaced (this has actually been our work around for dashboards that need the Logs service and support for variables). For the res template variable, once you have a subscription, resource group and namespace you can query all resources like so (also using a grafana query function in the Azure Monitor data source):

`ResourceNames($sub, $rg, $ns)`

I have a PR out for a potential fix for this (https://github.com/grafana/grafana/pull/43434) let me know what you think (P.S. I am working on adding test cases)

**Comment by andresmgot** [comment]
@jcolladokuri thanks for the suggestion in #43434! In any case, I don't think we should continue that path. The resource field is supposed to be the full path of the resource, we should not try to guess where the resource is coming from. If we do that, we could return the wrong resource (in case there are multiple resources named the same way in different namespaces, resource groups or subscriptions).

Here we could do two things:

1. Allow people to manually edit the value of the resource, so they can type things like:
```
/${sub}/${rg}/${ns}/${res}
```

2. Add a new function that returns the full path of the resource. Something like:
```
ResourcePaths($sub, $rg, $ns)
```

I like the first option because it's more flexible and allow people to workaround issues with the picker but it's probably out of the scope for this issue and more difficult. The second function should be trivial to implement.

**Comment by jcolladokuri** [comment]
@andresmgot Thank you for the feedback! 

For option 1, do you mean that we would change the resource picker to be able to take text input for the user to manually type in the path? 

I personally like something like 2 a bit more. My main concern with option 1 is that it would require the users to know the full path of the resource they want to view data for. In the case of OOB dashboards, for example, for those that use Log Analytics and dashboard variables, we would ideally just want the user to simply select a resource from the dropdowns and the dashboard updates automatically without having them to go into panels and input their own path.

Additionally, Logs can be run on subscriptions and resource groups, for a bigger scope, not just resources, so I think that whichever path we decide to take, should take this into consideration. Let me know what your thoughts are.

**Comment by andresmgot** [comment]
Yes, I agree that option 2 it's a more suitable path here. 

> Additionally, Logs can be run on subscriptions and resource groups, for a bigger scope, not just resources, so I think that whichever path we decide to take, should take this into consideration. Let me know what your thoughts are.

I agree, we can make some (or all) of the parameter optional: `ResourcePaths([$sub], [$rg], [$ns])`

**Comment by jcolladokuri** [comment]
To clarify, when you say function, do you mean add it as an Azure Monitor template variable function? Or simply one that gets called at runtime when a variable is selected in the resource picker?

**Comment by andresmgot** [comment]
yes sorry, I mean a template variable like the ones listed here: https://grafana.com/docs/grafana/latest/datasources/azuremonitor/template-variables/

**Comment by kayodeprinceMS** [comment]
@andresmgot We’re happy to move forward with the Template Variable suggestion offered above but note that this introduces another variable that the user must create and maintain.  This new variable will also introduce additional complexity in order to support queries on subscriptions and resource groups because some parameters will need to be optional depending on the intended scope. So, in addition to the variable, we’d also like to move forward with a solution that returns the path for Log resources when the other template variables such as subscription, resource groups and resource names are used.

**Comment by andresmgot** [comment]
> This new variable will also introduce additional complexity in order to support queries on subscriptions and resource groups because some parameters will need to be optional depending on the intended scope.

Yes, I would try to reduce the cases as much as possible. This means that if the function has one parameter, this has to be the subscription. If it has two, it should be subscription + resource group. Three for the subs + rg + resource namespace. 

> So, in addition to the variable, we’d also like to move forward with a solution that returns the path for Log resources when the other template variables such as subscription, resource groups and resource names are used.

I don't think it's a suitable solution for this. The way template variables work in Grafana (and variables in general) is that whatever the value of the variable is (in this case a resource name, e.g. `var=resource-1`) it will be exactly replaced when the variable is used.

That proposal would introduce a different behavior in which a variable `$var` would return a different value depending on the context of the dashboard. It would also make impossible to use just the resource name (not the full path) if other template variables are defined. Another possible issue is that the resolution of the path can be wrong if several resource groups contains the same resource, again being impossible to correct it.

Any solution we introduce, the reference to other variables should be explicit so we avoid the problems above.

**Comment by kayodeprinceMS** [comment]
> That proposal would introduce a different behavior in which a variable $var would return a different value depending on the context of the dashboard. It would also make impossible to use just the resource name (not the full path) if other template variables are defined. Another possible issue is that the resolution of the path can be wrong if several resource groups contains the same resource, again being impossible to correct it.

Fair point on the introducing inconsistency depending on where the variables are used. Today, there is already some inconsistency when vars are used in the Logs resource selector. The workspace template variable can be used directly without providing the path (sub/rg) where the workspace is located and other resources cannot.

> Another possible issue is that the resolution of the path can be wrong if several resource groups contains the same resource, again being impossible to correct it.

Isn't this already addressed with existing ResourceNames template variable that takes arguments for resource group and namespace.

I don't disagree with the new resource path variable proposal but I'm also interested in the simplest user experience.

**Comment by andresmgot** [comment]
> The workspace template variable can be used directly without providing the path (sub/rg) where the workspace is located and other resources cannot.

This is because the `workspaces()` function returns values for all the subscriptions and resource groups. Also, another difference with the proposal here is that `workspaces()` always return the same result, regardless of the state of the dashboard.

Also note that if we modify the behavior of `ResourceNames` (or any other function), that would be a breaking change since people already using that variable in Azure Monitor metrics may receive a different value.

> Isn't this already addressed with existing ResourceNames template variable that takes arguments for resource group and namespace.

Yes, that point could be addressed mapping back the value used in the argument to the variable that defines it but still I don't think we should go that way because the other issues.

> I don't disagree with the new resource path variable proposal but I'm also interested in the simplest user experience.

I think the UX would be as good as the current one because people would need to use `ResourcePaths(sub, rg, ns)` rather than `ResourceName(sub, rg, ns)`. To be more readable, we can do as the `workspaces()` function that prints in the selector only the workspace names but then, when used, it returns the whole path to the workspace.

**Comment by taleena** [comment]
Am I correct in reading that the proposed fix in #43434 is desired, but that there are some additional concerns regarding a complex behavior?

@kayodeprinceMS - would you agree that we go ahead with the proposed fix (which is better than a crash) and then further discuss the use cases you raise here, and simplifying the experience (which could involve changes in other areas)?

**Comment by andresmgot** [comment]
Thanks for the interest @taleena! Let me try to explain further:

> Am I correct in reading that the proposed fix in #43434 is desired, but that there are some additional concerns regarding a complex behavior?

Not really, there are several points (that are in the comments above) why we shouldn't go with what is proposed in #43434. As a summary, #43434 proposes to modify existing functions with new functionality. This would lead to breaking changes and, potentially, unexpected behaviors. Rather than that, I am proposing to create a new function for the new functionality proposed in #43434. 

> (which is better than a crash)

Note that this is a new feature so, if I am not missing anything, there is no crash atm. Just a proposal to improve the user experience with new functionality.

Hope that helps!

**Comment by taleena** [comment]
Ah ha. It wasn't clear that the one route would introduce breaking changes. Thank you for the clarity.

**Comment by kayodeprinceMS** [comment]
> I think the UX would be as good as the current one because people would need to use ResourcePaths(sub, rg, ns) rather than ResourceName(sub, rg, ns). To be more readable, we can do as the workspaces() function that prints in the selector only the workspace names but then, when used, it returns the whole path to the workspace.

@andresmgot  To identify the same resource, the editor of the dashboard would need to use two different template variables, ResourceName for metrics and ResourcePaths for logs. There would need to be additional doc and guidance to support different use-cases for different variables. More importantly, the user of a dashboard that uses logs and metrics panels for the same resource would now be presented with two different variable selector dropdowns where the same resource would need to be selected.

**Comment by andresmgot** [comment]
Yes, it's probably better to print the whole path when using `ResourcePaths` so the difference with `ResourceName` is clear. 

> There would need to be additional doc and guidance to support different use-cases for different variables

We would need to document the new behavior of `ResourceName` anyway. In my opinion, it's easier to reason (and document) about two different variables, that do different things that one variable that behaves differently depending on where it's used.

> More importantly, the user of a dashboard that uses logs and metrics panels for the same resource would now be presented with two different variable selector dropdowns where the same resource would need to be selected.

That's also why I suggested ([as option 1 in this comment](https://github.com/grafana/grafana/issues/43618#issuecomment-1008949716)) to be able to use different variables for the resource picker but that'd be a more complex task.

**Comment by kayodeprinceMS** [comment]
> For this use case, the new function should suffice.
How would the new function and different variable work here? As I understand it, the user would still need to select the same resource from two different variables dropdowns for metrics and logs panels to be populated.

**Comment by kayodeprinceMS** [comment]
>  In my opinion, it's easier to reason (and document) about two different variables, that do different things that one variable that behaves differently depending on where it's used.

I think one type of variable that works for both metrics and logs resource selection is also a reasonable approach. The editor of the dashboard only needs to consider and query for the resource once, and not a second time depending on whether logs or metrics are needed. For example, I use one variable to query for the resource of interest once and can use it for both metrics and logs panels for that resource.

**Comment by jcolladokuri** [comment]
@andresmgot Sorry if I am missing something here. I don't think I fully understand how it is that #43434 would introduce breaking changes. Mostly because I am not modifying any of the Azure Monitor template variables functions directly. The change occurs on the interpolateVariables function.

Additionally, this change also does not affect any other Azure Monitor service, so if a resource variable were to be selected in another panel with a metrics query, the variable should be replaced as expected (i.e. the name and not the path).

Finally, regarding the concern where the same resource name could exist under different resource groups, I believe that this would not be an issue since the full path (including subscription and resource group) will point to the right resource. Given that at least the resource group and namespace must be used to query for resource names.

**Comment by andresmgot** [comment]
> @andresmgot Sorry if I am missing something here. I don't think I fully understand how it is that #43434 would introduce breaking changes. Mostly because I am not modifying any of the Azure Monitor template variables functions directly. The change occurs on the interpolateVariables function.

Even if the change only applies to Azure Monitor Logs, people are still able to edit the dashboard JSON and use variables there (even if that's not possible through the UI). Something like `            "resource": "/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.Compute/virtualMachines/$resource_name",`.

We would be introducing a change in the behavior of current functionality, so that's a breaking change (even most of people won't hit it).

> Finally, regarding the concern where the same resource name could exist under different resource groups, I believe that this would not be an issue since the full path (including subscription and resource group) will point to the right resource. Given that at least the resource group and namespace must be used to query for resource names.

Yes, that's correct, mentioned that [in this comment](https://github.com/grafana/grafana/issues/43618#issuecomment-1017349453). It also true that the implementation relies in the resource group, namespace, etc. stored in the `grafanaTemplateVariableFn`, which could be removed in the future.

Let me reiterate that my main concern about the suggestion in #43434 is that we would be giving a new behavior to a template variable based on where this variable is used. This adds more complexity to an already cumbersome code base. Keeping it simple, a function `ResourceNames()` should return resource names, not paths. If we need a function to get paths, this should be handled by a new function.

The current behavior of the `workspaces()` function is something that we should avoid.

**Comment by taleena** [comment]
Linking this PR: https://github.com/grafana/grafana/pull/40841
