### ISSUE TITLE
Research/POC for ability to customize navbar

### ISSUE THREAD

**Issue by amy-super** [grafana/grafana#43822]
ok current thinking following torkel's comments:

Note: let's put all this work behind the `newNavigation` feature toggle

# Focusing on pinned/unpinned first

- [ ] (research spike) figure out how to store this information in a db (this is the bit with the most unknown for me)
  - for a PoC, could probably just hook into some other db as a hack for now (preferences?)
  - modify existing bootData to include pinned status
    - call db to get nav preferences
    - merge into existing getNavTree function
- [ ] add a new API to manage NavBar settings (pinned/unpinned):
  - [ ] add a new update route (POST/PUT?) to `/api/navbar` to update the navbar (e.g. when a new app plugin is added, when something is pinned/unpinned)
    - **structure tbd**.
    - do we want to just POST an update to `/api/navbar`?
    - do we want to PUT an individual update to `/api/navbar/{id}`?
  - [ ] (maybe) add a new DELETE route to `/api/navbar/{id}` to remove an item from the navbar settings (e.g. when an app plugin is uninstalled)
    - the main question is **how do we manage uninstalling an app plugin?** we might not need a DELETE route for this
  - [ ] (maybe) add a new GET API (something like `/api/navbar`?)
    - doesn't look like the frontend will use this at all, but might be useful to have the full RESTful actions
- [ ] refactor existing navbar/navbarnext to use the navModel stored in redux state (`navIndex`) (this doesn't need to be behind the feature toggle)
- [ ] add the ability to pin/unpin in the frontend
  - create new redux actions
  - these actions can use localStorage initially (eventually the POST api)
  - this can be hacky initially - let's use a switch in the megamenu for now?
- [ ] Add event tracking for feature usage (Rudderstack) (talk to zsofia re: which events to track)

# Extend to reordering

- [ ] modify existing bootData to include nav position
  - call db to get nav preferences
  - merge into existing getNavTree function
- [ ] update API to handle reordering
- [ ] add the ability to drag/drop to reorder in the frontend.
  - create new redux actions
  - these actions can use localStorage initially (eventually the POST api)

## questions
- what do we do about sections when reordering?

**Comment by ashharrison90** [comment]
current thinking:
- [ ] convert `navTree` to an API:
  - [ ] add a new GET API call to get the `navTree` (something like `/api/navtree`?) instead of adding it to `window.grafanaBootData`
    - this is probably something we should have done a while ago.
    - allows us to then use this API route to POST updates to later (e.g. when pinning/unpinning, reordering)
  - [ ] add a new update route (POST/PUT) to `/api/navtree` to update the navtree (e.g. when a new app plugin is added)
    - structure tbd.
      - do we want to just POST an update to `/api/navtree`?
      - do we want to PUT an individual update to `/api/navtree/{id}`?
  - [ ] add a new DELETE route to `/api/navtree/{id}` to delete an item in the navtree (e.g. when an app plugin is uninstalled)
  - [ ] update the frontend to use this new api
- [ ] figure out how to store this information in a db (this is the bit with the most unknown for me)
  - currently it's created at start up time and stored in `window.grafanaBootData.navTree`
  - for a PoC, could probably just hook into some other db as a hack for now (preferences?)
- [ ] add a new attribute to `NavLink` to indicate whether to show it in the navbar (`showInNavBar`?)
  - there's already a `sortWeight` attribute we can probably reuse/rename for ordering
- [ ] add the ability to pin/unpin in the frontend
  - this can be hacky initially - let's use a switch in the megamenu for now?
  - will utilise the POST api we created in a previous step
- [ ] add the ability to drag/drop to reorder in the frontend.
  - will utilise the POST api we created in a previous step

first checkbox is kind of technical debt we should do no matter what.
second checkbox is where we really need to do some technical research.
remaining checkboxes are basically just **the work**. 😂 

there's also a bit of an unknown of how we support user/admin/org level preferences of these things. haven't really thought about that yet.

wdyt @axelavargas @hugohaggmark ? 🤔

**Comment by torkelo** [comment]
> add a new GET API call to get the navTree (something like /api/navtree?) instead of adding it to window.grafanaBootData

why? bootdata is very important to speed up initial load/render, we want minimize network requests to render initial view. Having an API to reload the in-browser nav state state feels like a good idea (like we have an `/api/frontendsettings` that returns all the frontend settings that is also part of boot data. 

>  add a new update route (POST/PUT) to /api/navtree to update the navtree (e.g. when a new app plugin is added)

Is it not easier to have the navtreee built dynamically, (ie check what plugins are installed when it's generated)? Seems very complex to store nav tree and manage it as a separate list of entities that needs to be in sync with other things. But we do need some storage to pin dashboards, folders etc to the menu and control order. But having the frontend call an API when enabling an app to add it to the menu feels brittle, many provision apps or automate this via API, so then users will have to also add logic to call this API to add it to the menu. Tricky 🤔 

> add the ability to drag/drop to reorder in the frontend.

This feels like it will need some "menu edit mode", having drag and drop enabled at all times on menu items is not something I have seen before and feels like it will cause issues.

**Comment by torkelo** [comment]
A design doc for this feature would be good

**Comment by amy-super** [comment]
> This feels like it will need some "menu edit mode", having drag and drop enabled at all times on menu items is not something I have seen before and feels like it will cause issues.


Agree, right now we are thinking a drag/drop would be after a user has enabled editing in some way. We are also evaluating a simpler pin/unpin pattern but that won't allow for reordering as easily, which is something we've heard that would be helpful. Hopefully bringing design ideas to UX Feedback Session in the next couple of weeks.

**Comment by ashharrison90** [comment]
> why? bootdata is very important to speed up initial load/render, we want minimize network requests to render initial view. Having an API to reload the in-browser nav state state feels like a good idea (like we have an `/api/frontendsettings` that returns all the frontend settings that is also part of boot data.
>
> Is it not easier to have the navtreee built dynamically, (ie check what plugins are installed when it's generated)? Seems very complex to store nav tree and manage it as a separate list of entities that needs to be in sync with other things. But we do need some storage to pin dashboards, folders etc to the menu and control order. But having the frontend call an API when enabling an app to add it to the menu feels brittle, many provision apps or automate this via API, so then users will have to also add logic to call this API to add it to the menu. Tricky 🤔

yeah that probably does make things simpler. 🙌  so just having an api that stores the pinned/unpinned state + position for each item in the navtree.

> This feels like it will need some "menu edit mode", having drag and drop enabled at all times on menu items is not something I have seen before and feels like it will cause issues.

idk where i stand on this. on the one hand, i think it's probably a good idea to have a toggle to enable editing of the navbar since it's usually bad practice to make something clickable and draggable. on the other hand, it's a pretty common pattern for OS taskbars. mac/windows does this, pretty sure ubuntu does as well? 🤔 

> A design doc for this feature would be good

there's a design doc i started last year [here](https://docs.google.com/document/d/1Zh8hufGpERiZs2vYW4hj0n-794WuOukdKGDsL5Y9jek/edit#heading=h.t7gn8ijy9fiw) - i'll update it with this new proposal. 👌

**Comment by ashharrison90** [comment]
ok current thinking following torkel's comments:
- [ ] add a new API to manage NavBar settings (pinned/unpinned + position):
  - [ ] add a new GET API (something like `/api/navbar`?)
  - [ ] add a new update route (POST/PUT?) to `/api/navbar` to update the navbar (e.g. when a new app plugin is added, when something is pinned/unpinned/reordered)
    - structure tbd.
    - do we want to just POST an update to `/api/navbar`?
    - do we want to PUT an individual update to `/api/navbar/{id}`?
  - [ ] add a new DELETE route to `/api/navbar/{id}` to remove an item from the navbar settings (e.g. when an app plugin is uninstalled)
- [ ] figure out how to store this information in a db (this is the bit with the most unknown for me)
  - for a PoC, could probably just hook into some other db as a hack for now (preferences?)
- [ ] add the ability to pin/unpin in the frontend
  - this can be hacky initially - let's use a switch in the megamenu for now?
  - will utilise the POST api we created in a previous step
- [ ] add the ability to drag/drop to reorder in the frontend.
  - will utilise the POST api we created in a previous step

**Comment by axelavargas** [comment]
##  After User Research:

### Approach Changed(Behind feature toggle):

Instead of offering the ability to `pin/unpin`  items in the navbar, we are moving towards

- In the mega menu we will be adding a new section of `Saved Items`
- Having a mega menu with collapsible sections
	- Each section item will NOT contain icons
	- On hovering each item it will be possible to `save/bookmark` the item into the saved items
	- When clicking any saved item the active state should belong to the parent section of the item, not to the saved items 
	- An item that is `saved` can also be `unsaved` from the `saved Items` section and the parent section of the item.
- Keeping the current navbar with all the items but adding a scroll mechanism when items overflow
- Initially reordering is not going to be possible inside the the `saved Items`
- A persisted state is desirable when collapsing or uncollapsing sections in the mega menu
- Old prototype of the navbar should remove the visual sections(logo, core, plugins, etc), but should keep the home and + button changes

### Changes we need to make

- [ ] Clean up the old prototype of the navbar to remove the visual sections (keep the changes related to the home logo and remove the + button)
- [ ] Update [Navigation: Store pinned status in a db #44376](https://github.com/grafana/grafana/issues/44376) to support new approach
- [ ] {ANYTHING ELSE?}

**Comment by axelavargas** [comment]
Closing it in favor of https://github.com/grafana/grafana/issues/46354
