### ISSUE TITLE
Please list Azure Monitor logs as a supported data source on Grafana Logs documentation

### ISSUE THREAD

**Issue by mitulk** [grafana/grafana#43868]
**What happened**:
 https://grafana.com/docs/grafana/latest/explore/logs-integration/ doesn't list Azure Monitor Logs as supported

**What you expected to happen**:
https://grafana.com/docs/grafana/latest/explore/logs-integration/ lists Azure Monitor Logs as supported

**Comment by andresmgot** [comment]
Hi @mitulk,

Right now, Azure Monitor Logs queries are not formatted to be used as "logs" that can be consumed by Grafana. The supported formats at the moment are "Table" and "Time series":

![Screenshot from 2022-01-14 15-47-34](https://user-images.githubusercontent.com/4025665/149534714-7f7dbed7-a9be-4bb6-8456-91ce1338ba24.png)

In order to be able to format frames as Logs we would need to add support for it, that's a different feature request though.

Note that you can still use the Logs visualization in a normal dashboard panel and it will work with the Table format as long as the table contains at least a string but no further formatting will be applied.

Can you create a feature request so we can track that differently? Let me close this issue because we cannot list Azure Monitor Logs in that until it has support for log frames.

Thanks.
