### ISSUE TITLE
[Bug] OpenTSDB templating - Use auto complete on query metric field

### ISSUE THREAD

**Issue by vitorboschi** [grafana/grafana#4388]
Just as the title says, it'd be great if that field have auto complete, like the metric ones in Grafana

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
