### ISSUE TITLE
Inconsistency in alert rule quotas between Legacy and NG alerting (blocked: spec for exceeded quota)

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#43938]
**What happened**:

In the Grafana config, there are options for configuring quotas on the number of alert rules (`org_alert_rule` and `global_alert_rule`). The API will reject any newly created org rules once the quota is met, unless rules are deleted.

However, Legacy alerting did not have such a quota. The quotas are specific to `ngalerts` only: #33283

The migration correctly moves legacy alerts as expected, but it not obvious that quotas are a thing after migrating. So, it's easy for a user with lots of rules to get confused after migrating, as they can no longer create any additional rules, and there is nothing to say why.

**What you expected to happen**:

There are a couple possible solutions that we should pick between.
1. Have the migration check the alert quota before running. If the migration would exceed the quota, stop, and tell the user to raise the quota.
2. Similar to 1, but don't stop the migration. Instead, emit warnings.
3. Have some sort of indicator in the UI that there is a quota. For instance, in the page which lists alert rules, have a counter with the quota shown, i.e. some text saying something like `3169/2000 alert rules`
4. If the user somehow exceeded the quota (most likely, due to this issue) show a banner in the UI with some specific instructions telling the user about the state they're in.

**How to reproduce it (as minimally and precisely as possible)**:

1. Enable legacy alerting.
2. Create many alert rules, exceeding the quota.
3. Migrate to ngalerting.
4. No feedback that we're in a broken state.
5. Create a new alert rule. It's rejected due to quotas, but there's no way to tell what this mysterious quota is or where it came from.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: N/A
- OS Grafana is installed on: Linux
- User OS & Browser: Linux, Firefox 95.0.2
- Grafana plugins: N/A
- Others: N/A

**Comment by gillesdemey** [comment]
> Have some sort of indicator in the UI that there is a quota. 
Is there an API endpoint where we can retrieve the configured quotas?

**Comment by joeblubaugh** [comment]
I think we should never fail a migration for this reason. End-users can re-configure their system after migration to add more quota, and if their instance was humming along with X alert rules, X alert rules should still work OK, since they won't suddenly become multidimensional.

I'd vote for implementing 3 with a twist: Make sure the value is *extremely visible* when over quota. You can read and write quotas via an HTTP API, so actually fetching it for display isn't the tricky part. I think the UX of explaining the various configurations of quota limits is the hard bit. We don't have documentation online about quota that I could find, but we could add some ? hover text that explains something about changing the quota. Quota can be disabled, and set per-org, per-user, and per-host, so it could be a little tricky to explain in the UI when there are multiple quotas interacting.

If implementing 4, if we make the error response from the alert creation API verbose enough, we could display an "Over Quota" message.  That would be simpler than trying to load the correct quota based on the org, user, or instance and the interaction between those.

**Comment by jessover9000** [comment]
I have some questions: 

- Why do users care about quotas and about which part? Is this a limitation that we need from the implementation side or is it somehow useful for users to have this limit? 
- If users are over quota and have a system of thousands of alerts/instances, how do we (or the user) make fast and informed choices in which alerts we enable/disable or how the user should slim down their interface?
- Who do we assume will be affected by this / can we predict how many % of users might have this problem? I know that lots of users will have many alert rules that needed to be separate in panels due to the way Legacy Alerting worked, but now could be resolved into one alert rule with multiple instances. Are we somehow accounting for that during the migration?

**Comment by jtheory** [comment]
For 1) this is the only doc I found covering alert rule quotas: https://grafana.com/docs/grafana/latest/administration/configuration/#global_alert_rule -- it doesn't mention if this applies to legacy or only Unified Alerting. (I'm guessing it doesn't apply to legacy... because we have this problem)

2) looks like a hard & complex problem... it feels much safer if we can avoid going over quota. I guess that'd mean rejecting migration if the quota is too low (fix: raise the quota & retry), plus rejecting a new quota level that's > current alert count.

**Comment by jessover9000** [comment]
How could we get clear answers to these questions? @devinrcheevers can you help us with this, or who can we reach out to to learn more?

I do agree with @jtheory that there is no good solution for 2. except for rejecting quota levels that would lead to conflicts. But we need to have very foolproof tutorials/guidance around overcoming those rejections. Also maybe 3. can be resolved by telling people how they can combine/merge similar alerts. @armandgrillet and @yuri-tceretian (I think it was you Yuri who is working on migration? Sorry if I tagged you wrong) do we have any plans for reducing toil and automating away migration pains for on-prem users with similar panels that could be grouped into one Unified Alerting alert rule?

**Comment by joeblubaugh** [comment]
> I have some questions:

These are all answers from my perspective as a long-time user of various alerting systems, not necessarily Grafana product opinions.

> 1. Why do users care about quotas and about which part? Is this a limitation that we need from the implementation side or is it somehow useful for users to have this limit?

Quotas are useful for administrators - evaluating alert rules is the most resource-hungry part of the grafana backend, and also adds load to the datasources it queries. Admins can use it to keep the instance healthy by limiting the CPU and RAM consumed by alert rule evaluation. The default quota of 100 seems quite low, though quotas are also disabled by default. It's not something we need from an implementation standpoint.

> 2. If users are over quota and have a system of thousands of alerts/instances, how do we (or the user) make fast and informed choices in which alerts we enable/disable or how the user should slim down their interface?

Right now there's zero feedback about this. If I *know* I'm over quota there are some things I'd look for as an end-user:
1. Are there rules that I know are lower priority? Maybe I have an "environment=dev" label or similar. I can find rules that match that label using the Alert Rules page.
2. Are there rules that haven't fired in a long time? I can't find this out right now, but we could build features that allow us to.
3. Are there rules with no attached notification policy? Those are good candidates for deletion.
4. Are there rules created by hand, when I also use the provisioning API? In tightly-controlled organizations, non-provisioned dashboards or alert rules are first on the chopping block.

> 3. Who do we assume will be affected by this / can we predict how many % of users might have this problem? I know that lots of users will have many alert rules that needed to be separate in panels due to the way Legacy Alerting worked, but now could be resolved into one alert rule with multiple instances. Are we somehow accounting for that during the migration?

Users who explicitly enable quotas in unified alerting, or (maybe) use Grafana Cloud may encounter this problem.
No, we don't automatically simplify alert rules that could be collapsed into one.

There's a more general problem pointed to by this issue - if a quota is set, creating an alert rule can fail and users have zero feedback about why. Any in-app or API feedback that's useful in the migration case will also be useful in day-to-day operations if:
1. An admin decreases quota below the existing # of alerting rules.
2. Quota is totally consumed.
3. Automated Provisioning attempts to create more rules than quota allows for.

**Comment by jessover9000** [comment]
Thanks @joeblubaugh , this is super helpful! 

@achatterjee-grafana The tips about point 2 that Joe listed could be helpful als part of a migration troubleshooting guide, don't you think? Do we collect information about migration troubleshooting and possible solutions anywhere that I could add these points to?

Regarding in-app or API feedback, I would like to talk to engineers working on the migration to learn how we currently provide in-app feedback about migration-related stuff and then I can help with a feedback flowchart (If X happens, show Y feedback) and the text snippets for that :)

**Comment by jtheory** [comment]
Research from @papagian : :trophy: 

in the backend is called when:
[saving a dashboard](https://github.com/grafana/grafana/blob/acd31ae9f0f9627ccd2d928ea893ca211aeba4d4/pkg/api/dashboard.go#L332)
[creating a new user](https://github.com/grafana/grafana/blob/acd31ae9f0f9627ccd2d928ea893ca211aeba4d4/pkg/services/login/loginservice/loginservice.go#L59)
and as [a middleware handler](https://github.com/grafana/grafana/blob/acd31ae9f0f9627ccd2d928ea893ca211aeba4d4/pkg/middleware/quota.go#L12) in a number of places:
https://github.com/grafana/grafana/blob/acd31ae9f0f9627ccd2d928ea893ca211aeba4d4/pkg/api/api.go#L43
https://github.com/grafana/grafana/blob/acd31ae9f0f9627ccd2d928ea893ca211aeba4d4/pkg/api/api.go#L44
https://github.com/grafana/grafana/blob/acd31ae9f0f9627ccd2d928ea893ca211aeba4d4/pkg/api/api.go#L121
https://github.com/grafana/grafana/blob/acd31ae9f0f9627ccd2d928ea893ca211aeba4d4/pkg/api/api.go#L140
https://github.com/grafana/grafana/blob/acd31ae9f0f9627ccd2d928ea893ca211aeba4d4/pkg/api/api.go#L235
https://github.com/grafana/grafana/blob/acd31ae9f0f9627ccd2d928ea893ca211aeba4d4/pkg/api/api.go#L241
https://github.com/grafana/grafana/blob/acd31ae9f0f9627ccd2d928ea893ca211aeba4d4/pkg/api/api.go#L268
https://github.com/grafana/grafana/blob/acd31ae9f0f9627ccd2d928ea893ca211aeba4d4/pkg/api/api.go#L298
https://github.com/grafana/grafana/blob/acd31ae9f0f9627ccd2d928ea893ca211aeba4d4/pkg/api/api.go#L307

**Comment by jtheory** [comment]
[UX review 2022-05-18](https://docs.google.com/document/d/1m2yciWfQa-rp-KLUrMLYOge00GAd8bLPzmDtDwDFt0o/edit#heading=h.2wxesbqw7xlr); summary:

Decision we have to make before finalizing UI: 
* What happens if provisioning exceeds a quota?  Kill startup/provisioning, or allow it (and advertise the exceeded quota in this UI only)?

Looking for similar patterns:
* We have ingestion limits in Grafana cloud but I don’t know how we tell people about it
* look at free trial banners in Cloud – “try the enterprise plugin” banner that says “You’re getting close to the limit” -- this may be unhelpful if the current user isn't able to increase the limit. Anja P worked on this from the UX team.
* The free level in G Cloud uses quotas; they're shown in the Cloud homepage (...so maybe we have some UI already, if this also shows alert quotas? but it's not near the functionality)

Solution ideas:
* Grey out the New Alert button - must also give clear feedback on why, **how much** over, and the ways to fix it
* Could also add a notification... we'll be establishing a pattern, here
* Can we link to the stats & licenses page, for GCloud? Problem: that's good for GCloud, not for Enterprise, so we'd have to know which we're in
* Some Legacy -> UA migrations will be over limit just because we do a simple migration... can we have a migration help page that explains how to convert many similar legacy rules -> multi-dimensional UA rules? Possibility also to build automation (if this is a serious need with bigger-scale customers)

**Comment by jessover9000** [comment]
Regarding solution UI feedback, I think I need to know how we're handling the "quota exceeded" state. Do we

- just tell people that they're over quota but not do anything about it automatically, tell people that it could cause performance problems and they should run some tests, change their quota or delete some alerts?
- test for performance problems automatically ourselves and if there's none, just give people a dismissable infobox and if there's problems do a big non-dismissable warning?
- disable some stuff, like creation of new alerts, until people go under quota again?
- stop the migration entirely?

Also I don't know what options users have. Can they manually increase the quota to keep their alerts in case there's no expensive, high-performant querying going on? Or do they just need to slim down their alerting system?

> can we have a migration help page that explains how to convert many similar legacy rules -> multi-dimensional UA rules?

My initial thinking would be to remember how we did our own migration from legacy to unified alerting. Did we have to clean up our duplicate/similar alerts, did we recreate anything from scratch, or was there no need to fix anything? If we cleaned anything up, how did we do it and could we explain it in a blog post or something?

**Comment by jtheory** [comment]
I know these ones, Jess! :) I talked through in detail with @joeblubaugh  :)

When we're "quota exceeded" (which **can** happen in a migration from legacy to unified alerting -- we won't stop the migration):
* we don't take any automated action
* we don't tell users it'll harm performance (we don't actually know that... maybe their quota is just set way too low)
* if we want to help identify performance problems and give advice, that'd be a separate feature from this issue (it's not necessarily a quota problem)
* we **do** block creation of new alert rules, with UI changes (TODO for this issue) and back end (enforced already, I think)
* User options: an admin can increase the alert rule quota, or a user with enough privileges can delete rules.

Helping with cleanup - yep, a blog post or migration guide would be helpful! I can ask around to find out if that needs a new `area/docs` issue.

**Comment by achatterjee-grafana** [comment]
Can users change the quota limit? It is only an issue only if users have a custom limit, as the default is unlimited, correct?

Do we have a decision on what steps the users will take if they exceed the quota? I read we have a few to-do items.

For now, I will create a troubleshooting topic under migration based on some of the conversations here.

**Comment by joeblubaugh** [comment]
The default in Grafana Cloud is not unlimited, which is where we expect to encounter this issue most often. This value *can* be modified by the Grafana teams.

**Comment by gillesdemey** [comment]
Currently setting this to "blocked" because we'll need some sort of API / solution to get this information to the front-end.

**Comment by JacobsonMT** [comment]
Not a direct solution to the problem, but the new recommended method of upgrading to UA with the preview environment (https://github.com/grafana/grafana/pull/80071) is quota-aware. The previewed UA environment should not block migrating legacy alerts when they exceed the quota, but if you are above the quota during the preview you will not be able to create new alerts from scratch. This should at least increase awareness of those migrating to UA.

Banners or quotas on the page in UA could still be useful though.

**Comment by JacobsonMT** [comment]
Closing with the removal of legacy alerting in v11
