### ISSUE TITLE
Broken inline ad-hoc filtering using Elasticsearch with Table Panels

### ISSUE THREAD

**Issue by haelekuin** [grafana/grafana#43975]
**What happened**:
Updating existing and creating new table panels breaks the inline ad-hoc filtering functionality in Elasticsearch. After looking through the panel JSON, it seems like the datasource type and uid are not updated correctly.
I was unable to replicate this issue with datasources that were not the default.

**What you expected to happen**:
In-line filtering still works after updating the panel.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a table panel
2. Group by Terms
3. Try to filter for/our value

**Anything else we need to know?**:

Old, functioning panel:
```
      "query": "redacted",
      "refId": "A",
      "timeField": "created_at"
    }
  ],
  "datasource": {
    "type": "elasticsearch",
    "uid": "000000002"
  }
}
```

New, broken panel:
```
      "query": "redacted",
      "refId": "A",
      "timeField": "created_at",
      "datasource": {
        "type": "elasticsearch",
        "uid": "000000002"
      }
    }
  ],
  "datasource": null
```

**Environment**:
- Grafana version: 8.3.2 OSS
- Data source: Elasticsearch

**Comment by mckn** [comment]
When trying to reproduce this issue I can't change default database in my local Grafana instance. Since this error only occur when you are trying to apply an ad-hoc filter in a table panel where you are using the default database I am guessing we have managed to introduce a bug during the datasource reference work a while back.

**Comment by joshhunt** [comment]
Was able to reproduce this, and confirm it only happens when using a default data source. I'm not too familiar with adhoc variables, so will have to pull in some help to look into this 👍🏻 

@haelekuin Have you noticed whether this happens with other data sources (Prometheus, Loki, or InfluxDB) that are set to the default data source?

**Comment by haelekuin** [comment]
I was unable to reproduce the issue with Prometheus set as a default data source. I'm inclined to believe it only happens with Elasticsearch, but we don't have InfluxDB or Loki set up, so I can't say for sure.
