### ISSUE TITLE
Copy URL not working in Panel Share dialogue

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#44110]
**What happened**:
I pressed the Copy URL button in the Panel Share dialogue, but the URL did not copy.

![ezgif-5-9cb3c467e5](https://user-images.githubusercontent.com/3848559/149785849-9d2c6567-2ae3-48eb-bf87-8a6bd09f08cb.gif)

**What you expected to happen**:
Expected the URL to be copied into my clipboard, so I could paste it elsewhere

**How to reproduce it (as minimally and precisely as possible)**:
From a dashboard, click into the context menu for a panel and choose Share
Press the Copy button
Try to paste in another window

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.0 pre-release
- Data source type & version: N/A
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Mac OS Catalina 10.15.7, Chrome Version 97.0.4692.71

**Comment by belm0** [comment]
useful info from the summarily closed duplicate bug:

> I could not reproduce it at play.grafana.org (v8.4.0-beta1). However, no bug fix was mentioned in the 8.4.0 changelog. If it was fixed, it should be noted, and backported to v8.3.

**Comment by ashharrison90** [comment]
hi everyone 👋 

thanks for raising this. this has been fixed by https://github.com/grafana/grafana/pull/42996 which has been released in grafana 8.4.0-beta1 and will also be included in the upcoming 8.4.0 release.

if you're still seeing problems on versions after that feel free to add a comment or raise a new issue for us to investigate.

thanks! 😄

**Comment by belm0** [comment]
>  this has been fixed by #42996 which has been released in grafana 8.4.0-beta1 and will also be included in the upcoming 8.4.0 release.

It looks like a big change-- I don't suppose it could be backported to 8.3?

**Comment by ashharrison90** [comment]
@belm0 i'm not sure if there's a plan to release any more 8.3.x versions or if they're now just reserved for security fixes.

upgrading to 8.4.0 when it's released is probably your best bet. hope that makes sense! 👍

**Comment by belm0** [comment]
Unfortunately, this leaves us wedged, and high chance of miscommunication in our organization due to sharing the wrong link.
  1. v8.2 was working fine
  2. v8.3 has copy link bug
  3. we can't downgrade to v8.2 without headaches with alert migration (https://github.com/grafana/grafana/blob/main/CHANGELOG.md#breaking-changes)
  4. we can't upgrade to v8.4.0-beta1 due to metrics lookup performance issue, and bug in disable-lookup option(I'll file bug shortly)
