### ISSUE TITLE
[Feature Request] Datasource backend queries should be retriable

### ISSUE THREAD

**Issue by amuraru** [grafana/grafana#4413]
- What grafana version are you using? 2.6
- What datasource are you using? Graphite
- What OS are you running grafana on? Linux

Sometimes the datasource backend (in our case Graphite) may time out but subsequent request can succeed.
Grafana should have an option (globally or per datasource) to configure `retry`.

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
