### ISSUE TITLE
global_session quota fails with auth.proxy auto_sign_up

### ISSUE THREAD

**Issue by rayprill** [grafana/grafana#4419]
Version v 2.5.0-pre1

I have enabled quotas and set global_session = 1.  I am also using auth.proxy with auto_sign_up.

In this mode, I can go beyond the global_session limit of 1.  I currently have 3 sessions and 3 users running.  Perhaps I am missing a setting?

The limits seem to work with local basic authentication.

**Comment by marefr** [comment]
We've replaced the old session implementation with a short-lived token solution, see https://grafana.com/docs/grafana/latest/auth/grafana/#login-and-short-lived-tokens. The session quotas should now apply to how many active tokens there are in the system. This issue is very old and doesn't feel related to latest versions due to the changes so I'll close it. This doesn't mean we can reopen should you still have the same problem on latest version.
