### ISSUE TITLE
Question: https configuration

### ISSUE THREAD

**Issue by msmagoo60** [grafana/grafana#4437]
Hello,

I am using grafana version 2.6.0 on Ubuntu 12.04. We have been running successfully for quite some time, however we have decided to switch to https. In doing so, I have ran in to a few issues. Mainly, when accessed via old bookmarks with regular http, rather than redirecting to the https version of the page, it downloads a file on the user's desktop.

Ex: https://dns.com:3000 loads grafana as expected. http://dns.com:3000 downloads a file named "download". If I try to load a specific dashboard like http://dns.com:3000/dashboard/db/test-dashboard then it will download a file called "test-dashboard".

Any help here would be appreciated!
Thanks,
M

**Comment by calebcall** [comment]
I'd put apache in front of it.  However, since you're running on port 3000, you'd have to change the port grafana is running on, then have apache listen to port 3000.  Have the rewrite do anything non-ssl to ssl and the proxy pass that to the new grafana port.  Seamless to the end user, forces ssl, and gives an added layer of flexibility/security.

**Comment by torkelo** [comment]
using https on port 3000 (custom https port) and expect browser to work when issuing non https query is not possible.
