### ISSUE TITLE
Auth proxy to support non-ASCII characters

### ISSUE THREAD

**Issue by yuwaMSFT2** [grafana/grafana#44744]
**What happened**:
User email and names may have non-ASCII characters. Since auth proxy uses HTTP headers to pass the user information, there is no good way to pass the correct non-ASCII characters.

**What you expected to happen**:
Find a way to pass non-ASCII characters (maybe encoded) in auth proxy, and Grafana can store and display it correctly (maybe decoded first)

**How to reproduce it (as minimally and precisely as possible)**:
When using auth proxy as auth provider, try to pass non-ASCII user name

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by yuwaMSFT2** [comment]
@daniellee @jongyllen

**Comment by kostrse** [comment]
The following choices should be made:
1. Which encoding format to use.
2. Should we treat all header values as encoded by default or should we attempt decoding only if a special flag/signature is present. This is important for backwards compatibility if backwards compatibility is a concern.

I would want to give a few options for consideration.

### Encoding formats

#### 1. URL encoding (as in query strings)

```
X-WEBAUTH-USER: M%C3%BCnchen
X-WEBAUTH-EMAIL: m%C3%BCnchen%40%E5%85%AC%E5%8F%B8.com
X-WEBAUTH-ROLE: %CE%94%CE%B9%CE%B1%CF%87%CE%B5%CE%B9%CF%81%CE%B9%CF%83%CF%84%CE%AE%CF%82
```

A problem with URL encoding is that it treats many commonly used characters as special (`+`, `%`, `@`, `&`, etc.). A valid unencoded ASCII  string may contain some control characters, as result to avoid ambiguous interpretation, both sending and receiving parties should be aware of the encoding and should use it on both ends.

Explicit configuration setting should be introduced to provide backwards-compatibility for senders which do not encode.

#### 2. Unicode escape sequences

The encoding which is used in JSON.

```
X-WEBAUTH-USER: M\u00fcnchen
X-WEBAUTH-EMAIL: m\u00fcnchen@\u516c\u53f8.com
X-WEBAUTH-ROLE: \u0394\u03b9\u03b1\u03c7\u03b5\u03b9\u03c1\u03b9\u03c3\u03c4\u03ae\u03c2
```

A benefit of this encoding is that it only uses the `\u` (`\U`) control sequence which is in practice rarely used other than for the purpose of encoding Unicode characters. It would be safer to introduce this encoding as enabled by default without risking of breaking senders which do not explicitly encode their headers.

#### 3. Quoted-printable encoding

Wikipedia: https://en.wikipedia.org/wiki/Quoted-printable

```
X-WEBAUTH-USER: M=C3=BCnchen
X-WEBAUTH-EMAIL: m=C3=BCnchen@=E5=85=AC=E5=8F=B8.com
X-WEBAUTH-ROLE: =CE=94=CE=B9=CE=B1=CF=87=CE=B5=CE=B9=CF=81=CE=B9=CF=83=CF=84=CE=AE=CF=82
```

Used in mail protocols, was specifically designed to transfer byte streams over a 7-bit ASCII medium.

Similar to format (2) but more verbose because doesn't directly support Unicode characters. It treats the encoded string as a generic byte array (which in turn can represent a UTF-8 string).

### Encoding configuration

#### 1. Encoded by default

While there's no practical scenario when encoding wouldn't be desirable but enabling it by default may lead to problems with backward compatibility.

This is more an issue for encoding (1) but less for encoding (2) and maybe (3)

#### 2. Enabled via settings

It's possible to introduce a configuration setting which would enable encoding support only when explicitly configured.
This would solve potential compatibility issues.

```ini
[auth.proxy]
...
encode_headers = true
```

#### 3. Enabled via special prefix (RFC 5987)

Another option would be to use an optional special prefix in header value which indicates encoding.
[RFC 5987](https://datatracker.ietf.org/doc/html/rfc5987).

```
X-WEBAUTH-USER: utf-8''M%C3%BCnchen
X-WEBAUTH-EMAIL: utf-8''m%C3%BCnchen%40%E5%85%AC%E5%8F%B8.com
```

This RFC was introduced to solve this specific problem of encoding HTTP headers, but it doesn't have widespread practical usage. 


Personally I would go with either (2) or (3) encoding and not opinionated on the configuration mechanism.

**Comment by sdboyer** [comment]
This seems eminently reasonable, and i agree with your take on the need for a config setting. Noting as much over on the PR.

Thanks for putting together such a clear explanation of all this!
