### ISSUE TITLE
Loki Log Volume: Remove `10s` timeout constraint for Log Volume Query 

### ISSUE THREAD

**Issue by kavirajk** [grafana/grafana#44756]
**What happened**:
Based on some of the [user research](https://github.com/grafana/loki/issues/3858#issuecomment-1022281448), Looks like it's confusing to user to have two diffferent timeouts (one for Log Volume section and other for normal queries)

Main confusion is one of the section (Log Volume) shows some error while the actual query is still running.

**What you expected to happen**:

Some consistent timeout for all my Loki queries

**How to reproduce it (as minimally and precisely as possible)**:
Run Grafana8.3 + Loki datasource with config[feature_toggles][enable]=fullRangeLogsVolume

**Anything else we need to know?**:

User who wants to control the timeouts can do it on the Loki side (say Gateway in front of it using `X-Query-Tags` header).

**Environment**:

- Grafana version: 8.3
- Data source type & version: Loki 2.4.2
- OS Grafana is installed on: Linux
- User OS & Browser: Linux & Chrome
- Grafana plugins:
- Others:

**Comment by 09jvilla** [comment]
A little more context here:

Today, Grafana cancels the log volume query after 10s. This was originally instituted as a safety valve for the Loki backend, since there was concern that log volume queries could put excessive strain on Loki. 

However, this has caused some confusion for folks in the open source community because it is not necessarily clear that there is a different timeout for log volume queries than there is for user generated queries. Users see cases where the log volume histogram errors out (due to timeout), but their underlying query is still being executed since the general purpose query timeout set in Loki is significantly longer (it is defaulted to 60s). 

Given this, we'd like to remove Grafana's special case for cancelling log volume queries (originally introduced in this [PR](https://github.com/grafana/grafana/pull/40327)).

What this means:

1. Log volume queries sent by users running OSS Grafana and Loki will not be treated any differently than any other query. Loki will cancel them whenever `query_timeout` seconds have elapsed. Grafana will give up on them after `[timeout](https://grafana.com/docs/grafana/latest/administration/configuration/#timeout)` seconds. 

This results in consistent behavior for log volume queries when compared to other queries, and should eliminate the confusion. 

Should OSS Loki users notice that their cluster is being overwhelmed or falling over due to the log volume queries, we'll provide some docs on how they could set up a custom, shorter cancellation time for log volume queries. But, based on what we're seeing from running this internally, we're not very concerned about this risk. 

2. Log volume queries sent by users on Grafana Cloud Logs will still be cancelled after 10s, but this cancellation is implemented in the cortex-gateway (and therefore the Grafana custom cancellation is not needed). We're keeping the cancellation in place for Grafana Cloud Logs so our SLA is not affected by log volume queries (our SLA is our guarantee that X% of requests will finish within 10s).
