### ISSUE TITLE
Possible bug on frontend displaying data past last 7 days

### ISSUE THREAD

**Issue by colinmcparland** [grafana/grafana#44800]
https://user-images.githubusercontent.com/7502241/152258400-b3d4a00b-7c3c-4555-9609-912e37e32a67.mp4

**What happened**:
Queries not displaying any data for periods > 7d.

**What you expected to happen**:
When selecting a period greater than 7 days, eg. 30 days, I would expect to see points plotted over a 30 day range.

**How to reproduce it (as minimally and precisely as possible)**:
Change time range from 7d to anything longer

**Environment**:
- Grafana version: Grafana v8.3.3 (30bb7a93ca)
- Data source type & version: Graphite 1.1.x
- OS Grafana is installed on: Ubuntu
- User OS & Browser: MacOS 12.0.1, Chrome 98.0.4758.80 (x86_64)
- Grafana plugins: N/A
- Others: N/A

**Comment by zuchka** [comment]
Thanks for creating this issue, @colinmcparland 

Can you help us troubleshoot this a bit more?  Here is a public dashboard on our official sandbox. It is using Graphite and it will resolve time ranges from 1h to 7d+:

https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&editPanel=2

The instance is running Grafana 8.3.5. Do you see anything different between this instance / dashboard / panel and yours? What happens if you switch to the table panel? If you inspect the query after you change the timepicker to `8d`, what does is return, if anything? You can view this by hovering over the panel title, clicking the dropdown, hovering over the `inspect` drawer, and then choosing `query`.

thanks for your help 👍

**Comment by colinmcparland** [comment]
Hi @zuchka thanks for your prompt reply.

> Do you see anything different between this instance / dashboard / panel and yours?

Nothing significant, however I was unable to recreate the bug.

> What happens if you switch to the table panel?

If I start on a 7d view and switch to table panel, I can see the most recent data in the table.  If I go back to the graph, select 30 days, then back to table view, both the graph and the table data are gone.
https://user-images.githubusercontent.com/7502241/152275453-5686d03e-802a-4deb-8fc4-b806e1a09a53.mov

As a side note, I noticed that if I switched the date range in the table view, I was essentially stuck on the previous date range until hitting the refresh button:

https://user-images.githubusercontent.com/7502241/152276824-6e0ddaec-da24-4044-a6a6-63f029857839.mov

>  If you inspect the query after you change the timepicker to 8d, what does is return, if anything?

If I inspect query with 7d I get the data as expected, and when changing to 8d there are rows returned but with no data.  Something I noticed as well is that there were more rows returned for the 7d query.

8d
<img width="711" alt="152276318-4d7cb866-413d-4a31-9fa0-70dd531ef1f7" src="https://user-images.githubusercontent.com/7502241/152276597-e3eefab9-2bd2-457e-8c1a-8d2ad034b31d.png">

7d
<img width="703" alt="152276353-00cbb97a-3ef8-4279-9b16-b64796cf709d" src="https://user-images.githubusercontent.com/7502241/152276606-9e581a41-a1f2-4ff5-9b8a-936e2f1c5fcd.png">

Thanks again for your assistance, and please let me know if I can provide any more info!

**Comment by torkelo** [comment]
This looks like an issue with your data source, it's not returning any values when you increase the time range
