### ISSUE TITLE
[Question] Internet Explorer - Cache Problem

### ISSUE THREAD

**Issue by ahmetkakici** [grafana/grafana#4486]
Hi guys,
I'm using Grafana 2.6.0 on Ubuntu Server and using InfluxDB (v0.9) as datasource.

When i open dashboard from Opera (v36), Chrome (v49) it's refreshing my dashboards with auto-refresh option but whenever i open it from Internet Explorer (v11) it sends request to InfuxDB and IE uses it's cache to response these requests. Below is the output of Internet Explorer's network tab;

**Name** : http://192.168.0.102:8086/query? ....(here goes my query)
**Protocol** : HTTP
**Method**:GET
**Result** :200
**Content type**:application/json
**Received** : _(from cache)_
**Time	Initiator**: 0s

As it says, it always response these request from cache unless i disable cache option of Internet Explorer.

So i'm curious about if there is an option in query builder which adds a timestamp (or any random value) to queries to not hit the cache.

**Comment by torkelo** [comment]
no there is no such option currently.

**Comment by ahmetkakici** [comment]
Thanks for reply but auto-refresh problem is still here.
Is there any workaround for this issue?

**Comment by coussej** [comment]
@torkelo I just encountered the same issue. I noticed that when I opend the developer tools (F12), it suddenly worked. This is because by default, the 'Always refresh from server' option is enabled. When I disable it, the HTTP request looks like the one from @ahmetkakici. When enabled, the header **Cache-Control: no-cache** is added. 

Can grafana add this header by default, for the refresh requests? They should never be loaded from cache, so I see no point in not adding it.
