### ISSUE TITLE
Logarithmic scale rendering

### ISSUE THREAD

**Issue by ralphm** [grafana/grafana#452]
Graphite web has the `logBase` graph parameter for rendering the graph such that the Y-axis is in log scale. This is especially useful for timing diagrams that show minimum, mean, max and certain percentiles.

It would be great to have a similar feature in the Axis & Grid tab.

Note that this feature is different from #100, which implemented the `log` *function* that transforms values, as opposed to the graph.

**Comment by jdanbrown** [comment]
+1 A log-scale y axis is critical for any kind of long-tailed distribution like latency metrics. We use log scale heavily with our current graphite png dashboards, which we'd love to replace with grafana to get better interactivity.

**Comment by krzyk** [comment]
:+1:

**Comment by inthecloud247** [comment]
:+1:

**Comment by simple10** [comment]
+1

**Comment by esoel** [comment]
👍

**Comment by torkelo** [comment]
Worked on a very basic inital log 10 based scale. with y-axis steps that start with 0, 1, then 10, 100 etc depending on grid max or max of all series on the axis. 

Useful for timing / latency data. 
![logscale](https://cloud.githubusercontent.com/assets/10999/6721117/17487950-cda0-11e4-9341-0849541fe6fb.gif)

How important is it for control over y-axis ticks (to have more steps between 0 and 1), also it is technically possible to have ticks at non powers of 10 (they will just not be evenly spaced), is this useful? Are other log bases important (like log e) ?

**Comment by jdanbrown** [comment]
@torkelo Looks great! Can't wait to try this out.

I'm not OP, but here are my thoughts in case they're helpful:

- Note that log(x) in (0,1) means that x < 0, so in many cases the user will want y to start at 1, not 0. Maybe best to surface an option for it. (Note that log(x) is always positive, so y=0 won't ever actually happen.)

- Two most useful cases in my experience with system metrics: log base 10 with ticks at powers of 10 (e.g. latency), and log base 2 with ticks at powers of 2 (e.g. bytes). Ticks are maybe best determined by the log base and y range, e.g. uniformly divide the visual y range into K ticks. Not sure if log base e is ever useful quantitatively, even though it's almost always useful analytically.

And here are a few examples from graphite for inspiration:
- http://graphite.readthedocs.org/en/0.9.12/render_api.html
- `logBase=10` includes the minor grid lines, which are super helpful in understanding the nonlinear y values
- `yUnitSystem=binary` is nice for byte-valued graphs, but is also easy to live without
- `logBase=1024` would work better if graphite knew unit names beyond `Gi` ;)
- `logBase=1024` also wants more minor grid lines, to make the log y scale easier to read
- `logBase=2` works poorly because it tries to label every power of 2

`logBase=10`:

![render](https://cloud.githubusercontent.com/assets/627486/6721454/77f11458-cd8a-11e4-95f1-9d40c9b629ad.png)

`logBase=1024&yUnitSystem=binary`:

![render-3](https://cloud.githubusercontent.com/assets/627486/6721521/2d1ef8b8-cd8b-11e4-9f73-5a76477675ce.png)

`logBase=2&yUnitSystem=binary`:

![render-2](https://cloud.githubusercontent.com/assets/627486/6721481/bf0e0562-cd8a-11e4-8007-dc5de4cb3aa7.png)

**Comment by torkelo** [comment]
@jdanbrown thanks for your excellent feedback!

**Comment by rafrey** [comment]
This is probably lower priority than then the feature as a whole, but in the 1024 examples above, it would add value to the feature if Grafana could work past the Gi unit limit in Graphite by extrapolating units greater than Gi (e.g. Ti, Pi, Ei)...

Let me know if you would like example use cases for this request.

**Comment by torkelo** [comment]
Added log base 16:
![image](https://cloud.githubusercontent.com/assets/10999/6761781/e55d61ec-cf2c-11e4-8c95-4a3db909e46d.png)

And log base 1024:
![image](https://cloud.githubusercontent.com/assets/10999/6761802/0df6b91e-cf2d-11e4-8f82-f608c5dd44b5.png)

@rafrey as you can see they the units extend to EiB (I see now that is not included in the screenshot but it does, I promise). 

@jdanbrown I had the same issue as graphite with log base 2 (two many y-axis tick labels that overlap). I tried to reduce the number of tick labels to only show every 4th tick label but that is the same as log base 16

**Comment by jdanbrown** [comment]
Rockin! Yeah, dynamically computing the labels to optimally pack the y-axis would be cool but is definitely not critical for this to be useful.

What about base 32 instead of 16? That nicely subdivides base 1024 in half (32 = 2^5, 1024 = 2^10). I'd guess those two (or base 16 + base 1024) will cover most use cases.

Thoughts on the minor grid lines? I think those are important for UX, since it's hard to interpolate without them.

**Comment by jdanbrown** [comment]
Hmm, I guess there's not "one right way" to do minor grid lines. A few thoughts:
- The 8 minor grid lines on the graphite log base 10 graphs are because I manually specified `minorY=8`, which I think is a standard way for people to plot log-scale graphs... (low confidence)
- For the base 2^n graphs, maybe a good design is to draw 3 minor lines to give 4 subdivisions?
  - e.g. base 1024: 1B (256B 512B 768B) 1KiB (256KiB 512KiB 768KiB) 1MiB ...
  - e.g. base 16: 1B ( 16B

**Comment by jdanbrown** [comment]
Hmm, I guess there's not "one right way" to do minor grid lines. A couple thoughts:

- The 8 minor grid lines on the graphite log base-10 graphs are because I manually specified `minorY=8`, which I *think* is a standard way for people to plot log-scale graphs... (low confidence)

- For the base 2^n graphs, maybe a good design is to draw 3 minor lines to give 4 linear subdivisions for each major step?
  - e.g. base 1024: 1B (256B 512B 768B) 1KiB (256KiB 512KiB 768KiB) 1MiB ...
  - e.g. base 32: 1B (8B 16B 24B) 32B (256B 512B 768B) 1024B ...
  - e.g. base 16: 1B (4B 8B 12B) 16B (64B 128B 192B) 256B ...

**Comment by jdanbrown** [comment]
(Sorry, fumbling around operating the github comments here :P)

**Comment by jdanbrown** [comment]
Hmm, I guess there's not "one right way" to do minor grid lines. A couple thoughts:

- The 8 minor grid lines on the graphite log base-10 graphs are because I manually specified `minorY=8`, which I *think* is a standard way for people to plot log-scale graphs...

- For the base 2^n graphs, I propose dividing each major step linearly into 4ths and drawing 3 minor grid lines. I think that would be readable, and all (most) powers of 2 will divide by 4. Examples:
  - base 1024: 1B (256B 512B 768B) 1KiB (256KiB 512KiB 768KiB) 1MiB ...
  - base 32: 1B (8B 16B 24B) 32B (256B 512B 768B) 1024B ...
  - base 16: 1B (4B 8B 12B) 16B (64B 128B 192B) 256B ...

- (A quick scan http://images.google.com/images?q=log+scale+network+bandwidth shows only base-10 graphs...)

Thoughts?

**Comment by torkelo** [comment]
flot charts does not have minor grid lines, can be added with some code modifications, but not something added in couple of minutes

**Comment by jdanbrown** [comment]
Ah, got it. Then I'd vote for base 32 instead of base 16 and call it good.
