### ISSUE TITLE
origin not allowed popup and dashboard can not be saved when using IIS as reverse proxy

### ISSUE THREAD

**Issue by marianob85** [grafana/grafana#45261]
**What happened**:
When trying to save dashboard, yellow exclamation mark popup: "origin not allowed" and  dashboard is not saving. (  via domain name using IIS reverse proxy  )
When accessing grafana directly by internal IP:3000 everything works.  

Reverting grafana to version 8.3.4 solve problem. Problem exist on version 8.3.5 and 8.3.6

I'm not using sub path in IIS reverse proxy

**Environment**:
- Grafana version: 8.3.6
- Data source type & version: influxdb 1.8.10
- OS Grafana is installed on: Debian 11
- User OS & Browser: Win11/Chrome
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @marianob85 

this sounds like the same issue with NGINX + 8.3.6:
https://github.com/grafana/grafana/issues/45117#issuecomment-1033842787

the fix for NGINX and Apache was to preserve `Host` headers

For IIS, I did find this related solution on the [MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/44291437-3855-4f11-af1a-b3d9e41582d6/url-rewrite-original-hosst-header-?forum=iisurlrewritemodule):

>I assume you are using ARR with url-rewrite to accomplish this - you need to set the preserveHostHeader attribute to true in ARR configuration - note that some applications may still create wrong links in the response just because the port for the external url is different than the port for the internal server.

if this applies to your case, can you try setting `preserveHostHeader` to `true` and report back?

**Comment by marianob85** [comment]
Indeed. Changing preserveHostHeader  options to true solved problem. 
Thank you!

**Comment by IllusionVK** [comment]
For anyone else trying to work out where to configure `preserveHostHeader` 

I found the answer here  
https://serverfault.com/questions/936922/setting-up-iis-reverse-proxy-to-preserve-host-headers

which says to open cmd prompt and run 
`%windir%\system32\inetsrv\appcmd.exe set config -section:system.webServer/proxy -preserveHostHeader:true /commit:apphost`
