### ISSUE TITLE
Not able to silence alerts in folder with editor permission

### ISSUE THREAD

**Issue by stillsnowy** [grafana/grafana#45370]
**What happened**:
Users with global "viewer" permission and folder "editor" permission can create alerts in that folder, but can't silence them.
**What you expected to happen**:
Users should be able to silence the alerts they created, even they don't have global editor permission.
**How to reproduce it (as minimally and precisely as possible)**:
Create user with global viewer permission and grant editor permission on any folder. 
Create test alert in that folder.
Choose created alert at /alerting/list page and click "Silence" button.
Browser just redirects to grafana home page and silence is not created
**Anything else we need to know?**:
Nope
**Environment**:
- Grafana version: 8.3.6
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @stillsnowy 

I was able to reproduce this in a local docker instance running v8.3.6 `(bf8766bbf2)`

- log in as admin and create a new user `foo` with viewer privileges
- create a new folder and add a new dashboard
- edit folder permissions so that user `foo` is editor or admin (I also tried changing universal viewers to editors / admins
- log out and then log in as user `foo`
- create a new alert for that folder. Alert is created.
- check active alert in /alerting/list and click `silence` button: redirects to home page

**Comment by fereggert** [comment]
Same problem with Grafana 10.0.1

**Comment by tomratcliffe** [comment]
Hi all - apologies for the bug here. This functionality is fixed in Grafana 11.1.0, from changes within PRs such as https://github.com/grafana/grafana/pull/87320 / https://github.com/grafana/grafana/pull/87322. 

Those PRs reference Role Based Access Control, but the changes work without that functionality enabled. The silences creation logic from a given alert rule is now in a drawer, and when creating from this place in the UI, the silence will target that alert rule by UID.

If you have any further questions, please feel free to ask!

**Comment by VegasCasino777** [comment]
The SilenceURL still returns a link that an Editor cannot use. The link is composed for a global silence and an Editor cannot follow it, it just redirects to the home page.

**Comment by Scukerman** [comment]
The SilenceURL still returns a link that an Editor cannot use. The link is composed for a global silence and an Editor cannot follow it, it just redirects to the home page.

**Comment by tomratcliffe** [comment]
Apologies! You are correct regarding the permissions - this shouldn't have been closed. I have a change here that will address the redirecting issue if the user don't have the global permission for silence creation
