### ISSUE TITLE
Table: Bar gauge cell display mode with varying value lengths in a narrow column creates miss-alignment 

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#45442]
**What happened**: The LCD gauge display mode div is incorrect if, for example, a 3-digit number is displayed after 1000. The last LED is one more than the 4-digit higher value.

See value: "978"
![image](https://user-images.githubusercontent.com/2911588/154223696-d918cdaa-9656-4d43-97a9-dcfb261c42fd.png)

Setting of this column:
![image](https://user-images.githubusercontent.com/2911588/154223789-df1d8f61-a8a6-47d6-993c-03105f698070.png)

**Environment**:
- Grafana version: v8.3.3 (30bb7a93ca)
- User OS & Browser: Chrome 98.0.4758.102 Windows 64 bit

**Comment by zuchka** [comment]
Thanks for creating this issue, @sanchomuzax 

looks like this corrects itself with a wider width. I got it working ~480

**Comment by sanchomuzax** [comment]
Yes, I think that the 480px is too large. 😃

**Comment by codeincarnate** [comment]
Looking into this and indeed looks like it may not be working quite correctly. The cells of the LCD gauge should go smaller in this I'm pretty sure. What ends up happening in this particular case is that the loop [here](https://github.com/grafana/grafana/blob/8f6877e12adc76634f1b58282923bfdcae9c8f1f/packages/grafana-ui/src/components/BarGauge/BarGauge.tsx#L162) will terminate earlier with the 4 digit values because the label widths are greater. This happens even if we adjust the cell size smaller currently (more cells will be produced going to the same overall width).

In this case seems like we should be adjusting based on data values _and_ available space since we're primarily doing available space now. Working on an appropriate fix.

**Comment by codeincarnate** [comment]
Well, as things tend to be this is more complicated than it appears. We're currently using a single table cell for both the gauge and value. This is problematic because it means that the space available in the cell will always be split between the value and the gauge.

Further complicating this is that (at least currently) cells are unaware of what is being rendered outside of their row and the display value can be affected by value mappings. See below for a particularly ridiculous example of this (value is 805):

![lcd gauge](https://user-images.githubusercontent.com/199847/163057037-9bfac05e-0732-4873-9f43-faaa0eef86e9.jpg)

Figuring out an appropriate approach to this. I believe it effects all the gauge displays the same way. We could potentially separate gauge and value into separate cells though that could get ugly.  May try a first pass using sub-components for this to see if that can get a better behavior for this.

**Comment by torkelo** [comment]
It's not super easy to fix this. If you have a very narrow column and varying value lengths this feature is not a good fit. 

The way to solve it is to give the column more width. 

The dev solution here is to introduce an option to hide the gauge value so only the gauge would be shown. Then have a transform to duplicate a field so you can show the value in a different column

**Comment by sanchomuzax** [comment]
Alternatively, the number/value may appear in front of the LCD. This can also be an extra option.

**Comment by codeincarnate** [comment]
This should be fixed by #61477

**Comment by baldm0mma** [comment]
@codeincarnate will #61477 also fix #40925 ?

**Comment by codeincarnate** [comment]
Yes, it does 😄. I'll add that to the list
