### ISSUE TITLE
CloudWatch: Logs visualization of a Logs query results in "undefined (reading 'labels')" error message

### ISSUE THREAD

**Issue by fridgepoet** [grafana/grafana#45473]
**What happened**:
Choosing a Logs visualization of some CloudWatch logs results in undefined reading 'labels' error message.
![Screen Shot 2022-02-16 at 10 33 38](https://user-images.githubusercontent.com/4163034/154284822-dd501bfd-45b7-46fa-a9d0-384a0fe144f7.png)

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a dashboard panel 
2. Choose Logs visualization
3. Choose CloudWatch Logs
4. Enter a log group and valid query
Result: Running query results in: Cannot read properties of undefined (reading 'labels')

**Environment**:
- Grafana version: main ~8.4.0

**Comment by andresmgot** [comment]
I am not sure if this is a CloudWatch issue. The error is definitively happening outside its code base:

https://github.com/grafana/grafana/blob/main/public/app/core/logs_model.ts#L315

What it's happening here is that just running "limit 10" is not a valid CW Logs query since it only returns timestamps, it doesn't return a second (required) string field. 

![Screenshot from 2022-03-25 13-41-50](https://user-images.githubusercontent.com/4025665/160122695-43e39945-7f10-49b5-8d7e-b80085bb22fd.png)

You need a query like `fields @timestamp, @message | limit 10`.

What is wrong here is the error message, it shouldn't crash but say:

![Screenshot from 2022-03-25 13-43-32](https://user-images.githubusercontent.com/4025665/160122909-e7033118-4c21-423b-a394-1d46812eaf27.png)

(as it does with other input).

I assume something is unexpected with the data that CW logs returns for the first query and that causes the crash in the Logs panel. @grafana/observability-logs-and-traces can you chime in and check if this is a bug in our side or in the panel? Thanks in advance! 

Also, here is the CSV of the data that CW returns: [link](https://drive.google.com/file/d/1YRyM45tf2ORcThA3MbhHbNLZVNZ3vxte/view?usp=sharing) (even though I was not able to reproduce the issue just setting this CSV in the test data source).

**Comment by taleena** [comment]
@gabor we understand this is an obs issue, can we move this into the Todo column on your board? We'll keep track of this since we'll need to understand the effort once it's fixed.

**Comment by gabor** [comment]
@taleena sure, no problem. we have a quick fix already in a pull request in https://github.com/grafana/grafana/pull/46963

**Comment by gabor** [comment]
will be available in 8.4.5 or 8.4.6, depending on whether the CI job goes fast enough 😄

**Comment by taleena** [comment]
Excellent, thank you very much @gabor :)
