### ISSUE TITLE
[Feat Request]: Control over templating query and time range 

### ISSUE THREAD

**Issue by snc29590** [grafana/grafana#4583]
- I am using Grafana 2.6 on a CentOS 6.6 box. 
- I use grafana with a Elasticsearch (daily index) + Graphite combination
  - Graphite holds the actual server metrics 
  - Elasticsearch (v1.4.0) holds server metadata that is used to template the dashboards
- A new elasticsearch index is created everyday at midnight with latest server info. The timestamp field contains the timestamp corresponding to midnight of each day.
  - Template variables are populated correctly if the dashboard time range includes midnight.(example: 12 AM to 2 AM)
  - However, template variables don't get populated (shows None) if I choose a different time range (say, 3 AM to 9 AM)
- Below is the request sent by the browser to elasticsearch. It turns out this is happening because Grafana appends the dashboard time range to the template variable's elasticsearch query. 

`{"size":0,"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"customer:36 AND application:nginx AND datacenter:eu1 AND active:true"}},"filter":{"bool":{"must":[{"range":{"timestamp":{"gte":"1459914931788","lte":"1459936531788"}}}]}}}},"aggs":{"1":{"terms":{"field":"hostname","size":0,"order":{"_term":"asc"}}}}}`
- Is there a way to override this timestamp? Or, is there some workaround that will prevent automatic adding of the timestamp filter to the query?

**Comment by torkelo** [comment]
The dashboard time range is used for ES temulating queries. There is no option to disable this.

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
