### ISSUE TITLE
Alerting: Multidimensional alert history annotations do not stably sort

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#45873]
**What happened**:

Alert history is stored in annotations. When evaluating multidimensional alerts, each condition will be evaluated at the exact same time. So, there will be multiple annotations with the same orgID and same time (called `epoch` in the database).

The endpoint for querying annotations strictly sorts by orgID and epoch:
https://github.com/grafana/grafana/blob/8a98354844c49ea7b3cd4a3f463df73a754df124/pkg/services/sqlstore/annotation.go#L226

However, since many rows will have equal values for the (orgID, epoch, epoch_end) tuple, the DB can choose to return those rows in any order it likes.

The result is that the Alert History view looks different after multiple reloads of the page. A user can come to the same page later and see different order of results. This is compounded by the fact that the history view injects "empty" entries for sequential annotations that are nonlinear (i.e. two Alerting->Normal transitions in a row, the UI will inject a Normal->Alerting entry). If a multidimensional alert has a mix of alerting and normal conditions, the shuffling of results can result in these empty entries being needed in one request, but not being needed in another. So, after multiple navigations, not only is the order different, but the actual number of displayed records is different.

**What you expected to happen**:

The annotation route should return records in a consistent order, because order matters in alert history. It should include a clause to also sort records by something guaranteed to be unique per-record, usually `ID`, after all the existing sorts. That way, the route will return records in a consistent order every time.

**How to reproduce it (as minimally and precisely as possible)**:

Set up a multi-dimensional alert with some values alerting and some values as normal.
Navigate to that alert's history. Note the injected blanks, and the fact that there are groups of entries which have the exact same time:

![155618824-a02294c5-3995-46ac-b324-5eb487b4f2fc](https://user-images.githubusercontent.com/2117580/155695327-0910f6c0-99cb-4a9e-933a-261e2a895cfe.png)

Wait a bit, or restart. After enough navigations back to the page, the order will be different, and there will be a different number of injected blank entries.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.x
- Data source type & version: n/a
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by joeblubaugh** [comment]
The Grafana frontend makes a direct request to `/annotations?alertId=1234`, which executes the query alex mentions above. We *could* add an additional order-by to the query for the alertID, but it's only relevant for a particular kind of query, and the annotation query builder doesn't currently template order-by at all. Adding another order-by for queries where the alertId is almost always NULL could hurt their query performance, though it's not easy to know whether it will or won't. I'd rather not add another conditional component to the SQL query if we can avoid it.

Since we're already re-processing the list in the frontend in order to insert these blanks, I think it makes sense to do one more sort pass over the data in our particular use in alerting, rather than add an order-by that will require loading an unindexed column during scans.
