### ISSUE TITLE
In some conditions a dashboard including a library panel cannot be saved

### ISSUE THREAD

**Issue by gavol** [grafana/grafana#45924]
**What happened**:
I have saved a panel as a "library panel" and I'd like to export it in view-only mode. In order to do that, the panel has been saved in a folder where all the users have only "view" permissions.

It looks like users can import the library panel in their dashboard but then the dashboard cannot be saved. The following error is reported in UI: "Error while connecting library panels".

If users are given "edit" permissions to the folder where the library panel is saved in, then the dashboard can be saved. But, at that point, the panel itself can be modified by any user.

**What you expected to happen**:
Since a library panel inherits the permissions of the folder it is saved in, I would expect a panel saved in a read-only folder to be imported in a read-only manner in other dashboards.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a library panel;
- Save it in a folder where other users have only "view" permissions;
- As a different user, create a new dashboard and add the previously created library panel;
- Try to save the dashboard.

**Environment**:
- Grafana version: 8.4.1
- OS Grafana is installed on: Linux, CC7
- User OS & Browser: Linux, Windows - Firefox

**Comment by joshhunt** [comment]
Was able to replicate the issue. Editors cannot add Library Panels from a view-only folder to dashboards. The frontend will allow them to do this, but then the backend will prevent the dashboard from being saved.

Exact reproduction:
 1. As Admin:
     1. Create a "Read-only Library Panels" folder
     2. Set the Editor role permission on the "Read-only Library Panels" folder to "View" so "Editor (role) Can View"
     3. Create a Library Panel and save into the "Read-only Library Panels" folder
 2. As Editor:
     1. Create a new Dashboard
     2. Add the Library panel created from the "Read-only Library Panels" folder
     3. Save the dashboard.
 3. **Grafana will show "Error while connecting library panels" error when saving**

Looks like the backend explicitly requires edit permission on a Library Panel's folder in order to create the connection to it https://github.com/grafana/grafana/blob/35fe58de374003bb4b077a878cc47ffc0a9d27b5/pkg/services/libraryelements/database.go#L650

IMHO I agree with the author in that Editors should be able to add Library Panels from a view-only folder into Dashboards they have permission to edit, but I don't have the wider context to understand whether we should change this or not.

@grafana/backend-platform Are you able to help out here? This seems like a permissions bug in the backend to me.

**Comment by joshhunt** [comment]
Got clarification that this is a bug that we can "easily" fix by relaxing the permission requirements on using a Library Panel. 

We will change this to require only Viewer permission on the library panel when adding it to a panel you have edit permissions on.

**Comment by gavol** [comment]
Thanks a lot for looking into that.

**Comment by axelavargas** [comment]
Adding an extra use case that needs to be fixed related to library panels and user/folder permissions:

"The team's user folder permission is not taken into account when updating a library panel"

1. Admin creates a user "Ausr" with `Viewer Role`
2. Admin creates team "editors team" and adds "Ausr" to it
3. Admin create a folder and set "editors team " with  `Edit` permissions
4. "Ausr" sign in and create a dashboard, adds a panel, and convert this panel into a library panel (using test data)
5. The library panel is saved correctly
6. "Ausr"  modify a query in the library panel and try to `save`
7. `Ausr` gets 'Error saving library panel: "access denied to folder"

I found that the `Viewer` user role is being used when we edit the library panels and is not taken into account the editor role that the user inherits from the folder permission

https://github.com/grafana/grafana/blob/35fe58de374003bb4b077a878cc47ffc0a9d27b5/pkg/services/libraryelements/guard.go#L32

**Comment by dabernasty** [comment]
Hey team -- do we have an update on ETA for this? The customer is asking - thank you

**Comment by natellium** [comment]
Hey @dabernasty there's a PR open that should fix this https://github.com/grafana/grafana/pull/50241

**Comment by PankajChawla** [comment]
@natellium  does this PR covers the use case shared by @axelavargas as well?

**Comment by kristwaa** [comment]
I'm still seeing the behaviour described by @axelavargas ([comment](https://github.com/grafana/grafana/issues/45924#issuecomment-1114677918)) in v9.2 . #50665 seems relevant (still open, but now recently unblocked according to linked issue).
