### ISSUE TITLE
Unable to access all template variables when using templates for alerting/notifications in 8.4.1 cloud

### ISSUE THREAD

**Issue by tom0010** [grafana/grafana#45982]
**What happened**:
When using grafana cloud v8.4.1 and trying to template or customise my notifications, it seems you are only able to access `{{ .Labels }}`. 
If you iterate over the alerts, you should get given Labels, Value, Annotations etc. However it seems you can only access Labels. 
If you leave the template as default, in this case I am using Slack, I get all of the information/variables. 
Also, using the format of `{{ $value }}` or `{{ $labels }}` does not work.
The only way to get all of this information, is to actually leave the default template that grafana has. However, you end up getting too much information and it's not in a nice format. 
One thing to note too, this is the same if you are using templates, or you are modifying the "Text Body" inside the slack contact point.

**What you expected to happen**:
You should be able to access the values in the alert, such as the value. 
`{{ $value }}` and `{{ $labels }}` should return information. 

**How to reproduce it (as minimally and precisely as possible)**:
Create an alert, whether grafana managed or Cortex/Loki. 
Use Slack as a contact point, in the "Text Body" leave it as default, and you will get all the information from your alert, including "Value" or the alert that you setup. 
If you loop through the alerts, you cannot access Value or anything else apart from Labels:
```golang 
{{ range .Alerts }}
{{ .Labels }}
{{ .Value }}
{{ end }}
```
You will notice that only the labels are presented. 
If you remove the following config/text, you will see more information that you can use, more precisely, the `Value` of the alert.
It is "OK" to have just the labels, but actually it would be nice to actually give back to the user the value. In my case I'm alerting on linux disk space, so it would be nice to see the percent of the disk space from the query. 
My query:
```
A:
100 - ((node_filesystem_avail_bytes{instance="hostname:12345",job="integrations/node_exporter",mountpoint=~"/data",fstype!="rootfs"} * 100) / node_filesystem_size_bytes{instance="hostname:12345",job="integrations/node_exporter",mountpoint=~"/data",fstype!="rootfs"}) > 77
```
```
B:
Reduce, Last, Input = A
```
```
C: 
$B > 77
```

**Anything else we need to know?**:

**Environment**: Grafana Cloud 
- Grafana version: 8.4.1
- Data source type & version: Grafana cloud/Prometheus cloud
- OS Grafana is installed on: NA
- User OS & Browser: MacOS/Chrome
- Grafana plugins: Cloud default
- Others: N/A

**Comment by tom0010** [comment]
I found a "workaround", by looking at the `node_exporter` automatically generated rules, I was able to build something. 
It seems that grafana will only allow you to use `$label` and `$value` etc. when you are creating the rule. 
In step 4 when creating the rule (Add details for your alert) you are able to access them values. In this case, `$value`. 
As I said this is how `node_exporter` does it.
My workaround is by using a new `annotation` from the `$value`, e.g:
```
key:                    value: 
=====================================
query_value          {{ $value }}
```
Screenshot:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/41154665/156210602-a7f6bb47-7429-4add-80fc-a88825900e36.png">

It means I can reference that `value` by using templates or just inside of the default slack config, inside of `annotations`.
Inside slack config:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/41154665/156210780-d1c1341d-52c0-4a24-bd6c-a01a78c5e9ea.png">
Inside Contact Points > Message templates > Template:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/41154665/156211023-9fe7461d-8743-4aba-b687-75b38273f61f.png">

Output:
![image](https://user-images.githubusercontent.com/41154665/156211347-7fc86c00-f0f9-4f74-b6b9-427d73539f53.png)

You can see I get the `value` percentage of the query here inside the title and in the last line of the slack message.
My query: 
```
100﻿ - ﻿(﻿(﻿node_filesystem_avail_bytes﻿{﻿instance﻿=﻿"my_hostname:12345"﻿,﻿job﻿=﻿"integrations/node_exporter"﻿,﻿mountpoint﻿=~﻿"/data"﻿,﻿fstype﻿!=﻿"rootfs"﻿}﻿ * ﻿100﻿)﻿ / node_filesystem_size_bytes﻿{﻿instance﻿=﻿"my_hostname:12345"﻿,﻿job﻿=﻿"integrations/node_exporter"﻿,﻿mountpoint﻿=~﻿"/data"﻿,﻿fstype﻿!=﻿"rootfs"﻿}﻿)﻿ ﻿>﻿ ﻿77
```

It would sure be nice to just be able to access `$value` by looping through the alerts as per prometheus documentation (https://prometheus.io/docs/prometheus/latest/configuration/template_reference/#alert-field-templates):
```
{{ range .Alerts }}
{{ .Value }}
{{ end }}
```
Hope this actually helps with my original post.

**Comment by daverstam** [comment]
I have the same issue on 8.4.4 where I can't manage to extract the value in a reasonable way. This is a non issue using Prometheus/Alertmanager where you simply use {{ $value }}

**Comment by alexweav** [comment]
Hello @tom0010 ,

There is a field that has a reduced representation of alert value in Grafana alerts called `ValueString`. Is `{{ .ValueString }}` instead of `{{ .Value }}` sufficient for what you are trying to do?

**Comment by lfkdev** [comment]
Why is this closed as completed? The issue still exist and its an absolut pain to get simple variables in the Slack message. Why can't we just use {{ $variable }} in the body template?

**Comment by outinspace** [comment]
Can this be reopened?

**Comment by alexweav** [comment]
This was closed during a grooming session as there was a solution posted 4 months ago, that appears to have been accepted with no further information. It was closed as stale.

We'd be happy to re-open if there are still further roadblocks here. Could you provide some clarification on what those issues are? Is `ValueString` a sufficient enough replacement for the `$value` macro? Perhaps I am mis-understanding the issue here?

Also note that the templates inside the annotations box when generating the alert and the templating system for formatting notifications are two independent systems right now. We have a broader effort to improve the alignment of these, perhaps @santihernandezc could add some clarification in that area?

**Comment by santihernandezc** [comment]
@lfkdev There are currently two broad categories of template variables/functions in Alerting:
- The ones available during alert creation ([docs](https://grafana.com/docs/grafana/latest/alerting/fundamentals/annotation-label/variables-label-annotation/)).
- The ones available in contact point templates ([docs](https://grafana.com/docs/grafana/latest/alerting/contact-points/message-templating/template-data/)).

As an example, using `{{ $value }}` would only make sense in an alert rule, but not in a contact point template. 

As @alexweav said, we're aware that this separation creates some confusion around how templates work in Grafana, and improving this experience is in our plans.

**Comment by grobinson-grafana** [comment]
Hi! 👋 

I'm surprised Annotations were not accessible in the message template. With the following template:

```
{{ define "test.message" }}
{{ range .Alerts }}
Annotations: {{ .Annotations }}
Labels: {{ .Labels }}
{{ end }}
{{ end }}
```

I received this email:

```
Annotations: map[description:This is a test alert]
Labels: map[alertname:Test grafana_folder:GrafanaCloud]
```

You are correct in that `{{ .Value }}` is not available in message templates, but is available when templating custom annotations and labels.

I understand that `{{ .Value }}` is not available in message templates is because unlike in Prometheus where `{{ .Value }}` is the value of the left hand side of the expression, in Grafana `{{ .Value }}` would contain the value of the condition which in most cases will be either `0` or `1`.

**Comment by grobinson-grafana** [comment]
Hi! 👋 

I'm surprised Annotations were not accessible in the message template. With the following template:

```
{{ define "test.message" }}
{{ range .Alerts }}
Annotations: {{ .Annotations }}
Labels: {{ .Labels }}
{{ end }}
{{ end }}
```

I received this email:

```
Annotations: map[description:This is a test alert]
Labels: map[alertname:Test grafana_folder:GrafanaCloud]
```

I understand that `{{ .Value }}` is not available in message templates because unlike in Prometheus where `{{ .Value }}` is the value of the left hand side of the expression, in Grafana `{{ .Value }}` would contain the value of the condition which in most cases will be either `0` or `1`.

If it helps both `$value` and `$values` are available when templating custom annotations and labels. Documentation on how to use these can be found here in [How to template annotations and labels](https://grafana.com/docs/grafana/latest/alerting/fundamentals/annotation-label/variables-label-annotation/).
