### ISSUE TITLE
Trace View: Detail panel overlaps other spans

### ISSUE THREAD

**Issue by connorlindsey** [grafana/grafana#46032]
**What happened**:
![Screen Shot 2022-03-01 at 7 44 08 AM](https://user-images.githubusercontent.com/12838032/156189855-ca50268d-58a3-422f-8855-8ad01a09707f.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by svennergr** [comment]
Hi @connorlindsey,

to add a bit of context here.
Seems like I found the issue, that is causing this behaviour. The rows in the `KeyValuesTable` are changing their height due to their `Buttons` (and `SVG`-elements). That change is causing the inner panel to change the high causing the overlap.

![Image](https://user-images.githubusercontent.com/8092184/169259973-3d2183da-ace0-4081-8f9e-fd615647e77f.png)

^ shows that everything is fine when breaking when the height is set and the `KeyValuesTable` did not yet change in height.

![Image](https://user-images.githubusercontent.com/8092184/169260200-6e439c7e-3491-4938-aefe-55222c71d4a4.png)

^ shows that the rows in the `KeyValuesTable` are now a bit heigher, which is causing the overlap.

I am still investigating how to best fix this as this could potentially also cause other issues and is not solely related to the traces panel.
