### ISSUE TITLE
Explore: For logs query in Inspector we see log volume query instead of executed query

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#46087]
**What happened**:
In Explore's Inspector, for logs query we see the log volume query instead of executed query. This means that users can't use download logs because they see metrics. We should add `hideFromInspector: true` for log volume queries

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/30407135/156355245-6e5b9b4d-9116-499a-aac8-4f9b0a88ef6d.png">

**What you expected to happen**:
In Inspector I want to see results of queries that I executed. 

**How to reproduce it (as minimally and precisely as possible)**:
Open inspector, run log query, look at the results.

Grafana v8.3+

**Comment by gabor** [comment]
the problem is, when the datasource is a backend-datasource, we do not have access to `hideFromInspector`:
- when it's a frontend-datasource, it calls ` getBackendSrv().fetch({...})`, and we can pass `hideFromInspector` there.
- but when it's a backend-datasource, it calls `super.query({...})`, so no way to pass the `hideFromInspector` flag.

we could modify `DataSourceWithBackend.query` ( https://github.com/grafana/grafana/blob/main/packages/grafana-runtime/src/utils/DataSourceWithBackend.ts#L112 ), and add a second `options` param where we could pass the `hideFromInspector` flag.

or maybe there's some other way to achieve this?

@grafana/plugins-platform-frontend what do you think?

**Comment by mckn** [comment]
@gabor sorry for being late to the party. Did you manage to resolve this?

**Comment by gabor** [comment]
hi @mckn ! sorry, no, we still need some API where we can tell grafana to "do not report this request to the inspector please", when using the `DataSourceWithBackend.query`.

**Comment by mckn** [comment]
OK ok, I will get back to you in this issue. Thanks for the quick reply 🙏🏻
