### ISSUE TITLE
Alerting: labels from the alert query not present in the alert and for templating

### ISSUE THREAD

**Issue by codesome** [grafana/grafana#46094]
**What happened**:

_This is for Prometheus alert-generator compliance, read more [here](https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md). Using Grafana managed alert on a Prometheus datasource._

Take for example a metric present in Prometheus `up{job="bestjob", instance="goodinstance"} 0`, and I have an alerting rule set for `up == 0`. The labels `job` and `instance` is not present in the final alert (as seen in `/api/prometheus/grafana/api/v1/alerts` and `/api/prometheus/grafana/api/v1/rules`) and not available for templating using `$labels.job` and `$labels.instance`

**What you expected to happen**:

A Prometheus compliant behaviour would have the `job` and `instance` label in the final alert and also available for templating via `$labels.job` and `$labels.instance` for labels and annotations.

**Environment**:
- Grafana version: Latest at the time of opening this PR

**Comment by alexweav** [comment]
We tested this in the grooming meeting with @JacobsonMT and @yuri-tceretian. It seems this only happens with classic conditions - a standard reduce will preserve the labels like Prometheus. This is a common point of user confusion with alerting - users don't always know when to use reduce vs. classic condition. Generally in 9.0, we should make reduce the default, this is what users should prefer in general.

A potential new feature would be to have Classic Condition include common labels as it reduces. Generally, classic condition is a Grafana-specific concept.

Does the fact that this works with the standard reduce operation fulfill this requirement?

**Comment by santihernandezc** [comment]
@codesome after some [discussion](https://raintank-corp.slack.com/archives/C028MCV4R7C/p1661874059386559) on Slack we think a better alternative would be to make Reduce the default instead of Classic Conditions, which are only there for backwards compatibility reasons.
A redesign of the expressions pipeline is on the way, and there's the idea of supplementing this choice of making Reduce the default by something more simple than the Math expressions (more info in the thread I linked to earlier).

**Comment by santihernandezc** [comment]
I just opened an [issue](https://github.com/grafana/grafana/issues/54552) to make "Reduce" the default option. Closing this one.
