### ISSUE TITLE
Rule names with "/" in name cannot be deleted

### ISSUE THREAD

**Issue by ammaar8** [grafana/grafana#46276]
**What happened**:
A rule name contained "/" in the name and now I cannot delete it.

**What you expected to happen**:
Rule names with "/" in their names should be handled correctly or not be allowed to be saved.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an alert 
2. Input a rule name with "/" in its name. example - PAUSE/PAUSE2 Threshold
3. Save
4. Try to delete rule - get "Error: Not Found"

**Environment**:
- Grafana version: 8.3.4
- Data source type & version:
- OS Grafana is installed on: Ubuntu 20.04.3
- User OS & Browser: Windows 11/Edge
- Grafana plugins:
- Others:

Would be happy to contribute if told what to look for.

**Comment by Elfo404** [comment]
Hello @ammaar8, thanks for reporting this! 

I'm closing as it seems to have been fixed in 8.3.6 so that rules name are not allowed to contain either "/" or "\\" (https://github.com/grafana/grafana/pull/44872)
![Screenshot 2022-03-10 at 12 20 28](https://user-images.githubusercontent.com/1170767/157660578-0ccf08b5-efed-4e8c-8663-650d88d851b0.png)
