### ISSUE TITLE
Dashboards can hang within a loop in v7.x

### ISSUE THREAD

**Issue by rheng** [grafana/grafana#46388]
**What happened**:
Dashboards can hang in certain situations. After investigation, the loop is happing in uplot.

**Anything else we need to know?**:
This issue is fixed in in uplot version 1.6.10:
https://github.com/leeoniya/uPlot/commit/05f5a378630d770b66a06a6bfa3a2eb9aa0

Grafana v8.x has this resolved (https://github.com/grafana/grafana/blob/main/packages/grafana-ui/package.json#L93), but it would be nice if this were back-ported to the v7.x branch (https://github.com/grafana/grafana/blob/v7.5.15/packages/grafana-ui/package.json#L81).

**Environment**:
- Grafana version: 7.5.15

**Comment by Elfo404** [comment]
hi @rheng, thanks for opening this.

As you mentioned this have been fixed in 8.x, it is unlikely that we'll backport the fix to 7.x unless there's high demand for it.

I'll close this one as we are trying to reduce the number of actionable issues to better track work, but we can reopen if it gains traction and we'll consider it.
