### ISSUE TITLE
[Feat Req]: Clone a datasource

### ISSUE THREAD

**Issue by steverweber** [grafana/grafana#4639]
Often times wish there was an UI function to clone or duplicate a datasource.

Our deployment has multiple databases on one influxdb system.. It's kinda repetitive to rewrite the same data for each grafana datasource.

**Comment by bergquist** [comment]
Since Grafana now support configuring datasources in config files I think thats how this should be solved in environment with many datasources. 

Closing this since the problem have been solved in another way.

**Comment by shmish111** [comment]
@bergquist @steverweber @marefr can this be re-opened since it is not realistic for me to go into my database where my config is stored and manually run a query to do this since I don't have permission to access my DB directly.

**Comment by marefr** [comment]
@shmish111 what communicated earlier refers to using [provisioning through files](https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources)

**Comment by shmish111** [comment]
Hi, @marefr , I'm running in Google cloud run, I don't have access to a file system, hence why I'm managing config in postgres, which is a nice solution as long as there is a UI to do everything. I'm this case it seems there isn't.

**Comment by bergquist** [comment]
I think this is a reasonable feature request for those who are using Grafana in our cloud offering.

**Comment by arobertn** [comment]
For InfluxDB v3, sadly, you need one data source per bucket. There will generally be multiple buckets and thus it is necessary to configure URL and token laboriously for each one. Duplication is a UI concept found many places elsewhere in Grafana, so it is surprising not to see it here.

**Comment by sylr** [comment]
Wanted to duplicate a postgresql datasource to connect to a different database on the same host (with the same user).

**Comment by garethhumphriesgkc** [comment]
+1 for this.

We have an Elasticsearch backend, you have to create a new source for each index you want to query.  Would be great to have a template that you can just clone and change the one field for.  Especially considering things like the CA cert and API key are secrets which you can't see, so you can just pop open an existing one and copy+paste, you need to find someone with access to the secrets and get them to create it for you.

We can't store the API token in plain text in a config file, so that's not an option either.
