### ISSUE TITLE
Grafana unified alerting: wrong defaults for "Alert state if execution error or timeout"

### ISSUE THREAD

**Issue by erkexzcx** [grafana/grafana#46398]
This is how it looks when creating new alert:
![image](https://user-images.githubusercontent.com/5955795/157617734-8724069d-2059-4ff1-aa04-4bc14084721c.png)

Instead, it should be changed to `Error`.

Leaving it as `Alerting` shows these sort of alert messages:
```
Firing 1 alert:
 - Alert: My service alert title
   Summary: My service <no value> is down
```

And when using `Error`, it becomes ths (and totally makes sense):
```
Firing 1 alert:
 - Alert: DatasourceError
   Summary: My service <no value> is down
```

Please set defaults to `Error` for proper alerting...

**Comment by armandgrillet** [comment]
Talked among Grafana Alerting engineers during our weekly, `Error` should indeed be used instead.

**Comment by armandgrillet** [comment]
@alexweav Please decide if we should do this for 9.0 or not.

**Comment by alexweav** [comment]
@armandgrillet I believe Q2, after 9.0 is the right timing for this. It's not required for legacy alerting parity and is a fairly visible change, I am hesitant to make such a core behavior change right before the beta. As soon as 9.0 is out, let's make this change. It'll make it easier to debug alerts for sure.

Assigned prio/high to make sure it's at the top of the list after 9.0. IMO, this close to the release, "critical" should be the bar for 9.0.

**Comment by grobinson-grafana** [comment]
This has been fixed and will be available in Grafana 9.2.0.

**Comment by mhoran** [comment]
A downside of this change is that the `Error` state immediately sends a notification versus `Alerting`, which respects the configured `For` duration. I changed my alerts to `Error` but changed them back due to nuisance notifications due to Google Managed Prometheus unreliability. Not a huge deal, but I went chasing this wondering if `Error` purposefully ignored `For`. The code suggests this is a feature, not a bug, as per https://github.com/grafana/grafana/blob/4b417c8f3e7d77b6d790d77432bb8e60f634fdef/pkg/services/ngalert/state/state.go#L128-L138.

**Comment by grobinson-grafana** [comment]
Hi! 👋 

`Error` does not observe the `For` duration to avoid situations where alerts do not fire if a datasource is unreliable. However, it has been discussed that users might want to configure their alert rules to tolerate `N` successive failures, or even `N` failures within a certain time window before sending a `DatasourceError` alert.

If this is something that sounds useful please feel free to open a feature request [here](https://github.com/grafana/grafana/discussions).
