### ISSUE TITLE
Run grafana with docker without internet. Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by grigio** [grafana/grafana#46460]
It seems grafana or some plugins need internet during the start up

```
grafana   | Error: ✗ Get "https://grafana.com/api/plugins/repo/grafana-clock-panel": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by ivanahuckova** [comment]
Hello @grigio, could you please follow following template to report the issue, otherwise it is hard for us to understand what is the actual issue:

```
<!--
Please use this template to create your bug report. By providing as much info as possible you help us understand the issue, reproduce it and resolve it for you quicker. Therefore take a couple of extra minutes to make sure you have provided all info needed.

PROTIP: record your screen and attach it as a gif to showcase the issue.

- Questions should be posted to: https://community.grafana.com
- Use query inspector to troubleshoot issues: https://bit.ly/2XNF6YS
- How to record and attach gif: https://bit.ly/2Mi8T6K
-->

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:
```

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.

**Comment by JLammering** [comment]
Hi I've got the same errror. Here are the infos:
**What happened**:
Grafana container is not starting due to lack of internet connection. I installed the plugin as stated in the [docs](https://grafana.com/docs/grafana/latest/administration/plugin-management/#install-grafana-plugins) by unzipping the plgin and mounting it into the container (link to repo with minimal example below).
![grafik](https://user-images.githubusercontent.com/15649818/203777137-dace6094-6559-4150-8b4b-3334d6ada36a.png)

**What you expected to happen**:
I expected that grafana can install the plugin based on the unzipped directory without internet connection.

**How to reproduce it (as minimally and precisely as possible)**:
Check out this [repo](https://github.com/JLammering/grafana_minimal_issue_example) with a minimal example.

**Anything else we need to know?**:
It was also mentioned here: [community grafana](https://community.grafana.com/t/alerting-problem-error-message-error-context-deadline-exceeded/27791/5) .

**Environment**:
- Grafana version: [v9.2.6 (8ba6f0f1a8)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
- Data source type & version: no datasource used
- OS Grafana is installed on: Windows
- User OS & Browser: Windows & Firefox
- Grafana plugins: grafana-clock-panel
- Others: docker desktop on windows
