### ISSUE TITLE
Cannot save single dashboard link

### ISSUE THREAD

**Issue by zuchka** [grafana/grafana#46498]
**Steps to reproduce**:

try to save a single dashboard link

**Actual Result**:

This is a UI issue : there is no button to save the link we have to navigate out of the link tab and then back in to see our changes

**Expected Result**

workflow accessible for keyboard-only users

**Relevant WCAG Criteria:**

[2.1.1 Keyboard - Level A](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=335%2C332#keyboard)

**Environment**:
- Grafana version: 8.4.3
- Data source type & version:
- User OS & Browser:
- Others:

**Comment by torkelo** [comment]
What do you mean "save the link"  ?

You mean save the dashboard? 

the link is part of the dashboard and saved togethert with any other dashboard change

**Comment by yaelleC** [comment]
Yes, this is more of a puzzling UX behaviour than accessibility but we noticed that in template variables you can click the `update` button to save your variable and be redirected to the list of variables, it's not the case for `links` or `annotations` .

We found it cumbersome having to open another tab and go back to `links` to see the list displayed.

Does that make sense?

**Comment by xrisaD** [comment]
Hi @yaelleC,

I was thinking that there are two available options on that one:
1. The code as it is now saves the changes immediately. What I mean is that when the user changes a field it is saved automatically. If we want to keep it as it is, it is easy to just add a button which will get us back to the `links`. In this case, I was thinking that maybe it's confusing to call this button `Add` or `Update` since the user may think that if they don't click the button the update won't be applied. So we can call it `Go Back to List` or something like this? I could just name it `Add` or `Update` though, that's fine.
2. The other option is of course to have a `Update` or  `Add` button and change the functionality to actually update the link data only after the button is clicked.

What do you think? What do you want me to implement? 😄

**Comment by yaelleC** [comment]
Hi @xrisaD ,
Thanks for looking into this. 

I think having a 'Go Back to list' button would be a quick win for this one, improving the UX compared to the existing solution
But solution 2 sounds like the ideal thing to implement long term.

Could someone from @grafana/ux weigh in on this?

**Comment by amy-super** [comment]
Even though an `Apply` button is a little confusing because users might think it's required when it's not, it's a more common and understandable pattern than `Return to list` where users might not even know what list we're talking about - I had to fiddle with it a bit to understand the suggestion because of the ambiguity around the concept of the list. 

We definitely want to clean up how saves work overall in the future so we may be able to clear up any confusion then. My vote is an `Apply` button that then takes you back to the newly saved list.

**Comment by xrisaD** [comment]
Hi @yaelleC, maybe you would like to have a look at these two: https://github.com/grafana/grafana/pull/49075 and https://github.com/grafana/grafana/pull/49076

https://github.com/grafana/grafana/pull/49075: first idea, with a button called apply which just returns to the list, not extra functionality
https://github.com/grafana/grafana/pull/49076: an apply button which has to be pressed to go save the link and then go back (probably extra functionality needed)

**Comment by yaelleC** [comment]
Hi @xrisaD ,

Thanks for that. I agree with @amy-super an `apply` button is a good start and further UX work is needed to harmonise the whole saving flow in dashboard settings.
I'll add reviewing #49075 to my todo list for the week 😃
