### ISSUE TITLE
Feature Request: Alias Pattern for InfluxDB for the field name.

### ISSUE THREAD

**Issue by damm** [grafana/grafana#4655]
* What grafana version are you using?
3.0 Nightly
* What datasource are you using?
MySQL
* What OS are you running grafana on?
Ubuntu 14.04 LTS

I did notice you can alias each query; I am lazy and do something like.

`$tag_hostname - $m - $field`

$field is an example; I actually did `$m - $tag_metric`

**Comment by torkelo** [comment]
there is already, $col

**Comment by torkelo** [comment]
I know it should be $field, but they are called columns in the API :)

**Comment by damm** [comment]
Also alias'ing the field helps too :)

**Comment by bbinet** [comment]
The problem is that `$col`is not very useful because influxdb will always return the aggregation function only (min, max, last, mean, ...), so we must manually define an alias for every field if we want the `$col` alias pattern to be useful.

It would be great if Grafana could provide a new alias pattern which would be replaced by the actual field selection that is set in the query editor. This would be a good workaround for the bad naming of fields in the influxdb query responses.
See influxdata/influxdb#3838 for the influxdb related issue.

**Comment by bogd** [comment]
@torkelo - I think you might have rushed to close this too soon... 

As @bbinet mentioned, the problem is that $col is pretty much useless any time you are using a mathematical function (which, for me at least, is most of the time - as long as I am grouping by time interval, I tend to use a selector or an aggregating function). Once you use a function such as `sum(value)`, the column alias becomes "sum". Which in no way, shape, or form describes the actual data you are reading and graphing.

From what I've read so far, I understand that this is not an issue with Grafana, but an issue with InfluxDB (and the way it generates automatic column aliases). But it would still be nice to at least have a workaround on the Grafana side...

**Comment by Hivlaher** [comment]
There is a way to use $col in order to show a mean(field). You can use 'select mean("field") as field' and add $col on ALIAS BY

**Comment by william-cheung** [comment]
How can I use field name (with wildcards) in alias in the following case? Thanks.
```sh
SELECT non_negative_derivative(sum(/A.*/), 1s)  FROM "B" WHERE ("service" = "C") AND $timeFilter GROUP BY time(1s) fill(none)

**Comment by varun-dhawan** [comment]
> mean(

This trick works for me, thanks @Hivlaher

**Comment by Karan-M-Shah** [comment]
How do we manually define an alias for a field? I've been looking for documentation on it, but no luck

**Comment by Davidffry** [comment]
Hey, there an feature : 
![image](https://user-images.githubusercontent.com/31964077/79798056-ab265c00-8358-11ea-9105-d3d486069d66.png)

it enable to put an alias and call it into the Alias By, it can be help someone
