### ISSUE TITLE
[Feature Request] Allow configurable field separator for Measurements per different data sources

### ISSUE THREAD

**Issue by dever860** [grafana/grafana#4666]
[Feature Request] Allow configurable field separator for Measurements per different data sources

Version - grafana-3.0.0-beta31460415835
Datasource - influxdb
OS - Centos 6

Request: Please add the ability to configure the field separator for the Measurement field per data source and/or graph. The suggested measurement syntax for Influxdb uses a '_' (underscore) instead of a '.' (period) like graphite uses. I am guessing it was suggested like this to make it easier to do regular expressions without having to escape periods.

If the ability to change the field separator was available, it would then be possible to split the measurements via the Alias $1-$X variables.

Thank you!

**Comment by rahulghanate** [comment]
I am also in need of this feature, which was present Grafana 2.5, but not in grafana 3.0.1.

In my case, I am using Prometheus Data source in template variables to get the list of HAProxy backends, but I am using those backend names for querying Logstash/ElasticSearch data for more details at HTTP headers level.
As I cannot use ElasticSearch in template variables to get list of backends in haproxy, I have to use Prometheus to get the complete list of backends.

So earlier I used to get the list of backends from Prometheus and later use it in different template variable with Lucene separator so that I can use that template-var in ElaticSearch queries.

Now with auto-selecting separator based on datasource, doesn't allow me to use that template variable for querying different data source.

Many of my old dashboards are not loading because of this inconsistency.
Could you please move it to Bug/MustHave?

Thanks

**Comment by suicidejack** [comment]
I also have a similar problem.  Using prometheus as the data source and can't use template variables to form the metric names

**Comment by aocenas** [comment]
@ryantxu just a ping for this but also during triaging should influx be assigned to your github project? Or is there a github project for this?

**Comment by torkelo** [comment]
think we can close this, an old feature request for old influx with very little interest
