### ISSUE TITLE
Add option to hide tags list in annotation popups

### ISSUE THREAD

**Issue by brianfeucht** [grafana/grafana#468]
The annotation popup coming from Graphite is verbose.  It would be nice if there was an option to hide the tag list.  Even better would be some way to customize what data is displayed in the popup.

**Comment by torkelo** [comment]
We are trying use open GitHub issues as a way to track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long without any much interest in the feature or anyone showing interest in implementing it. 

A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
