### ISSUE TITLE
[Feature Request] Assign Multiple org_ids for auth.anonymous

### ISSUE THREAD

**Issue by olystretch** [grafana/grafana#4691]
We use organizations to separate dashboards among teams. I want to grant access to multiple organizations to anonymous users. When a member of one team sends a link to one of their dashboards, if the user is not logged, they won't see the dash. This causes some confusion, and also creates issues with displaying our dashboards on TVs without logging in.

**Comment by torkelo** [comment]
Organizations is not a to be used to organize dashboards. It is for multi-tenant installs. 

Anonymous mode is to turn a single grafana instance into a public instance. You can still have private non anonymous orgs. But only one can be open, otherwise all requests would have to ask "what org do you want to see"?
