### ISSUE TITLE
[Question] How to use Alias pattern with ElasticSearch?

### ISSUE THREAD

**Issue by Azef1** [grafana/grafana#4697]
Hi,
I using ElascticSearch as Source. On my graph i have two metrics, and i would like to change the name of metrics on graph:
![grafana_alias](https://cloud.githubusercontent.com/assets/15362041/14520919/29a8fe8c-0227-11e6-92f7-e9274d172cc6.png)
But when i use "Alias", this give same name for all metrics. My goal it's to replace first metric name "Min sla_duration ...' by UP and the second metric "Sum daily_2" by DOWN
How to do this ? 

I using Grafana 3.0 beta2

**Comment by torkelo** [comment]
click on alias patterns below the query to open the help box about all alias patterns

**Comment by whitelynx** [comment]
I'm running into the same issue as the OP, using Grafana 3.1.1 and Elasticsearch 2.4.0, using a direct connection from Grafana to Elasticsearch.

I've added a table panel, added a query string, added two metrics (an Average over one field, and Max over another), replaced "Date Histogram" in the Group by with two "Terms" entries to group by fields in my documents instead of grouping by time, and changed the "To Table Transform" to "JSON Data". After doing this, I'm able to see the JSON of each result in the table, but the properties holding my metrics are just called `Average` and `Max`. (I would have expected `Average duration` and `Max @timestamp` at least, and I'd like to be able to rename them)

The proposed solution doesn't help, because the text in the help box seems to assume that you always want to use the same alias for each metric in the query. (which I don't; I'd like to rename `Average` to `Average Duration` and `Max` to `Latest Build`)

Also, entering any text I can think of into the "Alias" box has no discernible effect on the resulting data. I've tried using just text (`foo`), a simple pattern as described in the help box (`{{field}}`), a `sed` expression (`s/Average/Average Duration/`), a comma-separated list of names (`Command,Environment,Average Duration,Latest Build`), and even a JSON mapping (`{"Average":"Average Duration"}`). I've checked both the console in the Chrome inspector and the Grafana server logs, and there are no errors in either. (though every time I change the "Alias", it _does_ do a new pair of requests to the Elasticsearch server)

![grafana-elasticsearch-alias-issue](https://cloud.githubusercontent.com/assets/285264/18186222/51e481f6-7067-11e6-8f69-685d8d34eeb9.png)

I'm not sure exactly what the expected effect of that single "Alias" value in the Elasticsearch source is supposed to be, given the little information contained in the "Alias patterns" help box, and I've been unable to find any information in the documentation pertaining to this... but it seems like it should do _something_.

**Comment by timtofan** [comment]
Perhaps something like graphite function aliasSub() would be perfect here.

**Comment by abaskin** [comment]
I was able to achieve the original goal by splitting the query into two queries, one per metric. Then use the name you want for the metric in the alias field.

**Comment by ZhukovAlexey** [comment]
@torkelo I'm sorry, but your solution to use doesn't suit properly for some use cases.

@whitelynx did a great explanation why

It would be really useful to make personal aliases per Metric.

**Comment by beingyash** [comment]
@torkelo Have we made any provisions to ease the above mentioned use cases? I'm facing the same problem wherein i just need to apply a regex on the metric names returned by the groupBy operation.

**Comment by johntdyer** [comment]
Any movement on this ?
