### ISSUE TITLE
Failed to open Grafana in WebOS, Tizen OS and Android TV

### ISSUE THREAD

**Issue by iuriaguiarr** [grafana/grafana#46991]
**What happened**:
When accessing the Grafana URL that is on my server through Smart TVs LG, Samsung and Sony, it returns "If you're seeing this Grafana has failed to load its application files", and when accessing another Grafana, it is possible to access it and log in.

**What you expected to happen**:
It was expected that at least the login screen would be displayed, however, only the loading and error message are returned.

**How to reproduce it (as minimal and accurate as possible)**:
Via a Samsung, LG or Sony Smart TV, access a URL of a Grafana in version 8.5.0-pre.

**Environment**:
- Grafana Version: 8.5.0-pre
- Data source type and version: N/A
- OS Grafana is installed on: Ubuntu 21.04
- User OS and browser: TizenOS, WebOS, AndroidTV.
- Grafana plugins: N/A
- Others: N/A

Note: We have already followed all the steps indicated on the error screen, such as: Reverse Proxy Verification, Grafana.ini adjustments...

Note 2: We also test in Desktop and Mobile browsers, such as Chrome, Edge, Firefox...

**Comment by mckn** [comment]
Thank you for reporting this! I might be that we do not support the browsers in the latest version of Grafana but I will forward this issue to the proper developers to investigate further.

**Comment by ashharrison90** [comment]
hi @iuriaguiarr 👋 

[we only ever claim support for the latest versions of the major browsers](https://grafana.com/docs/grafana/latest/installation/requirements/#supported-web-browsers). in order to keep improving grafana, we need to take advantage of newer and better web APIs. unfortunately it's not scalable for us to continue to maintain compatibility with TV built-in browsers that are often years behind current standards.

recommendation would probably be to either:
- switch to a setup where you have control of the browser (raspberry pi or something similar)
- continue to use an older version of grafana

appreciate that's probably not the answer you're after, but i'm sure you can understand. 🙌
