### ISSUE TITLE
[Bug] InfluxDB query duplicated db param

### ISSUE THREAD

**Issue by adrianlzt** [grafana/grafana#4703]
* What grafana version are you using? grafana-3.0.0-beta41460581169.x86_64
* What datasource are you using? InfluxDB
* What OS are you running grafana on? RHEL7.2

Queries to InfluxDB have _db_ param defined twice
```
GET /query?db=DATASOURCE&db=DATASOURCE&epoch=ms&q=SELECT...
```

The query produced in the frontend against the backend is correct:
```
api/datasources/proxy/32/query?db=sm2m&q=SELECT...
```

**Comment by torkelo** [comment]
thanks for reporting this, will fix!

**Comment by cobaugh** [comment]
I believe this fix broke proxied queries to an influxdb datasource. I was using this in a scripted dashboard, where I could specify /datasources/proxy/id/query?epoch=ms&q=myquery. Now I have to specify db=name, which is confusing because the grafana datasource already allows you to specify a database name! This also requires one to know both the name of the datasource and the name of the database in influxdb. Is that intentional?
