### ISSUE TITLE
8.3.0+ grafana dashboard json can't migrate to other instance because of datasource uid

### ISSUE THREAD

**Issue by ShenXinKang** [grafana/grafana#47119]
**What happened**:
I use grafana 8.3.4 (instance A) and create a new dashboard. I copy this dashboard's json to another grafana 8.3.4(instance B). Dashboard can't work correctly in instance B. Error is:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/19555166/161031454-01bada3c-55b0-4821-8ba2-0b8679c759ff.png">

And I found datasource's json format is changed:
on 8.2.7:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/19555166/161032482-a4d75623-acf5-4d2d-9644-df2eefc56250.png">

on 8.3.0:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/19555166/161032424-a51df461-6bd1-49a6-9833-ba12685a84cd.png">

**What you expected to happen**:
I think migrate dashboard by copy json between same version instance  shoud be work correctly.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.4
- Data source type & version: influxdb, v1
- OS Grafana is installed on: ubuntu
- User OS & Browser: chrome
- Grafana plugins: influxdb
- Others:

**Comment by ashharrison90** [comment]
hi @ShenXinKang 👋 

thanks for raising this!

you're right, the format has changed. in order to use dashboards from one instance in another instance, you'll want to check the `Export for sharing externally` option when sharing the dashboard:
![image](https://user-images.githubusercontent.com/20999846/161579030-f578f7d1-591f-41d6-96ac-2b447f8ec387.png)

this will templatize the datasource(s) in the dashboard json. when you then import the dashboard in another instance you'll be prompted to select which datasource(s) to use.

hope that helps! 😄
