### ISSUE TITLE
[Bug] Text formatting of code blocks is off

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4715]
![screenshot from 2016-04-14 15-08-49](https://cloud.githubusercontent.com/assets/3432/14540464/210cbaa8-0253-11e6-92e7-40026d644735.png)

Version: 7302dda

**Comment by torkelo** [comment]
@mattttt looks like the code element styles is not correctly applied to inline code elements in the text panel.

**Comment by mattttt** [comment]
Fixed in PR https://github.com/grafana/grafana/pull/4728

![screenshot 2016-04-15 15 01 34](https://cloud.githubusercontent.com/assets/2886187/14572145/1cdf24ca-031b-11e6-8680-a7f8188c9a49.png)


And made sure pre blocks were not impacted:
![screenshot 2016-04-15 15 01 48](https://cloud.githubusercontent.com/assets/2886187/14572142/17d6f872-031b-11e6-8d70-271058745e17.png)

Note: word-break is still break-all, which looks strange for text, but is necessary for long strings (like issuing API Keys). Not sure if it's worth changing this.
