### ISSUE TITLE
Time picker: absolute time range highlights the next day

### ISSUE THREAD

**Issue by kirederik** [grafana/grafana#47284]
**What happened**:
When selecting an absolute time range, the feedback on the UI highlights the end day + 1

**What you expected to happen**:

The background to highlight the selected range

**How to reproduce it (as minimally and precisely as possible)**:

https://user-images.githubusercontent.com/201163/161592255-8120d5a5-be31-42da-99ab-75121c14cc9a.mov

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.4.5
- Data source type & version: n/a
- OS Grafana is installed on: n/a
- User OS & Browser: OSX / Chrome
- Grafana plugins: n/a
- Others: n/a

**Comment by zuchka** [comment]
Hi @kirederik

Thanks for creating this issue. I remember seeing [similar behavior](https://github.com/grafana/grafana/issues/35290) a while ago here, but I thought it got fixed with [this PR in 8.0.3](https://github.com/grafana/grafana/pull/35829).

I had trouble reproducing this on main using a similar setup:

![CleanShot 2022-04-04 at 09 06 10@2x](https://user-images.githubusercontent.com/37156449/161614279-b8057e75-65c4-4cc8-b516-c582bdf8faad.png)

Anything else you can think of to help us reproduce?

I'm on 
OSX 11.5.2
Chrome 99.0.4844.83 (Official Build) (arm64)

**Comment by kirederik** [comment]
@zuchka I couldn't reproduce this one on main either -- the issue was recorded on play. Closing this one for now! Thanks!
