### ISSUE TITLE
Alerting: Intermittently failing test - TestSilenceCleanup

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#47470]
**What happened**:

TestSilenceCleanup is an intermittently failing test, due to sensitive handling of timestamps. Tests in the grafana repo propagate into other build pipelines, too: https://drone.grafana.net/grafana/grafana-enterprise/16959/1/11 

**What you expected to happen**:

The test to be stable

**How to reproduce it (as minimally and precisely as possible)**:

See above drone link

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by joeblubaugh** [comment]
When I added this test, I also wrote a PR in prometheus to add a fake clock in the Silences packaged. Once that's merged we can use the fake clock to make our tests perfectly deterministic: https://github.com/prometheus/alertmanager/pull/2867

I opened this discussion: https://github.com/grafana/grafana/discussions/46822, but it's not helpful here until we can inject a clock into the prometheus code.

I could make a private fork, patch in order to get that into our code before it lands in prom, but I'm not sure it's worth it.

For now, to address this issue, we could wait a longer time before verifying silence calls at the cost of longer test runs. It's still not perfect, but could get a lot better.

**Comment by alexweav** [comment]
@joeblubaugh I like the approach in your PR. In the ideal future, it'd be nice to have a set of tools available for test writers to deal with time without using flaky system clock values. But, I think this time extension strikes a good balance of fixing the test, while also leveraging what we have now - getting the test back up and running quickly is also important. Thank you for looking into this one, I appreciate it!

**Comment by joeblubaugh** [comment]
It was my test, feel free to `git blame` me in future. :-D

I really want to get that clock package into the silences bit when we can. It's used in other parts of the Unified Alerting for testing things like the scheduler.
