### ISSUE TITLE
LDAP login issue

### ISSUE THREAD

**Issue by bappan007** [grafana/grafana#47483]
**What happened**: LDAP login issue when allow_sign_up set to false.

**What you expected to happen**: LDAP login should work even when allow_sign_up is false.

**How to reproduce it (as minimally and precisely as possible)**: configure LDAP, and set allow_sign_up set to false.

**Environment**:
- Grafana version: 8.42.
- Data source type & version:
- OS Grafana is installed on: 18.04.1-Ubuntu
- User OS & Browser: Windows/Firefox 97.0.2 (64-bit)
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
This sounds like expected behavior based on the docs for enabling ldap referenced below. I'll close for now, but if pre-existing grafana users are not able to log in with allow_sign_up set to false, can you share more about what is happening and reopen the issue? 

https://grafana.com/docs/grafana/latest/administration/configuration/#allow_sign_up
https://grafana.com/docs/grafana/latest/auth/ldap/#enable-ldap 
```
# Allow sign up should almost always be true (default) to allow new Grafana users to be created (if LDAP authentication is ok). If set to
# false only pre-existing Grafana users will be able to login (if LDAP authentication is ok).
allow_sign_up = true
```
