### ISSUE TITLE
[Feature Request]  Hide pointer on graph 

### ISSUE THREAD

**Issue by Azef1** [grafana/grafana#4765]
Hi, 

I propose you, a little improvement: It's to add the possibility to hide the "pointer" on the graph.
Mockup:
![mockup](https://cloud.githubusercontent.com/assets/15362041/14641581/4ca0b46a-0647-11e6-9b1e-c7e9389e82d5.png)

For me the "pointer" it's the small circle:
![pointer](https://cloud.githubusercontent.com/assets/15362041/14641576/4713f638-0647-11e6-905f-5bd680e4c727.png)

- Pointer: false = hide the pointer
- Pointer: true = show the pointer

Why this feature ?
Because for example in my case UP+DOWN = always 24hour. I doesn't need to show the pointer DOWN  but i need to show the information (DOWN: 7.21 hour)
![example](https://cloud.githubusercontent.com/assets/15362041/14641965/dc7f37b8-0648-11e6-99f7-781a12fc7002.png)
(here UP and DOWN are stacked)

I using Grafana 3.0 beta1 with ElasticSearch

**Comment by torkelo** [comment]
I am sorry, will close this, not sure an option for this is needed, you are the first one to have ever raised this need, seems like very edge case and minor issue, and trying no limit the graph options to options that are actually used by more than 0.0001% of users :) 

Just need to say no to some options, otherwise the code base and UI will be full of toggles :)
