### ISSUE TITLE
Logout button disappears when using LDAP authentication

### ISSUE THREAD

**Issue by warshawd** [grafana/grafana#47805]
**What happened**:
When using LDAP authentication, the logout button in the bottom left of the screen is missing.

**What you expected to happen**:
The logout button to be in its usual place.

**How to reproduce it (as minimally and precisely as possible)**:
Enable LDAP auth and check the bottom left.

**Environment**:
- Grafana version: 8.4.6
- OS Grafana is installed on: linux
- User OS & Browser: Chrome, Firefox, Safari
- Grafana plugins: flant-statusmap

Expected:
<img width="606" alt="Screen Shot 2022-04-14 at 3 36 54 PM" src="https://user-images.githubusercontent.com/23515156/163489145-0c6b00a5-9708-46fe-a650-28337aff030c.png">

Actual:
<img width="560" alt="Screen Shot 2022-04-14 at 3 37 10 PM" src="https://user-images.githubusercontent.com/23515156/163489180-54a09f83-11ad-4b17-bb0d-bc7e9fd13fc4.png">

Inspect still sees it:
![grafana_logout](https://user-images.githubusercontent.com/23515156/163489207-e32b340f-c0ac-4540-8e13-07d6ed7c4af4.png)

**Comment by warshawd** [comment]
Hey @axelavargas , thanks for looking into it. Nothing special I can think of in our config - we actually had one of our users report the issue to us, and we verified the same behavior. Unfortunately I'm about to leave for a couple weeks of travel, but my coworker Jerry who worked on this story with me should be able to investigate with incognito and any other experiments.

**Comment by jessepye** [comment]
Hi @axelavargas - We are still seeing the problem in an incognito. We've also taken a look at our `grafana.ini`, but don't see any special configs that might be causing the problem. Here are a few of the relevant settings in `grafana.ini`:

```
[auth]
disable_login_form = false
disable_signout_menu = false
[auth.ldap]
enabled = true
config_file = /var/vcap/jobs/grafana/config/ldap.toml
allow_sign_up = true
```

And here is our `ldap.toml` config file:
```
[[servers]]
host = "<redacted>"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = true
bind_dn = "cn=<redacted>,ou=<redacted>,dc=<redacted>,dc=<redacted>"
bind_password = "<redacted>"
search_filter = "(cn=%s)"
search_base_dns = ["dc=<redacted>,dc=<redacted>"]
```
Anything else you can think to check?

**Comment by natellium** [comment]
@grafana/grafana-authnz-team maybe you can help with this one? We weren't able to reproduce it :)

**Comment by gberche-orange** [comment]
Also reproducing in v8.4.4.

![image](https://user-images.githubusercontent.com/4748380/193847219-0db70aa1-0878-4c97-826c-912a6c33f12d.png)
![image](https://user-images.githubusercontent.com/4748380/193847230-6171215d-216b-4ae5-b124-0745ff50aac9.png)

Workaround: manually browse to the `/logout` endpoint

**Comment by ybizeul** [comment]
v8.5.15 experiencing the same problem.

Profiles are enabled (Re: https://github.com/grafana/grafana/issues/51326)
I use a reverse proxy in front of grafana (redirecting the '/grafana' URL to Grafana), if that could be a factor.

**Comment by rimelek** [comment]
I had the same issue. Active Directory login, missing logout button. Since I have noticed this while I investigated another issue, fixing that issue made me realize the logout button was missing because it would have been in the menu after clicking on the profile icon which was also missing. When I log in using Active Directory, Grafana saves a record in the sqlite database in the "user" table. In case of an AD user, the login, email and name fields are empty.

Then I changed the fields manually and when I changed the "login" field's value to a non-empty string, the profile icon appeared. After that I found this related issue about the empty  username (login field)

https://github.com/grafana/grafana/issues/15978

The solution there was to map the "username" settiing to an LDAP field, so I mapped it to the same field which I used in the filter: `sAMAccountName` and the profile icon with the logout option appeared.

**Comment by DanielCerejo** [comment]
[rimelek](https://github.com/rimelek)  . Correct . After map the "username" setting to an LDAP field , Go to User, Delete Affected User . Login again and  profile icon reappear.

**Comment by forrejam** [comment]
For anyone having this issue, as the above users, I had to map these attributes for users to be created correctly.

[servers.attributes]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email = "mail"

**Comment by kalleep** [comment]
I could reproduce the issue. When both email and username mapping results in both empty username and email a user is still created in grafana. This should be an invalid state. We are preventing this from happening in http endpoints e.g. https://github.com/grafana/grafana/blob/main/pkg/api/admin_users.go#L60C2-L65C3. I will move this check to the user service so that this cannot happen from e.g. login sync. It would also probably be useful to add a warning log that something might be miss configured if this happens.
