### ISSUE TITLE
Explore : The inspector is not closed when navigating away from the explore view

### ISSUE THREAD

**Issue by yaelleC** [grafana/grafana#47820]
**What happened**:

In Explore, when you open the inspector and then navigate away from it (go to dashboards for example) the inspector is still open.

Screenshot:

https://user-images.githubusercontent.com/42030685/163569475-74c4982a-283a-4936-b20b-ae27b64b7e8d.mov

**What you expected to happen**:
Close the inspector when exiting the explore view?

**How to reproduce it (as minimally and precisely as possible)**:
See screenshot

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.0.0-057ff5bcpre (`ops`)
- Data source type & version: tried with Cloudwatch data source, but I suppose it's not DS related
- User OS & Browser: mac / chrome

**Comment by ifrost** [comment]
Note that it happens only when Search Dashboard is selected from the menu. This is because Search Dashboards is actually a full-page modal, so it does not navigate away from Explore. It's possible to close the modal and then Explore page is shown again. When picking anything else from the menu, the inspector disappears correctly because a different page is rendered.

@grafana/ux, @grafana/user-essentials - any reason why Search Dashboards is a full-page modal? If yes, should it cover everything all the time (in the case of Explore the inspector is on top of the modal).

**Comment by staton-hyse11** [comment]
Some of us on the UX team will be meeting to discuss this before providing any feedback.
