### ISSUE TITLE
Differentiate legacy alerting and alerting icons

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#47880]
No matter if unified_alerting is enabled or not, the alerting icon looks like this in the navbar and the Alerting view:
<img width="254" alt="PS 2022-04-11 à 18 44 11" src="https://user-images.githubusercontent.com/2117580/164008696-bd5c178c-e94c-49d2-91ad-0b7f7df2647e.png">

This does not help knowing if legacy alerting or alerting is used in an instance and a differentiation should thus be implement to quickly understand "Am I using the new alerting or not?".

**Comment by peterholmberg** [comment]
@jessover9000 can you help us with creating a new icon for either legacy or unified alerting?

**Comment by jtheory** [comment]
Attempting to split up by users' perspectives:

* **New to Grafana** (defaults to UA): no impact, won't notice anything
* **Grafana Enterprise or OSS, was auto-migrated**: trouble-shooting docs can ask them to check the icon... is this the best way? Some may have NOT migrated because there were errors, or they've set a flag... If they set the flag wrongly, they also want an easy way to check at a glance. Anyone suspecting bugs in migration (did it log a warning, but migrate anyway? What happens when we have two conflicting config flags?) also use this as a quick check
* **Grafana Enterprise or OSS, not yet migrated**:  most important for these users (and... lots of them?): reminder that they should migrate. So... we should have flyover text? Or hover popup with warning / link? (to where?)
* **Grafana Cloud, migrated OR held back**: less impt: migration is managed for them, they're getting comms already

**Comment by armandgrillet** [comment]
> trouble-shooting docs can ask them to check the icon... is this the best way?
In escalations, Cloud customers sometimes don't know if they've been migrated or not when we ask them. Having a different icon allow support to know if that happened from any Grafana screenshot (as the icon is always there on the left) and would be a bigger nudge to users to make them aware that something has changed.

**Comment by jtheory** [comment]
> > they've set a flag... If they set the flag wrongly, they also want an easy way to check at a glance
> What exactly does that mean? That the wrong flag keeps the migration from going through, or they do get migrated but with errors, or what happens in that case?

There are multiple flags that affect whether it runs legacy alerting, or migrates, or forces a re-migration. There **shouldn't** be any state that's "migrated but because of errors you're now in a broken state"; it should either migrate (maybe with warnings?) or hit errors and not migrate (and stay in legacy mode).  Basically... it's complex enough that it'll be cool to just check the icon and know what mode we're in now.

Maybe-useful thoughts about display:
* We'd expected no change for "migrated" state... but I've seen "feature highlights" before (as circles) & they're useful. We should be really careful we don't make it look like we're signaling **alarm state** (e.g. a green tick on the icon, but actually alarms are failing, could be bad)
* Another relevant pattern is "upgrade needed" like I've seen in Chrome -- I think it's a box with an up-arrow in it -- nudging you to take some action to upgrade

**Comment by amy-super** [comment]
@jessover9000 the feature highlights are @VesnaDean I believe. 

In terms of navigation, we will probably be moving away from an icon-only navbar at some point in the near-ish future. Depending on when you plan to release this, it may not end up being around for too long. I'd recommend checking out the new megamenu at https://ops.grafana.net for a peek at what the future menu direction will be and looking for ways to highlight within that framework rather than relying on icon indicators.

**Comment by peterholmberg** [comment]
A fairly quick workaround is to check the sub menu links.

Unified
![image](https://user-images.githubusercontent.com/946275/168537517-6b174d5b-e83e-4087-b7c9-d66e2e5f3145.png)


Legacy
![image](https://user-images.githubusercontent.com/946275/168537890-40262bf8-d7ad-4ed8-9d71-970b7d07ea66.png)

**Comment by jtheory** [comment]
Discussion here: https://docs.google.com/document/d/192WTqGcGjslISrdlE0_RPywodCvoqtVtF4JPkP6k6XU/edit#
Options discussed so far are "Legacy Alerting", "Alerting (deprecated)", "Alerting (legacy)"

**Comment by gillesdemey** [comment]
I prefer `Legacy alerting` over `Alerting (deprecated)` – might be misinterpreted as the entire alerting feature (including the new alerting) to be deprecated.

**Comment by peterholmberg** [comment]
Throwing in `Alerting (legacy)` in the mix

**Comment by jessover9000** [comment]
How about doing something like this? (if we can style the text)

![000 Migration legacy state_ Text-based](https://user-images.githubusercontent.com/53754871/169490595-3b026e4a-3ccf-4906-b40b-81ba69d09f4e.png)

**Comment by jtheory** [comment]
I like this ^ from Jess -- I _think_ this also addresses Gilles' worry (that they'll think the Alerting feature is deprecated).

@jessover9000 is the "Legacy" badge-thing a standard styling (with colors that we know are accessible, will also be okay in light-mode, etc.)?

**Comment by achatterjee-grafana** [comment]
I like Jess's idea - however, this seems to be only for the OSS users. 

Are we doing something similar for the cloud users? From what I understand, cloud users will not be able to see the Cloud Alerting plugin once they migrate (or if they are new users). How are we communicating with cloud users who have declined to migrate or migrated but have decided to roll back and use the Cloud Alerting plugin for now?

**Comment by achatterjee-grafana** [comment]
> Suggested change: Rename the title when hovering from "Alerting" to "Legacy Alerting". @achatterjee-grafana does this sound good to you?

Thanks, @peterholmberg. I upvoted Jess's idea.

**Comment by achatterjee-grafana** [comment]
@Eve832 and @alyssawada for visibility.

**Comment by jessover9000** [comment]
@jtheory Design wise I've used a design for "Feature Highlights" ([Figma](https://www.figma.com/file/APJdBk4ER8jB3FypFK040M/Feature-highlights?node-id=594%3A1781)). There it's usually a positive signifier for pro/paid features. I used our standard "yellow" tag color that we have in the Figma design system, but after checking you are right that the contrast there is not good enough. I guess that part of the design system needs fixing :D I pivoted to the warning notification yellow (#F5B73D) + max contrast text color (#24292E): 
![image](https://user-images.githubusercontent.com/53754871/169763344-e49fb7d6-1968-4a84-be21-dbb349448a91.png)

**Comment by jtheory** [comment]
Notes from Slack, Peter's discussion -- this menu entry text comes from the backend; we'd have to make bigger changes to make it possible to add the badge. :grimacing:

The "possible for the beta" change is to make this text only, "Alerting (Legacy)", and then see later if we can / should take more steps.
