### ISSUE TITLE
CloudWatch: Change Dimensions props to take getDimensionValues instead of datasource

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana#47892]
Currently the `Dimensions` object takes [datasource](https://github.com/grafana/grafana/blob/a4081aebb7a347d2726fc10b27e5f25658e9c672/public/app/plugins/datasource/cloudwatch/components/Dimensions/Dimensions.tsx#L12) as a prop, when it should just take the function that FilterItem needs, `getDimensionValues`.

**Comment by BusyDoingNothing** [comment]
Hello,
is still needed help for this issue? I would like to make my first contribution for this project!

**Comment by BusyDoingNothing** [comment]
Yes, I would like to!

**Comment by iwysiu** [comment]
@BusyDoingNothing go for it! 😄 If you need any help or clarification, feel free to ask.

**Comment by sarahzinger** [comment]
@ktw4071 feel free to make a pr and link to this issue thanks!

**Comment by katebrenner** [comment]
Looks like FilterItem calls [appendTemplateVariables](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/cloudwatch/components/Dimensions/FilterItem.tsx#L67), which uses the [datasource.getVariables method](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/cloudwatch/utils/utils.ts#L9).  Would likely need to pass both `getDimensionValues` and `getVariables` as props to FilterItem, and then update appendTemplateVariables to use the `getVariables` method as a parameter instead of `datasource`.  However, appendTemplateVariables is also used in several other places and would therefor need to be updated in those places as well to pass `getVariables`.  Still think it is worth doing? @iwysiu @sarahzinger

**Comment by iwysiu** [comment]
Yeah, this was just a refactor. We can close it if it doesn't make sense.
