### ISSUE TITLE
Bug: opentsdb-grafana tagk suggest queries not getting issued

### ISSUE THREAD

**Issue by abhisant** [grafana/grafana#4810]
The following suggest queries are not getting issued for latest version of grafana 3.0.0-beta3
suggest?max=1000&q=ca&type=tagk

Datasource: opentsdb
OS: MAC and Linux 

These queries are working on grafana 2.6. Are these suggest queries explicitly removed ?

**Comment by torkelo** [comment]
@utkarshcmu anything you can look at?

**Comment by utkarshcmu** [comment]
@abhisant Is this issue related to tagk suggestions in metric query autocomplete? If yes, then this is due to PR https://github.com/grafana/grafana/pull/3901. We removed querying tagk requests as we can get the tag keys associated with the metric with it in the metric query. For more details see this issue: https://github.com/grafana/grafana/issues/3610. Or is this issue with templating?

**Comment by utkarshcmu** [comment]
Grafana 3.0.0-beta6 is able to issue suggest queries. Please let us know how you are seeing this issue. I see no issues with suggest API queries from Grafana to Opentsdb. We need more details for reproducing the issue you are facing.

**Comment by abhisant** [comment]
Yes, I am mentioning about the tagk autocomplete. Looks like you have explicitly removed it.

**Comment by utkarshcmu** [comment]
Yes, tagk autocomplete does not issue any explicitly query to opentsdb because it gets that info from the metric query.

**Comment by utkarshcmu** [comment]
I do not think this is a bug as the autocomplete tagk feature is working without issuing the suggest query.

**Comment by abhisant** [comment]
Sure, closing it.
