### ISSUE TITLE
[Bug] Signature by key F86AA916A2195E121AEDB11437BBEE3F7AD95B3F uses weak digest algorithm (SHA1)

### ISSUE THREAD

**Issue by elnappo** [grafana/grafana#4816]
Ubuntu 16.04 LTS
Package: apt
Version: 1.2.10 (amd64)

```
root@bla:~# apt update
Hit:1 http://de.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://de.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [92.2 kB]
Hit:5 https://packagecloud.io/grafana/stable/debian wheezy InRelease
Fetched 92.2 kB in 2s (38.1 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
W: https://packagecloud.io/grafana/stable/debian/dists/wheezy/InRelease: Signature by key F86AA916A2195E121AEDB11437BBEE3F7AD95B3F uses weak digest algorithm (SHA1)
```

https://juliank.wordpress.com/2016/03/15/clarifications-and-updates-on-apt-sha1/

**Comment by osvalr** [comment]
This is happening

**Comment by capotej** [comment]
[packagecloud.io](packagecloud.io) engineer here, we only SHA256 sign xenial (or newer) indexes to maintain backwards compatibility with older APT clients that expect SHA1 signatures, hence why you get the above warning installing a `debian/wheezy` repository onto an `ubuntu/xenial` system.

To fix this, grafana will have to push a version of their packages to `ubuntu/xenial`, rather than installing it through another distribution.

**Comment by capotej** [comment]
We've tested and enabled SHA256 signatures for `debian/wheezy` for grafana, this should no longer be happening.
