### ISSUE TITLE
Docs: configuration should show list of feature_toggles that can be enabled

### ISSUE THREAD

**Issue by mmandrus** [grafana/grafana#48299]
**What happened**:
I was attempting to set up custom roles as explained in the [access-control/provisioning docs](https://grafana.com/docs/grafana/latest/enterprise/access-control/provisioning/). I got to the page through a series of links that bypassed the top-level FGAC page, so I didn't know there was a configuration step I needed.

When I got to the configuration section of the docs, I only saw that there is a feature_toggles.enable option, but still didn't know which flag to use. I eventually found the right flag by digging through code, and then someone else pointed out that the exact flag I needed was on a different docs page.

**What you expected to happen**:
It would be helpful to list all of the feature toggle options here, with links to the specific pages that talk more about each option. It should be broken down by OSS and enterprise features.

**Environment**:
- Grafana version: v8.5.x

**Comment by mellieA** [comment]
The link here to fine-grained access control on the page you mentioned: 
![Screen Shot 2022-04-28 at 12 28 46 PM](https://user-images.githubusercontent.com/18175287/165821970-f6646fd9-d0de-44f4-8f9a-d7c288026900.png)



The link for fine-grained access control directs to this page that mentions enabling the feature: 

![Screen Shot 2022-04-28 at 12 30 18 PM](https://user-images.githubusercontent.com/18175287/165822205-aca6354c-b1e0-42bd-a4c1-78ea24ebf6d0.png)



That link goes to here: 

![Screen Shot 2022-04-28 at 12 30 56 PM](https://user-images.githubusercontent.com/18175287/165822297-ca0533e8-38ae-4d08-9322-139090953159.png)

I realize that it's a few links deep. What do you suggest we change to make it easier to find? Keep in mind, that feature toggles are only temporary for alpha features, so once the feature is GA, the toggle is no longer needed. I'm wondering if that's why the docs team has designed the page this way.

**Comment by mellieA** [comment]
Feature toggles are documented here https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/
