### ISSUE TITLE
Save dashboard appears without made changes

### ISSUE THREAD

**Issue by agido-malter** [grafana/grafana#48304]
**What happened**:
After viewing the dashboard, scroll around and switching to another, a dialog box always appears asking you to save the dashboard. 
If you still save, then the next time you open and close the dashboard, everything repeats again.

**What you expected to happen**:
Open dashboard, scroll and switch to another dashboard without ask for save chages

**How to reproduce it (as minimally and precisely as possible)**:
Open dashboard, scroll and switch to another dashboard

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.0
- Data source type & version: prometheus: latest, cloudwatch: latest
- OS Grafana is installed on: Amazon Linux 2
- User OS & Browser: macOS Chrome: latest
- Grafana plugins: grafana-renderer
- Others:

**Comment by zuchka** [comment]
see also:

https://community.grafana.com/t/after-upgrading-to-8-5-0-dashboards-behavior-changes/64641/2

**Comment by torkelo** [comment]
Sometimes Grafana makes migrations to the dashboard schema, this can cause this modal to appear. 

We have a partial fix to this, in https://github.com/grafana/grafana/issues/48310  which will show the changes

**Comment by agido-malter** [comment]
Please reopen ticket, because it is a bug. It happens on each minor update of grafana, see screenshot of the changes @torkelo
![Grafana-2022-05-16](https://user-images.githubusercontent.com/34912574/168586160-5148255d-0553-4f53-8ab1-24cd6536726c.jpg)

**Comment by junior466** [comment]
Could we please reopen this? I am on the latest version and this issue won't go away no matter how many times I save.

**Comment by vshaev** [comment]
I also have no changes from version to version. Viewing the panels turned into torture. The link to solution #48310 is useless.

**Comment by agido-malter** [comment]
It's more worst that you think. After each Grafana Update, the story starts againbecause it stores the version number on each panel

**Comment by agido-malter** [comment]
@torkelo @zuchka This is definitely a major bug

**Comment by hhromic** [comment]
@torkelo thanks for the fix! I'm also facing the same issue.
I noticed that your fix is scheduled for Grafana `9.1.0`. Would it be possible to backport it to `8.5.x` series?
We just upgraded to `8.5.6` an this bug is _very_ annoying. We normally wait for newer Grafana versions to mature before upgrading, hence why a fix to `9.x` series only is sad for us. Otherwise we will have to revert to `8.4.7` which is the last working version.

Note that in our case, `pluginVersion` is not the attribute changing, but "random" attributes changing back and forth without actual human-made changes to the dashboards. As others have mentioned, no matter how many times we save, the modal almost always shows up again. Let me know if you would like me to provide more details such as diffs or if your PR takes care of all that already.

Thanks!

**Comment by heyrod** [comment]
We are planning to upgrade to Grafana 8.5.14 (the later versions are not compatible with our data sources) and this bug is really annoying. Is there any way to stop these messages?
![image](https://user-images.githubusercontent.com/39294778/201298118-3cc563b3-90eb-43c7-a7ad-bc04719c7912.png)
