### ISSUE TITLE
Timezone support for mute timings

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#48508]
What means "Monday" if I'm based in Sidney? It means that I will not have alerts muted during my Monday morning.
<img width="542" alt="PS 2022-04-29 à 11 37 30" src="https://user-images.githubusercontent.com/2117580/165920818-caffacb8-d670-4948-bf95-bd0519125be2.png">

On the engineering side, mute timings are taken care of by the alertmanager within Grafana which is based on the Prometheus Alertmanager and it also doesn't have this feature.

**Comment by tennox** [comment]
Have you verified that your TZ environment variable is set correctly? (if you are using a hosted instance) 

Disclaimer: I have no knowledge of grafana's code and cannot asses if it might be a bug on their side 💁‍♂️

**Comment by tennox** [comment]
Then again, trying it myself - I do see some issues with it:
```
dc exec grafana date
Sat May  7 00:46:49 CEST 2022
```

And tried a mute timing from 0:00-6:00 - and was awoken at 0:15 😓 

Then I had to fiddle my way around dubious UI error Snackbars "Error: Bad request data" (which meant to tell me that 00:00 wasn't valid as end time - granted, I should've known this, but the error wasn't telling me in which section of the settings I have an error, so it took me a while :/ )
![Screenshot_20220507-004154__01](https://user-images.githubusercontent.com/2084639/167225537-483d889b-e3c3-457a-9e23-4007d245d167.jpg)



... I will write again >= tomorrow night if that wasn't my issue

**Comment by brunobastosg** [comment]
Same problem here. I have a mute timing from 00:00 to 07:00. Under Preferences, timezone is set to America/Sao_Paulo (UTC-3).

However, I start receiving alerts daily at 4:00.

Right now I'll change the mute timings to take the timezone into account, but it would be great to have this feature.

**Comment by KyrumX** [comment]
This feature would be nice to have. Especially when DST kicks in.

**Comment by sathieu** [comment]
This has been done in alertmanager with https://github.com/prometheus/alertmanager/pull/2782.

Porting should be possible.

**Comment by zackman0010** [comment]
This would be nice to have to handle DST. As a workaround currently, I'm expanding the range so that my desired range will always be covered, just with one extra hour on either the front or back depending on DST.
Example: For midnight through two in CST, midnight would be 06:00 UTC and two would be 08:00 UTC. In CDT, they are 05:00 UTC and 07:00 UST. So the time I end up setting is 05:00 UTC - 08:00 UTC. This translates to 23:00-02:00 CST and 00:00-03:00 CDT, which covers my desired range of 00:00-02:00 in both CST and CDT. However, it would be much more convenient to just be able to use time zones.

**Comment by dsaintilma-flinks** [comment]
This would welcomed as a new feature.
