### ISSUE TITLE
grafana 3.0b7 - Unsaved changes warning is thrown after expanding/contracting row

### ISSUE THREAD

**Issue by dutchiechris** [grafana/grafana#4863]
grafana 3.0b7 + Graphite ds

I have about 20 templated dashboards which are imported by a customer as part of an integration pack.  With Grafana 3.x I have noticed that if I expand a row and try to browse away the 'unsaved changes' warning will be thrown in some cases.  I can't pinpoint the situation that causes the warning.  How can I troubleshoot?

**Comment by torkelo** [comment]
I could not replicate this. It is probably caused by some panels missing some settings in the panel json model, so when you expand the panels will be loaded and fill in missing properties (with default values), and will case an unsaved changes warning. 

try expand and collapse rows then save the dashboard.
