### ISSUE TITLE
[Feature Request] Allow shared Axis min/max across repeating graph panels

### ISSUE THREAD

**Issue by toddwh50** [grafana/grafana#4880]
It would be helpful if there ways a way that the axis min/max values for a repeating panel could be configured to be shared across the repeats.

For example, see below:
![image](https://cloud.githubusercontent.com/assets/17885456/14958626/3b71b284-1051-11e6-901e-6e78a5477e12.png)

Two of the repeated panels have a y-max of 150 and one has a y-max of 100.

For a viewer of the resulting dashboard that is not close enough to notice the axis values, it would appear that the values in the 3rd repeat are higher than the 1st and 2nd repeat values.

I know that I can enter a fixed y-axis max, but these values vary enough that I cannot know what a reasonable max value should be.

If such a "[x] Shared Axis Min/Max" setting is selected, the min and max for all panels should be calculated based on the min and max values across all panels.

**Comment by torkelo** [comment]
This is not possible (or would be incredibly complicated), as the automatic min/max is determined by each panel individually after the data query returns. For this to work all panels would need to wait for all data and then sync min/max. 

You can specify y min/max in the graph options. That way the min/max will be the same. But for automatic y min/max it is going to be automatic per panel.

**Comment by akuz** [comment]
I would like to argue against the "incredibly complicated" evaluation of this request. The individual panels don't need to wait for other panels, the common min/max could be updated by the container every time a child panel receives new data, and then the propagate the common min/max down to each child panel to set as limits. If anything, I would say this feature would be incredibly useful. It's disappointing to see this feature still being requested in 2021 (other submitted issues), and the creators seem to keep thinking it's useless. In fact, this is one of the key aspects of how the data should be presented for comparison of multiple graphs. All other plotting libraries have it (e.g. matplotlib sharey).

**Comment by leeoniya** [comment]
> and the creators seem to keep thinking it's useless

it's not useless, and we actually have something like this in the Stat panel with its repeat option. the data, of course, has to be available all at once, as is the case for a single query done by the panel.

> All other plotting libraries have it (e.g. matplotlib sharey).

from what i can tell about their example [1], matplotlib requires all the data for subplots (where sharey is used) to be available synchronously and up-front.

your claim that all other plotting libraries have this is proveably false, and those that do have this feature it very likely has to await and coordinate _all_ the data before anything can be shown (as mentioned above).

cross-panel coordination (with each having its own async lifecycle) is a hard problem. just because something is requested by people does nothing to move it forward.

this is similar in scope to the request where many people wish to align y axis widths across multiple panels, and my reply can be used pretty much verbatim: https://github.com/grafana/grafana/issues/4469#issuecomment-871077067

[1] https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplots.html

**Comment by chrs-myrs** [comment]
Being able to use a variable value for the Y-Max would get us part of the way there.  The charts y-axis updating as the data come in would be fine from my point of view.  As a heavy grafana user, this is something I've wanted to do many times and got frustrated with.

**Comment by ErikEngerd** [comment]
See [this issue](https://github.com/grafana/grafana/issues/3935). That was implemented in 2016, then reverted 'due to issues'. And since then it has never been implemented. There is another feature 'config from query' for the transformations to compute the min and max from the query results, but that does not address the issue of multiple panels having the same y-axis range. 

The surprising thing is that there have been patches by end-users already that seemed to work and that were never included. In principle, it should be possible to use a variable anywhere in a dashboard definition. Then the dashboard shown (the instance) would be obtained by substituting all the variable values in the dashboard definition. 

In addition it would still be extremely useful to have different panels optionally have the same y-axis range. This is very common in visualizations to support comparing values. Also, interactive tweaking of the ranges would be useful. Sometimes, there are peaks in one series that you wish to ignore because the peaks in one of the panels would cause the y-range to become too big. So, indeed it would be harder to implement that feature where different panels have the same y range. 

However, why is allowing variables in the axis configuration so difficult when there have already been proposed patches for this?

**Comment by silashansen** [comment]
It's almost the end of 2025 and it would still be useful.

I was surprised to stumble over my own comment above, as I was searching this feature once again. Is it just me?? Am I doing something wrong in wanting people to be able to easily compare values across panels without fixed limits?

**Comment by ErikEngerd** [comment]
You are not alone. I see the issue is closed but there is no comment given as to why.

**Comment by michalhosna** [comment]
I found a way to do it! Sharing for others that may stumble on this issue. 

1. You need to set up a query that will return your desired max and min. Any type of query can be used. 
2. That you can use [Config from query results.](https://grafana.com/docs/grafana/latest/visualizations/panels-visualizations/query-transform-data/transform-data/#config-from-query-results)

That way, you can calculate your desired shared min/max values

<img width="588" height="608" alt="Image" src="https://github.com/user-attachments/assets/8e05dd83-87ed-4c2c-ac72-d9c26b8163bf" />

Hint: Don't forget about the mixed "datasource" so you can mix and match different sources in a single panel.

<img width="852" height="157" alt="Image" src="https://github.com/user-attachments/assets/358faa74-6fc9-42d9-941b-634b5071e96c" />
