### ISSUE TITLE
CloudWatch Logs: "multi template variables are not supported for queryString"

### ISSUE THREAD

**Issue by Hazzard17h** [grafana/grafana#48806]
**What happened**:
Using multi template variable inside CloudWatch Logs query shows popup error, even if the query works well.

**What you expected to happen**:
The popup error is not shown.

**How to reproduce it (as minimally and precisely as possible)**:
Create multi-value variable, eg:
![image](https://user-images.githubusercontent.com/25725678/167113878-37c7bd0c-41f7-43a3-927b-12e9acb2dab2.png)

Use multi template variable inside CloudWatch Logs query, eg: `filter pod_name in [ ${pod:doublequote} ]`

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/25725678/167113561-130047e0-7d16-4a55-86eb-401bda1b94e8.png)

**Environment**:
- Grafana version: 8.5.0
- Data source type & version: CloudWatch
- OS Grafana is installed on: Linux
- User OS & Browser: Windows, Chrome 100

**Comment by sarahzinger** [comment]
@Hazzard17h Thanks so much for opening an issue! 

I was able to reproduce this easily by creating a custom multi-variable: `awsRegion, eventId` and then trying to use that in a cloudwatch logs query: 

```
fields @timestamp, @message, $varName |
sort @timestamp desc |
limit 25
```

If I selected just one of the template variables, the query works but throws the error (which seems rude tbh)

and if I selected both it sent the following query to the backend:
``` fields @timestamp, @message, {awsRegion,eventId} |sort @timestamp desc |limit 25```

which feels like we just need to get rid of the `{}` and it should work just fine? I see that we are throwing this error ourselves  here:

https://github.com/grafana/grafana/blob/e16dc72c94efe91dab1e85343e7a1a14aba6a0c6/public/app/plugins/datasource/cloudwatch/datasource.ts#L895

which indicates to me that this limitation is probably by design, but it seems possible to me we might want to revisit as it seems like a useful feature request. I'll put this in our backlog as something that would be good to investigate if there is a good way for us to add support for this feature or at least give good documentation on why it is not supported.

**Comment by Hazzard17h** [comment]
@sarahzinger you can simply use `${varName:csv}` in the query and see that to the backend it is sent `fields @timestamp, @message, awsRegion,eventId`...
The problem is not with the variable and template interpolation that are working as expected, the issue is about the error message that is misleading, exactly because the variable/template and the final query are working.

**Comment by jrc** [comment]
I'm hitting this too. Either I need to set up a second variable that's not multi-select and have 2 similar but different variables (I'm worried this will be confusing for dashboard users) or disable multi-select (not ideal).

**Comment by sunnygoel87** [comment]
> @sarahzinger you can simply use `${varName:csv}` in the query and see that to the backend it is sent `fields @timestamp, @message, awsRegion,eventId`... The problem is not with the variable and template interpolation that are working as expected, the issue is about the error message that is misleading, exactly because the variable/template and the final query are working.

@Hazzard17h - Are you saying that even though Grafana throws an error but underlying query is working fine ? You're able to get the results ??

**Comment by Hazzard17h** [comment]
> > @sarahzinger you can simply use `${varName:csv}` in the query and see that to the backend it is sent `fields @timestamp, @message, awsRegion,eventId`... The problem is not with the variable and template interpolation that are working as expected, the issue is about the error message that is misleading, exactly because the variable/template and the final query are working.
> 
> @Hazzard17h - Are you saying that even though Grafana throws an error but underlying query is working fine ? You're able to get the results ??

Yes

**Comment by kylehounslow** [comment]
Hi all. Users of Amazon Managed Grafana are also seeing this issue. Even if the query succeeds, we still get the distracting error message as shown in the example below: 
![image](https://user-images.githubusercontent.com/7102778/210660931-38dd1895-8941-45e3-8964-dc835d377f9f.png)
>I'll put this in our backlog as something that would be good to investigate if there is a good way for us to add support for this feature or at least give good documentation on why it is not supported.  

@sarahzinger any chance there's an ETA on the backlog item I can share with customers? Thanks

**Comment by 0xF4D3C0D3** [comment]
I bumped too 
![image](https://user-images.githubusercontent.com/19762154/210709414-fe0a7764-a04a-482d-b7c4-7c819d78f554.png)

the query seems ok though grafana gives me unaccountable errors

**Comment by sarahzinger** [comment]
Will talk to the team and see if we can bump this to a higher priority, thanks for the feedback!
