### ISSUE TITLE
UX: Page footer

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#4889]
Began work on a page footer that should be visible on all pages except dashboards (at least when side menu is non pinned).

![image](https://cloud.githubusercontent.com/assets/10999/14976678/02c7a822-110e-11e6-8dca-7f5dd69cc998.png)

It is very tricky however to place this footer correctly as main-view class has height 100& and page-container is also height 100%,  so if the footer is outside these elements it will always be below and trigger a scroll bar. I would like top have it defined on all pages automatically (which is why it is now defined in views/index.html). 

The only solution I have found is to remove the max-height on the main-nav / page-container. 

@mattttt do you have any thoughts on this? (placement / look and feel / links)

**Comment by bulletfactory** [comment]
We implemented the min-height so that the background "container" color
always stretched to the bottom because it felt very anemic without any
other content below it. The bg color gave the page some balance and form.
With the footer content added, I don't mind not having the background stop
right after the end of the page content. This will also feel less weird as
more content goes into the plugins page.

The links we can chat about, but I think we need to put some thought on the
styling - these (at least in the screenshot) seem a little large, and too
prominent. I would step back the color/size and make some real icons for
docs and support (which you might have already had in mind).

**Comment by mattttt** [comment]
Pretty much agree with all of that, without having to have thought of it myself 👍

**Comment by torkelo** [comment]
any progress on this?

**Comment by bulletfactory** [comment]
Will try and make progress today.
