### ISSUE TITLE
Legacy alerts: alerts can't created when dashboard import for the first time without a save

### ISSUE THREAD

**Issue by ShenXinKang** [grafana/grafana#48902]
**What happened**:
this bug will happen on v8.x+： 
I import a dashboard to grafana with alerts：
<img width="868" alt="image" src="https://user-images.githubusercontent.com/19555166/167862455-54be18ab-6472-4c81-8015-b0474cbf7a1c.png">
I can see alerts on UI
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/19555166/167862563-ebd29f40-c646-40f3-9ef9-71405718816a.png">
but can't find alerts on alerts list:
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/19555166/167862750-83299163-4e60-4dbe-b136-3228d8812ded.png">
back to the dashboard and save it

now I can see alerts just created:
<img width="1477" alt="image" src="https://user-images.githubusercontent.com/19555166/167862911-52efbd6e-e2cd-4b20-8d71-7a12837908ee.png">

**What you expected to happen**:
I think when first import, alerts should create

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.4
- Data source type & version:
- OS Grafana is installed on: Docker
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by alexweav** [comment]
Hello, this request seems to be very specific to legacy alerting, and doesn't apply to unified alerting since alerts are no longer bound to dashboards.

We aren't currently accepting feature requests that are specific to legacy alerting, since all of legacy alerting is now deprecated. Have you tried upgrading to 9.0 and testing out the new unified alerting?
