### ISSUE TITLE
Tempo fails to report error parsing trace

### ISSUE THREAD

**Issue by connorlindsey** [grafana/grafana#49265]
**What happened**:
Tempo fails to report an error parsing traces when querying by trace ID. See this issue in the Tempo repo to reproduce: https://github.com/grafana/tempo/issues/1432. 

**What you expected to happen**:
An error appears after querying by trace ID

**How to reproduce it (as minimally and precisely as possible)**:
- Setup tempo based on the Tempo issue linked above
- Query by trace ID - it silently fails
- Query tempo directly to get the trace as JSON
- Upload to the 'JSON file' tab and see a relevant error

**Comment by RayHong82** [comment]
Hello, may I know if the issue is fixed already?
We are using tempo single binary approach, with local storage for trace. 

We noticed above error from time to time, even for same trace id: some times it's successful; sometime it failed.

What can be used for troubleshooting? Please kindly advise, thanks a lot!

**Comment by connorlindsey** [comment]
This issue is still open. Could you share a bit more about what you're experiencing? A few places to check:
- Console logs
- Grafana inspector - what does the response look like? Any errors there?
- Tempo logs

If you can query Tempo directly (via curl or something else) and verify the trace that isn't appearing in Grafana is in fact in Tempo, that'd help to diagnose the bug.

**Comment by RayHong82** [comment]
Hi Connor,
  Thanks for getting back to me.
 Actually I realize this might be a red-herring only.

However, we do noticed that the even with same traceId, when we query for
the trace via query frontend:3200, we sometimes got valid trace back,
sometime it returns as 'trace_not_found'. Note we actually use "*local*" as
storage.

Attached is our yaml file where we are using *scalable-single-binary *
config.
We actually only have 2 hosts:
*10.70.172.19*
*10.70.172.20*

Both have installed and served single tempo server, and use local storage.

And the command line to test with the query is:

*curl -G -s
http://10.70.172.20:3200/api/traces/ffa22c6d3a74a927409f015b4b64c352
<http://10.70.172.20:3200/api/traces/ffa22c6d3a74a927409f015b4b64c352>*

*Appreciate if you could kindly advise:*
*1) Is it ok to set scable-single-binary for multiple hosts that have
[local] as storage? If yes, how shall we configure them.*

*2) From what we tested, it appears that even though I send http request to
an IP address, it still has chance to pass the request to another host.
Does it mean the query frontend will always distribute traceByID request to
either one of them? If so, does it just return the response from the
forwarded host as the final response?(which could explain since that host
may not have the data on its own local storage). How shall we modify code
to fix this is this is by design.*

*Thanks a lot!*
*Jing *

**Comment by RayHong82** [comment]
```
server:
  http_listen_address: 0.0.0.0
  http_listen_port: ${HTTP_PORT}
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: ${GRPC_PORT}
  grpc_server_max_recv_msg_size: 4194304_000000
  grpc_server_max_send_msg_size: 4194304_000000
  log_level: debug

search_enabled: false

query_frontend:
  query_shards: 256
  max_outstanding_per_tenant: 256

querier:
  query_timeout: 30s
  max_concurrent_queries: 20
  frontend_worker:
    frontend_address: tempo.recommend.shopee.io:9090

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:${RECEIVER_PORT}

ingester:
  lifecycler:
    id: ${RING_ID}
    interface_names:
      - bond0
    ring:
      replication_factor: 1
      kvstore:
        store: etcd
        etcd:
          endpoints:
              - http://node0.3e9fed8a211f197c.etcd.cloud.xxxx.io:12058
              - http://node1.3e9fed8a211f197c.etcd.cloud.xxxx.io:12058
              - http://node2.3e9fed8a211f197c.etcd.cloud.xxxx.io:12058
              - http://node3.3e9fed8a211f197c.etcd.cloud.xxxx.io:12058
              - http://node4.3e9fed8a211f197c.etcd.cloud.xxxx.io:12058
  trace_idle_period: 10s
  max_block_bytes: 1_000_000_000
  max_block_duration: 5m
  flush_check_period: 3s
  concurrent_flushes: 128

compactor:
  compaction:
    compaction_window: 12h
    max_block_bytes: 20_000_000_000
    block_retention: 72h
    compacted_block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /data/trace/tempo-data/blocks
    block:
      bloom_filter_false_positive: .01
      index_downsample_bytes: 1000
      encoding: zstd
    wal:
      path: /data/trace/tempo-data/${INS_NAME}/wal
      encoding: zstd
    s3:
      bucket: tempo
      endpoint: deep.s3.sto.shopee.io
      access_key: 4PS16R63NWGYWVLGG7L7
      secret_key: Fmwt5PxOqeKcnmBBMCDSoHPwLBbjgZgNVuNjb3gl
    pool:
      max_workers: 100
      queue_depth: 1000

overrides:
  ingestion_burst_size_bytes: 15000000_000000
  ingestion_rate_limit_bytes: 15000000_000000
  max_bytes_per_trace: 0
  max_traces_per_user: 0
  metrics_generator_processors: [span-metrics]

metrics_generator_enabled: true

metrics_generator:
  ring:
    instance_id: ${RING_ID}
    instance_addr: 10.70.172.19
    instance_interface_names:
      - bond0
    kvstore:
      store: etcd
      etcd:
        endpoints:
            - http://node0.3e9fed8a211f197c.etcd.cloud.xxxx.io:12058
            - http://node1.3e9fed8a211f197c.etcd.cloud.xxxx.io:12058
            - http://node2.3e9fed8a211f197c.etcd.cloud.xxxx.io:12058
            - http://node3.3e9fed8a211f197c.etcd.cloud.xxxx.io:12058
            - http://node4.3e9fed8a211f197c.etcd.cloud.xxxx.io:12058
  processor:
    span_metrics:
      dimensions: [ "rcmd_service", "scenario", "env", "method", "country", "strategy" ]
      service_map_path: /home/trace/configs/service_map.json
  registry:
    external_labels:
      source: tempo
      cluster: backend
  storage:
    path: /data/trace/tempo-data/generator/wal
    remote_write:
      - url: http://10.70.172.18:9090/api/v1/write
        send_exemplars: true

```

**Comment by connorlindsey** [comment]
cc @joey-grafana @grafana/tempo
