### ISSUE TITLE
Ctrl + S keyboard shortcut doesn't work reliably for saving dashboards

### ISSUE THREAD

**Issue by PAI5REECHO** [grafana/grafana#49361]
**What happened**:
The keyboard shortcut <kbd>Ctrl</kbd>+<kbd>S</kbd> for saving a dashboard doesn't work reliably. Often times it just executes the default web browser action of saving the current HTML page to disk (i.e. `<dashboard title> - Grafana.html`)

**What you expected to happen**:
<kbd>Ctrl</kbd>+<kbd>S</kbd>should always work reliably for saving dashboards
**How to reproduce it (as minimally and precisely as possible)**:
Edit some panel, back out to the dashboard view, hit the keyboard shortcut <kbd>Ctrl</kbd>+<kbd>S</kbd>
**Anything else we need to know?**:
I'm using Firefox as my web browser and a Wayland-based window manager on Linux, although I don't think this is contributing to this issue.

**Environment**:
- Grafana version: `8.5.3` (`docker.io/grafana/grafana-enterprise:8.5.3`)
- Data source type & version: `Prometheus 2.29.2`
- OS Grafana is installed on: `Linux 5.17.5, NixOS, 22.05 (Quokka), 22.05.20220512.d89d7af` (`grafana/grafana-enterprise:8.5.3` on `Docker version 20.10.15, build v20.10.15`)
- User OS & Browser: `Linux 5.17.5, NixOS, 22.05 (Quokka), 22.05.20220512.d89d7af` & `Firefox 99.0.1`
- Grafana plugins:
```
aidanmountford-html-panel @ 0.0.2
citilogics-geoloop-panel @ 1.1.2
cloudflare-app @ 0.2.4
fetzerch-sunandmoon-datasource @ 0.2.1
flant-statusmap-panel @ 0.5.1
grafana-clock-panel @ 1.3.0
grafana-image-renderer @ 3.4.2
grafana-kubernetes-app @ 1.0.1
grafana-piechart-panel @ 1.6.2
grafana-worldmap-panel @ 0.3.3
natel-plotly-panel @ 0.0.7
raintank-worldping-app @ 1.2.9
redis-datasource @ 2.1.1
vonage-status-panel @ 1.0.11
yesoreyeram-boomtheme-panel @ 0.2.1
```
- Other: Linux window manager/compositor: `sway version 1.7`

**Comment by polibb** [comment]
Tested this in multiple environments and got the same result. I can see how `mod+S` can be considered inconsistent.
`mod+S` can be used to save the dashboard you are working on, but only as long as none of the input fields is currently in focus. Once you have focused the cursor on any field, `mod+S` always asks to save the current HTML page to disk, instead of saving the dashboard. 
As of now we do not support `mod+S` shortcut on a focused field.
However, I do see how this is useful and suggest you open a feature request in the [github discussions](https://github.com/grafana/grafana/discussions), if you think it's important. Depending on the community engagement we may see to it in the future.

**Environments:**

Grafana version: `8.5.3`
OS: `Linux 5.13.0-14-generic, Ubuntu 20.04.4 LTS`
Browser: `Firefox 99.0.1`

Grafana version: `8.5.3`
OS: `Linux 5.13.0-14-generic, Ubuntu 20.04.4 LTS`
Browser: `Firefox 100.0.2`

Grafana version: `9.0.0`
OS: `Linux 5.13.0-14-generic, Ubuntu 20.04.4 LTS`
Browser: `Firefox 99.0.1`

Grafana version: `9.0.0`
OS: `Linux 5.13.0-14-generic, Ubuntu 20.04.4 LTS`
Browser: `Firefox 100.0.2`

Grafana version: `9.0.0`
OS: `macOS 12.4`
Browser: `Chrome 102.0.5005.61`

**Closing** this issue because it is a feature that is not supported.
