### ISSUE TITLE
Refactor usage of datasourceId and/or datasourceName in favor of datasource UID

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#49496]
Find all usages of datasourceId / datasourceName and investigate if we can switch over to using a datasource ref or datasource UID.

- Change Rich History files to pass references to datasources by UID. They will still use datasource name for display purposes. Rich history entries are already saved with datasource UIDs.
- Change URL state to use UID but support lookup by name to be backwards compatible. We do not plan on deprecating non UID URLs because the root datasource lookup functions support both name and UID for lookup. We will look into changing this if/when the datasource service does.
- `TraceView` uses datasource name to generate the title for a data link if one is not provided. We will use the UID for the URL itself
- Change `ExploreToolbar` to pass uid to the datasource picker
- Fix relevant tests

**Comment by gelicia** [comment]
Looking at usage in explore, I see the following
- Use of the name in rich history. The datasource is saved by UID, and some usage will be legitimate for display purposes, but we can refactor some things to do comparisons by UID instead of by name
- A usage in `ExploreToolbar` that can be easily refactored out
- Use in the Url state. I'm not sure we would want to keep an entire object in the URL but replacing name with UID makes sense to me, unless we want the URL to be more human readable.

Any objection to swapping "in favor of DatasourceRef" to "in favor of UID" ? @Elfo404

**Comment by gelicia** [comment]
> my main concern with this is making sure existing URLs will work after the refactor, having fancy URLs id not really a concern imho as they are practically not really human readable already.

Sounds good, updating the title and description
