### ISSUE TITLE
[Feature Request] Include selected metrics when sharing a dashboard

### ISSUE THREAD

**Issue by farzadpanahi** [grafana/grafana#4951]
grafana ver 2.6.0

Right now if I select couple of metrics on a graph panel and I want to share the dashboard with the only selected metrics, the share function will ignore the selected metrics and basically what is shared will be different from what you see when you are sharing. 

That would be great to have an option like the one there is already for time-range to include the selected metrics only when sharing. This will make it possible to share what you see on dashboard with your selected metrics only.

Thanks

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!

**Comment by pdf** [comment]
A closed issue is highly unlikely to garner any upvotes, this policy seems flawed.

With that said, let me explain a use-case for this feature:
I have a panel that monitors many endpoints. I wish to share the the output for a single metric related to a client or a supplier, however the other endpoints monitored may be sensitive, since they relate to other clients/suppliers, and those metrics cannot be shared with the intended recipient.

Currently the only way to do that would be to create a new panel for that specific endpoint, and set up all the parameters again, then export it. If this need to share arises from some sort of outage or other time-sensitive issue, this is a very painful requirement. Setting up all the required per-endpoint panels ahead of time would be extremely laborious, and it's not always predictable which specific custom panels may need to be created for this scenario.
