### ISSUE TITLE
Alertmanager Datasource: Handle mimir alertmanager tenant not having a configuration

### ISSUE THREAD

**Issue by gotjosh** [grafana/grafana#49728]
The mimir Alertmanager is a multi-tenant system. To save on compute costs, tenants are not active until they have a configuration set.

Mimir offers a flag that allows you to set a `fallback configuration`:

```
 Filename of fallback config to use if none specified for instance.
# CLI flag: -alertmanager.configs.fallback
[fallback_config_file: <string> | default = ""]
```

When this flag is present, the first request of a tenant that does not have a configuration will create one and start the instance on the fly. This is so that requests would never fail.

When this flag is not present and the tenant is yet to create a configuration, the response from the server will be "the Alertmanager is not configured"  and return a `404` status code. This will effectively fail the Grafana health check but technically, you can create an Alertmanager configuration for this datasource.  

I think Grafana should handle this more gracefully and detect that a case of configuration not being present but can be created via the Unified Alerting UI.

**Comment by jtheory** [comment]
Trying to assess the priority, things I don't know:

* how many users are affected? Anyone using the Mimir alert manager without using a fallback config -- and that's not a default thing, looks like, so probably most users of Mimir alert manager who haven't yet handled config, I think?
* This is poor UX; but not a technical blocker, I think? It's confusing + misleading but everything will work once they find out the problem is missing config. So.. I guess our fallback for now is user frustration & more support needed.
* What are the fix options? (+ approx effort/complexity guess). I'm guessing there's a bigger UX flow fix, where choosing the Mimir alert manager includes checking its state so we can guide the next required step.

**Comment by peterholmberg** [comment]
@gotjosh is this a problem when you're setting up the data source? Or when you want to configure the alertmanager via the alerting ui?

**Comment by gotjosh** [comment]
It manifests itself in both - it fails the datasource check and then it's not available for configuration in the unified alerting UI.

**Comment by peterholmberg** [comment]
The idea moving forward is that we can try utilize the buildInfo endpoint which for now only seems to be used for prometheus data sources. This will return `application: Grafana mimir` for mimir alertmanagers and we can use that information to allow creating notification policies, contact points etc even if there's no alertmanager config present (the api will create one when you post a notification policy for example).

This is however quite a bit of work and nothing we want to do in G9 since the last beta is planned for Monday 6/6. We'll plan this post G9 and have something for 9.1 cc @gotjosh

**Comment by Fantaztig** [comment]
Another way to work around this could be to add the ability to configure the fallback config to the mimir helm chart/jsonnet and provide a very plain default fallback config in the default values.yaml.
