### ISSUE TITLE
Folder Management: Deleting a folder doesn't immediately remove it from the UI

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#49941]
**What happened**:

Deleting a folder in the UI doesn't immediately remove it from the list.

**What you expected to happen**:

The folder to disappear from the UI. 

**How to reproduce it (as minimally and precisely as possible)**:

- Go to `Dashboards` -> `Browse`
- Select an existing folder
- Delete it
- Folder is still shown???

see video: 

https://user-images.githubusercontent.com/20999846/171210259-09c23028-3a2d-40e3-9e27-bcc6e4bedba5.mov

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by FZambia** [comment]
@ashharrison90 hello, should be fixed and part of 9.0.0-beta.3. The only thing is that in HA setup we still have up to 5 seconds delays since updates do not propagate to another node immediately – we will think on solution, one possible idea is this one: https://github.com/grafana/grafana/pull/50152
