### ISSUE TITLE
Implement datasource secrets migration to unified secrets

### ISSUE THREAD

**Issue by mmandrus** [grafana/grafana#50101]
- [ ] Add ability to migrate secrets to/from the plugin
- [ ] Trickle: Gradually migrate all secrets from Unified Secrets & Legacy to plugin and delete them if backwards compatibility is disabled
- [ ] Full: Immediately migrate all secrets from Unified Secrets & Legacy to plugin and delete them if backwards compatibility is disabled
- [ ] Full from Plugin: Migrate secrets from plugin back to Grafana, write to Unified Secrets and Legacy if backwards compatibility is enabled

Because of the gradual migration mechanism, migration to the plugin would have to pull secrets from both the old secrets location and the new unified secrets table. 

Migration from the plugin back to Grafana should push secrets to the new unified secrets location and the old location for backwards compatibility. This can be disabled with a feature flag (additional task).

This will also require augmenting the protobuf definition with bulk get/set methods, probably using some sort of paging mechanism.

**Comment by guicaulada** [comment]
Trickle with Backwards Compatibility is already implemented and part of 9.0-beta3 and is the default approach.

**Comment by guicaulada** [comment]
Because of the `disableSecretsCompatibility` flag and race conditions during secret deletion, as well as conflicts with provisioning, the full migration from legacy to unified secrets was converted to a common migration.

Migration from unified secrets to plugin will be a background service.

Migration from plugin to unified secrets (and legacy if the flag is disabled) will still have to be implemented.

**Comment by guicaulada** [comment]
Turns out it's not possible to use the secrets service for decryption during migration.

The full migration from legacy to unified is now a middle ground between a background secret and a common migration.
