### ISSUE TITLE
Unable to POST alerts to grafanas alertmanager

### ISSUE THREAD

**Issue by Fantaztig** [grafana/grafana#50150]
**What happened**:
We are trying to send alerts directly into the grafana alertmanager.
Unfortunately every post to `/api/alertmanager/grafana/api/v2/alerts` returns `bad request data`.
In grafanas logs we see the following error `json: cannot unmarshal array into Go value of type definitions.PostableAlerts`

We tried various different payloads that we are sure to be correct, but all return the same result.

**What you expected to happen**:
We expected the alert to show up in grafana so that we can route it to the relevant contact points.

**How to reproduce it (as minimally and precisely as possible)**:
Spin up grafana locally
```
docker run -p 3000:3000 grafana/grafana:8.5.4
```
Run the following curl against it
```
curl -X POST -H "Accept: application/json" -H "Content-Type: application/json" -u admin:admin localhost:3000/api/alertmanager/grafana/api/v2/alerts -d '[{"annotations":{"description":"Test","runbook_url":"https://test.k8s","summary":"A custom test alarm."},"generatorURL":"http://localhost:3000/alerting/grafana/","labels":{"alertname":"test"}]'
```

**Anything else we need to know?**:
We checked the docs whether this endpoint was exposed by accident but it's well documented here:
https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/pkg/services/ngalert/api/tooling/post.json

The issue remains regardless of unified alerting being enabled or disabled.

**Environment**:
- Grafana version: 8.5.4 & 8.5.3

**Comment by mellieA** [comment]
@Fantaztig I tried the docs at swagger and they weren't working for me either. I tried using developer tools in chrome to find the POST request when adding an alert via the UI and this worked for me. Let me know if this works for you. I'll follow up with our alerting squad to find out more about the docs. 

Because this uses the `datasourceUid` that's specific to my instance, you might try generating your own curl from your environment. 

Open developer tools in curl and find the POST request that creates the new alert: 

![Screen Shot 2022-06-03 at 5 07 02 PM](https://user-images.githubusercontent.com/18175287/171965226-e758bcd5-b233-47f2-ae10-9de2f4308033.png)

Use the **copy as curl** option to see the request sent by the browser formatted as curl: 

![Screen Shot 2022-06-03 at 5 07 15 PM](https://user-images.githubusercontent.com/18175287/171965238-4ae773ed-176c-41d8-9564-efd70a17a1e6.png)

Here's an example from my instance. I removed most of the extra headers and added the user credentials: 

`name` is the group name
`title` is the alert name

```
curl -XPOST -u admin:admin 'http://localhost:3000/api/ruler/grafana/api/v1/rules/Application?subtype=cortex' \
  -H 'accept: application/json, text/plain, */*' \ 
  -H 'content-type: application/json' \
  --data-raw '{"name":"TestGroup","interval":"1m","rules":[{"grafana_alert":{"title":"testAPITestDB1","condition":"B","no_data_state":"NoData","exec_err_state":"Alerting","data":[{"refId":"A","datasourceUid":"ZatY_PQ7k","queryType":"","relativeTimeRange":{"from":600,"to":0},"model":{"refId":"A","hide":false,"query":"","alias":"","metrics":[{"type":"count","id":"1"}],"bucketAggs":[{"type":"date_histogram","id":"2","settings":{"interval":"auto"},"field":"timestamp"}],"timeField":"timestamp","scenarioId":"server_error_500","stringInput":"1,20,90,30,5,0"}},{"refId":"B","datasourceUid":"-100","queryType":"","model":{"refId":"B","hide":false,"type":"classic_conditions","datasource":{"uid":"-100","type":"__expr__"},"conditions":[{"type":"query","evaluator":{"params":[3],"type":"gt"},"operator":{"type":"and"},"query":{"params":["A"]},"reducer":{"params":[],"type":"last"}}]}}]},"for":"5m","annotations":{},"labels":{}}]}' \ 
  --compressed
{"message":"rule group updated successfully"}
```

**Comment by Fantaztig** [comment]
@mellieA thanks for the answer! However this is a bit of a different use case as I am not trying to create alerting rules but to send actual alerts into the grafana alert manager.

This issue came up when trying to feed alerts coming from the mimir ruler directly into the grafana AM to be able to configure everything within a single AM instead of having to configure e.g. alerting rules in both the grafana and the mimir AM.

**Comment by gotjosh** [comment]
Grafana is not an alert receiver, I have written a detailed answer on the feature request: https://github.com/grafana/grafana/discussions/45773#discussioncomment-2235421

Please upvote the proposal if you'd like to see it happening in the future 🙏

**Comment by Fantaztig** [comment]
@gotjosh thanks for the answer! Would appreciate it if this was noted anywhere in the docs to prevent further confusion.

**Comment by gotjosh** [comment]
@brendamuir @gillesdemey can we add this to the list?
