### ISSUE TITLE
Variables get escaped weirdly when enabling Multi-Selection

### ISSUE THREAD

**Issue by aaronriedel** [grafana/grafana#50211]
**What happened**:
I have set up a variable "server" with data type "Custom" and 2 entries. Lets call them `server1.example.com` and `server2.example.com`. I can use those variables without problems in my promql queries with {server=$server}. 
When I set the variable to "Multi-Value" AND/OR "Include All Option" all my Queries show "no data", even when I just select one value at a time.

**What you expected to happen**:
I expect that a normal variable with custom fields behaves the same when I allow multi selection but just select one.

**How to reproduce it (as minimally and precisely as possible)**:

When I disable Multi-Select:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/68553182/172008285-d27fb130-aacd-44a5-b3b1-7678582bb556.png">
My Query looks like this, which works fine:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/68553182/172008433-2128f9ac-7467-4df7-9657-7b2356ff7225.png">

However, if I enable Multi-select:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/68553182/172008515-0ba2d32b-c008-4178-b015-9d362eb5af7b.png">

Then my Query looks like this (dots get escaped by quad-backslashes):
<img width="635" alt="image" src="https://user-images.githubusercontent.com/68553182/172008596-37f6106e-d9bd-4a5f-933e-dde873c8e52d.png">

I believe that this escaping causes my Query to fail when I enable Multi-select.

**Anything else we need to know?**:
Possibly this issue is related?
https://github.com/grafana/grafana/issues/5314

**Environment**:
- Grafana version: 8.5.2 and v9.0.0-beta2
- Data source type & version: Prometheus
- OS Grafana is installed on: docker

**Comment by torkelo** [comment]
that is because to support multiple values your prometheus label filter needs to be a regex filter, and then grafana needs to regex escape each value

**Comment by torkelo** [comment]
to disable the auto regex escaping for multi value variables you can use `${variableName:raw}` syntax, but then it will not work with the regex operator

**Comment by aaronriedel** [comment]
thanks

**Comment by sky-philipalmeida** [comment]
@torkelo as you stated, using raw breaks regex, should this be a bug?

**Comment by torkelo** [comment]
@sky-philipalmeida no it's by design, raw would of course break regex as it disabled regex escaping , why do you ask?

**Comment by sky-philipalmeida** [comment]
@torkelo if it's by design nothing to do about it.

IMHO as a user when using the custom field capability it feels like the escape feature is not well implement and looks more like a bug rather then a design option to be completely honest @torkelo.

As a user this blocks my ability to use the custom field in a natural way I guess but most of all I cannot "escape" in order to build regex enable fields which is a huge concern in my POV as user.

I was hoping you could reopen #50211 or give it another look.

If you did not do it already try to mimic or ask someone to mimic this simple case scenario presented by @aaronriedel is really frustrating and user expectation are frustrated.

**Comment by torkelo** [comment]
@sky-philipalmeida not sure what you are mean, can you describe your scenario? custom field? 

We cannot change this behavior, multi-value variables need regex escaping as otherwise they would not work in 99% of use cases. Changing this would break millions of dashboards. 

Do you have a change proposal?

**Comment by torkelo** [comment]
The issue described in this issue (top description) is easily fixed by switching to regex operator vs the used = equality operator. That is why this issue was closed

**Comment by sky-philipalmeida** [comment]
@torkelo I am sorry :) 

I think I did not understand that for my user case regex was not the way to go.

This was my initial approach (bumping into the escaping sequences of regex which are expected) using:
`mongodb_up{job=~"${job:regex}"}`

Configuration:
<img width="434" height="388" alt="Image" src="https://github.com/user-attachments/assets/6510fb32-636d-4003-b04d-a278f6aad380" />


Result:
<img width="801" height="147" alt="Image" src="https://github.com/user-attachments/assets/fa005d9d-b068-45dd-a049-9a3268cfb840" />

Expecting 
`mongodb_up{job=~"(.*configserver.*|.*shards.*)"}`


But after all what i really needed was a [join](https://grafana.com/docs/grafana/latest/visualizations/dashboards/variables/variable-syntax/#join) in order to construct my own regex:

`mongodb_up{job=~"${job:join:|}"}`

Using the above I get the correct result for my user case:
`mongodb_up{job=~".*shard.*|.*configserver.*"}`

Althougt auto regex escaping still does not fully convince me but join makes it happen :) 

Thanks @torkelo for the help.

**Comment by torkelo** [comment]
@sky-philipalmeida yea, if your values are already regex fragments, then you just need to inform grafana how to combine them into one string so join could work
