### ISSUE TITLE
Loki count_over_time doesn't work when the interval is too small

### ISSUE THREAD

**Issue by yukha-dw** [grafana/grafana#50220]
**What happened**: I cannot query large time range with small `count_over_time` interval.

**What you expected to happen**: Returns grainy data.

**How to reproduce it (as minimally and precisely as possible)**: 
```
1. Set time range to something like 5 years
2. Query these 2
sum (count_over_time ({deployment_name="deployment"} [7d])) by (deployment_name)
sum (count_over_time ({deployment_name="deployment"} [1m])) by (deployment_name)
```

**Anything else we need to know?**:
Screenshot:
Range: 5 years
Interval: 7 days
![image](https://user-images.githubusercontent.com/91457362/172078290-a57a8ba7-eb45-426a-a4cb-a49827c899aa.png)

Range: 5 years
Interval: 1 minute
![image](https://user-images.githubusercontent.com/91457362/172078326-da221d9a-89fb-4c69-b5c9-6008498f3c1f.png)

**Environment**:
- Grafana version: v8.4.4
- Data source type & version: Loki v2.2.1
- OS Grafana is installed on: I'm not sure, should be Ubuntu 20.04
- User OS & Browser: Windows 10 Build 19042 & Firefox 101.0
- Grafana plugins: Any Core Plugins by Grafana Labs
- Others:

**Comment by gabor** [comment]
hi @yukha-dw thanks for reporting the issue. the problem is, the "step" value that will be used by Loki is chosen automatically by Grafana. it will be chosen automatically based on how many pixels do you have for the graph on your screen.

now, let's say you have 1000pixels available. with a 5year-time-range, you have to show a (roughly) two-day time-range on every pixel, so grafana will pick such a step-value. and now consider the query:
```
sum (count_over_time ({deployment_name="deployment"} [1m])) by (deployment_name)
step: 2days
```

for every two days you will get the count of logs in the last minute. is this what you are trying to query?

alternatively, you could use the `$__interval` variable, like this:
```
sum (count_over_time ({deployment_name="deployment"} [$__interval])) by (deployment_name)
```

grafana will replace `$__interval` with the current step-value.

does this fix your problem?

**Comment by yukha-dw** [comment]
Thank you @gabor!
Seems like i haven't read enough documentation. I don't know such variable exists.
