### ISSUE TITLE
Table panel: Tooltip is cut of when the last column is too narrow to show entire data

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#50243]
Using Grafana 8.5.2 on Linux with Chrome browser

When trying to view the tooltip for text, using the Table panel, with an SQL Server Datasource.

When I (intentionally) shrink the width of the column, I can see a tooltip of the column data
![image](https://user-images.githubusercontent.com/1325158/172149925-824ae72b-c262-4a40-87cd-3b0f1fcf9ec1.png)

But when the same column is the right-most column, it doesn't show the tooltip
![image](https://user-images.githubusercontent.com/1325158/172150077-701c028a-d360-4acc-a274-fb54d9b391a2.png)

This is expanded
![image](https://user-images.githubusercontent.com/1325158/172150135-8de03549-37cb-42a1-a407-9c90ba19c96e.png)

**Comment by reuvygroovy** [comment]
With the new versions, the problem exists but you have a workaround with the new table option Cell Inspect Value

![image](https://user-images.githubusercontent.com/1325158/182763744-ae516827-e4dc-4817-8d0a-74c3f798da3d.png)

![image](https://user-images.githubusercontent.com/1325158/182763700-00b1d55b-913c-4700-a7bb-9753066b1433.png)

![image](https://user-images.githubusercontent.com/1325158/182763760-a849b7eb-fbf0-4ad1-b508-c4e7ea7bc723.png)

**Comment by baldm0mma** [comment]
Hey @reuvygroovy , you are correct, in version 9+, we rebuilt the Table component with a React library called React Table, and no longer supply Tooltips on hover in they way we did previously. The `Cell value inspect` feature will let you, as you mentioned, view the whole text, but it will cost a click of the `Cell value inspect` toggle, and another click on the "eye" icon to see it. For those clicks, however, in return you get the ability to not just see the longer strings, but also to copy them to the clipboard; a tradeoff we deemed worth it. Since you found the answer already anyway, I'm going to close this issue. Thanks!
