### ISSUE TITLE
Grafana didn't send No Data alerts in telegram notification point

### ISSUE THREAD

**Issue by greedyjohnny-yt** [grafana/grafana#50249]
**What happened**:
Seems like grafana didn't send alert with No Data and non-existent label after update from 8.3.6 to 8.5.3 to telegram
I think that telegram' API just can't interpret grafana messages with start tag ('<') in "'<'no value'>''"
I turned on debug mode in grafana.ini and get several messages about this error:

statuscode="400 Bad Request" body="{\"ok\":false,\"error_code\":400,\"description\":< vnBI/sendMessage statuscode=" 400 Bad Request"body="{\"ok\":false,\"error_code\":400,\"description\":\"Bad Request: can't parse entities: Unsupported start tag \\\"no\\\" at byte offset 404\"}"

**What you expected to happen**:
That alert will be sent to telegram

**How to reproduce it (as minimally and precisely as possible)**:
Install grafana 8.5.3
Create an alert with unknown label and description, setup telegram bot and connect with grafana as "Contact Point"

e.g. we use 
A: metric "go_memstats_alloc_bytes_total{}[5m]" 
and 2 (__expr__) :
B: Operation: Reduce
     Function: Max
     Input: A
     Mode: Strict
C: Operation: Math
     Expression: $B>0
     
To reproduce an issue you need to create a label with non-existent label in description (e.g. {{ $labels.lalala }} ) and make an alert firing.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.3
- Data source type & version:
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Firefox
- Grafana plugins: none
- Others:

**Comment by greedyjohnny-yt** [comment]
@ashharrison90 it seems like this issue presumably related with this lib: https://pkg.go.dev/text/template?tab=versions, because templating is carried out by it in grafana, but I'm not sure.

**Comment by Karsonito** [comment]
> @ashharrison90 it seems like this issue presumably related with this lib: https://pkg.go.dev/text/template?tab=versions, because templating is carried out by it in grafana, but I'm not sure.

no, error occurs after request to telegram server

https://core.telegram.org/bots/api#html-style
> All <, > and & symbols that are not a part of a tag or an HTML entity must be replaced with the corresponding HTML entities (< with &lt;, > with &gt; and & with &amp;).

**Comment by WiFiAdapter** [comment]
I am facing the same issue

**Comment by nejcb1** [comment]
Same issue.

**Comment by armandgrillet** [comment]
We should see that the request returned a `400` and do something about. Not sending the alert and not reporting an error to the end user somehow is wrong for an alerting system.
This should only be an issue with no data and no value because Telegram sees a `<` and `>` and interprets this as an HTML block. To fix this, we could replace the `<no data>` and `<no value>` to be static escaped strings.

**Comment by yuri-tceretian** [comment]
A few thoughts to reason about #60129 in this particular case.

I think the code changes in the notifier does not make sense because the Grafana implementation of the Telegram receiver will be replaced with the upstream Alertmanager's implementation. Therefore the changes in the code of the notifier will make the transition much harder.
1. One option is to change defaults:
- The notifier is set to HTML. There are 2 more options Markdown and Plain text. However, I think it still must be the default because we include Source and Silence as URLs, which are not displayed as clickable links in those two modes.
- Therefore, to switch to the markdown mode we will have to change the default template. However, later when we will let user pick the format of the message, changing defaults will not save users from this problem in the case they define a custom template (because it is hard to think about potentially missing keys in advance) and use it in HTML mode.

2. Another option is to escape HTML in labels and annotations right after expansion in the state manager. The problem is that it may make existing user-defined templates get broken that leverage HTML formatting. 
2.1. Replace just the string `<no value>` with something that does not look like an HTML tag. The reason is that this particular string cannot be controlled by the user, to work it around user needs to create a template with fallbacks `{{ or .Labels.Blah none }}` which is hard to think about in advance.
