### ISSUE TITLE
Prometheus Datasource: Modify to use contextual middleware layer

### ISSUE THREAD

**Issue by srclosson** [grafana/grafana#50407]
**What happened**:
Given #50199, and https://github.com/grafana/grafana/pull/50344, and https://github.com/grafana/grafana-plugin-sdk-go/pull/516 it's going to make sense to audit the prometheus datasource, and understand the requirements, and simplify and standardize the datasource so that it can use the contextual middleware layer.

Much of the history is in the issue, and two PR's listed above.

**Comment by marefr** [comment]
Would suggest prioritizing this to 
1) make sure caching HTTP clients/transports works as expected since it could make HTTP connection pooling/reuse not working and could lead to using up all available TCP connections on a busy server. Sounds like clients/transports are not properly cached based on https://github.com/grafana/grafana/pull/50344#issuecomment-1149208319, if that's true I would say it's a blocker for Grafana v9.

2) make use of [contextual middleware](https://github.com/grafana/grafana-plugin-sdk-go/pull/516) (when available) to refactor/clean up the code

**Comment by srclosson** [comment]
@marefr Any suggestions on how this can be tested to ensure this is not an issue? I can check this out.

**Comment by marefr** [comment]
> @marefr Any suggestions on how this can be tested to ensure this is not an issue? I can check this out.

@srclosson I'm afraid it's about manually digging through the code, maybe debugging, maybe writing unit tests.

 

> Also, is there an example on how the contextual middleware layer ideally is supposed to be used? 

There's one example provided in the changes: https://github.com/grafana/grafana-plugin-sdk-go/blob/d2de807a69fab2b995452deb45361e9fa0d0f8cc/backend/httpclient/contextual_middleware_example_test.go

Discussed this a bit with @toddtreece and we think use of contextual middleware can be implemented here https://github.com/grafana/grafana/blob/main/pkg/services/query/query.go#L139-L148

Meaning that core/builtin HTTP datasources automatically would get OAuth token and forwarded cookies automatically set on Authorization, X-ID-Token, Cookie header on outgoing requests. At least this is the working idea.

**Comment by marefr** [comment]
WIP #50466 by @toddtreece

**Comment by bohandley** [comment]
Hi @toddtreece and @itsmylife, how is this work going related to getting the streaming parser client in parity with the old buffered one?

**Comment by bohandley** [comment]
So there seems to be a lot going on in this one. Here is my best summary.

1. We need to audit the Prometheus datasource.
2. There are some areas in the Prom backed we can use the contextual middleware layer. It's too complicated.
3. We had many escalations/issues around headers and using the contextual middleware layer was part of fixing this.(@marefr correct?)
4. All of the work suggested looks to be merged, so we're using contextual middleware
5. We should still be wary of breaking things in Prometheus because [Azure auth is still located in the buffered client](https://github.com/grafana/grafana/blob/7146f2731c4ebc4f93c8fe0c634359c3dd89c6dc/pkg/tsdb/prometheus/buffered/client.go#L22) in `CreateTransportOptions`. Can this be handled with contextual middleware?
6. There are more hidden things that can be fixed by using contextual middleware but we won't know them until we comb through the code. @marefr is there a list of things the contextual middleware can do, some things that we are possibly missing, or some handy use cases?

@aocenas any thoughts?

Thanks all!
