### ISSUE TITLE
3.0.1: missing "public/vendor/npm/rxjs/Observable"

### ISSUE THREAD

**Issue by onlyjob** [grafana/grafana#5044]
Please commit `public/vendor/npm/rxjs/Observable` which is included by the following files:

 * public/app/core/live/live_srv.ts
 * public/app/features/panel/metrics_panel_ctrl.ts
 * public/app/plugins/datasource/grafana-live/datasource.ts

This would help to create comprehensive source tarball which would be very helpful to build official Debian package of Grafana.

Thanks.

**Comment by torkelo** [comment]
npm dependencies are not checked into source control, they are installed using "npm install"

**Comment by onlyjob** [comment]
Provided that all build tools are already installed to operating system we need to eliminate downloading of sources on build time. This is a requirement for secure and reproducible build.

It is not possible to use `npm install` on build servers without internet connectivity.

You are already "vendoring" _some_ 3rd party dependencies and I'm merely suggesting to bundle _all_ 3rd party sources.

Alternatively you can provide source archive with pre-fetched 3rd party dependencies.

**Comment by torkelo** [comment]
For go dependencies it makes sense since there is no central package manager that can reliably install dependencies. 

But where do you stop. Should Grafana include the Go compiler source? the Nodejs source?  

I don't know of any nodejs web application or frontend build system that add's all it's dependencies to source. 

Could you explain why you need a source package? If you need to a custom package (say you use a fork?) can't you build the packages on a build system (circleci / teamcity server etc). 

If Grafana was a simple backend server written just in C or Go I think your request is resonable, but for complex web frontends and web build systems that depends on so hundreds of node components it is not.  

If you want a source package, that includes a pre built frontend just clone this repo, thne run `npm install` and `grunt build`. Then zip up the folder.

**Comment by onlyjob** [comment]
> But where do you stop. Should Grafana include the Go compiler source? the Nodejs source? 

Let's be reasonable please.  :)  It is a practical issue, not a theoretical one.
All Grafana dependencies should be included i.e. sources that are required to build Grafana.
Of course you do not need to include interpreters and their sources -- that would be crazy. :)

> Could you explain why you need a source package?

To build [official Debian package of Grafana](https://tracker.debian.org/pkg/grafana) from source.
Binary packages are built from source archives on secure build servers without internet access so downloading on build time is not possible.

Some projects that use git submodules generate source archive as part of their release process because source tarball downloaded from GitHub is incomplete (does not include submodules).

I understand your reluctance to commit 3rd party dependencies but it would be helpful if you could consider generating official source tarball with all required dependencies as downloaded by _npm_.

> If you want a source package, that includes a pre built frontend just clone this repo, thne run npm install and grunt build. Then zip up the folder. 

I'd prefer to build Grafana from authoritative source so anyone could reproduce build. I do not wish to provide my own _build_ of Grafana sources and it would be highly unusual practice for Debian packaging...

Sorry for troubles...

**Comment by torkelo** [comment]
@onlyjob I see. 

I guess a PR to this repo (that builds the deb / rpm packages) could be made so that it saves a tar ball after "npm install" and "grunt build" has exectured, then uploads that to S3  (done in the cricle ci part)

**Comment by torkelo** [comment]
sorry, here is the link to the build repo:
https://github.com/grafana/grafana-packer

**Comment by onlyjob** [comment]
Thanks.
