### ISSUE TITLE
Adjusting Count Metric Queried from Elasticsearch after Changing Time Interval

### ISSUE THREAD

**Issue by zhenzh** [grafana/grafana#5045]
I'm using grafana 2.6 with elasticsearch data source. I use Metric - Count in my query to describe the frequency of certain log includes specified message changing with time series. It works well when I set time interval as 1s. While it contains too many data points if I'd like to monitor the result of a long time period. So, I tried changing time interval to 10s or larger.  Then, the issue comes - grafana simply sum the counts within the time interval and use the result as the new data point value but what I want is the average count within the time interval.
Is there a feature that I can choose the calculation method to be applied after counts grouped with time interval?
Or, will the post-process for Counts metric be available so that I can manually process the count value get from query? For example, scale with multiply/divide specified number or deviation with plus/minus specified number.

**Comment by torkelo** [comment]
you question is best directed to an elasticsearch forum, The count metric is just the count property on the bucket aggregation (date histogram in your case), since you group by time the Count metric will count each document as 1 and sum the counts, That is how it works in Elasticsearch. 

I am not sure I understand your scenario, Average count within time period? If you group documents into say 10s buckets, each bucket contain between 1-10 docs say, the count will contain the sum of the number of documents in each time bucket. The average number of documents in each time bucket will be the same as the sum. As I said I do not understand your question, what is the average you want and over what time period? 

>- grafana simply sum the counts within the time interval and use the result as the new data point value but what I want is the average count within the time interval.

This is done by Elasticsearch not grafana. 

Is is just a question of you wanting count/second?

**Comment by zhenzh** [comment]
Yes, what I want is count/second.  So, if the bucket is 10, the expected result is  sum count/10

**Comment by torkelo** [comment]
You can do this with elastic script option,  but elastic does not have this option for the  count metric

**Comment by zhenzh** [comment]
Yes, that's my problem as count metric can not be processed by script. So I wonder whether grafana can provide a post-process feature against count metric.
With such feature, we can not only adjust the count/s value, but also get counts from different queries calculated(sum #A+#B e.g.)

**Comment by torkelo** [comment]
Yes we plan to provide some metric processing
https://github.com/grafana/grafana/issues/3677

If you have a field that is just the value 1 in you docs, you can use the Sum metric aggregation that supports script

**Comment by zhenzh** [comment]
I finally added additional metric with value 1 in my doc to get the script function work over that. Thank you for your suggestion.

**Comment by renukuntaharish** [comment]
Is there any alternative for altering sum of metric count?
