### ISSUE TITLE
3.0.1: please make comprehensive source archive

### ISSUE THREAD

**Issue by onlyjob** [grafana/grafana#5046]
3.0.1 introduced regression (somewhat) where source archive is not comprehensive any more because it does not contain all the sources needed to build Grafana.

On Debian, all packages are built from source on secure build servers without internet access so builds are reproducible and do not depend on availability of external resources.
It is not possible to download anything during build.

It would be great to commit all downloadable (by npm, grunt, etc.) 3rd party sources or generate comprehensive "release" source archives with all dependencies.

Thanks.

**Comment by torkelo** [comment]
Github source tar has never been 100% comprehensive, Grafana has always required "npm install" to build  (like most web apps)

**Comment by onlyjob** [comment]
This is a practical problem... I hope you could give it some attention or thoughts. Denial does not help you know, and problem does not magically disappear by closing bug without an action...
FYI it was possible to build 2.6.0 from source tarball without downloading anything...

This problem block upload of updated package.

**Comment by torkelo** [comment]
Bug?? No its not possible to build 2.6 without npm install.  Grafana requires npm modules to build it has always, it is almost always a bad idea have node modules checked into source.  

You can build a source package but you need to build the front end using the grunt build system,  the frontend build requires hundred of node modules

**Comment by onlyjob** [comment]
> No its not possible to build 2.6 without npm install. 

But it is possible. That's how current Debian package is made -- without `npm`.
Sources are there and compiling stylesheets is easy with _lessc_ provided by operating system.
_node-typescript_ (`/usr/bin/tsc`) is also available so only sources are needed to build fully functional Grafana package.

With 3.0.1 this is no longer possible because not all sources are included. I'm not suggesting to commit compilers or packaging tools, only sources that _required_ to build Grafana.
See example of problem in #5044.

**Comment by torkelo** [comment]
@onlyjob that will at most create an un-optimized development build of the frontend, not a true minified concatenated frontend that is has gone through all the asset optimization pipelines.

**Comment by onlyjob** [comment]
Minification is easy to do (there are tools to choose from) but I believe minification is overrated (see #4006). Anyway minification is another (unrelated) issue...

**Comment by torkelo** [comment]
@onlyjob minification is only one minor part, 

the whole process is here:
https://github.com/grafana/grafana/blob/master/tasks/build_task.js

**Comment by Glandos** [comment]
Maybe everyone that land here know it, but this issue is related to trust.
Using `npm install` during the installation process is fine, as long as you don't need trust. NPM has proven [its unreliabilty](https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/) as a central repository.
Moreover, using a Internet connection in the building process makes [reproducible builds](https://reproducible-builds.org/) impractible.
All in all, trust is why people are using Debian packages from the main repository: they can be trusted more than any other. And installing package from any other sources implies less trusty packages, and more complicated installation process.

I know this does not really help, because what we really need is to package the two dozens of npm librairies needed by grafana into Debian. But I thought it should be said. I a fan of grafana, and I'll be delighted to see it back and up to date in Debian.

**Comment by Glandos** [comment]
Please read https://hackernoon.com/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5
We need to have a comprehensive list of packages installed. With their hashed values at least.
