### ISSUE TITLE
OData Support

### ISSUE THREAD

**Issue by efrecon** [grafana/grafana#5050]
Has anyone looked into supporting [OData](http://www.odata.org/) in datasources? I can't find anything relevant on github or the rest of the "Internet"... There are a number of OData implementations in javascript that should make the process rather painless for somebody at ease with implementing data sources, see:
- [Apache Olingo](http://olingo.apache.org/doc/javascript/index.html)
- [o.js](https://github.com/janhommes/o.js), smaller, standalone, ready for integration.
- Other libraries referenced from the [home page](http://www.odata.org/libraries/#javascript)

**Comment by frankfrommelt** [comment]
Has anything happened here in the past three years?

**Comment by dschoeneborn** [comment]
Would be a very big step forward. Would solve a lot of problems.

**Comment by fractal-joe** [comment]
Doesn't seem like priority.

**Comment by carroe** [comment]
Hi everybody!

We have recently released the first version of the OData Grafana Datasource plugin. The sources can be found here: https://github.com/d-velop/grafana-odata-datasource

We published the plugin as a community plugin, which means it is open source and not for profit. Community plugins are published in the official Grafana catalog, and are available to the Grafana community.

Here is the related plugin page on Grafana.com: https://grafana.com/grafana/plugins/dvelop-odata-datasource/
 
The first version only has a few basic features because we wanted to successfully complete the Grafana review first:
 
* We only support OData V4
* The plugin uses the $metadata endpoint to determine the available entity sets
* When building queries you can select an entity set, an appropriate time property, and a metric you want to view
* Queries can only be clicked together and not freely defined
 
We have a lot of other features in the backlog and hope for the support from the community.

Best regards,
Carsten

**Comment by T1000-Cyberd** [comment]
Please make Time Property Optional :) 👍
