### ISSUE TITLE
Template variable query function for listing CloudWatch log groups is limited to 50 items

### ISSUE THREAD

**Issue by Madh93** [grafana/grafana#50532]
**What happened**:

The template variable query function for listing CloudWatch log groups is limited to 50 items. For instance, If we filter by `/aws/lambda`  in a region with more than 200 lambda functions we only get the 50 first (in alphabetical order):

![image](https://user-images.githubusercontent.com/5855179/172884727-233a102a-bfae-4d48-b5ed-ace2b8222280.png)

**What you expected to happen**:

Return all available log groups.

**How to reproduce it (as minimally and precisely as possible)**:

Use the [`Log Groups`](https://github.com/grafana/grafana/pull/50100) query type and preview values.

**Anything else we need to know?**:

Initial implementation in https://github.com/grafana/grafana/pull/50100

**Environment**:
- Grafana version: v8.5.5 (d32ae18909)
- Data source type & version: CloudWatch
- OS Grafana is installed on: CentOS 7
- User OS & Browser: GNU/Linux & Google Chrome
- Grafana plugins: n/a
- Others: n/a

**Comment by iwysiu** [comment]
This is due to how `DescribeLogGroups` on the backend limits the results to 50, which is because the `Log Group` selectors use the user-submitted prefix to narrow down and find the one log group that they're looking for. This case would want to pull all the matching log groups, so fixing this would require adding a function to get all the matching log groups and using that for the variable query instead.
