### ISSUE TITLE
Docs: Document org & user preferences HTTP docs

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#5069]
Reported via raintank support:

> RE: The grafana 3.0 administrative API, I can not find a way to set the global/org level default time-zone display. I have to set it manually to UTC through the web interface. When I use the API to get ORG details the only information in the result are the org ID, Name, and Address fields.

> Do you know anything about that? We use puppet to automate our installations (datasources, database, default dashboards from VC'd json files, etc) and being able to ensure the time-zone display is uniformly set to UTC across our installation-base would be really nice.

cc: @tbielawa

**Comment by tbielawa** [comment]
Yes yes yes. This is quite relevant to my interests from a standpoint of automation. I'll respond back again with some examples of the typical **expected** vs **actual** results.

Thanks @mattttt for opening this for me.

**Comment by tbielawa** [comment]
# RFE

Enable configuration of the **global** and **per-org** default ``timezone`` parameter, _outside_ of the web interface. Ways this could be assigned:

* A configuration value in the ``grafana.ini`` file for a global default
* Via the REST API to (re)configure an org
* New orgs would inherit the global default (which does not appear to be configurable presently in 3.x)

Allowed values for the ``timezone`` parameter:
* ``UTC``
* ``local``
* ``default`` (which appears to be ``Local browser time`` in the current release)

## Global

Setting the **global** ``timezone`` parameter seems to me like it should take place outside of the scope of any ``[section]`` blocks in the ``grafana.ini`` file:
```ini
# Everything has defaults so you only need to uncomment things you want to
# change
# ...

# Either "UTC", or "local", default is "local" for Local browser time
timezone = UTC

#################################### Paths ####################################
[paths]
....
```

## REST Set/Update

We configure our instances using some automation ran through puppet. Presently this includes ensuring all of our specific datasources are present, and that the default org has the correct name set. (ensuring specific users are global admins is another function I'm working on presently).

Assuming a default org as such (from a ``GET /api/orgs/1 HTTP/1.1`` request):
```json
{
    "address": {
        "address1": "",
        "address2": "",
        "city": "",
        "country": "",
        "state": "",
        "zipCode": ""
    },
    "id": 1,
    "name": "Red Hat, Inc."
}
```

Then an additional key would be returned, ``timezone``. In a multi-tenant configuration, this would allow individual orgs to configure their own preferred timezone, overriding the global default.

Per the ``http_api`` docs [1], an org wishing to update its timezone setting would issue a REST call similar to this:

```
PUT /api/orgs/1 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk

{
  "timezone":"UTC"
}
```


[1] http://docs.grafana.org/http_api/org/#update-organisation

**Comment by tbielawa** [comment]
I have returned from reading the most recent source code and I think this is already implemented. If you grep around for timezone it shows up right away. ``timezone`` is a per-org preference (``api/dtos/prefs.go`` from ``api/preferences.go`` . I'm going to write out what I found in full in case anyone else out there is trying this out too.

What we're going to do is use curl to get the current org preferences, save it to a file called ``/tmp/preferences.json``. I couldn't find anywhere in the docs which covers this, so here's how I figured out it exists. 

There are bindings for these preference url locations in the main ``api/api.go`` file in the ``/org`` group. 

```go
  r.Get("/preferences", wrap(GetOrgPreferences))
  r.Put("/preferences", bind(dtos.UpdatePrefsCmd{}), wrap(UpdateOrgPreferences))
```


This location, org preferences, you can find presently defined in ``api/preferences.go``:

```go
// GET /api/org/preferences
func GetOrgPreferences(c *middleware.Context) Response {
        return getPreferencesFor(c.OrgId, 0)
}

// PUT /api/org/preferences
func UpdateOrgPreferences(c *middleware.Context, dtoCmd dtos.UpdatePrefsCmd) Response {
        return updatePreferencesFor(c.OrgId, 0, &dtoCmd)
}
```

ok. Let's make the api call, the code says there's a ``GET`` method available:

```
$ curl -X GET -s -u admin:admin localhost:3000/api/org/preferences > /tmp/preferences.json
```

Yielding /tmp/preferences.json like this:
```json
{"theme":"","homeDashboardId":0,"timezone":""}
```

Edit this file, change the ``timezone`` value to ``utc``. Save file. Close file.

Update the org preferences. The code says a ``PUT`` to this location should update the org prefs:
```
$ curl -X PUT -d @/tmp/preferences.json -u admin:admin \
    -H "Content-Type: Content-Type: application/json" \
    localhost:3000/api/org/preferences

{"message":"Preferences updated"}
```

And we can confirm this by running the original command again, just don't capture it into the same /tmp/preferences.json file this time :wink: 

```
$ curl -s -u admin:admin localhost:3000/api/org/preferences                                                                                
{"theme":"","homeDashboardId":0,"timezone":"utc"}
```

Great! There is a way to do this. Fantastic news.

But since it's not documented should I assume that means it isn't fully supported, or subject to change in the future? Maybe these errors answer that question for me. I think it always returns that "prefs updated" message. Even if you change the ``timezone`` value to ``spacetime`` in the preferences.json file and PUT it again:

```
$ cat /tmp/preferences.json 
{"theme":"","homeDashboardId":0,"timezone":"spacetime"}

$ curl -v -X PUT -d @/tmp/preferences.json -u admin:admin \
    -H "Content-Type: Content-Type: application/json" \
    localhost:3000/api/org/preferences
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
* Server auth using Basic with user 'admin'
> PUT /api/org/preferences HTTP/1.1
> Host: localhost:3000
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: Content-Type: application/json
> Content-Length: 55
> 
* upload completely sent off: 55 out of 55 bytes
< HTTP/1.1 200 OK
< Date: Wed, 18 May 2016 02:22:49 GMT
< Content-Length: 33
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact
{"message":"Preferences updated"}
```

This is technically true, our preferences have been updated. Let's verify that

```
$ curl -s -u admin:admin localhost:3000/api/org/preferences                                                                                
{"theme":"","homeDashboardId":0,"timezone":"spacetime"}
```

But that's not useful anymore :-) Not right now anyway, the app's not configured to handle anything other than the default/utc/local. I could see why someone _might_ want to restrict the range of valid values for this in the future, if you were incorporating it into UI elements or something else.

Just a fun observation now: The way the web interface handled this made me chuckle a little bit. The Org's timezone selector had another option in it with the value of just ``?``:

![spacetimezone](https://cloud.githubusercontent.com/assets/33121/15345643/bee2ec3a-1c7e-11e6-802f-36eebcfaf3a8.png)


Are there any plans or thoughts about documenting these API endpoints and defining their behavior like the other methods are presently?

Thanks a bunch :)

**Comment by tbielawa** [comment]
Sorry, I shouldn't say "these errors" I just mean the described behavior

**Comment by utkarshcmu** [comment]
Yes, preferences API is missing from the docs. Feel free to submit a PR for it, I guess. Documentation is the key. 😊

**Comment by tbielawa** [comment]
Working on it now.
