### ISSUE TITLE
failed to decrypt a secret encrypted with envelope encryption: envelope encryption is disabled in the grafana:8.5.5 version

### ISSUE THREAD

**Issue by alekseiapa** [grafana/grafana#50745]
**What happened**:

When attempting to sign in to Grafana using the gitlab auth method, I receive the following error: `failed to decrypt a secret encrypted with envelope encryption: envelope encryption is disabled`. This problem persists with the most recent version of the grafana docker image (8.5.5). [envelopeEncryption](https://grafana.com/docs/grafana/latest/administration/database-encryption/?cta=prod-cloud-hero-btn-1%3Fpg%3Dblog#envelope-encryption) was never enabled for me.  I downgraded to v 8.5.4 and everything is fine now.

**What you expected to happen**:

Sign in to Grafana using gitlab auth method without any errors

**How to reproduce it (as minimally and precisely as possible)**:

Click on `Sign in with gitlab` button  

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.5
- Data source type & version: MySQL v 8.0.29
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Firefox, Chrome
- Grafana plugins: grafana-clock-panel,grafana-simple-json-datasource,michaeldmoore-multistat-panel
- Others: None

**Comment by joanlopez** [comment]
Hi @alekseiapa,

It looks like your database contains some secrets with the format used by envelope encryption. So, considering that and that it has been enabled in Grafana v9 (or `main`), I'd like to ask if there's any chance your database has been used by a Grafana v9 (or `main`) instance?

Thanks!

**Comment by alekseiapa** [comment]
Hello, @joanlopez. Thank you for your response. No, we never used `version 9`. Our Grafana service runs on the Docker Swarm stack, and we always use the most recent Grafana image. I updated the stack yesterday. The `latest` version of the grafana image was in use, which resulted in the error message mentioned above. I've changed the Docker image to `8.5.4` and the error message has vanished. By the way, this problem only occurred for a few users after they signed out of Grafana. Not all users were impacted. Some users were still able to logout and login without issue. 
Another question is whether the option of `enveropeEncryption` in the v9 is required to be enabled ?

**Comment by joanlopez** [comment]
Hello,

> we always use the most recent Grafana image
> The `latest` version of the grafana image was in use

That's definitely an interesting insight! Honestly, I'd generally not recommend that practice because of the risks it implies, so I'd recommend you to start consciously updating from time to time instead of using `latest` label.

In fact, as far as I know, we experienced minor issues in one of the recent releases, so the `latest` label was used for a non-stable release (one of the Grafana v9 beta releases). The problem was solved in next few hours, but that could be the reason you run Grafana v9 without being aware of. Indeed, I think that should be the only possible reason to get these errors (moving back and forth between Grafana v9).

So, before moving one with possible workarounds and/or other verifications, could you please look at the contents of the `data_keys` table in the database and see if there's any entry? Thanks!

**Comment by alekseiapa** [comment]
Hello @joanlopez . Thank you for your response. I checked our database entries, but I couldn't find anything related to this. I'll update one more time the image version and check if it will work. Thanks!

**Comment by joanlopez** [comment]
Hello @alekseiapa,

Yes, please, let us know if you encounter any other issue.

Just as a final check, would you mind checking what of the migrations below are in your `migration_log` table (by `migration_id`), please?

- `create data_keys table`
- `create secrets table`
- `rename data_keys name column to id`
- `add name column into data_keys`
- `copy data_keys id column values into name`
- `rename data_keys name column to label`
- `rename data_keys id column back to name`

Thanks!!
