### ISSUE TITLE
API: Unexpected status code when creating folder with provided UID and reserved name

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#50767]
**What happened**:
<details>
<summary>Example request</summary>

```
curl -X 'POST'   'http://admin:admin@localhost:3000/api/folders'   -H 'accept: application/json'  -v  -H 'Content-Type: application/json'   -d '  {
	"title": "foo-foo-bar",
	"uid": "foo-bar"
      }'
    Note: Unnecessary use of -X or --request, POST is already inferred.
    *   Trying ::1...
    * TCP_NODELAY set
    * Connected to localhost (::1) port 3000 (#0)
    * Server auth using Basic with user 'admin'
    > POST /api/folders HTTP/1.1
    > Host: localhost:3000
    > Authorization: Basic YWRtaW46YWRtaW4=
    > User-Agent: curl/7.64.1
    > accept: application/json
    > Content-Type: application/json
    > Content-Length: 56
    > 
    * upload completely sent off: 56 out of 56 bytes
    < HTTP/1.1 412 Precondition Failed
    < Cache-Control: no-cache
    < Content-Type: application/json
    < Expires: -1
    < Pragma: no-cache
    < X-Content-Type-Options: nosniff
    < X-Frame-Options: deny
    < X-Xss-Protection: 1; mode=block
    < Date: Tue, 14 Jun 2022 09:10:20 GMT
    < Content-Length: 85
    < 
    * Connection #0 to host localhost left intact
    {"message":"the folder has been changed by someone else","status":"version-mismatch"}* Closing connection 0
```
</details>

**What you expected to happen**:
The above request should return [409 - Folder already exists](https://grafana.com/docs/grafana/latest/http_api/folder/#create-folder) instead

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The error is returned here:
https://github.com/grafana/grafana/blob/f87927c82e95ae87e90901bc2115b3a1b09ef4e0/pkg/services/dashboards/database/database.go#L350-L356

~Therefore, I think that a possible fix would be to set `Override` to `true` here:~
https://github.com/grafana/grafana/blob/f87927c82e95ae87e90901bc2115b3a1b09ef4e0/pkg/services/dashboards/service/folder_service.go#L148-L152

**Environment**:
- Grafana version: main (336c9fd5131be531dcfa53ad09349e088e30cdc2)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by MTLChrisLEE** [comment]
HI @papagian 

I investigated the issue and you are right.
Currently, the error returns here.
[grafana/pkg/services/dashboards/database/database.go](https://github.com/grafana/grafana/blob/f87927c82e95ae87e90901bc2115b3a1b09ef4e0/pkg/services/dashboards/database/database.go#L350-L356)

It will never go inside this if statement since id is not provided.
[grafana/pkg/services/dashboards/database/database.go]
(https://github.com/grafana/grafana/blob/1763b82b5d8b41556ddc6de3ed89413ea14a2df9/pkg/services/dashboards/database/database.go#L350-L352)

I created a PR and used version number value to see if a user is creating or updating.
However, version number is 0 when it's not provided. How will it impact this service?
