### ISSUE TITLE
Upgrade to 3.0.2 deleted everything?

### ISSUE THREAD

**Issue by claytondukes** [grafana/grafana#5086]
I just updated to v3.0.2-1463383025 (Ubuntu) and all of our dashboard, logins, data sources, etc. are gone. Is there a way to restore them?

**Comment by claytondukes** [comment]
Ok, I figured out why. I'll leave this here in case anyone else has the same problem:
edit /etc/grafana/grafana.ini and set up your database profile again.
The upgrade deletes all custom settings in that file. We had our data stored in postgres.
Once I did that and restarted grafana, it was back.

**Comment by torkelo** [comment]
The upgrade should not do that, since the `/etc/grafana/grafana.ini` is marked as configuration file, the debian deb package upgrade should have asked you if you wanted to keep your config file or overwrite it with the default one that comes with the package. 

At least that is what happens when I upgrade from 2.6 to 3.0 using apt-get or dpkg
