### ISSUE TITLE
Outdated glibc version

### ISSUE THREAD

**Issue by archoGk** [grafana/grafana#50863]
**What happened**:
glibc 2.30-r0 is being used in grafana

**What you expected to happen**:
update to newer verison or move to musl libc

**How to reproduce it (as minimally and precisely as possible)**:
list dependencies

**Anything else we need to know?**:
There are open CVEs for 2.30-r0 version like CVE-2021-3998,CVE-2021-3999,CVE-2022-23218,CVE-2022-23219

**Environment**:
- Grafana version: 8.5.x
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by sakjur** [comment]
I think you're talking about the Alpine based Docker image where the 2.30-r0 version of glibc is added to the x86_64 version of the image? (afaict, that's the only place where we use a different glibc from the "already installed" version)

https://github.com/grafana/grafana/blob/23956557d8c6a119b7de5be5c42024e29634d002/packaging/docker/Dockerfile#L38-L44

We should absolutely upgrade that to use a later version of glibc, thank you for bringing that to our attention 🙂 The good news is that Grafana itself is linked towards musl, the reason for having glibc as well is because there is at least one plugin that depends on a library dynamically linked towards glibc.

**Comment by zuchka** [comment]
see this related and old issue.

https://github.com/grafana/grafana/issues/24134

I don't know what to make of the author's suggestion. if we are intentionally keeping glibc and musl, maybe we could note as much and close it?

**Comment by sakjur** [comment]
Well, we should upgrade the glibc version in the container.

I’ll open a PR.

**Comment by cbl315** [comment]
Any update?

**Comment by cbl315** [comment]
Upgrade glibc to v1.35 could also fix below CVEs:
- [CVE-2021-33574](https://nvd.nist.gov/vuln/detail/CVE-2021-33574)
- [CVE-2021-35942](https://nvd.nist.gov/vuln/detail/CVE-2021-35942)
- [CVE-2020-6096](https://nvd.nist.gov/vuln/detail/CVE-2020-6096)
- [CVE-2021-38604](https://nvd.nist.gov/vuln/detail/CVE-2021-38604)
- [CVE-2021-3326](https://nvd.nist.gov/vuln/detail/CVE-2021-3326)
- [CVE-2020-1752](https://nvd.nist.gov/vuln/detail/CVE-2020-1752)
- [CVE-2020-1751](https://nvd.nist.gov/vuln/detail/CVE-2020-1751)
