### ISSUE TITLE
Missing table in Explore tab with "code" query interface

### ISSUE THREAD

**Issue by ngc104** [grafana/grafana#50973]
# What happened

I run a query (in explore tab) and I only have the graph. The table is missing

# What you expected to happen

I expected to have both the graph and the table.

# How to reproduce it (as minimally and precisely as possible)

In the following explanation, let's consider my Grafana is located at https://mygrafana.com/

## Step 1 : set the "code" query interface by default

Go to https://mygrafana.com/, login.

Click on the "explore" tab.

In the top left query interface, if "Code" is already selected, go to Step 2.

Click on "Code"

Ensure "Format: Time series" is selected.

Run some query like `kube_node_info` or whatever.

At this step, the bug does not appear for me : I have both the graph and the table.

Click on the "explore" tab : this should keep the "Code" query interface but it should empty the query field.

## Step 2 : query in "Code"

Ensure that
- "Format: Time series" is selected.
- "Code" query interface is selected

Type a query, like `kube_node_info` or whatever.

The graph appears.

The table is missing. *Here is the bug* !

## Step 3 : strange fix

Now click on "Builder" query interface (do not click on "Run query" yet).

It will switch to the builder query interface. But the table does not appear.

Now click on "Run query" : the graph is still there. *The table appears*. What happened !?

Now switch back to the "Code" query interface. The table does not disappear. Click on "Run query" again. *The table does not disappear*. Why does it work now ?

You can even reload with Ctrl-R or F5 : the table does not disappear.

# Anything else we need to know

I had some strange results with Grafana-8.5.3. The problem was probably existing at that time. In the previous version I was running, which was 8.1.6, there was no problem.

Queries are ran with Query options : Legend=Verbose, Format=Time series, Step=undefined, Type=Both

# Environment

- Grafana version: 9.0.0
- Data source type & version: Prometheus (using the built-in datasource)
- OS Grafana is installed on: Kubernetes with chart `grafana` from https://grafana.github.io/helm-charts
- User OS & Browser: Ubuntu 22.04 / Firefox 101.0.1 (64 bits)
- Grafana plugins: no additional plugins
- Others: -

**Comment by gelicia** [comment]
Thank you for so many details - that made replicating this so much easier! 

I dug into this a little bit and could replicate it using the devenv prometheus datasource. What I found is that a query including `"editorMode": "builder", "range": true, "instant": true,` will generate a table - the response has two frames (one for the timeseries and one for the table). This replication is when you go to the builder interface to build your query.

A query identical except for missing those three properties (as in neither the key nor value is defined) does not generate a table - only one frame. That is when you query via the code interface without going to the builder tab as described in step 2.

For step 3 with the strange fix of going to the builder and then going to the code interface, the query has `"editorMode": "code", "range": true, "instant": true,` and then generates the table with 2 frames in the response to show both the chart and table as expected.

So I believe the bug is that those three properties must be set when a user goes directly to the code interface to run a query.

**Comment by gtk-grafana** [comment]
@grafana/observability-metrics This is our ticket, let's review this in our next grooming session.

**Comment by gelicia** [comment]
I wasn't able to replicate this on a more current version of Grafana. Using the devenv prometheus datasource, ensuring that the query editor for prometheus starts in "Code" mode and with the settings legend: auto, min step: undefined, format: time series, type: both, no exemplars shows the table and the chart every time. As far as I know, there was no dedicated effort to fix this bug so it must have gotten unintentionally fixed along with other work. Please feel free to reopen if you run into this after updating.

**Comment by ngc104** [comment]
Hello,

I confirm : I cannot reproduce on 9.1.5.

Thanks for your attention.
