### ISSUE TITLE
TimePicker: The tooltip is always shown after selecting a quick time range. requiring a click to hide 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#51037]
![Screenshot from 2022-06-17 15-04-31](https://user-images.githubusercontent.com/10999/174303890-d5cd95f9-8cac-4a7a-84ea-a92b17eefaa7.png)

Replicate
* Click time range picker
* Select a quick range
* See tooltip being shown 

Not sure when this started happening or why.

**Comment by DmitrySidorow** [comment]
in addition to this, I don't like that it can only be closed by clicking on the check mark on the right, previously the closure worked for the entire area

**Comment by joshhunt** [comment]
This happens with all the items up in that little header. If you click the dashboard settings cog and click  ⬅️ Back arrow then the Dashboard Settings tooltip will be visible (when it shouldn't).

This is probably due to some focus trap/restoration thing.

**Comment by oscarkilhed** [comment]
`<FocusScope>` is causing this.

When `restoreFocus` is set and it unmounts, it sets the focus back to the component the user clicked, triggering the tooltip to show.

I see two immediate solutions, both are a trade off for accessability. Either we don't show the tooltip on focus, which makes it impossible to see the tooltip for someone using the keyboard to navigate, or we don't restore the focus when the `FocusScope` unmounts. Not restoring the focus will make it a bit awkward to navigate with keyboard.

I'm sure there's some more complex solution where we only restore the focus if the FocusScope mounting was triggerd by keyboard.

**Comment by natellium** [comment]
@yaelleC @axelavargas @JoaoSilvaGrafana any thoughts? There's a PR from an external contributor attached too

**Comment by JoaoSilvaGrafana** [comment]
This is an interesting one, because from a keyboard user perspective this is actually working well, so we either have a tradeoff on the UI or on accessibility.

If we do want to fix it, from the two options @oscarkilhed mentioned, I don't think not showing the tooltip on focus is viable, because the icons are not really enough to understand what each button does.

For an accessibility tradeoff, in my opinion not restoring the focus is the lesser of two evils. If you just remove the `restoreFocus` option, then when selecting a time range it loses the focus, but if you press tab it does actually continue to the next button (the zoom out), so it is not _terrible_.

**Comment by oscarkilhed** [comment]
I've submitted a PR to remove the restoreFocus and suggest we handle the accessibility issue and the similar issue with the settings button as separate issues.

**Comment by natellium** [comment]
Fixed by https://github.com/grafana/grafana/pull/51836
