### ISSUE TITLE
Migration from 8.5.2 to 9.0.0 failed 

### ISSUE THREAD

**Issue by mravvv** [grafana/grafana#51069]
**What happened**:
I've tried to upgrade from v.8.5.2 to v.9.0 but  upgrade process has failed with an error:
INFO [06-18|17:36:41] Starting Grafana                         logger=settings version=9.0.0 commit=b5c56f637 branch=HEAD compiled=2022-06-13T15:06:48+03:00
INFO [06-18|17:36:41] Config loaded from                       logger=settings file=/usr/share/grafana/conf/defaults.ini
INFO [06-18|17:36:41] Config loaded from                       logger=settings file=/etc/grafana/grafana.ini
INFO [06-18|17:36:41] Path Home                                logger=settings path=/usr/share/grafana/
INFO [06-18|17:36:41] Path Data                                logger=settings path=/usr/share/grafana/data
INFO [06-18|17:36:41] Path Logs                                logger=settings path=/usr/share/grafana/data/log
INFO [06-18|17:36:41] Path Plugins                             logger=settings path=/usr/share/grafana/data/plugins
INFO [06-18|17:36:41] Path Provisioning                        logger=settings path=/usr/share/grafana/conf/provisioning
INFO [06-18|17:36:41] App mode production                      logger=settings
INFO [06-18|17:36:41] Connecting to DB                         logger=sqlstore dbtype=mysql
INFO [06-18|17:36:41] Starting DB migrations                   logger=migrator
INFO [06-18|17:36:41] Executing migration                      logger=migrator id="rename data_keys name column to label"
ERROR[06-18|17:36:41] Executing migration failed               logger=migrator id="rename data_keys name column to label" error="Error 1054: Unknown column 'name' in 'data_keys'"
ERROR[06-18|17:36:41] Exec failed                              logger=migrator error="Error 1054: Unknown column 'name' in 'data_keys'" sql="ALTER TABLE `data_keys` CHANGE `name` `label` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
Failed to start grafana. error: migration failed (id = rename data_keys name column to label): Error 1054: Unknown column 'name' in 'data_keys'
migration failed (id = rename data_keys name column to label): Error 1054: Unknown column 'name' in 'data_keys'

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade from v.8.5.2 to v.9.0.0 using mysql database

**Comment by joanlopez** [comment]
Hi @mravvv, thanks for reporting!

Hmm.. this looks weird! Looks like [this](https://github.com/grafana/grafana/blob/b5c56f63710e09f37b8557ddd8b99ae3fc583169/pkg/services/sqlstore/migrations/secrets_mig.go#L65) is the migration that's failing, but what looks weird to me is that the migration just before the one failing relies in the same column (that seems to do not existing) but does not seem to be failing 🤔 

In order to help with the research of this bug, would you be able to share the most recent entries present in the migrations database table (`migration_log`), please? We'll continue investigating from our side meanwhile.

Thanks!

**Comment by joanlopez** [comment]
Hello @mravvv,

Okay, I see. Now I understand why in your previous log, the migrator starts from that specific migration, because it failed and you re-tried, right? (Not a problem at all, just confirming to have as much context as possible in order to help).

That being said, I've been looking into the migrations related with `data_keys` table in `v8.5.2` ([here](https://github.com/grafana/grafana/blob/v8.5.2/pkg/services/sqlstore/migrations/secrets_mig.go)) and `v9.0.0` (from [here](https://github.com/grafana/grafana/blob/v9.0.0/pkg/services/sqlstore/migrations/secrets_mig.go#L46)). So, as you can see, there are multiple migrations that should have been executed previously, before the one failing. Otherwise, it'd mean the database is in an inconsistent state, but even in that case, the `name` column should exist (see [here](https://github.com/grafana/grafana/blob/v8.5.2/pkg/services/sqlstore/migrations/secrets_mig.go#L9) from the table definition at `v8.5.2`).

Could you share with us any evidence (migration executed) present in the your `migration_log` table related with the `data_keys` table, please?

Thanks!

**Comment by undef1nd** [comment]
Hey @mravvv,
Thanks for logs! From what I see there, `name` column does exist in the `data_keys` table.
But just to double check - could you please share the DDL of this table (could be done via `SHOW CREATE TABLE data_keys`)? Thanks!

**Comment by joanlopez** [comment]
Great, then it's partly good news (easier to fix).

My suggestion in that case would be to:

1. Drop the table:

  `DROP TABLE data_keys; `

2. Remove executed migrations related with that table:

  Either this: 
  
  ```
  DELETE FROM migration_log
WHERE migration_id IN (
                       'create data_keys table',
                       'rename data_keys name column to id',
                       'add name column into data_keys',
                       'copy data_keys id column values into name',
                       'rename data_keys name column to label',
                       'rename data_keys id column back to name'
);
```

  or this:

  ```
  DELETE FROM migration_log WHERE migration_id LIKE '%data_keys%'
  ```

3. Confirm there's no one of the migrations [here](https://github.com/grafana/grafana/blob/v9.0.0/pkg/services/sqlstore/migrations/secrets_mig.go#L46) present in your `migration_log` table.

4. Run migrations again (start up Grafana again).

Looking for your feedback on results after following these steps. I hope it helps! 🤞🏻 

Thanks!

**Comment by mravvv** [comment]
@joanlopez ,

Yep, it helped, v.9.0.0 is running now! Thanks a lot :)

**Comment by joanlopez** [comment]
Hey-ya! I'm glad to read that! 😊 

Still a bit concerned about how your database ended up in that inconsistent state and if the reason that caused that (no idea, honestly) could have impacted other tables. But good news anyway.

Then, I think it's fair to close the issue.
Please, don't hesitate to re-open it or open another one if you detect any other weird behavior.

Thanks!

**Comment by Jasstkn** [comment]
Hello @joanlopez! 
I also faced with this issue after upgrading from 8.5.x to 9.1.7. After upgrade I noticed that I can't add a new datasource and I got "500" from Grafana with error about missing values in the data_keys table. Then I found out that I'm unable to login to Grafana via Github Oauth provider. Described steps helped me to resolve both issues but I am still wonder why did it happen in the first place. In our installation we have Grafana with 2 replicas but with the same sqlite database shared via PVC. I think this is the root cause of this failure. But I'm not 100% sure, because on the different environment with exactly the same setup this issue wasn't reproduced at all.

**Comment by joanlopez** [comment]
Hello @Jasstkn!

> Described steps helped me to resolve both issues

Happy to read that 😄

> but I am still wonder why did it happen in the first place

> In our installation we have Grafana with 2 replicas but with the same sqlite database shared via PVC. I think this is the root cause of this failure. But I'm not 100% sure, because on the different environment with exactly the same setup this issue wasn't reproduced at all.

Yeah, I agree it sounds like some kind of lock or conflict between both instances while executing the database migrations. I vaguely recall about some work in that direction for MySQL and Postgres (like [this](https://github.com/grafana/grafana/pull/44101)) but I don't recall the details and still not sure what could have happened exactly in your case.

If you somehow manage to reproduce it again and/or to get further details, don't hesitate to fill a new issue with all the information and we'll try to work on it, it'll be really appreciated.

Thanks! 😊
