### ISSUE TITLE
TimeSeries problem with bar 9.0.0 (narrow bar)

### ISSUE THREAD

**Issue by deejayluk** [grafana/grafana#51085]
**What happened**:
The bar are narrow

![image](https://user-images.githubusercontent.com/73607094/174530925-00a2de76-7a09-4905-9dfc-b44d340ca7e6.png)

**What you expected to happen**:
correct this issue, the problem are from verion 8.5.2
**Anything else we need to know?**:
In the version 8.4.4 everything was okay
**Environment**:
Grafana version: 8.5.2
Data source type & version: MSSQL
OS Grafana is installed on: Ubuntu 20.04.4 LTS
User OS & Browser: Chrome
Grafana plugins: TimeSeries
Others: N/A

RAW Data:
[data-2022-05-16.10_52_30.csv](https://github.com/grafana/grafana/files/8937734/data-2022-05-16.10_52_30.csv)

**Comment by leeoniya** [comment]
this happens because we assume in some parts of the code that the Time field is the first field in the frame. we then use that field to determine the minimum adjacent spacing between timestamps to figure out the bar width for a given dataset and visible timerange.

you can get this to work by doing any of:

1. modify your query to select the time column first
2. use the `Prepare time series` transform which, among other things, will put the time field first
3. use the `Organize fields` transform to move the time series field to the first position

**Comment by deejayluk** [comment]
okay, I changed code, the time column is first and bar are okay

**Comment by leeoniya** [comment]
:+1:
