### ISSUE TITLE
Unified alerting: Grafana 9.0.0 migration failed

### ISSUE THREAD

**Issue by GBBx** [grafana/grafana#51112]
**What happened**:
I have Grafana 8.5.5 with some dashboards that contain panels with alerts. I've never used unified alerting.
When I try to upgrade to 9.0.0 the migration fails and Grafana does not start anymore.

**What you expected to happen**:
Grafana to start.

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade Grafana via DNF from 8.5.5 to 9.0.0

**Anything else we need to know?**:
Logs:
```
logger=migrator t=2022-06-20T13:35:33.993793813+02:00 level=info msg="Starting DB migrations"
logger=migrator t=2022-06-20T13:35:34.000891718+02:00 level=info msg="Executing migration" id="clear migration entry \"remove unified alerting data\""
logger=migrator t=2022-06-20T13:35:34.001231789+02:00 level=info msg="Executing migration" id="move dashboard alerts to unified alerting"
logger=migrator t=2022-06-20T13:35:34.004774191+02:00 level=error msg="Executing migration failed" id="move dashboard alerts to unified alerting" error="json: cannot unmarshal array into Go struct field dashAlertSettings.alertRuleTags of type map[string]string"
logger=migrator t=2022-06-20T13:35:34.004889794+02:00 level=error msg="Exec failed" error="json: cannot unmarshal array into Go struct field dashAlertSettings.alertRuleTags of type map[string]string" sql="code migration"
```

**Environment**:
- Grafana version: 9.0.0
- Data source type & version: Loki
- OS Grafana is installed on: AlmaLinux
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by gotjosh** [comment]
Hi @GBBx,

I was able to reproduce this by using an array instead of a JSON object as the key for `alertRuleTags ` in a dashboard. 

I believe this is a discrepancy between what values we expect the dashboard key `alertRulesTag` to have - have you by any chance manually edited this field in the past? I don't think Grafana would throw a warning or an error based on this.

To solve the problem, you can probably delete that key and make it `alertRuleTags: {}` instead of `alertRuleTags: []` but I think we can do better at migration time to try and parse it directly. I'll whip up a pull request.

**Comment by GBBx** [comment]
Hi @gotjosh ,
removing the AlertRuleTags lines from the provisioned dashboard json files helped in one case.
But I have multiple machines and on one of them I still have the error even if I delete all the files from the provisioning folder and restart Grafana.
I don't know where it comes from. Is it in the database somewhere?
