### ISSUE TITLE
[Feature Request] Allow lucene multi value format in drilldown links

### ISSUE THREAD

**Issue by felixbarny** [grafana/grafana#5127]
I want to link from a Grafaha graph to a Kibana dashboard while applying all selected template variables but I have problems when using template variables where multiple selections are allowed. The multi value format is not lucene compatible then. A dropdown like in the templating editor would be awesome.

![](https://a.disquscdn.com/uploads/mediaembed/images/3572/5515/original.jpg)

Also, are there separate template variables for from and to? This would be very useful to keep the time range in Kibana.

This is how the templated link would look like:

```
/app/kibana#/dashboard/Request-Analysis?_a=(query:(query_string:(query:'instance:$Instance')))&_g=(time:(from:now-1h,mode:quick,to:now))
```

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
