### ISSUE TITLE
is this incorrent search result by interval 1d  with local timezone or operation mistake?

### ISSUE THREAD

**Issue by XasaKura** [grafana/grafana#5147]
version 3.0.3 RELEASE
db : Elasticsearch
timezone: Asia/Shanghai  (+8.00)

![localtimezone](https://cloud.githubusercontent.com/assets/15218277/15490254/01452d26-2199-11e6-92ac-d2e9202be4b4.png)
![utctimezone](https://cloud.githubusercontent.com/assets/15218277/15490255/014695c6-2199-11e6-8a6e-e6fef58e0110.png)

when I change timezone from utc to Asia/Shanghai , the time display look like '2016-05-23 08:00:00'.

but I want to search result between 2016-05-22 00:00:00 and 2016-05-23 00:00:00 in Asia/Shanghai (between  2016-05-21 16:00:00  and 2016-05-22 16:00:00 in UTC)

And  the result is not change, maybe just change display time?

Sorry for my poor English.

PS:
if I change intelval to 1h 10m or other time less than  1d  they are current.

**Comment by torkelo** [comment]
this is how the elasticsearch datehistogram works.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html

Not sure Elasticsearch has a feature to align the time buckets with real days. But if you set your time range so it aligns with midnight that might do it.

**Comment by kinhunt** [comment]
@torkelo I having the same problem here. Changing the time range setting doesn't seem to work. Tried both 'Override relative time' and 'Add time shift', they change query time range only. Unable to align datapoint to midnight. Any other settings I can try? Thanks.

**Comment by Bellovitello** [comment]
I'm looking at the same problem and I found that it is possible to align time buckets to real days in Elasticsearch: you need to specify _time_zone_ parameter in your ES query and use _basic_date_time_ format in gte and lte fields.

For example my working ES query filter is:
`"filter":{"bool":{"must":[{"range":{"time":{"gte":"20160630T000000.000Z","lte":"20160630T235959.999Z","format":"basic_date_time","time_zone": "America/Los_Angeles"}}}]}}}},"aggs":{"2":{"date_histogram":{"interval":"1d","field":"time","min_doc_count":0,"time_zone": "America/Los_Angeles","format":"epoch_millis"}`

And the original grafana query filter if:
`{"gte":"1467237600000","lte":"1467323999000","format":"epoch_millis"}}}]}}}},"aggs":{"2":{"date_histogram":{"interval":"1h","field":"time","min_doc_count":0,"format":"epoch_millis"}`

It seems that ES grafana plugin doesn't send _time_zone_ parameter and it uses _epoch_millis_ as format for time fields instead of _basic_date_time_.
