### ISSUE TITLE
Request for more flexibility of aggregations in legend 

### ISSUE THREAD

**Issue by dengliu** [grafana/grafana#5161]
The aggregation functions in legend give us extra insight about the data in a specific time range.
It would be great helpful to allow people to customize the aggregation functions. 
E.g. , I have collected the flow rate in the unit of kg/hour in the interval of 1 sec, if I am allowed to divide total by 3600, I will get the total mass of a specific time range.

![screen shot 2016-05-24 at 3 19 36 pm](https://cloud.githubusercontent.com/assets/5108773/15521933/8d6e6a54-21c3-11e6-81a3-160a79253f1a.png)
![screen shot 2016-05-24 at 3 19 45 pm](https://cloud.githubusercontent.com/assets/5108773/15521934/8d6f2e8a-21c3-11e6-9c5b-690d2ba64cf8.png)

**Comment by daniellee** [comment]
I think we would prefer to solve this at a different level. Rather than extending the legend options for the Graph panel, this could be done at the query level using [Transformations](https://grafana.com/docs/grafana/latest/panels/transformations/types-options/) or backend expressions (coming soon).
