### ISSUE TITLE
Inconsistent timeFilter resolution between ordinary and alert queries

### ISSUE THREAD

**Issue by puzpuzpuz** [grafana/grafana#51611]
**What happened**:

`__timeFilter` macro yields different timestamp resolution when used in ordinary (panel) and alert queries for PostgreSQL data source.

```
WHERE
  $__timeFilter(ts)
```

The above WHERE clause generates the following result for a panel query (notice millisecond resolution):

```
WHERE ts BETWEEN '2022-06-30T00:43:03.995Z' AND '2022-06-30T06:43:03.995Z'
```

while for an alert query it produces nanosecond resolution timestamps:
```
WHERE ts BETWEEN '2022-06-30T06:34:38.08965998Z' AND '2022-06-30T06:44:38.08965998Z'
```

**What you expected to happen**:

Both types of queries should use one or another resolution.

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure a PostgreSQL data source.
2. Create panel and alert rule with the `__timeFilter` macro used in WHERE clause.
3. Check generated queries.

**Anything else we need to know?**:

It's possible to produce consistent timestamps via `__unixEpochFrom` and `__unixEpochTo` macros in combination with BETWEEN and manual epoch to timestamp conversions. Yet, it would be nice to see consistent behavior for the `__timeFilter` macro.

**Environment**:
- Grafana version: 9.0.2, Docker
- Data source type & version: built-in PostgreSQL data source
- OS Grafana is installed on:
- User OS & Browser: Ubuntu 20.04 x64, Chrome 103.0.5060.53 (Official Build) (64-bit)
- Grafana plugins: none
- Others:

**Comment by dprokop** [comment]
@grafana/alerting-squad-backend or maybe @grafana/alerting-squad-frontend could you please have a look at this? We don't think this is a Postgres issue, but rather alerting providing a time range that's nanoseconds precise.

**Comment by gillesdemey** [comment]
After a bit of investigation we've found that all code paths call in to https://github.com/grafana/grafana/blob/7825ad6aa309a6bbdafe7e692460374f156a1c10/pkg/tsdb/postgres/macros.go#L86 which should formats timestamps with nano resolution, but with an important caveat – if the `timeRange` is only in millis resolution the nanos are discarded and the timestamp is formatted in millis resolution instead.

It turns out that most of the code paths (panels, explore view) don't pass in time ranges with such high resolution timestamps but the alerting evaluation endpoint (`/v1/eval`) does. The rationale here is that nano resolutions are of higher importance when alerting on data than when displaying it in a graph.

While this explain the discrepancies between the various parts of the product it doesn't present a solution; I'm curious to learn more about why the inconsistencies would be problematic? Can you elaborate a bit _why_ the inconsistency is problematic @puzpuzpuz ?

cc @JohnnyQQQQ

**Comment by puzpuzpuz** [comment]
> Can you elaborate a bit on _why_ the consistency is important @puzpuzpuz ?

QuestDB implements PG Wire, so we recommend our users to use the default Postgres plugin in Grafana. Timestamp format produced by non-alert queries is supported by QuestDB while the one used in alert queries is not supported. I've created this issue to check whether it's possible to align the formats in both query types. If not, I'm going to close the issue and fix the issue on QuestDB side.

**Comment by gillesdemey** [comment]
Gotcha, thanks for the additional context – as far as the Postgres data source is concerned we try to maintain compatibility with the official Postgres releases and versions. 

It seems like Postgres only supports up to [microsecond resolution](https://www.postgresql.org/docs/current/datatype-datetime.html) timestamps but happily accepts arbitrary resolution timestamps. 

Perhaps there is an opportunity for us to format the timestamps with a microsecond resolution to be compatible with other Postgres-compatible databases while retaining a higher resolution.

**Comment by armandgrillet** [comment]
Closing this as it can be fixed on QuestDB side.
