### ISSUE TITLE
Explore: Standardize and define when queries run

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#51979]
The Explore team has been a part of several discussions regarding definitions on when queries run automatically. Some users want queries to run immediately after an action without clicking the "run query" button as a matter of a seamless UX, and others have reservations when queries are ran automatically, as it can potentially run computationally expensive queries without any user interaction.  

It will be difficult to find a solution that will make everyone happy for every situation, but we will use this epic as a way to get an understanding of what we have in terms of queries being ran automatically and what issues our users are running into so we can brainstorm potential solutions. We can then implement those solutions and document some standardized rules so users know what to expect, and why decisions were made if our rules do not match their expectations.

The outcome of this ticket will be
- Rules on when queries would expect to be ran automatically, and when they would not
- Tickets for code changes needed for Explore or individual datasources to follow those rules
- Documentation on those rules so we can classify tickets as bugs or close them as working as intended as well as provide a reference point to be used in further discussions on the topic.

**Example issues** 
(This issue will not fix the child issues, nor should it be seen as a "fix" for any individual ticket. This is to consolidate examples of the kinds of bug tickets relating to this topic we get.)
- #51708 
- #48145

**Relevant code/PRs/definitions**
- #26161
- Run imported queries automatically ([src](https://github.com/grafana/grafana/blob/main/public/app/features/explore/state/datasource.ts#L65))

List of places the query is run in Explore (9.2.0-beta1):

* Command Palette:
  * Run query https://github.com/grafana/grafana/blob/release-9.2.0-beta1/public/app/features/explore/ExploreActions.tsx#L75
  * Split view: Run query (right) https://github.com/grafana/grafana/blob/release-9.2.0-beta1/public/app/features/explore/ExploreActions.tsx#L46
  * Split view: Run query (left) https://github.com/grafana/grafana/blob/release-9.2.0-beta1/public/app/features/explore/ExploreActions.tsx#L35
* Query Rows / Callback passed to plugins: https://github.com/grafana/grafana/blob/main/public/app/features/explore/QueryRows.tsx#L48
* Query imports: Run after a query is imported: https://github.com/grafana/grafana/blob/main/public/app/features/explore/state/datasource.ts#L72
* Explore panes:
  * Initialize Explore: https://github.com/grafana/grafana/blob/main/public/app/features/explore/state/explorePane.ts#L184
  * Refresh Explore: https://github.com/grafana/grafana/blob/main/public/app/features/explore/state/explorePane.ts#L243
* Query:
  * Modify queries: https://github.com/grafana/grafana/blob/release-9.2.0-beta1/public/app/features/explore/state/query.ts#L364
    * User by: Label filtering: https://github.com/grafana/grafana/blob/release-9.2.0-beta1/public/app/features/explore/Explore.tsx#L152
  * Set queries: https://github.com/grafana/grafana/blob/release-9.2.0-beta1/public/app/features/explore/state/query.ts#L616
    * Used by: Click Example on help page: https://github.com/grafana/grafana/blob/release-9.2.0-beta1/public/app/features/explore/Explore.tsx#L138
    * Used by: Run Rich History query: https://github.com/grafana/grafana/blob/release-9.2.0-beta1/public/app/features/explore/RichHistory/RichHistoryCard.tsx#L182
  * Scanning
    * Start scanning: https://github.com/grafana/grafana/blob/release-9.2.0-beta1/public/app/features/explore/state/query.ts#L633
    * Scan: https://github.com/grafana/grafana/blob/release-9.2.0-beta1/public/app/features/explore/state/query.ts#L522
    * Used by: Logs panel when no logs are found: https://github.com/grafana/grafana/blob/release-9.2.0-beta1/public/app/features/explore/Explore.tsx#L276
* Update time range: https://github.com/grafana/grafana/blob/release-9.2.0-beta1/public/app/features/explore/state/time.ts#L44
* Logs live tailing: https://github.com/grafana/grafana/blob/release-9.2.0-beta1/public/app/features/explore/useLiveTailControls.ts#L34
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/67745
```

**Comment by bohandley** [comment]
I have been working on https://github.com/grafana/grafana/issues/48145 for some time now and have gotten some good feedback from @ifrost and @Elfo404. This issue was originally brought up as a user wanting a query to be run on copying and pasting it into the graphite text editor. @mellieA worked on reproducing the issue and identified that a query is not run when clicking "duplicate" on a query editor row. So, we have two issues on when queries should be run here.

First, I made a fix for the copy and paste using the onChange event for the QueryField component [#49111](https://github.com/grafana/grafana/pull/49111). I agree with Piotr and Gio that this would get expensive, running a query every keystroke. Even with debouncing the event, most queries would not be complete. So, I am going to not implement this in Graphite and let the user know that the query will be run onBlur.  (Side question: who would I talk to about adding an onPaste event to the QueryField component? Is this an option for the future?))

Second, I am interested in running the query on clicking "duplicate." [#51681](https://github.com/grafana/grafana/pull/51681) This is not as expensive, as we are running a single query on initializing the new. I think in a majority of cases, users will end up changing the query, but I still think this is valuable because it shows the user that the query has been run. A user can then see the difference between the copied query and whatever they change it to. I have found that the Datadog, Azure Devops, and AppDynamics automatically run a duplicated query and Prometheus does not. 

So, I would like to implement the second case(run query on duplicate) and I am not intending to implement the first(run query on copy and paste). I am open to suggestions for these fixes, and look forward to seeing the rules that come out of this discussion. Thanks @gelicia!

**Comment by bohandley** [comment]
Ok, after all of that investigation and exploration, for Graphite, I agree that it should behave like Prometheus. The query should be run when clicking outside the input(onBlur) or when clicking the 'Run Query' button. The query should not be run on copy and paste of a query nor on duplicating a query. Thank you!

**Comment by bboreham** [comment]
For what it's worth, I offer my story: I am a software engineer who troubleshoots in production; I use Grafana Explore and PromQL most days, sometimes hundreds of times in a day.

I developed the habbit of adding an 'x' somewhere in the query to make it invalid, when I need to click out of the edit field.  I do this to ensure if Grafana decides to run the query automatically it will quickly fail.  I remove the 'x' when I do want to run the query.

The reason is, if I am assembling a query by copy-pasting pieces from other windows, I may temporarily have a query which will return hundreds of thousands of timeseries, and if that runs it will bog down everything in the chain, possibly rendering my machine unusable until the process crashes and memory is freed up.

So, I would prefer that Explore did not automatically run the query.

**Comment by ifrost** [comment]
Related PR: #64815

**Comment by svennergr** [comment]
Just sharing this here: we noticed that queries in Loki are autosubmitted on changes in the query options. Similar for Prometheus. 
![image](https://user-images.githubusercontent.com/8092184/226604996-df67c855-c102-4b9e-95ea-b47b8b42659a.png)

That feels wrong and should be improved.

**Comment by torkelo** [comment]
I do not think we can disable the run query button as query editors that have a text field need to be able to issue the query when you hit shift+enter , this is pretty important workflow

**Comment by bboreham** [comment]
Not sure if anyone suggested disabling the button - I thought we were talking about all the times the query will run when you didn't explicitly ask it to.

**Comment by torkelo** [comment]
@gelicia that is the challenge, if you remove the ability for data sources to control when the query should be executed then it could be tricky to implement shift+enter action as it only should happen for some inputs inside the editor. We could add some attribute to the inputs that should have this behavior potentially and subscribe to the keyboard event from outside the plugin component, so might not be impossible but a bit messy

**Comment by torkelo** [comment]
but second thought it could be possible but shift+enter (or some just enter key) to execute query is a very important feature for many editors

**Comment by ifrost** [comment]
We are not planning to work on this issue in the foreseeable future. Please upvote or comment if you would like it to be prioritized.
