### ISSUE TITLE
Explore: Loading query field takes too long and allows typing in it before it has loaded

### ISSUE THREAD

**Issue by polibb** [grafana/grafana#52213]
**What happened**:

On the Explore page, the field for a query loads after a long while and deletes all that has been written in it before it has loaded fully. It takes around 10 seconds sometimes.

On the video: Reload the page. Change the datasource. Type in some random "query" just for the example. See the field load fully and delete your progress in the process.

https://user-images.githubusercontent.com/13227501/178956121-c001772f-336f-45b9-b983-9d91e906f327.mov

**What you expected to happen**:

The field for the query either loads immediately, or it preserves the query I have written already once it the field has fully loaded.

**How to reproduce it (as minimally and precisely as possible)**:

Open the Explore page and go to Code tab for the query operation. 
Change the datasource and start typing a query for it. The field for a query loads after a while and deletes all that has been written in it before it has loaded fully. 

**Anything else we need to know?**:

Discussed that it is an issue with @dimitarvdimitrov and is loading so slowly on his system. 

**Environment**:
- Grafana version: 9.0.3
- OS Grafana is installed on: macOS 12.4, arm64
- User OS & Browser: Chrome 103.0.5060.114

**Comment by Elfo404** [comment]
does the same thing happen also in dashboards? i suspect this specific to the plugin itself, not Explore.
cc. @grafana/observability-logs-and-traces

**Comment by gabor** [comment]
what seems to be happening, is that when switching the datasource, we try to apply the query from the "previous" datasource (like, switching from `prometheus` to `loki`), and somehow we do it after label-browser has loaded, so if you enter something while the label-browser is loading, things get overwritten when it loads.

will look more into this.

**Comment by dimitarvdimitrov** [comment]
> does the same thing happen also in dashboards? i suspect this specific to the plugin itself, not Explore. cc. @grafana/observability-logs-and-traces

only happens in explore, not in dashbaords.

> when switching the datasource

I can confirm this only happens when switching the datasource. If I open a new tab with the loki datasource and start typing a query before the labels have loaded, my query _does not_ get deleted.

**Comment by gabor** [comment]
i did some more investigation, and the bug seems to be in the generic grafana-explore-mode-code here: https://github.com/grafana/grafana/blob/main/public/app/features/explore/state/query.ts#L262-L295

what happens is, when switching between datasources, this part of the code is responsible for trying to represent the "query in previous datasource" somehow in this datasource. for it, it calls various `async` methods on the datasources, and at the end sets a new query-expression based on what the datasources return. the problem happens when these events happen:

1. we switch to a different datasource
2. `importQueries` starts, and calls some `async` methods
3. while those `async` methods are running, the user enter some query in the query-field
4. now [2] finishes, and overwrites the user's output with the result of [2]
to trigger this, the easiest i have found is to add some

**Comment by Elfo404** [comment]
thanks for taking a look @gabor, my mistake. we'll look into this better.

**Comment by ifrost** [comment]
I wasn't able to reproduce it in the latest version. I think that with recent changes to mixed data sources in Explore the behavior changed and the editor is loaded only after queries are imported. In the case of Loki, importing queries may be slow if the request for getting labels is slow (Loki requires labels for importing to skip labels that do not exist). On the other hand, labels are cached so it's going to happen only once.

A side effect of recent changes is that Explore shows the previous/stale editor until importing is complete (see video below). Maybe we should show the user that the query builder is loading? One more option is to skip importing if it takes too long, but maybe better would be better to add some logic to Loki plugin to skip label verification if it takes too long and simply use all provided labels.

https://user-images.githubusercontent.com/745532/190639591-3e511aec-7337-41ca-929e-db4dee7e09e1.mov

**Comment by dimitarvdimitrov** [comment]
this is still happening for me on v9.2.0-33906pre (469f915b8c). Just tried it on an internal grafana instance. Can share this in a DM.

Is it possible to just abandon the labels lookup if the user has typed something? Or if the initial prometheus query is empty?

**Comment by ifrost** [comment]
> Is it possible to just abandon the labels lookup if the user has typed something? Or if the initial prometheus query is empty?

Yes, this could possibly be done in Loki plugin (cc @grafana/observability-logs)

**Comment by gabor** [comment]
@dimitarvdimitrov sorry, could you explain in more detail, what is still happening for you?
- is it the original problem as described by @polibb  https://github.com/grafana/grafana/issues/52213#issuecomment-1194062357 
- or what @ifrost described in https://github.com/grafana/grafana/issues/52213#issuecomment-1249309336 ?
- 
thanks!

**Comment by dimitarvdimitrov** [comment]
I was replying to @ifrost's comment:

> I wasn't able to reproduce it in the latest version. 

Whatever I typed into the query field after changing the datasource is still getting erased after the query is imported.

**Comment by dimitarvdimitrov** [comment]
Now I see what you were asking.

I'm not sure how to tell if the UI changed the datasource. The dropdown in the top left changes immediately. Is it the text in parenthesis next to the query ID? 
![Screenshot 2022-09-19 at 17 28 48](https://user-images.githubusercontent.com/21020035/191054997-7cf4ba50-a871-4847-b162-ec65dae3b650.png)

If yes, then I am observing the original report. I start with an empty query, change the datasource from the dropdown, the text in parenthesis changes, I write something in the query field, after some time my query is erased.

I also reproduced by starting with a non-empty query. In this case after some time, the UI doesn't erase my new query, it reverts it to the importer version of my starting query.

Should I file a new report for the issue ifrost showed? In my mind it's the same user experience, that's why I didn't realize there was a difference.

**Comment by ifrost** [comment]
We had a chat with about it with @gabor. We don't want to skip label validation in Loki to workaround this problem, but rather find a better flow for query imports. I've created an issue for it here https://github.com/grafana/grafana/issues/55462, once implemented it should fix the problem.

**Comment by ifrost** [comment]
Should be fixed by https://github.com/grafana/grafana/issues/62747

**Comment by dimitarvdimitrov** [comment]
i can no longer reproduce this on Grafana v11.2.0-72874 (77a4869fca)
