### ISSUE TITLE
Megamenu scrolling indicator

### ISSUE THREAD

**Issue by amy-super** [grafana/grafana#52285]
In the [navigation proof of concept user test](https://docs.google.com/presentation/d/1TKS7ILN30mC6TCBSNnC7efU1vnpQ_Bl3tdTJgjBVq_E/edit#slide=id.g10b7a169e20_0_12), some users found navigating the megamenu to be difficult once it was completely expanded. It was unclear that there was more content below as the scrollbar automatically hides. 

I believe we have something to indicate scrolling already but need to check with the team to see if design is needed. I think @ashharrison90 is most familiar with this and can maybe comment here or link to a related issue or PR. 

<img width="304" alt="Screen Shot 2022-07-14 at 4 03 53 PM" src="https://user-images.githubusercontent.com/87499219/179073433-88d5497d-5c04-420b-983a-a68dfecca433.png">

**Comment by ashharrison90** [comment]
@amy-super i've added the scroll indicators to the `MegaMenu`/`SectionNav` here: https://github.com/grafana/grafana/pull/54705 

we can tweak the design of these (if we want to) later. i do think we should use them sparingly and keep the design fairly muted, because they create clutter if there's lots of them

**Comment by amy-super** [comment]
@ashharrison90 I think these work well here - and agree they should be used sparingly. But for now this is a good solution 👍

**Comment by ashharrison90** [comment]
this has been done by https://github.com/grafana/grafana/pull/54705
