### ISSUE TITLE
Loki: Label filter with number value changes to string in query builder

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#52339]
**What happened**:
1. Write a query with label filter containing number value `{place="luna"} | logfmt | label != 5`
2. Change to query builder mode
3. change value to 6
4. The resulting query is` {place="luna"} | logfmt | label != `5`` with extra ` around number as we turned number into string. 

https://user-images.githubusercontent.com/30407135/179250908-59dd44a4-926b-4904-a4f9-24bdba282d3d.mov

**Environment**:
- Grafana version: main

**Comment by ivanahuckova** [comment]
Closing this up until https://github.com/grafana/loki/issues/6713 is resolved to see if this was actually loki issue.

**Comment by cyriltovena** [comment]
It's not related to the Loki issue. You should know that label filter are typed and the type is very important! This is because the type is used to infer the type transformation Loki will do in the log.

Avalaible type are :
- string
- number
- bytes (10kb,10MB,...)
- duration (5ms,1m)

For instance if `foo > 5` then Loki will try to convert `foo` from a string (it always is a string at first) to an int. The same apply for `foo > 5ms` Loki will convert every label `foo` in the log from a string to a duration then apply the binary operation of the filter.

Hope this helps, in my opinion you should may be avoid changing the type from one to another in place of the user.
