### ISSUE TITLE
Loki doesn't return data when the interval is too small

### ISSUE THREAD

**Issue by jhthedev** [grafana/grafana#52403]
**What happened**: Loki doesn't return any data when the interval is too small. For example, I have one log line saved in the last 7 days. If I set the interval to 5 min, Loki returns nothing. When the interval is changed to 10 min, this log line is plotted onto the graph.

**What you expected to happen**: Loki returns data or gives an error.

**How to reproduce it (as minimally and precisely as possible)**:

1. Set time range to 7 days or longer
2. Set interval to 5 min or shorter
3. Nothing plotted
4. Change the interval to larger numbers, the graph will be displayed

**Anything else we need to know?**:

The range in the interval variable.

![Interval 5 min](https://user-images.githubusercontent.com/3295998/179520738-1380bd75-a2c5-4ebd-a3e5-8d8707e562be.png)

![Interval 10 min](https://user-images.githubusercontent.com/3295998/179521052-0d2acc75-dc0c-4ade-a454-2e083cdccd02.png)

**Environment**:
- Grafana version: v9.0.3
- Data source type & version: Loki 2.6.1
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10 19044 & Microsoft Edge 103
- Grafana plugins: not related
- Others: none

**Comment by usmangt** [comment]
Hi @jhthedev ,

Thanks for the details + screenshots.

So, If I understood it correctly, there is a log line (in a log file) written 7 days ago.

And you want to view it in the Dashboard panel, but you are selecting the time range either to 5 mins or 10 mins.

If my understanding is correct then I think Its more about selecting the correct time range to view it correctly in the panel.

If not then please provide further details.

**Comment by jhthedev** [comment]
Hi @usmangt , thanks for your reply.

We do have a log line written in the last 7 days. We set the time range fixed to from 7 days to now.
The "range" in the screenshot is the name of a variable, which changes `$__interval`. Yes I admit the naming is very confusing. When we set the **range** (aka the interval) to 5 min, the log line is not plotted. But with 10 min, it does show up. We use `sum` and `count_over_time` in the query. The query is something like this:
```
sum by (some_label) {
  count_over_time (
    {some_criteria}
    | some pipelines
    [$range]
  )
}
```

I think this is a similar situation to [this issue](https://github.com/grafana/grafana/issues/50220). Instead of using the built-in `$__interval`, we want more control over aggregation and see consistent results when the variable is changed.

**Comment by gabor** [comment]
hi @jhthedev, i'm not 100% sure how the data is fed into the visualization (when doing `count_over_time`, it's usually fed into a time-series graph), but i'll try to describe a couple scenarios:

1. you are asking for a 7day time-range, one data-point every 5minutes that's roughly 2000 data-points. this can be a problem when this is drawn into a time-series-graph for example, when you do not have 2000pixels available. basically, the problem described in https://github.com/grafana/grafana/issues/50220
2. if Loki itself does not return the data you think it should return for the query, then i recommend reporting this in the Loki issue tracker at https://github.com/grafana/loki . please make sure Loki is really not returning the data, and the problem is not some visualisation-configuration. an easy way is to load the result of the query into a table-visualization, where you can see every data-point returned.
3. you are saying "we want more control over aggregation".. could you describe what is it that you are trying to achieve but is not possible? currently you can:
    - use a fixed aggregation-window
    - use a dynamic aggregation-window based on the available visual space (`$__interval`)
        - you can make sure it's never too low by using the `min interval` value in the query option
        - you can make it more "fixed" by using the `max data points` value in the query option

**Comment by jhthedev** [comment]
Hi @gabor , thanks for the detailed investigation. I believe this is a Loki issue, similar to the mentioned ticket. I will look into it again and see if it is necessary to create another new ticket for that.
For "more control over aggregation" I mean we would like to have several predefined intervals, and expect all the data returned and plotted. We are happy with all the options provided by Grafana now, this argument is followed by Loki's behavior.

From my side there's nothing unclear. Please close this issue if it's all good to you.
