### ISSUE TITLE
Library Panels : When saving a new library panel

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#52586]
When we open the Library Panels under Dashboards menu we get the list of added library panels. When we try to open a library panel its connections are loaded in order to get the list of dashboards it is connected to. However, the /connections API response carries a list of dashboards without their UIDs, just their IDs. When we then look for those dashboards through the /search API we use the dashboardId param because we have no knowledge of the dashboardUID as this point.

**Comment by polibb** [comment]
When we open the Library Panels under Dashboards menu we get the list of added library panels. When we try to open a library panel its connections are loaded in order to get which dashboards it is connected to. However, the `/connections` API response carries a list of dashboards without their UIDs, just their IDs. When we then look for those dashboards through the `/search` API we use the `dashboardId` param because we have no knowledge of the dashboardUID as this point.
