### ISSUE TITLE
Improve documentation of `hide_version` configuration setting

### ISSUE THREAD

**Issue by Koen1999** [grafana/grafana#52888]
The new configuration setting `hide_version` introduced in https://github.com/grafana/grafana/pull/24919 is not documented appropriately on https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/.

To my understanding, this option can be used to mask the Grafana version number for unauthenticated users.

And perhaps this is another issue, but you may consider enabling this by default even though it's not really a security improvement. If the front page screams to everyone that an update for Grafana is available, it may be tempting to go look for vulnerabilities in that deployment.

**Comment by GrafanaWriter** [comment]
@chri2547 - would you please research?

**Comment by GrafanaWriter** [comment]
@Koen1999 - I'm triaging the docs backlog, and I _believe_ this issue is still present. Unfortunately, we don’t have a dedicated writer for this area; if it is it still an issue, can you please create a PR and ping us on #docs to review?

And, please don’t let us be a blocker - use [our Writers' Toolkit](https://grafana.com/docs/writers-toolkit/). If the PR isn't reviewed by the time you need to merge, please move forward.

**Comment by Koen1999** [comment]
> @Koen1999 - I'm triaging the docs backlog, and I _believe_ this issue is still present. Unfortunately, we don’t have a dedicated writer for this area; if it is it still an issue, can you please create a PR and ping us on #docs to review?
> 
> And, please don’t let us be a blocker - use [our Writers' Toolkit](https://grafana.com/docs/writers-toolkit/). If the PR isn't reviewed by the time you need to merge, please move forward.

Thanks for getting back to this issue. I can confirm it's still present. Considering I don't use Grafana for any of my current projects (and there is a company who may profit of it), I would prefer not investing my personal time in this. However, I think the issue may still be relevant for present/future users.

**Comment by moxious** [comment]
I had a look at this ticket.  Since it was written, the relevant documentaiton on anonymous auth and hide_version has moved to here:  https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/grafana/#anonymous-authentication

Honestly, I don't know if there's anything left to do on this ticket.  The documentation is sparse, but it's documented, it's there, and it says what the option does:

> Hide the Grafana version text from the footer and help tooltip for unauthenticated users (default: false)

That might be about all that needs to be said in the configuration reference?  There could be security tradeoff language (about when and why you'd do this) but that type of language won't tend to fit in this reference-oriented topic (most other configuration items eventually need similar treatment)

**Comment by GrafanaWriter** [comment]
Given that we have - albeit sparse - documentation, I will close this issue.

**Comment by d-Rickyy-b** [comment]
Hi there, I just found this issue since the documentation on `hide_version` was still quite sparse. I only found https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-security-hardening/ but there it didn't specify the section under which the setting is configured.

For everyone searching, it is configured in the `[auth.anonymous]` section as I found out by searching the [source code](https://github.com/grafana/grafana/blob/e482c037bf930a9c810c53228f0f8c240b0a855a/conf/sample.ini#L665). For the docker folks, that translates to the env var `GF_AUTH_ANONYMOUS_HIDE_VERSION=true`.
