### ISSUE TITLE
Custom fonts and images for plugins doesn't work after v9

### ISSUE THREAD

**Issue by ZuperZee** [grafana/grafana#52923]
**What happened**:
When using the `@grafana/toolkit` `9.0.5` custom fonts and SVGs don't load.
![image](https://user-images.githubusercontent.com/39485579/181447442-b62f7350-fdc7-4454-a255-475d2776c66b.png)
![image](https://user-images.githubusercontent.com/39485579/181447675-1756393f-0a94-4f67-85b7-dd98dc75b628.png)

**What you expected to happen**:
Custom fonts and SVGs to load.
![image](https://user-images.githubusercontent.com/39485579/181446261-d5b4f811-be85-4c3d-8bd9-2f514b65b12b.png)
![image](https://user-images.githubusercontent.com/39485579/181446914-2e139769-0a7d-4173-9151-91d5e0f007c6.png)

**How to reproduce it (as minimally and precisely as possible)**:
Repo: https://github.com/ZuperZee/zuperzee-font-panel/tree/cebe4d245ff7ba992f726cd0c71f81167d3e8f1c

Add the panel plugin
Create a panel with the added panel plugin in Grafana

**Anything else we need to know?**:
Changing the toolkit to `8.5.6` loads the font properly.

This is related to https://github.com/grafana/grafana/issues/51953, but https://github.com/grafana/grafana/pull/52661 didn't seem to add the correct path.

**Environment**:
- Grafana version: v9.0.5
- Data source type & version:
- OS Grafana is installed on: Ubuntu 20.04 WSL (docker)
- User OS & Browser: Windows & Edge v103.0.1264.71
- Grafana plugins:
- Others:

**Comment by ZuperZee** [comment]
A quick workaround is to add `webpack.config.js` with the following content:

```js
const pluginJson = require('./src/plugin.json');

/**
 * @type {import("@grafana/toolkit/src/config").CustomWebpackConfigurationGetter}
 */
module.exports.getWebpackConfig = (config, options) => {
  config.module.rules.push(
    ...[
      {
        test: /\.(png|jpe?g|gif|svg)$/,
        type: 'asset/resource',
        generator: {
          publicPath: `public/plugins/${pluginJson.id}/img/`,
          outputPath: 'img/',
        },
      },
      {
        test: /\.(woff|woff2|eot|ttf|otf)(\?v=\d+\.\d+\.\d+)?$/,
        type: 'asset/resource',
        generator: {
          publicPath: `public/plugins/${pluginJson.id}/fonts/`,
          outputPath: 'fonts/',
        },
      },
    ]
  );

  return config;
};
```

**Comment by academo** [comment]
Hi @ZuperZee thanks for reporting this issue. I'm sorry to know the previous patch didn't fix this issue.

I have a new patch based on the suggested code that works locally for me here https://github.com/grafana/grafana/pull/52927

Could you please help me to test it? 

These are the instructions that work on mac,linux and windows WSL:

(I advice you to read all the instructions before following)
1) Make sure you have git, nodejs and yarn installed
2) Clone the grafana repo: `git clone git@github.com:grafana/grafana.git`
3) cd into the grafana repo `cd grafana`
4) checkout to my fix branch `git checkout academo/fix-toolkit-wrong-path-fonts-svg`
4) install the yarn dependencies `yarn --immutable`*
5) cd into the toolkit folder: `cd packages/grafana-toolkit`
6) build the toolkit: `yarn build`
7) Go to the plugin directory you want to build (e.g.: `cd /home/academo/plugins/zuperzee-font-panel`)
8) Run the following command: `NODE_OPTIONS="--require $GRAFANA_REPO/.pnp.cjs" $GRAFANA_REPO/packages/grafana-toolkit/dist/bin/grafana-toolkit.js plugin:build` 

    *IMPORTANT:* you will need to replace `$GRAFANA_REPO` with the directory where your grafana clone is. E.g. if your clone is in `/home/academo/clones/grafana/` this command would be: `NODE_OPTIONS="--require /home/academo/clones/grafana/.pnp.cjs" /home/academo/clones/grafana/dist/bin/grafana-toolkit.js plugin:build`

9) you can now test the build plugin the same way you test it when you run `yarn build` and see if it works.

Unfortunately testing the toolkit is a bit more complicated because of the special way it works, I will ping you in our slack community and assist you if you decide to help us testing.

* There is no need to run grafana from this clone, we will only use this clone to test the toolkit, you can keep running grafana from your own clone, docker or cloud.
