### ISSUE TITLE
Json View cannot work correctly after upgrade from V8 to V9.0.5

### ISSUE THREAD

**Issue by fordmao** [grafana/grafana#52972]
Json View cannot work correctly after upgrade from V8 to V9.0.5.

In V8 Table , overwrite "Cell Display Mode" from Auto(String) to "Json View" and the behavior is normal. Put mouse on the cell, popup dialog will show the whole string message.

But in V9.0.5, the same Table , overwrite "Cell Display Mode" from Auto(String) to "Json View" and there is no difference.
![image](https://user-images.githubusercontent.com/9525703/181696332-f46c0579-a4cc-4087-9097-ff932cff92c1.png)

**Comment by codeincarnate** [comment]
Thanks for the report on this. Tried this out on both 8.5.10 and 9.0.5 and I'm unable to reproduce it unfortunately in a c. Seeing the following behavior on both:

https://user-images.githubusercontent.com/199847/184006762-20d33ffc-b3e9-4a61-9068-ba13aae7edc9.mov

Going to close for now but feel free to re-open with more info if the problem is persisting.
