### ISSUE TITLE
__Potential memory leak__ The web-app crashes as long as you don't interact with it long enough

### ISSUE THREAD

**Issue by MHkaserz** [grafana/grafana#53313]
**What happened**:
The Grafana dashboard page was left up on display.
The dashboard has 6 panels that use transformation methods.
The memory used by the page was observed to be increasing non-stop.
The page would eventually crash. (seen reach 5 GB at one point)
Interacting with the page resets the memory usage to 150~300 MB.

**What you expected to happen**:
Leaving the page on display on an android device
with 2GB of RAM shouldn't cause the web-app to crash within an hour.
(or at all for that matter)

**How to reproduce it (as minimally and precisely as possible)**:
Open Grafana.
Login to a dashboard that has 6 panels that use the transformation feature.
Leave it open without interacting with it. (you can interact with anything else)
Observe the memory used by the tab/page/process going up.

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version: 9
- Data source type & version:
   -- Prometheus, with Prometheus v2.36.2 server
   -- queries are many, about 20 of the following sort:
       ---- "sum( rate(ifInOctets{instance=\~"switch0[1-3].\*"}[2m]) + rate(ifOutOctets{instance=\~"switch0[1-3].\*"}[2m]) ) * 8"
       ---- *5* "Add field from calculation" transformations followed by *1* "Organize fields" transformation in **ONE** of the panels.
       ---- *1* "Rename by regex" transformation in **ONE** of the other panels.
- OS Grafana is installed on: Linux
- User OS & Browser: (Windows 10 / Windows 11 / Android 9) & (Chrome / Firefox / Brave / Opera)
- Grafana plugins: N/A
- Others: N/A

**Comment by usmangt** [comment]
Hi @MHkaserz,

Thanks for opening this case.

Can you please also provide any information which were recorded in the logs? Might be a good idea to increase log level to debug mode in this case.

**Comment by leeoniya** [comment]
we're currently investigating a memory leak related to re-initialization of the UPlotChart component. this re-init can happen for many reasons, such as toggling a series on/off in the legend, but also as a result of the data structures changing between data updates such as field count, or other properties.

data refreshes should not typically cause frame structure or panel config changes. however, since transformations can affect frame structure, it's possible that this is being triggered, but we'll need a lot more details to try to reproduce this and see what's going on.

**Comment by MHkaserz** [comment]
- There was nothing of particular importance in the server logs.
- If you could be more specific with what kind of info would help, I'd be happy to provide such info.

![image](https://user-images.githubusercontent.com/24767465/184615862-6d685cb8-9c13-4ee6-9778-92992abe1987.png)
_(Here is a screenshot of the dashboard that if left unchecked, the memory keeps ramping up.)_

- Note that the ramping up of the memory takes a while before it is easily noticeable, specially since interacting with the page sometimes simply resets the memory usage.
- I wish you good luck with your investigation!

**Comment by leeoniya** [comment]
here are some steps you can use to try and narrow down what is happening in your specific case. press F12 to open chrome's dev tools and see if the chart canvas is being destroyed/recreated on every data update. you can see in the screen rec below that with random data updates the canvas stays in place and there is no leak, but when toggling a series, we have re-init of the chart on each click.

if your data shape is stable across updates (same number of series, names, etc), there should not be any re-inits. if this is occurring it's likely falling into some reconfig condition here:

https://github.com/grafana/grafana/blob/4a5afe4fb6344e46cf597da06d9f4d97e85de752/packages/grafana-ui/src/components/GraphNG/GraphNG.tsx#L218-L244

and

https://github.com/grafana/grafana/blob/4a5afe4fb6344e46cf597da06d9f4d97e85de752/packages/grafana-ui/src/components/uPlot/Plot.tsx#L102

if only only one of your panels is doing this, it may make sense to isolate it to its own dashboard and start removing transforms to see if the issue goes away. otherwise we'll need to step through this code to see what's causing the excessive re-inits (assuming your data shape/schema is consistent across data updates).


https://user-images.githubusercontent.com/43234/184732445-3d02a47c-889c-4b07-895a-9113671da01f.mp4
