### ISSUE TITLE
Public Dashboard Step size does not match logged in version

### ISSUE THREAD

**Issue by chickenbellyfin** [grafana/grafana#53499]
**What happened**:
I have minutely metrics which I have on a dashboard. When I go to the public dashboard link, it shows me the metric at a resolution of 5m instead of 1m.

The two prometheus queries on this dashboard don't have any duration and the min step is `auto`:
```
sum(player_count)

lobby_count
```

Logged in dashboard:
![image](https://user-images.githubusercontent.com/550995/183783855-e7b9b86c-ea50-4957-a471-1d9e850e99a6.png)

Navigating to the public dashboard link
![image](https://user-images.githubusercontent.com/550995/183783867-f12d48bd-2bc5-40b2-a9f7-6acc20d7f48a.png)

**What you expected to happen**:
The metrics on the public dashboard should appear identical to the logged in version.

**How to reproduce it (as minimally and precisely as possible)**:
The minimal reproduction is as follows, I believe:
1. Create a new dashboard and add  panel with a prometheus query of `0`
2. Hover over the graph and see that the step size changes in increments of 30s
3. Enable public dashboard and go to the link. When hovering over the chart, the timestamp increments in steps of 5 minutes.

**Anything else we need to know?**:

**Environment**:
- Grafana version: docker image grafana/grafana:9.1.0-beta1 digest: 17bf8bd0e7f0
- Data source type & version: prometheus 2.37.0 on arm64, revision b41e0750abf5cc18d8233161560731de05199330
- OS Grafana is installed on: docker
host:
$ uname -a
`Linux arm1 5.15.0-1013-oracle #17~20.04.1-Ubuntu SMP Mon Jul 4 05:29:46 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`
- User OS & Browser: Windows 10, brave browser
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
This is likely due to the queries missing maxDataPoints and intervalMs (two properties that are added in the frontend) 

https://github.com/grafana/grafana/blob/main/pkg/services/publicdashboards/service/service.go#L185

The type here is strange, Queries is untyped 
https://github.com/grafana/grafana/blob/45750da66758744061f3687184f47af5a606a076/pkg/api/dtos/models.go#L69

it should be of type DataQuery from *backend.QueryDataRequest
https://github.com/grafana/grafana-plugin-sdk-go/blob/main/backend/data.go#L46

maxDataPoints and intervalMs are dynamically calculated based on time range and already sent to the backend API: https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/services/PublicDashboardDataSource.ts#L67

I just expect that the query model sent by the frontend is ignored (which it should be, for the other properties) but maxDataPoints and interval needs to be taken from the frontend (or otherwise the other alternative is to redo their calculation which is a bit complex).

**Comment by timlevett** [comment]
Thank you for submitting this @chickenbellyfin, the team will take a look.
