### ISSUE TITLE
Geomap tooltip is not shown.

### ISSUE THREAD

**Issue by j-dc** [grafana/grafana#53504]
Geomap tooltip is no longer shown.

After an upgrade from grafana 8.x to 9.x the tooltip is no longer show when hovering/clicking a marker.

When in Edit modus, the tooltip is shown, and works as expected, BUT it is shown in the wrong place!

![image](https://user-images.githubusercontent.com/8330653/183856390-cc1b087c-bece-4795-9a28-15f2891c9d75.png)

**How to reproduce it (as minimally and precisely as possible)**:
Add a geomap. 
Add a marker layer.
Hover a marker.
Click a marker.

**Environment**:
- Grafana version: v9.0.6 (556faf829)
- Data source type & version: Microsoft SQL Server - 5.0.0
- OS Grafana is installed on:  Windows Server 2019 - Microsoft Windows Server Version 1809 (OS Build 17763.3046)
- User OS & Browser:  Windows - Chrome
- Grafana plugins:
- Others:

**Comment by usmangt** [comment]
Hi @j-dc ,

Thanks for opening this case.

Does it also happen on a fresh installation of the grafana server or only where it gets upgraded from a previous version?

Also, can you produce this on https://play.grafana.org/ ?

**Comment by j-dc** [comment]
I could not produce it in play.grafana.org. 
Updated my local test version to same version.
Issue seems to be fixed in 9.0.7

**Comment by Shadrack88** [comment]
I am currently using Grafana 9.1.2 version, and its challenging  to display meausred values at a location.  On the edit panel, i have the display tooltip available, but i cant activate it. 

When a mouse pointer is placed on a location on a map, it popups  a timestamp of all the locational values instead of a the actual metric value that has been measured at the location. for example instead of displaying the temperature value measured at point A, it displays "point A".

Is it possible to continuously display the location name as show on the map, and display the measured metric value when a mouse pointer is placed at location
<img width="1004" alt="grafana location" src="https://user-images.githubusercontent.com/98733568/192106629-7c9515e0-1421-4d44-9d6e-a47642c4befe.png">

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/98733568/192106672-cff80cb2-f610-414d-b292-b37adb222477.png">
