### ISSUE TITLE
Pie charts don't show correct legend with Elasticsearch as datasource

### ISSUE THREAD

**Issue by apollo13** [grafana/grafana#53534]
**What happened**:

I added a pie chart with elasticsearch as datasource and the legend always shows "Count" as label for each bucket.

![image](https://user-images.githubusercontent.com/81547/183921375-b52bf08b-c0f5-423b-b59f-5b9b3b0a2a0a.png)

If I change the grouping to use a string valued field, Grafana will display it properly. Data as shown by the query inspector:

![image](https://user-images.githubusercontent.com/81547/183921867-7f645db9-37a3-4c8b-baf7-d22c0a983578.png)

**What you expected to happen**:

Show the proper values (in my case ports)

**How to reproduce it (as minimally and precisely as possible)**:

Use play.grafana.com to setup a panel like this:
![image](https://user-images.githubusercontent.com/81547/183922849-0556c786-0c55-4261-b347-55dc6d850133.png)

**Environment**:
- Grafana version:  v9.0.7 (eed942a502)
- Data source type & version: Elasticsearch
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Fedora 36 & Firefox
- Grafana plugins: default docker install

**Comment by torkelo** [comment]
Sadly this data form is not supported by the pie chart. The problem is using a numeric field as the source of the names for each value. To use field row value as the source of a name of slice in pie chart (or stat panels), it needs to be a string field. 

You can fix this by using a Transform named "Convert field type":
Example (Here you would select DestPort)  :
![Screenshot from 2022-08-10 16-19-35](https://user-images.githubusercontent.com/10999/183925316-83dd7a34-e41b-4af7-b86a-1d56924d3cf3.png)

**Comment by torkelo** [comment]
logic is here: https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/field/fieldDisplay.ts#L245

**Comment by apollo13** [comment]
@torkelo Oh sorry that I overlooked this. Thank you for the explanation and the help.
