### ISSUE TITLE
Docs: Bug for SAML PEM Files

### ISSUE THREAD

**Issue by GrafanaWriter** [grafana/grafana#53639]
The steps for SAML tell you to base64 encode some PEM files, but that step breaks the workflow. 

PEM files are already base64 encoded. In fact, it specifically does NOT work if you encode them, and it does work if you do not
**What happened**:
does NOT work if you encode the PEM files as instructed
**What you expected to happen**:
Update https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/saml/#example-of-how-to-generate-saml-credentials to remove the base64 encoding of the PEM files
**How to reproduce it (as minimally and precisely as possible)**:
bug found by customer
**Anything else we need to know?**:
n/a

**Comment by chri2547** [comment]
@IevaVasiljeva , I'm wondering if you can help me determine if this issue is valid as it is quite old. I can perform the work, just wanted to check with you first. It appears that the change would be to remove the following content? Thank you!


![Image](https://github.com/grafana/grafana/assets/35463610/36365c96-a3f8-4c5d-9870-97529502d5b9)
