### ISSUE TITLE
[Feature Req]: Table panel Export should handle column formats

### ISSUE THREAD

**Issue by rafaturtle** [grafana/grafana#5372]
- **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
  3.0.4-1464167696
- What datasource are you using?
  InfluxDB
- What OS are you running grafana on?
  Ubuntu
- What did you do?
  Used export to CSV function from a table. It works well from a Chart.
- What was the expected result?
  The date column be in ISO format.
- What happenend instead?
  Date column in nanoseconds. Here is an example:
  Time;Int32polled.distinct;
  1466074220000;852888298;
  1466074200000;507504844;
  1466074180000;1787957227;
  1466074160000;1719267467;
  1466074140000;1251943914;

**IMPORTANT** If it realates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by ictcorebiz** [comment]
I'm facing the same issue with datasource ElasticSearch; I would expect the data to follow the defined "Column style" in the table-options.

**Comment by torkelo** [comment]
The json and csv export are currently only exporting raw data, so for table panel there is not formating

**Comment by kipe** [comment]
Just added a version of my solution. Not sure if this is the way this was meant, so creating PR after more discussion.

**Comment by conet** [comment]
Hi, I just found this issue while looking for a way to export raw data, having this change merged without providing a way to also export raw data is unfortunate because, for example, if a table with the `short` format is exported the data is useless, because there are values like 1.3Mil, 5.4K, 125, which is visually nice but useless for further processing.
The way kibana solves this is by allowing the user to choose the exported data format:
<img width="216" alt="kibana_csv_export" src="https://user-images.githubusercontent.com/11311763/53896053-f76ee980-403b-11e9-8126-fd9255e84cbe.png">

**Comment by conet** [comment]
I ended up patching grafana, creating a PR with both options is just too much dev work for me 😄

**Comment by pkolyvas** [comment]
Looks like the parent issue should have been closed against #5492.
