### ISSUE TITLE
logs: download-logs/download-csv buttons have different behavior

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#53742]
if you have logs-data in explore, where the data is contained in multiple dataframes (for example, Loki in grafana8.x),
and go to download the csv or the logs, you get this screen:
<img width="666" alt="export" src="https://user-images.githubusercontent.com/51989/184660536-0583ea87-a5c1-4252-9e17-11f6e0d0f252.png">

(the `{place="luna", source="data"}` part is the dataframe-name, and can be changed by opening the `Data options` section)

in this case, the data is in two dataframes.

- if you click [Download CSV], you get only data from the chosen dataframe
- if you click [Download logs], you get all the data, from all the dataframes

this is confusing to the user, because the visualization implies the download-logs also only gets the single dataframe.

i'm not sure what the best way to handle this problem is.

NOTE: starting with grafana9, Loki uses a single-dataframe for logs always, so it's not possible to reproduce the problem there.

( originally reported in https://github.com/grafana/grafana/issues/53479 )

**Comment by matyax** [comment]
We should make it more clear what's the difference between both buttons @grafana/observability-logs

**Comment by gguillotte-grafana** [comment]
@matyax It's unclear whether this behavior (one button retrieving only the inspected data frame, the other retrieving all data frames) is expected.

IMO either:

- both buttons should apply to only the selected data frame
  - but if we limit the "Download logs" functionality across data sources, then how does a user download all logs across all data frames?
- if they can't both apply to the data frame, then the "Download logs" buttons should have conditional text that communicates the scope, such as "Download all logs" vs. "Download frame logs" with Loki in Grafana 9
  - but if we conditionally change the text, then how do we/should we communicate why the context changes the functionality?
- if they can't have conditional text, then the "Download logs" button shouldn't be visually associated with one selected data frame in the Inspector
  - but if we move it to a broader visual context, then how does a user download logs for only the selected data frame, and how do we handle Loki?

Otherwise, the hackiest idea I've got for differentiating the buttons' behaviors is via tooltips that provide this context, like:

> Download query results for this data frame as comma-separated values

vs.

> Download log results for all available data frames as plain text

But that's a kludge - it doesn't make the behavior less confusing, it just explains the confusion closer to the user than the docs.

In any case we still also need to document the different behaviors and contexts for 8.5 to 9.2, and then any changes to those behaviors in 9.3 (#55163), because the [current docs](https://grafana.com/docs/grafana/latest/explore/explore-inspector/) don't describe the expected results at all:

> ### Download raw query results as CSV
> 
> Grafana generates a CSV file in your default browser download location. You can open it in the viewer of your choice.
> 
> - In the Inspector tab, raw query results following instructions in Inspect raw query results.
> - Refine query settings until you can see the raw data that you want to export.
> - Click Download CSV.
> 
> In order to download a CSV file specifically formatted for Excel, expand Data options and then enable the Download for Excel toggle before you click the Download CSV option.
> 
> ### Download log results as TXT
> 
> Grafana generates a TXT file in your default browser download location. You can open it in the viewer of your choice.
> 
> - Open the inspector.
> - Inspect the log query results as described above.
> - Click Download logs.
