### ISSUE TITLE
Problem with automatic update  datasources after upgrade from Grafana 8.4.4 to Grafana 9.1.0

### ISSUE THREAD

**Issue by pablozone** [grafana/grafana#53893]
Hi, When I upgrade Grafana from Grafana 8.4.4 to Grafana 9.1.0 there is problem with automatic update datasource. 
The Message bellow appears with prometheus, elasticserach, zabbix datasource

![obraz](https://user-images.githubusercontent.com/29774180/185394729-a9e80550-906d-41ea-ab91-09acecbff980.png)

When I add new datasource with exacly the same configuration, everything is OK. 
![obraz](https://user-images.githubusercontent.com/29774180/185394796-60aa2255-4ca8-47b2-950a-8b1125ceb582.png)

Could you please have a look.

**Comment by mellieA** [comment]
@pablozone are you able to share if there are any errors shown in developer tools when the "failed to update datasource" error appears? 

Prometheus and Elasticsearch are built-in datasources, for Zabbix you'll want to update the plugin manually.

**Comment by mc-em** [comment]
I also experienced the same in our prometheus datasource when I upgraded from v8.5 to v9. Our prometheus datasource is using custom http header Authorization. When i upgraded to v9, the value of Authorization went null and when I try to supply the value it failed to updated and logging error about data key not found. I had no issue like this when I upgraded from 8.4.3 to 8.5.0 and from 8.5.0 to 8.5.10. 

<img width="505" alt="snap1" src="https://user-images.githubusercontent.com/110811012/186836345-90dc35fd-9fda-4f1d-9e6f-889aab888912.png">
<img width="744" alt="snap2" src="https://user-images.githubusercontent.com/110811012/186836390-99edcba9-5751-4233-a402-35e04eb5c051.png">

`logger=secrets t=2022-08-26T10:14:31.4332779+04:00 level=error msg="Failed to lookup data key by id" id=FnVjcbgVz error="data key not found"
logger=secrets t=2022-08-26T10:14:31.4332779+04:00 level=error msg="Failed to decrypt secret" error="data key not found"
logger=context traceID=00000000000000000000000000000000 userId=25 orgId=1 uname=admin t=2022-08-26T10:14:31.4332779+04:00 level=error msg="Failed to update datasource" error="data key not found" remote_addr=172.21.135.312 traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=25 orgId=1 uname=admin t=2022-08-26T10:14:31.4332779+04:00 level=error msg="Request Completed" method=PUT path=/api/datasources/22 status=500 remote_addr=172.21.135.312 time_ms=28 duration=28.0584ms size=86 referer=http://172.21.135.311:8080/datasources/edit/2W1R5-Cnz traceID=00000000000000000000000000000000
`

If I create new Prometheus datasource with same values, it is created just fine and any update gets successful. However, we cannot do this in our current setup due to 75 dashboards are linked to the current prometheus datasource.

I would greatly appreciate it if you can suggest workaround for this case. Like maybe updating some value in grafana table/record in database or try some modification in configuration file.

**Comment by mc-em** [comment]
got it update and running in v9.0.1 after adding below in custom.ini

[feature_toggles]
enable = disableEnvelopeEncryption

Tried upgrading to v9.1.0 but facing different error.

**Comment by joanlopez** [comment]
> Hi, When I upgrade Grafana from Grafana 8.4.4 to Grafana 9.1.0 there is problem with automatic update datasource. The Message bellow appears with prometheus, elasticserach, zabbix datasource
> 
> ![obraz](https://user-images.githubusercontent.com/29774180/185394729-a9e80550-906d-41ea-ab91-09acecbff980.png)
> 
> When I add new datasource with exacly the same configuration, everything is OK. ![obraz](https://user-images.githubusercontent.com/29774180/185394796-60aa2255-4ca8-47b2-950a-8b1125ceb582.png)
> 
> Could you please have a look.

Hi @pablozone,

Here few questions about your case: 

- Do you recall with which version of Grafana did you set up those data sources? How are they created (manually, provisioning, etc)?
- Are you able to fix those data sources by configuring again the secrets (credentials)?
- If no, are you able to update the credentials (even if you introduce the same value is enough) of the data sources you created successfully?
- Could you share your server logs? At least if you see any error that could be related with this.

Thanks!

**Comment by joanlopez** [comment]
> I also experienced the same in our prometheus datasource when I upgraded from v8.5 to v9. Our prometheus datasource is using custom http header Authorization. When i upgraded to v9, the value of Authorization went null and when I try to supply the value it failed to updated and logging error about data key not found. I had no issue like this when I upgraded from 8.4.3 to 8.5.0 and from 8.5.0 to 8.5.10.
> 
> <img alt="snap1" width="505" src="https://user-images.githubusercontent.com/110811012/186836345-90dc35fd-9fda-4f1d-9e6f-889aab888912.png">
> 
> <img alt="snap2" width="744" src="https://user-images.githubusercontent.com/110811012/186836390-99edcba9-5751-4233-a402-35e04eb5c051.png">
> 
> `logger=secrets t=2022-08-26T10:14:31.4332779+04:00 level=error msg="Failed to lookup data key by id" id=FnVjcbgVz error="data key not found" logger=secrets t=2022-08-26T10:14:31.4332779+04:00 level=error msg="Failed to decrypt secret" error="data key not found" logger=context traceID=00000000000000000000000000000000 userId=25 orgId=1 uname=admin t=2022-08-26T10:14:31.4332779+04:00 level=error msg="Failed to update datasource" error="data key not found" remote_addr=172.21.135.312 traceID=00000000000000000000000000000000 logger=context traceID=00000000000000000000000000000000 userId=25 orgId=1 uname=admin t=2022-08-26T10:14:31.4332779+04:00 level=error msg="Request Completed" method=PUT path=/api/datasources/22 status=500 remote_addr=172.21.135.312 time_ms=28 duration=28.0584ms size=86 referer=http://172.21.135.311:8080/datasources/edit/2W1R5-Cnz traceID=00000000000000000000000000000000 `
> 
> If I create new Prometheus datasource with same values, it is created just fine and any update gets successful. However, we cannot do this in our current setup due to 75 dashboards are linked to the current prometheus datasource.
> 
> I would greatly appreciate it if you can suggest workaround for this case. Like maybe updating some value in grafana table/record in database or try some modification in configuration file.

Hi @mc-em,

Error logs are pretty clear here: seems there's (at least one) missing data key - and with no data key, Grafana cannot decrypted the encrypted data.

So, my question is, have you manually modified the database? (import-export, or whatever) We even don't have support to delete data keys, so it's extremely weird that a data key has magically disappeared.

In any case, even without that data key, you should be able to update the data source. I'll try to reproduce that error and see why you can't.

Finally, as it's stated in release notes, envelope encryption (they new way Grafana secrets stored into the database are encrypted) is enabled by default. So, if you disable it, you'll start experiencing even more errors, because your Grafana instance definitely won't be able to decrypt those secrets encrypted with envelope encryption (those created or updated after upgrading to Grafana v9+.

Thanks!

**Comment by pablozone** [comment]
Hi, sorry for delay, (I was on holiday) I finally upgrade succesfully my grafana from version 8.5.11 to 9.1.2. 
I have configuration in mariadb databases. 
When I upgrade grafana binaries problem still exist, and datasources not working. I havent find any errors on grafana log


What I did next, I delete my grafana database. I create fresh new one,  and loaded shema from backup. 
And then I upgrade grafana binaries again. With success, and all datasource working ok.

case can be close.
