### ISSUE TITLE
Character / allowed in dashboard folder names, but not in alert folder names

### ISSUE THREAD

**Issue by erkexzcx** [grafana/grafana#54021]
Grafana v9.0.4 OSS.

I am able to create dashboard folder `KeyDB/Redis` without any issues.

But I can't create/update alerts in this folder:
![image](https://user-images.githubusercontent.com/5955795/185909693-9ff50116-17b3-45b3-8995-c3bc8d5ae3f0.png)

I believe this isn't supposed to happen. :)

**Comment by gelicia** [comment]
I'm not sure if this is a bug or a feature request to the alerting team or not - I'll let them investigate and either move the topic to Discussions or not :) Thanks!

**Comment by erkexzcx** [comment]
It's a bug. This is how it becomes nasty:

1. Create a folder named "KeyDB"
2. Create any alert (unified alerting) and save to this folder.
3. Rename this folder to "KeyDB / Redis"
4. "Edit" previously created alert, but do not change anything and click "save"
5. `Cannot contain "/" or "\" characters`.

**Comment by michalcharvat** [comment]
Same problem exists in 11.0

**Comment by mtthwcmpbll** [comment]
I ran into this same issue with alerting rules created through Grafana Alloy's [mimir.rules.kubernetes](https://grafana.com/docs/agent/latest/flow/reference/components/mimir.rules.kubernetes/) to sync `PrometheusRules` with Mimir's Alertmanager instance.  You can set a namespace prefix in mimir.rules.kubernetes, but this ultimately creates rules with the namespace "<prefix>/<namespace>/<name>/<id>".  There doesn't seem to be any way to change this for Grafana Alloy.

It's not the end of the world here since we'd like to edit the original PrometheusRule and not the rule inside Grafana, but this is definitely confusing for developers that aren't tracking the whole chain of events (and seems weird that Alloy can create an invalid rule namespace to begin with).
