### ISSUE TITLE
can't add cluster datasource - getInstance error: cannot decode redis array into string

### ISSUE THREAD

**Issue by Nurlan199206** [grafana/grafana#54054]
grafana: 9.0.5
redis-datasource: 2.0.0

can't add 3 nodes redis cluster in datasource - error: getInstance error: cannot decode redis array into string

Address bar: 192.168.0.131:6379,192.168.0.132:6379,192.168.0.133:6379

![image](https://user-images.githubusercontent.com/22808731/185977281-ec2bdf3f-a1f5-4f69-b1c7-a8f42827d8ec.png)

**Comment by gelicia** [comment]
Grafana doesn't maintain the redis datasource, so I will close this issue. Please add it to https://github.com/RedisGrafana/grafana-redis-datasource 

That said, you may want to try separating values by `|` instead of commas. See the comment here https://github.com/RedisGrafana/grafana-redis-datasource/issues/63#issuecomment-700319683
