### ISSUE TITLE
Unable to add panels and graphs in grafana.

### ISSUE THREAD

**Issue by vilasmankala** [grafana/grafana#5415]
Hi,

I followed the below link to setup the monitoring for docker
https://www.brianchristner.io/how-to-setup-docker-monitoring/

I installed grafana but in that grafana dashboard I am unable to find "Add panel" option. Attached the screenshot of grafana.
As per above link we should see a "Home Menu drop Down" after clicking on "Dashboard", but I am unable to see that home menu dropdown neither I can find any add panel option.
Please suggest.

**Comment by bergquist** [comment]
Click the logo on the top left.

Please do not open a github issue for questions [Support Options](http://grafana.org/support/)

**Comment by jmccarty3** [comment]
I actually had this issue and the response from @bergquist was not correct. The issue was related to cached content on my machine. Forcing chrome to reload without a cache cleared up the problem.

The AddPanel box was rendered but was off screen from being set at left: -33px. I'm guessing this was related to updates.

**Comment by kevin71246** [comment]
FYI Still having this issue, ver 6.6.0, using an Android cell phone (not sure if that's supported). The button does not show up. A fix is to switch chrome to "desktop site", but then the zoom, etc, doesn't work correctly there.
