### ISSUE TITLE
inspector / json tab crashes if the data is too large

### ISSUE THREAD

**Issue by 09jvilla** [grafana/grafana#54188]
when you use the [inspector] / [json] option, and the data is too large, the whole webpage crashes, because an exception is thrown at https://github.com/grafana/grafana/blob/main/public/app/features/inspector/InspectJSONTab.tsx#L212

the exception is "RangeError: Invalid string length"

from searching on the internet, this error-message happens when the object-to-convert-to-json is simply too large.

how to reproduce it with Loki (but this is not loki specific):
1. make devenv sources=loki ... this will load around 300log-lines into loki automatically
2. node devenv/docker/blocks/loki/data/data.js http://localhost:3100 ... this load 300 more
3. repeat [2] until you have 3000 log-lines in Loki (you can adjust the script to sleep less for this to go faster)
4. run the loki query in grafana explore: {source="data"} , set line-limit to 3000
5. when the data is received open the [inspector], and go to [json]
6. the browser will hang for a while, and then there will be the above-mentioned error

**Comment by gabor** [comment]
i was able to reproduce it with public info too:

1. `make devenv sources=loki` ... this will load around 300log-lines into loki automatically
2. `node devenv/docker/blocks/loki/data/data.js http://localhost:3100` ... this load 300 more
3. repeat [2] until you have 3000 log-lines in Loki (you can adjust the script to sleep less for this to go faster)
4. run the loki query in grafana explore: `{source="data"}` , set line-limit to 3000
5. when the data is received open the [inspector], and go to [json]
6. the browser will hang for a while, and then there will be the above-mentioned error

the exception "RangeError: Invalid string length" is thrown at https://github.com/grafana/grafana/blob/main/public/app/features/inspector/InspectJSONTab.tsx#L212

from searching on the internet, this error-message happens when the object-to-convert-to-json is simply too large.

**Comment by gabor** [comment]
maybe a potential solution: we could check the size of the data-to-be-jsonified, and if it's too large we just show a message like "sorry, too large". so that at least the whole page does not crash.

**Comment by TsotosA** [comment]
Hi @gabor, opened a PR to address this. 
I implemented a slightly different approach that the data size since i wasnt sure its not hardware bound also, but i am open to suggestions for alternatives.

**Comment by gabor** [comment]
thanks @TsotosA for the PR! it's not my area of code, i'm sure @grafana/dashboards-squad will take a look at it 👍
