### ISSUE TITLE
Unable to upgrade to v9.1 due mysql statement error

### ISSUE THREAD

**Issue by mc-em** [grafana/grafana#54291]
**What happened**:  I tried to perform Grafana upgrade from v9.0 to v9.1 but the upgrade is failing due to failure to rename table dashboard_public_config in grafana database (mysql). Below error is found in grafana log when starting Grafana service which is causing the service be paused.

logger=migrator t=2022-08-26T14:02:33.63422+04:00 level=error msg="Executing migration failed" id="Rename table dashboard_public_config to dashboard_public - v2" error="Error 1050: Table 'dashboard_public' already exists"
logger=migrator t=2022-08-26T14:02:33.63422+04:00 level=error msg="Exec failed" error="Error 1050: Table 'dashboard_public' already exists" sql="ALTER TABLE `dashboard_public_config` RENAME TO `dashboard_public`"

I tried to check the mysql statement run by Grafana and it seems will not rename the table to **dashboard_public - v2** but will rename it to only **dashboard_public** 
`Rename table dashboard_public_config to dashboard_public - v2`

![image](https://user-images.githubusercontent.com/110811012/186887254-1d7b1c0e-041c-41a7-aeba-5a9fcd86337f.png)

**Anything else we need to know?**:
**Environment**:
- Grafana version: 9.0.7
- Data source type & version: mysql 8.0.22
- OS Grafana is installed on: Windows Server 2016 Standard

**Comment by owensmallwood** [comment]
Hi @mc-em, 

That migration is not trying to rename it the table to `dashboard_public -v2`. All of our migrations have an `id` associated with them that we generate. In this case, the migration id was `Rename table dashboard_public_config to dashboard_public - v2`. The migration that is failing is attempting to rename the table to `dashboard_public`, which is intended.

Regarding why it's failing, it's tough to tell from just info provided. From what I can see, the migration has already been ran since mysql is saying the `dashboard_public` table already exists.

Could you provide all the migration logs that were ran? Or possibly a dump of the `migration_log` table?

**Comment by mc-em** [comment]
> 

Hi @owensmallwood ,

Sorry, I was not able to get the dump of migration_log table. I got our Grafana upgraded successfully after manually renaming table dashboard_public then starting the Grafana service of v9.1.1. Will share it next time if I encounter again during next upgrade.

Regards,
