### ISSUE TITLE
Need to be able to aggregate over GROUP BY time within each series before aggregating across series

### ISSUE THREAD

**Issue by MatMeredith** [grafana/grafana#5429]
I've hit an issue that I think is going to prevent us from deploying InfluxDB.   The following is an example of this issue, but in reality it manifests in different ways in many of our use cases.

I have a set of nodes each reporting the rate at which differnet SIP messages are being received (in terms of messages per s)

~~~~
timestamp | tag_node | tag_message_type   |  value
---------------------------------------------------
          | node1    | INVITE             | 1728
          | node1    | BYE                | 1051
          | node2    | INVITE             | 1521
          | node2    | BYE                | 1241
~~~~

Each node reports writes these stats to InfluxDB roughly every 5s.

I want to draw charts showing the total rate of different types of SIP messages being processed across my deployment, split by message_type.

Ideally I would do this like so:

SELECT sum("value") FROM "sipMessages" WHERE  WHERE time > now() - 7d GROUP BY time(1h), "tag_message_type"

The problem here is that this sums across different values of node, but also sums multiple points within each series.  So the number I get returned is ~720 times higher than it should be.   If I knew that there were always going to be exactly 720 measurements in each time interval I could divide by 720, but this 720 is only an approximation.   [it is also the case that using Grafana to draw the graphs this "1h" period changes automatically based on the period that I'm graphing over]

What I really need to do is to run an average aggregation within each series over each GROUP BY time period (so that for each node / message_type combination I have one data point per time period), and then sum the results of those aggregations across the different series.

I don't believe this is possibe though, and I can't see any way to work around it?

What I don't understand is why this isn't a critical issue for lots of users as this seems like a very standard use case.   Is there a reason that other users are able to avoid this issue?

Would adding this capability (to do per series aggregation within "GROUP BY time" intervals) be technically difficult?

**Comment by torkelo** [comment]
This is an InfluxDB query issue, InfluxDB query language is very limiting in what you can do. I also do not understand how people can be happy with the limited query features in InfluxDB. 

So you want to group by tag `node`using sum aggregation, and then apply a group by time (1h) using and average aggregation. This would be dead simple to do in Graphite but sadly InfluxDB does not support nesting queries or multiple aggregation functions for different group by's. 

In graphite it would be:
`sip.messages.<node wildcard>.<message_type wildcard>.count -> groupByNode(2,'sum') -> summarize(1h, avg)`   

The `<xxx wildcard>` is just there to show that part of the metric path represents, the real query is:

`sip.messages.*.*.count -> groupByNode(2,'sum') -> summarize(1h, avg)`   

Maybe someday InfluxDB will support doing this but the query will look like a horribly nested complicated mess due to the SQL like structure. So if you want to do more rich analytics on your metrics I suggest you use Graphite :)

**Comment by o** [comment]
> I also do not understand how people can be happy with the limited query features in InfluxDB.
+1

**Comment by MatMeredith** [comment]
@torkelo Oops -- my apologies.   I had intended to raise this against InfluxDB not Grafana.   The question I wanted to raise against Grafana [was this one](https://groups.io/g/grafana/thread/how_to_divide_values_by/2078477?p=,,,20,0,0,0::RecentPostDate%2FSticky,,,20,2,0,2078477 ) to see about a possible workaround...

However my mistake was lucky for me, as you have very helpfully answered another question I had -- "whether another TSDB" would do better here.

Presumably in your example graphite query this is dependent upon the measurements for different nodes having identical timestamps (which admittedly they do in my example).   If this weren't the case would it be possible to do the query the other way: average over time period (to generate a single sample point per time period), and then sum these averages across nodes?

Many thanks for your help.

**Comment by torkelo** [comment]
Yes, you can do the summarize by 1h and then do the Group by node, would also work
