### ISSUE TITLE
Invert legend order

### ISSUE THREAD

**Issue by jeamland** [grafana/grafana#5436]
I'm trying to create a stacked bar chart of bug counts. The stacked elements in the bar are counts of bugs in a given state. I want the statuses stacked in a given order, NEW on top, then ASSIGNED through to CLOSED at the bottom.

I've attempted this in two ways, both of which have issues regarding the ordering of the data points.

The first attempt involved using a GROUP BY query. The problem with this is that InfluxDB has no way to specify the order of the groups and so they end up sorted lexically with ASSIGNED, then CLOSED, etc. 

The second was to use multiple queries, each specifying the status within the WHERE clause of the query.

This works except that the ordering in the legend is inverted compared to the order in the stacking in the chart. The first item in the legend is the bottom-most group in the stack and so on up. This can be seen in this screenshot:

<img width="1298" alt="screen shot 2016-06-25 at 14 25 18" src="https://cloud.githubusercontent.com/assets/492857/16359243/b725c284-3ae1-11e6-9da3-66b22e1f3e6c.png">

Is it possible to add an option to invert the legend order relative to the stacking order? I'd also accept an option to specify my own stacking and/or legend order.

Thanks!

**Comment by tdb-alcorn** [comment]
+1: I would like to specify my own stack order.

I am running a test where I want to show the percentage of requests that resulted in an error. I expect this number to always be low (~1%) so I want to use a log_10 scale to highlight the variance around in count of errors around 1% while still showing the full range of up to 100%. However because I can't set the stack order, the count of non-errors occupies the lower part of the y-axis and the small variations in count of errors is hard to see. Screenshot:

<img width="687" alt="screen shot 2016-10-26 at 15 58 08" src="https://cloud.githubusercontent.com/assets/1851861/19748275/7efb1246-9b95-11e6-888d-d3f5c9fff190.png">

If I could require that the count of errors be below the count of non-errors in the stack order then my problem would be solved!

**Comment by hernaneche** [comment]
Legend ordering seems to be random, options order change at every refresh?

**Comment by torkelo** [comment]
@hernaneche what data source do you use? to you sort series in query?

**Comment by hernaneche** [comment]
I am using mysql, and I've just read this [Add sort order to metrics, controlled by MySQL query #9091](https://github.com/grafana/grafana/pull/9091) perhaps that's my problem.

**Comment by ernstp** [comment]
Duplicate of #9538 ?
