### ISSUE TITLE
Azure Monitor: Integration test for HTTP header handling

### ISSUE THREAD

**Issue by yaelleC** [grafana/grafana#54379]
add an integration tests like it is done for prometheus in https://github.com/grafana/grafana/blob/main/pkg/tests/api/prometheus/prometheus_test.go

to make sure headers are correctly sent.

for more details see https://github.com/grafana/grafana/issues/54314

**Comment by kostrse** [comment]
Custom headers are useful for generic or standalone datasources Prometheus since they give extra flexibility for user to configure authentication etc.

But Azure SaaS services are fixed in what they can do and what they don’t.

I think that original implementation which was initializing empty httpclient without inheriting any  httpclient options was the correct one.
