### ISSUE TITLE
Enter key should update graph when typed in free-form query

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#5464]
- **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
  grafana-3.1.0-1466666977beta1
- What datasource are you using?
  InfluxDB
- What OS are you running grafana on?
  CentOS/7
- What did you do?
  Made changes to a query while in a free-form query box and pressed <kbd>ENTER</KBD>.
- What was the expected result?
  Graph to update with the changes I made to the query.
- What happened instead?
  Nothing
- Additional information
  Currently the graph only updates if you click outside the query box. This is rather inconvenient when you want to make a small change, see the result, make a small change, see the result, rinse, repeat.

The "free-form query box" I refer to is this:
![image](https://cloud.githubusercontent.com/assets/1826947/16461764/30140706-3dfc-11e6-8960-609c03329c26.png)

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
