### ISSUE TITLE
Explore tests: Query History errors

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#54778]
Test scenarios:

```
WHEN user adds a query, 
AND local rich history storage returns "quota exceeded" error
THEN the error is shown
AND the query **is not added**
```

```
WHEN user adds a query, 
AND local rich history storage returns "limit exceeded" error
THEN the error is shown
AND the query **is added**
```

**Comment by harisrozajac** [comment]
After giving this one a try, I'm not sure how to make it work. I've tried several different approaches but none of them worked

The most promising approach was:

1. Spy on RichHistoryLocalStorage's `addToRichHistory` function because this is the function that will run and then check if the quota is exceeded (throws `RichHistoryServiceError.StorageFull` error and doesn't save the query in history)  or if the limit is exceeded (returns RichHistoryStorageWarning.LimitExceeded and richHistoryQuery and saves the query by replacing it with the oldest unstarred one)
2. As I spy the function, I run `mockImplementationOnce` of `addToRichHistory` to mock the return values listed above.

However, I'm not sure how to check if the modal showed the expected warning/error. Maybe we can just mock the action dispatch because the modal is not a part of ExplorePage which is rendered with `setupExplore()`. I know jest can mock a component and check if it was displayed, but I couldn't make that work because it was just not showing up.
