### ISSUE TITLE
Navigation: Add News drawer

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#54838]
- [ ] There is a `News` icon in the `Navbar`
- [ ] Clicking the `News` icon opens a drawer containing the blog rss feed as seen on the default homepage

**Comment by lpskdl** [comment]
Hi @amy-super @ashharrison90 ,

I would like to ask about the feed we are going to use here. Should it be blog feed(xml) or the news feed(rss)? Should we rename this issue to blog drawer if we are using blog feed? 

I just noticed it that we are using "News Drawer" but the feed is blog. is it intentional? 

thanks.

**Comment by amy-super** [comment]
Today the title of the panel is `Latest from the blog` which I think could be fine here for now until we figure our our home page stuff (see #52275 for details on the problem to be solved there).
