### ISSUE TITLE
Grafana Alert not re-arming using the "Alert state if no data or all values are null"

### ISSUE THREAD

**Issue by SovnSkyrim** [grafana/grafana#54966]
**What happened**:
I have an alert on that checks if a single log passes through the query.
`count_over_time({critical="very-critical"} [1m])` with condition `Classic Condition: When Last() of A is above 0` evaluation every 10s for 20s.
The alert fires but does not go returns to "normal" state until after ~8h
[here's a proof](http://prntscr.com/rROXS6VqA8ax)

**What you expected to happen**:
Given after a minute; the query returns 0/null (given theres no input) it should rearm and be ready to listen for another log

**How to reproduce it (as minimally and precisely as possible)**:
Described above; I just use a container that sends one log to Grafana through Loki every 15min.

**Anything else we need to know?**:
**Environment**:

- Grafana version: latest dockerfile
- Data source type & version: raw logs being querried
- OS Grafana is installed on: Official Grafana image 
- User OS & Browser: Ubuntu Dockerfile
- Grafana plugins: None that should interact with this.
- Others:
Environment variables:
`     - GF_SERVER_PROTOCOL=https
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_CERT_FILE=/usr/share/grafana/grafana.crt
      - GF_SERVER_CERT_KEY=/usr/share/grafana/grafana.key
      - GF_SECURITY_COOKIE_SAMESITE=none
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=meln5674-
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true`

[Docker-compose.yml file](https://pastebin.com/4RAuYskD)

**Comment by JacobsonMT** [comment]
Hi @SovnSkyrim, thanks for reporting this issue!

Could you provide us with a screenshot of your alert configuration page, this will help us track down the specific problem going on here.

**Comment by SovnSkyrim** [comment]
Hi @JacobsonMT, here's more information about the alert itself
[Imgur Album](https://imgur.com/a/YLmsPVi)
Hopefully this helps.

**Comment by grobinson-grafana** [comment]
Hi! 👋

The alert does not return to Normal after a minute because of a combination of how the `last` function works and the **now-6h to now** range. What happens is when the last value is a `null` or `NaN` the `last` function looks back in the results until it finds the first non `null` or `NaN` value. This means that the alert in the screenshot will fire for at least 6 hours because the range is **now-6h to now**.

To fix this either change the alert from a range query to an instant query and change **Alert state if no data or all values are null** from `NoData` to `OK`, or change the range from **now-6h to now** to something like **now-5m to now**.

**Comment by SovnSkyrim** [comment]
This was indeed the issue. 
I find it personally a bit unclear whether its the query itself or not so documentation could be a little bit clearer; aside from that it works as intended so I will close this.
I thank you for your time and wish you a good day.
