### ISSUE TITLE
Datasources: "Emit event on dashboard load for Azure Monitor data source" does not work for dashboards with rows

### ISSUE THREAD

**Issue by zhichli** [grafana/grafana#55060]
**What happened**:
#52052 and #54286 implemented the feature of "Emit event on dashboard load for Azure Monitor data source". It would work (sending events to echo backend e.g. AppInsights) when the dashboard json has the following snippet like https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/dashboards/networkInsightsDashboard.json#L77 (essentially there is no **row** panel)
```json
      "datasource": {
        "type": "grafana-azure-monitor-datasource",
        "uid": "${ds}"
      },
```

However, when there is row panel in dashboard (e.g. https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/dashboards/cosmosdb.json#L103), the `targets` will not follow the PanelModel.DataQuery[] schema, which contain some custom fields. Hence, the logic https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/state/initDashboard.ts#L121 would not extract queries from the custom targets definition even though there might be [queries inside](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/dashboards/cosmosdb.json#L111)

**What you expected to happen**:
The event emitting feature should be able to track all events from all those dashboards with or without rows.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zhichli** [comment]
this issue is similar to #53722 in terms of root cause. @yaelleC

**Comment by yaelleC** [comment]
Thanks for raising that @zhichli , it looks related to an issue I created last week I noticed that tracking did not work with my `Azure / Insights / Storage Accounts` imported dashboard due to https://github.com/grafana/grafana/blob/9f45e2e7060e3878706e70c1465f1403b6e96082/public/app/plugins/datasource/grafana-azure-monitor-datasource/dashboards/storage.json#L195

However, some other imported dashboard work (as you pointed out). I have tried the cosmosDB dashboard you mention, and if I open a panel and change the `$ds` datasource for `Azure Monitor` then that query will be counted and tracking will happen.

**Comment by zhichli** [comment]
Hey @yaelleC, I also validated the workaround you mentioned. It worked because once you replaced the "`$ds`" with the hardcoded data source, the dashboard json will be changed in the way that the `"datasource`" would be populated with `"type"` field like below, and the json body will be persisted in DB:
```json
 "datasource": {
                "type": "grafana-azure-monitor-datasource",
                "uid": "${ds}"
            },
```

However, I think this is just a workaround and the metric sending logic still needs to be fixed to adapt the variable scenario.

**Comment by yaelleC** [comment]
@zhichli , I completely agree, I did not suggest opening and editing each panel as a workaround, it was still in the investigation phase to pin point that the `datasource.type` prop was the one missing. 

I agree with you that the logic should be updated to catch the `datasource: "${ds}"` case, the fix is part of the other issue that I have in progress, chances are once I close one it will fix both issues 🙂 but I'm keeping yours open in case it requires a different fix.

I'll keep you updated

**Comment by alyssabull** [comment]
Closing as this r[elated issue](https://github.com/grafana/grafana/issues/54605) was also closed.
