### ISSUE TITLE
Request is Forbidden while Importing JSON File

### ISSUE THREAD

**Issue by prabhu66** [grafana/grafana#55076]
Hi Team,

I have deployed Grafana in Kubernetes with Azure AD enabled. My aim is to import the JSON file. while I am trying to import the JSON file its throwing **Request Forbidden**, not sure why I am getting this error. Could any one can help on this issue.

I have installed Grafana locally and there I tried to import the same JSON file it worked. But while trying in Kubernetes Secured URL its throwing Error. Not sure what is missing.

**Note:** I have created docker image from the github repository from **Main** branch and deployed to Kubernetes.

![image](https://user-images.githubusercontent.com/18692829/189889836-4874118f-5492-4a8f-8274-c0f360ecf362.png)

**Comment by mellieA** [comment]
Hi @prabhu66! This looks like a question the community could help with at communities.grafana.com We like to reserve github for bugs and potential bugs, please reopen this issue if you do suspect this is a bug. 

When you create your post in the community forum, I would also include anything you see in developer tools for the browser. A lot of times you'll be able to spot the request that is causing the issue. It sounds like the JSON is sound since this worked locally.

You can also check the console or logs to see if anything is showing there and share those with the community so they can help you to find the cause.
