### ISSUE TITLE
Tempo UI: unexpectd trim traceID leading zero

### ISSUE THREAD

**Issue by hanjm** [grafana/grafana#55166]
**What happened**:
unexpectd trim traceID leading zero, which make tracesToLogs broken.
![image](https://user-images.githubusercontent.com/7621241/190154767-ceed9de8-3fb3-4f77-bd38-c805297a9757.png)

**What you expected to happen**:
not trim traceID leading zero
**How to reproduce it (as minimally and precisely as possible)**:
find a traceID with leading zero.
**Anything else we need to know?**:
I know traceID have two length formats, 128 bit and 64 bit.
**Environment**:
- Grafana version: 9.1.4
- Data source type & version: tempo latest
- OS Grafana is installed on: Linux
- User OS & Browser: Macos & Chrome
- Grafana plugins: No
- Others:

**Comment by zuchka** [comment]
interesting comment here about leading zeros and OTelemetry:

https://github.com/grafana/grafana/issues/45576#issuecomment-1085455512

**Comment by adrapereira** [comment]
Grafana doesn't trim the leading zeroes, the Trace ID is sent to Tempo exactly as is in the input field. However, Tempo does return the ID with the leading zeroes removed because it normalises the Trace ID to 128 bits first and loses track of the original ID from the request, so it may not return the original ID in its response if it has leading zeroes.

@aocenas Not sure what we can do to fix traceToLogs when this happens, thoughts?

**Comment by hanjm** [comment]
@adrapereira hi, this pr is fixed this issue, make sure only trim prefix when leading zero count is 16. could you help review? Thanks.
https://github.com/grafana/grafana/pull/55167/files
