### ISSUE TITLE
Alerting: Alert rules with an invalid folder_uid do not appear in the rules list panel

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#55202]
**What happened**:

Right now, the API allows users to pass any string as the folder_uid. If this string does not point to an actual folder, the created rules never appear in the alerting UI. The rule is still schedulable and evaluates just fine, it just never appears.

I am unsure of whether we should consider this a bug with the API, or a bug with the UI. I can see two possibilities:
- The API should reject rules with invalid folder UIDs.
- The UI should display rules that don't have an associated folder in their own separate group, maybe with a placeholder name like `<empty>`.

Does anyone know of any use-cases for setting a rule's folder UID to a folder that does not exist?

**What you expected to happen**:

I expected the rule to appear in the rules list panel.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a rule through the API.
2. Send some bogus string as the folder UID.
3. Go the rules list panel. Where's the rule?

**Anything else we need to know?**:

**Environment**:
- Grafana version: main
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by konrad147** [comment]
I think the API should reject such requests. The other solution will add much more complexity for hardly visible benefits

**Comment by jtheory** [comment]
@alexweav thanks for highlighting this!
I figure we want 100% valid rules; and if we can't have that reliably, then the FE must handle it.

How do we end up with rules with an invalid folder UID?
1. If the API allows them to be created (we can make the API stricter to prevent this)
2. ...if a rule is created with a valid UID but then the folder is deleted: would that also leave rules orphaned?

Probably:
* the API should prevent rule creation with invalid folder UIDs (reduce the problem)
* if we are likely to already have (or get) some, anyway, the FE needs to handle this (...because the rules **are** active and evaluated)

(Does this look right?)

**Comment by alexweav** [comment]
I feel like it's a backend bug. Right now, you are prevented from deleting folders containing rules.

The main area I can think of that's common in Grafana is provisioning. A lot of objects allow you to specify UIDs of objects that may not exist yet when provisioning - for instance, dashboards does this, that way the dashboard and folder can be applied and deleted in any order.

I think rejection is a good idea at the API level, there is no use case for this over the API. But, I think via files, it will still be possible to have rules with an invalid folder UID... and dashboards, and any other resource, via files. Grafana's file provisioning infra doesn't have the concept of object dependencies, it's not smart enough to create objects in order and delete them in reverse order.

**Comment by konrad147** [comment]
> The rule is still schedulable and evaluates just fine
Question: Does it mean we create a rule group that doesn't belong to any folder?

> I think via files, it will still be possible to have rules with an invalid folder UID
It looks like we should handle that in UI. As you suggested, we could add a particular folder, e.g., `Orphans`, at the top of the list for such cases

**Comment by konrad147** [comment]
I've just checked the problem, and here is what I've found out
**File provisioning**
- If you provision a rule to a non-existing folder, the folder will be automatically created for the rule
- If you use an empty string as a `folder` value, a provisioning error will be thrown

**API provisioning**
- There is validation neither for the `folderUid` nor `ruleGroup` field. These fields may be missing, and the rule still will be created
- Neither `/api/prometheus/grafana/api/v1/rules` nor `/api/ruler/grafana/api/v1/rules` endpoints return rules which don't have `folderUid` assigned, so they cannot be visible in the UI

> I think rejection is a good idea at the API level, there is no use case for allowing invalid UIDs over the API. But, I think via files, it will still be possible to have rules with an invalid folder UID.

It looks like you cannot create a rule in a non-existing folder using file provisioning. 

> I feel like there's a backend bug, if this is allowed at the API level.

I feel that too. We don't validate folders and rule groups in API provisioning, which seems to be a bug

**Comment by dmytro-zhernosiekov** [comment]
Hello. Is this bug still exists. I got similar behavior. I'm using `kube-prometheus-stack` and I tried to create alert with `configmap` and `grafana-sc-alerts`. But it failed, so I decided to create it first with API. At beginning I created Alert manually and read it with API call:
```
curl -u 'admin:password' -k http://localhost:3000/api/v1/provisioning/alert-rules | jq
```
After that deleted Alert and try to create same with API call. I deleted `uid`s.
```
curl -X POST -H "Content-Type: application/json" -u 'admin:password' -d @testrule.json http://localhost:3000/api/v1/provisioning/alert-rules | jq
```
I got 200 code, when I try to read it with API call I got same alert I created. But in UI I see nothing. Also I got Grafana log:
```
logger=context userId=2 orgId=1 uname=dmytro.zhernosiekov@xxx.yyy t=2023-05-22T13:22:09.659817658Z level=error msg="no rule groups found\n" error="no rule groups found\n" remote_addr=10.200.20.223 traceID=
```
Here several lines of alert code:
```
  {
    "orgID": 1,
    "folderUID": "test-group",
    "ruleGroup": "test-group",
    "title": "test-alert",
    "condition": "C",
    "data": [
        .....................
    ],
    "noDataState": "NoData",
    "execErrState": "Error",
    "for": "5m",
    "annotations": {
      "description": "Description",
      "runbook_url": "https://runbook.url",
      "summary": "Summary"
    },
    "labels": {
      "team": "infrastructure"
    },
    "isPaused": false
```
When I create Alert manually I create new group by typing text and pressing Entry. But looks like with API call or file provisioning it caused error. Because my code is appeared in grafana alert provisioning folder:
```
kube-prometheus-stack-grafana-6f89795d66-t7mvj:/etc/grafana/provisioning/alerting$ ls -la
total 24
drwxrwsrwx    2 root     472           4096 May 22 13:20 .
drwxrwxrwx    1 grafana  root          4096 Apr 24 17:00 ..
-rw-r--r--    1 grafana  472            755 May 22 06:07 contactpoints.json
-rw-r--r--    1 grafana  472           1310 May 22 06:07 templates.yaml
-rw-r--r--    1 grafana  472           3039 May 22 13:20 testrule.json
```
I checked Grafana API and there is no way to create Folder in advance - https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/pkg/services/ngalert/api/tooling/api.json

when the solution for this bug will be released?

**Comment by alexweav** [comment]
I think we should make two changes:
1. Update the ruler API to handle the case when the folder doesn't exist (it already does when datasource doesn't exist)
  - Consider pausing or skipping evaluation of these rules with a warning, because they are invisible but currently scheduled
2. In the UI display rules with a nonexistent folder in a separate group, only to admins, so that way the administrator can handle them.

**Comment by MichaelArida-BO** [comment]
Hello I am reaching out today because this seems to be a bug that appears multiple times in various different ways and many people seem to be impacted.

Is there a plan to fix this bug in the near future?

Thanks!

Related bugs:
https://github.com/grafana/grafana/issues/69510
https://github.com/grafana/grafana/issues/69512
https://github.com/grafana/grafana/issues/64357
