### ISSUE TITLE
Add max token lifetime configuration for service accounts

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#55233]
Requested by Azure, could be useful for other customers as well

As the administrator of a Grafana instance, I'd like to set a max token lifetime for service account tokens, so that users can't create long-lived tokens which violate my security policy. This setting should be shown next to the token lifetime field in the UI, and the UI and API should issue an error if I try to set a token lifetime past the limit.

_Open question: should this setting itself live in the .ini configuration file, or in the API/UI?_

**Comment by linoman** [comment]
I believe this setting could be easily implemented in the `ini` file since this setting wouldn't expect to change that often.

Pros
- Less unit test to implement

Cons
- Needs proper documentation

It would be worth considering an option to revoke/expire all the available tokens.

More questions
- What would happen to the current services?
- Will the UI reflect the expired tokens?

**Comment by linoman** [comment]
@mjseaman @vtorosyan I've created a design document for this issue.

https://docs.google.com/document/d/1HK4hqHs6483NeM5QiIw4kH1FyFAyc1V7Kg-sPFRmckU/

**Comment by linoman** [comment]
A separate issue has been created to address the behavior of existing SAT.

https://github.com/grafana/grafana-enterprise/issues/4126
