### ISSUE TITLE
content: strict clips time selector in panels

### ISSUE THREAD

**Issue by JorundMartinsen** [grafana/grafana#55438]
**What happened**:
We have a panel plugin with a time selector. The timeselector dropdown is clipped to the panel bounds when opened.

**What you expected to happen**:
The timeselector dropdown should render regardless of the panel bounds

**How to reproduce it (as minimally and precisely as possible)**:
Create a panel plugin, with a timeselector dropdown
```js
export const _TimeRangePanel: React.FC<PanelProps> = (props) => {
  return <TimeRangeInput value={props.timeRange} onChange={() => console.log('Time changed')} />;
};
```

Add the panel to a dashboard and set size to `"h": 2, "w": 3,`

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.1
- Data source type & version:
- OS Grafana is installed on: 
- User OS & Browser: Windows 10, Brave browser
- Grafana plugins: A custom panel plugin
- Others:

**Comment by JorundMartinsen** [comment]
For now, I'm removing `contain: strict` from `public\sass\pages\_dashboard.scss .panel-content`

**Comment by ashharrison90** [comment]
this is a little tricky, because we explicitly added `contain: strict` to prevent content exceeding the panel boundaries. 😅 

in this case, the best solution i can think of is to alter our `TimeRangeInput` to render the `TimePickerContent` in a portal. 

moving to @grafana/grafana-bi-squad for their input. wdyt? 🤔

**Comment by codeincarnate** [comment]
Talked with the BI folks about this and we agree on rendering within a portal. We're in the midst of a new time picker redesign and will be making those changes there upcoming. Beyond that this is tricky as we don't have an easy way to add interactive controls to a panel since they're designed for displaying charts, but probably something we should look at.

**Comment by JorundMartinsen** [comment]
I think it would be better to allow overflow, but update the panel templates. That way, the plugin author can choose to overflow. `contain: strict` seems to be a heavy handed approach to this problem.

**Comment by leeoniya** [comment]
we will be putting the new viz tooltips inside the panels, so we have relaxed the css containment in https://github.com/grafana/grafana/pull/75499
