### ISSUE TITLE
CVE-2022-35957 not mentioned in 9.1.6 Release Tag Notes?

### ISSUE THREAD

**Issue by Viajaz** [grafana/grafana#55531]
**What happened**:
https://nvd.nist.gov/vuln/detail/CVE-2022-35957 specifies:

> Versions prior to 9.1.6 and 8.5.13 are vulnerable

-implying that 9.1.6 has been fixed?

Changes listed on https://github.com/grafana/grafana/releases/tag/v9.1.6 do not mention a fix for CVE-2022-35957

**What you expected to happen**:
A mention that CVE-2022-35957 was fixed on release tag https://github.com/grafana/grafana/releases/tag/v9.1.6.

We automatically monitor the release feed, https://github.com/grafana/grafana/releases.atom, for any references to CVEs as part of our vulnerability management strategy, among others that serve the same purpose.

**Comment by dprokop** [comment]
@IevaVasiljeva I see the `add to changelog` label was there on the PR that fixed the issue. Has the note been manually removed from the changelog or has something wrong happened with the changelog generation?

**Comment by IevaVasiljeva** [comment]
Hi! Sorry for the late response, I've been on holiday for the past few weeks. 

I'd have to dig through PRs and builds to see why the changelog did not include the changes. The process for security releases has changed slightly since 9.1.6 was released, so I think it's best if I manually add the relevant info to 9.1.6 release notes and we pay extra attention to the change log of the next security release to make sure the changelogs are complete.

**Comment by IevaVasiljeva** [comment]
I'll close this issue now, but feel free to reopen it if you have any other questions or suggestions.
