### ISSUE TITLE
Alerting: Pagination in rules endpoint

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#55694]
**What happened**:

We do not paginate any endpoints in alerting right now. It's common for users to have many thousands of rules, and when they go to the rules list page it takes a very long time (minutes) to show any data.

This can be improved by adding pagination to the endpoint that the UI calls. This improves not just the DB layer of this query, but also reduces the size of the JSON blob that is transferred, which is faster to send, parse, and is generally less wasteful.

**What you expected to happen**:

I expected the rules list panel to not load many thousands of rules before displaying anything.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create many alert rules - several thousand.
2. Open the rules list panel. Takes a while to load.
3. Check the network transfer, all rules are sent.

**Anything else we need to know?**:

**Environment**:
- Grafana version: main
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by grobinson-grafana** [comment]
I think we should use token pagination instead of page numbers. There are a number of reasons for this:

1. Page number pagination requires `LIMIT` and `OFFSET`, which when combined with `ORDER BY` requires a full sequential scan of the table as the results must be ordered before the limit and offset
2. Page number pagination is not stable. For example, if someone creates an alert rule between page 1 and 2, someone else going from page 1 to page 2 might either miss the just created alert rule or see alert rules from the previous page
3. If we use token pagination we can change the internal pagination structure without breaking the UI since the current, previous and next page numbers are just opaque tokens

**Comment by alexweav** [comment]
Have worked with continuation token pagination in the past and can confirm it's really nice. Definitely agree with the above @grobinson-grafana.

It has great performance boosts in large tables, too. Skip/take slows down as you paginate, where tokens actually speed up as you paginate. They can also take advantage of indexes much better, so even the individual queries are significantly faster.

With some careful design as to how the token is constructed, they can also be stateless and require no extra storage, just like skip/take. Pagination can be resumed an arbitrary amount of time later, even years. There's a lot of benefits with comparatively few downsides.

That being said, we should see what other APIs in the project also support pagination and consider re-using what we can for consistency. I wrote this issue to try and be agnostic of _how_ we paginate.
