### ISSUE TITLE
[Alerting] Copy and paste panel - alert rule is not shown

### ISSUE THREAD

**Issue by mhollstein** [grafana/grafana#55714]
**What happened**:
I copied a panel Graph (old) with an alert rule to clipboard.
I create a new empty dashboard in another folder.
I paste the panel into this new dashboard and safe it.

**What you expected to happen**:
That the pasted panel looks the original panel with alert in in.
 
**How to reproduce it (as minimally and precisely as possible)**:
Do the steps unter "what happened"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.6
- Data source type & version: Prometheus
- OS Grafana is installed on: as docker container
- User OS & Browser: Windows 10, Browser: Chrome
- Grafana plugins:
 grafana-clock-panel/
grafana-image-renderer/
grafana-piechart-panel/
grafana-polystat-panel/
grafana-simple-json-datasource/
grafana-singlestat-panel/
jdbranham-diagram-panel/
monitoringartist-monitoringart-datasource/
natel-plotly-panel/
novalabs-annotations-panel/
radensolutions-netxms-datasource/
ryantxu-ajax-panel/
savantly-heatmap-panel/
vonage-status-panel/

- Others:

![2022-09-26 09_01_19-Copy and paste panel - alert rule is not shown · Issue #55714 · grafana_grafana](https://user-images.githubusercontent.com/56024424/192213439-58207794-1152-43d2-aa00-72574c3ad224.gif)

[Dashboard after import.json.txt](https://github.com/grafana/grafana/files/9643712/Dashboard.after.import.json.txt)

**Comment by dprokop** [comment]
@mhollstein I've tried to reproduce the issue against v9.1.6 and prior but could reproduce it.

Is the alert rule available in the pasted panel when you refresh the dashboard(browser refresh)?
Is this something that you can reproduce repeatedly? 
Are there any console errors when you paste the panel into new dashboard?

**Comment by mhollstein** [comment]
Is the alert rule available in the pasted panel when you refresh the dashboard(browser refresh)?  no
Is this something that you can reproduce repeatedly? yes
Are there any console errors when you paste the panel into new dashboard? no errors in the console

Here is the JSON from the panel I tried to copy   (Inspect, Panel JSON)

[panel-to-copy.json.txt](https://github.com/grafana/grafana/files/9661681/panel-to-copy.json.txt)

**Comment by torkelo** [comment]
This is by design.

Please move to new alerting system where alert rules are not defined in dashboard panels.

**Comment by axelavargas** [comment]
Hey, @mhollstein thanks for reporting this issue, I was able to reproduce it :), I am redirecting this issue to the @grafana/alerting-squad-backend as it seems when we paste the panel to the new dashboard the alert is not associated with the new dashboard (the panelJSON has the alert, but the dashboard does not have the relationship with that). I am not sure if this is a known issue, but hopefully, the team can help answer that :) 



https://user-images.githubusercontent.com/239999/194581971-d4970c26-1bb9-4b88-a26a-74d60c38ff86.mp4

**Comment by yuri-tceretian** [comment]
Since Grafana 8 alerting (or unified alerting) the alert rules are not bound to a panel. Instead, alert rules can be linked to a dashboard panel, but unfortunately, only one. The alert rule is linked to a panel by its ID. Therefore, when you copy a panel its id changes and therefore the link does not work. 

![image](https://user-images.githubusercontent.com/25988953/194583747-c3a86ec8-7e87-47c2-aa18-c4cba1034a36.png)

This is how a rule is linked to a panel

**Comment by yuri-tceretian** [comment]
The linkage of a rule to a dashboard has one consequence - the state history of the rule evaluations is written to annotations for the assigned panel. Other than that, there are no relationships between the panel and the rule in the backend. 

Technically, we can support a comma-separated list in the PanelID field. This can cause pretty serious performance problems as it will multiply the number of annotations, and therefore, write ops to the database, which is already a pretty serious problem in the case of a big number of alerts.

**Comment by mhollstein** [comment]
"alert rules can be linked to a dashboard panel, but unfortunately, only one."

What if...
During copy of a panel with an alert rule you create a new panel and you copy the alert rule too and link the new alert rule to the new panel? Is that a possible solution instead of having a long list in the panel ID field?
(the total number of annotations isn't reduced by that but the 1:1 connection remains)

On the other side: if you do not want to copy an alert rule in general, it would be good to clear all the alert information in the JSON of the copied panel.

A better approach would be to be able to link an alert rule to multiple panels and write the state history in a separate table. 
Then you can show this state information in multiple panels and have it only once in the database.
What do you think about?

**Comment by yuri-tceretian** [comment]
> During copy of a panel with an alert rule you create a new panel and you copy the alert rule too and link the new alert rule to the new panel? Is that a possible solution instead of having a long list in the panel ID field?

I would not go that way because:
- each copy of a rule will be evaluated as a single rule, which can cause more pressure on the data source. This will become even worse in HA mode as each Grafana instance evaluates all rules.
- similar to how Prometheus handles rules, Grafana handles rules as a group. Currently, it's only visible on API layer (for example, authorization, and order rules in a group) but soon we will update the scheduler to evaluate rules in the same group sequentially (currently they are evaluated independently).  Therefore, when we copy a rule we will have to decide to what position the rule needs to be placed in the existing group, or if we create a new group, whether other rules in the group need to be copied as well (there is an idea of having results of each rule be propagated down to the following rules in the group).


> On the other side: if you do not want to copy an alert rule in general, it would be good to clear all the alert information in the JSON of the copied panel.

That's a good point. We should strip the alerting info from the panel because it is related to legacy alerting.

> A better approach would be to be able to link an alert rule to multiple panels and write the state history in a separate table.
Then you can show this state information in multiple panels and have it only once in the database.
What do you think about?

We are working on a better state history, which won't be a part of the annotations. Once we do that we will be able to do a one-to-many relationship of a rule to panels.

**Comment by rathi909** [comment]
> Since Grafana 8 alerting (or unified alerting) the alert rules are not bound to a panel. Instead, alert rules can be linked to a dashboard panel, but unfortunately, only one. The alert rule is linked to a panel by its ID. Therefore, when you copy a panel its id changes and therefore the link does not work.
> 
> ![image](https://user-images.githubusercontent.com/25988953/194583747-c3a86ec8-7e87-47c2-aa18-c4cba1034a36.png)
> 
> This is how a rule is linked to a panel
