### ISSUE TITLE
Feature: Regex/Replace Metric Names

### ISSUE THREAD

**Issue by sblatnick** [grafana/grafana#5573]
I've noticed that tooltips and legends on graphs and table cell information get really wide because it includes the metric over and over.

For instance, let's say I group the metric by customer name and show a legend or tooltip with "all series".  Then I see something like:
```
metric.name.here.that.is.really.long (customerInfo=Apple)
metric.name.here.that.is.really.long (customerInfo=Banana)
metric.name.here.that.is.really.long (customerInfo=Pear)
...
```
Instead, I just want to display the customer name without the redundant metric.

**Comment by torkelo** [comment]
Use the ALIAS feature in the query editor to control what the series name should be. If you only want customerInfo and if this is a tag you can use that in the ALIAS field, click on the alias help info below the query editor to get more info on alias expressions. Since you removed the issue template (which contains required info about which data source you use), I cant be more specific as you dont mention what data source you use :)

**Comment by sblatnick** [comment]
Thanks for the help and sorry for the lack of details.  I was having difficulty finding the information.  We are using Grafana 3.0.4 with a KairosDB data source.  I didn't realize the alias field was able to do that.  I don't see any help on the Metric tab.  Googling around, it looks like maybe KairosDB as a datasource may not support a pattern in the alias?

**Comment by torkelo** [comment]
dont know, you can try ´$tag_<tagname>`

**Comment by sblatnick** [comment]
That didn't work.  Looks like maybe a feature for the KairosDB plugin?  I wouldn't suppose there is a way to move this over to grafana/kairosdb-datasource... so I recreated the ticket here: [grafana/kairosdb-datasource #24](https://github.com/grafana/kairosdb-datasource/issues/24)
Thanks!
