### ISSUE TITLE
TextArea: textareas have an extra spacing at the bottom

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#55804]
**What happened**:
Textareas have extra spacing at the bottom, which slightly breaks some layouts where they are used:
![image](https://user-images.githubusercontent.com/1170767/192505021-0a09e34b-7fcd-461f-a180-0d29c2e35cd6.png)

examples of layouts slightly breaking because of that:

![image](https://user-images.githubusercontent.com/1170767/192505807-c8b55491-9c95-4a49-8f8c-53936880ae5f.png)
![image](https://user-images.githubusercontent.com/1170767/192505850-9a0ee93f-c4bc-47ca-9e78-fa200df7c155.png)

**What you expected to happen**:
textareas shouldn't have that extra spacing

**Comment by L-M-K-B** [comment]
@Elfo404 
I'm currently looking into this and having problems to see the issue in the example screenshots. From your description I assume the issue is related to some margin at the bottom of the component, right?
I already checked the [TextArea](https://github.com/grafana/grafana/blob/2648fcb83369393d175c24547c389816cecc4e6f/packages/grafana-ui/src/components/TextArea/TextArea.tsx) component which doesn't have any margin below but there is a wrapper in the [related story](https://github.com/grafana/grafana/blob/2648fcb83369393d175c24547c389816cecc4e6f/packages/grafana-ui/src/components/TextArea/TextArea.story.tsx) which looks like the first screenshot in your description and behaves oddly. The wrapper shouldn't be a problem somewhere else.

Can you please point out what you mean exactly by "layouts slightly breaking"?

**Comment by Elfo404** [comment]
you can reproduce see the issue anywhere a textarea is placed on top of another input control, for instance in datasource settings (you can see an extra "space" between the textarea and the container:
![Screenshot 2023-04-06 at 12 39 43](https://user-images.githubusercontent.com/1170767/230366464-e0cff41c-787e-4fab-a00e-a71ca7f89b9d.png)

textareas are AFAIK displayed as inline-block elements, which means they follow typography-related rules. it is not an actual margin.

a few examples:

here you can see the inconsistency in spacing between a field with an input and one with a textarea:
![image](https://user-images.githubusercontent.com/1170767/230367455-7c6d16f8-1a09-4a99-9cce-44a6947882f2.png)

in alerting:
![image](https://user-images.githubusercontent.com/1170767/230367508-e7c255de-50e7-4991-96b8-f3406d9f77ce.png)

there was also a slack thread about this: https://raintank-corp.slack.com/archives/CT7S455SP/p1664272433392609
