### ISSUE TITLE
G 9.1.5 - Setting logarithmic scale does not impact the resolution of time series 

### ISSUE THREAD

**Issue by aengusrooneygrafana** [grafana/grafana#55867]
**What happened**:

when using a logarithmic scale and setting min/max/decimals the axis labels show minor logarithmic scales. It’s not readable and beautiful and apparently it was differently in their self-hosted 9.0.3. 
screenshots below with min/max/decimals and without - i.e no difference!  
They are currently evaluating 9.1.5 on GC.
Did something change?
Do you have some advice on how to make it more beautiful? 

![image](https://user-images.githubusercontent.com/54800912/192609656-9f751be2-687a-44e6-89e5-411e8241784e.png)

![image](https://user-images.githubusercontent.com/54800912/192609674-2f37ce2c-3183-47a2-ad46-2c8982c5a086.png)

**What you expected to happen**:

a visualisation rendered according to the logarithmic scale 

**How to reproduce it (as minimally and precisely as possible)**:

reproduce on G 9.0.3 and compare to G 9.1.5 

**Anything else we need to know?**:

**Environment**:
- Grafana version: above 
- Data source type & version: prometheus 
- OS Grafana is installed on: cloud 
- User OS & Browser: macos / chrome 
- Grafana plugins: prom datasource 
- Others: none

**Comment by aengusrooneygrafana** [comment]
as per the slack conversation i have raised https://github.com/grafana/grafana/issues/55867

**Comment by leeoniya** [comment]
looks like tick labels are not being skipped when decimals=0

**Comment by leeoniya** [comment]
@aengusrooneygrafana

> Setting logarithmic scale does not impact the resolution of time series

> screenshots below with min/max/decimals and without - i.e no difference!

just to be clear, the screenshots you're showing do in fact show the correct resolution difference. in the first screenshort you cannot see the green `AccountDetails.statistics` series, because it is below the specified `min` of 10ms. the top is also correctly clipped at 10s. i think the only issue here is the absent axis tick filtering to avoid overlap.

i also dont think `decimals=0` is really necessary for this case
