### ISSUE TITLE
Tempo: Service graph in dashboards does not work as Prometheus returns different dataFrame structure

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#55906]
Right now there is a difference between how metrics are returned from prometheus depending on whether it is in dashboards or explore. In one it returns a wide dataFrame in other it returns a dataFrame per series. The Tempo service graph assumes and transforms only one from those options (don't remember which now).

The tempo code should be able to transform both options into a node graph as both options are generally supported in Grafana.

**Comment by CrypticSignal** [comment]
Updates:
- I tried returning just the service graph but that didn't fix the issue,.
- Looked into this with @aocenas and confirmed that the cause of this issue is something else, hence the solution is more involved and requires further digging.
- The issue seems to be in the Prometheus code which processes the data in a different way depending on whether you are in Explore or Dashboard, and the difference in the format of the data being returned is causing this issue.

@aocenas Feel free to add any notes or updates.

**Comment by aocenas** [comment]
@CrypticSignal updated the description.

**Comment by aocenas** [comment]
cc @itsmylife
@gabor @ivanahuckova - do you remember why there is this difference? I wonder if it may make sense to just return the same structure in both cases from prometheus.

**Comment by ivanahuckova** [comment]
@aocenas I am wondering if the service graph works if you select format as table. 

<img width="750" alt="image" src="https://user-images.githubusercontent.com/30407135/195608085-9f7ddd45-0da0-477b-b8cd-d89990a59436.png">

**Comment by aocenas** [comment]
@CrypticSignal can you try Ivanas suggestion? Maybe that way we can just send the format in the query and always get the right response without adding any code.
