### ISSUE TITLE
[Feature request] Click to add a vertical line on all panels while scrolling

### ISSUE THREAD

**Issue by furnacification** [grafana/grafana#5592]
It would be great to be able to drop a vertical line (just like the shared crosshair) on a single panel and have that persist for the same moment in time on all other panels on a dashboard. Purely a temporary line for scrolling around a very long dashboard and not losing your focal point.

**Comment by volans-** [comment]
+1
Having a way to "lock" the shared crosshair, and potentially moving it with a slider when mouseovering it, would be very useful when debugging issues on larger dashboard (or smaller screens) where you have to scroll the page.

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!

**Comment by nikicat** [comment]
I want this too
