### ISSUE TITLE
BarChart: legend becomes right-aligned when bar orientation is horizontal

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#55932]
noticed while working on https://github.com/grafana/grafana/pull/55930

![image](https://user-images.githubusercontent.com/43234/192801196-16ff5ead-42c1-40db-a8e0-70cd940e4c34.png)

**Comment by codeincarnate** [comment]
Trying to dig up a similar issue we had with time series. I _think_ that this is another one of those instances where this particular layout hasn't been taken into account.

**Comment by mdvictor** [comment]
@leeoniya it seems that the legend alignment is based on the placement of the yAxis: https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/uPlot/PlotLegend.tsx#L59

Do we want that in any situation? Otherwise, I would just hard code it to the left, especially since `PlotLegend` is used only in `Timeseries`, `Histogram` and `BarChart` and as far as I've seen only `BarChart` has the ability to change yAxis placement

**Comment by leeoniya** [comment]
> as far as I've seen only BarChart has the ability to change yAxis placement

yep. i think the fix is to just add `AxisPlacement.Bottom` in there.

```js
yAxis: axisPlacement === AxisPlacement.Left || axisPlacement === AxisPlacement.Bottom ? 1 : 2,
```
