### ISSUE TITLE
Alerting: Move some common errors to a shared package

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#55966]
Some errors such as `ErrNoAlertmanagerConfiguration` are ubiquitious, but are defined in unusual packages like `store`. This requires many packages which reference/filter these errors to take an unnecessary dependency on `store`, when in reality these are more general in scope.

We should extract these errors to a shared package like `ngalert/errors`, or put them in something that's already ubiquitous like `model`. They shouldn't be necessarily coupled to store logic even though they can come from the storage layer. In reality, they are more closely aligned with the application logic of the alerting package in terms of how they are used.

I seem to remember at one point @joeblubaugh suggested something like this in a review comment. I think it's a good idea - thanks Joe! This issue was extracted from the task list here https://github.com/grafana/grafana/issues/55770.

**Comment by joeblubaugh** [comment]
I like this kind of naming:
```
errors.NoAlertmanagerConfiguration
errors.NotAuthorized
errors.ImageNotFound
```

Since the errors will rarely be used *within* the errors package, that makes for some clear names without too much clutter. However, we do already use the `errors` package quite a bit, calling `errors.Is` frequently in the `api` package and `errors.New` in a few places. I'm not sure what to do about that, because the `Is` check in particular is very meaningful to us. I don't want to have a bunch of `ngerrors.ImageNotFound`, because that reduces the clarity. `models` doesn't feel right as a prefix to me, as the models in question are the internal representations of our domain entities.

Here's another possibility. Bear with me, as I'm about to contradict myself: put them in the top-level `ngalert` package. If I were feeling really bold, I'd suggest doing that with all the shared domain models too, instead of giving them their own package. Now, the clarity of the `errors` prefix is replaced with the uglier `ngalert`, but *that's* a package that we'll rename to `alerting` after we remove the legacy alerting packages in G10. At which point the names will look like:

```
alerting.ErrImageNotFound
alerting.ErrNoAlertmanagerConfig
...
alerting.Rule
alerting.Instance
alerting.Query
```

So now any other packages importing the domain models don't do the "model package clash" that I see all over the codebase.

@grobinson-grafana should chime in, he had the clearest feedback last time we talked about it.

**Comment by grobinson-grafana** [comment]
If we put them in the top-level `ngalert` package I think we will end up with recursive imports.

For example, `ErrImageNotFound` is declared in `ngalert`, which imports the `image` package to initialize ngalert, but `image` also imports `ngalert` because it needs to return `ErrImageNotFound`.

```
ngalert --|
   |      | ErrImageNotFound
 image ---|
```

The `errors` package is a common idiom, the argument against it is that errors lose their context (i.e what package returns this error?)

I prefer to keep the declaration of errors local to the package that uses them, and prefer packages not to share errors. There are of course exceptions to this (for example, `encoding/json` returns `io.EOF`) but `EOF` is defined in `io` and not `errors`.

**Comment by alexweav** [comment]
> If we put them in the top-level ngalert package I think we will end up with recursive imports.

Agree, it can't go in `ngalert` as that's where our composition root is, `ngalert` depends on everything else. Errors need to be defined low in the dependency hierarchy, not high, or it won't be usable everywhere.

> I prefer to keep the declaration of errors local to the package that uses them

This is exactly what's tricky in these particular cases. Consider something like ErrNoAlertmanagerConfiguration. It's emitted in `store`, but also detected and translated into a status code in `api`.

FWIW, I'm not advocating for moving _every_ typed error to an errors package. Just the ones that are used at multiple layers of the application.

**Comment by alexweav** [comment]
:thinking: What about an errors _sub-package_, still in the relevant place?

I.e. `image` would have an `image/errors` subpackage that doesn't need to depend on anything. If someone else wants to parse an image-related errors, they can:
`import imgerrors ..../ngalert/errors`
 and then
`imgerrors.ImageNotFound` without taking a dependency on `image` proper?

**Comment by grobinson-grafana** [comment]
> This is exactly what's tricky in these particular cases. Consider something like `ErrNoAlertmanagerConfiguration`. It's emitted in store, but also detected and translated into a status code in api.

That seems correct to me though?
