### ISSUE TITLE
Edit JSON-File Dashboards from GUI

### ISSUE THREAD

**Issue by mjtrangoni** [grafana/grafana#5607]
* **I'm submitting a ...**
- [ ] Bug report
- [ X ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1
- What datasource are you using? Prometheus
- What OS are you running grafana on? Linux (CentOS 7.2)
- What did you do? Modify a JSON-File Dashboards located in /var/lib/grafana/dashboards/
- What was the expected result? An option to save those changes in this file 
- What happened instead? No Save-Dashboard Option available.
# cd /var/lib/grafana
# ll
total 900
drwxr-xr-x.  2 grafana grafana     97 Jul 15 13:01 dashboards/
-rw-r--r--.  1 grafana grafana 912384 Jul 18 15:40 grafana.db
drwxr-xr-x.  4 grafana grafana     61 Jun 17 09:03 plugins/
drwxr-xr-x. 18 grafana grafana   4096 Jul 11 07:56 sessions/

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
File based dashboards are only available if you auto generate dashboards etc, it is probably a feature that will be phased out, since you cannot star or mark a file based dashboard as a home dashboard. Will be replaced by syncing features that can sync a directory of dashboards to db. 

Why do you want to modify dashboards under `/var/lib/grafana/dashboards/`?
