### ISSUE TITLE
Google Cloud Monitoring runtime error index out of range

### ISSUE THREAD

**Issue by nokernel** [grafana/grafana#56181]
**What happened**: Grafana internal server error when doing heatmap bigtable server latencies repeating dashboard per app profile.
There is 3 app profile for this bigtable instance including the default app profile.

See [error.txt](https://github.com/grafana/grafana/files/9697838/error.txt)

**What you expected to happen**: See multiple dashboard show up with server latencies for each app profile.

**How to reproduce it (as minimally and precisely as possible)**: 
* Create grafana variable to fetch bigtable app profiles
* Create dashboard for metric bigtable server latencies, filter on metric.label.app_profile = $your_variable_you_just_created
* Group by function none
* Alignment function delta
* Alignment period, cloud monitoring auto
* Set panel to heatmap
* Set panel repeat option to repeat variable $your_variable_you_just_created with max 2 per row.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 9.1.6
- Data source type & version: Built in Google Cloud Monitoring datasource
- OS Grafana is installed on: Using grafana container image from `docker.io/grafana/grafana:9.1.6`
- User OS & Browser: firefox 105.0.1 on Linux.
- Grafana plugins:
- Others: Running within GKE cluster with workloadidentity

**Comment by andresmgot** [comment]
hi @nokernel, 

I have been trying to reproduce this issue with no luck but I am only able to try to reproduce it with some demo data. It seems that the problem is here:

https://github.com/grafana/grafana/blob/b287047052bbbbe6fc2d433a756b87646e1a2307/pkg/tsdb/cloudmonitoring/time_series_filter.go#L170-L178

For some reason, in your case, the number of `BucketCounts` is bigger than the number of `ExplicitBuckets.Bounds`, causing the `runtime error: index out of range` that you sent. 

According to this [documentation](https://developers.google.com/resources/api-libraries/documentation/monitoring/v3/python/latest/monitoring_v3.projects.collectdTimeSeries.html), that situation should not happen since that would mean that are values in buckets outside the range specified in the `BucketOptions`.

I have some follow up questions to try to get the root cause:

 - Do you also see this error when not using template variables? This is, targeting just one app_profile.
 - Is the error persistent? Does it always happens if you change parameters like removing the filter or using a shorter time frame?

**Comment by nokernel** [comment]
> hi @nokernel,
> 
> I have been trying to reproduce this issue with no luck but I am only able to try to reproduce it with some demo data. It seems that the problem is here:
[...]
> 
> I have some follow up questions to try to get the root cause:
> 
>     * Do you also see this error when not using template variables? This is, targeting just one app_profile.
> 
>     * Is the error persistent? Does it always happens if you change parameters like removing the filter or using a shorter time frame?

* I get the same behavior if I remove the project variable from the project field.
* I get a permanent error if I remove the filter completely here is the log with direct project name and no filter.

[log.txt](https://github.com/grafana/grafana/files/9725333/log.txt)

**Comment by andresmgot** [comment]
Thanks @nokernel, that discards the option that the error is caused by the template variable or the filter.

There are two possible options, either we are using the wrong bound number or my reasoning above is wrong. Since I am not able to reproduce the issue, can you go to the following URL, execute the request and send the response you get back? You need to modify the project name and authorize:

https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list?apix_params=%7B%22name%22%3A%22projects%2FYOUR_PROJECT%22%2C%22aggregation.alignmentPeriod%22%3A%22%2B300s%22%2C%22aggregation.crossSeriesReducer%22%3A%22REDUCE_NONE%22%2C%22aggregation.perSeriesAligner%22%3A%22ALIGN_DELTA%22%2C%22filter%22%3A%22metric.type%3D%5C%22bigtable.googleapis.com%2Fserver%2Flatencies%5C%22%22%2C%22interval.endTime%22%3A%222022-10-07T09%3A47%3A21Z%22%2C%22interval.startTime%22%3A%222022-10-06T09%3A47%3A21Z%22%2C%22view%22%3A%22FULL%22%7D

![Screenshot from 2022-10-07 11-59-39](https://user-images.githubusercontent.com/4025665/194528490-ebf741ed-0b20-47a3-966d-1b7b28015a56.png)

With the TimeSeries object that you should get back, I may able to indentify the issue.

**Comment by andresmgot** [comment]
okay, I spotted the issue, sending a quick PR

**Comment by andresmgot** [comment]
Thanks @nokernel, that discards the option that the error is caused by the template variable or the filter.

There are two possible options, either we are using the wrong bucket number or my reasoning above is wrong and there could be more buckets than ranges. Since I am not able to reproduce the issue, can you go to the following URL, execute the request and send the response you get back? You need to modify the project name and authorize:

https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list?apix_params=%7B%22name%22%3A%22projects%2FYOUR_PROJECT%22%2C%22aggregation.alignmentPeriod%22%3A%22%2B300s%22%2C%22aggregation.crossSeriesReducer%22%3A%22REDUCE_NONE%22%2C%22aggregation.perSeriesAligner%22%3A%22ALIGN_DELTA%22%2C%22filter%22%3A%22metric.type%3D%5C%22bigtable.googleapis.com%2Fserver%2Flatencies%5C%22%22%2C%22interval.endTime%22%3A%222022-10-07T09%3A47%3A21Z%22%2C%22interval.startTime%22%3A%222022-10-06T09%3A47%3A21Z%22%2C%22view%22%3A%22FULL%22%7D

Screenshot from 2022-10-07 11-59-39

With the TimeSeries object that you should get back, I may able to indentify the issue.

**Comment by nokernel** [comment]
Here uploading the results.txt gzipped file since the whole result file is about 6MB.

[results.txt.gz](https://github.com/grafana/grafana/files/9734303/results.txt.gz)

**Comment by andresmgot** [comment]
thanks @nokernel, that confirms what I wanted to verify :+1: I have opened a PR with a fix: https://github.com/grafana/grafana/pull/56565
