### ISSUE TITLE
Does "import" belong in the Dashboards section navigation?

### ISSUE THREAD

**Issue by amy-super** [grafana/grafana#56209]
To save room on the Dashboards (browse) page, I moved all of the "new" actions to a split button - New dashboard, New folder, Import. 

New dashboard creates and takes you right to the new dashboard. 
New folder opens a modal for naming the folder. 
Import takes you to a page with a workflow. 

This issue is the place to evaluate whether or not Import gets promoted to the section navigation or if it's OK to continue as-is.

**Comment by SeamusGrafana** [comment]
Hello,

I use the Dashboard Import option quite alot, particularly when replicating issues or using the new Panel Debug Export (which exports a Dashboard with the Panels Data in and more).

As such I frequently find myself adding new Dashboards quite often, prior to the `topnav` changes, I could hover over the Dashboards Icon until the menu showed, and then select the Import option. 

However since these changes that menu option is no longer accessible and I have to goto the new Menu, expand that, select Dashboards, goto the other side of the screen, select New then Import.

It would be nice if there was a quicker/easier way to Import Dashboards.

Some potential suggestions we discussed were;

* Add this to the new Command Palette Feature, so that there is an "Import Dashboard" option.
* Add this to the `+` menu in the top right corner now?

It would be great if we could find away to do one or both of these things, as I think they add additional value to those Menus and provide a quicker and better experience in doing this.

Thanks
