### ISSUE TITLE
Selected dropdown item is missaligned in prometheus and graphite configuration page

### ISSUE THREAD

**Issue by itsmylife** [grafana/grafana#56268]
**What happened**:
In the configuration page of Graphite and Prometheus data sources, when you select something in a dropdown, the selected item is misaligned. 
See the video for a better understanding:
https://user-images.githubusercontent.com/820946/193788418-09dd0379-dbb6-4ddd-bbff-56012ba8e581.mov

**What you expected to happen**:
It should not be misaligned.

**How to reproduce it (as minimally and precisely as possible)**:
Check the video 

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.2.0-beta
- Data source type & version: Prometheus, Graphite
- User OS & Browser: Chrome v105.0.5195.125

**Comment by arpitbhardwaj** [comment]
@itsmylife @bohandley Wish to start contributing in this repo. Let me know if I pick it up and start working on this.

**Comment by neel1996** [comment]
Hi, The PR raised above addresses the issue for the prometheus data-source setup alone. Found that the same is impacting the dropdown elements displayed on the graphite DS page as well (missed it initially).

![image](https://user-images.githubusercontent.com/47709856/195152051-38a732f8-fdb3-4c2e-a68a-569646452120.png)

Those dropdowns also use a custom width class (`width-10`) which leads to the same issue fixed in #56592. Considering this, should this issue to analyzed and addressed from the underlying `Select` component.

Please share your thoughts

**Comment by arpitbhardwaj** [comment]
Hi @neel1996 thanks for referencing your change.

@gtk-grafana @bohandley 
I have analysed it. 

The Select which we are using in prometheus and graphite are from LegacyForms but the one used in other pages where there is no alignment issue such as influxdb is the direct Select component from grafana-ui

I tried using the direct Select component from grafana-ui in graphite and it worked properly without any alignment issue.

Let me know if create a PR for the above fix.
