### ISSUE TITLE
Grafana 3.0.3 - Snapshot creation seems to not work from command line ?

### ISSUE THREAD

**Issue by machytkafitanalytics** [grafana/grafana#5639]
Sorry for submitting this issue maybe it is solved or not a bug but I was not able to find any comment about it....
*******************

I'm submitting a possible Bug report.

- Grafana version: 3.0.3 in Docker
- datasource: elasticsearch
- OS: Ubuntu 14.04
- I did: requested new snapshot to be created via "curl" request from linux command line
- expected result: snapshot with embedded data
- instead: I got snapshot without data with queries still in JSON  

But the same operation from Grafana GUI works OK and creates snapshot with embedded data series in it. Problem is that we would like to create ~80 snapshots every day for our customers. 

curl request looks like this:
```
curl --anyauth -XPOST 'http://localhost:3000/api/snapshots' -H 'Accept: application/json' -H 'Content-Type: application/json' -U mylogin:mypass -d'
{
  "dashboard": {
    "editable":false,
    "hideControls":true,
    "nav":[
    {
      "enable":false,
    "type":"timepicker"
    }
    ],
  "rows": [
    ......
  ],
  "time": {
    "from": "now-60d",
    "to": "now"
  },
    "timezone":"browser",
    "title":"Home",
    "version":5
    },
  "expires": 3600
}'
```
I got proper response with URLs and keys etc. But snapshot does not contain data....

**Comment by torkelo** [comment]
you want to use the api to create snapshots you need to include the metric data into the dashboard json (that is what the frontend code is doing when it creates a snapshot). Since all the metric quering and response handling is in the frontend, issuing queries for each panel and embedding the data into the dashboard before saving the snapshot is done in the frontend code. So if you want to create snapshots from the api, you will have to also issue metric queries and save the data into the dashboard json

**Comment by bharathrajbk** [comment]
If we have a very complicated dashboard, then adding so many queries makes it very difficult. :disappointed:
