### ISSUE TITLE
label_values does not scale well

### ISSUE THREAD

**Issue by thothothotho** [grafana/grafana#56464]
**What happened**:
I have a prometheus datasource with many series.  I have a few variables of type `Query`.  They are like
`label_values(some_metrics{some filters using previously defined variables}, some_label)`

At page load, each of this variable is initialized using an HTTP query like (encoding issue omitted)
```
GET /api/datasources/proxy/78/api/v1/series?match[]=some_metrics{some filters using previously defined variables}
```
This API fetches all the matching series, and the label values are aggregated client side.  In my case, this represents 8MB of json data, about 20 000 series are returned.  At the end, the result is a list of less than a dozen label values.

So my page loads in about 10s, more than 8s is dedicated to the loading of the label values only.  

**What you expected to happen**:

Fetching label values should be *much* faster.

**How to reproduce it (as minimally and precisely as possible)**:
Setup a prometheus datasource and add a label with this query `label_values(some_existing_metric, job)`
Observe the network traffic in the web inspector.

**Anything else we need to know?**:

Prometheus has an endpoint dedicated for that https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values
Example:
```bash
> curl -G 'http://localhost:9090/api/v1/label/category/values'  \
    --data-urlencode 'match[]=nq_request_duration_count{application_role="front"}'

{"status":"success","data":["HTTP","Net","RPCClient","RPCServer","Scenegraph","grpc","kafka","rabbit","redis"]}
```

**Environment**:
- Grafana version: 8.4.5
- Data source type & version: Prometheus  2.35.0
- OS Grafana is installed on:  Linux
- User OS & Browser: Linux ubuntu 22

**Comment by gtk-grafana** [comment]
@thothothotho This is a known issue: https://github.com/grafana/grafana/issues/33487.
The fix for this cannot be introduced without breaking functionality for older prometheus clients, (as the label API existed before the match parameter was introduced, and sending that parameter when not supported doesn't return any error) the good news is that we're in flight on a solution to introduce into the prometheus datasource config so people can use new prometheus API features like this without breaking functionality for older clients. We are hoping to get the version detection feature released this quarter, with a quick follow-up to add the label api support.

Closing as duplicate, but thank you for taking the time to document and report this issue!
