### ISSUE TITLE
export graph from grafana

### ISSUE THREAD

**Issue by psychopispa** [grafana/grafana#565]
Hello,

Is it possible to export graph from grafana in a png or jpeg... format ? Or is there a way to catch the url of a specific graph like in graphite

THanks !

**Comment by kssminus** [comment]
+1

**Comment by clawconduce** [comment]
+1 - We'd like to use capture the graphs as artifacts from our build & test process.

**Comment by flightjumpr** [comment]
+1

**Comment by pedroarthur** [comment]
I need build a post CHO (continuous hours of operation) test report and, since we are using grafana to keep track of our metrics, I've tried to use the share link with basic auth credentials to retrieve its graphics, but it only returns a failure image stating "Loading meta information failed". I have also tried using API keys, but got the same error. Does someone has some tip of how I could achieve this?

**Comment by menon0906** [comment]
How can i make this format "2017-07-13T00:00:00.000Z" correct in csv ? i tried replacing T and Z but doesn't seems to be correct. Any inputs please

**Comment by daniellee** [comment]
@menon0906 #8058 and its PR should solve this. Think you can just leave off the Z at the end. Googling gave me this: https://stackoverflow.com/questions/804118/best-timestamp-format-for-csv-excel

**Comment by soichih** [comment]
I need a way to export Grafana graphs into SVG format so that we can use it in our scientific publications / posters, etc. Is there a way to do that?

**Comment by JayjeetAtGithub** [comment]
> I need a way to export Grafana graphs into SVG format so that we can use it in our scientific publications / posters, etc. Is there a way to do that?

+1
