### ISSUE TITLE
Alerting Rule expand button hidden until search term is entered

### ISSUE THREAD

**Issue by wjordan** [grafana/grafana#56573]
The expand button appears and disappears when a search term is entered, resulting in a rather jarring UX:

![alert-filter](https://user-images.githubusercontent.com/56541/194615839-0f6620e8-15eb-4257-b3fe-1a5aec9e4091.gif)

It appears that this design choice was [intentional](https://github.com/grafana/grafana/pull/38770#discussion_r713848852) to indirectly prevent expanding a large number of alerts, but a disappearing button ends up being rather confusing and distracting. If anything, the button should simply be `disabled` (greyed-out and unclickable) when the number of displayed alert rules is greater than the amount that can reasonably handled without freezing.

**Comment by gelicia** [comment]
Hmm, the UX decision here was intentional as you said, so changing the UX to be dependent on the amount of alerts would be a feature request. To help with prioritization, we ask that feature requests go in [github discussions](https://github.com/grafana/grafana/discussions) so the teams can get upvotes from other people who want it, gather other information and prioritize.

**Comment by wjordan** [comment]
I disagree that this is a feature request warranting discussion, I see it as a pretty obvious UX issue that should clearly be fixed. In any case, here it is as a duplicate discussion thread as requested for your convenience: https://github.com/grafana/grafana/discussions/56574
