### ISSUE TITLE
alert behaviour changes after upgrade from 8 to 9

### ISSUE THREAD

**Issue by stonewesley** [grafana/grafana#56589]
**What happened**:
sum() or count() operator on a time-series query is different from version 8, so the alert always happens.

**What you expected to happen**:
same behaviour after upgrade 

**How to reproduce it (as minimally and precisely as possible)**:
1. create an alert with a time-series query range from now-3m to now and a sum classic-condition
2. upgrade from 8 to 9
3. open the alert and use reduce operator sum to check the result

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/5043930/194686716-cd81716b-e165-4315-9a74-d71f5c8188ab.png)
![image](https://user-images.githubusercontent.com/5043930/194686848-49f57542-daf0-42da-a11a-5e449b5a0be6.png)

**Environment**:
- Grafana version: 9.1.5
- Data source type & version: Prometheus 2.35.0
- OS Grafana is installed on: centos 7
- User OS & Browser: mac and chrome
- Grafana plugins: none
- Others:

**Comment by zuchka** [comment]
It looks like this issue is related to the legacy alerting platform, which is now deprecated. Have you considered using the new Unified Alerting platform in Grafana 9?

blog post: https://grafana.com/blog/2022/06/14/grafana-alerting-explore-our-latest-updates-in-grafana-9/
new docs: https://grafana.com/docs/grafana/latest/alerting/
how to migrate: https://grafana.com/docs/grafana/latest/alerting/migrating-alerts/
