### ISSUE TITLE
[Feature request] Have direct link rendered image use browser timezone

### ISSUE THREAD

**Issue by sgarg7** [grafana/grafana#5670]
Clicking on the title of a panel, then "share", then "Direct link rendered image" will generate an image with the X axis time in UTC. Can it be made to/have the option to generate the image with the browser time zone?

Grafana version: 3.1.0

**Comment by sgarg7** [comment]
It would be even better to be able to pass the time offset as a parameter; alerting bots can then generate the desired image for the right timezone. @torkelo

**Comment by andrewthad** [comment]
This is also an issue for me, and I think I agree with the solution that @sgarg7 suggested. More specifically, I would like:

- Time offset is passed as a querystring parameter to direct link render page
- This parameter is set by default to the users current time zone, if that setting in enabled for the dashboard.

**Comment by ictcorebiz** [comment]
Hi, Since the great new feature of alerting in Grafana, I'm also aware of the issue.

For me it would be a very nice solution if you could set the timezone in the dashboard settings. Currently you can only choose "local browser time" or "UTC", it would be nice to have UTC+[1-??] and UTC-[1-??].

@torkelo can you please comment on whether you see this as an issue too?

Thanks!
Sjoerd

**Comment by torkelo** [comment]
@ictcorebiz well of course it's an issue :) Currently the server side png rendering only uses the server time zone with no way to control it. It's tricky, would be good to include time zone somewhere in rendered image.

**Comment by sgarg7** [comment]
Thank you for adding this feature.
