### ISSUE TITLE
Import of dashboard using templated datasource does not respect template datasource usage

### ISSUE THREAD

**Issue by tcolgate** [grafana/grafana#5673]
- **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
  3.1
- What datasource are you using?
  Prometheus (applies generally though)
- What OS are you running grafana on?
  Linux
- What did you do?
  - Create a dashboard
  - Add a template variable called $datasource, that selects Prometheus datasources
  - Create a graph, set datasource to $datasource
  - export the dasboard
  - import the dashboard to another grafana
  - I am forced to pick a datasource, so pick one
- What was the expected result?
  - ideally the graphs on the imported dashboard would still use $datasource
- What happened instead?
  - They graph datasources are overwritten to use the datasource I selected on import

**Comment by phyber** [comment]
Just stumbled upon this when trying to automate the deployment of Grafana using pre-made dashboards.

- Grafana 4.6.2
- Prometheus datasource
- Linux
- Procedure
  - Created dashboard in a staging Grafana
  - Exported dashboard
  - Imported dashboard in a different Grafana via HTTP API (as used by the Puppet grafana module)
  - Dashboard is empty, complaining about the datasource.

Attempting to import manually via the UI instead of the HTTP API has Grafana prompt me for the datasource. In both the staging and other Grafana instances the Prometheus datasource is simply named `prometheus` and inspecting the JSON suggests that the `__inputs` section contains the correct information.

Expected behaviour:
  - That Grafana can actually use its own dashboard exports.

**Comment by megakoresh** [comment]
Hit this bug with Grafana 5.2.3

**Comment by hugohaggmark** [comment]
Closing this issue as I can't repro it on Grafana v7.4.0-pre (db637a3630) using the __`Export for sharing externally switch`__ and we're trying to limit open GitHub issues in order to better track planned work and features.

![image](https://user-images.githubusercontent.com/562238/98783580-1a999100-23fa-11eb-9bd4-bf79d4b998dc.png)

Thank You to you for taking the time to create this issue!
