### ISSUE TITLE
Unexpected save changes modal prompts when number of repeating charts changes because of filters  

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#56995]
**What happened**:

https://user-images.githubusercontent.com/5699976/195865359-ff33c853-8ced-4abe-aa2c-7c5e93e732fe.mov

When a widget is repeated by a variable and that variable changes the value, the dashboard proposes to save the changes when there are no changes made besides the filters.

**What you expected to happen**:
When the filter changes, those layout changes shouldn't affect to the persisted dashboard layout since they will depend on the original filter.

**How to reproduce it (as minimally and precisely as possible)**:
<details>
  <summary>
    Import this dashboard
  </summary>
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 1633,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "000000017"
      },
      "gridPos": {
        "h": 9,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "code": {
          "language": "plaintext",
          "showLineNumbers": false,
          "showMiniMap": false
        },
        "content": "# Repeated panel with value ${query0}",
        "mode": "markdown"
      },
      "pluginVersion": "9.2.0",
      "repeat": "query0",
      "repeatDirection": "h",
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "000000017"
          },
          "refId": "A",
          "scenarioId": "grafana_api",
          "stringInput": "datasources"
        }
      ],
      "title": "$query0",
      "type": "text"
    }
  ],
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": true,
          "text": [
            "1"
          ],
          "value": [
            "1"
          ]
        },
        "hide": 0,
        "includeAll": true,
        "multi": true,
        "name": "query0",
        "options": [
          {
            "selected": false,
            "text": "All",
            "value": "$__all"
          },
          {
            "selected": true,
            "text": "1",
            "value": "1"
          },
          {
            "selected": false,
            "text": "2",
            "value": "2"
          },
          {
            "selected": false,
            "text": "3",
            "value": "3"
          },
          {
            "selected": false,
            "text": "4",
            "value": "4"
          },
          {
            "selected": false,
            "text": "5",
            "value": "5"
          }
        ],
        "query": "1,2,3,4,5",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Layout changes when repeated row filter changes",
  "uid": "p6UVMhSVz",
  "version": 7,
  "weekStart": ""
}
</details>
1. Check there are no changes to be saved
2. Change the filter by selecting multiple values
3. Try to leave the dashboard, and it will prompt the warning to apply the stored changes. If you check the diff, the layout has changed.

**Environment**:
- Grafana version: 9.2.0
- OS Grafana is installed on: Cloud
- User OS & Browser: Chrome

**Comment by bschaeffer** [comment]
I think I reported this incident through enterprise support.

FWIW, I am also seeing this when our dashboards contain a repeated panel, but even when I change the non-repeated variable it will ask me to save my changes. For instance, if I repeat on `foo` but only change `bar`, it will ask if I want to save my changes.

**Comment by ivanortegaalba** [comment]
Thanks, @bschaeffer! We will take it into account when fixing it 👍

**Comment by polibb** [comment]
This issue describes the effort we need to consider when fixing the Save Changes modal popup in a dashboard: https://github.com/grafana/grafana/issues/24663, especially "Changes to template variable values should not be considered as a change worthy of unsaved change warning so ChangeTracker needs to go through a lot of cleanup to try to ignore them".
We discussed it with @natellium and she made a good point that we don't make a good distinction between "I'm viewing a dashboard" and "I'm editing a dashboard". Why wouldn't we want to save the new positioning of panels? Maybe sometimes it is needed. Imho we need to first set the clear and defined goal here and then make incremental changes.

**Comment by polibb** [comment]
This issue can probably be fixed separately, but I am concerned about a couple of things, which would make the effort here unnecessary for now.
It's not set in stone that this is a bug because it is actually a feature that needs to be replaced by a different-in-design feature. 
This open issue: [#24663](https://github.com/grafana/grafana/issues/24663) describes the effort we need to consider when fixing the changes-to-be-saved state in a dashboard.

We discussed it with [@natellium](https://github.com/natellium) and she made a good point that the current behaviour is confusing to the users: It understands variables changes are something we want to persist and they define the state of the dashboard.
It seems we need to first do some UX work, then set a clear goal and then make incremental changes.

**Comment by thanos-karachalios** [comment]
Dig into it. Not much to do from a UX perspective. The example showcases changes triggered from a layout alteration (I suspect there are reasons beyond a repeated panel due to variables for changes related to panel layout, eg panel rearrangement, deletion or addition of panels etc.). Don't think that intrinsic panel alterations (like width change) should trigger dashboard changes @Ijin08 @natellium

**Comment by natellium** [comment]
> Don't think that intrinsic panel alterations (like width change, or ordering panels. Eg panel rearrangement in my local instance triggers a number of changes) should trigger dashboard changes

@thanos-karachalios are we sure about this? How would you change the default order of panels in a dashboard if they didn't trigger any changes? Or to refer to the issue here, how would we change the default variable selection in a dashboard if it wouldn't count as a change?

I think the issue here is more related to the fact that there's no separation between the changes a user applies as a viewer  (e.g. applying filters or collapsing a row) vs the editing the dashboard state (e.g changing default filter selection or the default state of a row).

**Comment by thanos-karachalios** [comment]
@natellium I see the point between different user types, it make sense. What I was referring are the changes a user perceives(either viewer or editor). For example in this screenshot I reorder the two panels inside a dashboard (each panel draws from 2 two different DS in my local Grafana instance). As a user the change I apply and I am aware is the reordering, yet in the JSON model (under Changes tab I see 49 changes). I understand that this triggers changes but do they effectively reflect my action in what the user see in the UI? At this point not sure what would be a possible solution to this from a user standpoint. Taking back my comment about UX, probably we need to align on this @Ijin08 and get some more context understanding with @natellium 

![Image](https://user-images.githubusercontent.com/47744721/203309689-655ed0d8-8fe9-4059-a035-5565800ca683.png)
