### ISSUE TITLE
[Feature request] Let people set a custom refresh rate

### ISSUE THREAD

**Issue by martiei** [grafana/grafana#5707]
- **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request

Please include this information:
- What Grafana version are you using?
  3.1.1
- What datasource are you using?
  Graphite, ES
- What OS are you running grafana on?
  SLES11
- What did you do?
  nothing :)
- What was the expected result?
- What happened instead?

Hi,

currently my default refresh rate is 1m which results in a refresh at the full minute. We sometimes have a race condition where fresh data can't be aggregated properly since some graphite metrics are still being written at present.

This could be avoided by giving the user the ability to either refresh at every e.g. 30 second mark, or by letting people chose a custom refresh rate like 1m05s.

Hope my description makes the request clear.

Thanks!

**Comment by daniellee** [comment]
There is a work around for this. It is possible to change the refresh rate in the url. For example: https://play.grafana.org/d/6NmftOxZz/logs-panel?orgId=1&refresh=22s

This feature request has been open for a long time with few received upvotes or comments so we are closing it. We are trying to limit open GitHub issues in order to better track planned work and features.

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Still a big Thank You to you for taking the time to create this issue!
