### ISSUE TITLE
[Feature Request] Multiple Doc Type Support in Elasticsearch Datasource

### ISSUE THREAD

**Issue by vardancse** [grafana/grafana#5718]
The elastic search datasource can't be filtered using doc_type. Wouldn't it be better to have an option to filter on the basis of doc_type as well.
I was thinking of adding a new field to every query to choose doc_type.
Additionally, I suggest that on creating an ES data source, the user should have the option to pick the default doc_type (assuming that they want all the data from different doc_types available as default)

**Comment by torkelo** [comment]
you can filter by doc_type in the lucene query. Do you want to set this globally for all queries? (in data source options) ?

**Comment by marefr** [comment]
Since Elasticsearch 7 the support of using multiple mapping types oer index is deprecated and it's recommended to use an index per document type instead, see https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html for reference. Closing this, but will reconsider reopen it if I misunderstood something.
