### ISSUE TITLE
[Feature Request] Restrict allow_sign_up to list of domains

### ISSUE THREAD

**Issue by petemyron** [grafana/grafana#5722]
Allowing users to sign themselves up is great, but it exposes more info than you may want to if you're on the public interwebs or have multiple organizations. I propose that a list of acceptable domain names be added to the config. Then, when a user signs themselves up, the list of permitted domains is checked before creating the user account and shows an error if the user's email domain name is not on the list.

For example:
```###### ############ Users

[users]
# disable user signup / registration
allow_sign_up = true

# restrict self-sign-up users to only these domains, e.g. "example.com, school.edu"
# leave blank for any domain
# applies only to new users signing themselves up
# applies only if allow_sign_up = true
allowed_sign_up_domains = example.com, school.edu
```

I considered the name 'allowed_domains', but that isn't unique--it's used in the Google Auth section

**Comment by utkarshcmu** [comment]
+1

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
