### ISSUE TITLE
Viewer can edit library panel with viewers_can_edit = true

### ISSUE THREAD

**Issue by ashum81** [grafana/grafana#57242]
**What happened**:
Viewer can edit library panel.

**What you expected to happen**:
VIewer can't save changes to library panel.

**How to reproduce it (as minimally and precisely as possible)**:
Set viewers_can_edit = true.
Create dashboard with library panel.
Login user with viewer role.
Change library panel.
Save library panel.

**Environment**:
- Grafana version: 8.3.4

**Comment by axelavargas** [comment]
Hi @ashum81 👋🏾, thanks for reporting this issue, adding [viewers_can_edit](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#viewers_can_edit) to the configuration does not allow saving/updating library panels, a workaround that will be available after [this issue is fixed](https://github.com/grafana/grafana/issues/56997) is to create a folder where the admin can set "Editor" permissions to "Viewers". You can take a look [here](https://grafana.com/docs/grafana/latest/administration/user-management/manage-dashboard-permissions/) at how to achieve this :).

Thank you 🙏🏾
