### ISSUE TITLE
dial tcp i/o timeout

### ISSUE THREAD

**Issue by bentekkie** [grafana/grafana#5724]
* **I'm submitting a ...**
- [X] Bug report

I am using the latest grafana docker image on ubuntu 16.04
After a few days of grafana running I the graphs start to get 500 errors more and more frequently and this is the error in the log

2016/08/03 21:00:44 http: proxy error: dial tcp: lookup graphite.ourcompany.com on 127.0.0.11:53: read udp 127.0.0.1:39040->127.0.0.11:53: i/o timeout

Any ideas?

**Comment by torkelo** [comment]
no idea, never seen anything like this reported. Maybe some issue with your graphite server?

**Comment by sigmunau** [comment]
I'm seeing this also, though it happens right at start for me. The problem is not with the graphite server but with the DNS lookup. Docker exec into the container allows me to access network resources through ping etc without any issues related to dns lookup. Does grafana use some custom DNS settings/implementation? Most DNS implementations retries requests using TCP when UDP requests fails

**Comment by acerest** [comment]
It happens when I tried to set alert notification (email)

**Comment by sigmunau** [comment]
My research indicated that this is a bug in golang and that version 4.3.0 is compiled with a golang that does not have this bug and resolves the problem

**Comment by fredleger** [comment]
@sigmunau do you have a link to help with choosing the right golang version ?

**Comment by sigmunau** [comment]
@fredleger I don't remember the details anymore. Any fairly recent version should do

**Comment by Dmaina5054** [comment]
For me, the issue occurred when trying to add influxdb data source to grafana. I had to create a docker network and add the two containers.
