### ISSUE TITLE
v9.3: Grafana alert-edit: Red line rendered at `80` can't be dragged or moved

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#57258]
In Grafana 9.2 when editing a Grafana alert, there's a red-line rendered on the screen at `80` by default. This can be:
- Dragged with the mouse
- Moved by editing the value for `IS ABOVE` in the "Classic condition"

See this image:
![image](https://user-images.githubusercontent.com/2903904/196666587-da86b21b-9c86-4567-a89e-2d943e547d55.png)

In Grafana 9.3 the red line is still rendered, but can't be moved via either method. It's just fixed there permanently, with no explanation of what it is for, or why it is rendered:
![image](https://user-images.githubusercontent.com/2903904/196666809-d7179c80-f766-4a09-9285-8641a9721e2e.png)

**Comment by gillesdemey** [comment]
This is a consequence of the [threshold detection refactoring](https://github.com/grafana/grafana/pull/60046) which makes it much better at detecting thresholds in the expression pipeline but at the same time made it more complex to update the expression configuration from the time series panel.

The threshold indicator is tightly coupled to the `onChange` handler which meant that it wouldn't display the threshold indicator unless the drag-and-drop behaviour was implemented in its entirety.

[A follow-up PR](https://github.com/grafana/grafana/pull/60575) was introduced to decouple the `onChange` handler from the threshold indicator so we could show the values without having to implement the bidirectional threshold config update.

What's left to be done here is to do the _inverse_ of the threshold detection PR and instead of walking the DAG backwards to find the data query we have to walk it _forwards_ to find the expression that correlates with the threshold indicator and modify the correct properties of the expression.

The somewhat difficult part to figure out here is: thresholds drawn on the timeseries panel have no idea what expression drew them if you have multiple expressions pointing to the same data query. 

Maybe we can detect this somehow and make some exceptions and not implement it for these types of alert rule configurations.
