### ISSUE TITLE
Internal grafana metrics reporting needs to handle FQDN better

### ISSUE THREAD

**Issue by calebcall** [grafana/grafana#5739]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.0+
- What datasource are you using? Graphite
- What OS are you running grafana on? CentOS 6
- What did you do? Enabled internal reporting
- What was the expected result? Internal statistics being reported in at the defined prefix path
- What happened instead? Internal statistics were reported at a deeper path due to the hostname being FQDN.

I enabled the internal statistics reporting and instead of reporting in to $prefix.$server, they are actually reporting in to `$prefix.$server.<subdomain>.<domain>.com` (server name is server.subdomain.domain.com).  The internal reporting should replace any dots in the name with underscores.

**Comment by torkelo** [comment]
I could not find this fix in 3.1.x branch :(  all the commits needs to be cherry picked to that branch (since there are a few commits and they where done in master). 

Found a way to solve https://github.com/grafana/grafana/issues/5769 (setting this via ENV var).

If we add the section to defaults:  

```
[metrics.graphite]
address = 
prefix = prod.grafana.%(instance_name)s.
```

Leave the address default blank. If address is specified the graphite publisher is enabled.
