### ISSUE TITLE
[bug] layout problem when panel height is different

### ISSUE THREAD

**Issue by pkufranky** [grafana/grafana#5747]
- **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? opentsdb
- What OS are you running grafana on? debian

see following pictures. 

The first picture's layout is bad, due to the third panel which has different height .

after changing css from
.panel {
    float: left;
}

to

.panel {
    float: none;
}

the layout becomes good (the second picture)

So, any reason to setting float as left?

![bad](https://cloud.githubusercontent.com/assets/5346/17461506/3a05b23a-5cc1-11e6-87c8-aa8af7f2d541.jpg)
![ok](https://cloud.githubusercontent.com/assets/5346/17461507/42c1bc70-5cc1-11e6-838a-3c25cc0249d4.jpg)

**Comment by pkufranky** [comment]
This is a case that setting float to left is better than setting float to none.

However, i think this is a rare case, and the case above is the common case. So is it better to set float to none instead of left?

Another way to resolve the common case, keep the panel the same height even if the legend's height is different.

![float-left](https://cloud.githubusercontent.com/assets/5346/17463833/44f86034-5d02-11e6-92cc-0f0e03f6a904.jpg)
![float-none](https://cloud.githubusercontent.com/assets/5346/17463834/4bd0ba96-5d02-11e6-9b74-10c2afa4b3b5.jpg)

**Comment by torkelo** [comment]
One of you panels have a legend that does not fit (pushes to two rows) and expand the panel heigh above what it was supposed to be. You need to change the panel legend to use "table" format  in this case, in table format the panel can calculate the height of legend and scale down the height of the graph which makes the panel have the right total height and hence align with the other panels in the row

**Comment by pkufranky** [comment]
ok. I work around this by adjusting the order of .

**Comment by roman-vynar** [comment]
I have this problem since Grafana 3.0.

@pkufranky Re-ordering panels will also not always work. Say when you have dynamic number of rows in the table because some of them are hidden on zeros or simply more rows returned from datasource.

I agree that `float: none` is a some kind of fix for case 1 in this thread, however it breaks case 2.

Adjusted `float: none`:
<img width="1265" alt="screen shot 2016-08-18 at 10 32 07" src="https://cloud.githubusercontent.com/assets/2220941/17765598/85f0bf70-652f-11e6-882c-26008b0437ab.png">

Default `float: left`:
<img width="1268" alt="screen shot 2016-08-18 at 10 33 05" src="https://cloud.githubusercontent.com/assets/2220941/17765599/86261a8a-652f-11e6-81d8-8b2fdb0d11b4.png">

So it's not the legend table format. It was working differently in Grafana 2.6.x and was not a problem because the legend was expanding the graph. Since Grafana 3.x the legend became scrollable and this problem with height appeared.

I don't know what's the best solution is, however `float: none` works better to workaround those issues, the case 2 can be fixed to position singlestat panels differently, not one below other.

@torkelo do you have any suggestion to this? Should we put every 2 graphs into individual row so it's all aligned, I don't know?

**Comment by torkelo** [comment]
if you remove the relative tiem override on the Network Util Hourly graph does the issue persist?

**Comment by roman-vynar** [comment]
Yes, it persists. 
<img width="1271" alt="screen shot 2016-08-18 at 10 46 38" src="https://cloud.githubusercontent.com/assets/2220941/17765905/1f12b55e-6531-11e6-96b9-242fb8340a4d.png">

You can try on your own [here](https://pmmdemo.percona.com/graph/dashboard/file/System_Overview.json).

**Comment by torkelo** [comment]
I am unable to see the error there, should I select a specific host?

**Comment by roman-vynar** [comment]
No, you don't need to change the host. It's `ps57`. I am using Safari, also tried Firefox on OS X. Both have this issue now.

**Comment by torkelo** [comment]
yea, can replicate it in firefox (not chrome). 

Is there a reason why your not putting the Swap panel in a separate row?

**Comment by roman-vynar** [comment]
I can do this, however if every second graph comes with a bit (few pixels) longer legend than other we have to put every two graphs into an individual row. This is doable but does it make sense overall just to defeat this ui issue?

There are other places with the same issue, I reordered the graphs but it's conditional depending from how many rows on the legend I get.

Also moving all the graphs into individual rows is very time-consuming process, I would say `float: none` will be a better choice. It is interesting what it was in Grafana 2.6.x so case 1 and case 2 worked (the graphs were the same size, not one a bit higher by few pixels).

**Comment by roman-vynar** [comment]
To summarize, that's a browser issue:
- Chome: the graphs are the same height:
<img width="1276" alt="screen shot 2016-08-18 at 11 24 51" src="https://cloud.githubusercontent.com/assets/2220941/17766948/680c9414-6536-11e6-9301-b5b579b5478a.png">

- Safari/Firefox - one is a bit higher than other (few pixels):
<img width="1280" alt="screen shot 2016-08-18 at 11 25 29" src="https://cloud.githubusercontent.com/assets/2220941/17766962/7fa8d29a-6536-11e6-901e-36601b72ee8b.png">

**Comment by torkelo** [comment]
Panels should preferably not span more than one row, the layout system is based on rows. Each row should not contain panels that overflow (unless panel repeat where there is no alternative). 

I know the layout system kind of sucks :( We will try to improve it in future releases (it is on our backlog)
