### ISSUE TITLE
GUI allows two dashboards with the same name, API does not

### ISSUE THREAD

**Issue by RasmusLauritsen** [grafana/grafana#57526]
I am currently writing a Ansible Playbook that replaces the datasources in all of our dashboards using the API. In this process I stumpled upon this issue.

We have two dashboards with the same name, but in two different folders. This is allowed and doesn't seem to be a problem in the GUI.
```
/folder1/mydashboard
/folder2/mydashboard
```

In my Ansible Playbook I do the following:

1. Get all dashboards

`GET http://mygrafanainstance:3000/api/search?type=dash-db`

1. Loop all dashboards

```
GET http://mygrafanainstance:3000/api/dashboards/uid/uid-of-dashboard
Modify the datasource
POST http://mygrafanainstance:3000/api/dashboards/db
```

When I get to the second dashboard with a similar name I get the following error:
`fatal: [b0633s01.bdunet.dk]: FAILED! => {"cache_control": "no-cache", "changed": false, "connection": "close", "content_length": "96", "content_type": "application/json", "date": "Mon, 24 Oct 2022 12:12:30 GMT", "elapsed": 0, "expires": "-1", "json": {"message": "A dashboard with the same name in the folder already exists", "status": "name-exists"}, "msg": "Status code was 412 and not [200]: HTTP Error 412: Precondition Failed", "pragma": "no-cache", "redirected": false, "status": 412, "url": "http://mygrafanainstance:3000/api/dashboards/db"}`

**What happened**:
"A dashboard with the same name in the folder already exists"

**What you expected to happen**:
That dashboards is identified by meta.folderId and dashboard.id instead of dashboard.title.
The title should not be required to be unique.

**How to reproduce it (as minimally and precisely as possible)**:
Create two dashboards with the same title in two different folders (same organization)
Get the dashboards with API, and post the dashboards again - perhaps with a minor change like datasource uid.

**Environment**:
- Grafana version: 9.2.1 (and 9.1.3)
- OS Grafana is installed on: Docker running on RHEL

**Comment by sakjur** [comment]
Thanks for the report!

It looks like the APIs for `GET /api/dashboards/uid/…` and `POST /api/dashboards/db` are sufficiently similar but not quite to move dashboards out of folders if you don't provide `meta.folderId` or `meta.folderUid` as `folderId` or `folderUid` respectively when you save the dashboards.

…so the good news is that you should be able to workaround this relatively easily by copying over `{"meta": {"folderId": n}}` to `{"folderId": n}`.

On the other hand, it's annoying because there isn't a single clear right path to fix this. There are a few different approaches we could take for a solution here, the lowest hanging of which would be to not consider omission of folder to mean "folder zero" (i.e. general). We could also add support for the `meta` type when saving.

**Comment by ying-jeanne** [comment]
Hey @RasmusLauritsen as Emil mentioned, in the get response and post request, folderid is not in the same json field path, you need to map the folderid in your script before post. I would close this ticket for now, let us know if you still not able to make the script works.
