### ISSUE TITLE
Service Account: add service account check for IsRealUser()

### ISSUE THREAD

**Issue by Jguer** [grafana/grafana#57532]
Using a service account to create a team makes the team show up as a member of the newly created team.

Reproducing:

- Terraform provision teams using a service account as auth

Desired behavior:

- Service accounts creating a team should not get added as team members
- Service accounts creating a team should not get managed permissions as team managers

**Comment by eleijonmarck** [comment]
@Jguer 

The addition of a service account as the team member of the created team is due to this line:
https://github.com/grafana/grafana/blob/main/pkg/api/team.go#L48

We call a function `c.SignedInUser.IsRealUser()` which checks
```go
func (u *SignedInUser) IsRealUser() bool {
	return u.UserID > 0
}
```

The information for SignedInUser comes from the ReqContext struct which is constructed using the context of an api call.
https://github.com/grafana/grafana/blob/main/pkg/models/context.go#L17

**proposals**
Both proposals involve adding the IsServiceAccount bool to the `SignedUser` struct.
Currently I do not see another way to introduce the information about being a service account.

// proposal 1
```go
func (u *SignedInUser) IsServiceAccountUser() bool {
	return u.IsServiceAccount == true
}
```

**benefits**
- more control and to introduce this slowly in places where this is needed

**tradeoff**
- another control parameter to check for

// proposal 2
```go
func (u *SignedInUser) IsRealUser() bool {
	return u.UserID > 0 && u.IsServiceAccount == false
}
```
**benefits**
- Make sure that we cover all of the cases where `IsRealUser` is being used

**tradeoff**
- alot of places uses this and might introduce more bugs than fixes

---
let me know what you think

**Comment by papagian** [comment]
The reason that `IsRealUser()` was introduced was to catch [this](https://github.com/grafana/grafana/blob/6f8fcae01b3916749403dc0e2dfbdc99bde4bd4b/pkg/services/contexthandler/contexthandler.go#L110) case (so that we don't include API keys as team members). Both proposals LGTM as long as they both exclude API keys and service accounts.

**Comment by eleijonmarck** [comment]
Closed with https://github.com/grafana/grafana/pull/58015
