### ISSUE TITLE
Security: Grafana behind Azure Application Gateway

### ISSUE THREAD

**Issue by deweil** [grafana/grafana#57656]
**What happened**:

We are hosting Grafana, without any customizations, (on an AKS Cluster using [grafana helm charts](https://github.com/grafana/helm-charts)) behind an Azure Application Gateway, with Web Application Firewall(WAF) enabled and following the OWASP 3.1 rule set. However from the Firewall Logs, we see that Grafana application has multiple vulnerability entries which indicates that the application doesn't clearly follow the OWASP 3.1 rules. This result in blocked requests and unable to connect to the datasource without whitelisting each and every query going to the datasource.
Following are the Firewall Rules/Vulnerabilities that are reported in the logs so far.

Rule ID | Description
-- | --
931130 | Possible Remote File Inclusion (RFI) Attack: Off-Domain Reference/Link
932105 | Remote Command Execution: Unix Command Injection
932110 | Remote Command Execution: Windows Command Injection
932115 | Remote Command Execution: Windows Command Injection
942410 | SQL Injection Attack
942120 | SQL Injection Attack: SQL Operator Detected
942130 | SQL Injection Attack: SQL Tautology Detected.
942150 | SQL Injection Attack
942180 | Detects basic SQL authentication bypass attempts 1/3
942360 | Detects concatenated basic SQL injection and SQLLFI attempts
942410 | SQL Injection Attack
942430 | Restricted SQL Character Anomaly Detection (args): # of special characters exceed

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.6
- Data source type & version: data explorer
- OS Grafana is installed on:  Kubernetes / Linux
- User OS & Browser: Chrome
- Grafana plugins: Azure Data Explorer Datasource
- Others:

**Comment by mckn** [comment]
Thanks for opening this issue! Would it be possible to provide some logs on what requests caused the different entries?

**Comment by tolzhabayev** [comment]
closing as stale

**Comment by ivanmagdic** [comment]
For anyone who has a similar issue.

I've had a Grafana deployed with kube-prometheus-stack (HELM) behind the Azure Application Gateway Ingress Controller. AGIC was using WAF policy OWASP_3.2.

On certain endpoints (ex. /api/ds/query?ds_type=prometheus&requestId=Q166) received 403 (mainly POST and PUT methods) status codes when looking at certain default Grafana dashboards.

The fix for me was to make an exclusion for the OWASP_3.2 policy by defining **Request Arg Names**, operator selected as **Equals Any**, and specified "queries" as **Selector**. Just to validate the problem, you can select all the rules and later narrow it down by examining the WAF logs.

The assumption is that the WAF has issues with request body values under the "queries" key.
