### ISSUE TITLE
[Feature Request] capability to choose between Prometheus "query" and "query_range" API for table

### ISSUE THREAD

**Issue by askannon** [grafana/grafana#5765]
Grafana: 3.1.1 (docker image)
Prometheus: 1.0.1 (docker image)

I have the following Prometheus query:

topk(5, sum(rate(jaxrs_client_proxy_latency_seconds_sum[1h])) by (proxy, method))

When I run this in the Prometheus console I get a nice and simple "top 5"-style table because it is using the "/api/v1/query" endpoint on Prometheus. Now when I go to Grafana and add a "Table" and put the same query in I end up with a time series that I don't want/need because it is using the "/api/v1/query_range".

It would be great if - at least for the table element - it would be possible to choose what endpoint to use on Prometheus so that I can decide if I want to deal with a time series result or a simple table. Not only would it display the data that I am looking for but the "/api/v1/query" endpoint is responding about 10 times faster to the query than the "/api/v1/query_range" endpoint.

**Comment by ma05k1** [comment]
Agreed +1

**Comment by icholy** [comment]
Does https://github.com/grafana/grafana/pull/6140 solve this?

**Comment by askannon** [comment]
@icholy yes and no.

yes: #6140 is implementing access to the instant query API that I also need to use
no: the way #6140 is implementing it doesn't work for my use-case because I can't freely choose between what API to query

If #6140 could implement instant API usage trough some kind of choice in the Prometheus query editor instead of auto detecting it through "interval === 0" then it would solve my issue.

**Comment by mtanda** [comment]
@torkelo Would you add label "Prometheus" to this issue.

**Comment by mtanda** [comment]
Just a memo about Prometheus implementation.

The difference of Prometheus internal implementation is passing value for `newQuery()`.
https://github.com/prometheus/prometheus/blob/v1.6.1/promql/engine.go#L343
https://github.com/prometheus/prometheus/blob/v1.6.1/promql/engine.go#L359

But, pass `0` step to query_range is not allowed.
https://github.com/prometheus/prometheus/blob/v1.6.1/web/api/v1/api.go#L229

**Comment by wtip** [comment]
`max_over_time(node_load5[30d]) < 0.5` this is another prometheus query that I am trying to display in a grafana table using just the query api.

**Comment by NicolaiPetri** [comment]
This is also an issue for me with grafana / prometheus table handling. 
The query is: sum(service_ok) by (api,operation)
I'm trying nicely present this with only latest values, but no matter what I do it will always give me a range. 
I can cheat by setting resolution to 1m and timespan to 1m and hiding time, but then my value column is not working since metrics with different amount of labels seem to overflow into wrong column (value column)

**Comment by fmmr** [comment]
afaik this would be really helpfull for the pie-chart and other plugins as well.

pie-chart displays the last values of a time-series range - even if a metric does not have any values for the last/same timestamp as requested.

using query instead of query_range would solve the problem because prometheus would not return old value.

Also query is WAY more performant than query_range, especially for more complex queries.

**Comment by SuperQ** [comment]
👍 

This would also be very useful for single stat panels.
