### ISSUE TITLE
Security patch not applied on 8.x major line

### ISSUE THREAD

**Issue by gburton1** [grafana/grafana#57786]
There is a CVE from 2021 against Grafana Loki (CVE-2021-36156) that was patched a long time ago. Grafana used to take a dependency on `github.com/grafana/loki v1.6.2-0.20211015002020-7832783b1caa`, but they recently [refactored how they pull in Loki dependencies they need](https://github.com/grafana/grafana/pull/51500); instead of pulling in the whole Loki package, they just pull the parts they need. That change eliminated the old version from the dependencies. The problem is that this change is only part of the 9.x major line. They never ported it to the 8.x line, which we are on. The 8.x line should still be supported for security patches.

```
An issue was discovered in Grafana Loki through 2.2.1. The header value X-Scope-OrgID is used to construct file paths for rules files, and if crafted to conduct directory traversal such as ae ../../sensitive/path/in/deployment pathname, then Loki will attempt to parse a rules file at that location and include some of the contents in the error message.
```

![image (15)](https://user-images.githubusercontent.com/9094087/198384064-104fd190-2649-4298-92dc-f46104e91f26.png)

**What happened**: Security patch was not applied on Grafana 8.x

**What you expected to happen**: https://github.com/grafana/grafana/pull/51500 should be applied to 8.x

**How to reproduce it (as minimally and precisely as possible)**: No steps needs.

**Environment**:
- Grafana version: 8.5.13
- Data source type & version: n/a
- OS Grafana is installed on: Alpine Linux v3.15
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by sakjur** [comment]
CVE-2021-36156 was a false positive for Grafana from the very beginning, which is why it took so long until we addressed it. It'd be nice to not have to it show up for v8.5.x, but people staying on past versions also expect a certain level of stability coming with that, and I believe that considering all upgrades to dependencies with CVEs reported toward some part of the dependency as a security patch would be impractical.

I don't consider #51500 to be a security patch. While part of its job is to silence the vulnerability scanners, it doesn't actually fix a problem (since the problem in question is far away from the parts of the Loki codebase we were using).
