### ISSUE TITLE
Docs: Inconsistency in Math vs classic condition value results

### ISSUE THREAD

**Issue by mbrancato** [grafana/grafana#57846]
**What happened**:

Alerting in Grafana 9 has been quite a challenge over the legacy alerts, especially trying to get meaningful data formatting to the alert delivery. While attempting to use alerting with Slack and message templates, I've noticed some inconsistencies that I think should not exist.

I start with a simple query, this one here is used as just an example:
<img width="990" alt="image" src="https://user-images.githubusercontent.com/8493275/198702325-cf69e57a-e521-4876-bdd1-3679087b2124.png">

Then, there are two options here to set the "alert condition". Notice, it is referred to as a condition, not a data type. My view is this should be a boolean condition evaluation, and not affect the resulting data. Or, the user should be able to select what from each condition goes into the final result.

If I choose  a classic condition, a lot of the online documentation / forum posts are helpful. Best documentation I've found yet: https://community.grafana.com/t/how-to-use-alert-message-templates-in-grafana/67537/3

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/8493275/198702876-b6f6675c-d3ae-4419-bccd-c15ee03210ef.png">

I create alert details that look like this template:

```
{{ with $values }}
{{ range $k, $v := . }}
  key: {{ $k }}
  labels: {{ $v.Labels }}
  value: {{ $v }}
{{ end }}
{{ end }}
```

And I get these results:

```
  key: B0
  labels: map[cluster:mycluster]
  value: 71.49750415973378
```

If I do not use a classic condition, but instead use math, this breaks alerting.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/8493275/198706735-55dce732-7416-4a72-95c4-91540d4339fb.png">

Selecting "Preview alerts" returns an error:
```
invalid format of evaluation results for the alert definition B: looks like time series data, only reduced data can be alerted on.
```

So I need to reduce the data before math:

<img width="985" alt="image" src="https://user-images.githubusercontent.com/8493275/198707133-fc974762-8523-49c0-8360-2a803f2037f6.png">

This results in a strange set of data, different from what was returned with the classic condition:

```
  key: B
  labels: map[cluster:mycluster]
  value: 76

  key: C
  labels: map[cluster:mycluster]
  value: 1
```

As an aside, in my testing, playing with certain incompatible templates here seemed to be able to stall all alerting for all rules in a Grafana instance.

**What you expected to happen**:

When a condition is matched, a consistent data structure should be moved from the condition matching phase to the alerting phase. While that might include a free-form map like labels, the base structure should be the same, regardless of what type or how many expressions were used in the condition.

**How to reproduce it (as minimally and precisely as possible)**:

Create two rules for the same query, but use one with a classic condition, and another with reduce / math.

**Anything else we need to know?**:

It is possible to select which step is used to trigger the condition:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/8493275/198708723-243d50ca-77ac-4aac-a42c-43e713b3a993.png">

However, there is no similar ability to select which step the resulting alert data should be sourced from.

**Environment**:
- Grafana version: 9.1.7
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux / Grafana container / helm chart
- User OS & Browser: Mac / Chrome
- Grafana plugins:
- Others:

**Comment by wjordan** [comment]
> However, there is no similar ability to select which step the resulting alert data should be sourced from.

The current practice is to set an alert rule's annotation template to select the specific expression containing the meaningful value before it gets flattened to `1`, e.g., `{{$values.B.Value}}` or just `{{$values.B}}`. However, this is tedious and error-prone, since errors in the Go templates have a poor feedback loop (errors are only returned to the server's stdout after a firing alert instance is evaluated) and can break alerting if syntax errors are introduced. For classic-condition value results, however, you need to iterate over `{{$values}}` since each element represents a separate evaluated result. I also agree this inconsistency in value result types is a major issue, since it demands detailed knowledge of how these different expression types function internally in order to create simple alert rules with them. It made Grafana Alerting too complex for my team to use on a daily basis.

I proposed a alternate, simplified solution to this as part of #57489. The first part is to change the `mathexp` logic to preserve values for 'truthy' conditional expressions, so firing alerts conditioned on Math, Threshold, etc expressions retain their actual values instead of a meaningless `1`. The second part is to store only the final evaluated result values in the `Values` map, since this expression now consistently retains a meaningful value and so there's no need to select it from among the other intermediate expressions. This will allow you to iterate 
 over `$values` to render values consistently, whether using a classic condition or any other expression type.

**Comment by armandgrillet** [comment]
@wjordan is the right reply. This is poorly documented, we will improve that.

**Comment by brendamuir** [comment]
Closing this - as the related dev PR was closed https://github.com/grafana/grafana/pull/57489.
