### ISSUE TITLE
PanelRenderer/BarChart: Click handler for the bars

### ISSUE THREAD

**Issue by 2Steaks** [grafana/grafana#57966]
### What would you like to be added:
Add a click handler which fires for each bar in the graph, allowing for custom logic to be executed.

### Current behaviour:
None

### Why is this needed:
The k6 plugin requires the ability to navigate from a summary of tests (bars) to an individual test page

### Desirable:
```
const handleDataClick = ({ index, ...data }) => {
  // navigate to test page
}

return (
    <PanelRenderer
        onDataClick={handleDataClick}
    />
)
```

### Example:
https://user-images.githubusercontent.com/4395376/199224666-657b1be0-f925-48f9-b265-dd94bcb1ee91.mov

**Comment by tolzhabayev** [comment]
I don't think we want to go this road, we have some ideas on making what you wish for possible but via other means.

Read more: https://docs.google.com/document/d/1ul5iE6Q-CFhjbu9SOe-6LbsC71hobiSnYkHvdrXq014/edit and https://docs.google.com/document/d/1-g6-4RJx3LzsldvdwUZb_wHXAS5Z7_kt6Ql9zAoLj8I/edit

fyi @mckn

**Comment by mdvictor** [comment]
Hey! 
Correct me if I'm wrong: do you just want a way to open the test run page of an associated bar on click?
Because for this specific scenario there might be a workaround with datalinks and template vars, even though there are no custom click handlers in Grafana yet. 

I've made this example barchart with random bar values, but proper test ids (for correct data-link redirection), in this form:

```
  const dto: DataFrameDTO = {
    fields: [
      { name: 'tests', type: FieldType.string, values: ['test 1', 'test 2', 'test 3'] },
      { name: 'vals', type: FieldType.number, values: [1, 3, 4], config: { links : [ { title: "test", url:"/a/grafana-k6-app/runs/${__data.fields.test_ids}"} ] }},
      { name: 'test_ids', type: FieldType.number, values: [1623728, 1623725, 1623999], config: {custom: {hideFrom: {tooltip: true, viz:true, legend: true}}} },
    ],
  };
```

which would result in something of the sorts, that seems to do what you want (except that you can't directly click on the bar, but would need to go through the tooltip):


https://user-images.githubusercontent.com/36818606/211610507-57b39fbe-9b89-41ba-967d-d1fc7335f1f0.mov

the chart is rather messy, but let's focus on the bars: each bar has a different test run ID associated to it, and using datalinks we can open each test run by clicking on the bar (and then open the link).

Is this the functionality you'd like? 

As for the `onClick` handler I can possibly see a workaround to what @tolzhabayev suggested in the form on an option that allows running datalinks on bar click. Though I can see a couple of issues with this...

**Comment by nmarrs** [comment]
Hi @2Steaks - were you able to review @mdvictor comment? Will datalink functionality suffice?
