### ISSUE TITLE
[Feature Request]Turn Off Auto-Scaling

### ISSUE THREAD

**Issue by robinwang08** [grafana/grafana#5816]
I currently have a dashboard of multiple panels each displaying the response time of an individual service. I noticed that the y-axis will autoscale with the data. If the milliseconds are high enough, it will change my scale to seconds. But then I will have several other panels that are still in milliseconds, which makes the dashboard very inconsistent as the y-axis scale is different for each panel and will lead to confusion. Can we have a way to turn off the auto-scaling? I don't want to use the min/max feature as I will never know what the max is. It would be best to be able to specify that I want the Y-axis to be in ms and have the axis display ms instead of auto-scaling it to seconds when it is set to ms.

**Comment by agabert** [comment]
+1

**Comment by americano95** [comment]
+1

**Comment by debmalyapan53** [comment]
+1

**Comment by DonRichie** [comment]
I have the same problem, but found out a workaround with the new "Custom Units" Feature in Grafana 6.6:

a) Depending on your data source, change the select part so that you get the number which is correct for your unit:
       "select watthour / 1000 from energy;"
b) Set the custom unit: "kWh" by writing the letters in the unit selection (working since grafana 6.6)

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
