### ISSUE TITLE
Documentation refers to unmaintained ansible role from cloudalchemy

### ISSUE THREAD

**Issue by michaelkebe** [grafana/grafana#58485]
**What happened**:
The documentation refers to https://github.com/cloudalchemy/ansible-grafana in the documentation at https://grafana.com/docs/grafana/latest/administration/provisioning/#configuration-management-tools.

It looks like the maintainers have dropped the cloudalchemy project. See https://github.com/cloudalchemy/ansible-node-exporter/issues/266#issuecomment-1226926107

**What you expected to happen**:
Have a maintained ansible role to install grafana.

**Comment by GrafanaWriter** [comment]
@chri2547 - is this part of the As CodeIA work? On the referenced page, we state that "Currently we do not provide any scripts/manifests for configuring Grafana. Rather than spending time learning and creating scripts/manifests for each tool, we think our time is better spent making Grafana easier to provision. Therefore, we heavily rely on the expertise of the community."
