### ISSUE TITLE
Email redesign

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#5849]
All Grafana emails to follow the same email template as grafana.net

- design alert emails
- migrate all current emails for follow the grafana.net design

**Comment by bergquist** [comment]
@bulletfactory I'm assigning this to you. But just unassign it if you don't have time for this in the near future.

**Comment by bulletfactory** [comment]
happy to tackle this

**Comment by bulletfactory** [comment]
@bergquist please take a look at the emails branch - here's a screengrab of desktop and mobile. One issue I'm struggling with is the table on mobile - I having trouble getting the table to expand to 100% width, even though it says otherwise. You'll see what I mean in the screenshot, where metric name and value are so close together on mobile. I have to be overlooking something simple. But could use help to not waste more time.

<img width="820" alt="screenshot 2016-08-29 17 02 11" src="https://cloud.githubusercontent.com/assets/1950595/18067414/b7d0a60c-6e0a-11e6-81f9-5dddbea3a407.png">

<img width="402" alt="screenshot 2016-08-29 17 03 09" src="https://cloud.githubusercontent.com/assets/1950595/18067420/bd87f9f6-6e0a-11e6-8482-3437e21b1abf.png">

**Comment by bergquist** [comment]
@bulletfactory did the fix help you? or do you want me to take another look at it?

**Comment by bulletfactory** [comment]
I think it's ready to go. The only thing that I'm struggling with is the
table width on mobile wasn't respecting the width values. It's super close,
but if you could take a look, that would be great!

**Comment by bergquist** [comment]
@bulletfactory Great! If thats the only thing missing I can take over from here :)

**Comment by bergquist** [comment]
Aaaand its gone!

https://www.youtube.com/watch?v=DNLob2E_Q5s

**Comment by bulletfactory** [comment]
nice!
