### ISSUE TITLE
The first loading page is slow 

### ISSUE THREAD

**Issue by vijaybiradar** [grafana/grafana#58505]
We are using quay.io/prometheus/prometheus:v2.39.1 

first time when we  open the grafana page, the loading time will be long, Is there an optimization solution? Thank you

![image](https://user-images.githubusercontent.com/38376802/200796717-79408817-0b5a-45aa-81bb-17263927420f.png)
![image](https://user-images.githubusercontent.com/38376802/200796969-93c574c1-87cc-4a21-8e2e-4e58200abd4f.png)
![image](https://user-images.githubusercontent.com/38376802/200797086-a82534c9-5908-4343-b683-1b4f31936358.png)

We are getting below error for the first time loading. After 2-3 hits its working fine 

![image](https://user-images.githubusercontent.com/38376802/201276590-79c9a1e7-39a0-446a-b4e0-ac7d74afe5dd.png)

![image](https://user-images.githubusercontent.com/38376802/201276808-f9e3231e-bfee-4371-8670-1bb7d9ef91c7.png)
 

https://github.com/grafana/grafana/issues/58505#tasklist-block-6688b241-3d10-457a-81f7-36681c4badd3

**Comment by usmangt** [comment]
Hi @vijaybiradar,

Thanks for opening this issue.

I am closing this issue here on GitHub, as it does not seems an issue directly with Grafana.

Please create a new post at our [community forums](https://community.grafana.com/) by providing some details (in case if you missed any) so that our community members can help you out.

**Comment by itsmylife** [comment]
Since it is not related to Prometheus directly I am removing "prometheus" label.
