### ISSUE TITLE
Alert query retry

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#5855]
Failing queries should retry at least x times before its considered firing.

**Comment by bergquist** [comment]
Not sure this is enough or that I can remake those channels.

**Comment by Thib17** [comment]
Hello @bergquist ,
It seems there is no retry anymore (since https://github.com/grafana/grafana/commit/c38f6ff1827d47d8d087ac0a3c177900d38f58d0 ?)
Could you please provide more context why it was removed ? Was it replaced by some other mechanism (that I didn't find), or should we find a solution to re-implement it  ?

**Comment by dudusakharovich** [comment]
@bergquist - Hey,
Is this feature already exists in Beta 5.1.0, because I've installed it on a test machine and I can't find the option to retry.
