### ISSUE TITLE
clicking on transform detail does not add the transformation

### ISSUE THREAD

**Issue by nikoalch** [grafana/grafana#58616]
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/33036213/201213496-2234a799-f52b-4aad-b30a-6ec79e3280b7.png">

@ryantxu todo for more detail

**Comment by zuchka** [comment]
confirmed on main. You can click the title or the larger button element, but clicking on the description doesn't work. The issue is that the descriptions are using `Card.Meta` and not `Card.Description`: https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/components/TransformationsEditor/TransformationsEditor.tsx#L383

![CleanShot 2022-11-14 at 10 22 46](https://user-images.githubusercontent.com/37156449/201758464-f54a2a11-e44b-4e83-8e16-eba8ca1ccb1a.gif)
