### ISSUE TITLE
Unable login grafana in MS Edge

### ISSUE THREAD

**Issue by vijaybiradar** [grafana/grafana#58620]
What happened:
I am unable to login Grafana  in MS Edge on Windows 10 PFB error
Able to login n Grafana  in chrome on Windows 10.

Able to load grafana in Chrome  and I am able to login and see the Welcome to Grafana page. In Microsoft Edge  I get this page: NET::ERR_CERT_AUTHORITY_INVALID

Anything else we need to know?:
Works fine on Chrome.

Is there any known work around?

Chrome 
![image](https://user-images.githubusercontent.com/38376802/201254823-00955570-e287-48fe-adb2-71825d5c2d4d.png)

MS Edge

![image](https://user-images.githubusercontent.com/38376802/201255061-e39c15d7-ed3e-4b22-9c06-d758b564d4bb.png)

**Comment by usmangt** [comment]
Hi @vijaybiradar,

Thanks for opening this issue.

This is not a Grafana issue but more of an SSL cert as different browsers have different settings.

Please check the following links as reference:

https://www.hostinger.com/tutorials/err_cert_authority_invalid#Microsoft_Edge
or
https://answers.microsoft.com/en-us/microsoftedge/forum/all/microsoft-edge-and-google-display/eefb1da7-fcbe-40be-b949-e76ef0daa560

Also, the best place to ask about it is also at our [community forums](https://community.grafana.com/) by providing some details (in case if you missed any) so that our community members can help you out.


I am closing this issue here on GitHub.
