### ISSUE TITLE
Node Graph visualisation doesn't clean edge fields during refresh

### ISSUE THREAD

**Issue by mauriciogeneroso** [grafana/grafana#58672]
**What happened**:
Using a node Graph visualisation, it is not cleaning the edge fields properly during refreshes.
![image](https://user-images.githubusercontent.com/20258509/201394798-e7cbbfd2-904b-4fab-90f3-ee8c0b63eded.png)

**What you expected to happen**:
Clean all the previous data and refresh the Node graph with the up to date data.

**How to reproduce it (as minimally and precisely as possible)**:
1 - Set up the Datasource [nodegraph-api-plugin](https://github.com/hoptical/nodegraph-api-plugin)
2 - Provide the appropriate fields, nodes and edges as required by Node Graph.
3 - Create a dashboard using the `nodegraph-api-plugin` as datasource, and a variable as a static value (this variabled is used to filter data and refresh the graph).
4 - Use the variable to modify the data and refresh the Graph.

----
A sample project to reproduce the issue is available on this repo: https://github.com/mauriciogeneroso/grafana-issue-58672-reproducer

This sample will start up a server and grafana on docker, (all necessary configuration is already done), and it is only required to browse on the dashboard:

![Kapture 2022-11-11 at 17 37 35](https://user-images.githubusercontent.com/20258509/201397578-6f7e34f4-f4e9-497b-aa93-13fb6671260a.gif)

**Environment**:
- Grafana version: 9.1.1
- Data source type & version: hamedkarbasi93-nodegraphapi-datasource 1.0.1
- OS Grafana is installed on: Alpine Linux 3.15 (official docker image grafana/grafana:9.1.1) 
- User OS & Browser: Mac OS 12.6.1 & Google Chrome Version 106.0.5249.119 (Official Build) (x86_64)
- Grafana plugins: node-graph

**Comment by mauricio-sky** [comment]
Hi @connorlindsey, any news on this?

**Comment by connorlindsey** [comment]
Hey @mauricio-sky, I switched teams a couple months ago and am not working on this panel, but this should be on the relevant team's backlog because of the issue labels it is. Just in case, I'll cc @joey-grafana so that he's aware of the bug.

**Comment by joey-grafana** [comment]
Hey thanks for the ping! I'll add this to our board with the needs investigation tag.

**Comment by aocenas** [comment]
There seem to be 2 similar issues in the data you are testing this with which are inevitably about assigning uniq key to React components. When the key isn't unique React then looses track of some of the dom elements and leaves them in the DOM. We use IDs of the edges and nodes to create that unique key.

One is we don't distinguish between nodes and edge keys, so if the IDs are the same as in your data this can create duplication. This can be fixed in Grafana so we add some prefix to keys of nodes and edges respectively.

Another problem is you seem to have duplicated edges id 9 and id 10 in the dataset which will always create this issue. We could probably show some warning somewhere if that happens although it's hard to say if it would be better to filter the out or show them a bit broken like this.

**Comment by mauriciogeneroso** [comment]
Hi @aocenas , the issue was exactly what you mentioned, the IDs were duplicated, I fixed the ids and the issue was resolved. I would recommend as you also did to show warning or something when the data is not as expected. Thank you.

**Comment by aocenas** [comment]
@mauriciogeneroso thanks for the update, created a separate issue for that https://github.com/grafana/grafana/issues/83373 so will be closing this one.
