### ISSUE TITLE
Alerting: need to increase notification timeout for unified alerting

### ISSUE THREAD

**Issue by vsile** [grafana/grafana#58687]
Sometimes we receive 10-15 alerts at a moment.
Since we use grafana-image-renderer to attach panel screenshots we have encountered a timeout error (default 30s)

For **legacy** alerting there is an opportunity to increase notification timeout and evaluation timeout both:
![изображение](https://user-images.githubusercontent.com/9244347/201478114-e688971a-e7da-46e9-b6b1-1b885cf570c3.png)

But for **Unified Alerting** I can't increase notification timeout. There is evaluation timeout configuration only.
![изображение](https://user-images.githubusercontent.com/9244347/201478327-2e979ae6-2862-4f88-bd0e-1431aa7ad3c9.png)

- Grafana version: 9.2.4
- Contact point type: webhook (custom tool to send alert via Telegram)

Please, add an option to increase notification timeout for Unified Alerting

**Comment by grobinson-grafana** [comment]
Hi! :wave:

Screenshots must be taken within 15 seconds or the notification is sent without a screenshot. This isn't configurable at present, but we are planning to make it configurable in the ini file.

In Grafana 9.2.5 we fixed a bug where screenshots were not cached. This meant that two alert rules that fired at the same time would take two screenshots of the same panel, instead of sharing a screenshot. Would it be possible to upgrade to 9.2.5 and see if this helps?

**Comment by grobinson-grafana** [comment]
Hi! I'm not sure I understand the configuration here. Grafana takes a screenshot of the panel before sending the alert to the Alertmanager. Does this mean that you are taking screenshots each time a webhook has been received?

**Comment by grobinson-grafana** [comment]
Hi! :wave: Thanks for the information, I now understand the issue. Is there a reason why you're taking screenshots in your alert receiver rather than using the built-in screenshot feature in Grafana? It too can send screenshots to Telegram and has a number of optimizations such as caching, rate limiting and singleflight.

**Comment by vsile** [comment]
One of reasons why we don't use build-in screenshot feature is to get the correct screenshot from **Dashboards with variables**. We set additional parameters in Summary field (for example, "node=10.10.10.10:9100"). When we get an alert the Custom Notifier composes RenderUrl with additional parameters ("var-node")
http://grafana:3000/render/d-solo/rB9Yarsnk?var-node=10.10.10.10%3A9100&panelId=23
and send request to get an image.

We have found a way to decrease operation time from 40-45 second to 12-15 second through asynchronous request sending. But the increasing of notification timeout could be useful anyway.

**Comment by apollo13** [comment]
Hi @grobinson-grafana,

you said:
> Screenshots must be taken within 15 seconds or the notification is sent without a screenshot. This isn't configurable at present, but we are planning to make it configurable in the ini file.

As far as I can tell the timeout is 10 seconds: https://github.com/grafana/grafana/blob/a958b0be4411555b049159b04ffc18681d271d4e/pkg/services/ngalert/image/service.go#L24

Are we talking about different timeouts here or did you copy the wrong one? I am asking because I am trying to figure out if #59527 is indeed a duplicate or if those are different timeouts…

**Comment by grobinson-grafana** [comment]
Sorry you are right! It is 10 seconds, not 15 seconds! 🙂

**Comment by vsile** [comment]
The issue is about notification timeout when alerts are sending via webhook (default 30 seconds).
https://github.com/grafana/grafana/blob/a958b0be4411555b049159b04ffc18681d271d4e/pkg/services/notifications/webhook.go#L41
