### ISSUE TITLE
error using unix socket connection for postgres metadata database

### ISSUE THREAD

**Issue by robinboening** [grafana/grafana#58690]
**What happened**:
An error is raised when using a postgres instead of the default sqlite database and assigning a unix socket path to `GF_DATABASE_HOST` (e.g. /cloudsql/projectid:region:instance)

```
Failed to start grafana. error: failed to connect to database: invalid host specifier '/cloudsql/xxx:xxx:xxx': net.SplitHostPort failed for '/cloudsql/xxx:xxx:xxx': address /cloudsql/xxx:xxx:xxx: too many colons in address
```

This might not be directly related to grafana but to the pg driver, but since it affects my use of grafana I'd like to raise this here to see if there are workarounds or other options.

**What you expected to happen**:
To not split but accept the string and establish a connection to the database.

**How to reproduce it (as minimally and precisely as possible)**:
Assign a socket path to `GF_DATABASE_HOST` when starting grafana

**Environment**:
- Grafana version: 9.2.4

**Comment by zuchka** [comment]
Thanks for creating this issue, @robinboening 

. Assign a socket path to GF_DATABASE_HOST when starting grafana

can you please provide more detailed reproduction steps? The more specific the better. thx

**Comment by kingsukhoi** [comment]
Hi I'm having the same issue.

Here is a few of the config files I've tried. 
## url field
```ini
[database]
url = postgres:///grafana?host=/cloudsql/development-mycompany:northamerica-northeast2:company-db&user=grafana@development-mycompany.iam&password=apassword&port=5432
```
## split
```ini
[database]
host = /cloudsql/development-mycompany:northamerica-northeast2:company-db
name = grafana
password = apassword
type = postgres
user = dev-grafana@development-mycompany.iam
```

Both of the config files produce the below log:
``` json
{
    "logger": "migrator",
    "t": "2022-12-02T23:53:57.310466474Z",
    "msg": "alert migration failure: could not get migration log",
    "level": "error",
    "error": "failed to check table existence: dial tcp 127.0.0.1:5432: connect: connection refused"
  }
```

I know the unix path works because I ran `pg_isready` as part of a custom entrypoint script, and it said accepting connections.

I also run other go programs on CloudRun and those work.


**Environment**
- Grafana version: 9.3.1

**Comment by kingsukhoi** [comment]
I've also tried symlink-ing the expected directory, and ran into a limitation of CloudRun.

I'm guessing here, but only when you try to create a postgres connection does the folder path exist. It's some magic google does in the background.

**Comment by zuchka** [comment]
@kingsukhoi looks like your PR went stale. is this still an issue?

**Comment by vaisov-gemba** [comment]
I'm facing the same issue when running latest Grafana in Cloud Run. Did you find any workaround for this?

**Comment by feliperc-net** [comment]
I was facing the same issue and had to dig deep into this. But luckily I was able to find a workaround! It turns out, that the configuration file also accepts the setting `connection_string`. This can be seen here:

https://github.com/grafana/grafana/blob/960b0e770b65bd5e961d7ef17f20f94087770a7f/pkg/services/sqlstore/database_config.go#L98

So I just had to include the following two lines under `[database]` in the Grafana configuration file to use this setting:

```
type = postgres
connection_string = user=grafana host=/var/run/postgresql port='5432' dbname=grafana
```

Surprisingly the `connection_string` setting doesn't seem to be documented anywhere! (at least I was unable to find anything about it in the official documentation).
