### ISSUE TITLE
[Bug] Panel Dashboard shared URL time overriding panel time override 

### ISSUE THREAD

**Issue by digrich** [grafana/grafana#5872]
Please include this information:
- What Grafana version are you using? 
       v3.1.1
- What datasource are you using? 
      OpenTSDB 2.2
- What OS are you running grafana on? 
      Linux
- What did you do? 
      Overridden the time on Panel and shared the dashboard/panel URL with current dashboard time range.
- What was the expected result?
      Graph panel should consider the overridden time from 'Time Range' section. 
- What happened instead?
      Graph panel is taking the time range from shared URL.

**Comment by torkelo** [comment]
This is not a bug, the time range from time range section is only taking effect when the dashboard time range is relative. You should be able to zoom in on a panel with relative time override (which will set absolute time range for dashboard time, and the panel relative time range will not take effect). 

If the dashboard time is "Last 1 days", (ie relative), and you try to share a panel with relative time override (say last 1h), then you need to uncheck the "current time range", otherwise the dashboard time range will be turned into an absolute time range and panel relative time range will not take affect. So basically when sharing a panel with relative time override uncheck current time range checkbox if you want the panel to be shared with its overriden time range.

**Comment by mtanda** [comment]
@torkelo @bergquist 
I really surprised because you labeled this issue as "help wanted" and now you say "this is not a bug". (It is inconsistent!)
So you should check the issue carefully before using "help wanted" label.

Anyway, I feel current behavior is really strange, and think the current behavior loses some of good point of "relative time range override" feature.
So, you are only one who know the REAL specification of Grafana (maybe bergquist didn't know the spec, so he think this is a bug), you have a responsibility for explaining the reason why you think the current behavior is better.

**Comment by torkelo** [comment]
Yes, you are right, I am really sorry for that. I made a mistake. 

I thought this was a bug when I looked at it first, and depending on how you look at it it still might be. I think there is no right way, it just depends on how you look at it. 

Problem 1:
1) What should happen when you zoom in on a panel with **relative time** override? Should it only zoom in on that panel and keep dashboard time intact? That is not supported right now as panel override is only relative to dashboard time, and only if dashboard time is relative. 

I think being able to zoom in is an important feature so whenever you zoom in on a panel with relative time override you zoom in to the region you selected. I think this is the expected behavior. That is when you zoom in you loose the relative override. The bad side effect is that if you zoom in on any panel on a dashboard with relative time overriden panels the relative time override will not take effect (because dashboard time is no longer relative). 

Problem 2: 
Sharing a panel with relative time override. Sharing a panel with current time range checkbox checked sets the time range url params in absolute epochs, even if the time range is relative. This is in order to get a url that will capture the visible region if it is viewed a day later. This fact that "current time range" turns a relative time into an absolute time is what is causing this issue. which makes it tricky if you want to share a pane with relative time override, do you want to share it with "current time range" (ie dashboard time), or the relative time override? The "current time range" option is not very intuitive in this case. I think it should share it with the current visible time range. So in that sense I still think this issue is a bug (but I do not think your PR solved it, it made the issue worse by making it impossible to zoom in). 

I am not sure what the best way to solve these issues are :( 

@bergquist thoughts?

**Comment by mtanda** [comment]
Thanks for explanation. 🤝 
I understand you face a dilemma.

> The bad side effect is that if you zoom in on any panel on a dashboard with relative time overriden panels the relative time override will not take effect (because dashboard time is no longer relative).

Personally, I want to change the behavior, because I want to check long time trend and some load spike in short time range.
If Grafana can have "panel local time range" or other option, it can solve, but it cause more complexity.
I know you don't want it, I don't request such feature now.

> The "current time range" option is not very intuitive in this case. I think it should share it with the current visible time range.

I may understand what you think.
I think the opening "shared panel" should display same graph output what user share it.

So, I hope there is a good compromise plan for this issue.
