### ISSUE TITLE
Timeseries panels hang in timeAxisSplits infinite loop with certain TZ settings 

### ISSUE THREAD

**Issue by michael-sayapin** [grafana/grafana#58728]
**What happened**:

I am in Bangkok, the rest of the team is in Shanghai. Default time zone is set to Asia/Shanghai. If I set my user time zone to Asia/Shanghai, timeseries panels hang in `while (1)` loop in `timeAxisSplits` method of `uplot.esm.js`. If I switch to "browser time zone", it works.

**What you expected to happen**:

No hanging.

**How to reproduce it (as minimally and precisely as possible)**:

While in TZ A, set Grafana to TZ B, and set user TZ to B.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.4
- Data source type & version: Postgres
- OS Grafana is installed on: Debian
- User OS & Browser: Arch + Chrome 107

**Comment by zuchka** [comment]
Thanks for creating this issue, @michael-sayapin 

> While in TZ A, set Grafana to TZ B, and set user TZ to B.

can you please provide more specific details for reproduction? Are you setting [local timezone in config](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#default_timezone)? Are you setting [`use browser locale?`](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#use_browser_locale)? Anything else. More details on what you mean when you say "set Grafana" and "set user" would be ideal here. thx

**Comment by michael-sayapin** [comment]
Hi @zuchka 

I've been able to reproduce it by setting Time zone to Asia/Shanghai in https://grafana.example.com/org and setting Time zone to Asia/Shanghai as well in https://grafana.example.com/profile, while my browser time zone is Asia/Bangkok.

**Comment by zuchka** [comment]
thanks for this @michael-sayapin 

still no joy for me. I set org to Shanghai and profile to Shanghai and Chrome Version 107.0.5304.110 (Official Build) (arm64) to Asia/Bangkok. No issues loading a time series from a live datasource.

I tested on main [v9.4.0-pre (e157ef1171)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md). perhaps its the linux distro or perhaps I'm missing something...

**Comment by leeoniya** [comment]
@michael-sayapin i actually think i ran into this recently (i'm also on Arch, Chromium 107.0.5304.121).

i Arch's Chromium build is wonky and doesnt properly parse date strings. when i tried the same with Chrome instead of Chromium it worked as expected, here is the misbehavior that you can check in DevTools consoles (left is Chromium, right is Chrome):

![image](https://user-images.githubusercontent.com/43234/204962803-64eb1543-85aa-4f96-99c0-e4d3a782c275.png)

i wanted to open an issue with the Chromium maintainers but was not sure if this was specific to the distro/platform or to all Chromium builds on all platforms. if you can confirm on your side, we can try opening a bug in https://bugs.chromium.org/p/chromium/issues/list and see what they tell us.

this issue also crashes my Chromium but not Chrome here: https://leeoniya.github.io/uPlot/demos/timezones-dst.html

**Comment by michael-sayapin** [comment]
You are right @leeoniya , I get the same "invalid date" behavior on Chromium 107.0.5304.121 (Official Build) Arch Linux (64-bit). Firefox works. I'll close the issue here then and let's take it to Chromium.

**Comment by leeoniya** [comment]
reported here: https://bugs.archlinux.org/task/76773

let's see where this goes.
