### ISSUE TITLE
Unable to forward authentication cookie to InfluxDB V2 (Flux)

### ISSUE THREAD

**Issue by rul-hydro** [grafana/grafana#58759]
I am running InfluxDB V2 behind a reverse proxy secured with Apache mod_auth_openidc. Grafana is using the same authentication path, so the session used for Grafana can also unlock InfluxDB.
When configuring the datasource in Grafana, I tried the options "Forward OAuth Identity" as well as "Allowed cookies" in order to pass the authentication session to the datasource.
However, the Apache access log shows that the cookie and the auth session were not forwarded to InfluxDB. Running the same reverse proxy with authentication disabled will connect to InfluxDB as expected.

I suspect that cookie and session forwarding are not actually implemented in the Grafana Flux datasource.

**Environment**:
- Grafana version: 9.2.4
- Data source type & version: InfluxDB/Flux (builtin)
- OS Grafana is installed on: Debian 10
- User OS & Browser: Windows 11 / Chrome
- Grafana plugins: None
- Others: InfluxDB 2.1.1 / Apache 2.4.38 / mod-auth-openidc 2.3.10.2

**Comment by mellieA** [comment]
@rul-hydro the authentication options are slightly different for flux, did you see the docs [here](https://grafana.com/docs/grafana/latest/datasources/influxdb/influxdb-flux/#flux-query-language-in-grafana)



Token | The authentication token used for Flux queries. With Influx 2.0, use the influx authentication token to function. For influx 1.8, the token is username:password.
-- | --


Token	The authentication token used for Flux queries. With Influx 2.0, use the [influx authentication token to function](https://v2.docs.influxdata.com/v2.0/security/tokens/create-token/). For influx 1.8, the token is username:password.

I'll close this for now since it looks like that should resolve it. But if you think this is a bug, feel free to reopen.

**Comment by rul-hydro** [comment]
I agree that Influx's standard authentication method works as intended. However, I'm trying to use OpenID Connect, because the default authentication method is not sufficient for my requirements. The options "Forward OAuth Identity" and "Allowed cookies" suggest that this should be possible, but the auth cookie is not forwarded as expected.

**Comment by rul-hydro** [comment]
@mellieA I tried again and verified that my setup _would_ work if Grafana forwarded the "Allowed cookies" to the datasource. If I add my authentication cookie to the "Custom HTTP Headers" field, it will show up in the access log and enable protected access to the datasource. Of course, this is not feasible in reality, as the cookie value will be different for each request.

So, here is the setup for reproducing the issue:
- InfluxDB running behind a reverse proxy that will pass the necessary token if provided with the correct authentication cookie (in my case, the proxy is using apache mod_auth_openidc, but any other cookie auth will do)
- Add the name of the auth cookie to "Allowed cookies", datasource will fail with error 401. Apache access log shows that the call did not include the cookie
- Add the auth cookie to "Custom HTTP Headers" as Header: "Cookie" and Value: "CookieName=CookieValue", datasource will work as intended. Apache access log shows the expected cookie

So, what I need is that the Flux datasource forwards cookies as the field in the settings suggests it should.
