### ISSUE TITLE
Navigation IA: Combine the Org and Server Admin Users pages

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#58828]
#58211 will reorganize the Admin section. As part of that effort, we would like to combine the current /admin/users and /org/users pages into a single page/section.

Users who can see both /admin/users and /org/users should see the toggle, and /admin/users should be selected by default. Users who can see only one or the other should not see the toggle at all.

This change should sit behind the `topnav` feature toggle, so that it is enabled along with the rest of the nav updates.

<img width="2448" alt="Screenshot 2022-11-10 at 16 48 18" src="https://user-images.githubusercontent.com/3848559/202197058-010ff436-fde9-4f42-9649-04d63b9abeb4.png">

- [ ] TODO: @VesnaDean and @Clarity-89 meet to discuss feasibility of combining the pages using a toggle as shown in the image above.
- [ ] Make sure that the docs team is aware of these changes.

**Comment by mjseaman** [comment]
FYI @zsofiakomaromigrafana and @ashharrison90

**Comment by lukasztyrala** [comment]
@mjseaman + @VesnaDean – there is one use case to consider if we present `/admin/users` (_All organisations_ users) by default:

* `/admin/users` table has no links to user detail (people cannot click on a user row to see the user detail view page)
* this can be a problem for current users with server admin roles because:
  - their all orgs user list will have moved to a new location (there will be no Server Admin app/section),
  - when they navigate to the user list to manage org roles, they might overlook the group switcher,
  - if they try to click on users, nothing will happen (no drill-down for this list),
  - with frustration clicking in, their cognitive capabilities will lower, and it is furthermore probable they will miss the switcher.
* potentially, this is more disrupting than having `/org/users` (_This organisation_ users) – this one provides links to the user detail view page.

A potential solutions to this are:
* make the user row clickable and take people to the user's detail view page (the question is, should the server admin see the detail view page of a user with information related to all orgs or just the current org?),
* add a tooltip explaining that there is a _current_ org user list as well (well, a better message than this one, ofc).

WDYT?

**Comment by VesnaDean** [comment]
It's actually the other way around – server admin sees the detail page for each user and the org admin doesn't. If a server admin lands on the new unified page, they should by default see all users across all orgs and be able to drill down.
