### ISSUE TITLE
Plugins: fully convert to kind system

### ISSUE THREAD

**Issue by sdboyer** [grafana/grafana#59001]
With the addition of the kind system (#56492), a number of follow-ups are necessary to bring Grafana's plugin system fully into alignment. Some is refactoring existing code. Some is making clear design decisions that lacked necessary foundation before the kind system.

https://github.com/grafana/grafana/issues/59001#tasklist-block-7948d6fe-49c0-4fe4-975b-3c13d3f66822

**Comment by sdboyer** [comment]
i don't expect the draft issue titles to be fully self-explanatory, but they're a start - we can iteratively turn them into full issues.

**Comment by sdboyer** [comment]
Talked a bit with @marefr yesterday, and there's some reasonable questions about where responsibility sits for getting all this done.

Getting these things settled is fairly pressing from an as-code perspective - probably something we should sync on and make a plan.

**Comment by marefr** [comment]
> Decide whether composable kinds a plugin may declare are limited by plugin's type

@marefr, @mckn, @wbrowne, @xnyo conclusion:
- Do not make the plugininstance schema strict, rather we can validate things when Grafana loads the plugin. This will allow a plugin author to define any composable kind, but Grafana would decide what schema to register/use when loading the plugin or it just doesn't care.
- At least this makes sense for now, since each plugin have a type
- Later we might be able to use capability/slot relation to enforce stricter validation of the schema

@sdboyer any objections/questions?

**Comment by sdboyer** [comment]
nope! that sounds good to me. we'll start making progress on these ASAP

**Comment by sdboyer** [comment]
https://github.com/grafana/grafana/pull/61069 is the last pre-req PR before i can put up a PR that will address all of my items in the list.

this

> Decide on a relation between a plugin's id and the namespace of its composable and custom kinds

is gonna be interesting in that PR, because i have to make a decision about it. i think it'll be easiest for us to discuss in the context of the implementation

**Comment by sdboyer** [comment]
#61192 will finish out the as-code team's parts of the TODO list here.
