### ISSUE TITLE
e.index.Of is not a function 

### ISSUE THREAD

**Issue by github-ps1304** [grafana/grafana#59003]
**After adding several metrics to the canvas panel (panel was was displayed correct)  - t some point in time I received a blank screen with the following error message:

![canvas-error01](https://user-images.githubusercontent.com/79707394/202906676-e0ee6d4b-3b4b-430f-b64c-51bfd521fffb.gif)

Attached my json file:
[Canvas-json.txt](https://github.com/grafana/grafana/files/10049872/Canvas-json.txt)

What happened**:
** blank screen with error message
What should have happened**:
**Canvas panel should display my metrics**:

**How to reproduce it (as minimally and precisely as possible)**:
not sure right now - happened 2 times now

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.5
- Data source type & version: InfluxDB 1.8.10
- OS Grafana is installed on: Ubuntu Server
- User OS & Browser: MAc OS Ventura - Safari
- Grafana plugins: Canvas
- Others:

**Comment by github-ps1304** [comment]
Update: Panel started working after several hours within any change made !!!

**Comment by mellieA** [comment]
@github-ps1304 the file attached doesn't look like panel json. I found an old issue where there was json in the panel that was unexpected and produced the same error. Since it's not reproducible anymore it's hard to say exactly what happened. 

If you see this again, please reopen this issue and include the dashboard or panel json using the **Query Inspector** or **Share > Export >  View JSON** buttons. 

![Screen Shot 2022-11-21 at 3 46 20 PM](https://user-images.githubusercontent.com/18175287/203173288-7a41193f-a8cd-4cf1-b12d-ebc95ec9f2b5.png)
