### ISSUE TITLE
Bug: Graphs created by repetition rules are set to be editable

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#5901]
@bergquist As per promcon :)

Reproduce:
1. Set any graph to repeat on a template
2. Edit any of the non-first graphs and save those changes
3. Disable repetition

Now all your edits are gone.

**Comment by bergquist** [comment]
I can think of two solutions for this problem.
* always link to the first panel for the edit button.
* disable the edit button for the second+ panels

**Comment by RichiH** [comment]
If you do the former, please rename the action to "edit repeated graph" or something; else, you would break the principle of least surprise.

If you do the second, please don't disable it, but use "[show source](https://github.com/grafana/grafana/issues/5902)", instead.

**Comment by RichiH** [comment]
PS: After some thinking, I think I personally prefer the former.

**Comment by AvnerCohen** [comment]
@RichiH @torkelo 
1. By now (v7.1) this seems to be implemented, e.g. it's no longer possible to edit repeated panels.
2. The resulting UI is very confusing, there is no way to know who is the "origin" graph and as a result, from user point of view, there is a random graph that can be edited, while others can't be edited.

Can anyone maybe point me to the relevant changelog for this change?

**Comment by torkelo** [comment]
The first is always the editable source panel

**Comment by AvnerCohen** [comment]
Not sure what "first" is, is it first in the row?
You can see in the screenshot, it's actually the second one (dragged it) and this caused also the first one to have "edit" option.
Also, since there is no indication on "repeated panel" type, even if it were always the first one, it would still be confusing because it's pretty common to work on multiple dashboards, some using repeated panels and some don't.
![image](https://user-images.githubusercontent.com/1297254/90386504-5805b100-e08d-11ea-997d-d1d975cddb13.png)

**Comment by torkelo** [comment]
Maybe a repeat icon and number next to title could help

**Comment by AvnerCohen** [comment]
This could be helpful, a repeate icon + maybe a "source" and "replicas" icon or just "source", not sure number is helpful, since 2-3-4 are all the same in that sense.
Another option is to have the "edit" in the non-source graphs have a different text and have it always open the "source".
Or add a "lock" icon of some sort.

so many options :) I guess it's about what would be easiest path.
