### ISSUE TITLE
[Elasticsearch]: Support template variables in filters bucket aggregation

### ISSUE THREAD

**Issue by tonyC2016** [grafana/grafana#5909]
i use the nightly version about grafana-4.0.0-1471946435pre1.x86_64, i new add some tempalte Variables it worked well ,but i use the Variables at filter,it not work ,i use like as below:
![image](https://cloud.githubusercontent.com/assets/18416187/18002551/1a892690-6bbb-11e6-9fcb-f29b9dd95bf2.png)
![image](https://cloud.githubusercontent.com/assets/18416187/18002556/26f7a104-6bbb-11e6-9faa-1d3ef461203b.png)

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
