### ISSUE TITLE
Incorrect canvas css height causing blurry heatmap panels

### ISSUE THREAD

**Issue by KeeganOP** [grafana/grafana#59205]
**What happened**: Blurry Heatmap panel

**What you expected to happen**: Crisp looking graph

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new dashboard
2. Add a Time Series panel (Random Walk)
3. Add a Heatmap panel (Random Walk)
Looking at the differences between the Time Series and Heatmap, Heatmap is blurry where Time series is not (specifically the XY Axes text):
![image](https://user-images.githubusercontent.com/87812012/203532283-c8e3450b-1a12-4aea-b56b-1756e17f7571.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.4
- Data source type & version: Random Walk
- OS Grafana is installed on: Official grafana docker container on k8s
- User OS & Browser: Windows. Firefox. (Chrome seems fine)
- Grafana plugins: None
- Others: Direction from https://github.com/grafana/grafana/issues/10220 
    - window.devicePixelRatio = 1 
    - Using inspect element and removing all of the float px values for that panel clears it up (Not for the "A-series" text though only for the x axes time ):
 
![image](https://user-images.githubusercontent.com/87812012/203535165-8d31f79d-181d-4f1d-b039-3f22c9bd6c60.png)

**Comment by leeoniya** [comment]
this one was...interesting.

- the legend in the Heatmap panel is ColorScale, which is set to `font-size: 11px`
- with devicePixelRatio: 1, we get a global style `line-height: 1.5`

these multiplied cause the height to be 16.5px, which makes the legend height have a 0.5-pixel size, and the viz container to also have a 0.5-pixel size since it takes up the rest of the height of the panel.

https://github.com/grafana/grafana/pull/59260 should fix this, hopefully.
