### ISSUE TITLE
Bug: Grafana won't load if help is disabled

### ISSUE THREAD

**Issue by gldraphael** [grafana/grafana#59302]
**What happened**:

![image](https://user-images.githubusercontent.com/10794213/203802854-ed070b3d-2831-4b85-850e-3af60042209d.png)

**What you expected to happen**: Grafana to work

**How to reproduce it (as minimally and precisely as possible)**:

Create a helm release with the following in `values.yaml`:

```yaml
    grafana.ini:
      help:
        enabled: false
```

**Anything else we need to know?**   
[Link to relevant documentation](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#help)

**Environment**:
- Grafana version: 9.2.5 (docker image tag)
- Helm chart version: 6.44.8

**Comment by usmangt** [comment]
Hi @gldraphael,

Thanks for opening this issue.

Yes, it seems a bug as was also easily reproducible on my local machine where grafana was installed. 

Once restarted the server after config changes, It did not appear as if I was still logged in but when I logout and just go back to the login page, the same screen appear as you shared.

I will report it to our Engineers so that they can have a look.

**Comment by joshhunt** [comment]
This was fixed in this PR, but unfortunately it was not backported to 9.2.x https://github.com/grafana/grafana/pull/58919

 I'll try and backport it if we do one last 9.2.x release, but otherwise this is fixed in 9.3.0
