### ISSUE TITLE
Adhoc filter works, but without filter lense icons in table plugin

### ISSUE THREAD

**Issue by HolgerHees** [grafana/grafana#59327]
I was using AdHoc filters in combination with a prometheus datasource. Everything was working fine. Including the lense icon inside the tables plugins. 

![lense](https://user-images.githubusercontent.com/5681988/203920746-c53983b4-889d-41e8-bec2-95d0a6798448.png)

But now, I converted everything to InfluxDB 2 using InfluxQL (not flux).

AdHoc filters still works, but without the lense icons inside the table plugins.

![grafik](https://user-images.githubusercontent.com/5681988/203920573-9c3e58fa-ce84-4733-af7c-9099efbd117d.png)

I was using it a lot, because it gives a very easy way for filtering without searching for the right tag or value.

I know, there is the possibility to enable filtering in each table, but this is not applied globally like the adhoc filters.

**Environment**:
- Grafana version: 9.2.6
- Data source type & version: InfluxQL
- OS Grafana is installed on: Grafana container
- User OS & Browser: Linux & Firefox

**Comment by zuchka** [comment]
Thanks for creating this issue, @HolgerHees 

can confirm this using main and a Flux datasource. Also confirmed on play.grafana.org that the lens icons appear on [Elasticsearch](https://play.grafana.org/d/PSA7M667k/elasticsearch-8-2-0-sample-ecommerce-orders?orgId=1) and [Loki](https://play.grafana.org/d/T512JVH7z/loki-nginx-service-mesh-json-version?orgId=1) dashboards.

I believe the issue is somewhere around here:

[Those icons only appear](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Table/CellActions.tsx#L63-L68) when `showFilters` returns `true`

[`showFilters` is only true when](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Table/CellActions.tsx#L25-L26) `field.config.filterable = true`, which is set during the dataframe construction inside each datasource plugin. I can see references to `filterable` in various ds plugins like elastic, loki, tempo, but not in influx.

I'm also a bit confused here because there is a property inside panel JSONs called `filterable`, but that seems to refer to the column-filtering feature. maybe a naming collision here?

**Comment by HolgerHees** [comment]
I've now found a workaround. After playing around with "Add field override" a bit, I came across "Standard options - Ad-hoc filterable" which enables exactly this behavior. You just have to activate it manually for each column in all tables.
