### ISSUE TITLE
TraceView: Represent OTLP Span Intrinsics correctly

### ISSUE THREAD

**Issue by joe-elliott** [grafana/grafana#59607]
**What happened**:
Currently when rendering traces from Tempo, Grafana pushes certain "intrinsic" properties on a span into attributes (or ignores them entirely). There are quite a few intrinsic properties to a span that should be considered when rendering OTLP spans, but this issue will only specifically call out two of them. Please review the [data model](https://github.com/open-telemetry/opentelemetry-proto/tree/main/opentelemetry/proto/trace/v1) for full details.

[**Status**](https://github.com/open-telemetry/opentelemetry-proto/blob/d8729d40f629dba12694b44c4c32c1eab109b00a/opentelemetry/proto/trace/v1/trace.proto#L255)

Currently when rendering a span with a status of error Grafana creates an "error" attribute with the value `true`. This should instead be displayed somehow as part of the span.
![image](https://user-images.githubusercontent.com/2272392/204901980-e11e8e2d-e5cb-4e03-91d0-2c55b14874a9.png)

[**Kind**](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto#L156)

Currently when rendering a span with the kind set Grafana creates a "span.kind" attribute with a string value. This should also be displayed as an intrinsic element of the span instead of as an attribute.

![image](https://user-images.githubusercontent.com/2272392/204902639-54baae27-af7d-4440-b6ac-74fcce679617.png)

**What you expected to happen**:
These properties are intrinsic to the span should not be rendered as attributes.

**How to reproduce it (as minimally and precisely as possible)**:
Render a trace with any of the above properties.

**Additional Context**:
Tempo uses the OTLP object model natively and currently the Grafana UI doesn't display represent that faithfully. This will be increasingly important as TraceQL rolls out. The language distinguishes between dynamic attributes and intrinsic properties of the span and we would like the Grafana view to be consistent with the object model and query language.

**Comment by aocenas** [comment]
@joe-elliott at this point these tags already affect some visuals.

`error = true` adds an error icon to the span:
![Screenshot from 2022-12-01 11-22-24](https://user-images.githubusercontent.com/1014802/205041316-c1c057b1-38ef-4b6d-97d8-b9d6a6ea371e.png)

`span.kind = client` + `span.kind = server` create a relationship which looks like this if the span and it's children are collapsed:
![Screenshot from 2022-12-01 12-27-23](https://user-images.githubusercontent.com/1014802/205041612-783ca766-1cab-45e0-9e9d-c98b41dda59e.png)

Do you think it makes sense to have both represented as some sort of icon so it is visible in span row without having to expand it? Otherwise the textual part of the span has limited space due to the indentation:
![Screenshot from 2022-12-01 12-34-15](https://user-images.githubusercontent.com/1014802/205042799-074a1af4-796a-44a4-8478-d2824de41718.png)

In expanded details it would be easy to add it as text to this section in the expanded details:
![Screenshot from 2022-12-01 12-35-01](https://user-images.githubusercontent.com/1014802/205042947-82079d0e-92e1-4329-88fa-d6dac8d9f203.png)
But that needs expanding the span detail section making it a bit more hidden.

**Comment by joe-elliott** [comment]
The issue is primarily that those attributes don't really exist but the Grafana traceview is displaying them as if they do.

If you search Tempo for `{ .error = true }` it won't find that span b/c there isn't actually an attribute `error` with the value `true`. To find that span you have to search for `{ status = error }`. We need to remove those attributes in order to faithfully represent the data and not confuse our users.

**Comment by aocenas** [comment]
@joe-elliott the problem is that we started of the trace view with the jaeger data model. This means on the front end error actually is a tag. We basically convert the otlp format to a jaeger one at this point. So we can show them differently case by case at this point if it makes sense, or we can try to refactor to internally use otlp but that will need much more work. I think the using otlp format makes sense as it will probably eventually be more familiar even for people using jaeger or zipkin but for now we will probably try to do some quick fixes for this.

**Comment by joe-elliott** [comment]
Oh, one other note. The field `status.code` is also a "fake" field generated from the OTLP status field. So it should be removed along with the `error=true` field. Thanks!

**Comment by 09jvilla** [comment]
@joe-elliott Taking a read through this issue since you flagged it in our [other thread](https://raintank-corp.slack.com/archives/C01UMS158LF/p1675451457937589?thread_ts=1675441588.015619&cid=C01UMS158LF). 

In terms of the proposed short term solution (given some of the complexities that @aocenas pointed out), am I right that it is:

- `span.kind` and `status.code` and `error` no longer show up under "Attributes"


But now what do you want to show up in the upper right corner? is it this? 
- Status: <string> where string="error", "ok" unset", etc?
-Span Kind: <string> where string=["unspecified", "server", "client", etc. ](https://github.com/open-telemetry/opentelemetry-proto/blob/2bdeb79c7646d205c3e05322789afe30cb9ebaa8/opentelemetry/proto/trace/v1/trace.proto#L121)


<img width="1278" alt="Screenshot 2023-02-03 at 4 22 16 PM" src="https://user-images.githubusercontent.com/9610816/216715358-f3af16a4-fa0e-4473-b86d-725b6a23a269.png">



I guess what's kind of funny for me with the `span.kind` case is that if the way you search for is it really just `span.kind`, it feels like you could just list `kind` under the "Attributes" section, and then the user could search for it in traceQL like they could any other custom attribute, namely by prepending the span scope and searching for { `span.kind` }.

In the future, if there are enough intrinsics, could be neat to give them their own section in addition to the attributes and resources sections. And/or help create a better connection between these fields in the upper right corner and the way you would write them for querying in a TraceQL query. Though maybe that bit is solved by a more visual query building experience someday...

**Comment by joe-elliott** [comment]
> But now what do you want to show up in the upper right corner? is it this?

I think what you've pictured is a fine solution, but I purposefully didn't suggest anything. I was leaving it up to the expertise of the Grafana devs to layout the new info.

> I guess what's kind of funny for me with the span.kind case is that if the way you search for is it really just span.kind ...

span.kind will likely be searched with just the keyword kind. something like `{ kind = client }`. agree that `span.kind` would be quite confusing.

**Comment by 09jvilla** [comment]
> I think what you've pictured is a fine solution, but I purposefully didn't suggest anything. I was leaving it up to the expertise of the Grafana devs to layout the new info.

I like the sound of that =) 

> span.kind will likely be searched with just the keyword kind. something like { kind = client }.
And ah great.

**Comment by joe-elliott** [comment]
Two other fields that are rendered as attributes but are not:

```
otel.library.name
otel.library.version
```

These values are intrinsic to the scope:

https://github.com/open-telemetry/opentelemetry-proto/blob/7aa439cb0ba78afbd009d83f32fdda6c128e0342/opentelemetry/proto/common/v1/common.proto#L73-L74

Please clean these up as well when correcting the above.

**Comment by cyrille-leclerc** [comment]
@joe-elliott I think that `otel.library.name` and `otel.library.version` have been deprecated in favor of `otel.scope.name` and `otel.scope.version`.

I can't find the detail in the spec but here is the statement in the OTel Java lib
https://github.com/open-telemetry/opentelemetry-java/blob/v1.24.0/semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java#L74

**Comment by joe-elliott** [comment]
Yes, these have been moved from "library" to "scope". The comment mentions `otel.library.*` b/c that is how they are currently rendered in Grafana, but I agree when we find a better way to represent these values we should use the up to date "scope" instead of "library".
