### ISSUE TITLE
TraceView: Showing and understanding large traces

### ISSUE THREAD

**Issue by joe-elliott** [grafana/grafana#59612]
**The problem**:
The value of viewing individual traces in Grafana goes down the larger they are. Even a trace in the hundreds of spans can start to exceed the size that can easily be parsed looking at the current traceview. Loki/Tempo/Mimir can easily make traces in the 10s or 100s of thousands of spans.

A number of ideas have been discussed, but there hasn't been progress in this area. This issue has been created to catalog some of the ideas in the hopes that we can add some value here in the future.

*Critical Path Highlighting*
Often a user of tracing is most interested in the paths that "push" the duration of the trace. By either highlighting, filtering down to, or otherwise indicating the longest paths in the trace we can help a user immediately view the most important parts of a trace.

*Dynamic Span Filtering*
There is modest search functionality available in the current trace view. Perhaps this feature could be used to express conditions by which to filter the traceview. Common ideas might be to only show spans from particular services, namespaces, spans in error or perhaps only the critical path.

*Flamegraph visualization*
If we consider a trace a similar to a stack trace we could render a large trace as a flamegraph. This would provide valuable summary information about the overall shape of the request and where time was spent without individually renderings thousands upon thousands of spans.

cc @slim-bean @cyriltovena

**Comment by aocenas** [comment]
My 2 cents:
### Flamegraph visualization
Just a note: I was confused about how to show a trace in a flamegraph, technically it's not really a flamegraph just sort of looks like it.
Because of the differences (mainly having parallel execution and overlapping children) we would have to change a bit or create a new visualization for this. Even though this makes for a much dense view not sure how much it would help with 10k trace. It may fit fewer pixels but not sure if it would help navigation and search that much.

### Critical Path Highlighting
I assume this may help quite a bit in understanding the trace and showing the important bits, but it seems it may overlap with the `Dynamic Span Filtering`.

### Dynamic Span Filtering
This may be the most interesting one imho while not being too hard to implement. Right now we have a simple search box that highlights matching spans. We could do a more advanced UI with some more controls about how to search, and whether to highlight or filter out spans. Critical path may be filter criteria here.
Interesting idea could be to somehow integrate this with TraceQL or provide similar search language but that would probably add quite a bit of complexity and not sure if that much additional value.

**Comment by joe-elliott** [comment]
Jaeger has added a [flamegraph view](https://github.com/jaegertracing/jaeger-ui/issues/525) so perhaps we could look there for inspiration. This particular view would likely serve primarily as a way to get quickly get summary information from an enormous trace. I'm also not sure how it could help with navigation or search.

Agree with all of the thoughts regarding Critical Path and Dynamic Span filtering.

**Comment by darkleaf** [comment]
up

**Comment by aocenas** [comment]
@joe-elliott I think it makes sense to close this. We have critical path highlighting and span filtering already while trace as flamegraph haw it's own set of technical issues which means we will probably go some other way.

**Comment by aocenas** [comment]
@darkleaf sorry this is probably not the outcome you wanted from your comment 😅 but as I mentioned we implemented most parts of this request already.

**Comment by alburthoffman** [comment]
@aocenas could u share how to use flamegraph to show the critical path? we are suffering from big traces as well. I would like to see if it helps.
