### ISSUE TITLE
Axes on timeseries panels can no longer have an interval of 10

### ISSUE THREAD

**Issue by JoelHaslam** [grafana/grafana#59657]
We have run into a problem upgrading to use Grafana v9 (9.0.5 to be exact) where our graphs are failing to render.

When loading, the panel looks like:

![image](https://user-images.githubusercontent.com/63413067/205078432-ed88db4b-5be8-40cb-aec2-6d27c23da732.png)

With the console giving us the following error:

![image](https://user-images.githubusercontent.com/63413067/205078542-26514aba-4bbc-4f98-9511-410e4cd8a7c1.png)

I believe this is caused by the fact that we set the values of `Decimals` on our y-axis to `-1` (as we want only want to show 10/20/30... etc), or at least when I change this to `0` the graph displays as expected.

I don't know if this is an expected behaviour change between grafana 8 vs 9, or a regression, but I'd expect there to still be an option available to present the y-axis like this.

To repro this, create a new panel and set the value of `Standard Options -> Decimals` to `-1`

See below for the difference in graphs due to this change:

![image](https://user-images.githubusercontent.com/63413067/205079363-b3c697f6-11b6-463d-b898-f938bcc0b195.png)

**Environment**:
- Grafana version: 9.0.5
- Data source type & version: Prometheus
- OS Grafana is installed on: CentOS
- User OS & Browser: Edge + Windows 11
- Grafana plugins: None
- Others:

**Comment by leeoniya** [comment]
interesting, i didnt know :) first time this has come up, must not be common. we have special handling for 0 decimals, in the scale ranging logic, so i think we can support this as well.

i guess the scale range logic would be

-1 -> round away from dataMin and dataMax to nearest 10.
-2 -> nearest 100
etc...

this likely wont make it into a release before 9.4, so i would recommend updating to latest 9.3 release today instead of making a bigger jump later.

**Comment by leeoniya** [comment]
took a stab at this and it's actually pretty tricky because we use Decimals for both, raw value formatting (in tick labels, tooltips, and legend). it's not logically possible to have a single setting that controls tick granularity without also reducing the value display in other places to the same reduced magnitudes. e.g. for `decimals: -2`, hovering over a value of 51 and 149 would show 100 in both cases (i think).

hows did it work in the old graph panel?
