### ISSUE TITLE
[Feature Req]: Digest Auth

### ISSUE THREAD

**Issue by Michsh** [grafana/grafana#5977]
Do y work on Digest authentication ? It will be great to have such protection !

**Comment by Michsh** [comment]
TX ;)

**Comment by bergquist** [comment]
Thank you for taking the time to provide feedback to us. 

Due to the number of authentication providers, we cannot integrate with all of them. 

Right now we don't think this idea aligns with the current scope/goal of the Project. I'm closing this issue since we want open issues to reflect the current state of the project. It doesn't mean we never considered it. A closed issue can still get attention from other users and be reopened.
