### ISSUE TITLE
Alerting: Feature Request: Delete alert state history with alert rule

### ISSUE THREAD

**Issue by ulrichSchreiner** [grafana/grafana#59813]
hi,

i used the old alert system where the alerts are stored in a panel. when grafana was upgraded, these alerts where migrated to alert rules. and everything worked as expected.

now i wrote my new alert rules by hand and removed the old from the panel. so i used the API to upload new alerts and delete the old alerts from the panel. and i did this for every alert one after another. i uploaed alert rules as JSON without an ID so i got a new ID.

but now i have an `alert-id` which already existed. so for example i created alert `A`, deleted alert `old-A` and created new alert `B`. but now the new `B` received the alertid of `old-A`. And now when i click on the `Show state history` in the `Alert rules`  for the `B-Rule` i see history entries which are completly wrong for my new `B` alert (these are entry from `old-A` ).

and to make it worse: the state history is missing all new alarming states. it shows only the old states which are from an already deleted alert.

It would be great to delete the state history if i delete an alert.

**Comment by JacobsonMT** [comment]
With the new state history I think it's good idea to cleanup the history on alert deletion.

For the existing state history based on annotations we have [retention configuration](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#max_annotation_age-) so that annotations will be periodically removed. This could be improved to look for orphaned annotations.

**Comment by ryan-grafana** [comment]
@JacobsonMT is this ticket still valid with the new alert state history implementation?
