### ISSUE TITLE
Duration doesn't appear in tooltip for the most recent value in state timeline

### ISSUE THREAD

**Issue by MxMarx** [grafana/grafana#59921]
**What happened**:
When hovering over values in a state timeline visualization, the duration of the most recent value isn't displayed when using a time series.
![grafana](https://user-images.githubusercontent.com/44880075/206047726-aee923ec-602f-4ae1-91b7-253c962eeec2.gif)

**What you expected to happen**:
It would be useful if the duration of the most recent value was displayed.

**How to reproduce it (as minimally and precisely as possible)**:
This panel: [State timeline with time series + thresholds](https://play.grafana.org/d/qD-rVv6Mz/6-state-timeline-and-status-history?orgId=1)

**Environment**:
- Grafana version: 9.27

**Comment by leeoniya** [comment]
the durations in state timeline are computed from reading the start of the next state. since we do not have future states outside the query range there's no way to tell you how long that state lasted, it could be an hour or a year.

i guess if your query time range ends with "now" we can say something like "10m30s _so far_ until the prior data refresh 5mins ago". but then if you ever zoom to an explicit time range in the past, you're back to not having the full duration known of the last state that's partially in view.
