### ISSUE TITLE
Prometheus: duplicate header X-ID-Token and X-Id-Token with oauth

### ISSUE THREAD

**Issue by PG2000** [grafana/grafana#59940]
**What happened**:
If i use the "Forward OAuth Identity" on a prometheus datasource then the header X-ID-Token and X-Id-Token are both sent.
Proxies are concatenating this values (with a comma) to a single header ([as stated in the RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
)) and the value of both headers and making them useless if jwt_authentication relies on it.

**What you expected to happen**:
Just have a single header X-ID-Token or X-Id-Token and not both.

**How to reproduce it (as minimally and precisely as possible)**:

I have installed a mitmproxy as a sidecar in kubernetes with [kubectl-tap](https://github.com/soluble-ai/kubetap)
in front of my envoy proxy and cheked the request headers

 

**Anything else we need to know?**:
<img width="1313" alt="Screenshot 2022-12-07 at 11 05 45" src="https://user-images.githubusercontent.com/10741029/206151287-4d0a81b6-b5a5-44e3-8367-1e9d96c50312.png">

I've tested the same with the Loki Datasource and the X-Id-Token Header is set just once

**Environment**:
- Grafana version: 9.3.0
- Data source type & version: Prometheus
- OS Grafana is installed on: k8s
- User OS & Browser: Firefox, MacOS
- Grafana plugins: none
- Others:

**Comment by alexanderzobnin** [comment]
I think this issue is caused by duplication of token header setup. It's set twice in this line

https://github.com/grafana/grafana/blob/47551c742b0ceebbc0d8882130e4c405ae06f137/pkg/services/pluginsintegration/clientmiddleware/oauthtoken_middleware.go#L73-L75

and in this

https://github.com/grafana/grafana/blob/47551c742b0ceebbc0d8882130e4c405ae06f137/pkg/services/pluginsintegration/clientmiddleware/oauthtoken_middleware.go#L91-L93

But then `httpHeaders` processed with `SetHeadersMiddleware` which transform header name to the canonical form:

https://github.com/grafana/grafana/blob/47551c742b0ceebbc0d8882130e4c405ae06f137/pkg/services/pluginsintegration/clientmiddleware/oauthtoken_middleware.go#L95

https://github.com/grafana/grafana/blob/47551c742b0ceebbc0d8882130e4c405ae06f137/pkg/infra/httpclient/httpclientprovider/set_headers_middleware.go#L23-L25

So `X-ID-Token` becames `X-Id-Token` so final request contains both.

CC @marefr
