### ISSUE TITLE
Hackathon: Pages - Component / Button

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#59987]
Add content and images to the button page

**Comment by staton-hyse11** [comment]
Content added but there are rendering issues. @joey-grafana / @JoaoSilvaGrafana can you review and advice or correct?

**Comment by joey-grafana** [comment]
Pushed the changes

- the docs to markdown converter doesn't seem to convert tables to the correct format. It also doesn't format the page nicely.. extra blank lines and poor indentation + it leaves behind a comment in the top of the doc that can be deleted (first image is correct table format)

- images need to start with /img/ so that they are correct when building the website. GitHub can't render the images as it's not a built version



![Image](https://user-images.githubusercontent.com/90795735/206400958-6161797c-a667-4f75-bc26-a0d8ee9c5fd5.png)
![Image](https://user-images.githubusercontent.com/90795735/206400959-5ba275c5-fbb5-42cd-a447-4a492bcfa8da.png)
![Image](https://user-images.githubusercontent.com/90795735/206400983-a5e3b359-76ad-4901-9a09-36eb9c4c1a20.png)
