### ISSUE TITLE
Support for histograms

### ISSUE THREAD

**Issue by jcellary** [grafana/grafana#600]
It would be very useful to have histograms displayed

Example:

![histogram](https://cloud.githubusercontent.com/assets/7473307/3616586/0786b562-0dd5-11e4-9bed-b482615d112d.jpg)

**Comment by cypreess** [comment]
+1 for both

**Comment by fsauer65** [comment]
+ 1, also this would be an aswesome way to visualize a percentiles "histogram": http://hdrhistogram.github.io/HdrHistogram/plotFiles.html

**Comment by gsaray101** [comment]
+1

**Comment by vitillo** [comment]
+1

**Comment by jheusser** [comment]
+1

**Comment by MalteJ** [comment]
+1

**Comment by makapuf** [comment]
+1 !

**Comment by jmorlock** [comment]
+1

**Comment by arthur-flam** [comment]
:+1: it would be great ! :)

**Comment by PaulKuiper** [comment]
+1

**Comment by shankar-piriya** [comment]
+1 Would be a good addition to the excellent platform

**Comment by Dieterbe** [comment]
if you want histograms maybe look at #949 and try to update it so it's in good shape to merge it :)

**Comment by mtanda** [comment]
FYI
I create histogram panel plugin (by forking graph panel code and importing woodsaj PR).
The code is here, https://github.com/mtanda/grafana-panel-plugin-histogram.

**Comment by sischnei** [comment]
How can I try your plugin? Does it need the raintank externalPlugin branch?

**Comment by mtanda** [comment]
I use it by building master branch.

If you don't have build environment, please try latest build at first.
http://grafana.org/download/builds

**Comment by sischnei** [comment]
I tried copying it to grafana-3.0.0-pre1/public/plugins/histogram/ but it doesn't seem to work (no additional entry in the "Add panel" menu).

I'm willing to setup a build environment to get this working - where would I have to copy the files there? Are there any other changes required - changing some config to pick up the new plugin?

**Comment by mtanda** [comment]
Sorry, I prepare README.
https://github.com/mtanda/grafana-panel-plugin-histogram/blob/master/README.md

**Comment by xadhoom** [comment]
I'm testing this with elasticsearch backend (and grafana master as now) but it does not displays any data.

by inspecting the seriesData variable in module.js@159, my query returns this type of data:

```javascript
{"target":"docs",
"type":"docs",
"datapoints":[
{"hour_of_day":0,"Max":255},
{"hour_of_day":1,"Max":227},
{"hour_of_day":2,"Max":222},
{"hour_of_day":3,"Max":232},
{"hour_of_day":4,"Max":342},
{"hour_of_day":5,"Max":474},
{"hour_of_day":6,"Max":641},
{"hour_of_day":7,"Max":1010},
{"hour_of_day":8,"Max":1426},
{"hour_of_day":9,"Max":1551},
{"hour_of_day":10,"Max":1532},
{"hour_of_day":11,"Max":1473},
{"hour_of_day":12,"Max":1656},
{"hour_of_day":13,"Max":1966},
{"hour_of_day":14,"Max":1956},
{"hour_of_day":15,"Max":1493},
{"hour_of_day":16,"Max":1688},
{"hour_of_day":17,"Max":1588},
{"hour_of_day":18,"Max":1521},
{"hour_of_day":19,"Max":1508},
{"hour_of_day":20,"Max":1409},
{"hour_of_day":21,"Max":1283},
{"hour_of_day":22,"Max":689},
{"hour_of_day":23,"Max":373}]
}
```

basically, for any timerange, I'm willing to show the distribution across the 24 hours of he day.
The query itself works ok, I'm just struggling to display it :)

any hint?

Also, it is (or will be) possible to show more than one metric as multiple bars on same point of X-axis ?

**Comment by jtyr** [comment]
@mtanda Please could you create a PR for Grafana to bring your plugin to the mainstream project?

**Comment by xadhoom** [comment]
@jtyr well, instead of integrating that plugin, which is basically a Graph plugin with some little mods, I think it make sense to add the same functions on the graph itself.
In my tests this should be feasible, but I need to find out a way to discriminate between a time serie and a generic serie.

**Comment by Dieterbe** [comment]
@xadhoom what is a generic series?

**Comment by xadhoom** [comment]
well, maybe is not the correct name for it, but basically is a series that does not have a timestamp on x axis, but something different.
For example, max number of connections in the previous month aggregated on the 24 hours and so on.

see also #3164 for a sample screenshot or other ideas.

**Comment by XANi** [comment]
> For example, max number of connections in the previous month aggregated on the 24 hours and so on.

You can already do that using min() and max functions, I do my DC's AC temperature using that :)

Histogram a bit of a complicated problem as there are basically 2 types of histograms: ones aggregated inside DB (like InfluxDB) where you just get pre-bucketed data,  and ones that are generated by Grafana from "raw data".

And heatmap is just "short time period histograms over long time-period" case

**Comment by mtanda** [comment]
@jtyr Sorry for late response.
I hesitate to create a PR. Because, I think @torkelo and @bergquist don't want to merge it.

To integrate histogram panel to graph panel, we need to add "if" statement for graph panel specific code. (I remove such code from histogram panel, https://github.com/mtanda/grafana-panel-plugin-histogram/commit/99ca821fc63ebe05b1cf31b4d40ca40ae6405e84)

I'm not sure, is it possible to integrate these panel plugin elegantly.
Each plugin may have their specific code. The code might be very complicated.

@torkelo If you have opinion about this, please tell me how do you think.

**Comment by bergquist** [comment]
We are not likley to merge new panels into master at this point. 
Merging Histogram and graph panel does not sound appealing right now. Graph panels is the bread and butter of Grafana so we want to keep it as clean and simple as possible.

Our goal is that the new plug-in support will enable people to add the panels they need. 

I'm closing this since we wont add anything to grafana core at this moment.

**Comment by bergquist** [comment]
I guess I didnt have my coffee before closing this. Support for histogram in the graph panel could make it into grafana core. But it cannot increase the complexity of the graph panel to much.

**Comment by xadhoom** [comment]
I've fiddled a bit and this seems possible without changing the graph too much, the only concern I have is that there must be some way to "detect" that the dataset is not a timeseries.
The only solution I have found so far is to add a specific option into display styles. 
Any suggestion is welcome.

**Comment by XANi** [comment]
It seems to me like it could go in 2 directions, either:

Have histogram as separate panel type (which kinda makes sense as it will have vastly different config than normal graph, same with heatmap. Disadvantage is possible code duplication (as 80% of histogram "setup" will probably be reusable for heatmap.

or

Change method of building graphs, spliiting it into query->transform->display parts.

So:

* display part will be just graph type (so X axis could be feed time, or histogram buckets, or whatever is needed) + formatting/color/scales etc
* transform part would be just "map time to X, data to Y" for normal graphs and histogram generation for histograms,
* query part would be basically unchanged.

**Comment by BrannonKing** [comment]
What I want to see for histogram is the ability to specify "bucket size". For example, if I'm showing velocity (in m/s) over time and pick a bucket size of "5 m/s", my X axis should change from time to the individual buckets: 0-5, 5-10, 10-15, etc. My Y axis should change to time quantities rather than time ranges. A bar chart probably looks better than a continuous chart at that point (but not necessarily).

**Comment by jessetan** [comment]
What would be the preferred way to support histograms in Grafana?
The PR in #949 (which @bergquist mentioned may be eligible for inclusion pending merging in master and adding tests) can be ported to the latest version. I've gone so far as to verify it actually works, no tests yet and some minor UI issues. Since there is quite some overlap with the other graph code, this would make sense.
On the other hand, a histogram is a totally different type of graph and can not be mixed with existing graph types (lines, points, bars). So a separate plugin would be more logical then (similar to the piechart plugin). @mtanda already did work on this, but it is not compatible with the plugin API in 3.0

**Comment by XANi** [comment]
IMO the only case where it would make sense to have it in same "type" would be if you could say have "normal" over time data on one layer and histogram on other, to basically have histogram bars as bacground with over-time data in foreground. If that way is not supported it doesn't really make sense to put it in same place.

Especially that over time "histogram plugin" could be expanded to do "histogram over time"/heatmap visualisations

**Comment by jessetan** [comment]
A "histogram over time" / heatmap is possible and would make sense to put in the graph panel, but a "regular" histogram can not be combined with other graph types since the x-axis shows buckets, not time.

**Comment by mtanda** [comment]
Hi, I try to support Grafana 3.0.
I don't test it well, but it seems to work.
https://github.com/mtanda/grafana-panel-plugin-histogram

I extend GraphCtrl class, and add HistogramCtrl. So, some part of code is shared with graph panel.

**Comment by jessetan** [comment]
@mtanda great, this is easier than patching the code myself ;)
I'll file any issues I see to your repo, I don't think it is ready for grafana.net yet. But once it is, I think this issue can be closed.

**Comment by mtanda** [comment]
@jessetan Thanks! I'm waiting for your feedback.

**Comment by hgfischer** [comment]
This issue seems abandoned by the Grafana team.

**Comment by torkelo** [comment]
@hgfischer in what way? not sure we have promised this :)

**Comment by mtanda** [comment]
I'm working on heatmap panel too.
https://github.com/mtanda/grafana-heatmap-epoch-panel
Currently, it doesn't support InfluxDB/Elasticsearch histogram response.

If https://github.com/grafana/grafana/issues/3164 is implemented, the panel becomes more useful.

**Comment by johnou** [comment]
@mtanda would you please attach some sample screenshots of the histogram and heat map plugin panels?

**Comment by mtanda** [comment]
@johnou These are screenshots. I notice there are some bugs in query editor, but other part works well.

Histogram:
![histogram](https://raw.githubusercontent.com/mtanda/grafana-histogram-panel/master/src/images/histogram.png
)

Heatmap:
![heatmap](https://raw.githubusercontent.com/mtanda/grafana-heatmap-epoch-panel/master/src/images/heatmap.png)

**Comment by LuboVarga** [comment]
+1

**Comment by WIZARD-CXY** [comment]
+1

**Comment by cederigo** [comment]
+1

**Comment by cattt84** [comment]
+1

**Comment by GillesBIANNIC** [comment]
+1

**Comment by felixge** [comment]
@mtanda your heatmap plugin looks great. I hope to be able to try it out soon. Also +1 for something similar to be included in grafana core.

**Comment by torkelo** [comment]
histogram support added to main graph panel:

![image](https://cloud.githubusercontent.com/assets/10999/24907260/ba0a4844-1ebb-11e7-9c64-f715bfde0ae4.png)

https://github.com/grafana/grafana/pull/8053

**Comment by Dieterbe** [comment]
Wow so the same old graph panel can now do histograms ? That's even better then a separate panel. Thanks Alex and torkel

**Comment by Jan-Axoom** [comment]
I still have a problem using this new feature. I want to see the distribution of for example the run times of a certain function. For that I connected an elasticsearch source and fill it with the desired data. The thing is that the new function aggregates over the timestamp when the data was written and not, what would be more logical, over the inherit data. With the current state I have to choose an interval for the group by clause, so that no data points are combined. Otherwise the sown distribution is completely misleading.

(I tested min / max / average as metric, all of them are equally bad)
Following pictures involve run times from 100ms to 1000ms with interval set to 1. 100ms (how it should look), 2. 1s and 3. 10s (auto)
![100ms](https://user-images.githubusercontent.com/35104812/34567213-94b2266a-f161-11e7-8f09-8590ca38f94c.PNG)
![1s](https://user-images.githubusercontent.com/35104812/34567217-980dd17e-f161-11e7-9e14-27d8f13ef80b.PNG)
![auto](https://user-images.githubusercontent.com/35104812/34567219-99bdd62c-f161-11e7-8a8a-a1f30aec902d.PNG)

Auto makes no sense here because the inspected time interval (here last 24 hours) can be changed, what will result in a whole other graph as well.

**Comment by alexanderzobnin** [comment]
@Jan-Axoom could you please share your ES query? This mode just transform timeseries data to histogram. More source points make more precise result. But for ES and other datasources supporting histogram aggregation make more sense to use aggregated data like Heatmap panel does (#11087). We think about extracting histogram to the separate panel, so I think it would be a nice feature to have.

**Comment by wmaiouiru** [comment]
@mrdeveloperdude 
Were you able to resolve this? I am trying implement on the same thing except with PostgreSQL database. I am stuck on creating multiple series from the same data source to compare the histogram between different series.

In my research, the query still needs to be time series format for histogram to work.
SELECT
    value,   -- the value that I want histogram where y-axis is the occurrence and x-axis is the bins
    metric,  -- the series
    time
FROM
    db

After you can display your data in a time-series graph, if you change the x-axis mode to histogram, you would be able to view your data in histogram. However, the series is all converted to count which is where I am struggling with.
https://grafana.com/docs/features/panels/graph/
