### ISSUE TITLE
SingleStat: Dynamic Images based on Boolean Query (up/down arrow)

### ISSUE THREAD

**Issue by roscoe57** [grafana/grafana#6001]
- **I'm submitting a ...**
- [ ] Bug report
- [X ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 4.0.0beta
- What datasource are you using? InfluxDb
- What OS are you running grafana on? ubuntu 

I'm using IOT temperature displays for brewing, the scadas or web visualisations for Temperatures, since they are very slow moving have a computed UP-ARROW to indicate temp is rising (its slow)

Anyway of enhancing the SINGLESTAT panel to trigger dynamic characters or images ?

**Comment by torkelo** [comment]
Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.
