### ISSUE TITLE
Tempo: Allow writing custom query for trace to logs option

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#60081]
At this moment users can create log query from a trace only by selecting a specific tag from the trace which will be included in the logs query. Optionally they can also remap the tags' names. These then create a simple key=value list that is used as a query. There is no option to add custom static items to the query or alter it.

For metrics query from trace, we already have an option to create custom query and just interpolate the tags into it:
![Screenshot from 2022-12-09 11-37-12](https://user-images.githubusercontent.com/1014802/206683392-6fabbf94-31b9-4683-ad55-2be20c35cb97.png)

User can insert any text and use `$__tags` variable inside it to interpolate the tags. We may need a bit better control using a template service to be able to insert the values separately if needed with for example `$__tags.key1.value` to allow for better control and align with other variable interpolation in Grafana.

We should have a similar mechanism for the logs query so users can modify it if needed.

**Comment by michaelmoreira** [comment]
It sounds like you are suggesting adding support for customizing log queries from traces in Grafana. Currently, users can only create log queries by selecting a specific tag from the trace, and optionally remapping the tags' names. There is no option to add custom static items to the query or alter it in any way.

One possible solution to this issue is to add support for using a template service to create custom log queries from traces in Grafana. This would allow users to insert any text into the log query and use the $__tags variable to interpolate the tags into it, similar to the existing support for custom metrics queries from traces.

Additionally, the template service could provide better control over variable interpolation by allowing users to insert the values of specific tags separately, using syntax like $__tags.key1.value. This would align with other variable interpolation in Grafana and provide more flexibility for customizing log queries from traces.

Overall, adding support for customizing log queries from traces in Grafana would provide more flexibility and control for users, and align the functionality with the existing support for custom metrics queries from traces.

**Comment by hamishliu** [comment]
![image](https://user-images.githubusercontent.com/79596614/228794637-0974c3ba-9dbd-4195-b2e4-d2f9512e381c.png)
![image](https://user-images.githubusercontent.com/79596614/228794777-e5b1eb75-4f76-45c4-83cf-e028f8e3756e.png)

![image](https://user-images.githubusercontent.com/79596614/228794719-08e0de44-f00c-46f1-afd0-db2343f3b966.png)
