### ISSUE TITLE
feature request: drill down has select option for influxdb query

### ISSUE THREAD

**Issue by bf228** [grafana/grafana#6040]
Maybe I missed how to do this easily but I would like to setup the drill down to show the json content associated with the metric in the grafana panel.  I've been able to manually create an absolute link in the drill down to query influx with the target metric and get back json.  painful.  since grafana already has this URL encoding in order to get the data from influx in the first place, i'm looking for an option on the drill down UI that basically says "check here for existing metric" and it uses that as the absolute link.  When one selects on the panel to do the drill down, one gets a new page which is the json data from influx.

Thanks

**Comment by torkelo** [comment]
I am not sure what your talking about, drilldown panel links?

**Comment by bf228** [comment]
Sure.  Consider some panel where one has defined a query under the metrics tab.  Now suppose one wants to define the drill down URL associated with the panel to show the actual data that was used to create a line in a graph panel (or text in a table).  Basically I want a new browser window to pop-up and show the json data that was used to create the line graph.   To do this we open the general tab.  Under the general tab one would define an absolute link to influx which encodes the already specified query info that's in the metric tab.  Rather than me having to manually translate the metric query into an absolute URL and corresponding URL encoding, and since grafana already can construct this URL, I was hoping for a mechanism on the drill down page where I select a button and the absolute link field gets auto-populated with the URL grafana creates to grab the data specified in the query under the metrics tab.

Is there some alternative automated way to access the URL grafana uses (for a panel) when talking to influx?

**Comment by torkelo** [comment]
you want view the raw json data returned by influxdb? you can open chrome dev tools and look at network tab if you want to view the raw json values returned by influxdb. 

The response from a query is not the same as the raw json you write to influxdb. B

**Comment by jerbrownie** [comment]
This sounds similar to what our management has requested. They want to be able to drill-down into the 'raw' data of the query that produced the chart. (Not http debugging)

I haven't seen any documentation if the db, measurement (table) and conditions (where clause) can be passed as a url param... (If so, then we could use that immediately and no enhancement would be needed). If these can be passed as params, please let me know and you can stop reading here.

The current "drilldown" solution doesn't scale well for us because we have hundreds of unique dashboards with multiple graphs on each. It's not feasible to create a 'drill-in' dashboard for each graph with a table filled with many group by conditions so we can see the source data.

Having this capability natively in Grafana would be a big win, but may not be practical.
(eg. Click 'View raw data' on a graph which opens a new tab and dumps a select * version of the current query and selection into a table on the new page)

Alternatively, we can handle the raw data rending on our end if we had the capability to extract out the db, table, time and where clause from the graph drilldown click. (showing only the selected series would be nice too)

For example, one of our dashboards is sourced from Influx, where we track our github commits:


[Checkbox] Add query source (eg. adds the following to the hyperlink)
&db=githubdb
&epoch=ms
&tbl=commits
&where=cond1 = abc , cond2 = def , etc..

[Checkbox] Add selected series (eg. adds the series that were selected)
&selected=repo = grafana , repo = influxdb , etc...

Another option could be provide this in a single parameter
&db=githubdb&q=SELECT * FROM commits WHERE time > 1440072223s and time < 1474373023s and cond1 = 'abc' and cond2 = 'def' ... etc...

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/1232
