### ISSUE TITLE
95th percentile calculation in Graph's Legend

### ISSUE THREAD

**Issue by felipewd** [grafana/grafana#6053]
Currently, it's only possible to (calculate and) display min/max/total/avg in a given graph's dataset.

It'd be useful to have a 95th percentile also. 99th possibly too.

I have a patch which adds this. This a sort of "we use it and would like to make it public" sort of feature....so, we'd like some feedback from you guys if you think this could be useful to everyone else.

**Comment by torkelo** [comment]
tricky, as most time series queries apply some form of aggregation (avg for example), doing percentiles on aggregated data can be very misleading. This is better done in the metric query.

**Comment by incoquinita** [comment]
Hi @torkelo ,

It's possible to add a 95th percentile to Grafana or Grafana Apps (like Table, Graph, Single Stat Etc)? Because it's a important metric, that we have no way calculate directly in Grafana.

**Comment by torkelo** [comment]
@incoquinita sure you can add it if your data source supports calculating it, Grafana cannot do it, needs to be done in your metric query

**Comment by PrestonTaylor** [comment]
This is quite frustrating to see. If you claim not to be able to calculate percentile due to inaccuracies then you must also concede that you can't accurately calculate median and should remove it from the options.

**Comment by PrestonTaylor** [comment]
If you claim not to be able to calculate percentile due to innacuracies then you must also concede that you cannot calculate max, min and count for the same reasons and should remove them from the options and tell everyone to use their metric.

**Comment by torkelo** [comment]
Max, mean , avg works great and can be accurate, just need to match the aggregation used in the query.

**Comment by vellala2000** [comment]
i don't understand the justification behind turning down this feature. Mean and total also aggregated data why is it only problem for percentile.

most of the time series database supports to calculate percentile, the problem here is that we wont be able to show in the same graph panel where we plotted the time series. creating separate single stats panel might do the job if it is simple dashboard with only one or 2 time series data. however when there are 10-15 time series data with every series has its own graph panel, it will look like a lot clutter and hard to

**Comment by PrestonTaylor** [comment]
> Max, mean , avg works great and can be accurate, just need to match the aggregation used in the query.

I don't understand. Doing a percentile on "aggregated" data is no different from doing other aggregate functions. Values are missing that would be used for min/max/avg just the same as percentile.

**Comment by torkelo** [comment]
@PrestonTaylor you can aggregate your data using min/max/mean  then those legend values will be correct , but you cannot aggregate your values using a percentile

**Comment by AmeanAsad** [comment]
For people reading this issue in the future, this explains why you cannot aggregate percentiles: https://www.circonus.com/2018/11/the-problem-with-percentiles-aggregation-brings-aggravation/

**Comment by wxiaoguang** [comment]
What users need is just to draw a "95th percentile line". It doesn't seem to be evil. And, zabbix has such feature ..... 

Well, I know the the Grafana's low level design is totally different from zabbix, but as an end user, this feature is really useful.

**Comment by PrestonTaylor** [comment]
I have yet to see an argument on how a user wouldn't be able to use percentiles accurately. The only reason so far is that "most time series have aggregation" Well, what if mine doesn't? What if it doesn't matter in my use case? There is nothing inherent about Grafana or any of its' data sources that requires a time series to be aggregated in any way. Users could misuse any one of dozens of statistical analysis tools available in Grafana but you would never consider remove them entirely because of that.

**Comment by thomas-biesmans** [comment]
> For people reading this issue in the future, this explains why you cannot aggregate percentiles: https://www.circonus.com/2018/11/the-problem-with-percentiles-aggregation-brings-aggravation/

For people reading this issue in the future, I believe @AmeanAsad is missing the point with [https://web.archive.org/web/20240205031322/https://www.circonus.com/2018/11/the-problem-with-percentiles-aggregation-brings-aggravation/](https://web.archive.org/web/20240205031322/https://www.circonus.com/2018/11/the-problem-with-percentiles-aggregation-brings-aggravation/) (archived version due to redirect). Turn it around: we want a percentile for the (separate) aggregates, not an aggregate of percentiles.

Compared to that article's metrics: I'm not interested in the average of W1's and W2's 95th percentiles, the article is right in that it would not make much sense. However, what was requested and what I'm looking for as well, is having Grafana show the xth percentile for W1, and the  xth percentile for W2. Both separately in the legend, like Grafana already does for min, max and / or avg. Just another toggle for another calculated value.

> [@PrestonTaylor](https://github.com/PrestonTaylor) you can aggregate your data using min/max/mean then those legend values will be correct , but you cannot aggregate your values using a percentile

Glad to see you @torkelo finally saw the light in [https://github.com/grafana/grafana/pull/46270](https://github.com/grafana/grafana/pull/46270). To be truly honest, both discussions come across as failing to see the points that are being offered because of sheer stubbornness. Having one or multiple percentiles for a series should have been an option for the legend (and / or graph, because sometimes you just want that percentile line in all its glory). It is the absolute most logical place for a data visualization tool, yet another calculated value. Even Microsoft does percentiles in PowerBI and you can choose your percentile values... The newer time series in Grafana even has a mean, a.k.a. a 50th percentile...

Fairly miffed that the original merge was blocked for silly reasons and that I had to look further for a suboptimal approach, e.g. using 
`quantile_over_time(0.95, node_load1{instance=~"$instancePicked.*"}[$__range])`
for my percentile across
`node_load1{instance=~"$instancePicked.*"}`

Fine for this one limited series, but it could've been much better, e.g. a bare minimum table with CPU performance with a max, average & 95th percentile for each container on a Docker host.
