### ISSUE TITLE
Stat plugin threshold colouring not working

### ISSUE THREAD

**Issue by ollie-campbell** [grafana/grafana#60565]
**What happened**:
Threshold colours not being applied to stat panel when using negative numbers.

**What you expected to happen**:
Colourings should be applied in a negative direction for negative numbers rather than a positive one (I'll try and describe this in a better way below).

**How to reproduce it (as minimally and precisely as possible)**:
Setup a stat that you can connect to some data that ranges in value from negative to positive values. Apply thresholds at 0, a positive number and a negative number.

**Environment**:
- Grafana version: 9.3.0
- Data source type & version: Influxdb 2.6.0
- OS Grafana is installed on: Ubuntu 22.04.1 LTS
- User OS & Browser: Windows 11 22H2 build 22621.963, Brave 1.46.144
- Grafana plugins: 
- Others:

I have a sensor that is calculating a trend value for temperature values. I'd like to have coloured thresholds to indicate an increase over a certain amount and a decrease below a certain amount. So I have these thresholds:

- 0.6 - Green
- 0 - White
- -0.06 - Yellow
- Base - White

This is trying to mimic the following:
- Between -0.059 and +0.59 it should be white
- Equal or greater than +0.6 should be green
- Equal or greater than (or is it less than for a negative number?) -0.06 should be yellow.

Here's what I am seeing:
- +0.6 = Green (correct)
- +0.01 = White (correct)
- 0 = White or yellow. It seems to decide randomly, I guess there is rounding at play here.
- -0.03 = Yellow (wrong)
- -0.05 = Yellow (wrong)
- -0.07 = White (wrong)
- -0.08 = White (wrong)
- -0.10 = White (wrong)

It seems the threshold of -0.06 is looking for values the wrong side of the threshold i.e. its looking to colour the text yellow between -0.06 and 0, rather than -0.06 and -0.09

**Comment by usmangt** [comment]
Hi @ollie-campbell,

Thanks for opening this issue.

Can you please try to reproduce this same issue on https://play.grafana.org/ and then share the dashboard link so that we can view it?

Thanks

**Comment by ollie-campbell** [comment]
@usmangt of course. But how do I use it to do that? I can't create dashboards and can't save existing ones....

**Comment by usmangt** [comment]
Hi,

You can use [this one](https://play.grafana.org/d/qD-rVv6Mz/6-state-timeline-and-status-history?orgId=1&from=1671531277107&to=1671617677107&viewPanel=70) and just alter the values and data (as close as possible) to show it if the -ve values are working correctly or not.

Let us know if this helps.

**Comment by ollie-campbell** [comment]
I'm unable to save any changes still:
![image](https://user-images.githubusercontent.com/43950743/208883013-98d83ebd-ea34-48d5-b993-f6bcd90bf42c.png)


But the problem still exists. I can't save or export the panel that I changed so I can only give you how to make changes to it to set it up yourself.....

Use this panel here (Influx datasource):

Query A:
```
from(bucket: "grafana")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "boltdb_reads_total")
  |> filter(fn: (r) => r._field == "counter")
  |> derivative(unit: v.windowPeriod, nonNegative: true)
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> drop(columns: ["_field"])
  |> tail(n:3, offset:2)
  |> yield(name: "derivative")
```

Query B:
```
from(bucket: "grafana")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "boltdb_reads_total")
  |> filter(fn: (r) => r._field == "counter")
  |> derivative(unit: v.windowPeriod, nonNegative: true)
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> drop(columns: ["_field"])
  |> tail(n:1)
  |> yield(name: "derivative")
```

Expressions C and D:
![image](https://user-images.githubusercontent.com/43950743/208885140-301730b1-c806-40bd-834a-fcce0e11650b.png)

Thresholds:
![image](https://user-images.githubusercontent.com/43950743/208885184-cc7c273d-e7fb-413b-8c10-b02826c18add.png)

Change the stat options "Value options -> Fields" to "D".

Keep refreshing and watch the results.....

**Comment by ollie-campbell** [comment]
Just checking to see if I can help anymore with this?

**Comment by usmangt** [comment]
Hi @ollie-campbell,

Just need quick info. What Unit you had set in the "Standard Option"? (please see reference screenshot)

![image](https://user-images.githubusercontent.com/69509548/210864901-4f10da72-384a-4c3b-90e6-e98cbf12e3ff.png)

**Comment by ollie-campbell** [comment]
It's set to 'Number'

**Comment by usmangt** [comment]
Took some time to get back on this one due to some other stuff.

I was not able to reproduce it on the play.grafana.com with the sample you provided but while testing it on my test machine I was able to see the effect while simply using the TestDB and putting -ve CSV values to replicate.

I am not sure what is missing here. I will forward this issue to our Engineers as they might be able to tell in more detail.

**Comment by joshhunt** [comment]
Hi @ollie-campbell - does this look like a reproduction of your issue? I used 'simpler' numbers to make it a bit easier for me to wrap my head around things.

https://play.grafana.org/d/7XoEEIoVz/60565-stat-plugin-threshold-colouring-not-working?orgId=1&editPanel=2

![image](https://user-images.githubusercontent.com/46142/213438095-64765658-bbd1-4c7c-9a5b-5330862d3a29.png)

It looks like the issue here is that thresholds don't work as expected with negative numbers?

**Comment by joshhunt** [comment]
[See this panel](https://play.grafana.org/d/7XoEEIoVz/60565-stat-plugin-threshold-colouring-not-working?orgId=1&editPanel=3), which I believe I've found a solution/workaround for your issue.

I believe the confusion is is due to thresholds applying 'upwards', not 'out from zero'. So to achieve:

 - Less than -10 is Yellow
 - Between -10 and 10 is White
 - Greater than 10 is Green

We must configure thresholds like so

![image](https://user-images.githubusercontent.com/46142/213440429-701586a3-20b8-42cf-aab7-f83e45e9da85.png)

Counting from the bottom:

 - Values lower than the first threshold (-10) are Yellow
 - Values From -10 (until 10) are White
 - Values above 10 are Green

I think this is what you're after?

**Comment by ollie-campbell** [comment]
Hi @joshhunt,
Yes, you've hit the nail on the head and thanks for the work around, I'll test it out fully and report back.

Is there a plan to change this so it works as I'm expecting it?

**Comment by joshhunt** [comment]
Probably not - changing how thresholds work without breaking people's existing dashboards is a tough sell. UI improvements could make it easier to understand how they work, but I don't think there's anything planned for this.

**Comment by andoks** [comment]
@joshhunt 

> Probably not - changing how thresholds work without breaking people's existing dashboards is a tough sell. UI improvements could make it easier to understand how they work, but I don't think there's anything planned for this.

It could perhaps be possible by "renaming" the current thresholds to "Upwards Thresholds" (or something similar), and introducing a new set of "Downwards Thresholds" that works the same way, just in the opposite "direction".
