### ISSUE TITLE
Timeseries panel: can't highlight a value from the legend in Firefox

### ISSUE THREAD

**Issue by adeptg** [grafana/grafana#60715]
Here is how it works in Google Chrome

![grafana_firefox_highlighting_issue](https://user-images.githubusercontent.com/212955/209236375-7b2655fd-40f5-49d6-a114-570b652a63c1.gif)

For some reason, it doesn't work the same way in Firefox - it just doesn't highlight.
I remember that it used to work in some old version of grafana. I can't recall which exact version broke it, but it works in grafana 8.4.4

**Environment**:
- Grafana version: 9.3.2
- Data source type & version: p8s
- OS Grafana is installed on: official Docker container with -ubuntu
- User OS & Browser: KDE Neon. Works in Google Chrome, doesn't work in Firefox

**Comment by usmangt** [comment]
Hi @adeptg 

Thanks for opening this issue. It seems to be working fine if I take this Timeseries panel visualisation from [play.grafana.org](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&viewPanel=2)

My Firefox version is 102.4.0esr (64-bit) (on-Linux)

Can you please try to reproduce this same issue on https://play.grafana.org/ so that we can view it?

Thanks

**Comment by adeptg** [comment]
Hi @usmangt. Thanks for your answer.
I have Firefox 108.0.1+build1-0ubuntu0.22.04.1~mt1, and I can reproduce it on https://play.grafana.org/ (in the incognito window as well)
It's hard to record a GIF for the function that doesn't work :( Please see my GIF for Google Chrome above: both click (to display only one line) and highlight work. In Firefox only click works, highlight - doesn't.
Happy holidays!

**Comment by codeincarnate** [comment]
We render labels using a `button` element. Whether text is selectable on a button element is undefined behavior and therefore browser specific. We can probably apply  the `user-select` property in CSS to these buttons to solve this.
