### ISSUE TITLE
Mixed Data Source + Live Streaming + Expressions error 

### ISSUE THREAD

**Issue by 0xMihir** [grafana/grafana#60767]
When creating a mixed data source that combines live-streamed data, and a simple math expression operating on the previous query, I get a server error. This seems to be related to https://github.com/grafana/grafana/discussions/38309, as the live-streamed data never loads when using a mixed data source.

This is the log error:
```log
logger=context userId=1 orgId=1 uname=admin t=2022-12-27T00:32:37.917911-05:00 level=error msg="Query data error" error="expression request error: failed to execute query A: unknown query type" remote_addr=[::1] traceID=
```

# Expected results
1. The live stream source loads when using a mixed datasource.
2. There is no error when creating an expression 

# Steps to Reproduce
1. Create a time series panel with the mixed data source
3. Make the first query a live stream from the test sample
4. Create a math expression with a reference to the previous query, like `$A * 5`

# Demonstration: 
https://user-images.githubusercontent.com/93171064/209618406-c844aa3b-c0d4-4ab7-ab37-a0f334352718.mp4

**Environment**:
- Grafana version: 9.3.2
- Data source type & version: Mixed ( Grafana example stream and expression)
- OS Grafana is installed on: Mac M1 Pro
- User OS & Browser: Chrome 108.0.5359.124 (Official Build) (arm64) 
- Grafana plugins: simpod-json-datasource, but reproducible without it

**Comment by zuchka** [comment]
Thanks for creating this issue, @0xMihir 

> Create a math expression with a reference to the previous query, like $A * 5

Have you tried using [transformations](https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/) instead of expressions?

While you can use expressions in a dashboard panel, they are primarily used for the alerting platform. More importantly, they are a server-side feature while transformations are client-side. With live channels you might have better luck doing maths in the browser

**Comment by 0xMihir** [comment]
Transformations do work, but for some reason, the mixed query does not support the live-streamed data source.
