### ISSUE TITLE
BarGauge with prometheus heatmap query not ordering fields correctly

### ISSUE THREAD

**Issue by owensmallwood** [grafana/grafana#60802]
Heatmap panel using Prometheus is formatting data like a timeseries

See [github discussion](https://github.com/grafana/grafana/discussions/49253#discussioncomment-4488874)

**Comment by leeoniya** [comment]
i don't see a Heatmap panel in that discussion. they're using `bargauge`, correct?

**Comment by twilde** [comment]
It is the heatmap format on the target that is not being respected, plus the ordering aspect of the organization transform.

**Comment by juanicabanas** [comment]
[This is the code line](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/datasource.tsx#L452
) which changes the response between a dashboard and a public dashboard.
Basically, after the api request, the response is being transformed in the PrometheusDataSource class, while the PublicDashboardDataSource class doesn't do it.

There are many possible complex solutions:

- We should make that transformation in the backend (I think that's the best solution)
- We should add a method in DataSourceApi class like `transformRequest`, which will return the original response but can be overriden in the subclasses that want it. Therefore, after calling `query` https://github.com/grafana/grafana/blob/main/public/app/features/query/state/runRequest.ts#L201, call that method as well.
- Should we start creating one PublicDashboardDataSource per every datasource, such as PrometheusPublicDashboardDataSource? 
- Should we change the way we call `query` inside PrometheusDataSource class and, instead of calling it from `super.query()`, make a **Strategy design pattern**, where a method from a property is the one that is called and, based on wether it is PublicDashboard or Dashboard itself, initialize PrometheusDataSource class with one or another class, which has `query` method?

**Comment by natellium** [comment]
Probably related to https://github.com/grafana/grafana/issues/65101

**Comment by evictorero** [comment]
Probably related to https://github.com/grafana/grafana/issues/61984

**Comment by torkelo** [comment]
Ideally this post query transformation should be moved to the Prometheus backend implementation

**Comment by evictorero** [comment]
Closing and tracking this issue [here](https://github.com/grafana/grafana/issues/67556)

**Comment by juanicabanas** [comment]
@torkelo I think moving the logic to the backend is the best solution but we also found other datasources making transformations after the response from the backend.
Therefore, and taking into account it would be really hard to change all that logic to the backend, I was thinking about the second point I wrote [here](https://github.com/grafana/grafana/issues/60802#issuecomment-1476916906).
Do you think it's a good solution? Basically, the idea is to create an abstract method or a method with a default behavior in DataSourceWithBackend like `transformResponse` and then, every subclass would be able to over it or not so it's not mandatory. 
Those datasources classes which make a transformation, would overwrite this method and runRequest would call, after 
`datasource.query()`, `datasource.transformResponse(queryRs)`.

**Comment by juanicabanas** [comment]
@torkelo At least this issue and [this other](https://github.com/grafana/grafana/issues/61984) **seem to be fixed** after [this changes](https://github.com/grafana/grafana/tree/juanicabanas/prometheus_transformation_poc).
Thoughts about this new implementation? Take into account it's a POC but it's almost the final work
