### ISSUE TITLE
Investigate Zabbix plugin not working with pubdash

### ISSUE THREAD

**Issue by owensmallwood** [grafana/grafana#60801]
Got a report the Zabbix plugin isn't working with pubdash.

https://github.com/grafana/grafana/discussions/49253#discussioncomment-4484240

**Comment by timlevett** [comment]
Might be a front end datasource issue.

**Comment by timlevett** [comment]
Chat with Alex on the AuthNZ team, they are the creator of this plugin. Also @guicaulada has some experience with it.

**Comment by evictorero** [comment]
I think the problem is [Zabbix datasource does not extend](https://github.com/alexanderzobnin/grafana-zabbix/blob/master/src/datasource/datasource.ts#L30) from DataSourceWithBackend so instead of doing super.query it is doing the query with a [hardcoded url](https://github.com/alexanderzobnin/grafana-zabbix/blob/master/src/datasource/datasource.ts#L197) which is not valid for public dashboards

Asked to @alexanderzobnin if he can take a look

**Comment by evictorero** [comment]
Hi @alexanderzobnin friendly reminder 😃. Did you have a chance to take a look at this?

**Comment by evictorero** [comment]
We are closing this issue since it's not related to Grafana and requires changes to the plugin. I opened a [new issue](https://github.com/alexanderzobnin/grafana-zabbix/issues/1635) on the project.

**Comment by sulaiman21** [comment]
@evictorero I think the issue is within grafana but on the plugin. If you try to hit the following URL you will get unauthenticated error 

http://localhost:3001/api/ds/query

Thank you.

**Comment by sulaiman21** [comment]
Hi @evictorero 
Well we have issue in Grafana Cloud where we are not getting data in public dashboard but when a user logged-in then we are getting Data.

Any solution on this?

Thank you
