### ISSUE TITLE
SnapShots: Descriptive Text Field 

### ISSUE THREAD

**Issue by roscoe57** [grafana/grafana#6080]
- **I'm submitting a ...**
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

It would be super useful to add a descriptive text to each Snapshot, eg Server room overheat, Brownout in June16, shared with boilerman

As you rack up a number snapshots from the same dashboard it gets difficult to recall what/who they were for.

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
