### ISSUE TITLE
Panel Edit Alerting: Editing legacy alerting cannot be temp saved through Apply 

### ISSUE THREAD

**Issue by polibb** [grafana/grafana#60839]
**What happened**:
When _applying_ changes (without saving them) to a panel's alerting configuration, if it is legacy alerting the changes are not applied at all. 

**What you expected to happen**:
_Applying_ changes to a panel's legacy alerting should temporarily save them when the user is returned to the dashboard page. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard with a panel. Add a rule for alerting using legacy alerts. Save the dashboard.
(On the video below) Go to the dashboard again and then to panel edit again. Change something on the alert you just created. Hit "Apply". 
Go back to the panel and check the alert - the changes are not applied. 

https://user-images.githubusercontent.com/13227501/210062351-8501e656-da73-40ed-920b-82549c010984.mov

**Anything else we need to know?**:
This is reproducible for admin, editor and viewer. The viewer has access to editing a panel without saving when `viewers_can_edit `configuration is set to `true`.

**Environment**:
- Grafana version: Grafana v9.2.4+
- Others: legacy alerts (use through [configuration](https://grafana.com/docs/grafana/latest/alerting/migrating-alerts/roll-back/) if not using them otherwise)

**Comment by ignas-sedunovas** [comment]
I'm seeing this issue in `Grafana v9.3.2 (21c1d14e91)`.

Which version is expected to have this fix?

**Comment by natellium** [comment]
Hey @ignas-sedunovas, as it states in the alerting view since v9: this is legacy alerting, which has been deprecated and planned to be removed in our next major version. We don't have plans to fix this specific issue, instead we encourage to upgrade to the new alerting experience. If you're unable to upgrade, please do open an issue and we'll be able to try to help!

**Comment by natellium** [comment]
ah, thanks for the pointer @ignas-sedunovas! I labelled it as `wontfix` for clarity

**Comment by alkuzad** [comment]
@natellium  I know that you deprecated old Grafana alerting, but I wanted to mention that there could be some unintended consequences with the deprecation process. We're in the middle of migrating over a thousand alerts, and we had initially decided not to move to AlertManager due to our tight schedule. We started planning the migration before images were added to the new Grafana alerting, which was a requirement for us. We're now experiencing an issue where developers are changing alert thresholds and the changes aren't being saved. The bug doesn't show anything on the screen, so if someone doesn't know about it, the changes will just silently not apply.

We didn't catch this issue during testing, and we're now receiving reports that this problem is also affecting others. I was wondering if we could collaborate on finding a solution to this issue, as it's starting to have a significant impact on our migration project. Thanks for your attention to this matter.

**Comment by natellium** [comment]
cc @grafana/alerting-squad pinging so you're aware of the feedback above :)

**Comment by JeeWeetje** [comment]
Is there a way to circumvent this bug so that I am able to remove recipients from an alert? We are in the midst of migrating our Grafana alerts to an Azure Stream Analytics & Logic Apps solution, but during the migration period I would like to remove some recipients on the existing Grafana Legacy alerts.

We use the Grafana legacy alerts since the recipients systems are configured on the plain text emails sent from Grafana which seemed quite a hustle to replicate in the new alerting system.

Please advise, if it is possible to just remove the recipients in another way than adjusting the alert on a dashboard which won't save due to this bug.

**Comment by alkuzad** [comment]
> Please advise, if it is possible to just remove the recipients in another way than adjusting the alert on a dashboard which won't save due to this bug.

save button works, the "apply" button does not work. If in your case save also do not work it is another bug then.

**Comment by konrad147** [comment]
The apply button does not work save button does. 
The legacy alerting AlertTab is written in AngularJS, and due to inconsistencies in handling state between React and Angular, the issue surfaces. 
A lot of investigation time would be needed to fix the issue. Given it's not a blocker but rather an inconvenience we are not eager to fix this
