### ISSUE TITLE
Cloudwatch data source provisioning not working

### ISSUE THREAD

**Issue by ismael-contentful** [grafana/grafana#60921]
**What happened**:
Cloudwatch data source provisioning doesn't seem to be working. I followed the steps in the documentation but Cloudwatch doesn't appear as a Data Source. It does appear installed though.

<img width="481" alt="Screenshot 2023-01-03 at 18 46 06" src="https://user-images.githubusercontent.com/93582811/210412647-16721f6e-c422-4f1d-91da-3626496f33f8.png">

<img width="1413" alt="Screenshot 2023-01-03 at 18 45 35" src="https://user-images.githubusercontent.com/93582811/210412667-148ec1b8-e6b0-45a0-b70b-26458ad9af6c.png">

**What you expected to happen**:
Cloudwatch data source to appear in Grafana data sources.

**How to reproduce it (as minimally and precisely as possible)**:
Block of code from first screenshot in your production or staging deployment YAML.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.1
- Data source type & version: CloudWatch
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS Ventura 13.0.1 | Chrome
- Grafana plugins: Redshift
- Others:

**Comment by mellieA** [comment]
@ismael-contentful if you select the datasource in the UI, do you see any errors or missing configuration options? I see you're provisioning this datasource, but you can still use the test button in the Configuration>Datasources UI to validate the connection. What result do you see?

**Comment by ismael-contentful** [comment]
Sorry for the late reply @mellieA , Christmas holidays got in between.

I can correctly select, configure and query the datasource manually via the UI, so the error seems to be in the provisioning phase.

<img width="835" alt="Screenshot 2023-01-09 at 17 29 27" src="https://user-images.githubusercontent.com/93582811/211358089-2b7dc2b4-ecc7-4d39-8782-232984e4b9ba.png">

**Comment by fritzstauff** [comment]
Still see this issue on grafana v9.4.7.

**Comment by kevinwcyu** [comment]
Hi, `additionalDataSources` should be changed to `datasources` in your provisioning yaml file. I couldn't find any references to `additionalDataSources` in the docs here https://grafana.com/docs/grafana/v9.2/administration/provisioning/#data-sources. If you still have the link to the docs on hand, would you be able to post it here so we can make sure it's corrected.

I tested this on 9.2.1, 9.4.7 and main and using `datasources` works, while `additionalDataSources` doesn't work. Therefore I'm closing this for now since it appears to be a misconfiguration in the provisioning file. But feel free to reopen if using `datasources` does not work.
