### ISSUE TITLE
Can't have a fixed step of 15s for big time ranges

### ISSUE THREAD

**Issue by Irrational-NX** [grafana/grafana#60993]
## Context : 

We have to report every downtime for components, we do that with different panels using grafana. 
Even if it's just 15s of interuption, we have to report it.
We mainly use blackbox, but I don't think it's important. The results are always "1" (the component works), or "0" (The component is down). If we do not have data on a given moment, we consider the point to be "0" (component down).

For my panels, to make sure the doesn't change from 15s and that I check all of my data, I configured `max data points : 1000000` in every panel. 
I use prometheus to collect metrics, but it stores everything in Victoria Metrics, so Grafana uses a "prometheus" Datasource but talks with a VMselect.

**What happened**:
For time ranges higher than 2 days, results are inconsistent. If I use 3d, I see downtimes that did not really occur :
![availability](https://user-images.githubusercontent.com/32514952/210598782-ca96da7c-f76b-4d8c-bc85-1aaeeaa1e057.gif)

If I open the Query Inspector, I see that the step is "20s". If I modify the query to only list occurences of "0"s in the selected period, I found 16 occurences with the Query Inspector. This is wrong because (I guess...) the step shouldn't be 20s here. I could replicate this by asking the same query to the vmselect component directly. I can configure the step, so when using "20s", I get the same 16 occurences on the very same time frames. If I change the step to 15s, I get 4 occurences only (The correct result I want to display on grafana... And that I only can display on smaller time ranges.

And for bigger time ranges (4d and more) some downtimes that did occur are absent. the step becomes higher.

**What you expected to happen**:

The step should stay 15s because I want to display a large amount of points.

**How to reproduce it (as minimally and precisely as possible)**:

Use a state timeline panel (works with others but it's easy to spot changes), fix an almost unlimited number of points. to display and make sure the interval stays 15s. Change the time range to at least 3d and launch the Query inspector. The step is not 15s.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.1
- Data source type & version:
- OS Grafana is installed on: Ubunut (docker)
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@Irrational-NX I've moved this to the squad that handles the prometheus datasource. It's my understanding that this is due to the number of data points that would be included in the graph if every point were used. Over larger time ranges the step is adjusted to fit. I saw you are setting max_data_points. 

This question comes up often, I couldn't find docs to explain what is expected in this case. I'm hoping that the squad can provide a more detailed explanation and perhaps we can capture it for the docs

**Comment by eadwu** [comment]
Also experiencing this? Is there any particular reason why it is blocked from changing the step interval in the dashboard configuration? You can only transitively adjust it using the other knobs which is not even close to ideal.

I'm also confused in how when using `InfluxQL` you would have to explicitly add a `groupBy($__interval)` but in PromQL/MetricsQL it appears to be forcibly injected to every query?

**Comment by Sin4wd** [comment]
I want to emphasize that we are experiencing "wrong" and "misleading" visualizations because we can't specify the step correctly.
Our query looks like this `metric_name < 0` with `min step: 15s`. When we set time interval to 1 or 2 days the panel looks like every the metrics is always around -1 and sometimes less.
<img width="1398" alt="long shot" src="https://github.com/grafana/grafana/assets/30809018/190ab8cf-6a94-4843-b7d3-8d76cf6eb4c7">
However if you zoom close enough there is almost no points in those areas that we saw -1 earlier. Only some sparse points.
<img width="1397" alt="closeup" src="https://github.com/grafana/grafana/assets/30809018/0242f3ff-180e-4af6-9b49-3b7a18934433">
Then, if you increase the min step to 60s in the closer view the problem rises again.
There was previously an effort in #9705 that was addressed with PR #36422. Unfortunately it was reverted here #38982 for the sake of UX .
I think correctness must come first and please consider having a way of enforcing `step` value in the grafana.

**Comment by MattByczko** [comment]
Pinging here as there is no work-around and this feature is heavily requested in previous issues. I'd like to have some workaround or supported solution to get accurate data over wider time-periods.

**Comment by MattByczko** [comment]
Follow up - Found this to work around:

https://github.com/prometheus/prometheus/issues/2364#issuecomment-391903174
