### ISSUE TITLE
Glue: Mixing non-provisioned and provisioned data sources does not create a correlation

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#61029]
Some issues with provisioning to check:

> Bug? When creating a correlation from a non-provisioned to a provisioned data source, after restarting and reconstructing all provisioned correlations the custom one from a non-provisioned data source is gone.

> Correlations obviously need a non-provisioned data source as the source, but it looks like there’s some oddities with the target data source. For example, I could create a correlation to a provisioned (non-writable) Prometheus data source… but I couldn’t create one targeting a provisioned Loki data source. A non-provisioned Loki data source did work as a target, though. I still couldn’t use a non-provisioned Loki as a source though, regardless.

**Comment by Elfo404** [comment]
this may happen if the provisioning file deletes AND creates datasources.

let's say you have this:

```yaml
apiVersion: 1

deleteDatasources:
  - name: prometheus

datasources:
  - name: prometheus
    uid: prometheus
    type: prometheus
 # ...
```

upon restarting grafana, the datasource is first deleted, which causes all correlations targeting `prometheus` to be deleted, the created again, but given the provisioning file doesn't have correlations defined, no new correlation is created.

i'm not sure why in a prod environment one would want to delete and recreate datasources on every restart, but that behavior was actually intentional: https://github.com/grafana/grafana/blob/main/pkg/services/provisioning/datasources/datasources.go#L179 . that's because if you actually want to delete datasources via provisioning file, then no orphan correlation is left in the db. As an alternative, if we'd consider this to be an actual issue, we may skip deleting correlations during provisioning, but we'd have to create a cleanup function that kicks in after provisioning is completed to delete all orphaned correlation before returning from https://github.com/grafana/grafana/blob/main/pkg/services/provisioning/datasources/datasources.go#L60.

but again, at that point why wouldn't someone persist the correlations in the provisioning file in the first place?

**Comment by ifrost** [comment]
This should be documented as part of https://github.com/grafana/grafana/issues/62100
