### ISSUE TITLE
Bug: Long dashboard names cause the command palette to crash

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#61093]

**Comment by ashharrison90** [comment]
dug into this a little... it's due to the performance of `command-score` which `kbar` uses under the hood (see https://github.com/timc1/kbar/issues/252). [this is being worked on](https://github.com/timc1/kbar/issues/255), but we need a solution in the intermediate term.

given we have our own search backend which already ranks the dashboard search results, i wonder whether we should stop registering the dashboard results as actions? we don't need command-score to run over them again 🤔 

we can instead manually create `ActionImpl`s for each dashboard returned from the search, append them to the results returned from `useMatches` before passing this concatenated list as `items` to `KBarResults`

i've done this locally and it does work, but it's a little hacky/brittle.
