### ISSUE TITLE
Bug: Prometheus source escapes . (dot)

### ISSUE THREAD

**Issue by discordianfish** [grafana/grafana#6118]
- Running v3.1.1 (commit: a4d2708)
A query like `node_filesystem_free{job="node", instance="master0", mountpoint="var/lib/kubelet/pods/234f0590-80e8-11e6-8aa4-4eef5830841f/volumes/5pi.de~do-volume/data"}` gets turned into this request to the grafana proxy (See the \\ after `5pi`):

```
GET /api/datasources/proxy/1/api/v1/query_range?query=node_filesystem_free{job="node", instance="master0", mountpoint="/var/lib/kubelet/pods/234f0590-80e8-11e6-8aa4-4eef5830841f/volumes/5pi\\.de~do-volume/data"}&start=1474618349&end=1474629149&step=40
```

**Comment by discordianfish** [comment]
I suspect it's caused by https://github.com/grafana/grafana/blob/56622ee2c6d030efb7b39433b1b1fc6f0e7250a4/public/app/plugins/datasource/prometheus/datasource.ts#L42
What is this used for? Why not just urlencode the query?

**Comment by torkelo** [comment]
regexEscape is only used when interpolating variables, and only if the variable is marked as Multi select or support All value, in that case we need to Regex escape it because for the query to work it needs to use the regex operator in the condition `=~`

Are you using a template variable in your query?

**Comment by discordianfish** [comment]
@torkelo Oh right, it's a template variable.. And I now get what you mean, still a bit surprising UX. Anyways, thanks!
