### ISSUE TITLE
Alert rule panic; runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by robinkanters** [grafana/grafana#61304]
**What happened**:
- Grafana quits unexpectedly from time to time, logging alert rule panic (stacktrace below)

**What you expected to happen**:
- For it not to crash :wink: 

**How to reproduce it (as minimally and precisely as possible)**:
I have the alert rule that I pasted below, if I click the Refresh button, it shows an error popup in the top right, I think this might be the cause. The screenshot below is of the rule with the uid from the stack trace.

**Anything else we need to know?**:
- Might be related to #58703
- [Stack trace](https://github.com/grafana/grafana/files/10393720/stack.txt)

**Environment**:
- Grafana version: v9.3.2 \(21c1d14e91\)
- Data source type & version: AlertManager, Athena, cloudwatch, ElasticSearch, OpenSearch, Prometheus
- OS Grafana is installed on: Linux (AWS ECS)
- User OS & Browser: EndeavourOS; Firefox 108.0.2
- Grafana plugins: 
  - Amazon Athena
  - Direct Input
  - Grafana OnCall
  - OpenSearch
- Others:

![image](https://user-images.githubusercontent.com/1043866/211846686-e31d12e6-69ac-4499-a430-6c7fd5d5a680.png)

**Comment by mellieA** [comment]
@robinkanters Does this same query complete as expected in the explore view? If so, are you able to share a sample of what the return data looks like?

**Comment by yuri-tceretian** [comment]
I can confirm the bug. The Cloudwatch plugin returns no data result as a data frame with a single value. After https://github.com/grafana/grafana/pull/55347 that value gets converted to a single value NoData

https://github.com/grafana/grafana/blob/2d20c8db7b01b3f1f3c946cf0cc6c78c13a178fa/pkg/expr/commands.go#L175-L176

then when math expression tree is executed, the `is_nan` method walkFunc produces a slice with a `nil` element.
https://github.com/grafana/grafana/blob/05fd7eb047607ab1fe25f8a7d21b27ed0da36794/pkg/expr/mathexp/exp.go#L491-L517
because NoData result has nil value.

Then that result is provided to unary operator `!` that crashes because `nil` it does not match any type in walkUnary matcher
https://github.com/grafana/grafana/blob/05fd7eb047607ab1fe25f8a7d21b27ed0da36794/pkg/expr/mathexp/exp.go#L124
and in the default branch it tries to call method Type() on the nil, which causes a crash.

**Comment by Roberto6969** [comment]
Update from 9.4.0-960xxx to 9.4.0-96993pre caused same error:

 panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x27a2d8c]

How can I resolve this?

Thank You.

**Comment by Roberto6969** [comment]
Update: Update from 9.4.0-96993pre to version=9.4.0-97045pre didn't solve problem.

Is this error somehow in relation with:

logger=ngalert.multiorg.alertmanager t=2023-01-18T11:35:46.792823325Z level=error msg="unable to create Alertmanager for org" org=6 error="unable to initialize the notification log component of alerting: proto: wrong wireType = 2 for field Idx"

**Comment by yuri-tceretian** [comment]
> Update: Update from 9.4.0-96993pre to version=9.4.0-97045pre didn't solve problem.
> 
> Is this error somehow in relation with:
> 
> logger=ngalert.multiorg.alertmanager t=2023-01-18T11:35:46.792823325Z level=error msg="unable to create Alertmanager for org" org=6 error="unable to initialize the notification log component of alerting: proto: wrong wireType = 2 for field Idx"

@Roberto6969 this is not related. Main seems to be broken (panics when starts with database that created . We're fixing this right now

**Comment by Roberto6969** [comment]
@yuri-tceretian Great - I appreciate your effort.
