### ISSUE TITLE
display graph stacked depending on template variable

### ISSUE THREAD

**Issue by it-eddy** [grafana/grafana#6132]
Feature request:
Add support to toggle graph display style stacked depending on a template variable (true/false). Changeable on the top like other variables.
That way you can change display style of all graphs on one dashboard with one click.

Workaround till now:
Build and save to dashboard. identical but one with all stacked. Use Settings -> Links, to add a link to the other dashboard with the other style.

currently using v3.1.0

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
