### ISSUE TITLE
Import overwrites dashboard permissions without warning

### ISSUE THREAD

**Issue by froskarel** [grafana/grafana#61368]
Hello!
When I'm trying to import a dashboard with the same UID from one organisation to another Grafana overwrites dashboard permissions of main dashboard without warning. There is need to add some logic handling if a dashboard will be overwritten or not and also need to add forced changed UID for preventing replace permissions...

**Environment**:
- Grafana version: 9.0.7
- OS Grafana is installed on: RHEL 7
- User OS & Browser: Any

**Comment by froskarel** [comment]
Same issues:
https://github.com/grafana/grafana/issues/54086
https://github.com/grafana/grafana/issues/11515
https://github.com/grafana/grafana/issues/11860

**Comment by tonypowa** [comment]
Thanks for creating this issue, @froskarel 

I am forwarding this issue to the dashboard squad

**Comment by axelavargas** [comment]
Hey @froskarel, thank you for reporting this issue,  I am forwarding it to the @grafana/grafana-authnz-team as this is related to permissions.

**Comment by mgyongyosi** [comment]
Hey @froskarel,

Thanks for reporting this issue. I tried to reproduce it based on the information you provided (with 9.0.7 OSS and with 9.3.6 OSS), but I haven't seen any permission changes after the import (same uid). Could you please provide a step by step guide on how to reproduce this?

However, when one of the dashboards were removed I realised that the permissions of the other dashboard (same uid, different orgs) have disappeared and this seems to be a bug.

**Comment by froskarel** [comment]
@mgyongyosi  hello.
1. In Grafana must be more than 1 org. 
2. Export 1 of dashboards via JSON from 1 org
3. Import dashboard from second step into new organisation with the same UID
4. Finally all permissions in first organisation in dashboard on 2 step will be erased(((

**Comment by tobhv** [comment]
i have the same issue. although even during import when i change the uid I see permissions get removed from the same dashboard in other organizations.
running on grafana 9.3.11

**Comment by unique0lai** [comment]
I meet same problem.

The data struct of permission table don't support same uid in different organization. 
Permission table should add org_id field.
<img width="1135" alt="企业微信截图_a3ef0802-3a26-4ead-8fb4-143b0ef62678" src="https://user-images.githubusercontent.com/11598235/234281435-429b1b58-739a-4c8a-9ac4-535ca3234117.png">

**Comment by mgyongyosi** [comment]
@froskarel We tried again with both RBAC enabled/disabled, but couldn't reproduce the issue with the import and it seems that the code handles the different `orgID`s correctly.

We suspect that the error is caused by RBAC migrations, did you update Grafana to 9.0.7 from 7.x or 8.x? Or did you enabled/disabled RBAC manually from the config file? To fix the migration issue you can execute this: https://github.com/grafana/grafana/issues/54974#issuecomment-1252179049 

Be aware that permissions that have been changed/created after the Grafana upgrade will be lost.

@unique0lai Could you please create a different issue with repro steps for your case?

> The data struct of permission table don't support same uid in different organizations.
Permission table should add org_id field.

The permission table does not have an org_id field, because the org_id is stored and handled on the role level. (A Role has multiple Permissions.)

**Comment by tobhv** [comment]
@mgyongyosi 
i am running on 9.5.8 and still see the issue.
as @froskarel has stated i also applied the following steps:
1) export dashboard1 from org A, share it for external use.
2) import dashboard1 to org B, leave UID as is
result: 
a) the editor role and user role are removed on the dashboard in the other organization. 
b) only admins can still see the dashboard. 
c) the editor role and user role are removed on the dashboard in any other organization (where that dashboard is in use)
info on my environment:
- started on version 9
- rbac not in use (default)

any other info i could share ?
