### ISSUE TITLE
Time series: Multi tooltip for graph with many series obstructs the view and is hard to use

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#61615]
**What happened**:

This came up during https://github.com/grafana/grafana/pull/61432 where we were deciding is `single` or `multi` tooltip would be better for Explore's graph panel. 

During discussion we discovered multiple issues related to `multi` tooltip that prevents us using it as default in Explore, even though it cover valid usecase - comparing 2+ values over time: 

- `multi` tooltip used with 10+ series blocks the view over graph and is in the way. There are other tools that solve this by having tooltip above/on the side of the graph.
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/30407135/212901259-3e32842a-9dc2-4573-b04f-85a058ab337d.png">

- When there are many series, tooltip becomes unusable as series in tooltip can't fit on the screen. Maybe showing only x surrounding values could be a good solution there
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/30407135/212901024-5c4b9f0d-8838-44c9-b462-19207f17d357.png">

**What you expected to happen**:

Tooltip that does not obstruct the view over data can be used to compare multiple values across the time, without worrying about how many series are displayed in graph.

**Comment by radiorental** [comment]
We ideated around many ideas, the conclusion was that there's not immediate and obvious solution to this design challenge.  For example the concept below works ok for a small set that are not too close together, but it becomes click intensive if comparing a larger set of values. I feel what is needed for this issue was a larger design initiative to define use cases and usability testing of different potential design proposals
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/3299847/213010123-2d9242b7-5135-43ad-9e40-128c28a4d93e.png">

**Comment by supilee** [comment]
The timeseries panel recently moved to the DataViz squad. Re-assigning it to the DataViz Squad.

**Comment by yalpay** [comment]
![image](https://github.com/grafana/grafana/assets/37114514/3ced8937-7dc7-4d6e-942f-de338b052131)

My solution is updating css files and renerating the frontend. I think there should be a feature under Hover Tooltip menu in Panel Setting, where we can adjust the tooltip menu column number. For example there is "As Table" option under Legend setting. Similarly, tooltip area can be a table and the column count can be adjustable
