### ISSUE TITLE
[Bar Chart] Bug when using Bar Radius with staking for multiple series.

### ISSUE THREAD

**Issue by marinnedea** [grafana/grafana#61833]
**What happened**:

Bar chart rounded corners do not behave right when overlapping

**What you expected to happen**:

Bars with rounded corners to overlap without visible corners at the bottom.

**How to reproduce it (as minimally and precisely as possible)**:

- using BarChart with 2 or more series
- set  stacking to Normal or 100%
- set the Bar Radius to a value higher than 0

The result is:

![image](https://user-images.githubusercontent.com/7581631/213648550-05708f93-92c7-468a-8bde-b6798252ae8a.png)

**Anything else we need to know?**:

**Environment**: All  (OSS and  Grafana Cloud)
- Grafana version: 9.3.2
- Data source type & version:  used the TestDB to replicate the behaviour
- OS Grafana is installed on: Tested with Ubuntu 20.04 for OSS, in cloud you can use [this panel in Grafana Play](https://play.grafana.org/d/timeseries-stacking2/timeseries-and-barchart-stacking?orgId=1&editPanel=18) to replicate the problem.
- User OS & Browser: MacOS Ventura 13.1 and Google Chrome 109.0.5414.87 (Official Build) (arm64)
- Grafana plugins: N/A
- Others: N/A

**Comment by leeoniya** [comment]
pretty sure thebbug is here: https://github.com/leeoniya/uPlot/blob/468b3b325d2f35819e9827c7a0249411ffab9532/src/paths/bars.js#L186

that clipping rect needs to be a rounded rect (with the radius)

**Comment by leeoniya** [comment]
just pushed [a commit](https://github.com/leeoniya/uPlot/commit/4f944b48f422397cc86d78599da98ec870543f13) to the uPlot which should allow us to round just the two outer corners of the top bar (or bottom bar when negative)  in the stack instead of rounding all corners on all bars.

https://leeoniya.github.io/uPlot/demos/high-low-bands.html

![image](https://user-images.githubusercontent.com/43234/213825629-43006cfd-ec23-4958-810c-83432d3dfb9b.png)

**Comment by leeoniya** [comment]
the situation below will still likely be problematic since the top segment is rounded independently (the bar is not rounded holistically). the reason for this is that each segment supports a border with configurable width around its perimeter which matches the segment color. if we just drew the bar unrounded and simply chopped off corners with a cookie cutter, you would lose the borders around the corners and edges of low-value segments that fall within the clipping radius. working around _that_ problem is really complicated. 

![image](https://user-images.githubusercontent.com/43234/213827273-fc27dd2d-5877-4deb-8daf-0456bf790d1e.png)
