### ISSUE TITLE
Login: Poor user feedback when login is blocked after brute force / too many failed attempts

### ISSUE THREAD

**Issue by HenrysCat** [grafana/grafana#62037]
**What happened**:
Test brute force mitigation on login page by trying to login with correct user name and wrong password.

**What you expected to happen**:
IP blocked after a few attemps.

**How to reproduce it (as minimally and precisely as possible)**:
Try to login with correct user name and wrong password.

**Anything else we need to know?**:
Got password wrong over 50 times and not blocked in any way.

**Environment**:
- Grafana version: v9.3.2
- Data source type & version: influxdb
- OS Grafana is installed on: Debian 11
- User OS & Browser: Firefox
- Grafana plugins: None
- Others: None

**Comment by zuchka** [comment]
Thanks for creating this issue, @HenrysCat 

This is actually working. If you make 30 failed login requests and then try to login with the correct credentials, you'll see that also fail. If you check your grafana server logs while you try and brute force, you'll see this in the logs:

> logger=context userId=0 orgId=0 uname= t=2023-01-25T01:56:13.117920376Z level=error msg="Invalid username or password" error="too many consecutive incorrect login attempts for user - login for user temporarily blocked" remote_addr=169.150.203.32 traceID=

So I would say the problem is not that brute force is broken but that Grafana has poor user feedback for when a user does get blocked after too many requests.

perhaps a better error message would improve the UX and lessen confusion.

**Comment by HenrysCat** [comment]
I see thanks, 30 is a very high number, 5 would be better, but leaving the user/password login page available even though IP is blocked still leaves any brute force bot running potentially for days, would it not be better to present another screen stating IP blocked for x number of minutes or even just a generic error page?
