### ISSUE TITLE
allow me to troubleshoot "error unexpected end of JSON input" alerting errors

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6234]
sometimes alerting runs result in an execution error "tsdb.HandleRequest() error unexpected end of JSON input"

However this is useless and countereffective if there's no way for me to troubleshoot the problem.
So grafana should log the response it got from the datasource. http headers and http data. so that i can actually do something about it. instead of triggering inactionable alerts.

**Comment by torkelo** [comment]
Since this is an error where the tsdb backend is returning invalid json, and maybe even 500 error, should it not also be logged in the TSDB backend? 

Grafana can log error responses (the should show up when you test the alert rule) but responses that cannot be parsed is trickier to log / return. Where should this be saved and presented?

**Comment by torkelo** [comment]
in develeopment mode if you enable the `tsdb.graphite` grafana logger with debug level logging:

```
[log.console]
filters = tsdb.graphite:debug
```

Then the request params sent to graphite and response is logged. By but wont solve this case (where the response cannot be parsed). Will add a logging case for as well to log the whole body (when in development mode and debug is enabled for this logger)

**Comment by torkelo** [comment]
Actually it is logged. 

set app mode to development (in custom.ini or grafana.ini)

```
app_mode = development
```
and make sure the graphite logger level is set to debug

```
[log.console]
filters = tsdb.graphite:debug
```

**Comment by Dieterbe** [comment]
the machine is a production machine though. seems weird to have to set it to development. perhaps `app_mode` conflates log verbosity with the actual app mode.  Either way you made a good point about the tsdb itself, seems like a better approach to use the tsdb logs.

**Comment by torkelo** [comment]
Yea, the app_mode = development was only if you wanted to log request and response even when there was no error (As this can be super expensive, so that is why you needed development mode as well).

But for you case where there is an error in the response parsing or just error returned from TSDB you do not need to set development mode. Grafana logs all error responses and unmarshal errors as INFO level on the tsdb.graphite logger
