### ISSUE TITLE
Spike: how can we hide ui components for logged in users when its a public page?

### ISSUE THREAD

**Issue by owensmallwood** [grafana/grafana#62368]
When its a public page (a pubdash or the email sharing request access page), we use the config flag `isPublicDashboardView` to determine if we render components in `AppWrapper.tsx`. Is there a better way of doing this? Should consult the #frontend Slack channel.

**Comment by juanicabanas** [comment]
After [some talks with Torkel ](https://raintank-corp.slack.com/archives/CHKLEJ668/p1674671903106909), he made a [PR](https://github.com/grafana/grafana/pull/62281) with some modifications in order to use chromeless attribute and hide some elements. With that already merged, it's possible to remove this flag in many places
