### ISSUE TITLE
Add group name and tenant labels to `grafana_alerting_rule_group_rules`

### ISSUE THREAD

**Issue by gotjosh** [grafana/grafana#62361]
I stumbled upon:
```
// TODO: once rule groups support multiple rules, consider partitioning
// on rule group as well as tenant, similar to loki|cortex.
```

We now do, so let's do that.

**Comment by stevesg** [comment]
After speaking to @alexander-akhmetov, we realized that because group names are only unique within a folder, we should be including the folder in the group_name label of the metric. This is consistent with Prometheus which includes the filename in the lavel value, e.g. `group_name="/path/to/rules.yaml;my_group"`.

We should do the same, but include the folder in the name. We think it would be nicer to include the folder full path, and not the UID, though you could argue for either, e.g. `group_name="folder/full/path;my_group"`.
