### ISSUE TITLE
Import Service Graph into Dashbaord 

### ISSUE THREAD

**Issue by Juandavi1** [grafana/grafana#62899]
Hi ! 

I'm again ! I come from here https://github.com/grafana/tempo/issues/1509 

Im trying to add service graph to a dashboard but i can't achieve it :( 

Dashboard : 
![image](https://user-images.githubusercontent.com/18731612/216515796-de40462f-d6c7-422c-9c9b-82f8556dc60a.png)

Exporer:
![image](https://user-images.githubusercontent.com/18731612/216515894-7564a2ae-0fb9-47c9-88f4-3f81a377fb7a.png)

Is it posible to do it ? 

And the last one, Can i use variables in the service graph's filters ? 

Thanks a lot

**Comment by aocenas** [comment]
@Juandavi1 this should be possible, you just need to select nodeGraph visualization. The issue may be that we don't show the top table with the service map in dashboard at the moment because explore and dashboards work a bit differently.

Regarding the variables you can use template variables in the filters like this:
<img width="545" alt="Screenshot 2023-05-17 at 11 24 27" src="https://github.com/grafana/grafana/assets/1014802/5729f088-12f4-4c25-a16c-d8a667ac1357">
