### ISSUE TITLE
Item scroll missing

### ISSUE THREAD

**Issue by gonzalo-** [grafana/grafana#63057]
**What happened**:
For example on the explore window ( [explore](https://play.grafana-zabbix.org/explore?orgId=2&left=%7B%22datasource%22%3A%22000000005%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22resultFormat%22%3A%22time_series%22%2C%22itemTag%22%3A%7B%22filter%22%3A%22Application%3A+Network+interfaces%22%7D%2C%22queryType%22%3A%220%22%2C%22group%22%3A%7B%22filter%22%3A%22Backend%22%7D%2C%22host%22%3A%7B%22filter%22%3A%22backend03%22%7D%2C%22application%22%3A%7B%22filter%22%3A%22%22%7D%2C%22item%22%3A%7B%22filter%22%3A%22%22%7D%2C%22functions%22%3A%5B%5D%2C%22triggers%22%3A%7B%22count%22%3Atrue%2C%22minSeverity%22%3A3%2C%22acknowledged%22%3A2%7D%2C%22trigger%22%3A%7B%22filter%22%3A%22%22%7D%2C%22tags%22%3A%7B%22filter%22%3A%22%22%7D%2C%22proxy%22%3A%7B%22filter%22%3A%22%22%7D%2C%22options%22%3A%7B%22showDisabledItems%22%3Afalse%2C%22skipEmptyValues%22%3Afalse%2C%22disableDataAlignment%22%3Afalse%2C%22useZabbixValueMapping%22%3Afalse%7D%2C%22table%22%3A%7B%22skipEmptyValues%22%3Afalse%7D%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-1h%22%2C%22to%22%3A%22now%22%7D%7D) ) in the "item" seccion I have a lot of items that doesn't show completly, if I search for them from the top of my mind, they are there, but I don't have them all in a list with an scroll bar on the side to manually look for them.

**What you expected to happen**:
When I want to search for an Item it should have an scrollbar to look all of them instead of just guessing names.

**How to reproduce it (as minimally and precisely as possible)**:
Same as in first question.

**Anything else we need to know?**:
It was working before around v7ish, I am not sure if it is a problem with the zabbix plugin or grafana itself.

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: Grafana-Zabbix Plugin - 4.2.10 
- OS Grafana is installed on: Ubuntu 22
- User OS & Browser: Windows / Firefox, Chrome, etc.
- Grafana plugins: Grafana-Zabbix Plugin - 4.2.10 
- Others:

**Comment by usmangt** [comment]
Hi @gonzalo-,

Thanks for opening this issue.

There are some big changes (both UI and backend) from v7 to v9 of Grafana. Plus Zabbix is a community-based plugin so the best would be to first contact the Zabbix team (which I can see that you already did there).

If they filter out that it is the Grafana Explore issue then come back to us and then we can start the investigation.

**Comment by gonzalo-** [comment]
@usmangt thanks for your replied! I will update the ticket if the zabbix people give me any feedback.

**Comment by gelicia** [comment]
Hello - populating the "Item" list for this datasource is something the datasource has to take care of. I see the issue raised on their repo at https://github.com/alexanderzobnin/grafana-zabbix/issues/1570 which is perfect.

Looking at this, one thing I'm wondering is if you have the correct "Item Tag" since selecting that seems to populate the list of Items, and having Item Tag blank does not mean that all items will load. For instance, in the link you shared, the item tag "Application: CPU" has 5 items that all show up when no item tag is selected, but "component: system" has two items - one shows up when nothing is selected and one does not. Looking at the dom for this list, it isn't like there are more options that aren't being displayed and can't be scrolled through - its showing all the items. I'm not familiar with Zabbix enough to give much help beyond that. If you know a bit about how zabbix queries for items, the relevant code that populates that list is here https://github.com/alexanderzobnin/grafana-zabbix/blob/master/src/datasource/components/QueryEditor/MetricsQueryEditor.tsx#L97 

If the folks maintaining that datasource have additional input that indicates it's something on Grafana's side, please feel free to re-open this ticket.
