### ISSUE TITLE
Ability to configure staticUrl for hosting JS assets

### ISSUE THREAD

**Issue by tardyp** [grafana/grafana#6307]
- **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- What Grafana version are you using?
  GH master

I am hosting grafana server on a low upload bandwith home server, and the load time is very high (10/20s) because of the JS assets. Once the JS assets are loaded, the application is fast enough

Looking at the code it looks easy to put the static assets in another static server like S3.
Is this something impossible for un-obvious-to-me reasons?

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
