### ISSUE TITLE
API: Starring already starred dashboard returns 500 internal server error

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#63133]
Using the API to star a dashboard that's already starred returns a 500 internal server, with a SQL-ish looking error in the body:

```json
{
  "error": "UNIQUE constraint failed: star.user_id, star.dashboard_id",
  "message": "Failed to star dashboard",
  "traceID": ""
}
```

While there's not strictly a bug here, it doesn't seem great that the SQL error is bubbled up. If we intend starring an already starred dashboard to be an error, then I think it should return a more appropriate error.

I think it would also be fine to just return 200-OK if the dashboard is already starred. The request might not have altered any state, but the desired effect (the dashboard is starred) is still true. But i don't feel _super_ strongly about this.

**Comment by MTLChrisLEE** [comment]
Hi @joshhunt,

I agree with you.
The error message is misleading.

Although, I am not also sure about the status code.

Who should confirm that this issue is good to go?

**Comment by sakjur** [comment]
@joshhunt I think you're being too careful about not calling it a bug. Since it can be triggered by a user and results in an internal server error status code, I think we should call it a bug. It's hard to implement a reasonable observability strategy for thousands of HTTP requests already without 5xx status codes that aren't actually server errors 😛

**Comment by MTLChrisLEE** [comment]
Hi @sakjur,

I created a PR since you marked this as a bug.
Please, feel free to _unmark_ if you change your mind. 

Thanks!
