### ISSUE TITLE
Value Mapping is coloring text without being a match

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#63151]
When setting value mappings for a table, the mapping is applies also to values that should not be affected.
Example:
1. Under Value mappings, Set the value mapping to be colored when a certain string is found
2. under cell options, select colored text
Expected result: i expected only the cell content to be colored that match the value mapping
Actual result
Every cell in the table is being mapped even though some to not even match the mapping.

See attached screenshots

![Image](https://user-images.githubusercontent.com/110845248/217646954-daf5944c-22a2-49ec-86d1-29f150e98b45.png)

![Image](https://user-images.githubusercontent.com/110845248/217646964-75e5169f-cd82-4efb-82de-9431f917a77a.png)

**Comment by baldm0mma** [comment]
Thanks for bringing this to our attention, @supilee ! I checked into it, and it looks like wether we like it or not, the `Thresholds` colors - which default to 2, the `Base` being green, and a second that is red - kick in once you choose `Cell Type: Colored text` under `Cell Options`. Also, since you can't delete the `Base` threshold color for whatever reason, if you delete all other thresholds other than the `Base`, and then update the `Base` threshold color to `Text color`, that should provide a workaround for now.

I advise we think through how this works moving forward. If nothing else, we should default the thresholds to simply 1 `Base`, which is of color `Text color`. Doing that would remove most of the trouble you found above. I'll loop in @codeincarnate  to see what he thinks.

**Comment by supilee** [comment]
Thanks @baldm0mma.. works well.. . One more thing: the cell option selection has to be set manually. Can't we have it so that the cell value option selection is being triggered when having a value mapping with colors? With a default selection of "colored text"?

**Comment by baldm0mma** [comment]
Also a good idea. I think we should think about implementing that workflow as the default as well.

**Comment by supilee** [comment]
Closing this and will create a feature request for a modified workflow.
