### ISSUE TITLE
[Grafana Cloud Traces - search]"Span Name" search criteria seems to be ignored

### ISSUE THREAD

**Issue by cyrille-leclerc** [grafana/grafana#63197]
**Describe the bug**

When searching for traces by "Service Name" and "Span Name", the "Span Name" criteria seems to be ignored, result with completely different span names are returned.

The problem occurs whatever the span name passed in the search criteria uses single quotes, double quotes, or no quotes

![image](https://user-images.githubusercontent.com/459691/217763427-b7a178c8-7952-47c3-9a1d-abc6cdbc0642.png)

**To Reproduce**

* Persist some traces in Grafana Cloud Traces
* In Grafana Explore / Tempo, search for traces specifying the "service name" and the "span name" using as "span name" criteria, the name of a root span.
* Verify that the result only contains traces with a matching span name

**Expected behavior**

* all returned traces have a root span name that matches the search criteria
 
**Environment:**
 - Grafana Cloud Traces 2023/02/09

**Additional Context**

**Comment by 09jvilla** [comment]
Going forward do we expect this to be fixed by the "new" search experience that's powered by TraceQL under the hood?

Not saying we shouldn't fix this, but if it will be fixed starting in 9.5 and going forward, we could consider this lower priority relative to some of the other bugs @cyrille-leclerc has pointed out. 

i.e. this one? 

https://github.com/grafana/grafana/pull/63808

<img width="1065" alt="Screenshot 2023-03-22 at 11 58 26 PM" src="https://user-images.githubusercontent.com/9610816/227107588-aabb5078-333b-4999-9ebf-1e554d657ed4.png">

**Comment by 09jvilla** [comment]
@cyrille-leclerc -- I'm closing this for now since I think this is solved in the updated 'Search' experience within the Explore, but please reopen if you still see this issue.
