### ISSUE TITLE
while creating plugin,i will get error like..Plugin Error 

### ISSUE THREAD

**Issue by yuvaraj951** [grafana/grafana#6319]
Plugin Error
Error: XHR error (404 Not Found) loading http://localhost:3000/public/traceur?bust=1476854915426 Error loading http://localhost:3000/public/traceur Error loading http://localhost:3000/public/plugins/grafana-processline-panel/module.js

please help me out!!!!!

I am using grafana 3.1

**Comment by torkelo** [comment]
where is your plugin located, it most be located in the external plugins dir defined in your grafana.ini/custom.ini  (in dev env it usually at data/plugins relative to gtthub repo), when using the official rpm/deb packages the plugins dir is at /var/lib/grafana/plugins

**Comment by dylanPowers** [comment]
I was getting this exact same issue and had to look up how to rewrite the examples in ES5 by reading https://github.com/ModuleLoader/es-module-loader/blob/master/docs/system-register.md and looking into the compiled dist directories of some of the example panels like in https://github.com/grafana/clock-panel/blob/master/dist/clock_ctrl.js. Then it worked. Is this the expected behaviour? The examples in http://docs.grafana.org/plugins/developing/development/ never made that clear.

**Comment by daniellee** [comment]
@dylanPowers not sure I understand. Why did you have to rewrite it in ES5?
