### ISSUE TITLE
Saga - Typography alignment [design]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#63280]
The product has different type sizes for H1-body copy. Some are the same but some are different. We need to adjust Figma to match the product.

**Warning**
Testing will need to be done as this will most likely be a breaking change for Figma components and communicating the changes and any resulting work designers need to do will be critical.

the [createTypograhpy.ts](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/themes/createTypography.ts#L118-L127) file is the source of the styles for the product and what should be mirrored in Figma

**Comment by natydej** [comment]
Figma branch updates, waiting for review:

- Updated the text styles properties: **font-size**, **line-height** and **letter-spacing** for H1,H2,H3,H4,Body
- Removed Body bold, Small, Small Bold, and Code from the Textstyles
- Added H5, H6, Body, and Body Small for Textstyles
- Added the **rem** scale to switch from the px converter, to increase the A11y
- Changed layout guidelines to give a clearer way to read the Typography properties.

**Comment by natydej** [comment]
@staton-hyse11  Identified usage for the text styles that need to be deprecated, because there is no usage in code.


- **Body bold**
  - Button
  - Collapse
  - RadioButtonGroup
  - Field
  - Inline Banner
  - Toast
  - TopNav
  - Banner
  - FileListItem

- **Small**
  - Field
  - RadioButtonGroup
  - Breadcrumbs
  - FileDropZone
  - TopNav
  - Tooltip

- **Small bold**
  - Badge
  - FieldValidationMessage
  - Tag
  - Input
  - TextArea
- 
- **Small italic** and **Code** text styles don’t use for any components.

**Next steps:**

Revert the changes about removing some text styles and editing them instead.

**Comment by natydej** [comment]
Updates:

-Text styles updated to match product: (H1, H2, H3, H4, H6, Body, BodySmall and BodySmallBold)

-About “BodySmallBold”, I already talk with @JoaoSilvaGrafana , and it’s something that we use a lot, so we should make it a `variant` in code.

-Text styles “Small italic” and “Code” were removed because we are not using them anywhere.

-H5 Text style was necessarily added.

About all the 83 changes in this branch, just 13 are components affected, but only affects the **line-height**, so any component is broken.

I did some adjustments for the next components because of the font-size usage:

-CollapsableSection
-PageToolbar

**Next steps:** 

Add text-styles for the next components:

- [ ] Tabs
- [ ] ToolBarButton
- [ ] Badge
- [ ] FieldValidationMessage
- [ ] Tag
- [ ] TopNav
- [ ] TextArea
- [ ] Input

**Comment by natydej** [comment]
**Updates about components that need to be adjusted**

Created this [spreadsheet](https://docs.google.com/spreadsheets/d/1-DSopUUeeuzByx-FEY2sYk8RaDaNjnZm_B2P53-rhbw/edit#gid=0) where I have identified all the gaps between Figma and Storybook, need a review from @JoaoSilvaGrafana to see it on the product and then we can apply these changes to adjust components on Figma.

**Comment by natydej** [comment]
**Last Updates (ready yo merge and publish)**

Update the text-style to match the product:

-Breadcrumbs
-Megamenu 

Connect some components to text-styles:

-Tabs 
-ToolBarButton
-Badge
-FieldValidationMessage
-Tag 
-TopNav
-TextArea 
-Input 

Padding/height/gap changing to match the product:

-Buttons 
-Large / height 48px / padding 0 24px / gap 12px
-Medium / height 32px/ padding 0 16px / gap 8px
-Small / height 24px/ 0 8px / gap 4px

-RadioButtonGroup (Padding from 3px to 2px/Height to be fixed for medium 32px for small 24px)
-Select (Adjust the height to 32px)
-FilterPill (Adjust the height to 32px and border-radius to 999px)
-Menu (adjust the height to 32px)
-Field (Adjust the height to 32px)
-Badge (Adjust padding to 1px 4px/ and the height to 24px)
-ToolBarButton (Height to 32px and paddings 0 16px and gap 8px)
