### ISSUE TITLE
datasource_uid label is missing from DatasourceError alerts

### ISSUE THREAD

**Issue by akorosi** [grafana/grafana#63337]
**What happened**:
Alert was fired with `alertname = DatasourceError`, but the `datasource_uid` is not in the label list

**What you expected to happen**:
`datasource_uid ` to be in the labels list

**How to reproduce it (as minimally and precisely as possible)**:
Grafana Enterprise v.9.3.6
![image](https://user-images.githubusercontent.com/2691869/218740886-e014c7df-6380-4031-8644-8c93637812b5.png)

![image](https://user-images.githubusercontent.com/2691869/218741074-00311c58-3c86-4cbd-8117-6ceff65cf8c0.png)
**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana Enterprise v.9.3.6
- Data source type & version: Mimir (latest)
- OS Grafana is installed on: AWS ECS Fargate, Ubuntu parent docker image
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by grobinson-grafana** [comment]
I think what's happening is that Grafana is not annotating the Dashboard UID for `plugin.downstreamError` errors, just `expr.QueryError`. We will investigate this, thank you for opening this issue!

**Comment by yuri-tceretian** [comment]
George is right, the expression engine returns unwrapped error when data source plugin retuns error 
https://github.com/grafana/grafana/blob/426fab32ebd48a9a395cc7febc91aefbdfa6b8bc/pkg/expr/nodes.go#L239-L242 
instead of response.
If error comes from response 
https://github.com/grafana/grafana/blob/426fab32ebd48a9a395cc7febc91aefbdfa6b8bc/pkg/expr/nodes.go#L246-L248
then it is wrapped correctly, and alerting correctly handles this error.

There were many changes in Prometheus plugin, so perhaps https://github.com/grafana/grafana/pull/48477 changed this to return error instead of the response.
But recently, that code was refactored https://github.com/grafana/grafana/pull/62254 and now we have error in the response and it works as expected.

That's said. I think we should not be dependent on the error propagated from upstream. I think the expression engine should reliably provide information about what data source failed.

**Comment by yuri-tceretian** [comment]
I can confirm that this was the case in Grafana 9.3.6. I tested a few versions including the latest 9.5.2 and the issue was fixed since 9.4.0
