### ISSUE TITLE
Release: Version stamps in the 9.2.10 tarball and repo tag v9.2.10 are still all "9.2.8"

### ISSUE THREAD

**Issue by youattd** [grafana/grafana#63345]
**What happened**:  Attempted build from source from both the source tarball for 9.2.10 and from a local git repo with v9.2.10 checked out.  Binaries report version 9.2.8

**What you expected to happen**:  Expected to see version 9.2.10 reported by the binaries.

**How to reproduce it (as minimally and precisely as possible)**:  Download the 9.2.10 source tarball and build the product.  Or checkout tag v9.2.10 and build from source.

**Anything else we need to know?**:  
* The grafana/CHANGELOG.md has last update at version 9.2.7
* `grep -rF 9.2.8` of the 9.2.10 source shows many version vars assigned "9.2.8" rather than "9.2.10"
* Near the end of the build log, there is a `go build ... ldflags ... "9.2.8"`
* 9.2.10 release download files are not marked as Verified.

**Environment**: RHEL9 build from source
- Grafana version: 9.2.10
- Data source type & version:  9.2.10 source tarball or tag v9.2.10 from the git. repo
- OS Grafana is installed on:  RHEL9
- User OS & Browser: any
- Grafana plugins: any
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @youattd 

confirmed that checking out the v9.2.10 tag and building from source still shows 9.2.8 in the UI.

Curious @youattd,

Why build that version from source?

**Comment by youattd** [comment]
@zuchka Thank you for confirming.  We need to build internally for the CVE that is fixed in 9.2.10

**Comment by kminehart** [comment]
Sorry for the late response. We're working on improving our build process so that these things don't get missed. As you can probably guess by the amount of weirdness you're experiencing here, it's a manual and laborious process.

Most of this comes down to:
* The changelog is generated from pull requests and there weren't any pull requests for these CVE fixes since they were done in a private mirror.
* The version is generated from the version in package.json, which was not updated appropriately before this release was created.
* The 9.2.10 release was likely unverified because the tag was not signed with GPG appropriately.

Your feedback is valuable and helps us in our future releases. Sorry for the inconvenience!
