### ISSUE TITLE
Property 'children' does not exist on type 'CustomScrollbar.Props'

### ISSUE THREAD

**Issue by barnettZQG** [grafana/grafana#63395]
**What happened**:

![image](https://user-images.githubusercontent.com/18493394/219573766-748588fc-2622-4e01-83d0-fe5d9ae59686.png)

I'm developing a Grafana plugin and use the CustomScrollbar component, which is in the `grafana-ui` package. Because of the typescript error, I can not build the plugin.

**What you expected to happen**:

The props of the CustomScrollbar should include a property named children.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by stefan-toubia** [comment]
Same issue with `ControlledCollapse`

**Comment by JoaoSilvaGrafana** [comment]
Hi @barnettZQG thanks for raising this and sorry for the delay in replying. Could you let us know which version of grafana/ui you are importing? Because this should work as of [version 9.3.0](https://github.com/grafana/grafana/pull/56898/files#diff-13e9e8473d43a1f7729287cc3347205c45c2e2c5afa830caf6f5c59b4b9b289e) when it was changed from using `FC<Props>` to `React.PropsWithChildren<Props>`, since as of React 18 `React. FunctionComponent` no longer automatically adds `children`. So let us know if you are using a version post 9.3.0 and still getting this error.

@stefan-toubia It seems this would still be a problem with `ControlledCollapse` as it is still using `FunctionComponent` there. I will create a separate issue for it 👍
