### ISSUE TITLE
Unable to edit Teams message template with images

### ISSUE THREAD

**Issue by andrearota** [grafana/grafana#63464]
**What happened**:
We have successfully set up a Teams connector to send alert notifications to a specific channel, and have integrated Azure Blob storage as an external image provider. However, we now need to modify the message template to better suit our needs while still retaining the image functionality.

We cannot find a way to include the image in the new template.

**What you expected to happen**:

I expected to have a template data element to embedd the image uploaded in the Azure Blob Storage.

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure Azure Blob store as external image provider
2. Create an alert
3. Setup and test a Teams contact point

**Anything else we need to know?**:

If we try to specify a template, the Teams connector does not send messages anymore, with no error in logs.

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: PostgreSQL 12
- OS Grafana is installed on: Kubernetes (grafana/grafana image)
- User OS & Browser: Edge running on Windows
- Grafana plugins: none
- Others:

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @andrearota 

>Setup and test a Teams contact point 

when testing, what happens [if you use a predefined test notification instead of a custom message](https://grafana.com/docs/grafana/latest/alerting/manage-notifications/create-contact-point/#test-a-contact-point). Does the message reach the Teams contact point?

> If we try to specify a template, the Teams connector does not send messages anymore, with no error in logs.

no logs even after you have enabled[ debug mode](https://grafana.com/docs/grafana/v9.0/troubleshooting/) ? 

in addtion, could you please share your image rendering config and what [configuration method](https://grafana.com/docs/grafana/next/setup-grafana/image-rendering/#configuration) you opted for?

thanks in advance!

**Comment by andrearota** [comment]
Hi, we are investigating a little further and it seems more related to an error while generating the screenshot. We are investigating but we found a missing log entry as documented in https://github.com/grafana/grafana/issues/63791

**Comment by tonypowa** [comment]
thanks for the info @andrearota 
it seems that you found the culprit in the linked issue!
please let us know if it's okay to close this one

**Comment by andrearota** [comment]
The error was that I used quotes in my docker-compose.yml and basically I was not loading the component that makes screenshot.

We can close this issue, thanks.
