### ISSUE TITLE
Input: error-state does not work as expected

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#63515]
When the input field is resized w/ placeholder text, switching to the error state reverts it back to the original size, and removes the placeholder text.

Expectation: Keeping the resized field and placeholder text 

https://user-images.githubusercontent.com/5264102/220417085-a338558a-04de-4bf9-951c-4298afd7531f.mov

**Comment by natydej** [comment]
Merged and published the Figma branch with these updates:

- Updated invalid and invalid + focus variants to fill container instead of fixed width
- Updated text layers so text persists to invalid and invalid + focus
- Updated variant state naming to match table naming
- Updated width from 200px —> 240px to be divisible by 80

  **Next steps:**
  - Create the documentation guidelines for this component.
