### ISSUE TITLE
Grafana time/date bar has unusable jitter

### ISSUE THREAD

**Issue by davidbhoward** [grafana/grafana#63530]
**What happened**:  
While using Grafana with both Prometheus and Loki data sources, the date time and Run query bar at the top jitters are quite hard to see and use.

Here is a screen recording of the problem:
https://user-images.githubusercontent.com/11968222/220461165-6eefa092-5bb1-4648-b55b-faf12c3fd977.mov

**What you expected to happen**:  
I would expect the bar to stay static, not move when not selecting options.

**How to reproduce it (as minimally and precisely as possible)**:  
I am able to reproduce the problem when I use Google Chrome with a zoom of 100% (normal or reset).   I am on a MacBook pro with resolution scaled to the middle (3840 x 2160), 60 Hertz, external 27" monitor Dell S2721QS.

**Anything else we need to know?**:  
There is a workaround for this and it is to zoom in on the browser.  Once you zoom and stay there, the issue goes away.  If you zoom back out, it starts to jitter again.

**Environment**:
- Grafana version: v9.3.6 (I had this problem before years ago and now it seems like it has come back in the recent past...we just upgraded to this version)
- Data source type & version: Prometheus and Loki...but doesn't matter what data source
- OS Grafana is installed on: Linux (but doesn't seem Grafana server related but rather browser assets
- User OS & Browser: macOS Monterey (12.5.1), Google Chrome Version 98.0.4758.80 (Official Build) (x86_64)
- Grafana plugins: Several, but doesn't seem related to plugins.
- Others:

**Comment by scrhobbs** [comment]
I'm getting same issue on v9.4.3 and a fresh install of v9.3.1 with no dashboards set up yet. 
I believe its been happening since we went up to 9, and its getting very annoying now. 
I have checked with both Chrome 91.0.4472.124 and Edge 93.0.961.47 , and its same on both. 
I'm accessing via Citrix, and can't upgrade to a newer browser, so this might be the issue, but I have no way to test.

**Comment by tonypowa** [comment]
hi @davidbhoward  and @scrhobbs 

it's been awhile since you opened/commented this issue, apologies for that 🙏 

can you please update to latest version of your browsers and try again?

>I'm accessing via Citrix, and can't upgrade to a newer browser

let's see if the issue persists for @davidbhoward david once he updated , and we will now if the above is true for you @scrhobbs 

note: older versions of these browsers [might not be supported](https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-web-browsers)
