### ISSUE TITLE
Support Redis or Memcache for Caching on Grafana Server

### ISSUE THREAD

**Issue by willneumob** [grafana/grafana#6358]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?  Latest
- What datasource are you using? Graphite, ElasticSearch
- What OS are you running grafana on? Ubuntu 16.04
- What did you do? Click the Dashboards dropdown.
- What was the expected result? Instant dashboard list!
- What happened instead? Wait 30 seconds.

Hello,

I've noticed as we start to build more complex dashboards, that certain parts of Grafana really slow down. My initial thought was "oh, I probably forgot to configure caching", so I search the docs for Memcache and Redis, and it seems, they are only supported for session storage. Couldn't things like dashboard metadata be cached in Redis pretty easily? I would expect things like navigation dropdowns to be instant. So, the feature request, is to support caching on the Grafana server itself with Redis.

Thanks!

**Comment by torkelo** [comment]
Grafana is pretty instant, never seen a report of Grafana being slow yet. Graphs and panels can be slow to load data from the time series store (Graphite / ES), but that there is not much Grafana can do about the TSDB backend being slow. Graphite has memcache which can speed things up (as well as a good SSD), Elasticsearch has numerous ways for you to increase performance. 

There was a report for slow dashboard search on MySQL, this is fixed in master / v4 nightly build. It was due to missing index, with the new index dashboard search is 3-8 ms with about 3000 dashboards.

**Comment by scharissis** [comment]
If many people are viewing/refreshing the exact same dashboard with the same time-ranges, then won't they all be querying the datastore for the same information?
Thus, if Grafana-server cached this, the performance could be improved.

So this seems like a valid request? At least, in spirit?

**Comment by athenot** [comment]
There's another use-case for caching: when going back and forth between several dashboards, the data has to be re-fetched every time. Not every time series store is instant. :)

**Comment by NorseGaud** [comment]
Did anyone get any solid solutions for caching?

**Comment by cznewt** [comment]
F
