### ISSUE TITLE
AzureMonitor: Invalid series names when multiple time series are returned from a metrics query

### ISSUE THREAD

**Issue by aangelisc** [grafana/grafana#63633]
A query that returns multiple time series does not display labels that are informative to the user. The labels returned should be descriptive enough for a user to distinctly identify each series.

![image](https://user-images.githubusercontent.com/15019026/220911586-7ea6f4b1-662c-4915-8628-748e47ccf2be.png)

**Comment by ashutosh887** [comment]
@aangelisc I would like to work on this

**Comment by aangelisc** [comment]
Hi @ashutosh887, please feel free to pick this up. The contribution guidelines [here](https://github.com/grafana/grafana/blob/main/CONTRIBUTING.md) should provide information on where to start 😊

**Comment by ashutosh887** [comment]
Please assign the issue to me @aangelisc Sir

**Comment by ashutosh887** [comment]
@aangelisc can you share how can I replicate the issue in mine?
Or suggest me where are the changes required

**Comment by aangelisc** [comment]
Hi @ashutosh887, if you execute a query similar to the one displayed in the image in the original issue comment you should be able to see the invalid series names returned 😊

**Comment by Blackbaud-ChrisBlythe** [comment]
@aangelisc @ashutosh887 Any updates on this? Unfortunately, I opened the issue above before realizing this one already existed.

Also, FWIW... This was working correctly in v9.3.6, and this incorrect behavior only showed up after upgrading to v9.4.7. Since both versions used v1.0.0 of the Azure Monitor datasource, I suspect this is NOT an issue with the Azure Monitor datasource.

**Comment by aangelisc** [comment]
@Blackbaud-ChrisBlythe I have a PR open to fix this bug which will be released in the next version of 9.5.x once merged 😊
