### ISSUE TITLE
Error creating alert rules

### ISSUE THREAD

**Issue by Daniel100262** [grafana/grafana#63770]
**What happened**: When adding an alert rule using Zabbix as a data source, no matter which field tries to be filled in, the error below is returned:

![image](https://user-images.githubusercontent.com/6551994/221339213-a786c9f7-fbdf-4473-bba3-2573dca40733.png)

**What you expected to happen**: Select Zabbix group, host and item with success

**How to reproduce it (as minimally and precisely as possible)**: Create a Zabbix datasource, go to Alert Rules > New Alert Rule > select Zabbix as datasource and try to select group from combobox.

**Anything else we need to know?**: Grafana has been updated from version 8.x two months ago.

**Environment**:
- Grafana version: [v9.3.6 (978237e7cb)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
- Data source type & version: Zabbix plugin version 4.2.10
- OS Grafana is installed on: Ubuntu Server 20.0.4 LTS
- User OS & Browser: Ubuntu Desktop 22.04 Google Chrome 104
- Grafana plugins: Zabbix plugin version 4.2.10
- Others:

**Comment by mellieA** [comment]
@Daniel100262 the zabbix datasource is community supported. I see that other users were having a similar problem and it resolved when they used version 9.2.x of grafana https://github.com/grafana/grafana/issues/60432. 

Because the issue only occurs with the zabbix plugin, I'd suggest to add your feedback to the issue in the zabbix repository here: 

https://github.com/alexanderzobnin/grafana-zabbix/issues/1562
