### ISSUE TITLE
unable to change font size of text panel

### ISSUE THREAD

**Issue by rlonberg** [grafana/grafana#6389]
- [ ] Bug report

grafana 3.1.1

Reproduce procedure.
1. Open "Dashboard" 
2. Add "text" from "Add Panel"
3. Open the "Edit" view
4. Select "Edit Text" tab and set the mode to "text"
5. Change the "Font Size" and see the "text"

The size of string displayed in the "text" isn't changed when changing "Font Size".
The displayed string size should be changed following the "Font Size".

**Comment by torkelo** [comment]
The text panel's font size option has been broken for a very long time, with only 2 users having reported it. So the text panels "text" mode seems to be very rarely used, and seems like an unnecessary option given how flexible the markdown and html options are. So instead of merging this PR I actually removed the text option in an effort to remove an option that is extremely seldom used.
