### ISSUE TITLE
Alerting: error lingers in the GUI in contact point even if it's no longer relevant

### ISSUE THREAD

**Issue by lethargosapatheia** [grafana/grafana#63961]
**What happened**:
Error is displayed on the UI in the contact points tab even if it doesn't apply anymore.

**What you expected to happen**:
The error should disappear.

**How to reproduce it (as minimally and precisely as possible)**:
Probably create the circumstances for grafana not to be able to connect to the contact point. In my case the email service was temporarily disabled.

**Anything else we need to know?**:

<img width="1126" alt="error_lingers" src="https://user-images.githubusercontent.com/22618815/222207527-03b6dc0d-a607-425a-b6fd-eaed9614aae9.png">
As you can see in the screenshot, the error occurred 3 hours before.

Sending a test alarm to that contact point works without any issues.

**Environment**:
- Grafana version: 9.4.1
- OS Grafana is installed on: Kubernetes
- User OS & Browser: Mac OS Ventura 13.2 / Firefox 110.0
- Grafana plugins: none

**Comment by lethargosapatheia** [comment]
It disappeared after maybe 4 hours. Could this be related to the default repeat interval of 4 hours for alerts? Even if that's the case, does it make any sense for the error notification to linger there?

**Comment by santihernandezc** [comment]
Hi @lethargosapatheia, just to be clear, the behavior you saw was:
1. A notification failed to be delivered due to the email server being disabled.
2. The error appeared in the UI.
3. You tested the contact point using the "Test" feature and no error occurred.
4. No further notifications were sent.

If that's the case, then that's the expected behavior. A notification could fail due to reasons specific to your alert rule, so we can't clear an error after a test notification succeeds. When an actual notification (i.e. one that results from an alert evaluation) succeeds, then the error would be cleared.

> It disappeared after maybe 4 hours. Could this be related to the default repeat interval of 4 hours for alerts?

Yes, totally.

**Comment by santihernandezc** [comment]
This looks like the expected behavior for this feature.
