### ISSUE TITLE
Slack notifications are repeated in Mattermost

### ISSUE THREAD

**Issue by leitmori** [grafana/grafana#64079]
**What happened**:
When using the Slack integration of Grafana Alerting in Mattermost, alerts are repeated according to the group interval, as Grafana incorrectly assumes that the notification was not sent successfully. Issue exists since upgrading Grafana from an older version to v9.4.2.
```
logger=ngalert.notifier.slack t=2023-03-02T19:45:11.745411891Z level=error msg="Failed to unmarshal response" body=ok err="invalid character 'o' looking for beginning of value"
logger=ngalert.notifier.slack t=2023-03-02T19:45:11.745663447Z level=error msg="Failed to send Slack message" err="failed to unmarshal response: invalid character 'o' looking for beginning of value"
logger=alertmanager org=1 t=2023-03-02T19:45:11.745821515Z level=error component=alertmanager orgID=1 component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="Slack/slack[1]: notify retry canceled due to unrecoverable error after 1 attempts: failed to send Slack message: failed to unmarshal response: invalid character 'o' looking for beginning of value"
```
The following screenshot shows the error for a test notification:
![Screenshot 2023-03-02 at 20 32 35](https://user-images.githubusercontent.com/29522608/222562642-fcd20dd6-1e0f-4fb4-9de3-75f3a8f9e7a7.jpg)

**Environment**:
- Grafana version: v9.4.2
- Mattermost version: v7.8.0

**Comment by UnrealCraig** [comment]
We also use MM and are seeing alerts repeated as per the group interval since upgrade to Grafana 9.4.3 today

**Comment by mellieA** [comment]
@UnrealCraig @leitmori are either of you seeing repeated alerts when sending directly to slack?

I've seen that some users use the slack compatibility feature of mattermost to receive alerts there and configure grafana's slack contact point to send to the mattermost URL. However, that's not a configuration that we test and the problem could potentially be how mattermost is acknowledging the alert in a different way than Grafana alerting expects to receive it from slack. 

If you're seeing this issue occur connecting directly connecting to slack, then that is something we could look further into.

**Comment by UnrealCraig** [comment]
No, we don't use slack, I also know many other projects / companies that use the slack option in Grafana to send notifications to MM. This worked perfectly until 9.3.x but misbehaves since 9.4.x
It's unrelated to MM version (tested with different MM servers)
If you intend for the slack plugin to no longer be compatible with MM then can you please bring back your previous version of slack plugin ( <= 9.3.x ) and just rename it as Mattermost plugin?

**Comment by leitmori** [comment]
+1

**Comment by tomtpc** [comment]
+1, we encounter this problem too, also using Slack option to send Grafana's alerts/notification to MatterMost. It just recently appear when we upgrade from 9.3.x to the new 9.4x version.

**Comment by bfontaine** [comment]
We have this problem as well; going back from 9.4.3 to 9.3.8 "fixed" the issue for now.

I’m not familiar with Grafana’s code base, but after some fiddling I think I found the culprit.

Here is the response from Mattermost when you call an incoming webhook:

```
HTTP/2 200 
content-type: text/plain
vary: Accept-Encoding
content-length: 2
date: Wed, 15 Mar 2023 09:28:55 GMT

ok
```

Here is the response from Slack:

```
HTTP/2 200 
date: Wed, 15 Mar 2023 09:34:56 GMT
server: Apache
vary: Accept-Encoding
content-type: text/html
x-powered-by: HHVM/4.153.1
content-length: 2
via: 1.1 slack-prod.tinyspeck.com, envoy-www-iad-vqqq, envoy-edge-fra-gwno

ok
```

(in both cases I removed some headers to reduce the noise)

The response from Slack works, but the one from Mattermost doesn’t. Beside some irrelevant headers, the only difference is that Slack (wrongly) says it’s `text/html` while Mattermost says it’s `text/plain`.

To validate the hypothesis that this header is the issue, I created [a gist](https://gist.github.com/bfontaine/a84f9f95f35f968dbf9957757ca38835) that you can use to reproduce the issue.

Setup:
```bash
git clone https://gist.github.com/bfontaine/a84f9f95f35f968dbf9957757ca38835 && cd a84f9f95f35f968dbf9957757ca38835
chmod u+x server.sh
./server.sh
```
You can also copy the files from the gist by hand. The "server" is a while loop with `netcat` listening on port 1234 and alternatingly responding with the content of `mattermost-response` (response with `text/plain`) and with the content of `response` (exact same content except that `text/plain` is replaced with `text/html`).

1. Go to the "Create a new contact point" page in Grafana
2. Choose the "Slack" integration
3. In the "Webhook URL" field, enter http://localhost:1234 (assuming you launched the server.sh on the same host as Grafana)
4. Click on "Test", then "Send test notification"

The first time you send a test notification, `netcat` responds with an `text/html` header and it works. Now if you hit "Send test notification" again, it responds with a `text/plain` header, and it fails. You can hit the button again to see how it alternates success and failure.

Now, diving into Grafana’s code base, I assume the code responsible for this part is here: https://github.com/grafana/grafana/blob/v9.4.3/pkg/services/alerting/notifiers/slack.go#L378-L405

However, after carefully reading it multiple times, I don’t see anything related to a content-type header. If the `body` is the string "`ok`", the first `if` won’t match (because `json.Valid("ok")` is `false`), and neither will the second (because `rslt.Ok` is false due to the failed unmarshaling). The issue must be elsewhere, but I don’t know where.

**Comment by m4r1u2** [comment]
We had the same problem as described above. Going back to our previous version (9.3.6) corrected our Mattermost notification issues

**Comment by Sallaxer** [comment]
Same problem.
Mattermost: 7.7.1
Grafana: 9.4.3

**Comment by bfontaine** [comment]
This header is set since [at least Mattermost 3.0.0](https://github.com/mattermost/mattermost-server/commit/9ac6bc50299e6931315a6088bd9ff680bdcb8f61#diff-f0ae69dd66c106c255eb284044155aaa493ad2a6af3dfc987b7a78fa93a8aeceR441) so yes, you’ll have the same problem with pretty much any version of Mattermost and Grafana 9.4.2+.

**Comment by Sallaxer** [comment]
> This header is set since [at least Mattermost 3.0.0](https://github.com/mattermost/mattermost-server/commit/9ac6bc50299e6931315a6088bd9ff680bdcb8f61#diff-f0ae69dd66c106c255eb284044155aaa493ad2a6af3dfc987b7a78fa93a8aeceR441) so yes, you’ll have the same problem with pretty much any version of Mattermost and Grafana 9.4.2+.

Ok, thx, waiting for fix in new versions of Grafana?

**Comment by a-gerhard** [comment]
+1

**Comment by UnrealCraig** [comment]
Why is the fix not included in the 9.5.1 release?
It shows as being in the 9.5.0 milestone; did another commit regress this fix?

**Comment by Makasuro** [comment]
Grafana 9.5.1 still have this bug

**Comment by leitmori** [comment]
@yuri-tceretian Can you fix the regression?

**Comment by Sallaxer** [comment]
In 9.4.9 bug fixed

**Comment by Makasuro** [comment]
Indeed, 9.4.9 works. Hope 9.5.2 will too

**Comment by yuri-tceretian** [comment]
https://github.com/grafana/grafana/pull/67541
