### ISSUE TITLE
UI Freeze in Create Alertrule from this panel view

### ISSUE THREAD

**Issue by KacperLegowski** [grafana/grafana#64110]
**What happened**:
After I clicked `Create alertrule from this panel` and try to change type of expression or remove an expression UI is getting freeze and I can't even close the browser tab.
It does not happen if I choose panel with other datasource (Tested on Google Cloud Monitoring) 
![image](https://user-images.githubusercontent.com/21225629/222681030-755d5909-05e3-40cc-ab4e-0b312c69cd18.png)

**What you expected to happen**:
Change or remove alert rule expression

**How to reproduce it (as minimally and precisely as possible)**:
1. Open dashboard
2. Go into Alert tab
3. Clik 'Create alertrule from this panel'
4. Get UI freeze

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: Graphite 1.1.x
- User OS & Browser: MacOS ventura 13.2.1, Chrome 110.0.5481.177

**Comment by gillesdemey** [comment]
Thanks for reporting, we've been trying to reproduce this on our end with no success so far – do you have any additional information for us?

You mention it only occurs with the "Google Cloud Monitoring" data source selected, is that correct? If yes it might be related to the data source editor and not alerting.

**Comment by KacperLegowski** [comment]
It only occurs with Graphite, works with Google Cloud Monitoring.

**Comment by KacperLegowski** [comment]
What additional information may you need for the investigation?

**Comment by KacperLegowski** [comment]
@gillesdemey ?

**Comment by gillesdemey** [comment]
I've taken another pass at trying to replicate this on my local machine with the following setup:

**Grafana version**: 9.4.3
**Data source type & version**: Graphite 1.1.x

I've created a panel in a dashboard using the Graphite datasource, and changed the expression type after the initial page was loaded. I've not noticed any UI freezing or crashes, and I couldn't find any errors in the console either.

Are there any steps I've missed here to reproduce? Are there any errors in your console environment?

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/868844/224349684-0de47f71-cf9f-42b0-97c2-74b4a78a0ad0.png">

**Comment by filip-aipl** [comment]
Ok, so I've unfortunately stepped into this and it is not completed nor resolved. This issue still occurs and we can't do anything about it. 
#### What is actually going on?
I have a target based on Graphite datasource. The target works on Grafana 9 and also on Grafana 7. Everything works perfectly, no issues with displaying it. 
Problem occurs when I am trying to create an alert based on the selected TimeSeries in Grafana 9. When I click anything in the Alert Rule creation UI, everything freezes. 
It can be hacked around by creating manually alert from clear template, not based on a panel.
I can send you a quick video with this situation happening. 

grafana:9.5.1
tested on chrome & safari

@gillesdemey 
@armandgrillet

**Comment by piotrszacinski** [comment]
Hi,

The issue still persists and it's easily reproducable on our end on both Chrome (Version 120.0.6099.216 (Official Build) (arm64)) and Safari (Version 17.2.1 (19617.1.17.11.12)).

There is something broken with dropdown selector. We have tried to debug it further but the whole tab gets frozen and we cannot get any details from the debugger.
The only one thing we have spotted which may help you with further investigations is that strange things happen with `/find` endpoint. When everything works it's just called once but in this case it's called 5 times. However requests are never finished as the app gets frozen.

This may be a root cause or just a result - hard to say but I hope it could be a starting point for your investigation.


<img width="533" alt="Screenshot 2024-01-19 at 11 57 27" src="https://github.com/grafana/grafana/assets/97895048/9bd9b142-e250-415a-afee-0c10f9f820ba">
<img width="1320" alt="Screenshot 2024-01-19 at 11 05 03" src="https://github.com/grafana/grafana/assets/97895048/eb1df2e6-b374-4bd1-988f-075040ba5fc3">
<img width="1030" alt="Screenshot 2024-01-19 at 11 11 58" src="https://github.com/grafana/grafana/assets/97895048/768f4224-9bca-480a-9ca7-455fb78ea479">

Please let me know if there is anything more we could to to help you debug it.

Regards

**Comment by KacperLegowski** [comment]
@gillesdemey @armandgrillet More context added

**Comment by cypreess** [comment]
+1 happens to me as well.
