### ISSUE TITLE
Can't edit queries on a panel if they're using an undefined datasource

### ISSUE THREAD

**Issue by farnoy** [grafana/grafana#64194]
**What happened**: I upgraded my Prometheus & Grafana setup some time ago and noticed recently that I can't edit the existing dashboard that I had there. I was unable to expand the query row when editing a panel, nothing would show up there.

**What you expected to happen**: I expected the query editor to render

**How to reproduce it (as minimally and precisely as possible)**: Update your dashboard JSON in place and mess up the `uid` of a Prometheus data source, that should make the query editor not render at all.

**Anything else we need to know?**: The query editor does not get rendered in HTML at all, see screenshot - query A is the old one pointing at an old `uid` of a datasource, query B was created in the editor as a new query. DOM element `#A_19` is empty where it should contain an editor.
![image](https://user-images.githubusercontent.com/345808/222993914-c9090edb-9b57-4ccf-af95-15082ed07b77.png)

It's strange that the queries still execute just fine, despite being configured to use outdated datasource `uid` for Prometheus. It's only the editing that's broken.

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: Prometheus 2.41.0
- OS Grafana is installed on: NixOS 22.11
- User OS & Browser: Windows 11 Firefox
- Grafana plugins: -
- Others:

**Comment by polibb** [comment]
Hi @farnoy 👋, there are two separate problems I read here:

1. _I upgraded my Prometheus & Grafana setup some time ago and noticed recently that I can't edit the existing dashboard that I had there._ 
Is this connected to https://github.com/grafana/grafana/issues/64123? Meaning, do you see a weird UID for the datasource after upgrading? If it seems like it is, can you tell us more about the upgrading?
Which version to which version?
Can you share the dashboard JSON you are using, with all sensitive details removed? 

2. _Update your dashboard JSON in place and mess up the uid of a Prometheus data source, that should make the query editor not render at all._
This is fixed by https://github.com/grafana/grafana/pull/62617 😊. When the UID does not refer to a real datasource or is missing, the query will default to the set default datasource, instead of not rendering.
It will be released in all 9.4. and above versions next week.

**Comment by farnoy** [comment]
Hi Polina,

1. From what I could gather, this was an upgrade from 9.3.1 to 9.3.6
```
$ nix run nixpkgs#nix-diff -- (nix eval --raw .#nixosConfigurations.eridanis.c
onfig.system.build.toplevel.drvPath)  /run/current-system | rg grafana
          - grafana-9.3.1
          + grafana-9.3.6
```

But I also changed my setup to use Grafana Provisioning for this Prometheus datasource, so that seems to be the more likely reason behind the UID change. Note that I'm still on 9.3.6, so the issue you linked about upgrading to 9.4.3 is probably unrelated.

2. That's great news, I'm OK with closing this issue since it's a duplicate of #63904

**Comment by polibb** [comment]
Thank you for the quick response, @farnoy 🙌.
This is indeed great, I hope everything is alright with the setup you have now after you get a hold of the fix we have pushed for next week. I'll close this issue and if there's something in the future we're here to help.
