### ISSUE TITLE
Color Schema Not available in Grafana Time Series Graph

### ISSUE THREAD

**Issue by tusharecmc** [grafana/grafana#64216]
**What happened**:
I am trying to use timeseries Graph to display number of command getting executed by particular user. But It is assigning single color to all the entries. This is how my graph looks like.
![1](https://user-images.githubusercontent.com/22578147/223078216-2945b0f9-792a-4b95-9747-d507ff54544c.PNG)

And this is sample how my table view looks like

|name     |    count   | timestamp            |
|---------|------------|----------------------|
|abc      |      2     | 2023-02-13 06:14:00  |
|bcd      |      5     | 2023-02-13 06:20:00  |
|xyz      |      3     | 2023-02-13 06:31:00  |
|xyz      |      7     | 2023-02-13 06:45:00  |

I have already selected classic palette for color schema

**What you expected to happen**:

I was expecting that It would assign different Colors to name values

**How to reproduce it (as minimally and precisely as possible)**:
With the same table you can reproduce it

**Anything else we need to know?**:
 Same query and Table was working fine in Grafana 6

**Environment**:
- Grafana version: 8.5.13
- Data source type & version: PostgreSQL(9.5.25)
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Windows 10 (Google Chrome)
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@tusharecmc you can see examples of the bar chart at https://play.grafana.org/d/ktMs4D6Mk/5-bar-charts-and-pie-charts?orgId=1&editPanel=15 for release (9.4.3)

I noticed you upgraded from grafana 6. The table panel [changed between release 6 and 8](https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v7-0/#table-panel). What you are noticing could be due to the migration.

For questions, we ask users to use our community forum. When opening your question, its helpful to add details like your panel settings or panel JSON.
