### ISSUE TITLE
[Bug Alerting Graphite]: Transform time intervals to graphite time intervals in query (5m -> 5min)

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6423]
- **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Master branch
- What datasource are you using? Graphite
- What OS are you running grafana on? MacOS
- What did you do? I wrote a Graphite query with "hitCount" function and created an alert for it.
- What was the expected result? "Test Rule" should have resulted in true/false depending on the result of the alerting result handler.
- What happened instead? 500 Internal Server Error from Graphite.

The catch is that the metric (containing "hitcount" function) is giving the correct datapoints back to the graph and datapoints are plotted on the graph without any issues . But when alert is test for the same query, it results in "500 Internal Server Error". Looks like Graphite alert checks are missing something.

**Comment by torkelo** [comment]
Think it's the use of `hitcount(1m)` that is causing the issue, `1m` is not a valid graphite time range, but this is fixed in the fronted datasource code to normalize timerange syntax between data sources, 1m is replaced with 1min. This is done in the backend for the query time range but the replace logic is not done on time ranges in the actual query.

**Comment by utkarshcmu** [comment]
You are right! hitcount(1min) is not making Graphite throw any error.
