### ISSUE TITLE
Gauge Panel with multiple guages - Threshold Value of Lower Gauge shown differently when value is configured for 'Last' vs 'Total'

### ISSUE THREAD

**Issue by yajrendrag** [grafana/grafana#64274]
**What happened**:
I have 2 guages in a panel - when the value is configured to show the last value, the threshold values seem to be applied in a way that the lower value guage (right side) shows up as a correct percentage of the larger value guage  (left side) - giving a nice visual indicator of how the right hand value compares to the left hand value.  But if the value is configured to show the Total value instead,  the threshold values of the lower threshold seems disconnected from the upper threshold value's guage.  Threshollds are specified as percentages.  See Graphics below.

**What you expected to happen**:
I would expect for the two scenarios to behave the same way.
**How to reproduce it (as minimally and precisely as possible)**:
Create any series of data - column A is a list of items for which you want to show two metrics - columns B and C show the two  metrics. In this case, column A is a media recording and column B is the file space required in one scenario and Column C is the file space required in a 2nd scenario.  Produce a gauge view of the two columns of numbers - in a single panel.  In one case, use the Total for the values in the gauges, in another case, use the Last value for the values in the gauges.

![image](https://user-images.githubusercontent.com/5522635/223303137-666aa2e7-182a-428f-9026-c951252b200a.png)

This image uses the Last Value.  Notice that Max (under standard options is left as default) and notice that the green bar is approximately at 40% of the guage and colored green (because it's under the threshold percentage value).  And the left hand guage is shown at 100% - as it's the larger of the two cases and so uses 100% relative to the larges number of the two columns.  and it's red as it exceeds the upper threshold value.

Now, if i switch the gauge value to use Total instead of Last - here's what the gauges look like without any changes to the right hand panel:

![image](https://user-images.githubusercontent.com/5522635/223303761-3b6cafa1-a4c7-4e44-ae60-a62c5eabcf1a.png)

Notice here that both gauges are now red even though the right hand gauge is numerically still about 40% of the left hand gauge.  To me, this should have produced the same graphical view that the first image shows just with total values instead of last values.

In both cases the threshold values were set to:
 
![image](https://user-images.githubusercontent.com/5522635/223304136-44cb5c84-bf4a-4273-bddd-e1da5ff0daa0.png)

I stumbled across this accidentally because originally my data source was mysql and the database was set up to track the cumulative totals of the two columns, so it was simple to just select the "last value" for the calculation field in the right hand panel.  However, i'm trying to not use mysql and just pull data from the logs and when i do it this way, there is no cumulative value available - only individual metrics - and when i picked total value for the calculation i was surprised at the differing behavior.

**Anything else we need to know?**:
I can force the view to look "correct" when using Total Values by entering in the max value of the left hand guage into the Max field of standard options, but this is not automated well.

**Environment**:
- Grafana version:9.3.6
- Data source type & version:Grafan Loki 2.7.3
- OS Grafana is installed on: Ubuntu 22.04 via Docker
- User OS & Browser: MacOS Chrome and Safari, Ubuntu 22.04 Chrome
- Grafana plugins: Loki, Mysql, JSON API
- Others:

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @yajrendrag 

I'm forwarding this issue to the User essential's squad for review

**Comment by ashharrison90** [comment]
hi @yajrendrag 👋 

believe this is the same issue as outlined in https://github.com/grafana/grafana/issues/60797
although it's slightly confusing, it is working as designed.

by transforming the data **before** it reaches the panel (e.g. via a transformation or expression), the panel can then correctly calculate an automatic min/max

it might help to refer to the comment here for how to accomplish what you want: https://github.com/grafana/grafana/issues/60797#issuecomment-1448323196

hope that helps! 🙌

**Comment by yajrendrag** [comment]
i still think there's a problem then - i tried adding a total reduce transformation and the result is different still - see new pic:

![image](https://user-images.githubusercontent.com/5522635/224087585-f56be25d-8471-4ef3-abf4-548b45e79ae2.png)

Oddly, if i have 2 calculation types in the reduce calculations box, it does add the graphic to the total gauges - seems very strange to me:

![image](https://user-images.githubusercontent.com/5522635/224088004-bfb3028c-1d36-4905-8d14-6b89bc9a1882.png)

According to the expression documentation I cannot use an expression since i have two numbers columns and not 1 - https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/expression-queries/#data-source-queries

**Comment by yajrendrag** [comment]
i understand what you are saying about there only being two numbers - but then using that same logic when there are only 2 numbers and using 'Last' instead of 'Total' i would expect the graphics to look the same - no green bar on the right hand graph (see my very first graphic).  I just cannot grasp yet why these two situations are so different that this is working as intended.  If there's another way, i'm happy to try and get there but i am still not seeing it.  

The post to which you referred me possibly hints at it - the underlying data in the panel is what is used to calculate min and max - not any calculated data from within my panel..  So, with that i don't see how adding a transformation is supposed to fix this, which was the other posts solution.

I looked at expressions but i have never used them, and when i click to add one - there's no field to type into - maybe they are incompatible with Loki data source?

**Comment by ashharrison90** [comment]
@yajrendrag the transformation fixes it because it transforms the data **before** it reaches the panel.

simple example: let's just consider the `total` calculation and say we have 2 series of datapoints:
A: [1,2,3]
B: [4,5,6]

we pass these to the gauge component, with min and max set to auto. the gauge panel looks over **all data points** to calculate the min and max, so the min is 1 and the max is 6.

using the total calculation in the gauge value options will give you the values 6 and 15 scaled against a min of 1 and a max of 6:
![image](https://user-images.githubusercontent.com/20999846/224108225-2b6f6473-3ab3-467b-a16c-f0bc7e674044.png)

when using a transformation, the data is transformed **before** it reaches the gauge panel. so by using a reduce total transformation, the data becomes
A: [6]
B: [15]

we pass these to the gauge component, with min and max set to auto. the gauge panel looks over **all data points** to calculate the min and max, so the min is 6 and the max is 15

using the total calculation in the gauge value options will give you the values 6 and 15 scaled against a min of 6 and a max of 15:
![image](https://user-images.githubusercontent.com/20999846/224108924-f76de36b-67ee-48d1-9637-7a5e368322d9.png)

i made a little repro dashboard here you can play around with: https://play.grafana.org/d/MRexo4aVz/gauge-transformations?orgId=1

**Comment by yajrendrag** [comment]
ok, thanks for the explanation - it's beginning to sink in.. so a few questions then (i tried to save on your example, but can't) - if you turn on threshold markers and labels and set the threshold to 40% (i guessed and it turned out to be exact), the upper left graph (w/o reduce and using last), the green gauge is at 40%... i would have expected it to be 50% (3 is half of 6)... so what is being calculated for that graph to show 40% - 6/15 is 40% but if graphing  Last, i'm not sure why that would be relevant... i can move that point around by adjusting min and max - e.g., if i set min to 2 and max to 6 the graph is at 25%. 

Also, is there any way to use a variable or something else to automatically fill in values for min and max?  Or, is there a way (without going back to the original datasource) to produce a cumulative sum from a list of numbers (via a transform)?

Net of all this is that i like this gauge display and i like the upper left view in particular but i need to use total.  now i'm trying to figure out if i can manufacture it automatically somehow - adding calculations or extra data - something... i don't really care if it's an accurate depiction of the percentage as long as it's reasonably close.

**Comment by ashharrison90** [comment]
@yajrendrag 

- it would be 50% **if the gauge was scaled from a minimum of 0**. but the gauge is scaled from 1-6. 3 is 40% of the way between 1 and 6.

 - > is there a way (without going back to the original datasource) to produce a cumulative sum from a list of numbers (via a transform)
   - yes. the total reduce fields transformation (as shown in the bottom-right panel on the repro dashboard).
 
 - if you need to use total, then the bottom right panel in the example is exactly what you want. the only thing you need to decide is what you want your scale (minimum and maximum) to be. it sounds like you want maximum set to auto. as for minimum there are only really 2 options that make sense:
   - set the minimum to the minimum value of the reduced data. that's what the bottom right panel shows. if there are only 2 series, this will **always** show one series full and one series empty. because one will be the max and the other will be the min. with more than 2 series, it will make more sense. try adding more dummy series in the panel to see what i mean.
   - set the minimum to 0.

**Comment by yajrendrag** [comment]
but the data will change over time - is there a way to set the minimum value automatically or to use a variable?  i can't just type a fixed number in and use it...

**Comment by yajrendrag** [comment]
i think i am asking you the wrong question... i need the graph to look like the upper left using totals.  If my series of numbers is a running cumulative sum, it will work like i want it to because the last number in the series will be the total and then i can use Last in the panel instead of Total.  So, if i have a series of numbers, e.g., [1,2,3,4] can i transform it to [1,3,6,10] - where each number, i, is the sum of all the numbers up to and including the i-th number?

Or, do i have to go back to the source to produce that?  If so, is there a way to produce it from within Loki - i am looking at sum_over_time at the moment, but not sure it's doing what i want...
thanks
