### ISSUE TITLE
Alerting: Support OR condition in alerts

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#6438]
Currently, we evaluate alert conditions with AND operators only. So, the alert is sent only when all conditions are met. If I need to send alerts if any of the condition is met, I should have an OR operator as a choice with the AND operator.

**Comment by bergquist** [comment]
We have discussed this a few times internally and had a hard time coming up with use cases that we didn't think should be handled in the query instead. 

Adding the OR operator makes alert rules harder to grasp and reason about. We are hesitant about adding it just for the sake of it since we think alert rules should be as simple as possible. Perhaps you could give us some examples when it would be useful for you?

**Comment by torkelo** [comment]
I think OR could be possibly be added ,the really hard part is combing/supporting both OR and AND

**Comment by Gelob** [comment]
@bergquist what about cases where we have two channels and want to have a single alert for each channel?

**Comment by utkarshcmu** [comment]
@bergquist One example could be as follows:

One Panel with 3 metric queries:

A. grafana.success.count
B. grafana.failures.count

So, I want to setup an alert for this panel with conditions:

if A ISBELOW 10 OR B ISABOVE 50, set the alert state to "Alerting".

**Comment by bergquist** [comment]
Wouldn't it be better to have two alerts?

If you have two alerts the naming and alert message would probably be more clear and to the point. While if you have to name an alert and explaining the alert would be harder in your example. When I'm on call I find it very frustrating to get a page say A or B is broken. Pages/Notifications should be as clear as possible

This might cause some extra work when setting up alerts in grafana but isn't it worth it?

**Comment by utkarshcmu** [comment]
Agreed with @bergquist to have multiple alerts per panel. 👍🏽

**Comment by leovin** [comment]
example: monitoring heartbeat for 10 services
if done via single query - how alert rule should look like? (count() -> query (B, 10s, now) -> IS BELOW 1 = doesn't work when GROUP BY is used to group by service name)
if done via 10 queries - how to configure alerts without OR condition?

**Comment by torkelo** [comment]
@leovin not sure what you mean? If a query returns multiple series the condition will be evaluated for each series (and if any is below 1, the condition will fire)

**Comment by bergquist** [comment]
The fact that each serie returned from the query is matches against the threshold might not be so obvious right now.

**Comment by leovin** [comment]
but it's not working for me - hopefully it's not a bug, just something wrong with my query

**Comment by bergquist** [comment]
@leovin if you press the test button on the bottom of the page you will see the resulting value for each serie. Perhaps that can be of help

**Comment by utkarshcmu** [comment]
I think if we can have multiple alerts per panel, we do not need OR condition. We should have multiple alerts per panel so that we can specify different messages for different alerts in different notifications.

**Comment by utkarshcmu** [comment]
It would be great if we can make this feature request go in 4.0.0 release. I can work on a PR if @bergquist is busy working on other important features/bug fixes! :)

**Comment by torkelo** [comment]
This is not going to happen I think, the whole design is built around one alert per panel, the panel heart and state etx

**Comment by utkarshcmu** [comment]
If we cannot have multiple alerts per panel then can we have "OR" condition in the query?

And then user can select all alert queries with either "OR" or "AND" and not a combination of the two?

**Comment by utkarshcmu** [comment]
For example, I have a graph plotting metric A: 4xx and metric B: 5xx for some service and want to put alerts on both the metric queries.

<img width="792" alt="screen shot 2016-11-09 at 11 47 22 pm" src="https://cloud.githubusercontent.com/assets/1019609/20168510/717570e2-a6d7-11e6-85d0-7e8288ab3b0e.png">

So, according to current model I can only put alert as alert on metric A "AND" alert on metric B.

If I can have multiple alerts on the same panel, it would be best but if we want to stick with 1 alert per panel restriction then we might need "OR" condition to put alert on both the metric queries separately.

**Comment by torkelo** [comment]
since both would have different thresholds it would not be a very visual alert, so I would suggest having two panels so you can clearly see the threshold for the two alerts. 

Yes, having OR between conditions is definitely something that we can add.

**Comment by utkarshcmu** [comment]
So, there are two ways to bring in "OR" in the condition combinations:

1. Either the conditions can have only "OR" between them or only "AND" but not both because use of both will make the computation more complex. For example:

Valid condition combinations:
- condition A OR condition B OR condition C
- condition A AND condition B AND condition C
Invalid condition combinations:
- condition A AND condition B OR condition C
- condition A OR condition B AND condition C

2. We process conditions serially:

For example: if we have condition combinations as:

condition A OR condition B AND condition C OR condition D then the evaluation will be:

`(((condition A OR condition B) AND condition C) OR condition D)`

Any thoughts which way to go with?

**Comment by torkelo** [comment]
Not sure, I mean we can begin with the either or option. 

The serial option is interesting:
`(((condition A OR condition B) AND condition C) OR condition D)`

It would enable mixing AND's and ORs without having a nested array structure in the rule model (to determine operator operands). Having a simple array of conditions is preferable as the alternative is too complex to deal with I think. 

The problem with this approach is how to make it understandable in the UI

**Comment by bergquist** [comment]
I dont want to sound to whiney... But keep in mind that complex alert rules should be avoided as long as possible. IMO its better to move the complexity to the TSDB query since its easier to reproduce and reason about. 

`(((condition A OR condition B) AND condition C) OR condition D)` Im having a hard time to come up with a use case for conditions like that. 

I'm not saying we shouldn't add this capability. Just that we should have a really strong reason for doing it.

**Comment by utkarshcmu** [comment]
Brining in "OR" makes alerting config more complex. :|

It would be best if we can have multiple alerts on a panel Or 1 alert per metric query in a panel.

**Comment by utkarshcmu** [comment]
If we can have consensus on any one implementation, I can work on a PR. Please let me know as having this capability is important for a lot of people as they have multiple queries in a single graph. Thanks! :)

**Comment by utkarshcmu** [comment]
The problem we are trying to solve is to put different alert conditions on different queries in a single panel.

**Comment by berglh** [comment]
Just to throw my two cents into this topic. I have a bunch of InfluxDB time series that have varying metrics for a cluster of servers. I use the regex query capability of InfluxDB to return relevant series into a single graph - it's very easy to build lots of dashboards in this fashion.

In my test scenario I have five redis queues on five separate nodes. I would like one alert for a single query which returns values for five separate series. In the current implementation; it only alerts if I only supply one specific series in the query. As soon as more than two series are returned by the query, one series going past the threshold value doesn't trigger the alert as one or more series are still beneath the threshold - perhaps this is it's own specific bug.

The only other approach is to split these up in to individual queries (five instead of one - yawn). Then configure five individual alerts (more yawning).

I'd be happy with any of the proposed solutions here; I like the idea of nested OR/AND queries personally. But I'd also be satisfied with a single alert per graph that work across an arbitrary number of returned series from a regex query.

**Comment by torkelo** [comment]
That is not correct, if any series passes the condition test the alert will fire

**Comment by utkarshcmu** [comment]
As per ease of implementation and adding the code to current implementation, serial AND or OR computation might be the best. I am not sure how we can make that easy to understand for the users on the UI. May be a tooltip and in the docs.

**Comment by utkarshcmu** [comment]
I can work on a PR if we agree on the implementation of serial computation of AND and OR.

**Comment by roscoe57** [comment]
I would like this even if only to implement an OUTSIDE range using max() for upper limit and min() for lower limit atm with the AND logic you can only do a fudgey INSIDE RANGE

oh and with simple multiple alerts only the 1st threshold is dislayed graphically, I'd like to see both in my simple case if possible.

**Comment by torkelo** [comment]
Yes, only the first query condition thresholds gets visualized in graphs and get threshold level handles, this is by design.

**Comment by berglh** [comment]
@torkelo I am correct - it's not working as intended, still on the latest master docker container with influxdb data source. I will raise a bug for the issue now. The behaviour you describe, though is perfectly acceptable for my use case. I'll raise a bug documenting this issue. Would not complain with having nested OR/AND alert triggers though. Cheers :+1:

**Comment by utkarshcmu** [comment]
Now we can have "OR" and "AND" conditions nested/serially calculated for the alert!

<img width="834" alt="screen shot 2016-11-15 at 10 42 32 am" src="https://cloud.githubusercontent.com/assets/1019609/20318802/a0a8dd02-ab20-11e6-8a86-9159737dbce1.png">

Implemented in #6579

**Comment by amoghRZP** [comment]
@utkarshcmu @torkelo does this support :
(condition 1 AND condition 2) OR (condition 3 AND condition 4) OR (condition 5 AND condition 6) ?
