### ISSUE TITLE
[Alerting] How to handle missing data points and execution errors.

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#6444]
**Our current implementation**
An alert execution can result in one of the following states: `pending, no_data, execution_error, paused, alerting, ok`. If the tsdb query returns no data the users have the option to set the state to ok/alerting/no_data or keeping the last value. 

If the state changed since the last execution it will be sent to the notification package.

We currently send notifications for the following alert states `ok, alerting, no_data, execution_error` and there is currently no way of filter out which states that is passed to the notifier. 

**Suggested changes**
- Remove the no_data state and force the user to choose between alerting/ok/keep last when a query returns no data. (default keep last value)
- Remove the execution_error state and force the user to choose between alerting/ok/keep last (default alerting)

Instead of having a specific state for execuction_error/no_data we can make it a part of the state as extra information. This will reduce the amount of states that notification package have to care about down to `ok/alerting`.

**Comment by utkarshcmu** [comment]
What I think is we should keep all the current states `pending, no_data, execution_error, paused, alerting, ok` in the database so that we know what exactly is triggering the alert.

But we send alert only on two state changes `ok -> alerting` and `alerting -> ok`.

While creating the alert, user can set state for `no_data` and `exec_error`, whether he/she wants `ok,alerting,keep last`.

And when we alert, we can have a line in the alert message whether the alert is due to `alerting`, `no_data` or `exec_error` state (if user has chosen both `no_data` and `exec_error` to be "Alerting").

**Comment by utkarshcmu** [comment]
I can help on this if you need a PR and we can finish it before the Beta release and resolve #6424 too.

**Comment by bergquist** [comment]
Im working on this right now :) Should be done soon.
