### ISSUE TITLE
Dashboard version history shows Grafana ID from the users table instead of the username

### ISSUE THREAD

**Issue by brunoakamere** [grafana/grafana#64584]
**What happened**:
After upgrading to Grafana 9.4.1, the version history of a dashboard shows the "updated by" column as the user ID from the Grafana users database, instead of the username of the user. Without the username, it's hard to tell who made the changes on the dashboard.

![image](https://user-images.githubusercontent.com/80133595/224199899-020e0cb9-36b5-41fd-a4d8-9df326f4a585.png)

**What you expected to happen**:
The updated by column in the dashboard version history should contain the username, rather than the user ID from the Grafana users table. As seen below from Grafana 9.3.
![image](https://user-images.githubusercontent.com/80133595/224200302-391ceb46-b502-40f4-a4e5-e1a5ec9c1fb7.png)

**How to reproduce it (as minimally and precisely as possible)**:
- Edit a dashboard
- And go to versions tab under settings

**Anything else we need to know?**: Nope

**Environment**:
- Grafana version: v9.4.1
- Data source type & version: N/A
- OS Grafana is installed on: Docker
- User OS & Browser: MS Edge
- Grafana plugins: N/A
- Others:

**Comment by evgenymarkov** [comment]
I found that the "createdBy" field is just an int and the backend doesn't return user information:

- https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/components/VersionHistory/VersionHistoryTable.tsx#L44
- https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/components/VersionHistory/HistorySrv.ts#L32
- https://github.com/grafana/grafana/blob/main/pkg/api/dashboard.go#L669-L690
- https://github.com/grafana/grafana/blob/main/pkg/services/dashboardversion/model.go#L78

Sorry for direct mention, @mildwonkey, but is it possible to add some extra info about user to dashboard/<id>/versions endpoint and render username instead of user id?

**Comment by tonypowa** [comment]
reproduced in Grafana 9.4.1 (docker 23.0.1,) Ubuntu 22.04.2 LTS

**Comment by Lekensteyn** [comment]
Can confirm. Funny enough, the actual username is still available in the `createdBy` field from the Compare Versions API (`/api/dashboards/uid/<uid>/versions/<revision number>`).

Could it be related to #60736 by @mildwonkey ?

**Comment by andyidea** [comment]
any update on this?

**Comment by NKR-github** [comment]
> Duplicate of #60935
> and fixed by #65351

Is this fix already released? Because I see in Dashboard>Versions>updated by : contains only id’s not username. 
I am using the latest Grafana v9.4.7
Please advise which version has the fix. Does the fox involved displaying the way it was in examples Grafana v8.4.4 displaying username instead of userid in the Update by section?

**Comment by belm0** [comment]
> Is this fix already released?

It's not.  The fix would be in Grafana release that follows v9.4.7.

Having to wait weeks for basic regressions to be fixed is not a great experience.

**Comment by NKR-github** [comment]
> > Is this fix already released?
> 
> It's not. The fix would be in Grafana release that follows v9.4.7.
> 
> Having to wait weeks for basic regressions to be fixed is not a great experience.

Many thanks for your reply.
I am glad at least the fix is ready and this would be included in the next release. I just upgraded Grafana seems I will need to do this one as well as soon as this is out.
