### ISSUE TITLE
High browser RAM usage on 9.4

### ISSUE THREAD

**Issue by Sh4d1** [grafana/grafana#64886]
**What happened**: When using the time series panel, and the logarithmic scale, if the min is set to 0, the RAM used by the browser will grow up to 3/4GB (on my end)

**What you expected to happen**:

No RAM growth

**How to reproduce it (as minimally and precisely as possible)**:

- Create a new time series panel (works with default datasource)
- Set the `min` in `Standard options` to 0
- Set the `scale` in `Axis` to `logarithmic` 
- Watch your ram grow

**Anything else we need to know?**:

No issues on 9.2

**Environment**:
- Grafana version: 9.4.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Chromium, Firefox, qutebrowser
- Grafana plugins:
- Others:

**Comment by jplanckeel** [comment]
The panel concerned  
[panel.json.zip](https://github.com/grafana/grafana/files/10989594/panel.json.zip)

**Comment by usmangt** [comment]
Hi @Sh4d1,

Thanks for opening this issue. We would like to have the following information to process this issue:

1. Backend Logs

Could you please change the default log level to debug mode? To do this go to the server where grafana is installed and edit the configuration file (/etc/grafana//grafana.ini)
There you will this section;

```
#################################### Logging ##########################
[log]
# Either "console", "file", "syslog". Default is console and  file
# Use space to separate multiple modes, e.g. "console file"
;mode = console file

# Either "debug", "info", "warn", "error", "critical", default is "info"
;level = info
```
Set the parameter level to debug and remove the colon in the beginning i.e.

`level = debug`

Then restart the grafana service and resent the logs once the issue occurs again.

2. Can you please try to reproduce this same issue on https://play.grafana.org/ and then share the dashboard link so that we can view it?

IF NOT, 

Then simply send us a small .GIF where we can see your steps of reproduction more clearly.

Thanks

**Comment by Sh4d1** [comment]
And here is the video: http://s3.fr-par.scw.cloud/ghissue/recording.mp4

**Comment by usmangt** [comment]
Hi @Sh4d1,

Thanks for the wait.

Based on your steps of reproduction, I was not able to reproduce it on my test machine.

I tested it on my VM which has Docker installed and run the Grafana via CMD

`docker run -d -p 3000:3000 grafana/grafana-oss
`

And then when selecting logarithmic, the memory still didn't grow above 47 MB out of 991 MB
![image](https://user-images.githubusercontent.com/69509548/226433217-38cbef12-e327-45de-a29f-39763691eceb.png)

I measured this via [ctop](https://ctop.sh/) tool

What might be the difference here is that you are specifying the configuration file and therefore, not sure if there is some modification from the default one?

**Comment by Sh4d1** [comment]
Thanks for taking a look @usmangt!
 
> What might be the difference here is that you are specifying the configuration file and therefore, not sure if there is some modification from the default one?

I just copied the file from the container and edited the log level that's it

> I measured this via [ctop](https://ctop.sh/) tool

Maybe I was not clear, it's the browser that's using a lot of RAM, not the grafana process*
