### ISSUE TITLE
Improve performance of Alert list panel and Alert list view

### ISSUE THREAD

**Issue by gotjosh** [grafana/grafana#65071]
### Background

The Alert list panel and Alert list view load all alert rules and their alert instances from the API. This is problematic for some of our larger customers and users as the JSON response from the API can be 10s of MBs. This incurs CPU time in encoding and decoding JSON, increases work for the database, and keeps more data in memory in the browser than is needed which could be problematic on low end and mobile devices.

This cannot be fixed in the UI without support from the API as:

1. The API does not support filtering, limits or pagination of alert rules
2. Each alert rule is returned with all of its alert instances, even if the client doesn't need them

### Proposal

We are going to update the `api/prometheus/grafana/api/v1/rules` to support filtering and limits, but not pagination. This will allow us to move all of this behaviour from the UI to the API and reduce the size of the JSON response returned to the browser, and pagination is not required to make this work.

We have created the following tasks that will allow us to address this issue for users of GMA:

```[tasklist]
- [ ] https://github.com/grafana/grafana/issues/65420
- [ ] https://github.com/grafana/grafana/issues/65421
- [ ] https://github.com/grafana/grafana/issues/65422
- [ ] https://github.com/grafana/grafana/issues/65423
- [ ] https://github.com/grafana/grafana/issues/65582
- [ ] https://github.com/grafana/grafana/issues/66834
```

**Comment by konrad147** [comment]
Related https://github.com/grafana/grafana/issues/55694 https://github.com/grafana/alerting-squad/issues/327 https://github.com/grafana/alerting-squad/issues/379

**Comment by gillesdemey** [comment]
afaik the proposal is to not return the "instances" but still return namespaces + groups + rules. iirc we don't filter on instances, right?

**Comment by gillesdemey** [comment]
Oh right, the labels we receive from the data queries are taken in to account 👌

**Comment by konrad147** [comment]
Exactly. I think it's especially important for multi-dimensional rules

**Comment by gillesdemey** [comment]
Here's the current filtering that we support in the alert list panel and its behaviour – focusing on the ones that need to be supported in the BE or need access to all instances to function.

# Alert List Panel

## Default grouping (group by Alert Rule)

### Filtering

In order to support limits on alert instances in the alert list panel, the following server-side filters should be implemented:

#### Alert and instance state

Support for following state filter values

```
firing: boolean;
pending: boolean;
inactive?: boolean; // backwards compatability, alias for normal
noData: boolean;
normal: boolean;
error: boolean;
```

`firing`, `pending` and `normal / inactive` are first applied to the state of the alert rule. The other states are ignored.

Then apply filtering to the alert instances for the filtered set of alert rules. All of the state filters above should be supported.

The default state filters are 

```
Alerting / Firing
Pending
Error
```

#### Alert instance label filters

Apply instance label filters to all instance in alerts. Supported syntax is the same as prometheus label matchers (support for all matchers `=`, `!=`, `=~`, `!~`).

#### A combination of the above

Always filter out alert rules with 0 instances matching the filters above.

If a combination of state filter and instance label filter are combined, it is possible that alert rules with 0 matching instances are returned. 

We omit these from the alert list panel because they might show as false positives.

See [this PR](https://github.com/grafana/grafana/blob/main/public/app/features/alerting/unified/components/rules/RuleState.tsx#L25-L52) for an example / valid use-case.

If there are additional instances in an alert rule that don't match the state or instance label filter, we show "x hidden by filters".

### Sorting

The following sorting should be supported on the backend because they use alert instances for sorting:

1. `Time (asc)`
2. `Time (desc)`

This can be done by updating the alert rule property `activeAt` or something similar.

### Additional

To compute the "Firing for x time" we traverse the list of instances and figure it out from the earliest firing alert.

See [this piece of code](https://github.com/grafana/grafana/blob/main/public/app/features/alerting/unified/components/rules/RuleState.tsx#L25-L52).

**Comment by soniaAguilarPeiron** [comment]
In the alert list panel we also have the `hidden by filters` count. Now, this is something we should add to the response of the api.

**Comment by qinxx108** [comment]
Just to cross reference, we are planning to do the implementation on alert manager api: https://github.com/prometheus/alertmanager/issues/3297

**Comment by gillesdemey** [comment]
@qinxx108 we're keeping an eye on that proposal – this PR is mostly to put out fires and drastically reduce the payload size for Grafana managed alerts only.

**Comment by grobinson-grafana** [comment]
@soniaAguilarPeiron and @gillesdemey feel free to close this issue once the lay front end PR has been merged!

**Comment by gillesdemey** [comment]
Closing this one; great job everyone! 💪
