### ISSUE TITLE
Loki Query Builder: odd behavior of "remove pipeline errors" hint

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#65377]
The “remove pipeline errors” hint only appeared when we select a label filter with no value.

![Image](https://user-images.githubusercontent.com/1069378/227980516-6672335f-39f7-48ec-b5c9-b731e2672012.png)

Part of https://github.com/grafana/grafana/issues/65370

**Comment by matyax** [comment]
FYI @ivanahuckova

**Comment by ivanahuckova** [comment]
The hint is here correctly suggested because if the label expression is `level=""`, then we there are pipeline errors 
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/30407135/232033295-74435178-1ce6-4fe7-a9c5-b724aaef294a.png">

If you select value, then pipeline error is correctly removed 
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/30407135/232033672-49184058-d75b-42f8-9e5f-2ca9b4e9f108.png">

From my perspective, this seems like correct behaviour. I would be slightly worried if we checked what is the last pipeline operation and if it was label filter without value, then don't with offer error filtering, because sometimes users can be using label filter to filter for logs that don't have that value, and in this case, we wouldn't be showing them this help. 

But let me know what do you think @matyax.

**Comment by matyax** [comment]
Makes sense! Thanks for investigating this @ivanahuckova ! Closing.
