### ISSUE TITLE
Time series: tooltip not visible while other panels are loading

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#65408]
**What happened**:
Using "Time series" visualization with tooltip enabled, the tooltip does not display while other panels are loading.  In other words, the panel with tooltip may have all its series loaded and displayed, but display of tooltip is deferred until other panels on the dashboard are done loading (many seconds depending on number of preceding panels and query demands).

update:  the bug is only seen when the dashboard has a mix of "Time series" and "Graph (old)" components

https://user-images.githubusercontent.com/1708631/228134082-1c25d89d-e36c-46b6-b5c1-9393b935077e.mov

**What you expected to happen**:
The tooltip should be available whenever the panel's series are displayed.

**How to reproduce it (as minimally and precisely as possible)**:
1. create dashboard with panel using "Time series" viz with a lightweight query and tooltip enabled.  Additionally, create some panels using "Graph (old)" with a heavy query.
2. load the dashboard.  Observe that the "Time series" panel with light query displays the time series quickly, but tooltip display is deferred until the "Graph (old)" panels are done loading.

**Anything else we need to know?**:
Notably, this problem does not exist for "Graph (old)" visualization.

This bug is probably as old as the new Time series, and at least present since Grafana 7.x.

**Environment**:
- Grafana version: 9.4.7
- Data source type & version: Prometheus

**Comment by usmangt** [comment]
Hi @belm0,

Thanks for opening this issue.

Can you please try to reproduce this same issue on https://play.grafana.org/ and then share the dashboard link so that we can view it?

**Comment by usmangt** [comment]
Hi @belm0 

the labels are for internal usage and tracking purpose.

One question, does it works well if you e.g. not use Graph(Old)?

The reason for asking it because there will be no further development (as I encounter this issue last week https://github.com/grafana/grafana/issues/65501#issuecomment-1490188383)

So is it reproducible only using Time Series Panel?

**Comment by belm0** [comment]
It seems to involve Graph (old), so I guess you're going to close it.

The policy is quite disappointing, and I don't agree with the original engineering decision to fork the component, rather than provide a seamless, automatic upgrade.

**Comment by leeoniya** [comment]
> The policy is quite disappointing, and I don't agree with the original engineering decision to fork the component,

Graph (old) is a very complex panel that did way too much, and had numerous, unfixable bugs and performance issues. it was a combo of TimeSeries, BarChart, and Histogram. the engineering decision was to split it so that we can fix, enhance, and extend each of these use cases independently.

> rather than provide a seamless, automatic upgrade.

we do have migration code that should be able to auto-migrate the old config to the correct new panel+config. it works quite well for most settings, but occasionally people find bugs, which we fix when feasible. e.g. https://github.com/grafana/grafana/issues/84263. you can enable this auto migration using the `autoMigrateGraphPanel` feature toggle [1].

if you find a migration bug, please open a new issue so we can look into fixing it.

[1] https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/#preview-feature-toggles
