### ISSUE TITLE
Implement Trusted Types

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#65611]
[Design doc](https://docs.google.com/document/d/1-N7URLS1kaqvbuwGZgj4iyc4laH9Qmj0TFwVnhZCIc4/edit#)

Most up to date discussion can be found in the PR

## Discovery
- [x] Implement POC https://github.com/grafana/grafana/pull/64975
- [x] Add usage examples to design 
- [x] Evaluate impact and required changes to the codebase
- [ ] Define test cases

## Communicate changes
- [ ] Add info about Trusted Types in plugin documentation and tutorials
- [ ] Inform plugin developers on Slack
- [ ] Write blog post

**Comment by KristianGrafana** [comment]
The current POC works as expected where we follow W3C's recommendation of using a `default` policy for 3rd party libraries and return a TT where applicable. 

When it comes to testing the efficiency of the implementation you can set the `disable_sanitize_html` configuration option to `true` which opens up for XSS-attacks. Then insert XSS-payloads into a Text panel and see how TT forces sanitation through DOMPurify (`default` policy). You can then change the policy in the index to disallow some tags with `FORBID_TAGS` and see for yourself that the tag is sanitized. 

The current issues (to my extent) is that we load DOMPurify in a script-tag which is not an ideal solution. It seems that we stumble upon a race condition when attaching the sanitation function to the window object. Maybe this is still fine for a first iteration? 
Second issue is that DOMPurify creates a different `TrustedHTML` object than `createHTML` does. This means that currently we can't build our own policies where we don't use DOMPurify. This might also be fine as DOMPurify is highly flexible. 

Other than this, I'm satisfied with the current POC as its main goal is to combat DOM-XSS and after extensive testing, TT has shown to be extremely powerful (as long as we don't see bypasses and weak sanitation).

**Comment by tskarhed** [comment]
I am currently trying to figure out how to not load DOMPurify with a script tag. It would also be nice if we could figure out some test cases. Do we intend to merge the POC soon-ish, or do we want more people to review it?

**Comment by KristianGrafana** [comment]
> It would also be nice if we could figure out some test cases.

Since TT is currently only available in Chromium-based web browsers, e2e tests would be best suitable. How do you usually go about building tests; do you want me to name a few test cases in the design doc?


> Do we intend to merge the POC soon-ish, or do we want more people to review it?

Since this is behind a flag, it should be fine to merge the POC soon without extensive reviewing. One thing we could do is check if the `trusted_types` options is set where we sanitize with `sanitizeTrustedTypes` even though DOMPurify does feature testing and will return a string if TT is not supported. If we do that, I would be very confident in merging this ASAP.

**Comment by KristianGrafana** [comment]
@tskarhed Nice work with the PR! The two main issues are now resolved :) 

`createHTML` and `createScriptURL` are being handled in the `default` policy also. 

There will be some change when using Trusted Types, specifically;
1. Since we use DOMPurify, sanitized data will be removed in Text panel. This will change the behavior where we currently keep the sanitized data (TT will use DOMPurify instead of js-xss).
2. `disable_sanitize_html=true` will not have any effect when TT is active. It's obvious but could be worth to mention.
3. `require-trusted-types-for 'script'` needs to be in the CSP for TT to be active. We need to mention that in the docs as well. 

Other than this, I think this looks really good! Next week we'll do some more testing :+1:

**Comment by tskarhed** [comment]
Also, how do we want plugin developers to implement custom policies? Maybe we should a function from grafana/runtime that does the feature flag check and TT support? Then plugin developers don't need to bother to check for the support themselves. In this case we might have some issues figuring out when the custom policies load.
