### ISSUE TITLE
Update moment-timezone to latest TZDB on 8.x branch

### ISSUE THREAD

**Issue by andrearota** [grafana/grafana#65934]
**What happened**:

Using Grafana 8.5.22, Mexico City appears to be UTC-5:00 while it is supposed to be UTC-06:00 as Mexico is not using DST anymore.

**What you expected to happen**:

Being released after announcement of IANA TZDB 2022f, I expected Grafana 8.5.22 to do not switch Mexico to DST. The package moment-timezone is held back to 0.5.34, which stops to TZDB 2021e (https://github.com/moment/moment-timezone/blob/develop/changelog.md)

**How to reproduce it (as minimally and precisely as possible)**:

Go to time picker and select "America/Mexico City", you will see UTC-05:00 while it should UTC-06:00.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.22
- Data source type & version: any
- OS Grafana is installed on: Docker
- User OS & Browser: Windows Edge
- Grafana plugins:
- Others:

**Comment by andrearota** [comment]
I verified. The latest release for 8 and 9 (8.5.22, 9.4.7 as today) have the issue.

**Comment by tskarhed** [comment]
Issue confirmed. It is fixed in 9.5. Unfortunately we only backport critical bug fixes, and as this can be worked around by changing the timezone to some other UTC-6, we will not backport it. A dependency bump is usually risky and may cause more bugs, which creates a lot of extra work with multiple releases required.
