### ISSUE TITLE
Alerting: Query Condition that can compare two queries (with different time ranges & reducers)

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#6593]
For example 

Condition:

```sql
WHEN avg() of query(A, 5m, now)  IS BELOW max() of query(B, 1h, now)
```

Any other ideas?

**Comment by lebernardo** [comment]
+1

I need this feature for compare two querys with timeShift

On Wed, 16 Nov 2016 at 07:48 Torkel Ödegaard <notifications@github.com>
wrote:

For example

Condition:

WHEN avg() of query(A, 5m, now)  IS BELOW max() of query(B, 1h, now)

Any other ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/grafana/grafana/issues/6593>, or mute the thread

**Comment by ronnevo** [comment]
+1
We are looking for this feature to generate an alert based on a how an actual measurements is different from a calculated / predicted value.

**Comment by sumit1294** [comment]
+1, We also need this feature.

**Comment by garceri** [comment]
Would it be possible to add a feature so arithmetic operators can be used for example
WHEN avg() of query(A,5m, now) is ABOVE 85% of query(B,5m,now).
This comes handy to generate an alert like "Alert whenever the heap memory utilization goes above 85%".

**Comment by jdraymon** [comment]
@torkelo what would you expect the alert rule to do if the second query returns multiple results? (Knee deep in implementation at the moment)

Options as I see it:
 * Have the alert fail validation on setup if the query returns multiple values
 * choose the (min / max) value of the set of reduced values from the sub queries

Let me know if you have something else in mind

**Comment by torkelo** [comment]
if both queries return more than 1 series try to match on series names, if one of the queries return more than one series evaluate each series in returned by query A against the single series in query B

**Comment by d-shi** [comment]
Is there an ETA on this feature? I am also trying to generate alerts that compare one series against another series. In Prometheus you can get around this by just doing math in the metric query. However when looking at Cloudwatch the datasource plugin does not allow you to do math in the metric query. I am try to generate an alert when the InServiceInstances for an AWS Autoscaling Group has been below the GroupDesiredCapacity for an extended period of time (specifically for autoscaling groups using spot instances).

**Comment by bert2002** [comment]
Would really like to see this feature :)

**Comment by thejchap** [comment]
@torkelo @jdraymon is any help needed with this? happy to contribute as this will be very valuable for us

**Comment by josestbernard** [comment]
+1

**Comment by luispabon** [comment]
Another use case. When monitoring an ECS setup, I'd like to be able to trigger an alarm when I'm reaching max capacity, which is defined by three metrics in my particular use case:
  * A: GroupInServiceInstances
  * B: GroupMaxSize
  * C: CPUUtilization

Essentially I want to trigger an alarm when:
  * A = B
  * C > 80%

**Comment by pekzanan** [comment]
So any plan here guys?

**Comment by bergquist** [comment]
I’ve been thinking about this lately and I’m not sure I think this is something that should be solved by Grafana alerting engine. I’m gonna try to explain why I think so.

- Alert rules should be simple to reason about. Alert rules that are hard to understand makes it very harder to understand why you got paged. 
- If the alert rule generates false positive alert notifications it should be easy to start tweaking the Alert rule to make sure you don't get woken up in the middle of the night again. 

Splitting up the rule into two queries make both use-cases harder. I think any datasource that is suitable for monitoring should allow you to do subqueries and simple math operations on it own, which should make it possible to all suggested alert rules in on query. Writing an alert rule in one query makes it easier to understand why it triggered, tweak if needed and test on old data. 

If the datasources does not support this behavior I think the complexity should be fixed by https://github.com/grafana/grafana/issues/3677 rather than the alerting engine.

**Comment by jdraymon** [comment]
@bergquist subqueries and simple math are possible, what's been elusive is the ability to do exactly the query described by @torkelo at the top. It's possible, of course, that I'm missing something in influxDB, but in our case, we have series A; call it predicted traffic, and series B, actual traffic. If the average of series B is statistically significantly higher than the average of series A over a given timeframe, we want to send an alert.

I suppose that there are cases where an end user writing a query might make it harder to reason about, but fundamentally the complexity resides in the query that's being done and the datasource that's being fed into it - If you can't reason about the datasource being fed in, you're always going to have an unpredictable alert rule; having a fixed threshold or a computed variable one doesn't change the complexity significantly.

Even if there is a way to write the query such that it is all in one, we haven't moved the needle on reducing the complexity of reasoning about the alert, it's just made it harder to implement a solution and forced the end user into making a query that's much harder to read, since it won't render in Grafana's simple query editor.

**Comment by deepakksahu** [comment]
+1

**Comment by pmahalwar-intertrust** [comment]
+1

**Comment by pmahalwar-intertrust** [comment]
I would like to get an alert when A reaches up to '80%' of B. How is that possible ?

* A: GroupInServiceInstances
* B: GroupMaxSize

**Comment by pdf** [comment]
FYI @pmahalwar-intertrust the reason people downvote `+1` comments is because they spam everyone who's subscribed to an issue and add nothing of value.  You clearly know how to use the reaction buttons, so if you want to express your support for an issue on Github, add a reaction to the original issue comment.

To answer your question - if you don't need to evaluate different time windows, you should typically be able to do this using the query language for your data source, by performing the required math as part of your query.  This is not a support forum though, so if you need help writing queries I suggest you ask in a more appropriate forum.

**Comment by Gauravshah** [comment]
> I’ve been thinking about this lately and I’m not sure I think this is something that should be solved by Grafana alerting engine. I’m gonna try to explain why I think so.
> 
> * Alert rules should be simple to reason about. Alert rules that are hard to understand makes it very harder to understand why you got paged.
> * If the alert rule generates false positive alert notifications it should be easy to start tweaking the Alert rule to make sure you don't get woken up in the middle of the night again.
> 
> Splitting up the rule into two queries make both use-cases harder. I think any datasource that is suitable for monitoring should allow you to do subqueries and simple math operations on it own, which should make it possible to all suggested alert rules in on query. Writing an alert rule in one query makes it easier to understand why it triggered, tweak if needed and test on old data.
> 
> If the datasources does not support this behavior I think the complexity should be fixed by #3677 rather than the alerting engine.

@bergquist The assumption here is that data belongs to one datasource, we could have multiple datasources and their combined effect contributes to an alert. Spend data, click data, Orders data will not be in the same database because of the nature of data they have. one is external batch, one is realtime other is internal batch

**Comment by d-shi** [comment]
@bergquist @pdf There are some datasources that do not allow any sort of math in the query, like the AWS Cloudwatch one (please correct me if I'm wrong). I have had to resort to defining alerts inside Cloudwatch itself instead of Grafana because it is not possible to define these alerts in Grafana, but this means I now have alerts in two different systems. It would be much better to just be able to have everything in Grafana.

**Comment by mlindes** [comment]
I came here looking for ways to create alerts on the AWS/Billing namespace. 
I'd like to be able to create an alert that either compares a single stat to that same stat from some point in the past, like 1m ago, or to be able to graph a derivative to alert on.

Since the AWS/Billing namespace of the Cloudwatch datasource sets the counter to 0 at the start of every month, it would be nice to compare the same metric from today and today-30d on the same graph and use that as a potential alert. The same may be possible if derivative values were available with Cloudwatch metrics.

**Comment by kairiruutel** [comment]
**+1** For the feature to compare two graphs against each other!

**Comment by kladiv** [comment]
+1

**Comment by Gauravshah** [comment]
> I’ve been thinking about this lately and I’m not sure I think this is something that should be solved by Grafana alerting engine. I’m gonna try to explain why I think so.
> 
> * Alert rules should be simple to reason about. Alert rules that are hard to understand makes it very harder to understand why you got paged.
> * If the alert rule generates false positive alert notifications it should be easy to start tweaking the Alert rule to make sure you don't get woken up in the middle of the night again.
> 
> Splitting up the rule into two queries make both use-cases harder. I think any datasource that is suitable for monitoring should allow you to do subqueries and simple math operations on it own, which should make it possible to all suggested alert rules in on query. Writing an alert rule in one query makes it easier to understand why it triggered, tweak if needed and test on old data.
> 
> If the datasources does not support this behavior I think the complexity should be fixed by #3677 rather than the alerting engine.

 @bergquist  did give it more thought I do agree it should work with metaqueries, but for metaqueries to work as backend plugin grafana needs to support it. can you please take a look at this PR and give it right direction ?
https://github.com/grafana/grafana/pull/16387

**Comment by bert2002** [comment]
I think we should still make this happen :)

**Comment by spencer-edh** [comment]
I for one would still love to see this feature. We just started to use grafana and would love to compare two lines on a graph. If one ever was greater than the other by a certain percent then alert us.  unless anyone knows how to do this with the current alerting tools in grafana?

**Comment by NeverUsedID** [comment]
+1

**Comment by codax0r** [comment]
I also agree that this would be very useful. I tried to make something like that work with an elasticsearch query but it was a painful and resultless experience..

**Comment by jlsam** [comment]
I also agree that this feature is extremely useful. I don't think it's complicated at all to compare 2 data sources. And there can always be an annotation field to explain what is being tested.

I have a situation where I would like to compare a local metric to a value from an external source (oracle). The data from the external source doesn't even need to be stored, I just need to get a reading whenever the alert routine is triggered. I can collect both using Telegraf - using 2 different input plugins, but as far as I can see, there is no way to merge or evaluate data from separate inputs, although something like that seems to be under discussion https://github.com/influxdata/telegraf/issues/6254

In any case, a solution using Telegraf's architecture would be far more complex and confusing than using Grafana's point and click expression builder, so that also defeats the 'complicated' argument.

One could also write a custom alert script, but that would 1. be a lot more work, 2. partially duplicate what Telegraf is doing, 3. be considerably more 'complicated' to maintain in the long term and 4. reduce the value of the excellent alerting system already built into Grafana.

**Comment by mnuic** [comment]
This is something we need badly :)

**Comment by lireanne** [comment]
would also like to see this feature!

**Comment by gaiachik** [comment]
Hello 👋 I got here because I wanted to set up what I thought was a very simple alert. If the error response rate is above a certain % of total requests.. send a notification. 
In order to do this, I meant to compare what the current rate of requests is and match that against the error rate.... 
so +1 on this.

**Comment by pattontim** [comment]
This feature would also be useful to me! Seems like a common solution is to store a percentage measurement as an entry

**Comment by kylebrandt** [comment]
Server side expressions, planned for Grafana 8 with Alerting NG should allow for this.

Prototype looks like:

![image](https://user-images.githubusercontent.com/1692624/96619637-67df8280-12d4-11eb-9a27-07c0b92bbae0.png)

So while it would be nice to have a rewrite rules handy in every data source, so instead of complex expression you get metrics, practically that is not possible. So alerting NG will be able to point to server side expressions to cover the gap when data sources don't allow for logic needed, or if you are feeling adventures and want to alert across data sources.

The math is meant to work on labeled sets of things (similar prometheus math does), so for tying into alerting something like `$A` could be a bunch of time series, and so could `$B`, and the math operators will do a join. So this ties into alerting in that you can have multiple instances in your response to create multiple alerts (instead of having to one query per alert).

**Comment by visup-devs** [comment]
I think it would a great upgrade to the new alerting tab.

**Comment by kylebrandt** [comment]
The new beta version of alerting in Grafana 8 ([opt-in with "ngalert" feature toggle]( https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/)) can alerts based on Server Side Expressions, and time ranges have been moved to be per query with alerting, so this can be done in the new system.

![image](https://user-images.githubusercontent.com/1692624/121200949-20e1d580-c842-11eb-87ab-c3544bc17442.png)

![image](https://user-images.githubusercontent.com/1692624/121200967-24755c80-c842-11eb-95b1-9c92f710358b.png)
