### ISSUE TITLE
Task: omit writer request call in public dashboard

### ISSUE THREAD

**Issue by juanicabanas** [grafana/grafana#65957]

**Comment by juanicabanas** [comment]
![Image](https://user-images.githubusercontent.com/11707172/229885737-69e69de3-c044-4c4b-b412-4d457806138d.png)

**Comment by evictorero** [comment]
Currently, we are loading and initializing all features of Grafana when showing a Public Dashboard. One of those services requires an additional API request to get info needed for `recorded queries`. Because this request needs authentication, it is failing with a 401.
We need a way to skip initializing components that public dashboards do not need or add additional logic to ignore these requests.
