### ISSUE TITLE
CloudMonitor: Health check should return relevant errors when failing.

### ISSUE THREAD

**Issue by aangelisc** [grafana/grafana#66274]
Currently, no messages are returned when the health check fails. Only the status code is returned. The plugin should return appropriate information to the user to aid in diagnosis.

**Comment by Carcraftz** [comment]
Hi, I believe this issue has already been fixed. 

I attempted to provide a fix for it (I am new to open source contributions and this is my first issue) but noticed that the code changed recently to already fix this.

In pkg\plugins\manager\client\client.go
the previous code was 
return nil, fmt.Errorf("%v: %w", "failed to check plugin health", backendplugin.ErrHealthCheckFailed)
and the code has been updated to
return nil, fmt.Errorf("%w: %w", backendplugin.ErrHealthCheckFailed, err)

Thus the new code returns the full relevant errors and I believe that this issue is resolved and should be closed.

**Comment by aangelisc** [comment]
There is still a subtle change that is required to return an error message 😊
