### ISSUE TITLE
Annotations:  opentsdb datasource support

### ISSUE THREAD

**Issue by fabienp85** [grafana/grafana#664]
Is the support of opentsdb datasource for Annotations in the roadmap ?

**Comment by nickman** [comment]
+1

**Comment by kylemallory** [comment]
+1

I've made a stab at this; I'm still trying to find the right context for OpenTSDB annotations, and how they will fit into Grafana.  For starters, TSDB has "global annotations" which don't really have a query.  You either get them back, or your don't.  This is where I am starting.  Otherwise, all TSDB annotations are tied to, and returned as part of any specific metric query.  There is not yet a way, that I know of, to query annotations by themselves.  This presents a delima, as the Annotations Query builder doesn't really make sense; rather if you query a metric in a graph, and that metric includes annotations in its results, how do you graph them.

While poking into the code, there isn't a direct means to send annotations to the rendering engine outside of the Annotations feature.

**Comment by haomingz** [comment]
+1

**Comment by lexh** [comment]
+1

**Comment by utkarshcmu** [comment]
+1

**Comment by digrich** [comment]
+1

**Comment by Engineiro** [comment]
+1 

any progress on this?

**Comment by juancb** [comment]
+1

**Comment by digrich** [comment]
Any progress on this? +1

**Comment by vitorboschi** [comment]
+1

**Comment by huhongbo** [comment]
+1

**Comment by floyd-may** [comment]
+1

**Comment by eswdd** [comment]
+1

**Comment by dbcook** [comment]
+1

**Comment by rconn01** [comment]
+1

**Comment by knowroozi** [comment]
+1

**Comment by knowroozi** [comment]
Submitted PR for this - https://github.com/grafana/grafana/pull/4296

**Comment by bergquist** [comment]
closed by https://github.com/grafana/grafana/pull/4296

**Comment by utkarshcmu** [comment]
@bergquist Please add this change to CHANGLOG, its a big addition for Opentsdb users :)

**Comment by bergquist** [comment]
@utkarshcmu ofc! https://github.com/grafana/grafana/commit/ca7c3cc27d86b5085f983c83db5ade61082e75c7

**Comment by gnydick** [comment]
i don't see how this works. can you add annotations via the ctrl+click in grafana that are stored in opentsdb? if so, since I tried, how do you get them to show up?

**Comment by torkelo** [comment]
They are stored in Grafana’s DB
