### ISSUE TITLE
Cross compile on Windows for Solaris

### ISSUE THREAD

**Issue by dewi-ny-je** [grafana/grafana#6656]
Grafana 3.1.1, Windows 10, Go 1.7.3, TDM-GCC, Git.
I successfully cross-compiled InfluxDB.

With Grafana I was following http://docs.grafana.org/project/building_from_source/, I just set the target architecture and operating system as environment variables. 
>set GOOS=solaris
>set GOARCH=amd64

Then with
>go get github.com/grafana/grafana
package github.com/grafana/grafana: no buildable Go source files in c:\Users\Olaf\Downloads\gopath\src\github.com\grafana\grafana

I cannot continue further.
What is the procedure for cross-compilation of Grafana? the standard Go-procedure apparently doesn't work.

**Comment by bergquist** [comment]
To cross compile grafana you need to send some custom flags to build.go

ex
`go run build.go -goarch=armv7 -cgo-enabled=1 -cc=arm-linux-gnueabihf-gcc -cxx=arm-linux-gnueabihf-g++ -pkg-arch=armhf -phjs=./phantomjs build pkg-deb`

**Comment by torkelo** [comment]
unsure you can cross compile on windows given the sqlite3 dependency. 

Your best bet is to compile on solaris

**Comment by fg2it** [comment]
@dewi-ny-je As torkelo said, to build grafana you need to compile sqlite3. Go takes care of that under the hood but, to do so, it relies on an external toolchain. So if you want to cross compile Grafana for solaris, you surely need a toolchain, able to perform the cross build, installed in your windows build system. I can't help you further with that toolchain and I am not sure it would be enough, but I think so. Let say I am more optimistic than torkelo. On the other hand, getting the right toolchain will probably require some work. Finally, you have to find a phantomjs build for solaris.
Surely it would be easier to build on solaris. If this is not possible, and have to stick with windows, maybe a linux VM running on your windows host would ease the toolchain problem (that is the way I use to cross build for raspberry pi). 

You can see a short description on how to use the flags mentioned by bergquist in the PR #6068. They are needed because `build.go` need to be run on your host and not on the target arch.

By the way, influxdb doesn't have such external C library dependency, so Go can directly do the cross build. Moreover, they use python script to build and package instead of go, so standard env variables work out of the box. 

@bergquist @torkelo The cross compile flags are not documented in the current doc. I can submit a PR if you want. Where should this documentation go ?
