### ISSUE TITLE
Panel link not working in collapsed row with repeated panels

### ISSUE THREAD

**Issue by JiKook31** [grafana/grafana#66666]
## What happened:
We have a dashboard with collapsed rows by default that contain automatically generated panels (repeated by variable). Trying to open any panel (except the first one in a row) by link gives "Panel not found" error. However, if the rows are expanded by default everything works fine.

## What you expected to happen:
Opening a panel link in collapsed row with generated panels displays the required panel.

## How to reproduce it (as minimally and precisely as possible):
1. Create a row.
2. Create a variable with custom variable type and fill it with few items. For example: test, test1, test2. Enable the "Include All" option.
3. Create a new panel, place it inside the created row and in repeat options choose to repeat it by variable that was created in the previous step. Choose 'All' option for this variable.
4. Collapse the row and save the dashboard.
5. Open any panel (except the first one), copy the link and open it in the new tab.

## Anything else we need to know?:
Gif of the error:
![Animation](https://user-images.githubusercontent.com/20677175/232482289-db9f64bc-b839-449e-8938-69ce50bf5409.gif)
Gif with expanded row by default, but still with generated panels:
![ezgif-3-f258a7fe84](https://user-images.githubusercontent.com/20677175/232483963-e26c9e2b-beae-464d-8511-217e505e7397.gif)

## Environment:
- Grafana version: v9.3.6 (978237e7cb)
- Data source type & version: PostgreSQL
- OS Grafana is installed on: 
- User OS & Browser: Windows, Google Chrome
- Grafana plugins:
- Others:

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue, @JiKook31 

Besides the error in the UI, can you check if the error got logged?

Try increasing [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to debug and note any errors. For printing to console, [set the console logs to ](https://grafana.com/docs/grafana/latest/administration/configuration/#level-1)debug as well. More info on troubleshooting Grafana issues here https://grafana.com/docs/grafana/v9.0/troubleshooting/

**Comment by JiKook31** [comment]
@tonypowa I've inspected the logs and it seems that the error is not present there.

**Comment by tonypowa** [comment]
thank you @JiKook31 
i will forward this issue to the dashboard's squad for further review

**Comment by evictorero** [comment]
I was able to reproduce this issue in Grafana 9.5.0 too.
The problem is that repeating panels do not exist on loading when the row is collapsed and it's triggering [this alert](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/containers/DashboardPage.tsx#L276). 
When rows are not collapsed, the panel exists after loading so it is possible to open it directly.

This can be reproduced with this simple dashboard.
[collapsed-rows-repeating-panel.json.txt](https://github.com/grafana/grafana/files/11290675/collapsed-rows-repeating-panel.json.txt)

We will add this issue to our backlog for prioritization.

**Comment by JiKook31** [comment]
@evictorero Great, thank you a lot!

**Comment by bucko909** [comment]
This bug is not caused by collapsed rows, though collapsed rows can make it worse. Fundamentally, when linking a resource which is generated by "repeat over" on a multi-valued variable, the URL _must_ include the variable values used to generate the panel and the source id of the panel, _not_ the id of the panel which is generated.

Steps to reproduce _without_ using rows:

* Create a new dashboard.
* Add two custom variables with default names `query0` and `query1`, with multi-values `1, 2` and `a, b` (mostly to distinguish).
* Create two panels, the first repeating over `query0`, the second over `query1`.
* Ensure `query0` is set to `1`, and `query1` is set to `a`. Save, then reload the page to ensure state is consistent.
* Set `query1` to be `a` and `b`. This generates a new "virtual" panel with `id=3`.
* Set `query0` to be `1` and `2`. This generates a new "virtual" panel with `id=4`.
* "View" the fourth panel on the dashboard with `query1=b` (ie. `id=3`).
* Refresh the page.
* You are still viewing panel `id=3`, but are now viewing the _second_ panel of the dashboard with `query0=2`.

An equivalent to the OP's post can be created by loading `id=4`, then removing any value from either variable. The reloaded dashboard will not have a panel with `id=4`.

There are a lot of other ways to replicate the issue, some don't even need user attention -- for instance a variable that repeats over the results of a query can gain new values (or lose old ones) between page loads, thus changing the `id` of all generated panels.

A fix would be that the panel URL in my example could rather than `&id=3`, use `&id=2&with-var-query1=b`, or `&base-id=2&with-var-query1=b`, or something similar. Grafana can still generate the "virtual" `id` values internally, but ought to use the `with-var-*` parameter(s) to "find or create" the panel the user wanted to link. Create may be needed if the panel would have been in a collapsed row, as in the OP, or perhaps if the variable value was no longer present in the variable's query results. The fix probably should not use the existing `var-*` query parameters, as those would alter what's shown on the full dashboard -- this would be pretty confusing, as selecting 'view' on a panel and then reloading would alter the variable selection when going back.

JSON definition of my test dashboard, which exhibits the issue in Grafana v10.2.0: [grafana-bug-66666.json](https://github.com/grafana/grafana/files/13427092/grafana-bug-66666.json)
