### ISSUE TITLE
[Bug] Silent dashboard overwrite with slash

### ISSUE THREAD

**Issue by rlex** [grafana/grafana#6702]
Please include this information:
- What Grafana version are you using?
4.0.0-beta2
- What datasource are you using?
Doesn't matter
- What OS are you running grafana on?
Ubuntu 16.04
- What did you do?
1. Create dashboard with name, for example, "Telegraf rabbitmq".
2. Import another panel via UI, name it "Telegraf/rabbitmq" (was doing mass dashboards adjustments - adding additional row to 15 dashboards)
3. Import interface shows no conflicts, so press "save"
- What was the expected result?
  - dashboard with name "Telegraf/rabbitmq" should appear
  - "Telegraf rabbitmq" dashboard should be here as well 
OR
  - Grafana should warn about name conflict
- What happened instead?
"Telegraf rabbitmq" dashboard silently deleted from both grafana dashboard listing and database, and Telegraf/rabbitmq appeared

Looks like there is some issue with "/" escaping.
I'm using SQLite, if that matters.

**Comment by torkelo** [comment]
I tried to follow your steps to reproduce

- I created a dashboard name `Telegraf rabbitmq`
- I then created a new dashboard and named it `Telegraf/rabbitmq`

When I save that I get:
![image](https://cloud.githubusercontent.com/assets/10999/20621045/04047544-b2fd-11e6-9525-a4cd1269b45e.png)

But the import step that checks if a dashboard exists seem to only do name check (no the slug/id), the slug which is the unique id removes whitespace/slashes.

Will fix so the import checks for slug instead of name

**Comment by bergquist** [comment]
@torkelo working in this?

**Comment by torkelo** [comment]
no, I did look at it once, at it was not the 10min quick fix I had hoped :(

**Comment by torkelo** [comment]
this should not be possible anymore in v5
