### ISSUE TITLE
"Tempo Cheat Sheet" saying "Tempo is a trace id lookup store", outdated?

### ISSUE THREAD

**Issue by cyrille-leclerc** [grafana/grafana#67045]
The Tempo Cheat Sheet says

> Tempo is a trace id lookup store. Enter a trace id in the above field and hit “Run Query” to retrieve your trace. Tempo is generally paired with other datasources such as Loki or Prometheus to find traces.
> Here are some [instrumentation examples](https://grafana.com/docs/tempo/latest/guides/instrumentation/) to get you started with trace discovery through logs and metrics (exemplars).

Isn't it an outdated presentation of Tempo? shouldn't we say that "Tempo distributed traces store accessible thought a rich query language: TraceQL

![image](https://user-images.githubusercontent.com/459691/233494412-12bcc520-d448-4041-8d29-f4440424cdbd.png)

I couldn't find where this text is located in the source code so I couldn't initiate a conversation on a pull request.

**Comment by knylander-grafana** [comment]
Greetings. The text is located in this file: /grafana/public/app/plugins/datasource/tempo/CheatSheet.tsx

I talked with @joey-grafana about this today. I'll provide text in this issue and he'll test it in Grafana build to make sure it works okay. 

I did notice that the existing cheat sheet doesn't have any active links, even though they are defined in the file, probably because the link it out of date.

The cheat sheet is accessed by pressing the "?" when looking at the Tempo data source in Grafana.

**Comment by knylander-grafana** [comment]
I kept this text focused on using the query builder and TraceQL, since that is the context in which it appears. 

Proposed text: 
```
<a href="https://grafana.com/docs/tempo/latest/">Grafana Tempo</a> is an open source, easy-to-use, and high-volume distributed tracing backend.

Tempo implements <a href="https://grafana.com/docs/tempo/latest/traceql">TraceQL</a>, a traces-first query language inspired by LogQL and PromQL. This query language allows users to very precisely and easily select spans and jump directly to the spans fulfilling the specified conditions.

You can compose TraceQL queries using either the Query type > Search (the TraceQL query builder) or the TraceQL tab (the TraceQL query editor). Both of these methods let you build queries and drill-down into result sets. (<a href="https://grafana.com/docs/grafana/latest/datasources/tempo/query-editor/>Learn more</a>)
```
