### ISSUE TITLE
Prometheus: Create e2e test for 'undo' (cmd+z) in the code editor

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#67126]
**What is this?**
This issue is to create an e2e test to check if 'undo' works in the prometheus query builder. [(see this test for reference)](https://github.com/grafana/grafana/blob/main/e2e/various-suite/query-editor.spec.ts)

If we use the existing test code in this PR, we should rename things to make it a bit clearer what part of the UI this is testing.

**Why**
Part of an e2e test was removed as it was timing out. This was in a check for 'undo' in the prometheus code editor. The par that was removed was in checking the presence of the query builder. 
https://github.com/grafana/grafana/pull/67116

**Comment by gtk-grafana** [comment]
This refers to the control+z undo behavior? There's no UI for this right?

**Comment by bohandley** [comment]
No UI that I am aware of.

The e2e test leads me to believe that it would be control+z but the old test only tested typing the character 'backspace'. I think the test could be renamed.
https://github.com/grafana/grafana/blob/c308118fc024eae0a7bf48a0b681e234e37262c3/e2e/various-suite/query-editor.spec.ts#L25

**Comment by shantanualsi** [comment]
@bohandley @gtk-grafana I think the test consists doing a backspace first and then undo on the backspace.. Anything that I am missing? 
```
    e2e.components.QueryField.container().type(queryText, { parseSpecialCharSequences: false }).type('{backspace}');
    cy.contains(queryText.slice(0, -1)).should('be.visible');
    e2e.components.QueryField.container().type(e2e.typings.undo());
    cy.contains(queryText).should('be.visible');
```

**Comment by gtk-grafana** [comment]
Yes that looks right!

**Comment by shantanualsi** [comment]
I understand that the test is only for the code editor. Does the query builder support undo? I am trying on my local environment UI and it does not work..

**Comment by gtk-grafana** [comment]
No I don't think the query builder supports undo behavior.

**Comment by shantanualsi** [comment]
I think we can close this issue in that case?

**Comment by gtk-grafana** [comment]
Hmmm yeah, something doesn't add up. @bohandley do you have more context on this, maybe ctrl+z used to work in query builder?

**Comment by gtk-grafana** [comment]
Ok, I think we're being thrown off by the terminology.
The test explicitly calls the code editor the `query editor for prometheus`, I believe it was written before a "query builder" existed, so that's throwing us off, I'll update the ticket name and description to hopefully make things clearer.

Ctrl+z does still work in the code editor, and this is what we want to be testing.

**Comment by shantanualsi** [comment]
Sorry, I might be missing something here.. Just trying to understand - 

**query builder** - does not support undo, so no tests required
**query editor** - the e2e test has testing for undo (as mentioned in the [snippet in this comment](https://github.com/grafana/grafana/issues/67126#issuecomment-1614651069) - line 3 and 4. So that isn't sufficient?

**Comment by gtk-grafana** [comment]
🤦 Rough Friday today. https://github.com/grafana/grafana/pull/67116/files. yeah, we never removed the control+z part of the test, I'm just being obtuse. Closing this out, thank you @shantanualsi!
