### ISSUE TITLE
Lazy loading not working as expected for Table panels

### ISSUE THREAD

**Issue by Migueljfs** [grafana/grafana#67146]
## What happened:
Table panels with multiple queries and hundreds of rows taking a long time to load.
I have some table panels where I do multiple queries to my Thanos backend, which return hundred of results for each query (for example I query CPU usage, memory usage, etc for all pods in my k8s cluster)

## What you expected to happen:
Expected a subset of the results to be loaded and more results to be loaded as users scroll the table.

## How to reproduce it (as minimally and precisely as possible):
- Create a table panel to fetch a lot of records from multiple queries
- Open the network tab in chrome or another browser.
- Load the dashboard.
- Notice in the network tab how no subsequent queries are done as you scroll the table and how it takes as significant time to load it

## Anything else we need to know?:
I might have interpreted the "Lazy Loading" feature wrong, if so I apologize in advance and is there a way to achieve this behaviour if so?

## Environment:
- Grafana version: 9.4.7
- Data source type & version: Prometheus 5.0.0
- OS Grafana is installed on: Alpine Linux v3.17
- User OS & Browser:  Ventura 13.2.1 / Google Chrome Version 112.0.5615.137 (Official Build) (x86_64)
- Grafana plugins: N/A
- Others: N/A

**Comment by mellieA** [comment]
@Migueljfs the lazy loading feature issues queries for panels as they are in the viewable area of the dashboard: 
https://grafana.com/blog/2019/07/08/a-closer-look-at-lazy-loading-grafana-dashboards/

The feature you're looking for would be server-side paging, where multiple queries are sent to the datasource. There was a feature request for that, but the response is that it would likely not be done due to the complexity of supporting so many different implementations of it for each datasource: https://github.com/grafana/grafana/issues/14517

**Comment by jicki** [comment]
> @mellieA Is there a solution you would propose for this sort of issue?
> 
> Say I have a table to display various information regarding all pods for a given deployment, if that deployment has 4000 replicas it will be extremely slow.
> 
> Even if I hide that panel in a non-viewable area of the dashboard (which I don't want to do since it is the most important panel to look at) it will still take ages to load when someone tries to view it

me too
