### ISSUE TITLE
Dashboard Save Dialog click away breaks UI

### ISSUE THREAD

**Issue by mkg20001** [grafana/grafana#67203]
## What happened:

- The dashboard gets saved but incrementing the version fails / isn't done, so grafana thinks there are still changes and warns you of an overwrite when saving

https://user-images.githubusercontent.com/7735145/234277928-31f0901c-8395-40e7-8bf3-6479b86e4316.mp4

## What you expected to happen:

- It should just work

## How to reproduce it (as minimally and precisely as possible):

- Change dashboard, save dashboard
- While save animation is displayed click away dialogue (by clicking outside of it on left side)

## Anything else we need to know?:

- Maybe something related to the request success handling is destroyed prematurely by clicking away the ui. It shouldn't be attached to that.

## Environment:
- Grafana version: v9.4.7
- Data source type & version: -
- OS Grafana is installed on: nixos unstable
- User OS & Browser: nixos unstable, chrome 113.0.5672.37
- Grafana plugins: default
- Others:

**Comment by mellieA** [comment]
@mkg20001 I'm not seeing this behavior on 9.5 (cloud) or running on-prem on MacOS. On both releases, I can only see the changes tab after I've saved. Have you tried using developer tools or capturing a HAR file while performing these actions to see if the "save" (a network call to /db) happens when you click away? 

Using MacOS 13.3.1 and Chrome Version 112.0.5615.137

**Comment by mkg20001** [comment]
I upgraded and no longer occuring
