### ISSUE TITLE
[Feature request] Add open tracing in grafana

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#6734]
Using the tracing support in golang 1.7 it should be possible improve the metrics collection for all http requests and add support for distributed tracing using the [opentracing](http://opentracing.io/) golang library.

**Comment by bergquist** [comment]
Would make it easier to debug issues like this https://github.com/grafana/grafana/issues/6718

**Comment by Dieterbe** [comment]
+1 for opentracing support, i've done it for metrictank, so can give some tips.

I recommend using https://uber.github.io/jaeger/ it has good clients in a variety of languages (go being one of the main ones) and implements opentracing.

here's my 2c: 

* grafana should propagate a context if it received one (so that requests to backend datasources can be tied to the request in grafana, and to whatever was sending the request to grafana)

* alert queries should get a request id, so that if an alert fires and results in "no data", "execution error", or anything weird really, you can track down the exact request in the tracing system and/or in logs of the datasource and find out exactly went wrong for that exact request

* similarly, I want to tie back exact requests in grafana to the backend datasource. this means that every request generated by the frontend should have a requestid, so that when you click on the red error box in the grafana UI, you can get the id or a link which takes you straight to jaeger's interface.

**Comment by bergquist** [comment]
POC: https://github.com/grafana/grafana/tree/dist_tracing

**Comment by bergquist** [comment]
Closing this issue since we added initial support for open tracing using jaeger. If you want more tracing please open an new issue/PR.
