### ISSUE TITLE
Publicly reported Security vulnerabilities

### ISSUE THREAD

**Issue by dppatel99** [grafana/grafana#67464]
Hi team,

In our vulnerability scan report there are 2 HIGH vulnerabilities in grafana/grafana:v9.5.1

Component | Vulnerability | Severity | Installed Version | Latest Version | Description
| ---------- | ------------ | -------- | ----------------- | ---- | ---- |
| ncurses  | [CVE-2023-29491](https://nvd.nist.gov/vuln/detail/CVE-2023-29491) | HIGH | 6.3_p20221119-r0 | 6.4 | https://github.com/advisories/GHSA-vh2x-5rx6-qqhv
|  sqlite3  | [CVE-2022-46908](https://nvd.nist.gov/vuln/detail/CVE-2022-46908)   | HIGH | 3.39.4 | 3.41.2 | https://github.com/advisories/GHSA-993x-6558-2xmj

My suggestion: ncurses and sqlite3 version update should solve the problem.

Can we expect fix in upcoming release ?

**Comment by papagian** [comment]
thank you for reporting this

for buliding grafana we use [alpine:3.17](https://github.com/grafana/grafana/blob/8ca9a89cf1ca4f6c99b65f57b808bf4fe1c8c4d2/Dockerfile#L3) image (latest stable) that does not seem to include the patched releases (only the edge branch does):
[ncurces version](https://pkgs.alpinelinux.org/packages?name=ncurses&branch=v3.17&repo=&arch=&maintainer=) is still 6.3_p20221119-r0 and [sqlite version](https://pkgs.alpinelinux.org/packages?name=sqlite&branch=v3.17&repo=&arch=&maintainer=) is 3.40.1-r0.

we don't think that grafana is vulnerable to these CVEs (not using sqlite3 CLI and ncurses with setuid) 
but in any case they will be fixed in the next grafana release that it will be build after they are fixed in alpine.
