### ISSUE TITLE
BarChart: Labeling is skipped for every other bar when too many bars are present

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#67788]
Only every other bar gets a label when adding more bars via datagrid entries. 
This is only visible on the dashboard itself. If you go into the edit mode all bars are labeled. 

Steps to reproduce:
1. create a data grid with some entries
2. create a bar chart with the datagrid dashboard as source
3. add multiple entries to the datagrid

Expected Result:
I expected that the new entries of the datagrid are being added to the barchart, including the labels for each bar.

Actual Result:
The bars are being added but when there are too many entries, only every other bar gets labelled. When switching to the editing mode, all bars are labelled accordingly.

https://user-images.githubusercontent.com/110845248/236053096-a8611179-6589-46cd-ad56-c119a5bf92a4.mov

**Comment by leeoniya** [comment]
this is by design when you have x label minimum spacing set to something other than None. the label skipping depends on chart width, so may look different in edit mode where the panel becomes full width.

![image](https://user-images.githubusercontent.com/43234/236056184-5009efa2-132a-42a6-8e0d-54bbaeda52fb.png)
