### ISSUE TITLE
[Bug]4.0.0 grafana-cli on OpenSuse not working correctly

### ISSUE THREAD

**Issue by steviecoaster** [grafana/grafana#6780]
Trying to install the Pie Chart Panel, as well as the Zabbix plugins results in the following error:

:~# grafana-cli plugins list-remote
Failed to send requesterrorGet https://grafana.net/api/plugins/repo: x509: failed to load system roots and no roots provided
Error: ✗ Failed to send request. error: Get https://grafana.net/api/plugins/repo: x509: failed to load system roots and no roots provided

NAME:
   Grafana cli plugins list-remote - list remote available plugins

USAGE:
   Grafana cli plugins list-remote [arguments...]
:~#

Is there something I should check on my system?

**Comment by bergquist** [comment]
Seems like the CLI cannot establish a secure connection with grafana.net. Can you run `curl https://grafana.net/api/` on our machine and see if it works?

**Comment by steviecoaster** [comment]
Seems you are correct. Output from my server:
 curl https://grafana.net/api/
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

using curl https://grafana.net/api/ -k returns good data.

**Comment by daniellee** [comment]
Ran a quick check with ssllabs and grafana.net gets an A: https://www.ssllabs.com/ssltest/analyze.html?d=www.grafana.net

![image](https://cloud.githubusercontent.com/assets/434655/20856111/be47ac18-b907-11e6-8bed-7a96a08d8f03.png)

I think the problem is with your curl's ca cert. See this [Stack Overflow answer](http://stackoverflow.com/a/31830614/22688) and this [Ask Ubuntu answer](http://askubuntu.com/a/719624/498572) where they recommend downloading the [ca certs for curl from Mozilla](https://curl.haxx.se/docs/caextract.html).
