### ISSUE TITLE
[Bug] The datasource does not support alerting queries

### ISSUE THREAD

**Issue by rmsys** [grafana/grafana#6782]
- What Grafana version are you using?
Grafana v4.1.0-pre1 (commit: 09e49f0)
- What datasource are you using?
Zabbix / Plugin grafana-zabbix v3.1.0
- What OS are you running grafana on?
CentOS 6 x64 (AMI Linux AWS v4.4.5-15.26.amzn1.x86_64) 
- What did you do?
Setup Alerting
- What was the expected result?
Alert successfully created
- What happened instead?
Error message came " The datasource does not support alerting queries"

If it relates to *alerting*
- An image of the test execution data fully expanded.

![chat-alert-grafana-zabbix](https://cloud.githubusercontent.com/assets/7168855/20801535/6969d44c-b7d0-11e6-9f0b-1a28fd5c15a8.PNG)

**Comment by torkelo** [comment]
Zabbix is not supported by the alerting engine

**Comment by steviecoaster** [comment]
Is this something on the roadmap to implement? Or is this up to the maintainer of the zabbix plugin to add support for alerting on his end of things?

**Comment by torkelo** [comment]
Kind of, but first we need to make it possible to implement backend plugins, which we hope to do this year

**Comment by shawnloong** [comment]
which version 4.2 support zabbix plugin

**Comment by torkelo** [comment]
@shawnloong no version supports alerting & zabbix

**Comment by shawnloong** [comment]
In development?

**Comment by torkelo** [comment]
no there is no development being done for zabbix alerting support. 

Since alerting is backend feature (backend in Go),  we need backend plugins in order to support alerting for non core data source plugins. 

Here is the issue for backend plugins. And no we have yet to start working on backend plugins, but hope to get to it within the next 12 months. 
https://github.com/grafana/grafana/issues/6841
