### ISSUE TITLE
[Bug]Graph shows nothing but the data is received

### ISSUE THREAD

**Issue by 3tinkers** [grafana/grafana#6797]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
- 2.0.2
- What datasource are you using?
- graphite
- What OS are you running grafana on?
- Cent OS 7
- What did you do?
- Use graph to display data
- What was the expected result?
- Graph should show the data
- What happened instead?
- Graph shows nothing.When I check the 'Current' under 'Legend' it can display the current received data in the legent, but nothing displays in the graph.

**Comment by orester** [comment]
faced the same issu.

**Comment by torkelo** [comment]
Can you show the query and the response from influxdb? You can see the response from InfluxDB if you open chrome dev tools network tab.

**Comment by orester** [comment]
Sure – here we go:

The query in cleartext from the query-editor:

SELECT mean("value") FROM "icmpstats_rtt" WHERE "dst.loc" =~ /^$dst$/ AND "src.loc" =~ /^$src$/ AND "value" = -1 AND $timeFilter GROUP BY time($interval), "dst.loc" fill(null)

From dev-tools:

1.     Request URL:
https://grafana.is.icepor.com/api/datasources/proxy/12/query?db=uv&q=SELECT%20mean(%22value%22)%20FROM%20%22icmpstats_rtt%22%20WHERE%20%22dst.loc%22%20%3D~%20%2F%5EGCI%7CGIB%7COOS%7CPAR%7CSOF%7CVIE%24%2F%20AND%20%22src.loc%22%20%3D~%20%2F%5EGCI2%7CGIB2%7COOS%7CPAR%7CSOF%7CVIE%24%2F%20AND%20%22value%22%20%3D%20-1%20AND%20time%20%3E%20now()%20-%201h%20GROUP%20BY%20time(5s)%2C%20%22dst.loc%22%20fill(null)&epoch=ms
2.     Request Method:
GET
3.     Status Code:
200
4.     Remote Address:
xxxxxxx
2.     Response Headers
1.     content-encoding:
gzip
2.     content-length:
3905
3.     content-type:
application/json
4.     date:
Mon, 05 Dec 2016 11:42:31 GMT
5.     request-id:
e7f925ba-badf-11e6-8be1-000000000000
6.     status:
200
7.     x-influxdb-version:
1.1.0
3.     Request Headers
1.     :authority:
grafana.is.icepor.com
2.     :method:
GET
3.     :path:
/api/datasources/proxy/12/query?db=uv&q=SELECT%20mean(%22value%22)%20FROM%20%22icmpstats_rtt%22%20WHERE%20%22dst.loc%22%20%3D~%20%2F%5EGCI%7CGIB%7COOS%7CPAR%7CSOF%7CVIE%24%2F%20AND%20%22src.loc%22%20%3D~%20%2F%5EGCI2%7CGIB2%7COOS%7CPAR%7CSOF%7CVIE%24%2F%20AND%20%22value%22%20%3D%20-1%20AND%20time%20%3E%20now()%20-%201h%20GROUP%20BY%20time(5s)%2C%20%22dst.loc%22%20fill(null)&epoch=ms
4.     :scheme:
https
5.     accept:
application/json, text/plain, */*
6.     accept-encoding:
gzip, deflate, sdch, br
7.     accept-language:
en-US,en;q=0.8,de;q=0.6
8.     cookie:
grafana1_icepor_sess=0b72f0a7d741536f; grafana_user=orester; grafana_remember=9d54544a0e1844044e9cc63abbeec0e4ab9df17930f9ab44a40ec7b1
9.     referer:
https://grafana.is.icepor.com/dashboard/db/noc-rtt-uv?panelId=21&fullscreen
10.   user-agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
4.     Query String Parametersview sourceview URL encoded
1.     db:
uv
2.     q:
SELECT mean("value") FROM "icmpstats_rtt" WHERE "dst.loc" =~ /^GCI|GIB|OOS|PAR|SOF|VIE$/ AND "src.loc" =~ /^GCI2|GIB2|OOS|PAR|SOF|VIE$/ AND "value" = -1 AND time > now() - 1h GROUP BY time(5s), "dst.loc" fill(null)
3.     epoch:
ms

I am able to see “points” in hover info:

[cid:image001.png@01D24EF5.D7560AA0]

But not in the graph. Otherwise – after removing query where-clause (where value = -1):

[cid:image002.png@01D24EF5.D7560AA0]


I double checked query in influx cli – its correct (and was already in use in an older grafana dash).


Many Thanks for looking into!

Cheers & BR
Oliver

**Comment by torkelo** [comment]
you have fill(null) in your query, make sure the group by time is not lower than your write rate. 

You can below the queries specify a lower limit, like `>10` in the group by time option

**Comment by orester** [comment]
Write rate is one point per second (in detail – 1 ping every second which is sent, metered  and response is written to influx).

Changing group by time interval unfortunately not helped. But .. IMHO – I am not missing any response in terms of data points – they were simply to drawn in the graph (But I am able to see the hover info .. ).

I will test with an older grafana version ..
Cheers & BR
Oliver

**Comment by orester** [comment]
Same Dashboard / Query with grafana version 3.2.x:

[cid:image001.png@01D24EFA.EA7F0870]

Works!!

Cheers & BR
Oliver

From: Oliver Rester
Sent: Monday, December 5, 2016 13:07
To: 'grafana/grafana' <reply@reply.github.com>; grafana/grafana <grafana@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [grafana/grafana] [Bug]Graph shows nothing but the data is received (#6797)

Write rate is one point per second (in detail – 1 ping every second which is sent, metered  and response is written to influx).

Changing group by time interval unfortunately not helped. But .. IMHO – I am not missing any response in terms of data points – they were simply to drawn in the graph (But I am able to see the hover info .. ).

I will test with an older grafana version ..
Cheers & BR
Oliver

**Comment by torkelo** [comment]
have you open chrome dev tools network tab and inspected the response from InfluxDB? what are the raw data returned by your query? Sure there are no nulls there between points? You also check by going into graph display tab and change null value mode
