### ISSUE TITLE
Grafana: Alert Notifications cannot be edit by non-Admins

### ISSUE THREAD

**Issue by davidnewhall** [grafana/grafana#68037]
### 
# What went wrong?

**What happened**:
After upgrading from legacy to unified alerting, my users can no longer control where their notifications go.
 

**What did you expect to happen**:
My users should still be able to control the notification channel for alerts they own.

### 
# How do we reproduce it?

**Step 1**:

Create an alert and a matcher rule as an admin. Save the alert in a folder.

**Step 2**:

Log into Grafana as a Viewer user with admin on the folder the alert is in. This user cannot edit the Notification policy.

### 
# What Grafana version are you using?

OSS 9.4.7

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### Is this a Regression?

Yes

### Anything else to add?

All of my users are 'Viewers'. Each user is a member of a team. Each team has admin access to one of more folders. Users are free to edit dashboards and alerts in their folders. Since notification policies do not have a folder, the users do not have access to them.

We do not have enough Grafana admins to handle the influx of requests for muting and changing notification policies. Please fix this.

**Comment by yuri-tceretian** [comment]
Unfortunately, this is how it is intended to work. Currently, only the admin can edit notification policies because they are applied globally and do not have any scopes. There are plans to work on a better API for notification policies but no specific date\release when that will happen.

In Grafana Enterprise which supports a fine-grained access control admins can let users update the notification policy without admin permissions, but it still has global scope, which means that one user can create a notification policy that affects rules created by another user that the first user cannot even see. 

As a potential workaround, I recommend using provisioning (file or API): split notification policies by files, let users edit only one file (of a team they belong to), and moderate changes. 
Each alert has a label `grafana_folder` that contains the name of the folder that contains a rule that created the alert. So the moderator could verify that the notification policies of one group will not affect another.

Another alternative is to split teams by organization.

The workarounds are not trivial but unfortunately, those are the only possible options I can think of now. 
cc @ryan-grafana @armandgrillet

**Comment by davidnewhall** [comment]
Sounds like I'll be going back to legacy alerting. This sucks.
