### ISSUE TITLE
[bug] alerting goes back to OK for some weird reason

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#6805]
![alerting-back-to-ok-why](https://cloud.githubusercontent.com/assets/20774/20847279/6110e828-b89b-11e6-9630-37fa6273b33d.png)
using Grafana v4.0.0-beta1 (commit: 6e94cce) with graphite-metrictank.

![condition](https://cloud.githubusercontent.com/assets/20774/20847392/d8af8c0e-b89b-11e6-88e1-40fbb7fdc959.png)

so it triggers when the "avg" (of valid points with null points) becomes low, this is what i want (because null means 0), but after that, when all values are null, for some reason the state goes back to OK, pretty much when all points in the 5m window have become null

**Comment by bergquist** [comment]
ref https://github.com/grafana/grafana/commit/6c9cf87080e52966846a48d04209d90c166ca42e

**Comment by bergquist** [comment]
This alert was triggered and set back to ok for 2 reasons. 
- It trigger due to the avg calculation bug fixed in https://github.com/grafana/grafana/commit/6c9cf87080e52966846a48d04209d90c166ca42e
- It then got back to status ok due to an other bug which was fixed by https://github.com/grafana/grafana/commit/50811c80eaa5a37d78a6cd99c636067e50d36d78#diff-60eb372c14914c3d8d9d9b4d6e468cb2
