### ISSUE TITLE
[Feature request] Annotations' details without mouse hover

### ISSUE THREAD

**Issue by messier51a** [grafana/grafana#6814]
Would it be possible to add the option to permanently display the Annotation's information on the chart without having to mouse hover?

Thanks!

**Comment by torkelo** [comment]
no, there is no real room for them.

You can use the table panel to show annotation data

**Comment by dineshdh** [comment]
This is a valid request. I’m an SRE and I can see this being a valuable feature when conducting blameless post-mortems etc. surely the text can be rotated vertically. Additionally can we set a colour for each annotation so that it is easier to visually match annotation markers with the tabular text (assume each row is coloured differently)

**Comment by pkoevesdi** [comment]
I would second that feature. I have annotated a graph with 3 annotations and want to make a screenshot containing all of them. The space is enough, they are clearly visible and can easily matched visually - one at a time. How am I supposed to hover over all 3 of them simultaneously?
I'd suggest to make a small checkbox inside the annotation edit field to makr it as persistently visible.
Whether there is enough room for them or not is up to the user and strongly depends on his screen, setting, graph zoom, amount of annotations etc. Quite daring to generally say, there would be not enough room to show more than one at a time.

**Comment by peterprvy** [comment]
I agree with the checkbox for permanent display
