### ISSUE TITLE
[Feature request]  Integration of Grafana 4 with irc server

### ISSUE THREAD

**Issue by brijesh27** [grafana/grafana#6823]
Please include this information:
- We are using Grafana 4 
- Datasource : Graphite 
- OS : centos 6.8

Is there any way to integrate the grafana alerts to internal irc servers( sending alerts to specific irc chat channel) like it have slack ?

Thanks,
Brijesh

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
