### ISSUE TITLE
Change panel visualizations do not set the `target.format = 'table'` anymore?

### ISSUE THREAD

**Issue by shezhangzhang** [grafana/grafana#68294]
### 
# What went wrong?

**What happened**:

I found in v9, change panel visualizations do not set the `target.format = 'table'`, it changes `type = 'table'`, how can I get the current panel format type (here is 'table') in my old angular system plugin?

And how to get the panel JSON in a plugin?

  - 

**What did you expect to happen**:

  - 

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and do X 

**Step 2**:

- Now click button Y

**Step 3**:

- Wait for the browser to crash. Error message says: "Error..."

use the v9 vs v6

### 
# What Grafana version are you using?

v9.2.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by usmangt** [comment]
Hi @shezhangzhang,

Thanks for opening this issue.

Regarding your 1st part of the question about changing panel visualization. Can you please provide the steps of reproduction so that the community can also try to reproduce it on a test machine? 

For the 2nd part, You first need to install a JSON Plugin (you can find a list of available Data source plugins [here](https://grafana.com/grafana/plugins/?search=json)). 

For e.g. if you have installed the JSON Infinity plugin, then enable this Data source plugin and after that it will be available into your query section to select the Data Source.

Thanks.
