### ISSUE TITLE
[Feature request] Graph Panel like Thresholds for Singelstat Gauges

### ISSUE THREAD

**Issue by aaron868** [grafana/grafana#6831]
The version 4.x Thresholds feature for graph panels is excellent. Could you add this same feature to Singlestat gauges? Ideally this would show the threshold markers and labels for the complex threshold parameters. I have, and imagine many others do as well, measures where the normal value has an upper and lower bound (e.g., -1 to 1) and warning values are those that exceed these upper and lower bounds (e.g., LT -1 and GT 1). 

Thank you.

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

We are working on a threshold system for all panels rather than implementing one per panel.

Thank you to you for taking the time to create this issue!
