### ISSUE TITLE
[Feature Request]: Support serving static assets of CDN 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#6844]

**Comment by mtanda** [comment]
same as https://github.com/grafana/grafana/issues/2954

**Comment by lorenwest** [comment]
@mtanda - I don't think this is the same as #2594, because that was about .js assets and the resolution in that issue doesn't work for other assets (fonts, images, etc). Still waiting for this feature as our CDN is closer to the edge, and the 5.1 release doubled the size of javascript, so mobile download speed has suffered.

**Comment by torkelo** [comment]
5.1 doubled size? Compared to which release?

**Comment by sdenel** [comment]
@lorenwest It is to note that vendor.0cea50118711e7e6c839.js and app.5372b9bbcb8c6d1c027e.js are not minified (nor sent compressed) at the time of writing.
At least for compression, you can use a reverse proxy (like Nginx).

**Comment by Gauravshah** [comment]
@lorenwest would you be able to open a PR so that all can benefit from your changes?

**Comment by lorenwest** [comment]
@Gauravshah - My fork hardcodes to my CDN in the index.html file. The proper way to incorporate this is to define asset paths in configuration. It shouldn't be very difficult, but it's bigger than the hack that works for me.

**Comment by lorenwest** [comment]
@torkelo - I'd like to recommend re-opening this, or expanding #2594 to include all assets.

**Comment by lukecyca** [comment]
@lorenwest any chance you would post your diff in a gist or something? We are interested to make a similar hack to serve the (rather large) javascript assets from a CDN.

**Comment by Gauravshah** [comment]
@torkelo do you suggest adding a feature in grafana that would upload the js or just provide an option to replace the host and provide a tool on the grafana-cli to upload to given location

**Comment by torkelo** [comment]
Think it needs some modifications of the webpack builds, at least last time I tried it it only loaded the first js file from cdn and other files from local install.

But welcome a PR that adds a sever setting for CDN

**Comment by contactsagarkate** [comment]
@lorenwest Thanks for providing a way for supporting it.
@torkelo  Instead of changing in index.html we need a way to config it in config file.
So please let me know, if you have done this, or if not, when will it done.

**Comment by marefr** [comment]
Stumbled upon the webpack documentation and it seems like it should be possible to change the `publicPath` on the fly, see https://webpack.js.org/guides/public-path/#on-the-fly. Have no idea how easy or hard it would be to use that so needs to be investigated/tested.

As Torkel says we need a server setting to point at CDN location. This should be used to dynamically fix all paths so that core builtin static assets like javascript, css, images are loaded from cdn url or local (the default and how it currently works). When in dev mode should always load local assets and not from CDN.

Assets for external plugins are dynamically loaded by SystemJS and in a first step you'll need to make sure that those are resolved by local paths and not CDN. Related code is here: https://github.com/grafana/grafana/blob/master/public/app/features/plugins/plugin_loader.ts#L144-L158

One neat thing would be if the Grafana version/commit could be included as part of the CDN url allowing a CDN to host assets for multiple Grafana versions.

**Comment by jimaek** [comment]
You could use jsDelivr for this. https://cdn.jsdelivr.net/gh/grafana/grafana@7.3.7/public/
All versions are automatically available without any action. 
You can also use version aliasing or specific specific commits.

minification is also supported 
https://cdn.jsdelivr.net/gh/grafana/grafana@7.3.7/public/vendor/css/timepicker.css
https://cdn.jsdelivr.net/gh/grafana/grafana@7.3.7/public/vendor/css/timepicker.min.css

**Comment by Gauravshah** [comment]
@marefr even if its not dynamic we should be able to create a conf on grafana.ini ?
