### ISSUE TITLE
[Feature request] Substitution in custom template variables

### ISSUE THREAD

**Issue by LMnet** [grafana/grafana#6861]
Currently I can't use substitutions in template variables of type _Custom_. I want to use one custom template variable in another custom variable. For example:
`$a = [1,2,3,4]`
`$b = 0.$a`, which will expand to `$b = [0.1,0.2,0.3,0.4]`.

**Comment by daniellee** [comment]
This feature request has been open for a long time with no received upvotes or comments so we are closing it. We are trying to limit open GitHub issues in order to better track planned work and features.

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Still a big Thank You to you for taking the time to create this issue!
