### ISSUE TITLE
We need an endpoint to get the list of potential alerts 

### ISSUE THREAD

**Issue by soniaAguilarPeiron** [grafana/grafana#68615]
During the work on the [notification policies preview ](https://github.com/grafana/grafana/issues/68098), we realised that it would simplify a lot the code if we could add to the eval endpoint (`/api/v1/eval`) an additional parameter with the list of custom labels.

And use this list for the eval calculation alongside the auto-generated labels. 

With this, we can delegate to the BE to interpolate variables in the labels with the correct values.

Update: we will create/update another  endpoint for this purpose.

**Comment by yuri-tceretian** [comment]
I would recommend using a backtesting API that expands labels. Currently, it is behind a feature flag `alertingBacktesting`. You can find information about API, example requests and responses at https://github.com/grafana/grafana/issues/57318

**Comment by soniaAguilarPeiron** [comment]
@yuri-tceretian I tested the api and it works as we expect for the feature we are building 🙌

**Comment by yuri-tceretian** [comment]
After thinking a bit more, I realized that backtesting API might not be a good candidate for the feature we need.

In this diagram, you can see how rule evaluation is transformed into an alert.

![image](https://github.com/grafana/grafana/assets/25988953/87fc240d-f4ac-43c0-a6c1-a649f40cc946)
In my opinion, the preview of rule should do all operations in this diagram to correctly display notification policies.

As you can see, backtesting API does only part of the blocks in the diagram. 
- It does not include some system labels, which can be used for routing and therefore will make the preview incorrect. It is not a big problem to support that in the API, though.
- More important is that backtesting API does not create special types of alerts DatasourceNoData and DatasourceError because it is n
- ot needed for the purpose of testing.

So, I think we need another API endpoint that will evaluate rule, pass results via all steps in the diagram and basically return a list of `alerts` Similar to what we return in Alert Groups page.

I can see great benefits for having such API: we can use it in contact points testing and template testing as a source of alerts\input data.
