### ISSUE TITLE
Merge graphs with drag-and-drop

### ISSUE THREAD

**Issue by rlipscombe** [grafana/grafana#688]
Graphite allows you to merge graphs by dragging one graph on top of another. It'd be cool if grafana either offered this (where it merges the whole graph), or if it allowed you to drag-and-drop a single metric.

This is useful after importing existing graphite graphs.

**Comment by bergquist** [comment]
We might add better ways to move metrics between panels but not using drag and drop since its currently how people rearrange panel positions.

**Comment by torkelo** [comment]
We are trying use open GitHub issues as a way to track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long without any much interest in the feature or anyone showing interest in implementing it. 

A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
