### ISSUE TITLE
[Feature request]Add known security issue in release note

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#6884]
As Grafana is widely used, it is good to know if it has any known security issue or vulnerability, so I suggest adding security section in changelog/release note.

**Comment by torkelo** [comment]
Yes, of course, Anything in particular you are referring to?

**Comment by wei-hai** [comment]
no specific concern. We have security engineer who would like to know if there is vulnerability in order to do assessment.

**Comment by ericvrp** [comment]
@torkelo , In the issue tracking you keep mentioning that when an end-user is able to view a graph from a datasource they are essentially able to handcraft/access (curl) all data because Grafana acts as a proxy to the datasource. The reason being that some datasource (like InfluxDB) have no user access control system. Did I understand that correct so far?

If the above is correctly would it not be more secure if the client only sends some query parameters to the server where a kind of query template is used to construct the actual query?

**Comment by torkelo** [comment]
@ericpp yes, limiting what queries can be proxied would solve that. Currently it's just a proxy

**Comment by ericvrp** [comment]
Sounds like a plan 👍
