### ISSUE TITLE
[Bug] Problem with displaying procent stack graph if all values is near 100% 

### ISSUE THREAD

**Issue by d-ulyanov** [grafana/grafana#6893]
Problem with displaying procent stack graph if all values is near 100%:
Expected: top value is always = 100%
Actual: top value is around 100% but not always rounded to 100% (see picture)

Please include this information:
- Grafana v4.0.1 (commit: v4.0.1) 
- Datasource: Prometheus
- OS X, Chrome

<img width="1266" alt="screenshot" src="https://cloud.githubusercontent.com/assets/3064640/21049520/5d7b24e0-be26-11e6-87a7-c4e330700fc2.png">
[panel.txt](https://github.com/grafana/grafana/files/642147/panel.txt)
[server_response.txt](https://github.com/grafana/grafana/files/642152/server_response.txt)

**Comment by torkelo** [comment]
are you using the grafana stack percent option?

**Comment by torkelo** [comment]
closing this due to lack of more info

**Comment by d-ulyanov** [comment]
Hi, @torkelo !

Yes, stack + percent options used.

See [panel source](https://github.com/grafana/grafana/files/642147/panel.txt)

**Comment by torkelo** [comment]
since you only have one series the min/max in you case becomes very small, in grid options Set Y-min to 0

**Comment by d-ulyanov** [comment]
I purposely set Y-min to auto to see small values from another series. 
For example, if we have 99.7% of HTTP 200 responses on this panel - we will not be able to see 0.1% of HTTP 500.

**Comment by grafov** [comment]
It was example with one kind of codes only but in general this graph shows 3 series (the one for each response code). And we have dynamic range for them with Y-min set to auto. Because it is typical case for us for this metric start Y from 90-99%. And it is looks good in these cases. The bug only appeared then only the metric for the single response code shown - as in the screenshot above.
