### ISSUE TITLE
Loki: Stats endpoint for instant query should get time range based on duration

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#69086]
At the moment, the query size estimation is only (relatively) accurate when doing range queriers, because start and end of the stats query are defined by the values in the time picker.  However, when I do an instant query the time range is not relevant, but rather the range of the query (within the brackets) is. 

So if you have query `rate({a="B"}[5m])` and time range is `now` - `now-1h` , then for query estimation:
- for range query we would send the time range `now` - `now-1h`
= for instant query we would send the time range `now` - `now-5m`

**Comment by gabor** [comment]
i THINK that even for range-queries, we need to add the logql-duration to the time-range, so, for the example at the top, for the range query we should send the range `now` - `now-65m`

(because i think loki will return a data-point right at the beginning of the time-range, and to calculate that data-point, it needs to look "back" 5 minutes... but we should doublecheck this assumption 😄 )
