### ISSUE TITLE
[Feature request] cloudwatch datasource: browse individual log streams

### ISSUE THREAD

**Issue by rt711** [grafana/grafana#6908]
- What Grafana version are you using?
Grafana version 4.0.1
- What datasource are you using?
with built in CloudWatch
- What OS are you running grafana on?
on Ubuntu 16.10
- What did you do?
It's good practice to oraganize awslog streams into groups once they are shipped to CloudWatch, these groups contain all the streams appropriate for a specific log group. 
http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SearchDataFilterPattern.html
I created a new graph by adding the log group from CloudWatch namespace to Grafana installation.
I added CloudWatch as datasource and created metric by: selecting region > aws/logs > log_group_name 
- What was the expected result?
Browse / count incoming lines by individual stream inside CloudWatch log group, so individual streams could be measured within a group.
- What happened instead?
Streams are not browsable, CloudWatch plugin stays on a group level.

**Comment by vickyyyyyyy** [comment]
will investigate this - added to the board

**Comment by sunker** [comment]
From what I understand, this is not possible to do since there is no dimension for log stream. See [AWS docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CloudWatch-Logs-Monitoring-CloudWatch-Metrics.html). 

I'm gonna close this issue, but feel free to re-open it if you have an idea on how to solve this in the cloudwatch data source in Grafana.
