### ISSUE TITLE
error loading alert group in UI when creating new alert via UI

### ISSUE THREAD

**Issue by nkol2307** [grafana/grafana#69213]
### 
# What went wrong?

**What happened**:

  We have positioned alerts and alert group e.g RWS-DEV

during creating of new alert via ui we wanted to load already existing RWS-DEV alert gourp but it was not loading existing alert groups and if we want to create add new one RWS-DEV it gives following error it can not create RWS-DEV since it is provistioned 

![MicrosoftTeams-image (18)](https://github.com/grafana/grafana/assets/56689311/d556dd21-7195-4079-9ad9-6107384e2473)

**What did you expect to happen**:

  We expect that already persisted alerts groups are loaded in uI and gave to users as option to be choosen

### 
# How do we reproduce it?

**Step 1**:

Grafana 9.5.2 persist some alerts via file
**Step 2**:

create new alert

**Step 3**:

choose alert group

### 
# What Grafana version are you using?

9.5.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by grobinson-grafana** [comment]
Hi! :wave:

In Grafana, you cannot add alert rules via the UI to existing (Folders, Evaluation groups) that already contain provisioned alert rules. I appreciate that the error message is not helpful in explaining this and we will look at how to improve it.

**Comment by nkol2307** [comment]
so datasource was Prometheus and we created new alert rule via ui but wanted to use the same group like it is already provisioned for other alert rules and this was not possible to load via UI for this new alert

**Comment by armandgrillet** [comment]
We need to do two things:

1. Backend: stop users from provisioning alert rules to an existing alert group (that has not been provisioned). Otherwise, they can "block" an alert group that has not been provisioned. **We cannot do this as this would create a regression and block the flow "export alert rules" => "provision alert rules" => existing alert rules have been replaced**
2. Frontend: make it clear in the front-end that a group has been provisioned when listing rules.
3. Frontend: show provisioned groups as disabled when creating an alert rule via the UI.

**Comment by nkol2307** [comment]
so this one is resolved ?
