### ISSUE TITLE
Alerting: Webhook/Slack generatorURL/SilenceURL missing orgId when alert-rule has no dashboard/panel link set

### ISSUE THREAD

**Issue by michael-sawczuk** [grafana/grafana#69293]
### 
# What went wrong?

**What happened**:
I noticed sometimes the generatorURL will be missing the orgId from our Slack and Webhook messages, I managed to track it down to alerts without a dashboard/panel link. This is also affecting the silenceURL.

**What did you expect to happen**:
Regardless whether a dashboard/panel link is present, I would always expect an orgId to be present.

### 
# How do we reproduce it?

**Step 1**:
- Open Grafana (with multi-orgs) and create an alert rule with a dashboard/panel link and route it slack and/or webhook

**Step 2**:
- Trigger the alert to fire, observe `generatorURL` and `silenceURL` has an orgId specified.

**Step 3**:
- Remove the dashboard/panel link and retrigger the alert-rule

**Step 4**:
- `generatorURL` and `silenceURL` won't have an orgId present

### 
# What Grafana version are you using?

v9.4, v9.5

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

MacOS Ventura

### User's Browser?

Firefox

### Is this a Regression?

None

**Comment by JacobsonMT** [comment]
Thanks for the bug report! This has been fixed in main and backported to v10.0.x, see: upstream [silenceUrl](https://github.com/grafana/alerting/commit/a8e75e4dfdda7be361544cc9eb60bd74c82682fc), [generatorUrl](https://github.com/grafana/alerting/commit/ae6e544ef5e30e1d38dc29642e0935d002687753), as well as [fix](https://github.com/grafana/grafana/pull/69011) in grafana/grafana v10.0.x
