### ISSUE TITLE
[Bug] Flapping alerting

### ISSUE THREAD

**Issue by ingtarius** [grafana/grafana#6934]
Hello there! We are trying to use cool feature in Grafana - alerting and have some strange issue: After warning value, notifications start to flapping from error to ok and back to error
Below is graph for some metric, stored in graphite:
![image](https://cloud.githubusercontent.com/assets/7605516/21109941/54d078f8-c0ac-11e6-89b6-cad4f32a7a6c.png)

Below is alert data settings:
![image](https://cloud.githubusercontent.com/assets/7605516/21110062/d1e810bc-c0ac-11e6-9791-b703fa43e9f6.png)

Could you please help me in this situation?...

**Comment by bergquist** [comment]
Which version of grafana are you using? Could you please show the queries in the metrics tab?

**Comment by ingtarius** [comment]
Graphana package have 4.0.0-1480439068 version
And metrics is:
A: servers.server01.munin.pg_dwh_export_succes.count.age_daily
B: servers.server02.munin.pg_dwh_export_succes.count.age_delta

**Comment by bergquist** [comment]
I suggest you upgrade to 4.0.2.

4.0.0 have a bug in the avg() reducer that threat null values as 0. Which would affect the value that is compared against the threshold.

**Comment by ingtarius** [comment]
oh, sounds great. 
Thanks, give me 3 days for update and re-check this issue

**Comment by torkelo** [comment]
ok, let us know and we will re-open it

**Comment by eMerzh** [comment]
hi @torkelo , 
i think i experience the same kind of issue
<img width="925" alt="image" src="https://user-images.githubusercontent.com/177003/33906342-f5c69c5c-df81-11e7-89bf-71afbfa36a37.png">

<img width="817" alt="image" src="https://user-images.githubusercontent.com/177003/33906393-179135b8-df82-11e7-94ff-6a964e96fc0e.png">

with grafana  Grafana v4.5.2 (commit: ec2b0fe) (and graphite)

**Comment by eMerzh** [comment]
@torkelo ,
still the issue with 4.5.2 
<img width="686" alt="image" src="https://user-images.githubusercontent.com/177003/35264273-63766cea-001c-11e8-8188-383539c011bb.png">


<img width="541" alt="image" src="https://user-images.githubusercontent.com/177003/35264316-9263eb36-001c-11e8-95a3-00eb84671d00.png">

i can't see what was the detected value for the OK state but you got the idea

**Comment by bergquist** [comment]
Better logging for understanding the alert rule execution is something we really want to start working on after the 5.0 release. Until then I suggest you upgrade to latest version of grafana and add a second condition that require at least X datapoints for the rule to trigger. Ex http://play.grafana.org/dashboard/db/alerting?panelId=1&fullscreen&edit&orgId=1&tab=alert

That might help if the query returns too few data points for avg to make sense. 

Another solution might be to use `min()` instead of `avg` which will require all datapoints within the timerange to be above the threshhold.
