### ISSUE TITLE
[Feature request] Hide null/empty series when using X-Axis mode Series

### ISSUE THREAD

**Issue by absolutejam** [grafana/grafana#6942]
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
4.0.0
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Ubuntu 16.04
- What did you do?
Created a graph with X-Axis in 'Series' mode.
- What was the expected result?
Works as expected, but it would be handy to have an option to hide empty/null series. For example, I am showing the disk usage by hosts, but some of the hosts no longer exist, so their current value is empty and they still appear along the X-Axis.

Thanks for this amazing piece of software and your hard work!

**Comment by ckaenzig** [comment]
Hi, I'm also interested in this (Prometheus datasource, grafana 4.2). In a graph in series mode, I'm showing the current value for the disk usage of all volumes on a server. Volumes that don't exist anymore have a null current value.

There is an option to hide series "with only nulls", but that doesn't help because the the series have non-null data further in the past. I would like to hide series where the current value is null (or where whatever is selected under X-Axis Value is null).

Thanks!

**Comment by daniellee** [comment]
The graph panel is in the process of being ported from Angular to React. We are going to be building a new bar chart panel in React rather making any changes to the existing graph panel. So closing this issue.

ref #27848
