### ISSUE TITLE
Load SheetJS only when neccessary

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#69463]
it looks like https://github.com/grafana/grafana/pull/60586 introduced an `xlsx` dependency from SheetJS, which is now always loaded unconditionally, and is the 4th largest file of the compiled Grafana codebase at 476KB.

we should load it only on demand.

![image](https://github.com/grafana/grafana/assets/43234/e20bbb2b-1c3a-4e07-9c82-d0f63b36293f)

**Comment by codeincarnate** [comment]
Oooh, this is a tricky one perhaps. The drag and drop appears in the data source picker and in a couple of other places which is why the library is being loaded in. Currently it's behind a feature flag and so we could tie loading the library to the feature being enabled. 

That's still not a great solution though as you could potentially never drag and drop a file and still have this be loaded. Seems like the sensible thing to do would be to load SheetJS upon a successful drag hover or something similar. Considering the asymmetric nature of most internet connections,  potential slowdowns should go mostly unnoticed for the majority of users. I need to ask around a bit and see if this is a viable solution.

**Comment by leeoniya** [comment]
some prior art:

https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Monaco/ReactMonacoEditorLazy.tsx

https://github.com/grafana/grafana/blob/6c7b17b59fa77d8413b90f6395b057e1f591009c/public/app/plugins/datasource/loki/components/monaco-query-field/MonacoQueryFieldLazy.tsx#L5

https://github.com/grafana/grafana/blob/6c7b17b59fa77d8413b90f6395b057e1f591009c/public/app/plugins/datasource/prometheus/components/monaco-query-field/MonacoQueryField.tsx#L290-L295

**Comment by ryantxu** [comment]
We should be sure to only load sheets when it will be used (after drop!) Not just when showing the option to drop

**Comment by leeoniya** [comment]
and only when the file is xlsx. for CSV we already have tge 19kb PapaParse in our dependencies, and loaded.
