### ISSUE TITLE
Datepicker is not displayed in "kiosk=tv" mode in version 9

### ISSUE THREAD

**Issue by ZengTianShengZ** [grafana/grafana#69526]
### 
# What went wrong?

**What happened**:

  - Datepicker is not displayed in the kiosk=tv mode (grafana v9):
![image](https://github.com/grafana/grafana/assets/15622519/a23d1bf4-efc5-4377-9e6d-71d92ebba9f2)

**What did you expect to happen**:

  - The datepicker button is displayed in grafana v9

### 
# How do we reproduce it?

**Step 1**:

- Open dashboard in kiosk=tv mode.

### 
# What Grafana version are you using?

v9.5.0

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by tonypowa** [comment]
hi @ZengTianShengZ 

thank you for creating this issue

this is the expected behavior when clicking on the kiosk mode button

see section 12) of [this document](https://grafana.com/docs/grafana/latest/dashboards/use-dashboards/#dashboard-feature-overview)

if you feel the menu or at least the datepicker should remain visible, you could open a [new discussion here](https://github.com/grafana/grafana/discussions)
