### ISSUE TITLE
[Feature request] send notification while state is `Alerting` without any change

### ISSUE THREAD

**Issue by Colstuwjx** [grafana/grafana#6954]
Hi team, I met the issue about the alert `notification`.

Currently, the `notification` is based on the state change event by design, so, sth changed to `Alerting`, there will be a notification fired, and if it recoveried, sth changed to `OK`, and another notification is sent.

But it maybe not meet my requirements, just like zabbix alert, it will send alert while state still be `Alerting`, or send `NoData` notification while the state is `NoData`.

Could grafana support this, just send notification while state equals xx without any change?

**Comment by utkarshcmu** [comment]
@Colstuwjx Instead of Grafana pushing an alert out even when the state does not change is not ideal. If your app wants to know the current status of alerts, here are two APIs you can query to get them:

http://localhost:3000/api/alerts
http://localhost:3000/api/alerts/states-for-dashboard?dashboardId=478

Pull every minute to find the alert states and you should be good. 👍

**Comment by Colstuwjx** [comment]
Thanks a lot for your nice reply, I will turn to try out this approach :)
