### ISSUE TITLE
Loosing API Annotations after restarting Grafana k8s deployment with database

### ISSUE THREAD

**Issue by alisvend** [grafana/grafana#69710]
### 
# What went wrong?

**What happened**:

  - Whenever I restart the grafana deployment, I loose the annotation.

**What did you expect to happen**:

  - I expected for the annotation to persist in the database.

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and create a service account along with a token.

**Step 2**:

- Use below curl request to create an annotation for a specific dashboard:

curl -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer <APIToken>" \
  -d '{
    "dashboardUID": "xxxx",
    "panelId": x,
    "text": "Annotation Description"
  }' \
  https://<grafana-URL>/api/annotations

**Step 3**:

In the defaults.ini add an RDS MySQL connection.

**Step 4**:

Connect to the database and check for the added annotation in the annotations table. (I am able to see it there)

**Step 5**:

Restart the Grafana deployment and the annotation will disappear from database.

### 
# What Grafana version are you using?

helm.sh/chart=grafana-6.56.5

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### Is this a Regression?

None

**Comment by tonypowa** [comment]
hi @alisvend 

thank you for creating this issue

could you safely share your `grafana.yaml` 

thank you

**Comment by marratj** [comment]
I have the same issue. I found it's a problem with provisioned dashboards. The `annotation` table in the database stores the internal `dashboard_id` as foreign key. However, the dashboard ID of a provisioned dashboard changes upon restart (even when `id:` is hardcoded in the dashboard JSON and with that, the annotation loses its relationship to the dashboard.

What's more, Grafana actually deletes the row in the annotation table when it does not find the corresponding dashboard with the specified ID.

I think the relationship between annotation and dashboard needs to be based on the dashboard UID instead of internal ID to solve this problem.

**Comment by juanicabanas** [comment]
seems to be related to @grafana/backend-platform

**Comment by papagian** [comment]
@marratj thank you for you report, it's very helpful
are there changes in the provisioned dashboard? otherwise I would expect the checksum check to prevent the dashboard from being updated:
https://github.com/grafana/grafana/blob/8ae92db53dda5b6236bcf50c7c7e39259a54c0ed/pkg/services/provisioning/dashboards/file_reader.go#L240

could you provide some additional information so that we can better troubleshoot it:
is it possible to share the provisioned dashboard JSON? also, what is the checksum stored it the database?
```
select check_sum from dashboard_provisioning where name = '<dashboard_name>';
```

if you cannot share it: is it possible to compute the MD5 checksum:
https://github.com/grafana/grafana/blob/8ae92db53dda5b6236bcf50c7c7e39259a54c0ed/pkg/services/provisioning/dashboards/file_reader.go#L408
and compare it with the one in the database?

**Comment by marratj** [comment]
@papagian here is the link to the dashboard JSON that is affected (it's just the included K8s APIserver dashboard from kube-prometheus-stack): https://gist.github.com/marratj/1288cd09ff363ec50f5ea5c0f23a3791

Below the query results from grafana.db before and after restarting the Grafana pod. Persistency is enabled and I have another testfile in `/var/lib/grafana` to make sure that I was not trapping into that rookie error... ;-)

`select * from dashboard_provisioning;` before restart:

`261|264|sidecarProvider|/tmp/dashboards/apiserver.json|1689666283|3df55517a39a8e3d5fa24b80dcacb1f9`

`select * from annotation;` before restart:

`2|1|0|2|264|4||||APIserver test annotation|||||1689663514242|0|[]|1689666474875|1689666474875|1689663514242`


`select * dashboard_provisioning;` after restart:

`282|285|sidecarProvider|/tmp/dashboards/apiserver.json|1689666640|3df55517a39a8e3d5fa24b80dcacb1f9`

`select * from annotation;` after restart: empty

So the `dashboard_id` of the provisioned dashboard (provisioned with the sidecarProvider from the Grafana Helm chart) in question has changed from `264` before the restart to `285` after the restart.

Now when I test the same with the dashboard saved under a new name regularly in the database (non-provisioned), it works just fine (dashboard JSON: https://gist.github.com/marratj/3662896620c5deef1c00adc1315c8667).

`select id,title from dashboard;` both before and after restart:

`314|Kubernetes / API server non-provisioned in DB`

`select * from annotation;` both before and after restart:

`3|1|0|2|314|4||||Test annotation non-provisioned|||||1689664499081|0|[]|1689667227874|1689667227874|1689664499081`

So the non-provisioned dashboard keeps both its `id` and the linked annotation just fine.

**Comment by 27am** [comment]
Hi, I am facing the same issue with provisioned dashboards and disappearing annotations. Any updates on this?:)

**Comment by abezkorovayny** [comment]
Hi, I am facing the same issue with provisioned dashboards and disappearing annotations. Any updates on this?:)

**Comment by abezkorovayny** [comment]
Hi, I am facing the same issue with provisioned dashboards and disappearing annotations. Any updates on this?
The version I am using is Grafana Enterprise v.10.1.1

**Comment by mildwonkey** [comment]
Hey all, thanks for reporting this, and I'm sorry for the bad behavior. It looks like we have a couple of issues here. @marratj is correct in that the annotation service should be refactored to use dashboardUID instead of ID when it's available.

I'll open a new issue to track that work, but in the meantime perhaps we can find a workaround for y'all. It seems plausible that the file checksums on your to-be-provisioned dashboard are changing when you restart Grafana.  

@alisvend - to build off on @papagian 's comment about checksums, can you tell us a bit more about how you are provisioning those dashboards in the k8s environment? Are you running a script, or using file-based provisioning?  Are the dashboards stored or mounted to the container in such a way that the file checksum would change between restarts?  

There are a lot of variables in docker volume mounting so I can't offer specific suggestions (yet), but if it's possible, try and modify your deployments in a way that the file checksums don't change between restarts and we can see if that fixes the issue.
