### ISSUE TITLE
[Feature request] Make it easier to scroll through future times

### ISSUE THREAD

**Issue by robinsonjj** [grafana/grafana#6976]
Please include this information:
- What Grafana version are you using? 4.0.1
- What datasource are you using? influxdb
- What OS are you running grafana on? windows

The t+LEFT_ARROW and t+RIGHT_ARROW shortcuts and the arrow shortcuts next to the zoom out button: 
![image](https://cloud.githubusercontent.com/assets/10656485/21223864/59e82298-c2c1-11e6-82a3-b9fb756b71cc.png)

work great for shifting the time period of graphs when the graph is in the past, however if I try to advance beyond the present day using these shortcuts, then it only advances time by a second which is a bit annoying if my data spans months and I'm trying to flick through future forecasts.

**Comment by gwuillou** [comment]
hello,

I say again what I say in the other closed issue, because I think it is a bug and not a feature request... If not I would like to know the reason why it is done like that.

![grafana_bug2](https://user-images.githubusercontent.com/20662503/50270828-24dfca00-0433-11e9-9f81-37b79b45cf77.gif)

I think it is at the line 123 in the file TimePicker.tsx but I am not sure:

```
       if (nextTo > Date.now() && to < Date.now()) {
            nextTo = Date.now();
            nextFrom = from.valueOf();
      }
```
Why this condition and why put to now a future time if the from date is in the past?

Thank you

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
