### ISSUE TITLE
Histogram: Should handle both classic and native histograms correctly for Prometheus datasource

### ISSUE THREAD

**Issue by krajorama** [grafana/grafana#69790]
### Discussed in https://github.com/grafana/grafana/discussions/69789

<div type='discussions-op-text'>

<sup>Originally posted by **krajorama** June  8, 2023</sup>
Histogram panel can display "classic" histograms from the Prometheus data source. The classic histograms were encoded as several time series representing cumulative buckets and a count and sum series.

Prometheus has introduced [native histograms](https://prometheus.io/docs/prometheus/latest/feature_flags/#native-histograms). This encodes sparse/exponential high resolution histograms into a single time series. This means the time series no longer contains floating point numbers, rather a complex data structure.

Result format on data source: https://prometheus.io/docs/prometheus/latest/querying/api/#native-histograms

For more information see presentations at PromCon for example: https://www.youtube.com/watch?v=RDdlDRkuVL8&t=2780s

![image (6)](https://github.com/grafana/grafana/assets/13435893/438a5632-e137-44cf-92e9-312246822d7c)

</div>

**Comment by gtk-grafana** [comment]
@kylebrandt We're going to need some help getting started on this before dataViz can get started on making the panels work with heatmap-cells.

First of all, we'll need some real data, while there is a simple go script we [used internally](https://raintank-corp.slack.com/archives/C8C98CETS/p1689342808361939), it is heavily contrived and doesn't produce "valid" output. While there is a datasource with some data [available in ops](https://nativehistogram.grafana-dev.net/explore?left=%7B%22datasource%22:%22grafanacloud-prom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22cortex_request_duration_seconds%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22grafanacloud-prom%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22%7D%5D,%22range%22:%7B%22from%22:%22now-15m%22,%22to%22:%22now%22%7D%7D&orgId=1), we'll need native histogram data in dev-prometheus for developers to work with locally.

Secondly, what queries are expected to work with native histograms, histogram_quantile won't work anymore? It would be nice to have some examples of queries and drawings of the expected output.

And then before dataviz can start they will need some requirements on how this format will be visualize: how do users select which histogram is visualized, since a heatmap-cell response could potentially contain many histograms?
@leeoniya and I discussed adding some UI element to let the user select which dimension is active, like the current table panel.

On the metrics side, I think we'll need to understand how this will impact writing queries, do we just remove the `by (le)` aggregation to our current histogram queries? Native histograms don't end in _bucket, so the query hints won't be correct either. I heard mention in the slack thread that there are new functions around native histograms that we'll need to add support for as well. What are they? If they aren't supported by the version of lezer-promql we're currently using we might have to fork that repo and add that functionality ourselves to the parser. 

Additional context on [internal slack](https://raintank-corp.slack.com/archives/C04AT2ANL90/p1683037266468959)

It would be awesome to get the existing panels working with native histograms, but I want to point out that the feature is still experimental on the Prometheus side, they could release breaking changes to the API at any time, so we probably want to mark this feature as experimental, and release it under a feature flag.

Also there might be a bug in which the current backend implementation, the heatmap-cell is returning an the __name__ label, which I don't think is valid @ryantxu

@kylebrandt @leeoniya we should touch base on this ASAP before Leon goes on leave.

**Comment by krajorama** [comment]
Hi,

For impact on PromQL, it's embedded in the existing documentation: The PromQL capabilities for native histograms are part of the normal documentation. Search for "native histogram" on https://prometheus.io/docs/prometheus/latest/querying/basics/ , https://prometheus.io/docs/prometheus/latest/querying/operators/ , and https://prometheus.io/docs/prometheus/latest/querying/functions/ .

There's plans to make it more targeted.

I've made a very short summary for myself in an internal presentation, let me copy the gist here:

### Series of my_metric histogram metric

- Classic:
   - my_metric_count
        Number of observations
   - my_metric_sum
        Sum of observed values
   - my_metric_bucket{le=”float”}
        As many as the predefined of buckets. le=less or equal, the upper inclusive bound of bucket. Bucket count is cumulative, le=”0.2” contains le=”0.1” count.
- Native
   - my_metric
      Encodes count, sum and buckets. Bucket count is exact, not cumulative. Boundaries can be inclusive/exclusive.

### Queries

- Get overall count of observations
   - Classic: my_metric_count
   - Native: histogram_count(my_metric)
- Get overall sum of observations
   - Classic: my_metric_sum
   - Native: histogram_sum(my_metric)
- Quantile - get count of 95 percentile
   - Classic: histogram_quantile(0.95, sum by(le) (rate(my_metric_bucket[$__rate_interval])))
   - Native:  histogram_quantile(0.95, sum(rate(my_metric[$__rate_interval])))

**Comment by zhehao-grafana** [comment]
@gtk-grafana Hello Galen! Just want to understand the priority of this item from your end as we are doing Q4 planning on the metric side. From my understanding after reading through the thread, is sending more real data on native instagram the only request from your end?
