### ISSUE TITLE
Timepicker: Datepicker for absolute time range adding extra day

### ISSUE THREAD

**Issue by rmiesen8934567** [grafana/grafana#69939]
### 
# What went wrong?

The color overlay in the datepicker is one day longer than what is selected by clicking on the dates. The "To" date textbox correctly reflects the date that was clicked on. This happens for any interval length (in days).
When klicking a single day repeatedly the overlay switches between one and two days.
I can reproduce this in Edge and Firefox.

![grafik](https://github.com/grafana/grafana/assets/99186298/87c9a14e-092e-470b-82e7-da72115a9e47)

### 
# What Grafana version are you using?

9.5.2

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by joshhunt** [comment]
Hmm, I'm not able to reproduce this on [play.grafana.org](https://play.grafana.org) 
![image](https://github.com/grafana/grafana/assets/46142/53d07efe-cf20-4c0c-9402-22a6579de75e)

My local browser timezone is UK/UTC+1, which might be obscuring an issue. What timezone is your computer configured to?

**Comment by rmiesen8934567** [comment]
Thank you very much for looking into it!

- Computer / Browser Timezone: GMT+2 (Europe/Berlin)
- grafana.ini: default_timezone = browser
- Administration -> default preferences: timezone = Coordinated Universal Time
- Personal Timezone (Profile): timezone = Default (when I open the dropdown it shows: Default UTC, GMT)

I tried setting the default_timezone in grafana.ini to UTC. No change.

**Comment by JoaoSilvaGrafana** [comment]
I was able to reproduce this (maybe easier since I am currently in Asia/Tokyo timezone). I noticed that the time plays a part here:

Setting the "to" to after 15:00:00 (UTC 00:00:00 when in Japan), it breaks:
<img width="508" alt="Screenshot 2023-06-18 at 23 38 30" src="https://github.com/grafana/grafana/assets/100691367/119c49d7-0280-483e-a303-1d534f56c813">

Setting the "to" to before 15:00:00 (UTC 00:00:00 when in Japan), it works fine:
<img width="519" alt="Screenshot 2023-06-18 at 23 38 44" src="https://github.com/grafana/grafana/assets/100691367/48fc123f-c2da-48d9-9e6d-940538cb75ac">

So the timezone is playing a part here. Will add this to our board 👍

**Comment by ashharrison90** [comment]
can reproduce only when browser time is different from grafana timezone preference. so for example, either:
- set grafana timezone preference to tokyo whilst browser time is UK
- set grafana timezone preference to london and emulate browser time to be tokyo
