### ISSUE TITLE
[Bug] day "d" not allowed in alert query condition eg. query(A,1d,now)

### ISSUE THREAD

**Issue by cr42** [grafana/grafana#7007]
Please include this information:
- What Grafana version are you using?
4.02

- What datasource are you using?
OpenTSDB

- What OS are you running grafana on?
Windows

- What did you do?
Used a "day" in my alert query period. When I tried to save the dashboard the error "Invalid alert data cannot save dashboard" appears.

I used "query (A, 1d, now)" for the query. Also tried month (M) and year (y) but they also cause same problem. Only hour (h), minute (m) and second (s) work correctly.

**Comment by bergquist** [comment]
golang time.Parseduration does not support parsing `1d` but you could use `24h` instead. 
ref https://github.com/golang/go/issues/17767

If more people run into this we should write our own dateparser.

**Comment by Krinkle** [comment]
Please note that notation of "1d" and "30d" already works in Grafana for the time ranges of dashboards and graph panels. It is only a problem (according to this report) in alert queries.

What is currently making this work for dashboards and panels? Could alerting use the same logic?

**Comment by marefr** [comment]
@Krinkle dashboards and panels are executing in browsers where's alerting are executing in the server side so it's not as easy to reuse the same parser.

Closing this since specific problem with using `d` have been fixed in #16182. Using months and years as intervals for alerts may be interesting long term, but nothing we're aiming at supporting currently. If you would like month/year intervals for alert rule I would suggest open a new feature request.
