### ISSUE TITLE
Dashboard redirects

### ISSUE THREAD

**Issue by filippog** [grafana/grafana#7043]
I was looking for a way to redirect users from an obsoleted dashboard to another version.

In this case the dashboard didn't change name but it was moved to a revision-controlled file instead and thus changed its URL. The solution for now has been to add a banner to the old version with a link to the new dashboard, though it would be nicer for e.g. existing links to issue HTTP redirects instead. Is it possible to have Grafana do some kind of redirect?
Sort of related to this would also address #1223 in "ways to keep things clean" where obsoleted dashboard could redirect to e.g. the home dashboard.

thanks!

**Comment by torkelo** [comment]
The best way to solve your case it to add a redirect to an nginx proxy you have infront of grafana. Since you moved from a database dashboard to a file based one, I guess the db dashboard was removed. 

The best solution is probably to leave the old dashboard but add html panel that links to the new dashboard. 

If you rename a dashboard grafana could potentially create a redirect for the old name but that would not solve your case

**Comment by filippog** [comment]
> The best way to solve your case it to add a redirect to an nginx proxy you have infront of grafana. Since you moved from a database dashboard to a file based one, I guess the db dashboard was removed.

Thanks @torkelo ! Yeah that's likely what we'll end up doing. So far what I had in mind is to issue HTTP 301s for `/dashboard/db/<OLD>` into `/dashboard/file/<NEW>` and `/api/dashboards/db/<OLD>` into `/api/dashboards/file/<NEW>`, that AFAICT should cover it?

Would you be interested in the configs to be added to the Grafana documentation for this use case?

> The best solution is probably to leave the old dashboard but add html panel that links to the new dashboard.
> 
> If you rename a dashboard grafana could potentially create a redirect for the old name but that would not solve your case

I believe it would, unless it isn't possible to create `db` -> `file` dashboards redirects?
