### ISSUE TITLE
Alerting: Template expression value is zero on resolved message

### ISSUE THREAD

**Issue by michael-sawczuk** [grafana/grafana#70462]
### 
# What went wrong?

**What happened**:
Building a Slack template which uses {{ .Values.B }} produces the correct value when the alert rule going into firing however on resolved a value of `0` is always returned.

**What did you expect to happen**:
Show the currently value of B.

### 
# How do we reproduce it?

**Step 1**:
Create a template as follows:
`{{- define "slack.panel-link-with-values-b-only.message" -}}
{{ range .Alerts }}
{{ if .PanelURL -}}<{{ .PanelURL }}|Dashboard panel link>
{{- end }}
{{ if .Labels -}}
{{ range .Labels.SortedPairs -}}*{{ .Name }}*: {{ .Value }}
{{ end -}}
{{ end -}}
Value: {{- .Values.B }}
{{ end }}
{{ end }}`

**Step 2**:
Ensure a contact point has been setup to use the template

**Step 3**:
Create an alert rule, A is the query, B is the reduce expression, C is the threshold

**Step 4**:
Set threshold to a value that would cause the rule to trigger an alert, observe the alert contains the current value of B

**Step 5**:
Set the threshold value to clear the alert, observe the alert contains a value of zero which isn't the actual value.

![alerting](https://github.com/grafana/grafana/assets/16261916/eabc2391-e63c-4ad9-abde-80f5c543fc08)
![resolved](https://github.com/grafana/grafana/assets/16261916/db818a9f-0d1e-45c5-82fa-3b070d99f266)

### 
# What Grafana version are you using?

v9.4.9

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

MacOS Ventura

### Is this a Regression?

None

**Comment by alexweav** [comment]
This is expected when editing a rule to change the condition.

When a rule is edited, the alerting engine force-resolves any alerts on the old rule **all the time**. This is because it doesn't know what state the rule will be in until a proper evaluation can happen. The labels might have changed, so it doesn't want to leave a "dangling" firing alert in Alertmanager.

That's what you are seeing here, it's force-resolving the "old" version of the rule so it isn't dangling in alertmanager - but no actual query was executed, so the value is zero.

This is an edge case where editing the rule's condition by hand doesn't necessarily simulate a rule firing or resolving from a real query.

Under typical operation, (i.e. where a real resolution happens from a query, not from an edit to the rule), the value does appear, using the customer's exact same template: 
![2023-06-23-123127_491x210_scrot](https://github.com/grafana/grafana/assets/8410871/83d6d0fb-5b2e-456b-9a2f-51cc24158384)

**Comment by ahutson-bbc** [comment]
This happens for _real_ resolve messages too, not just ones that are force-generated by editing the threshold. Can you reopen please?
