### ISSUE TITLE
Dashboard variable search should show exact match above alphabetical/numerical matches

### ISSUE THREAD

**Issue by lihmc** [grafana/grafana#70629]
**Steps to reproduce**:
Create dashboard with many dashboard variables. One simple set would be (A, AA, AB, AC, BC, C, CD)
Go to and dashboard and type C into variable search.

**Actual Result**:
The results show up in alphabetical order: AC, BC, C, CD. Pressing enter selects AC.

**Expected Result**
C should be shown first, then AC, BC, CD. Pressing enter should select C. This is not a big problem for smaller sample sets, but in a sample set with many entries, it becomes very difficult to find C buried within the huge list of partial matches.

**Relevant WCAG Criteria:**
Not sure which one would fit, but this would help grafana keyboard navigation.

**Environment**:
- Grafana version: 9 (but probably all)
- Data source type & version: Any
- User OS & Browser: Any

**Comment by usmangt** [comment]
Hi @lihmc,

Thanks for opening this issue.

Based on your steps of reproduction, I was also able to reproduce it on my test machine using Grafana version 10

I can understand your point that it can be a bit hard to select and then find the right variable if there are many variables configured for a complex enviornemt.

I will forward this issue to our Engineers so that they can have a look and analyze it.

**Comment by ivanortegaalba** [comment]
👋 Hi @lihmc! Thanks for the feedback!

I asked for a second opinion from @Ijin08, but IMO this is the expected behavior when the filter work as `CONTAIN`. If we change the content of the select based on the STARTS_WITH it will be confusing for users, since they will find an unsorted select.

So, IMO, the behavior is correct.

**Comment by lihmc** [comment]
Hi, thanks for the reply @ivanortegaalba. I agree that the current behavior CONTAIN is better in a lot of cases and I'm not suggesting to change it to STARTS_WITH. 

Instead I'm talking about a case where the user inputs a value that is an exact match. Here I'm suggesting we should bubble that exact match to the top of the list so the user doesn't have to hunt for it.

**Comment by leeoniya** [comment]
assuming this is a frontend filter? (haven't checked the code).

i think we can use our fuzzy search for this, which sorts by relevance (and tolerates small typos).

example: https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy&search=cade

**Comment by Ijin08** [comment]
Hey!
In the case you describe it would be useful. But I think we need to consider the impact on users overall. As @ivanortegaalba mentioned this is the expected behavior for a filter. And without more knowledge of the general users experience of it I can't recommend changing it.

**Comment by ivanortegaalba** [comment]
@leeoniya can you point me to a place where we use this fuzzy alg?

**Comment by ivanortegaalba** [comment]
I like this approach. I think it improves the search for big chunks of complex names like K8s nodes.

@lihmc PRs are welcome in case you want to integrate uFuzzy with the search logic of the dropdown 😄 

I'll be happy to help and review
