### ISSUE TITLE
[Bug] After deleting a panel, an empty space is here

### ISSUE THREAD

**Issue by scraly** [grafana/grafana#7068]
Please include this information:
- What Grafana version are you using?
4.0.2

- What datasource are you using?
Graphite

- What OS are you running grafana on?
CentOS 7

- What did you do?
Remove a panel in a row

- What was the expected result?
Panel removed, not empty space between rows

- What happened instead?
An empty space between row. Can't remove it?!

Before Grafana 4 when I removed a panel, I can resize my others panel and didn't have this empty space.

![grafana_empty_space](https://cloud.githubusercontent.com/assets/2543381/21479250/f4ae89d6-cb52-11e6-823e-ed69d8514047.png)

Thanks.

**Comment by torkelo** [comment]
I am unable to replicate this :(

**Comment by torkelo** [comment]
can you describe steps to reproduce?  Can you try to replicate it here? http://play.grafana.org/dashboard/db/big-dashboard?from=now-1h&to=now

**Comment by scraly** [comment]
Steps:
1. Create a new row
2. Add one panel (6 col for ewample)
3. Add another panel (6 col for example)
4. Remove one panel
You have an empty space.

In our dashboards we have huge empty space :-(.

**Comment by rovincent** [comment]
Im in the same boat:
OS: Unbuntu 16.04
Grafana: 4.0.0 (just realized theres is an update but have not upgraded as I'm on vacation and want to wait until im back at the office : )

To reproduce in my case:
 Add two or more panels to a row and/or drag a panel to another row already containing panels then delete one panel.

I end up with the deleted panel "space" listed as empty but have no way to delete. The only way to fix the issue i have found it to delete and recreate the entire row, not really a fix of a WORK around.

**Comment by torkelo** [comment]
@scraly 

In your scenario the empty space indication is correct, since there is unused space in the row (6 col panel, + 6 col panel, remove one panel, 6 span empty). You can hide the empty space indicators by CTRL/MOD+H  (hide controls in dashboard settings).

The screenshot you added shows something different hower, it shows empty space on a already full row. Do you have steps to reproduce that?

**Comment by torkelo** [comment]
@rovincent 
The scenario you describe also sounds like correct behavior, if you remove a panel it will leave an empty space on the row. Remove the empty space by increasing the size of the other panels on the row. 

What could be a bug is empty space on a row that already contains panels that have a combined span of more than 12. 

Please upgrade to latest stable release. Since your using 4.0.0, there has been a number of fixes in 4.0.1 and 4.0.2, not sure if there was one that concerned empty space indicator

**Comment by scraly** [comment]
Just reproduced again the issue in one of our dashboard.

Steps to reproduce the issue:
1. Add a new row in one of existing dashboard
2. Duplicate an existing Graph panel
3. Drag & drop it in the new row
4. We have the empty space with a width of the duplicated graph panel

![grafana_issue_2](https://cloud.githubusercontent.com/assets/2543381/21525139/79848c18-cd1b-11e6-9535-009e014b1e88.png)
_Edit mode_

![grafana_issue_1](https://cloud.githubusercontent.com/assets/2543381/21525140/7985e1c6-cd1b-11e6-997f-89d26f45980c.png)
_View mode_

**Comment by scraly** [comment]
I have reproduced the issue in http://play.grafana.org/dashboard/db/big-dashboard?from=now-1h&to=now

![play_grafana_dashboard_issue_reproduce](https://cloud.githubusercontent.com/assets/2543381/21525327/ebfdfa30-cd1c-11e6-8b44-b291f6ea60e2.png)

**Comment by torkelo** [comment]
>Add a new row in one of existing dashboard
Duplicate an existing Graph panel
Drag & drop it in the new row
Change the width of the existing panel (because it has been reduced)
Results: We have the empty space with a width of the duplicated graph panel

Trying to follow these steps bug fail to replicate the empty space.  When I change the width the empty space is also reduced (and eventually removed when there is no more space on in the row)

**Comment by rovincent** [comment]
Please see attached screen shits as follows: 

1. Create new dashboard, 
2. Add panel (graph) 
3. Add second panel (graph) 
4. Add third panel (graph) (screen shot 1a.png) 
5. Delete last panel added (screen shot 1b.png) - Empty space shows for first time 
6. Re-size Panel 1 span to 6 (screen shot 1c.png) - Empty space jumps to next line 
7. Re-size Panel 2 span to 6 (screen shot 1d.png) 

I have not found a way to delete the empty space other then delete the entire row. 

Hope this helps. 

I can provide access to the interface if needed but would prefer to only transmit user creds via email directly to a user (not via the forum). 

Robin 

----- Original Message -----

**Comment by torkelo** [comment]
@rovincent follow your exact steps on play.grafana.org leaves me with no empty space, when I resize the panels 1 and 2 the empty space width gets reduced and eventually disapears

**Comment by eskilblomfeldt** [comment]
I have this same problem. To explain what I am doing: I am creating a dashboard with something like 100 graphs that are nearly identical. I want them arranged in rows of three panels each. To make this convenient, I will duplicate a graph. This then adds it to the same row as the source. When I move the graph out of that row, it will leave an empty space. Manually resizing the three remaining graphs to make the empty space disappear and also have them line up with the other rows is really fudgy and inconvenient. Doing this for 100s of graphs is not practical. It would be nice if removing a panel from the row was as easy as adding it, so that I can easily get rid of the empty space and have the remaining three panels automatically adjust to fill one third of the row width. 

Is there any way of doing this that I am missing, or should I perhaps be constructing my dashboard in a different way?

**Comment by master-elodin** [comment]
I had this same issue, but saving the dashboard and reloading the page made the extra space go away.

**Comment by k1ng87** [comment]
same issue here...sounds like a bug to me

**Comment by candlerb** [comment]
(See also #6804)

I am also getting this problem with grafana 4.4.3, but I think I got to the bottom of it.

The sequence was:

* Create a graph panel, default width 12
* Select "Duplicate". This gives two 6-unit wide panels.
* Create a new row
* Drag the RH panel to the new row
* On the LH panel, **go to Edit/General, set the span to 12 from the drop-down**
* Now the row consists of a panel which is 12 units wide, followed by an empty space of width 6 that can't be deleted

WORKAROUND: Put the panel back to width 6.  Then **drag** the panel to width 12, by pulling on the lower right-hand corner.

**Comment by erdna1982** [comment]
same here. I guess it's a bug

**Comment by dritchie-mtc** [comment]
I can easily duplicate it by doing the following:
1. Click "Add Row"
2. Click the "X" to cancel the adding of a graph
You now have 1 blank row that you can't remove.

**Comment by master-elodin** [comment]
I found that the extra space disappears if I save the dashboard and reload
the page. It's still annoying to not be able to fix without that, but I've
at least got a workaround.

**Comment by vervoorn** [comment]
Interesting ... I have the same but if I resize the browser window the space disappears and reappears as if the rendering does not always calculate the space correctly.
![image](https://user-images.githubusercontent.com/29597617/45861925-add16180-bd6f-11e8-9859-a53ef6935e4a.png)
Same screen, browser resized 5 pixels larger:
![image](https://user-images.githubusercontent.com/29597617/45861964-e7a26800-bd6f-11e8-9dee-42692154faa5.png)

**Comment by sirganya** [comment]
Hover over the very right hand side of the empty space and a menu will appear. You can the select 'remove'
