### ISSUE TITLE
CommandPalette: Search dashboards in top search input box in Chinese

### ISSUE THREAD

**Issue by dmsolr** [grafana/grafana#70883]
### 
# What went wrong?

**What happened**:

Input in Chinese will append whitespace around Chinses character automical. That is causing search failed.

![IMG20230629165054](https://github.com/grafana/grafana/assets/29735230/6fba4e71-6419-4f55-ae76-c932f6e4dced)

but input Chinese characters for searching is ok here:

![IMG20230629170141](https://github.com/grafana/grafana/assets/29735230/6534c4d2-3848-4d28-8b3c-533c715797f8)

**What did you expect to happen**:

  - 

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and do X 

**Step 2**:

- Now click button Y

**Step 3**:

- Wait for the browser to crash. Error message says: "Error..."

### 
# What Grafana version are you using?

Grafana v10.0.1 (5a30620b85)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's Browser?

Google Chrome 114.0.5735.134 X64

### Is this a Regression?

None

**Comment by usmangt** [comment]
Hi @dmsolr,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by tskarhed** [comment]
I don't have a Chinese keyboard, but I tried with copying "对", and the search seems to work fine in the command palette.
[Screencast from 30-06-23 13:09:00.webm](https://github.com/grafana/grafana/assets/1438972/5f68aee8-de31-4a2d-a513-4aab3e6a9cd2)

I might have to change the language for my keyboard

**Comment by dmsolr** [comment]
> I don't have a Chinese keyboard, but I tried with copying "对", and the search seems to work fine in the command palette. [Screencast from 30-06-23 13:09:00.webm](https://github.com/grafana/grafana/assets/1438972/5f68aee8-de31-4a2d-a513-4aab3e6a9cd2)
> 
> I might have to change the language for my keyboard

Thanks @tskarhed 
Actually yes. Copying is work well. And I found there is issue in different input method.
For instance,  type d-u-i and the it is replaced by ""对" after typing whitespace. During that, will triggle real-time search several times.

**Comment by dmsolr** [comment]
show detailed in screenshot, but it demostrated in other Chinese input method.
https://github.com/grafana/grafana/assets/29735230/cf69a523-8bc4-485e-b361-8588910428ca

**Comment by joshhunt** [comment]
Thanks @dmsolr - we were able to reproduce this using Pinyin input. Your example `dui` for 对 worked great.

---

Investigated this today in mob and couldn't find the root cause, but learned:

 - This is just an issue with the CommandPalette input (`KBarSearch`) - other text inputs in Grafana work fine.
 - We vendored the KBarSearch component and changed the input value to local state (instead of from `useKbar`) and the problem went away. The issue appears to be something to do with the value being stored in kbar state and read back.
 - The issue doesn't occur on the kbar example website https://kbar.vercel.app/ 
 - We appear to be using the latest version of kbar, so nothing to upgrade to.
 - Appears similar to https://github.com/timc1/kbar/issues/237, which was closed due to inactivity.

**Comment by BruceMa29** [comment]
@joshhunt Hi, have any progress on fixing this issue? we have encountered the same issue.

**Comment by life-plant** [comment]
I found the same problem, and then I found that using ReactDOM.createRoot(document.getElementById("root")!).render(xxx) to create a react project in a react 18 project will cause KBarSearch fail to input Chinese, but there is no problem with using ReactDOM.render(xxx). react 17  is also no problem, because it is also created project with ReactDOM.render(xxx). The reason why the kbar official website shows no problem is because it  uses react 17

**Comment by quanzhibingrv** [comment]
Hi, all.
Any update so far?  We plan to update Grafana from 9.3.13 to 10.1.2, but found this issue.
