### ISSUE TITLE
Elasticsearch: Add backend support for multiple indexes

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#71092]
Initially reported [here](https://github.com/grafana/support-escalations/issues/6606). When Elastic is in frontend mode it supports a comma-separated list of indexes, but when it's called as a backend data source it does not.

E.g. the data source settings test succeeds.

![Image](https://github.com/grafana/grafana/assets/1069378/d2358d90-719a-413f-9a2a-816458402d1e)

But then you get no logs in Explore.

![Image](https://github.com/grafana/grafana/assets/1069378/9275d6c2-cda3-4905-bd72-dcd7345f2214)

As a side effect, this is affecting alerting.

**Comment by gabor** [comment]
hey all, so... i clicked [revert] on https://github.com/grafana/grafana/pull/67276 , which created https://github.com/grafana/grafana/pull/71284, because technically it introduces a bug. i recommend we merge that revert, and then we can discuss if we want to do something more or better. this way we can separate the:
- bugfix  (this needs backporting)
- maybe an improvement

WDYT?

if you agree you can approve the revert PR 😁

**Comment by matyax** [comment]
I think this is done. Reopen otherwise.
