### ISSUE TITLE
[Feature request] Table plugin value mappings

### ISSUE THREAD

**Issue by tfylling** [grafana/grafana#7119]
Could the Table plugin receive the same options to map numbers or ranges to text values as the singlestat plugin has. My current use case scenario is to show the association condition of ntp peers as outlyer, candidate, sys.peer etc, rather than the codes I use to store the time series.

**Comment by utkarshcmu** [comment]
Table panel can get value/range mappings using similar code as in PR https://github.com/grafana/grafana/pull/4644 :)

**Comment by infernix** [comment]
I have a PR out for this over at https://github.com/lucasrodcosta/grafana/pull/1 which builds onto the work of https://github.com/grafana/grafana/pull/9455 since it's related. 

The value-to-text functionality is exactly the same as on singlestat panels. Talked briefly to @marefr at FOSDEM and this won't get merged until after Grafana 5 (but feedback welcome!). Marcus, if 9455 can't be merged we can rebase it against master and submit a new PR here, just let me know!

**Comment by infernix** [comment]
@marefr separeted it and rebase against master. please comment :)

**Comment by marefr** [comment]
Fixed in #11094 so closing this

**Comment by JamesGalt** [comment]
@marefr Do you think as test to number is possible? it would allow to use thresholds.
Thank you

**Comment by marefr** [comment]
@JamesGalt we closed a PR for text to value mappings, see [comment](https://github.com/grafana/grafana/pull/9455#issuecomment-379783985), in favor of #11418
