### ISSUE TITLE
Tooltip: The positioning and transitions can make the tooltip look erratic

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#71393]
When using the `VizTooltipContainer` the automatic positioning probably tries to do a bit too much.

For example the position is computed based on content size, which is neat but if you have multiple items with different content sizes next to each other the tooltip can jump from left to right multiple times which looks a bit weird:

https://github.com/grafana/grafana/assets/1014802/e8585a8a-9d99-429d-900f-7317f96235f5

Maybe a simpler positioning based on screen quadrants could make more sense to make the position of the tooltip a bit more stable.

Also the transition css has this weird artefact when sometimes it seems like the tooltip slides from somewhere, which looks neat at first but I find it a bit too much movement:

https://github.com/grafana/grafana/assets/1014802/9464cc07-10dc-4d37-833d-582feacf036e

**Comment by leeoniya** [comment]
a lot of related TooltipContainer work is happening in https://github.com/grafana/grafana/pull/70872.

the current strategy still takes viewport bounds into account as well as content size, which i think makes sense. i don;t think we need transitions any more, either.

the problem here looks exacerbated by rendering tooltips for the the merged (gray) micro regions. i'm not sure how useful this is in practice and a quick fix might be to simply not render tooltips for them.

**Comment by aocenas** [comment]
> a lot of related TooltipContainer work is happening in https://github.com/grafana/grafana/pull/70872.

Let me know if this is relevant then or can be closed.

> the problem here looks exacerbated by rendering tooltips for the the merged (gray) micro regions.

Definitely, but I think this illustrates a bit extreme version of this and this could still happen to less extent in more "normal" circumstances.

**Comment by leeoniya** [comment]
> Definitely, but I think this illustrates a bit extreme version of this and this could still happen to less extent in more "normal" circumstances.

i'm willing to live with imperfect but simple rather than perfect bu :exploding_head:
