### ISSUE TITLE
[Feature request] Slack alert graph using files.upload

### ISSUE THREAD

**Issue by gerrickw** [grafana/grafana#7175]
- What Grafana version are you using?
v4.1.0-beta1
- What datasource are you using?
influxdb, graphite, opentsdb
- What OS are you running grafana on?
ubuntu 16.04 and 14.04

Would it be possible to support file uploading to slack instead of s3 or webdav?  Looking at hubot it appears they added support near the end of June based on https://github.com/slackapi/hubot-slack/issues/62. Previously files.upload api was not allowed from bots, but looks like policy allows bots to upload. https://api.slack.com/methods/files.upload

Within our company policy we can not upload to a public repo, although a slack image push would be allowed.

Finding the alerting setup interesting, thanks for the great work.

**Comment by bergquist** [comment]
This makes sense. 

We implemented the slack notifier before the summer and I guess we missed the fact that they added support for file upload. 

This should be implemented the same way as emails. If public_image_store is configure it should be used, otherwise it should fall back to slack file upload. 

Should also make it configurable in notifications settings since some people don't want to share their graphs to slack.

**Comment by DanCech** [comment]
+1 this would be very helpful for hosted grafana

**Comment by neokyle1** [comment]
+1 agreed

**Comment by meganchinburg** [comment]
+1
