### ISSUE TITLE
Dashboards: Auto refresh dashboard causes JSON cell value inspect popout to close

### ISSUE THREAD

**Issue by pathakhimanshucs** [grafana/grafana#71863]
### What happened?

We have a dashboard with a table panel. If the dashboard is set to auto-reload, suppose every 10s. Then the `cell value inspect` popout gets closed. 

### What did you expect to happen?

I would expect the popout to stay open regardless of the underlying data being refreshed

### Did this work before?

Didn't try with older versions

### How do we reproduce it?

1. Create a table panel with a column containing JSON data
2. Set the field override to `Cell Type: JSON View` and `Cell Value Inspect: True`
3. Set refresh to 5s or some other interval
4. Open the Inspect Value popout for a cell
5. The popout should close automatically when the data is refreshed

### Is the bug inside a dashboard panel?

Yes inside the `Table` panel

### Environment (with versions)?

Grafana: 10.0.2
OS: Windows
Browser: Firefox

### Grafana platform?

Kubernetes

### Datasource(s)?

Postgres

**Comment by mellieA** [comment]
@pathakhimanshucs thanks for reporting this. I'm seeing the same thing - I'll get this to the squad that works on the table panel to confirm if this is expected.

**Comment by codeincarnate** [comment]
I'd say that this probably is the expected behavior as it exists though this could have just been something missed. I'm guessing dashboard refresh is designed to close modals though in this case it likely doesn't make sense.

That being said, I think in this case it makes sense to keep the modal open, though we'll probably need to have some kind of data refresh indicator or something similar. I don't think this is super high priority (though if this is being experienced widely please comment here) but we can add it to the roadmap 😄

**Comment by jvallade** [comment]
Hi, 
I just encountered this issue : I'm building a dashboard to display docker logs, that can be quite long and the inspect pop-up comes in quite handy. But the fact the auto-refresh closes the pop-up is quite annoying 😄. Would it be possible to re-open this issue and add it in the roadmap ? 
Thanks !

**Comment by Nathan-Harlan** [comment]
Please consider opening this up again. It's a minor annoyance to a fantastic table-view dashboard.

Thanks!
