### ISSUE TITLE
Wrong timezone description for Europe/Simferopol

### ISSUE THREAD

**Issue by fri-K** [grafana/grafana#72031]
### What happened?

Home/Administration/Default preferences/Preferences -> Timezone
When choosing Europe/Simferopol it gives description: "Europe/Simferopol Russian Federation, MSK", which is wrong

### What did you expect to happen?

It should be "Europe/Simferopol Ukraine, EEST" as Crimea is Ukraine territory by international law

### Did this work before?

I don't know, first time seeing it

### How do we reproduce it?

1. Go to Home/Administration/Default preferences
2. Change timezone
3. Choose Simferopol

### Environment (with versions)?

Grafana: v10.0.2 (b2bbe10fbc)
OS: Docker default image
Browser: Mozilla Firefox

### Grafana platform?

Docker

**Comment by JoaoSilvaGrafana** [comment]
Hi @fri-K 👋  Thanks for bringing this to our attention! The way we display this description label for each of these timezones is that we get all the countries that are associated with that timezone from `moment` [library](https://momentjs.com/timezone/) and if there are multiple just show the first alphabetically. 

We will make the change to ignore what we get from `moment` in this case and just display the description you said 🙌

**Comment by JoaoSilvaGrafana** [comment]
Hi @fri-K , this was merged last week now and should be changed from v10.1!

One thing we wanted to raise as well is that someone raised a similar [issue](https://github.com/moment/moment-timezone/issues/954) on `moment` last year that points to [IANA](https://www.iana.org/time-zones) having both countries listed for this timezone. We wanted to mention this in case you wanted to try to get IANA to change it so this would get fixed in other places outside Grafana 😄
