### ISSUE TITLE
HTTP API: search user by email using service account

### ISSUE THREAD

**Issue by FUSAKLA** [grafana/grafana#72103]
### What happened?

If I try to follow the documentation in https://grafana.com/docs/grafana/latest/developers/http_api/user/#get-single-user-by-usernamelogin-or-email and search used by **email** I get error 

```json
{
"accessErrorId":"ACE1890040084",
"message":"You'll need additional permissions to perform this action. Permissions needed: users:read",
"title":"Access denied"
}
```
According to the documentation, only searching by **username** requires `Grafana Admin` role (or is the example and documentation misleading)

I do not see a way to have service account with `Grafana Admin` role unfortunately.

Sound related to https://community.grafana.com/t/permission-issue-when-using-service-account-and-http-api/90920

### What did you expect to happen?

To have a way to find a user using API

### Did this work before?

IDK

### How do we reproduce it?

1. Create admin SA
2. Call the API `/api/users/lookup?loginOrEmail=user@mygraf.com` as showed in the example

### Environment (with versions)?

Grafana: 10.0.2
OS: Linux
Browser: Firefox

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
thank you for creating this issue @FUSAKLA 

in order to call that endpoint, you need to authenticate with basic Auth (username + password), not via bearer token. I have used my admin creds for that.

![image](https://github.com/grafana/grafana/assets/45235678/a865fee3-f053-4aaf-9fe8-64a1ea538b5b)

PS. this is something I already knew, and that I have not found in the[ docs](https://grafana.com/docs/grafana/latest/developers/http_api/user/#user-api), so I'd agree that the docs could be improved.  I will work with the docs team regarding this.

**Comment by tonypowa** [comment]
oh I missed that sorry.I see it now. 
I feel that the example must have been a mistake. I will get it reviewed and I will get back to you

**Comment by FUSAKLA** [comment]
Thanks for fixing that! 
TBH I hoped that it's not a bug in the docs and the bearer token would work, but at least it's clear now :)
