### ISSUE TITLE
Dashboards: Duration table column is sorted alphabetically instead of the duration

### ISSUE THREAD

**Issue by letmaik** [grafana/grafana#72133]
### What happened?

The column data is in seconds. When choosing Unit Time -> "duration (s)", then the column gets sorted alphabetically by the original text string in seconds:

![image](https://github.com/grafana/grafana/assets/530988/4ac5f58c-0e4e-458d-b59b-762bfa81ea2d)

For reference, these are the raw numbers:
![image](https://github.com/grafana/grafana/assets/530988/ca326727-dc0d-4084-aeb5-ab51c54e88ca)

### What did you expect to happen?

Sorting of time, date, duration should just work when the unit is set correctly. 

### Did this work before?

Probably not but I don't know.

### How do we reproduce it?

1. Create a dataset with a column of seconds
2. Create a table and set Unit to Time -> "duration (s)"
3. Try to sort the column and observe what happens

### Environment (with versions)?

Grafana: 9.4.12
Browser: Edge

### Grafana platform?

Other

**Comment by tonypowa** [comment]
thank you for creating this issue @letmaik 

can you reproduce this on [Grafanaplay](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1) ?

also, in order to reproduce the issue from our side, share your panel via  `panel --> more --> get help` workflow in the panel's dropdown menu? 

https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/

![CleanShot 2023-01-31 at 14 40 21](https://user-images.githubusercontent.com/37156449/215916832-8d29d39c-57a1-40a7-a6e0-bfe584ea8bd4.gif)

**Comment by letmaik** [comment]
I figured out what the problem was. The Runtime field apparently wasn't of numeric type. Adding a Transform "Convert field type" to Numeric solved the issue. I still think this is a bug as it is clear from the Unit that the field is numeric, considering that it is perfectable able to parse it as seconds and show it as human-readable duration.

**Comment by tonypowa** [comment]
Thank you for sharing your research @letmaik 

I will forward your feedback to the Dashboard squad.

**Comment by evictorero** [comment]
Hey @letmaik, thanks for letting us know about this.
The sorting is based on the underlying unit (not duration (s)) so your particular case seems to be working as expected.
I understand that it could be desirable to infer a different type in this particular case but there are several transformations and would be complex to have different behavior on each one.
