### ISSUE TITLE
[Feature request] Units/Output formating should include binary option.

### ISSUE THREAD

**Issue by gerritavenant** [grafana/grafana#7217]
The Unit for display in Tables for example can also include a binary formatting.  Normal and with '0b' prefixed.

Binary masking and binary operators would also be useful, but probably have to be done on the Grafana side.

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
