### ISSUE TITLE
LDAP Authentication Config Overwrite on Upgrade

### ISSUE THREAD

**Issue by alexjn1984** [grafana/grafana#72198]
### What happened?

Whenever I upgrade Grafana, using the windows install package, or when a management component performs the upgrade, ldap.conf is overwritten, resulting in loss of service to users.

### What did you expect to happen?

ldap.conf is not replaced upon upgrade

### Did this work before?

Always happens

### How do we reproduce it?

1.Configure LDAP
2.Upgrade Grafana
3.End up re-configuring LDAP

### Environment (with versions)?

Grafana: Latest
OS: Windows 2022

### Grafana platform?

A downloaded binary

**Comment by usmangt** [comment]
Hi @alexjn1984,

Thanks for opening this issue.

This seems more of a question than a real issue.

Please create a new post at our community forums under the [Authentication category](https://community.grafana.com/c/support/auth/22) by providing the same details (add in case if you missed any) so that our community members can help you out.

If incase you do not get any help, then let us know. For now I am closing this issue.
