### ISSUE TITLE
Cannot connect to influxDB Data source

### ISSUE THREAD

**Issue by Ninhrod** [grafana/grafana#72305]
### What happened?

Hello everyone i'm trying to syncronizate my influxdb with the grafana. I'm following the steps based in create a new connection on settings and after fullfield with the user and password and my token generaded by influxdb, a message of Get "http://127.0.0.1:8086/query?db=telegraf&epoch=ms&q=SHOW+measurements": dial tcp 127.0.0.1:8086: connect: connection refused error performing influxQL query

### What did you expect to happen?

i'm weting for get sync with de database

### Did this work before?

my first time

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by usmangt** [comment]
Hi @Ninhrod,

Thanks for opening this issue.

I am closing this issue here on GitHub, as it seems more of a question.

Please create a new post at our community forums in the [InfluxDB category](https://community.grafana.com/c/support/influxdb/11) by providing the same details (in case if you missed any add that as well) so that our community members can help you out.
