### ISSUE TITLE
Alerting: Group interval for notification policy doesn't work properly for value less than 1 minute

### ISSUE THREAD

**Issue by atimin** [grafana/grafana#72332]
### What happened?

For some reason, I would like to send a webhook as fast as possible when an alert happens. In production, we experienced that the notification policy ignores alerts that change their states a few times in a second. If I understood the description of `Group interval` correctly, this setting is responsible for the delay between alerts to send.  I tried to reduce it to 10s , which is the evaluation time of our alerts.  Unfortunately, it doesn't help.

I created a minimal setup with an alert with toggles its change each 10s:

![image](https://github.com/grafana/grafana/assets/67068/fc415019-c33f-4dcc-ae9c-2c78122ac226)

I use the following notification policy settings:

![image](https://github.com/grafana/grafana/assets/67068/81d56220-107b-466b-b848-8e3fbc3f6bd7)

Unfortunately, this setup doesn't send any alerts at all:

![image](https://github.com/grafana/grafana/assets/67068/3884a801-6a66-4bce-a4f1-e7ce76b2b141)

### What did you expect to happen?

I expect to receive a webhook each 10s

### Did this work before?

It works if alerts happen once a minute or rare.

### How do we reproduce it?

1. Get an alert that changes a few times in a minute
2. Set `Group interval` in Notification Policy to 10s
3. Create an integration which you can use to test.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.0.2
OS: Docker instance on Ubuntu 22.04
Browser: Chromium  114.0.5735.198

### Grafana platform?

Docker

### Datasource(s)?

InfluxDb

**Comment by usmangt** [comment]
Hi @atimin,

Thanks for opening this issue.

This sounds like you may need to [setup alerting high availability](https://grafana.com/docs/grafana/latest/alerting/set-up/configure-high-availability/) but I will forward this to our engineers if there is a configuration option that might help here.

**Comment by grobinson-grafana** [comment]
Hi! Thanks for opening this issue! Without knowing more about what it is that is being monitored, alerts that change this often are considered flapping alerts. Grafana (and Alertmanager) go to a lot of effort to reduce the effects of flapping alerts, it is one of their design goals. If you really want a notification when the alert changes from firing to normal and back again, given a 10 second evaluation interval I would change `group_interval` to a number less than `10s` such as `5s`.w

**Comment by grobinson-grafana** [comment]
Hi! Thanks for opening this issue! Without knowing more about what it is that is being monitored, alerts that change this often are considered flapping alerts. Grafana (and Alertmanager) go to a lot of effort to reduce the effects of flapping alerts, it is one of their design goals. If you really want a notification when the alert changes from firing to normal and back again, given a 10 second evaluation interval I would change `group_interval` to a number less than `10s` such as `5s`.

**Comment by atimin** [comment]
Hi @grobinson-grafana, thank you for your request. Unfortunately, it doesn't work. This is exactly why I created the issue. It looks like the option isn't working properly, or Grafana can't keep up with the alerts, and the alerts are flapping even when the option is set to 5.  In my setup, the fastest configuration where I don't miss any alerts is one alert per minute.

**Comment by grobinson-grafana** [comment]
I think you've run into something called the Resend Delay which is another flap-reduction feature in Grafana. Would it be possible to share a little more about your use case? For example, what is it you're trying to do in Grafana and what problem you're trying to solve?

**Comment by atimin** [comment]
We use the alerts to trigger video recording, and we need to be fast as possible. However, I found that 10s evaluation interval for the alerting and 1 second `group wait` option work fine for our application.  We receive the first notification fast enough, and we actually don't need the rest.   
However, the notification policy doesn't work as expected for `group_interval` less than 1 minute anyway.

My suggestions:
 * If it isn't a bug, and we have an additional Resend Delay, let's add it to the documentation. So the users could better understand how it works. 
 * If it is Grafana's limitation, and it isn't able to notify faster than once a minute, let's make it impossible to set a value less than 1m for the `group interval` option.

**Comment by gotjosh** [comment]
Thanks very much for your report @atimin. I think we can make this better - currently, we have a fix resend delay of [30s](https://github.com/grafana/grafana/blob/02f2ff1870e7f93389436be99bc33ab6af0534ba/pkg/services/ngalert/state/manager.go#L73) and you're right in cases where you're allowing a `min_interval` lower than `30s` this doesn't make much sense.

As such, I think this should match the `min_interval` in the worts-case scenario which would allow you to make it configurable.

It's important to note that is completely orthogonal to what  `group_interval` is which is how often we'll evaluate for new alerts in the group - so if every 10s a new alert instance is coming out of alert rule we'll still deliver that one on a 10s basis.

To illustrate this, you can think of a set of labels as `[cluster=prod namespace=myservice instance=service-pod01]`. If the same alert of `[cluster=prod namespace=myservice instance=service-pod01]` happes every 10s then this protection kicks in until 30s have passed, but if you have `[cluster=prod namespace=myservice instance=service-pod02]` then will be effectively delivered immediately to the alertmanager and then be evaluated as part of the group on a 10s basis.

This has nothing to do with a "limitation" and more to do with service protection - in the case of an alert storm, we wish this not to be a footgun and we bring the whole system down because if you're receiving a high number of alerts every 10s we don't think this humanly actionable anyways. 

With that said, I'm curious to understand what do you mean with:

>However, the notification policy doesn't work as expected for group_interval less than 1 minute anyway.

Can you please elaborate on what doesn't work as expected?

**Comment by atimin** [comment]
Hey @gotjosh, I apologize for my belated answer. I was on my vacation. 

Thank you for the clarification! Now It completely explains the behaviour which I experience.

> However, the notification policy doesn't work as expected for group_interval less than 1 minute anyway.

Please, ignore this. I've made a mistake in my test setup and made a wrong estimation.

**Comment by gotjosh** [comment]
I have to be completely honest with you and tell you that it is very low priority for us at the moment. However, we would love to accept a contribution if you're up for it.

What I think we should do is:

- Allow the resend the delay to be configurable through a configuration option

or

- Pick the minimum between [min_interval](https://github.com/grafana/grafana/blob/main/conf/defaults.ini#L1105) or the current default which is 30s. Emit a warning when we do this.

My preference would be the latter, as it's less invasive.

**Comment by atimin** [comment]
I see. Unfortunately, our company doesn't have enough expertise to contribute Gradana's code. Now we are aware of the resend delay and the 30 seconds is acceptable. However, if we need to reduce the delay, we will find some resources and make it configurable. Thanks for your support!
