### ISSUE TITLE
Dashboards: reloading a dashboard with special characters (/) leads to 404 error

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#72341]
### What happened:
When visiting a dashboard in hosted Grafana that contains special characters, we encounter a 404 error upon dashboard reload. This seems to be related to URL encoding. Oddly enough, I'm not able to reproduce this issue locally.

### How to reproduce it:
1. In your Grafana instance (hosted), create a dashboard with the name `dashboard/name-with-special-characters`.
2. Notice that as the dashboard loads, the URL transforms into: `<instance>/<dashUId>/dashboard%2name-with-special-characters?orgId=1`.
3. Reload the dashboard.
4. You'll see a 404 error, and the URL changes to `<instance>/<dashUId>/dashboard/name-with-special-characters?orgId=1`.

https://github.com/grafana/grafana/assets/239999/b4ce7ca1-1056-4337-8b17-ad99a133ddf4

### Expected Behavior:
The dashboard should load without encountering a 404 error.

### Notes from the Investigation:

During my investigation, I observed that in play Grafana (v10.0.3), if a dashboard contains special characters like 'dashboard/name-with-special-characters', the URL transforms to 'https://play.grafana.org/d/c2824862-8769-41f0-a9dc-64490db9ef85/dashboard-name-with-special-characters?orgId=1'. It's interesting to note that instead of using '/', it changes it to '-'.

#### Environment
Grafana: v10.1.0-58755pre (f7c6491f73)
Browser: Chrome Version 115.0.5790.98 (Official Build) (64-bit)

**Comment by kaydelaney** [comment]
Tried everything I could to reproduce this locally: using HTTPS, serving from subdomain, using different versions of grafana, etc. but I couldn't reproduce :(
I wonder if it's the specific server config? 🤔

**Comment by kaydelaney** [comment]
Could @grafana/backend-platform take a look at this?

**Comment by leveyjam** [comment]
I've managed to reproduce this. If the dashboard name is "something/something" (no spaces) it's reproducable with the steps described above. If the name is "something / something", this seems to work and be encoded as "something-something". "something/something" is getting turned into "something%fsomething", and on reload "something/something" (=> 404). 
The symptoms suggest the UI or backend is doing some " " based tokenizing when handling "/" and turning it into "-" when it is a token by itself, but `%2f` when it is encountered within another token.

**Comment by leveyjam** [comment]
Update: The `/` encoding is actually being done by a proxy server with `UNESCAPE_AND_REDIRECT` enabled. 

e.g., https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge 

A work around is to use spaces before/after (before / after) `/` in names. 
A solution would be to not use names with `/` in path-based-routes, because even if handled correctly, proxies are regularly configured to disallow `%2f`, and it can be a source of confusion when dashboard links don't work, etc.

Maybe some documentation or troubleshooting FAQ around 404s due to `/` in names would be a good? (maybe the 404 error page could detect/suggest if `/` + intermediary proxy settings could be breaking URLs, etc?).

**Comment by natellium** [comment]
Bit more info from a thread:

> Here is how [alerting worked around it](https://github.com/grafana/grafana/issues/42947) and [how auth worked around it](https://github.com/grafana/grafana-enterprise/issues/4840). There is also more background [here](https://github.com/grafana/hosted-grafana/issues/1667#issuecomment-986789629)

**Comment by natellium** [comment]
The workaround doesn't seem to fix it for me neither @ethirolle

**Comment by leveyjam** [comment]
> A work around is to use spaces before/after (before / after) / in names.

I've tested this out again - and I see the workaround is not successful. It just so happens that the examples I was using are *not* behind a proxy w/re-write rule, and I assumed it was working. On closer inspection, ` / ` is being encoded to `-%2f-`, and on refresh/transport through a proxy with `UNESCAPE_AND_REDIRECT` enabled, it fails.

The only solution I see in that case is to have a "special" encoding for dashboard names (replace `/` with `---` or similar) if we wanted to use dashboard name as part of the path. And then all code that generates URLs including dashboard names would need to use this "special" encoding (and decoding).

I think the only workaround is to avoid `/` in dashboard names until a solution is found.

**Comment by ethirolle** [comment]
The funny thing is that this last portion of a dashboard URL (the part after `/d/<uid>/`) does not seem to matter much: I can replace it with almost any string of characters, and it resolves and takes me to the dashboard with the provided uid. The only thing that really trips it up is adding a slash (or a `%2f` that gets resolved to a slash). So it seems like any solution would work except keeping a slash or `%2f` in the URL.

**Comment by natellium** [comment]
After some [conversations](https://raintank-corp.slack.com/archives/C03KVDHTWAH/p1691675108878769?thread_ts=1691594861.419179&cid=C03KVDHTWAH) seems the issue was introduced by this [PR](https://github.com/grafana/grafana/pull/70691). @DanCech is working on reverting it and a new implementation will follow up.

This is not really related to the areas of responsibility of the Dashboards squad so I will remove it from our project. Nevertheless, do ping us if any work is needed from our side :)

**Comment by DanCech** [comment]
#73164

**Comment by natellium** [comment]
I just checked my grafana instance and it's working again after reverting.

**Comment by burninmedia** [comment]
Thanks so much for fixing this! I reported the bug.
