### ISSUE TITLE
Alerting: too many error log for return code 404

### ISSUE THREAD

**Issue by wkshare** [grafana/grafana#72415]
### What happened?

```
2023-07-26 14:37:38
logger=context traceID=00000000000000000000000000000000 userId=4 orgId=1 uname=paul t=2023-07-26T01:37:38.87-0500 lvl=info msg="Request Completed" method=GET path=/api/ruler/142/api/v1/rules status=404 remote_addr=10.157.135.235 time_ms=613 duration=613.105296ms size=81 referer=https://10.157.135.235:3000/alerting/list traceID=00000000000000000000000000000000
2023-07-26 14:37:38
logger=context traceID=00000000000000000000000000000000 userId=4 orgId=1 uname=paul t=2023-07-26T01:37:38.87-0500 lvl=eror msg="no rule groups found\n" error="no rule groups found\n" remote_addr=10.157.135.235 traceID=00000000000000000000000000000000
```

my configs:
```
[alerting]
enabled = false
```

### What did you expect to happen?

Alerting: too many error log for return code 404

### Did this work before?

I don't use other version.

### How do we reproduce it?

1. open alert rules 
2. to check grafana log
3. you can saw those error logs

### Environment (with versions)?

Grafana: v8..5.4
OS: Oracle Linux 7
Browser: Chrome

### Grafana platform?

A downloaded binary

### Datasource(s)?

Loki

**Comment by usmangt** [comment]
Hi @wkshare,

I am closing this issue here on GitHub, as it seems more of a question.

Please create a new post at our community forums in the [Alerting category](https://community.grafana.com/c/support/alerting/60) by providing the same details (in case if you missed any, provide that as well) so that our community members can help you out.

Thank you
