### ISSUE TITLE
[Feature Request] Support AWS SigV4 authentication for Elasticsearch Datasource

### ISSUE THREAD

**Issue by wjbuys** [grafana/grafana#7245]
I would like to use an [Amazon Elasticsearch Service](https://aws.amazon.com/elasticsearch-service/) cluster as an Elasticsearch datasource in Grafana. This works just fine if I allow public access to the cluster, but I'd prefer to lock it down to authenticated users only.

The only user-level access control Amazon ES supports is [through AWS SigV4 signing the HTTP requests to Elasticsearch with IAM credentials](http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html#es-createdomain-configure-access-policies). For example, [here's how the Golang `elastic` client does it](https://github.com/olivere/elastic/wiki/Using-with-AWS-Elasticsearch-Service).

I had a look at how the `proxy` mode of the ElasticSearch datasource works, and it looks like it would be pretty straightforward to build this signing into `dataproxy.go`, similarly to [how it's handled for the CloudWatch data source.](https://github.com/grafana/grafana/blob/master/pkg/api/dataproxy.go#L81-L84)

**Comment by vincent6767** [comment]
Any update here?

**Comment by kerbou** [comment]
Hi. We're very keen on getting an update on this feature as it is painful to work around the lacking support for managed ES instances.

**Comment by Datise** [comment]
@kerbou  @vincent6767  @wjbuys did either of you figure out how to do this? Currently have a project stuck.

**Comment by kerbou** [comment]
Nope - ended up with IP whitelisting for security while silently barfing in my mouth a little   :o/

**Comment by Datise** [comment]
That's what I"m doing now but it's left me silently barfing in my mouth for a bit and won't work long term given our environment constraints =/ 

I started looking at https://github.com/grafana/grafana/pull/8652 
but it seems at an impasse and I'm not a go developer so trying it out myself has been pain.

**Comment by emepetres** [comment]
For now you can use aws-es-proxy (
https://github.com/abutaha/aws-es-proxy/blob/master/README.md) together
with grafana.

Once you have the proxy running, just connect the data source to the proxy
endpoint and everything should work.

**Comment by Datise** [comment]
@emepetres thanks for the suggestion I will take a look tomorrow =).

**Comment by Datise** [comment]
@emepetres  I was hoping not to have to manage another service but this was extremely simple to setup and is working so thank you for the pointer.

**Comment by emepetres** [comment]
@Datise glad to help! I think this is the best solution for now, it simple and lightweight, and it doesn't seem to be implemented by the backend in the near future.

**Comment by bpair** [comment]
Rather than use aws-es-proxy and hosting a web server it would be preferable to use API Gateway and the Access Key Id and Access Key option. This was implemented in the Cloudwatch datasource and it would be great if it was available in the elasticsearch datasource.

This would make it possible to use your hosted grafana service hitting an API Gateway proxy that hits elasticsearch via lambda. No servers to maintain.

I think that might be the easiest workaround. 

Also Amazon just launched their serverless application template repository so I could see a template for creating the API Gateway and Lambda portion which makes this setup easy. https://aws.amazon.com/serverless/serverlessrepo

I am not sure how much work is involved in adding that feature to the datasource but I think a lot of people would benefit.

**Comment by jangaraj** [comment]
My final serverless AWS setup: AWS API Gateway, with custom Lambda authorizer to verify basic authentification and Lambda proxy function to proxy request to AWS ES in my VPC.

IMHO the easiest workaround will be to add a new option for custom datasource request header(s), which can be used for API key, JWT token, etc.

**Comment by hobbs** [comment]
@jangaraj any chance you'd be open to sharing the source for the lambda function?

**Comment by jangaraj** [comment]
@hobbs I can't because of legal enterprise issues. Good starting points for Python versions:
- AWS Lambda authorizer: https://github.com/awslabs/aws-apigateway-lambda-authorizer-blueprints/blob/master/blueprints/python/api-gateway-authorizer-python.py
- AWS Lambda proxy: http://webscale.plumbing/python-lambda-api-gateway-proxy

**Comment by pierluigilenoci** [comment]
Any news in this topic?

**Comment by pierluigilenoci** [comment]
I found this https://github.com/grafana/grafana/issues/10971, is it related?
