### ISSUE TITLE
Logs: Clicking hide this field after filtering freezes the app

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#72504]
In Explore, clicking on interactions in following order makes app frozen:
1. Click `show this field instead of log line` in log details
2. Click `filter for` or `filter out` some field
3. Click `hide this field`  after filtering freezes the app

https://github.com/grafana/grafana/assets/30407135/d5fc9950-3f12-4f05-80cb-39102d5c3d60

**Comment by hiepqdinh** [comment]
This bug seems to be re-introduced after https://github.com/grafana/grafana/pull/77264 where the feature flag is removed and AsyncIconButton is used again for 'search-plus' button.

Basically after I interact with this async icon button, the browser will hang if I click on any of the other regular `IconButton` (either the stats button, or the toggleField button).

We are using 10.4.1 FWIW.
