### ISSUE TITLE
[Feature request] Edit Multiple Panels at Once

### ISSUE THREAD

**Issue by ericturnerit** [grafana/grafana#7261]
Would be really cool if you could select multiple panels and be able to edit some or all parts of the panels at once. I know you could just edit the JSON file but that kind of a pain when you just want to do a quick edit like changing a column's color.

Let me know if this isn't clear.

**Comment by utkarshcmu** [comment]
You might want to look at https://github.com/utkarshcmu/wizzy , it does something similar and we can add more commands to it do more things. For example, one of the things it does is, it changes datasource on all the panels in a dashboard.

**Comment by ericturnerit** [comment]
@utkarshcmu Perfect! This will work for now. Thank you!

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

We are working on a shared panel feature that might be what you are looking for. The other way to do this by working with Grafana dashboards as code. See our jsonnet lib: https://github.com/grafana/grafonnet-lib and mixins: https://grafana.com/blog/2018/09/13/everything-you-need-to-know-about-monitoring-mixins/

Thank you to you for taking the time to create this issue!
