### ISSUE TITLE
User: Login not possible with version 9.5.5 due to: duplicate key value violates unique constraint "UQE_org_name"

### ISSUE THREAD

**Issue by merlinj1** [grafana/grafana#72683]
### What happened?

After Updating from Grafana Version 9.5.3 to Grafana 9.5.5 we observed the following Problem when trying to login as an existing user with an assigned organisation:

![image](https://github.com/grafana/grafana/assets/89360266/4521a7f9-d794-457e-a7d1-a1a1b865fc3f)

It seems that grafana is trying to create a new default organisation for that user, although an existing organisation is already assigned to that user.
The setting "_user.auto_assign_org_" is set to _true_, but should only be considered for new users.
Also "_auth.generic_oauth.skip_org_role_sync_" and "_oauth_skip_org_role_update_sync_" are set to _true_.

We are using a generic oauth2 provider for authentication with following settings:

Auth settings:
```
 "auth": { 
   "api_key_max_seconds_to_live": "-1",
    "azure_auth_enabled": "false",
    "disable_login": "false",
    "disable_login_form": "true",
    "disable_signout_menu": "true",
    "disable_sync_lock": "false",
    "login_cookie_name": "grafana_session",
    "login_maximum_inactive_lifetime_duration": "7d",
    "login_maximum_lifetime_duration": "30d",
    "oauth_allow_insecure_email_lookup": "false",
    "oauth_auto_login": "true",
    "oauth_skip_org_role_update_sync": "true",
    "oauth_state_cookie_max_age": "600",
    "signout_redirect_url": "",
    "sigv4_auth_enabled": "false",
    "sigv4_verbose_logging": "false",
    "token_rotation_interval_minutes": "10"
  } 
```

 Generic Oauth settings:

``` 
"auth.generic_oauth": {
    "allow_assign_grafana_admin": "false",
    "allow_sign_up": "true",
    "allowed_domains": "",
    "allowed_organizations": "",
    "api_url": "<hidden>",
    "auth_style": "",
    "auth_url": "<hidden>",
    "auto_login": "false",
    "client_id": "<hidden>",
    "client_secret": "<hidden>",
    "email_attribute_name": "email:primary",
    "email_attribute_path": "contact",
    "empty_scopes": "false",
    "enabled": "true",
    "groups_attribute_path": "",
    "hosted_domain": "",
    "icon": "signin",
    "id_token_attribute_name": "",
    "login_attribute_path": "preferred_username",
    "name": "FusionAuth",
    "name_attribute_path": "",
    "role_attribute_path": "",
    "role_attribute_strict": "false",
    "scopes": "openid,offline_access",
    "skip_org_role_sync": "true",
    "team_ids": "",
    "team_ids_attribute_path": "",
    "teams_url": "",
    "tls_client_ca": "",
    "tls_client_cert": "",
    "tls_client_key": "",
    "tls_skip_verify_insecure": "false",
    "token_url": "<hidden>",
    "use_pkce": "false"
```
User settings:
``` 
"users": {
    "allow_org_create": "false",
    "allow_sign_up": "false",
    "auto_assign_org": "false",
    "auto_assign_org_id": "1",
    "auto_assign_org_role": "Viewer",
    "case_insensitive_login": "false",
    "default_language": "en-US",
    "default_theme": "light",
    "editors_can_admin": "false",
    "external_manage_info": "",
    "external_manage_link_name": "",
    "external_manage_link_url": "",
    "hidden_users": "",
    "home_page": "",
    "login_hint": "email or username",
    "password_hint": "*********",
    "user_invite_max_lifetime_duration": "24h",
    "verify_email_enabled": "false",
    "viewers_can_edit": "false"
  } 
```

### What did you expect to happen?

Login is possible as in previous version.

### Did this work before?

Yes, the login was working with Grafana version 9.5.3

### How do we reproduce it?

1. Setup Grafana version 9.5.5 with generic oauth as login provider.
2. Create a new user and assign a certain organisation
3. Set Grafana Setting _user.auto_assign_org_ to _false_
4. Try to login with user from 2.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 9.5.5
OS: Ubuntu
Browser: This is not browser dependent

### Grafana platform?

Kubernetes

**Comment by IevaVasiljeva** [comment]
Hi @merlinj1 and thanks for reporting the issue!

This issue is a byproduct of a fix for a [security vulnerability](https://github.com/advisories/GHSA-mpv3-g8m3-3fjc). You can fix this by setting `oauth_allow_insecure_email_lookup` configuration option to `true`. You can disable this option again on Grafana v10+ once all the users have logged in once.

Some background on what is happening here: starting from Grafana 9.5, we have changed the user lookup to be based on user auth ID instead of email. This is because lookups based on email can be insecure. However, we did not use to register auth IDs for users. So Grafana cannot recognise users who have been created with older versions. Therefore when an existing user tries to log in, Grafana is attempting to create a new user entry and a new organization for this user (if `auto_assign_org` is set to false). This is where the `duplicate key value violates unique constraint "UQE_org_name"` comes from.

You can find more context on the security vulnerability [here](https://github.com/grafana/grafana/issues/70203#issuecomment-1603895013) and more information about the `oauth_allow_insecure_email_lookup` workaround [here](https://github.com/grafana/grafana/issues/70203#issuecomment-1609850174).

I'll close this issue, but feel free to reopen it if you have any further questions.
