### ISSUE TITLE
[Feature request]Add cause of alert to state history

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#7284]
Please include this information:
- What Grafana version are you using?
4.0.2
- What datasource are you using?
influxdb
- What OS are you running grafana on?
centOS

it would be better to include the cause of alert, for example, by indicating whether the alert is triggered by condition, timeout or execution error.

**Comment by bergquist** [comment]
We had some bugs regarding alert state history.

I master you will be able to see which are triggered by execution error (inc timeout), no data or conditions. 
You will also see which series that triggered the condition.

Closing this since I think thats what your asking for. Ill reopen this if you think something is missing
