### ISSUE TITLE
[Bug] Problem adding AWS CloudWatch as Data Source in new Grafana version

### ISSUE THREAD

**Issue by bamerrell** [grafana/grafana#7295]
- v4.1.1
- CloudWatch
- AWS Linux [amzn-ami-hvm-2016.09.1.20161221-x86_64-gp2 (ami-1e299d7e)]

- What did you do?
I'm attempting to add AWS cloudwatch as a data source

- What was the expected result?
Successfully adding the data source using an ARN as the auth provider and a role (E.g. arn:aws:iam::000000000000:role/my-role)

- What happened instead?
When I try to save & test, I receive "HTTP Error Internal Server Error". Looking into the logs, I see an entry as follows: 

> t=2017-01-18T01:39:18+0000 lvl=eror msg="Unable to call AWS API" logger=context userId=1 orgId=1 uname=admin error="AccessDenied: User: arn:aws:sts::000000000000:assumed-role/my-role/i-90sfd089asdf is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::000000000000:role/my-role\n\tstatus code: 403, request id: xxxxxx"

I'm not certain, but it appears that the instance has already assumed the role successfully, and is then trying to assume it again? I have successfully used the exact same role (and thus the same Assume Role ARN) for a previous instance on Grafana v4.0.2. - leading me to believe that this is a Grafana issue, not an AWS issue.

Any ideas? I will attempt to add the datasource using a credentials file when I get a chance, and will post the results here, but a role is certainly more preferable for both security purposes and ease of use.

**Comment by torkelo** [comment]
@mtanda any ideas?

**Comment by mtanda** [comment]
I installed Grafana v4.1.1 in my env, and confirm that Assume Role is working in my env.
The Grafana settings is seems to be correct, and AWS settings might be correct.
It's very strange.

**Comment by bamerrell** [comment]
To close this one out...

We successfully added the data source after adding the bolded line to our role's trust relationship as follows:

_{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com",
        **"AWS": "arn:aws:iam::0000000000000:role/my-role"**
      },
      "Action": "sts:AssumeRole"
    }
  ]
}_

It is curious that it worked in an earlier version without explicitly specifying the role itself in its own trust relationship, but at least there is a solution.

**Comment by jujugrrr** [comment]
> It is curious that it worked in an earlier version without explicitly specifying the role itself in its own trust relationship, but at least there is a solution.

I've just started to use the cloudwatch datasource, it looks to me like there is a behaviour issue. By doing what you say, the SDK will assume the instance role, to then assume the same role.

What most people would do (and should?) is just to assume the instance role(done automatically by the SDK), then query metrics with this role. You then need to make sure the role assigned to the instance has the correct IAM permissions for cloudwatch.

@torkelo @mtanda 
**Would it make sense to have another auth provider? Rather than ARN just have "Instance" or "auto " or even "SDK" ? **.

**Comment by jayangshu84** [comment]
Hi guys, 

Same issue exists in Grafana v4.2.0. Please reopen this issue.
Even after adding the following line on the trust policy, I was getting the same error.

v4.2.0

CloudWatch

ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20170221 (ami-f4cc1de2)

What did you do?
I'm attempting to add AWS cloudwatch as a data source

Line I added on the trust policy:
"AWS": "arn:aws:iam::<My AWS Id>:role/<name-of-my-role>"

Now my trust policy looks like:

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com",
        "AWS": "arn:aws:iam::<My-AWS-ID>:role/<My-role-name>"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}


Error appearing on my /var/log/grafana.log:

t=2017-04-18T09:39:11+0000 lvl=eror msg="Unable to call AWS API" logger=context userId=1 orgId=1 uname=admin error="AccessDenied: Not authorized to perform sts:AssumeRole\n\tstatus code: 403, request id: xxxxx"
t=2017-04-18T09:39:11+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/5 status=500 remote_addr=xx.xx.xx.xx time_ms=20ns size=36

Thanks,
Jay

**Comment by Kasunmadura** [comment]
Same issue on 4.3.2 also

**Comment by daniellee** [comment]
@Kasunmadura can you provide more information (what does your config look like)? Is this a bug in the Cloudwatch data source or do you need help configuring your IAM role?

http://docs.grafana.org/features/datasources/cloudwatch/#using-aws-cloudwatch-in-grafana

**Comment by mooyoul** [comment]
@daniellee It seems Cloudwatch data source bug, We had to modify our trust relationship (@bamerrell pointed out) even Another applications (e.g. Influxdata telegraf) works correctly without modifying trust relationship.

**Comment by torkelo** [comment]
@mooyoul do you use AWS IAM role auth for influxdb & telegraf?

**Comment by Kasunmadura** [comment]
@daniellee  It's working fine with IAM role assign to an instance.thanks

**Comment by mooyoul** [comment]
@torkelo Yes, I am using IAM role auth for grafana and telegraf (both for personal projects and for my company product monitoring). It works great, never failed. just works. really awesome.

**Comment by dbendelman** [comment]
I'm running Grafana v4.4.3 (commit: 54c79c5) and still seeing this issue. I agree with the idea @jujugrrr had for solving this easily: just make a new option `Instance Profile` in the `Auth Provider` dropdown that takes no other configuration, and then Grafana code can just expect that making calls into the AWS SDK authenticates automatically with no further action from Grafana.

@torkelo @mtanda Although the OP found a workaround he was happy with and closed this, I think the underlying bug is still around and this issue should be reopened and fixed.

**Comment by polasekr** [comment]
I am running Grafana 4.4.3 as a container within Kubernetes cluster and since I struggled with setting up datasource for AWS I wanted to share my configuration, hopefully it will help some other people to quickly fix their issue. 
I downloaded and using a dashboard template from https://grafana.com/dashboards/617. 

My datasource is set up as follows:
Name:                                        AWS
Type:                                          CloudWatch
Auth Provider:                           Credentials file
Credentials profile name:          default 
Default Region                          us-east-1
Custom Metrics                         AWS/EC2

I am not sure what custom metrics suppose to be, it also works when left blank.

I created a role EC2-cloudwatch (arn:aws:iam::533108516651:role/EC2-cloudwatch ) and attached a policy CloudWatchReadOnlyAccess to it.

The name of the role assigned to Kubernetes node EC2 instances is **nodes.k8s-dev.hubub.com**. 
In that role (nodes.k8s-dev.hubub.com) on permissions tab I have following inline policy attached to it:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:Describe*"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ecr:GetAuthorizationToken",
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetRepositoryPolicy",
                "ecr:DescribeRepositories",
                "ecr:ListImages",
                "ecr:BatchGetImage"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "route53:ChangeResourceRecordSets",
                "route53:ListResourceRecordSets",
                "route53:GetHostedZone"
            ],
            "Resource": [
                "arn:aws:route53:::hostedzone/Z220JSW9HF9CX3"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "route53:GetChange"
            ],
            "Resource": [
                "arn:aws:route53:::change/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "route53:ListHostedZones"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::hu-s3b-kops/k8s-dev.hubub.com",
                "arn:aws:s3:::hu-s3b-kops/k8s-dev.hubub.com/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::hu-s3b-kops"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "cloudwatch:*"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "sts:AssumeRole"
            ],
            "Resource": [
                "arn:aws:iam::533108516651:role/EC2-cloudwatch"
            ]
        }
    ]
}
```
Permissions for s3, ec2 and ecr are for kops used as a Kubernetes provisioning tool, route53 is for helm dns-controller to update dns records in route53. All those are not directly related to this topic, I am just listing them for completeness. Two policies needed for grafana datasource are sts and cloudwatch.

As discussed in this thread I also updated a "trust relationship" tab for this role (nodes.k8s-dev.hubub.com) as follows:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::533108516651:role/nodes.k8s-dev.hubub.com",
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

This setup works perfectly for me. It is important to watch Grafana log for any issues and clues. I also learned that in my setup I wasn't getting any data for default time period of the template. If you getting no errors but charts display message "no data points", play with your selections for the template.

**Comment by toanc** [comment]
I had same issue with version 4.5.2 and tested with latest version.
The thing is when I able to assume role manually & fetching the metrics from across account. 
It seems Grafana ARN bug function

**Comment by rubberduck203** [comment]
> > It is curious that it worked in an earlier version without explicitly specifying the role itself in its own trust relationship, but at least there is a solution.
> 
> I've just started to use the cloudwatch datasource, it looks to me like there is a behaviour issue. By doing what you say, the SDK will assume the instance role, to then assume the same role.
> 
> What most people would do (and should?) is just to assume the instance role(done automatically by the SDK), then query metrics with this role. You then need to make sure the role assigned to the instance has the correct IAM permissions for cloudwatch.
> 
> @torkelo @mtanda
> **Would it make sense to have another auth provider? Rather than ARN just have "Instance" or "auto " or even "SDK" ?**.

This is how this should work.
This issue should really be re-opened.
The "proper" way to handle this when running in AWS is to attach instance policies.
We shouldn't have to work around this by modifying the trust relationship.

Would the maintainers be willing to accept a pull request to fix this?

**Comment by torkelo** [comment]
We are using the official aws sdk, so not sure what could be wrong. Any help would be appreciated

**Comment by rubberduck203** [comment]
Cool. I’ll try to figure out what’s happening here. 

Note to self: This file seems to be where the credentials are retrieved. https://github.com/grafana/grafana/blob/1165d098b0d0ae705955f9d2ea104beea98ca6eb/pkg/tsdb/cloudwatch/credentials.go

**Comment by mtanda** [comment]
Sorry, I don't use Grafana UI for provision CloudWatch datasource, so I didn't notice the problem.
Auth type dropdown is introduced in https://github.com/grafana/grafana/pull/6698 .

I think, we need to add another auth type for EC2 Instance IAM like @dbendelman 's suggestion.
> @jujugrrr had for solving this easily: just make a new option Instance Profile in the Auth Provider dropdown that takes no other configuration, and then Grafana code can just expect that making calls into the AWS SDK authenticates automatically with no further action from Grafana.

**Comment by mtanda** [comment]
FYI, I succeed to provision CloudWatch by following setting file.
```
apiVersion: 1

deleteDatasources:
  - name: CloudWatch
    orgId: 1

datasources:
- name: CloudWatch
  type: cloudwatch
  access: proxy
  orgId: 1
  jsonData:
     defaultRegion: "ap-northeast-1"
  version: 1
  editable: false
  ```
