### ISSUE TITLE
[panel] "Untitled" title appears when not giving a title to a panel.

### ISSUE THREAD

**Issue by usmangt** [grafana/grafana#72978]
### What happened?

When creating a new panel and not giving it any title. What happens is that when hovering to that panel appears title as Untitled.

This might be not a good case in some areas for user if they do not want to name a panel title on purpose. For e.g. https://community.grafana.com/t/untitled-box-button-in-new-grafan-10-x/100604

Therefore, would be good to give an option to hide this "Untitled" option or simply do not bring it on display when hovering.

A temporary workaround I found was to put a spacebar character in it and it would work

### What did you expect to happen?

Panel title should not say Untitled when hovering over it. Just stay blank.

### Did this work before?

Changed noted in Grafana ver. 10

### How do we reproduce it?

Already defined in **What happened**

### Environment (with versions)?

Grafana: 10
OS: NA
Browser: NA

### Grafana platform?

Other

### Datasource(s)?

NA

**Comment by ashharrison90** [comment]
pretty sure this is working as intended, but i'll leave it to the dashboards team to confirm that 👍

**Comment by psheehymn** [comment]
The suggested workaround (a space) is not an effective solution, at least with Text and Stat panels. We use both extensively and we do NOT want a title because want the visualization to extend upward into the space that the title would otherwise occupy. Adding a space to get rid of the "Untitled" adds an undesired downshift of one blank line to the visualization. See the four attachments. 

The extra space is merely annoying in the Stat case, but forces me to increase the height of the Text panel when I shouldn't have to. Please fix this; if this is "working as intended," then it is "Broken As Designed" (a.k.a. B.A.D)!

**Comment by juanicabanas** [comment]
This is going to be discussed with the team in the following weeks, since the "Untitled" title is intentional but it makes sense if someone doesn't want to show anything

**Comment by natellium** [comment]
Hey @psheehymn, after discussing with the team we agree that the "Untitled" doesn't add much value anymore and we should remove it. Thanks for the feedback!
