### ISSUE TITLE
Alerting: No label in resolved message for dynamic nodes monitor

### ISSUE THREAD

**Issue by dingweiqings** [grafana/grafana#73088]
### What happened?

Prometheus config and targets
![image](https://github.com/grafana/grafana/assets/30000877/c2c0d45e-4786-4510-a13d-db9cd55b7115)
![image](https://github.com/grafana/grafana/assets/30000877/94715e24-efb0-44cf-b56e-8634b54ce735)
1. Add an alert rule for check a host cpu metric, set NoData config to Alerting
![image](https://github.com/grafana/grafana/assets/30000877/8fec2067-c73f-47a2-b9ca-f381f0c924de)
3. Shutdown this host and prometheus target is removed
4. We got a alert message with no label.
5. Start this host and add prometheus target .
6. We got a resolved message, but there is  still no label in  resolved message.
**webhook json file**
[no-data-alert.txt](https://github.com/grafana/grafana/files/12300669/no-data-alert.txt)
[no-data-resolved.txt](https://github.com/grafana/grafana/files/12300670/no-data-resolved.txt)

### What did you expect to happen?

It show all labels in resolved message.

### Did this work before?

No

### How do we reproduce it?
Follow steps in bug description

### Environment (with versions)?

Grafana: v9.1.0 (82e32447b4)
OS: 18.04.6 LTS (Bionic Beaver)
Browser: firefox

### Grafana platform?

Docker

### Datasource(s)?

prometheus

**Comment by dingweiqings** [comment]
I read souce code about ngalert  module. But I am still  confused how ngalert sends new alert state to alertmanager when alert state changed .   
 I don't see postable alerts in debug log after a evaluate tick even if alert state changed.   Do you have some idea for this problem ? @zuchka 
![image](https://github.com/grafana/grafana/assets/30000877/6386c99a-b082-40a8-99d3-2ef70b372a3e)

**Comment by dingweiqings** [comment]
Is it controled by ```defaultResolveTimeout```  ?

**Comment by grobinson-grafana** [comment]
Hi! :wave: You won't receive labels about which series is firing as [classic conditions](https://grafana.com/docs/grafana/latest/alerting/fundamentals/alert-rules/queries-conditions/#:~:text=You%20can%20also%20use%20classic,are%20met%20for%20multiple%20series) remove them to create a single alert. It sounds like you might want to use [multi-dimensional alerting](https://grafana.com/docs/grafana/latest/alerting/alerting-rules/create-grafana-managed-rule/#single-and-multi-dimensional-rule) instead of classic conditions?
