### ISSUE TITLE
Alerting: 'View as List' no longer shows correct alert counts since v10.0.3

### ISSUE THREAD

**Issue by acaos** [grafana/grafana#73126]
### What happened?

We updated Grafana to v10.0.3 and when using `View as List`, the view no longer shows the correct alert counts (firing/pending/normal).

![image](https://github.com/grafana/grafana/assets/295044/508f8973-21ec-46b7-b390-debaa63f524a)

### What did you expect to happen?

We expect the alert count to match the values shown when expanding (in the above screenshot we would expect `1 firing` and `8 normal`).

### Did this work before?

Yes, this worked in earlier versions of v10. It also appears to work when using `View as Grouped`.

### How do we reproduce it?

1. Create several alert groups in the same folder, each with multiple alerts.
2. Have some of those alerts in each state (firing, pending, normal).
3. Go to the main Alerting List and click `List` in the `View As` selector to view grouped by folder.

### Is the bug inside a dashboard panel?

No, this is inside the main Alert List.

### Environment (with versions)?

Grafana: v10.0.3
OS: Windows
Browser: Chromium

### Grafana platform?

Kubernetes

**Comment by armandgrillet** [comment]
We are fetching this count from the backend since new versions of Grafana 10 to fix performance issues. However, this bug seems to have been introduced on the way. We are working on a new list view for later versions of Grafana, we will work on this bug if more people report it but we don't believe many users use "View as list".
