### ISSUE TITLE
[Feature request] Filter a table based on the selected series of a graph

### ISSUE THREAD

**Issue by ava7** [grafana/grafana#7317]
Grafana v4.1.1 (ElasticSearch, InfluxDb)

Hello, folks,

here is one suggestion from me. Let's say that we have the following dashboard - a graph with multiple series and a table below that shows the same information but more detailed. Would it be possible to make it so, that if one of the series in the graph is selected, the information in the table is also filtered accordingly? I don't know if it is even possible, but it would be great if there was a way to somehow link the a table with a graph.

Cheers, please hit me up if I wasn't clear enough. I would be glad to help with some coding but I am afraid I am not very familiar with AngularJS.

**Comment by daniellee** [comment]
Thank you for submitting this feature request. However, due to inactivity and/or lack of upvotes, we’re going to close this for now. This does not mean that we are closing it forever. Feel free to comment on this issue to clarify why this is needed and upvote it.

This feature request is in an area where will be doing more work in the near future - to make it easier it to drill down into data in the same dashboard.
