### ISSUE TITLE
Feature Request: InfluxDB, Flux language - Visual Query Builder

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#73432]
### Discussed in https://github.com/grafana/grafana/discussions/43848

<div type='discussions-op-text'>

<sup>Originally posted by **rjvtww** September 22, 2020</sup>
**What would you like to be added**:

Add visual query builder functionality for the Flux query language on InfluxDB v2

**Why is this needed**:

For my organization, the visual query builder is everything. It enables any form of user to easily query data. Without it, I cannot start exploring a transition into the flux query language, together with all the nice features it allows inside of influxdb</div>

**Comment by ajsicek** [comment]
This would be very helpful

**Comment by Milne77** [comment]
This is an important feature for non-programmers users who used flexQL before.
We are looking forward to it.

**Comment by sxwebster** [comment]
This is somewhat critical for us also

**Comment by itsmylife** [comment]
We truly value your needs and asks, but implementing a visual query editor for flux is not in our plans right now.

This is because InfluxDB put Flux into maintenance mode. See the article here https://www.influxdata.com/blog/the-plan-for-influxdb-3-0-open-source/ it was explained under the “Flux in maintenance mode” title.
So we are de-prioritizing this work and prioritizing the SQL support in InfluxDB. We are tracking SQL support in this epic https://github.com/grafana/grafana/issues/72169.
