### ISSUE TITLE
Import/Export alert rule in UI.

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#73437]
### Discussed in https://github.com/grafana/grafana/discussions/47036

<div type='discussions-op-text'>

<sup>Originally posted by **wangqinghuan** March 29, 2022</sup>
Currently, we can only import/export alert rule of new Grafana 8 with REST API. Could we support it in UI?
https://community.grafana.com/t/ngalert-grafana-8-alert-feature-how-to-export-import-alerts-as-yml-json/51677/17
</div>

**Comment by yuri-tceretian** [comment]
Export is already available. You can export in YAML. 
Also, we plan to add export in Terraform format.
As for import, it's not available in UI but we're discussing this feature, and likely it will be implemented in the future versions

**Comment by makamekm** [comment]
> Export is already available. You can export in YAML. Also, we plan to add export in Terraform format. As for import, it's not available in UI but we're discussing this feature, and likely it will be implemented in the future versions

Hi. How to import it without UI then???

**Comment by yuri-tceretian** [comment]
> Hi. How to import it without UI then???

You need to use file provisioning API. Please refer to https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/ for detailed instructions.

**Comment by Quoaa** [comment]
Hello,

Do I get it right that grafana allows export only for users or service accounts with Admin roles?

Because for edit role I don't see assignment of `alert.provisioning:read`

**Comment by yuri-tceretian** [comment]
@Quoaa this is correct. In future versions, we will downgrade it to Edit role probably in 10.2 or 10.3.

**Comment by VShamray1979** [comment]
@yuri-tceretian Hello! Has something changed? I have the 10.3 version and it looks like it has the same issue. Do you know in which version these changes were applied?

**Comment by VertexToEdge** [comment]
Hi, I want to contribute to this feature.
I will just going to add Import button that just calling Rule Provisioning API. 
Can I send PR when I done the work?

**Comment by yuri-tceretian** [comment]
Hi @VertexToEdge! All contributions are highly appreciated. Open a PR and we will review it. 
There are some things in the import that we discussed, and I would really appreciate it if you could include them in your PR.
- Alert rules in provisioning API can refer to folders by title. The import component should try to find the folder and ask user to pick one, if the folder does not exist or the user does not have access to it.
- Rules use data sources, and refer to them by UID. If data source does not exist, the import component should ask the user to pick one, ideally the picker should contain only data sources of the same type as specified in the rule.
Similar features are implemented in Dashboards, so you can refer to that part.

**Comment by VertexToEdge** [comment]
@yuri-tceretian Thanks for kind description!
I will try to making PR soon!

**Comment by yuri-tceretian** [comment]
One more thing that I forgot to mention. Currently, the main problem is that UI does not understand the format of provisioning API models. It operates uses models from our unstable API (PostableRuleGroupConfig and PostableExtendedRuleNode). We encountered it while working on the `modify export` feature. We created an API that accepted the unstable model and returned export data for provisioning. I think in the case of import we should stick to this plan as well. So, the workflow should be following:

- User clicks the import button in UI. UI shows it a panel with a text field.
- User pastes the content of the file into the field and clicks "Import".
- UI sends the content to an API (a new one) that parses the content and returns `PostableRuleGroupConfig` (or a list of them!) that describes a group of rules. 
After that there are two options:
1. API can automatically commit all the changes, i.e. validate that all folders and data sources exist, validate that user has permissions and save import to the database. Otherwise, return error that will mention the problem.
2. API can perform just a conversion of one format to another and return the model as is. Then user will have to click "Save" button and UI will submit the rules via the regular API, which will perform all validations.

I am leaning towards the 2nd option because it will open some other exciting opportunities like editing provisioned rule using our VSCode plugin. However, this will require more UI work.  On the good side, we can split this task in two or even more PRs: one for the back end (conversion) and other PRs - UI:
- Simple import button with text field and submit button + a list of imported data (two-level list, similar to Alert Rule List page) and save button.
- Update the list to be able to click on items and edit rules before saving + show problems (missing data sources, folders etc).

I wonder if @grafana/alerting-frontend has the capacity to help with the second part.

**Comment by kevinyang372** [comment]
Hi! Just want to cross-mention a feature request to export alerting rules within the editing UI here: https://github.com/grafana/grafana/issues/80323

**Comment by ryan-grafana** [comment]
this feature was released in 10.2. https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/export-alerting-resources/#export-alert-rules

**Comment by jr-dimedis** [comment]
@ryan-grafana: maybe I overseeing something obvious, but this PR is about having an UI for importing rules, correct? 

The feature release you mention is about exporting and @kevinyang372 mentioned another feature about exporting an edited version of a rule.

I just installed current kube-prometheus-stack (61.3.1) containing Grafana 11.1.0 and can't see anything about importing in the UI. So maybe this PR is still open?

**Comment by rosxz** [comment]
My exact thoughts. It seems importing alert rules through the UI is still missing as of 11.1.0

**Comment by wuestkamp** [comment]
It seems like it's possible to Export rules, but not to import.
So the only way is to "import" via provisioning, which means Alerts no longer possible to edit via UI.

We would like to create Alerts via UI, then Export and Save/Backup so we're able to import again in new Grafana or after crash/loss. After import we would like to continue to edit the Alerts via UI.

Is there a way to mark all provisioned rules as non-provisioned again? Maybe even via a dirty hack?

**Comment by yuri-tceretian** [comment]
@wuestkamp, you can use provisioning API with special header `X-Disable-Provenance` and it will not lock the resources in UI. Please check out the Grafana documentation for more details.

**Comment by yuri-tceretian** [comment]
I have added the issue to the team's whiteboard to prioritize the import. The implementation is not very straightforward because the rules refer to data sources, folders, dashboards etc by UID. Therefore, there must be some additional UI work to let users re-map the missing UIDs.

**Comment by wuestkamp** [comment]
Thanks @yuri-tceretian that would be nice to have!

This workflow seems to be working, and it's easier for me than calling the Api manually.
**BUT it requires a manual Grafana DB update, so only do this in production if you know what's up!**

1. Create Alerts via UI
2. Export Alerts via UI to Yaml
3. Import Alerts Yaml via file provisioning (https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning)
4. Manually mark the imported Alerts as non-provisioned/provenance in the Grafana DB:
```
# Access the Grafana volume/filesystem
sqlite3 grafana.db

# This query will mark !!ALL!! provisioned/provenance Alerts as non-provisioned/provenance
update provenance_type set record_type = 'alertRuleDISABLED' where record_type = 'alertRule';
```
5. Remove the Alerts Yaml again from file provisioning

In case you want to know a little about how the provenance_type SQL table works this seems to be the related Go code for it:
https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/store/provisioning_store.go

**Comment by jade-tseng** [comment]
@yuri-tceretian  Is the "Export" button for alert rules available for Editor role on Grafana OS? I am running into this problem that it is only available for admin. Editor user gets "You'll need additional permissions to perform this action. Permissions needed: alert.provisioning:read"
and it seems based [on this doc](https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/custom-role-actions-scopes/) that changing this RBAC is only available in enterprise/cloud?

**Comment by pcpathikpg** [comment]
@aifraenkel  @yuri-tceretian  I see this has been marked closed. When would be this available?
