### ISSUE TITLE
Allow grafana to receive alerts from other sources

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#73447]
### Discussed in https://github.com/grafana/grafana/discussions/45773

<div type='discussions-op-text'>

<sup>Originally posted by **damienleger** September 15, 2021</sup>
Hello!

**What happened**:

I'm running prometheus-operator on k8s and Grafana 8.1.3

I have a bunch of alerts set in prometheus-operator through ServiceMonitor or Probe (for blackbox-exporter) k8s resources. I see them in the alert panel [1] and one is firing.

I have setup notification system to send POST request to https://webhook.site/ because it's convenient for testing [2] [3] [4]. But no notifications are sent at all I don't know why, and debug logs aren't helping [5].

[1]
![image](https://user-images.githubusercontent.com/16499022/133401632-1b81208f-fa7d-4483-adc6-be735cd49552.png)

[2]
![image](https://user-images.githubusercontent.com/16499022/133401732-e387e9b8-2707-47d9-9c9d-ffd4610161b7.png)

[3]
![image](https://user-images.githubusercontent.com/16499022/133401795-6a4ad4cc-ed3d-46cc-baf2-dd674f170f60.png)

[4]
![image](https://user-images.githubusercontent.com/16499022/133401851-519ed1b5-15a5-4ea9-831f-29b00a35bf4d.png)

[5]
![image](https://user-images.githubusercontent.com/16499022/133403351-733f3273-bfa2-4ae5-bfd1-14085ff706a9.png)

**What you expected to happen**:

To see a notification every 10s.

**How to reproduce it (as minimally and precisely as possible)**:

Have some alert firing set in prometheus. Go to https://webhook.site/ and get the URL from there to configure the notification panel according to screenshots.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.3 (tried 8.1.2 after this https://github.com/grafana/grafana/issues/39009#issuecomment-915948936 but same behavior)
- Data source type & version: Prometheus 2.29.1
- OS Grafana is installed on: optimized Linux OS on EKS 1.21
- User OS & Browser: Windows 10, Firefox developer 93
- Grafana plugins: none
- Others: setup on EKS done following this method https://grafana.com/docs/grafana/latest/installation/kubernetes/ with two envvar set additionnaly: `GF_FEATURE_TOGGLES_ENABLE=ngalert` + `GF_LOG_LEVEL=debug`</div>

**Comment by yuri-tceretian** [comment]
It looks like you try to configure internal Alertmanager but the alert rule you want to test is executed by Prometheus. You need to add a new data source of type Alertmanager and configure it to point to the Alertmanager that the Prometheus ruler is configured to send alerts.

**Comment by yuri-tceretian** [comment]
It's worth mentioning that sending alerts from external source to Grafana internal Alert manager will not be supported in the future. Actually, we go in the opposite direction, making Grafana use the external Alert manager for alerts. You can configure this via Admin page.

**Comment by gelicia** [comment]
Because we are deciding to not pursue this, I will close this ticket.

**Comment by Dunge** [comment]
I understand the complexity of adding that feature, but I also add a +1 request for it.

Justification:
Grafana offers a more user friendly interface. Prometheus AlertManager look like an advanced admin-only system in comparison, while alert receivers are not always tech-savvy persons. Grafana email template look better, and it's webpage to manage contact points and silence is much more presentable. Grafana also support taking screenshots of the dashboard graphs with grafana-image-renderer that Prometheus AlertManager does not support. Just up to me, I would uninstall Prometheus AlertManager and just keep Grafana for everything.

But the kube-prometheus-stack helm template comes with a tons of very important alerts (registered under Prometheus AlertManager) that we cannot ignore.

Now we end up stuck with 2 different configuration of contact points and silence rules and e-mail templates, and it's not pretty and hard to explain to users.

**Comment by yuri-tceretian** [comment]
Thanks for the feedback! You're right, Grafana Alertmanager has some interesting features that neither "vanilla" nor Mimir Alertmanager supports. We are working to unify experience across two of them: Mimir and Grafana, and also try to push some improvements upstream. When we achieve that you will be able to run Alertmanager as an external service to Grafana and have all the features supported. 

Also, you can manage external Alertmanager by adding it to the Grafana as a data source and you will get better UI than the one that goes out of the box.

**Comment by davordbetter** [comment]
Sorry but there are many cases where this feature would be very useful.
As mentioned, Grafana UI is friendly and easy to adjust even templates as example

While adding Alertmanager as data source, I don't see option to edit template and support for MS Teams is horrible (which requires additinal templating system...).

Feature that internal Grafana could accept Prometheus alerts would be very welcome in out case.

**Comment by CyberWhiskey** [comment]
Ran across this discussion/issue after getting Thanos Ruler in place to start offsetting Grafana managed alert rules. I prefer managing them via source control for bulk add/edit. Got the look and feel for how they show up under Grafana as external alert rules, go to plumb them in with existing extensive Notification Policies > Contact Points using built-in Alertman and ran into the same realization as most that it Grafana doesn't process external alert rules. Nothing gave me the impression this wouldn't work, docs nor UI. 

As I finished getting Mimir Alertmanager setup I also noticed that I couldn't just copy/paste our Grafana-Alertman config to Mimir-Alertman too. 

Then realized an easier solution which was to create one Grafana managed Alert Rule to act on ALERTS metrics coming out of Thanos Ruler.

Grafana ALERT highlights:
- rule expr used: `label_replace(ALERTS{alert_source="thanos-ruler",alertstate="firing"}, "alert_name", "$1", "alertname", "(.*)")`
- for: `20s`
- eval interval: `20s` 
(idk, just went with my gut there with 'for' & 'interval', 20s for better or worse) 
- added labels:
  - "Alert_Source": `https://grafana.domain/alerting/list?search=label:alert_source%3Dthanos-ruler%20rule:{{ .Labels.alert_name }}`
  (I add alert_source via Thanos Ruler option `--label=alert_source="thanos-ruler"`)
  - "Alert_Description": _A description telling folks to navigate to Alert_Source link to explore the true origin._
  (don't want to link back to the single Grafana managed alert, but rather the actual source Thanos Ruler alert group.)

Reason you'd want to rename "alertname" label is because it'd get overwritten by the Grafana managed alert rule. Doing this you'll also want to consider a custom go-template for Titles and/or Bodies of events to favor "alert_name" vs "alertname" like:

```
{{ define "DevOpsThanosRulerAlerts.Title" -}}
  [{{ .Status | toUpper -}}
  {{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{- end }} - {{ .CommonLabels.severity -}}
  ] {{ .CommonLabels.alert_name }}
    Env: {{ template "uniqueEnv" . }}
    Cluster: {{ template "uniqueCluster" . }}
{{- end }}



{{ define "DevOpsThanosRulerAlerts.Body" }}
  {{ range .Alerts -}}
---
*Alert:* {{ .Labels.alert_name }}{{ if .Labels.severity }}{{ end }}
*Details:*
  {{- range .Labels.SortedPairs }}
    {{- if not (or (eq .Name "alertname") (eq .Name "alert_name") (eq .Name "grafana_folder")) }}
      • *{{ .Name }}:* `{{ .Value }}`
    {{- end }}
  {{- end }}
*Annotations:*
    Description: {{ .Annotations.Alert_Description }}
    Source: {{ .Annotations.Alert_Source }}
    SilenceURL: {{ .SilenceURL }}
  {{ end }}
{{ end }}


{{ define "uniqueEnv" }}
    {{- $previousEnv := "" -}}
    {{- range .Alerts -}}
        {{- if and (ne .Labels.environment $previousEnv) (ne .Labels.environment "") -}}
            {{- if ne $previousEnv "" -}}, {{ end -}}
            {{- $previousEnv = .Labels.environment -}}
            {{- .Labels.environment -}}
        {{- end -}}
    {{- end -}}
{{ end }}

{{ define "uniqueCluster" }}
    {{- $previousCluster := "" -}}
    {{- range .Alerts -}}
        {{- if and (ne .Labels.cluster $previousCluster) (ne .Labels.cluster "") -}}
            {{- if ne $previousCluster "" -}}, {{ end -}}
            {{- $previousCluster = .Labels.cluster -}}
            {{- .Labels.cluster -}}
        {{- end -}}
    {{- end -}}
{{ end }}
```

**Comment by kristeey** [comment]
2025 and Grafana still don't see this as a welcoming feature...
