### ISSUE TITLE
[Accessibility issue] Screen reader 'cursor focus' is not representative of the focussed item (MAS issue 335339)

### ISSUE THREAD

**Issue by ckbedwell** [grafana/grafana#73500]
**User experience**
Users with low vision may be confused what element is focussed as their screen reader 'cursor focus' is not following the active element correctly.

**Steps to reproduce**:
Activate your screen reader (confirmed with NVDA on Windows and VoiceOver on macOS) and navigate to the following components. Notice the screen reader 'focus cursor' does not outline the focussed component accurately.
[Radio button group](https://developers.grafana.com/ui/latest/index.html?path=/story/forms-radiobuttongroup--radio-buttons)
![image](https://github.com/grafana/grafana/assets/6906380/dc78ff00-26b8-4465-a44d-719ee407f61c)

[Select](https://developers.grafana.com/ui/latest/index.html?path=/story/forms-select--basic)
![image](https://github.com/grafana/grafana/assets/6906380/51b056da-e6a0-4b28-875b-93e31ed0692f)

[Switch](https://developers.grafana.com/ui/latest/index.html?path=/story/forms-switch--controlled)
![image](https://github.com/grafana/grafana/assets/6906380/15b2aff4-2043-41af-ab12-aaa3c685d6dd)

**Actual Result**:
See screenshots above for where VoiceOver's 'cursor focus' appears in relation to the normal focussed state.

**Expected Result**
Screen reader cursor focus correctly outlines the focussed element.

```[tasklist]
### Tasks
- [x] Radiobutton group https://github.com/grafana/grafana/pull/75933#pullrequestreview-1662153684
- [x] Select
- [x] Switch https://github.com/grafana/grafana/pull/93100
```

**Comment by abhiShandy** [comment]
After a brief investigation, I found that the input elements of the radio group have an absolute position, and they are stacked on top of each other. These input elements are picked up by the VoiceOver cursor which appears to not switch from one to another.

One solution is to position the input elements on top of the respective label elements.

Let me try that out with CSS.

**Comment by abhiShandy** [comment]
Fixing the select component might involve manipulating the [React-Select](https://react-select.com/home) library

**Comment by JoaoSilvaGrafana** [comment]
Opened a PR to fix the position of the hidden checkbox behind the "Switch" component: https://github.com/grafana/grafana/pull/93100

Regarding the `Select`, as abhiShandy mentioned, it would require modifying the react-select styles. However, we are currently building a new select component and I just tested this in Tobias' [branch](https://github.com/grafana/grafana/pull/92826) and it works fine!

New select:
![Image](https://github.com/user-attachments/assets/08e78ac1-5e02-41d5-9a2d-d1d77a97fbee)

Old select:
![Image](https://github.com/user-attachments/assets/6ee0eb90-1a5c-47ee-a830-a2c57bac1bb2)

So I think we can mark the `Select` as done since it is not worth the effort of playing around with react-select styles when it will be fixed in the new select.

**Comment by JoaoSilvaGrafana** [comment]
Closing as the new select will fix the Select task
