### ISSUE TITLE
[Bug]Scroll hover info popup when there are too many legends

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#7353]
Please include this information:
- What Grafana version are you using?
v4.0.2
- What datasource are you using?
influxdb
- What OS are you running grafana on?
centOS 6

When there are too many legends, part of the hover info popup will be out of screen, please add scroll bar to the hover info popup. To scroll on the popup, you can click the graph to freeze the popup and then scroll up and down on it, then you can click the graph to unfreeze the popup, another option is to make it scroll automatically when hovering.

**Comment by llevar** [comment]
+1

**Comment by bergerx** [comment]
This should be a bug rather than a feature request, we have been doing dirty tricks to work around this like adding dummy rows on top, really annoying, here is an example screenshot:
![image](https://user-images.githubusercontent.com/45531/28205417-9bdebd78-688a-11e7-8aaa-d0c31a370ee6.png)

**Comment by gaoagong** [comment]
I am seeing something similar.

![screen shot 2018-08-14 at 9 02 13 am](https://user-images.githubusercontent.com/1412911/44103362-e02341ae-9fa0-11e8-8c16-5abe459166a6.png)

**Comment by deejamin** [comment]
+1 

We just hit this same issue today with grafana. A lot of legends with no scrolling within the hover popup.

Grafana v6.1.0 (03346b6)

**Comment by ahinh43** [comment]
+1

Also seeing the same issue on 6.1.0

**Comment by tangxinfa** [comment]
+1

We have 100+ api in a panel

**Comment by nocturne-mit** [comment]
+1

This bug is made worse by the fact that Grafana is not very clever about placement of the hover-info popups.

If a graph is too close to the top of a page, no amount of vertical scrolling helps with this bug. However, if I put other graphs above the "problem" graph I can then scroll my page vertically so the problem graph is at the very bottom of the page, at which point the graph-inspector is fully visible.

It would be very helpful if the graph-inspector placement algorithm prevented it from spilling off the top of my visible browser page when possible.

**Comment by rualark** [comment]
+1

will this be fixed?

**Comment by mcwienczek** [comment]
+1 same here with grafana 7.1.3

**Comment by giulioco** [comment]
+1 any updates on this?
