### ISSUE TITLE
i18n: Mark up `HelpModal` for translations

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#73614]
help modal is accessed by pressing `h`:
![image](https://github.com/grafana/grafana/assets/20999846/b0cb8e0a-7cbd-42a0-9a9d-04b19159a13d)

follow instructions [here](https://github.com/grafana/grafana/blob/main/contribute/internationalization.md#how-to-add-a-new-translation-phrase). can verify translation strings have been marked up correctly by using the development-only pseudo locale: 
![image](https://github.com/grafana/grafana/assets/20999846/30890cfd-89bc-4d8f-8c47-daa8a92f5727)

checklist:
- [ ] modal title
- [ ] close tooltip
- [ ] shortcut category titles
- [ ] shortcut descriptions

**Comment by Dennnnny** [comment]
hello, I would like to contribute to this one.
and I have a question in Modal title part: 

so, Modal.tsx in grafana-ui, title might be string or JSX
```js
  {typeof title === 'string' && <DefaultModalHeader {...props} title={title} id={titleProps.id} />}
  {
    // FIXME: custom title components won't get an accessible title.
    // Do we really want to support them or shall we just limit this ModalTabsHeader?
    typeof title !== 'string' && title
  }
  
  // so I'm thinking I would do changes like below: 
  
  {typeof title === 'string' && <DefaultModalHeader {...props} title={  t ( 'modal.title' , title )  } id={titleProps.id} />}
  {
    // FIXME: custom title components won't get an accessible title.
    // Do we really want to support them or shall we just limit this ModalTabsHeader?
    typeof title !== 'string' &&  <Trans i18key='modal.title'> {title} </Trans>
  }
```

I asking because I know that it's better to only put string inside <Trans>,
but in object scenario, I'm not sure what's the better way 
any suggestion on this object title or any advices ? 

thanks

**Comment by Dennnnny** [comment]
sorry for another one question here:

in HelpModal
I did this change 
```js
<th className={styles.shortcutTableCategoryHeader} colSpan={2}>
  {t('help-modal.shortcut.category', category)}
</th>
...
<td className={styles.shortcutTableDescription}>
  {t('help-modal.shortcut.description', shortcut.description)}
</td>
``` 

but when I try to build English grafana.json default value
I'm not sure what to put in default value ?? 

```js
  // in English grafana.json: 
  ...
  "help-modal": {
    "title": "Shortcuts",
    "shortcut": {
      "category": "",
      "description": ""
    }
  },
  ...
```

thanks

**Comment by joshhunt** [comment]
@Dennnnny When translating the UI, calls to `t("greeting", "Hello world")` should be for a single, static, translatable phrase. `t('help-modal.shortcut.category', category)` is incorrect because then what would be the one French translation for `help-modal.shortcut.category`?

Instead, for this example we would want to mark up the description inside the [`getShortcuts()`](https://github.com/grafana/grafana/blob/5ec88b1fb65d8ff07acf483f12595c3b02c0e136/public/app/core/components/help/HelpModal.tsx/#L8) function like:

```ts
const getShortcuts = (modKey: string) => {
  return {
    Global: [
      { keys: ['g', 'h'], description: t('help-modal.shortcut-description.go-to-home-dashboard', 'Go to Home Dashboard') },
      { keys: ['g', 'd'], description: t('help-modal.shortcut-descriptio.go-to-dashboards', 'Go to Dashboards') },
```

However, this still leaves the category titles (such as "Global" untranslated. We could use computed propery names (`{[t("blah", "blah)]: [...]}`), but it doesn't feel right to translate object keys... Instead, it might be better to change the shape of the shortcuts object to something like

```ts
const getShortcuts = (modKey: string) => {
  return [
    {
      category: t('shortcuts-modal.category.global', 'Global'),
      shortcuts: [
        { keys: ['g', 'h'], description: t('shortcuts-modal.description.go-to-home-dashboard', 'Go to Home Dashboard'), },
        { keys: ['g', 'd'], description: t('shortcuts-modal.description.go-to-dashboards', 'Go to Dashboards') },
        ...
      ],
    },
    {
      category: t('help-modal.shortcut-category.dashboard', 'Dashboard'),
      shortcuts: [ ... ]
    }
  ];
```

And then update the render function slightly to adjust for the new structure
