### ISSUE TITLE
[Feature request] Ability to add filter tags in search box without clicking

### ISSUE THREAD

**Issue by filippog** [grafana/grafana#7362]
Please include this information:
- What Grafana version are you using?
4.0.2

- What did you do?
Typed `tag:<tag>` while searching for dashboards

- What was the expected result?
The tag `<tag>` added to the current search/filter

It'd be nice to be able to add tags to the current search without clicking, a-la gmail where you can search e.g. for `is:starred`.

In other words extend the search to more than dashboard names, what do you think?

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
