### ISSUE TITLE
Missing release notes for grafana 10.1.0

### ISSUE THREAD

**Issue by wargamez** [grafana/grafana#73711]
### What happened?

In the last year or more you seem to have a tendency to release new versions of grafana (in apt repo atleast) without having the release notes / changelogs ready. This is really unfortunate, and I really hope this can change.

### What did you expect to happen?

Be able to read what has been changed when a new version is avaiable.

### Did this work before?

yes, but quite some time ago you always had the docs ready.

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 10.1.0
OS: Ubuntu
Browser:

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by zerok** [comment]
Hi 🙂  This is mostly a timing issue. Right now the changelog-generation is triggered manually after the release pipeline has completed in order to allow for some manual checks before "announcing" the release.

As these steps sometimes take a bit longer than we'd like them to, there may be a delay between the packages appearing on the deb/rpm indexes and the changelog being updated. Sorry for the inconvenience there but at least for 10.1.0 the changelog has been updated 45 minutes after you opened this issue 🎉

That being said, we are continuously improving especially these last steps of the release process and are trying to integrate more and more into the fully automated part.
