### ISSUE TITLE
Design the error message when users need to configure the Plugin

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#74285]
**Goal**

Give the user the possibility to configure the plugin correctly.

**Tasks**

- [x] Display a warning and a link to documentation

**Comment by natydej** [comment]
Given the scenario where the user has installed the LLM plugin but is not configured correctly, we notify them with an inline banner above the **Re-generation buttons disabled** that they need to that page and configure the plugin. After click on the "settings" link will be open the LLM page with the configuration, where also will be a link to the[ documentation](https://grafana.com/docs/grafana-cloud/alerting-and-irm/incident/configure/integrations/configure-open-ai/) at Grafana.

Design below:

<img width="539" alt="error-plugin" src="https://github.com/grafana/grafana/assets/51436795/3847a8e1-1ff1-40fd-8ae0-3cff74e02688">


[Figma link](https://www.figma.com/file/yBuMIJDWHJbsfujZK2raRo/DashGPT?type=design&node-id=603-285&mode=design
)

**Comment by ivanortegaalba** [comment]
The team agreed on the design and they started with the implementation 💪

**Comment by ivanortegaalba** [comment]
The problem I see with this design is:
* Very disruptive for a first-time user. They will see a big error in the screen when creating the first panel. This will create uncertainty and a sense of urgency to fix something that won't work. Actually, they could even think the changes won't be effective on the panel, because of this error.
* The component is not reusable across different UIs. In this case is part of the form, but in some other cases, it might not. 

For the "non-configured" use case, I'd consider just disabling the button. The similar pattern we use for the user that doesn't have permission to edit or create. Blocked button with a tooltip indicating the error.

Since we're creating a 100% reusable component across different UIs, if you don't mind, we will have a disabled button with a tooltip with the same text. And once you're back, we can reconsider this option. It will save us a lot of time going for the tooltip instead of the inline banner.
