### ISSUE TITLE
[Feature request] Add a vagrant file to setup the build/development environment quickly and temporarily

### ISSUE THREAD

**Issue by inbilla** [grafana/grafana#7438]
I would like to see a Vagrantfile added to the grafana repository to setup and configure a development environment.

My machines generally run Windows environments, but I regularly interact with linux environments through shells and VM's. Grafana is a great product that I'd like to help contribute to, but the build environment is foreign to me. By offering a vagrant file to setup an environment easily, it lowers the bar to people contributing, whilst also potentially codifying the current build environment. 
It also allows casual contribution of bugfixes and improvements as a potential contributorcan temporarily setup the environment quickly and then destroy it without tainting their normal environment.

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments so we are closing it. We are trying to limit open GitHub issues in order to better track planned work and features.

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Still a big Thank You to you for taking the time to create this issue and the linked PR is hopefully of use to someone building Grafana with vagrant.
