### ISSUE TITLE
Loki: label_values() - Use labels API instead of series API

### ISSUE THREAD

**Issue by garrettlish** [grafana/grafana#74432]
**Why is this needed**:

Make loki label_values more efficient.

**What would you like to be added**:

The original loki label values API - https://grafana.com/docs/loki/latest/api/#list-label-values-within-a-range-of-time doesn't support an optional label matcher, causing problems like https://github.com/grafana/grafana/issues/25205, as mentioned, such as the inability to filter by label matcher. As a result, the Loki datasource switches to the series API. However, now the optional label matcher for the label values API - https://github.com/grafana/loki/pull/8824 is ready. It might be better to switch back to the label values API since the series API returns label combinations rather than specific label values, which is more efficient.

**Comment by vishiy** [comment]
this also breaks a lot of variables in many dashboards now. ex;- variable queries like below --

label_values(kube_pod_container_info * on(pod) group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{workload_type="deployment"}, container)

**Comment by yuri-rs** [comment]
I think the best way would be to have an option in Loki datasource to select what API to use, defaulted to series API.
It will be similar to Prometheus approach with selection of "Prometheus type" and "version" that control `hasLabelsMatchAPISupport()` variable, but O would prefer explicit selector of API instead of "Prometheus type" and "version".
thoughts?

**Comment by dvidben** [comment]
Series API also causes some of the label values to be missed for some scenarios- not yet clear why, but my assumption is that the query scan might be limited by the maxLines in the datasource configuratoin.
Opened https://github.com/grafana/grafana/issues/83941 since this is not just an improvement, but a fix for an actual bug
