### ISSUE TITLE
Feature: Support for dashboard variables

### ISSUE THREAD

**Issue by baldm0mma** [grafana/grafana#74478]
[Product board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/16818823/detail)
[Zendesk Ticket](https://grafana.zendesk.com/agent/tickets/70828)
[Zendesk Ticket](https://grafana.zendesk.com/agent/tickets/84785)
[Zendesk Ticket](https://grafana.zendesk.com/agent/tickets/91575)
[Design doc](https://docs.google.com/document/d/1grz0EavSTUrgxIX3FWZc-Dhwj54pd-p9wh1AoxMAYzU)

**Comment by baldm0mma** [comment]
OSS issue here: https://github.com/grafana/grafana/issues/25469

**Comment by samjewell** [comment]
Should we close https://github.com/grafana/grafana/issues/25469 too? It's still getting traffic - two comments only yesterday. @oscarkilhed

**Comment by oscarkilhed** [comment]
@samjewell 
> Should we close #25469 too? It's still getting traffic - two comments only yesterday. @oscarkilhed

The original ask in that issue is to use repeat variables, transformations and the dashboard datasource to only query once. Unfortunately when using the dashboard datasource the variables are scoped by the original panel. So before we can address that issue in the dashboard datasource I’m hesitant to close that issue, even though I think a lot of the use cases brought up in it, by other users, are solved.
