### ISSUE TITLE
Feature: Pass result of 'add field' from calculation transformation to future transformations

### ISSUE THREAD

**Issue by baldm0mma** [grafana/grafana#74486]
[Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/20274422/detail)

**Comment by oscarkilhed** [comment]
I tried to investigate this, but the added field already seemed to be passed to future transformations. Then I found this new issue #76090

It seems the added field does not get passed if a variable is used.

**Comment by mdvictor** [comment]
Seems like the problem stems from not having the `ctx` sent in all apply tranasform calls. This means that even though panel shows the correct dataframe, with the newly created field, the editor doesn't have it because in there the transformation fails and returns undefined (because the operators are not interpolated and thus undefined), so any other transformations downstream don't see it.

**Comment by oscarkilhed** [comment]
@mdvictor Nice catch!

**Comment by mdvictor** [comment]
fixed by https://github.com/grafana/grafana/pull/76317
