### ISSUE TITLE
Cloudwatch: unexpected "u" error when creating new datasource

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#74703]
Hi there, noticed the below when trying to create a new datasource

![Image](https://github.com/grafana/grafana/assets/19860021/f310ec12-c6c3-4ce2-b2e0-9ac91b4ff49d)

Running  `Grafana v10.2.0-60477 (6f785f72)`

To reproduce:

connections > connections/datasources/cloudwatch/ > Add new datasource

**Comment by fridgepoet** [comment]
Thanks for reporting @sympatheticmoose! I believe Sarah is working on improving this experience in this PR which is in progress right now. https://github.com/grafana/grafana/issues/73294

**Comment by fridgepoet** [comment]
Hiya @sympatheticmoose love the github username!
(Sorry I linked the issue and not the PR here https://github.com/grafana/grafana/pull/74420)
Your issue should be fixed by https://github.com/grafana/grafana/pull/74420; it's been merged and set for Grafana 10.2.
Going to close this issue, thanks so much for reporting it!
