### ISSUE TITLE
Grafana Server: Running grafana server makes VM unresponsive 

### ISSUE THREAD

**Issue by stankovic-marko** [grafana/grafana#74748]
### What happened?

I needed to make a simple dashboard for Prometheus metrics with Grafana. I spawned a new ubuntu VM though vmware ESXi, installed Grafana with apt and started a grafana-server service. The service started as expected and I was able to log into a Grafana web app. After about 1 minute, a web app became unresponsive. Then I tried to see if a grafana-server is still running on VM, but VM itself became unresponsive, so i had to restart it. The problem persisted in multiple attempts. I also checked server logs and they did not tell me anything that could tell me what was the problem.

### What did you expect to happen?

I expected to run grafana-server and use a web app to build dashboard.

### Did this work before?

I have not tested running grafana-server installed with apt before.

### How do we reproduce it?

1. Spawn new ubuntu VM
2. Install grafana `apt-get install grafana`
3. `systemctl start grafana-server`
4. Wait 1 minute
5. VM becomes unresponsive

### Environment (with versions)?

Grafana: 10.1.11 OSS
OS: Ubuntu 22.04.2 LTS
VM Specs: 10GB RAM, 8 cores, 30GB storage

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by mellieA** [comment]
@stankovic-marko the community might have some ideas for you at community.grafana.com. We use github for bugs and feature requests. 

Were you able to collect any information that points to a problem with the grafana-server service? Your VM size looks good, but I'm curious if there could be an issue of overprovisioning VMs so that it's not actually getting all of the resources that you've allocated. Grafana is a fairly small service (it can run on raspberry pi)! 

I suggest including any resource utilization from outside of the VM if you're able to see that in vCenter or perhaps try starting it with the standalone binaries instead of the service to see if you can catch what's going on.
