### ISSUE TITLE
alerting: Copy rule URL doesn't work

### ISSUE THREAD

**Issue by gouthamve** [grafana/grafana#74807]
### What happened?

https://github.com/grafana/grafana/assets/7354143/99d9c97e-cb21-4081-896a-4ffcd1fbc285

The URL that was copied on clicking the button (404): https://XXXXXX.grafana-dev.net/alerting/grafanacloud-otlpcortexdev01-prom/%5Bsuccess-rate%5D%20adservice%20%23%20oteldemo.AdService%2FGetAds/find

The URL the I manually copied from the browser window (works): https://XXXXXX.grafana-dev.net/alerting/grafanacloud-otlpcortexdev01-prom/cri%24grafanacloud-otlpcortexdev01-prom%24app-observability%24otel-demo---adservice%24%5Bsuccess-rate%5D%20adservice%20%23%20oteldemo.AdService%1FGetAds%241592852012/view?returnTo=%2Falerting%2Flist%3Fsearch%3Ddatasource%3Agrafanacloud-otlpcortexdev01-prom

### What did you expect to happen?

Copy Rule URL shouldn't send me to a 404 page

### Did this work before?

No idea

### How do we reproduce it?

Create an Alert with the name `[success-rate] adservice # oteldemo.AdService/GetAds`

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Grafana v10.2.0-60625 (3bae1c56)
OS: MacOS
Browser: Arc Browser

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Prometheus

**Comment by gillesdemey** [comment]
Does this occur on your local environment or only in Hosted Grafana? If the latter (which I suspect, because I wasn't able to repro locally but I might be missing some steps) it's very likely https://github.com/grafana/hosted-grafana/issues/1667 and https://github.com/grafana/grafana/issues/42947 (which in this case also seems to affect rule names)
