### ISSUE TITLE
Bug: Core plugins not listed when listing "All" plugins

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#74816]
In the catalog view, when selecting "All", core plugins are omitted:

![image](https://github.com/grafana/grafana/assets/4025665/572e54b5-c96a-4f59-aa6e-eb5079970b60)
![Screenshot from 2023-09-13 12-41-04](https://github.com/grafana/grafana/assets/4025665/458e9b22-9e2a-4666-87f2-8abfd2e83d03)

Interestingly, installed plugins (which are not in the catalog either) are shown.

**Comment by tolzhabayev** [comment]
@mckn please take a look, what the reason was for that.

**Comment by mckn** [comment]
@leventebalogh @wbrowne do you remember?

**Comment by leventebalogh** [comment]
Based on [this old Slack discussion](https://raintank-corp.slack.com/archives/C024NL6AEJH/p1624277231047200?thread_ts=1624261175.045100&cid=C024NL6AEJH) (Will & Marcus), maybe it was because we only wanted to list plugins that could be managed / changed (core plugins couldn't be installed or uninstalled)? 

In case if that was the root cause, then probably we could list them, and just don't display the install controls?
