### ISSUE TITLE
Cloudwatch: Return query with super.query

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#74872]
Fixes: https://github.com/grafana/support-escalations/issues/7426

We seem to have some trouble with public dashboards and cloudwatch right now and the [latest theory](https://raintank-corp.slack.com/archives/C01LVB0CYTW/p1694608422896999) is that is because our query method does not return super.query ([see working example in athena](https://github.com/grafana/athena-datasource/blob/main/src/datasource.ts#L110))

Would be good to:
- verify that returning super.query fixes the issue
- if that indeed works, let's make sure that this sort of thing is documented well both in our plugin but also in the [create-plugin](https://github.com/grafana/plugin-tools/blob/main/packages/create-plugin/templates/backend/src/datasource.ts) package (or somewhere else) as it's easy to miss that this is a necessary step.

**Comment by juanicabanas** [comment]
Some things I've investigated today.
Doing a little [audit](https://github.com/grafana/grafana/issues/62374) for datasource plugins, I checked cloudwatch has:

- logs query runner
- metrics query runner
- annotation query runner

I'm not sure if all those cases would be executed in a public dashboard context since, for example for the annotations, we instantiate a `PublicAnnotationsDataSource` for calling the public endpoint ([see code](https://github.com/grafana/grafana/blob/main/public/app/features/query/state/DashboardQueryRunner/AnnotationsWorker.ts#L52)).

However:
- For the `logs query runner`, I see you pass a `header` for the request: `"X-Cache-Skip"`
- Both `logs query runner` and `metrics query runner` pass the body with a `queries` attribute.

I think, from a high-level review of the code, if `super.query` must be called, it has to be modified since:
- It doesn't accept any `header` (and also creates a list of them)
- It creates a `body` with a `query` attribute, **BUT**, based on`targets` attribute that is passed as an attribute in the request function parameter `query(request: DataQueryRequest<TQuery>).`
