### ISSUE TITLE
Panel Filtering in Dashboard

### ISSUE THREAD

**Issue by s0lesurviv0r** [grafana/grafana#74891]
Hi there. We moving over dashboards from an in-house legacy system to our Grafana instance. Something that's a bit unique about our current system is that users have created very large dashboards, with sometimes thousands of panels. This is possible to navigate because our in-house system provides a panel filter where a user can specify filtering regex and only display only those panel's whose title matches said regex. Finally, the regex is included in the URL so that a filtered view can be shared.

We realize this is an impractical paradigm and the obvious solution would be to force users to sub-divide or reorganize dashboards prior to moving to Grafana. However, due to the constraints of our migration to Grafana the only option is to do an initial copy-paste, followed by a dashboard refactor at our user's leisure.

I intend to submit a PR to add this panel regex filter feature and place it under a feature flag. However, I'd still like to ask for feedback to ensure the implementation is elegant and architecturally sound. With that I'd like to ask:

* Would it be more strategic to place this functionality into a new variable type? This way the [URL support](https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/create-dashboard-url-variables/) would come for free
* If the variable route is not recommended, can you recommend a place to start? (e.g. New component, wiring to URL component, etc). I want to make sure I structure this neatly and not just duct-tape the feature in
* Could this feature be made more generic so that others can benefit? Our use case requires regex filtering but maybe we can make different types available (e.g. prefix filtering)

Thanks again and please forgive my shallow understanding of Grafana's internals.

**Why is this needed**:
- We require legacy dashboards to be moved as is
- These dashboards sometimes have thousands of panels
- We need to provide our users with a 1:1 panel filtering experience

**What would you like to be added**:
- A way to filter panels in a dashboard based on user inputed regex
- The regex should be encoded in the URL so that the state of the dashboard can be shared

**Who is this feature for?**
- For a large migration away from a legacy in-house solution to Grafana

**Comment by torkelo** [comment]
This will not work for the current dashboard architecture (and grid layout) but will be very easy in the new scenes-based dashboard architecture:
https://github.com/grafana/grafana/blob/main/public/app/features/dashboard-scene/scene/DashboardScene.tsx 

All new feature work should be directed to this, as the old (current) dashboard page and architecture is "frozen" (ie no new development). 

The new dashboard engine supports SceneFlexLayout that makes filtering what panels to show super easy, but we have yet to add support for this in the persisted dashboard schema model (only runtime support)

**Comment by torkelo** [comment]
To try the new scene based dashboard enable the "scenes" feature flag. This will add a "view as scene" button where you can open any dashboard in the new architecture. There are still a lot of features missing (mainly editing features), you can track our progress in this epic: https://github.com/grafana/grafana/issues/73874

![image](https://github.com/grafana/grafana/assets/10999/0761f164-4bae-4531-96d7-4a10b5dc6d32)

**Comment by natellium** [comment]
Hey @s0lesurviv0r, thanks for creating this. Sorry if the comments above were a bit confusing. We'd missed some internal comms for everyone to be aware of the proposal. It is in our TODO list and we'll look into your suggestions and questions next week!

**Comment by s0lesurviv0r** [comment]
Thanks for the suggestion @torkelo. We've done some experimenting with Scenes and our original idea was to build this feature on top of Scenes. We upgraded to Grafana 10 to have Scenes support. However, as you mentioned there's no support for editing dashboards through Scenes.

I have enabled the feature flag so we can track this migration as new releases get shipped. Thanks for sharing that with us. We look forward to the future when dashboards will be built on top of Scenes.

@natellium Thanks for coming back to me. Yes we've had some out-of-band communications and I think we're aligned on Scenes not being able to meet our needs in time. We'll take whatever suggestions we can on how to implement this. If you feel https://github.com/grafana/grafana/issues/73874 can be finished relatively quickly we can pivot back to that.

**Comment by dprokop** [comment]
@s0lesurviv0r - me and @torkelo spent some time thinking about how to get this feature implemented with minimal effort given we don't want to generalize the solution at the moment. As said before, with Scenes based dashboards implementing such filtering will be trivial.

What we can do to get this working (and  URL sync for "free") is to utilize already existing text variable. The idea is to:

1. Create a text variable with a reserved name, i.e. `systemPanelFilterVar`
2. Subscribe to`VariablesChanged` event in the `DashboardGrid` component, and filter the panels accordingly for rendering. It's important to skip rebuiding the layout for react-grid-layout as then the panels positions will be updated and will brake a dashboard when saved.
3. UrlSync. This will be provided by the variables system, but the `DashboardGrid` needs to read from the url on initialisation to set the filter correctly.
4. I think we should disable panels dragging and resizing when filter is present, as otherwise the original grid can be messed up with such an action.

I did a super rough and quick sketch of this solution. You can see it on this branch and it should give you an idea of what we are thinkging about: https://github.com/grafana/grafana/tree/filtering-panels

**Comment by s0lesurviv0r** [comment]
Thanks for getting back to me @dprokop. From my understanding of Grafana internals and the constraints we both have this seems like a very reasonable solution. It may seem rough but the branch you've provided has almost everything we need at this point. There are just two points:

1. We'd like this filter to support regex
2. Can we have the filtered panels fold in together and not have gaps between them. See screenshot below:

<img width="1494" alt="Screenshot 2023-09-25 at 12 48 28" src="https://github.com/grafana/grafana/assets/25852638/8763facf-592a-49ab-aa1b-4a3b03f42c6c">

**Comment by dprokop** [comment]
@s0lesurviv0r

Regarding `We'd like this filter to support regex` - yest, this is possible, you just need to use regex match rather than `indexOf` as in my POC.

Regarding `Can we have the filtered panels fold in together and not have gaps between them` - maybe- you would have to recalculate all grid elements' positions for that, as Grafana panels have position defined. This is going to be a bit trickier, given that panels can have different dimensions. A possible approach would be to use two layout column for filtered view, so that it would ignore the panel dimensions all together, and just apply 50% and some fixed height to all filtered panels.

**Comment by s0lesurviv0r** [comment]
I appreciate the help @dprokop. Is it OK if I take build off your POC and submit a PR? Or would you prefer to do this?

**Comment by dprokop** [comment]
@s0lesurviv0r - please feel free to start off my POC branch :)

**Comment by s0lesurviv0r** [comment]
Hi @dprokop. I've submitted a draft based on your POC. I'll still give it another round of manual testing before I take it out of draft state. I was curious, should we document this feature? And since this feature is very customer specific, would you like additional code comments? Any other feedback to get this in the main branch would be greatly appreciated.
