### ISSUE TITLE
Teams: Cannot add team to dashboard/folder permission after deleting and recreating it with the same ID

### ISSUE THREAD

**Issue by Bujupah** [grafana/grafana#74900]
### What happened?

It appears that the team's re-addition with the same ID after deletion is not successfully granted as a permission to dashboards/folders, despite receiving a success message.

### What did you expect to happen?

A team that once got deleted from Grafana and recreated with the same team id can be assigned as a permission to dashboards/folders.

### Did this work before?

No

### How do we reproduce it?

1. create/sync a team
2. add team as permission in dashboard/folder
3. delete team
4. re-add team with same id
5. add team to any dashboard
6. success message will appear but team will not get added

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 9.5.4 / 10.2.0
OS: Windows/Linux
Browser: N/A

### Grafana platform?

Other

### Datasource(s)?

N/A

**Comment by Bujupah** [comment]
We have a case were the team's ID is fixed and coming from another service that syncs to Grafana. 

Our other service also have teams, so whenever we give reporting permission to a team in our other service, it created a team in Grafana, if we remove reporting permission, the team gets deleted from grafana.

Since the team is getting synced fully even the ID will be same in this case then this issue appears and It gives duplicated key in role table cause of the constraint causing the creation of a new relation record in team_role to fail.

**Comment by mellieA** [comment]
@Bujupah thank you for opening this and proposing a fix. I'll ask the team responsible for this part of Grafana to take a look and review the associated PR

**Comment by gamab** [comment]
Hey, great job spotting this and suggesting your fix :100: 

Out of curiosity what DB are you using, the team's ID is meant to auto-increment, how do you manage to recreate it with the same ID?

As you uncovered, when the team is deleted, we delete its assignments but not its associated managed role. Therefore upon re-creation, we correctly modify the managed role but since it is not assigned anymore, the team does not get permissions.

It would be great if we could do the fix in the same form as what we do for users' permissions deletion. We should probably add a `DeleteTeamPermissions` function to the accesscontrol `Service` interface similar to the [`DeleteUserPermissions` function](https://github.com/grafana/grafana/blob/main/pkg/services/accesscontrol/accesscontrol.go#L33-L35) (that ends up calling [this store function](https://github.com/grafana/grafana/blob/main/pkg/services/accesscontrol/database/database.go#L172-L236)).
Finally we would also need a migration to clean up managed permissions for teams that were removed and for which we did not properly clean up permissions.

Do you want us to take over the fix? :slightly_smiling_face:

**Comment by Bujupah** [comment]
@gamab, I appreciate your quick response and willingness to help out! I'll continue working on the fix for now, but if I run into any roadblocks or need assistance, I'll definitely reach out.

But one doubt, do you want to refactor the code ? or you're saying delete team permission also we need to add?

Can you please check this line, I think it is removing team permissions

https://github.com/grafana/grafana/blob/c999979bc5f11845a1735a5978361200aa55bdcd/pkg/services/team/teamimpl/store.go#L151-L153

**Comment by tgip-work** [comment]
Hi, is there any update on solving this issue?

**Comment by gamab** [comment]
Hey :wave: 
Writing to let you know that I fixed this issue with:  #83442
Should be available in v11.0.0 :slightly_smiling_face:
