### ISSUE TITLE
Alert list twitching when the list is empty

### ISSUE THREAD

**Issue by electrofloat** [grafana/grafana#74971]
### What happened?

See:

https://github.com/grafana/grafana/assets/477252/81bf8468-353e-4e4e-b9e3-f8cc233132c6

### What did you expect to happen?

To not do that.

### Did this work before?

Before what?

### How do we reproduce it?

1. Add an empty alert list to a dashboard
2. Set auto refresh rate to a low value
3. Observe

### Environment (with versions)?

Grafana: Grafana v10.1.1 (0cfa76b22d)
OS: Docker
Browser: Firefox (Rulez!)

### Grafana platform?

Docker

**Comment by usmangt** [comment]
Hi @electrofloat,

Thanks for opening this issue.

Based on your steps of reproduction, I was also able to reproduce it on my test machine.

I will forward this issue to our Engineers so that they can have a look and analyse it.

Here is the HAR file while using 
[network-har.zip](https://github.com/grafana/grafana/files/12658110/network-har.zip)

- Grafana version 10.1.1
- Chrome stable version Version 117.0.5938.62 (Official Build) (64-bit)
- OS Docker
-

**Comment by usmangt** [comment]
Assigning it to the Alerting team as the panel is specific to it. Incase it is not correctly assigned then kindly let me know (will assign to Dashboard team).
