### ISSUE TITLE
[Feature request] First or last point shall be drawn even if group by is out of view

### ISSUE THREAD

**Issue by makareth** [grafana/grafana#7498]
Grafana 4.0.2
Datasource: InfluxDb 0.13
Ubuntu 16.04

I currently use InfluxDB to graph two timeseries. One of them holds my actual observations, the other one is a 'prediction' timeserie. As a consequence, the 'prediction' timeserie holds datapoints timestamped in the future.
Although the observations timeseries has 1 datapoint evey single minute, the prediction one only has one datapoint every 6 hours (basically at 3AM, 9AM, 3PM and 9PM UTC every single day).

What I see is that when setting the view to display the last 24 hours, and use lines to connect the datapoints, then the line is empty for around 6 hours. This emptiness can alter either the leftmost part of the graph, either the rightmost part.

Right now, it is 16:03Z+01:00 and as can be seen in the screen capture, between 4PM yesterday and 10PM yesterday, there is nothing plotted. I expected a line to go from 4pm yestarday to 10pm yesterday (the datapoint for yesterday 4pm exists [even though the point itself is out of view] so the line could be drawn).

Looks like the query should include one more point on the left, and one more point on the right to handle such cases where the actual datapoint is out of the period but we still want to display a line between the "virtual" point and the very first point of the graph.

![image](https://cloud.githubusercontent.com/assets/2042576/22745677/aba57d0c-ee21-11e6-9c93-c00b643deb97.png)

**Comment by gabor** [comment]
i tested with the current version of grafana, and the generated query will also include the start-point and end-point (it does a `WHERE time >= ... and time <= ...`, so if your time-range is chosen correctly it should contain also data-points that are at the "border". for points that are outside the chosen time-range we cannot do anything, because they are simply not part of the data returned by the query. (and if we think about automatically extending the area a little, we do not know how far the next data-point is).

i hope this explains the situation. if i misunderstood something, feel free to reply, and we can continue the discussion.
