### ISSUE TITLE
Search: Listing dashboard with no tags

### ISSUE THREAD

**Issue by kamaradclimber** [grafana/grafana#751]
It is currently possible to list existing dashboards tags.
Many of our users don't add tags to their dashboard and because of #750 have much trouble to find their dashboards.

How can they find the list of dashboard without tags ?

**Comment by torkelo** [comment]
We are trying use open GitHub issues as a way to track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long without any much interest in the feature or anyone showing interest in implementing it. 

A closed issue can still attract up votes and act as a ticket to track feature demand/interest.
