### ISSUE TITLE
Traffic light plugins not showing expected behaviour

### ISSUE THREAD

**Issue by vipingragit** [grafana/grafana#75222]
### What happened?

When attempting to use traffic light plugin with promql query in Grafana, the threshold value is not showing the expected behaviour. The color is not changing on the basis of values.

### What did you expect to happen?

The color of the light should changed on the basis of threeshold values. For example, red color should be visible in traffic light plugins for red threshold and same for other color.

### Did this work before?

No

### How do we reproduce it?

1. login to grafana and using the below sample promql query:

    (kube_deployment_status_replicas_available{namespace="test"}/kube_deployment_spec_replicas{namespace="test"})*100

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

Kubernetes

**Comment by usmangt** [comment]
Hi @vipingragit,

Thanks for opening this issue.

There are actually 2 Traffic Lights plugins:

https://grafana.com/grafana/plugins/snuids-trafficlights-panel/
https://grafana.com/grafana/plugins/smartmakers-trafficlight-panel/

As both are community-based plugin as described on the plugin page (that means, it is not maintained by us).

Therefore, the suggestion would be to report this by opening a new issue to their official GitHub page so that they can check it.


I hope this is helpful.
