### ISSUE TITLE
[Feature Request] Cloud watch Datasource - Using Regular expression in the dimension values or metric name

### ISSUE THREAD

**Issue by kamalvpm777** [grafana/grafana#7530]
[Feature request]Grafana with Cloud watch as a datasource- Using regex on dimension value

We have a requirements to pull the all the containers on the host , and query the CPU usage on each of container using a single query rather having a query for each container. In my case lets assume there are 3  container images called container-image1, container-image2, container-image3 within host ip-10.10.10.10, how do i pull all container using regular experssion on the dimension value as attached on the screenshot. Already within our custom AWS namespace tried the regular expression "container-image.*" but it doesn't seems to be working. Overall looking for guidance on applying regexp within the dimension values and metric name . 

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? CLOUDWATCH
- What OS are you running grafana on? Centos
- What did you do? Used regexpression ".*" on the dimension value and metric name
- What was the expected result? To bring all the container matching the regular expression
- What happened instead? It works when we hard code the container name, but using regexp it never pulls any metrics as shown in screenshot

**IMPORTANT** 
If it relates to *metric data viz*:

![image](https://cloud.githubusercontent.com/assets/25632887/22840597/307ae01e-ef9c-11e6-9d0a-997d2fe3f848.png)

Container Image with Regular expression to retrieve all the container within namespace

![image](https://cloud.githubusercontent.com/assets/25632887/22840978/a172867c-ef9d-11e6-8763-7b38639e6b95.png)

**Comment by torkelo** [comment]
You need to request this from Amazon, they need to implement it in their api

**Comment by kamalvpm777** [comment]
Thanks for your inputs. 

So wondering for this cloud watch dimension values there is no way to implement regex within the grafana query dimension values. we are in the process of building dashboards within few days for production stuff.Any other suggestions or guidances will be appreciated.

Here is what we are trying to do

Retrieve all the containers on the host and plot the CPU usage of each containers. All the containers have the same 10 dimension with different values for each

**Comment by mtanda** [comment]
I think you can utilize templating feature for your purpose.
If you didn't read the doc, please read https://github.com/grafana/grafana/blob/master/docs/sources/features/datasources/cloudwatch.md .

About this feature, there is difficulty to implement this feature appropriately.
To implement this, datasource need to get all dimension list for the metrics, due to ListMetrics limit the response size, the datasource need to call ListMetrics several times.
And then filter dimension pair which match regex, the result is very slow response.

Caching the ListMetrics result may improve the response, but not sure how long we can cache the response. (For dynamic environment, cache time should short, and static environment, cache time should long)

I think it is difficult to implement it without AWS API support regex.

**Comment by mweiden** [comment]
@mtanda @torkelo I think so long as the caching limitation is documented, this feature is worth the complications. Not having at least a wildcard for metric dimensions means that the dashboard has to be updated every time someone adds a dimension value (say creates a new Lambda function). This makes the maintenance of the dashboards pretty burdensome at scale and could cause users to miss important information when the systems generating the metrics change
