### ISSUE TITLE
[Bug] 413 Request Entity Too Large, on POST request

### ISSUE THREAD

**Issue by Alexul** [grafana/grafana#7532]
Grafana debian build 4.1.1-1484211277

curl -XPOST -H "Content-Type: application/json" -H "Authorization: Bearer <key>" http://<grafana>/api/dashboards/db -d @editor.json

Returns "413 Request Entity Too Large" on big jsons (~1mB).

It's not expected behaviour on POST requests, can i ask why that particular limit?

**Comment by Alexul** [comment]
my bad its nginx reverse proxy over grafana

**Comment by GokulSNarayan** [comment]
Can you please explain this error, because I am also getting this while trying to import a dashboard
x-special/nautilus-clipboard
copy
file:///home/gokul/Desktop/Screenshot%20from%202020-07-12%2021-08-06.png

**Comment by d-Rickyy-b** [comment]
Hi @GokulSNarayan, I get it, you probably don't need an answer after 2 years of waiting, but I figured others might come across this issue and find themselves in a similar situation, searching for an answer.

For me I was able to resolve the issue by changing my nginx (reverse proxy) configuration. By default nginx only allows for 1MB of body size. I tried creating a snapshot link and ran into the error, because the dashboard was larger than 1MB. I changed the nginx config to accept up to 10MB in the body.

```nginx
http {
    ...
    client_max_body_size 10M;
}  
```

Source: https://www.tecmint.com/limit-file-upload-size-in-nginx/
