### ISSUE TITLE
[Build] Install script for homebrew is broken

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#7553]
https://github.com/Homebrew/homebrew-core/pull/9918#issuecomment-279543313

**Comment by ilovezfs** [comment]
I've managed to fix the build, but still seeing a PhantomJS issue as described here: https://github.com/Homebrew/homebrew-core/pull/9918#issuecomment-279818019

**Comment by bergquist** [comment]
The karma test runner breaks the build. Not sure how to fix this without create a new release. Im kinda leaning towards skiping 4.1.2 for brew and stick to 4.1.1 in brew. Not sure its worth spending the time to fix this. 

I think we should make sure we can build grafana with brew in 4.2.0 before we release. 4.2.0

**Comment by ilovezfs** [comment]
>The karma test runner breaks the build. Not sure how to fix this without create a new release.

We can apply a patch if necessary. See for example https://github.com/Homebrew/homebrew-core/commit/195d0182de9ad5c61f0dc344b8cf5c77db726672

>Im kinda leaning towards skiping 4.1.2 for brew and stick to 4.1.1 in brew

Currently grafana 4.1.1 doesn't build either due to tslint errrors, and once those are overcome by pinning tslint to 4.3.1, it has what appear to be the same PhantomJS issues.

**Comment by daniellee** [comment]
Think this was fixed ages ago. The homebrew script works now.
