### ISSUE TITLE
Custom Plugins: Usage of SecretInput from @grafana/ui breaks ConfigEditor in Grafana versions <9.0

### ISSUE THREAD

**Issue by mullerpeter** [grafana/grafana#75758]
### What happened?

Boilerplate custom datasource backend plugin created via `@grafana/create-plugin` does not work on Grafana versions <9.0 (i.e. 8.5.22).

When trying to add a Datasource in the UI of the custom plugin type, the following error message is displayed in the browser:

```
An unexpected error happened
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

I pinpointed the error to the `SecretInput` component from @grafana/ui. When removing the SecretInput field from the ConfigEditor the error is gone.

### What did you expect to happen?

The `SecretInput` component should be usable in custom datasource plugins on Grafana versions <9.0. 

### Did this work before?

It works in Grafana Versions 9 & 10

### How do we reproduce it?

1. Use `@grafana/create-plugin` to create a new datasource backend plugin
2. Set `grafana_version: 8.5.22` in the docker compose file created
3. Start the docker container & try to add a new Datasource with the custom plugin in the Grafana UI

### Environment (with versions)?

Grafana: 8.5.22

### Grafana platform?

Docker

**Comment by leventebalogh** [comment]
Hey @mullerpeter 👋 

Thanks a lot for reaching out. Unfortunately with `@grafana/create-plugin` we are only supporting the current latest major version (currently Grafana 10). Although we are trying to do our best to be backwards compatible, it's sometimes unavoidable that we introduce breaking changes.

What you could try doing is to change the version of the `@grafana/` packages as well in the `package.json` to 8.5.22, so you might get some better error messages during compilation as well to see better what the issue is (`SecretInput` should be available 8.5 if I remember correctly).
