### ISSUE TITLE
CVE-2019-3826 - CVE-2021-21317

### ISSUE THREAD

**Issue by hessamalipour** [grafana/grafana#76043]
### What happened?

AWS Inspector shows, these vulnerabilities CVE-2019-3826 - CVE-2021-21317 

### What did you expect to happen?

I have reviewed pull requests and issue, and noticed CVE-2019-3826 - CVE-2021-21317, addressed here: https://github.com/grafana/grafana/issues/67452 and https://github.com/grafana/grafana/pull/43285, and both close and merged. Therefore, they should be in 10.1.x. However, AWS Inspector is showing them as vulnerabilities 

### Environment (with versions)?

Grafana version: v10.1.1
Data source type & version: N/A
OS Grafana is installed on: AWS ECS services
User OS & Browser: N/A
Grafana plugins: N/A
Others: N/a

### Grafana platform?

Docker

**Comment by usmangt** [comment]
Hi @hessamalipour,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by usmangt** [comment]
These seem to be false positives as listed here:

https://github.com/grafana/security-internal/wiki/Known-false-positive-vulnerability-detectons

**Comment by hessamalipour** [comment]
@usmangt  I am not able to open the link, showing 404, I see it is point to internal, possibly not visible to us, may have screenshot, or a link that visible to public, thank you

**Comment by simonc6372** [comment]
@hessamalipour sorry for the confusion on the 404 link 🙃 

Amazon's scanner is not detecting these as it's not identifying the version correctly due to the way go modules sometimes need to be versioned. 
 https://github.com/grafana/grafana/blob/bb9e66e6716e2bd0793dc0770ccf2f54e4343c8b/go.mod#L23C1-L26C85 

shows the renumbering and explains it. 

The overall problem is covered quite well in  https://github.com/prometheus/prometheus/issues/8852

**Comment by hessamalipour** [comment]
@simonc6372 Thanks a lot for more details
