### ISSUE TITLE
[Feat Req]: Protect against brute force (frequent) login attempts

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#7616]
Would be good to have some kind of protection against repeated login attempts.

**Comment by brittag** [comment]
Hi @torkelo! My team uses Grafana, and we recently received a related report from the public about this - that logins might be able to brute-forced on our Grafana instance because there is no rate-limiting for username/password auth.

We actually use the auth integration feature instead of using username/password auth, so there's nothing useful to brute-force in our own instance, but since this can affect other instances, I'm glad to see this in the bug tracker, and I'd encourage resolving this issue in a future release.

Thanks!

**Comment by jeandet** [comment]
@torkelo , hi, I've a naive question, could a malicious person exploit this mechanism to prevent users from login by locking their accounts? He won't get the control of anything but that would be quite annoying.

**Comment by marefr** [comment]
@jeandet yes that's a possibility with the current solution implemented

**Comment by jeandet** [comment]
@marefr , a per IP blocking rule wouldn't solve both brute force and "DOS" like attack?
I mean instead of locking an account for N minutes Grafana could block an account for a given IP for N minutes.
