### ISSUE TITLE
Provide documentation about querying the Loki datasource through Grafana

### ISSUE THREAD

**Issue by dark-penguin** [grafana/grafana#76202]
**What would you like to be added**:
I am trying to query a Loki datasource - not directly, but through Grafana, using this documentation:
https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#fetch-data-source-resources
But this is only about the "normal" metrics datasources - not Loki. For a Loki datasource, things are vastly different (examples provided here don't even work, and there is no explanation about other log-related options).
There is also the Loki API itself - the one used internally by Grafana. That one is even more different, and it's impossible to deduce anything from comparing the two.

**Why is this needed**:
In my case, the Loki installation is firewalled away in a cluster no one has access to, and the only access we have is through Grafana.

**Who is this feature for?**
The same people who use datasource querying (first link). Ops people who want to automate their monitoring without exposing Loki itself to the outside world.

**Comment by Elfo404** [comment]
Hello @dark-penguin, in order to query a datasource via grafana itself you can take a look at https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#query-a-data-source, as explained there you can send a POST to `/api/ds/query` with a valid query model - which is the internal representation of a query that grafana uses to then query the data source itself.
As for which options to include in your request, in the case of Loki you can have a look at https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/dataquery.gen.ts#L36. In general - given the vast number of datasources grafana supports - the best way to check what to include in your request may be checking the network tab in your browser, run a query via Explore with your desired options and copy the request payload from there:

![image](https://github.com/grafana/grafana/assets/1170767/89d478df-f64a-4acc-920c-8887592e37f4)

as of providing better documentation - what we do right now is having cue models for built-in datasources - in case of loki you can find it in https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/dataquery.cue which then is used to generate go and ts types.

Closing this issue, feel free to comment if there's anything i missed
