### ISSUE TITLE
Trace Panel: top graph cursor and vertical indicator not aligned after resizing

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#76273]
### What happened?

When resizing a pane in Explore (or in dashboad edit, but possibly other places as well) the vertical "red bar" in the trace graph stops being aligned with the cursor.

https://github.com/grafana/grafana/assets/1170767/2b57fb05-8ca0-41cd-8f30-4882ac4446e9

### What did you expect to happen?

for the cursor to always be aligned with vertical red bar.

### Did this work before?

no

### How do we reproduce it?

1. Open a trace
2. resize a pane
3. hover the trace's graph

### Environment (with versions)?

Grafana: main
OS: Mac
Browser: FF + chrome

### Grafana platform?

None

**Comment by neel1996** [comment]
Hi @Elfo404 

I have taken a look at this and the issue was due to the bounds calculated on cursor move which is not getting reset after the pane is resized

![shows_old_bounds_value](https://github.com/grafana/grafana/assets/47709856/dc41c265-8111-435a-a7a4-398cbd8fb7ea)

The `DraggableManager.tsx` component resets the bounds when the window is resized (`window.addEventListener('resize', this.resetBounds)`), but the same is not done when the split pane is resized

I couldn't find a way to listen to the pane resize event from the `ViewingLayer.tsx` component, however I managed to resolve this by invoking the `resetBounds()` function when the cursor leaves the trace graph.

If you think there is a better way to do this by subscribing to the actual pane resize event, then please advise

The fix is available on #76587

**Comment by Elfo404** [comment]
I'm not super familiar with that part of the codebase, but i'd imagine a resizeObserver would be a viable solution. i'd wait for @grafana/observability-traces-and-profiling to advise though, as they own this and have for sure more context

**Comment by aocenas** [comment]
I think @adrapereira or @joey-grafana are either working on this or there is a duplicate issue for this
