### ISSUE TITLE
[Feature request] Allow use formatting template for annotations

### ISSUE THREAD

**Issue by gbrian** [grafana/grafana#7643]
Grafana v4.0.2

I think will be great to been able to introduce a (kind of) moustache template to be used when formatting annotations. Been able to execute custom javascript on the response is welcome as well :) i for the case you can not change how data is stored.

Example: 
My object has a list of exceptions so the `Text`field could be a moustache or similar template:

```
{{#exceptions}}
<h3>{{Message}}</h3>
<p>{{CallStack}}</p>
{{/exceptions}}
```

And the output

## Error on whatever
at func() line 10
at func() line 12
...

## Error on whatever
at func() line 10
at func() line 12
...

Thanks

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
