### ISSUE TITLE
[Feature request] 'Config Include'

### ISSUE THREAD

**Issue by andyl** [grafana/grafana#7648]
Using Grafana 4.1.2 with InfluxDB on Ubuntu 16.04.

I would like more flexibility in laying out the Grafana config file thru the use of 'include file' directives.

I can imagine include file directives taking a couple of different forms.

1) an "include_file: <filename>" directive

2) an 'include directory' (like /etc/grafana.conf.d) that includes all files. ("include_directory: <dirname>")

A "Config include" feature would be useful for me in scripted Grafana deployments where configuration options differ deployment to deployment.  Especially useful for isolating private configuration options (account_id's, usernames/passwords) in a Grafana config.

**Comment by twblamer** [comment]
Option 2 would be great for me.  Many tools use this pattern in the CentOS/Fedora world, it helps us easily deploy our environment specific configuration via RPM without conflicting with the upstream package.

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
