### ISSUE TITLE
Dockerhub missing arm/v7 images since 10.1.4

### ISSUE THREAD

**Issue by tillsteinbach** [grafana/grafana#76629]
### What happened?

Builds since 10.1.4 are missing a build vor linux/arm/v7 on docker hub
<img width="1292" alt="image" src="https://github.com/grafana/grafana/assets/3825852/4fa48a7a-4da1-4acc-a2ce-17002321f987">

### What did you expect to happen?

Since I have not read that support is dropped I would expect the same images like in 10.1.2:
<img width="1292" alt="image" src="https://github.com/grafana/grafana/assets/3825852/85011416-007f-40ab-9a1c-54e1675d3d98">

### Did this work before?

Yes, only broken since 10.1.2

### How do we reproduce it?

1. Go here https://hub.docker.com/r/grafana/grafana/tags?page=1&name=10.1.2
2. Go here https://hub.docker.com/r/grafana/grafana/tags?page=1&name=10.1.5
3. compare

### Environment (with versions)?

Grafana: 10.1.5
OS: Docker

### Grafana platform?

Docker

**Comment by dicer** [comment]
10.2.0 was also released as amd64 and arm64 only. Is this a problem with the new release/build mechanism and will be solved eventually or should I update to a arm64 kernel?

**Comment by dsotirakis** [comment]
Hello all 👋 
According to this https://grafana.com/blog/2023/09/29/grafana-and-grafana-enterprise-updates-for-armv6-and-armv7-will-be-temporarily-paused/, we have paused 32-bit arm releases on purpose. According to the Golang community (since this is a Golang issue), the next minor version should include the fix for this and the missing arm builds should be brought back again. Thanks for your patience!
