### ISSUE TITLE
No more arm/v8 builds ?

### ISSUE THREAD

**Issue by Rebell81** [grafana/grafana#76924]
### What happened?

linux/arm/v8 docker builds are gone? Is it misstake or smth?

![image](https://github.com/grafana/grafana/assets/13855710/8e42c722-8741-416a-b5c0-f13dbf7c1596)

**Comment by usmangt** [comment]
Hi @Rebell81,

Thanks for opening this issue.

Was it available before? asking because I personally do not keep track but definitely would be v.helpful to know so that I can ask the right team

**Comment by Rebell81** [comment]
@usmangt Yes it was
Actualy i found that v7 gone too. Latest version of v7 is 10.1.2 and v8 is 9.5.8

![image](https://github.com/grafana/grafana/assets/13855710/99a162bc-3482-4cde-b570-5fdf3ec46156)

![image](https://github.com/grafana/grafana/assets/13855710/5c8c9381-1f6f-42a8-9959-0ba16bfb7bd2)

**Comment by dsotirakis** [comment]
Hello all 👋 
According to this https://grafana.com/blog/2023/09/29/grafana-and-grafana-enterprise-updates-for-armv6-and-armv7-will-be-temporarily-paused/, we have paused 32-bit arm releases on purpose. According to the Golang community (since this is a Golang issue), the next minor version should include the fix for this and the missing arm builds should be brought back again. Thanks for your patience!
