### ISSUE TITLE
Connections: Clicking on a logo of the plugin does not open plugin page

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#77045]
### What happened?

When Adding new connection and clicking on a logo of plugin, the click does not work - plugin page does not open.

https://github.com/grafana/grafana/assets/30407135/26588e17-5bbb-4bc1-9546-a80b58cc837c

### What did you expect to happen?

I can click on logo/name/card and ever click would open plugin page.

### Did this work before?

I don't know

### How do we reproduce it?

1. Go to Connections
2. Add new connection
3. Click on the logo, rather than name/card of the plugin

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: Grafana v10.3.0-pre (7929b19aeb)
OS: OSX
Browser: Chrome

### Grafana platform?

Other

**Comment by tolzhabayev** [comment]
fyi @mikkancso

**Comment by mikkancso** [comment]
I think this is a problem with `Card.Figure`. This bug seems to be present at other places as well, where there is a `Card` with an `onClick` handler and a `Card.Figure`, i.e. the click from the `Figure` does not propagate to the `Card`. I could reproduce this on the data source list page (`/connections/datasources`) as well by clicking on a data source's logo.

I tried to fix it, but I couldn't. @grafana/grafana-frontend-platform as you're the owners of `packages/grafana-ui/src/components/Card/Card.tsx` could you please take a look at this?

**Comment by Clarity-89** [comment]
This probably could be done as part of this work: https://github.com/grafana/grafana/issues/75548.

**Comment by timlevett** [comment]
Could not replicate on the latest version of connections UI, please reopen if issue persists. Tested on Grafana v10.3.0-64663 (f6f259f0b5)
