### ISSUE TITLE
Stat: Text is not scaling correctly

### ISSUE THREAD

**Issue by jostrasser** [grafana/grafana#77092]
### What happened?

After updating from 10.1.5 to 10.2.0 the Stat Panel text does not scale correctly. The "Alias" is way to small to read, normally the Alias was shown on the left and the value on the right in one line.
The settings are all set to "Auto" like on 10.1.5, no changes are made on the settings.

![SCR-20231024-thpo](https://github.com/grafana/grafana/assets/14274103/b925f24a-1442-4585-ae50-1cde91641177)

![SCR-20231024-tirh](https://github.com/grafana/grafana/assets/14274103/397e9fec-91e2-476c-9729-c335b355aa57)

### What did you expect to happen?

Correct alignment of text in the Stat Panel, row is small for this big text... 
Alias and Value should be displayed on one line (left Alias, right Value)

No way to workaround this!

### Did this work before?

Yes, on 10.1.5

### How do we reproduce it?

Update to 10.2.0

### Is the bug inside a dashboard panel?

Yes, attached:
[ENERGIEÜBERWACHUNG OG-1698179934755.json](https://github.com/grafana/grafana/files/13127192/ENERGIEUBERWACHUNG.OG-1698179934755.json)

### Environment (with versions)?

Grafana: 10.2.0
OS: Ubuntu Focal
Browser: Safari

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

InfluxDB

**Comment by bob454522** [comment]
see this PR / change , apparently this is an intentional change grafana made but as of now there was no way to enable/disable it  (silly / Unfortunate decision to not allow us to change it yet)

https://github.com/grafana/grafana/pull/77018
and 
https://github.com/grafana/grafana/pull/75556

What I don't understand is I tried manually editing this file as well as trying to comment out the line but the changes aren't taking hold (i'm assuming they are hard coded and this line that I'm seeing is only so that in the future they can make it so we can turn this on or off)
  /usr/share/grafana/public/app/plugins/panel/stat/StatPanel.tsx  
and i changed disableWideLayout={true} to disableWideLayout={false} 
(had no effect even after Apache restart and Graphana Service Restart, and clearing browser caches)  -  so i then tried to just comment that line out (same thing,  still no change)

here is my post over there:
We have 4x large 4k Monitors showing beautiful grafana dashboards (Exclusively), and running 24/7 - with panels using lots of stat Visualizations. Thus was quite surprised after the 10.1.5 to 10.2 update to see alot of our panels overlapping and not looking so good now.

I see there is the option:
disableWideLayout={true}

(over here: https://github.com/grafana/grafana/pull/75556#discussion_r1338777449)

Is this something we can change in Grafana INI? Or Is that something internal only where y'all are waiting to potentially add this in the future into the webGUI? please lmk, as i would like to revert back to wideLayout, If but not sure where to make this change (if it's even possible currently)

bc its worth noting That I think this should not have gone live until the on/off toggle feature was in place (somewhere), partly because by the time users wait for the current WIP to be pushed through and released, most of them will have spent a huge chunk of time rearranging the dashboards that would need this feature. (As users aren't going to want to have dashboards looking all funky waiting a month or longer for the next release)

**Comment by jostrasser** [comment]
Hi @bob454522 
Thanks!! Hopefully we will see an option to easily configure the behavior of the panel. As you mentioned, maybe directly in the Grafana.ini file.

The best option would be to get the possibility to configure this directly in the panel settings in Grafana.

**Comment by KOCIU22** [comment]
Im also waiting for this option becouse like bob454522 we have lot of panels with this and now looks terrible i dont wann change every panel so im waiting for update to adding tis toggle button :) when can we expect this change ?

**Comment by jostrasser** [comment]
Hi,

Same here, way too many dashboards to change.😞

**Comment by nmarrs** [comment]
Hi @jostrasser / all - I want to apologize for the handling of this change. It was an oversight on our end to modify how the stat panel styles work without any ability to eject from the new behavior.

I have [a WIP PR to add a toggle to the stat wide layout setting](https://github.com/grafana/grafana/pull/77018), with the default value being the original layout behavior of the stat panel. I anticipate this being included in the 10.2.1 release. I apologize again for any headaches this has caused and for the dashboards that have had their designs messed up by this change. I agree with @bob454522 100% that this change should of shipped with a way to eject out of it. We will keep this failure on our part in mind for future changes that we ship to avoid this from happening again.

In the meantime the only workaround for this is to set the `disableWideLayout` prop to `false` [in the StatPanel.tsx file](https://github.com/grafana/grafana/blob/v10.2.x/public/app/plugins/panel/stat/StatPanel.tsx#L51)

https://github.com/grafana/grafana/assets/22381771/6e2bd5f8-eee8-4390-8266-6a2d55d64d0e

**Comment by jostrasser** [comment]
Thanks @nmarrs for the quick response! :)

**Comment by bob454522** [comment]
> In the meantime the only workaround for this is to set the `disableWideLayout` prop to `false` [in the StatPanel.tsx file](https://github.com/grafana/grafana/blob/v10.2.x/public/app/plugins/panel/stat/StatPanel.tsx#L51)

This is great news on both fronts!  
#1- that the option to enable/disable the wide-layout will be exposed in the webGUI at some point soon (via a future post-10.2.0 update)  
and
#2- that for now we can manually modify the StatPanel.tsx file to fix this while waiting for future update (Which when that update arrives, this manual modification will be overwritten by the update/install action).

Best of both worlds!  - thank you,
LOVE GRAFANA!

**Comment by manny4566** [comment]
Hi,

i have the same problem. But changing the value to false, don't help.

![grafik](https://github.com/grafana/grafana/assets/23473485/6efdd923-012b-4465-affb-ee7ee82cc24f)

![grafik](https://github.com/grafana/grafana/assets/23473485/06571d18-e36a-45bd-abe3-76620c26913f)


Bevor the upgrade to 10.2.0 each stat where in this format:

Name        Value

In one line. Now it is in two lines and in a very small scaling.

Thank you

**Comment by KOCIU22** [comment]
Doesn't work. modifies this entry "disableWideLayout={false}" I still have the problem, nothing changes... Any idea why ?

Best Regards Luke

**Comment by bob454522** [comment]
> Doesn't work. modifies this entry "disableWideLayout={false}" I still have the problem, nothing changes... Any idea why ?
> 
> Best Regards Luke

hi @nmarrs - after making this temporary change (setting to false) , do we have to **locally re-Build/re-make Grafana,**  or should this change happen to an existing 10.2.0 grafana install simply by modifying ```/usr/share/grafana/public/app/plugins/panel/stat/StatPanel.tsx```
and changing to: ``disableWideLayout={false}```

(Apologies if I'm using the wrong terminology In regards to rebuild / re-make , I'm just not familiar with building / making applications from source code -  But I can of course modify a file of an application already installed).
thanks!
LOVE GRAFANA!

**Comment by bob454522** [comment]
@nmarrs  - In regards to setting ```disableWideLayout={true}```  TO  ```disableWideLayout={false}```

after doing this - do users need to locally re-Build/re-make Grafana (ie the app/binary), or should this change happen to an existing 10.2.0 grafana install simply by modifying the .tsx file: ```/usr/share/grafana/public/app/plugins/panel/stat/StatPanel.tsx```  (and then restarting grafana-server and apache )?  
thanks

**Comment by alex-tate** [comment]
It would be great to have some clarity around the temporary StatPanel.tsx change given the user comments above. Like others, I though I would wait it out until v10.2.1, but with dozens of negatively affected dashboards I'm being pushed to get the original format back asap.

**Comment by jostrasser** [comment]
@nmarrs do you have an information when the fix will be official released? Thanks!

**Comment by bob454522** [comment]
to update this thread - 10.2.1 has been released now!  and the stat panel is back to defaulting to the old wide mode (ie what we were looking for in this post).
we also have the option to enable / disable wide mode, as was described in this post.

great news!

(i do wish we could still get an answer to my question though -   if one was to make a change to a grafana `.tsx file`,  ie `StatPanel.tsx` in this example -  would that change take effect once you restart Grafana Server? Or are changes to .tsx files something that you would have to re-build / re-make (re-compile) the Grafana-Server app/executable  to see take effect?

tks
LOVE GRAFANA!

**Comment by leeoniya** [comment]
> Or are changes to .tsx files something that you would have to re-build / re-make (re-compile) the Grafana-Server app/executable to see take effect?

yes, you have to rebuild the frontend code via `yarn build` or `yarn start` for dev.
