### ISSUE TITLE
Docs: add info about creating an alert from a dashboard panel

### ISSUE THREAD

**Issue by brendamuir** [grafana/grafana#77116]
Alerting recently added a feature to be able to create alerts from panels - see here: https://grafana.com/docs/grafana/next/alerting/alerting-rules/create-grafana-managed-rule/#create-alerts-from-panels

To do -- 

i think this info or section also belongs in dashboard/panel docs since that's the ui users will be using to create the alerts. 

it's being released next week in cloud and then also in core in 10.3 - so we will also need release notes. i'll cover that.

@09jvilla fyi.

**Comment by imatwawana** [comment]
I don't think this content you've created needs to be copied into the Dashboards/Panels docs as there isn't a logical place for it to live. However, I'm adding some content to provide quick descriptions of the panel actions menu where and then that can link to the Alerting content. [Draft PR started here](https://github.com/grafana/grafana/pull/77162/). There are pieces I need to get reviewed by the Dashboards/Dataviz teams because I'm not familiar with every item in that menu.

**Comment by brendamuir** [comment]
Sounds like a plan to me -- thanks:)

**Comment by imatwawana** [comment]
@brendamuir I wasn't sure whether I should close this with my PR so I've assigned it back to you for the release docs. Of course just go ahead and close it if that's what makes sense.

**Comment by natellium** [comment]
@brendamuir I'm closing this as it seems you approved @imatwawana's PR. Do let us know if this should be reopened :)
