### ISSUE TITLE
Data source query builder - Update Code/Builder Toggle

### ISSUE THREAD

**Issue by catherineymgui** [grafana/grafana#77150]
Move the code / builder toggle from the right to the left of the query page. Resize to be the "default" query builder size.

<img width="1383" alt="Screenshot 2023-10-23 at 11 57 20" src="https://github.com/grafana/grafana/assets/5264102/584cf679-4200-4dce-8575-381555ae514f">

[See relevant UX issue](https://github.com/grafana/observability-metrics-squad/issues/132) from the metrics data sources team:

- [ ] Prometheus
- [ ] Loki
- [ ] Cloudwatch
- ~~MySQL~~
- ~~PostgresSQL~~
- ~~Google BigQuery~~

**Comment by sasklacz** [comment]
When is this supposed to be released ? We're closing in on releasing a Sumo plugin with query builders so could integrate this for the final version.

**Comment by catherineymgui** [comment]
Hey Kuba! No timelines on this yet but Prometheus will implement this sometime Q4 for sure (probably earlier rather than later)

**Comment by sasklacz** [comment]
cc @ktw4071

**Comment by gabor** [comment]
hi @catherineymgui , is this still actual?
i'm asking because it seems neither Prometheus nor Loki has done this change, so i wonder if we are going to do this or not, thanks!

also, for other datasources there are other visual elements there. for example, see this screenshot from PostgreSQL:
<img width="1002" alt="pg" src="https://github.com/grafana/grafana/assets/51989/1defcbfa-f40f-41e0-b628-a7c96762b26e">

all those controls like `Format: Table` , `Filter`, `Group`, `Order`, `Preview`, they are all parts of the query-builder (meaning parts of the widget below), so i'm not sure how best handle this, i guess we could have one more row of controls, but in general we try to not consume vertical space when it is avoidable. what do you think?

**Comment by catherineymgui** [comment]
@gabor Hey! So we decided to deprioritize this for Prometheus / Loki as we are deprioritizing work on query builders to focus on queryless apps. 

I think if the data source teams wanted to test this change (just move builder / code to the left, and the other toggles and controls shift to the right) to see if there's any incremental improvement, I support this. However we will not be doing this for Prometheus / Loki atm. 

If not - we can just close this issue.

**Comment by gabor** [comment]
hi @catherineymgui , thank you for the info 👍 . with regard to the datasources we own (postgres/mysql/bigquery), if the work is not going to happen for prom/loki, we'll also not do it.
the remaining one is cloudwatch, pinging @grafana/aws-datasources to ask about their approach.

(@catherineymgui i adjusted the issue to mark postgres/mysql/bigquery as removed, i hope that's ok)

**Comment by kevinwcyu** [comment]
i don't see any planned work for this on our board so i'll just close this as not doing.
