### ISSUE TITLE
Tooltip problem with TimeSeries

### ISSUE THREAD

**Issue by GrzegorzLyp** [grafana/grafana#77197]
There is a problem with hints on TimeSeries. As you move cursor from top to bottom of the bar suddenly hint disappears and as you go further down, hint from next bar is shown. You can see the color in the tooltip is orange and we are still on the red bar. That's really strange and need a fix. Screen shown below taken from https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1

Tested version: 10.2

![image](https://github.com/grafana/grafana/assets/29247982/5ff4ce1f-d10c-4429-b982-8a69aef555cb)

_Originally posted by @GrzegorzLyp in https://github.com/grafana/grafana/issues/76492#issuecomment-1778067051_

**Comment by GrzegorzLyp** [comment]
This is another example. This time tooltip outside the bar is shown. This seems to be messed up.

![image](https://github.com/grafana/grafana/assets/29247982/f175bd7f-a0b1-4e26-a779-f106f889d202)

**Comment by GrzegorzLyp** [comment]
Is there any chance for fix in the following version?

**Comment by leeoniya** [comment]
the hover behavior in TimeSeries is by proximity to the data value because it is possible to mix and match different rendering styles and fill opacities from different series. for example if you have several line series in front of a bar series and put your mouse over thay region, what should be hovered in Single tooltip mode? there is no "correct" answer to this, so we always hover by proximity to the value in this panel for all series. this is very unlikely to change.

**Comment by GrzegorzLyp** [comment]
It was working correctly in previous versions of TimeSeries, so I suppose it can be done correctly. For example BarChart has proper hovering of tooltips.
Without proper hovering DataLinks are just useless. We did great tools with Grafana but it is getting worse with new versions of Grafana.
