### ISSUE TITLE
Alerting: Alertmanager sends resolved notifications while Grafana alert is still firing

### ISSUE THREAD

**Issue by github-vincent-miszczak** [grafana/grafana#77285]
### What happened?

having :
- a Grafana alert that is always firing :
`vector(1)` Prometheus query.
with evaluation group interval at 1m
and `for` at 5m
- a notification policy that forwards all Grafana alerts to an Alertmanager(Mimir)

I receive an alert notification after ~5 minutes, which is fine, but also a resolved notification 5 minutes after the alert notification, while the alert is still firing.

### What did you expect to happen?

Resolved message should only happen if the alert is not firing.

### Did this work before?

No

### How do we reproduce it?

1. have a notification policy that forwards  Grafana alerts to an Alertmanager

2. setup a Grafana alert that is always firing :
`vector(1)` Prometheus query.
with evaluation group interval at 1m
and `for` at 5m

### Environment (with versions)?

Grafana: v9.5.7

### Grafana platform?

None

**Comment by tonypowa** [comment]
hi @github-vincent-miszczak 
what are the timing options of the your notification policy (i.e. the notif. policy concerning your alert rule) ?

**Comment by github-vincent-miszczak** [comment]
![image](https://github.com/grafana/grafana/assets/35925003/0261899b-b1df-442f-a5cf-ff6c5f55e0b9)
```
group_wait      = "30s"
group_interval  = "5m"
```

**Comment by tonypowa** [comment]
thanks for the info @github-vincent-miszczak 
one last thing, can we look at the state history? this is in the view menu of the alert
this is to see if the alert was firing all the time
![image](https://github.com/grafana/grafana/assets/45235678/9ab0e70e-9b8d-4f4b-aa61-263116dc2099)

**Comment by github-vincent-miszczak** [comment]
![image](https://github.com/grafana/grafana/assets/35925003/efe5fe38-159a-4739-b6a0-02c38fdfa69b)

We have the same alert twice in the history because we have 2 HA Grafana instances.

For instance, one alert started to fire at 2:06 AM, a Slack notification was received at this time, but a resolved notification was sent at 2:11 AM, while the alert was still firing as shown in the capture.

The alert/resolve-5minutes interval notification was repeated every `repeat_interval=4h` until the alert returned to normal. At the time of returning to normal, there was no notification at all.

**Comment by armandgrillet** [comment]
It looks like Grafana failed to talk to Prometheus, especially as the query is a simple one that should not time out. Could we get your Grafana logs when this happens to debug this more? It would also be interesting to know what you have `NO DATA` and `ERROR` mapped to.

**Comment by hunsbea** [comment]
I found this thread because I had a similar issue - we were sending alerts from Grafana to Alertmanager and they were getting auto-resolved after 5 minutes despite the Grafana alert still firing.

And then I found this https://prometheus.io/docs/alerting/latest/configuration/#file-layout-and-global-settings

Alertmanager has a `resolve_timeout` parameter that defaults to 5 minutes. This doesn't affect alerts coming from Prometheus, because they always include the `EndsAt` param. But for alerts from anywhere else, like Grafana, it means if it doesn't hear from Grafana again within 5 minutes, the alert will auto resolve.

So, to get around this, you can either set the resolve_timeout to something higher in Alertmanager, or you can override the time interval settings in your Grafana configuration to re-send the alert every e.g. 3 minutes.

Hope that's helpful for anyone who reads this later.
