### ISSUE TITLE
[Feature request] When repeating a panel on template var, optionally share Y axis scale

### ISSUE THREAD

**Issue by nyerup** [grafana/grafana#7742]
Sometimes when repeating a panel for each value of a template variable, it would be useful to make sure the Y axis scale, min, and max were shared between all of them. To make sure all data points are visible, this would have to be the widest range between all the panels, ie. the lowest Y min and the highest Y max from all the panels.

I'm attaching an example from a dashboard where this would make sense. The graphs show disk latency across three different storage installations, and to be able to compare them at a glance would be very helpful.

<img width="841" alt="screen shot 2017-03-06 at 12 49 02" src="https://cloud.githubusercontent.com/assets/76253/23608914/d4dbb066-026b-11e7-9c67-fb20d17d770d.png">

**Comment by torkelo** [comment]
yes, this would be nice.

Closing this as there is a very similar request open already:
https://github.com/grafana/grafana/issues/4156

**Comment by nyerup** [comment]
I read #4156, and didn't think it covered this use case, so I didn't want to obfuscate their request.

It seems to suggest just specifying a range in addition to putting down min and max values – I think the auto-range behaviour should still apply, but that it should span multiple panels within a relation.

Would it be okay if I added this suggestion in #4156?

**Comment by torkelo** [comment]
> It seems to suggest just specifying a range in addition to putting down min and max values – I think the auto-range behaviour should still apply, but that it should span multiple panels within a relation.

the title says pretty much that no? "Y axis auto min/max that aligns min/max across many graphs"

**Comment by nyerup** [comment]
Sure. But the discussion proposes a different behaviour.

**Comment by jpriebe** [comment]
I know this is closed, but I think that #4156 has the wrong title;  the discussion talks about setting ranges, which I think is more of an edge case than what #7742 is about.

I think it would be hugely valuable to "sync" multiple graphs' y-axis min/max.  Otherwise, it's hard to make relative comparisons between them at a glance.  And I would like to see it be broader than @nyerup originally proposed -- I would like to see *any* panels on a dashboard be able to share y-axis min/max.
