### ISSUE TITLE
[Bug] LDAP authorization failing for group_dn and group_mappings

### ISSUE THREAD

**Issue by igoratencompass** [grafana/grafana#7759]
Hi,

Looks like Grafana is not picking up the user's groups membership returned by the LDAP server.

Grafana 4.1.2
Ubuntu 12.04.5 LTS

Please see https://groups.io/g/grafana/message/2999 for more details.

Thanks

**Comment by torkelo** [comment]
maybe a permission issue? Looks like the group search is not returning any results.  strange.

**Comment by gabosvk** [comment]
In my case it was an issue of group_dn values - I followed the instructions and used full DN as a a value for group_dn and have no results
`group_dn = "cn=grafana-admins,ou=groups,dc=myorg.com"`

When I changed the group_dn to "grafana-admins" only, suddenly I was able to search defined groups
`group_dn = "grafana-admins"`

Just adding - we are using IBM LDAP and POSIX user accounts. As group class the admins defined groupOfNames which pretty complicates the whole thing - member attributes have key "member" and value whole DN so I'm not able to use "group_search_filter_user_attribute" settings option because there is no way I could get full DN (in IBM LDAP there is no attribtue like distinguishedName).

**Comment by igoratencompass** [comment]
@torkelo the message link I left clearly shows ldapsearch returning 3 dn's. What kind of help do you need from my side regarding this issue?

**Comment by igoratencompass** [comment]
This is the debug log from when a user with Admin permissions logs in:

```
t=2017-05-09T12:23:17+1000 lvl=info msg="Searching for user's groups" logger=ldap filter="(&(objectClass=posixGroup)(memberUid=MY_USER))"
t=2017-05-09T12:23:17+1000 lvl=dbug msg="Ldap User found" logger=ldap info="(*login.LdapUserInfo)(0xc420244d20)({\n DN: (string) (len=49) \"uid=MY_USER,ou=Users,dc=domain,dc=com\",\n FirstName: (string) (len=4) \"MY_NAME\",\n LastName: (string) (len=7) \"MY_SURNAME\",\n Username: (string) (len=12) \"MY_USER\",\n Email: (string) \"\",\n MemberOf: ([]string) (len=3 cap=4) {\n  (string) (len=14) \"group-users\",\n  (string) (len=12) \"MY_USER\",\n  (string) (len=6) \"**Admins**\"\n }\n})\n"
```

As you can see the **Admins** group is one of the returned group memberships for the user. It is also a member of the **group-users** as we can see above so either my settings are not good enough to filter just the Admin group or the ldap code does not check for multiple groups membership and only handles the first group returned from the ldap server.

**Comment by igoratencompass** [comment]
@gabosvk the `group_dn` change worked, thanks!

**Comment by joaquin386** [comment]
@gabosvk yes also not putting the full dn just the name of the group also did it for me. Good catch.

**Comment by geekofalltrades** [comment]
We use OpenLDAP with POSIX schema; no memberOf attribute on users. I just hit the same issue @gabosvk did. Changing the `servers.group_mappings` block to use just the string name of the group instead of the full DN also fixed it for me.

We're on grafana 4.0.2; here's the LDAP setup documentation for that version: http://docs.grafana.org/v4.0/installation/ldap/

The documentation seems to suggest that the full DN is what's needed. Either that's completely wrong, or there's an undocumented change in behavior when you use the `group_search_filter` and `group_search_base_dns` values.

In either case, the documentation needs to be updated.

**Comment by torkelo** [comment]
Closing this as there appears to be workarounds
