### ISSUE TITLE
[Feature request] Time range override per query

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#7762]
It could be useful if Grafana provide time range override per each panel target.

Most of TSDB has timeshift feature, but the expression becomes little complicated.
So I want to control it from Grafana side.

**Comment by wei-hai** [comment]
+1

**Comment by groyee** [comment]
Any plans to implement this feature?

Currently the only solution is to duplicate the data source and provide a different value for the time field.

**Comment by Anandababu** [comment]
+1. 
Would love to use absolute time 
per panel - This will allow to have two graph side-by-side to compare two time range.
per query - This will allow to have 2 series in the same graph to overlay with each other.

I understand we can use relative time shifting, while its most often used, but thats not the ONLY requirement always.

**Comment by xbsura** [comment]
So, any plans now?

two years passed...

**Comment by freemanoid** [comment]
There is still some interest in this feature. 😄

**Comment by mdvictor** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. We're trying to limit open GitHub issues in order to better track planned work and features.
This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.
Thank you for taking the time to create this issue!
