### ISSUE TITLE
[Security] Unmaintained and archived dependency (yahoo/blink-diff) with CVEs 

### ISSUE THREAD

**Issue by hbollon** [grafana/grafana#77711]
**What is the chore?**:
Hello Grafana' team
I noticed a deprecated dependency used in your npm module `@grafana/e2e`  called [yahoo/blink-diff](https://github.com/yahoo/blink-diff) which wasn't updated since 2016.
The issue is that it have some outdated dependencies which contain critical CVEs in particular in `underscore` module.
Currently, `@grafana/e2e` have the following dependendy path:
```
@grafana/e2e:10.2.0 -> yahoo/blink-diff:1.0.13 -> yahoo/pngjs-image:0.11.7 -> jashkenas/underscore:1.7.0
```

The CVE which concern me is [CVE-2021-23358](https://github.com/advisories/GHSA-cf4h-3jhx-xvhq), it's present in the module `underscore@1.7.0`.
What are you planing to get rid of this dependency and how can we mitigate this security issue?

**Comment by joshhunt** [comment]
Good catch! We don't rely on this too much, and can probably either remove or replace it. Created https://github.com/grafana/grafana/issues/77887 to track this specifically.

To clarify, Grafana does not actually depend on underscore 1.7.0 - we resolve pngjs-image's underscore dependency to 1.13.6, which does not appear to have any CVEs for it.

https://github.com/grafana/grafana/blob/0b03344baaec650da4cc32971bea6961b0219584/yarn.lock/#L29668-L29673

```bash
$ yarn why underscore --recursive
├─ @grafana/e2e@workspace:packages/grafana-e2e
│  └─ blink-diff@npm:1.0.13 (via npm:1.0.13)
│     ├─ pngjs-image@npm:0.11.7 (via npm:~0.11.5)
│     │  └─ underscore@npm:1.13.6 (via npm:1.13.6)
│     └─ preceptor-core@npm:0.10.1 (via npm:~0.10.0)
│        └─ underscore@npm:1.13.6 (via npm:1.13.6)
│
└─ grafana@workspace:.
   └─ blink-diff@npm:1.0.13 (via npm:1.0.13)
```

Otherwise, there's a few factors that I believe make this non-exploitable:

 - Grafana does not run Javascript/NodeJS on the server. We only use it at build time to generate the js artefacts for browser javascript.
 - `@grafana/e2e` specifically is a testing framework, and is not involved in building any grafana artefacts
 - [CVE-2021-23358](https://github.com/advisories/GHSA-cf4h-3jhx-xvhq) refers to `underscore.template`, which it doesn't appear to be used by [pngjs-image](https://github.com/YahooArchive/pngjs-image/tree/master/lib)
