### ISSUE TITLE
Explore: When dragging split screen, graph does not expand to full width

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#77740]
When dragging split screen, graph does not expand to full width. This was discovered during user interview and I am sharing the screenshot of the screen. 

<img width="827" alt="image" src="https://github.com/grafana/grafana/assets/30407135/ccdacb9f-f74a-4417-99c7-82e37212fd13">

**Comment by harisrozajac** [comment]
@ivanahuckova I tried reproducing this locally and in production in our play and ops instances (on Chrome and Firefox), but the graph expands as expected. I see that they are using the most recent version of Grafana because I see the content outline button. I wonder if we could get a little more detail about the browser type they use, and what type of datasource so we can try to reproduce this.

**Comment by ivanahuckova** [comment]
@harisrozajac Chrome browser + Prometheus data source. You can find more information + recording (26 min) in https://docs.google.com/document/d/1KwwqBVeIVHZX9TFuIitLOsiQSC46Zpi7X_EPsVOuHKk

**Comment by ifrost** [comment]
Thank you for reporting this 🚀  To help us with the investigation, please reopen the issue providing a minimal, reproducible example.
