### ISSUE TITLE
Add support for multi-columns in Cloudwatch Logs

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#77949]
### Discussed in https://github.com/grafana/grafana/discussions/48776

<div type='discussions-op-text'>

<sup>Originally posted by **sarahzinger** May  5, 2022</sup>
When using AWS Cloudwatch you can get logs organized in multiple columns like so:
![Screen Shot 2022-05-05 at 9 38 27 AM](https://user-images.githubusercontent.com/6620164/166961618-fee8d658-d7bc-4285-b221-8bc6e7dcf607.png)

In the above example you see we select for 3 fields and we get back the logs formatted in 3 columns. In my memories this is a similar pattern to other Logs visualization tools like Kibana. 

But with Grafana, I believe the Logs visualization only supports 2 columns, timestamp, and the log message. 

![Screen Shot 2022-05-05 at 11 52 39 AM](https://user-images.githubusercontent.com/6620164/166963096-1e97f510-c836-4a32-af8b-b4f3f4a1be52.png)

The only way to get this data surfaced at a column level is to use a Table, which is less than ideal because a message is often in JSON form, and it's hard to read JSON in a table format. 
![Screen Shot 2022-05-05 at 11 51 25 AM](https://user-images.githubusercontent.com/6620164/166963133-7d1856e2-c2ca-42ef-a187-1db6e9f346b4.png)

I'm not sure if the answer here is to improve the Logs visualization to allow for multiple column support, or if the answer is to make a new visualization altogether like LogTable or something like that?
</div>

**Comment by katebrenner** [comment]
close as won't do

**Comment by vanjasmailovic** [comment]
> close as won't do

Why?

**Comment by mvillafuertem** [comment]
@katebrenner why?

**Comment by diranged** [comment]
Agreed. .. @katebrenner why?

**Comment by taleena** [comment]
Hi all, it sounds like there is interest in something like this, and it hasn't been something we've been able to prioritize against our other work. Would you be willing to share some examples on where this might be useful to you so we can better understand your desire for it?

**Comment by matyax** [comment]
I'm using Elasticsearch to show this because I don't have a Cloudwatch instance to try, but as it was mentioned in this issue, in Explore, we have a few ways of displaying fields.

One involves toggling "displayed fields" from the Log Details panel that appears when you click at a log line. This has recently been added to Dashboards too; just keep in mind that we don't persist your display selection at this time.

The other, which is ideal for dealing with tabulated data or multiple fields, is the Logs Table, which in the latest Grafana releases is enabled by default.

https://github.com/user-attachments/assets/80bbe872-9001-489e-a603-80cb0c3de814

For dashboards, another suggestion that I have is to use transformations to override the field that is shown as the log message.
