### ISSUE TITLE
Datasource organisation and management improvements.

### ISSUE THREAD

**Issue by Shane-OH** [grafana/grafana#77944]
**Why is this needed**:

We are increasing our use of datasource's in our company. [Opensearch, Postgres, SQL Server, AWS Cloudwatch, Appdynamics] and have 100+ datasources currently and increasing. We are finding that alot of these datasources have repeatable fields or params. For example our opensearch datasources all use the same domain endpoint with the index name and possibly the time field name being different.

This isnt possible for every datasource but could dramatically cut back on duplication we need to do. 
Another area of improvement would be in the UI page where it displays all the data-sources in a list, maybe a design similar to the /dashboard page?

**What would you like to be added**:

- More generic-ised datasources with drop-down sortable fields. 
- More organised datasources page with collapsible folders like the [/Dashboards](https://play.grafana.org/dashboards) page

**Who is this feature for?**

Everyone, we all use datasources for our data.

**_Below_**
_Arrows = possible generic-isable fields._

![image](https://github.com/grafana/grafana/assets/74359284/18c3cccf-461e-4e95-acf0-62b28c39e23c)

**Comment by bijwaard** [comment]
In my case I have a great number of Influxdb and JSON datasources that have either a different URL or same URL but different database and consistent naming with a location (such as e552, e553) and fields such as (F0, F1, ..., F8):

| Type | name | database | url |
| ------- | -------- | ------------- | ---- |
| influxdb | e552-F0 | e552_F0 | http://localhost:8086
| influxdb | e552-F1 | e552_F1 | http://localhost:8086
| influxdb | e552-F2 | e552_F2 | http://localhost:8086
| influxdb | e552-F3 | e552_F3 | http://localhost:8086
| influxdb | e553-F0 | e553_F0 | http://localhost:8086
| influxdb | e553-F1 | e553_F1 | http://localhost:8086
| influxdb | e553-F2 | e553_F2 | http://localhost:8086
| influxdb | e553-F3 | e553_F3 | http://localhost:8086
| JSON       | rtHome-F0 | | https://localhost/country/city/home/f0/
| JSON       | rtHome-F1 | | https://localhost/country/city/home/f1/
| JSON       | rtOffice-F0 | | https://localhost/country/city/office/f0/
| JSON       | rtOffice-F1 | | https://localhost/country/city/office/f1/

I could of course script the creation of these datasources, but they also get harder to manage because of the number of datasourcces. Also when creating panels, selecting 1 out of hundreds of datasources also becomes a nightmare. I now use dashboard variables to construct a datasource name, e.g. $SelectedField=$location-$field.

To show e.g. power of all 8 fields in a flowcharting graph, I have to create 8 similar metrics using the 8 different datasources. And when one of the datasources is yet created or unavailable, I get an error and nothing is shown.

Also dashboard datasource reuse across panels is quite restrictive. I can only choose between:
- reusing all metrics from another panel, while I often only want one of the metrics
- creating an expression seems to be mutably exclusive with using dashboard datasource, while I often want to visualise e.g. power difference between some fields. e.g. $F0 - F1 and show the power themselves in another timeseries panel.

Kind regards,
Dennis
