### ISSUE TITLE
CloudWatch: Find a better solution than hard-coded metrics

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#77963]
I don't know that this is an actionable ticket just yet but I also wanted to make sure we don't lose this context.

We have right now a list of hard-coded metrics that we manually update quite regularly, as new metrics are frequently added, and we tend to only know we're missing them when users open github issues for them. 

One solution that was discussed here was to use the ListMetrics api, but it's not clear how this would work for larger customers, and there seems to be costs associated with it which we may want to consider. As we move from [discussions to issues](https://github.com/grafana/grafana/discussions/73424) for feature-requests, I think it makes sense to open an issue to talk about the best way to handle this moving forward.

### Discussed in https://github.com/grafana/grafana/discussions/41814

<div type='discussions-op-text'>

<sup>Originally posted by **sunker** February  8, 2021</sup>
**What would you like to be added**:
The metrics, namespaces and dimension keys that are shown in the query editor in Grafana should be a union of the result from the [ListMetrics API](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_ListMetrics.html) and the [hard coded list](https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go#L44-L234) of namespaces, metrics and dimension keys that we already have in Grafana. 

**Why is this needed**:
At the moment, namespaces, metrics and dimension keys are  [hard coded](https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go#L44-L234) in Grafana. The problem with that is that each time a new namespace, metric or dimension is added in AWS, this hard coded list needs to be updated manually. Also, this doesn't take custom namespaces into consideration, so at the moment they have to be added manually in the [data source configuration page](https://grafana.com/docs/grafana/latest/datasources/cloudwatch/#adding-the-data-source). 

The aforementioned problem would be partly solved by using [ListMetrics API](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_ListMetrics.html). However, the ListMetrics API doesn't return information about metrics if those metrics haven't reported data in the past two weeks. So if we switched over to only use the API, we would potentially change the query editor behavior for our users. Therefore, we should present a union of the hard coded metrics and the result from ListMetrics API in Grafana.

The ListMetrics API is part of the [paid tier](https://aws.amazon.com/cloudwatch/pricing/#Paid_tier), so we should not issue a new request to the API each time the namespace, metrics or dimension key field is clicked on in the query editor or is requested using a template variable query. Instead, the result should be cached and used for some time. I suggest 1 hour. 

This is related to #28382, #23134, #22215, #26505

Feedback appreciated @mtanda @chrs-myrs @mchene</div>

**Comment by jangaraj** [comment]
IMHO: I guess Grafana Labs has partnership with AWS, so I would ask AWS to publish regularly updated list of CloudWatch namespaces, metrics, dimensions anf their relations.

Then sync of hardcoded CloudWatch constants with that list provided by AWS can be part of Grafana release procedure. So each new release will have full current list of CloudWatch constants. ListMetric API can be used only for custom namespaces and can be available as feature, which will be disabled by default. It can be used also on non current Grafana releases, which doesn't have current list of CloudWatch constants to "refresh" them. 

I would say 95% of users don't need ListMetric API, but 5% of advance users should have an option to enable ListMetric API in the config. It should be disabled by default, because it is paid API and user/admin should make a decision if it should be enabled explicitly.
