### ISSUE TITLE
[ERROR] npm run build 

### ISSUE THREAD

**Issue by lin-credible** [grafana/grafana#7805]
`npm run build` error:

```
Version 4.3.0-pre1
Loading "sass.js" tasks...ERROR
>> Error: ENOENT: no such file or directory, scandir '/root/go/src/github.com/grafana/grafana/node_modules/node-sass/vendor'

...

Running "phantomjs" task
Warning: Unable to read "./node_modules/phantomjs-prebuilt/lib/location.js" file (Error code: ENOENT). Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 3.10.0-514.6.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! grafana@4.3.0-pre1 build: `./node_modules/grunt-cli/bin/grunt`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the grafana@4.3.0-pre1 build script './node_modules/grunt-cli/bin/grunt'.
```

**Comment by torkelo** [comment]
try `npm install -g yarn & yarn install`

you seem to be missing a few npm packages

**Comment by lin-credible** [comment]
I download another version `4.1.2` to compile:

waiting......
```
[1/2] ⠠ node-sass: Downloading binary from https://github.com/sass/node
[2/2] ⠠ phantomjs-prebuilt: Receiving...
[-/2] ⠠ waiting...
[-/2] ⠠ waiting...
[-/2] ⠠ waiting...
```

I can't visit this url: `https://github.com/sass/node` in browser. 

Could you help me?

**Comment by lin-credible** [comment]
package.json:
```
"engines": {
    "node": "4.x",
    "npm": "2.14.x"
  },
```
mine:
```
node: v6.9.4
npm: 3.10.10
```

**Comment by daniellee** [comment]
Delete the node_modules directory and then retry the yarn install.

**Comment by lin-credible** [comment]
I tried again and again... `phantomjs-prebuilt`    `phantomjs not found on path` 

It still does't work : (

**Comment by daniellee** [comment]
@lin-credible are you getting a different error now? Can you include the whole stack trace, please.

**Comment by lin-credible** [comment]
I give it up... I installed it by 'yum'.  But I'll try it in a few days 🤔 @daniellee Thanks

**Comment by wenglixiang1990** [comment]
Help, please.
I have meet the same issue, the same as lin-credible's. I have  try to delete the node_modules directory and then retry the yarn install, but it still does't work.
Here is the details:

1. npm run build error
# npm run build

> grafana@4.3.0-pre1 build /root/go/src/github.com/grafana/grafana
> ./node_modules/grunt-cli/bin/grunt

Version 4.3.0-pre1
Loading "sass.js" tasks...ERROR
>> Error: ENOENT: no such file or directory, scandir '/root/go/src/github.com/grafana/grafana/node_modules/node-sass/vendor'

Running "jscs:src" (jscs) task
>> 86 files without code style errors.

Running "jshint:source" (jshint) task

✔ No problems


Running "jshint:tests" (jshint) task

✔ No problems


Running "exec:tslint" (exec) task

Running "clean:gen" (clean) task
>> 1 path cleaned.

Running "copy:node_modules" (copy) task
Created 100 directories, copied 1596 files

Running "copy:public_to_gen" (copy) task
Created 324 directories, copied 2645 files

Running "phantomjs" task
Warning: Unable to read "./node_modules/phantomjs-prebuilt/lib/location.js" file (Error code: ENOENT). Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "run" "build"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! grafana@4.3.0-pre1 build: `./node_modules/grunt-cli/bin/grunt`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the grafana@4.3.0-pre1 build script './node_modules/grunt-cli/bin/grunt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grafana package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/grunt-cli/bin/grunt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grafana
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grafana
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/go/src/github.com/grafana/grafana/npm-debug.log
root@wenglixiang-ThinkPad-T450:~/go/src/github.com/grafana/grafana# 
root@wenglixiang-ThinkPad-T450:~/go/src/github.com/grafana/grafana# 
root@wenglixiang-ThinkPad-T450:~/go/src/github.com/grafana/grafana# 

2. Delete the node_modules directory and then retry the yarn instal
# yarn install --pure-lockfile
yarn install v0.21.3
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.17: The platform "linux" is incompatible with this module.
info "fsevents@1.0.17" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/3] ⠁ waiting...
[2/3] ⠂ node-sass: Testing binary
[3/3] ⠂ phantomjs-prebuilt: Receiving...
[-/3] ⠂ waiting...
error /root/go/src/github.com/grafana/grafana/node_modules/node-sass: Command failed.
Exit code: 135
Command: sh
Arguments: -c node scripts/build.js
Directory: /root/go/src/github.com/grafana/grafana/node_modules/node-sass
Output:
Binary found at /root/go/src/github.com/grafana/grafana/node_modules/node-sass/vendor/linux-x64-48/binding.node
Testing binary
Bus error (core dumped)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
root@wenglixiang-ThinkPad-T450:~/go/src/github.com/grafana/grafana#

**Comment by daniellee** [comment]
Works on my computer :-) (only joking!) I'm running Ubuntu 16.04, with Node v6.9.1 and npm 4.1.0.

What OS are you on? What version of node and npm?

Maybe it is do with file permissions for the yarn cache directory?

https://github.com/sass/node-sass/issues/1781#issuecomment-258073386

On Ubuntu, my cache directory is: ~/.yarn-cache

**Comment by wenglixiang1990** [comment]
Thanks for help.


I have solved this problem. The reason for the error is that there was an error in the previous step “yarn install --pure-lockfile”.


Thanks again.




At 2017-03-16 19:20:31, "Daniel Lee" <notifications@github.com> wrote:


Works on my computer :-) (only joking!) I'm running Ubuntu 16.04, with Node v6.9.1 and npm 4.1.0.

What OS are you on? What version of node and npm?

Maybe it is do with file permissions for the yarn cache directory?

sass/node-sass#1781 (comment)

On Ubuntu, my cache directory is: ~/.yarn-cache

**Comment by YouZhengChuan** [comment]
@wenglixiang1990 
Hey ，Can u leave your QQ number，i encountered the same problem, use your provide but not solve(npm install -g yarn && yarn install --pure-lockfile), can you help me?

Im use go version go1.8 darwin/amd64,
MacOS 10.12.4 / Xcode 8.3
Node.js V6.10.2 LTS

"npm install -g yarn"  and "yarn install --pure-lockfile" is success, and "npm install -g yarn && yarn install --pure-lockfile" is success.

-------------
> npm install -g yarn && yarn install --pure-lockfile
npm WARN deprecated yarn@0.22.0: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
/usr/local/bin/yarn -> /usr/local/lib/node_modules/yarn/bin/yarn.js
/usr/local/bin/yarnpkg -> /usr/local/lib/node_modules/yarn/bin/yarn.js
/usr/local/lib
└── yarn@0.22.0 
>
> yarn install v0.22.0
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 1.01s.


But "npm run build" still fails, i have tried to solve this problem for a few days, can not find a solution.
------------------------------
>$ npm run build
> grafana@4.2.0 build /Users/youzhengchuan/gitlab/isurecloud/src/github.com/grafana/grafana
> ./node_modules/grunt-cli/bin/grunt
Version 4.2.0
Loading "sass.js" tasks...ERROR
>> Error: ENOENT: no such file or directory, scandir '/Users/youzhengchuan/gitlab/isurecloud/src/github.com/grafana/grafana/node_modules/node-sass/vendor'
>
>Running "jscs:src" (jscs) task
>> 86 files without code style errors.
>
>Running "jshint:source" (jshint) task
>
>public/app/core/services/analytics.js
>  line 14   col 107  Missing '()' invoking a constructor.
>
>public/app/core/services/keyboard_manager.js
  line 39   col 16   ['inputDisabled'] is better written in dot notation.
  line 195  col 25   ['keyCode'] is better written in dot notation.
  line 196  col 20   ['keyCode'] is better written in dot notation.
  line 223  col 19   ['propagate'] is better written in dot notation.
  line 242  col 24   ['type'] is better written in dot notation.
  line 246  col 33   ['type'] is better written in dot notation.
  line 249  col 35   ['type'] is better written in dot notation.
  line 252  col 23   ['type'] is better written in dot notation.
  line 273  col 28   ['event'] is better written in dot notation.
  line 274  col 24   ['target'] is better written in dot notation.
  line 275  col 26   ['callback'] is better written in dot notation.
>
> public/app/core/utils/kbn.js
  line 256  col 18   Use '!==' to compare with 'null'.
  line 384  col 15   Use '===' to compare with 'null'.
  line 389  col 15   Use '===' to compare with 'null'.
>
> public/app/features/dashboard/shareSnapshotCtrl.js
  line 35   col 37   ['externalSnapshotURL'] is better written in dot notation.
  line 36   col 43   ['externalSnapshotName'] is better written in dot notation.
  line 37   col 41   ['externalEnabled'] is better written in dot notation.
>
>public/app/features/panellinks/linkSrv.js
  line 19   col 17   ['from'] is better written in dot notation.
  line 20   col 17   ['to'] is better written in dot notation.
  line 98   col 17   ['from'] is better written in dot notation.
  line 99   col 17   ['to'] is better written in dot notation.
>
>public/app/features/templating/templateSrv.js
  line 22   col 19   ['__interval'] is better written in dot notation.
  line 23   col 19   ['__interval_ms'] is better written in dot notation.
>
> public/app/plugins/datasource/elasticsearch/bucket_agg.js
  line 183  col 20   Expected an assignment or function call and instead saw an expression.
>
> public/app/plugins/datasource/elasticsearch/datasource.js
  line 108  col 13   ['fields'] is better written in dot notation.
>
> public/app/plugins/datasource/elasticsearch/elastic_response.js
  line 172  col 18   ['filter'] is better written in dot notation.
>
> public/app/plugins/datasource/elasticsearch/query_builder.js
  line 109  col 45   Expected an assignment or function call and instead saw an expression.
  line 192  col 16   ['date_histogram'] is better written in dot notation.
  line 196  col 16   ['filters'] is better written in dot notation.
  line 204  col 16   ['geohash_grid'] is better written in dot notation.
>
> public/app/plugins/datasource/prometheus/metric_find_query.js
  line 57   col 9    Misleading line break before '+'; readers may interpret this as an expression boundary.
  line 58   col 9    Misleading line break before '+'; readers may interpret this as an expression boundary.
  line 118  col 7    Misleading line break before '+'; readers may interpret this as an expression boundary.
  line 119  col 7    Misleading line break before '+'; readers may interpret this as an expression boundary.
>
> public/app/plugins/panel/graph/graph_tooltip.js
  line 27   col 71   Use '!==' to compare with 'null'.
  line 27   col 110  Use '===' to compare with 'null'.
  line 29   col 13   Misleading line break before '||'; readers may interpret this as an expression boundary.
  line 93   col 13   Misleading line break before '||'; readers may interpret this as an expression boundary.
  line 94   col 13   Misleading line break before '||'; readers may interpret this as an expression boundary.
>
> public/app/plugins/panel/graph/jquery.flot.events.js
  line 116  col 27   Did you mean to return a conditional instead of an assignment?
  line 223  col 23   Use '===' to compare with 'null'.
  line 229  col 23   Use '===' to compare with 'null'.
  line 361  col 31   Use '!==' to compare with 'null'.
>
> public/app/plugins/panel/graph/series_overrides_ctrl.js
  line 41   col 24   ['lines'] is better written in dot notation.
  line 50   col 22   ['color'] is better written in dot notation.
>
>  ⚠  46 warnings
>
> Warning: Task "jshint:source" failed. Use --force to continue.
>
> Aborted due to warnings.
>
>npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! grafana@4.2.0 build: `./node_modules/grunt-cli/bin/grunt`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the grafana@4.2.0 build script './node_modules/grunt-cli/bin/grunt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grafana package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/grunt-cli/bin/grunt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grafana
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grafana
npm ERR! There is likely additional logging output above.
>
>npm ERR! Please include the following file with any support request:
npm ERR!     /Users/youzhengchuan/gitlab/isurecloud/src/github.com/grafana/grafana/npm-debug.log

>$ ./bin/grafana-server 
CRIT[04-13|17:01:25] Failed to detect generated css or javascript files in static root (/Users/youzhengchuan/gitlab/isurecloud/src/github.com/grafana/grafana/public), have you executed default grunt task?%!(EXTRA []interface {}=[])

**Comment by daniellee** [comment]
@YouZhengChuan did you try deleting the node_modules directory and then running `yarn install --pure-lockfile` again?
