### ISSUE TITLE
[Feature request]How to change the  graph's x-axis ?

### ISSUE THREAD

**Issue by Nymph-fan** [grafana/grafana#7817]
I see  the abscissa of graph always be  time-unit.Only the  Y-Axis I can change ,Is there any way to use customize data to draw graph.

**Comment by daniellee** [comment]
Do you mean the X-axis mode option or something else? You can find the Mode option on the axes tab - see below:

![axesmode](https://cloud.githubusercontent.com/assets/434655/23878511/0b72e040-0848-11e7-8433-fd4c74fb571a.png)

**Comment by Nymph-fan** [comment]
@daniellee 
![qq 20170314094546](https://cloud.githubusercontent.com/assets/10972046/23882343/d9b4e4ce-089a-11e7-90ea-717292c47722.png)

 May I ask you which  version of grafana you are using,My version is 3.x and it does not have option to change X-axis

**Comment by daniellee** [comment]
The X-axis mode feature was released in version 4.0 last September.

**Comment by mbadh** [comment]
Hey is there any possible way to change the x-axis to label values? Because the data I need to visualize for my job is through prometheus and has a label called "timestamp". I need to have the metric values on Y-axis and timestamps on xaxis. But the x-axis would not let you customize the time line in grafana. Yeah it has three modes but instead of those modes I need to substitute the timestamp labels. Is there anyway to do that? maybe through scripted dashboards?

your help would be highly appreciated!
