### ISSUE TITLE
Cursor synchronization between diagrams along one axis only

### ISSUE THREAD

**Issue by korinekgergely** [grafana/grafana#78444]
**Why is this needed**:

I can imagine a case where I show different values on different charts, temperature, wind speed, rainfall, etc. All moving on the same time axis, I want to compare the current values. Let's say this is the X axis. In this case it makes no sense to see the Y axis together.

**What would you like to be added**:

I need a setting here, or where the developers see fit:
`$behaviors: [new behaviors.CursorSync({ key: 'cursor-sync-scope', sync: DashboardCursorSync.Tooltip })],`
which allows me to select which axis along which axis I want cursor sync to be exclusive.
I can imageine, like:
`$behaviors: [new behaviors.CursorSync({ key: 'cursor-sync-scope', sync: DashboardCursorSync.Tooltip, syncaxis: 'X' })],`
X or Y or as default: all

**Who is this feature for?**

For those who want to present different units of measurement along a common denominator, for example: time.

**Comment by leeoniya** [comment]
happy coincidence, we're actually reworking this currently :)

we're going to remove y axis sync since it doesnt make sense in 99.9% of cases where you have not only different y ranges based on the visible data but also different units, multiple y axes. it is both too complex internally and poor nonsense ux.

we'll be simplifying sync so it only works for x = time panels (and table panel with time a column)

one question we'll need to address is the synced tooltips. without a Y, they would have to be in the All mode during sync, but not all x = time panels have a working All tooltip mode currently. additionally panels can have 100 series, so we'll nees to figure out a good way to sort and truncate the series list to keep it sane.

stay tuned, updates soon!
