### ISSUE TITLE
Singlestat font color for text.

### ISSUE THREAD

**Issue by avinhaes** [grafana/grafana#7855]
- What Grafana version I´m using?
          Grafana 4.1.2
- What datasource I´m using?
           Zabbix 3.1.1
- What OS I´m running grafana on?
          CentOS 7

Hi Support,
in previous version of Grafana (version 3), I had control of my text color using htlm tags in the text. For example, if I include the text bellow, my singlestat panel showed colors what I want. For example, I could include the text bellow to have my information in red (or any color) in singlestat output panel:
{b}{span style="color:#D21B21"}Error{/b}

Note: I have changed bellow <> by {} in order to exemplify the html code

After upgrade for Grafana 4, it doesn't work anymore. How can I work with text colours in text singletstat panel from version 4 ?

Thank you.

Alexandre.

**Comment by torkelo** [comment]
Singlestat panel currently only supports either background color or text color based on threshold. No option for text color. The reason your solution worked was that we did not properly escaped html in the prefix / postfix fields, a security issue we fixed in 4.x

**Comment by avinhaes** [comment]
Hi,
what is the alternative in having text colours in according to threshold / certain string ?

Thank you.

**Comment by iyuvalk** [comment]
Hi, Is there a way to set the background/text color of the singlestat panel to a specific value that is not depended on the value presented? The way I understand the UI, Since it is only possible to select one set of green, yellow, red colors, it would only make sense to set either the background **or** the text color based on the presented value but not both (because otherwise the text will become hidden). So it possible to set either the text or the background to a fixed value to make it usable?
