### ISSUE TITLE
Cloudwatch: allow expressions to do division when data-points have been dropped

### ISSUE THREAD

**Issue by polak785** [grafana/grafana#78608]
### What happened?

This is the following of discuss on https://github.com/grafana/grafana/discussions/43142

I have the exact problem explain on the discuss.

Here is my panel : 
[panel.json](https://github.com/grafana/grafana/files/13452549/panel.json)

I reproduce the queries and math expressions to get EFS bandwitch usage that were on AWS Cloudwatch.

Sometime it works, sometime I have this error. The errors occurs more often unfortunately.

The error is  `ArithmeticError in query \"F\": One or more data-points have been dropped due to non-numeric values (NaN, -Infinite, +Infinite)`

### What did you expect to happen?

I want no error so that I always have a working graph. 

### Did this work before?

Never (added 1 month ago)

### How do we reproduce it?

cf. my panel : 
[panel.json](https://github.com/grafana/grafana/files/13452558/panel.json)

### Environment (with versions)?

Grafana: 10.1.5
OS: Ubuntu

### Grafana platform?

Kubernetes

### Datasource(s)?

Amazon CloudWatch

**Comment by sarahzinger** [comment]
@polak785 I recreated your panel in 10.1.5 (only I used EC2 instead of EFS) and notice I can sometimes recreate the error and sometimes can not depending on the times I select.

The error `ArithmeticError in query \"F\": One or more data-points have been dropped due to non-numeric values (NaN, -Infinite, +Infinite)` is coming directly from AWS. I can recreate it reliably if I try to divide by zero or if I try to calculate a math expression on a query that returns no data.

To help debug this I'd recommend looking at the network tab to try to identify which query is failing. In my experience it was almost always the last one `(e1)*100)/(e2)`

Then I'd recommend seeing if it's possible that e1 or e2 is returning either 0 or no data and then seeing if you can use FILL or some similar metric math function to ensure that you always have valid arithmetic values that you can divide with. 

At this time, I don't see evidence of an issue with the datasource plugin that can explain this issue and think you'd get the same results if you'd use AWS's API's directly, although I think we could definitely improve the trouble shooting experience on our end to surface which queries are experiencing an error.

**Comment by polak785** [comment]
I read somewhere that using `FILL` might change the results.

What you said is interesting. You said that it fails because of divide by zero, which I interprete it by "none data available". :thinking: Thus, my hypothesis is that the very recent data for the metrics used here are not all available at the same time.
So I tested to set time range without the latest minute and it always display graph without issue. 

Finally, as workaround, I added a 1min timeshift on the graph. So far, so good :) :crossed_fingers:

**Comment by polak785** [comment]
Ok unfortunaltely it still failing with a timeshift.

It appears that the values 0 comes from the 'm2' metric. Thus I use FILL function in query : `FILL(m2,REPEAT)/1048576` 

 So far, so good :) 🤞

**Comment by sarahzinger** [comment]
Hi @polak785 just checking in to see if using FILL has fixed your issue?

**Comment by polak785** [comment]
Yes it works like expected :+1: 

Except another weird bug, when we select a time range > 33h the graph output is not good.

For exemple, with the same graph tooks at same time, with a time range for the last 33h:
![image](https://github.com/grafana/grafana/assets/37365812/86e76074-f596-4257-8aa3-4ad6d044e415)

with a time range for the last 34h :
![image](https://github.com/grafana/grafana/assets/37365812/62d92507-2c2f-4fa7-ba6d-3bb433ff22b3)

I don't know why :man_shrugging: 

But the initial bug reported here is properly fixed so I closed it :)
