### ISSUE TITLE
XY Chart Adjust X axis max

### ISSUE THREAD

**Issue by IdjazB** [grafana/grafana#78616]
### What happened?

Dear grafana community,

on the XY-Chart the limits do not work correctly.

If Min and Max are set individually for the x AND y axis (overrides), it only works for the y axis. In my case the x-axis should also be limited.

### What did you expect to happen?

The overrides on the y-axis work, the max and min are set properly there, but the x axis completely ignores the settings.

### Did this work before?

No

### How do we reproduce it?

N/A

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by tonypowa** [comment]
hi @IdjazB 

Thank you for reaching out with your issue

Can you share the specific version of Grafana you are using?
- What operating system and browser version are you using when encountering this issue?
- Would it be possible for you to provide a step-by-step guide on how to reproduce the issue starting from a new dashboard? This greatly helps in diagnosing the problem.

Thank you

**Comment by Mayerch1** [comment]
I'm having the same issue here.
I'll try to give a few steps to recreate the issue

### Info
Grafana `Grafana v10.2.3 `
on docker with `grafana/grafana:latest`
docker is running on a windows host, but that shouldn't really matter here

### Panel Creation
On an empty dashboard, I'm creating a new panel of type `XY Chart`.
My datasource is influxdb

### Query
my query is 
```flux
from(bucket: "data")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "AccelX" or r["_measurement"] == "AccelY")
  |> filter(fn: (r) => r["ECU"] == "INS")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
  ```

The data is joined using `Transform data -> Join by field -> OUTER (TIME SERIES), time`
I'm using the transform feature instead of a better flux query as I want to use a live data provider later on, which 
is not capable of transforming data this way. 
For simplicity of this example, I'm using a flux query, as it shows the same behaviour.


### Panel Config
Selecting `Series (0)`, __X Field__ is assigned to `value {..., name="AccelY"}` and __Y Fields__ is then automatically set to
`value {...name="AccelX"}` by grafana.

I'm entering __soft min/max__ values, as well as specific overrides for the data mapped to y- and x-Axis.
Overrides are created with `Fields with name` for `AccelY` and `AccelX`.


### Issue
While the y-Axis is limited according to the entered soft limits, the x-Axis is completely ignoring this setting.
Other axis settings, like `Label` or `Scale` are applied to both axis, even when not using any overrides.


### Panel JSON
You can see the config of my panel below (`Inspect->Panel JSON`)

```json
{
  "datasource": {
    "uid": "bcfb08ca-30a6-4f55-8735-fb6ddf7b70fe",
    "type": "influxdb"
  },
  "type": "xychart",
  "title": "Panel Title",
  "gridPos": {
    "x": 0,
    "y": 8,
    "w": 13,
    "h": 16
  },
  "id": 2,
  "options": {
    "seriesMapping": "auto",
    "series": [],
    "tooltip": {
      "mode": "single",
      "sort": "none"
    },
    "legend": {
      "showLegend": true,
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    },
    "dims": {
      "x": "value {ECU=\"INS\", host=\"lnx_server\", name=\"AccelY\"}"
    }
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "show": "points",
        "pointSize": {
          "fixed": 5
        },
        "axisPlacement": "auto",
        "axisLabel": "Test",
        "axisColorMode": "text",
        "axisBorderShow": false,
        "scaleDistribution": {
          "type": "linear"
        },
        "axisCenteredZero": false,
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "axisSoftMin": -25,
        "axisSoftMax": 25,
        "axisWidth": 0
      },
      "color": {
        "mode": "palette-classic"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "value": null,
            "color": "green"
          },
          {
            "value": 80,
            "color": "red"
          }
        ]
      }
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "value {ECU=\"INS\", host=\"lnx_server\", name=\"AccelX\"}"
        },
        "properties": [
          {
            "id": "custom.axisSoftMin",
            "value": -25
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "value {ECU=\"INS\", host=\"lnx_server\", name=\"AccelY\"}"
        },
        "properties": [
          {
            "id": "custom.axisSoftMin",
            "value": -25
          }
        ]
      }
    ]
  },
  "targets": [
    {
      "datasource": {
        "type": "influxdb",
        "uid": "bcfb08ca-30a6-4f55-8735-fb6ddf7b70fe"
      },
      "refId": "A",
      "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AccelX\" or r[\"_measurement\"] == \"AccelY\")\r\n  |> filter(fn: (r) => r[\"ECU\"] == \"INS\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
  ],
  "transformations": [
    {
      "id": "joinByField",
      "options": {
        "byField": "Time",
        "mode": "outer"
      }
    }
  ]
}
```

**Comment by IdjazB** [comment]
@tonypowa @leeoniya whats the status on the above? are we able to adjust the x-axis of XY Chart using the max/min overrides? Seems it still only adjusts the y-axis. Any advice would be much appreciated, thank you

**Comment by nastynaz** [comment]
Any updates on this? Would be a very useful feature to have.
