### ISSUE TITLE
Dynamic MySQL Query Variable based on Selected Prometheus Data Source in Grafana

### ISSUE THREAD

**Issue by sys0613** [grafana/grafana#78666]
I have a Dashboard in Grafana with a Prometheus data source variable named $privatePromDataSource, which corresponds to three Prometheus data sources—AA, BB, and CC. The variable is used to dynamically switch between these data sources in the Dashboard.

Now, I want to define a second variable called $system_name, which is a Query type. The intention is to query MySQL with the statement select distinct system_name from kc_grafana_nginx_info where state=1 and data_source = $privatePromDataSource. The goal is to dynamically obtain system_name based on the selected Prometheus data source.

However, it seems that the filtering with data_source = $privatePromDataSource is not taking effect, and I'm getting results for all system_name values instead of those specific to the chosen Prometheus data source.

Is there a way to achieve dynamic parameter passing from the selected Prometheus data source to a MySQL query variable in Grafana?

**Comment by usmangt** [comment]
Hi @sys0613,

Thanks for opening this issue. This sounds more like a question as how to use Dynamic dashboard variables.

Please create a new post at our community forums in the [Dashboard category](https://community.grafana.com/c/support/dashboards/61) by providing the same details (in case if you missed any, provide that as well) so that our community members can help you out.

For now I am closing this issue, but feel free to reach back if you cannot find the working solution

Thanks
