### ISSUE TITLE
Inappropriate status code for calling the dashboard import API with an invalid payload

### ISSUE THREAD

**Issue by mengjie-ms** [grafana/grafana#78878]
### What happened?

 Calling the import API with an invalid payload – it seems a user error, but gets 500 response code on error. 

| msg      | error | method | path | status code|
| ----------- | ----------- |--------| ----------- | ----------- |
| Failed to save dashboard     | Dashboard input variable: DS_PROMETHEUS missing from import command | POST| /api/dashboards/import| 500|

### What did you expect to happen?

Return correct status code, not 500.

### Did this work before?

no

### How do we reproduce it?

see above

### Environment (with versions)?

Grafana: 9.5.13
OS:
Browser:

### Grafana platform?

None

**Comment by tonypowa** [comment]
hi @mengjie-ms 

Thank you for reporting this issue
I can't find any reference to the endpoint `/api/dashboards/import`  in our docs.
Could you share the link to the docs, and also share an example of an invalid payload?

This will help me reproduce this issue before I can forward it to the engineering team
Thank you

**Comment by jim-du** [comment]
Hi @tonypowa,

Thank you for looking into this issue.

The API `/api/dashboards/import` is served by Grafana backend [here](https://github.com/grafana/grafana/blob/505196bcd5043d57355e7134f89963c71b54d969/pkg/services/dashboardimport/api/api.go#L40C14-L40C14), and used by Grafana frontend in various places. One most visible place is the "import dashboard" page (`//<grafana>/dashboard/import`).

For our specific case, we don't know with 100% certainty where the request originates, since the request is sent by our customer. However, I suspect that the request is made by one of our custom tools.

Under this assumption, I was able to reproduce the issue with the following steps:

1. Run Grafana 10.2.3 (other versions should also work) OSS docker container with default settings
2. Set up a Service Account with Admin permission, and generate an API token.
3. POST [payload.json](https://github.com/grafana/grafana/files/13863128/payload.json) as body to `/api/dashboards/import` endpoint, authorized using the above bearer token. (You could use cURL, Postman, Insomnia, or similar tools.)

Note that `payload.json` is a minimized payload just for reproduction purposes. It is purposely crafted to **not provide an `input` array**, which causes the error below:

```
logger=context userId=2 orgId=1 uname=sa-test t=2024-01-08T15:36:19.699625836Z level=error msg="Failed to save dashboard" error="Dashboard input variable: DS_PROMETHEUS missing from import command" remote_addr=172.17.0.1 traceID=
logger=context userId=2 orgId=1 uname=sa-test t=2024-01-08T15:36:19.69970753Z level=error msg="Request Completed" method=POST path=/api/dashboards/import status=500 remote_addr=172.17.0.1 time_ms=19 duration=19.689624ms size=51 referer= handler=/api/dashboards/import
```

Given the nature of this problem that it involves an undocumented API and a customized client tool, I will leave it to Grafana team's judgment to determine if it can be categorized as a user error.

**Comment by taleena** [comment]
Hey all, with the repro steps above, I've added this to the manage dashboards area and put it in that project. If this is incorrect, please redirect to the right spot.

**Comment by natellium** [comment]
@grafana/backend-platform is this something you could help with?

**Comment by taleena** [comment]
I moved this into discovery - could it be possible to plan for this in Q2?

**Comment by taleena** [comment]
Thanks for getting this done!

**Comment by undef1nd** [comment]
@taleena no problem. 
The version mentioned in the issue description is 9.5.13, but I don't think this change can be backported to 9.x version - we only support security and critical bug fixes for it, iirc.

**Comment by taleena** [comment]
No expectation to backport beyond that, thank you for clarifying!
