### ISSUE TITLE
[Bug] Documentation mismatch for disabling alerting configuration (4.2.0)

### ISSUE THREAD

**Issue by jaimegago** [grafana/grafana#7900]
At time of filing latest stable is 4.1.2. There is a discrepancy between the configuration documentation and the 4.1.2 defaults config file, namely the doc refers to [alerting] enabled which is a setting only available on 4.2.0 default config file which is still in beta.

http://docs.grafana.org/installation/configuration/ vs https://github.com/grafana/grafana/blob/v4.1.2/conf/defaults.ini#L397 and https://github.com/grafana/grafana/blob/v4.2.0-beta1/conf/defaults.ini#L410

**Comment by torkelo** [comment]
yes, we should have a note about that. We accidentally pushed 4.2 docs prematurely. 

Releasing 4.2 stable tomorrow however. 

Need to add version support to our docs. It's close to broken since we upgraded docs system to use hugo which made version management next to impossible, but think I have a way to do that.
