### ISSUE TITLE
[Feature Request] Slanted X-Axis Values

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#7901]
Hi,

Just wanted to suggest whether there's a possibility of an option that can enable values on the X-axis to be shown in a slanted manner rather than a straight one? 

For example, if I'm using a bar graph showing the response time of several APIs (say 20-30), and I've enbaled the x-axis to show the names of each of the API under it's respective bar. An example of an API name is GET_Login_Screen. 

![image](https://cloud.githubusercontent.com/assets/10860168/24183847/bc4f6362-0ef0-11e7-8856-9c1a3cc08ec0.png)
So you can see that each of the names on the X-Axis, since there are so many of them, they get cramped up. As of now I'm using the Legend to display the x-axis values on the right hand side as a table and disabled the x-axis below the graph. But just as a request, if possible, is there a way to have them on the x-axis bar but in a slanting (rather than straight) manner so that all the API names fit?

Not the best picture, but something like this?

![image](https://cloud.githubusercontent.com/assets/10860168/24183939/48d0554e-0ef1-11e7-9ccf-ce2087a0e1a5.png)

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
