### ISSUE TITLE
Dashboards: Grafana's undocumented feature which interprets a custom unit as an internal unit ID is confusing

### ISSUE THREAD

**Issue by nodakai** [grafana/grafana#79055]
### What happened?

I input `bps` [1] as a custom unit but it was interpreted as an internal ID for "bits/sec", without any explanations on the behavior

![Screenshot 2023-12-05 at 4 04 33 PM](https://github.com/grafana/grafana/assets/90726/2c0a9b40-50c8-41ca-9018-cbe29fc140ce)

![Screenshot 2023-12-05 at 4 05 31 PM](https://github.com/grafana/grafana/assets/90726/fb605cf9-7f05-4b75-80d0-33065d5f0b21)

[1] https://www.investopedia.com/ask/answers/what-basis-point-bps/

### What did you expect to happen?

Essentially, I expected what's equivalent to `suffix: bps`

https://grafana.com/docs/grafana/latest/panels-visualizations/configure-standard-options/#custom-units

### Did this work before?

N.A.

### How do we reproduce it?

See above

### Environment (with versions)?

Grafana: Grafana v10.2.1 (533a733e4eda44041e43358c5a51203e9b42c9ea)
OS:
Browser:

### Grafana platform?

Docker

**Comment by natellium** [comment]
Hey @nodakai thanks for reporting this. Looking into it the issue, it is not only related to bps but any custom unit that has the same key as an internal one. For example, if we try to use a custom unit called `humidity` it'll always show  as `%H`. 

In the [UnitPicker component](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/UnitPicker/UnitPicker.tsx#L52) you can see the way we're showing the custom value is by checking if it exists in the list of internal units. And I would actually imagine this is the same for any other select that has the custom value option... With all this, I'm actually not sure if this is by design, @torkelo do you know? I do agree it can be confusing.
