### ISSUE TITLE
[Feature Request] Allow to set different ImageBaseUrl for WebDAV upload and image link

### ISSUE THREAD

**Issue by fir4** [grafana/grafana#7914]
Version: 4.2.0

I've been attempting to setup Grafana Notifications and use the public image upload. Currently, there are two different providers for uploading public images : S3 API and WebDAV.
My first thought was: Hey, that's cool, it supports WebDAV so i can throw them into Owncloud !
Unfortunately, while the upload works, Grafana sends notifications with the same URL as upload, which requires the user viewing the image to be logged in as the same user than the one uploading it.

Owncloud WebDAV endpoint looks like this:
   [owncloud-fqdn]/remote.php/webdav/[folder-path]/[file-name.png]

Once the file is uploaded in a shared folder, however, to access images without login requires a different URL:
   [owncloud-fqdn]/index.php/apps/files_sharing/ajax/publicpreview.php?x=[dimension]&y=[dimension]&a=true&t=[public-folder-share-token]&file=[file-name.png]

While in this usecase i'm using Owncloud, there are probably other providers which specify different endpoints for accessing and uploading. Simply allowing them to be set in config could be beneficial in this case.

**Comment by arodland** [comment]
This could be as useful for S3 as it is for DAV; it's possible to have an S3 bucket set to a custom domain name, or used as the backend for a CloudFront instance.

**Comment by phal0r** [comment]
@fir4 @daniellee 
I am having the exact use case right now with netcloud. Structure of the url is the same and this issue is not solved out of the box with the implemeneted solution, cause the filename needs to be passed as query parameter, not as path parameter.

To be more flexible wouldn't it be nice to be able to use placeholder? The code part which generates the complete public url could first check for a [fileName] placeholder and if none is found fall back to appending it to the path. What do yout think?

Meanwhile I solved it with a custom url rewrite in my haproxy:
```
acl is_grafana_request path_beg -i /publicpreview/
http-request set-query %[query]&file=%[path,regsub(/publicpreview/,)] if is_grafana_request
http-request set-path /index.php/apps/files_sharing/ajax/publicpreview.php if is_grafana_request
```

Grafana is configured with the public url `[owncloud-fqdn]/publicpreview/?[all query params except file]`

et voila, it works. But still would be better to have this working out of the box :)
