### ISSUE TITLE
Grafana web ui: Reverse proxy issue after >= 10.2.1

### ISSUE THREAD

**Issue by Azim-Azizov** [grafana/grafana#79241]
### What happened?

After update to 10.2.2 from 10.2.0 reverse proxy stopped working. Checked again with previous (10.2.1) and not working in that version as well. Versions before that function correctly.

Here is my nginx configuration:

```
# this is required to proxy Grafana Live WebSocket connections.
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

upstream grafana {
  server localhost:3000;
}

server {
  listen 80;

  server_name domain.com;

  location /grafana/ {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://grafana;
  }

  # Proxy Grafana Live WebSocket connections.
  location /grafana/api/live/ {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Host $http_host;
    proxy_pass http://grafana;
  }
}
```

Grafana config.ini differences from default:
```
domain = domain.com
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = true
```

### What did you expect to happen?

Being able to seeing login page.

### Did this work before?

Yes, before version 10.2.1

### How do we reproduce it?

1. Install grafana locally.
2. Create reverse proxy in nginx with subpath enabled (e.g. /grafana)
3. Configure grafana with your domain, root_url and subpath true accordingly.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: >=10.2.1
OS: Linux Ubuntu 22.04 LTS
Browser: Google Chrome desktop Latest at this moment

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Loki (doesn't matter in my case)

**Comment by usmangt** [comment]
Hi @Azim-Azizov,

I am closing this issue here on GitHub, as it seems more of a question.

Please create a new post at our community forums in the [Configuration category](https://community.grafana.com/c/support/configuration/20) by providing the same details (in case if you missed any, provide that as well) so that our community members can help you out.

You can also search in the Community forums as this question has been asked many times and the community members provided multiple solutions.

If incase your issue does not get solved, then let me know and I will be happy to reopen it.

Thanks

**Comment by Azim-Azizov** [comment]
Hello again. Actually, the issue was all about Cloudflare minifier malfunction.
