### ISSUE TITLE
Migration Issues from 8 to 9

### ISSUE THREAD

**Issue by thunderbird86** [grafana/grafana#79298]
### What happened?

There is no way to migrate Grafana 8.5.13 to any of Grafana 9 versions with Postgres backend.
It works if only the database is empty. If it contains data (dashboard, alerts, etc) after updating to grafana 9.0.x () it skipp all migrations. Running versions higher also skips migrations, but also fails to start with errors related to missed relations in the database  (e.g. secrets, correlations, etc)

### What did you expect to happen?

Update Grafana  8.5.13 to Grafana 9

### Did this work before?

Don't know

### How do we reproduce it?

1. Run Grafana 8.5.13 with Postgres backend
2. Fill with data (dashboards, alerts, datasources, etc)
3. Update to Grafana 9

### Environment (with versions)?

Grafana:  8.5.13
OS: docker image 
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus, elasticsearch, cloudwatch

**Comment by usmangt** [comment]
Hi @thunderbird86,

I would recommend that you ask this question at our community forums in the [Configuration category](https://community.grafana.com/c/support/configuration/20) by providing the same details (in case if you missed any, provide that as well) so that our community members can help you out.

Grafana OSS ver. 8 is no longer supported so will be not possible to get help from the Engineers. However, we do have some experts in the community forum who can give you hint in the right direction. For e.g. there is this [post](https://community.grafana.com/t/how-to-move-migrate-grafana-to-a-newer-version-system-on-a-local-container-environment/13822) that explains multiple scenarios for Docker, local-vm, Kubernetes

Thanks
