### ISSUE TITLE
[Feature request] Plotting option for "stepped" staircase graphs

### ISSUE THREAD

**Issue by Sineos** [grafana/grafana#7941]
I'm using Grafana mainly to plot consumption values from my home, e.g. power, solar yield, water consumption etc.

When using impulse meters (e.g. [S0 meters](https://www.sbc-support.com/uploads/tx_srcproducts/Applicationnote_S0puls_output_EN_V1.1_01.pdf)) I noticed that the stepped mode in Grafana will plot them in a way that, at least graphically, suggests a wrong value:
![grafik](https://cloud.githubusercontent.com/assets/4459312/24323170/26f0507c-1172-11e7-88bd-d2f23388fe08.png)

- At time 2 the impulses give a power value of 10
- We assume between time 1 and time 2 we had: Work = Delta(t) x 10
- The "test left" graph is wrong here, since for the same time it would give a Work of 0
- As of today, Grafana plots "test left" for stepped graphs

"test left" style is suitable for counters or sensor that transmit absolute values only when they have changed.

"test right" style would be needed where values are calculated according to the time between two readings / impluses, i.e. for most enegry or consumption monitoring use cases.

I would like to ask for an option, that switches between the two styles for stepped graphs.

**Comment by phelicksen** [comment]
I'm also interested in this.
I'm graphing energy consumption, so when using staircase or bar graph mode, I would like a data point to be rendered for the time period ((now-x) -> now) where x is the group by time value

**Comment by ioanszilagyi** [comment]
https://github.com/grafana/grafana/issues/6986

**Comment by alexism7hz** [comment]
Hi, 

I'd like to make a contribution that might help as a little trick, because this feature is not released yet. 

I'm computing 5-minute average values of a sensor giving data every second. Considering the following data points:
- Between 10:45AM and 10:50AM, `averageValue = 106.9` (**so the 10:45 to 10:50 period should have the value 106.9**)
- Between 10:50AM and 10:55AM, `averageValue = 105.7` (so the 10:50 to 10:55 period should have the value 105.7)
- Between 10:55AM and 11:00AM, `averageValue = 105.8` (so the 10:55 to 11:00 period should have the value 105.8)

In my database, I have in every row the timestamp of the beginning (`timestamp_begin`) and the end (`timestamp_end`) of the 5 minutes period, with the corresponding `averageValue`.

I ran two queries:
- In yellow: I query the data by selecting `timestamp_begin`
- In green: I query the data by selecting `timestamp_end`

You can see in the picture that the yellow one (selecting the timestamp of the beginning of the period) displays correctly what I want (_test_left_ of @Sineos I guess), whereas the green one (selecting the timestamp of the end of the period) displays what is described as _test_right_ by @Sineos.

![image](https://user-images.githubusercontent.com/45498062/73092264-41f29200-3eaa-11ea-9085-9b58e7d7e21b.png)

**Comment by leeoniya** [comment]
this will be available in the new graph panel. see https://github.com/grafana/grafana/pull/29593.
