### ISSUE TITLE
Generic_OAuth: Cannot assign GrafanaAdmin 

### ISSUE THREAD

**Issue by lesh3000** [grafana/grafana#79450]
### What happened?

Cannot assign GrafanaAdmin role with the following settings:

```
allow_assign_grafana_admin = true
skip_org_role_sync = false
oauth_skip_org_role_update_sync = true
```

In detalis:
I map user AD roles using `generic_Oauth` 
here are the settings:
```
################################### Generic OAuth ##########################
[auth.generic_oauth]
enabled = true
name = Account
allow_sign_up = true
client_id = ************************
client_secret = **************************
scopes = openid email profile
;empty_scopes = false
;email_attribute_name = email:primary
;email_attribute_path =
;login_attribute_path =
;name_attribute_path =
;id_token_attribute_name =
auth_url = https://login.microsoftonline.com/*************************/oauth2/authorize
token_url = https://login.microsoftonline.com/****************************/oauth2/token
;api_url = https://foo.bar/user
;teams_url =
;allowed_domains =
;team_ids =
;allowed_organizations =
role_attribute_path =  contains(roles[*], 'GrafanaAdmin') && 'GrafanaAdmin' || contains(roles[*], 'Viewer') && 'Viewer'
role_attribute_strict = false
;groups_attribute_path =
;team_ids_attribute_path =
;tls_skip_verify_insecure = false
;tls_client_cert =
;tls_client_key =
;tls_client_ca =
;use_pkce = false
;auth_style =
allow_assign_grafana_admin = true
skip_org_role_sync = false
oauth_skip_org_role_update_sync = true
```
______________________________________________________

When checking logs I see

```
oauth.generic_oauth t=2023-12-13T10:55:07.103445987Z level=debug msg="Received id_token" raw_json="{...........................\"roles\":[\"GrafanaAdmin\"],...........................................}" data="Name: Global_1 testuser, Displayname: , Login: , Username: , Email: global2@************, Upn: uit2363@**************8, Attributes: map[]"
logger=oauth.generic_oauth t=2023-12-13T10:55:07.103482915Z level=debug msg="Getting user info from API"
logger=oauth.generic_oauth t=2023-12-13T10:55:07.103646402Z level=debug msg="No api url configured"
logger=oauth.generic_oauth t=2023-12-13T10:55:07.103662072Z level=debug msg="Processing external user info" source=token data="Name: Global_1 testuser, Displayname: , Login: , Username: , Email: global2@*************, Upn: uit2363@**********, Attributes: map[]"
logger=oauth.generic_oauth t=2023-12-13T10:55:07.103682298Z level=debug msg="Setting user info name from name field"
logger=oauth.generic_oauth t=2023-12-13T10:55:07.103697567Z level=debug msg="Set user info email from extracted email" email=global2@******************
logger=oauth.generic_oauth t=2023-12-13T10:55:07.104141778Z level=debug msg="Defaulting to using email for user info login" email=global2@******************
logger=oauth.generic_oauth t=2023-12-13T10:55:07.104165379Z level=debug msg="User info result" result="Id: O3a_urUs7tiqu8NF6_fFQ7G8ngV51tenI3yf0u1wOsY, Name: sysex_Global_1 testuser, Email: global2@**********, Login: global2@**********, Role: Admin, Groups: []"
```
### What did you expect to happen?

The user supposed to have grafanaAdmin role, but when I access the UI I see it has only Viewer access

### Did this work before?

It worked when assigning Admin role, but with GrafanaAdmin it does not work

### How do we reproduce it?

1.install latest version
2.create AD user and assign it with GrafanaAdmin role
3. login with this user, reproducing the following config

### Environment (with versions)?

Grafana:10.2.2
OS:
Browser:

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by usmangt** [comment]
Hi @lesh3000,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by linoman** [comment]
Hello @lesh3000 

I'd like to apologize for the late reply. I've researching the issue and I have some comments and I'll be adding some suggestions for you to consider.

The log information you provided, shows the `Role: Admin` is being assigned correctly.

```
logger=oauth.generic_oauth t=2023-12-13T10:55:07.104165379Z level=debug msg="User info result" result="Id: O3a_urUs7tiqu8NF6_fFQ7G8ngV51tenI3yf0u1wOsY, Name: sysex_Global_1 testuser, Email: global2@**********, Login: global2@**********, Role: Admin, Groups: []"
```

GrafanaAdmin and Admin role are labeled the same in the user's profile page. However, in order to verify the user has the Grafana Admin role, head over the user's details page (example: http://localhost/admin/users/edit/1) and there you can see under the permissions section if the user is a Grafana Admin.

From the look at your Grafana settings, everything looks correct. However, the settings in your Azure AD tenant/application might provide some insight on what the problem might be. We need to validate the configuration of the `appRoles` attribute stored in the application manifest as described [here](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/azuread/#assign-server-administrator-privileges).

### Suggestions
1. Ensure the configuration of the `appRoles` includes the Grafana Admin role.
2. Double check what roles are being assigned in the user's details page.
3. Instead of using Generic OAuth, use the Azure OAuth integration.
  1. Most of the attributes are the same.
  2. You won't need to configure role mapping with `role_attribute_path` since the integration handles this.

Let us know if these suggestions are helping you or what problems are you finding.

Have a great day!

**Comment by linoman** [comment]
Hello @lesh3000. Do you need more assistance with this topic?

**Comment by linoman** [comment]
closing inactive issue
