### ISSUE TITLE
Cloudwatch: Metric Search "Code" and "Builder" modes have different behavior

### ISSUE THREAD

**Issue by anurag-patnaik** [grafana/grafana#79489]
### What happened?

It looks like Metrics Search > Code is using Metrics Insights query, which gives different output from Metrics Search > Builder results.

**Example**
**Metrics Search - Code**
<img width="1115" alt="metric_search_code" src="https://github.com/grafana/grafana/assets/949305/61934237-2c52-4cb9-b44f-4451bc16bcba">

**Metrics search - Builder**
<img width="1119" alt="metric_search_builder" src="https://github.com/grafana/grafana/assets/949305/a6214cab-7e68-4fc3-b4de-b9c67e6ec2e5">

Note how in "Code" mode, the values are calculated in the 400Ks, while in the "Builder" mode the values are calculated in the 200Ks. 

**Root Cause**
This is because "Code" uses Metrics Insights query which aggregating all 3 time series into a single time series result. To get the same result as "Builder", the user needs to add an additional "GROUP BY" clause.

### What did you expect to happen?

The expectation is to have both "Code" and "Builder" modes produce the same output.

### Did this work before?

Unsure if this was different before.

### How do we reproduce it?

1. Create a CW Metrics query using Builder mode and aggregate values by SUM() as shown in screenshots above.
2. Run the same query in Code mode
3. Results are different in Code and Builder

### Environment (with versions)?

Grafana: 9.4
OS: macOS
Browser: Chrome

### Grafana platform?

None

**Comment by zspeaks** [comment]
Issue is also observed on grafana version 8.4

**Comment by sarahzinger** [comment]
Hey there,

I am able to recreate the differences you're seeing in these graphs and agree the UI here it's a bit confusing, but I'm not sure I follow what the ask here is for us to change on our end. We're a bit limited to whatever is offered from the AWS-SDK. 

Let me know if I'm missing anything but it seems like the only available endpoint for us to get metric math information (aka metric search) is from the [GetMetricData](https://pkg.go.dev/github.com/aws/aws-sdk-go/service/cloudwatch#CloudWatch.GetMetricData) function, which is pretty explicit that `A Metrics Insights query without a GROUP BY clause returns a single time-series (TS), and can be used as input for a metric math expression that expects a single time series`. 

When we use the default Metric Builder (Metric Search), we are attempting to recreate the default metrics you'll see on the AWS Console (I believe these are called Metric Insights). In order to do that using the API available. We need to make a Metric Search Query. You can see what that Metric Search Query is under the hood using the Query Inspector:
<img width="1381" alt="Screenshot 2023-12-21 at 2 58 56 PM" src="https://github.com/grafana/grafana/assets/6620164/14caa21a-a78c-4dbc-8946-0480e9b6554f">

If you then use that in the "Code" editor you'll get the same results.

However I think what you may be looking for is the `Metric Query Tab` rather than the `Metric Search` tab:

<img width="1072" alt="Screenshot 2023-12-21 at 2 49 00 PM" src="https://github.com/grafana/grafana/assets/6620164/27fc4a3f-11c7-4e99-b4b0-3f1c471cc95a">

<img width="1360" alt="Screenshot 2023-12-21 at 2 48 05 PM" src="https://github.com/grafana/grafana/assets/6620164/bc5b83d9-6365-4863-8f1b-ecd46288cb6f">

The Metric Query Tab will let you write Metric Queries using SQL with the correct syntax highlighting, and when you use the Builder it will actually show you precisely what the SQL is you're writing, with optional ability to add a Group By clause if you'd like. 

I wonder if this could be made more clear by calling these things names that better match that in the AWS Console? Let us know if you have any suggestions or if I'm missing anything!

**Comment by sarahzinger** [comment]
Going to close this due to inactivity. I think this is "as designed" but let us know if there's anything we're missing or if you have suggestions for improvement! I suspect there might be some kind of UX fix we could do to make this more clear.

**Comment by Dawn9419** [comment]
Hello team,

I am new to the GitHub community. Please let me know whether it is appropriate to reopen this issue or if I should create a new one instead.

Could you also explain the difference between "MetricsSearch" and "MetricsQuery"? In the alert rule editing console, I followed the instructions to use "MetricsQuery". However, I noticed that in the expression part, the Lambda function identifier is displayed as "series0":

![Screenshot 2024-02-07 at 1_mosaic(2)](https://github.com/grafana/grafana/assets/65911014/fc687c91-edfa-4980-a426-dbe2f52a787b)

When I use "MetricsSearch" and select "FunctionName" as the dimension, the expression part correctly displays the function name:

![Screenshot 2024-02-07 at 1_mosaic(1)](https://github.com/grafana/grafana/assets/65911014/3554c61b-dbc1-41cf-a853-9f13d843474a)

I would appreciate your guidance in explaining the differences between these two and advising on how to obtain the correct identifier through the code method.

Thank you for your assistance.
