### ISSUE TITLE
grafana Unauthorized problem

### ISSUE THREAD

**Issue by sLuvpreet33** [grafana/grafana#7965]
![screenshot from 2017-03-28 15-16-45](https://cloud.githubusercontent.com/assets/23127804/24399220/b05849ce-13c9-11e7-80de-fed08b2aea6f.png)

Grafana was working normal, and then suddenly, this has come up, and It is kind of like freezed on this screen.

Why is this happening and what is its solution ?

**Comment by torkelo** [comment]
depends on what your data source is and how you authenticate against it. Is your data source working?  Check chrome dev console network tab for details on why your data source is not working.

**Comment by sLuvpreet33** [comment]
yeah thats ok, I have to reload the grafana page, log in and then it works fine.

But it is happening frequently (like in every 10 mins), so I have to refresh it every 10 mins, and then log in again, why so?

**Comment by torkelo** [comment]
not sure, maybe a problem with your auth mechanism? or session store?

**Comment by sLuvpreet33** [comment]
okay, where I can find the root of this problem and how do we solve that?

**Comment by torkelo** [comment]
check network traffic, cookies, grafana.log, disk permissions on grafana server for sessions, what are you using for auth? etc

**Comment by sLuvpreet33** [comment]
I am using the default user made by grafana,

user- admin
password -admin

**Comment by wavded** [comment]
I also have this problem, charts will work and eventually you'll get an unauthorized for the whole page.

**Comment by daniellee** [comment]
Sounds like you are getting logged out and is therefore a session problem. Could be something to do with your cookies. The session id is stored in a cookie. Are you losing your cookies (plugin that blocks them maybe? I see that you have uBlock.)?

**Comment by Andysimcoe** [comment]
I'm plagued by this, sometimes there's a whole stack of them down the screen. The only difference is it's a red box. 

I thought it may have been due to the sqlite database as all users see these boxes. Deployed a new container, configured for postgres, no data sources added to it yet and saw one... 

Logs don't say anything so I guess from the above I might be able to play with the session settings in grafana.ini? 

![grafana-unauth](https://user-images.githubusercontent.com/42643041/51759709-bf7d9980-20c0-11e9-85e8-f8e2bcd26198.PNG)
