### ISSUE TITLE
[Feature request] - template variable delimiter

### ISSUE THREAD

**Issue by Boolman** [grafana/grafana#7966]
I would like to have the option to change delimiter in Manage Dashboar - Templating - Variables.
as you can see in the pictures, my regex breaks due to the delimiter. 

![screen shot 2017-03-28 at 12 57 10](https://cloud.githubusercontent.com/assets/9446644/24401869/6d5d3c3c-13b6-11e7-9fc4-d582ed0bb241.png)
![screen shot 2017-03-28 at 12 57 30](https://cloud.githubusercontent.com/assets/9446644/24401872/74c84f16-13b6-11e7-8171-d862135e8629.png)

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
