### ISSUE TITLE
Why does Grafana add a $timefilter and fill(null) to my query?

### ISSUE THREAD

**Issue by InH4te** [grafana/grafana#7967]
I'm running Grafana v.4.1.1. I'm using InfluxDB to store values.

I'm generating a JSON format from my application and sending it to Grafana to create the dashboard. However, if I send this as the target query: `"target": "SELECT "SOMEVALUE" FROM "MyMeasurement" WHERE "Key1" = abc AND "Key2" = bca AND \"id\" = 1007"`

and the rest of the JSON format is correct! But when I look at my graph via the UI, the query column is blank and when I toggle it to edit the query, I see the following query pasted instead.
`"SELECT "SOMEVALUE" FROM "MyMeasurement" WHERE "Key1" = abc AND "Key2" = bca AND \"id\" = 1007" AND $timeFilter GROUP BY time($interval) fill(null)`

When I remove the last timefiler, time and fill function, my graph looks perfect. But by default, why does this even get appended? And the group by block gets added to the JSON automatically. How do I change this automatic feature?

Much thanks!

**Comment by R-e-M** [comment]
Hello !
I had the same question some times ago but I finally found out what it mean, it aims to improve stability and performance of data plotting :
- WHERE $timeFilter refers to the time interval you choose to display in the top right corner. For example if you select only the last hour, $timeFilter replace time > now() - 1h. If you remove it, the display does not change but in the background grafana requests all the available data in influxDB, which can yield a lot of data and make your server/network/grafana slow/buggy.
- GROUP BY time($interval) refers to the text box edit>metrics>Group by time interval : in case of you wish to see a long time period, to avoid requesting too many data and so the above mentioned problems, influxDB can group your data by a time interval (based by default on the pixel size) and make an operation on it to reduce the number of data returned, as by default the mean.
- fill is attached to GROUP BY, as said by the doc : "By default, a GROUP BY interval with no data has null as its value in the output column. Use fill() to change the value reported for intervals that have no data. fill() options include:"

I also used to remove these parts before, but finally come back to it since it gives faster plotting. However, I don't know how to remove it from the default..

**Comment by eaglewu** [comment]
![image](https://user-images.githubusercontent.com/3753615/42082732-5a2142da-7bbb-11e8-848f-7e19726954f0.png)

The way to do it below:

![image](https://user-images.githubusercontent.com/3753615/42082705-4678179a-7bbb-11e8-85d7-472b363efde5.png)
