### ISSUE TITLE
State timeline with gap in data still display

### ISSUE THREAD

**Issue by Nikoos** [grafana/grafana#79675]
### What happened?

Hello Team, I am working on Grafana OSS v10.2.2 with InfluxDB2 datasource.

I need to draw HTTP status code through time and am using State timeline as my goto graph. I tested this graph behavior and seems to hit an issue with the "no data" behavior still being draw, even if no data has been stored.

To be complete, HTTP status code is pulled by Telegraf connected to HAProxy, I use this basic query : 

```
from(bucket: "LAB-HaProxy")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "haproxy")
  |> filter(fn: (r) => r["_field"] == "check_code")
```
I deliberately stopped backend to check if Grafana will show something, as we can see, in the raw data from the Table view, there is missing data (which is correct) : 

![image](https://github.com/grafana/grafana/assets/458388/17928237-78f0-4592-85b6-2f97644c3c55)

However when i switch to state timeline, there is no data gap or no data draw through time : 

![image](https://github.com/grafana/grafana/assets/458388/0b13b0a6-8d85-44dc-8253-d2b7c80ca9d5)
The blue rectangle should not have data, it should be empty in my opinion.

### What did you expect to happen?

Missing data should be empty not "connected".

I check on the state timeline configuration : 
![image](https://github.com/grafana/grafana/assets/458388/f3cb19bb-8735-4f1c-9039-cc18b92d0d79)

And settings seems to be OK.

### Did this work before?

it's the first time I have this issue since I installed Grafana (2/3 days ago)

### How do we reproduce it?

1. Create Influxdb2 data source, with data pulled from HAProxy via Telegraf (from EL7)
2. Create a dashboard.
3. Add a state timeline
4. Copy paste the following query : 
```
from(bucket: "LAB-HaProxy")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "haproxy")
  |> filter(fn: (r) => r["_field"] == "check_code")
```
5. Generate an outage on your HAProxy (poweroff) for 5 minutes
6. Poweron your HAProxy.
7. Wait to receive data from Telegraf (via Table view). confirm that there is a gap between data received from Telegraf
8. Switch to state timeline
9. Check if missing data is drawn (it is)

### Is the bug inside a dashboard panel?

```
{
  "datasource": {
    "type": "influxdb",
    "uid": "b66a88a8-390c-4723-b759-ed20fa33c4d7"
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "lineWidth": 1,
        "fillOpacity": 70,
        "spanNulls": false,
        "insertNulls": false,
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        }
      },
      "color": {
        "mode": "continuous-GrYlRd"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      }
    },
    "overrides": []
  },
  "gridPos": {
    "h": 8,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "id": 2,
  "options": {
    "mergeValues": false,
    "showValue": "always",
    "alignValue": "center",
    "rowHeight": 0.9,
    "legend": {
      "showLegend": true,
      "displayMode": "list",
      "placement": "bottom"
    },
    "tooltip": {
      "mode": "single",
      "sort": "none"
    }
  },
  "targets": [
    {
      "datasource": {
        "type": "influxdb",
        "uid": "b66a88a8-390c-4723-b759-ed20fa33c4d7"
      },
      "query": "from(bucket: \"LAB-HaProxy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"check_code\")",
      "refId": "A"
    }
  ],
  "title": "Panel Title",
  "type": "state-timeline"
}
```

### Environment (with versions)?

Grafana: 10.2.2
OS: Windows 10
Browser: Firefox

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Influxdb 2

**Comment by leeoniya** [comment]
grafana needs to be told what "missing" data is, since this is impossible for us to determine this without knowing whether the data points are expected to be regular (as with queries that aggregate over a known window / interval) or irregular (as random events over web socket).

there are a few ways to do this.

our panels treat `null` values in the data as indicators of gaps or discontinuity. if you insert one or more null values into that discontinuity, state timeline will show the gap. not sure if this is possible with influx, but you can maybe fill with 0 and then make 0 a transparent color in the panel settings. https://docs.influxdata.com/influxdb/cloud/query-data/flux/fill/
https://github.com/influxdata/flux/issues/2428

we also look at the time field's `field.config.interval` to do this null-fill when there are absent timestamps from data that is expected to be regular, as indicated by the interval. currently only the core Prometheus datasource returns this in the query response, however.

finally, the panels have a "Disconnect values" panel option (visible in your screenshot) with a threshold setting that allows you to manually configure this null insertion threshold. this should work for you. it does require a static value, so you have to know your data regularity in advance.

those are all the available options. hopefully one works for you :)

**Comment by Nikoos** [comment]
Hello @leeoniya ,

Thanks for your message. I was able to do what I wanted initially and use your third option : tweak the Disconnect values threshold. As I know that (normally) every 10 seconds, I should have a new record, if none is received for that 10s then a gap is displayed.

![image](https://github.com/grafana/grafana/assets/458388/296b2786-7173-4742-b1a0-b21cf091f8eb)

Indeed, it was not a bug, I will archive this issue
