### ISSUE TITLE
Cloudwatch: Investigate inconsistencies on meaning of "match exact" toggle

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#79764]
I'm not 100% convinced we have a bug here, but I've found myself a bit confused on the intended behavior of the "match exact" toggle in Cloudwatch. It seems like something that would be good to understand better and document what the intended behavior is in various scenarios, particularly as it relates to wildcard dimensions and dynamic labels.

Here's some results I've gotten back recently and some questions that I've had that I imagine others have as well. 

![Screenshot 2023-12-20 at 10 13 31 AM](https://github.com/grafana/grafana/assets/6620164/35ca9198-30ff-49c6-81d2-1b3dfb96b827)

| ~ | Match Exact is OFF | Match Exact is ON |
| ------------- | ------------- | ------------- |
| `*` selected | only data with that dimension existing shows, seems like this might be intentional, tho possibly confusing  | nothing shows (I guess makes sense because there is no literal value of *, but potentially confusing)  |
| no dimensions selected  | everything shows including time series that don't have that dimension label. Seems as expected | No data comes back. This seems confusing to me... I suspect this may be this is "correct" as there are no time series that do NOT have some kind of dimension value? But its a confusing ux experience  |

<img width="1289" alt="Screenshot 2023-12-20 at 10 23 38 AM" src="https://github.com/grafana/grafana/assets/6620164/a908f3e2-1204-4122-b124-b77ac1e490ab">

Above is the same metric, but a different dimension

| ~ | Match Exact is OFF | Match Exact is ON |
| ------------- | ------------- | ------------- |
| `*` selected | 11 time series on the graph | now only 8 show? Seems confusing, isn't this different behavior than what we see in the other table above? Why only 8?  |
| no dimensions selected  | 11 time series shows again | No data comes back, confusing but consistent with above  |

![Screenshot 2023-12-20 at 10 38 27 AM](https://github.com/grafana/grafana/assets/6620164/05c98295-534f-4d37-8db6-914de928a8a3)

| ~ | Match Exact is OFF | Match Exact is ON |
| ------------- | ------------- | ------------- |
| `*` selected | the same whether match exact is on or off | the same whether match exact is on or off, this seems inconsistent with the first example (but consistent perhaps with the second?)   |
| no dimensions selected  | we get more time series back because we now include time series that do not have autoscaling group names, seems potentially as expected?  | Very unclear why we get back this one time series. My only guess is that this could be the overall average?  But then why didn't the other 2 examples above do the same?  |

It would be good to spend some time figuring out:
- is this all expected behavior and why?
- if it is, let's document some various scenarios so others running into these issues might be able to better understand why/debug what they are seeing
- if it's not expected, is there a bug on grafana's side? Or is this reflective of inconsistencies with the cloudwatch api? If the former, let's create issues and fix, if the latter, let's reach out to our contacts there.

**Comment by iwysiu** [comment]
I looked into this and we do mention it in the [docs](https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/query-editor/#create-a-metric-search-query). However it's not super clear from the query editor itself (and I did misunderstand it while working on the wildcard dimensions).
For the backend details, basically when `MatchExact` is selected, we need to include every dimension in the query (even if its set to `*`) because we will create a `metric schema` (which from what i can tell, AWS never actually defines in their documentation, but I'm assuming is every dimension on a metric) that we pass as part of the [search expression](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/search-expression-syntax.html), and it will only return metrics with the same dimensions as described in the schema (no extras). When no dimensions values are selected for a given key, we don't send the dimension key to the backend and it doesn't get added to the `metric schema`. 
The reason that results still get returned when `MatchExact` is false is because we don't build the schema in that case, and the query we build in that case just has the `SearchTerm` part of the search expression (see the link above), which returns metrics that have the asked for dimensions without caring if there are any additional dimensions on the metric.

In summary: It does work as designed, and our docs do describe how the builder options affect the resulting query, but the info pop-up in the query editor is describing it poorly. `Match Exact` intuitively feels like it should be about dimension values, but it isn't and nothing in the editor explains that. For their part, the AWS docs do not explicitly ever explain that the `metric schema` has to contain all the dimensions on the metric and they should probably add that. I wouldn't change the behavior now (because its worked like this for a long time and I assume some users depend on it), but it would make sense to have pr that makes the query builder explain more clearly what it's for (and maybe change `Match Exact` to something like `Match Dimension Fields`? I feel like that name is also bad)
