### ISSUE TITLE
Grafana: Bar Gauge "Bar Size = Auto" broken in 10.2.3

### ISSUE THREAD

**Issue by perosb** [grafana/grafana#79797]
### What happened?

In grafana 10.2.3, the Bar Gauge `Bar Size` set to `Auto` doesn't work as before showing multiple scroll bars.
![Screenshot from 2023-12-21 15-24-30](https://github.com/grafana/grafana/assets/982752/1e9a1e02-38a1-4779-9017-a171934084ea)

### What did you expect to happen?

Auto sized bars as in 10.2.2 to fit the panel.

### Did this work before?

This is how it looks in 10.2.2
![Screenshot from 2023-12-21 15-23-55](https://github.com/grafana/grafana/assets/982752/742a60b8-b613-4812-8ba1-60ffc5874c88)

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 10.3.2
OS: linux
Browser: chrome 120

### Grafana platform?

Kubernetes

**Comment by perosb** [comment]
Maybe caused by https://github.com/grafana/grafana/pull/76042 ?

**Comment by Klionheart** [comment]
This is probably not going to be a surprise, but for completeness, note that this also applies to "Gauge" Panels, see example from a "Vanilla" node-exporter dashboard, otherwise untouched:
![grafana_10_2_3_gauge](https://github.com/grafana/grafana/assets/20490660/a0996ed8-d528-4677-858e-6ca83f503cc5)

Working fine in 10.2.2:
![grafana_10_2_2_gauge](https://github.com/grafana/grafana/assets/20490660/c34bf755-2f15-4581-88cc-943b22657265)

**Comment by Leviathan09** [comment]
Same Problem on my Dashboards
All my Gauge Panels and Bar Gauge Panels are now sized incorrectly. That new "Min hieght, Max height, Min width" stuff is poorly implementet.
Why the hell would someone keep the "Auto" function when it makes every Gauge Panel Auto-Crap-Looking
I have to edit now every single Panel and all my Dashboards.

Not amused !!!

**Comment by torkelo** [comment]
Really sorry we introduced this bug, we will get it fixed ASAP, a fix PR is already up https://github.com/grafana/grafana/pull/79926

**Comment by nmarrs** [comment]
Fixed by https://github.com/grafana/grafana/pull/79926 - fix will be available in v10.3

**Comment by harmv** [comment]
workaround in ubuntu (to wait for the fixed version)

```apt-get install grafana=10.2.2```
