### ISSUE TITLE
Cloudwatch: Dimension Labels Inconsistencies Bug with wildcard selected, Match Exact turned off, and an expression used

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#79809]
To Reproduce:

- Create a Cloudwatch Metrics query with 3 dimensions selected, and the third one is *
- Add an expression (I think any expression)
- Ensure match exact is turned off. 
- Notice that the label for the third wildcard dimension is inaccurate. I believe it is taking it from a different dimension possibility (so in the case below AutoScaling is the first Service option when the resource dimension is removed)

<img width="1387" alt="Screenshot 2023-12-21 at 12 40 57 PM" src="https://github.com/grafana/grafana/assets/6620164/2a57904a-2621-459e-947f-e902fac66e95">

Another example:
<img width="1082" alt="Screenshot 2023-12-21 at 1 01 46 PM" src="https://github.com/grafana/grafana/assets/6620164/d9441cc7-c23b-497c-8577-8aa2e90af4b7">

It's not much better when match exact is turned off:
<img width="1387" alt="Screenshot 2023-12-21 at 12 46 35 PM" src="https://github.com/grafana/grafana/assets/6620164/9594a33d-eeef-446f-8f21-982557895bf0">
seems to create some sort of uid? 

Confusingly this only happens sometimes. So far we've had reports of this happening with Kafka Metrics when the dimensions of Cluster Name, Consumer Group, and Topic is selected, and I've been able to reproduce it those in the screenshot above as well, but many times I can not reproduce it. Sometimes I'll select 3 and one of the labels is missing?

<img width="1098" alt="Screenshot 2023-12-21 at 12 59 52 PM" src="https://github.com/grafana/grafana/assets/6620164/eb920c87-f4ef-43f4-b6bc-8d1534bed6ef">

Other times it seems to work just fine?
<img width="1096" alt="Screenshot 2023-12-21 at 1 04 59 PM" src="https://github.com/grafana/grafana/assets/6620164/6da63bf7-1398-4d40-aaa5-25323f5786e3">

I'm not entirely clear what's going on, but I see we've had [challenges](https://github.com/grafana/grafana/issues/72172) with this in the past, so perhaps there's one more edge case here we've missed? 

Grafana Version: main (I was on commit 315dd757678282d9a621301ebb341d1943df57b4)

**Comment by sarahzinger** [comment]
Potentially connected/dupe? https://github.com/grafana/grafana/issues/69591

**Comment by iwysiu** [comment]
The behavior designed in the issue isn't really a bug (though the linked support escalation is running into an edge case on a workaround that I'll describe as the bottom).

For us getting different dimension values depending on which filters are already selected, that’s because we pass the filters along to AWS when we fetch the dimension values. Thus, when we ask for dimension values for Service with `Class=None` and `Resource=DBClusters` already selected, AWS only returns `RDS` because that’s the only dimension value available on Service for resources where the other two are true.

The match exact issue is only kind of an issue. We could change [this line](https://github.com/grafana/grafana/blob/2d1cd82a98e2e38376008529fe704e04cd67cf7a/pkg/tsdb/cloudwatch/response_parser.go#L95) to include a check for `query.MatchExact` to make it so that it sets label to `*` but I'm not sure if that’s ever a valid query that would actually get results (though AWS doesn’t error for it so maybe?)

Now for the edge case the support escalation is hitting: They’re hitting that because AWS doesn’t actually return the labels as individual labels, the way that they identify the different results is that they return the data with a single label that is either: 
1) All the dimension values appended with spaces (the default) 
2) User specified. 

We turn this single label into our separated labels by separately getting the dimension values and seeing if they’re substrings of that big label that AWS returns. What I suspect is happening in the linked ticket is that since `Contact` is also a valid dimension value for topic and a substring of the label they want, it’s being matched instead. I brought this issue up in the initial implementation [pr](https://github.com/grafana/grafana/pull/74847).
There are a few things we could try to do to improve it, though anything short of AWS actually just sending us the labels isn’t a 100% fix:
1. Be stricter about matching labels: check that they have whitespace/nothing to either side (though this might interact badly with custom labels, which do not guarantee this and we don’t expect this from existing user queries)
2. Always take the longest matching value (I have an example of how this could go wrong in the linked pr).
3. We’re currently are searching for the dimension values for the wildcards without filters, but if made them part of the query we can reduce the possible value matches, and the probability of a mismatch. However, this may increase how many dimension values queries we make for labeling purposes (though we are caching them to once a day so it shouldn’t be that bad)

Three is probably a good idea, and maybe 2.
(Before you ask, the only thing forbidden in dimension values are [control characters](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_Dimension.html), so we can’t space out the dimension values with a forbidden character to make parsing easier)

Though honestly I am confused as to how its working for them at all with match exact enabled, but I think investigating that is more part of the other issue.
