### ISSUE TITLE
Cloudwatch: Cannot Query for DB_PERF_INSIGHTS counter metrics

### ISSUE THREAD

**Issue by Vimao** [grafana/grafana#79829]
### What happened?

I tried querying Cloudwatch using the new metrics math function DB_PERF_INSIGHTS but unfortunately grafana returns absolutely no results, even though the cloudwatch console returns information for the same query.

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights_Counters.html

Result from Cloudwatch:

![image](https://github.com/grafana/grafana/assets/47415312/441b5c26-afdf-4e74-aee8-a89479ab2a77)

Result from Grafana:

![image](https://github.com/grafana/grafana/assets/47415312/795016bb-fa32-48f8-9888-10ce5ef674a9)

Query Information and results
[Cloudwatch_DB_PERF_INSIGHTS_query.json](https://github.com/grafana/grafana/files/13751668/Cloudwatch_DB_PERF_INSIGHTS_query.json)

### What did you expect to happen?

Time series returned with the information stored in cloudwatch

### Did this work before?

Did not try this before

### How do we reproduce it?

1. Create a Cloudwatch datasource for an account that has an RDS Database
2. Query that datasource with Metric Math Query using the DB_PERF_INSIGHTS

### Environment (with versions)?

Grafana: 10.2.3
OS: Ubuntu 22.04
Browser: Edge/Firefox

### Grafana platform?

A downloaded binary

### Datasource(s)?

Cloudwatch

**Comment by sarahzinger** [comment]
Hello, I was able to reproduce this issue on Grafana Cloud, but not locally on the latest main. I'm not sure yet if that's because there has been a fix deployed already, or if there's an error unique to grafana cloud? Will make sure someone from our team can investigate soon, thanks for reporting!

In Grafana Cloud:
<img width="1276" alt="Screenshot 2024-01-23 at 10 28 55 AM" src="https://github.com/grafana/grafana/assets/6620164/83d811ee-ee1f-4f7b-ba84-562634f8ee04">

Locally:
<img width="1401" alt="Screenshot 2024-01-23 at 10 31 05 AM" src="https://github.com/grafana/grafana/assets/6620164/bf372478-107c-4b13-8d80-f22a0f0bbd6a">

**Comment by vekien** [comment]
Hello, I am not getting any data on v10.3.3 and just wondering if this feature was added in a specific version? Tried many different `DB_PERF_INSIGHTS` options but never get any results.

**Comment by sarahzinger** [comment]
I think this is related to https://github.com/grafana/grafana/pull/84835 We'll bring it back to the team to see the best way to fix this, but in the meantime I believe if you disable the `cloudWatchNewLabelParsing` feature flag you should get back the old behavior and the query should work. 

Thank you for reporting and for your patience!

**Comment by iwysiu** [comment]
Hi @Vimao ! After investigating, I found that we need additional permissions for the `DB_PERF_INSIGHTS` metric, and it should work if you add `pi:GetResourceMetrics` to your IAM policy. Example json below:

```
{
	"Sid": "AmazonRDSPerformanceInsightsGetResourceMetrics",
	"Effect": "Allow",
	"Action": "pi:GetResourceMetrics",
	"Resource": [
		"*"
	]
}
``` 
We weren't passing the permission error, so it was failing. I'll put up a PR to fix the error handling and update the docs.
