### ISSUE TITLE
Grafana UI: QueryField removes part of the query when using the autocomplete function

### ISSUE THREAD

**Issue by eledobleefe** [grafana/grafana#79856]
This issue is created due to this escalation: 
[Splunk datasource - Editor issues with variable autocomplete (ARR $37K) #7856](https://github.com/grafana/support-escalations/issues/7856)

Issue: when the customer uses the autocomplete function of the variables part of the query is removed.

As commented [here](https://github.com/grafana/support-escalations/issues/7856#issuecomment-1858164329), it seems to be related to the [SuggestionPlugin](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/slate-plugins/suggestions.tsx#L166).

**Comment by ashharrison90** [comment]
think we've found the problem. we've fixed it with https://github.com/grafana/grafana/pull/81484. out of an abundance of caution, we've put this fix behind a feature toggle (`slateAutocomplete`) which defaults to on.

what this means for you as a consumer:
- this will be fixed in 10.4.0 without needing to do anything
- if you notice any **regressions**, please let us know!
- you can disable the `slateAutocomplete` toggle to revert to the old behaviour.
- this toggle will be removed fairly swiftly if we don't hear any negative feedback 👍
