### ISSUE TITLE
Dashboard List: Search Function Not Working After Enabling Subfolders

### ISSUE THREAD

**Issue by Dino1010** [grafana/grafana#79852]
### What happened?

![image](https://github.com/grafana/grafana/assets/48425373/b328a5ee-6d7f-4fcd-98f6-e53b94ab2199)
I encountered an issue while using the Dashboard List. I attempted to use Tags for searching, with Dashboards selected as my folder and the Subfolders option enabled. However, I found that the search function did not work as expected.

### What did you expect to happen?

Filter out the Dashboards with the tag "class".
Select a single folder  works to filter out Dashboards with the tag "class".

### Did this work before?

Disabling Subfolders works

### How do we reproduce it?

1. Enabling Subfolders　
2. Adding tags to the dashboard in Subfolders　
3. Using Dashboard List, filter tags under the Dashboards scope

### Environment (with versions)?

Grafana: 10.2.2
OS: linux
Browser: Chrome 120

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment]
hi @Dino1010 

Can you please double check if any of those dashboards that you are expecting to show up in your dashboard list panel have any tags in their settings?  For me it works well in Grafana v10.2.2 

![image](https://github.com/grafana/grafana/assets/45235678/bcfeda17-7784-4c4b-80ec-98258c36f134)

### However, 

*This is for the reviewer:*

In the process I have just found a, perhaps, unintended behavior of the tag search feature. If you use tags that match dashboards in conjunction with tags that don't, the result is an empty body

![pollo](https://github.com/grafana/grafana/assets/45235678/755586bb-ae8d-47b0-a847-dc7e099caedb)

In my test, the tag `pollo` was added to a dashboard, and hence the search does works. However the second tag `hola` does not match any . 
Inspecting the console I see that the API is chaining both search tags, resulting in a 200 OK requests, but that returns an empty JSON body.

`/api/search?limit=10&query=&tag=pollo&tag=hola&type=dash-db`
 
Perhaps the API should make separate requests or the receiving endpoint process the request differently ? 

Adding issue to the dashboard team for review

**Comment by ashharrison90** [comment]
thanks for reporting! 🙌 

can repro and confirm this is a problem. 

@tonypowa the behaviour with multiple tags is expected and working correctly. multiple tags are ANDed together, not OR.

**Comment by ashharrison90** [comment]
@Dino1010 just to give you a little bit of context...

1. when no folder is selected (i.e. the Folder dropdown is empty), a search request is performed against the whole database.
1. selecting a folder passes that `folderUID` as a parameter to the search request.
1. currently if a `folderUID` is specified, this **does not** recursively search children. it only ever searches the immediate children of that `folderUID`

so far this is all expected behaviour. but what is annoying/unexpected is that once you've selected a folder, you can never clear your folder selection to return to searching the whole database. i've fixed this as part of https://github.com/grafana/grafana/pull/81114

so the search behaviour will remain exactly the same, but you'll be able to clear your folder selection to allow showing results from the entire database. as a workaround in the mean time, you should be able to create a new `DashboardList` panel and just not populate the folder selector and it should search against the whole database 👍

**Comment by Dino1010** [comment]
@ashharrison90 

Thank you for your detailed explanation. Using the method you provided, I am now able to search for tags across the entire database. However, regarding the functionality of subfolders, I wonder if it would be beneficial to add an option for users to choose whether to include subfolders in their searches.

For instance, once the subfolder feature is enabled, and I have meticulously organized the contents of the current directory into subdirectories, I would still prefer the search to return results from both the current directory and its subdirectories. This feature would enhance the user experience by providing more comprehensive search results especially, especially  since the current system does not support selecting multiple directories simultaneously.
