### ISSUE TITLE
[Feature request] Allow database query within InfluxDB datasource

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#7990]
Currently each InfluxDB datasource is configured with a database.  It would be great to change the database with the query, not the configuration.

see #7948

**Comment by bbczeuz** [comment]
Yes, my current setup has like 10 InfluxDB datasources only with different DBs. That feature would reduce maintenance efforts.
Possible issues:
- This feature could easily be a breaking change. Some transition mechanism would be good.
- When importing Dashboard JSONs, it should be possible to select DB sources and names.

**Comment by torkelo** [comment]
@bbczeuz when you export a dashboard that is exported via the UI, and then try to import it, you will get a change to pick which Grafana Data source to use (not InfluxDB database but Data source) this is in order to make dashboard sharing easier (so when you import a dashboard from https://grafana.com/dashboads for example you do not have to modify all panels to use your data source that is covered in the import modal.

**Comment by bbczeuz** [comment]
@torkelo Yes, I like and use this feature quite often. When splitting the DB name from the source, the feature would need to be extended for the now two variables.

**Comment by torkelo** [comment]
@bbczeuz very unlikely to happen

**Comment by marefr** [comment]
Fixed by #8096
