### ISSUE TITLE
Angular support removed early?

### ISSUE THREAD

**Issue by gfrankliu** [grafana/grafana#79905]
### What happened?

Based on https://grafana.com/docs/grafana/latest/developers/angular_deprecation/ , Angular is still supported in Grafana 10 when `angular_support_enabled` is set to `true`, and the removal of the support will happen in Grafana 11 that will be released next year.

I just tried upgrading to grafana 10.2.3 (latest) and set angular_support_enabled to true, but angular still not functioning properly. The panel (using https://github.com/AidanMountford/aidanmountford-html-panel ) throws the error "Error loading: aidanmountford-html-panel". One of my colleagues tried grafana 10.1.x and found the same panel works fine. 

Is this a bug introduced in 10.2.x for the option `angular_support_enabled`? Or have you decided to remove the support in grafana v10 instead of waiting for v11?

### What did you expect to happen?

Option angular_support_enabled should work in grafana v10

### Did this work before?

It works in grafana v10.1.x but not v10.2.x

### How do we reproduce it?

Try https://github.com/AidanMountford/aidanmountford-html-panel which uses the angular.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by sympatheticmoose** [comment]
Hi @gfrankliu thanks for reaching out. Support for angular remains as stated in the deprecation notice, it has not been removed early.

The plugin in question is failing due to a change in the version of systemjs https://github.com/grafana/grafana/pull/70068 which was in 10.2. Unfortunately for this particular plugin, it is not compatible with the newer version. The plugin itself has not been updated in 5 years and has subsequently been removed (deprecated) from the Grafana plugins catalog.

Given this, I would strongly advise looking to migrate to an alternative plugin - https://grafana.com/grafana/plugins/gapit-htmlgraphics-panel/ may be of use.
