### ISSUE TITLE
Support connection to MonetDB

### ISSUE THREAD

**Issue by simonaubertbd** [grafana/grafana#79922]
**Why is this needed**:

MonetDB is one my favorite database for dataviz:
-it's free
-it's open-source
-it's fast
-it's easy to install on linux, mac and windows.
-it cares about SQL norm
-you can use odbc, jdbc, sql alchemy 2, etc... 
To me, it's like the postgresql of analytics db. All the competitors have it : Tableau, Qlik, Apache Superset... it's weird not to find it here. 
More information on https://www.monetdb.org/

**What would you like to be added**:

A simple/easy way to connect to MonetDB

**Who is this feature for?**

Well, any kind of user that uses MonetDB.

**Comment by usmangt** [comment]
Hi @simonaubertbd,

Thanks for opening this issue.

I searched on this and there have been some posts on integrating MonetDB with Grafana but did not find a final answer and the reason is that, MonetDB has not yet provided/created a plugin/Datasource that can be easily integrated with Grafana.

So I see the following 2 possibilities here:

1- Asking MonetDB to provide a plugin/datasource to get easily integrated in the Grafana environment. This might be a feature-request or they might have been working on it but not yet officially released it yet.

2- Create it by yourself and ask for some help and guidance from the Grafana Plugin Development using this [link](https://community.grafana.com/c/plugin-development/30)

I hope this helps.

**Comment by simonaubertbd** [comment]
Hello @usmangt  . First of all, thanks for your answer and your time. I also doubt MonetdDB developped such a plugin. However :
1/there are odbc, jdbc, db-api, even sql alchemy that you can leverage
2/usually, this is the initiative of the dataviz to support a database, not the opposite. (At least with the one I use to work : Tableau and Qlik). To be frank, I'm really surprised by your answer O_o
3/I poste this feature request on the Monet DB Github https://github.com/MonetDB/MonetDB/issues/7446
Can you at least propose some help to do so? 

Best regards,

Simon

**Comment by arjenderijke** [comment]
Hello @simonaubertbd, @usmangt  I am working on a Grafana plugin for MonetDB. Before this could work, the MonetDB driver for Go needed to be upgraded to support several new interfaces that are needed by the Grafana SDK. This morning i published a new version of the [driver](https://github.com/MonetDB/MonetDB-Go/releases/tag/v2.0.0) Now i will continue with finishing the Grafana plugin. It will take some time before the plugin is ready to be published, but it works basically. I hope it will be ready somewhere next month.

**Comment by simonaubertbd** [comment]
Hello @arjenderijke  That's great, thanks a lot for your work.

Best regards,

Simon

**Comment by arjenderijke** [comment]
The first version of the plugin was submitted and approved. It is now available: https://grafana.com/grafana/plugins/dataspex-monetdb-datasource/

**Comment by usmangt** [comment]
@arjenderijke Thank you very much for this.

I very highly recommend putting links to the GitHub repo and Documentation so that users can report issues, features, pr, etc and can also use documentation.

Without having these 2 core items, i am afraid that it will also end up in vain like many other Plugins in the past.

**Comment by arjenderijke** [comment]
Sure, no problem, the code for the plugin is hosted at https://github.com/dataspex/dataspex-monetdb-grafana-datasource I am happy to respond to issues or pull requests. The documentation is in the [README](https://github.com/dataspex/dataspex-monetdb-grafana-datasource/blob/main/README.md) Please note that this is a first release, so there are certain features missing. But we have plans to implement what is missing.

**Comment by simonaubertbd** [comment]
@arjenderijke  Hello. Thank you for your great (and fast ;)  ) job ! 
Best regards,
Simon

**Comment by usmangt** [comment]
Hi @arjenderijke 

thank you. That is what I was saying. But can you please include the GitHub and links on this page
https://grafana.com/grafana/plugins/dataspex-monetdb-datasource/?tab=overview

**Comment by arjenderijke** [comment]
Aha, ok. That will have to wait until i can create a new version, since that page is the [README](https://github.com/dataspex/dataspex-monetdb-grafana-datasource/blob/main/src/README.md) of the frontend of the plugin. But i will add this to my todo list.
