### ISSUE TITLE
[Feature Request] Time Override Condition

### ISSUE THREAD

**Issue by mmahacek** [grafana/grafana#7993]
Is there a way to set a panel's time override to be conditional? I would like to set a panel to show one week if the dashboard is set to one week or shorter, but have it match the dashboard if the time range is longer than a week.

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments so we are closing it. We are trying to limit open GitHub issues in order to better track planned work and features.

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Still a big Thank You to you for taking the time to create this issue!
