### ISSUE TITLE
[Feat Req] Alerting: HipChat notifications & More info

### ISSUE THREAD

**Issue by Remusss** [grafana/grafana#8030]
Grafana seems to send a lot more information than HipChat is showing. See below HipChat history from web versus the windows HipChat client.
![2017-04-04_18-26-44](https://cloud.githubusercontent.com/assets/26903410/24665452/152282ce-1966-11e7-8f4e-fb439c0ba33a.png)

I would expect to see the whole notification.

I am using Grafana 4.2.0 on CentOS 6.6.

**Comment by torkelo** [comment]
Maybe an issue with the centos client? We are sending the info as you can  see

**Comment by Remusss** [comment]
Not sure how this should've looked like and the intended usage versus the roles and permissions from the HipChat API. I have the feeling that notifications lack some messaging features (e.g. picture embedding).

**Comment by Samuel1989** [comment]
According to Hipchats documentation only a card or a message are supported via their API, not both. A Card is optional but if included will replace the message body.

https://developer.atlassian.com/hipchat/guide/sending-messages

> When a card object is rendered in a supported client it is rendered instead of the message body.

When I looked at Grafana's code, it seems that only the alert title and it's state is being sent in the cards description, this is likely because the cards description is truncated if it becomes to long and the alert name and state was all that could sensibly fit, however, far more useful information is being sent in the message body.

Sam

**Comment by Remusss** [comment]
So, bottom thing is either use attributes and values or a multi line description in a card. I would bet on the first option. 
The message should still be provided as a fallback.

Remus.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
