### ISSUE TITLE
Prometheus Datasource Forwarding OAuth Identity does not work

### ISSUE THREAD

**Issue by moritz31** [grafana/grafana#80698]
### What happened?

My instana instance is configured with okta as oidc provider. Until now i had configured several prometheus datasources with basic auth and thought it would be more simple to use the forward oauth identity feature of the datasource. Original i had an aws application loadbalancer in place which has okta as oidc configured as well, but i didn't get a result from the datasource save & test produced an error. Then i tried the same with oauth2-proxy with the same result and in the and i tried it with an caddy to log all incoming headers. There is one header with X-Id-Token which has the token set, but the Authorization header is sent as empty array. 

### What did you expect to happen?

I expect if i can login both grafana and prometheus with the same oidc provider that forwarding oauth identity just works 

### Did this work before?

Never tried 

### How do we reproduce it?

1. Setup grafana with oidc 
2. Setup prometheus behind some reverse proxy that uses the same oidc
3. Configure the prometheus datasource and click save&test

### Environment (with versions)?

Grafana: 8.X-10.X
OS: macOs 
Browser: Firefox/Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Prometheus

**Comment by chaijunkin** [comment]
Hi @moritz31 , I'm having similar issue with same setup but using grafana community, did you manage to solve this issue?

**Comment by marefr** [comment]
It sounds like Okta (your configuration) doesn't return any access/refresh token, rather only the id token. For reference the Authorization and X-ID-Token headers are populated here https://github.com/grafana/grafana/blob/main/pkg/services/pluginsintegration/clientmiddleware/oauthtoken_middleware.go#L62. X-ID-Token are forwarded as expected. 

https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/okta/#configure-a-refresh-token might help.

I'm closing this due to configuration error and suggest https://community.grafana.com/ for further questions/help. If you still think this is a bug, please include Grafana (debug) logs and/or similar and we'll consider reopen.
