### ISSUE TITLE
UI: Loki metadata is considered as labels.

### ISSUE THREAD

**Issue by matthisholleville** [grafana/grafana#80893]
### What happened?

Loki metadata is considered as labels, which makes the Query shortcut unusable.

https://github.com/grafana/grafana/assets/99146727/84bda881-ffec-44bc-ae05-5d69beac1a1d

> 

### What did you expect to happen?

It would be great to have a Query shortcut for metadata, similar to what exists for labels.

I'm not sure if this [PR](https://github.com/grafana/grafana/pull/77361) can help address the issue.

### Did this work before?

No.

### How do we reproduce it?

1. Activate loki metadata in limit_configs
2. Try to use query shortcut on metadata

### Environment (with versions)?

Grafana: v10.2.3
OS: macOS Sonoma
Browser: Brave

### Grafana platform?

Docker

### Datasource(s)?

Loki

**Comment by tonypowa** [comment]
Hi @matthisholleville 

Thank you for reporting this issue
I am not sure that this issue is related https://github.com/grafana/grafana/issues/49618 but still, have a look.
In the meantime, I will send this to the maintainers for review

**Comment by ivanahuckova** [comment]
@svennergr could you please have a look. I think it should have been fixed by https://github.com/grafana/grafana/pull/78595 that was part of `v10.2.3`, but it seems that in that version, it is still an issue. Not sure if version of Loki is important here, if structured metadata and header that includes types of labels were introduced in different versions, or not.

**Comment by svennergr** [comment]
Hi @matthisholleville,

sorry for the delay here. You are right, Grafana v10.2.x and v10.3.x need the [feature toggle `lokiStructuredMetadata`](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/#:~:text=lokiStructuredMetadata) to be turned on, otherwise the query might be wrongly composed.

**Comment by matthisholleville** [comment]
Hi @svennergr 

How can you enable the feature toggle?

I actually added it, but the issue still occurred.

```ini
[feature_toggles]
enable = lokiStructuredMetadata
lokiStructuredMetadata = true
featureToggleAdminPage = true

[feature_management]
allow_editing = true
```

**Comment by matthisholleville** [comment]
Tested with other experimental feature ( `dockedMegaMenu = true` ) and it work. My configuration format look good.

But the issue still occurred...

@svennergr can you re-open this issue please ?

**Comment by svennergr** [comment]
Oh, @matthisholleville, right. I took another look and the API used to distinguish the label types in Loki is not released yet, so unfortunately we have to wait for another Loki release with that [API change](https://github.com/grafana/loki/pull/10419). That's similar to https://github.com/grafana/loki/issues/11912.

**Comment by matthisholleville** [comment]
Hi @svennergr, we've just upgraded to Loki 3.0 and the problem persists 👎
