### ISSUE TITLE
Dashboards: Unable to see dashboard changes in drawer

### ISSUE THREAD

**Issue by baldm0mma** [grafana/grafana#81009]
### What happened?

When I click on the "changes" tab after clicking on the "save" icon to save the dashboard, the drawer closes instead of showing me the changes.

video: https://github.com/grafana/grafana/assets/46619047/0788cb65-584e-4ec5-a512-2d7b9fe102b7

But! This **ONLY** happens under the following dashboard grid constraints: the screen must be flexed in a way where the dropdown ellipsis, when clicked, only displays the "save," "settings," "add" dropdown, and "share" buttons. If there are more or fewer options, it doesn't break.

### What did you expect to happen?

To see the changes displayed in the drawer.

### Did this work before?

Unknown.

### How do we reproduce it?

1. Open a Grafana dashboard, flex the width to the constraints mentioned above.
2. Click on the more options ellipsis.
3. Click on "save."
4. Click on "changes," tab.

### Environment (with versions)?

Grafana: 2024/01/19 `main` branch
OS: macos 14.2.1
Browser: Brave 1.61.120

### Grafana platform?

None

**Comment by samjewell** [comment]
The same thing happens if you try to write a commit message / description whilst saving.

### How do we reproduce it?

1. Open a Grafana dashboard, flex the width to the constraints mentioned above.
2. Click on the more options ellipsis.
3. Click on "save."
4. Click on the text-area to try to write a message
