### ISSUE TITLE
[Feature request] Force a check of an alert

### ISSUE THREAD

**Issue by jkv** [grafana/grafana#8104]
I'd like to be able to force a check of an alert instead of waiting until the next scheduled check happens. I know there is the "Test Rule" but I'd like to be able to force a check and clear up an Alerting condition in the case where an additional check is all that is needed.

**Comment by bergquist** [comment]
Thank you for taking the time to provide feedback to us. 

Right now we don't think this idea aligns with the current scope/goal of the Project. I'm closing this issue since we want open issues to reflect the current state of the project. It doesn't mean we never considered it. A closed issue can still get attention from other users and be reopened.
