### ISSUE TITLE
[Feature request] Ability to group panels in a row by tag

### ISSUE THREAD

**Issue by mvadu** [grafana/grafana#8106]
Please include this information:
- Grafana version : 4.2.0
- datasource : InfluxDB

Request: Ability to group panels in a row by tag, when the panels are auto generated by a repeater tag.

Use case: 
I have a dataset with hirarchy Application->Environment->Server.
I am using a (Status-Panel) [https://github.com/Vonage/Grafana_Status_panel] to show a health of bunch of servers. The panel is setup to repeat by `HostName` tag. Problem is not all hosts are alike, and I am looking for a way to group them by another tag. I can't use the row repeat option as its already being used to generate rows by application. Having an option to group the auto generated panels by another tag will help here. In the visualization this group can just have small border and a heading which shows the value of that tag. (e.g. `$tag_Environment`) in my case.

#### Current
![image](https://cloud.githubusercontent.com/assets/8618235/24975515/f4d05418-1f93-11e7-89aa-1f179d6e43a7.png)

#### Proposed
![image](https://cloud.githubusercontent.com/assets/8618235/24977392/ecebfe8a-1f9a-11e7-9640-cfa59878cbc0.png)

**Comment by torkelo** [comment]
Intersting idea! But it feels like this will add a bunch of complexity, amd not very likely to be implemented (due to complexity & trying to avoid feature creep). You can solve this by using two rows instead. 

Or looking further ahead to solve more complex dynamic dashboards we will revamp the scripted dashboard support.
