### ISSUE TITLE
Starred Query can be seen/shared within an Orgnization 

### ISSUE THREAD

**Issue by dhutsj** [grafana/grafana#81221]
Taken from https://community.grafana.com/t/how-can-i-share-a-starred-query-in-grafana-within-an-org-or-say-does-it-support/112695/2

**Why is this needed**:

Currently, Starred Query is only can be seen by the one who created it. In other words, it is account-level's config. But many queries can be re-used by a group of people belong to a same develop squad.

**What would you like to be added**:

Make the Starred Query can be seen within an origination, not only the one who created it.

**Who is this feature for?**

User logged in the Grafana org

**Comment by gelicia** [comment]
Hello! This is actually a rather large initiative we are working on, to implement a Grafana-wide query library. This means not only will you be able to share your starred explore queries, but also you will be able to share your queries all over Grafana. 

The broader task for this work is https://github.com/grafana/grafana/issues/77974 . Since this ticket is an aspect of that, I am going to close this just to remove the duplicate. Thank you for your patience, and I really hope you like the Query Library :)
