### ISSUE TITLE
Adding new query to a Mixed data source has incorrect data source pre-selected

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#81469]
Follow-up to https://github.com/grafana/grafana/pull/81027

When Mixed data source is selected, the default data source is not respected. All newly added queries have Mixed data source pre-selected. See the attached video:

https://github.com/grafana/grafana/assets/2376619/2f4ff658-7ab2-4c72-9388-3f8c7a9bc678

**Comment by harisrozajac** [comment]
@dprokop I'm confused about this one because I'm not able to reproduce this except in one panel. I've also added more panels directly from dashboard and from explore, and this bug doesn't show up. Here's a video of what I'm seeing (I'm talking, so unmute the audio because it will be easier to follow :)):

https://github.com/grafana/grafana/assets/58232930/b572904a-d3ed-4afa-8d3c-4a06044e0695

**Comment by harisrozajac** [comment]
After doing a bit more investigation, this issue seems to be related to `grafana.dashboards.panelEdit.lastUsedDatasource` key in local storage. For some reason, this key was misconfigured in one of my panels, and clearing this key resolved the issue. This shouldn't be a problem moving forward because I've tried creating a new dashboard and the bug doesn't occur anymore.
