### ISSUE TITLE
[Feature request] histogram support x-axis min/max 

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#8148]
If the original data value is widely distributed, and some value is too big, the histogram is draw like below.

![histogram](https://cloud.githubusercontent.com/assets/224552/25113363/bc2069da-2431-11e7-81d4-060d857a0795.png)

It is normal case if the original data is response time of application.
If user doesn't have interest for 2.0 or above value, they want to set max of x-axis.

**Comment by Kamairo** [comment]
Another use case:
Image you have multiple histograms showing the same type of data but different samples. If the samples are differently distributed you can hardly compare those histograms by eye because the x scale will be totally different in each histogram. Example: I have a temperature sensor that logs every 20 min. I now have a histogram for each month of the year showing the distribution of the temperature per month. In January the samples range from -8 to 10 but in June they range from 10 to 35. Showing those two histograms next to each other makes you think it's the same base of samples. Would be nice if I could control each histogram's x axis from say -10 to 40. That way the histograms would be much more easy to compare by just looking at them.

**Comment by DanielO** [comment]
"Me too": I want to compare data between two different systems which have slightly different biases and fixing the X axis would make the visual comparison much simpler.
