### ISSUE TITLE
[Bug] Templating: "All" query does match too much

### ISSUE THREAD

**Issue by Finkregh** [grafana/grafana#8165]
- What Grafana version are you using?
v4.2.0 (commit: 349f3eb)

- What datasource are you using?
InfluxDB / Telegraf

- What OS are you running grafana on?
OpenSUSE

- What did you do?
In the templating do a query for disks:
`SHOW TAG VALUES FROM diskio WITH KEY="name"`
which returns e.g. [sda, sda1, sda2, sdb, sdb1]
add a regex-filter, as we only want major block devices, not the partitions:
`/^[a-z]d[a-z]+$/`
this returns [sda, sdb]
Enable "Multi-Value" and "Include All Option"

In the graph-view select "All"

- What was the expected result?
Only graphs from sda and sdb are shown
Query (part): `WHERE "name" =~ /^(sda|sdb)$/` or
Query (part): `WHERE "name" =~ /^sda$|^sdb$/`

- What happened instead?
Graphs from sda, sda1, sda2, sdb, sdb1 are shown
Query (part): `WHERE "name" =~ /^sda|sdb$/`
Query (full): `SELECT mean("iops_in_progress") FROM "diskio" WHERE "name" =~ /^sda|sdb$/ AND "host" =~ /^something$/ AND time > now() - 24h GROUP BY time(10m), "host", "name" fill(null)`

**Comment by JohannesAtGit** [comment]
What Grafana version are you using?
v4.1.2

What datasource are you using?
InfluxDB / Telegraf

What OS are you running grafana on?
Ubuntu

What did you do?
In the templating select query or custom:
e.g.
Variable: nodename, Type: Custom
Custom Options: node1,node2,node3
Selection Options: "Select Multi-Value" or "Include All" option.

In the graph-view select "All" or "node1 and node2"

What was the expected result?
Only graphs data from specified nodes is shown
Query (part): select * from /$cluster\.$nodename.####/ where ###
Query result should be: select * from /$cluster\.node1|node2.####/ where ###

What happened instead?
Every metric from $cluster is shown. The dashboard freezes because of the huge amount.

In a previous Grafana version 3.* , it was working.

**Comment by torkelo** [comment]
unable to replicate, All works fine for me:
http://play.grafana.org/dashboard/db/influxdb-templated-queries?orgId=1&var-datacenter=Asia&var-host=All&var-summarize=1m 

Can you include more details, for example the raw query before interpolation and the raw query grafana sends to InfluxDB and the value of your template variables.

**Comment by JohannesAtGit** [comment]
Maybe the problem is that we are not using tags. In our view it is still a bug because it was working before.

Templating:
Name: _nodename_
Query:
```
SHOW MEASUREMENTS WITH MEASUREMENT =~ /^abc\.nodetool\.$clustername\.host\.cal.*\.status\.value/
```

Regex:
```
/.*(calculator-.*)\.status\.value/
```

Panel Query:
```
SELECT mean("value") FROM /^$nodename\.$clustername\..*HeapMemoryUsage\.HeapMemoryUsage(\.|_max|_used)/ WHERE $timeFilter GROUP BY time($interval) fill(null)
```

_$clustername_ is a constant template variable.

**Comment by torkelo** [comment]
Ok so your query is:
`SELECT mean("value") FROM /^$nodename\.$clustername\..*HeapMemoryUsage\.HeapMemoryUsage(\.|_max|_used)/ WHERE $timeFilter GROUP BY time($interval) fill(null)`

what is the query grafana sends to InfluxDB (the interpolated one) ?

**Comment by JohannesAtGit** [comment]
This is the log from influxDB when I select all in Grafana.

"GET /query?db=metrics&epoch=ms&q=SELECT+mean%28%22value%22%29+FROM+%2F%5Ecalculator-0-10%7Ccalculator-1-11%7Ccalculator-2-12%5C.cal1%5C..%2AHeapMemoryUsage%5C.HeapMemoryUsage%28%5C.%7C_max%7C_used%29%2F+WHERE+time+%3E+now%28%29+-+6h+GROUP+BY+time%2810s%29+fill%28null%29 HTTP/1.1" 200 4702886 "http://ip/dashboard/db/test?panelId=1&fullscreen&edit&editview=templating&var-clustername=cal1&var-nodename=calculator-0-10" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" 8d1e3146-250f-11e7-800d-000000000000 6123517
[I] 2017-04-19T14:50:49Z SELECT mean(value) FROM metrics.metrics_default./^calculator-0-10|calculator-1-11|calculator-2-12\.cal1\..*HeapMemoryUsage\.HeapMemoryUsage(\.|_max|_used)/ WHERE time > now() - 6h GROUP BY time(10s) service=query

**Comment by torkelo** [comment]
Ok, looks to be a minor difference in variable interpolation when using raw query mode (not using query editor), which is why I could not replicate it. 

So if you can switch to using query editor it should work.

Need to add parenthesis to the interpolation / pattern replacement here
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/influxdb/influx_query.ts#L197

**Comment by JohannesAtGit** [comment]
We will wait for the release of the bugfix.
Thank you very much for the quick response.

**Comment by cloudyday** [comment]
Also experiencing this issue. 

This breaks all our dashboards on Grafana 4.x

Needs urgent fix.
