### ISSUE TITLE
[Feature request] Computations on multiple Query Results

### ISSUE THREAD

**Issue by yuva-phani** [grafana/grafana#8167]
Hi Team,
I am using grafana version 4.1.1 with data sources Elastic search and InfluxDB. 
I am facing issue while computing multiple query results.

For example: 

Query 1 got the result as 1000 in single stat graph
Query 2 got result as 100 in single stat graph
now i want to perform some mathematical operations on these two results.

I want to compute  (Query 1 Result / Query 2 Result) and show  final result in one more single stat graph.

It  would be great if it can be implemented.

Thanks,
Yuva Phani

**Comment by torkelo** [comment]
Some time series databases like Graphite support nested queries and a chain of operations on time series query results. Elasticsearch & InfluxDB does not support this sadly. 

In order to solve this for other databases we hope to introduce meta queries some day:
https://github.com/grafana/grafana/issues/3677
