### ISSUE TITLE
Canvas: Ability to dynamically change background image based on url

### ISSUE THREAD

**Issue by accessfalk** [grafana/grafana#82025]
**Why is this needed**:

To visualize e.g. weather information or other stati of whatever devices

**What would you like to be added**:

Change background picture of a rectangle or ellipse based on query result --> URL to picture comes from query

**Who is this feature for?**

All Canvas Panel users who would like to show various stati of their home automation --> Is the dishwasher on or off, is the heater on or off (so gif's could be loaded when on, jpg's when off, what weather symbol to be shown, what moon status do we have, dark mode or light mode for my location?

**Comment by nmarrs** [comment]
Hi @accessfalk - thank you for creating this issue! This functionality should be already supported by canvas. You can set the element's background image to be driven by field data, where the field data is a string of a publicly accessible url of the desired image for the given data row.

<img width="774" alt="Screenshot 2024-02-23 at 9 50 23 PM" src="https://github.com/grafana/grafana/assets/22381771/63e9385d-c6e3-42f2-9c93-600acddbea82">

**Comment by accessfalk** [comment]
Many thanks Nathan!
It's not working for me unfortunately. I used a rectangle and a string field to set the background as shown in the screenshot you provided, tested the url as well, but nothing is shown.than the background colour (either transparent or whatever else I selected). The Query outcome is formatted as string like "https://my-server/image.png".What am I missing? 
Many thanks again and Cheers,
Falk
    Am Freitag, 23. Februar 2024 um 21:51:06 MEZ hat Nathan Marrs ***@***.***> Folgendes geschrieben:  
 
 


Hi @accessfalk - thank you for creating this issue! This functionality should be already supported by canvas. You can set the element's background image to be driven by field data, where the field data is a string of a publicly accessible url of the desired image for the given data row.
Screenshot.2024-02-23.at.9.50.23.PM.png (view on web)

**Comment by Leandro4002** [comment]
As of March 2026 this feature does not work in Grafana v12.0.1 (80658a73c5).

I tried with a local image path, a public url or with a base64 image string (with or without data:image prefix), but none of those method work.

To try this out, I use a SQL query like that:
`SELECT 'http://localhost:3000/public/img/bg/p1.png' AS test;`

Which gives me this data:
<img width="937" height="218" alt="Image" src="https://github.com/user-attachments/assets/4a3b5f36-0d7b-46bd-ba92-8664c41800d5" />

Then set the image property to be this field:
<img width="387" height="587" alt="Image" src="https://github.com/user-attachments/assets/8649cebf-eb83-4597-bf03-a7c1c17e5140" />

I can see that nothing changes, even if I reload the page, refresh the dashboard or close and reopen the browser. In the debug menu of my browser (F12 menu), I can see that no HTTP query are made in order to fetch the image that I put in in the field "test"
