### ISSUE TITLE
[Feature request] Max-width for legend in graph panel

### ISSUE THREAD

**Issue by Ultraseamus** [grafana/grafana#8214]
Problem: Not having the option to set a max width is particularly frustrating if you have the legend displayed as a table "To the Right". If a single series name in 1,000 is very long, the entire legend grows to accommodate it. Sometimes it even grows so large that there is literally no room to display the graph to the left, and an error is output on screen.

In addition to that buggy functionality, not being able to set a max-width (or a fixed-width) means you can't force multiple graph panels to line up cleanly. If there is any variance in legend value max-length, the graph portions from one panel to the next will be offset. "Shared Crosshair" prevents that from being a serious problem, but it does negatively affect the aesthetics of a dashboard. Currently there is a min-width value for the graph legends. So the problem is solved form one direction, but not the other.

Request: You should be able to set a legend max-width in addition to min-width (alternately, there could be a "Fixed-Width" option). If an entry would exceed that max-width, then it could be simply cut off, or cut off with a "..." indicating that there is more to the name. The full name shoudl always be visable in the tooltips.

Grafana Version: 4.2
Datasource: ElasticSearch
OS: Windows

**Comment by torkelo** [comment]
Not a big fan of introducing an option for this, mainly because adding new options for every edge case will eventually make the UI unusable and code unmaintainable. And since legend table to the right mode has existed in Grafana for over 2 years without any complaint about missing max-width.

Since most time series database allow you to modify the series name using either it's built in query language  or using Grafana Alias patterns this has not been a big issue. But I can see that with log data or data you have less control over (like docs in ES), then a single doc with large field could mess things up. And ES does not have a way to reduce the field lenght built into query language (like Graphite).

What I see could be done is to have a default max-width of about 40% of the panel.

**Comment by Ultraseamus** [comment]
I agree that too many options would eventually make the UI unusable. Though I may not fully understand the reasoning behind providing a "min-width" setting instead of "fixed-width". Possibly there is a common use-case for min-width that I am not considering. In my mind the only use for that would be to help make sure graphs line up to some degree; so long as you set the min-width to fit the longest entry you have, all of your legends will align. But, if there is much variance in name length, you end up with a lot of dead-space.

And, if that is your use-case, then you would be just as well served with a fixed-width setting instead of min-width.

Either way, your suggestion of a default max-width percentage does make sense. Since I'd argue that being able to have legend entries so long that it leaves no room for the graph, and causes Grafana to output an error, is a bug.

**Comment by torkelo** [comment]
this was done a long time ago in a galaxy far far away (v4)
