### ISSUE TITLE
[Bug] 100% client CPU usage on red alert glow animation

### ISSUE THREAD

**Issue by vonox7** [grafana/grafana#8222]
When having an alert, the corresponding panel receives a red heart and glows red in the background. This glow animation consumes 100% desktop CPU load, which is pretty bad.
Expected: Less than 5% CPU load or no animation.

I'm using Grafana v4.1.0 with Influx on Linux. My desktop machine is the latest MacbookPro with the latest Chrome 57.0.2987.133.

**Comment by torkelo** [comment]
@mattttt your animation needs a tweak :)

**Comment by mattttt** [comment]
I think I have a solution for this, based on this post: http://tobiasahlin.com/blog/how-to-animate-box-shadow/

Testing now in a branch.

**Comment by mattttt** [comment]
While I wasnt able to replicate CPU usage spiking to 100%, I did observe that it did spike a bit (~15-20% on my laptop) and looked for more efficient ways to handle the animation. 

Refactored code in PR: https://github.com/grafana/grafana/pull/8227

**Comment by torkelo** [comment]
great, thanks @mattttt for quick fix!

**Comment by youurayy** [comment]
Hi, the animation is definitely still taxing, e.g. on laptops (Macbook/Chrome), and on a bigger dashboard page with several open alerts, it adds up and the laptop goes into a full-fan/very-hot mode.

Things go back to normal after adding this CSS (e.g. via the Stylebot extension):

```css
.panel-alert-state--alerting:after {
    -webkit-animation: none;
    animation: none;
    opacity: inherit;
}
```
... plus I feel I have even better overview of where the alerts are because the red border is now solid.

Perhaps this could make it as an option into future Grafanas -- to have the animation on a user setting, possible to turn on/off (or just remove it entirely).

**Comment by youurayy** [comment]
Grafana signalling an error with a CSS animation, Macbook Pro i9 CPU (top-spec), cca. 2019:

![image](https://user-images.githubusercontent.com/588573/65740063-22ac4980-e0f0-11e9-9bd9-75876e81ad37.png)

*laptop hot and spinning fans loudly

**Comment by marefr** [comment]
@youurayy thanks for the suggestions. I would recommend you to open a new issue where you can report more detailed information since this issue have been closed for over 2 years.
