### ISSUE TITLE
Prometheus: confusion in table panel

### ISSUE THREAD

**Issue by cemo** [grafana/grafana#8223]
I could not understand table panel legend and columns. Before suggesting a new approach I wanted to be sure that my understanding is correct or not. 

In order to format a column I have to use `legend format`

![image](https://cloud.githubusercontent.com/assets/44156/25442731/7a327f3a-2aae-11e7-8608-332b60d45f1a.png)

However there is also a column configuration tab in the panel:

![image](https://cloud.githubusercontent.com/assets/44156/25442779/9cce15ae-2aae-11e7-894f-7892416ef42b.png)

Confusion things:

1. Why I need to use `format legend` instead of `column`? 
2. What is the point of adding more series to table? I added and happened nothing.

And my 2 cents to improve things: 

1. Disable `legend format`. Use columns of options. 
2. Allow users to labels as a value in columns as `{{label}}` as in legend format right now. When user select: `time series to columns`, a user can only add single column. If user selects `time series to rows`, in this case user can add multiple columns since the value can be label as well.
3. Allow arbitrary columns to be formatted and used from series results.

**Comment by torkelo** [comment]
> Why I need to use format legend instead of column?
Legend format expression controls the naming of each time series your query returns. Not sure what you mean "instead of column" 

> What is the point of adding more series to table? I added and happened nothing.
More series? You mean more queries or a query that returns more series? If you query for more series they should be shown in the table, might be further down or on another page depending on your time series -> table transform and page size 

> Disable legend format. Use columns of options.
Makes no sense, would not be able to query for time series then. 

In next release (v4.3 & master) you can choose to return prometheus in "Table" Format (instead of time series), this way all labels will automatically show up as columns:
https://github.com/grafana/grafana/pull/6140

**Comment by haizaar** [comment]
Apologies for reanimating the old issue, but it confuses me as well:

* Adding second (third, etc.) query does not seem to do anything - only the first query results are displayed
* "Legend format" field does not seem to have any impact at all on the displayed results.

I'm using Grafana 4.6.3 with Prometheus data source.
