### ISSUE TITLE
[feat req]  Use time range at load for panels loaded on scroll 

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#8235]
- What Grafana version are you using?
  - 4.3.0-7412pre1
- What datasource are you using?
  - Prometheus
- What OS are you running grafana on?
  - Mac
- What did you do?
  - Open dashboard and scroll to the bottom, time range is `now-1h` to `now`
- What was the expected result?
  - All graph panel time range is aligned
  - If top of graph panel range is 0:00 - 1:00, bottom of graph panel range should be 0:00 - 1:00
- What happened instead?
  - bottom of graph panel range is 0:01 - 1:01 or 0:05 - 1:05 or ...

I'm not sure this is a bug.

Because the panel loading is deferred until displayed, and `now` is resolved when loading.
https://github.com/grafana/grafana/pull/7452

So, it is expected result, but if possible I want to align the time range.

**Comment by torkelo** [comment]
Well since the dashboard time range is relative to now, it will be dependent on when the panel is loaded, so if not all panels are visible then sure it will differ by a tiny bit. If you want them to align just hit refresh. 

The same has been true for collapsed rows for years with no complaints so I didn't this is going to be seen as a big problem. But we leave this open as a feature request to see if more find this a problem

**Comment by mtanda** [comment]
I never notice we already have same issue with collapsed rows...
I feel current behavior is little strange, most of user want to compare graphs in same time range.
(If all panel width is 12, I expect the vertical line is aligned by time)

Anyway, the feature is quite new, I wait for other user's feedback.

**Comment by torkelo** [comment]
closing this as loading on scroll was removed
