### ISSUE TITLE
Sub-components version disclosure in grafana 10.2.1 

### ISSUE THREAD

**Issue by VeenaThimmegowda** [grafana/grafana#82409]
### What happened?

Low-level vulnerabilities have been identified in the Invicti tool on Grafana version 10.2.1. The disclosed sub-component versions are as follows
AngularJs (1.8.3)
Jquery (3.7.1)
lodash (4.17.21)

Attached screenshots for reference.
![image](https://github.com/grafana/grafana/assets/38758323/11c71e54-08ad-4b1f-ac3b-f0fc51a2a3b8)
![image](https://github.com/grafana/grafana/assets/38758323/78b8acda-f9ce-44a5-a119-da327721e467)
![image](https://github.com/grafana/grafana/assets/38758323/300a770b-4d66-4d7a-a19a-55b27f32ae1e)

### What did you expect to happen?

Normally we shouldn't get any sub-component version before login

### Did this work before?

Not checked for previous versions

### How do we reproduce it?

1.Open the Grafana 10.2.1 GUI
2. Before logging in, search for the respective versions in the Developer tools.

### Environment (with versions)?

Grafana: 10.2.1
Browser: Microsoft Edge

### Grafana platform?

None

**Comment by simonc6372** [comment]
HI @VeenaThimmegowda, 
Thanks for the interest in Grafana and taking the time to report this. 
Before getting into the details of your issue, can I ask that if you think you've found any security issues with Grafana, to please follow the process indicated in [https://github.com/grafana/grafana/blob/main/SECURITY.md , ](https://github.com/grafana/grafana/security/policy), rather than logging it as an issue in public. 

Although there are probably techniques to mask the versions of components running, it's unlikely they would withstand attempts to fingerprint the Grafana it self. And, because Grafana is open source, as soon as the version of Grafana it self is identified, the version of components is easily discovered. There are also downsides of the techniques used to hide version numbers, which make debugging much harder.  Also, generally speaking, security through obscurity is consider to be of very limited value as a security measure. 

If you really want to make it harder for someone who is not signed in to know what version you are running, I would suggest running Grafana behind an authentication proxy, and not direct traffic to your Grafana instance until the user is logged in.
