### ISSUE TITLE
Describe in docs what is grafana_state_reason: NoData

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82578]
### Discussed in https://github.com/grafana/grafana/discussions/68810

<div type='discussions-op-text'>

<sup>Originally posted by **lex-pec** May 22, 2023</sup>
I have some alerts, which by default do not have any data, so their panels show "No Data" in the middle of the graph. 
These alerts are triggered when something appears on the panel - dots of data, usually. So when something appears the alert is triggered and I have a message in my Telegram contact point. When time passes and the time range of the alert leaving that data behind, I am receiving another message, something like: 
``` 
<Alert's name>
grafana_state_reason: NoData

NoData: 
```
Because by default I have no data in my panel a `Nodata = OK` setting is turned on. So I don't understand why I am receiving the latter message.
I've noticed that such a behavior appeared after upgrading Grafana from 9.0.1 to 9.3.6.

Trying to find similar issues or discussions I came across an isssue #57115 which solved a problem of misunderstanding of `grafana_state_reason: MissingSeries`. 

Generally, a similar issue is needed here: to describe how grafana_state_reason: NoData works and the most important is it possible to turn this off and stop receiving this kind of messages when the `NoData = OK` setting is on.

Link to the post on Grafana Community:
https://community.grafana.com/t/alert-returns-grafana-state-reason-nodata-with-nodata-ok-setting/83490
</div>

**Comment by yuri-tceretian** [comment]
This state reason is sent to distinguish between situations when the transition `Alerting -> Normal` happens due to the metric going below the threshold or due to missing data points. 
This is what happens in this case. 
Now, to stop receiving such messages users have two options:
- disable resolve notifications. Each contact point integration has this setting. It can be changed on "Contact points" page. This way, only notifications about firing Alerts will be sent.
- use custom notification template and drop the annotation `grafana_state_reason`
