### ISSUE TITLE
[Feature request] Update Graphite support to include functions introduced in the 1.0.0 release.

### ISSUE THREAD

**Issue by bascarsija** [grafana/grafana#8261]
Master (88dd8af at the time of writing) does not support the selection/autocompletion any of the new Graphite functions introduced in the 1.0.0 release, as listed in [the release notes](https://graphite.readthedocs.io/en/latest/releases/1_0_0.html).

Issue #2481, which predates the Graphite 1.0.0 release, requests that a specific function (i.e. `fallbackSeries()`) be added, but @torkelo responded that the function should only be added "when it is available in the latest stable release."

Now that 1.0.0 is available, `fallbackSeries()` and all of the other functions introduced in 1.0.0 should be added to the set of functions supported by the selection/autocompletion feature.

As an aside, note that #4622 separately requests the addition of a new feature to maintain version-specific function sets and allow users to specify the data source version.

**Comment by torkelo** [comment]
Some tips on how to implement 

Add Graphite Version option to data source settings

Implement similar to ES version, https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/partials/config.html#L26
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/config_ctrl.ts#L24
Add version property and filtering to function definitions
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/gfunc.js#L36
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/gfunc.js#L755

So that function menu / autocomplete only shows functions for your graphite version, add new function definitions for Graphite 1.0 functions
