### ISSUE TITLE
Support Metric Selectors for Prometheus data sources in dashboard query variables

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82768]
### Discussed in https://github.com/grafana/grafana/discussions/65881

<div type='discussions-op-text'>

<sup>Originally posted by **joeblubaugh** April  3, 2023</sup>
Grafana supports several query types when creating dashboard variables. For the Prometheus data source plugin, these are:
* Label Names
* Label Values
* Metrics
* Query Result
* Series Query

Label Values supports a metric selector, which allows you to query the values for a label, as long as the series also match the metric selector. This is useful to say something like: "all the values for the service label on HTTP Request metrics"

This isn't possible for Label Names. The datasource calls this endpoint for label names: https://prometheus.io/docs/prometheus/latest/querying/api/#getting-label-names but it passes no parameters. The API supports a `match[]` query parameter, much like the label values endpoint. Adding support for this would permit asking the question: "what label names are there for all HTTP Request metric series?"</div>

**Comment by NWRichmond** [comment]
Hi @joeblubaugh! In https://github.com/grafana/grafana/pull/70452, we added support for limiting label names by query. But instead of a query selector, we offer regex matching for the query name:

https://github.com/grafana/grafana/assets/5732000/6758ce47-0b72-444b-bb11-4facc3818c72

Although the implementation is different than requested in this issue, this seems to solve the underlying problem. I'll close this for now, but please reach out with any follow-ups, and we can reopen as needed.

**Comment by joeblubaugh** [comment]
Hi - thanks! This gets me most of what I'd like. Does it support labels? If I can write a metric selector, I can pass something like `http_request_duration_count{server=~"cortex-*"}` to get label names that exist on HTTP requests that for any cortex server. I'm not sure if I can do that with this feature.
