### ISSUE TITLE
[Feature request] Make Graphite time series rounding configurable or intelligent

### ISSUE THREAD

**Issue by greck** [grafana/grafana#8337]
Grafana 4.2.0
Graphite 0.9.15
Ubuntu 16.04 LTS

Commit [02af2db](https://github.com/grafana/grafana/commit/02af2dbe7314a991635c6ec02c91610bfc28a972) introduced a one-minute padding of time ranges requested from Graphite to cure [issue #320](https://github.com/grafana/grafana/issues/320). This yields very over-padded results when using time series with much higher resolution (e.g. 5 seconds). In these cases, trying to use (again, e.g.) Singlestat to generate summary results over a time range is fairly imprecise. Adjusting the rounding amount to 5s to match our time series resolution generates excellent results.

May I suggest either

a) Allowing the padding to be configurable in grafana.ini

or even better

b) Detecting the resolution for each Graphite series and padding by 1 sample period, whatever it's duration

**Comment by accwebs** [comment]
+1 for this.  

My symptoms were that I could not zoom a Grafana graph in closer than about a 2 minute range.   This is problematic behavior when trying to inspect a particular part of the graph closely (when you have, say, very-granularity data reporting in Graphite).  

I found that commenting out the following code in graphite's datasource.ts (translateTime function) worked around the problem (with obvious side-effect of reintroducing issue #320):

```
    // graphite' s from filter is exclusive
    // here we step back one minute in order
    // to guarantee that we get all the data that
    // exists for the specified range
    if (roundUp) {
      if (date.get('s')) {
        date.add(1, 'm');
      }
    } else if (roundUp === false) {
      if (date.get('s')) {
        date.subtract(1, 'm');
      }
    }
```

Searching 'grafana minimum range' and 'grafana minimum zoom' didn't help (obviously, since there isn't one, except for this data source).  Maybe this comment will add the keywords needed for the search engines to find this next time :-)

**Comment by itsmylife** [comment]
@grafana/observability-metrics does not currently have the bandwidth to prioritize development on this issue. If members of the community want to take this issue we will help review any submitted PRs. Please upvote or comment to help us re-prioritize this issue in the future!
