### ISSUE TITLE
timeGroup macro to fill values only until present moment

### ISSUE THREAD

**Issue by xforman2** [grafana/grafana#83663]
**Why is this needed**:

I could be useful if user could select whether or not he wants to fill values completely throughout the whole time range or
just cut it at now. 
One example can be the time-series graph:
![image](https://github.com/grafana/grafana/assets/129223585/042e998a-9336-46cb-b490-f61f21eb84ca)

- User selected time range that goes to future
- Graph fills the values using timeGroup macro like so: $__timeGroup(x, y, 0) 

As you can see it could be quite confusing because now it seems that the values are there for the future timestamps

**What would you like to be added**:

Option for user to cut the filling time range to current timestamp. 
Result would look like this:
![image](https://github.com/grafana/grafana/assets/129223585/ea8a83da-0c7d-40d6-8a72-30cf5662cfa2)

**Who is this feature for?**

It would be beneficial for users who want to have more control over how their time-series graphs are displayed, especially when dealing with future timestamps.

**Comment by gabor** [comment]
(copy of the comment from https://github.com/grafana/grafana/pull/83665#issuecomment-2115235339)

hi @xforman2 thank you for creating the issue and the PR! unfortunately, we have decided that we will not add this feature, because it adds a lot of complexity while what we gain is small, considering the usual time-ranges, like "last 6 hours" already end at "NOW" so there would be no observable difference. some examples of the extra complexity:
- the user-interface becomes very complex (the macro has now 4 parameters)
- the source code also becomes more complicated. please note that it would need some more code to handle certain corner-cases, like what if there are data-points in the future etc.

sorry. we'll close the issue and the accompanying PR.
