### ISSUE TITLE
Repeated panels should move independently

### ISSUE THREAD

**Issue by mdvictor** [grafana/grafana#83917]
Currently, repeated panels move around the layout as a group, instead of individual panels. 

Steps to reproduce:
- Add a custom variable with some numeric values and multi select
- Select multiple values in the variable
- Add a new viz panel in edit mode
- In panel edit set the panel repeat to that variable
- Drag and drop one of the panels

It should drag all panels as a group, which we do not want. We want each repeated panel to be independently moved.

https://github.com/grafana/grafana/assets/36818606/5e30e865-5545-4595-88de-89156a2263f0

**Comment by FOWind** [comment]
I don't think it's necessary to move the repeated panel independently , because the repeated panel is depended on the variable, while the variable changes the panels will change, adding this features means we should hold the states for each variable.

**Comment by dprokop** [comment]
@mdvictor - this is intentional change we introduced when @torkelo implemented the new repeat behavior. Moving repeated panels independently was very awkward and lead to weird bugs. Now those are considered groups that you can move and resize together.

**Comment by gsainsbury86** [comment]
To justify this request, I'd like to explain my use case which would also benefit from this, or an alternative approach.

I have panels which are Text/HTML panels containing some HTML and Javascript to fetch a video stream and display it in an iframe. Each panel is associated with a particular camera, but I'd like to have these panels be placed specifically because the number of cameras do not change and they are associated with other information on the dashboard.

A library panel is not suitable because there is an identifier which is used for each camera and so the script changes. Variables seem like one way to do this, but then I cannot move them. Library panels also seem like a potential option, but then I cannot edit them individually. At the moment I am manually duplicating and editing the panels but that is problematic if I want to change anything about the panel.
