### ISSUE TITLE
Azure Monitor: Time-range for Log queries do not appear consistent between Grafana versions 9.5.16 and 10.3.3

### ISSUE THREAD

**Issue by judyer28** [grafana/grafana#84410]
### What happened?

In Grafana v9.5.16 there was no time-range option for log queries.  The query for my panel does not explicitly define a time range so it just used the specified dashboard time range.  In Grafana v10.3.3 there is an option for my query to use time-range defined in query or dashboard.  See here:
<img width="455" alt="image" src="https://github.com/grafana/grafana/assets/60985418/8b55b8a8-aef9-4d7e-8136-40f4c18e67b3">

If I import a dashboard from v9.5.16 to v10.3.3 it sets this Time-range by default to "Query."  But I have no time range explicitly specified in the query so it pulls all data.  In V9.5.16 this same query only pulled data defined by time range specified in dashboard.  This is inconsistent and feels like a bug in the upgrade process.

### What did you expect to happen?

I expected the same behavior for the time range set for the query when upgrading between versions.

### Did this work before?

Unknown.

### How do we reproduce it?

1.  In version 9.5.16, create an Azure Monitor Log query that does not include a statement for specifying time range.  This means it will use the Dashboard time range. 
2.  Export the diagram to JSON and import into version 10.3.3
3.  Open the query and you will time-range set to query.  Should be set to dashboard.

### Environment (with versions)?

Grafana: 9.5.16 and 10.3.3
OS:  Windows
Browser:  Microsoft Edge

### Grafana platform?

Other

### Datasource(s)?

Azure Monitor

**Comment by judyer28** [comment]
@kayodeprinceMS, @taleena

**Comment by taleena** [comment]
@kayodeprinceMS I think you brought something up in this area this week - LA question around session ID?

@judyer28 this is fixed and works as expected if you select Dashboard, yeah?

**Comment by judyer28** [comment]
Yes, if I change all the queries to dashboard it then works as it did in version 9.5.16

**Comment by kayodeprinceMS** [comment]
This issue is unrelated to using session ID for LA queries. This is based on the Time range 'Dashboard' vs 'Query 'option having different default settings across Grafana version upgrades.

**Comment by alyssabull** [comment]
Hi @judyer28 + @kayodeprinceMS! Thanks for your feedback. In [this PR](https://github.com/grafana/grafana/pull/67914) the ability to use the dashboard time range was added. We received community feedback outlined in [this PR](https://github.com/grafana/grafana/pull/71278) to give users the option to control the time range by switching between Query (only time-ranges specified within the query are used) or Intersection (Grafana time-range intersected with any time-ranges specified within the query) with Query being the default behavior. Most recently, in [this PR](https://github.com/grafana/grafana/pull/74675) the Intersection option was removed and replaced with Dashboard to reduce confusion. Adjusting the queries to dashboard is the expected behavior.

**Comment by judyer28** [comment]
@alyssabull I'm not sure I understand what you are saying.  To clarify, are you saying that the behavior I experienced when upgrading from 9.5.16 to 10.3.3 is expected?  That it will switch from dashboard time range to query based time range?

**Comment by aangelisc** [comment]
Hi @judyer28 - that's correct, the current behaviour is that queries will default to utilising the query time-range unless the `dashboardTime` property is set in the query.

**Comment by alyssabull** [comment]
Closing this issue as resolved.
