### ISSUE TITLE
Grafana 4.3.1 breaks influxdb datasource support as non-admin user

### ISSUE THREAD

**Issue by maxenced** [grafana/grafana#8481]
Introduced in Grafana 4.3.1, commit 89a7c2c686854790f5306ab6de7f7aa48a55643b introduced a regression. 

The SHOW DATABASES request is available only to influxDb admin users. However, it is expected that non admin users can be defined for datasource creation. 
There is an issue on InfluxDb side ( https://github.com/influxdata/influxdb/issues/4785 ) about this. Fix is expected to be released in 1.3.0 milestone.

Until this, using Grafana 4.3.1 breaks every influx datasource as long as non-admin users are used.

Maxence

**Comment by torkelo** [comment]
This error message does not stop the data source from being saved/updated, just the test & verification step that is failing. Since they are going to fix this in InfluxDB 1.3 I will close this

**Comment by rwarren** [comment]
Just to clarify for anyone else landing here, you *can* use a non-admin influxdb user, even though you get the grafana error.  It is only the "Test" portion of Grafana's "Save & Test" that fails. 

If you get the message below it **is** actually working (assuming the user you specified has read access to the influxdb database) since a connection was made.

```
InfluxDB Error
error authorizing query: grafana not authorized to execute statement 'SHOW DATABASES', requires admin privilege
```

**Comment by joriws** [comment]
But still on grafana-side we could discuss is "SHOW DATABASES" required on datasource "save&test" when vital is connection to influxdb, enter auth and the "USE [database entered in datasource]". Additional checking could be "SHOW MEASUREMENTS".
