### ISSUE TITLE
Lazy Loading: Reverting

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#8500]
This feature is reverted due to a internal Chrome bug that causes all javascript execution to hang if scrolling when XHR requests are being made. This paired with lazy loading caused a very slow experience when scrolling down a long dashboard.

**Comment by robskillington** [comment]
PS @torkelo is there any news on whether this will be brought back, even if only in a config opt-in manner?

Uber is at 4.3.1 and would love to upgrade our internal to 4.4 to be able to use dashboard histories, however the speed benefit (we have a ton of very large dashboards) and also resource benefit (not rendering graphs not in view every page load) is a large mitigating factor against us upgrading.

**Comment by torkelo** [comment]
No news yet, we can bring it back once the chrome bug is fixed (in Chrome)

**Comment by robskillington** [comment]
@torkelo is there a way we can provide this optionally with a configuration switch?  This bug is not manifesting for us.  If you wanted to point us in the right direction to how we might go about making a change to make it configurable opt-in we'd be more than happy to do the leg work to submit a PR, etc.

Also do you happen to have a reference to the Chrome bug in question?  I went for a quick look and could not find it.

**Comment by torkelo** [comment]
can''t find the issue right now, but there was one in the chrome issue tracker.

**Comment by ghwlchlaks** [comment]
when I get iframe source to another page, it occurs like this. How can I fix?
<img width="163" alt="default" src="https://user-images.githubusercontent.com/29689525/31802060-fd3792e0-b586-11e7-839f-ac28f7fae5dd.png">

**Comment by simPod** [comment]
What about now?
