### ISSUE TITLE
AdHocFilters: Allow picking multiple values for a given dimension

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#85074]
Ad hoc filters should allow picking up multiple values for a selected dimension. 

It's currently possible from the UI to an extent if the data source API (`getTagKeys`) will not respect previously selected filters when returning available dimensions. But eventually this is problematic, as it requires the user to configure multiple filters for the same dimension and the data source implementation to respect the multiple filters configured for a dimension.

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. This is a friendly reminder that the Steady `11.1.x` Release branch has already been cut. This means that PRs merged to `main` from now on will not go into any `11.1.x` Release unless they use the [backport v11.1.x](https://github.com/grafana/grafana/labels/backport%20v11.1.x) label.

I'm mentioning that since this issue is marked with [Milestone 11.1.x](https://github.com/grafana/grafana/milestone/512). Please, consider if moving this issue to [Milestone 11.2.x](https://github.com/grafana/grafana/milestone/529) makes sense for you.

Thank you!
