### ISSUE TITLE
Dashboards/Explore: '@' in graphite path causes issues

### ISSUE THREAD

**Issue by dmrlawson** [grafana/grafana#85142]
### What happened?

If a graphite path contains an '@' character the dropdown mode editor behaves strangely. It will either cut off before the '@' character or will refuse to go into the dropdown mode.
![grafana_at_symbol](https://github.com/grafana/grafana/assets/6436321/b297c0ae-e5bd-439e-9e95-8cae7f93443a)

### What did you expect to happen?

Dropdown mode to display the path that is typed in text mode.

### Did this work before?

I believe this might have been an issue for a while.

### How do we reproduce it?

1. Go to Explore
2. Type in a graphite path containing an '@' character
3. Observe that switching to dropdown mode cuts the path off before the '@' character

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Grafana v10.4.1 (d94d597d84)
OS: Linux
Browser: Chrome 123.0.6312.58

### Grafana platform?

Kubernetes

### Datasource(s)?

Graphite

**Comment by bucko909** [comment]
Most likely because the symbol is absent here:

https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/graphite/lexer.ts#L67

Causing the lexer to bail out mid-way without error here:

https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/graphite/lexer.ts#L149

Adding the symbol seems trivial enough, however I'm not set up for dev on Grafana currently, and I'm not sure if the lexer can be more sensible about bailing out, which would be a more "proper" additional fix.
