### ISSUE TITLE
[Feature request] Add "semantic versioning" to Units

### ISSUE THREAD

**Issue by karolisc** [grafana/grafana#8542]
Hi, 

I have `semantic` BIOS version in the table e.g. 1.0.1 per server and would like to color it depending on threshold limits. 

Have tried some `thresholds` variations but I guess it fails due to it does not recognize the data type:

```
1.0.0,2.0.0
"1.0.0","2.0.0"
1,2
```

Karolis

**Comment by torkelo** [comment]
This feels like a very uncommon edge case. So would not expect many to need this (and is therefore unlikely to be added)

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.

Thank you to you for taking the time to create this issue!
