### ISSUE TITLE
[Docs] Templating section: Needs improvement

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#8555]
We currently have an old, section on templating: http://docs.grafana.org/reference/templating/#templating

This needs to be extended substantially to include:
- What is templating in Grafana?
- Adding and configuring template variables
- Using templating in dashboards
- Common Use Cases
- Ad-hoc filters (currently only mentioned in release notes and influx page)

**Comment by torkelo** [comment]
It's not old, it just saw a massive update and rewrite a few weeks ago, spent 3 days on a total overhaul, so it's not top priority anymore, (it was in a miserable state but quite good now). A few holes, and maybe more concrete examples & guides.

The templating sections with each datasource doc also saw rewrites. So the main thing goes missing is ad-hoc variables, otherwise most of the list is done.can be fleshed out more. But I think that mainly has to e be done in separate guides as it so different for each datasource

**Comment by mattttt** [comment]
Awesome! Thanks @torkelo
