### ISSUE TITLE
Dashboard Variables: Missing Query Options (Query Definition) using query variable type 

### ISSUE THREAD

**Issue by Dzuzepppe** [grafana/grafana#86662]
### What happened?

You are not able to configure query, using query variable type.
Options are not available:
![image](https://github.com/grafana/grafana/assets/57093337/b32ae39a-4570-48fb-ade2-af85b3bf9570)

### What did you expect to happen?

Query options should be available:
![image](https://github.com/grafana/grafana/assets/57093337/99bcc042-6f27-4e3a-a84e-510bda08fe37)

### Did this work before?

Query options not available in Grafana Version 11.0.0-preview
Last tested version was Grafana 9.4

### How do we reproduce it?

1. Start Grafana 11.0.0 - preview (docker version)
2. Create new dashboard
3. Define new Query Variable
4. Try configure Query variable

### Environment (with versions)?

Grafana: 11.0.0
OS: Docker
Browser: Opera One(wersja: 108.0.5067.29)

### Grafana platform?

Docker

**Comment by sam30606** [comment]
It also happen at latest version.

**Comment by Dzuzepppe** [comment]
It looks like that bug was related to my custom datasource. We can close this report. Sorry for unjustified bug report.

**Comment by quanghungb** [comment]
> It looks like that bug was related to my custom datasource. We can close this report. Sorry for unjustified bug report.

hey @Dzuzepppe I got the same issue that yours. How do know and fix it?

**Comment by testinfected** [comment]
hey @Dzuzepppe I have the same question. Thanks!

**Comment by quanghungb** [comment]
hey .. for those who would have the same issue than me. FYI how mine is resolved below

It seems to be that some new prom datasources have been added recently and there is NO default datasource!  

The query variable seems to consider that there are no available prom datasource so the "query options section" does not show up.

I just defined a default prom datasource...  then the "query options section" show up again when I tried to create a new one.

Grafana could warn us instead of hide it silently. :(
