### ISSUE TITLE
[Feature request]Automate extracting metrics from a dashboard

### ISSUE THREAD

**Issue by storagedevops** [grafana/grafana#8667]
Would love to see a new feature that allows one to extract metrics from a dashboard into a csv file which can then be emailed or stored.  Something like a report feature feature that can be scheduled.  Just putting this out there to see if there is enough interest.

**Comment by torkelo** [comment]
dashboards & panels are UI constructs, so to automate them it would have to involve a browser so this is not easy to do.  

We hope to introduce a fully featured reporting (PDF/CSV most likely) feature next year.

**Comment by petemyron** [comment]
This isn't exactly what you're looking for since it's not in the UI, but maybe this will help someone else trying to get data out of Grafana programmatically. I eventually got this to work for getting the graphed data "exported" in json: _query the datasource directly_. This is what happens when the graph refreshes with ajax.

Here's a relatively complex, nested query and how to curl it. The query looks like this (it gets messy with url encoding): `SELECT mean("weightedAverage") FROM (SELECT "avg"  AS "weightedAverage" FROM "thing" WHERE "Operation" = 'offers' AND time > now() - 1h) WHERE time > now() - 1h  GROUP BY time(1h) fill(null)`

```
https://[grafana]/api/datasources/proxy/1/query?db=[database]&q=SELECT%20mean(%22weightedAverage%22)%20FROM%20(SELECT%20%22avg%22%20AS%20%22weightedAverage%22%20FROM%20%22thing%22%20WHERE%20%22Operation%22%20%3D%20%27offers%27%20AND%20time%20%3E%20now()%20-%201h)%20WHERE%20time%20%3E%20now()%20-%201h%20GROUP%20BY%20time(1h)%20fill(null)[&epoch=ms]
```

This outputs the data in json format:

`{"results":[{"statement_id":0,"series":[{"name":"thing","columns":["time","mean"],"values":[["2017-08-08T16:00:00Z",29.630639730639732],["2017-08-08T17:00:00Z",26.182254196642685]]}]}]}`

**Comment by ashu-rawat** [comment]
Dear Torkelo,

Have we got this feature now?

**Comment by akaeme** [comment]
+1

**Comment by Magthalion** [comment]
+1

**Comment by Alexander-Minyushkin** [comment]
> Dear Torkelo,
> 
> Have we got this feature now?

UI feature was released in v6.4 for enterprise https://grafana.com/docs/guides/whats-new-in-v6-4/#reporting

But I  @storagedevops was waiting for API

**Comment by psuter80** [comment]
@storagedevops, you could use `/api/datasources/proxy/1/render?target=powermeter.phase*.watt&from=1598939104&until=1598939114&format=json` or even use `format=csv` to export data from grafana.. it won't export an entire panel, but at least you can get the same data using the same query string as in a panel. 

sadly the csv export is not very useful as it does not create a nice table with multiple columns for multiple data targets. that's why i wrote a [little php script ](https://wiki.psuter.ch/doku.php?id=api_csv_export_for_grafana) to help re-format the json output to a csv table. may not be what you are looking for but could give you some inspiration to implement your own workaround.

**Comment by awnyshaheen** [comment]
> @storagedevops, you could use `/api/datasources/proxy/1/render?target=powermeter.phase*.watt&from=1598939104&until=1598939114&format=json` or even use `format=csv` to export data from grafana.. it won't export an entire panel, but at least you can get the same data using the same query string as in a panel.
> 
> sadly the csv export is not very useful as it does not create a nice table with multiple columns for multiple data targets. that's why i wrote a [little php script ](https://wiki.psuter.ch/doku.php?id=api_csv_export_for_grafana) to help re-format the json output to a csv table. may not be what you are looking for but could give you some inspiration to implement your own workaround.

Hi Pascal,
Is it still working in the last Grafana update?
I saw your code, what is the target param? is it dashboard uid? can you please explain your solution with some example?
I tried to contact you but I didn't find your mail anywhere
I really hope that you can reply to my question.

Thanks in advance
Awny
