### ISSUE TITLE
Explore: Toolbar hides items in a kebab menu even if there's enough space to show them

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#86830]
Investigate why toolbar items are being hidden even though it looks like there's enough space to fit them. Please check https://github.com/grafana/grafana/pull/86279#issuecomment-2072353681 for more details.

**Comment by gelicia** [comment]
This behavior to do with the ordering of items - specifically having a child with a smaller width come before a child that is wider. 

The intersection observer in the component simply looks at the entries, and if any of them intersect, they are hidden behind the kebab menu ([src](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/ToolbarButton/ToolbarButtonRow.tsx#L46)).

The entries it looks at goes left to right, meaning the 0th entry is query library (143px wide), and 1st is the split options (237px). When the query library intersects, it is hidden, giving 143px of empty space, then when the split options is hidden, it frees up 237px of space - this is enough to show query library, but as the query library button has already previously been intersected, it will stay that way.

Rather than try to make this function go through and figure out what smaller elements to show and hide just based on width of what is hidden vs what is not, I think (if this problem needs to be fixed absolutely) we would want to pass in a list of indexes that indicate the priority of things hidden. So even though the entries array is [query library, split options], it would hide the split options first if it intersected. 

We could also swap the positions of query library and the split buttons, if we wanted to.

Honestly though, the logic as is, while it does look confusing at some screen widths, does preserve the order of the entries which is probably important for consistency. I also don't want to change our existing element order for this. I would recommend not bothering to fix this unless it becomes a more pressing issue.

**Comment by ifrost** [comment]
Thanks @gelicia for a great write up! It seems it all works as expected. 

@diegoadams do we think we can close it? If you have a specific ideas on how to change / reorder elements we can include it as a part of toolbar redesign work.

**Comment by diegoadams** [comment]
@ifrost, yes, we can close this. I agree with @gelicia comment above.  

I will be working on the toolbar redesign so any new edits or responsive suggestions can go there. 
We'll likely shuffle some buttons around and later assess how these changes impact the responsive behaviour.

This is a great figma plugin i found to help with that. 

Uploading Screen Recording 2024-05-13 at 18.22.44.mov…
