### ISSUE TITLE
Explore: Show user who created the query template

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#86987]
Grafan API Server does not support this out of the box yet. For an experimental stage of the feature we can, however, apporach it the same was as SLO app:

* Store user name or email as meta in the resource spec: https://github.com/grafana/slo/blob/fee5b77a651067b42ba2345ec664a2311aebe8ab/definitions/slo.grafana-slo-app.plugins.grafana.com.json#L129
* ~The user should be added in backend, SLO app is doing it [here](https://github.com/grafana/slo/blob/2e06b0537f0c21f47058849b8cd47c5dcbd5ed91/pkg/api/slo_handlers.go#L459) (this is called for example [here](https://github.com/grafana/slo/blob/2e06b0537f0c21f47058849b8cd47c5dcbd5ed91/pkg/api/slo_handlers.go#L265))~ (seems plugins do it in a different way, see below)
* It can be extracted from appcontext like in [DashboardSnapshot](https://github.com/grafana/grafana/blob/36f42853dd348aade4fb1dc005d488ea2baed73e/pkg/registry/apis/dashboardsnapshot/register.go#L253)

Another apporoach would be to do it front-end only and pass the user in the payload but that will only fly during experimental stage ⚠️  (otherwise it'd be too easy to submit something for a different user)

**Comment by gelicia** [comment]
I investigated this but after some debugging and discussion, it is not currently possible with how app platform works - the action of creating a new query library entry doesn't have its own go code, it is simply added from the front end by the app platform. Since we want adding the user data to be handled by the backend, we either need to add this into the app platform or create some middleware to make this possible. I would recommend the app platform team figure this aspect out, as it's something others will want - not just the query library.

**Comment by ifrost** [comment]
I think we can unblock this. It seems we can work on unified storage which already supports annotating with the user who created the resource, e.g.

![Image](https://github.com/grafana/grafana/assets/745532/255c98a6-2503-424d-b59e-de2b5161b6b8)


Make sure you use the following config to enabled US:

```
[grafana-apiserver]
storage_type = unified
```

[This PR](https://github.com/grafana/grafana/pull/88877) should also bring annotations to the generic strategy and make it work with file system storage type.
