### ISSUE TITLE
Templating with same node (application) name in Graphite path.

### ISSUE THREAD

**Issue by JosephFY** [grafana/grafana#8724]
I have the following Metrics from a Graphite data source

Sever1.App1.Metric1 
Sever2.App1.Metric1 
Sever3.App1.Metric1 
Sever4.App1.Metric1 
Sever5.App1.Metric1

I am trying to create a templating for the applications as $app, as you can see the app name is the same across multiple servers and when I set the panel to be repeated on the variable it shows all the Metric1 on one panel instead of repeating it(and on the list it shows only App1 to select from). Not sure if this is an issue or if there is there any work around for this? let me know if more explanation is needed please.

- What Grafana version are you using?
 Grafana v4.2.0 (commit: 349f3eb93)
- What datasource are you using?
Graphite
- What OS are you running grafana on?
Windows Server 2012

**Comment by daniellee** [comment]
This does not sound like a bug. Questions should be asked on our community site: https://community.grafana.com/

If you created a template variable $app, that only contains one value `App1`. Then the panel will only be repeated once.

It sounds like you need to create a template variable for server with values Server1, Server 2 etc. and repeat on that instead. (Don't forget to use the template variable in your query so that each panel shows the results per server).
