### ISSUE TITLE
[Feature request] Group annotations into groups to make many annotations close together more visible 

### ISSUE THREAD

**Issue by yoshikakbudto** [grafana/grafana#8758]
Sometimes we have a series of events almost at the same time. Those are looks like one annotation. And it could lead to a wrong understanding of the importance of the problem. We had 50+ crashed services at time (which is a big number for us) and for all of them there was an annotaion, but it looked like a one. We just by some luck zoomed in to 1 minute period  (out from the "last 24h period")  to see the thruth.

So it would be a great feature to somehow show that thereare more then one annotation on grafix. For example, to show a ballon with "+NN more, please zoom in to reveal" or to tile the first 10 and if there more to notify about them also

**Comment by pkolyvas** [comment]
We're in the process of [moving how we process feature requests in GitHub from GitHub Issues to GitHub Discussions](https://github.com/grafana/grafana/issues/36683).

As part of that process, we're closing many issues to help clean the slate. This one caught my eye because we have a feature being released in Grafana 8.1 that will help solve this concern, though not in the way proposed here. 

We're [introducing an Annotations Panel ](https://github.com/grafana/grafana/blob/3af9759d1d3727de589481aabc4537addcd1da97/docs/sources/panels/visualizations/annotations.md)that will be able to list out Annotations on a given dashboard (or even for your whole organizations). This can make it easier to discover and filter annotations that may be very close together. I've linked to the raw docs here because we're just publishing them now. You can try the panel in the Grafana beta release if you like!

Should you try the panel and find it doesn't meet your needs, please do [start a feature request on our GitHub Discussions board.](https://github.com/grafana/grafana/discussions)
