### ISSUE TITLE
can support a plugin of kylin database

### ISSUE THREAD

**Issue by winterJIE** [grafana/grafana#8772]
can support a plugin of kylin database or give a document of how to write a datasource plugin

http://kylin.apache.org/

**Comment by daniellee** [comment]
This probably will not be possible until we introduce backend plugins. We currently only have frontend plugins. The new MySQL data source has a Go backend and this would be similar. 

Backend plugins are on the [road map](https://github.com/grafana/grafana/blob/master/ROADMAP.md) for Grafana.

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest. 

It is possible to build this yourself: 

- https://grafana.com/docs/grafana/latest/developers/plugins/
- https://grafana.com/tutorials/build-a-data-source-plugin

Thank you to you for taking the time to create this issue!
