### ISSUE TITLE
[Feat] Unit duration days/seconds without auto conversion

### ISSUE THREAD

**Issue by daven1985** [grafana/grafana#8781]
I would like to stop my Up Time single stat's from going to Weeks/Months/Years. Is there a way to set them to stay in the Day format... so it would say 65 Days up instead of 2.1 Months?

Cheers.

**Comment by daniellee** [comment]
Unit as short and then use the postfix field like this:

![image](https://user-images.githubusercontent.com/434655/27926386-8df5a0b2-6288-11e7-815c-d20fdb1a9ba5.png)

**Comment by ET-Bent** [comment]
@daniellee this makes no sense since the uptime in most cases is provided in seconds.

**Comment by torkelo** [comment]
There are units for duration that can calculate seconds to days

**Comment by SamuelmAsh** [comment]
Singlestat in grafana 5+ is turning seconds from my uptime data to decimals of year when set to duration seconds or Seconds.   I have uptime of 38342755s, when setting the unit to seconds it displays as 1.21years. How can i resolve this, i was happy to scale it by division but that option seems to have gone with newer versions ?

**Comment by marefr** [comment]
@SamuelmAsh what do you expect to see - the results in seconds? Then skip the unit and add postfix of s or seconds. Have you tried the duration (hh:mm:ss)?

**Comment by SamuelmAsh** [comment]
I would like to see the result in hours/days or just days, or just hours. Anything less precise than seconds but moreso than year.year :)  

hh:mm:ss just shows 10651:35:55 

dd:hh:mm:ss is probably more what im after but i cant see an option

**Comment by pabigot** [comment]
I would also like this feature.  1179811 seconds comes out as 327:43:31 which is not easily understood.  I'd prefer `# d HH:MM:SS` (`13 d 15:43:31`) over `dd:hh:mm:ss` (`13:15:43:31`) to make the separation between number of days and time more clear.

**Comment by torkelo** [comment]
To fix this is easy for anyone up for creating a PR for this: 

We support custom prefixes if you type `prefix:unit` (then select Custom option in the unit picker)

We do support custom suffixes as well by just typing in something that does not match an existing unit id. But for `s` and `ms` etc they do exist already as units (that scale) so you cannot have a custom suffix with those today. But it is easy to add: 

We just need to add support for custom suffix in the same way we support prefix. So if the unit specified is `suffix:<unit>` we only show the unit specified as suffix. 
https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/valueFormats/valueFormats.ts#L197

**Comment by Loader23** [comment]
@torkelo Is this a solution or a suggestion? I can't find a custom option in the unit picker.
I just started with Grafana and Iam suprised that something like dd:hh:mm:ss is so difficult to achieve.

**Comment by pabigot** [comment]
It's not clear to me how the suffix approach solves the problem at least in the way [I proposed](https://github.com/grafana/grafana/issues/8781#issuecomment-432631725) so I've done it a different way in #24175.

**Comment by pabigot** [comment]
I think there are actually two features requested between this issue and #23712:

* The original feature requested here is to have a single-value durations expressed in the largest unit that doesn't exceed the duration, but to stop advancing the unit at Days.  Thus 5618765 seconds would display as "65 days" rather than "9 weeks" or "2 months", but 45 seconds would still display as "45 seconds"

  #23712 wants that feature using a cap in seconds.

* A different feature requested in  https://github.com/grafana/grafana/issues/8781#issuecomment-393874576   wanted 38342755 seconds to be displayed as something like "443 d 18:45:55" rather than "10650:43:31".

The second feature is the one added by #24175.  Perhaps it should be its own issue?

I'm probably missing something, but I don't see how custom prefixes or suffixes would make the first feature easy to implement, as the unit to use is value-dependent.  Rather it looks like an extension to `toDuration()` is required that adds another Interval parameter and won't generate elements for units larger than the maximum requested.  Something like:
```
diff --git a/packages/grafana-data/src/valueFormats/dateTimeFormatters.ts b/packages/grafana-data/src/valueFormats/dateTimeFormatters.ts
index 971683276a..5ccdf4f97e 100644
--- a/packages/grafana-data/src/valueFormats/dateTimeFormatters.ts
+++ b/packages/grafana-data/src/valueFormats/dateTimeFormatters.ts
@@ -179,7 +179,7 @@ export function toDays(size: number, decimals?: DecimalCount, scaledDecimals?: D
   }
 }
 
-export function toDuration(size: number, decimals: DecimalCount, timeScale: Interval): FormattedValue {
+export function toDuration(size: number, decimals: DecimalCount, timeScale: Interval, maxScale: Interval): FormattedValue {
   if (size === null) {
     return { text: '' };
   }
@@ -189,7 +189,7 @@ export function toDuration(size: number, decimals: DecimalCount, timeScale: Inte
   }
 
   if (size < 0) {
-    const v = toDuration(-size, decimals, timeScale);
+    const v = toDuration(-size, decimals, timeScale, maxScale);
     if (!v.suffix) {
       v.suffix = '';
     }
@@ -222,7 +222,13 @@ export function toDuration(size: number, decimals: DecimalCount, timeScale: Inte
     decimalsCount = decimals as number;
   }
 
-  for (let i = 0; i < units.length && decimalsCount >= 0; i++) {
+  let i = 0;
+  if (maxScale) {
+    while (i < units.length && units[i].long !== maxScale) {
+      ++i; 
+    }
+  }
+  while (i < units.length && decimalsCount >= 0) {
     const interval = INTERVALS_IN_SECONDS[units[i].long] * 1000;
     const value = size / interval;
     if (value >= 1 || decrementDecimals) {
@@ -233,6 +239,7 @@ export function toDuration(size: number, decimals: DecimalCount, timeScale: Inte
       size = size % interval;
       decimalsCount--;
     }
+    ++i;
   }
 
   return { text: strings.join(', ') };
```

so `toDuration(5618765, 0, Interval.Second, Interval.Day)` returns `"65 days"`, but I have no clue how to get that fourth parameter through the UI to where it could be used.

**Comment by pabigot** [comment]
This issue was closed with a feature that I don't think covered the use cases several people commenting here had in mind.  I've added #25830 and #25831 to provide more detail on those cases.
