### ISSUE TITLE
Alert tab not visible for panels for certain visualization types

### ISSUE THREAD

**Issue by nagylzs** [grafana/grafana#87909]
### What happened?

- Create a new panel with "time series" type
- Add a query, save the panel
- Add an alert to the panel (using the "Alert" tab on the panel editor) and save it
- Check appearance: the panel shows on the dashboard, and also the heart icon is showing the state of the associated alert
- Then go back and edit the panel
- Change its visualization type to something else - in my case I changed it to "heatmap"
- Notice that the "Alerts" tab disappears from the panel editor <<<< this is the actual bug
- Save the panel and look at the dashboard. The alert heart icon is still there ,and the alert is still associated with the panel. It works, but it is not accessible through the panel editor.

![image](https://github.com/grafana/grafana/assets/15814836/86eece71-8661-4be4-b11b-8ee44460de88)

![image](https://github.com/grafana/grafana/assets/15814836/b6893047-4353-4999-8c19-ef42de401e01)

If you change back the visualization type to time series, then the alert re-appears.

### What did you expect to happen?

Always show the "Alert" tab, independently of the panel type. The alert can have a separate underlying database query; there is no reason to hide it.

### Did this work before?

I have no idea if it was working before.

### How do we reproduce it?

Please see the "what happened" section for this.

### Is the bug inside a dashboard panel?

I'm not able to paste the panel's JSON here because the db query is confidental, but this problem is a general, so it seems.

### Environment (with versions)?

Grafana: [Grafana v11.0.0 (277ef258d4)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
OS: Server is Ubuntu 22.04.3 LTS
Browser: Chrome on linux (not relevant, it happens on all browsers)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment]
Hi @nagylzs 

Thank you for creating this issue

We were actually about update the docs to list the panels that support alerts (time-series, and alert list panel)

Alerting will only work if the data format is in wide series. However, since data sources can emit different sorts of data frame formats (even switching dynamically based on toggles / drop downs in the data source editor), we can't determine whether to show the alerts tab in panels other than the one listed above. Similarly, Grafana won't update the UI retro-actively.

Hope that makes sense. 
I'm closing this issue, but feel free to add any feedback or comments!

**Comment by nagylzs** [comment]
I'm sorry, I don't understand the explanation. The alert has its own query. The data format is determined by the query of the alert, not the query of the panel. How can the data panel's query limit the associated alert?

**Comment by tonypowa** [comment]
You're right, the alert rule doesn't need to match the visualization since they're separate. We only show the alerts tab for time series because that's what the old system supported. It's something we might revisit later. There are valid use cases for supporting alert rules in panels.

**Comment by nagylzs** [comment]
Should we open this issue then? Or do you think that it works as it should? (I don't see any reason for not showing the alert tab.)

**Comment by tonypowa** [comment]
I've reopened the issue and added it to the Alerting project for future planning or backlog consideration. Currently, only the time-series and alert list panels support alerts. While we recognize the value in extending this feature to other panels, our team unfortunately does not have the resources to implement this at the moment. We appreciate your understanding and patience.

**Comment by timtofan** [comment]
I was also confused by lack of alert tab for state timeline panel.
It's non-intuitive that some panels types support it while others don't.

**Comment by nagylzs** [comment]
Problem reappeared in a different form, opened a new issue

**Comment by iridos** [comment]
Any updates on this?  
Alerts become pretty hard to find when they are connected to a table or a heatmap, because the panel doesn't indicate an alert. But when these are the best data/representations to have a look at when the alert triggers - I don't want to make a timeseries or graph from something just to make known there is an alert when that's not a good representation.

**Comment by nagylzs** [comment]
> Any updates on this?

This issue is closed but it was reopened here in a different form: https://github.com/grafana/grafana/issues/103039 - please ask there, because that is still open.

**Comment by iridos** [comment]
Oh, thanks for the heads up. That made me realize that our production environment was still on 12.x (testing had 13 for a while) and didn't have it, it has only been fixed recently in 13. 

Thank you for reporting and getting it fixed. 👍
