### ISSUE TITLE
mysql: make sure it's multi-tenant safe

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#87971]
refer to this internal document: https://docs.google.com/document/d/15apCdutmdxJwyt5DdgfLTjPvaX0J5eIPmeoKSNakakM

**Comment by gabor** [comment]
**Project Update**

**Highlight**

no progress

**Trending**

🟢 on track


**Next**

* test PDC and other setup
* fix the tenant id related bug

**Comment by gwdawson** [comment]
**Project Update**

**Highlight**
no progress made updates

**Trending**


🟢 on track


**Next**

test agains edge cases, then deploy to the api server

**Comment by szabalza** [comment]
**Project Update**

**Highlight**
no progress made updates

**Trending**


🟢 on track


**Next**

test agains edge cases, then deploy to the api server

**Comment by gwdawson** [comment]
**Project Update**

**Highlight**

no progress due to being on call and focusing on other tasks

**Trending**


🟢 on track


**Next**

continue with the next steps stated above

**Comment by szabalza** [comment]
**Project Update**

**Highlight**

no progress due to being on call and due to prioritizing the Github app token authentication implementation. There was a security escalation requiring to move away from Gihub PATs and use app tokens instead.

**Trending**


🟢 on track


**Next**

Work will continue next week as the Github app token implementation is almost completed.

**Comment by gwdawson** [comment]
**Project Update**

**Highlight**

no updates due to the extended time working on the GitHub PAT work. 

**Trending**


🟢 on track


**Next**

Work will continue once Github app token implementation is released.

**Comment by zoltanbedi** [comment]
This is done.
