### ISSUE TITLE
[Bug] Templating: query options are not saved until focus changes

### ISSUE THREAD

**Issue by tmalkowski** [grafana/grafana#8803]
Version: grafana-4.3.2-1.x86_64 (via yum repo)

Data source: graphite

OS: RHEL7.3

Steps to reproduce:
- open up templating, and edit one of the dashboard's templating values
- update the Query value (under Query Options). Without changing focus to a different element, hit enter.

Expected behavior: either that field's value is updated, or the keypress is ignored and nothing happens

Actual behavior: edit pane is closed out and the new value is not saved

Haven't looked at the source code, but if I had to guess, I'd imagine there's a input:blur event handler that stores these values in some data structure, and also, a form:submit event handler that reads those stored values, and that leads to the above scenario where the new value isn't stored until I focus elsewhere. I only tested with the one field, but I'd imagine it's not specific to just one of the text fields but everything.

**Comment by matthiasr** [comment]
A very similar (possibly the same) bug happens when creating a new variable. My observation is that hitting enter in with the focus on a text field closes the dialog without saving. tab-ing to the "save" button then triggers the right action.

this has cost me many carefully composed variables already …

**Comment by torkelo** [comment]
think this is fixed in later versions of Grafana
