### ISSUE TITLE
Regarding Significant Errors in Chinese Translation in Internationalization, How Should I Modify the Translation?

### ISSUE THREAD

**Issue by sqkkyzx** [grafana/grafana#88032]
### What happened?

In your instructions on feedback about localization, you mentioned that you would handle translations with your translation partners, and thus do not accept translation contributions. However, I have noticed several obvious errors in the Chinese translation. The translated text fails to convey the original meaning and might even be less clear than using English directly.

For example, in the time picker, "From" is translated as "发件人" (which means "sender"). From my observations, this translation error has persisted for at least two major versions, continuing into the current V11.

### What did you expect to happen?

If you are unable to maintain the accuracy of translations, could you possibly allow the community to contribute to the translations? At the very least, such significant errors should not be allowed to occur.

I noticed that `public\locals\{locale}\grafana.json` is automatically pulled from Crowdin. May I apply to join the Crowdin project? I am willing to maintain the accuracy of the Chinese translations and complete the untranslated texts.

### Did this work before?

None

### How do we reproduce it?

None

### Environment (with versions)?

Grafana: ALL
OS: ALL
Browser: ALL

### Grafana platform?

None

**Comment by sqkkyzx** [comment]
In my memory, these erroneous translations, as well as the overall completion of the translation, seem to have always existed since Chinese was added, from version 9.3 to version 11.

I have reason to suspect that the so-called translation partners do not exist, as these errors appear to be the result of machine translations, such as Google Translate.

I find it perplexing that you refuse community contributions, do not maintain it yourselves, and do not correct the errors.

**Comment by joshhunt** [comment]
Hey @sqkkyzx - this is fair feedback. I'm not fluent in Chinese, so I myself can't speak to the accuracy of the translations. This is what we trust on our translation agency partners (which we definitely use - I promise), but sometimes quality issues slip through due to missing context.

We're still iterating on our translations process, but it's been difficult to prioritise this work. At the moment we don't have the processes to accept external contributions. We're unsure of the model of how to trust translation contributions from the community, and whether we need Grafana employees to be auditors of each language.

I've flagged this issue with our translation agency and we're investigating how to prevent issues like this (due to missing context) in the future. If you have any specific problems or feedback, you can report them in here or in new issues and we'll check them out 👍

**Comment by sqkkyzx** [comment]
Community translation has indeed helped many projects with internationalization, allowing users to translate English into their native languages. Clearly, this is better than having someone who speaks English do the translation, as they are more familiar with idiomatic expressions in their own language.

Of course, I also understand your concerns and distrust.

However, the current issue lies in the fact that the translation company you trust has not been able to effectively advance the work. They have left some errors and a large amount of untranslated text. Across multiple versions, there has been no improvement seen from them. If it were me, I would certainly fire them.

My suggestion is, since you have concerns about community translation, how about having the translation company review the community translations before merging them? You trust them, so you would probably also trust their review results. In any case, the final result would not be worse than it is now.

**Comment by joshhunt** [comment]
Thanks for the feedback. We're continuing to work on improving translations and our processes around them, and I hope to have something in place for community contributions for this one day.

I'll close this for now, but please feel free to report any specific errors in translations and we'll pass them on.
