### ISSUE TITLE
Sorting of organization popup in alphabetical order

### ISSUE THREAD

**Issue by Vitaliy155** [grafana/grafana#88275]
### What happened?

We have 2 organizations and user in both org (Play (id:2) and Infra (id:5) for example)
Grafana integrated with LDAP.

After login to grafana user logged to org Play.
![1](https://github.com/grafana/grafana/assets/90462334/cd83ae4f-fc34-49c2-a479-28c81a2f8a93)

### What did you expect to happen?

After login to Grafana User should have logged to org Infra by default ( in alphabetical order)
https://github.com/grafana/grafana/pull/22259
Seems it was requested and fixed

![image](https://github.com/grafana/grafana/assets/90462334/139a5957-b59b-4ed7-a270-dd52cc229097)

### Did this work before?

I don't know

### How do we reproduce it?

1.Create new one organizations 
2.Create user 
3.Move user to both organizations 
4. Login to grafana

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.2.6
OS: AlmaLinux 8.9
Browser: Firefox 126.0

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment]
Hello @Vitaliy155 

Thank you for  creating this issue

I can't reproduce this issue in Grafana v10.4.1 (without LDAP) . However, since you are using LDAP I am forwarding this to the team for review.

**Comment by kalleep** [comment]
Hey, during login we always try to login to last used org. If a user last was on org Infra then the next login should pick that org otherwise it will select org by lowest id. Signing in by alphabetical order has never been a thing and the issue you pr you linked was just to display them in that order in the picker. 

There exists an option that will try to force a certain org during login but this obviously only work if the user is a member of that selected org.
```
[users]
login_default_org_id =
```

**Comment by Vitaliy155** [comment]
@kalleep  Thanks for update!
