### ISSUE TITLE
Add excerpt about duplicate or out-of-order notifications to our HA Alerting docs

### ISSUE THREAD

**Issue by santihernandezc** [grafana/grafana#88446]
Create a short section explaining potential issues with duplicate/out-of-order notifications and mention the possibility of forwarding alerts to an external Alertmanager cluster.

Related page: https://grafana.com/docs/grafana/latest/alerting/set-up/performance-limitations/

**Comment by brendamuir** [comment]
Hi @ppcano found another one related to high availability.

**Comment by ppcano** [comment]
Hey @santihernandezc,  I am looking at this after working on this [PR](https://github.com/grafana/grafana/pull/92063/). 

The [Alerting high availability docs](https://grafana.com/docs/grafana/latest/alerting/set-up/configure-high-availability/) currently mentions the potential for duplicate or out-of-order notifications:
> While the alert generator evaluates all alert rules on all instances, the alert receiver makes a best-effort attempt to avoid sending duplicate notifications. Alertmanager chooses availability over consistency, which may result in **occasional duplicated or out-of-order notifications**. It takes the opinion that duplicate or out-of-order notifications are better than no notifications.

If we want to discuss using an external Alertmanager to reduce duplicate notifications, I think it makes more sense to include this information in the High Availability docs rather than in the [Performance limitations docs](https://grafana.com/docs/grafana/latest/alerting/set-up/performance-limitations/)), wdyt?

I haven’t tested this setup, so I’m curious whether users would need to configure additional HA settings when using a shared external Alertmanager.

- If no additional configuration is needed, we could simply mention this as an alternative, with a link to the [Add an external Alertmanager instructions](https://grafana.com/docs/grafana/latest/alerting/set-up/configure-alertmanager/#add-an-external-alertmanager).

- If more steps are required, what would those be?

**Comment by santihernandezc** [comment]
@ppcano hi! I agree with adding this info to the High Availability docs instead of the Performance Limitations page. I think the disclaimer about potential duplicate or out-of-order notifications is enough tbh, we can complement it by mentioning that sending alerts to an external Alertmanager cluster can help with these issues.

We can link to the [docs for adding an external Alertmanager](https://grafana.com/docs/grafana/latest/alerting/set-up/configure-alertmanager/#add-an-external-alertmanager), details about configuring an Alertmanager cluster can be found in [Prometheus' docs](https://prometheus.io/docs/alerting/latest/alertmanager/#high-availability). Once the Alertmanager cluster is configured, no extra config should be needed on Grafana's side.
