### ISSUE TITLE
Log scale looks weird in v4.4.1

### ISSUE THREAD

**Issue by PhantomPhreak** [grafana/grafana#8872]
Axes with log scale (base 2) looks wierd on my graphs
![logscale](https://user-images.githubusercontent.com/8307692/28255939-6b5cdcde-6ae7-11e7-8d07-badf5eb48c35.png)
I'm using auto Y-min and Y-max there.

Problem was reported in #8244 but still not fixed

**Comment by torkelo** [comment]
strange, unable to replicate it :(
http://play.grafana.org/dashboard/db/logarithmic-scales?orgId=1

Can you do a external snapshot (publish graph snapshot)

**Comment by PhantomPhreak** [comment]
Sure, exported to snapshot.raintank.io, please take a look. Actually, it looks weird too.
https://snapshot.raintank.io/dashboard/snapshot/vPVIs7o3VnihrJHvKBhiSyCjB6eDisEw

**Comment by torkelo** [comment]
@daniellee the logscale Y-axis trouble continues, at least we have the snapshot to replicate this strange issue

**Comment by daniellee** [comment]
@PhantomPhreak cannot replicate locally either - it looks fine no matter how small or large values I have. Can you provide a screenshot of the axes tab of the single panel in the single panel snapshot. Thanks.

@torkelo the snapshot server seems to be 4.3.0. Can we upgrade it and see if this problem persists.

**Comment by PhantomPhreak** [comment]
@daniellee sure, here it is
![weird_logscale2_axes_tab](https://user-images.githubusercontent.com/8307692/28401944-58bca75a-6d47-11e7-9a57-c365c5672e8e.png)
In addition, screenshot of the same ussie with logscale base32
![weird_logscale32_axes_tab](https://user-images.githubusercontent.com/8307692/28401969-74a02d66-6d47-11e7-83b4-9f5251bc9625.png)

I can easily reproduce this behavior using collectd's statsd plugin with timers module, by sending a few events with values in range 1-32000ms.

I'm using graphite v0.9.15 as datasource for grafana if it's important.

Thank you!

**Comment by daniellee** [comment]
I just upgraded the snapshot server to 4.4.1 and the two snapshots look fine now compared to when the snapshot server was on 4.3.0. Or do you mean the number of decimal places on the y-axis?

![image](https://user-images.githubusercontent.com/434655/28586028-a6c54374-7172-11e7-90ff-c9b65ddbb866.png)

**Comment by torkelo** [comment]
I think the number of decimals is the main issue yes. Looks like scaledDecimals is out of whack

**Comment by daniellee** [comment]
As a workaround I think setting y-min to 0 should help. Fix coming up for very small min values.

**Comment by PhantomPhreak** [comment]
@daniellee Thank you, now the snapshot looks same with my panel.
But yes, the main issue is a number decimals, it's soo long, wasting space on the panel and looks bad.

I tried to set y-min to 0, it works, but some lines (with smaller values) goes under the x-axis, hiding there. So, i decided to keep it as is.

**Comment by daniellee** [comment]
@PhantomPhreak the problem is figuring out the correct number of decimal places when you have very small values and large values. It does look strange when you are using seconds as the unit but if you change the unit to short then your smallest values would have 10 decimal places. At the moment, all the ticks on the y-axis have the same amount of decimal places. This is what it looks like with Unit short:

![image](https://user-images.githubusercontent.com/434655/28613467-b82d91e0-71f2-11e7-9ba2-a2b74df7fadc.png)


Currently, the approach is to take the number of decimal places of the smallest value. An alternative approach is to use the default algorithm for calculating decimal places which will have less decimal places as the values grow. It would look like this with several ticks having the value 0:

![image](https://user-images.githubusercontent.com/434655/28613357-7b514410-71f2-11e7-82f0-ea8a528de50e.png)


@torkelo what do you think? The second approach works much better with a unit like seconds but looks strange when using a unit like short. Is there a third approach that is better?

**Comment by torkelo** [comment]
But in the screenshots in the original issue comment the y axis has no decimals for the lowest values, but many for the highest.

**Comment by PhantomPhreak** [comment]
daniellee@
> It does look strange when you are using seconds as the unit
Yes, but unit "seconds" making values short (converting it to ms, ns, us). So, at my point of view unit "seconds" doint the same as "short" - shorting the values on the axis making it easy-readable.

> if you change the unit to short then your smallest values would have 10 decimal places.
But why there is 10 decimal places? 

What about adding the "Decimals" parameter for Y-axes as it was done for the legend? 
For examle with 3 decimals "0.12512" will look like "0.125", and it's better than "0".
Actually, i miss these feature much, because i can't limit the amount of decimal values on the Y-axes. It will be useful with "short" and "none" units.

torkelo@
> But in the screenshots in the original issue comment the y axis has no decimals for the lowest values, but many for the highest.
Yes, you're right.

**Comment by daniellee** [comment]
At the moment, we set the number of decimals to be the number of decimals that the min value has. This obviously doesn't work very well when mixing small and large numbers.

As a solution, going to go with adding a Decimals field - feature request here: #8187 and using the auto decimals as default (screenshot number two above). 

> @torkelo

>But in the screenshots in the original issue comment the y axis has no decimals for the lowest values, but many for the highest.
Yes, you're right.

I talked to Torkel about this. It is due to choosing seconds rather than milliseconds as the unit. Not a bug.
