### ISSUE TITLE
Plugin Management Pages: Forced login does not work when anonymous access is enabled

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#88837]
### What happened?

When anonymous access is enabled:

```
[auth.anonymous]
enabled = 1
org_role = Admin
```

any of the pages behind `CanAdminPlugins` [middleware](https://github.com/grafana/grafana/blob/main/pkg/middleware/auth.go#L94) ignore the `?forcedLogin=1` flag and do not redirect to the login page and the user stays on the same page.

### What did you expect to happen?

Being redirected to the login page as it is the case on other pages

### Did this work before?

Yeah probably before https://github.com/grafana/grafana/pull/76321

### How do we reproduce it?

1. Do not login / or if logged in -> logout.

2. Enable anonymous access:
```
[auth.anonymous]
enabled = 1
org_role = Admin
```

3. Visit your instance plugin management pages - for example this one `YOUR-INSTANCE/plugins/grafana-azure-data-explorer-datasource` and click on the Login link at the top.

<img width="1917" alt="SCR-20240606-mlws" src="https://github.com/grafana/grafana/assets/580672/f0874746-a567-4839-a3e8-486c4d3f7728">

### Environment (with versions)?

Grafana: latest
OS:
Browser:

### Grafana platform?

Other

**Comment by s4kh** [comment]
In order to redirect to login with `forceLogin=true` param endpoint must be behind `authorize` middleware.
```r.Get("/datasources/correlations", authorize(correlations.ConfigurationPageAccess), hs.Index)```

`authorize` is created through below function: https://github.com/grafana/grafana/blob/main/pkg/api/api.go#L65.

[middleware.go](https://github.com/grafana/grafana/blob/main/pkg/services/accesscontrol/middleware.go#L29)
<pre>
func Middleware(ac AccessControl) func(Evaluator) web.Handler {
	return func(evaluator Evaluator) web.Handler {
		return func(c *contextmodel.ReqContext) {
			ctx, span := tracer.Start(c.Req.Context(), "accesscontrol.Middleware")
			defer span.End()
			c.Req = c.Req.WithContext(ctx)

			if c.AllowAnonymous {
				forceLogin, _ := strconv.ParseBool(c.Req.URL.Query().Get("forceLogin")) // ignoring error, assuming false for non-true values is ok.
				orgID, err := strconv.ParseInt(c.Req.URL.Query().Get("orgId"), 10, 64)
				if err == nil && orgID > 0 && orgID != c.SignedInUser.GetOrgID() {
					forceLogin = true
				}

				if !c.IsSignedIn && forceLogin {
<b>					unauthorized(c) -- this is where redirect happens</b>
					return
				}
			}

			if c.LookupTokenErr != nil {
				var revokedErr *usertoken.TokenRevokedError
				if errors.As(c.LookupTokenErr, &revokedErr) {
					tokenRevoked(c, revokedErr)
					return
				}

				unauthorized(c)
				return
			}

			authorize(c, ac, c.SignedInUser, evaluator)
		}
	}
}
</pre>
I don't think it was working before https://github.com/grafana/grafana/pull/76321. A possible solution would be to incorporate `forceLogin && !c.IsSignedIn` inside the `CanAdminPlugin` middleware(code duplication). Or maybe call the `authorize` middleware inside `CanAdminPlugin`.
cc @tolzhabayev @xnyo
