### ISSUE TITLE
[Feature request] Option to disable dashboard history

### ISSUE THREAD

**Issue by jochenehret** [grafana/grafana#8887]
Hi all,

we have just updated to Grafana 4.4. Some of our dashboards are automatically generated and frequently updated. Due to the new dashboard history feature, our database size has suddenly increased significantly. Can you please add an option to disable dashboard versioning globally?

Thanks and Best Regards,

  Jochen.

**Comment by carlf** [comment]
We have some processes that generate dashboards and it is causing our database size to grow out of control. Would love to have a way to disable this as we already have a process for versioning dashboards that is working well.

**Comment by bergquist** [comment]
We added support for deleting old dashboard versions. By default, Grafana will only keep 20 dashboard versions but you can set this to 1 to keep pruning dashboard versions in the background. 

I understand that this is not really what you're asking for but I'm not sure we need to introduce yet another option since this will have the same effect. Is this good enough for your you?

**Comment by carlf** [comment]
This works perfectly well for our use case.

**Comment by jochenehret** [comment]
Sounds fine for us!

**Comment by bergquist** [comment]
Great!

**Comment by charlemagnelasse** [comment]
Please reopen. The problem is still not fixed in 5.1.0. My history is again 5GB (without history the size of the whole database is 0.0009GB)

**Comment by bergquist** [comment]
did you set
http://docs.grafana.org/installation/configuration/#versions-to-keep-introduced-in-v5-0
to `1`?

**Comment by charlemagnelasse** [comment]
$ tail /etc/grafana/grafana.ini
    ;secret_key =
    
    [external_image_storage.webdav]
    ;url =
    ;username =
    ;password =
    ;
    
    [dashboards]
    versions_to_keep=1


But even for the default values (20), the 4 GB are a lot to high. 0.9MB * 21 is by far not 5GB.

**Comment by charlemagnelasse** [comment]
As said earlier, I see that there are hundreds/thousands of history entries per dashboard. Even when I have  recently deleted it manually using 

    echo 'delete from dashboard_version;vacuum;'|sqlite3 /var/lib/grafana/grafana.db

I run this now via cron to prevent that it goes over 10 gb. But sometimes, it still gets so large and I have manually download it from the server, delete it on a different machine (with more HDD space) and then upload the 900 KB large file back to the server.


Btw. I have now upgraded to 5.1.3 and it has the same problem.

**Comment by zasca** [comment]
Could you set `filters = cleanup:debug` for `[log]` in config.ini and restart grafana-server?
After that you can see (every 10 minutes) in the log:
```
t=2018-05-22T09:33:54+0300 lvl=dbug msg="Deleted old/expired dashboard versions" logger=cleanup rows affected=0
```
When cleanup service work as expect you should see a nonzero number of affected rows.

**Comment by charlemagnelasse** [comment]
The startup now showed following output:

    t=2018-05-22T09:01:12+0200 lvl=info msg="Starting Grafana" logger=server version=5.1.3 commit=087143285 compiled=2018-05-16T17:39:55+0200
    t=2018-05-22T09:01:12+0200 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
    t=2018-05-22T09:01:12+0200 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
    t=2018-05-22T09:01:12+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
    t=2018-05-22T09:01:12+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
    t=2018-05-22T09:01:12+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
    t=2018-05-22T09:01:12+0200 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
    t=2018-05-22T09:01:12+0200 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
    t=2018-05-22T09:01:12+0200 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
    t=2018-05-22T09:01:12+0200 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
    t=2018-05-22T09:01:12+0200 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
    t=2018-05-22T09:01:12+0200 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
    t=2018-05-22T09:01:12+0200 lvl=info msg="App mode production" logger=settings
    t=2018-05-22T09:01:12+0200 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=2695
    t=2018-05-22T09:01:12+0200 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
    t=2018-05-22T09:01:12+0200 lvl=info msg="Starting DB migration" logger=migrator
    t=2018-05-22T09:01:12+0200 lvl=info msg="Starting plugin search" logger=plugins
    t=2018-05-22T09:01:12+0200 lvl=info msg="Initializing CleanUpService" logger=cleanup
    t=2018-05-22T09:01:12+0200 lvl=dbug msg="Found old rendered image to delete" logger=cleanup deleted=0 keept=110
    t=2018-05-22T09:01:12+0200 lvl=info msg="Initializing Alerting" logger=alerting.engine
    t=2018-05-22T09:01:12+0200 lvl=info msg="Initializing Stream Manager"
    t=2018-05-22T09:01:12+0200 lvl=info msg="Initializing HTTP Server" logger=http.server address=127.0.0.1:3000 protocol=http subUrl= socket=

I will now wait a while (10-15 minutes) and post the new output

**Comment by charlemagnelasse** [comment]
I just got following messages:

    t=2018-05-22T09:11:12+0200 lvl=dbug msg="Found old rendered image to delete" logger=cleanup deleted=0 keept=110
    t=2018-05-22T09:11:12+0200 lvl=dbug msg="Deleted expired snapshots" logger=cleanup rows affected=0
    t=2018-05-22T09:11:12+0200 lvl=dbug msg="Deleted old/expired dashboard versions" logger=cleanup rows affected=100
    t=2018-05-22T09:11:12+0200 lvl=dbug msg="Deleted expired login attempts" logger=cleanup rows affected=0

But the problem is that I still see hundreds/thousands of entries in the version entry for each dashboard (there are a couple of dozen dashboards).

**Comment by charlemagnelasse** [comment]
This is what I now got (and the status which was just requested a couple of seconds after the log entries were shown):

    t=2018-05-22T09:31:12+0200 lvl=dbug msg="Found old rendered image to delete" logger=cleanup deleted=0 keept=110
    t=2018-05-22T09:31:12+0200 lvl=dbug msg="Deleted expired snapshots" logger=cleanup rows affected=0
    t=2018-05-22T09:31:13+0200 lvl=dbug msg="Deleted old/expired dashboard versions" logger=cleanup rows affected=100
    t=2018-05-22T09:31:13+0200 lvl=dbug msg="Deleted expired login attempts" logger=cleanup rows affected=0


    22585
    23|20
    27|20
    28|20
    29|20
    30|20
    31|20
    32|20
    33|52
    34|343
    35|604
    36|604
    37|613
    38|613
    39|613
    40|613
    41|613
    42|613
    43|613
    44|613
    45|613
    46|613
    47|613
    48|613
    49|613
    50|613
    51|613
    52|613
    53|613
    54|613
    55|613
    56|613
    57|613
    58|613
    59|613
    60|613
    61|613
    62|613
    63|613
    64|613
    65|613
    66|613
    67|613
    68|613
    69|613
    70|613

----

The bug in the code is that you only allow MAX_VERSIONS_TO_DELETE (100). This is a lot less than what grafana adds in each cleanup period. https://github.com/grafana/grafana/blob/f0d77804daf79d251a813c92cb6954e93600923b/pkg/services/sqlstore/dashboard_version.go#L70


Btw. I've played around with the versions_to_keep to check what infuence it has. This is the reason why it now only deletes down to 20 entries for the first couple of dashboard_ids. Will switch later back (but this will not help because of the bug which was explained earlier)

    [dashboards]
    versions_to_keep=1

**Comment by RuralHunter** [comment]
I have a related question:
```
sqlite3 /var/lib/grafana/grafana.db 'select count(*) from dashboard_version;'
393
```
The size of grafana.db  is now around 800M. Is that normal?

**Comment by kmurudi** [comment]
Mine goes up to 80 GB in a couple of weeks and I was having a hard time seeing why the grafana.db expands so soon. Good thread but the documentation has very less info about grafana.db file and troubleshooting.

**Comment by jowparks** [comment]
+1 for this still being an issue. I am running the Kubernetes from grafana and it seems to version the kubernetes dashboard versions I am guessing everytime something changes about the cluster because I currently have 70,000 versions of each kubernetes dashboard. Accounting for 10GB db. Wish there was at least a way to more simply delete versions as a workaround until we can fix the root cause of the garbage collection not actually keeping up with its job.

**Comment by torkelo** [comment]
That is strange, must be something with dashboard json files that cause this, maybe two files with same uid?

**Comment by jowparks** [comment]
@torkelo You are right I think, I figured out that when I did
`helm delete prometheus-operator --purge` it somehow didn't clean up the old ConfigMaps for some Kubernetes dashboards that were replaced with `kubernetes-mixin` dashboards. The two versions of the kubernetes dashboards seemed to be competing for the same namespace (or uid possibly) and were versioning themselves every 10 seconds.
 I had to manually remove the old config maps, delete the database, restart grafana, and all is well now.

**Comment by skob** [comment]
reopen plz

```
du -sh /var/lib/mysql/grafana/dashboard_version.ibd
195G	/var/lib/mysql/grafana/dashboard_version.ibd```
it's not ok for me :-)

**Comment by torkelo** [comment]
Are you using provisioning?

**Comment by jowparks** [comment]
@torkelo is there a reason that grafana can’t disallow provisioning on the same id? Or just override?

**Comment by wision** [comment]
May I ask, what is the reason behind having `MAX_VERSIONS_TO_DELETE` hard-coded to 100?

We're having ~600 automatically generated dashboards every 5 minutes, which means that old versions are never cleaned up and the database increases its size for about 1GB per day. Looking at https://github.com/grafana/grafana/blob/81c42fc912cba9c3e553d5ac433147a04638a045/pkg/services/sqlstore/dashboard_version.go#L83 shows that grafana itself will try to get all the ids which should be deleted, but that's no ideal, if you have millions of history rows (because they are not getting cleaned up). Grafana will start transfering hundreds of megabytes every 10 minutes, eating up cpu/memory (from 100MB to 1GB in our case) and that also burdens the database server.

We had to duplicate the code and have separate cron, just to delete rows from `dashboard_version`.

**Comment by torkelo** [comment]
how are 600 versions created every 5min? Agree that that setting should be a lot higher, it is there to not overload the DB on startup when we introduced the cleanup.

**Comment by wision** [comment]
That's our internal script, which gathers information about current infrastructure (hundreds of APIs * multiple environments) and for each of those we have separate dashboard, which is updated every 5 minutes. Most of the time there are no changes, but the version is created anyway.
