### ISSUE TITLE
Scenes: Dashboard toolbar doesn't hide in kiosk mode

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#88906]
**Problem**
When enabling `kiosk=true` for a dashboard, the toolbar containing the variables, time range, links, etc doesn't hide. In the old architecture, it does. 

**Expected behavior**
Hide the toolbar when kiosk mode is enabled

**Screenshots**
|Scenes disabled|Scenes enabled|
|-|-|
<img width="1728" alt="Captura de pantalla 2024-06-07 a las 13 01 02" src="https://github.com/grafana/grafana/assets/5699976/ff2e38fb-b04c-45d6-be49-661cf9711e92">|<img width="1728" alt="Captura de pantalla 2024-06-07 a las 13 00 41" src="https://github.com/grafana/grafana/assets/5699976/51e2c084-9945-4ee7-9196-010e1c31ced6">

**Steps to reproduce**
1. Open any dashboard
2. Add to the URL `&kiosk=true`. You see the controls still available
3. Add to the URL `&scenes=false`. You will see the controls are hidden because we disabled Scenes.

**Comment by diegommm** [comment]
Hi! Greetings from the Release Guild. This is a friendly reminder that the Steady `11.1.x` Release branch has already been cut. This means that PRs merged to `main` from now on will not go into any `11.1.x` Release unless they use the [backport v11.1.x](https://github.com/grafana/grafana/labels/backport%20v11.1.x) label.

I'm mentioning that since this issue is marked with [Milestone 11.1.x](https://github.com/grafana/grafana/milestone/512). Please, consider if moving this issue to [Milestone 11.2.x](https://github.com/grafana/grafana/milestone/529) makes sense for you.

Thank you!
