### ISSUE TITLE
Alerting: Rule group deleted when renaming with only case changes on MySQL

### ISSUE THREAD

**Issue by JacobsonMT** [grafana/grafana#88990]
### What happened?

When renaming an Grafana-Managed alert rule group's name and only changing the case of letters, the entire rule group gets deleted fit he backing database is MySQL-like.

### What did you expect to happen

The rules in the group should remain under the new name.

### How do we reproduce it?

- Create one or more GMA rules in a group called "Test Group".
- Edit the group and rename it to "TEST Group".
- The group will be deleted.

### Cause

Rule groups are renamed in the frontend by:
- Sending a request to create the new rule group (with all rules) under the new name.
- Sending a delete request to delete the old rule group.

Currently, default MySQL collation on the `alert_rule` table means listing rules via `rule_group='TEST Group'` will return all rules from both "TEST Group" and "Test Group". This results in a case-insensitive delete.

Note: The FE doesn't currently use the existing patch request endpoint to modify the group name as the endpoint doesn't exist for all supported rulers.

### Some possible solutions:

1. **Modify `alert_rule` table collation to be case-sensitive**. This approach has pros and cons.
    pro.  Will possibly prevent similar the collation difference causing similar issues in the future.
    con: Fairly heavy-handed, requires reindexing, and the repercussions might be difficult to determine beforehand without significant testing.
2. **Mitigate the collation difference in code**. This approach will require require reproducing the case-sensitive collation via filtering (or similar). Since PSQL and SQLite are already case-sensitive, this will likely not require any MySQL-specific changes. The intent here should not be to fully reproduce the collation in code (this is a losing battle) but to mitigate the main issue of case-sensitivity.
3. **Don't call DELETE from FE for GMA ruler only**. Unlike other rulers, the initial POST request for creating the new group in GMA doesn't actually create two groups. Since rules retain their UIDs, we detect the rename and just change the group. This approach requires special logic in FE for GMA compared to other supported rulers and should be out last resort IMO.

**Comment by yuri-tceretian** [comment]
I propose we use post-processing in code as:
- more db agnostic solution
- much safer to backport

We considering changing the collation for the column from the current `utf8mb4_unicode_ci` to either `utf8mb4_bin` or `utf8mb4_0900_bin`. However, there are downsides in either of those:
- `utf`8mb4_bin` is supported since MySQL 5.7 but it has pad attribute "PAD SPACE" and therefore, it ignores trailing spaces in comparison, e.g string `'a '` is considered the same as `'a'`. 
- `utf8mb4_0900_bin` is alternative to the former that does correctly compares trailing spaces but it is not available in 5.7. 

Using `BINARY` in WHERE clause also has downsides because, from what I understand, it affects all expressions in the clause and therefore it will conduct UID comparison other way than in other cases.

**Comment by yuri-tceretian** [comment]
I think the fix merged in https://github.com/grafana/grafana/pull/88992 should work for the time being. Closing
