### ISSUE TITLE
[Feature request] down sampling support in Flot

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#8914]
I tried to improve flot drawing chart performance, and finally notice that, the performance is depend on number of datapoints passed to `stroke()` API.

The downsample plugin can reduce the datapoints, it can improve performance.
https://github.com/flot/flot/issues/1544#issuecomment-287604703
https://github.com/sveinn-steinarsson/flot-downsample/
http://flot.base.is/

**Comment by torkelo** [comment]
this is why Graphite has maxDataPoints automatically set to width of the graph so there are never more points than pixels. Similarly the most other data sources have a interval/step that can be automatically managed so that the number of points is never to much. 

But users who do not know what they are doing can issue queries that return many thousand data points which will usually hang the browser. Not sure how much browser side downsample will improve things as it can still be slow as hell / hang browser if there are a lot of data points returned to the browser.

**Comment by torkelo** [comment]
> The advantage of browser side down sampling is, user can control resolution without extra query.

Extra query? 

Think downsampling should be done by the backend, doing it in the frontend is always going to be multiple order of magnitude slower. 


Regarding mackarel
The simplified graph seems to just combine series?

**Comment by mtanda** [comment]
> Extra query?

Query to the TSDB.
If TSDB responds enough high-resolution data, user can change the displayed graph resolution without TSDB query.
The query is expensive, I want to reduce the query count.

> Think downsampling should be done by the backend, doing it in the frontend is always going to be multiple order of magnitude slower.

Compared to `stroke()`, the downsampling cost is small.
Actually, downsampling can improve rendering performance.
I check it by Benchmark.js.

But, I also understand your position, you want to keep Grafana simple.

> The simplified graph seems to just combine series?

Yes, it just combine series, loose detail.
But, it is useful, because user can't predict how much data series returns from TSDB.

**Comment by aocenas** [comment]
Considering how old is this issue and that we are moving to use different plotting library I think this can be closed.
