### ISSUE TITLE
Add limits for Data Frame size

### ISSUE THREAD

**Issue by robbierolin** [grafana/grafana#89257]
**Why is this needed**:
Grafana should have a way to limit the blast radius of individual queries. Without this, it is possible for a single query to be executed that consumes all the memory on a Grafana instance and crashes Grafana for all users. I see there are some attempts at this with the `response_limit` and `row_limit` settings, however these do not apply to all plugins and do not directly address internal memory usage in Grafana (e.g. [this issue](https://github.com/grafana/grafana/issues/72662) where memory usage was affected by query size, not response size). 

**What would you like to be added**:
An ini setting on maximum data frame size. The data frame should only grow if it does not or would not exceed that limit. If the response size is too large, a suitable error message should be relayed back to the browser. This feels like it should be possible with the streaming parser for Prometheus queries, but hopefully it could be generalized for all plugins.

**Who is this feature for?**
All Grafana administrators who want to keep Grafana available for all their users.

**Comment by andresmgot** [comment]
Hello,

Indeed, using `response_limit` (for HTTP data sources) and `row_limit` (for SQL data sources) is the recommended way to limit sizes. All plugins have access to the [response_limit_middleware](https://github.com/grafana/grafana-plugin-sdk-go/blame/main/backend/httpclient/response_limit_middleware.go) for the HTTP case (as Prometheus does) but we cannot add it by default since that can cause breaking changes for plugins that don't expect it. Plugin owners should own their limit handling.

At the moment, there are no plans to add this capability at the data frame level so let me close this issue. If you still think there is an issue only fixable at this level, feel free to reopen it.
