### ISSUE TITLE
AWS Data Lifecycle Manager not autopopulating policy ids

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana#89303]
The user wants to filter the `AWS/DataLifecycleManager` `SnapshotsCreateCompleted` metric by DLMPolicyId, however it does not appear in the dropdown for the query builder when they try this.

The user ran the command `aws cloudwatch list-metrics --namespace "AWS/DataLifecycleManager" --metric-name "SnapshotsCreateCompleted" --query "Metrics[?Dimensions[?Name=='DLMPolicyId']]" --output json` and it came back empty [].

The user also ran
`aws cloudwatch list-metrics --namespace "AWS/EBS" --metric-name "SnapshotsCreateCompleted" --query "Metrics[?Dimensions[?Name=='DLMPolicyId']]" --output json` and received the desired policy ids.

This sounds like a bug in the aws-sdk that they should fix (I would expect the first query to return the valid dimension values for that namespace and metric instead of having to check a separate namespace), but we could work around it by checking for this specific namespace and handling it differently. We should check with the AWS team and see whether/when they can fix it before doing the workaround.

made to track https://github.com/grafana/support-escalations/issues/11038

**Comment by robertrv** [comment]
Hello, 

can you verify that the namespace has any metric? I mean when you go to the AWS CloudWatch Console instead of Grafana.

Looking at the [EBS documentation for those metrics](https://docs.aws.amazon.com/en_en/ebs/latest/userguide/monitor-dlm-cw-metrics.html) it seems to indicate that the namespace is actually `AWS/EBS` so it's expected for you to not see anything under `AWS/DataLifecycleManager`. 

Cheers, robert

**Comment by iwysiu** [comment]
Hi Robert! Thanks for checking, I do see those listed under "AWS/EBS" in the cli. We'll handle updating them
