### ISSUE TITLE
Grafana UI : Fails to load on niche Android apps (and Amazon Silk Browser) that worked for many years before.

### ISSUE THREAD

**Issue by ingel81** [grafana/grafana#89440]
### What happened?

Starting from Grafana version 10.4.4 and including version 11.0.0, the Grafana UI fails to load and displays the following error message:

```
If you’re seeing this Grafana has failed to load its application files

This could be caused by your reverse proxy settings.

If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath. If not using a reverse proxy make sure to set serve_from_sub_path to true.

IF you have a local dev build make sure you build frontend using: yarn start, yarn start:hot, or yarn build

Sometimes restarting grafana-serve can help

Check if you are using a non-supported browser. For more information, refer to the list of supported browsers.
```

This issue has been observed on two niche Android apps, Wallpanel and Fully Kiosk Browser, which run web pages in fullscreen mode on tablets and offer additional features compared to a normal browser. These apps are popular in the home automation community. The problem also occurs with the Amazon Silk Browser.

These apps likely use an Android WebView internally. The issue seems to be specific to the browser environment provided by these apps and the Amazon Silk Browser, as the same setup works correctly on standard browsers.

### What did you expect to happen?

Grafana UI should load correctly without displaying any error messages.

### Did this work before?

Yes. For many years.

### How do we reproduce it?

1. Install Grafana version 10.4.4 or later.
2. Access the Grafana instance using Wallpanel, Fully Kiosk Browser, or Amazon Silk Browser on an Amazon FireHD 10" (11th gen) tablet.
3. Observe that the Grafana UI fails to load and displays the error message.

### Environment (with versions)?

Environment:
Device: Amazon FireHD 10" (11th gen)
Apps: Wallpanel, Fully Kiosk Browser, Amazon Silk Browser
OS: Amazon Android (FireOs ?)
Grafana versions: 10.4.4 to 11.0.0

### Grafana platform?

Docker

**Comment by eledobleefe** [comment]
Hi @ingel81,
We only [support the latest versions](https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-web-browsers) of the major browsers. In order to keep improving Grafana, we need to take advantage of newer and better APIs and it's not scalable for us to continue to maintain compatibility with old browsers.
Our recommendation would be to update the versions of the browsers either used by your tablet or by those Apps.
If, after making this, you still reproduce this issue on the latest versions, please raise an issue with all the details you can so we can investigate it.
Thanks for your understanding.
