### ISSUE TITLE
[Bug] Repeating Singlestat items dont respect Span attribute

### ISSUE THREAD

**Issue by MartB** [grafana/grafana#8973]
Please include this information:
- Using the latest Master branch ()
- Influxdb
- Archlinux ARM
- Tried to add a repeating singlestat item using a template variable.
- The span works and the elements stay small.
- The span got reset to 6 on every page reload.

**Comment by torkelo** [comment]
this works as intended, you set panel repeat and grafana will fill the row with panels or adjust the span so that the panels take up as much space as possible on the row (so if only 1 value it will be span 12, if 2, span 6). There is an option to set how small the panels can be (minSpan), but not max. 

See this feature request
https://github.com/grafana/grafana/issues/2950
