### ISSUE TITLE
Grafana 11.1.0 the new tooltip got broken

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#89834]
### What happened?

The new tooltip add a srcalling option, moving to grafana 11.1.0 got it broken.
This is how it looks in grafana 11.1.0:
![Screenshot_20240627_143208](https://github.com/grafana/grafana/assets/2118079/8171d0bd-102d-4190-8560-60a67160e4a6)

### What did you expect to happen?

This is how it looks like with grafana 11.0.0
![Screenshot_20240627_143026](https://github.com/grafana/grafana/assets/2118079/2e526ae0-51e4-4c5b-a5c2-9c92a8ea54d2)

### Did this work before?

yes

### How do we reproduce it?

1. create a panel with lots of graphs in them and hover over the graph

### Is the bug inside a dashboard panel?

yes

### Environment (with versions)?

Grafana: 11.1.0
OS:  docker container
Browser: chrome

### Grafana platform?

Docker

### Datasource(s)?

prometheus

**Comment by leeoniya** [comment]
we removed the default maxHeight from the tooltip because it's difficult to figure out a sensible default that works for everyone, since each dashboard layout and panel sizes are different. you can set the tooltip maxHeight in the panel settings/

<img width="540" alt="image" src="https://github.com/grafana/grafana/assets/43234/de0dc139-01de-4711-976b-270c9ce17e23">
