### ISSUE TITLE
[Bug] graph spikes appear when browser window size changes

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#8993]
- What Grafana version are you using? 4
- What datasource are you using? influxdb 1.2.1
- What OS are you running grafana on? CentOS 6.6
- What did you do? Change the size of the browser window
- What was the expected result? Compressed graph
- What happened instead? Spikes appeared in the graph

The the browser at full screen size, the graph of data appears a bit bumpy, which is what I'd expect.

![screen shot 2017-08-06 at 6 05 40 pm](https://user-images.githubusercontent.com/24280758/29001680-b20c631e-7ad4-11e7-9c12-e051f823d1df.png)

When I resize the browser window and then reapply the time range, the graph is redrawn with huge spikes.

![screen shot 2017-08-06 at 6 05 03 pm](https://user-images.githubusercontent.com/24280758/29001689-ddba8a0e-7ad4-11e7-8e42-56adf647a7d1.png)

The time range does not change. The source does not change. Only the browser window size changes.

Browser: Google Chrome, Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by torkelo** [comment]
Unable to replicate, 

What happens if you refresh (icon navbar, top right)? This causes query to be executed again. Does the graph spikes stay? 

What does your query look like? What is your group by time option? May be a derivative issue with InfluxDB and the group by time interval (when you change graph width the grafana built  $__interval  variable will be changed so to reflect the new graph width). 

When you see the spikes , hit refresh and investigate what InfluxDB is returning.
https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

**Comment by yellowpattern** [comment]
The query is similar to this:

SELECT non_negative_derivative(sum("value"), 1m) FROM "series" WHERE "host" =~ /^$host$/ AND "instance" = 'X' AND "type" = Y' AND "type_instance" =~ /^$Z$/ AND $timeFilter GROUP BY time($interval), "type_instance"

**Comment by yellowpattern** [comment]
OIC! Yes. Problem is with data returned from influxdb!

**Comment by yellowpattern** [comment]
https://github.com/influxdata/influxdb/issues/8666
