### ISSUE TITLE
Iphone 11 pro unable to reach grafana

### ISSUE THREAD

**Issue by DonatoD** [grafana/grafana#90157]
### What happened?

I have upgraded from grafana 9.1.6 to grafana 11.0.0 and from iphone 11pro I'm not able to reach the site anymore. I always get this page.
![01 (1)](https://github.com/grafana/grafana/assets/51508670/143c4442-075d-491d-83ab-5c51d242d051)
Cache has been cleaned. I even tryed to update to the last grafana available version, but nothing.
I use ngnix, and docker installaion for grafana (Alpine base image). From others Iphone there is no problem, even with othesr android mobiles or PC. So it doesn't seem something related to the site. I have even tried with firefox (a pretty new installation since I didn't have it installed) but nothing

### What did you expect to happen?

use my grafana dashboard as usual

### Did this work before?

yes

### How do we reproduce it?

try to reach dashboard using iphone 11 pro

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 11.0.0 and 11.1.0
OS: iphone
Browser: google chrome / firefox

### Grafana platform?

Docker

**Comment by alexadamski** [comment]
Same issue with iPad Air 2 IOS 15.8.2

**Comment by DonatoD** [comment]
@alexadamski have you been able to fix it?

**Comment by link-wecom** [comment]
+1

**Comment by alexadamski** [comment]
> @alexadamski have you been able to fix it?

Sadly not. Open for any ideas

**Comment by snack32** [comment]
Same problem here (iphone 11 pro).

**Comment by ashharrison90** [comment]
hi everyone! 👋 

for desktop, [we support the latest version of all major browsers](https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-web-browsers). for phone OSs, there's no official support statement, but i think it's safe to say we'll support the latest iOS/android version. in order to keep improving grafana, we need to take advantage of newer and better web APIs. unfortunately it's not scalable for us to continue to maintain compatibility with every old OS + browser version combo.

couple of people here have mentioned iphone 11 pro. running a simulator on my mac:
- works on iOS 16.4 ✅ 
- does not work on iOS 15.5 ❌ 

my number 1 recommendation would be to ensure you're on the latest OS and browser versions for your particular platform.
