### ISSUE TITLE
[Feature request] Overwrite id of notification_channels and version of dashboards

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#9031]
- What Grafana version are you using?
  5.0.0-pre1 dd40394

- What datasource are you using?
  elasticsearch/graphite

- What OS are you running grafana on?
  RHEL 7

- What did you do?
  Import dashboards and notification channels via api
  In my team we save dashboards and notification channels and datasources like they are via "view json" or my.grafana.server/api/alert-notifications in a git repo. From this repo we import dashboard/datasources/notification_channels via http-api. Notification channels get on each creation a new id, this is in our case very inappropriate because the channel ist linked by the channel id and not - like with datasources - by the name. 

The Problem here is: we have 2 grafana instances: one for live and one for testing. We generate dashboards/channels/source on git-changes and do not copy db from one server to an other..

- What was the expected result?
  In my team we save dashboards and notification channels like they are via "view json" or my.grafana.server/api/alert-notifications in a git repo. 
  I am expeting, that all field, even "id" of dashboards or "notification channels" or "version" of dashboards will be taken from slug.

- What happened instead?
  Settings of fields "version" or "id" are ignored.
 
It would be great if dashboards will link the notification name instead of id - or - if overwriting of id would be possible. I would prefer linking it the name like in datasources.
It would be also wonderful if the field "version" in dashboards might be overwritten

**Comment by torkelo** [comment]
why do you want to overwrite dashboard version? it's an internal field used to stop users overwriting each others changes (optimistic concurrency). 

using an id has big advantages over using the name. If you change the name of the notification we would have to loop through and update json model of possibly hundreds alert rules. The same problem is with data source names right now, so that if you change a name of a datasource you will break lots of dashboards that refer to that data source using that name.

**Comment by Luke1887** [comment]
Managing dashboards, sources and channels via local git is very comfortable for us. We have dozens of user created dashboards wich are managed by the users in a local git repo after beeing tested and hundreds of dynamic dashboards (several for each server/service) and some dozen datasources (elastic search indexes).
In fact, we have some naming-guidelines, but the advantage is, that using names instead of id's, one can setup a new grafana-test-server, import all the stuff (dashes, sources, channels) from json without managing dynamic ids.  Datasources for example are already saved via name in all the dashboard and this work very fine. I have setup a grafana-test-vm and from all the json-data, the notification channels do not match the required ones.

An other problem with the dashboard version ist that one:
On each git commit I push all the files via http-api: dashboards, sources, channels. This causes grafana.db (the default local sqltie-db) to grow on each import.

**Comment by randallt** [comment]
Looks like I ran into an issue migrating dashboards from a Grafana 4 server to a new Grafana 5 server. I recreated the notification channels manually. I didn't know this would break the dashboard alerts. When I imported dashboards that use alerts, several of them were completely wrong.

**Comment by PeterBellish** [comment]
@torkelo Hi Torkel, 

We have the same setup as described above. Can you suggest a better way of solving this problem, when you hvae these two instances. You need some way of making sure they are equal between servers/setups.
