### ISSUE TITLE
Tempo Data Source: default "Trace to logs on trace ID" cfg broken with the new  Loki OTel logs format

### ISSUE THREAD

**Issue by cyrille-leclerc** [grafana/grafana#90335]
### What happened?

In the "Data sources / Loki / Trace to Logs", the default LogQL query is broken when activating "filter by traceID".
The actual query looks like
```
{service_name="my-service", service_namespace="my-service-namespace"} |="7f52950c6d44906e97820d5e5f8fd954"
```

### What did you expect to happen?

When the expected query should look like

```
{service_name="my-service", service_namespace="my-service-namespace"} | trace_id="7f52950c6d44906e97820d5e5f8fd954"
```

### Did this work before?

It worked with JSON formatted OTel logs, never with the new OTel logs fromat using labels and metadata introduced in Loki v3.

### How do we reproduce it?

1. Instrument with OTel an application that produces traces and logs
2. send those OTLP traces and logs to the Grafana Cloud OTLP endpoint or to the Loki OTLP endpoint
3. configure the Loki data source / trace to logs activating filter by trace ID
3. try to navigate from traces to logs

<img width="741" alt="image" src="https://github.com/grafana/grafana/assets/459691/839d921a-65ee-41bd-ab4d-c982070d44b1">

<img width="2304" alt="image" src="https://github.com/grafana/grafana/assets/459691/bfeabf1f-eb15-4935-bcd0-22863a2f9a16">

<img width="2325" alt="image" src="https://github.com/grafana/grafana/assets/459691/da58fa94-ffd6-4619-b7ed-cf2c6cf744b2">

<img width="2309" alt="image" src="https://github.com/grafana/grafana/assets/459691/ad727f59-a60a-42d6-8b2b-dca13f40e891">

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

I use Grafana Cloud

**Comment by aco-mreble** [comment]
A workaround is using a custom query, but I havn't found out the variable name for the service name so I had to use RegEx to use all services. Can anyone tell me if and how I can access the service name tag?
`{service_name=~".+"} | trace_id = `${__trace.traceId}`

**Comment by cyrille-leclerc** [comment]
Thanks @aco-mreble, here is a summary of the workaround


# Tempo datasource - trace to logs configuration

To enable the "trace to logs" navigation from Tempo to Loki, navigate to the Grafana Tempo data source configuration screen, in the "Trace to logs" section, 

* Select a logs / Loki data source on which logs to trace is configured for the new Loki format for OTel logs (example [here](https://github.com/grafana/grafana/issues/92699#issuecomment-2367458654))

* Select "use custom query" and specify the query:

    ```
    {${__tags}} | trace_id="${__span.traceId}"
    ```


![Grafana / Tempo datasource / Trace to logs for the Loki format for OTl logs with metadata](https://github.com/user-attachments/assets/f9728223-d6ba-4ce4-a377-77d6452a2014)

**Comment by vlad-diachenko** [comment]
Proposed solution [here](https://github.com/grafana/grafana/issues/90335#issuecomment-2367556026) works only if `trace_id` exists in structured_metadata. It does not cover the cases when the log line is ingested through the regular push endpoint in Loki format. 
In this case, the log line might not have trace_id specified in structured metadata, so Loki returns no results.

There is a query that can cover both cases, when trace_id exists in structured metadata and when trace_id is a part of log line itself:
```
| label_format log_line_contains_trace=`{{ contains "123123" __line__  }}`  | log_line_contains_trace="true" OR trace_id="123123"
```
1. This stage attaches the label that has value `true` only if log line contains needed trace ID (`123123` in this case) 
    ```
    | label_format log_line_contains_trace=`{{ contains "123123" __line__  }}`
    ``` 
2. This stage, matches the lines with needed trace_id in structured metadata or in logline itself. 
    ```
    | log_line_contains_trace="true" OR trace_id="123123"
    ```


Also, if the query needs to include `span_id` as well, it becomes a bit more complex but still possible... 

That said, if Loki can extract `trace_id` and `span_id` for the logs ingested through the regular push endpoint([solution described here](https://github.com/grafana/grafana/issues/92699#issuecomment-2374259684)) and attach them as structured metadata, it would simplify the query because we could always search for the values in structured metadata only.

**Comment by cyrille-leclerc** [comment]
> That said, if Loki can extract trace_id and span_id for the logs ingested through the regular push endpoint(https://github.com/grafana/grafana/issues/92699#issuecomment-2374259684) and attach them as structured metadata, it would simplify the query because we could always search for the values in structured metadata only.

I see a migration challenge. The json/logfmt format for OTel logs through the OTel Collector Loki Exporter has been used for so long that I'm afraid it will take a lot of time & effort for users to migrate all their logs.

I prefer the solution that supports both scenarios even if the query is very complex to understand

**Comment by cyrille-leclerc** [comment]
We are working on a permanent fix to make the builtin "trace to logs" feature wok with both traceId /spanid in the log line and in metadata.

The LogQL query will look like:

```
{${__tags}} | label_format log_line_contains_trace_id=`{{ contains "${__span.traceId}" __line__  }}` 
| log_line_contains_trace_id="true" OR trace_id="${__span.traceId}"
```
