### ISSUE TITLE
Grafana 11.1 uses browser scrollbar instead of grafana scroll bar

### ISSUE THREAD

**Issue by PhilippDehner** [grafana/grafana#90586]
### What happened?

I opened grafana in edge and firefox, and the scrollbar is the respective scroll bar from the browser is used. 

Example, firefox 128:
Not only in plugins, but only as example:
![grafik](https://github.com/user-attachments/assets/bb7ab43c-5bff-4449-a346-2ce48be4cf5e)

### What did you expect to happen?

The grafana scrollbar should be used

### Did this work before?

grafana 9.x

### How do we reproduce it?

1. Open a grafana web page with scrollbar

### Environment (with versions)?

Grafana: 11.1.0
OS: Docker, Windows
Browser: Firefox, Edge

### Grafana platform?

Docker

**Comment by PhilippDehner** [comment]
Same scrollbar used in #89975

**Comment by ashharrison90** [comment]
hi! 👋 

this is intentional. we're gradually phasing out usage of the custom scrollbar. there are a few reasons for this:
- native scrollbars are more accessible (see e.g. https://github.com/grafana/grafana/issues/17725)
- users are more familiar with the scrollbar that's native to their platform + browser combo
- there are better customisation options for native scrollbars now which makes using the custom scrollbar less attractive
  - `scrollbar-color` and `scrollbar-width` are widely supported in chrome and firefox, safari will default to OSX scrollbars which is what the custom scrollbar currently does anyway on OSX

hope that makes sense! 😄

**Comment by MA-MacDonald** [comment]
@ashharrison90 I've noticed the switch to native scrollbars has not played well for things like the bar gauge. 
Do you know if there are plans to address this?

![image](https://github.com/user-attachments/assets/4da44016-9dce-4843-9a48-d7f821dbf374)

**Comment by ashharrison90** [comment]
hi @MA-MacDonald 👋 

looks like that's being tracked in https://github.com/grafana/grafana/issues/89226
