### ISSUE TITLE
Cloudwatch Bug: Issue with Labels in Alerting causes Duplicate Results

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#90669]
A User was using AWS CloudWatch Agent which allows for collecting configurable metrics, logs, and traces: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html

I believe when that is done it is possible to have multiple time series that are about the same instance id. 

When they made a query in the Query Editor the labels generated for that response were all unique. I'm not entirely sure how those labels were generated but they seemed to contain information in the format like "instanceId-t3.small" and things like that. I imagine the labels were auto generated by aws based on the query. The Query in Question was: `CWAgenat, mem_used_percent, average, instanceId = *`

But then when the same query is made with alerts, all of the labels were suddenly reduced to just the dimension name, in this case Instance Id. However in this case InstanceId is not a unique identifier, as you can have multiple time series sets that are referencing the same instance id. And you can't set up an alert if you do not have unique labels. 

I think it would be ideal to fix it so that when transitioning from the query editor to alerting, the labels for cloudwatch metrics stay the same. Or if for some reason that is not possible that we explicitly call out/describe why that is in our documentation and guide users on how to generate their own unique labels as needed with Dynamic Labels. 

~ Grafana 11.1

**Comment by iwysiu** [comment]
I'm going to tentatively say that this was fixed by the fix for https://github.com/grafana/grafana/issues/86426 (it's a little hard to tell exactly what versions the customer was having the issue on since they would get different commits delivered on different dates depending on whether their on steady vs fast vs etc.) since the fix of adding the aws label as a `series` label should have fixed the duplicate label problem. If the user has the issue again, we can reopen it.
