### ISSUE TITLE
Make docked navigation a URL parameter

### ISSUE THREAD

**Issue by laundmo** [grafana/grafana#91040]
**Why is this needed**:

When sharing dashboards with a link, theres no need to show the navigation menu by default in most cases. But it seems that its always docked by default in new browsers.

A related question about how to make this not default here: https://community.grafana.com/t/how-to-disable-grafana-navigation-docked-localstorage-variable-by-default/116791

**What would you like to be added**:

A URL query parameter like ?kiosk= to undock the navigation

**Who is this feature for?**

Anyone sharing links
related to:
- #82973

**Comment by shehenshah14** [comment]
This will be wonderful feature for ourselves too.

**Comment by mark-sch** [comment]
this would very useful

**Comment by ashharrison90** [comment]
hi all! apologies for not seeing this issue til now, it never got correctly triaged to our board.

the current behaviour is that the menu docks by default the very first time you visit an instance if your screen size is big enough (bigger than ~1440px). after that, it will remember your preference via the browser's localStorage. so once you've visited the instance and undocked, it will leave it undocked. 

we added this behaviour to help orient users within the instance.

> When sharing dashboards with a link, theres no need to show the navigation menu by default in most cases.

i'm not sure this is true. if you're following a link, it feels more important to let the user know where they are within the instance 🤔 unless the expectation is that they won't navigate anywhere else after following that link. is that the use case?

i don't think we'd want to make it a url parameter since it's more of a personal preference. we could add a config option to change the default docking behaviour, but we'd need to understand the use case well enough to make sure it's worth adding it.

**Comment by laundmo** [comment]
> unless the expectation is that they won't navigate anywhere else after following that link. is that the use case?

This is exactly the use-case. For example, sharing a public dashboard where navigation isn't expected at all but the user should still see the time selector.

Sorry I didn't respond right away, could this be reopened?

**Comment by ashharrison90** [comment]
hey again @laundmo (and others) 👋 sorry for the slow reply, just back from holidays 😄 

have a follow up question if that's ok: you mentioned public dashboards... are these predominantly anonymous (i.e. not logged in) users you're sharing these dashboard links with?

i'm wondering if there's a middle ground. we think it's important to help orient new users by pinning the navigation menu open by default on first visit. but i don't think we feel so strongly about anonymous users, since they're unlikely to be able to access other areas of the instance anyway. if we changed the docking behaviour to only happen for logged in users, would that solve your use case?

**Comment by laundmo** [comment]
> anonymous users, since they're unlikely to be able to access other areas of the instance anyway


it may be correct to consider the users anonymous from grafanas perspective, but the dashboards do require authentication. They're not actually anonymous, just logged into a completely separate web frontend with the dashboards showing in an iframe (using header-auth, service worker, and reverse proxy shenanigans to make sure users can only see dashboards they're supposed to)
