### ISSUE TITLE
Home Page: Clicking on "Tutorial Complete Grafana Fundamentals" does not do any action

### ISSUE THREAD

**Issue by AleksandraGrafana** [grafana/grafana#91565]
### What happened?

I installed Grafana OSS and Enteprise 11.1.3. After changing admin password I got to Home page. Clicking on "Tutorial Complete Grafana Fundamentals" does not do any action. I have to right-click on this tile and choose open link in new tab to actually open the link.
![image](https://github.com/user-attachments/assets/c75d8eb8-1073-4d90-95fb-32c2c20a18fd)

### What did you expect to happen?

New page opens after clicking "Tutorial Complete Grafana Fundamentals"

### Did this work before?

Not sure, I have not tried in other versions

### How do we reproduce it?

1. With Grafana OSS or Enterprise 11.1.3 open http://localhost:3000/?orgId=1
2. Go to Home page
3. Click on "Tutorial Complete Grafana Fundamentals" tile

### Environment (with versions)?

Grafana: OSS, Enterprise 11.1.3
OS: Windows 
Browser: Chrome and MS Edge as well

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by L-M-K-B** [comment]
I could reproduce the issue while running Grafana locally and checked the links in `public/app/plugins/panel/gettingstarted/steps.ts` They seem to be fine.

**Comment by yincongcyincong** [comment]
actually, i think it's intentional operation.
this is the a tags, it contains a href is tutorial link. howerver it has a click function.
https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/gettingstarted/components/TutorialCard.tsx#L26

the click function intentional stop to go to the link
```
event.preventDefault();
```
at blew code.
https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/gettingstarted/components/TutorialCard.tsx#L39
maybe not a issue.
@L-M-K-B @AleksandraGrafana

**Comment by AleksandraGrafana** [comment]
Hi Jackyin, thank you for your input on this. I am not sure what is the intention behind such behavior, do you have any idea?

**Comment by yincongcyincong** [comment]
> Hi Jackyin, thank you for your input on this. I am not sure what is the intention behind such behavior, do you have any idea?

i think we can at the code writer. @peterholmberg . could you please explan why not to go to the tutorial. thanks
