### ISSUE TITLE
[Feat Req] Prometheus: Support multiple table formated queries in table panel

### ISSUE THREAD

**Issue by carlpett** [grafana/grafana#9170]
Please include this information:
- What Grafana version are you using?
4.4.1

- What datasource are you using?
Prometheus

- What OS are you running grafana on?
Centos 7.3

- What did you do?
Created a table panel, with two metrics/queries. 

- What was the expected result?
The results concatenated results from the two queries

- What happened instead?
Only the results from the first query are returned. If the first query is disabled, the results from the second one are returned.

**Comment by torkelo** [comment]
maybe this can be solved when this issue is solved
https://github.com/grafana/grafana/issues/9134

**Comment by yunchih** [comment]
Hi, I'm using the nightly build `grafana_5.0.0-11292pre1_amd64.deb`

I expect the 6 columns to be displayed side by side.  However, they are being separated because there's a small time difference (just a few milliseconds) between the two queries ("system" and "cpu").
![f](https://i.imgur.com/cTRZO2Q.png)
![f](https://i.imgur.com/p4pUXgz.png)

Any workaround for this?

**Comment by nizamsp** [comment]
When the table has "Instant" mode checked, we can ignore the timeseries and merge only based on the prometheus labels?

**Comment by FounderHy** [comment]
> When the table has "Instant" mode checked, we can ignore the timeseries and merge only based on the prometheus labels?

Can you explain how to ignore the timeseries and merge only based on the prometheus labels? thank you in advance.
