### ISSUE TITLE
Tooltip: Hides on autorefresh

### ISSUE THREAD

**Issue by piecler** [grafana/grafana#91935]
### What happened?

When autorefresh triggers and you hover a bar in a time series chart, the tooltip disappears. If you move the mouse, it is visible again. This does not happen with lines or points. Only when at least one bar is in the chart.

This was already fixed half a year ago, but it is broken again.
See [https://github.com/grafana/grafana/issues/63247](https://github.com/grafana/grafana/issues/63247)

### What did you expect to happen?

The tooltip should stay visible while hovering the chart and autofresh triggers. As it does with lines instead of bars.

### Did this work before?

Yes, in Version 10 it worked fine after [leeoniya](https://github.com/leeoniya) fixed it. Since a few releases it is broken again.

### How do we reproduce it?

Create a timeseries chart with bars, turn on autorefresh, hover the charts so you see the tooltip with values and wait for autorefresh.

### Environment (with versions)?

Grafana: 11.1.x
OS: Ubuntu 24.04.4 LTS
Browser: at lease Chrome and Edge, probably all

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by leeoniya** [comment]
> Create a timeseries chart with bars, turn on autorefresh, hover the charts so you see the tooltip with values and wait for autorefresh.

i did this on play.grafana.org and tooltip remains as long as the new bar value is still within the hover proximity:

[Kooha-2024-08-14-17-08-33.webm](https://github.com/user-attachments/assets/b7f64557-06b8-4fba-8c90-67cfb15bccad)

if you want the tooltip to remain regardless of proximity, the only way to do this is to use the `Tooltip: All` mode instead of Single.

![image](https://github.com/user-attachments/assets/b66bd0b2-fe91-4fba-b4b5-3fc26d90d770)

**Comment by piecler** [comment]
Sorry, I was too quick with my analysis this time.
The bars seem not to be the problem this time.
My tooltip definetly disappears on refresh, but this time on every panel and every dashboard.
I try to find out more on what's going on here.
But in any case it's definetly broken somehow.

**Comment by leeoniya** [comment]
the tooltip will disappear if we have to re-initialize the plot. this happens when the config or the data schema changes.

i noticed you has `ORDER BY time DESC` in your query, which may be causing the issue. can you try switching to `ORDER BY time ASC` and see if this helps?

![image](https://github.com/user-attachments/assets/e24f45f1-711e-4ae8-a387-a64760641a83)

also, make sure you're on the latest version: https://grafana.com/grafana/download/nightly?edition=oss

if the bug is still present, then we'll have to figure out what is causing the plot to re-config by setting breakpoints and inspecting the query responses.

**Comment by piecler** [comment]
The changed ORDER BY did not work.
But just got the Update via apt to v11.2.0
The tooltip seems to be stable again.
At first glance I'd say it is fixed.
Thank you!

**Comment by leeoniya** [comment]
great, thanks for checking back in :)
