### ISSUE TITLE
Table panel: Update current dashboard template variable via cell links 

### ISSUE THREAD

**Issue by m-o-e** [grafana/grafana#9259]
- Grafana v4.6.0

To reproduce:

1. Set a table-column to `Render value as link`

1. Create a link that points to the current dashboard but with changed variables (e.g. `https://example.com/dashboard/db/overview?var-server=$__cell`)

1. Try to click the link. The address bar changes but the page does not reload.

**Comment by roozeec** [comment]
Hi

I have the same problem, the url in adress bar is ok, but page is not updated

**Comment by daniellee** [comment]
Tried this on the play site and it seemed to work. Is this localhost or a domain name?

**Comment by roozeec** [comment]
Domain name site (intranet)

**Comment by m-o-e** [comment]
Same here, domain name (not localhost).
I also tried with relative links, could not get it to work no matter what.

**Comment by daniellee** [comment]
I added a link to the first column of the first panel on this [dashboard](http://play.grafana.org/dashboard/db/table-panel-showcase?orgId=1).

Does this work for you? What do your links look like?

**Comment by m-o-e** [comment]
Yes, your test-link works for me.

I don't have my links up anymore (since they didn't work) but they were nothing special,
just the full URL of a dashboard, as displayed in the address-bar.

I'll try upgrading to latest grafana next week and see if the problem persists.

**Comment by m-o-e** [comment]
Ah, sorry, my description of the problem was wrong.

Linking to a different dashboard actually works for me,
but not linking to the *same* dashboard with different variables.

For example I'd like to use this template to switch to different server view:
`https://example.com/dashboard/db/overview?var-server=$__cell`

When clicking on that link (being on the overview dashboard) the address
bar changes but the page does not refresh. It looks like the url-change handler
doesn't get triggered when only the query-string changes.

**Comment by roozeec** [comment]
you're right, same behavior for me
but linking to the same url in new browser tab works ('open in a new tab' checked)

**Comment by DanKindaTheMan** [comment]
Hey Grafana team--

Bumping this. I just ran into this problem is a pretty bad way. See the screenshot for the use case here.

Basically, I have a list of failures from the latest software build test on the left, and I want to be able to click the module to update the "$module" variable. This should in-turn update the chart on the right with failures for that specific module.

Because the module does not update until the page is manually refreshed, the revised query for that table does not run, and it remains static.

The workaround of opening the link in a new tab works, but it rather defeats the point of making the dashboard interactive with the ability to click the module you want to view failures for.

Can this issue be re-evaluated for a new priority? This seems more of a bug than a feature request. Linking to the same page should still trigger the new parameters to take effect.

Thanks!
-Dan

![url variable does not update until refresh](https://user-images.githubusercontent.com/38562750/39055119-ac4b46ee-44b3-11e8-91f9-43db88e552c5.jpg)

**Comment by NateZimmer** [comment]
I've noticed the same behavior. Address bar text changes but page does not refresh. 

Only way for it to work is if I do the ``Open In New Tab`` option which gets annoying fairly quickly due to 20+ tabs.

**Comment by benclapp** [comment]
We're seeing the same issue, for almost exactly the same scenario as @DanSoQt. URL is correct, but only applied on page refresh. Running on Grafana 5.1.3.

**Comment by Vista-Group** [comment]
When the column style is defined, the link attributes allow to check **Open in a new tab**

![image](https://user-images.githubusercontent.com/34108958/41073856-51fe7cc6-6a59-11e8-8a71-0778bdbbbfe8.png)

What happens here is;
When **open in a new tab** is checked _Grafana_ renders the target attribute with the value: _blank which Opens the linked document in a new window or tab

On the other hand, when **open in a new tab** is unchecked _Grafana_ renders the target attribute without a value. I reckon that should be changed to _top or _self, so it replaces the frame content.

**Comment by coussej** [comment]
🤔I probably shouldn't do this, but I found a 'dirty' hack for grafana 5+:

Dashboard urls are now `/d/:uid/:slug`, and it looks like the slug values are being ignored during the routing. If you just replace the :slug with a unique value for the row that was clicked, and set some template variables in the query paramterers, a refresh gets triggered, the template variables are set and the slug is rewritten to the actual dashboard title.   

Example: `/d/BOzTbKKik/test-routing`

When I link to `/d/BOzTbKKik/rowValue1?var-testVariable=rowValue2`, a refresh gets triggered, rowValue1 is ignored and rewritten to test-routing and testVariable is set to rowValue2 🎉

Ugly, but works.

**Comment by DanSoQt** [comment]
@coussej This is great! A pretty nasty hack indeed, but it seems to be a fine workaround for the time being.

Thanks! :D

**Comment by DanSoQt** [comment]
@coussej @daniellee @torkelo 

Sorry to call you guys out with a mention, but can this issue be re-evaluated for a different priority or at least added to a project?

The workaround that coussej mentioned above does work, but it unfortunately has the side effect of resetting all non-specified template variables to their default values. (Of course, because the URL is altered.)

We really need some method for updating the template variables based on query data displayed in grafana dashboards.

**Use case / Justification:** Providing a method for updating template variables and re-running affected queries would help transform grafana from fairly static dashboards to interactive queries that the user can dynamically drill down into displayed data. Providing this functionality would also allow for de-cluttering of otherwise busy dashboards that are difficult to read at a glance. A dynamically updated template variable could be utilized by an overview panel to then switch targets for other panels in a dashboard such as graphs, pie charts, and other detail tables. In this way, panels can focus on a single target where the use needs only mouse-click an item they are interested in, thereby updating all related panels with the relevant data.

While of course users can accomplish this by manually selecting relevant entries from the appropriate template variable combo-boxes, this feature request makes grafana more intuitive and easier to use without explicit instruction for a given dashboard.

**Comment by amjad** [comment]
This is a very important feature for us as well. Is there a status update on this? @torkelo

**Comment by sonal1687** [comment]
Is there any update on this. This is quite needed feature. There should be some way to update variables in same dashboard on clicking cells in table. So this variable can be used by other panel items to load. Always opening new page for viewing details is not a good user experience.

**Comment by mattposch** [comment]
+1 absolutely need this!!

**Comment by qiujinhua** [comment]
The correct syntax is the variable name defined by the template in the target dashboard plus the "var-" prefix. For example, if a template variable is defined, such as server, the url is passed as a variable var-server=${__cell}
good luck

**Comment by jnereu** [comment]
I also had this problem on a scripted dasboard. I was able to work around the problem with:
-using the table click event with jquery
-parse the cell content and then inject with angular into variableSrv.

**Comment by Stono** [comment]
Also having to +1 this, it makes a whole load of our dashboards absolutely awful, please can we have an update?

**Comment by andreievg** [comment]
For devs wanting to update template variables from within plug in: https://community.grafana.com/t/how-to-change-a-dashboard-variable-value-from-a-plugin/10107/2

```
  updateVarable(varname:string, path:string) {
      console.log('update variable', varname, path );
      let v = _.find(this.variableSrv.variables, check => {
        return check.name === varname;
      });
      if(v) {
        this.variableSrv.setOptionAsCurrent(v, {
          text: path,
          value: path,
        });
        this.variableSrv.variableUpdated(v, true);
      }
  }
```

kudos @ryantxu

**Comment by NetSensors** [comment]
+1 on this. Grafana could be a fantastic tool with this functionality.

**Comment by fadeer** [comment]
> This workaround, the backslash before the query params, causes a full page refresh and updates the other panels but it looks clunky and none of the panel setting such as timescale persist.
> /grafana/d/bRO_GUaWz/things/?orgId=1&var-deveui=393435377C378008

This workaround help me a lot, thanks!
And you can try to append from/to query params to keep timescale.
`/grafana/d/bRO_GUaWz/things/?orgId=1&from=$__from&to=$__to&var-...`

**Comment by CarlosNZ** [comment]
Yes, +1 here. Would be good to have this working correctly. Opening new tabs is a clunky way to operate.

**Comment by carlosoliverosmonti** [comment]
maybe this helps =)

javascript:window.location.href='/d/qXHtipxZz/nodos-puertos-usados-y-libres?var-no_sitio=${__cell_1}&var-no_destino=${__cell_2}&orgId=1&from=$__from&to=$__to'
![Captura de pantalla -2020-01-21 11-57-30](https://user-images.githubusercontent.com/29068197/72825358-dfe52300-3c44-11ea-9e54-d3e4b58efe56.png)
