### ISSUE TITLE
Search: Document sub folders not searching

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#92973]
Current nested folders search implementation has a known limitation that when searching in a folder, subfolders of that folder are not searched. The only way to search in subfolders is to search from the root view.

This known limitation should be documented to help people out.

**Comment by eledobleefe** [comment]
@joshhunt would you add it [here](https://grafana.com/docs/grafana-cloud/whats-new/2024-08-29-improved-subfolder-creation-flow/), where we talk about subfolders creation?

**Comment by suntala** [comment]
Wanted to flag that some users have the opposite expectation. They expect that when searching in the General folder, nested folders should not be returned. See [NestedFolders: Fix a bug when searching folders under the general folder](https://github.com/grafana/grafana/pull/91042). Has a product decision already been made about what the expected behaviour should be?

**Comment by eledobleefe** [comment]
> [@joshhunt](https://github.com/joshhunt) would you add it [here](https://grafana.com/docs/grafana-cloud/whats-new/2024-02-27-subfolders/), where we talk about subfolders?

To add here: https://grafana.com/docs/grafana/latest/search

**Comment by imatwawana** [comment]
Per our conversation @eledobleefe, I did a bit more investigating and I think you're right and adding this content to the [Search](https://grafana.com/docs/grafana/latest/search) page is the right spot. I'll be automatically tagged on the PR; please give me a chance to review it so I can make sure the positioning makes sense.
