### ISSUE TITLE
Build for Windows 32bit not working

### ISSUE THREAD

**Issue by BartWitdouckVDW** [grafana/grafana#9310]
Hello, 

I'm new to Golang but I'm trying to implement Grafana to our HMI solution.
Unfortunately we're running on a 32-bit Windows OS and no installer is available.

I've tried all the steps [under](http://docs.grafana.org/project/building_from_source/) but without success.

I've set the constant GOARCH to 386
![image](https://user-images.githubusercontent.com/30232821/30636057-ad3f2ee6-9df4-11e7-9765-e76549e8b83d.png)

And then afterward I get this error
![image](https://user-images.githubusercontent.com/30232821/30636091-ce1b9316-9df4-11e7-907f-e8d2a9196b35.png)

Could anyone succesfully build Grafana for 32-bit?
Please send me the package.

Thank you!

**Comment by torkelo** [comment]
not sure what could be the cause, same error as in this issue ,https://github.com/grafana/grafana/issues/8992

**Comment by BartWitdouckVDW** [comment]
@torkelo Are you able to build for Windows 32? If so, could you share the package?

I've read only it should be possible but the link is dead:
[http://system-network-administration.blogspot.in/2016/02/grafana-32-bit-windows.html](http://system-network-administration.blogspot.in/2016/02/grafana-32-bit-windows.html )

**Comment by tomhollingworth** [comment]
@BartWitdouckVDW I've managed to compile for Windows 32. I was getting the same error as above and found that `CGO_ENABLED=1` was required after reading https://github.com/mattn/go-sqlite3/issues/327

I'll test it out on my 32-bit windows tomorrow.

**Comment by rajeshkumarsugumar** [comment]
@BartWitdouckVDW Did you get any luck on your testing?

**Comment by scelle** [comment]
windows 32-bit compiled version succesfull here.  
I followed this post combined with mattn/go-sqlite3#327
used latest go version (1.12)

**Comment by asimakos** [comment]
Hello! I have just read your interesting blog and i have got the same issue. Could someone share it with me as it would help me a lot? Regards

**Comment by vdwpsmt** [comment]
Hi @asimakos, 
It is not clear what exactly you want to have shared?  This is an old post and I'm not sure the build process for grafana is still exactly the same.  Have you checked this?
https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md

**Comment by asimakos** [comment]
Hello @vdwpsmt  and thanks a lot for your reply!

I had had studied the following
https://www.bookstack.cn/read/grafana-v6.2/7adb4f0d26baf1da.md  and additionally   
https://faun.pub/how-to-build-grafana-from-source-dbf116cf2175.

To be honest i had come across several errors during backend process ( installed of course gcc), while frontend process had downloaded a lot of stuff (>3GB).  Sorry if I do not remember exactly about it as many days have already passed (25 or more days) since i last tried it unsuccessfully and afterwards i quitted due to no reply.

I had had sent a post to grafana community for it
https://community.grafana.com/t/grafana-for-win-32bit/69613  and even emailed to @grafana and still nothing. 

I wonder if it would be convenient for you in case you have got a workable win-32 grafana distribution (executable). That would help me a lot!

Regards

**Comment by asimakos** [comment]
Hello  @vdwpsmt  and thanks again for your reply!

I just found the following link that dates 3 years ago (old grafana version)
https://stackoverflow.com/questions/55374581/why-grafana-is-not-available-for-32-bit-windows-machine

and of course mine that dates 23 days ago
https://stackoverflow.com/questions/73090801/grafana-build-win-32-bit-version

To be honest i do not expect someone willing to help me.

Regards again

**Comment by vdwpsmt** [comment]
As I mentioned in the previous post, try to follow the official developer-guide.  Once you succeed in building for standard 64 bit, you're almost there, than it's only a matter of changing a go env variable (set goarch=386) and building again.
Unfortunately, I don't have this env on my laptop anymore, so can't be of much more help now.

**Comment by asimakos** [comment]
I will try it but I think that it would be easier for @grafana to give me a win-32 version (despite numerous requests) since they build it frequently for win64 and they know the whole process inside out. In case something goes wrong regarding golang edition or anything else I am afraid that no one will reply to me again.
Anyway thanks for your own interest and advice!

Regards

**Comment by asimakos** [comment]
Hello @vdwpsmt !
Unfortunately I have got an issue to build grafana from souce. I describe it below
https://forum.golangbridge.org/t/grafana-error-build-from-source/32489/6
Your assistance would be convenient to me!
Regards
