### ISSUE TITLE
Grafana/Runtime: using useChromeHeaderHeight results in infinite rendering cycle

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#93219]
`useChromeHeaderHeight` should just return a height of the header based on a visual mode grafana is in like `kiosk` or `chromeless`. This information though is all inside `AppChromeService` state and so the hook is dependant on the whole `AppChromeService.state` for this.
https://github.com/grafana/grafana/blob/334657e1cb46bc30699dfcafef14e1b42e86dbd8/public/app/core/context/GrafanaContext.ts#L49

It seems that because of this in some case the hook can create a cycle, if the render path also changes something in the `AppChromeService.state` most likely `sectionNav`.

### Repro scenario
To test this behavior, minimal report seems to be to add these lines:
```
const height = useChromeHeaderHeight();
console.log(height);
```
here
https://github.com/grafana/grafana/blob/47f87171496f675bc44ddf839effaed1846bfa4e/public/app/features/explore/ExploreToolbar.tsx#L71

which should result in
```
An unexpected error happened
Details
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

------------------

This may not be a clear bug on the side of `useChromeHeaderHeight` hook. This happens in Explore probably because of updating the `AppChromeService.state` like here https://github.com/grafana/grafana/blob/40157111336615a85440f990dd584c93c42600b6/public/app/features/explore/ExplorePage.tsx#L70

I think though that such dependant behavior is very surprising in this case and I think we should find a way to make the `useChromeHeaderHeight` not force rerender on changes of `AppChromeService.state` that aren't relevant to it, in a similar way that you can select only parts of Redux state that are relevant to render using selectors.

**Comment by ashharrison90** [comment]
ok started looking into this a bit. so it's caused by using a combination of `AppChromeUpdate` and `useChromeHeaderHeight` in the same component. basically:
- `useChromeHeaderHeight` relies on `chrome.useState()`, which returns an observable that watches the whole state
- `ExploreToolbar` renders `AppChromeUpdate` which updates the `actions` (part of the state)
- because the `actions` (and therefore the state) are updated, the observable triggers which causes the component (`ExploreToolbar`) to rerender
- `AppChromeUpdate` gets rerendered, and updates the `actions` again
- infinite loop!

my rxjs isn't the best, so need to do a little digging, but i imagine this is solvable with something like you suggested in your last paragraph 👍
