### ISSUE TITLE
Teams: Team creation is taking placing in user active org

### ISSUE THREAD

**Issue by michael-sawczuk** [grafana/grafana#93375]
### What happened?

Attempting create a new team via the API, providing a `name`, `email` and `orgId`, when POSTed the team is created in the user's active org, ignoring the `orgId` value in the request.

The request itself is returning a 200 with a confirmation message the team had been created:
`{
    "message": "Team created",
    "teamId": 41
}`

### What did you expect to happen?

The `orgId` in the payload is honoured and the team is stood up in that org.

### Did this work before?

Only started to use teams now so never seen this working correctly.

### How do we reproduce it?

1. Open up Grafana and navigate to a different org to that held in the JSON payload to create the team.
2. Create the team via the API, I used Grafana's example request. **Make sure the orgId does not match your current active org in Grafana**:
```
{
  "name": "MyTestTeam",
  "email": "email@test.com",
  "orgId": 16
}
```
3.POST the payload to Grafana_base_url/api/teams/
4. Go to your active org's team section, you will find the newly created team there and not in org 16.

### Environment (with versions)?

Grafana v10.4.8 (7a08b0bae7)
OS: Rocky 8 server, client python requests / curl
Browser: Firefox

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by kalleep** [comment]
Hey, the team api org specific. The documentation is wrong https://grafana.com/docs/grafana/latest/developers/http_api/team/#add-team. We never parse the org id from request body and we don't want that because the request is authenticated in the current org.

To achieve the desired result you need to authenticate the request in the target org instead. That can be done by either adding a query parameter to the request e.g `http://admin:admin@localhost:3000/api/teams?targetOrgId=2` or setting `X-Grafana-Org-Id` header. 

Be aware that this does not work for service accounts because they are org specific
