### ISSUE TITLE
.deb package creation

### ISSUE THREAD

**Issue by dataselfservice** [grafana/grafana#93370]
Hi,

wrt `11.2.0`, what is the way to create a .deb package from source? It appears some commands were removed from `Makefile` and `build.go`. Can anybody help or comment?

Cheers!

**Comment by kminehart** [comment]
Hi @dataselfservice , sorry for the late response. Been swamped lately.

We've moved all of our packaging code to `github.com/grafana/grafana-build`.

You can build a `.deb` for any version of grafana by using a command like this:

Note that it uses [`dagger`](https://dagger.io) and docker buildkit to make a production build of Grafana, so it will take at least several minutes depending on your hardware.

```
go run ./cmd artifacts -a deb:linux/amd64:grafana --grafana-ref=v11.0.5 --go-version=1.22.7
```

Alternatively, you can set `--grafana-dir` instead of `--grafana-ref` to skip cloning.

If you want more insight into what it's doing, do `dagger run go run` instead of just `go run`.
