### ISSUE TITLE
Explore Metrics: Homepage graph does not match detailed graph

### ISSUE THREAD

**Issue by catherineymgui** [grafana/grafana#93413]
Sometimes, the graph on a metric select page does not seem to match the graph when you click into the metric.

See video: https://github.com/user-attachments/assets/3cf25aba-75f4-4725-82e8-30d053a20cf9

I've only noticed this on the mythical-app data source, but not any other ones

**Comment by itsmylife** [comment]
We request different datapoints in different places. Please see the image below:

![Image](https://github.com/user-attachments/assets/efcc101a-db45-4bcf-a9aa-116ac9075a20)

In some edge cases, this leads to having a different-looking graph. Since we request small amount or big amount of data points some spikes might be missed. I've talked to @darrenjaneczek about this and he suggested to use values that multiples of each other. Like `250, 500, 1000` etc. Or use same datapoint value everywhere. (There is a catch. On the main screen we don't want to fetch a lot of datapoints so we request small amount)

@zhehao-grafana @catherineymgui Since this is kind of an edge case maybe we use `250 and 500` only. We eliminate having lots of different `maxDatapoints` and have some sort of consistency. This is not a silver bullet but we can try.

**Comment by catherineymgui** [comment]
FYI - Ismail and I talked through this to understand
1. What datapoints were (units of data stored over time, the more data points, the more granular the detail)
2. How using 250/500 datapoints vs. 200/300 datapoints may be helpful (The hypothesis is that by only splitting datapoints in half, it's more likely that the two graphs would be more 'equal', like resizing an image by 50% vs 40% or smth) 

As part of next steps, @itsmylife will confirm which part of Explore Metrics the different Panels refer to, and then we can try this out

**Comment by itsmylife** [comment]
"Select Metric" scene -> 200
"When you select a metric" scene -> 500 
"Breakdown" scene -> 250 
"On breakdown selecting a label" -> 300

**Comment by catherineymgui** [comment]
Thanks for the context! I think we can try your proposal and see how it goes.
