### ISSUE TITLE
Grafana 11.1, 11.2: Navigation path change after starring a dashboard hinders access to other dashboards

### ISSUE THREAD

**Issue by krzysion** [grafana/grafana#93564]
### What happened?

Since Grafana version 11.1.0, after marking a dashboard with a star, the navigation path changes. Instead of the folder where the dashboard is located, the "starred" location appears. This makes it very difficult to navigate to other dashboards from the same folder as the starred dashboard.

Grafana 11.0.0
![Image](https://github.com/user-attachments/assets/1bc534eb-049d-44f0-b1b2-3218e9249c11)

Grafana 11.1, 11.2
![Image](https://github.com/user-attachments/assets/fe9dd55a-5372-4c27-91c9-8d6fdead3cc7)

### What did you expect to happen?

Even after a dashboard is starred, the navigation should continue to display its full path

### Did this work before?

10.x.x, 11.0.0

### Environment (with versions)?

Grafana: 11.2.0
OS: Windows 11
Browser: Chrome

**Comment by joshhunt** [comment]
Hmm, there appears to be some uncertainty about the expected behaviour here.

 - @ashharrison90 tweaked the behaviour for this recently to make sure that Starred 'correctly' shows in the breadcrumbs for starred dashboards https://github.com/grafana/grafana/pull/87145
 - With non-scenes dashboards (the default in OSS), it gets the Starred breadcrumbs
 - In the new scenes dashboards (append `scenes=true` to the querystring for a dashboard url), you don't get the Starred breadcrumbs.

I think I agree with your preference for the ideal behaviour.

**Comment by joshhunt** [comment]
Discussed with a few people, and we agree that the breadcrumbs for starred dashboards should not include "Starred". Thankfully, the new dashboards architecture already functions like this. Because this is almost rolled out to all users (including OSS/on-prem in the near future), we don't think it's worth the effort to fix it in the old dashboards implementation, although we could accept a PR if someone felt strongly about it.
