### ISSUE TITLE
[Feature request] Alternative positions for graph panel label (on top of data)

### ISSUE THREAD

**Issue by tuukkamustonen** [grafana/grafana#9394]
A graph label is often taking unnecessary amount of space:

![image](https://user-images.githubusercontent.com/94327/31070087-c8825486-a767-11e7-97f6-2374caa00d80.png)

Would it be possible to allow re-positioning the label on top of the drawn graph as in:

![image](https://user-images.githubusercontent.com/94327/31070447-09a8d4d4-a769-11e7-82c4-c8c4a3c789d4.png)

This allows to show the actual data bigger in size, while the graph panel is actually the same size.

Or maybe:

![image](https://user-images.githubusercontent.com/94327/31070419-ee640a86-a768-11e7-9435-ff4dc5ac0071.png)
![image](https://user-images.githubusercontent.com/94327/31070107-d508f642-a767-11e7-9dcb-14f136caeca1.png)

It could allow multiple pre-selected positions, e.g. top-left/bottom-left/top-right/top-bottom/top-middle/bottom-middle.

Could work so that when you hover over the graph in question, the label becomes (mostly?) transparent.

This would save a lot of space in multi-row dashboards.

This is related to https://github.com/grafana/grafana/issues/9305 and https://github.com/grafana/grafana/issues/9393 in attempt to make dashboards a little bit easier for the eye.

Running Grafana 4.5.1.

**Comment by daniellee** [comment]
Thank you for submitting this feature request. However, due to inactivity and/or lack of upvotes, we’re going to close this for now. This does not mean that we are closing it forever. Feel free to comment on this issue to clarify why this is needed and upvote it.

We hopefully will be solving this problem in the near future by adding the feature to have one query and multiple small visualiations (like the bar gauge and [table](https://grafana.com/docs/grafana/latest/panels/visualizations/table/table-field-options/#cell-display-mode) panels) to the new Graph panel that we are working on right now.
