### ISSUE TITLE
Correlations: Handle loki dataplane log lines, even if different field is used

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#94075]
### What happened?

There is a feature to move loki logs to have standardized fields. This is currently behind a feature flag, but is being moved to be GA'd soon.

For correlations, the user explicitly defines what field the correlation is attached to. Commonly, the `Line` field is used, as that is where the log line data is. The `Line` field can then be transformed using `logfmt` or a regular expression to extract out data for the correlation.

In the standardization, the `Line` field is named `body`. The field can actually be named whatever, and with the data plane, there are other settings to indicate the field is the log line.

We would like to support this working, even if the Correlation explicitly defined the Correlation to use `Line`. 

If the feature flag is on, the source data source is Loki, and the results field is specified as `Line`, use the data plane information to find the `body` field and use that as the results field instead for the correlation.

### What did you expect to happen?

Correlations should work as expected, even if the underlying information changes.

### Did this work before?

No, this would have always been broken when the feature flag is enabled.

### How do we reproduce it?

1. Create a correlation for a log line, using the `Line` field, and check it works as expected
2. Enable `lokiLogsDataplane`
3. Try to find the correlation again and see it no longer works.

### Environment (with versions)?

Grafana main

### Grafana platform?

None

### Datasource(s)?

Loki

**Comment by naaa760** [comment]
Hello @gelicia :)


I think the correlation retrieval logic needs to be updated to automatically **remap correlations** defined with {Line{ to {body} when the {lokiLogsDataplane} feature flag is enabled. 
This will address the bug that affects log correlations in the Loki data plane caused by the switch from the {Line} field to the standardized {body} field. 
The relevant log line field can be found by consulting the data plane settings. 
To further explain these modifications and their effect on current correlations, user documentation must be updated. 
To maintain the reliability and user experience thorough testing should be carried out to guarantee that correlations operate as intended in the both cases.
