### ISSUE TITLE
Panel sharing improvements

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#94145]
**Goal**
The goal is to enable image rendering within the same dialog (drawer) to maintain user context and improve the flow without redirecting to a new tab.

**Background**
Currently, the image render feature in the sharing panel opens in a new tab, causing users to lose context by leaving the page. We propose allowing the image to render within the same dialog (drawer) to keep the user engaged and maintain context within the flow.

**CTA to render image in a new tab:**
![Image](https://github.com/user-attachments/assets/03fee871-6808-4cf7-81b1-90a008167dab)

**Image rendered in a new tab:**
![Image](https://github.com/user-attachments/assets/9e7ac3fc-6692-49ce-b648-62aa957454dc)

**Comment by natydej** [comment]
[Figma file](https://www.figma.com/design/AjvrAorYpnfSoMpU5kwf39/Adoption-of-Sharing?node-id=5317-26064)
**Designs proposals**
**OptionA:** Showing the render image right away without any action from the user
![Image](https://github.com/user-attachments/assets/02cce9ce-fcb9-4728-b37b-96e21acf7ec8)

**OptionB:**Having a CTA that will render the image in the same context below
![Image](https://github.com/user-attachments/assets/cd3da7b6-a728-4ab9-8799-15f592c2f713)
![Image](https://github.com/user-attachments/assets/d926de96-82ed-443c-ab2e-71994e82ecb7)
![Image](https://github.com/user-attachments/assets/f1e2d070-eebc-44ed-9876-5fe794a2386e)

**Comment by juanicabanas** [comment]
My opinion on this:

**Option A**
It will call the render service whenever the user opens the drawer. That consumes a lot of resources and the user may not want to render the image, but make modifications in the configuration and copy the link. **Therefore, I prefer option B**

**Option A and B**

1. Once the image is generated, it cannot be generated again. With the current approach, you reload the browser page and get a new image with, for example, updated data due to the relative time range. We would need a `refresh` button to create it again
2. The copy link button seems weird. As it's next to the Download image button, it appears to copy the URL image while it's the panel URL inside grafana
3. Although the current URL that renders the image is an API URL that calls the service every time the user access it, it's a way of "sharing" the image. I mean, the user can share that URL with anyone with access and get an image. I think we should add a "copy" image link button, but improving this case: instead of being the URL that generates an image once again, investigate if it's possible to return the path where the image is stored (I think it's possible)
4. I prefer [this design](https://www.figma.com/design/AjvrAorYpnfSoMpU5kwf39/Adoption-of-Sharing?node-id=5544-10751&node-type=frame&t=EFQJwI31DA0wmXus-0), as it doesn't cause a screen flickering and changes the buttons position

**Comment by juanicabanas** [comment]
Discuss if it's possible to add some inputs to customize the image, as some users are currently changing the URL parameters
- width
- height
- scaleFactor

**Comment by natydej** [comment]
I have 2 designs proposals:
[Figma link](https://www.figma.com/design/AjvrAorYpnfSoMpU5kwf39/Adoption-of-Sharing?node-id=5317-26064)

**Option A**
![Image](https://github.com/user-attachments/assets/1fc04e6c-4646-4e4a-b9ee-8faaeefac992)


**Option B**
![Image](https://github.com/user-attachments/assets/9f9bad2a-9ccc-4f91-a560-4cc9dcc51773)

**Comment by natydej** [comment]
We decided to go with proposal B cc @juanicabanas

**Comment by natydej** [comment]
Updated designs below
![Image](https://github.com/user-attachments/assets/a307814b-b5f2-42a6-98df-fcad1507cf35)
[Figma link](https://www.figma.com/design/AjvrAorYpnfSoMpU5kwf39/Adoption-of-Sharing?node-id=5317-26064)

**Comment by natydej** [comment]
Changes updated:

- Change the description text, by removing the word "your" in the share panel sentence.
- Change the `px` suffix to be at the end of the `input` to follow the pattern of the component.
- Change the wording of the CTA from "Render image" to "Generate image", because more people would be familiar with the concept of generating an image vs rendering it, and also to keep consistency with other places where we use the "generate" word.
![Image](https://github.com/user-attachments/assets/4214f08b-fce4-42e3-b455-8144456459e0)
