### ISSUE TITLE
How to use Prometheus data source to create a State Timeline panel display?

### ISSUE THREAD

**Issue by double-yaya** [grafana/grafana#94446]
**Why is this needed**:

[Add a description of the problem the feature is trying to solve.]

**What would you like to be added**:

[Add a brief description of what the feature or enhancement should do.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Comment by bohandley** [comment]
Handing this over to @grafana/dataviz-squad for the panel. Is it possible to use this State Timeline panel? Please add us dataviz squad if you need to but for now, we are handing this off to you.

**Comment by gelicia** [comment]
I'm not sure what is really being asked here in terms of changes to the code base. I encourage you to check out the documentation for state timeline here https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/state-timeline/

When I'm looking at Prometheus and State Timeline, I think the most important configuration is setting up the right threshholds to indicate the state changes - that is how you would turn a metric from prometheus into a state

In this example, the threshhold I specified defines what is a "green" state and a "red" state. I set this up using data available on https://play.grafana.org/ 

![Image](https://github.com/user-attachments/assets/9cdadc21-82e0-4af1-b296-d9efdc4e660b)

Please check it out, play around, and let us know if you still see something Grafana is missing to make this work for you.

**Comment by MarleTangible** [comment]
I think Grafana has no concept of state transitions over time. Not everything is a time series value that translates well. 

For example, a machine can be in a state of online, idle, running, error, setup, transferring, etc. There are no numerical values that makes sense here, and assigning numerical values to such states is also asinine because an idle machine is not a half of a running machine and things like averages of such values over time has no meaning.

A lot of places that use Grafana would like to have a state timeline of what the machines were doing within certain times. Creating a panel like below takes a lot of conversions between different values and I think that's where people are getting lost.

<img width="1829" height="611" alt="Image" src="https://github.com/user-attachments/assets/4cc103a8-e9e9-4308-a983-4d20ac2f9a5a" />

Edit: Please note the machine status changing over time. It's not a numerical value that is considered one thing or another for a given range of thresholds.

**Comment by MarleTangible** [comment]
And here's how such an information usually look like in a database.

<img width="319" height="618" alt="Image" src="https://github.com/user-attachments/assets/04f5c713-fd07-488a-a64e-91873b962dea" />
