### ISSUE TITLE
[Feature request] Allow vertical zoom in graph panel

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#9457]
* Grafana version: v4.5.2
* What datasource: Graphite, Prometheus.

Grafana graphs currently support horizontal zoom, e.g. to focus on a particular subset of the current time range. It would be very helpful to also support vertical zoom. In order words, to temporarily override the Y-axis min and max.

This can enable much better understanding of the data in a more granular level. Especially for one-off cases. Without requiring one to edit the graph settings. (Apart from being a big barrier, also not all viewers will have edit rights.)

Here is an example from the London Datastore that provides this ability:

<https://data.london.gov.uk/>

![](https://user-images.githubusercontent.com/156867/31311341-580c4d8a-aba2-11e7-8a48-bd348f4b3a9f.png)

==============================
‣ Zoom 
‣ Result 
------------------------------
![](https://user-images.githubusercontent.com/156867/31311349-71d7eac6-aba2-11e7-9a8b-c5ba41da6628.png)
![](https://user-images.githubusercontent.com/156867/31311348-71d52070-aba2-11e7-8d99-6f18945843a0.png)
\==============================

==============================
‣ Zoom 
‣ Result 
------------------------------
![](https://user-images.githubusercontent.com/156867/31311367-df799066-aba2-11e7-99a7-8793b541ded4.png)
![](https://user-images.githubusercontent.com/156867/31311370-e13a47f6-aba2-11e7-8019-5f9066e8f398.png)
\==============================

**Comment by texnic** [comment]
This is a very needed feature. Actually, until finding this feature request, I thought I just haven't yet found how to zoom vertically.

**Comment by pdlje82** [comment]
I was also looking for vertical zoom function. Has this already been added?

**Comment by rdubya16** [comment]
Any movement on this feature? Would be great to have.

**Comment by gsgiles** [comment]
Is this serious? You can zoom out but then you cannot zoom in?

**Comment by torkelo** [comment]
You can zoom in, just mark a region on the graph

**Comment by rmunoz10** [comment]
Following up on the original Feature Request "Allow vertical zoom in graph panel #9457" @Krinkle as I was looking for the same feature as a must have for us.  Is this feature on the roadmap?

**Comment by ole-kaas-coop** [comment]
As a workaround, you can define a variable to simulate zoom functionality. E.g. in applications insights:
`| extend duration_clamp=iif(duration < $Ymax, duration , real($Ymax))` 
This will clamp spikes to value defined by $Ymax

**Comment by baecker1337** [comment]
Any movement on this feature? Would be great to have.

**Comment by johnhtodd** [comment]
I finally got around to looking for where this functionality was (it's so obviously needed, I figured I was just being thick and not seeing it) but it turns out it doesn't exist.  So +1 for me.

A brief idea on how it might work:  Each Y axis in the Editing mode would have a toggle with a name like "Show resizing" which would put new UI objects on the graph on the respective axis.  Each axis would get a small up & down arrow set at both the top and bottom of the axis text.  Pressing the "up" arrow or "down" arrow would add/remove a horizontal division multiple increment of the original graph size. 

An example might be better: A graph that, at a particular size, goes from 0 to 10, and has 5 horizontal lines, each indicating a step of 2000. Clicking the "up" icon at the top of the graph would add 2000 to the maximum Y value, and would re-size the graph to now have 12000 as the maximum Y, with 7 lines (number of lines is auto-computed via some method that is unrelated.)  Pressing "up" again would add (2000*2) to the maximum Y, increasing the maximum Y to 16000.  Pressing "up" again would add (2000*3) to the maximum Y, increasing it to 22000.  Pressing "down" would subtract in a similar fashion.  The same would be true on the bottom line.

This allows for what seems like a logical, smooth but increasing progression to quickly find the top or bottom edge of any data that may be off the previous chart while using the original graph as the basis for increase so the steps would not be surprisingly large or tediously small. The graph would be a little busy looking with the up/down arrows, but it would be an optional flag to permit resizing so "buyer beware."

There are simpler UI models (a "wheel" beside the axis, for example) but they don't allow for any easy way to modify the lower bounds as well as the top. If your data exists below the bottom of the shown graph area, there still would need to be a UI element to allow zooming action on that area.

**Comment by tgree** [comment]
Please, somebody has to add this type of zooming!  For such an advanced product it's extremely disappointing that it is missing such basic functionality.  It should have Y-axis zoom and rectangular zoom along with the current Time-axis zoom.  That's like the bare minimum for a product like this.

**Comment by mpw-eng** [comment]
I've just started tinkering with Grafana and it's an excellent package.  I work in the process control and automation space. In my industry, the ability to zoom in on time-series charts using a window, or override vertical axis scaling is a standard feature of nearly all commercial historical data trending/charting packages - so this one gets my vote too!

**Comment by McSunas** [comment]
Another +1 for y-axis zooming, please. Needed!

**Comment by htlinn-go** [comment]
+1 from me. I am a huge fan of grafana but the lack of vertical zoom keeps me starting alternatives way to often.

**Comment by leeoniya** [comment]
while i cannot say when or if this is on the roadmap, the new graph panel (Graph NG) should technically be capable of supporting vertical, rectangular and additional zooming variants: https://leeoniya.github.io/uPlot/demos/zoom-variations.html. i don't know how or if these capabilities will be exposed in the UI.

cc @mckn @dprokop this could probably use an additional `area/panel/graph` tag.

**Comment by gronat** [comment]
Still impossible to scale y axis? InfluxDB UI can do it.

**Comment by nabelekt** [comment]
Just want to state that it would be useful to be able to zoom out as well as in. Sometimes, when I don't see my threshold values on the plot, I want to zoom out on the y-axis to see what/where they are.

**Comment by iqcqiti** [comment]
3+ years waiting...

**Comment by tollk** [comment]
+1 from me. Also see this as the most basic feature currently missing. Currently our users have to deselect the lines with the biggest scale in order to zoom in.

**Comment by PMehrfeld** [comment]
+1

Related to #1387

**Comment by MPatzek** [comment]
+1

**Comment by jesusdf** [comment]
+1

**Comment by Romathonat** [comment]
+1

**Comment by AnesBendimerad** [comment]
+1

**Comment by mehdi-kaytoue** [comment]
+1 ! I would LOVE this feature !

**Comment by AlexSzczepaniak** [comment]
+1

**Comment by RishoT17** [comment]
+1

**Comment by peterhinson** [comment]
+1

**Comment by wfjm** [comment]
+1  
As @tgree wrote
> For such an advanced product it's extremely disappointing that it is missing such basic functionality.  
> It should have Y-axis zoom and rectangular zoom along with the current Time-axis zoom.   
> That's like the bare minimum for a product like this.  

I've many panels where I don't want to fix the scale.  
But a single outlier can make the panel unusable.  
In other tools, even in Chronograf, one simply stops auto-update and does an Y-Axis zoom.

And in cases where the y scale is fixed, typically from 0 to a maximal value, one often wants to see what happen at small values. Again, a Y-axis zoom is the way to go.

This issue is 3 years old, as  @iqcqiti remarked, and this seemingly simple, obviously useful, and given the like and "+1" count much missed feature is still missing.

**Comment by alexschroeter** [comment]
+1

**Comment by darksidelemm** [comment]
Adding another +1 for this functionality. One outlier and our plots are unusable.

**Comment by gasagna** [comment]
+1

**Comment by sinamics** [comment]
+1

**Comment by athamour1** [comment]
+1

**Comment by giukio** [comment]
+1 for me as well!

**Comment by kakila** [comment]
+1, super useful.

**Comment by wijjj** [comment]
Yes, this would still be amazing, actually. :)

**Comment by darksidelemm** [comment]
... and we got so close with https://github.com/grafana/grafana/pull/58016 as well...

**Comment by sinamics** [comment]
It's unfortunate that the Grafana team seems unwilling to incorporate this feature, considering their extensive user base. 
Why not provide this feature as an optional setting, letting users decide whether they want to activate it or not?

**Comment by mampersat** [comment]
+1

**Comment by OscarFueGo** [comment]
+1

**Comment by duane-impulse** [comment]
+1

**Comment by jorgenhs** [comment]
+1

**Comment by tomerr90** [comment]
6 years, so much interest, and such basic functionality is still missing, crazy....

**Comment by hannesrrr** [comment]
+2

**Comment by tobiokanobi** [comment]
Arghhhhh ...if that is not possible to zoom to y, it is a reason to zoom out of grafana and zoom in somewhere else.

**Comment by leeoniya** [comment]
this will be available in 10.2, and in the upcoming nightly build: https://grafana.com/grafana/download/nightly?edition=oss

**Comment by cesuper** [comment]
Great! Is this feature available in this version: Grafana v10.2.0-134720 (4f5728233c) ?

**Comment by leeoniya** [comment]
i guess our nightly build pipeline is currently busted, that commit is 2 weeks old :(

**Comment by JakkuSakura** [comment]
For those who wanted to know, the zoom in on y-axis is shift-drag

**Comment by bclrk** [comment]
Is there any way to remember the amount I've zoomed in? If I set the auto-refresh value to 5s, as soon as I zoom in it will refresh and unzoom. This is frustrating if I'm trying to look at live data without an outlier.

**Comment by nabelekt** [comment]
What is the best/easiest way to undo the vertical zoom?
Ctrl+click does it, but that also tries to add an annotation.
Changing the time range also does it, but I don't want to do that.

**Comment by leeoniya** [comment]
> What is the best/easiest way to undo the vertical zoom?

double-click

**Comment by ahutson-bbc** [comment]
FWIW I've found that it's quite hard to zoom to a selection that goes all the way to the bottom of the y-axis. If you move your mouse past the bottom, it snaps to the top of the y-axis instead for some reason. It would be good if that could be fixed.

**Comment by leeoniya** [comment]
please open new issue for this

**Comment by ahutson-bbc** [comment]
> please open new issue for this

https://github.com/grafana/grafana/issues/93118
