### ISSUE TITLE
Annotations: Be clear about what annotations cannot be deleted

### ISSUE THREAD

**Issue by adela-almasan** [grafana/grafana#94651]
Grafana is configured to load alert annotations from Loki's backend, the annotations cannot be deleted because Loki's backend does not support such an operation. The annotations are loaded from the API as normal, but an id of 0 indicates they cannot be deleted.

We should hide the invalid UI options for these types of annotations, so users are clear on what operations cannot be performed.

**Comment by yuri-tceretian** [comment]
I think I know what's going on: when Grafana is configured to load alert annotations from Loki's backend, the annotations cannot be deleted because Loki's backend does not support such an operation. 
I recommend that the UI remove the button to avoid confusion. We can add some information that explains why it cannot be deleted. I believe the ID=0 is a good indicator of such annotations.
