### ISSUE TITLE
Ability to set transparency for line/bar/point

### ISSUE THREAD

**Issue by XANi** [grafana/grafana#948]
It should be possible to set up specic color for given metric (bot for single, and via overrides) and also have ability to make lines transparent to specified level.

Transparency is a useful feature when there is many lines on graph but only rough estmate of value is needed (like looking for trends in history) like here:

![power distribution](http://i.imgur.com/50Xj9D9.png)

**Comment by mkadin** [comment]
+1 to this feature. I like to use it to show this week (opacity of 1) vs. last week (e.g. opacity 0.3)

**Comment by zsbee** [comment]
+1

**Comment by marccardinal** [comment]
+1, it could be implemented via one of the options under "Series specific overrides"

**Comment by kkoch986** [comment]
i know this issue is pretty old, but this is definitely possible now:

![image](https://user-images.githubusercontent.com/1666071/119594085-20a8fb00-bda9-11eb-9b9a-dff6b2be281d.png)

![image](https://user-images.githubusercontent.com/1666071/119594129-33233480-bda9-11eb-88fc-626e701f384d.png)

![image](https://user-images.githubusercontent.com/1666071/119594212-53eb8a00-bda9-11eb-86a0-4a400f94201c.png)

**Comment by XANi** [comment]
Yup, you're right.
