### ISSUE TITLE
[BUG] SingleStat Error Show Value

### ISSUE THREAD

**Issue by Diegonarducci88** [grafana/grafana#9482]
Please include this information:
- What Grafana version are you using?
4.5.2
- What datasource are you using?
Zabbix
- What OS are you running grafana on?
Centos 7

Hello, I wanted to understand why some items in zabbix only return 0 or 1. I select the option "current" and it is sampled values ​​broken in decimal, eg: 0.3, 0.50, 0.58, this is a bug, because in no time the zabbix returned these values.
![bug](https://user-images.githubusercontent.com/11810798/31389283-ed8fb260-ada6-11e7-9a9e-4a2c4ce32425.png)

**Comment by daniellee** [comment]
Can you show the raw response from the query? If you are using a recent version of Grafana then you can use the [query inspector](https://community.grafana.com/t/using-grafanas-query-inspector-to-troubleshoot-issues/2630) on the Metrics tab otherwise you can examine the response with [Chrome Dev Tools](https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50/2)

**Comment by Diegonarducci88** [comment]
I use zabbix, I use zabbix_get to return the raw zabbix returns, for example, in the first command an item returns 0, next collection it goes to 1, grafana in singleStat goes to 0.4, deplois 0,7 and only after changes to 1, I put the option "current", I noticed that when I put a low value in the time range, for example 5 minutes, this does not happen, the value changes from 0 to 1 and this error only happens in singleStat, I already saw other people reporting this problem in groups on the telegram.

**Comment by torkelo** [comment]
Can you include the raw response form Zabbix?

**Comment by torkelo** [comment]
This is 99% likley a zabbix query issue, maybe some averaging  or aggregation that is going on in the Zabbix query logic
