### ISSUE TITLE
[MYSQL] Cant use mysql datasource (old password authentication)

### ISSUE THREAD

**Issue by drix1994** [grafana/grafana#9507]
Hello,

I'm just starting work with grafana. I started Grafana 4.5.2 on RedHat7. I configured grafana.ini. I started server and went to configure data sources. When I'm trying to add mysql data source I'm getting warning:

> this user requires old password authentication. If you still want to use it, please add allowOldPasswords=1' to your DSN. See also https://github.com/go-sql-driver/mysql/wiki/old_passwords

I defined:
Host: xxx.xxx.xxx.xxx:3306
Database: example_name
User: user
Password: password

 I read about this warning and I don't know where can I add option "allowOldPasswords=1"?
Will be greate if someone tell me, what i must do.
Best greetings

**Comment by torkelo** [comment]
what version of MySQL are you using?

**Comment by drix1994** [comment]
It's very old... 5.0.77

**Comment by torkelo** [comment]
that explains it. Any change you can upgrade?

**Comment by drix1994** [comment]
I know that. Probably I will can't change anything in configuration of mysql. 
Is any solution for thar problem?

**Comment by drix1994** [comment]
any help?

**Comment by daniellee** [comment]
@drix1994 To get this to work, it would need to be added as an option in the MySQL data source. I'm not sure we want to want to expose this option - it seems insecure and an edge case that affects very few people. It has been deprecated since 2004 - that's 13 years ago. Maybe it is time to upgrade to the new password format?

If you really want this feature then you can fork Grafana and add it yourself.

**Comment by drix1994** [comment]
I know that, but I work in corpo, so my capabilities for upgrade are small. So as I wrote, i changed variable, generated new password and its work.
