### ISSUE TITLE
[Feature Request] Support Multiplexing of Proxied Datasource Queries

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#9530]
Grafana dashboards with high information density (i.e. lots of small panels) can be slow to load since only ~6 panels can be loading at a time. This is because of two main current limitations:

1. Grafana does not allow for a single datasource query to map to multiple panels
2. With HTTP/1.1, browsers only allow [about 6 simultaneous queries to a single domain](https://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser) so we end up with head of line blocking. See [Why is HTTP/2 multiplexed](https://http2.github.io/faq/#why-is-http2-multiplexed)

To get a feel for this, the [Golang http2 Gophertiles demo](https://http2.golang.org/gophertiles) can give a good feeling of loading lots of "tiles", which are analogous to panels, with a higher latency -- what you might get from more expensive time series queries. 

The query-per-panel limitation will also often not fit database performance characteristics for certain types of dense dashboards. Consider the following dashboards from Opserver and trying to recreate them in Grafana:

Host Overview:
![screen shot 2017-10-15 at 9 32 07 am](https://user-images.githubusercontent.com/1692624/31585189-d3ad6d54-b18b-11e7-8faf-e1f0404dd62a.png)

Switch Interfaces:
![screen shot 2017-10-15 at 9 35 56 am](https://user-images.githubusercontent.com/1692624/31585217-4ef63b80-b18c-11e7-9c67-9681b63079cc.png)

In any datasource where for example CPU, Memory, Network are stored together, multiple panels would share a scan/index like query ("get cpu for all hosts") and having say 50-100 individual queries won't perform well.

In particular with the new grid engine (mentioned [here by torkel](https://community.grafana.com/t/table-panel-span-multiple-rows/2945)) I expect people will try to create more of these sorts of dashboards and run into these performance problems with real world latency against TSDBs.

A waterfall Network load from Chrome illustrated this well. The gray bars are time that panels have not actually started, "stalled", because they are waiting for other panels to load first:

![screen shot 2017-10-15 at 9 46 30 am](https://user-images.githubusercontent.com/1692624/31585322-d9abe2d8-b18d-11e7-9f70-730c62a1e20a.png)

**Comment by HactarofDoom** [comment]
I am having this exact problem in one of our applications and would like to add a bit of information.

As you mentioned only 6 query's go out at a time which is one of the problems, most likely the biggest of them. However looking at the Wireshark trace i see another problem occur when the answers come in. This is roughly how every site refresh pans out:

- 6 requests are sent out and acknowledged within less than 0.5s by the server.
- Some milliseconds later the first, and only the first query gets an answer by the server side application.
- This is directly followed by the request for query seven.
- About two seconds later the answer for query three (yes, query two comes about 8sec. down the line) is sent directly followed by the answer. So 2sec. of nothing before query two gets an ok and an answer.
- This is then followed by another cycle of 2sec.+ delays.

All in all our dashboard with 92 SingleStat panels takes a full 2min+ to load. Since the update frequency for this dashboard should be below a minute (30sec. to start with) one can see this is a problem. What one cannot directly see is what the auto refresh does if the initial query is still running. From what i could gather the auto refresh polls the whole dashboard again (via the same slow initial 6 and then one at a time method) with the initial query still running causing the dashboard to lock up even more.

So the problem is twofold, first the HTTP/1.1 query method is very slow indeed for more than a few data-points and second the auto refresh feature does not take into account that a query is already running and amplifies the problem even more.
Is there a current way to go around this limitation and if so how would one go about implementing it?

Currently running Grafana 4.5.2 with a proxy access Graphite 0.9-12 datasource.

**Comment by aocenas** [comment]
@kylebrandt I would expect with `~~dashboard~~` type datasource we now can reuse single query in multiple panels so I assume this can be closed?
