### ISSUE TITLE
Tracing: Group span by dashboard

### ISSUE THREAD

**Issue by ledor473** [grafana/grafana#9532]
Please include this information:
- What Grafana version are you using?
4.6.0 beta1
- What datasource are you using?
Prometheus/Elasticsearch/Cloudwatch/OpenTSDB
- What OS are you running grafana on?
Running it in Dockr
- What did you do?
I tried the new tracing feature
- What was the expected result?
See all the call generated by a dashboard grouped together in Jaeger
- What happened instead?
I can see all the calls in Jaeger, but they are not grouped together 
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
Probably not needed

First, I’m very excited to see the new distributed tracing feature that was included in 4.6.0 !
I feel that the initial implememtation is very great and this is clearly just an enhancement on top of it.

My understanding is that the multiplecalls are not grouped/batched by the UI which makes it harder for the backend to represent that in Jaeger.
We could probably start the traces from the UI to make it easier to group them!

Let me know if you have any idea on how that could be implemented. I might try to send a PR if I find some time!

**Comment by bergquist** [comment]
We talked about that internally but gave up due to the browser not being able to create new spans. It might be possible to force the Grafana back end to create a new span for the browser but it felt like a hacky solution. Any other idea of how we could include tie the whole dashboard loading into one span?

**Comment by ledor473** [comment]
At first, I was looking at [opentracing-javascript](https://github.com/opentracing/opentracing-javascript/), but then [jaeger-client-javascript](https://github.com/jaegertracing/jaeger-client-javascript) made me realize why you're saying the browser cannot start a span...

Still, I think it would make sense to support proxying trace information via Grafana just like it proxies request to Datasource.
Currently, most of our users that can access Grafana could access the Jaeger, but I dont think it will always be the case.

Here's the 2 options I'm thinking about:
- `/dashboard/db/<slug>` could start a span, return the context as a response header and every subsequent request would just use that context as the parent span.
  - Problem would be that every refresh after that would still be part of the same span so its probably not a very good idea
- A call would be made (just like `/api/annotations`) to create a new span context using a new API (maybe something like `/api/traces`)
  - That API would be call for each refresh

It does feel it's a bit hacky, but maybe its not that bad as its already proxying a lot of stuff

**Comment by ledor473** [comment]
After digging a bit more, I found the following:
https://github.com/jaegertracing/jaeger/blob/master/examples/hotrod/services/frontend/web_assets/index.html#L71-L77

So as a first step, we could probably pass the dashboard `slug` and maybe some more information from the UI by passing the `jaeger-baggage` headers!

**Comment by bergquist** [comment]
@ledor473 sounds like a good idea :) wanna submit a PR?

**Comment by bergquist** [comment]
ping @Dieterbe

**Comment by Dieterbe** [comment]
what do you guys mean by grouping spans? via the inheritance model all spans that correspond to the same request should already be bundled together in the same trace the jaeger UI, since they share the same trace id. is this not the case?
do you mean being able to search/filter by dashboard, in the jaeger UI?

the thing to watch out for with baggage is that it gets propagated throughout the entire chain. (e.g. it will make its way into all the contexts used by the datasource - in metrictank's case, that will propagate to all cluster nodes - and it will be included in all emitted spans.
It would be nicer I think to just set the dashboard property in the root span emitted by grafana, and not propagate it from there. that way we can still seach/filter by it.

**Comment by bergquist** [comment]
Perhaps a simpler solution would be for the browser to add header parameters for all datasource requests. Then add them as jaeger tags in the datasource proxy https://github.com/grafana/grafana/blob/master/pkg/api/pluginproxy/ds_proxy.go#L88

**Comment by ledor473** [comment]
@Dieterbe So here's a screenshot of what I saw when testing it https://imgur.com/a/JKdY2

This feature request was really about grouping. By that, I might that it would be nice if all `/datasources/proxy` would be shown under the `/dashboard/`.
Right now, these are all different trace. But I feel they should really be span under a `Dashboard load` level trace

The bagage work could be a separate feature request. It was about adding the dashboard slug (or any information that's available in the UI) as a bagage so you can filter on that.

It's probably easier to add the dashboard slug as a bagage, which is why I discussed it. Also, it would be probably make the tracing feature a bit more useful than it currently is (you could filter by Dashboard, know which Dashboard generated a slow query or something like that) but it does not fix the real issue that was about grouping them together.

**Comment by Dieterbe** [comment]
again, you do not need to add it as baggage to be able to filter on it or to know which dashboard generated a slow query. adding it as a tag allows that also.

i don't think all data requests should show up under a dashboard load. they are different requests with different lifecycles. when the dashboard is loaded, it will then load the data for all its panels as separate requests, and you may have refresh on (or manually refresh) triggering more requests that have nothing to do with the dashboard load.

**Comment by Dieterbe** [comment]
when you say "should be under a user has loaded the dashboard trace",
I think you mean it should have a parent span displayed as "a user has loaded the dashboard trace".
but that's not what spans are for. spans mark a transaction that takes time. you're talking about a piece of info that seems like it should simply be a tag so that you can search on it.

**Comment by ledor473** [comment]
Here's the diagram of what I **think** we should strive to see when a user loads the dashboard (single *trace* with 6 *spans*)
```
––|–––––––|–––––––|–––––––|–––––––|–––––––|–––––––|–––––––|–> time

 [Span A···············································]
   [Span B······]
                 [Span C···········]
                 [Span D···]
                 [Span E······]
                 [Span F·······························]
```
Where:
Span A == Complete load time of the dashboard for the user
Span B == Call to `/dashboard/db/<slug>`
Span C & E & F == Call to `/api/datasources`
Span D == Call to `/api/annotations`

As of now, that would yield 6 different *traces*

What if a user click on the refresh / the dashboard is on auto-refresh?
I dont think it really change anything... we would start a new trace for everything that's related to the proper refresh action (click on the button or auto-refresh)

**Comment by ledor473** [comment]
I mean it would still be nice to have that but it's been some time...

**Comment by mdvictor** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. We're trying to limit open GitHub issues in order to better track planned work and features.
This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.
Thank you for taking the time to create this issue!
