### ISSUE TITLE
[Feature request] Add Spread Option to Legend (Max - Min)

### ISSUE THREAD

**Issue by giantjunkbox** [grafana/grafana#9598]
The current Min/Max/Avg/Current/Total values that can be displayed on the legend and are great; however it is difficult to locate series that have a lot of activity in stack graphs with a large numbers of series.

It would be helpful to have an additional option, spread, that shows the difference between the Min and Max values - like the SPREAD function in InfluxDB: https://docs.influxdata.com/influxdb/v1.3/query_language/functions/#spread

This can be faked by just adding a grid next to the graph with the spread, but clicking on the other graph does not do anything useful and it takes up a lot of screen real estate.

As an example, a stack graph with with around 150 series:
![spread](https://user-images.githubusercontent.com/17022073/31795062-496e5e54-b4d9-11e7-8573-38daffc40b88.png)

Thank you for the outstanding product!

Grafana v4.5.2
Influx v1.3.5
Red Hat Enterprise Linux 7.3

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand\/interest.

Thank you to you for taking the time to create this issue!
