### ISSUE TITLE
grafana alerting is total bullshit

### ISSUE THREAD

**Issue by celesteking** [grafana/grafana#96583]
Look, I don't know what happened @ your team and why you've chosen to implement it that way, but it sucks big time. 
I'm not going to go into details, I'm not spending any more time on this. You've gotta find SRE/ops/sysadmin people and ask them what they think about what you've coded. It's plain simple - just ask your damn target audience, and that's it.

It's 2025 guys. Nagios has been there for how long, 25 years? Zabbix, Zenoss, PRTG for 20? Just copy what they've got, it's easy, productive, it leads to results. 

![Image](https://github.com/user-attachments/assets/7e185683-4991-48a5-ad0e-f2cc2fbe1cb0)

How is this even usable, why did it ever land in production? How am I, a sysadmin, supposed to understand what is firing and how bad it is? I'm not going to press any extra buttons switches toggles, I need an overview at a glance of what is happening right now, stat, without additional actions.

Just look at this 20 years old Nagios dashboard.

![Image](https://github.com/user-attachments/assets/692e0ee4-2a75-462c-88de-da00b54eec85)

It's clear as day. You can see what hosts have bad services, you can see the services, you can goddamn see the SEVERITY of the alerts.  You can filter out OK alerts and get a list of what is currently in bad shape. You can't filter much there, that's why over here we DON'T use the software from 2004 and use Zenoss. Take a look at our current zenoss events list:

![Image](https://github.com/user-attachments/assets/dfcc9efb-f031-478e-a549-db0c44f5ae2b)

CLEAR AS DAY. You see the severity (icon), the host (essentially, the most and foremost important data), the reason for the alert, time, for how long it's been active. It's currently sorted by age, with newer alerts at the top. You can sort by any column there. It's essentially a highly configurable sortable table. Those are just columns that *I* need, you can configure the displayed columns (~30 various event params) and their order. You can filter by pressing on column headings and checking necessary boxes, you can filter out by writing your expression in column heading input fields just below the table head row, depending on what you want to filter on. You can acknowledge the alert by pressing a button. Just like that, 1 click and you're done, it will show ack'ed right there in the table and everyone in the team will know it's being taken care of. Just 1 click. You can enable event coloring in which case it will color the background differently depending on the SEVERITY of the alert. It's now switched off because I don't like a messy table.

I mean, just give me the goddamn table. Why on Earth would you code your monster above that's absolutely unusable?

We're trying to switch from Zenoss but as far as I see this grafana alerting stuff is a children's toy in comparison.

**Comment by Max-E-Million** [comment]
Although this might have been a better post for /r/grafana, I completely agree.

I love Grafana. Me and my team are using it to monitor a few IBM mainframe systems.
It's super niche, so what's out there from contenders like Nagios, Datadog, etc. is just not that great.
Nothing there comes close to the simple set-up, the overall fantastic UI/UX design, etc.

The alerting however? Can't recommend it at all. No idea what they were thinking.
Everytime I have to adjust, create or even simply look at alerting dashboards/rules I feel like a complete idiot because it's been 3 weeks since I last had anything to do with this and it feels like I'm seeing this for the first time. It's just not very intuitive.

I've also had times when:
- Alerting was firing and sending out mails when it shouldn't have
- Alerting was firing for valid reasons but no mails were sent out
- Alerting wasn't firing at all, even though tresholds had been reached

Imagine an alert waking up your on-call guy at 3 a.m., forcing him to log on, only for him to find out everything's fine and the alert that was sent out was a false-positive.
I simply can't have that in a business environment, so we're using something else to handle the alerting.

As long as there's not a complete overhaul in terms of usability and reliability I'm not touching Grafana Alerting with a 10ft pole.

**Comment by gillesdemey** [comment]
Hi! Thanks for the write-up, we love hearing from our users and welcome any and all feedback, positive and negative alike.

Firstly, we have a [code of conduct](https://github.com/grafana/grafana/blob/main/CODE_OF_CONDUCT.md) to ensure everyone in our community and our staff are treated respectfully and we ask everyone to follow it, software is built first and foremost by humans. 

Secondly, we will dig into this and discuss this with the team like we do with any other GitHub issue.

In the meantime we will close and lock this issue since we feel like there is no room here for having a constructive conversation. If anyone has additional or similar thoughts and opinions feel free to open new GitHub issues with a concise explanation of what you are trying to do and how Grafana fails to meet expectations.

**Comment by RichiH** [comment]
Hi @celesteking 

Alongside the (lack of) config-in-git, alerting is one of my longer-standing frustrations in Grafana. In particular because I have built something like https://github.com/RichiH/tactical_dashboard/blob/master/tac.png twice in my life before Grafana.

I do understand your frustration. It's something that impacts you, directly, as a human. Bad feeling, I know.

It can sometimes be easy to forget that there's humans on the other side of the computer screen as well. Calling the work of others names also impacts them, directly, as a human. Bad feeling, you know.

Your technical points have merit and we're working towards some of them already. It would be great if your behavior matched your technical expertise.

We'd be happy to welcome you again in the future in a more positive manner.

Best,
Richard
