### ISSUE TITLE
[feature request]: label and title with Mathematical Expression Using LaTeX

### ISSUE THREAD

**Issue by gwuillou** [grafana/grafana#9670]
All is in the title. Is there a easy way to add this feature or is it to complicated to implement? For example, Matlab do that for its figures:
![g6ttp](https://user-images.githubusercontent.com/20662503/32038739-9a277ab8-ba2b-11e7-9394-c6954db83e00.png)

**Comment by daniellee** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. Were trying to limit open GitHub issues in order to better track planned work and features.

This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand\/interest.

Thank you to you for taking the time to create this issue!
