### ISSUE TITLE
Support for cassandra data source. 

### ISSUE THREAD

**Issue by jrespeto** [grafana/grafana#9683]
Some of our projects are having databases with cassandra.
Can you add cassandra as a data sources for Grafana?

https://github.com/gocql/gocql

**Comment by bergquist** [comment]
This have to wait until we support backend plugins

https://github.com/grafana/grafana/issues/6841

**Comment by HadesArchitect** [comment]
Hi there, glad to announce 'work-in-progress' for the grafana-cassandra-datasource as grafana plugin, PR should be ready in the upcoming weeks. 

https://github.com/HadesArchitect/grafana-cassandra-source

**Comment by daniellee** [comment]
Thank you for submitting this feature request. However, due to inactivity and/or lack of upvotes, we’re going to close this for now. This does not mean that we are closing it forever. 

There is a Cassandra data source plugin but feel free to comment on this issue to clarify why this is needed and upvote it.

**Comment by jeromatron** [comment]
It looks like the grafana-cassandra-source from @HadesArchitect is consistently getting updated.  What would be the criteria to accept that?

**Comment by HadesArchitect** [comment]
Thanks @jeromatron The datasource is ready for the 1.0.0 release so I've create an official request to add it to the datasources: https://github.com/grafana/grafana-plugin-repository/pull/862
