### ISSUE TITLE
Update official internal Grafana dashboard to use new Prometheus metrics

### ISSUE THREAD

**Issue by mattbostock** [grafana/grafana#9704]
- What Grafana version are you using?

4.6.0

- What datasource are you using?

Prometheus

* * *

Grafana 4.6.0 exposes Prometheus metrics via #9187 but the [official Grafana internal dashboard](https://grafana.com/dashboards/55) was last updated a year ago.

It should be updated to use the Prometheus metrics.

**Comment by bergquist** [comment]
Datasources -> Click on one of your Prometheus datasources -> Dashboard tab -> Import :)

This should be documented better.

**Comment by alexandrul** [comment]
@bergquist This seems to be about the Grafana metrics, not the Prometheus ones.

**Comment by mattbostock** [comment]
Yes, this is regarding Grafana metrics that are exposed in the Prometheus format :-)

**Comment by bergquist** [comment]
The Graphite version of internal metrics also needs to be updated.

**Comment by bergquist** [comment]
Since 4.6.0 we provide a Prometheus and Grafana dashboard in that tab. 

I've also added info about this in the docs. Not sure how we could highlight this in more places.

https://github.com/grafana/grafana/commit/beb203209b6d7b2236995434ddcd47f346d27ab8
https://github.com/grafana/grafana/commit/d23c77119e39e5b36d250a5f9feb42288e300843

Unless you have other suggestions I think we can close this issue.

**Comment by mattbostock** [comment]
Thanks @bergquist. It might be worth adding a note to the [official Grafana internal dashboard](https://grafana.com/dashboards/55) to point new users in the right direction, assuming that that dashboard no longer works with 4.6+?

Otherwise I agree that this can be closed.
