### ISSUE TITLE
[Bug] Singlestat color does not disappear when there are no datapoints

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#9747]
Please include this information:
- What Grafana version are you using? -  Grafana v4.7.0-pre1 (commit: e91b00c)
- What datasource are you using? - Cloudwatch
- What OS are you running grafana on? - MacOS
- What did you do? - Set thresholds for colors on singlestat.
- What was the expected result? - For no datapoints, singlestat should have no color.
- What happened instead? - It works as expected when there are datapoints but if there are no datapoints after a while of having datapoints, the color does not disappear when there are no datapoints. It remains what it was in its last state.

**Comment by Angrite** [comment]
I want to confirm this bug, in Grafana 4.6.2, browser - Chrome.  If no datapoints,  singlestat does not reset the background color during auto-refresh. If you refresh the page manually (CTRL+F5), background is reverted to default (black).

**Comment by Angrite** [comment]
Additional info: Grafana 4.3.2 is not affected by this bug.

**Comment by Angrite** [comment]
The problem is [here](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/module.ts#L609) 

It has been introduced during https://github.com/grafana/grafana/pull/9469 fix: Fix NaN handling https://github.com/grafana/grafana/pull/9469/commits/697418676f75d55a626aa160a58a658c97e50498 
The puprose was to _prevent singlestat from coloring of null/NaN values ?_

If code 

`if (panel.colorBackground) {`

is changed back to

`if (panel.colorBackground && !isNaN(data.value))`,

singlestat background color disappears when there are no datapoints, as before.

I didn't tested yet, how my fix (adding back `&& !isNaN(data.value)`) correlates with the rest part of the https://github.com/grafana/grafana/pull/9469/commits/697418676f75d55a626aa160a58a658c97e50498
