### ISSUE TITLE
[Bug] Escaped character adds column when exporting to CSV

### ISSUE THREAD

**Issue by jwilles** [grafana/grafana#9748]
- What Grafana version are you using?
4.5.2
- What datasource are you using?
MySQL
- What OS are you running grafana on?
Centos
- What did you do?
Exported table as CSV with escaped characters (ex. &amp;) and resulting document had extra columns due to semicolon delimiting.
- What was the expected result?
Export CSV with correct columns
- What happened instead?
Exported CSV had extra columns

**Comment by adolci** [comment]
Why this solution could not be possible? #8518
You should also add double quote characters " as string delimiters:
public/app/core/utils/file_export.ts
```
export function exportTableDataToCsv(table) {
    var text = '';
    // add header
    _.each(table.columns, function(column) {
-        text += (column.title || column.text) + ';';
+       text += '"' + _.unescape(column.title || column.text) + '";';
    });
    text += '\n';
    // process data
    _.each(table.rows, function(row) {
        _.each(row, function(value) {
 -           text += value + ';';
+           text += '"' + _.unescape(value) + '";';
        });
        text += '\n';
    });
    saveSaveBlob(text, 'grafana_data_export.csv');
}
```
I don't know how to test this, but this problem is very big, because a lot of extractions will be wrong, not only for escaped characters.

P.S.
How can I test this?
