### ISSUE TITLE
Generic OAuth and user role mapping 

### ISSUE THREAD

**Issue by freman** [grafana/grafana#9766]
It would be super convenient to have Oauth2 be able to pass role/group information as a parameter.

Perhaps this can be mapped dynamically like the ldap option.

EG. Keycloak lets me send the ldap groups with the userinfo, if UserInfo.Group contains Founder then user is Admin

**Comment by lukeplausin** [comment]
+ 1

**Comment by frankiedunn** [comment]
+1

**Comment by volodymyrdoba** [comment]
+1

**Comment by boyand** [comment]
+1

**Comment by javicho21** [comment]
+1

**Comment by roidelapluie** [comment]
Maybe we can use OIDC for this

**Comment by wireless00** [comment]
+1

**Comment by emaimit** [comment]
+1

**Comment by hcbraun** [comment]
+1

**Comment by marcelfischer** [comment]
+1

**Comment by magowant** [comment]
+1

**Comment by setonez** [comment]
+1

**Comment by lsilvatux** [comment]
+1

**Comment by Xyaren** [comment]
+1

**Comment by rommi4** [comment]
Hi!
There is 
![image](https://user-images.githubusercontent.com/7159273/43828327-e10a0ef4-9b04-11e8-9617-2f3afd9d70c6.png)
announced in Enterprise version

Does this mean that we'll never see generic OAuth user mapping for community version?

**Comment by schen1** [comment]
+1

**Comment by lsilvatux** [comment]
+1

**Comment by rjfv** [comment]
+1

**Comment by ronnysha** [comment]
+1

**Comment by dannysauer** [comment]
Advanced Auth shows as available now, rather than coming soon.  Would a patch adding OIDC support (or other external group lookup) be accepted into the community edition, or is this going to be kept as a commercial differentiator?

**Comment by jhohertz** [comment]
Looking for something around this here as well.

**Comment by hypery2k** [comment]
I tried to hack around with a script mapping Keycloak to add the "role" attribute:
```
token.setOtherClaims("role", "Editor");
user.getGroups().forEach(function(group) {
    group.getRealmRoleMappings().forEach(function(role) {
        if (role.getName() === 'admin' ){ 
           token.setOtherClaims("role", "Admin");
        }
    });
});
```

In Grafana log i see the attribute gets through:
```
t=2019-02-07T05:20:41+0100 lvl=dbug msg="HTTP GET https://keycloak/auth/realms/holisticon/protocol/openid-connect/userinfo: 200 OK {\"sub\":\"3227c5de-ab50-4823-ab78-e12eeb07cc7d\",\"email_verified\":true,\"role\":\"Editor\",\"name\":\"Test User\",\"preferred_username\":\"testuser\",\"given_name\":\"Test\",\"family_name\":\"User\",\"email\":\"123@sample.com\"
```
But still the user gets only Viewer role in Grafana. Due to [this entry](https://github.com/grafana/grafana/blob/master/pkg/api/login_oauth.go#L175) I thought an attribute `role` should be mapped from user info, or?

**Comment by Hippolyteb** [comment]
+1

**Comment by jfuechsl** [comment]
@hypery2k Good idea. Unfortunately it seems the role attribute isn't set in https://github.com/grafana/grafana/blob/369aa2d5ddd24e3adb96eb5ead67a4cf549c3da6/pkg/login/social/generic_oauth.go#L210

**Comment by stromnet** [comment]
Very much looks like it can be easily fixed by reading the role string from a configurable field in the token. Would be a very useful addition, with (I guess) quite few lines of code!


> @hypery2k Good idea. Unfortunately it seems the role attribute isn't set in
> 
> [grafana/pkg/login/social/generic_oauth.go](https://github.com/grafana/grafana/blob/369aa2d5ddd24e3adb96eb5ead67a4cf549c3da6/pkg/login/social/generic_oauth.go#L210)
> 
> Line 210 in [369aa2d](/grafana/grafana/commit/369aa2d5ddd24e3adb96eb5ead67a4cf549c3da6)
> 
>  userInfo := &BasicUserInfo{

**Comment by hypery2k** [comment]
I will try to send a PR via my fork: https://github.com/hypery2k/grafana/tree/feature/9766-oauth-roles

**Comment by satyasameer** [comment]
+1

**Comment by hypery2k** [comment]
@torkelo May somebody have a look at my PR?

**Comment by dbeinder** [comment]
Does this also work once the Oauth server updates the role, or is it only used during the initial signup?

**Comment by hypery2k** [comment]
it would also update if OAuth server sends updated role info

**Comment by dbeinder** [comment]
I'd also really like to see this feature merged, @DanCech of Grafana Labs was the last to work on generic oauth, any comment?
But I think you will need to sign the CLA first, there is a bot-comment on the PR.

**Comment by VladPedosyuk** [comment]
@hypery2k thank you for your efforts, I am trying to build Grafana with your commits and as I understood, your changes require to include in **token_id**  _"attributes"_ key which would contain an embedded mapping with _<role_attribute_name>_ key. Is there a way to avoid using this embedded mapping and just pass  _<role_attribute_name>_ key at the same level as, for example, _"preferred_username"_?

And maybe someone tried to integrate Okta to get roles working with the mentioned PR? I faced an issue when Okta's "Token Preview" in the API section shows my custom _"grafana_role"_ claim: I do a request with the same scope set and "Authorization code" grant type - and I got the custom claim included in the response payload. But it seems Grafana makes a different API call because no custom key is included in **token_id** no matter I do with Okta config.

**Comment by pirminjanka** [comment]
+1

**Comment by pirminjanka** [comment]
+1

**Comment by iamvijayaragavan** [comment]
Grafana role mapping is not working for Azure AD user groups. when we set auto_assign_org to true. 

Anyone have idea how to get rectify this.

**Comment by marefr** [comment]
@iamvijayaragavan please refer to https://github.com/grafana/grafana/pull/20300#issuecomment-575732127

**Comment by yesoreyeram** [comment]
@marefr i assume with the fix you provided, we can assign role to the current organizations. If multiple organizations exist, we can't assign different roles. Correct?

**Comment by marefr** [comment]
@yesoreyeram true
