### ISSUE TITLE
Dashboard templating OpenTSDB tag_values doesn't pick up all of the tag_values

### ISSUE THREAD

**Issue by ibdimitrov** [grafana/grafana#9773]
- Grafana 4.2.0 (but also reproducible with 4.6.0)
- OpenTSDB datasource

When having a template variable defined to be fed from tag_values - 
tag_values(prod.oc-registry.components.footer.shared-cache.cache.hit.counter, service)
it fetches the tags from the last 3000 data points. In our case however this metric produces a lot more data points and it leads to picking up not all of the tag values available.

The query that it sends in this case is with limit=3000 parameter and without downsampling:
http://graphana_endpoint_url/api/datasources/proxy/61/api/search/lookup?limit=3000&m=prod.oc-registry.components.footer.shared-cache.cache.hit.counter%7Bservice%3D*%7D

The response is 1MB and it includes only 2 of the service tags we expect to see.

However all of the graphs on the dashboard have set downsampling and for them the tag decomposition works well. As an example I have exactly the same metric with the service tag picked correctly.

The request made in this case is:
http://graphana_endpoint_url/api/datasources/proxy/61/api/query

With the following payload:
`
{"start":1509620946591,"queries":[{"metric":"prod.oc-registry.components.footer.shared-cache.cache.hit.counter","aggregator":"sum","downsample":"30s-avg","filters":[{"filter":"eu-west-1|eu-central-1|ap-southeast-1|ap-northeast-1","groupBy":false,"tagk":"region","type":"literal_or"},{"filter":"*","groupBy":true,"tagk":"service","type":"iwildcard"}]}],"msResolution":false,"globalAnnotations":true,"showQuery":true}
`
The response is 5.9KB and includes all of the service tags we expect

**Comment by torkelo** [comment]
Yes, the metric lookup has a limit of 3000 tag values, can you narrow down the search a bit? 

> The response is 1MB and it includes only 2 of the service tags we expect to see.

What does that 1MB of data contain? a bug in OpenTSDB? Maybe you need to remove old tag values? 

Not sure why you compare the lookup api with the query api.

**Comment by torkelo** [comment]
closed due to duplicate of https://github.com/grafana/grafana/issues/8155

**Comment by i-b-dimitrov** [comment]
With all of the narrowing in place it fails to pick all of the tag values (as I said this is a metric with a lot of data points per second. Additionally it has 6 tags associated with it, which makes the space even bigger).
Here's an example of what we get in the templating compared to what we get in querying (I'm comparing them because I'm getting different results for the tags). Because of the nature of the templating I would expect to be capable of downsampling the results there as well so that I can see all of the tags in this limit of 3000.
Please take a look at the attached zip-file...
[grafana.zip](https://github.com/grafana/grafana/files/1437634/grafana.zip)

**Comment by i-b-dimitrov** [comment]
In response to the lookup API I see only 'travel-api' and 'ums' services, while with the querying I see 'travel-api', 'ums', 'strings-service' and 'culture-service'

**Comment by torkelo** [comment]
OpenTSDB lookup api can be incomplete I think, depending on realtime meta database is up to date.  not sure though, not an OpenTSDB expert

**Comment by i-b-dimitrov** [comment]
Yes, the metadata is up to date - we fixed that a while ago.

And I'm not complaining about the limit of 3000 in this issue because I'm far from thinking that increasing this limit will fix the issue.
To me the querying in the templating there seems a bit incorrect. It should not fetch the timeseries with some limit (something that the OpenTSDB lookup API does). At least it should have an option for downsampling so to minimise the size of the result. It will be both much more correct and much faster not transferring hundreds of KB.

**Comment by torkelo** [comment]
there is no downsampling option in the lookup api
