### ISSUE TITLE
Graph: Limits on Y auto scale (min max)

### ISSUE THREAD

**Issue by mattdeclaire** [grafana/grafana#979]
I've got a graph displaying error rates, and I've set the axis max to `auto`.  The problem is that on quiet days, with a low error rate, the axis shrinks down to display tiny blips as large mountains.  I could set the max to a particular vaule. But, I don't want to aim to low and experience a graph that goes off the chart. And, I don't want to set the max so high as to not get readable "medium" graphs.  (I don't want to use thresholds, as I've got graphs on the other axis, and I don't want to cause confusion with those ranges.)

An ideal solution would to have a "min-max" setting.  I could set the min-max to 100, and the axis would never get smaller than that.  But, it would grow if need be.

**Comment by kavdragon** [comment]
+1

**Comment by mattttt** [comment]
+1 from a Grafana.net user.

> The minimum scale would help for things like network interfaces, where some of our private / vpn links are idle (~20kb/s) but when in use are 50-100Mb/s. If I set the scale to 100Mb/s and it's over, I don't know and if I set it to 200Mb/s then I can't see data clearly when it's only 5-10Mb/s.

**Comment by thoj** [comment]
I understand that this function is probably only useful for very few people. But I've been hacking on this a bit. And I've come up with something that works for me. The commit in my fork adds a Y-Span box to the Axes tab.

Where X is a integer or float:
```
~X Span X around average
=X Span X around current value
>X Span is atleast X
<X Span is clamped to X
```

https://github.com/thoj/grafana/commit/7dcdccbd42e9f63b7388e439f7194fe7ead8039a

Example of why i need it: 
![y-span](https://cloud.githubusercontent.com/assets/153440/16985695/7ce60908-4e82-11e6-9b8d-60334877008b.PNG)

Any interest in a PR?

**Comment by lpalm** [comment]
@thoj That would be a great addition. We use thresholds for some graphs and would like to always show it, but still scaling the graph to show points much higher than the threshold. ">X" would work well here (and <X for negative thresholds).

**Comment by thoj** [comment]
@lpalm Yeah! I'll add a pull request to try to get the discussion going,

**Comment by torkelo** [comment]
implemented in https://github.com/grafana/grafana/pull/6051

**Comment by bluecmd** [comment]
Is this in the 4.0.x release train? I'm trying to use "<" and ">" in the Y-axis settings but to no avail.

**Comment by torkelo** [comment]
no had to revert it, we wanted a more user friendly input / UI than just hidden feature that the input field supports expressions like `>` and `<` so reverted the feature in wait for time to figure out the UI

**Comment by thoj** [comment]
Could we have this in a dropbox besides Y-min and Y-max?

**Comment by Kvistian** [comment]
Hi, 

I created this feature for graphite project a while back and came to the following conclusion that I would never ever want to use **yMax**, since I always want to know the values of the graph, which I won't with **yMax**.
It there anyone who thinks that **yMax** is a useful function or should **yMax** just be re-designed to work as **minYMax**?

I mean, if I set **yMax** to **x** and the counter exceeds **x** would anyone not want to see how much it exceeded the limit?

**Comment by iksaif** [comment]
I use yMax when I have percentages to make sure that the 100% is always exactly at the top of the graph (even if there is a small blip)

**Comment by thoj** [comment]
I also need yMax. This is due to some noisy signals that have very tall spikes that distort the graphs.

**Comment by Kvistian** [comment]
@iksaif yes, but that shouldn't require yMax to be fixed. Since your graph won't ever exceed `100%` and your dynamic **yMax** then would be `100%` your graph would look exactly the same as with the current implementation of **yMax**?

@thoj that doesn't sound like a reliable metric? Wouldn't you instead want those spikes excluded from the graph or if you care about them actually know the value?

**Comment by iksaif** [comment]
@Kvistian they would, it happens, for reasons, that it displays 100.02%, and I like the fact that I'm able to cap that.

Also there are times when I only want to see when I want to "zoom in" and I can use yMax to do that.

**Comment by Kvistian** [comment]
Ok, but you agree on that most cases would require a dynamic **yMax**? In that case, would it make sense to make the **yMax** dynamic and a new function like **staticYMax** or **fixedYMax** for those edge cases?

**Comment by iksaif** [comment]
Sounds like setting the lower bound of the top of the graph could be useful but I wouldn't change the semantic of the existing yMax (which, really is the maximum y that can be displayed).

Would be interesting to find how this thing is named in other similar software

**Comment by thoj** [comment]
@Kvistian Not everyone wants to use grafana to only display nice clean metrics from servers. I want to display metrics from physical processes that are noisy and can return weird data sometimes. Se my examples and explanations here: https://github.com/grafana/grafana/pull/5720

**Comment by Kvistian** [comment]
@thoj I didn't suggest to remove it if it's a useful feature, I simply questioned if it is. But it seems like there are some use cases for it, so in that case it shouldn't be removed. But personally I feel that there should be more cases where you would like a dynamic **yMax**. When I stumbled up on the problem with graphite I actually assumed that **yMax** would solve my problem (since I couldn't see any useful case for an actual static **yMax**). Ultimately it's just a naming problem at this point.

I don't really care if it's called **yMax** or **minYMax**, just thought that **yMax** feels more like a `default` function that should solve the most common use case.

**Comment by royemmerich** [comment]
I am displaying a battery state of charge (SOC) value and would really love the feature of being able to set an upper (or lower) limit while preserving auto-scaling.

Here are some images of the problem I'm facing by setting or not setting the Y-Max value.

If I **_don't_** set the Y-Max value then the graph shows SOC values > 100% which will never occur.
![screen shot 2017-02-07 at 21 31 01](https://cloud.githubusercontent.com/assets/3904395/22710411/7bddffee-ed7d-11e6-85d0-123211c8793a.png)

If I **_do_** set the Y-Max value then when I have low SOC values for a long time, the graph doesn't auto-scale.
![screen shot 2017-02-07 at 21 29 35](https://cloud.githubusercontent.com/assets/3904395/22710491/cb3a149c-ed7d-11e6-8764-01ca30536422.png)

What I would like is to be able to set an upper limit (100% in this case) but still have the plot auto-scale as it does at the moment when Y-Max isn't set.

**Comment by mikeparker** [comment]
Just adding our use case. We are monitoring a website and have a baseline level of healthchecking traffic for 'working' instances, which I'd like to display as a graphically 'low' graph line (e.g. 0.1 request/sec but the axis would be minimum of 1, whilst still enabling the graph axis to scale upwards when the 'real' traffic arrives.

**Comment by bobrik** [comment]
There's a hack to have a minimal maximum Y axis value.

Create a `Baseline` metric for the minimal scale you want. Here I picked 1s for CPU time:

![image](https://user-images.githubusercontent.com/89186/27094078-cdff51e4-501d-11e7-9725-667efce62114.png)

Add overrides for the baseline metric to make it disappear from the graph:

![image](https://user-images.githubusercontent.com/89186/27094111-e4fb94ca-501d-11e7-9c5c-21046a1ceec3.png)

That's it.

The only drawback is that you can see the baseline of you hover it:

![image](https://user-images.githubusercontent.com/89186/27094166-14907066-501e-11e7-9337-b8fa5e86c388.png)

**Comment by C0rn3j** [comment]
I also need this for IO display.

for example read speed can be 50kb/min or 500MB/min, setting some minimum scale - for example 100MB/min as default would make my graphs way more consistent.

**Comment by dstensnes** [comment]
+1
Please?

**Comment by sometoby** [comment]
@dstensnes Please don't leave comments of this form on GitHub issues. You can add a reaction to the initial post to show you'd like this feature. When you comment +1's, everyone following this issue gets a notification email without any relevant info. It's simply bad form.

**Comment by ssvenn** [comment]
I think most peoples use cases would be covered by adding a "soft limit" checkbox next to the Y-Min and Y-Max fields. If you move Y-Max down to the next row there should be enough space both for the checkbox and the label, and the functionality should be pretty self explanatory :)

**Comment by schmurfy** [comment]
I am not sure how this can be considered an edge case, the main application we have is network traffic but on most graphs you don't want to see tiny values shown as "mountains".

is there currently a workaround to do that ?

**Comment by aveao** [comment]
Any updates to this?

**Comment by davemichels** [comment]
One UI idea would be to have:
* YMax(soft) - Top of graph always extends to at least here
* YMax(hard) - Top of graph never extends beyond here
* YMin(soft) - Bottom of graph always extends to at least here
* YMin(hard) - Bottom of graph never extends beyond here

**Comment by hoerup** [comment]
Another take on this one could be a minimum span for Y-axis defining that the span from current Y-low to Y-high should never be less than the given value. That way the render is free to set where y axis should begin and end - and in the same time avoid minor changes in values to be rendered as mountains.

**Comment by ekutner** [comment]
I too find that this is a very common problem with noisy data and most of the data is noisy. 

I think the real problem is that outlier values skew the scale of the Y axis making everything else disappear. The way I see the right solution is to allow the Y axis range to be dynamic based on the displayed data while trimming extreme outlier values. The best way to do that would be to base the range on standard deviations from the average of the displayed data. For example, if setting 1 standard deviation than anything that is more than 1 standard deviation above the average would be trimmed on the graph. This is both easy to configure, can easily be calculated on the client side so it doesn't depend on the data source and would be reasonably easy for people to understand.

**Comment by nylen** [comment]
From almost 2 years ago:

> reverted the feature in wait for time to figure out the UI

Please bring back `>` and `<` while a better UI is considered.

**Comment by bobrik** [comment]
cc @davkals

**Comment by fjlour** [comment]
I'm desperately waiting for such a feature as the one that was removed 2 years ago!

Even templated charts that monitor the same metric on different systems, side by side give inaccurate visuals as the scales are auto adjusted independently based solely on the current data on the chart.

**Comment by sb3tcs** [comment]
> There's a hack to have a minimal maximum Y axis value.
> 
> Create a `Baseline` metric for the minimal scale you want. Here I picked 1s for CPU time:
> 
> ![image](https://user-images.githubusercontent.com/89186/27094078-cdff51e4-501d-11e7-9725-667efce62114.png)
> 
> Add overrides for the baseline metric to make it disappear from the graph:
> 
> ![image](https://user-images.githubusercontent.com/89186/27094111-e4fb94ca-501d-11e7-9c5c-21046a1ceec3.png)
> 
> That's it.
> 
> The only drawback is that you can see the baseline of you hover it:
> 
> ![image](https://user-images.githubusercontent.com/89186/27094166-14907066-501e-11e7-9337-b8fa5e86c388.png)

For those who read @bobrik's helpful work-around, these days you may also hide the `baseline` item from tooltips in the override as well.
![image](https://user-images.githubusercontent.com/45599185/52421789-66e3ce80-2aba-11e9-92be-01e2bf70c100.png)

**Comment by peci1** [comment]
@bobrik @sb3tcs Hi, I'd like to use your workaround, but Grafana ends up with a query syntax error if all I put into the query is just `20` or some other number. How to create the baseline metric? Or is my Grafana 5.1 too old to support this kind of query?

**Comment by Elfe** [comment]
I used some chained functions on a second query to prevent the graphs from zooming in to much on the y-axis.
In this example I graph logged in users from multiple servers in one graph.

I added an additional query with the same data points:
offset(-20) aggregateBy(1m,min) removeBelowValue(0) setAlias(hidden_min)

This changes the dynamic zoom from
min up to max
to
min-20 (while not going into negatives) up to max

To hide the fake graph:
visualization override with regex "/hidden_.*/"
Lines:false
Legend:false
Hide in tooltip:true

You could probably even sync the y-axis between multiple graphs. Like a panel per server and gather min/max from data points of all the servers in each panel.

**Comment by nikilase** [comment]
I found another workaround. I just added a min and max timeseries with the min and max tag. The line was like this
`weather,sensorID=min temperature=0`
`weather,sensorID=max temperature=20`
Those get added to the graph and hidden like mentioned above. Only issue is that you need to inject it on a regular basis.
Here is how it looks, may need to set max temperature to 19 so it auto adjusts the axis to 20.

<img width="449" alt="Unbenannt" src="https://user-images.githubusercontent.com/38077998/78165196-40fe5380-744b-11ea-9235-83c876f63267.png">

**Comment by JumpOnCloud** [comment]
I stumbled upon this thread looking for a solution to setting a flexible y-max in Grafana.  For my use case, I am graphing request latency and volume for an API.  I want to set a flexible y-max to about 500 ms (.5 seconds), so that I can better see the nuance to the lower-latency calls by excluding spiky outliers and auto adjusting the y-max when the maximum latency is below that threshold.

I tried setting:  y-min to 0 and y-max to <.5, but then my y-axis either disappears entirely or ignores the y-min.  This problem happened regardless of graphing the latency and request volume queries together/separately.  Has there been any new progress on this issue?  It would be really beneficial to my team.

I'm including a few screenshots of my graph with y-max configured differently (each case labelled by graph title)
<img width="718" alt="Screen Shot 2020-05-27 at 2 44 03 PM" src="https://user-images.githubusercontent.com/31859387/83060003-cad03480-a028-11ea-8293-c53de99722aa.png">
<img width="721" alt="Screen Shot 2020-05-27 at 2 42 56 PM" src="https://user-images.githubusercontent.com/31859387/83060014-cd328e80-a028-11ea-937f-24dd263733e8.png">
<img width="722" alt="Screen Shot 2020-05-27 at 2 42 19 PM" src="https://user-images.githubusercontent.com/31859387/83060019-cdcb2500-a028-11ea-98d7-993182323f04.png">
<img width="718" alt="Screen Shot 2020-05-27 at 2 41 39 PM" src="https://user-images.githubusercontent.com/31859387/83060022-ce63bb80-a028-11ea-92ad-444207abee85.png">

**Comment by Elfe** [comment]
if you don't want to graph values above 500ms you could try to use removeAboveValue(0.5)
then tell the graph how the null values should be handled

no clue if there is a way to use calculated parameters for this function

**Comment by gsuberland** [comment]
A slightly more up-to-date baseline workaround is as follows:

![image](https://user-images.githubusercontent.com/6430604/90838714-7ac5ed00-e34d-11ea-827f-48946f2628b8.png)

This stops the baseline query appearing in the graph and legend, and prevents it from causing issues with stacking.

**Comment by osks** [comment]
This is not an really an edge case, but rather a very common case. I actually think it's very often that one wants an y-axis with "soft" min/max values. The main reason for setting the y-axis scale is that one want to align it with expected data range, and also to have multiple graphs with aligned y-axis so one can easily compare values.

> Would be interesting to find how this thing is named in other similar software

Highchartjs calls it softMin/softMax.
https://api.highcharts.com/highcharts/yAxis

AnyChart calls it soft min/max.
https://docs.anychart.com/Axes_and_Grids/Scales#soft

Chartjs has "suggestedMin/Max" option for handling this use-case.
https://www.chartjs.org/docs/latest/axes/cartesian/linear.html#axis-range-settings

amCharts calls them min/max and strictMin/Max.
https://www.amcharts.com/docs/v4/reference/valueaxis/#strictMinMax_property

RRDtool for example has "soft" limits by default when one uses autoscale, but has an option called `rigid` that forces "hard" limits on the scale.
> [-u|--upper-limit value] [-l|--lower-limit value] [-r|--rigid] [--allow-shrink]
> 
> By default the graph will be autoscaling so that it will adjust the y-axis to the range of the data. You can change this behavior by explicitly setting the limits. The displayed y-axis will then range at least from lower-limit to upper-limit. Autoscaling will still permit those boundaries to be stretched unless the rigid option is set. allow-shrink alters behavior of rigid by allowing auto down scale, graph will not overrun user specified limits.
https://oss.oetiker.ch/rrdtool/doc/rrdgraph.en.html

**Comment by gsuberland** [comment]
I think it may also be useful to consider implementing a "minimum y-axis range" feature as part of this, distinct from the "soft" min/max. The soft minimums and maximums would be used to specify fixed positions on the y-axis which must always be visible during auto-scaling. This can be used when you've got a known range of y-axis values that you always want to have visible, which is useful for preventing small variances appearing as exaggerated peaks and troughs due to the zooming effect of auto-scaling. However, this only works if you know what those y-axis values are going to be at design time, which isn't always the case, especially for people building templates for use by end-users who might have different hardware and load patterns.

A minimum y-axis range option for auto scaling would remove this requirement. When used on a set of values where the range of the data (i.e. `abs(max(Y)-min(Y))`) does not exceed the configured minimum y-axis range, the minimum and maximum values on the y-axis would be set such that the data is centered vertically. This avoids the issue of exaggerating small variances, without the graph designer needing to know the exact y-axis values ahead of time.

Quick bit of pseudocode to demonstrate the calculation:

```
minRange = 25
dataRange = abs(max(Y)-min(Y))
if dataRange < minRange:
    yAxisExtension = (minRange - dataRange) / 2
    yAxisMin = min(Y) - yAxisExtension
    yAxisMax = max(Y) + yAxisExtension
```

This approach will not push outliers off the scale, like centering about the mean would.

As an example use-case, imagine you're designing a dashboard for monitoring data from [NUT](https://networkupstools.org/)/upsd, and you're putting together the power usage graph. While my UPS might average 400W, someone else's might average 100W or 1000W, depending on what their hardware setup looks like. It isn't possible to know this ahead of time. The amount of power drawn is usually fairly constant over a short time scale, though, meaning that it is prone to y-axis exaggeration when autoscaling is performed. This is a perfect use-case for a minimum y-axis range, where you can make reasonable assumptions about the scale of the variance over a given time period, but not the magnitude of the absolute value.

**Comment by rohoog** [comment]
If a sensor has limited resolution, all you see is the quantization noise when the quantity varies very little in the selected time span. I would like to see a minimum y-span for instance to not amplify this quantization noise too much in the graph.
In the case of little y-value span in both left and right y-axes, it would be nice to 'nudge' the center of the one y-axis towards the upper half and the center of the other y-axis towards the lower half. The will suppress unnecessary left/right Y-value intersections. Of course if both Y-axes show the same quantity, the axes should not be nudged like that, but there is already the 'synchronze y-axes' option.

**Comment by acortelyou** [comment]
> no had to revert it, we wanted a more user friendly input / UI than just hidden feature that the input field supports expressions like `>` and `<` so reverted the feature in wait for time to figure out the UI

four years later, still figuring out that ui @torkelo ?

**Comment by torkelo** [comment]
yepp, that is the problem. We are working on a new graph panel and it the underlying component can do this, just need to figure out how to expose it

**Comment by acortelyou** [comment]
@torkelo would you accept a PR to reinstate the "hidden feature" until you've had a few more years to work on the new ui that implements it?

Per @osks 's research and the 100+ requests, this is an industry-standard basic feature not a "little edge case".

Additionally, the previous hacky workaround no longer works so we're back out in the cold over this. 😢

**Comment by torkelo** [comment]
Yea , sure if done for the new time series panel / UPlot component

**Comment by leeoniya** [comment]
@acortelyou look at the softMin/softMax demo [1] and the typings comments [2]. if you need additional clarification on the chart side of things, feel free to open an issue in the uPlot repo.

[1] https://leeoniya.github.io/uPlot/demos/soft-minmax.html
[2] https://github.com/leeoniya/uPlot/blob/e870fc16cef352fb283a050957ec08374e21a47f/dist/uPlot.d.ts#L109-L110

**Comment by leeoniya** [comment]
we might be able to squeak this into 7.4 (#30238)

**Comment by acortelyou** [comment]
I am not a fan of the UI as described in #30238, as it applies to both the max and the min unilaterally.

eg, there's a very real use case for setting the min to exactly 0 and soft clamping the max to 100.

This sort of feature is very easy to succinctly describe as a text expression in the min and max fields and very difficult to translate into a UI.

**Comment by leeoniya** [comment]
> eg, there's a very real use case for setting the min to exactly 0 and soft clamping the max to 100.

can you describe the specifics in more detail?

the implication being that you'd have negative values but still want to clamp min to 0 and anything below 0 gets clipped by the chart edge?

softMax of 100 and softMin of 0 would work fine unless you were specifically looking for the above case. however, if you dont want to render negative values it may be possible to just us a transform to preprocess the data and clamp negatives to nulls or 0s.

**Comment by abursavich** [comment]
The "softness" or "hardness" of the min and max should be independently controllable.

**Comment by thoj** [comment]
It's very useful to clamp both max and min combined with soft max and softmin. Specifically to hide noise. If you get some impulse In the data that competly hides the real data until the impulse is gone from the data.

See my example from 4 years ago: https://cloud.githubusercontent.com/assets/153440/16985695/7ce60908-4e82-11e6-9b8d-60334877008b.PNG

Please please don't fall into the trap of trying to make this too simple. For true data trending you need both soft limits and clamping!  4 years ago I had to write my soultution because of this issue that I tried to fix in grafana 😑

**Comment by leeoniya** [comment]
@thoj do you happen to have the datasets for those graphs so i can play around with a few variants. i see there are tests in https://github.com/grafana/grafana/pull/5720, do they cover all cases?

the current Time series field config looks like below. the Min/Max under "Standard options" are the hard limits (clamps). adding `Axis > SoftMin` and `Axis > SoftMax` into the "Time series options" could be workable and would allow simultaneous hard and soft limits.

![image](https://user-images.githubusercontent.com/43234/104411774-a631ba00-5530-11eb-9dc1-fec28f3864b9.png)

**Comment by acortelyou** [comment]
> The "softness" or "hardness" of the min and max should be independently controllable.

Yes, this is what I was trying to say.

> It's very useful to clamp both max and min combined with soft max and softmin. Specifically to hide noise. If you get some impulse In the data that competly hides the real data until the impulse is gone from the data.

+1

> Please please don't fall into the trap of trying to make this too simple. For true data trending you need both soft limits and clamping!

+1

**Comment by thoj** [comment]
@leeoniya maybe not the exact same data but I can dump out something similar. Csv OK?

**Comment by leeoniya** [comment]
yep, csv is fine. as long as it's easy to correlate the hard & soft min/max settings you want associated with each dataset to remove some guesswork.

**Comment by thoj** [comment]
Hi

One thing before you look at the data. In my case 4 years ago I wanted the min/max and softmin/softmax to follow the **latest value**, **not all the values**. This was to avoid "Steps" in the data getting hidden away. Where the average value over some time might be 4.5 and you want to have to softmin at +/- 0.5 and max at +/- 1.0 of the latest value. This is to show relevant changes (+/- 0.5) in the 3.5-5.5 rage and hide big impulses. But the average might suddenly change to 3.5 and then you want soft min to still be +/- 0.5 but you want to change the range to 2.5-4.5. I hope i made myself understood. 

Said in another way. I want Max/Min to be +/- 1v relative to the latest value. This might be a too special case. 

I have to find some better data later but here is one that should be an example of what i described above, with step and impulse:

So the goal is to show changes without destroying resolution because of impulse noise and not make tiny (+/- 0.05) changes become huge: 

Impuse_and_step.csv:
[Impulse_and_step.txt](https://github.com/grafana/grafana/files/5815338/Impulse_and_step.txt)

**Comment by leeoniya** [comment]
thanks, we'll take a look.

> Said in another way. I want Max/Min to be +/- 1v relative to the latest value. This might be a too special case.

yes, this is definitely too niche for general inclusion, at least for now while all options are in a flat "show everything" layout -- even moving forward with 2 instead of 1 additional field needs a very strong case (i do think there is one here). for "latest value" mode, the compromise would be to make sure the hard limit is not way larger than the soft limit, so you can still get an acceptable level of resolution even if you have historical spikes still within the view.

another side-effect of setting soft limits, that hopefully everyone is aware of, is that it will limit the ability to "zoom" vertically to increase the vertical resolution beyond the configured soft limits.

another question i have, relates to the extra "padding" normally added to the min & max, so ensure the y scale range is not _exactly_ matched to the data range. uPlot's soft ranging function fill try to keep this buffer in place for soft limits. example case:

data max: 8
padded scale max: 10
soft limit: 10
hard limit 15

once data max goes > 8 (and the padding is still max + 2), then the scale range will begin to grow past the soft limit, since the _padded_ max is greater. this is desirable in most cases, i think because it allows potentially some extra headroom even in the soft limit case. however, i can see people wanting the data max to literally hit the soft limit, but then the issue is that it would "snap" from 10 -> 12.1 (with the padding) once data max hits 10.1.

i'll have to do a few variants and see which feels better, i think i prefer the smoother transition instead of letting the data max touch the soft limit (and squashing the padding to 0) before expanding the rang and re-adding the padding in an instant.

**Comment by leeoniya** [comment]
@thoj 

let's start with what your dataset looks like.

![image](https://user-images.githubusercontent.com/43234/104790576-318f9300-575d-11eb-878e-a8f33bc53e0f.png)

the implementation we're going to do will be a static `softMin` and a static `softMax`, in addition to the existing hard `min` and hard `max`. this would allow you to stabilize this graph by setting soft limits of `2.5, 5.5` and maybe hard limits at `1.5, 6.0`. i think this is the 99% use-case and resolves the primary problem as stated in the first comment: to avoid showing "tiny blips as large mountains" when the data is mostly flat. the hard limits solve the opposite problem of large blips flattening what should be larger mountains.

i'll elaborate a bit why imo your dynamic soft limits are problematic. in short, this method removes a level of expected stability in the axis range.

your ~3.5 plateau might look like this

```
4-
 - ~v~^~v~~~~
3-
```

and then shortly afterwards your ~4.7 plateau might look like this:

```
5-
 - ~^~~~v~^~~
4-
```

the only discernible difference would be the min/max axis ticks, it would be extremely easy to miss such a tiny distinction for a whopping jump of 1.2 while usually staring at blips of 0.01.

with static soft limits, you would at least see an upwards shift in blip baseline after the transition. additionally, i cannot understand when someone would be interested in the micro detail of the plateaus when legitimate jumps are several orders of magnitude larger -- it's like saying you want to see changes of a cent, while also expecting changes of $10 dollars.

**Comment by leeoniya** [comment]
alright, here we go..

top panels are the default ranging behavior. the wide version is the full dataset, and each smaller panel is different interesting subset of the same data.

the bottom copies of the same panels all have the following limits: `Hard: 1.5 - 6.0, Soft: 2.5 - 5.0`:

![soft-limits](https://user-images.githubusercontent.com/43234/104795069-44ac5e00-5771-11eb-9e74-29ff50345adf.png)

**Comment by thoj** [comment]
@leeoniya first of all this looks really good! It's exactly what I was looking for. And I see where you are coming from. Its difficult for outsiders to understand why this is needed. 

About the data. This data was probably too clean. I didn't have time to find a better example. I'll try to find the time to find a better example. 

Just to explain what is happening here. This is a voltage signal. The impulse noise is either a power disconnect or operator action (a lot of different things, electrode cleaning etc. ). What you want to look for in this data is "fast" changes +/- 0.2v this may indicate a intermittent short circuit that is really bad for this process.

**Comment by abursavich** [comment]
I'm confused about what we ended up with here... I just want to be able to say "auto min but don't go below this value" and/or "auto max but don't go above this value" (see my original issue https://github.com/grafana/grafana/issues/26597).

**Comment by leeoniya** [comment]
you should be able to get this behavior by setting the soft limits to the inverted hard limits:

```
hard: 30,  50
soft:  50, 30
```

**Comment by abursavich** [comment]
What if you want an auto max and "auto min but don't go below this value"?

**Comment by leeoniya** [comment]
you would leave the hardMax empty.

**Comment by bslade** [comment]
> Thanks, interesting idea. Seems a little edge case. But I agree, could be useful at times.

This is not at all an edge case.  Most performance monitoring dashboards (looking at a set of servers for example) need to be able to look at long term trends, but ignore spurious spikes in values (eg. cause by reboots or one time hiccups).   For my dashboard with 14 servers, the only way to do this is to hand edit each of the 14 graphs to manually set the Y-Max value (variables don't work in that field)

So for now, I have to create a whole second dashboard (with Y-Max set low in each graph) for the purpose of viewing long term trends.  Ugly.

**Comment by leeoniya** [comment]
> So for now,...

what does this mean? we implemented this requested feature almost two years ago. the new options are called softMin and softMax.

**Comment by leeoniya** [comment]
> If you set the hardMax you loose the auto-scaling functionality.

this had always been the case in grafana before we added soft limits, so we didnt want to break compat with existing panels.

> Thus alongside to softMax a new hardMax would allow you to cut off spikes maintaining auto-scaling whenever values do not reach the hardMax or hardMin boundary.

you can still get autoscaling up to the hard limit by setting hardMax: 100 and softMax: - 10000, though it's not _exactly_ the same (you might lose the top scale padding above the max data value)

**Comment by mokrafoka** [comment]
> you can still get autoscaling up to the hard limit by setting hardMax: 100 and softMax: -10000, though it's not _exactly_ the same (you might lose the top scale padding above the max data value)

Oh, that works. THX!
