### ISSUE TITLE
Decimals option show more digits than needed

### ISSUE THREAD

**Issue by LordMike** [grafana/grafana#9848]
Please include this information:
- What Grafana version are you using?
Grafana v4.6.1 (commit: cac8b97)

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Ubuntu 16.04

- What did you do?
Created a graph tallying up numbers. I played around with the options, and found an error in the decimal places option for the legends. 

It seems that when you chose one decimal place, it actually shows two decimals for some numbers, when they're formatted with the "short" unit.

- What was the expected result?
That 0 decimals will show 0 decimals, 1 decimal will show one etc., across all values.

- What happened instead?

Observe in the picture below that 2 decimal places rendered 2 decimals for all the collapsed numbers (the thousands), but 3 decimals for the singular number.

![image](https://user-images.githubusercontent.com/1027111/32653080-d8ad02d0-c606-11e7-8803-75c316b6b005.png)

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
That decimal option is for the Left Y axis. The Tooltip is using the legend decimals option:
![image](https://user-images.githubusercontent.com/10999/32719608-41380b9a-c861-11e7-958a-9a355a723173.png)

Why two options? Well Y-axis is usually left set to automatic because Grafana can determine optimal use of decimals (usually), but the legend and tooltip might require more and is not as easy to automatically determine the optimal range for.

**Comment by LordMike** [comment]
Ah. Thanks :)

Purely perfecentional: Shouldn't the 200K in the topleft of the image be "200.00 K", then?
