### ISSUE TITLE
Grafana logs says "Database table locked, sleeping then retrying" logger=sqlstore retry=0.

### ISSUE THREAD

**Issue by Abhishek321singh** [grafana/grafana#9870]
Hi,

I am new to grafana, using it for some POC but ran into the issue.
Log says:--

t=2017-11-13T14:51:06+0000 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
t=2017-11-13T14:56:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0

- What Grafana version are you using?
Grafana v4.6.1
- What datasource are you using?
influxdb
- What OS are you running grafana on?
Linux a198-18-52-100 3.13.0-107-generic #154-Ubuntu SMP Tue Dec 20 09:57:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- What did you do?
installed influxdb and grafana was populating some data in DB and trying to see in grafana. For some reason data was not coming checked /var/log/grafana/grafana.log saw the error "Grafana logs says "Database table locked, sleeping then retrying" logger=sqlstore retry=0."
- What was the expected result?
wanted to see the request and status code for that request
- What happened instead?
Saw error "Grafana logs says "Database table locked, sleeping then retrying" logger=sqlstore retry=0."

Thanks in Advance for the help

**Comment by bedrin** [comment]
"Database table locked, sleeping then retrying" is not an error

**Comment by Abhishek321singh** [comment]
okay @bedrin ... How to get out of it? I don't see any query request coming from Grafana :(

**Comment by svenklemm** [comment]
This looks alot like #7992. Are you using sqlite as grafana database? Try migrating to postgresql or mysql?

**Comment by torkelo** [comment]
What are you running grafana-server on? VM? what is the disk? network disk? What kind of load are you putting grafana under (req/s), what api calls are made?

**Comment by Abhishek321singh** [comment]
@svenklemm  i am using influxdb

**Comment by Abhishek321singh** [comment]
@torkelo Every 5 secs i was pushing some data to influxDB, just to see some graphs on grafana .. as i installed grafana and influxdb couple of hours back

 while true; do curl -i -XPOST 'http://localhost:8086/write?db=statsdemo' --data-binary "cpu,host=serverA value=`cat /proc/loadavg | cut -f1 -d' '`"; sleep 5; done

It is not on VM. it's hardware

**Comment by Abhishek321singh** [comment]
@torkelo Actually i want to use telegraf which can send metrics to the influx DB and that can be shown on grafana.

So, i started with display part with grafana and wanted to ensure with some POC kind of thing that it shows some graphs from the data points from the influx DB but ran into this issue even before seeing as single data point on the garafana

**Comment by torkelo** [comment]
closing this, can't see any error with the database locked, it's retrying successfully. 

This warning message is completely unrelated to your issue writing/querying data from InfluxDB

**Comment by sslupsky** [comment]
Hi,

A couple days ago I started to see these messages appear in the log of a new installation of Grafana (installation was about 6 days old ... created first panel Nov 10 I think, error message in the log began Nov 14).  It's not obvious to me what I was doing at the time to "trigger" the log messages.  Since they started they do not stop.  The version is 4.5.2.  Using default database (sqlite).  I stopped Grafana, rebooted the machine and restarted but the messages continue to appear in the log.

Here is a snippet from the log:

t=2017-11-16T07:05:13-0700 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2017-11-16T07:11:13-0700 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2017-11-16T07:11:13-0700 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2017-11-16T07:33:29-0700 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2017-11-16T07:33:29-0700 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2017-11-16T07:33:29-0700 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2017-11-16T07:33:29-0700 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2017-11-16T07:33:29-0700 lvl=eror msg="Failed to get user with id" logger=context userId=2 error="User not found"
t=2017-11-16T07:33:29-0700 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/datasources/proxy/2/query status=401 remote_addr=192.168.125.40 time_ms=4 size=26 referer="http://192.168.125.108/dashboard/db/test-dashboard?refresh=1m&orgId=1&from=now-90m&to=now"
t=2017-11-16T07:33:29-0700 lvl=info msg="Request Completed" logger=context userId=2 orgId=1 uname=name@company.com method=GET path=/api/login/ping status=401 remote_addr=192.168.125.40 time_ms=1 size=26 referer="http://192.168.125.108/dashboard/db/test-dashboard?refresh=1m&orgId=1&from=now-90m&to=now"

**Comment by sslupsky** [comment]
I should note I am using influx as the datasource.  The influx queries appear to work fine.  The dashboard is rendered.  Only thing that triggered me to go look at the logs was the size of the log ... obviously something was piling up.  I have not found what this is affecting (i.e.: which database table is locked) so I do not know if this actually affects the use of Grafana in some way.

**Comment by svenklemm** [comment]
The locks are referring to sqlite which grafana uses to store meta data (users,dashboards,...) unless you configured it to use mysql or postgres.

**Comment by sslupsky** [comment]
I found the "event" that triggered the messages.  Grafana was shut down and restarted.  Shortly after the restart, they began to appear.  Here is the log snip:

t=2017-11-14T08:16:46-0700 lvl=info msg="Shutdown started" logger=server code=0 reason="system signal: terminated"
t=2017-11-14T08:16:46-0700 lvl=info msg="stopped http server" logger=http.server
t=2017-11-14T08:21:21-0700 lvl=info msg="Starting Grafana" logger=server version=4.5.2 commit=unknown-dev compiled=2017-09-27T08:12:11-0600
t=2017-11-14T08:21:21-0700 lvl=info msg="Config loaded from" logger=settings file=/usr/local/opt/grafana/share/grafana/conf/defaults.ini
t=2017-11-14T08:21:21-0700 lvl=info msg="Config loaded from" logger=settings file=/usr/local/etc/grafana/grafana.ini
t=2017-11-14T08:21:21-0700 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/usr/local/var/lib/grafana"
t=2017-11-14T08:21:21-0700 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/usr/local/var/log/grafana"
t=2017-11-14T08:21:21-0700 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/usr/local/var/lib/grafana/plugins"
t=2017-11-14T08:21:21-0700 lvl=info msg="Path Home" logger=settings path=/usr/local/opt/grafana/share/grafana
t=2017-11-14T08:21:21-0700 lvl=info msg="Path Data" logger=settings path=/usr/local/var/lib/grafana
t=2017-11-14T08:21:21-0700 lvl=info msg="Path Logs" logger=settings path=/usr/local/var/log/grafana
t=2017-11-14T08:21:21-0700 lvl=info msg="Path Plugins" logger=settings path=/usr/local/var/lib/grafana/plugins
t=2017-11-14T08:21:21-0700 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2017-11-14T08:21:21-0700 lvl=info msg="Starting DB migration" logger=migrator
t=2017-11-14T08:21:21-0700 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2017-11-14T08:21:21-0700 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2017-11-14T08:21:21-0700 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2017-11-14T08:21:21-0700 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2017-11-14T08:21:21-0700 lvl=info msg="Starting plugin search" logger=plugins
t=2017-11-14T08:21:21-0700 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2017-11-14T08:21:21-0700 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2017-11-14T08:21:21-0700 lvl=info msg="Initializing Stream Manager"
t=2017-11-14T08:21:21-0700 lvl=info msg="Initializing HTTP Server" logger=http.server address=192.168.125.108:80 protocol=http subUrl= socket=
t=2017-11-14T08:47:14-0700 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=192.168.125.40 time_ms=6 size=29 referer=
t=2017-11-14T08:57:58-0700 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2017-11-14T08:57:58-0700 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2017-11-14T08:57:58-0700 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t

**Comment by svenklemm** [comment]
There were a couple tickets about problems with sqlite recently and i had problems with sqlite too. After migrating to postgres as grafana database all those went away.

**Comment by sslupsky** [comment]
Thanks for the feedback.  Change the database ... is there an easy way to migrate the existing sqlite db to mysql or postgres?  Or, just start over?

**Comment by svenklemm** [comment]
There is nothing on the grafana side to support you with this task. I would suggest letting grafana create the initial schema so you get the datatypes right for your database. But after that you can just dump your sqlite database as sql statements and then run those inserts in your new database.
