### ISSUE TITLE
Sass compiler is needed, yet doesn't install

### ISSUE THREAD

**Issue by Vaelatern** [grafana/grafana#9872]
In a Linux environment where `npm install node-sass` works without incident, and sucessfully installs node-sass@4.6.1, gyp fails to build because it tries to build `libsass`. `libsass` is already installed. https://gist.github.com/anonymous/cd37a1e9d847967c5b459055775dbc44 but `libsass` is already present in this environment.

This is in a truly minimalistic environment otherwise.

One solution would be to make the `npm` install work better elsewhere, but that takes a lot of developer work.

The node modules are not necessary in a production environment, and even the standalone Linux binaries only ship with javascript assets. An alternative to improving the frontend build would just be to ship a tarball with frontend assets, or perhaps check in frontend assets to the repository.
I do not want to see `node_modules` in the repo any more than anybody else. I do not propose this. I propose using those node modules in a known working environment to provide a frontend for people trying to expand grafana's userbase.

**Comment by torkelo** [comment]
Strange, we have no other reports of failing to run npm install due to node-sass. Something strange with your setup? 

> The node modules are not necessary in a production environment,

True, they are not shipped in release packages. 

> An alternative to improving the frontend build would just be to ship a tarball with frontend assets, or perhaps check in frontend assets to the repository.

This sounds like a very bad idea. The compiled frontend changes with every change and big megabyte sized js files would have to checked in every commit that changes the frontend (the frontend is built and packages into a few big js files that contain the code and html). Sorry, adding this to the repo is not an option.

If you want to work on the backend without having to build the frontend you can download the latest build https://grafana.com/grafana/download and copy the public/build dir from that tar ball. Not ideal for you I know, but your situation i not being able to install https://github.com/sass/node-sass seems very unique (at least right now). Will re-open if others report similar behavior and your issue with node-sass is not isolated.
