### ISSUE TITLE
grafana datasource mysql 

### ISSUE THREAD

**Issue by hualidi123** [grafana/grafana#9898]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
example:
SELECT
  UNIX_TIMESTAMP(createTime) as time_sec,
  count(userId) as value,
  'User frequency' as metric
FROM operateLog
where $__timeFilter(createTime) and userId !=1
GROUP BY UNIX_TIMESTAMP(createTime) DIV 2592000
ORDER BY time_sec asc

how can i make curve display of Graph base on time/months? 
 i don't know the point of time shown is determined by what
i want  the point of time determines by months,how much frequency every month is

**Comment by daniellee** [comment]
In the next major version of Grafana (probably 4.7), the `$__timeGroup` macro will be available for this use case (see this PR #9596). In the meantime, you can do something similar yourself:

```sql
SELECT 
  cast(cast(UNIX_TIMESTAMP(atimestamp)/(300) as signed)*300 as signed) as time_sec,
  count(afloat) as value, 
  avarchar as metric 
FROM testdata.mysql_types 
GROUP BY 1, avarchar 
ORDER BY 1
```

**Comment by hualidi123** [comment]
thanks too much ! it works! i want know where i can study grammar of grafana from mysql datasource.

**Comment by daniellee** [comment]
There is a “Show Help” button in the Query Editor and there are docs too - http://docs.grafana.org/features/datasources/mysql/

**Comment by hualidi123** [comment]
i know this ,i want like this "$__timeGroup" Macro variables. Simply put, i want know mysql SQL grammar of grafana different of mysql ,are there some  documents about my need ?thanks

**Comment by daniellee** [comment]
@hualidi123 not sure exactly what you are asking. Are you asking if there is documentation about the sql output for the macros? Or if there is different sql outputs for different versions of mysql?

The help section shows the generated sql. Otherwise there is no special docs for it (except for the [macro tests](https://github.com/grafana/grafana/blob/master/pkg/tsdb/mysql/macros_test.go) in the code).

**Comment by umangsmcx** [comment]
How can we add more than one column as metric like column2 with USer Frequency
SELECT
UNIX_TIMESTAMP(createTime) as time_sec,
count(userId) as value,
'User frequency', 'cloumn2' as metric
FROM operateLog
where $__timeFilter(createTime) and userId !=1
GROUP BY UNIX_TIMESTAMP(createTime) DIV 2592000
ORDER BY time_sec asc

**Comment by marefr** [comment]
@umangsmcx Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Since you're grouping by time you'll need to use an aggregate function like count, sum, avg etc for your user frequency column. If you can't use an aggregate function for that you'll probable need to group by this column as well. Basically you can skip returning a column aliased as metric and do for example `count(<your other column>) as value2` - value2 will be the name of your series. Please refer to [documentation](http://docs.grafana.org/features/datasources/mysql/#time-series-queries) for further information.

**Comment by umangsmcx** [comment]
Thanks for the help, Actly that was the sample query. I dont have groupby as of now. 
All I am trying to do is lets say I have a table users in mysql cloumns as user_name, user_organization and registration date. Now I want to create a graph for specific month lets say 1st quarter. with Employee user_name, user_organization and the count of total registration companywise. How would I query so as my legends table will have company name, total users and registration count

**Comment by umangsmcx** [comment]
Thanks, I didn't wanted you to write query as query I have already written, Just wanted to know about the provision if available on grafana for multiple metrics, But as you mentioned there isnt any. I would try on community site if I get anything. 

Thanks & Regards
