### ISSUE TITLE
Facing issues while installing grfana!

### ISSUE THREAD

**Issue by iamsivacheerla** [grafana/grafana#9970]
![screenshot from 2017-11-23 08-58-50](https://user-images.githubusercontent.com/9480389/33158057-b361d50c-d02c-11e7-960b-d4aa8124d0ad.png)

**Comment by torkelo** [comment]
you seem to be trying to build grafana from source (not installing it). If you want to install we recommend downloading a debian package or using the APT repo: 
http://docs.grafana.org/installation/debian/

If you want to build from source follow this guide (think the error your getting is due to too old version of go)
http://docs.grafana.org/project/building_from_source/#building-grafana-from-source
