### ISSUE TITLE
unable to increase/change the alert execution timeout

### ISSUE THREAD

**Issue by swdream** [grafana/grafana#9971]
we are using 
- grafana 4.6.0
- influxdb 1.4.1

setting up alerting for metrics, I configured *"If execution error or timeout"* to *"Alerting"* . And in ``state history``, we often get this
```
ALERTING
Error: Alert execution exceeded the timeout
```
it means the alert rule execution took a long time, more than the default timeout (30 seconds). 
but seems that there is no way to increase this default timeout for alert execution.
http://docs.grafana.org/alerting/rules/#execution-errors-or-timeouts

note: set "If execution error or timeout" to "Keep last" will ignore this error only, not solve this problem.

**Comment by bergquist** [comment]
Why is the response so slow? Do you really need to such complex queries for alerting?

**Comment by quantonganh** [comment]
@bergquist Is this a complex query?

```
SELECT mean(load1) as short,mean(load5) as medium,mean(load15) as long FROM "system" WHERE host = 'telegraf'
```

and the alert condition is:

``
When avg() of query(B, 5m, now) IS ABOVE 5
```

Anyway, I just changed it to just alert on `load15`.

**Comment by bergquist** [comment]
@quantonganh no :) That query should be able to execute within a second. Perhaps influxdb is slow due to many series?

**Comment by swdream** [comment]
> I think alert queries should be simple and fast. So 30s should be enough for most use cases. that's why Im curious :)
@bergquist ok. thanks a lot. I will review my queries again :)
anyway, one more question: this timeout is unable to change. so, what is the reason? isn't it better if we can change that timeout value? I think it can help in some cases :)

**Comment by bergquist** [comment]
Making everything configurable usually turns things into a mess. If someone have a good use case for it I will make it configurable and make a patch release. Until then I really want to avoid making everything configurable. 

I think this image sums it up 
![image](https://user-images.githubusercontent.com/618863/33200650-cdf63092-d0f5-11e7-85ed-7f5a0a984fe5.png)

In this case, the config is the user experience :)

**Comment by rhefner1** [comment]
@bergquist My use case is in a Kubernetes environment where I sometimes update the InfluxDB configuration and have to restart the server, which takes 1-2 mins. Once it comes back up, my alerts channel on Slack is flooded with [OK] messages (since it was alerting because of the execution timeout). I like the alerting on timeout feature, but I would rather make it 3-4 minutes instead of what it currently is (maybe 60 seconds?).

If there is a better way to do this, please let me know!

**Comment by ChappIO** [comment]
Here's another use-case. We use external services such as WorldPing. Some of those databases take a long time to process the queries. This causes the execution to fail due to timeouts.

**Comment by yangyu66** [comment]
so why expose this config is not work @bergquist ?

**Comment by AndreKR** [comment]
I'm also running into timeouts with my alert queries, especially while my InfluxDB machine is running backups.

I do have fairly heavy queries: I'm querying the last report time per host within the last 4 weeks.

Why 4 weeks? Because I use multi-dimensional alerting and if a host simply goes away it's not considered a reason for alert. So instead I query the last report time. This gives me 4 weeks to solve the issue before the host disappears from the time window and with it the alert.

I have opened https://github.com/grafana/grafana/issues/76920 for a better solution but unless that gets implemented I don't know any better way.

So 👍 for making the timeout configurable.
