### ISSUE TITLE
Urgent help: Do we have Oracle datasource plugin available to query Oracle DB from Grafana?

### ISSUE THREAD

**Issue by Lisahegde** [grafana/grafana#9972]
Hi All,

I am new to Grafana and it is an amazing tool. I have an requirement to connect Oracle Database from Grafana. Do we have ready made plugin available? If yes, can you please point out me to the url?
Grafana Version installed: 4.4.3

I am looking for urgent help.

Thanks,

**Comment by bergquist** [comment]
Hi @Lisahegde 

We currently don't support Oracle as an data source. But we are investigating the possibility to support Oracle as a premium plugin. Could you send me an email at carl@grafana.com so I can give you more detail?

Closing this since its a question and we prefer to keep issues about bugs and feature requests.

**Comment by Lisahegde** [comment]
Thanks a lot Carl for the update!!
